#!/bin/bash

git clone https://github.com/ablab/quast '/storage/nvme5/new_clones/AMPL/quast' &
git clone https://github.com/Chadderz121/wii-ct-code '/storage/nvme5/new_clones/AMPL/wii-ct-code' &
git clone https://github.com/cellularmitosis/LTSpice-parts '/storage/nvme5/new_clones/AMPL/LTSpice-parts' &
git clone https://github.com/wmutschl/mutschler.eu '/storage/nvme5/new_clones/AMPL/mutschler.eu' &
git clone https://github.com/Orient-Empires-Project/Orient_Empires_and_sub_MOD '/storage/nvme5/new_clones/AMPL/Orient_Empires_and_sub_MOD' &
git clone https://github.com/giant-axon/lu.i-neuron-pcb '/storage/nvme5/new_clones/AMPL/lu.i-neuron-pcb' &
git clone https://github.com/peopleplusrobots/robo-op '/storage/nvme5/new_clones/AMPL/robo-op' &
git clone https://github.com/singpolyma/shttpd '/storage/nvme5/new_clones/AMPL/shttpd' &
git clone https://github.com/ernell/ABB-RAPID-UTILITY-LIBRARY '/storage/nvme5/new_clones/AMPL/ABB-RAPID-UTILITY-LIBRARY' &
git clone https://github.com/ZhangHongBo2019/CPLEX '/storage/nvme5/new_clones/AMPL/CPLEX' &
git clone https://github.com/raziele/Nigun '/storage/nvme5/new_clones/AMPL/Nigun' &
git clone https://github.com/materialsvirtuallab/snap '/storage/nvme5/new_clones/AMPL/snap' &
git clone https://github.com/libai1943/Tractor-trailer-trajectory-planning-case-studies-ICRA-19 '/storage/nvme5/new_clones/AMPL/Tractor-trailer-trajectory-planning-case-studies-ICRA-19' &
git clone https://github.com/ros-industrial/abb_driver '/storage/nvme5/new_clones/AMPL/abb_driver' &
git clone https://github.com/afurculita/cplex-vrptw-implementation '/storage/nvme5/new_clones/AMPL/cplex-vrptw-implementation' &
git clone https://github.com/rparak/ABB-RobotStudio-Tutorial-Simple '/storage/nvme5/new_clones/AMPL/ABB-RobotStudio-Tutorial-Simple' &
git clone https://github.com/savenlid/kicad '/storage/nvme5/new_clones/AMPL/kicad' &
git clone https://github.com/NaokiAkai/AutoNavi '/storage/nvme5/new_clones/AMPL/AutoNavi' &
git clone https://github.com/mlubin/JuMPSupplement '/storage/nvme5/new_clones/AMPL/JuMPSupplement' &
git clone https://github.com/a-chol/farewell_pcb '/storage/nvme5/new_clones/AMPL/farewell_pcb' &
git clone https://github.com/skullbe/Kaiserreich-Korean-Translation '/storage/nvme5/new_clones/AMPL/Kaiserreich-Korean-Translation' &
git clone https://github.com/cybrxkhan/RICE-for-CK3 '/storage/nvme5/new_clones/AMPL/RICE-for-CK3' &
git clone https://github.com/irena-flextool/flextool '/storage/nvme5/new_clones/AMPL/flextool' &
git clone https://github.com/Niukron/Crusader-Kings-3-Spolszczenie '/storage/nvme5/new_clones/AMPL/Crusader-Kings-3-Spolszczenie' &
git clone https://github.com/cybrxkhan/VIET-Events-for-CK3 '/storage/nvme5/new_clones/AMPL/VIET-Events-for-CK3' &
git clone https://github.com/gatech-genemark/GeneMark-ETP '/storage/nvme5/new_clones/AMPL/GeneMark-ETP' &
git clone https://github.com/visionspacetec/VST104 '/storage/nvme5/new_clones/AMPL/VST104' &
git clone https://github.com/FriedrichvonEbert/KaiserreichKoreanTranslation '/storage/nvme5/new_clones/AMPL/KaiserreichKoreanTranslation' &
git clone https://github.com/zanellia/feasible_sqp '/storage/nvme5/new_clones/AMPL/feasible_sqp' &
git clone https://github.com/gatech-genemark/MetaGeneMark-2 '/storage/nvme5/new_clones/AMPL/MetaGeneMark-2' &
git clone https://github.com/MetaCell/NEURON-UI '/storage/nvme5/new_clones/AMPL/NEURON-UI' &
git clone https://github.com/nasa/WinSURE '/storage/nvme5/new_clones/AMPL/WinSURE' &
git clone https://github.com/matijapretnar/proofs '/storage/nvme5/new_clones/AMPL/proofs' &
git clone https://github.com/ElTyranos/CommunityFlavorPack '/storage/nvme5/new_clones/AMPL/CommunityFlavorPack' &
git clone https://github.com/v-community/repo_template '/storage/nvme5/new_clones/AMPL/repo_template' &
git clone https://github.com/Ariphaos/StellarisUnofficialPatch '/storage/nvme5/new_clones/AMPL/StellarisUnofficialPatch' &
git clone https://github.com/alltheatreides/AVE_MARIA_CK3 '/storage/nvme5/new_clones/AMPL/AVE_MARIA_CK3' &
git clone https://github.com/TechnoX/ABB-YUMI-LIB '/storage/nvme5/new_clones/AMPL/ABB-YUMI-LIB' &
git clone https://github.com/cocolinfff/Ethics-Civics-Infinity-new '/storage/nvme5/new_clones/AMPL/Ethics-Civics-Infinity-new' &
git clone https://github.com/ampl/global-optimization '/storage/nvme5/new_clones/AMPL/global-optimization' &
git clone https://github.com/gmarciani/amplitude '/storage/nvme5/new_clones/AMPL/amplitude' &
git clone https://github.com/JustasB/hoc2swc '/storage/nvme5/new_clones/AMPL/hoc2swc' &
git clone https://github.com/jmanzolli/E-VRPTW '/storage/nvme5/new_clones/AMPL/E-VRPTW' &
git clone https://github.com/tum-ens/mathprog-energy-models '/storage/nvme5/new_clones/AMPL/mathprog-energy-models' &
git clone https://github.com/renatosvmor/MDLText '/storage/nvme5/new_clones/AMPL/MDLText' &
git clone https://github.com/Vasolik/CK3ACS '/storage/nvme5/new_clones/AMPL/CK3ACS' &
git clone https://github.com/fatih/testmod '/storage/nvme5/new_clones/AMPL/testmod' &
git clone https://github.com/NoisyLeon/CPSPy '/storage/nvme5/new_clones/AMPL/CPSPy' &
git clone https://github.com/tardis-sn/stardis '/storage/nvme5/new_clones/AMPL/stardis' &
git clone https://github.com/Ivysaur-Mrquestionmarks/epstein2020 '/storage/nvme5/new_clones/AMPL/epstein2020' &
git clone https://github.com/ronkeizer/nonmem_examples '/storage/nvme5/new_clones/AMPL/nonmem_examples' &
git clone https://github.com/davidebasile/RoutingProblem '/storage/nvme5/new_clones/AMPL/RoutingProblem' &
git clone https://github.com/Jeff09/Word-Sense-Disambiguation-using-Bidirectional-LSTM '/storage/nvme5/new_clones/AMPL/Word-Sense-Disambiguation-using-Bidirectional-LSTM' &
git clone https://github.com/hirothreading/dynare_files '/storage/nvme5/new_clones/AMPL/dynare_files' &
git clone https://github.com/LuxArdens/Stellaris---RPG-Traits-mod '/storage/nvme5/new_clones/AMPL/Stellaris---RPG-Traits-mod' &
git clone https://github.com/bristolroboticslab/OpenABB-FDM '/storage/nvme5/new_clones/AMPL/OpenABB-FDM' &
git clone https://github.com/nasa/WinASSIST '/storage/nvme5/new_clones/AMPL/WinASSIST' &
git clone https://github.com/jeromematthewcelestine/smetswouters2007 '/storage/nvme5/new_clones/AMPL/smetswouters2007' &
git clone https://github.com/mpf/Optimization-Test-Problems '/storage/nvme5/new_clones/AMPL/Optimization-Test-Problems' &
git clone https://github.com/sheo0147/CEoR '/storage/nvme5/new_clones/AMPL/CEoR' &
git clone https://github.com/SFUSatClub/obc-hardware '/storage/nvme5/new_clones/AMPL/obc-hardware' &
git clone https://github.com/The-Grand-Combination/The-Grand-Orchestra '/storage/nvme5/new_clones/AMPL/The-Grand-Orchestra' &
git clone https://github.com/ParadigmHyperloop/electrical '/storage/nvme5/new_clones/AMPL/electrical' &
git clone https://github.com/willroberts/raven-shield-2020 '/storage/nvme5/new_clones/AMPL/raven-shield-2020' &
git clone https://github.com/dpastoor/ddmore_scraping '/storage/nvme5/new_clones/AMPL/ddmore_scraping' &
git clone https://github.com/compneuro/LFPsim '/storage/nvme5/new_clones/AMPL/LFPsim' &
git clone https://github.com/cm1518/practicing_dynare '/storage/nvme5/new_clones/AMPL/practicing_dynare' &
git clone https://github.com/rparak/ABB-RobotStudio-SortingProductionLine '/storage/nvme5/new_clones/AMPL/ABB-RobotStudio-SortingProductionLine' &
git clone https://github.com/SteveMacenski/ABB-IRB120-MultiRobot-Downloader '/storage/nvme5/new_clones/AMPL/ABB-IRB120-MultiRobot-Downloader' &
git clone https://github.com/FallenSkyscraper/Fallen-Skyscraper-CK3 '/storage/nvme5/new_clones/AMPL/Fallen-Skyscraper-CK3' &
git clone https://github.com/carlosgeos/free-money '/storage/nvme5/new_clones/AMPL/free-money' &
git clone https://github.com/paige404/CK3_Immortality '/storage/nvme5/new_clones/AMPL/CK3_Immortality' &
git clone https://github.com/EngVargas/tutorial_LTspice '/storage/nvme5/new_clones/AMPL/tutorial_LTspice' &
git clone https://github.com/RiVer2000/Machine-Tending '/storage/nvme5/new_clones/AMPL/Machine-Tending' &
git clone https://github.com/fcbarbi/dsge '/storage/nvme5/new_clones/AMPL/dsge' &
git clone https://github.com/pongmadee/Stellaris-Thai-Translation-MOD '/storage/nvme5/new_clones/AMPL/Stellaris-Thai-Translation-MOD' &
git clone https://github.com/AlderonTyran/Victoria3Mods '/storage/nvme5/new_clones/AMPL/Victoria3Mods' &
git clone https://github.com/mcubelab/abb_robotnode '/storage/nvme5/new_clones/AMPL/abb_robotnode' &
git clone https://github.com/OldEnt/stellaris-starnet-ai '/storage/nvme5/new_clones/AMPL/stellaris-starnet-ai' &
git clone https://github.com/UCDenver-ccp/ccp-nlp-pipelines '/storage/nvme5/new_clones/AMPL/ccp-nlp-pipelines' &
git clone https://github.com/silascript/HOI4CHIntegration '/storage/nvme5/new_clones/AMPL/HOI4CHIntegration' &
git clone https://github.com/UberEpicZach/FlavourEventsExpanded '/storage/nvme5/new_clones/AMPL/FlavourEventsExpanded' &
git clone https://github.com/cybrxkhan/VIET-Events-Reborn '/storage/nvme5/new_clones/AMPL/VIET-Events-Reborn' &
git clone https://github.com/NeoResearch/milp_bft_failures_attacks '/storage/nvme5/new_clones/AMPL/milp_bft_failures_attacks' &
git clone https://github.com/AlexFleischerParis/howtowithopl '/storage/nvme5/new_clones/AMPL/howtowithopl' &
git clone https://github.com/IMFS-MMB/mmb-gui-electron '/storage/nvme5/new_clones/AMPL/mmb-gui-electron' &
git clone https://github.com/LaTueur/CK2-Community-Patch '/storage/nvme5/new_clones/AMPL/CK2-Community-Patch' &
git clone https://github.com/by-student-2017/lammps_MoS_REBO '/storage/nvme5/new_clones/AMPL/lammps_MoS_REBO' &
git clone https://github.com/AlexFleischerParis/ponderthis '/storage/nvme5/new_clones/AMPL/ponderthis' &
git clone https://github.com/shuaiwang88/optimization_modeling_class_using_R_Pyomo '/storage/nvme5/new_clones/AMPL/optimization_modeling_class_using_R_Pyomo' &
git clone https://github.com/michaeldong1/ZOONOMIA '/storage/nvme5/new_clones/AMPL/ZOONOMIA' &
git clone https://github.com/DrMaple/ui_overhaul_1080 '/storage/nvme5/new_clones/AMPL/ui_overhaul_1080' &
git clone https://github.com/Gr770/CK3-Community-Title-Project '/storage/nvme5/new_clones/AMPL/CK3-Community-Title-Project' &
git clone https://github.com/m00nnsplit/EU4-equestria-mod '/storage/nvme5/new_clones/AMPL/EU4-equestria-mod' &
git clone https://github.com/marangisto/Kick-808 '/storage/nvme5/new_clones/AMPL/Kick-808' &
git clone https://github.com/calniotrey/stellaris-list-extender '/storage/nvme5/new_clones/AMPL/stellaris-list-extender' &
git clone https://github.com/RohitRadar/RCS-Reduction '/storage/nvme5/new_clones/AMPL/RCS-Reduction' &
git clone https://github.com/aff3ct/configuration_files '/storage/nvme5/new_clones/AMPL/configuration_files' &
git clone https://github.com/Issam-KEBIRI/Optimization-of-the-satellite-image-acquisition-plan '/storage/nvme5/new_clones/AMPL/Optimization-of-the-satellite-image-acquisition-plan' &
git clone https://github.com/Solovyev-Pavel/nh_esc_next '/storage/nvme5/new_clones/AMPL/nh_esc_next' &
git clone https://github.com/State-Within-a-State/theeastisred '/storage/nvme5/new_clones/AMPL/theeastisred' &
git clone https://github.com/rorichto/RobotstudioCode '/storage/nvme5/new_clones/AMPL/RobotstudioCode' &
git clone https://github.com/marekyggdrasil/optilogistics '/storage/nvme5/new_clones/AMPL/optilogistics' &
git clone https://github.com/leon123442/AsiaExpansionProject '/storage/nvme5/new_clones/AMPL/AsiaExpansionProject' &
git clone https://github.com/rdmeneze/LTSpiceModels '/storage/nvme5/new_clones/AMPL/LTSpiceModels' &
git clone https://github.com/hamcruise/FJSP-TOU '/storage/nvme5/new_clones/AMPL/FJSP-TOU' &
git clone https://github.com/miguelcjalmeida/gridshortcut '/storage/nvme5/new_clones/AMPL/gridshortcut' &
git clone https://github.com/fietkiewicz/PointerBuilder '/storage/nvme5/new_clones/AMPL/PointerBuilder' &
git clone https://github.com/Namelesss1/Mkwii-Battle-Mod '/storage/nvme5/new_clones/AMPL/Mkwii-Battle-Mod' &
git clone https://github.com/TehFishey/stellaris-crisis-managers '/storage/nvme5/new_clones/AMPL/stellaris-crisis-managers' &
git clone https://github.com/libai1943/Multi-Vehicle-Motion-Planning '/storage/nvme5/new_clones/AMPL/Multi-Vehicle-Motion-Planning' &
git clone https://github.com/stefanomoret/energyscope-MILP '/storage/nvme5/new_clones/AMPL/energyscope-MILP' &
git clone https://github.com/EnderShadow/HyperStellaris-Neptunia '/storage/nvme5/new_clones/AMPL/HyperStellaris-Neptunia' &
git clone https://github.com/jaessy77/kicad-spice '/storage/nvme5/new_clones/AMPL/kicad-spice' &
git clone https://github.com/MatheusBarbieri/SALBP-1-Simulated-Annealing '/storage/nvme5/new_clones/AMPL/SALBP-1-Simulated-Annealing' &
git clone https://github.com/MetaBorgCube/statix-sandbox '/storage/nvme5/new_clones/AMPL/statix-sandbox' &
git clone https://github.com/Zephyrum/FoI '/storage/nvme5/new_clones/AMPL/FoI' &
git clone https://github.com/AlexFleischerParis/modelbuilding '/storage/nvme5/new_clones/AMPL/modelbuilding' &
