#!/bin/bash

git clone https://github.com/h5bp/mobile-boilerplate '/storage/nvme5/new_clones/ApacheConf/mobile-boilerplate' &
git clone https://github.com/patrickdlee/vagrant-examples '/storage/nvme5/new_clones/ApacheConf/vagrant-examples' &
git clone https://github.com/addyosmani/critical-path-css-demo '/storage/nvme5/new_clones/ApacheConf/critical-path-css-demo' &
git clone https://github.com/vasyabigi/angular-slick '/storage/nvme5/new_clones/ApacheConf/angular-slick' &
git clone https://github.com/grayghostvisuals/webdesignerschecklist '/storage/nvme5/new_clones/ApacheConf/webdesignerschecklist' &
git clone https://github.com/scm-ninja/starter-web '/storage/nvme5/new_clones/ApacheConf/starter-web' &
git clone https://github.com/ctrlaltdylan/MirrorMirror '/storage/nvme5/new_clones/ApacheConf/MirrorMirror' &
git clone https://github.com/mgechev/angular-webrtc '/storage/nvme5/new_clones/ApacheConf/angular-webrtc' &
git clone https://github.com/fuelphp-storage/fuelphp '/storage/nvme5/new_clones/ApacheConf/fuelphp' &
git clone https://github.com/tuplejump/play-yeoman '/storage/nvme5/new_clones/ApacheConf/play-yeoman' &
git clone https://github.com/purpleworks/fleet-ui '/storage/nvme5/new_clones/ApacheConf/fleet-ui' &
git clone https://github.com/fdavis/ansible-best-practices '/storage/nvme5/new_clones/ApacheConf/ansible-best-practices' &
git clone https://github.com/travist/meanapp '/storage/nvme5/new_clones/ApacheConf/meanapp' &
git clone https://github.com/kamipo/etcfiles '/storage/nvme5/new_clones/ApacheConf/etcfiles' &
git clone https://github.com/Creare/magento-htaccess '/storage/nvme5/new_clones/ApacheConf/magento-htaccess' &
git clone https://github.com/krimple/angular-socketio-chat '/storage/nvme5/new_clones/ApacheConf/angular-socketio-chat' &
git clone https://github.com/PinkyJie/resume '/storage/nvme5/new_clones/ApacheConf/resume' &
git clone https://github.com/shinvdu/shadowsock '/storage/nvme5/new_clones/ApacheConf/shadowsock' &
git clone https://github.com/cferdinandi/htaccess '/storage/nvme5/new_clones/ApacheConf/htaccess' &
git clone https://github.com/Creare/WP-htaccess '/storage/nvme5/new_clones/ApacheConf/WP-htaccess' &
git clone https://github.com/bylexus/docker-apache-php53 '/storage/nvme5/new_clones/ApacheConf/docker-apache-php53' &
git clone https://github.com/denibertovic/logstash-dockerfile '/storage/nvme5/new_clones/ApacheConf/logstash-dockerfile' &
git clone https://github.com/antoniocapelo/angular-typewrite '/storage/nvme5/new_clones/ApacheConf/angular-typewrite' &
git clone https://github.com/Yelp/docker-observium '/storage/nvme5/new_clones/ApacheConf/docker-observium' &
git clone https://github.com/divshot/polymer-firebase-qa '/storage/nvme5/new_clones/ApacheConf/polymer-firebase-qa' &
git clone https://github.com/learncodeacademy/docker-static-nginx '/storage/nvme5/new_clones/ApacheConf/docker-static-nginx' &
git clone https://github.com/pesterhazy/vagrant-lamp-ansible '/storage/nvme5/new_clones/ApacheConf/vagrant-lamp-ansible' &
git clone https://github.com/TalkingQuickly/docker_rails_dev_env_example '/storage/nvme5/new_clones/ApacheConf/docker_rails_dev_env_example' &
git clone https://github.com/TalkingQuickly/docker_rails_dev_env '/storage/nvme5/new_clones/ApacheConf/docker_rails_dev_env' &
git clone https://github.com/centresource/generator-playbook '/storage/nvme5/new_clones/ApacheConf/generator-playbook' &
git clone https://github.com/Munter/generator-greenfield '/storage/nvme5/new_clones/ApacheConf/generator-greenfield' &
git clone https://github.com/efacilitation/docker-janus-webrtc-gateway '/storage/nvme5/new_clones/ApacheConf/docker-janus-webrtc-gateway' &
git clone https://github.com/rwhaling/dinosaur '/storage/nvme5/new_clones/ApacheConf/dinosaur' &
git clone https://github.com/chronick/middleman-bower-template '/storage/nvme5/new_clones/ApacheConf/middleman-bower-template' &
git clone https://github.com/sashee/letsencrypt-proxy-docker '/storage/nvme5/new_clones/ApacheConf/letsencrypt-proxy-docker' &
git clone https://github.com/rcousens/packer-php7-dev '/storage/nvme5/new_clones/ApacheConf/packer-php7-dev' &
git clone https://github.com/Jamlee/docker-laravel '/storage/nvme5/new_clones/ApacheConf/docker-laravel' &
git clone https://github.com/bjoernklose/angular-wordpress-pods '/storage/nvme5/new_clones/ApacheConf/angular-wordpress-pods' &
git clone https://github.com/hsb4995/Apachange '/storage/nvme5/new_clones/ApacheConf/Apachange' &
git clone https://github.com/ianblenke/docker-avahi '/storage/nvme5/new_clones/ApacheConf/docker-avahi' &
git clone https://github.com/delight-im/htaccess '/storage/nvme5/new_clones/ApacheConf/htaccess' &
git clone https://github.com/aahan/wp-server-config '/storage/nvme5/new_clones/ApacheConf/wp-server-config' &
git clone https://github.com/tnunamak/tech-radar '/storage/nvme5/new_clones/ApacheConf/tech-radar' &
git clone https://github.com/jberta93/ng-facebook-api '/storage/nvme5/new_clones/ApacheConf/ng-facebook-api' &
git clone https://github.com/Zuhkov/docker-containers '/storage/nvme5/new_clones/ApacheConf/docker-containers' &
git clone https://github.com/elitelinux/killer-htaccess '/storage/nvme5/new_clones/ApacheConf/killer-htaccess' &
git clone https://github.com/Autodesk/molecule-2d-for-react '/storage/nvme5/new_clones/ApacheConf/molecule-2d-for-react' &
git clone https://github.com/origamid/origamid-wp-boilerplate '/storage/nvme5/new_clones/ApacheConf/origamid-wp-boilerplate' &
git clone https://github.com/arter97/back-to-n00t '/storage/nvme5/new_clones/ApacheConf/back-to-n00t' &
git clone https://github.com/bylexus/docker-apache-php56 '/storage/nvme5/new_clones/ApacheConf/docker-apache-php56' &
git clone https://github.com/ypid/squid3-config '/storage/nvme5/new_clones/ApacheConf/squid3-config' &
git clone https://github.com/jasodeep/ansible-lamp-stack-playbook '/storage/nvme5/new_clones/ApacheConf/ansible-lamp-stack-playbook' &
git clone https://github.com/tiant167/PhotoFlow '/storage/nvme5/new_clones/ApacheConf/PhotoFlow' &
git clone https://github.com/jroeckle/Marionette-Require-Gulpjs-Boilerplate '/storage/nvme5/new_clones/ApacheConf/Marionette-Require-Gulpjs-Boilerplate' &
git clone https://github.com/hello-jason/middleman-bss '/storage/nvme5/new_clones/ApacheConf/middleman-bss' &
git clone https://github.com/nknj/django-angular-auth '/storage/nvme5/new_clones/ApacheConf/django-angular-auth' &
git clone https://github.com/dskaggs/vagrant-centos-lucee '/storage/nvme5/new_clones/ApacheConf/vagrant-centos-lucee' &
git clone https://github.com/Eyevinn/docker-dash-packager '/storage/nvme5/new_clones/ApacheConf/docker-dash-packager' &
git clone https://github.com/artbelikov/angular-tree-diagram '/storage/nvme5/new_clones/ApacheConf/angular-tree-diagram' &
git clone https://github.com/itsmattsoria/killersvgworkflow '/storage/nvme5/new_clones/ApacheConf/killersvgworkflow' &
git clone https://github.com/thegreatsunra/propeller '/storage/nvme5/new_clones/ApacheConf/propeller' &
git clone https://github.com/liusec/CVE-2017-7529 '/storage/nvme5/new_clones/ApacheConf/CVE-2017-7529' &
git clone https://github.com/tykling/logstash-grok-patterns '/storage/nvme5/new_clones/ApacheConf/logstash-grok-patterns' &
git clone https://github.com/daniel-melzer/flight-skeleton '/storage/nvme5/new_clones/ApacheConf/flight-skeleton' &
git clone https://github.com/yellowmessenger/django-libspark '/storage/nvme5/new_clones/ApacheConf/django-libspark' &
git clone https://github.com/teddymacn/archived-windows-docker-iis-demo '/storage/nvme5/new_clones/ApacheConf/archived-windows-docker-iis-demo' &
git clone https://github.com/phy1729/cv_config '/storage/nvme5/new_clones/ApacheConf/cv_config' &
git clone https://github.com/rafaeltuelho/jboss-eap-managed-on-docker '/storage/nvme5/new_clones/ApacheConf/jboss-eap-managed-on-docker' &
git clone https://github.com/algeriatech/algeria-meetup '/storage/nvme5/new_clones/ApacheConf/algeria-meetup' &
git clone https://github.com/jadianes/olssen '/storage/nvme5/new_clones/ApacheConf/olssen' &
git clone https://github.com/sadapon2008/ansible-roles '/storage/nvme5/new_clones/ApacheConf/ansible-roles' &
git clone https://github.com/mrhieu/ngTranslateEditor '/storage/nvme5/new_clones/ApacheConf/ngTranslateEditor' &
git clone https://github.com/monsat/vagrant-lamp-sample '/storage/nvme5/new_clones/ApacheConf/vagrant-lamp-sample' &
git clone https://github.com/invokr/docker-cgit '/storage/nvme5/new_clones/ApacheConf/docker-cgit' &
git clone https://github.com/chanusukarno/Seat-Reservation-System-AngularJS '/storage/nvme5/new_clones/ApacheConf/Seat-Reservation-System-AngularJS' &
git clone https://github.com/Kadajett/angularHttpPromiseTutorial '/storage/nvme5/new_clones/ApacheConf/angularHttpPromiseTutorial' &
git clone https://github.com/TheIronYard--Orlando/FEE--2015--SPRING '/storage/nvme5/new_clones/ApacheConf/FEE--2015--SPRING' &
git clone https://github.com/acseo/docker-cocorico '/storage/nvme5/new_clones/ApacheConf/docker-cocorico' &
git clone https://github.com/inem/aegea-ansible '/storage/nvme5/new_clones/ApacheConf/aegea-ansible' &
git clone https://github.com/deviantony/docker-opsmanager '/storage/nvme5/new_clones/ApacheConf/docker-opsmanager' &
git clone https://github.com/themejuice/sprout '/storage/nvme5/new_clones/ApacheConf/sprout' &
git clone https://github.com/PatrickHeneise/angular-digest-interceptor '/storage/nvme5/new_clones/ApacheConf/angular-digest-interceptor' &
git clone https://github.com/kobake/filydoc '/storage/nvme5/new_clones/ApacheConf/filydoc' &
git clone https://github.com/jamalshahverdiev/engapng-mysql '/storage/nvme5/new_clones/ApacheConf/engapng-mysql' &
git clone https://github.com/puli/demo-application '/storage/nvme5/new_clones/ApacheConf/demo-application' &
git clone https://github.com/divergentdave/raspberry-pi-configuration '/storage/nvme5/new_clones/ApacheConf/raspberry-pi-configuration' &
git clone https://github.com/dunglas/blog-client '/storage/nvme5/new_clones/ApacheConf/blog-client' &
git clone https://github.com/riconeitzel/magento_sample_data_1.9.1.0_clean '/storage/nvme5/new_clones/ApacheConf/magento_sample_data_1.9.1.0_clean' &
git clone https://github.com/DockerIt/wordpress-docker '/storage/nvme5/new_clones/ApacheConf/wordpress-docker' &
git clone https://github.com/digiaonline/docker-nginx-php-node '/storage/nvme5/new_clones/ApacheConf/docker-nginx-php-node' &
git clone https://github.com/ryanve/css3base '/storage/nvme5/new_clones/ApacheConf/css3base' &
git clone https://github.com/swhitt/centos-apache-passenger '/storage/nvme5/new_clones/ApacheConf/centos-apache-passenger' &
git clone https://github.com/seabornlee/Awesome-Day '/storage/nvme5/new_clones/ApacheConf/Awesome-Day' &
git clone https://github.com/strycore/gamera-manifesto '/storage/nvme5/new_clones/ApacheConf/gamera-manifesto' &
git clone https://github.com/dschneller/haproxy-peers-demo '/storage/nvme5/new_clones/ApacheConf/haproxy-peers-demo' &
git clone https://github.com/Zetaphor/docker-lamp-ssl '/storage/nvme5/new_clones/ApacheConf/docker-lamp-ssl' &
git clone https://github.com/Yonet/WebUnleashed-example '/storage/nvme5/new_clones/ApacheConf/WebUnleashed-example' &
git clone https://github.com/bfgasparin/laravel-apache-docker '/storage/nvme5/new_clones/ApacheConf/laravel-apache-docker' &
git clone https://github.com/yannart/docker-compose-demo '/storage/nvme5/new_clones/ApacheConf/docker-compose-demo' &
git clone https://github.com/slashphoto/slashphoto.github.io '/storage/nvme5/new_clones/ApacheConf/slashphotohub.io' &
git clone https://github.com/million12/docker-nginx-hhvm '/storage/nvme5/new_clones/ApacheConf/docker-nginx-hhvm' &
git clone https://github.com/dieuhd/scrolltofixed-ng '/storage/nvme5/new_clones/ApacheConf/scrolltofixed-ng' &
git clone https://github.com/rastandy/xwiki-ansible-playbook '/storage/nvme5/new_clones/ApacheConf/xwiki-ansible-playbook' &
git clone https://github.com/stevenosloan/heroku-buildpack-apache '/storage/nvme5/new_clones/ApacheConf/heroku-buildpack-apache' &
git clone https://github.com/Aviah/one-click-django-server '/storage/nvme5/new_clones/ApacheConf/one-click-django-server' &
git clone https://github.com/BigAl/CIS '/storage/nvme5/new_clones/ApacheConf/CIS' &
git clone https://github.com/anarcher/ansible-docker-registry '/storage/nvme5/new_clones/ApacheConf/ansible-docker-registry' &
git clone https://github.com/carlosreig/drupal7-docker '/storage/nvme5/new_clones/ApacheConf/drupal7-docker' &
git clone https://github.com/Kunstmaan/KunstmaanAnsibleSandbox '/storage/nvme5/new_clones/ApacheConf/KunstmaanAnsibleSandbox' &
git clone https://github.com/timotheeg/distort_faces '/storage/nvme5/new_clones/ApacheConf/distort_faces' &
git clone https://github.com/AOSPA-legacy/android_device_oneplus_bacon '/storage/nvme5/new_clones/ApacheConf/android_device_oneplus_bacon' &
git clone https://github.com/serkansokmen/processing.js-starter '/storage/nvme5/new_clones/ApacheConf/processing.js-starter' &
git clone https://github.com/idelsink/ampache-docker '/storage/nvme5/new_clones/ApacheConf/ampache-docker' &
git clone https://github.com/JonDotsoy/docker-laravel '/storage/nvme5/new_clones/ApacheConf/docker-laravel' &
git clone https://github.com/madvas/simple-angularfire-angularmaterial-chat '/storage/nvme5/new_clones/ApacheConf/simple-angularfire-angularmaterial-chat' &
git clone https://github.com/peterjmag/css3-animated-type '/storage/nvme5/new_clones/ApacheConf/css3-animated-type' &
git clone https://github.com/nelsonomuto/angular-multi-version-example '/storage/nvme5/new_clones/ApacheConf/angular-multi-version-example' &
git clone https://github.com/angular/angular-prs '/storage/nvme5/new_clones/ApacheConf/angular-prs' &
git clone https://github.com/tanakahisateru/wp-demo-wck2016 '/storage/nvme5/new_clones/ApacheConf/wp-demo-wck2016' &
git clone https://github.com/v5tech/apache2-tomcat7-cluster '/storage/nvme5/new_clones/ApacheConf/apache2-tomcat7-cluster' &
git clone https://github.com/mpas/collect-distributed-application-logging-using-fluentd-efk-stack '/storage/nvme5/new_clones/ApacheConf/collect-distributed-application-logging-using-fluentd-efk-stack' &
git clone https://github.com/GuGuss/headless-drupal8-platformsh '/storage/nvme5/new_clones/ApacheConf/headless-drupal8-platformsh' &
git clone https://github.com/cboggs/gmond-influxdb-bridge '/storage/nvme5/new_clones/ApacheConf/gmond-influxdb-bridge' &
git clone https://github.com/bobthecow/heroku-buildpack-nanoc '/storage/nvme5/new_clones/ApacheConf/heroku-buildpack-nanoc' &
git clone https://github.com/tongsq/Dockerfiles '/storage/nvme5/new_clones/ApacheConf/Dockerfiles' &
git clone https://github.com/ZoeyWolfe/have-you-read-nevada '/storage/nvme5/new_clones/ApacheConf/have-you-read-nevada' &
git clone https://github.com/miguelbalparda/vm '/storage/nvme5/new_clones/ApacheConf/vm' &
git clone https://github.com/paopaoyu/docker-lvs '/storage/nvme5/new_clones/ApacheConf/docker-lvs' &
git clone https://github.com/enspiral-dev-academy/angular-workshop '/storage/nvme5/new_clones/ApacheConf/angular-workshop' &
git clone https://github.com/Pestov/awesome-htaccess '/storage/nvme5/new_clones/ApacheConf/awesome-htaccess' &
git clone https://github.com/noeltimar/Dotfiles '/storage/nvme5/new_clones/ApacheConf/Dotfiles' &
git clone https://github.com/47ronin/forecastview '/storage/nvme5/new_clones/ApacheConf/forecastview' &
git clone https://github.com/joehack3r/awsTechies201509 '/storage/nvme5/new_clones/ApacheConf/awsTechies201509' &
git clone https://github.com/madvas/multiline-string-to-javascript-converter '/storage/nvme5/new_clones/ApacheConf/multiline-string-to-javascript-converter' &
git clone https://github.com/rigelhope/testprep '/storage/nvme5/new_clones/ApacheConf/testprep' &
git clone https://github.com/zenoamaro/ansible-rethinkdb '/storage/nvme5/new_clones/ApacheConf/ansible-rethinkdb' &
git clone https://github.com/UtahDave/salt-vagrant-lxc '/storage/nvme5/new_clones/ApacheConf/salt-vagrant-lxc' &
git clone https://github.com/ruyrybeyro/ansible-freeradius '/storage/nvme5/new_clones/ApacheConf/ansible-freeradius' &
git clone https://github.com/cloudtrov/dockyard '/storage/nvme5/new_clones/ApacheConf/dockyard' &
git clone https://github.com/qalingo/qalingo-quick-start-windows-env '/storage/nvme5/new_clones/ApacheConf/qalingo-quick-start-windows-env' &
git clone https://github.com/eumendoza/yeomanTesting '/storage/nvme5/new_clones/ApacheConf/yeomanTesting' &
git clone https://github.com/GoogleCloudPlatform/compute-video-demo-chef '/storage/nvme5/new_clones/ApacheConf/compute-video-demo-chef' &
git clone https://github.com/EmileKroeger/geekydic '/storage/nvme5/new_clones/ApacheConf/geekydic' &
git clone https://github.com/g00glen00b/angular-samples '/storage/nvme5/new_clones/ApacheConf/angular-samples' &
git clone https://github.com/fredr/silex-html5-boilerplate '/storage/nvme5/new_clones/ApacheConf/silex-html5-boilerplate' &
git clone https://github.com/thiagohps/htaccess '/storage/nvme5/new_clones/ApacheConf/htaccess' &
git clone https://github.com/KennethWangDotDev/LucidCSS '/storage/nvme5/new_clones/ApacheConf/LucidCSS' &
git clone https://github.com/BlackIkeEagle-archived/docker-images '/storage/nvme5/new_clones/ApacheConf/docker-images' &
git clone https://github.com/V3ckt0r/docker-httpd-proxy '/storage/nvme5/new_clones/ApacheConf/docker-httpd-proxy' &
git clone https://github.com/appleboy/backbone-template-engine '/storage/nvme5/new_clones/ApacheConf/backbone-template-engine' &
git clone https://github.com/basho/riak-zabbix '/storage/nvme5/new_clones/ApacheConf/riak-zabbix' &
git clone https://github.com/nikosdano/fosscomm '/storage/nvme5/new_clones/ApacheConf/fosscomm' &
git clone https://github.com/jldowns/vatic-docker '/storage/nvme5/new_clones/ApacheConf/vatic-docker' &
git clone https://github.com/ZHAJOR/Docker-Apache-2.4-Php-5.6-for-Laravel '/storage/nvme5/new_clones/ApacheConf/Docker-Apache-2.4-Php-5.6-for-Laravel' &
git clone https://github.com/Makio64/Template-Modules '/storage/nvme5/new_clones/ApacheConf/Template-Modules' &
git clone https://github.com/sandermangel/magento-htaccess '/storage/nvme5/new_clones/ApacheConf/magento-htaccess' &
git clone https://github.com/heyamykate/provoPads '/storage/nvme5/new_clones/ApacheConf/provoPads' &
git clone https://github.com/bpietraga/wordpress-speed-htaccess '/storage/nvme5/new_clones/ApacheConf/wordpress-speed-htaccess' &
git clone https://github.com/grep4linux/salt-admin-student '/storage/nvme5/new_clones/ApacheConf/salt-admin-student' &
git clone https://github.com/bpoinsot/slim-skeleton '/storage/nvme5/new_clones/ApacheConf/slim-skeleton' &
git clone https://github.com/cwmdo/docker-php5-nginx '/storage/nvme5/new_clones/ApacheConf/docker-php5-nginx' &
git clone https://github.com/tangpool/TangAgent '/storage/nvme5/new_clones/ApacheConf/TangAgent' &
git clone https://github.com/AlJohri/nuze '/storage/nvme5/new_clones/ApacheConf/nuze' &
git clone https://github.com/benmanu/silverstripe-skeleton '/storage/nvme5/new_clones/ApacheConf/silverstripe-skeleton' &
git clone https://github.com/giuseppemorelli/Vagrant-LAMP '/storage/nvme5/new_clones/ApacheConf/Vagrant-LAMP' &
git clone https://github.com/containerize/custom-pptp-docker '/storage/nvme5/new_clones/ApacheConf/custom-pptp-docker' &
git clone https://github.com/jamalshahverdiev/apng-mysqlphp-vhost-autoinstall '/storage/nvme5/new_clones/ApacheConf/apng-mysqlphp-vhost-autoinstall' &
git clone https://github.com/yahyazini/simple-laravel-docker '/storage/nvme5/new_clones/ApacheConf/simple-laravel-docker' &
git clone https://github.com/Servers-for-Hackers/ansible-pgsql-example '/storage/nvme5/new_clones/ApacheConf/ansible-pgsql-example' &
git clone https://github.com/d11wtq/apache-docker '/storage/nvme5/new_clones/ApacheConf/apache-docker' &
git clone https://github.com/vhoen/docker-xdebug-sublime-text '/storage/nvme5/new_clones/ApacheConf/docker-xdebug-sublime-text' &
git clone https://github.com/onattyso/BuzzFeed-Headline-Generator '/storage/nvme5/new_clones/ApacheConf/BuzzFeed-Headline-Generator' &
git clone https://github.com/dcu/git-http-server '/storage/nvme5/new_clones/ApacheConf/git-http-server' &
git clone https://github.com/maximelebreton/SpotiFIP '/storage/nvme5/new_clones/ApacheConf/SpotiFIP' &
git clone https://github.com/ibmjstart/bluemix-wordpress '/storage/nvme5/new_clones/ApacheConf/bluemix-wordpress' &
git clone https://github.com/dalibo/pgsql_logwatch '/storage/nvme5/new_clones/ApacheConf/pgsql_logwatch' &
git clone https://github.com/eumendoza/prototiposYeoman '/storage/nvme5/new_clones/ApacheConf/prototiposYeoman' &
git clone https://github.com/fructify/wordpress '/storage/nvme5/new_clones/ApacheConf/wordpress' &
