#!/bin/bash

git clone https://github.com/daliansky/XiaoMi-Pro-Hackintosh '/storage/nvme5/new_clones/ASL/XiaoMi-Pro-Hackintosh' &
git clone https://github.com/edk2-porting/edk2-msm '/storage/nvme5/new_clones/ASL/edk2-msm' &
git clone https://github.com/postgres-cn/pgdoc-cn '/storage/nvme5/new_clones/ASL/pgdoc-cn' &
git clone https://github.com/daliansky/OC-little '/storage/nvme5/new_clones/ASL/OC-little' &
git clone https://github.com/osy/HaC-Mini '/storage/nvme5/new_clones/ASL/HaC-Mini' &
git clone https://github.com/tylernguyen/x1c6-hackintosh '/storage/nvme5/new_clones/ASL/x1c6-hackintosh' &
git clone https://github.com/dortania/Getting-Started-With-ACPI '/storage/nvme5/new_clones/ASL/Getting-Started-With-ACPI' &
git clone https://github.com/5T33Z0/OC-Little-Translated '/storage/nvme5/new_clones/ASL/OC-Little-Translated' &
git clone https://github.com/acpica/acpica '/storage/nvme5/new_clones/ASL/acpica' &
git clone https://github.com/kirainmoe/tongfang-macos '/storage/nvme5/new_clones/ASL/tongfang-macos' &
git clone https://github.com/krim404/DellXPS15-9550-OSX '/storage/nvme5/new_clones/ASL/DellXPS15-9550-OSX' &
git clone https://github.com/valnoxy/t480-oc '/storage/nvme5/new_clones/ASL/t480-oc' &
git clone https://github.com/profzei/Matebook-X-Pro-2018 '/storage/nvme5/new_clones/ASL/Matebook-X-Pro-2018' &
git clone https://github.com/appleserial/NUC8I5BEH '/storage/nvme5/new_clones/ASL/NUC8I5BEH' &
git clone https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPad-T460s-macOS-OpenCore' &
git clone https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-T450s-Hackintosh-OpenCore' &
git clone https://github.com/banhbaoxamlan/X230-Hackintosh '/storage/nvme5/new_clones/ASL/X230-Hackintosh' &
git clone https://github.com/jardenliu/XPS15-9560-Ventura '/storage/nvme5/new_clones/ASL/XPS15-9560-Ventura' &
git clone https://github.com/aarch64-laptops/build '/storage/nvme5/new_clones/ASL/build' &
git clone https://github.com/appleserial/DeskMini '/storage/nvme5/new_clones/ASL/DeskMini' &
git clone https://github.com/Cr0wTom/Mi-Notebook-Pro-Mods '/storage/nvme5/new_clones/ASL/Mi-Notebook-Pro-Mods' &
git clone https://github.com/tluck/Lenovo-T420-Clover '/storage/nvme5/new_clones/ASL/Lenovo-T420-Clover' &
git clone https://github.com/hieplpvip/Asus-Zenbook-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-Zenbook-Hackintosh' &
git clone https://github.com/frezs/MateBook14-Hackintosh '/storage/nvme5/new_clones/ASL/MateBook14-Hackintosh' &
git clone https://github.com/JettyMetty/Hackintosh-ROG-STRIX-Z490I '/storage/nvme5/new_clones/ASL/Hackintosh-ROG-STRIX-Z490I' &
git clone https://github.com/jaromeyer/XPS9570-Catalina '/storage/nvme5/new_clones/ASL/XPS9570-Catalina' &
git clone https://github.com/HouCoder/asrock-z370m-pro4-hackintosh '/storage/nvme5/new_clones/ASL/asrock-z370m-pro4-hackintosh' &
git clone https://github.com/5T33Z0/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Gigabyte-Z490-Vision-G-Hackintosh-OpenCore' &
git clone https://github.com/theQuert/XPS-9360-macOS '/storage/nvme5/new_clones/ASL/XPS-9360-macOS' &
git clone https://github.com/hoanX/xps13-9360-Hackintosh '/storage/nvme5/new_clones/ASL/xps13-9360-Hackintosh' &
git clone https://github.com/Fu-Yuxuan-hub/Generic-EFI-for-H610-B660-Z690-B760-Z790 '/storage/nvme5/new_clones/ASL/Generic-EFI-for-H610-B660-Z690-B760-Z790' &
git clone https://github.com/johnnynunez/Xiaomi-Notebook-Air-1Gen '/storage/nvme5/new_clones/ASL/Xiaomi-Notebook-Air-1Gen' &
git clone https://github.com/tluck/Lenovo-T460-Clover '/storage/nvme5/new_clones/ASL/Lenovo-T460-Clover' &
git clone https://github.com/Pinming/Dell-Inspiron-7590-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/Dell-Inspiron-7590-Hackintosh-Opencore' &
git clone https://github.com/kayoyin/transformer-slt '/storage/nvme5/new_clones/ASL/transformer-slt' &
git clone https://github.com/johnnynunez/XiaomiGaming '/storage/nvme5/new_clones/ASL/XiaomiGaming' &
git clone https://github.com/blacklizard/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore '/storage/nvme5/new_clones/ASL/gigabyte-z390-aorus-pro-wifi-hackintosh-opencore' &
git clone https://github.com/iamthaoly/amd-laptop-hackintosh '/storage/nvme5/new_clones/ASL/amd-laptop-hackintosh' &
git clone https://github.com/valnoxy/t440p-oc '/storage/nvme5/new_clones/ASL/t440p-oc' &
git clone https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579 '/storage/nvme5/new_clones/ASL/OpenCore-Hackintosh-Dell-G3-3579' &
git clone https://github.com/Project-Aloha/mu_aloha_platforms '/storage/nvme5/new_clones/ASL/mu_aloha_platforms' &
git clone https://github.com/verfasor/X230-Hackintosh '/storage/nvme5/new_clones/ASL/X230-Hackintosh' &
git clone https://github.com/yusifsalam/t490-macos '/storage/nvme5/new_clones/ASL/t490-macos' &
git clone https://github.com/weachy/CoreBookX-14-Hackintosh '/storage/nvme5/new_clones/ASL/CoreBookX-14-Hackintosh' &
git clone https://github.com/sqlsec/CHUWI-COREBOOK-X-I5-8259U '/storage/nvme5/new_clones/ASL/CHUWI-COREBOOK-X-I5-8259U' &
git clone https://github.com/cassiobotaro/modeloC4 '/storage/nvme5/new_clones/ASL/modeloC4' &
git clone https://github.com/aliyoge/Hackintosh-ThinkPad-E480 '/storage/nvme5/new_clones/ASL/Hackintosh-ThinkPad-E480' &
git clone https://github.com/b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh '/storage/nvme5/new_clones/ASL/ROG-Zephyrus-G14-GA402-Hackintosh' &
git clone https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Lenovo-T530-Hackintosh-OpenCore' &
git clone https://github.com/luchina-gabriel/EFI-GIGABYTE-Z690-AORUS-ELITE-AX-12900K-RX6900XT '/storage/nvme5/new_clones/ASL/EFI-GIGABYTE-Z690-AORUS-ELITE-AX-12900K-RX6900XT' &
git clone https://github.com/zachs78/MacOS-XPS-9500-OpenCore '/storage/nvme5/new_clones/ASL/MacOS-XPS-9500-OpenCore' &
git clone https://github.com/daggeryu/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh '/storage/nvme5/new_clones/ASL/DELL-Inspiron_5488_5480_5580_5482_5582_Hackintosh' &
git clone https://github.com/whtiehack/XiaoMi-Air '/storage/nvme5/new_clones/ASL/XiaoMi-Air' &
git clone https://github.com/tunglamvghy/AsusS530UN-hackintosh '/storage/nvme5/new_clones/ASL/AsusS530UN-hackintosh' &
git clone https://github.com/zysuper/Thinkpad-X1-extreme-EFI '/storage/nvme5/new_clones/ASL/Thinkpad-X1-extreme-EFI' &
git clone https://github.com/Baio1977/Hackintosh-EFI-Collection '/storage/nvme5/new_clones/ASL/Hackintosh-EFI-Collection' &
git clone https://github.com/tlefko/Huawei-Matebook-X-Pro-Ventura '/storage/nvme5/new_clones/ASL/Huawei-Matebook-X-Pro-Ventura' &
git clone https://github.com/johnnynunez/Xiaomi-Notebook-air-12-5 '/storage/nvme5/new_clones/ASL/Xiaomi-Notebook-air-12-5' &
git clone https://github.com/shm007g/hackintosh_handcraft '/storage/nvme5/new_clones/ASL/hackintosh_handcraft' &
git clone https://github.com/wxjiyc/FunHouse-F10-MPro-1005G1-1065G7-Hackintosh '/storage/nvme5/new_clones/ASL/FunHouse-F10-MPro-1005G1-1065G7-Hackintosh' &
git clone https://github.com/jekhor/yogabook-linux '/storage/nvme5/new_clones/ASL/yogabook-linux' &
git clone https://github.com/Azkali/GPD-P2-MAX-Hackintosh '/storage/nvme5/new_clones/ASL/GPD-P2-MAX-Hackintosh' &
git clone https://github.com/mbarbierato/Intel-NUC8i3BEH '/storage/nvme5/new_clones/ASL/Intel-NUC8i3BEH' &
git clone https://github.com/5T33Z0/Clover-Crate '/storage/nvme5/new_clones/ASL/Clover-Crate' &
git clone https://github.com/zacmks/Hackintosh-Aero-15X '/storage/nvme5/new_clones/ASL/Hackintosh-Aero-15X' &
git clone https://github.com/rursache/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT '/storage/nvme5/new_clones/ASL/Hackintosh-13900k-Z690-AORUS-ELITE-AX-DDR5-AMD-6900XT' &
git clone https://github.com/Sharlion/z170_6700k_hackintosh '/storage/nvme5/new_clones/ASL/z170_6700k_hackintosh' &
git clone https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh '/storage/nvme5/new_clones/ASL/Acer-A515-51G-Hackintosh' &
git clone https://github.com/Juan-VC-gh/Hackintosh-macOS-Dell-G7-7588 '/storage/nvme5/new_clones/ASL/Hackintosh-macOS-Dell-G7-7588' &
git clone https://github.com/ducnm9/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend '/storage/nvme5/new_clones/ASL/Hackintosh-Intel-i5-10400-Asrock-B460M-Steel-Legend' &
git clone https://github.com/deeplyfriedchicken/Jared-PC '/storage/nvme5/new_clones/ASL/Jared-PC' &
git clone https://github.com/roederja/asus-rog-strix-b460I-hackintosh '/storage/nvme5/new_clones/ASL/asus-rog-strix-b460I-hackintosh' &
git clone https://github.com/vampjaz/razer_blade_stealth_hackintosh '/storage/nvme5/new_clones/ASL/razer_blade_stealth_hackintosh' &
git clone https://github.com/0xNILADRI/Acer-Nitro5-Hackintosh-OC '/storage/nvme5/new_clones/ASL/Acer-Nitro5-Hackintosh-OC' &
git clone https://github.com/Baio1977/Lenovo-Thinkpad-T14 '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-T14' &
git clone https://github.com/GeekyCoder7/OpenCore-EFI-Lenovo-Y50-70 '/storage/nvme5/new_clones/ASL/OpenCore-EFI-Lenovo-Y50-70' &
git clone https://github.com/Amin-0-1/hackintosh-Dell-g3-15-3590- '/storage/nvme5/new_clones/ASL/hackintosh-Dell-g3-15-3590-' &
git clone https://github.com/TylerLyczak/Unsupported-6900XT-Hackintosh-Fix '/storage/nvme5/new_clones/ASL/Unsupported-6900XT-Hackintosh-Fix' &
git clone https://github.com/jsassu20/OpenCore-HotPatching-Guide '/storage/nvme5/new_clones/ASL/OpenCore-HotPatching-Guide' &
git clone https://github.com/sakoula/XiaoMi-Air-6200U '/storage/nvme5/new_clones/ASL/XiaoMi-Air-6200U' &
git clone https://github.com/SukkaW/ThinkPad-E480-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-E480-Hackintosh' &
git clone https://github.com/picopock/hackintosh_ASUS_ROG_Z390 '/storage/nvme5/new_clones/ASL/hackintosh_ASUS_ROG_Z390' &
git clone https://github.com/dragonflylee/Yoga730-hackintosh '/storage/nvme5/new_clones/ASL/Yoga730-hackintosh' &
git clone https://github.com/Sniki/Lenovo-Thinkpad-X240 '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-X240' &
git clone https://github.com/alexpotter1/intel-nuc6i7kyk-opencore '/storage/nvme5/new_clones/ASL/intel-nuc6i7kyk-opencore' &
git clone https://github.com/DocSystem/razerbladehackintosh '/storage/nvme5/new_clones/ASL/razerbladehackintosh' &
git clone https://github.com/HJebbour/ThinkPad-X1C8-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-X1C8-Hackintosh' &
git clone https://github.com/athlonreg/ASRock-Z370-Pro4-Hackintosh '/storage/nvme5/new_clones/ASL/ASRock-Z370-Pro4-Hackintosh' &
git clone https://github.com/leocg/Hackintosh-Dell-G5-5590 '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-G5-5590' &
git clone https://github.com/sakoula/HP-EliteDesk-800-G2-6700 '/storage/nvme5/new_clones/ASL/HP-EliteDesk-800-G2-6700' &
git clone https://github.com/zhtengw/EFI-for-X1C6-hackintosh '/storage/nvme5/new_clones/ASL/EFI-for-X1C6-hackintosh' &
git clone https://github.com/Lorys89/DELL_OPTIPLEX_3060_MFF '/storage/nvme5/new_clones/ASL/DELL_OPTIPLEX_3060_MFF' &
git clone https://github.com/rsdev69/ThinkPad-E560-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-E560-Hackintosh' &
git clone https://github.com/zty199/HP_Pavilion_15-cb073tx_Hackintosh '/storage/nvme5/new_clones/ASL/HP_Pavilion_15-cb073tx_Hackintosh' &
git clone https://github.com/nitingaury/Thinkpad-T470-EFI-Opencore '/storage/nvme5/new_clones/ASL/Thinkpad-T470-EFI-Opencore' &
git clone https://github.com/SuhailSherief/ThinkPad-x260-macOS-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPad-x260-macOS-OpenCore' &
git clone https://github.com/khronokernel/OpenCore-Asus-X299 '/storage/nvme5/new_clones/ASL/OpenCore-Asus-X299' &
git clone https://github.com/chuxubank/MSI-GP62-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-GP62-Hackintosh' &
git clone https://github.com/wy414012/huaNan_x79_e5_2670_v1_c2 '/storage/nvme5/new_clones/ASL/huaNan_x79_e5_2670_v1_c2' &
git clone https://github.com/SwimmingPig/Hackintosh-Intel-i5-10400-Gigabyte-Z490M-Gaming-X '/storage/nvme5/new_clones/ASL/Hackintosh-Intel-i5-10400-Gigabyte-Z490M-Gaming-X' &
git clone https://github.com/LinhNC/XPS9570-OpenCore '/storage/nvme5/new_clones/ASL/XPS9570-OpenCore' &
git clone https://github.com/nakquada/Z790-Hackintosh '/storage/nvme5/new_clones/ASL/Z790-Hackintosh' &
git clone https://github.com/beyondgary/Hackintosh_i5-7500_B250_HD630_EFI '/storage/nvme5/new_clones/ASL/Hackintosh_i5-7500_B250_HD630_EFI' &
git clone https://github.com/lshbluesky/Samsung-NT750XDA-KF59U-Hackintosh '/storage/nvme5/new_clones/ASL/Samsung-NT750XDA-KF59U-Hackintosh' &
git clone https://github.com/bangbaew/Gigabyte-B460M-DS3H-Hackintosh '/storage/nvme5/new_clones/ASL/Gigabyte-B460M-DS3H-Hackintosh' &
git clone https://github.com/Dwarven/Hackintosh '/storage/nvme5/new_clones/ASL/Hackintosh' &
git clone https://github.com/shuai620/NUC7i7BNH '/storage/nvme5/new_clones/ASL/NUC7i7BNH' &
git clone https://github.com/Jonny-china/R720-15IKBN-Hackintosh '/storage/nvme5/new_clones/ASL/R720-15IKBN-Hackintosh' &
git clone https://github.com/macOS-Dell-Latitude-E7470/macOS-Dell-Latitude-E7470 '/storage/nvme5/new_clones/ASL/macOS-Dell-Latitude-E7470' &
git clone https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-ROG-GL552VW-Hackintosh' &
git clone https://github.com/Ab2774/Lenovo-IdeaPad-320-14-IKB-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-IdeaPad-320-14-IKB-Hackintosh' &
git clone https://github.com/m4salah/hackintosh-T480s '/storage/nvme5/new_clones/ASL/hackintosh-T480s' &
git clone https://github.com/XenOriginal/XiaoMi-Ruby-15.6-UMA-only '/storage/nvme5/new_clones/ASL/XiaoMi-Ruby-15.6-UMA-only' &
git clone https://github.com/Spectrelai/Hackintosh-B460M-MORTAR-WIFI '/storage/nvme5/new_clones/ASL/Hackintosh-B460M-MORTAR-WIFI' &
git clone https://github.com/gabrielcasag/EFI-IDEAPAD-330-15IKBR-i5-8250U '/storage/nvme5/new_clones/ASL/EFI-IDEAPAD-330-15IKBR-i5-8250U' &
git clone https://github.com/Autocrit/Asus-ROG-STRIX-H370-I-GAMING-Hackintosh-Guide '/storage/nvme5/new_clones/ASL/Asus-ROG-STRIX-H370-I-GAMING-Hackintosh-Guide' &
git clone https://github.com/gorquan/OC-XPS-7590 '/storage/nvme5/new_clones/ASL/OC-XPS-7590' &
git clone https://github.com/jbwharris/hackintosh-msi-GL72M-7RDX '/storage/nvme5/new_clones/ASL/hackintosh-msi-GL72M-7RDX' &
git clone https://github.com/XuCpeng/GIGABYTE-B360M_AORUS_PRO-8700-Hackintosh-OpenCore-EFI '/storage/nvme5/new_clones/ASL/GIGABYTE-B360M_AORUS_PRO-8700-Hackintosh-OpenCore-EFI' &
git clone https://github.com/barijaona/OpenCore_GA-Z170X-Gaming5 '/storage/nvme5/new_clones/ASL/OpenCore_GA-Z170X-Gaming5' &
git clone https://github.com/RockJesus/Alienware-17-R4-Dual-GPU-MacOS-15-10-Hackintosh-Sequoia '/storage/nvme5/new_clones/ASL/Alienware-17-R4-Dual-GPU-MacOS-15-10-Hackintosh-Sequoia' &
git clone https://github.com/rafaelmaeuer/Asus-Z590-P-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-Z590-P-Hackintosh' &
git clone https://github.com/bdragonh/T480S-BIGSUR-EFI '/storage/nvme5/new_clones/ASL/T480S-BIGSUR-EFI' &
git clone https://github.com/Z39/Lenovo-Y430p-OS-X-Clover-OpenCore-Hotpatch '/storage/nvme5/new_clones/ASL/Lenovo-Y430p-OS-X-Clover-OpenCore-Hotpatch' &
git clone https://github.com/Z39/Lenovo-Rescuer-14isk-15isk-OS-X-Clover-Hotpatch '/storage/nvme5/new_clones/ASL/Lenovo-Rescuer-14isk-15isk-OS-X-Clover-Hotpatch' &
git clone https://github.com/msbence/hackintosh-DellLatitude5400 '/storage/nvme5/new_clones/ASL/hackintosh-DellLatitude5400' &
git clone https://github.com/Baio1977/GA-Z490M-Gaming-X '/storage/nvme5/new_clones/ASL/GA-Z490M-Gaming-X' &
git clone https://github.com/kinoute/Hack-Dell-Latitude-E6430 '/storage/nvme5/new_clones/ASL/Hack-Dell-Latitude-E6430' &
git clone https://github.com/mackonsti/nuc10i7fnh '/storage/nvme5/new_clones/ASL/nuc10i7fnh' &
git clone https://github.com/suzuke/LG-Gram-13z980-Opencore '/storage/nvme5/new_clones/ASL/LG-Gram-13z980-Opencore' &
git clone https://github.com/kecinzer/hpelitebook850g5-opencore '/storage/nvme5/new_clones/ASL/hpelitebook850g5-opencore' &
git clone https://github.com/lhl/linuxlaptops '/storage/nvme5/new_clones/ASL/linuxlaptops' &
git clone https://github.com/wu-hongjun/Hackintosh-Thinkpad-P50 '/storage/nvme5/new_clones/ASL/Hackintosh-Thinkpad-P50' &
git clone https://github.com/kingo132/GPD-Win-Max-Hackintosh '/storage/nvme5/new_clones/ASL/GPD-Win-Max-Hackintosh' &
git clone https://github.com/balopez83/Surface_Pro_4_Hackintosh '/storage/nvme5/new_clones/ASL/Surface_Pro_4_Hackintosh' &
git clone https://github.com/Sniki/Lenovo-Thinkpad-T440S '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-T440S' &
git clone https://github.com/khanhtran-cse/lenovo-ideapad-l340-hackintosh '/storage/nvme5/new_clones/ASL/lenovo-ideapad-l340-hackintosh' &
git clone https://github.com/xma/T480-Clover '/storage/nvme5/new_clones/ASL/T480-Clover' &
git clone https://github.com/kinoute/Hack-HP-EliteBook-850-G5 '/storage/nvme5/new_clones/ASL/Hack-HP-EliteBook-850-G5' &
git clone https://github.com/lshbluesky/OC-GA-B250M-DS3H-Hackintosh '/storage/nvme5/new_clones/ASL/OC-GA-B250M-DS3H-Hackintosh' &
git clone https://github.com/Innoxious/hackintosh-hp-840-g3-intel-ac8260 '/storage/nvme5/new_clones/ASL/hackintosh-hp-840-g3-intel-ac8260' &
git clone https://github.com/koluris/ZEPHYRUS-M15-GU502-OpenCore '/storage/nvme5/new_clones/ASL/ZEPHYRUS-M15-GU502-OpenCore' &
git clone https://github.com/midi1996/P50-opencore-hackintosh '/storage/nvme5/new_clones/ASL/P50-opencore-hackintosh' &
git clone https://github.com/MohammadtaghiFarkhondekar/macOS-For-Asus-ROG-GL553VD '/storage/nvme5/new_clones/ASL/macOS-For-Asus-ROG-GL553VD' &
git clone https://github.com/duszmox/ThinkPad-X1C4-macOS-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPad-X1C4-macOS-OpenCore' &
git clone https://github.com/SiddheshNan/Acer-A515-51G-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Acer-A515-51G-Hackintosh-OpenCore' &
git clone https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh '/storage/nvme5/new_clones/ASL/HP-ProBook-430-440-450-G6-Hackintosh' &
git clone https://github.com/M69W/XPS-15-9570-macOS '/storage/nvme5/new_clones/ASL/XPS-15-9570-macOS' &
git clone https://github.com/Z39/Lenovo-G410-G510-OS-X-Clover-OpenCore-Hotpatch '/storage/nvme5/new_clones/ASL/Lenovo-G410-G510-OS-X-Clover-OpenCore-Hotpatch' &
git clone https://github.com/zhaxingyu/MSI-B460i-Hackintosh-Wifi '/storage/nvme5/new_clones/ASL/MSI-B460i-Hackintosh-Wifi' &
git clone https://github.com/THEDEVIOUS1/CHUWI-MINIBOOK-HACKINTOSH '/storage/nvme5/new_clones/ASL/CHUWI-MINIBOOK-HACKINTOSH' &
git clone https://github.com/sambow23/Dell-XPS-13-7390-macOS '/storage/nvme5/new_clones/ASL/Dell-XPS-13-7390-macOS' &
git clone https://github.com/altjz/NUC8I5BEH-EFI '/storage/nvme5/new_clones/ASL/NUC8I5BEH-EFI' &
git clone https://github.com/MokkaSchnalle/macOS-Dell-5411-5511 '/storage/nvme5/new_clones/ASL/macOS-Dell-5411-5511' &
git clone https://github.com/Chilluminati91/Huawei-Matebook-X-Pro-2020-Hackintosh '/storage/nvme5/new_clones/ASL/Huawei-Matebook-X-Pro-2020-Hackintosh' &
git clone https://github.com/Mateo1234454545/DELL-5570-Hackintosh '/storage/nvme5/new_clones/ASL/DELL-5570-Hackintosh' &
git clone https://github.com/AskDavis/LG-Gram-17Z90N '/storage/nvme5/new_clones/ASL/LG-Gram-17Z90N' &
git clone https://github.com/mishailovic/Hackintosh-Dell-7567-OpenCore_Ventura '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-7567-OpenCore_Ventura' &
git clone https://github.com/Shaw-fung/Intel-NUC8I5BEH-Hackintosh '/storage/nvme5/new_clones/ASL/Intel-NUC8I5BEH-Hackintosh' &
git clone https://github.com/muhrizki1996/Hackintosh-Lenovo-ThinkPad-X230 '/storage/nvme5/new_clones/ASL/Hackintosh-Lenovo-ThinkPad-X230' &
git clone https://github.com/joaodematejr/S145-Hackintosh '/storage/nvme5/new_clones/ASL/S145-Hackintosh' &
git clone https://github.com/GaisaiYuno/magicbook2019-ryzen3500u-hackintosh '/storage/nvme5/new_clones/ASL/magicbook2019-ryzen3500u-hackintosh' &
git clone https://github.com/pjungkamp/yoga9-linux '/storage/nvme5/new_clones/ASL/yoga9-linux' &
git clone https://github.com/duquewu/Hackintosh-XPS7590 '/storage/nvme5/new_clones/ASL/Hackintosh-XPS7590' &
git clone https://github.com/dnsdk/Dell-Precision-5510-macOS '/storage/nvme5/new_clones/ASL/Dell-Precision-5510-macOS' &
git clone https://github.com/wxjiyc/CHUWI-CoreBook-X-2022-8259U-Hackintosh '/storage/nvme5/new_clones/ASL/CHUWI-CoreBook-X-2022-8259U-Hackintosh' &
git clone https://github.com/cowpod/Framework-Hackintosh '/storage/nvme5/new_clones/ASL/Framework-Hackintosh' &
git clone https://github.com/luchina-gabriel/EFI-HUANANZHI-X99-QD4-2630L-RX5500XT '/storage/nvme5/new_clones/ASL/EFI-HUANANZHI-X99-QD4-2630L-RX5500XT' &
git clone https://github.com/vietthai2512/HP_Pavilion_15_cs0101TX_Hackintosh '/storage/nvme5/new_clones/ASL/HP_Pavilion_15_cs0101TX_Hackintosh' &
git clone https://github.com/Z39/Lenovo-Y510p-OS-X-Clover-OpenCore-Hotpatch '/storage/nvme5/new_clones/ASL/Lenovo-Y510p-OS-X-Clover-OpenCore-Hotpatch' &
git clone https://github.com/sve1r/OMEN-By-HP-15-ax225TX-Hackintosh-EFI '/storage/nvme5/new_clones/ASL/OMEN-By-HP-15-ax225TX-Hackintosh-EFI' &
git clone https://github.com/dyne/dynebolic-upstream '/storage/nvme5/new_clones/ASL/dynebolic-upstream' &
git clone https://github.com/Baio1977/MSI-MAG-Z490-Tomahawk-UHD630 '/storage/nvme5/new_clones/ASL/MSI-MAG-Z490-Tomahawk-UHD630' &
git clone https://github.com/brunoanc/AN515-54-Hackintosh '/storage/nvme5/new_clones/ASL/AN515-54-Hackintosh' &
git clone https://github.com/seven-of-eleven/Lenovo-ThinkPad-X1C7-OC-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-X1C7-OC-Hackintosh' &
git clone https://github.com/Corazon0513/Y9000X-2020-i9-Hackintosh '/storage/nvme5/new_clones/ASL/Y9000X-2020-i9-Hackintosh' &
git clone https://github.com/mozilla/ecosystem-platform '/storage/nvme5/new_clones/ASL/ecosystem-platform' &
git clone https://github.com/kingo132/a51m-r2-5700m-hackintosh '/storage/nvme5/new_clones/ASL/a51m-r2-5700m-hackintosh' &
git clone https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh '/storage/nvme5/new_clones/ASL/ASUS-ZenBook-Duo-14-UX481-Hackintosh' &
git clone https://github.com/jsassu20/Lenovo-T450-Catalina-OpenCore '/storage/nvme5/new_clones/ASL/Lenovo-T450-Catalina-OpenCore' &
git clone https://github.com/doanhxd/Razer-Blade-15-Advanced-2018-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-15-Advanced-2018-Hackintosh' &
git clone https://github.com/athlonreg/Thunderobot-911-Air-i7-9750h '/storage/nvme5/new_clones/ASL/Thunderobot-911-Air-i7-9750h' &
git clone https://github.com/RockJesus/Alienware-17-R4-I7-7700HQ-MacOS-High-Sierra '/storage/nvme5/new_clones/ASL/Alienware-17-R4-I7-7700HQ-MacOS-High-Sierra' &
git clone https://github.com/alirezatheh/asus-n550jk-hackintosh '/storage/nvme5/new_clones/ASL/asus-n550jk-hackintosh' &
git clone https://github.com/Lorys89/DELL_LATITUDE_7280 '/storage/nvme5/new_clones/ASL/DELL_LATITUDE_7280' &
git clone https://github.com/seven-of-eleven/Lenovo-ThinkPad-L13-Yoga-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-L13-Yoga-Hackintosh' &
git clone https://github.com/wu-hongjun/Hackintosh-Razer-Blade-RZ09-0301 '/storage/nvme5/new_clones/ASL/Hackintosh-Razer-Blade-RZ09-0301' &
git clone https://github.com/ThrRip/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML '/storage/nvme5/new_clones/ASL/OpenCore-EFI-Laptop-Lenovo-Yoga-C740-14IML' &
git clone https://github.com/t-8ch/linux-gigabyte-wmi-driver '/storage/nvme5/new_clones/ASL/linux-gigabyte-wmi-driver' &
git clone https://github.com/eenie/YogaDuet-Hackintosh-EFI-OC '/storage/nvme5/new_clones/ASL/YogaDuet-Hackintosh-EFI-OC' &
git clone https://github.com/yusufklncc/HP-EliteBook-840-G5-Hackintosh '/storage/nvme5/new_clones/ASL/HP-EliteBook-840-G5-Hackintosh' &
git clone https://github.com/jtaczanowski/ThinkPad-X201-Arrandale-macOS-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPad-X201-Arrandale-macOS-OpenCore' &
git clone https://github.com/Lorys89/ASROCK_Z490M-ITX-AC '/storage/nvme5/new_clones/ASL/ASROCK_Z490M-ITX-AC' &
git clone https://github.com/ivan19871002/Thinkpad-P15V-Gen1-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-P15V-Gen1-Hackintosh' &
git clone https://github.com/3ig/IdeaPad-S540-15IML-hackintosh '/storage/nvme5/new_clones/ASL/IdeaPad-S540-15IML-hackintosh' &
git clone https://github.com/IvanAleksandrov94/Lenovo-s340-s540-Big-Sur-OpenCore-i5-8265u '/storage/nvme5/new_clones/ASL/Lenovo-s340-s540-Big-Sur-OpenCore-i5-8265u' &
git clone https://github.com/jackhanyuan/Dell-XPS15-7590-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-XPS15-7590-Hackintosh' &
git clone https://github.com/Lorys89/DELL_VOSTRO_5401-ICE-LAKE '/storage/nvme5/new_clones/ASL/DELL_VOSTRO_5401-ICE-LAKE' &
git clone https://github.com/wy414012/OpenCore-GA-b75 '/storage/nvme5/new_clones/ASL/OpenCore-GA-b75' &
git clone https://github.com/adrianjagielak/HP-Elitebook-850-G7-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Elitebook-850-G7-Hackintosh' &
git clone https://github.com/BlackOtton/ThinkPad-X270-OpenCore-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-X270-OpenCore-Hackintosh' &
git clone https://github.com/Z39/Lenovo-Y410p-OS-X-Clover-OpenCore-Hotpatch '/storage/nvme5/new_clones/ASL/Lenovo-Y410p-OS-X-Clover-OpenCore-Hotpatch' &
git clone https://github.com/imEgo/ASRock-Z390m-ITX-ac-Hackintosh '/storage/nvme5/new_clones/ASL/ASRock-Z390m-ITX-ac-Hackintosh' &
git clone https://github.com/MlgmXyysd/FunHouse-F10-MPro-Ice-Lake-Hackintosh '/storage/nvme5/new_clones/ASL/FunHouse-F10-MPro-Ice-Lake-Hackintosh' &
git clone https://github.com/restuindrawan/Nitro-5-AN515-54-Hackintosh '/storage/nvme5/new_clones/ASL/Nitro-5-AN515-54-Hackintosh' &
git clone https://github.com/osmaniax/hackintosh '/storage/nvme5/new_clones/ASL/hackintosh' &
git clone https://github.com/rafaelmaeuer/Asus-UX32VD-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-UX32VD-Hackintosh' &
git clone https://github.com/uttufy/Xiaomi-Notebook14-Hackintosh '/storage/nvme5/new_clones/ASL/Xiaomi-Notebook14-Hackintosh' &
git clone https://github.com/ZoR3oL/t490-hackintosh '/storage/nvme5/new_clones/ASL/t490-hackintosh' &
git clone https://github.com/i0Ek3/Hackintosh_4_Hasee_Shinelon_A40L '/storage/nvme5/new_clones/ASL/Hackintosh_4_Hasee_Shinelon_A40L' &
git clone https://github.com/xuandung38/thinkpad-lenovo-t440s-hackintosh '/storage/nvme5/new_clones/ASL/thinkpad-lenovo-t440s-hackintosh' &
git clone https://github.com/yahgoo/Hackintosh-HP-840-G3-Opencore-Monterey '/storage/nvme5/new_clones/ASL/Hackintosh-HP-840-G3-Opencore-Monterey' &
git clone https://github.com/cstrouse/Dell-PowerEdge-T30-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-PowerEdge-T30-Hackintosh' &
git clone https://github.com/yulianjie/Hackintosh_Of_Lenovo_R720 '/storage/nvme5/new_clones/ASL/Hackintosh_Of_Lenovo_R720' &
git clone https://github.com/OC-KextsReddit/Surface-Pro-3-Hackintosh-OC- '/storage/nvme5/new_clones/ASL/Surface-Pro-3-Hackintosh-OC-' &
git clone https://github.com/dhbxs/ThinkPad-T480-OpenCore-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-T480-OpenCore-Hackintosh' &
git clone https://github.com/BenDevelopment/MacOS-XPS-9500-2020-OpenCore '/storage/nvme5/new_clones/ASL/MacOS-XPS-9500-2020-OpenCore' &
git clone https://github.com/baranovskis/xps9570-hackintosh '/storage/nvme5/new_clones/ASL/xps9570-hackintosh' &
git clone https://github.com/laggykiller/Hackintosh_MSI_B660M-A_WIFI_DDR4 '/storage/nvme5/new_clones/ASL/Hackintosh_MSI_B660M-A_WIFI_DDR4' &
git clone https://github.com/digital-land/digital-land '/storage/nvme5/new_clones/ASL/digital-land' &
git clone https://github.com/jamieernest/Dell-Inspiron-7501-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Inspiron-7501-Hackintosh' &
git clone https://github.com/dimka4996/Thinkpad-x250-Catalina-Big-sur-opencore '/storage/nvme5/new_clones/ASL/Thinkpad-x250-Catalina-Big-sur-opencore' &
git clone https://github.com/koluris/HP-ENVY-13-AH0002-OpenCore '/storage/nvme5/new_clones/ASL/HP-ENVY-13-AH0002-OpenCore' &
git clone https://github.com/ferxiit/Y520-15IKBN-OpenCore '/storage/nvme5/new_clones/ASL/Y520-15IKBN-OpenCore' &
git clone https://github.com/nickw444/opencore-efi-z77 '/storage/nvme5/new_clones/ASL/opencore-efi-z77' &
git clone https://github.com/luchina-gabriel/EFI-GIGABYTE-X570-AORUS-MASTER-5950X-RX-580 '/storage/nvme5/new_clones/ASL/EFI-GIGABYTE-X570-AORUS-MASTER-5950X-RX-580' &
git clone https://github.com/AndresGarciaSobrado91/MSI-Modern15-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-Modern15-Hackintosh' &
git clone https://github.com/dandepeched/Hackintosh-ThinkPad-E580 '/storage/nvme5/new_clones/ASL/Hackintosh-ThinkPad-E580' &
git clone https://github.com/kreizlie/HP-ProBook-430-G5-Hackintosh '/storage/nvme5/new_clones/ASL/HP-ProBook-430-G5-Hackintosh' &
git clone https://github.com/kushwavez/lenovo-x1c6-clover-efi '/storage/nvme5/new_clones/ASL/lenovo-x1c6-clover-efi' &
git clone https://github.com/ErrorErrorError/msi-gs65-8se-opencore-macos '/storage/nvme5/new_clones/ASL/msi-gs65-8se-opencore-macos' &
git clone https://github.com/tamht298/Hackintosh-OpenCore-EFI-Dell-Inspiron-5559 '/storage/nvme5/new_clones/ASL/Hackintosh-OpenCore-EFI-Dell-Inspiron-5559' &
git clone https://github.com/isoulgh/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore '/storage/nvme5/new_clones/ASL/isoul-Hackintosh-EFI-Dell-G3-3579-OpenCore' &
git clone https://github.com/alexanderkin/ASUS-FL8000UQ-Hackintosh '/storage/nvme5/new_clones/ASL/ASUS-FL8000UQ-Hackintosh' &
git clone https://github.com/PurpleCrumpets/Hackintosh-Dell-Latitude-7390-2-in-1-OpenCore-EFI '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-Latitude-7390-2-in-1-OpenCore-EFI' &
git clone https://github.com/mackonsti/nuc8i7beh '/storage/nvme5/new_clones/ASL/nuc8i7beh' &
git clone https://github.com/IlhamSevensky/ASUS-X556UQ-HACKINTOSH-OPENCORE '/storage/nvme5/new_clones/ASL/ASUS-X556UQ-HACKINTOSH-OPENCORE' &
git clone https://github.com/SilentSliver/HP-ENVY-13-ad1XX-Hackintosh '/storage/nvme5/new_clones/ASL/HP-ENVY-13-ad1XX-Hackintosh' &
git clone https://github.com/littlesum/nuc9hacktosh-config '/storage/nvme5/new_clones/ASL/nuc9hacktosh-config' &
git clone https://github.com/hexart/T480-OpenCore-Hackintosh '/storage/nvme5/new_clones/ASL/T480-OpenCore-Hackintosh' &
git clone https://github.com/e-senturk/G531GD-GT-GU-Hackintosh '/storage/nvme5/new_clones/ASL/G531GD-GT-GU-Hackintosh' &
git clone https://github.com/pdff/Hackintosh-HP-Elitebook840G7 '/storage/nvme5/new_clones/ASL/Hackintosh-HP-Elitebook840G7' &
git clone https://github.com/nguyenhung9x2020/HP-PROBOOK-4540S-HACKINTOSH '/storage/nvme5/new_clones/ASL/HP-PROBOOK-4540S-HACKINTOSH' &
git clone https://github.com/korzhyk/OpenCore_GA-H97M-D3H '/storage/nvme5/new_clones/ASL/OpenCore_GA-H97M-D3H' &
git clone https://github.com/robotblox/XPS-15-9500-Catalina-10.15.6 '/storage/nvme5/new_clones/ASL/XPS-15-9500-Catalina-10.15.6' &
git clone https://github.com/lunjielee/Opencore-HP-Omen-15-2020 '/storage/nvme5/new_clones/ASL/Opencore-HP-Omen-15-2020' &
git clone https://github.com/ocd0711/MacOS-XPS-9700-OpenCore '/storage/nvme5/new_clones/ASL/MacOS-XPS-9700-OpenCore' &
git clone https://github.com/hrytskivr/rba-hackintosh '/storage/nvme5/new_clones/ASL/rba-hackintosh' &
git clone https://github.com/juanpy0223/Dell-Latitude-5490-8th-gen '/storage/nvme5/new_clones/ASL/Dell-Latitude-5490-8th-gen' &
git clone https://github.com/nurdiny13/LENOVO-IDEAPAD-GAMING-3i-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/LENOVO-IDEAPAD-GAMING-3i-Hackintosh-Opencore' &
git clone https://github.com/alex-spataru/HP-Spectre-4101dx-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Spectre-4101dx-Hackintosh' &
git clone https://github.com/kreactnative/Z690-12900K-RX6600XT-DDR5-Monterey '/storage/nvme5/new_clones/ASL/Z690-12900K-RX6600XT-DDR5-Monterey' &
git clone https://github.com/itsabhishekolkha/Mi-notebook-14-Hackintosh '/storage/nvme5/new_clones/ASL/Mi-notebook-14-Hackintosh' &
git clone https://github.com/HeartAndSoul001/my-EFI-for-x1-carbon-5th '/storage/nvme5/new_clones/ASL/my-EFI-for-x1-carbon-5th' &
git clone https://github.com/aleixsr/MSI-Prestige-15-A10SC-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-Prestige-15-A10SC-Hackintosh' &
git clone https://github.com/hibobmaster/HP-15-dc1010nr-hackintosh '/storage/nvme5/new_clones/ASL/HP-15-dc1010nr-hackintosh' &
git clone https://github.com/jkcoxson/Inspiron-3583-Hackintosh '/storage/nvme5/new_clones/ASL/Inspiron-3583-Hackintosh' &
git clone https://github.com/Caipe97/Hackintosh-Thinkpad-L14-Gen-1 '/storage/nvme5/new_clones/ASL/Hackintosh-Thinkpad-L14-Gen-1' &
git clone https://github.com/naveenkrdy/Misc '/storage/nvme5/new_clones/ASL/Misc' &
git clone https://github.com/1orz/y7000p-2020H-macOS-EFI '/storage/nvme5/new_clones/ASL/y7000p-2020H-macOS-EFI' &
git clone https://github.com/steelbrain/razer-blade-17-pro-2020-hackintosh '/storage/nvme5/new_clones/ASL/razer-blade-17-pro-2020-hackintosh' &
git clone https://github.com/mistzzt/XPS-9560-OpenCore '/storage/nvme5/new_clones/ASL/XPS-9560-OpenCore' &
git clone https://github.com/antoniomcr96/Thinkpad-L390-Yoga-macOS-Opencore '/storage/nvme5/new_clones/ASL/Thinkpad-L390-Yoga-macOS-Opencore' &
git clone https://github.com/valnoxy/t420-oc '/storage/nvme5/new_clones/ASL/t420-oc' &
git clone https://github.com/kreizlie/Lenovo-Yoga-260-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-Yoga-260-Hackintosh' &
git clone https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Dell-G3-3579-3779-Hackintosh-OpenCore' &
git clone https://github.com/lzjqsdd/Thinkpad-X1C4-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-X1C4-Hackintosh' &
git clone https://github.com/charlesSheep/-gs65-opencore-eif '/storage/nvme5/new_clones/ASL/-gs65-opencore-eif' &
git clone https://github.com/TiToMoskito/Razer-Blade-Base-2020-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-Base-2020-Hackintosh' &
git clone https://github.com/Bhavinjain260/Hackintosh-dell-inspiron-5559 '/storage/nvme5/new_clones/ASL/Hackintosh-dell-inspiron-5559' &
git clone https://github.com/celerond256/X260-Opencore-Hackintosh '/storage/nvme5/new_clones/ASL/X260-Opencore-Hackintosh' &
git clone https://github.com/Baio1977/Dell-Inspiron-5584 '/storage/nvme5/new_clones/ASL/Dell-Inspiron-5584' &
git clone https://github.com/EigenTom/ThinkPad-X1-Yoga-3rd-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-X1-Yoga-3rd-Hackintosh' &
git clone https://github.com/guitaoliu/MSI-GS63VR-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-GS63VR-Hackintosh' &
git clone https://github.com/Levonhard/X515JA-Hackintosh '/storage/nvme5/new_clones/ASL/X515JA-Hackintosh' &
git clone https://github.com/yifan-gu/hackintosh '/storage/nvme5/new_clones/ASL/hackintosh' &
git clone https://github.com/latin-1/um5302ta '/storage/nvme5/new_clones/ASL/um5302ta' &
git clone https://github.com/VictorxD70/Hackintosh-OC-Dell-Inspiron-15-3567 '/storage/nvme5/new_clones/ASL/Hackintosh-OC-Dell-Inspiron-15-3567' &
git clone https://github.com/findyy99/ThinkPad-T450S-Hackintosh-macOS-Big-Sur '/storage/nvme5/new_clones/ASL/ThinkPad-T450S-Hackintosh-macOS-Big-Sur' &
git clone https://github.com/ashishpatel1992/Dell-Inspiron-3521-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Dell-Inspiron-3521-Hackintosh-OpenCore' &
git clone https://github.com/CerteKim/Dell-G3-3579-Hackintosh-Clover '/storage/nvme5/new_clones/ASL/Dell-G3-3579-Hackintosh-Clover' &
git clone https://github.com/itsmeshibintmz/Acer-Nitro-5-AN515-54-Monterey '/storage/nvme5/new_clones/ASL/Acer-Nitro-5-AN515-54-Monterey' &
git clone https://github.com/ijonglin/teclast-f5-ubuntu-finalizer '/storage/nvme5/new_clones/ASL/teclast-f5-ubuntu-finalizer' &
git clone https://github.com/moqsien/hackintosh_p310s_b360_i5_10400f_rx550_lexa '/storage/nvme5/new_clones/ASL/hackintosh_p310s_b360_i5_10400f_rx550_lexa' &
git clone https://github.com/VanXNF/Hackintosh-Acer-Swift3-SF313-52 '/storage/nvme5/new_clones/ASL/Hackintosh-Acer-Swift3-SF313-52' &
git clone https://github.com/TranNgocKhoa/Dell-Latitude-7480-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Latitude-7480-Hackintosh' &
git clone https://github.com/adeelpm/Acer-Aspire-A515-54G-CPU-i5-8265u '/storage/nvme5/new_clones/ASL/Acer-Aspire-A515-54G-CPU-i5-8265u' &
git clone https://github.com/XXCoreRangerX/Hackintosh-HP-EliteBook-840-G4 '/storage/nvme5/new_clones/ASL/Hackintosh-HP-EliteBook-840-G4' &
git clone https://github.com/DeekshithSN/Jenkins '/storage/nvme5/new_clones/ASL/Jenkins' &
git clone https://github.com/stonexing/Asus-S4000VA8550-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-S4000VA8550-Hackintosh' &
git clone https://github.com/L0ngxhn/Hackintosh-Hasee-T96E '/storage/nvme5/new_clones/ASL/Hackintosh-Hasee-T96E' &
git clone https://github.com/qianbinbin/hackintosh-m73-tiny '/storage/nvme5/new_clones/ASL/hackintosh-m73-tiny' &
git clone https://github.com/ppjjhh/Hackintosh-Dell-Inspiron-7580 '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-Inspiron-7580' &
git clone https://github.com/nabaonan/airbook-6200u-efi '/storage/nvme5/new_clones/ASL/airbook-6200u-efi' &
git clone https://github.com/anullog/HP-ProBook-450-G3-Hackintosh '/storage/nvme5/new_clones/ASL/HP-ProBook-450-G3-Hackintosh' &
git clone https://github.com/jamieernest/Lenovo-ThinkPad-E490-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-E490-Hackintosh' &
git clone https://github.com/DtHnAme/Dell-Latitude-5290-2-in-1-Opencore '/storage/nvme5/new_clones/ASL/Dell-Latitude-5290-2-in-1-Opencore' &
git clone https://github.com/Cheers0606/XIAOMI_AIR-13.3_EFI '/storage/nvme5/new_clones/ASL/XIAOMI_AIR-13.3_EFI' &
git clone https://github.com/DagerDW/Lenovo-ideapad-3-14iil05-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ideapad-3-14iil05-Hackintosh' &
git clone https://github.com/nguyenphucdev/OpenCore_X79_X99_Xeon_E5_2650v2 '/storage/nvme5/new_clones/ASL/OpenCore_X79_X99_Xeon_E5_2650v2' &
git clone https://github.com/jianyun8023/MSI-MAG-B560M-i5-11500 '/storage/nvme5/new_clones/ASL/MSI-MAG-B560M-i5-11500' &
git clone https://github.com/goofysun/y9000x-4k-macos '/storage/nvme5/new_clones/ASL/y9000x-4k-macos' &
git clone https://github.com/smart-village-solutions/smart-village-app '/storage/nvme5/new_clones/ASL/smart-village-app' &
git clone https://github.com/Zhongli0401/OC_macOScomet_lake '/storage/nvme5/new_clones/ASL/OC_macOScomet_lake' &
git clone https://github.com/nidemimihihi/Dell5557-I5-6200U-bigsur-Monterey-OC '/storage/nvme5/new_clones/ASL/Dell5557-I5-6200U-bigsur-Monterey-OC' &
git clone https://github.com/flyfeng2002/FYQ-Hackintosh '/storage/nvme5/new_clones/ASL/FYQ-Hackintosh' &
git clone https://github.com/ananjaser1211/Opencore-HP-Pavilion-Gaming-15-cx0056wm '/storage/nvme5/new_clones/ASL/Opencore-HP-Pavilion-Gaming-15-cx0056wm' &
git clone https://github.com/fjh1997/HP_Probook_440_G6_hackintosh '/storage/nvme5/new_clones/ASL/HP_Probook_440_G6_hackintosh' &
git clone https://github.com/queensferryme/Hackintosh-Dell-7580 '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-7580' &
git clone https://github.com/Sniki/Lenovo-Thinkpad-T440 '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-T440' &
git clone https://github.com/oscarsanchezdm/hackintoshXPS9350 '/storage/nvme5/new_clones/ASL/hackintoshXPS9350' &
git clone https://github.com/stutter0718/ASUS-TUF-B360M-OC '/storage/nvme5/new_clones/ASL/ASUS-TUF-B360M-OC' &
git clone https://github.com/Dream471/ASUS-X550VC-Hackintosh '/storage/nvme5/new_clones/ASL/ASUS-X550VC-Hackintosh' &
git clone https://github.com/ravnized/XiaoMi-Pro-Enhanced-Hackintosh '/storage/nvme5/new_clones/ASL/XiaoMi-Pro-Enhanced-Hackintosh' &
git clone https://github.com/hla63/Msi-modern-15-Hackintosh '/storage/nvme5/new_clones/ASL/Msi-modern-15-Hackintosh' &
git clone https://github.com/p455555555/Thinkpad-P1-EFI '/storage/nvme5/new_clones/ASL/Thinkpad-P1-EFI' &
git clone https://github.com/dz-ps/Hackintosh-Dell-G15-5510 '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-G15-5510' &
git clone https://github.com/waldoxhm/Panasonic_CF-SZ5_SZ5PDYVS_hackintosh_EFI '/storage/nvme5/new_clones/ASL/Panasonic_CF-SZ5_SZ5PDYVS_hackintosh_EFI' &
git clone https://github.com/aamirswati/LenovoThinkbook15-IML-Hackintosh '/storage/nvme5/new_clones/ASL/LenovoThinkbook15-IML-Hackintosh' &
git clone https://github.com/Necromancer2Point0/MSI-GS66-OC-New-Dawn '/storage/nvme5/new_clones/ASL/MSI-GS66-OC-New-Dawn' &
git clone https://github.com/b4iterdev/opencore-dell-inspriron-14-3467 '/storage/nvme5/new_clones/ASL/opencore-dell-inspriron-14-3467' &
git clone https://github.com/crystall1nedev/Inspiron-N5110-SNDB-Hackintosh '/storage/nvme5/new_clones/ASL/Inspiron-N5110-SNDB-Hackintosh' &
git clone https://github.com/Joaotcs/Hackintosh-Elitebook-8x0-g5 '/storage/nvme5/new_clones/ASL/Hackintosh-Elitebook-8x0-g5' &
git clone https://github.com/trandtung1209/X1C3-T450s-T450-X250-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/X1C3-T450s-T450-X250-Hackintosh-Opencore' &
git clone https://github.com/luchina-gabriel/EFI-GIGABYTE-Z590M-GAMING-X-11900K-ES-QV1K-RX6900XT '/storage/nvme5/new_clones/ASL/EFI-GIGABYTE-Z590M-GAMING-X-11900K-ES-QV1K-RX6900XT' &
git clone https://github.com/maxis7567/Hackintosh-Dell-7567-OpenCore_Big-Sur '/storage/nvme5/new_clones/ASL/Hackintosh-Dell-7567-OpenCore_Big-Sur' &
git clone https://github.com/dongcodebmt/VX5-591G-OpenCore '/storage/nvme5/new_clones/ASL/VX5-591G-OpenCore' &
git clone https://github.com/luoei/hackintosh-opencore-efi-for-huawei-matebook-14-2020 '/storage/nvme5/new_clones/ASL/hackintosh-opencore-efi-for-huawei-matebook-14-2020' &
git clone https://github.com/Vejtarn/Hackintosh-Asus-X555LJ-BigSur '/storage/nvme5/new_clones/ASL/Hackintosh-Asus-X555LJ-BigSur' &
git clone https://github.com/luchina-gabriel/EFI-NOTEBOOK-DELL-5490-i7-10510U-iGPU '/storage/nvme5/new_clones/ASL/EFI-NOTEBOOK-DELL-5490-i7-10510U-iGPU' &
git clone https://github.com/szguomy/hackintosh '/storage/nvme5/new_clones/ASL/hackintosh' &
git clone https://github.com/andrewlsa/Matebook14-2019-Hackintosh '/storage/nvme5/new_clones/ASL/Matebook14-2019-Hackintosh' &
git clone https://github.com/swlfigo/HackintoshEFI '/storage/nvme5/new_clones/ASL/HackintoshEFI' &
git clone https://github.com/yhl452493373/ASROCK-X570-Taichi-6800XT '/storage/nvme5/new_clones/ASL/ASROCK-X570-Taichi-6800XT' &
git clone https://github.com/FuckDoctors/ideapad-720s-13ikb-oc '/storage/nvme5/new_clones/ASL/ideapad-720s-13ikb-oc' &
git clone https://github.com/marianopela/Lenovo-Ideapad-S540-14IML-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-Ideapad-S540-14IML-Hackintosh' &
git clone https://github.com/aspadeto/Inspiron-14-5480_MacOS '/storage/nvme5/new_clones/ASL/Inspiron-14-5480_MacOS' &
git clone https://github.com/LucasDondo/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE '/storage/nvme5/new_clones/ASL/Hackintosh-Lenovo-IdeaPad-330-15IKB-81DE' &
git clone https://github.com/private-static/X1C6-OpenCore-EFI '/storage/nvme5/new_clones/ASL/X1C6-OpenCore-EFI' &
git clone https://github.com/Rameshei87/jenkinsPipeline '/storage/nvme5/new_clones/ASL/jenkinsPipeline' &
git clone https://github.com/Jarvay/Acer-Swift3-SF313-52 '/storage/nvme5/new_clones/ASL/Acer-Swift3-SF313-52' &
git clone https://github.com/tonyu124/DELL-XPS-13-9370-Hackintosh '/storage/nvme5/new_clones/ASL/DELL-XPS-13-9370-Hackintosh' &
git clone https://github.com/Forever331/Dell_G5_5500_Hackintosh_OpenCore '/storage/nvme5/new_clones/ASL/Dell_G5_5500_Hackintosh_OpenCore' &
git clone https://github.com/Howardnm/HP-OMEN-3-Hackintosh-Bigsur-Monterey '/storage/nvme5/new_clones/ASL/HP-OMEN-3-Hackintosh-Bigsur-Monterey' &
git clone https://github.com/DeTeKe/HP800G1DM_Hackintosh '/storage/nvme5/new_clones/ASL/HP800G1DM_Hackintosh' &
git clone https://github.com/mackonsti/d54250wykh '/storage/nvme5/new_clones/ASL/d54250wykh' &
git clone https://github.com/lohseng97/Dell-Latitude-7490-EFI-macOS-BigSur '/storage/nvme5/new_clones/ASL/Dell-Latitude-7490-EFI-macOS-BigSur' &
git clone https://github.com/liaojack8/ASUS-Z390F-Hack '/storage/nvme5/new_clones/ASL/ASUS-Z390F-Hack' &
git clone https://github.com/stryses/Mi-Laptop-Air12.5-8100Y-Hackintosh '/storage/nvme5/new_clones/ASL/Mi-Laptop-Air12.5-8100Y-Hackintosh' &
git clone https://github.com/qilskcter/Dell-Vostro-3460-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Vostro-3460-Hackintosh' &
git clone https://github.com/westeri/meta-acpi '/storage/nvme5/new_clones/ASL/meta-acpi' &
git clone https://github.com/ericpuwang/lenovo-xiaoxinchao7000-14ikbr-efi '/storage/nvme5/new_clones/ASL/lenovo-xiaoxinchao7000-14ikbr-efi' &
git clone https://github.com/amogh-w/Hackintosh-MSI-GV62-7RE '/storage/nvme5/new_clones/ASL/Hackintosh-MSI-GV62-7RE' &
git clone https://github.com/Baio1977/Acer-Aspire-A515-54g-CPU-10xxx '/storage/nvme5/new_clones/ASL/Acer-Aspire-A515-54g-CPU-10xxx' &
git clone https://github.com/jennie26/Lenovo-Miix-720-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-Miix-720-Hackintosh' &
git clone https://github.com/664235822/EFI-OpenCore-ASUS-ROG-Strix-Hero2 '/storage/nvme5/new_clones/ASL/EFI-OpenCore-ASUS-ROG-Strix-Hero2' &
git clone https://github.com/jiangwweie/ROG-B360I-EFI '/storage/nvme5/new_clones/ASL/ROG-B360I-EFI' &
git clone https://github.com/hadymic/Y9000X-Hackintosh '/storage/nvme5/new_clones/ASL/Y9000X-Hackintosh' &
git clone https://github.com/AbhaySingh15/Acer-aspire-7-A715-75G-Opencore-EFI '/storage/nvme5/new_clones/ASL/Acer-aspire-7-A715-75G-Opencore-EFI' &
git clone https://github.com/kekkokk/t480s_hackintosh_opencore '/storage/nvme5/new_clones/ASL/t480s_hackintosh_opencore' &
git clone https://github.com/cjtim/SF314-55G-hackintosh '/storage/nvme5/new_clones/ASL/SF314-55G-hackintosh' &
git clone https://github.com/AlbinoGiraffe/Latitude-7390-Hackintosh '/storage/nvme5/new_clones/ASL/Latitude-7390-Hackintosh' &
git clone https://github.com/teddytaod/macos-catalina-thinkpad-x250 '/storage/nvme5/new_clones/ASL/macos-catalina-thinkpad-x250' &
git clone https://github.com/Bluestar-coder/Hases-z7-kp7sc-10.15.4-OC '/storage/nvme5/new_clones/ASL/Hases-z7-kp7sc-10.15.4-OC' &
git clone https://github.com/mahronid/thinkpad-e480-hackintosh '/storage/nvme5/new_clones/ASL/thinkpad-e480-hackintosh' &
git clone https://github.com/KrolSeb/HP-Pavilion-Gaming-15-dk00xxxx-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/HP-Pavilion-Gaming-15-dk00xxxx-Hackintosh-OpenCore' &
git clone https://github.com/Lorys89/DELL_OPTIPLEX_9020_USFF '/storage/nvme5/new_clones/ASL/DELL_OPTIPLEX_9020_USFF' &
git clone https://github.com/VGerris/asus-tuf-15-opencore '/storage/nvme5/new_clones/ASL/asus-tuf-15-opencore' &
git clone https://github.com/Edwardwich/hp-DA1023nia-macOS '/storage/nvme5/new_clones/ASL/hp-DA1023nia-macOS' &
git clone https://github.com/afzl-wtu/Dell-E6440-Opencore-EFI '/storage/nvme5/new_clones/ASL/Dell-E6440-Opencore-EFI' &
git clone https://github.com/FlopRe/hackintosh-Z390-gigabyte-aorus-pro-wifi-OpenCore-9600K-iGPU '/storage/nvme5/new_clones/ASL/hackintosh-Z390-gigabyte-aorus-pro-wifi-OpenCore-9600K-iGPU' &
git clone https://github.com/brightkan/HP-ProBook-450-G5-Hackintosh-EFI '/storage/nvme5/new_clones/ASL/HP-ProBook-450-G5-Hackintosh-EFI' &
git clone https://github.com/aidmax/structurizr-cli-docker '/storage/nvme5/new_clones/ASL/structurizr-cli-docker' &
git clone https://github.com/NOTNlCE/Latitude-E5470-OpenCore '/storage/nvme5/new_clones/ASL/Latitude-E5470-OpenCore' &
git clone https://github.com/aidmax/structurizr-cli-action '/storage/nvme5/new_clones/ASL/structurizr-cli-action' &
git clone https://github.com/newham/yoga710-7500u-oc-bigsur '/storage/nvme5/new_clones/ASL/yoga710-7500u-oc-bigsur' &
git clone https://github.com/vinaypundith/bettercamp '/storage/nvme5/new_clones/ASL/bettercamp' &
git clone https://github.com/rjm521/asus-fl5900u-hackintosh-oc '/storage/nvme5/new_clones/ASL/asus-fl5900u-hackintosh-oc' &
git clone https://github.com/b00t0x/GPD-WIN-Max-Hackintosh '/storage/nvme5/new_clones/ASL/GPD-WIN-Max-Hackintosh' &
git clone https://github.com/yaza-putu/lenovo-thinkpad-l430 '/storage/nvme5/new_clones/ASL/lenovo-thinkpad-l430' &
git clone https://github.com/1Revenger1/Dell-M4700-MacOS-Resources '/storage/nvme5/new_clones/ASL/Dell-M4700-MacOS-Resources' &
git clone https://github.com/vantuan88291/clover-xps13-9343 '/storage/nvme5/new_clones/ASL/clover-xps13-9343' &
git clone https://github.com/jigarpatel7600/Acer-Nitro5 '/storage/nvme5/new_clones/ASL/Acer-Nitro5' &
git clone https://github.com/shammu2bd/Asus-X540LJ-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Asus-X540LJ-Hackintosh-OpenCore' &
git clone https://github.com/yahgoo/Hackintosh-HP-840-G3-Opencore-Ventura '/storage/nvme5/new_clones/ASL/Hackintosh-HP-840-G3-Opencore-Ventura' &
git clone https://github.com/wjz304/Hackintosh-EFI-Lenovo-Yoga-910-13IKB '/storage/nvme5/new_clones/ASL/Hackintosh-EFI-Lenovo-Yoga-910-13IKB' &
git clone https://github.com/DimitriDokuchaev/hackintosh-xps-9360 '/storage/nvme5/new_clones/ASL/hackintosh-xps-9360' &
git clone https://github.com/haoyaxuan/Hasee-K550d-i7d1-hackintosh '/storage/nvme5/new_clones/ASL/Hasee-K550d-i7d1-hackintosh' &
git clone https://github.com/Xoloth/Dell-G3-3500-Opencore-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-G3-3500-Opencore-Hackintosh' &
git clone https://github.com/hansyao/Hackintosh_Monterey_M4800 '/storage/nvme5/new_clones/ASL/Hackintosh_Monterey_M4800' &
git clone https://github.com/MuntashirAkon/HackintoshDellInspiron5567 '/storage/nvme5/new_clones/ASL/HackintoshDellInspiron5567' &
git clone https://github.com/GuaiYiHu/Hackintosh '/storage/nvme5/new_clones/ASL/Hackintosh' &
git clone https://github.com/YYYHeart/Nitro-5-AN515-55-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/Nitro-5-AN515-55-Hackintosh-Opencore' &
git clone https://github.com/luchina-gabriel/EFI-GIGABYTE-Z490M-GAMING-X-10700K-iGPU '/storage/nvme5/new_clones/ASL/EFI-GIGABYTE-Z490M-GAMING-X-10700K-iGPU' &
git clone https://github.com/jqqqqqqqqqq/Hackintosh-HP-Z2-Mini-G4 '/storage/nvme5/new_clones/ASL/Hackintosh-HP-Z2-Mini-G4' &
git clone https://github.com/HEROhuqinchao/HP-ENVY-X360-15-BP103TX-OC '/storage/nvme5/new_clones/ASL/HP-ENVY-X360-15-BP103TX-OC' &
git clone https://github.com/mcjimsr/thinkpad-x1-carbon-5th-gen-hackintosh '/storage/nvme5/new_clones/ASL/thinkpad-x1-carbon-5th-gen-hackintosh' &
git clone https://github.com/Doublevil/scbspeedrun '/storage/nvme5/new_clones/ASL/scbspeedrun' &
git clone https://github.com/lehuutrung1412/Hackintosh-HP-Laptop '/storage/nvme5/new_clones/ASL/Hackintosh-HP-Laptop' &
git clone https://github.com/XJ814/G3_3579_OC '/storage/nvme5/new_clones/ASL/G3_3579_OC' &
git clone https://github.com/0nTheGoRepairs/Thinkpad-T450s-Opencore-0.8-English-Intel-WIFI-Monterey-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-T450s-Opencore-0.8-English-Intel-WIFI-Monterey-Hackintosh' &
git clone https://github.com/felipebarcelospro/Acer-Nitro-5-Hackintosh-Monterey '/storage/nvme5/new_clones/ASL/Acer-Nitro-5-Hackintosh-Monterey' &
git clone https://github.com/tspng/gigabyte-z390-m-gaming-opencore '/storage/nvme5/new_clones/ASL/gigabyte-z390-m-gaming-opencore' &
git clone https://github.com/shuntan/Dell-Precision-5550-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Precision-5550-Hackintosh' &
git clone https://github.com/Ronein/HP-ZHAN-66-Pro-14-G3-OC-EFI '/storage/nvme5/new_clones/ASL/HP-ZHAN-66-Pro-14-G3-OC-EFI' &
git clone https://github.com/ouija/android-x86-toshiba_encore2 '/storage/nvme5/new_clones/ASL/android-x86-toshiba_encore2' &
git clone https://github.com/TingyiChen/Dell-Latitude-7390-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Latitude-7390-Hackintosh' &
git clone https://github.com/5-Super-Rookie-5/edk2-Pixel3 '/storage/nvme5/new_clones/ASL/edk2-Pixel3' &
git clone https://github.com/diyanqi/Lenovo-Xiaoxin-Air14-2019-IWL-Hackintosh-EFI '/storage/nvme5/new_clones/ASL/Lenovo-Xiaoxin-Air14-2019-IWL-Hackintosh-EFI' &
git clone https://github.com/mechtifs/hackintosh-hp-15-cx0 '/storage/nvme5/new_clones/ASL/hackintosh-hp-15-cx0' &
git clone https://github.com/lighterEB/ThinkPad-T440p '/storage/nvme5/new_clones/ASL/ThinkPad-T440p' &
git clone https://github.com/Not-a-true-statement/Hackintosh-OC-XPS-13-9300 '/storage/nvme5/new_clones/ASL/Hackintosh-OC-XPS-13-9300' &
git clone https://github.com/CalvinXu17/OpenCore-Dell-G3-3579-1060mq '/storage/nvme5/new_clones/ASL/OpenCore-Dell-G3-3579-1060mq' &
git clone https://github.com/huburtx/Dell-Latitude-3490-hackintosh-Open-Core '/storage/nvme5/new_clones/ASL/Dell-Latitude-3490-hackintosh-Open-Core' &
git clone https://github.com/Allanrfox/ThinkPad-X1-Carbon-5th-gen-Hackintosh '/storage/nvme5/new_clones/ASL/ThinkPad-X1-Carbon-5th-gen-Hackintosh' &
git clone https://github.com/quangvinhdam/Monterey-On-Dell-Inspiron-3567 '/storage/nvme5/new_clones/ASL/Monterey-On-Dell-Inspiron-3567' &
git clone https://github.com/FREEWING-JP/OpenCore-Ventura-AMD-Ryzen-4750G-Lenovo-M75s-Small-Gen2 '/storage/nvme5/new_clones/ASL/OpenCore-Ventura-AMD-Ryzen-4750G-Lenovo-M75s-Small-Gen2' &
git clone https://github.com/baumph/Surface-Book-1-Hackintosh '/storage/nvme5/new_clones/ASL/Surface-Book-1-Hackintosh' &
git clone https://github.com/wei756/NT950XCR-G58A-Hackintosh '/storage/nvme5/new_clones/ASL/NT950XCR-G58A-Hackintosh' &
git clone https://github.com/dursonATWIT/Razer-Blade-15-advanced-2020-hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Razer-Blade-15-advanced-2020-hackintosh-OpenCore' &
git clone https://github.com/Iwantwater1116/EFI_Hackintosh_ASUS_VivoBook_Pro_15_N580GD_OC7.3 '/storage/nvme5/new_clones/ASL/EFI_Hackintosh_ASUS_VivoBook_Pro_15_N580GD_OC7.3' &
git clone https://github.com/shuai132/ThinkPad-X13-EFI '/storage/nvme5/new_clones/ASL/ThinkPad-X13-EFI' &
git clone https://github.com/khronokernel/HP-Elite-X2-G1-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Elite-X2-G1-Hackintosh' &
git clone https://github.com/IamCarron/Lenovo-Ideapad-700-15isk-Hackintosh-Monterey '/storage/nvme5/new_clones/ASL/Lenovo-Ideapad-700-15isk-Hackintosh-Monterey' &
git clone https://github.com/marianopela/MSI-GS66-Stealth-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-GS66-Stealth-Hackintosh' &
git clone https://github.com/nidemimihihi/Acer-Swift3-SF313-52-Monterey-Ventura '/storage/nvme5/new_clones/ASL/Acer-Swift3-SF313-52-Monterey-Ventura' &
git clone https://github.com/devdahyuk/LGGram-Z990-Hackintosh '/storage/nvme5/new_clones/ASL/LGGram-Z990-Hackintosh' &
git clone https://github.com/norton287/Gigabyte-Z370-HD3P '/storage/nvme5/new_clones/ASL/Gigabyte-Z370-HD3P' &
git clone https://github.com/uditkarode/XPS9570-Hackintosh '/storage/nvme5/new_clones/ASL/XPS9570-Hackintosh' &
git clone https://github.com/ad1tyx666/ASUS-TUF-F15-OPENCORE '/storage/nvme5/new_clones/ASL/ASUS-TUF-F15-OPENCORE' &
git clone https://github.com/osx86-ijb/Dell-Latitude-e5430-3rd-Gen-Core-i5-3210m-macOS-BigSur '/storage/nvme5/new_clones/ASL/Dell-Latitude-e5430-3rd-Gen-Core-i5-3210m-macOS-BigSur' &
git clone https://github.com/djmanri3/OpenCoreBigSur_Microsoft_Surface_Go_3 '/storage/nvme5/new_clones/ASL/OpenCoreBigSur_Microsoft_Surface_Go_3' &
git clone https://github.com/Smuger12/Hackintosh_Dell_Latitude_E7470 '/storage/nvme5/new_clones/ASL/Hackintosh_Dell_Latitude_E7470' &
git clone https://github.com/JoK3rLeE/Asus-S510UQ-BQ178T '/storage/nvme5/new_clones/ASL/Asus-S510UQ-BQ178T' &
git clone https://github.com/xiaoshimu/macos-opencore-hp-zhan66-pro15-g3-i7-10510u '/storage/nvme5/new_clones/ASL/macos-opencore-hp-zhan66-pro15-g3-i7-10510u' &
git clone https://github.com/danceking/EliteBook-830-G5-OpenCore '/storage/nvme5/new_clones/ASL/EliteBook-830-G5-OpenCore' &
git clone https://github.com/zncs520/GPD-P2-MAX-Hackintosh '/storage/nvme5/new_clones/ASL/GPD-P2-MAX-Hackintosh' &
git clone https://github.com/1nferious/Dell-XPS-15-7590-MacOS-Monterey--12.0.1--Hackintosh '/storage/nvme5/new_clones/ASL/Dell-XPS-15-7590-MacOS-Monterey--12.0.1--Hackintosh' &
git clone https://github.com/t0mmas0/T470-Hackintosh-OC-Monterey-7300u '/storage/nvme5/new_clones/ASL/T470-Hackintosh-OC-Monterey-7300u' &
git clone https://github.com/rynaardb/hackintosh-strix-z490i '/storage/nvme5/new_clones/ASL/hackintosh-strix-z490i' &
git clone https://github.com/Atrewin/PGen '/storage/nvme5/new_clones/ASL/PGen' &
git clone https://github.com/Kouseu/hackintosh-Lenovo-Yoga-C940 '/storage/nvme5/new_clones/ASL/hackintosh-Lenovo-Yoga-C940' &
git clone https://github.com/stevedat/HP-Elitebook-830-G6-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Elitebook-830-G6-Hackintosh' &
git clone https://github.com/EdisonGates/VN7-591G-56BD-Hackintosh '/storage/nvme5/new_clones/ASL/VN7-591G-56BD-Hackintosh' &
git clone https://github.com/JosephDuffy/aorus-pro-wifi-z390-hack '/storage/nvme5/new_clones/ASL/aorus-pro-wifi-z390-hack' &
git clone https://github.com/RuaGulu/Surface-Book-Hackintosh '/storage/nvme5/new_clones/ASL/Surface-Book-Hackintosh' &
git clone https://github.com/rogercamara/OpenCore-Dell-G15-5510 '/storage/nvme5/new_clones/ASL/OpenCore-Dell-G15-5510' &
git clone https://github.com/wgjas2/MSI-Prestige-15-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-Prestige-15-Hackintosh' &
git clone https://github.com/Comet1903/t480-monterey-opencore '/storage/nvme5/new_clones/ASL/t480-monterey-opencore' &
git clone https://github.com/RieGan/Ideapad-S340-15iwl-Hackintosh '/storage/nvme5/new_clones/ASL/Ideapad-S340-15iwl-Hackintosh' &
git clone https://github.com/WHCMrShi/Dell-Latitude-3410_Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Latitude-3410_Hackintosh' &
git clone https://github.com/M3C-Owx/HP-EliteBook-Folio-1040-G3-OpenCore '/storage/nvme5/new_clones/ASL/HP-EliteBook-Folio-1040-G3-OpenCore' &
git clone https://github.com/hanngoc1406/ACER-A315-53G-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/ACER-A315-53G-Hackintosh-Opencore' &
git clone https://github.com/mateusangelo/Hackintosh-Lenovo-Legion-5i-10750h '/storage/nvme5/new_clones/ASL/Hackintosh-Lenovo-Legion-5i-10750h' &
git clone https://github.com/dreamhunter2333/Lenovo_G40_70M_EFI '/storage/nvme5/new_clones/ASL/Lenovo_G40_70M_EFI' &
git clone https://github.com/acai66/LENOVO-G50-80-V3000-Hackintosh '/storage/nvme5/new_clones/ASL/LENOVO-G50-80-V3000-Hackintosh' &
git clone https://github.com/Baio1977/Dell-Latitude-5280 '/storage/nvme5/new_clones/ASL/Dell-Latitude-5280' &
git clone https://github.com/oldweek/GS63 '/storage/nvme5/new_clones/ASL/GS63' &
git clone https://github.com/SunSeekerX/hasee_g8_ca5ns_NH5x_7xDPx_hackintosh_opencore_efi '/storage/nvme5/new_clones/ASL/hasee_g8_ca5ns_NH5x_7xDPx_hackintosh_opencore_efi' &
git clone https://github.com/stjepankos/Thinkpad-E490-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-E490-Hackintosh' &
git clone https://github.com/Dave1482/Maximus-XIII-Hero-Z590-11900K-6800XT-OpenCore-EFI-Public '/storage/nvme5/new_clones/ASL/Maximus-XIII-Hero-Z590-11900K-6800XT-OpenCore-EFI-Public' &
git clone https://github.com/ExodazTH/ASROCK-B560-STEEL-LEGEND-INTEL-CORE-I5-11400-BIG-SUR '/storage/nvme5/new_clones/ASL/ASROCK-B560-STEEL-LEGEND-INTEL-CORE-I5-11400-BIG-SUR' &
git clone https://github.com/MVDB0110/OC-XPS13-7390 '/storage/nvme5/new_clones/ASL/OC-XPS13-7390' &
git clone https://github.com/chengxuray/Hackintosh-thinkpad-e490 '/storage/nvme5/new_clones/ASL/Hackintosh-thinkpad-e490' &
git clone https://github.com/bzasy/Hackintosh '/storage/nvme5/new_clones/ASL/Hackintosh' &
git clone https://github.com/SeptemberHX/HP-Spectre-X360-13-late-2018-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Spectre-X360-13-late-2018-Hackintosh' &
git clone https://github.com/BlvckBytes/T480S_HACK '/storage/nvme5/new_clones/ASL/T480S_HACK' &
git clone https://github.com/wadimw/dell-7577-hackintosh '/storage/nvme5/new_clones/ASL/dell-7577-hackintosh' &
git clone https://github.com/nerdynikhil/Acer-Nitro-5-AN515-52-593F-OpenCore-Hackintosh '/storage/nvme5/new_clones/ASL/Acer-Nitro-5-AN515-52-593F-OpenCore-Hackintosh' &
git clone https://github.com/opflep/T480s_Hackintosh '/storage/nvme5/new_clones/ASL/T480s_Hackintosh' &
git clone https://github.com/managarm/lai_tools '/storage/nvme5/new_clones/ASL/lai_tools' &
git clone https://github.com/mydevilroot/thinkpad-x270-opencore '/storage/nvme5/new_clones/ASL/thinkpad-x270-opencore' &
git clone https://github.com/Baio1977/Asus-Vivobook-Pro-N580VD '/storage/nvme5/new_clones/ASL/Asus-Vivobook-Pro-N580VD' &
git clone https://github.com/duydoanx/gl553vd-opencore-macos-big-sur '/storage/nvme5/new_clones/ASL/gl553vd-opencore-macos-big-sur' &
git clone https://github.com/wilsomwong/Asus-TUF-FX504GE-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-TUF-FX504GE-Hackintosh' &
git clone https://github.com/AppleBreak1/EP45-UD3P-Customac '/storage/nvme5/new_clones/ASL/EP45-UD3P-Customac' &
git clone https://github.com/kmasterycsl/hpelitebook840g5-opencore '/storage/nvme5/new_clones/ASL/hpelitebook840g5-opencore' &
git clone https://github.com/RobyRew/Lenovo-Ideapad-Flex-5-14IIL05_Hackintosh_OpenCore '/storage/nvme5/new_clones/ASL/Lenovo-Ideapad-Flex-5-14IIL05_Hackintosh_OpenCore' &
git clone https://github.com/iXeor/Dell-Inspiron-7572-BigSur-OC '/storage/nvme5/new_clones/ASL/Dell-Inspiron-7572-BigSur-OC' &
git clone https://github.com/217heidai/Acer_TraveMate_P249_hackintosh '/storage/nvme5/new_clones/ASL/Acer_TraveMate_P249_hackintosh' &
git clone https://github.com/daixian/Hasee-Z10-CU7PF-Hackintosh '/storage/nvme5/new_clones/ASL/Hasee-Z10-CU7PF-Hackintosh' &
git clone https://github.com/gkShine/MSI_GS65_9SE_EFI '/storage/nvme5/new_clones/ASL/MSI_GS65_9SE_EFI' &
git clone https://github.com/jardenliu/XPS15-9560-Catalina '/storage/nvme5/new_clones/ASL/XPS15-9560-Catalina' &
git clone https://github.com/34306/Opencore-HP-340S-G7-Notebook-Hackintosh '/storage/nvme5/new_clones/ASL/Opencore-HP-340S-G7-Notebook-Hackintosh' &
git clone https://github.com/Paul-Eau/Lenovo-ThinkPad-P14s-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-P14s-Hackintosh' &
git clone https://github.com/lumingyu0423/edk2-MSM8998 '/storage/nvme5/new_clones/ASL/edk2-MSM8998' &
git clone https://github.com/GaryDoooo/acer_e51_osx '/storage/nvme5/new_clones/ASL/acer_e51_osx' &
git clone https://github.com/y053f01/macOS-Monterey-Dell-Latitude-E7470 '/storage/nvme5/new_clones/ASL/macOS-Monterey-Dell-Latitude-E7470' &
git clone https://github.com/Goldfish64/Hackintosh '/storage/nvme5/new_clones/ASL/Hackintosh' &
git clone https://github.com/dragons3232/Lenovo-gaming-3-10750h-hackintosh-EFI '/storage/nvme5/new_clones/ASL/Lenovo-gaming-3-10750h-hackintosh-EFI' &
git clone https://github.com/hoXyy/GTAV-AutoSplitter '/storage/nvme5/new_clones/ASL/GTAV-AutoSplitter' &
git clone https://github.com/amu1680c/Y470-Hackintosh '/storage/nvme5/new_clones/ASL/Y470-Hackintosh' &
git clone https://github.com/cursedtoast/re2-remake-autosplitter '/storage/nvme5/new_clones/ASL/re2-remake-autosplitter' &
git clone https://github.com/ObiwanKonami/Lenovo-x260-Hackintosh-Moneterey '/storage/nvme5/new_clones/ASL/Lenovo-x260-Hackintosh-Moneterey' &
git clone https://github.com/cjlawson02/Lenovo-ideapad-Flex-15IML-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ideapad-Flex-15IML-Hackintosh' &
git clone https://github.com/1nferious/Dell-XPS-15-7590-MacOS-Ventura--13.0--Hackintosh '/storage/nvme5/new_clones/ASL/Dell-XPS-15-7590-MacOS-Ventura--13.0--Hackintosh' &
git clone https://github.com/ChicoHan/Hackingtosh-HP-DesktopMini-800G4-Monterey '/storage/nvme5/new_clones/ASL/Hackingtosh-HP-DesktopMini-800G4-Monterey' &
git clone https://github.com/adrgumula/oc-m3800 '/storage/nvme5/new_clones/ASL/oc-m3800' &
git clone https://github.com/Charly1000/probook_450_g7 '/storage/nvme5/new_clones/ASL/probook_450_g7' &
git clone https://github.com/aglab2/LiveSplitAutoSplitters '/storage/nvme5/new_clones/ASL/LiveSplitAutoSplitters' &
git clone https://github.com/hejsekvojtech/hackintosh '/storage/nvme5/new_clones/ASL/hackintosh' &
git clone https://github.com/Tonymiugrey/STOP-UPDATING-Hackintosh-HP-PAVILION-GAMING-LAPTOP-15-dk0xxx '/storage/nvme5/new_clones/ASL/STOP-UPDATING-Hackintosh-HP-PAVILION-GAMING-LAPTOP-15-dk0xxx' &
git clone https://github.com/kreactnative/Z690-Aorus-master-Monterey '/storage/nvme5/new_clones/ASL/Z690-Aorus-master-Monterey' &
git clone https://github.com/Rocky7842/Msi-Gs66-Opencore-Hackintosh '/storage/nvme5/new_clones/ASL/Msi-Gs66-Opencore-Hackintosh' &
git clone https://github.com/baobaoit/Asus-ROG-GL552VW-OC '/storage/nvme5/new_clones/ASL/Asus-ROG-GL552VW-OC' &
git clone https://github.com/soft98-top/Lenovo-ThinkPad-L14-Gen1-i7-10510u-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-ThinkPad-L14-Gen1-i7-10510u-Hackintosh' &
git clone https://github.com/tunglamvghy/AcerSpin5-SP513-54N-hackintosh '/storage/nvme5/new_clones/ASL/AcerSpin5-SP513-54N-hackintosh' &
git clone https://github.com/bangmaple/HP-ZBook-G1-OpenCore '/storage/nvme5/new_clones/ASL/HP-ZBook-G1-OpenCore' &
git clone https://github.com/osxfr33k/Asus-G750JX '/storage/nvme5/new_clones/ASL/Asus-G750JX' &
git clone https://github.com/zhujinle/MSI-GS66-Stealth-OC-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-GS66-Stealth-OC-Hackintosh' &
git clone https://github.com/rayae/Asus_X550VQ-Hackintosh '/storage/nvme5/new_clones/ASL/Asus_X550VQ-Hackintosh' &
git clone https://github.com/zllovesuki/reverse_engineering '/storage/nvme5/new_clones/ASL/reverse_engineering' &
git clone https://github.com/elton11220/Hackintosh-ASUS-GL552VW-FXPRO6300HQ-Clover '/storage/nvme5/new_clones/ASL/Hackintosh-ASUS-GL552VW-FXPRO6300HQ-Clover' &
git clone https://github.com/quynkk1/e-series-skylake-hackintosh-dell '/storage/nvme5/new_clones/ASL/e-series-skylake-hackintosh-dell' &
git clone https://github.com/R-a-s-c-a-l/Thinkpad-X13-Gen1-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-X13-Gen1-Hackintosh' &
git clone https://github.com/jsassu20/Dell-DW1820a-Broadcom-BCM94350Zae-macOS-Full-Support '/storage/nvme5/new_clones/ASL/Dell-DW1820a-Broadcom-BCM94350Zae-macOS-Full-Support' &
git clone https://github.com/BearTS/Opencore '/storage/nvme5/new_clones/ASL/Opencore' &
git clone https://github.com/tane123/Razer-Blade-15-Base-2021-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-15-Base-2021-Hackintosh' &
git clone https://github.com/MoozIiSP/dell-7348-hackintosh '/storage/nvme5/new_clones/ASL/dell-7348-hackintosh' &
git clone https://github.com/blegas78/autoSplitters '/storage/nvme5/new_clones/ASL/autoSplitters' &
git clone https://github.com/Speeedo83/Dell-Inspiron-5491-2in1-Hakintosh '/storage/nvme5/new_clones/ASL/Dell-Inspiron-5491-2in1-Hakintosh' &
git clone https://github.com/kaditya25/HP_Envy_15bp_194cl_OpenCore '/storage/nvme5/new_clones/ASL/HP_Envy_15bp_194cl_OpenCore' &
git clone https://github.com/QuanTrieuPCYT/ASRock-B560M-Pro4_Hackintosh '/storage/nvme5/new_clones/ASL/ASRock-B560M-Pro4_Hackintosh' &
git clone https://github.com/mdadsh/opencore-dell-3567-hackintosh '/storage/nvme5/new_clones/ASL/opencore-dell-3567-hackintosh' &
git clone https://github.com/huyhoang8398/x1c7-hackintosh-20R1 '/storage/nvme5/new_clones/ASL/x1c7-hackintosh-20R1' &
git clone https://github.com/billthan/XPS9500-MacOS-BigSur-OC '/storage/nvme5/new_clones/ASL/XPS9500-MacOS-BigSur-OC' &
git clone https://github.com/hexart/X280-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/X280-Hackintosh-OpenCore' &
git clone https://github.com/darkhandz/XPS15-9550-BigSur '/storage/nvme5/new_clones/ASL/XPS15-9550-BigSur' &
git clone https://github.com/dasha-samples/dasha-first-app '/storage/nvme5/new_clones/ASL/dasha-first-app' &
git clone https://github.com/bonki/hackintosh-opencore-hp-elitebook-840-g1 '/storage/nvme5/new_clones/ASL/hackintosh-opencore-hp-elitebook-840-g1' &
git clone https://github.com/kursatufukcoskun/Dell-Precision-5520-Hackintosh-macos-Opencore '/storage/nvme5/new_clones/ASL/Dell-Precision-5520-Hackintosh-macos-Opencore' &
git clone https://github.com/gencharitaci/Hackintosh-OpenCore-EFI-for-MSI-GL65-Leopard-10SDR-412XTR '/storage/nvme5/new_clones/ASL/Hackintosh-OpenCore-EFI-for-MSI-GL65-Leopard-10SDR-412XTR' &
git clone https://github.com/ijiki16/Dell-Latitude-E5270-OpenCore '/storage/nvme5/new_clones/ASL/Dell-Latitude-E5270-OpenCore' &
git clone https://github.com/linux-surface/acpidumps '/storage/nvme5/new_clones/ASL/acpidumps' &
git clone https://github.com/superrnovae/asusn550jv-hackintosh '/storage/nvme5/new_clones/ASL/asusn550jv-hackintosh' &
git clone https://github.com/yahgoo/Hackintosh-HP-9470m-Opencore-Monterey-1600x900-Broadcom-WiFi '/storage/nvme5/new_clones/ASL/Hackintosh-HP-9470m-Opencore-Monterey-1600x900-Broadcom-WiFi' &
git clone https://github.com/Lockzi/macOS-XPS-9700-Catalina '/storage/nvme5/new_clones/ASL/macOS-XPS-9700-Catalina' &
git clone https://github.com/zsakvo/hp-348-g5-hackintosh '/storage/nvme5/new_clones/ASL/hp-348-g5-hackintosh' &
git clone https://github.com/menukaonline/hackintosh-msi-gf63-thin-10SCXR '/storage/nvme5/new_clones/ASL/hackintosh-msi-gf63-thin-10SCXR' &
git clone https://github.com/Parthvsquare/Opencore-LG-gram-14z980 '/storage/nvme5/new_clones/ASL/Opencore-LG-gram-14z980' &
git clone https://github.com/Baio1977/GA-Z390M-Gaming '/storage/nvme5/new_clones/ASL/GA-Z390M-Gaming' &
git clone https://github.com/UNHchabo/AutoSplitters '/storage/nvme5/new_clones/ASL/AutoSplitters' &
git clone https://github.com/zhongmax/XPS-9570-macOS '/storage/nvme5/new_clones/ASL/XPS-9570-macOS' &
git clone https://github.com/bitsmuggler/supabase-architecture '/storage/nvme5/new_clones/ASL/supabase-architecture' &
git clone https://github.com/faithvoid/X220-Catalina '/storage/nvme5/new_clones/ASL/X220-Catalina' &
git clone https://github.com/Spiraster/ASLScripts '/storage/nvme5/new_clones/ASL/ASLScripts' &
git clone https://github.com/KadeReolance/Predator-Helios-300-OpenCore-0.6.2 '/storage/nvme5/new_clones/ASL/Predator-Helios-300-OpenCore-0.6.2' &
git clone https://github.com/AlliotTech/hackintosh-y7000-2018-i58300H '/storage/nvme5/new_clones/ASL/hackintosh-y7000-2018-i58300H' &
git clone https://github.com/foremind/Dell-Inspiron-7490-OpenCore '/storage/nvme5/new_clones/ASL/Dell-Inspiron-7490-OpenCore' &
git clone https://github.com/sqlsec/ASUS-ZenBook14-UX434FLC '/storage/nvme5/new_clones/ASL/ASUS-ZenBook14-UX434FLC' &
git clone https://github.com/FERARMAO/Hackintosh-OC-BigSur-Catalina-Dell-5570 '/storage/nvme5/new_clones/ASL/Hackintosh-OC-BigSur-Catalina-Dell-5570' &
git clone https://github.com/deeplyfriedchicken/A-Z390-9700K-EFI '/storage/nvme5/new_clones/ASL/A-Z390-9700K-EFI' &
git clone https://github.com/tangalbert919/Hackintosh-Aero-15-Classic '/storage/nvme5/new_clones/ASL/Hackintosh-Aero-15-Classic' &
git clone https://github.com/christiancuri/Nitro-5-AN515-54-Hackintosh '/storage/nvme5/new_clones/ASL/Nitro-5-AN515-54-Hackintosh' &
git clone https://github.com/arun-praj/Hackintosh-MSI-mpg-z390-gaming-plus '/storage/nvme5/new_clones/ASL/Hackintosh-MSI-mpg-z390-gaming-plus' &
git clone https://github.com/Hegg5577/OpenCore-For-DELL-5577 '/storage/nvme5/new_clones/ASL/OpenCore-For-DELL-5577' &
git clone https://github.com/pastfuture777/Monterey-ASUS-TUF-Gaming-FX506LI-opencore '/storage/nvme5/new_clones/ASL/Monterey-ASUS-TUF-Gaming-FX506LI-opencore' &
git clone https://github.com/plcharriere/hackintosh-lenovo-thinkpad-t14s '/storage/nvme5/new_clones/ASL/hackintosh-lenovo-thinkpad-t14s' &
git clone https://github.com/allansrc/Catalina-macOS-Aspire-5 '/storage/nvme5/new_clones/ASL/Catalina-macOS-Aspire-5' &
git clone https://github.com/vivzero/LG-14Z90N-hackintosh '/storage/nvme5/new_clones/ASL/LG-14Z90N-hackintosh' &
git clone https://github.com/rockavoldy/Acer-E5-476G-Hackintosh '/storage/nvme5/new_clones/ASL/Acer-E5-476G-Hackintosh' &
git clone https://github.com/lohcve/EFI_T470P_OC '/storage/nvme5/new_clones/ASL/EFI_T470P_OC' &
git clone https://github.com/Baio1977/HP-250-G6-Kabylake '/storage/nvme5/new_clones/ASL/HP-250-G6-Kabylake' &
git clone https://github.com/qanhta2710/Hackintosh '/storage/nvme5/new_clones/ASL/Hackintosh' &
git clone https://github.com/koluris/SURFACE-PRO-4-OpenCore '/storage/nvme5/new_clones/ASL/SURFACE-PRO-4-OpenCore' &
git clone https://github.com/imcczy/Gigabyte_B560m_AORUS_PRO_AX_10850K_6900XT_EFI '/storage/nvme5/new_clones/ASL/Gigabyte_B560m_AORUS_PRO_AX_10850K_6900XT_EFI' &
git clone https://github.com/sanoj-m/Razer-Blade-Pro-17-2020-Hackintosh-Monterey '/storage/nvme5/new_clones/ASL/Razer-Blade-Pro-17-2020-Hackintosh-Monterey' &
git clone https://github.com/pangdahaiNo1/lenovo-E49-macos-efi '/storage/nvme5/new_clones/ASL/lenovo-E49-macos-efi' &
git clone https://github.com/lshbluesky/LG-Ultra-PC-15U480-KA56K-Hackintosh '/storage/nvme5/new_clones/ASL/LG-Ultra-PC-15U480-KA56K-Hackintosh' &
git clone https://github.com/Lorys89/DELL_OPTIPLEX_9030_AIO '/storage/nvme5/new_clones/ASL/DELL_OPTIPLEX_9030_AIO' &
git clone https://github.com/SheehabMuhammad/Lenovo-X1C3-OpenCore '/storage/nvme5/new_clones/ASL/Lenovo-X1C3-OpenCore' &
git clone https://github.com/the-eric-kwok/HP-Pavilion-bc015tx-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Pavilion-bc015tx-Hackintosh' &
git clone https://github.com/a520ass/ASUS-X550VC-Hackintosh '/storage/nvme5/new_clones/ASL/ASUS-X550VC-Hackintosh' &
git clone https://github.com/sash11/Dell-XPS15-7590 '/storage/nvme5/new_clones/ASL/Dell-XPS15-7590' &
git clone https://github.com/doubleyoustew/Razer-Blade-15 '/storage/nvme5/new_clones/ASL/Razer-Blade-15' &
git clone https://github.com/RANSAA/OpenCore '/storage/nvme5/new_clones/ASL/OpenCore' &
git clone https://github.com/lienkheict/Dell-M4800-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-M4800-Hackintosh' &
git clone https://github.com/Danny-Z/T460p-OpenCore '/storage/nvme5/new_clones/ASL/T460p-OpenCore' &
git clone https://github.com/cephasara/lenovo-yoga-920-hackintosh '/storage/nvme5/new_clones/ASL/lenovo-yoga-920-hackintosh' &
git clone https://github.com/w43322/X220-OpenCore '/storage/nvme5/new_clones/ASL/X220-OpenCore' &
git clone https://github.com/xzajyjs/XiaoXin13Pro-Hackintosh '/storage/nvme5/new_clones/ASL/XiaoXin13Pro-Hackintosh' &
git clone https://github.com/sambow23/blade-stealth-2016-macOS '/storage/nvme5/new_clones/ASL/blade-stealth-2016-macOS' &
git clone https://github.com/Enmusushi/XiaomiAir13.3TM1604-EFI '/storage/nvme5/new_clones/ASL/XiaomiAir13.3TM1604-EFI' &
git clone https://github.com/luchina-gabriel/EFI-GIGABYTE-W480-Vision-D-10900K-RX580 '/storage/nvme5/new_clones/ASL/EFI-GIGABYTE-W480-Vision-D-10900K-RX580' &
git clone https://github.com/osx86-ijb/Dell-Inspiron-15-3567-7th-Gen-Core-i3-7100u-macOS '/storage/nvme5/new_clones/ASL/Dell-Inspiron-15-3567-7th-Gen-Core-i3-7100u-macOS' &
git clone https://github.com/nanne007/opencore-z390p-9600k '/storage/nvme5/new_clones/ASL/opencore-z390p-9600k' &
git clone https://github.com/isherlockliu/Thinkpad-T480-Opencore-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkpad-T480-Opencore-Hackintosh' &
git clone https://github.com/Italo-Nogueira/EFI-Acer-Nitro5-AN515-54-58CL_Hackintosh_OC_0.7.3 '/storage/nvme5/new_clones/ASL/EFI-Acer-Nitro5-AN515-54-58CL_Hackintosh_OC_0.7.3' &
git clone https://github.com/Flex1911/macOS-V130-15IKB '/storage/nvme5/new_clones/ASL/macOS-V130-15IKB' &
git clone https://github.com/ettingshausen/k43c-80-hackintosh '/storage/nvme5/new_clones/ASL/k43c-80-hackintosh' &
git clone https://github.com/jsan-repo/ThinkPad-X1-Carbon-2nd-OpenCoreEFI '/storage/nvme5/new_clones/ASL/ThinkPad-X1-Carbon-2nd-OpenCoreEFI' &
git clone https://github.com/rafaelwms/PH315-52-79VM '/storage/nvme5/new_clones/ASL/PH315-52-79VM' &
git clone https://github.com/YGQ8988/HP-ProBook430G6 '/storage/nvme5/new_clones/ASL/HP-ProBook430G6' &
git clone https://github.com/ForceGT/Hackintosh--MSIGL62M-7RDX '/storage/nvme5/new_clones/ASL/Hackintosh--MSIGL62M-7RDX' &
git clone https://github.com/Baio1977/Acer-Aspire-E5-574G '/storage/nvme5/new_clones/ASL/Acer-Aspire-E5-574G' &
git clone https://github.com/almodroid/Dell-vostro-5471-hackintosh '/storage/nvme5/new_clones/ASL/Dell-vostro-5471-hackintosh' &
git clone https://github.com/Ricardo-SS/Hackintosh-Yoga-520-i3-7100U '/storage/nvme5/new_clones/ASL/Hackintosh-Yoga-520-i3-7100U' &
git clone https://github.com/basett1/Asus-N551JK-OC-EFI '/storage/nvme5/new_clones/ASL/Asus-N551JK-OC-EFI' &
git clone https://github.com/julianpetriv/EFI-HP-ZBook15G3 '/storage/nvme5/new_clones/ASL/EFI-HP-ZBook15G3' &
git clone https://github.com/rofyfirm/EFI-OpenCore-A456URK '/storage/nvme5/new_clones/ASL/EFI-OpenCore-A456URK' &
git clone https://github.com/Lorys89/Lenovo_ThinkPad_E570 '/storage/nvme5/new_clones/ASL/Lenovo_ThinkPad_E570' &
git clone https://github.com/Davis-T/Hackintosh_For_GE60_2OE-218XCN '/storage/nvme5/new_clones/ASL/Hackintosh_For_GE60_2OE-218XCN' &
git clone https://github.com/ZHUIMEN/MSI-B365M-i5-9600f-EFI '/storage/nvme5/new_clones/ASL/MSI-B365M-i5-9600f-EFI' &
git clone https://github.com/dalisoft/Z390-I9-9900K-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Z390-I9-9900K-Hackintosh-OpenCore' &
git clone https://github.com/markuslohn/asus-rog-z390i-hackintosh '/storage/nvme5/new_clones/ASL/asus-rog-z390i-hackintosh' &
git clone https://github.com/SteFiD93/ge60-2pe-opencore-bigsur '/storage/nvme5/new_clones/ASL/ge60-2pe-opencore-bigsur' &
git clone https://github.com/alexjaixd/Lenovo-Thinkpad-X1-Tablet-Gen-2-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-X1-Tablet-Gen-2-Hackintosh' &
git clone https://github.com/jardenliu/XPS15-9560-BigSur '/storage/nvme5/new_clones/ASL/XPS15-9560-BigSur' &
git clone https://github.com/peidgnad/15vG5 '/storage/nvme5/new_clones/ASL/15vG5' &
git clone https://github.com/polo7261/Unsupported-GPU-Hackintosh-Fix '/storage/nvme5/new_clones/ASL/Unsupported-GPU-Hackintosh-Fix' &
git clone https://github.com/KenDxD/Lenovo-Thinkpad-E560-Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-Thinkpad-E560-Hackintosh' &
git clone https://github.com/danang-id/ASUS-TP412FA-ESP '/storage/nvme5/new_clones/ASL/ASUS-TP412FA-ESP' &
git clone https://github.com/hieuvh/EFI-OpenCore-Dell-E7440-Big-Sur '/storage/nvme5/new_clones/ASL/EFI-OpenCore-Dell-E7440-Big-Sur' &
git clone https://github.com/chendianVista/Thinkpad-X240-Ventura-EFI-opencore-0.8.5 '/storage/nvme5/new_clones/ASL/Thinkpad-X240-Ventura-EFI-opencore-0.8.5' &
git clone https://github.com/dursonATWIT/T480-OpenCore-Hackintosh-Thunderbolt '/storage/nvme5/new_clones/ASL/T480-OpenCore-Hackintosh-Thunderbolt' &
git clone https://github.com/whatnameisit/HP-Elite-X2-1012-G2-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Elite-X2-1012-G2-Hackintosh' &
git clone https://github.com/chansLam/hackintosh-dell-G3-3590 '/storage/nvme5/new_clones/ASL/hackintosh-dell-G3-3590' &
git clone https://github.com/RuaGulu/ASUS-ROG-Zephyrus-Duo-GX550-Hackintosh '/storage/nvme5/new_clones/ASL/ASUS-ROG-Zephyrus-Duo-GX550-Hackintosh' &
git clone https://github.com/haoyaxuan/XiaoXinPro-13-hackintosh '/storage/nvme5/new_clones/ASL/XiaoXinPro-13-hackintosh' &
git clone https://github.com/keyboardcrash32/LiveSplit.Ultimate-DOOM '/storage/nvme5/new_clones/ASL/LiveSplit.Ultimate-DOOM' &
git clone https://github.com/LongTaiJun/Dell-XPS-8940-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-XPS-8940-Hackintosh' &
git clone https://github.com/ouqiting/DELL-g3-3590-opencore-v1.0.1 '/storage/nvme5/new_clones/ASL/DELL-g3-3590-opencore-v1.0.1' &
git clone https://github.com/abctel/ThinkPadX390_4GLTE-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPadX390_4GLTE-OpenCore' &
git clone https://github.com/rbikbov/msi-gl65-9sc-hackintosh '/storage/nvme5/new_clones/ASL/msi-gl65-9sc-hackintosh' &
git clone https://github.com/Crap-Mayur/Dell-3521-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-3521-Hackintosh' &
git clone https://github.com/blacksd/Dell-Inspiron-7559-hackintosh-opencore '/storage/nvme5/new_clones/ASL/Dell-Inspiron-7559-hackintosh-opencore' &
git clone https://github.com/NLTD2010/Dell-Inspiron-15-3576-hackintosh '/storage/nvme5/new_clones/ASL/Dell-Inspiron-15-3576-hackintosh' &
git clone https://github.com/Dugganclock/Dell-Latitude-5400-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Dell-Latitude-5400-Hackintosh-OpenCore' &
git clone https://github.com/velickovicdj/A315-54K-34P6-OpenCore '/storage/nvme5/new_clones/ASL/A315-54K-34P6-OpenCore' &
git clone https://github.com/rlatn1234/XPS15-9570-Catalina-BigSur '/storage/nvme5/new_clones/ASL/XPS15-9570-Catalina-BigSur' &
git clone https://github.com/MumetNgoding/Hackintosh-DELL-Vostro-5468 '/storage/nvme5/new_clones/ASL/Hackintosh-DELL-Vostro-5468' &
git clone https://github.com/andysandford/sm64-livesplit-autosplitter '/storage/nvme5/new_clones/ASL/sm64-livesplit-autosplitter' &
git clone https://github.com/Datta0/Opencore_Acer_i7-8565U '/storage/nvme5/new_clones/ASL/Opencore_Acer_i7-8565U' &
git clone https://github.com/Vins95/DELL-Inspiron-7391-Hackintosh-EFI- '/storage/nvme5/new_clones/ASL/DELL-Inspiron-7391-Hackintosh-EFI-' &
git clone https://github.com/apollohackintosh/Dell-5310-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-5310-Hackintosh' &
git clone https://github.com/mortalis13/StarDict-To-DSL-Converter '/storage/nvme5/new_clones/ASL/StarDict-To-DSL-Converter' &
git clone https://github.com/jt1900jt/Razer-Blade-15-2020-4K-OLED-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-15-2020-4K-OLED-Hackintosh' &
git clone https://github.com/MuziShaoxing/HP-Pavilion-Laptop-14-ce3xxx-1035G1 '/storage/nvme5/new_clones/ASL/HP-Pavilion-Laptop-14-ce3xxx-1035G1' &
git clone https://github.com/Burnt-o/MCC_autosplitter '/storage/nvme5/new_clones/ASL/MCC_autosplitter' &
git clone https://github.com/tduva/LiveSplit-ASL '/storage/nvme5/new_clones/ASL/LiveSplit-ASL' &
git clone https://github.com/dashjay/thinkpad-t14-gen-1 '/storage/nvme5/new_clones/ASL/thinkpad-t14-gen-1' &
git clone https://github.com/bankm1/Dell-XPS-9370-Hackintosh-Opencore '/storage/nvme5/new_clones/ASL/Dell-XPS-9370-Hackintosh-Opencore' &
git clone https://github.com/BrandTime/Asus-K550J-Hackintosh '/storage/nvme5/new_clones/ASL/Asus-K550J-Hackintosh' &
git clone https://github.com/lshbluesky/Samsung-Sens-Q36-Hackintosh '/storage/nvme5/new_clones/ASL/Samsung-Sens-Q36-Hackintosh' &
git clone https://github.com/namirjahmed/T440p-Hackintosh '/storage/nvme5/new_clones/ASL/T440p-Hackintosh' &
git clone https://github.com/Lorys89/DELL_VOSTRO_5471 '/storage/nvme5/new_clones/ASL/DELL_VOSTRO_5471' &
git clone https://github.com/giusedm/Xiaomi_Air_12.5_EFI_O.C '/storage/nvme5/new_clones/ASL/Xiaomi_Air_12.5_EFI_O.C' &
git clone https://github.com/quangvinhdam/Big-Sur-On-Dell-Inspiron-3567 '/storage/nvme5/new_clones/ASL/Big-Sur-On-Dell-Inspiron-3567' &
git clone https://github.com/98przem/ThinkPad-X260-OpenCore '/storage/nvme5/new_clones/ASL/ThinkPad-X260-OpenCore' &
git clone https://github.com/WeB-CoDeR-01/Asus-GL553VD-Opencore-EFI-for-BigSur '/storage/nvme5/new_clones/ASL/Asus-GL553VD-Opencore-EFI-for-BigSur' &
git clone https://github.com/ahianf/dell-latitude-5300-hackintosh '/storage/nvme5/new_clones/ASL/dell-latitude-5300-hackintosh' &
git clone https://github.com/mirifi2k/lenovo-g50-70-hackintosh '/storage/nvme5/new_clones/ASL/lenovo-g50-70-hackintosh' &
git clone https://github.com/CuitGGyy/x250-hackintosh '/storage/nvme5/new_clones/ASL/x250-hackintosh' &
git clone https://github.com/cstefann/Vostro-3490-hackintosh '/storage/nvme5/new_clones/ASL/Vostro-3490-hackintosh' &
git clone https://github.com/pixelmorto/Acer-F5-573G-50KS-Hackintosh '/storage/nvme5/new_clones/ASL/Acer-F5-573G-50KS-Hackintosh' &
git clone https://github.com/mykimy/MSI-GF63-9RCX_OpenCore-Hackintosh '/storage/nvme5/new_clones/ASL/MSI-GF63-9RCX_OpenCore-Hackintosh' &
git clone https://github.com/cupugila/Thinkbook-13s-IWL-EFI-Hackintosh '/storage/nvme5/new_clones/ASL/Thinkbook-13s-IWL-EFI-Hackintosh' &
git clone https://github.com/psabadac/Acer-A515-51G-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/Acer-A515-51G-Hackintosh-OpenCore' &
git clone https://github.com/takobaba/EFI-Opencore-Thinkpad-L490 '/storage/nvme5/new_clones/ASL/EFI-Opencore-Thinkpad-L490' &
git clone https://github.com/ahianf/dell-vostro-3468-hackintosh '/storage/nvme5/new_clones/ASL/dell-vostro-3468-hackintosh' &
git clone https://github.com/jman985/Razer-Blade-Stealth-13--Early-2020--Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-Stealth-13--Early-2020--Hackintosh' &
git clone https://github.com/Louis-lew/L470-OpenCore '/storage/nvme5/new_clones/ASL/L470-OpenCore' &
git clone https://github.com/bpefei/Lenovo-QiTian-M425-N050-OpenCore-EFI '/storage/nvme5/new_clones/ASL/Lenovo-QiTian-M425-N050-OpenCore-EFI' &
git clone https://github.com/QuanTrieuPCYT/HPHamar_Hackintosh '/storage/nvme5/new_clones/ASL/HPHamar_Hackintosh' &
git clone https://github.com/keyboardcrash32/HL1-PCSX2-Load-Removal '/storage/nvme5/new_clones/ASL/HL1-PCSX2-Load-Removal' &
git clone https://github.com/IFierta/mac-os-opencore-asus-k501lx_lb '/storage/nvme5/new_clones/ASL/mac-os-opencore-asus-k501lx_lb' &
git clone https://github.com/rote66/Hackintosh_HP_ZBOOK15VG5 '/storage/nvme5/new_clones/ASL/Hackintosh_HP_ZBOOK15VG5' &
git clone https://github.com/xueziQQ/desktop_soyo_maxsun_h110_ql3x_ql2x_opencore_efi '/storage/nvme5/new_clones/ASL/desktop_soyo_maxsun_h110_ql3x_ql2x_opencore_efi' &
git clone https://github.com/jpransxdev/HP-Spectre-X360-13-Early-2019-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Spectre-X360-13-Early-2019-Hackintosh' &
git clone https://github.com/SamHGA/HP-EliteBook-2570p-OpenCore-EFI '/storage/nvme5/new_clones/ASL/HP-EliteBook-2570p-OpenCore-EFI' &
git clone https://github.com/adu27366754/YOGA-14s-2021-hackintosh '/storage/nvme5/new_clones/ASL/YOGA-14s-2021-hackintosh' &
git clone https://github.com/w43322/X220-OpenCore-DualBoot '/storage/nvme5/new_clones/ASL/X220-OpenCore-DualBoot' &
git clone https://github.com/HackyMacky/Opencore-HP-Elitebook-840-G3 '/storage/nvme5/new_clones/ASL/Opencore-HP-Elitebook-840-G3' &
git clone https://github.com/faizauthar12/ASUS_VivoBook_A411UF_Hackintosh '/storage/nvme5/new_clones/ASL/ASUS_VivoBook_A411UF_Hackintosh' &
git clone https://github.com/magua33/MSI-Z390M-Motar_i7-9700KF_OpenCore_EFI '/storage/nvme5/new_clones/ASL/MSI-Z390M-Motar_i7-9700KF_OpenCore_EFI' &
git clone https://github.com/jnr0602/2021-Razer-Blade-15-Advanced-OpenCore '/storage/nvme5/new_clones/ASL/2021-Razer-Blade-15-Advanced-OpenCore' &
git clone https://github.com/drtchops/asl '/storage/nvme5/new_clones/ASL/asl' &
git clone https://github.com/shijianzhiwai/Hackintosh-Gigabyte-Z370-OC-EFI '/storage/nvme5/new_clones/ASL/Hackintosh-Gigabyte-Z370-OC-EFI' &
git clone https://github.com/LuxuryWasTaken/Razer-Blade-2020-Base-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-2020-Base-Hackintosh' &
git clone https://github.com/zxiuwu/hackintosh-efi '/storage/nvme5/new_clones/ASL/hackintosh-efi' &
git clone https://github.com/city8208/Hackintosh-thinkpad-P53 '/storage/nvme5/new_clones/ASL/Hackintosh-thinkpad-P53' &
git clone https://github.com/jfneto/Dell-Inspiron-15-7580-i7-8565U '/storage/nvme5/new_clones/ASL/Dell-Inspiron-15-7580-i7-8565U' &
git clone https://github.com/im1ke/Huawei_MatebookD15-2018-Hackintosh '/storage/nvme5/new_clones/ASL/Huawei_MatebookD15-2018-Hackintosh' &
git clone https://github.com/oracc/osl '/storage/nvme5/new_clones/ASL/osl' &
git clone https://github.com/EtaoinWu/SuperliminalASL '/storage/nvme5/new_clones/ASL/SuperliminalASL' &
git clone https://github.com/Rezenders/active-perception-experiments '/storage/nvme5/new_clones/ASL/active-perception-experiments' &
git clone https://github.com/RaffaySajjad/HP-Pavilion-15-Gaming-Hackintosh-EFI- '/storage/nvme5/new_clones/ASL/HP-Pavilion-15-Gaming-Hackintosh-EFI-' &
git clone https://github.com/joske/DELL-XPS-13-9370 '/storage/nvme5/new_clones/ASL/DELL-XPS-13-9370' &
git clone https://github.com/KernelPanic-OpenSource/hackintosh-HP-ProBook-640-G1 '/storage/nvme5/new_clones/ASL/hackintosh-HP-ProBook-640-G1' &
git clone https://github.com/Japerz12138/RazerBladeAdvanced2020_Hackintosh '/storage/nvme5/new_clones/ASL/RazerBladeAdvanced2020_Hackintosh' &
git clone https://github.com/AndroidOL/NUC6i3SYK '/storage/nvme5/new_clones/ASL/NUC6i3SYK' &
git clone https://github.com/andreibleortu/Dell-Vostro-5590-Hackintosh-EFI '/storage/nvme5/new_clones/ASL/Dell-Vostro-5590-Hackintosh-EFI' &
git clone https://github.com/demon3434/Hackintosh-EFI-ThinkPadT540p '/storage/nvme5/new_clones/ASL/Hackintosh-EFI-ThinkPadT540p' &
git clone https://github.com/krasscy/Hackintosh_HASEE_Z7-KP7G1 '/storage/nvme5/new_clones/ASL/Hackintosh_HASEE_Z7-KP7G1' &
git clone https://github.com/SandiTT/Hackintosh-3700X-5700-B450M-Catalina-10.15.7 '/storage/nvme5/new_clones/ASL/Hackintosh-3700X-5700-B450M-Catalina-10.15.7' &
git clone https://github.com/hykilpikonna/XPS-7390-2in1 '/storage/nvme5/new_clones/ASL/XPS-7390-2in1' &
git clone https://github.com/y0ngj1e/ASUS-S531FL-Hackintosh-OpenCore '/storage/nvme5/new_clones/ASL/ASUS-S531FL-Hackintosh-OpenCore' &
git clone https://github.com/kidonng/HP-Pavilion-13-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Pavilion-13-Hackintosh' &
git clone https://github.com/ac1ra/GA-H61N-USB3-Hackintosh '/storage/nvme5/new_clones/ASL/GA-H61N-USB3-Hackintosh' &
git clone https://github.com/Zheng-Jiakun/ThinkPad-T450s-Hackintosh-Catalina-Clover '/storage/nvme5/new_clones/ASL/ThinkPad-T450s-Hackintosh-Catalina-Clover' &
git clone https://github.com/doanhxd/Dell-Vostro-3568-Hackintosh '/storage/nvme5/new_clones/ASL/Dell-Vostro-3568-Hackintosh' &
git clone https://github.com/blankqwq/asus-fl5900u-hackintosh '/storage/nvme5/new_clones/ASL/asus-fl5900u-hackintosh' &
git clone https://github.com/Alitaaaaa/Hackintosh_Opencore_Gigabyte_GA_B150M_D3H_QTJ2_EFI '/storage/nvme5/new_clones/ASL/Hackintosh_Opencore_Gigabyte_GA_B150M_D3H_QTJ2_EFI' &
git clone https://github.com/toshinori8/HP-ProDesk-400-G2-DM '/storage/nvme5/new_clones/ASL/HP-ProDesk-400-G2-DM' &
git clone https://github.com/jiashunzheng/Lenovo_Yoga_720_Hackintosh '/storage/nvme5/new_clones/ASL/Lenovo_Yoga_720_Hackintosh' &
git clone https://github.com/challenger800/T470-MacOS '/storage/nvme5/new_clones/ASL/T470-MacOS' &
git clone https://github.com/FivEawE/AutoSplitterGTAVCS '/storage/nvme5/new_clones/ASL/AutoSplitterGTAVCS' &
git clone https://github.com/freaksavior/OptiHack5070 '/storage/nvme5/new_clones/ASL/OptiHack5070' &
git clone https://github.com/Ketuer/HUANANZHI-B85-ITX-Hackintosh '/storage/nvme5/new_clones/ASL/HUANANZHI-B85-ITX-Hackintosh' &
git clone https://github.com/maxbelyanin/Xiaomi-Mi-Notebook-Pro-2019-Enhanced-Edition-Hackintosh '/storage/nvme5/new_clones/ASL/Xiaomi-Mi-Notebook-Pro-2019-Enhanced-Edition-Hackintosh' &
git clone https://github.com/rchunping/Hackintosh-OC-Dell-OptiPlex-7060-Micro '/storage/nvme5/new_clones/ASL/Hackintosh-OC-Dell-OptiPlex-7060-Micro' &
git clone https://github.com/akazakarin/OpenCore-Catalina-T430 '/storage/nvme5/new_clones/ASL/OpenCore-Catalina-T430' &
git clone https://github.com/kushwavez/acer-aspire-v5-591g-clover-efi '/storage/nvme5/new_clones/ASL/acer-aspire-v5-591g-clover-efi' &
git clone https://github.com/mdezc/Razer-Blade-15-Base-2021-Hackintosh '/storage/nvme5/new_clones/ASL/Razer-Blade-15-Base-2021-Hackintosh' &
git clone https://github.com/tookdes/HP-Elitebook-830-G6-Hackintosh '/storage/nvme5/new_clones/ASL/HP-Elitebook-830-G6-Hackintosh' &
git clone https://github.com/laggykiller/hackintosh-gmk-nucbox2 '/storage/nvme5/new_clones/ASL/hackintosh-gmk-nucbox2' &
git clone https://github.com/theisyraff/Opencore-Vivobook-A409JA '/storage/nvme5/new_clones/ASL/Opencore-Vivobook-A409JA' &
git clone https://github.com/WangGang-a1/Acer-A715-EFI '/storage/nvme5/new_clones/ASL/Acer-A715-EFI' &
git clone https://github.com/Mustang-Sun/HUANANZHI-B85-ITX-Hackintosh '/storage/nvme5/new_clones/ASL/HUANANZHI-B85-ITX-Hackintosh' &
git clone https://github.com/rohanbojja/MSI-GF-63-10 '/storage/nvme5/new_clones/ASL/MSI-GF-63-10' &
git clone https://github.com/mbarbierato/Lenovo-Miix720 '/storage/nvme5/new_clones/ASL/Lenovo-Miix720' &
git clone https://github.com/heiwa9/BladeStealthLate2019_Hackintosh '/storage/nvme5/new_clones/ASL/BladeStealthLate2019_Hackintosh' &
git clone https://github.com/linlinger/hasee-N960Kx-hackintosh '/storage/nvme5/new_clones/ASL/hasee-N960Kx-hackintosh' &
git clone https://github.com/pnapt/ASUS-FX504GD-Opencore '/storage/nvme5/new_clones/ASL/ASUS-FX504GD-Opencore' &
git clone https://github.com/jubarim/Hackintosh-Lenovo-E490 '/storage/nvme5/new_clones/ASL/Hackintosh-Lenovo-E490' &
git clone https://github.com/cstefann/Lenovo-530s-15IKB-hackintosh '/storage/nvme5/new_clones/ASL/Lenovo-530s-15IKB-hackintosh' &
git clone https://github.com/dungnt11/dell-5568-efi-10.15.6 '/storage/nvme5/new_clones/ASL/dell-5568-efi-10.15.6' &
git clone https://github.com/dashjay/thinkpad-t14-gen-1 '/storage/nvme5/new_clones/ASL/thinkpad-t14-gen-1' &
git clone https://github.com/Shaw-fung/dell-5175-efi-opencore-oc '/storage/nvme5/new_clones/ASL/dell-5175-efi-opencore-oc' &
