#!/bin/bash

git clone https://github.com/koolshare/koolshare.github.io '/storage/nvme5/new_clones/ASP/koolsharehub.io' &
git clone https://github.com/askme765cs/Wine-QQ-TIM '/storage/nvme5/new_clones/ASP/Wine-QQ-TIM' &
git clone https://github.com/koolshare/rogsoft '/storage/nvme5/new_clones/ASP/rogsoft' &
git clone https://github.com/LandGrey/webshell-detect-bypass '/storage/nvme5/new_clones/ASP/webshell-detect-bypass' &
git clone https://github.com/ArztSamuel/Applying_EANNs '/storage/nvme5/new_clones/ASP/Applying_EANNs' &
git clone https://github.com/koolshare/ledesoft '/storage/nvme5/new_clones/ASP/ledesoft' &
git clone https://github.com/koolshare/armsoft '/storage/nvme5/new_clones/ASP/armsoft' &
git clone https://github.com/Anime4000/RTL960x '/storage/nvme5/new_clones/ASP/RTL960x' &
git clone https://github.com/Aabyss-Team/WebShell '/storage/nvme5/new_clones/ASP/WebShell' &
git clone https://github.com/gorden5566/padavan '/storage/nvme5/new_clones/ASP/padavan' &
git clone https://github.com/koolproxy/merlin-koolproxy '/storage/nvme5/new_clones/ASP/merlin-koolproxy' &
git clone https://github.com/zusterben/plan_b '/storage/nvme5/new_clones/ASP/plan_b' &
git clone https://github.com/wbcyclist/merlin_shadowsocks '/storage/nvme5/new_clones/ASP/merlin_shadowsocks' &
git clone https://github.com/misterch0c/APT34 '/storage/nvme5/new_clones/ASP/APT34' &
git clone https://github.com/howardchn/location-to-phone-number '/storage/nvme5/new_clones/ASP/location-to-phone-number' &
git clone https://github.com/rcdmk/aspJSON '/storage/nvme5/new_clones/ASP/aspJSON' &
git clone https://github.com/kyriosli/koolshare-aliddns '/storage/nvme5/new_clones/ASP/koolshare-aliddns' &
git clone https://github.com/Unity-Technologies/AddressableAssetsWebinar '/storage/nvme5/new_clones/ASP/AddressableAssetsWebinar' &
git clone https://github.com/merttasci/weapons4pentester '/storage/nvme5/new_clones/ASP/weapons4pentester' &
git clone https://github.com/millerc3/Marching-Cubes '/storage/nvme5/new_clones/ASP/Marching-Cubes' &
git clone https://github.com/Jackysi/advancedtomato-gui '/storage/nvme5/new_clones/ASP/advancedtomato-gui' &
git clone https://github.com/oazabir/SQLServerPerformanceDashboard '/storage/nvme5/new_clones/ASP/SQLServerPerformanceDashboard' &
git clone https://github.com/everstu/Koolcenter_alist '/storage/nvme5/new_clones/ASP/Koolcenter_alist' &
git clone https://github.com/SWRT-dev/softcenterarm '/storage/nvme5/new_clones/ASP/softcenterarm' &
git clone https://github.com/Ivan1ee/ashxLessSpy '/storage/nvme5/new_clones/ASP/ashxLessSpy' &
git clone https://github.com/coldstone/easyasp '/storage/nvme5/new_clones/ASP/easyasp' &
git clone https://github.com/stangelid/oposum '/storage/nvme5/new_clones/ASP/oposum' &
git clone https://github.com/borjmz/aspx-reverse-shell '/storage/nvme5/new_clones/ASP/aspx-reverse-shell' &
git clone https://github.com/SURFBOARD-ONE/fancyss '/storage/nvme5/new_clones/ASP/fancyss' &
git clone https://github.com/todototry/AncientChinesePoemsDB '/storage/nvme5/new_clones/ASP/AncientChinesePoemsDB' &
git clone https://github.com/RubenCUR/ShaderGraph-Examples '/storage/nvme5/new_clones/ASP/ShaderGraph-Examples' &
git clone https://github.com/zusterben/plan_f '/storage/nvme5/new_clones/ASP/plan_f' &
git clone https://github.com/ArturoNereu/ShaderProfilingAndOptimization '/storage/nvme5/new_clones/ASP/ShaderProfilingAndOptimization' &
git clone https://github.com/Larryxi/MSSQL-SQLi-Labs '/storage/nvme5/new_clones/ASP/MSSQL-SQLi-Labs' &
git clone https://github.com/gerritvankuipers/aspjson '/storage/nvme5/new_clones/ASP/aspjson' &
git clone https://github.com/xiaopan233/AntSword-Cryption-WebShell '/storage/nvme5/new_clones/ASP/AntSword-Cryption-WebShell' &
git clone https://github.com/zblogcn/zblogasp '/storage/nvme5/new_clones/ASP/zblogasp' &
git clone https://github.com/DynamsoftRD/HTML5-Photo-Upload '/storage/nvme5/new_clones/ASP/HTML5-Photo-Upload' &
git clone https://github.com/vinaymancha/Subway-Surfers-AI '/storage/nvme5/new_clones/ASP/Subway-Surfers-AI' &
git clone https://github.com/zfergus/unity-examples '/storage/nvme5/new_clones/ASP/unity-examples' &
git clone https://github.com/koolshare/ttsoft '/storage/nvme5/new_clones/ASP/ttsoft' &
git clone https://github.com/SWRT-dev/softcentermips '/storage/nvme5/new_clones/ASP/softcentermips' &
git clone https://github.com/sadoneli/merlin380-qiandao '/storage/nvme5/new_clones/ASP/merlin380-qiandao' &
git clone https://github.com/aspLite/aspLite '/storage/nvme5/new_clones/ASP/aspLite' &
git clone https://github.com/ustwo/ReplayKitUnityBridge '/storage/nvme5/new_clones/ASP/ReplayKitUnityBridge' &
git clone https://github.com/Badgerdox/AddressableAsset-HowTo '/storage/nvme5/new_clones/ASP/AddressableAsset-HowTo' &
git clone https://github.com/cybercritic/City-Generator '/storage/nvme5/new_clones/ASP/City-Generator' &
git clone https://github.com/david-mark/My-Library '/storage/nvme5/new_clones/ASP/My-Library' &
git clone https://github.com/JackStouffer/Violent-Python '/storage/nvme5/new_clones/ASP/Violent-Python' &
git clone https://github.com/sdesapio/Classic-ASP-VBScript-OAuth '/storage/nvme5/new_clones/ASP/Classic-ASP-VBScript-OAuth' &
git clone https://github.com/bbsec3/ledesoft '/storage/nvme5/new_clones/ASP/ledesoft' &
git clone https://github.com/PentestHub/PriviledgeBook '/storage/nvme5/new_clones/ASP/PriviledgeBook' &
git clone https://github.com/MangoSister/SPHFluid '/storage/nvme5/new_clones/ASP/SPHFluid' &
git clone https://github.com/zoecarver/unityWS '/storage/nvme5/new_clones/ASP/unityWS' &
git clone https://github.com/hrbrmstr/rstudioconf2017 '/storage/nvme5/new_clones/ASP/rstudioconf2017' &
git clone https://github.com/undefinedv/ZF-system '/storage/nvme5/new_clones/ASP/ZF-system' &
git clone https://github.com/superpikar/learn-classic-asp '/storage/nvme5/new_clones/ASP/learn-classic-asp' &
git clone https://github.com/Ivan1ee/asmxLessSpy '/storage/nvme5/new_clones/ASP/asmxLessSpy' &
git clone https://github.com/pms67/ControlSystemDesign-Tutorial '/storage/nvme5/new_clones/ASP/ControlSystemDesign-Tutorial' &
git clone https://github.com/Vicebery/Student-Management-System '/storage/nvme5/new_clones/ASP/Student-Management-System' &
git clone https://github.com/dwProjectark/Digimon-World-Project-Ark '/storage/nvme5/new_clones/ASP/Digimon-World-Project-Ark' &
git clone https://github.com/iAladdin/koolss '/storage/nvme5/new_clones/ASP/koolss' &
git clone https://github.com/SWRT-dev/softcenterarm64 '/storage/nvme5/new_clones/ASP/softcenterarm64' &
git clone https://github.com/tutsplus/shockingly-good-2d-lightning-effects-unity '/storage/nvme5/new_clones/ASP/shockingly-good-2d-lightning-effects-unity' &
git clone https://github.com/SteveSanderson/Deleporter '/storage/nvme5/new_clones/ASP/Deleporter' &
git clone https://github.com/NetEase/pomelo-unitychat-socket '/storage/nvme5/new_clones/ASP/pomelo-unitychat-socket' &
git clone https://github.com/SWRT-dev/softcenterarmng '/storage/nvme5/new_clones/ASP/softcenterarmng' &
git clone https://github.com/koolshare/merlin-ssserver '/storage/nvme5/new_clones/ASP/merlin-ssserver' &
git clone https://github.com/firebelley/GameFeel '/storage/nvme5/new_clones/ASP/GameFeel' &
git clone https://github.com/davecan/Sane '/storage/nvme5/new_clones/ASP/Sane' &
git clone https://github.com/Dheer-Rajpoot/ASP.NET '/storage/nvme5/new_clones/ASP/ASP.NET' &
git clone https://github.com/HappySlice/hide-escape '/storage/nvme5/new_clones/ASP/hide-escape' &
git clone https://github.com/shanta3220/Riko-The-Adventurer '/storage/nvme5/new_clones/ASP/Riko-The-Adventurer' &
git clone https://github.com/EelcoKoster/ReverseProxySiteExtension '/storage/nvme5/new_clones/ASP/ReverseProxySiteExtension' &
git clone https://github.com/rpeterclark/aspunit '/storage/nvme5/new_clones/ASP/aspunit' &
git clone https://github.com/KalikoCMS/DemoSite.Mvc '/storage/nvme5/new_clones/ASP/DemoSite.Mvc' &
git clone https://github.com/tugrul/aspjson '/storage/nvme5/new_clones/ASP/aspjson' &
git clone https://github.com/mckapur/SPCSAISelfDrivingCar '/storage/nvme5/new_clones/ASP/SPCSAISelfDrivingCar' &
git clone https://github.com/zendesk/classic_asp_jwt '/storage/nvme5/new_clones/ASP/classic_asp_jwt' &
git clone https://github.com/DukeChiang/FGUI2ET '/storage/nvme5/new_clones/ASP/FGUI2ET' &
git clone https://github.com/kamranahmedse/brainza-fps-unity3d-game '/storage/nvme5/new_clones/ASP/brainza-fps-unity3d-game' &
git clone https://github.com/mritd/koolshare-gdddns '/storage/nvme5/new_clones/ASP/koolshare-gdddns' &
git clone https://github.com/lucascassiano/Processing-to-Unity '/storage/nvme5/new_clones/ASP/Processing-to-Unity' &
git clone https://github.com/NataliaDeng/Data-Collection-Web-APP '/storage/nvme5/new_clones/ASP/Data-Collection-Web-APP' &
git clone https://github.com/johnnliu/UserCustomActionsConfigPage '/storage/nvme5/new_clones/ASP/UserCustomActionsConfigPage' &
git clone https://github.com/hussien89aa/Alrubaye.net '/storage/nvme5/new_clones/ASP/Alrubaye.net' &
git clone https://github.com/Andrew-Stebel/Unity-SUMO '/storage/nvme5/new_clones/ASP/Unity-SUMO' &
git clone https://github.com/HardlyDifficult/MultiplayerGameProgramming '/storage/nvme5/new_clones/ASP/MultiplayerGameProgramming' &
git clone https://github.com/grCod/poly '/storage/nvme5/new_clones/ASP/poly' &
git clone https://github.com/zusterben/plan_a '/storage/nvme5/new_clones/ASP/plan_a' &
git clone https://github.com/akitaonrails/ASP_Classic_WebForm '/storage/nvme5/new_clones/ASP/ASP_Classic_WebForm' &
git clone https://github.com/AtiLion/AtiRoNya '/storage/nvme5/new_clones/ASP/AtiRoNya' &
git clone https://github.com/fivestrong/v2ray_switch '/storage/nvme5/new_clones/ASP/v2ray_switch' &
git clone https://github.com/tshwangq/IISDeploy '/storage/nvme5/new_clones/ASP/IISDeploy' &
git clone https://github.com/Didox/torne-se-programador '/storage/nvme5/new_clones/ASP/torne-se-programador' &
git clone https://github.com/CompleteUnityDeveloper/11-Ahoy-Matey-Original '/storage/nvme5/new_clones/ASP/11-Ahoy-Matey-Original' &
git clone https://github.com/csdz/SnapToSnap '/storage/nvme5/new_clones/ASP/SnapToSnap' &
git clone https://github.com/Prastiwar/ECS2048 '/storage/nvme5/new_clones/ASP/ECS2048' &
git clone https://github.com/jsztompka/MultiAgent-PPO '/storage/nvme5/new_clones/ASP/MultiAgent-PPO' &
git clone https://github.com/torneseumprogramador/estudos '/storage/nvme5/new_clones/ASP/estudos' &
git clone https://github.com/Mohan-Zhang-u/HungryBall '/storage/nvme5/new_clones/ASP/HungryBall' &
git clone https://github.com/nirzaf/HospitalSystem '/storage/nvme5/new_clones/ASP/HospitalSystem' &
git clone https://github.com/linkease/merlin_ddnsto '/storage/nvme5/new_clones/ASP/merlin_ddnsto' &
git clone https://github.com/MrFlick/whats-in-a-gif '/storage/nvme5/new_clones/ASP/whats-in-a-gif' &
git clone https://github.com/edengold/gomoku '/storage/nvme5/new_clones/ASP/gomoku' &
git clone https://github.com/grCod/webshells '/storage/nvme5/new_clones/ASP/webshells' &
git clone https://github.com/spbooks/ASPNET4 '/storage/nvme5/new_clones/ASP/ASPNET4' &
git clone https://github.com/anderssonjohan/Nettest '/storage/nvme5/new_clones/ASP/Nettest' &
git clone https://github.com/rcdmk/aspZip '/storage/nvme5/new_clones/ASP/aspZip' &
git clone https://github.com/Sebastian-Schuchmann/A.I.-Shooting-Game-ML-Agents-Unity-Example '/storage/nvme5/new_clones/ASP/A.I.-Shooting-Game-ML-Agents-Unity-Example' &
git clone https://github.com/khopaderahul01/vehicletracking '/storage/nvme5/new_clones/ASP/vehicletracking' &
git clone https://github.com/zsxsoft/JWT-ASP '/storage/nvme5/new_clones/ASP/JWT-ASP' &
git clone https://github.com/Magic-Xin/mips '/storage/nvme5/new_clones/ASP/mips' &
git clone https://github.com/KylinC/FPS-Game '/storage/nvme5/new_clones/ASP/FPS-Game' &
git clone https://github.com/nviet/simple-asp-file-manager '/storage/nvme5/new_clones/ASP/simple-asp-file-manager' &
git clone https://github.com/PrateekAdhikaree/Nightmares '/storage/nvme5/new_clones/ASP/Nightmares' &
git clone https://github.com/thatcoderguy/OWASP-Faux-Bank-ClassicASP '/storage/nvme5/new_clones/ASP/OWASP-Faux-Bank-ClassicASP' &
git clone https://github.com/WhitePetal/Unity-Desktop-Wizard '/storage/nvme5/new_clones/ASP/Unity-Desktop-Wizard' &
git clone https://github.com/PetrSnobelt/UmbracoOAuthLogin '/storage/nvme5/new_clones/ASP/UmbracoOAuthLogin' &
git clone https://github.com/codewithkyle/Unity-Tutorials '/storage/nvme5/new_clones/ASP/Unity-Tutorials' &
git clone https://github.com/AshV/SmartLocatorHackathon '/storage/nvme5/new_clones/ASP/SmartLocatorHackathon' &
git clone https://github.com/charlesbarros/VoxelEngine '/storage/nvme5/new_clones/ASP/VoxelEngine' &
git clone https://github.com/Skatterbrainz/CMWT '/storage/nvme5/new_clones/ASP/CMWT' &
git clone https://github.com/elmagnificogi/merlin-koolshare-ss-for-mipsel '/storage/nvme5/new_clones/ASP/merlin-koolshare-ss-for-mipsel' &
git clone https://github.com/sysboss/IISADMPWD '/storage/nvme5/new_clones/ASP/IISADMPWD' &
git clone https://github.com/ASP-Ajaxed/asp-ajaxed '/storage/nvme5/new_clones/ASP/asp-ajaxed' &
git clone https://github.com/deercoder/0-tech-notes '/storage/nvme5/new_clones/ASP/0-tech-notes' &
git clone https://github.com/zhongsheng23/WebShell '/storage/nvme5/new_clones/ASP/WebShell' &
git clone https://github.com/UnderGear/Klonamari '/storage/nvme5/new_clones/ASP/Klonamari' &
git clone https://github.com/ekede/WTS-Classic-ASP-MVC-Framework '/storage/nvme5/new_clones/ASP/WTS-Classic-ASP-MVC-Framework' &
git clone https://github.com/koolshare/merlin-aria2 '/storage/nvme5/new_clones/ASP/merlin-aria2' &
git clone https://github.com/imaculate/Scheme '/storage/nvme5/new_clones/ASP/Scheme' &
git clone https://github.com/scnu-sloth/hsctf-2019-freshmen '/storage/nvme5/new_clones/ASP/hsctf-2019-freshmen' &
git clone https://github.com/le4f/aspexec '/storage/nvme5/new_clones/ASP/aspexec' &
git clone https://github.com/dmeagor/ClassicASP-FirePHP '/storage/nvme5/new_clones/ASP/ClassicASP-FirePHP' &
git clone https://github.com/nostalgicbear/FootballGame '/storage/nvme5/new_clones/ASP/FootballGame' &
git clone https://github.com/adoprog/Sitecore-Deployment-Helpers '/storage/nvme5/new_clones/ASP/Sitecore-Deployment-Helpers' &
git clone https://github.com/wolf46russia/ASPXSpy-sh3ll '/storage/nvme5/new_clones/ASP/ASPXSpy-sh3ll' &
git clone https://github.com/NetEase/pomelo-unitychat '/storage/nvme5/new_clones/ASP/pomelo-unitychat' &
git clone https://github.com/shipcod3/sploitchits '/storage/nvme5/new_clones/ASP/sploitchits' &
git clone https://github.com/koolshare/qcasoft '/storage/nvme5/new_clones/ASP/qcasoft' &
git clone https://github.com/letsRobot/LetsRobot-Unity '/storage/nvme5/new_clones/ASP/LetsRobot-Unity' &
git clone https://github.com/codemaker2015/Line-Graph '/storage/nvme5/new_clones/ASP/Line-Graph' &
git clone https://github.com/jeremylcarter/Clapper '/storage/nvme5/new_clones/ASP/Clapper' &
git clone https://github.com/iperov/Tensoid '/storage/nvme5/new_clones/ASP/Tensoid' &
git clone https://github.com/OWASP/DotNet_ANSA '/storage/nvme5/new_clones/ASP/DotNet_ANSA' &
git clone https://github.com/tavik000/MazeGameAI '/storage/nvme5/new_clones/ASP/MazeGameAI' &
git clone https://github.com/joeythelantern/UnetMovement '/storage/nvme5/new_clones/ASP/UnetMovement' &
git clone https://github.com/bbsecxyz/koolv2ray '/storage/nvme5/new_clones/ASP/koolv2ray' &
git clone https://github.com/zs5460/Classic-ASP-Common-Function '/storage/nvme5/new_clones/ASP/Classic-ASP-Common-Function' &
git clone https://github.com/yoshi295295/rblx-scripts '/storage/nvme5/new_clones/ASP/rblx-scripts' &
git clone https://github.com/Bekwnn/Unity-Shaders '/storage/nvme5/new_clones/ASP/Unity-Shaders' &
git clone https://github.com/andrewmacquarrie/ProjMap64 '/storage/nvme5/new_clones/ASP/ProjMap64' &
git clone https://github.com/brcontainer/html2canvas-csharp-proxy '/storage/nvme5/new_clones/ASP/html2canvas-csharp-proxy' &
git clone https://github.com/Zhang-Sir/advancedtomato-gui-chinese '/storage/nvme5/new_clones/ASP/advancedtomato-gui-chinese' &
git clone https://github.com/Cymmetria/micros_honeypot '/storage/nvme5/new_clones/ASP/micros_honeypot' &
git clone https://github.com/kennux/cubicworld '/storage/nvme5/new_clones/ASP/cubicworld' &
git clone https://github.com/darkhorse07232020/spservices.js-example '/storage/nvme5/new_clones/ASP/spservices.js-example' &
git clone https://github.com/pronaypeddiraju/Memory-Game '/storage/nvme5/new_clones/ASP/Memory-Game' &
git clone https://github.com/doctording/pomelo_unity_multi_room_chat '/storage/nvme5/new_clones/ASP/pomelo_unity_multi_room_chat' &
git clone https://github.com/nu1ee/softcenter '/storage/nvme5/new_clones/ASP/softcenter' &
git clone https://github.com/zeirishin/phpvbs '/storage/nvme5/new_clones/ASP/phpvbs' &
git clone https://github.com/00575/padavan '/storage/nvme5/new_clones/ASP/padavan' &
git clone https://github.com/ritwickdey/WeMate '/storage/nvme5/new_clones/ASP/WeMate' &
git clone https://github.com/FearlessHyena/unity-basic-grpc '/storage/nvme5/new_clones/ASP/unity-basic-grpc' &
git clone https://github.com/HassanAfnan/Serving-Hands '/storage/nvme5/new_clones/ASP/Serving-Hands' &
git clone https://github.com/yLong765/Mahjong '/storage/nvme5/new_clones/ASP/Mahjong' &
git clone https://github.com/sapientcoder/QuickCAML '/storage/nvme5/new_clones/ASP/QuickCAML' &
git clone https://github.com/modux/ShortShells '/storage/nvme5/new_clones/ASP/ShortShells' &
git clone https://github.com/PetersonDave/SinglePageAppDemo '/storage/nvme5/new_clones/ASP/SinglePageAppDemo' &
git clone https://github.com/rcdmk/aspXls '/storage/nvme5/new_clones/ASP/aspXls' &
git clone https://github.com/fernandoacorreia/StaticAuthSample '/storage/nvme5/new_clones/ASP/StaticAuthSample' &
git clone https://github.com/koolshare/merlin_frpc '/storage/nvme5/new_clones/ASP/merlin_frpc' &
git clone https://github.com/pixelflag/EasingTest '/storage/nvme5/new_clones/ASP/EasingTest' &
git clone https://github.com/GergesBernaba1/LawyerSys '/storage/nvme5/new_clones/ASP/LawyerSys' &
git clone https://github.com/richdizz/OfficeGraphExplorer '/storage/nvme5/new_clones/ASP/OfficeGraphExplorer' &
git clone https://github.com/Spikef/NodeAsp '/storage/nvme5/new_clones/ASP/NodeAsp' &
git clone https://github.com/moranyijiu/ASP-MVC-W3school- '/storage/nvme5/new_clones/ASP/ASP-MVC-W3school-' &
git clone https://github.com/textmate/asp.tmbundle '/storage/nvme5/new_clones/ASP/asp.tmbundle' &
git clone https://github.com/fedecheller/ExtNetModernUI '/storage/nvme5/new_clones/ASP/ExtNetModernUI' &
git clone https://github.com/Nitij/DotNetAngularChat '/storage/nvme5/new_clones/ASP/DotNetAngularChat' &
git clone https://github.com/idlehanz/UT-Substation-Simulator '/storage/nvme5/new_clones/ASP/UT-Substation-Simulator' &
git clone https://github.com/AlfonsoML/CKEditorUploader '/storage/nvme5/new_clones/ASP/CKEditorUploader' &
git clone https://github.com/ShawnZhou2000/Knowledge-management-system '/storage/nvme5/new_clones/ASP/Knowledge-management-system' &
git clone https://github.com/Xrzser/music-website '/storage/nvme5/new_clones/ASP/music-website' &
git clone https://github.com/PieterCooreman/QuickerSite '/storage/nvme5/new_clones/ASP/QuickerSite' &
git clone https://github.com/koolshare/signdog_hnd '/storage/nvme5/new_clones/ASP/signdog_hnd' &
git clone https://github.com/ictmanagement/redsysHMAC256_API_ASP '/storage/nvme5/new_clones/ASP/redsysHMAC256_API_ASP' &
git clone https://github.com/Thanasis1101/CubeRun '/storage/nvme5/new_clones/ASP/CubeRun' &
git clone https://github.com/bonniesjli/DQN_SR '/storage/nvme5/new_clones/ASP/DQN_SR' &
git clone https://github.com/blakeim/Unity-Fire-Spread-Simulation '/storage/nvme5/new_clones/ASP/Unity-Fire-Spread-Simulation' &
git clone https://github.com/RetailGameSourceCode/BOB '/storage/nvme5/new_clones/ASP/BOB' &
git clone https://github.com/kendemu/gym-ros '/storage/nvme5/new_clones/ASP/gym-ros' &
git clone https://github.com/marcelloaborges/Soccer-PPO '/storage/nvme5/new_clones/ASP/Soccer-PPO' &
git clone https://github.com/robrohan/MvCasp '/storage/nvme5/new_clones/ASP/MvCasp' &
git clone https://github.com/verysync/verysync-merlin '/storage/nvme5/new_clones/ASP/verysync-merlin' &
git clone https://github.com/Hanyoma/UnityCardGame '/storage/nvme5/new_clones/ASP/UnityCardGame' &
git clone https://github.com/dluxem/LiberumASP '/storage/nvme5/new_clones/ASP/LiberumASP' &
git clone https://github.com/oneoneplus/webshell '/storage/nvme5/new_clones/ASP/webshell' &
git clone https://github.com/bdogan/iyzico-iyzipay-classic-asp '/storage/nvme5/new_clones/ASP/iyzico-iyzipay-classic-asp' &
git clone https://github.com/klaus201192239/BookRentalSystem '/storage/nvme5/new_clones/ASP/BookRentalSystem' &
git clone https://github.com/anitakym/STMWebsite '/storage/nvme5/new_clones/ASP/STMWebsite' &
git clone https://github.com/Mr-strlen/BCI_VR_Game_Demo '/storage/nvme5/new_clones/ASP/BCI_VR_Game_Demo' &
git clone https://github.com/bhasha102/-Internet-Banking-Fraud-Detection-System-Using-HMM '/storage/nvme5/new_clones/ASP/-Internet-Banking-Fraud-Detection-System-Using-HMM' &
git clone https://github.com/Tobias64/Mario-Multiplayer-Unity3d '/storage/nvme5/new_clones/ASP/Mario-Multiplayer-Unity3d' &
git clone https://github.com/bonniesjli/PPO_Reacher '/storage/nvme5/new_clones/ASP/PPO_Reacher' &
git clone https://github.com/moetaku/fancyss_arm '/storage/nvme5/new_clones/ASP/fancyss_arm' &
git clone https://github.com/LaCreArthur/RodyAIbiza '/storage/nvme5/new_clones/ASP/RodyAIbiza' &
git clone https://github.com/yangbaopeng/ashx_webshell '/storage/nvme5/new_clones/ASP/ashx_webshell' &
git clone https://github.com/puterjam/pjblog '/storage/nvme5/new_clones/ASP/pjblog' &
git clone https://github.com/jtalbert123/Cell-Lab-Remake '/storage/nvme5/new_clones/ASP/Cell-Lab-Remake' &
git clone https://github.com/vertigooooo/Unity3D-fps-game '/storage/nvme5/new_clones/ASP/Unity3D-fps-game' &
git clone https://github.com/surger1/BeadSurge '/storage/nvme5/new_clones/ASP/BeadSurge' &
git clone https://github.com/Maplecool123/xunjia0201 '/storage/nvme5/new_clones/ASP/xunjia0201' &
git clone https://github.com/nfzhou/lp-contest '/storage/nvme5/new_clones/ASP/lp-contest' &
git clone https://github.com/bzaar/odict '/storage/nvme5/new_clones/ASP/odict' &
git clone https://github.com/wescules/Project-Management-Web-App '/storage/nvme5/new_clones/ASP/Project-Management-Web-App' &
git clone https://github.com/bonniesjli/MADDPG_Tennis '/storage/nvme5/new_clones/ASP/MADDPG_Tennis' &
git clone https://github.com/purtuga/SPImages '/storage/nvme5/new_clones/ASP/SPImages' &
git clone https://github.com/graycrawford/Novae '/storage/nvme5/new_clones/ASP/Novae' &
git clone https://github.com/cloudfoundry-incubator/NET-sample-app '/storage/nvme5/new_clones/ASP/NET-sample-app' &
git clone https://github.com/agross/netopenspace '/storage/nvme5/new_clones/ASP/netopenspace' &
git clone https://github.com/Nemivyasis/Underwater-Environment '/storage/nvme5/new_clones/ASP/Underwater-Environment' &
git clone https://github.com/sugi-cho/Triangles100x100x100 '/storage/nvme5/new_clones/ASP/Triangles100x100x100' &
git clone https://github.com/klpatil/CacheTuner '/storage/nvme5/new_clones/ASP/CacheTuner' &
git clone https://github.com/shenjia/saolei.net-2008 '/storage/nvme5/new_clones/ASP/saolei.net-2008' &
git clone https://github.com/HustLion/pomelo-chat-unity-socket '/storage/nvme5/new_clones/ASP/pomelo-chat-unity-socket' &
git clone https://github.com/shadowfox87/ygopro2 '/storage/nvme5/new_clones/ASP/ygopro2' &
git clone https://github.com/KSAMissionCtrl/FlightTracker '/storage/nvme5/new_clones/ASP/FlightTracker' &
git clone https://github.com/koolshare/merlin_frps '/storage/nvme5/new_clones/ASP/merlin_frps' &
git clone https://github.com/jometzg/classicaspdocker '/storage/nvme5/new_clones/ASP/classicaspdocker' &
git clone https://github.com/aspjs/aspjs '/storage/nvme5/new_clones/ASP/aspjs' &
git clone https://github.com/Encosia/Encosia-Samples-jQuery-Page-Method '/storage/nvme5/new_clones/ASP/Encosia-Samples-jQuery-Page-Method' &
git clone https://github.com/GetSomeRest/tutorial-aspnet-view.and.data.api '/storage/nvme5/new_clones/ASP/tutorial-aspnet-view.and.data.api' &
git clone https://github.com/DigitalEpidemic/fps-multiplayer-unity '/storage/nvme5/new_clones/ASP/fps-multiplayer-unity' &
git clone https://github.com/deekayen/ansible-aws-windows '/storage/nvme5/new_clones/ASP/ansible-aws-windows' &
git clone https://github.com/babylife/KoolProxy-Rule '/storage/nvme5/new_clones/ASP/KoolProxy-Rule' &
git clone https://github.com/Collegiennes/volkenessen '/storage/nvme5/new_clones/ASP/volkenessen' &
git clone https://github.com/HearthSim/unity-examples '/storage/nvme5/new_clones/ASP/unity-examples' &
git clone https://github.com/sijiaxu/Adaptive_Game_AI_Demo '/storage/nvme5/new_clones/ASP/Adaptive_Game_AI_Demo' &
git clone https://github.com/davidawad/IronMyo '/storage/nvme5/new_clones/ASP/IronMyo' &
git clone https://github.com/kaorun55/Kinect2UnityWrapper '/storage/nvme5/new_clones/ASP/Kinect2UnityWrapper' &
git clone https://github.com/Agile2010/Wina '/storage/nvme5/new_clones/ASP/Wina' &
git clone https://github.com/ZerlenZhang/ChartRoom '/storage/nvme5/new_clones/ASP/ChartRoom' &
git clone https://github.com/koolshare/merlin_serverChan '/storage/nvme5/new_clones/ASP/merlin_serverChan' &
git clone https://github.com/flyhigherpi/filebrowser '/storage/nvme5/new_clones/ASP/filebrowser' &
git clone https://github.com/akshaykhanna/Hotel-Booking-website '/storage/nvme5/new_clones/ASP/Hotel-Booking-website' &
git clone https://github.com/leandroribeiro/ASPJSON '/storage/nvme5/new_clones/ASP/ASPJSON' &
git clone https://github.com/donma/TelegramNotifier '/storage/nvme5/new_clones/ASP/TelegramNotifier' &
git clone https://github.com/dmg9626/This-Is-Trump '/storage/nvme5/new_clones/ASP/This-Is-Trump' &
git clone https://github.com/sergiyd/jQuery-File-Upload_ASP.NET-Upload-Handler '/storage/nvme5/new_clones/ASP/jQuery-File-Upload_ASP.NET-Upload-Handler' &
git clone https://github.com/dudleycodes/ClassicASP-MSSQLSanitizer '/storage/nvme5/new_clones/ASP/ClassicASP-MSSQLSanitizer' &
git clone https://github.com/rcdmk/classicAspUnit '/storage/nvme5/new_clones/ASP/classicAspUnit' &
git clone https://github.com/stephenmcd/aspchat '/storage/nvme5/new_clones/ASP/aspchat' &
git clone https://github.com/linkease/merlin_EasyExplorer '/storage/nvme5/new_clones/ASP/merlin_EasyExplorer' &
git clone https://github.com/tcOops/Library '/storage/nvme5/new_clones/ASP/Library' &
git clone https://github.com/xtephan/Cars '/storage/nvme5/new_clones/ASP/Cars' &
git clone https://github.com/fireside21/vscode-cshtml '/storage/nvme5/new_clones/ASP/vscode-cshtml' &
git clone https://github.com/SUSTech-CS309-Mozart-A-Musical-Game/Mozart-A-Music-Game '/storage/nvme5/new_clones/ASP/Mozart-A-Music-Game' &
git clone https://github.com/Demiguise/Unitycraft3 '/storage/nvme5/new_clones/ASP/Unitycraft3' &
git clone https://github.com/dthunziker/sitecore-font-icon-picker-field '/storage/nvme5/new_clones/ASP/sitecore-font-icon-picker-field' &
git clone https://github.com/chihoxtra/continuous_actions_rl '/storage/nvme5/new_clones/ASP/continuous_actions_rl' &
git clone https://github.com/leixd1994/Wine-TIM-2.1.0 '/storage/nvme5/new_clones/ASP/Wine-TIM-2.1.0' &
git clone https://github.com/Komal7209/hotel-booking-system '/storage/nvme5/new_clones/ASP/hotel-booking-system' &
git clone https://github.com/alonecat06/ACTGame '/storage/nvme5/new_clones/ASP/ACTGame' &
git clone https://github.com/giordi91/Unity-Tutorials '/storage/nvme5/new_clones/ASP/Unity-Tutorials' &
git clone https://github.com/SWRT-dev/softcentermipsle '/storage/nvme5/new_clones/ASP/softcentermipsle' &
git clone https://github.com/linnananan/MagicDrawingBoard '/storage/nvme5/new_clones/ASP/MagicDrawingBoard' &
git clone https://github.com/TairinySimeonato/WebAuditing '/storage/nvme5/new_clones/ASP/WebAuditing' &
git clone https://github.com/XMJGame/RadarTool '/storage/nvme5/new_clones/ASP/RadarTool' &
git clone https://github.com/gesture-based-ui-development/voice-controlled-millionaire '/storage/nvme5/new_clones/ASP/voice-controlled-millionaire' &
git clone https://github.com/HikaruChang/telespeedup-koolsoft '/storage/nvme5/new_clones/ASP/telespeedup-koolsoft' &
git clone https://github.com/jaxee/perfit '/storage/nvme5/new_clones/ASP/perfit' &
git clone https://github.com/koolshare/merlin-aliddns '/storage/nvme5/new_clones/ASP/merlin-aliddns' &
git clone https://github.com/Deams51/JerkEngine '/storage/nvme5/new_clones/ASP/JerkEngine' &
git clone https://github.com/se7enmuting/koolshare-cfddns '/storage/nvme5/new_clones/ASP/koolshare-cfddns' &
git clone https://github.com/selfsame/clojurecup2015 '/storage/nvme5/new_clones/ASP/clojurecup2015' &
git clone https://github.com/dbatesx/asp-utilities '/storage/nvme5/new_clones/ASP/asp-utilities' &
git clone https://github.com/zhangyujia0506/asp.net_simple_jiaoxueguanlixitong '/storage/nvme5/new_clones/ASP/asp.net_simple_jiaoxueguanlixitong' &
git clone https://github.com/webaware/ASP-JSONEncode '/storage/nvme5/new_clones/ASP/ASP-JSONEncode' &
git clone https://github.com/techbrij/star-bus '/storage/nvme5/new_clones/ASP/star-bus' &
git clone https://github.com/yhangang/StockMining '/storage/nvme5/new_clones/ASP/StockMining' &
git clone https://github.com/mtconnect/Unity3D '/storage/nvme5/new_clones/ASP/Unity3D' &
git clone https://github.com/wangchll/kuainiao_for_xiaobao '/storage/nvme5/new_clones/ASP/kuainiao_for_xiaobao' &
git clone https://github.com/yoheigon/sagemaker-unity-mlagents '/storage/nvme5/new_clones/ASP/sagemaker-unity-mlagents' &
git clone https://github.com/EndlessBeard/PerlinVisualizer '/storage/nvme5/new_clones/ASP/PerlinVisualizer' &
git clone https://github.com/Encosia/Encosia-Samples-WebForms-jQuery-Validation '/storage/nvme5/new_clones/ASP/Encosia-Samples-WebForms-jQuery-Validation' &
git clone https://github.com/issamalidev/bs.pagination.js '/storage/nvme5/new_clones/ASP/bs.pagination.js' &
git clone https://github.com/Perry961002/Asp.net-Course-Design '/storage/nvme5/new_clones/ASP/Asp.net-Course-Design' &
git clone https://github.com/nbagul-ITC/Vehicle-Simulation-Toolkit '/storage/nvme5/new_clones/ASP/Vehicle-Simulation-Toolkit' &
git clone https://github.com/rcdmk/ASPGoogleCharts '/storage/nvme5/new_clones/ASP/ASPGoogleCharts' &
git clone https://github.com/hminaya/DevDomWeb '/storage/nvme5/new_clones/ASP/DevDomWeb' &
git clone https://github.com/Yh793/Padavan-build '/storage/nvme5/new_clones/ASP/Padavan-build' &
git clone https://github.com/AnnaAD/DungeonGameUnity '/storage/nvme5/new_clones/ASP/DungeonGameUnity' &
git clone https://github.com/nvthuong1996/qldt_overload_public '/storage/nvme5/new_clones/ASP/qldt_overload_public' &
git clone https://github.com/opendns/SampleBlockPages '/storage/nvme5/new_clones/ASP/SampleBlockPages' &
git clone https://github.com/0xAnalyst/webshells '/storage/nvme5/new_clones/ASP/webshells' &
git clone https://github.com/wfkwdw/fancyss '/storage/nvme5/new_clones/ASP/fancyss' &
git clone https://github.com/Phylliida/P2PDraw '/storage/nvme5/new_clones/ASP/P2PDraw' &
git clone https://github.com/vitechliu/Unity-Arduino-AutoGate-Project '/storage/nvme5/new_clones/ASP/Unity-Arduino-AutoGate-Project' &
git clone https://github.com/3dcart/REST-API-Client '/storage/nvme5/new_clones/ASP/REST-API-Client' &
git clone https://github.com/GITHUB243884919/Unity3D_AI_2 '/storage/nvme5/new_clones/ASP/Unity3D_AI_2' &
git clone https://github.com/akidevcat/Procedural-Real-Scale-Planet-Generation-in-Real-Time '/storage/nvme5/new_clones/ASP/Procedural-Real-Scale-Planet-Generation-in-Real-Time' &
git clone https://github.com/hytcwangfang/FoodOrderSys '/storage/nvme5/new_clones/ASP/FoodOrderSys' &
git clone https://github.com/nickpinheiro/SharePointAppListData '/storage/nvme5/new_clones/ASP/SharePointAppListData' &
git clone https://github.com/DavidJoyceIre/Zurb-Foundation-Ecommerce-Template '/storage/nvme5/new_clones/ASP/Zurb-Foundation-Ecommerce-Template' &
git clone https://github.com/akitaonrails/ASP-Classic-XML-NoSQL '/storage/nvme5/new_clones/ASP/ASP-Classic-XML-NoSQL' &
git clone https://github.com/KalikoCMS/DemoSite.WebForms '/storage/nvme5/new_clones/ASP/DemoSite.WebForms' &
git clone https://github.com/iamkrut/Multiplayer-First-Person-Shooter-Prototype '/storage/nvme5/new_clones/ASP/Multiplayer-First-Person-Shooter-Prototype' &
git clone https://github.com/dwillis/shboom '/storage/nvme5/new_clones/ASP/shboom' &
git clone https://github.com/Apress/neural-networks-in-unity '/storage/nvme5/new_clones/ASP/neural-networks-in-unity' &
git clone https://github.com/yashvakil/Automated-Warehousing '/storage/nvme5/new_clones/ASP/Automated-Warehousing' &
git clone https://github.com/bonniesjli/icm '/storage/nvme5/new_clones/ASP/icm' &
git clone https://github.com/hasheminezhad/scrollsaver '/storage/nvme5/new_clones/ASP/scrollsaver' &
git clone https://github.com/cevio/PJBlog4 '/storage/nvme5/new_clones/ASP/PJBlog4' &
git clone https://github.com/shobhitsharma/stud '/storage/nvme5/new_clones/ASP/stud' &
git clone https://github.com/MatoPlus/GyroscopeMaze '/storage/nvme5/new_clones/ASP/GyroscopeMaze' &
git clone https://github.com/longinlin/mip3.1 '/storage/nvme5/new_clones/ASP/mip3.1' &
git clone https://github.com/twurman/Metroid '/storage/nvme5/new_clones/ASP/Metroid' &
git clone https://github.com/DhruvKinger/MovieTicketBooking '/storage/nvme5/new_clones/ASP/MovieTicketBooking' &
git clone https://github.com/SagarBChauhan/Hostel-Management-System '/storage/nvme5/new_clones/ASP/Hostel-Management-System' &
git clone https://github.com/hotchk155/hotchk155.github.io '/storage/nvme5/new_clones/ASP/hotchk155hub.io' &
git clone https://github.com/CanyonsCSClub/Spring2017 '/storage/nvme5/new_clones/ASP/Spring2017' &
git clone https://github.com/horaceyoung/NTUOSS-UnityGameWorkshop '/storage/nvme5/new_clones/ASP/NTUOSS-UnityGameWorkshop' &
git clone https://github.com/nikmd23/talk-website-secrets-exposed '/storage/nvme5/new_clones/ASP/talk-website-secrets-exposed' &
git clone https://github.com/eloipuertas/ES2013Dijous '/storage/nvme5/new_clones/ASP/ES2013Dijous' &
git clone https://github.com/RileyCodes/zhongnanhaifengyun '/storage/nvme5/new_clones/ASP/zhongnanhaifengyun' &
git clone https://github.com/zamiur/SuperMario64HD '/storage/nvme5/new_clones/ASP/SuperMario64HD' &
git clone https://github.com/joaosigno/classic-asp-utilities '/storage/nvme5/new_clones/ASP/classic-asp-utilities' &
git clone https://github.com/JingjingBNU/The-Learning-Sciences '/storage/nvme5/new_clones/ASP/The-Learning-Sciences' &
git clone https://github.com/brcontainer/simple-http-proxy-csharp '/storage/nvme5/new_clones/ASP/simple-http-proxy-csharp' &
git clone https://github.com/Greentwip/SuperMarioWorld '/storage/nvme5/new_clones/ASP/SuperMarioWorld' &
git clone https://github.com/OctoClo/OctopusProject '/storage/nvme5/new_clones/ASP/OctopusProject' &
git clone https://github.com/saber3371/Desktop-Awoo '/storage/nvme5/new_clones/ASP/Desktop-Awoo' &
git clone https://github.com/ugurkanates/BrainComputerInterface '/storage/nvme5/new_clones/ASP/BrainComputerInterface' &
git clone https://github.com/stucco/STIXExtractors '/storage/nvme5/new_clones/ASP/STIXExtractors' &
git clone https://github.com/CorianderLi/Gobang '/storage/nvme5/new_clones/ASP/Gobang' &
git clone https://github.com/thebobrhett/ShoreTel-Utils '/storage/nvme5/new_clones/ASP/ShoreTel-Utils' &
git clone https://github.com/hubi037/SnowSimulation '/storage/nvme5/new_clones/ASP/SnowSimulation' &
git clone https://github.com/andrewmanq/cs344 '/storage/nvme5/new_clones/ASP/cs344' &
git clone https://github.com/agavrel/42_Subjects '/storage/nvme5/new_clones/ASP/42_Subjects' &
git clone https://github.com/matheuseduardo/fpdf-asp '/storage/nvme5/new_clones/ASP/fpdf-asp' &
git clone https://github.com/ZeroChiLi/NetworkProject '/storage/nvme5/new_clones/ASP/NetworkProject' &
git clone https://github.com/DarkShadow04/Dictionary '/storage/nvme5/new_clones/ASP/Dictionary' &
git clone https://github.com/logono123/Forest-fight-of-Unity '/storage/nvme5/new_clones/ASP/Forest-fight-of-Unity' &
git clone https://github.com/hebiqi/Software-Engineering '/storage/nvme5/new_clones/ASP/Software-Engineering' &
git clone https://github.com/mkskelet/baba-is-fake '/storage/nvme5/new_clones/ASP/baba-is-fake' &
git clone https://github.com/likeU-ctrl-c/hanfuboke '/storage/nvme5/new_clones/ASP/hanfuboke' &
git clone https://github.com/jameswilson/asp-vbscript-cms '/storage/nvme5/new_clones/ASP/asp-vbscript-cms' &
git clone https://github.com/HiromuKato/StreetViewVR '/storage/nvme5/new_clones/ASP/StreetViewVR' &
git clone https://github.com/mattjuffs/slickcms-classic-asp '/storage/nvme5/new_clones/ASP/slickcms-classic-asp' &
git clone https://github.com/teamaton/toolbelt '/storage/nvme5/new_clones/ASP/toolbelt' &
git clone https://github.com/bdogan/hepsipay-asp '/storage/nvme5/new_clones/ASP/hepsipay-asp' &
git clone https://github.com/pablobd/ContinuousControl-D4PG '/storage/nvme5/new_clones/ASP/ContinuousControl-D4PG' &
git clone https://github.com/Aleqsd/GolfRevolution '/storage/nvme5/new_clones/ASP/GolfRevolution' &
git clone https://github.com/bitcoinwarrior1/Bitcoin-Double-Spend '/storage/nvme5/new_clones/ASP/Bitcoin-Double-Spend' &
git clone https://github.com/yingweiy/drlnd_project1_navigation '/storage/nvme5/new_clones/ASP/drlnd_project1_navigation' &
git clone https://github.com/feeyy/FoShan-Smart-City '/storage/nvme5/new_clones/ASP/FoShan-Smart-City' &
git clone https://github.com/Vallar/UNet-Server-Authoritative-Multiplayer-Tutorial '/storage/nvme5/new_clones/ASP/UNet-Server-Authoritative-Multiplayer-Tutorial' &
git clone https://github.com/jmccormack200/RPLidar-Unity-Simulator '/storage/nvme5/new_clones/ASP/RPLidar-Unity-Simulator' &
git clone https://github.com/Manisso/Manisso.asp '/storage/nvme5/new_clones/ASP/Manisso.asp' &
git clone https://github.com/JamesDunne/sql.ashx '/storage/nvme5/new_clones/ASP/sql.ashx' &
git clone https://github.com/sumuongit/asp-mvc-list-without-database-crud '/storage/nvme5/new_clones/ASP/asp-mvc-list-without-database-crud' &
git clone https://github.com/FelipeRes/Iti-Machine '/storage/nvme5/new_clones/ASP/Iti-Machine' &
git clone https://github.com/dingyi-History/xc-201507-aspmsgboard '/storage/nvme5/new_clones/ASP/xc-201507-aspmsgboard' &
git clone https://github.com/Morena96/Unity3D-Game '/storage/nvme5/new_clones/ASP/Unity3D-Game' &
