#!/bin/bash

git clone https://github.com/ColorlibHQ/AdminLTE '/storage/nvme5/new_clones/Astro/AdminLTE' &
git clone https://github.com/HubSpot/youmightnotneedjquery '/storage/nvme5/new_clones/Astro/youmightnotneedjquery' &
git clone https://github.com/andrew--r/frontend-case-studies '/storage/nvme5/new_clones/Astro/frontend-case-studies' &
git clone https://github.com/Lissy93/awesome-privacy '/storage/nvme5/new_clones/Astro/awesome-privacy' &
git clone https://github.com/roadmapsh/deprecated-version '/storage/nvme5/new_clones/Astro/deprecated-version' &
git clone https://github.com/onwidget/astrowind '/storage/nvme5/new_clones/Astro/astrowind' &
git clone https://github.com/neiesc/awesome-minimalist '/storage/nvme5/new_clones/Astro/awesome-minimalist' &
git clone https://github.com/nas5w/interview-guide '/storage/nvme5/new_clones/Astro/interview-guide' &
git clone https://github.com/Keycapsss/awesome-mechanical-keyboard '/storage/nvme5/new_clones/Astro/awesome-mechanical-keyboard' &
git clone https://github.com/satnaing/astro-paper '/storage/nvme5/new_clones/Astro/astro-paper' &
git clone https://github.com/hilmanski/freeStuffDev '/storage/nvme5/new_clones/Astro/freeStuffDev' &
git clone https://github.com/swagger-api/swagger.io-docs '/storage/nvme5/new_clones/Astro/swagger.io-docs' &
git clone https://github.com/chantastic/sites '/storage/nvme5/new_clones/Astro/sites' &
git clone https://github.com/bestofjs/javascript-risingstars '/storage/nvme5/new_clones/Astro/javascript-risingstars' &
git clone https://github.com/chrismwilliams/astro-theme-cactus '/storage/nvme5/new_clones/Astro/astro-theme-cactus' &
git clone https://github.com/manuelernestog/astrofy '/storage/nvme5/new_clones/Astro/astrofy' &
git clone https://github.com/jonasmerlin/astro-seo '/storage/nvme5/new_clones/Astro/astro-seo' &
git clone https://github.com/pseudoyu/yu-tools '/storage/nvme5/new_clones/Astro/yu-tools' &
git clone https://github.com/Jocs/jocs.github.io '/storage/nvme5/new_clones/Astro/jocshub.io' &
git clone https://github.com/markteekman/accessible-astro-starter '/storage/nvme5/new_clones/Astro/accessible-astro-starter' &
git clone https://github.com/tw93/weekly '/storage/nvme5/new_clones/Astro/weekly' &
git clone https://github.com/flexdinesh/blogster '/storage/nvme5/new_clones/Astro/blogster' &
git clone https://github.com/treefarmstudio/odyssey-theme '/storage/nvme5/new_clones/Astro/odyssey-theme' &
git clone https://github.com/mhyfritz/astro-landing-page '/storage/nvme5/new_clones/Astro/astro-landing-page' &
git clone https://github.com/one-aalam/astro-ink '/storage/nvme5/new_clones/Astro/astro-ink' &
git clone https://github.com/CSS-Tricks/serverless '/storage/nvme5/new_clones/Astro/serverless' &
git clone https://github.com/godruoyi/gblog '/storage/nvme5/new_clones/Astro/gblog' &
git clone https://github.com/codiume/orbit '/storage/nvme5/new_clones/Astro/orbit' &
git clone https://github.com/Charca/astro-blog-template '/storage/nvme5/new_clones/Astro/astro-blog-template' &
git clone https://github.com/cassidoo/blahg '/storage/nvme5/new_clones/Astro/blahg' &
git clone https://github.com/markteekman/accessible-astro-components '/storage/nvme5/new_clones/Astro/accessible-astro-components' &
git clone https://github.com/manasky/lorem.space '/storage/nvme5/new_clones/Astro/lorem.space' &
git clone https://github.com/NixOS/nixos-homepage '/storage/nvme5/new_clones/Astro/nixos-homepage' &
git clone https://github.com/cssninjaStudio/krypton '/storage/nvme5/new_clones/Astro/krypton' &
git clone https://github.com/kossnocorp/opensource.how '/storage/nvme5/new_clones/Astro/opensource.how' &
git clone https://github.com/SaudiOpenSourceCommunity/SaudiOSS '/storage/nvme5/new_clones/Astro/SaudiOSS' &
git clone https://github.com/sindresorhus/sindresorhus.github.com '/storage/nvme5/new_clones/Astro/sindresorhushub.com' &
git clone https://github.com/delucis/astro-embed '/storage/nvme5/new_clones/Astro/astro-embed' &
git clone https://github.com/geeksblabla/geeksblabla.community '/storage/nvme5/new_clones/Astro/geeksblabla.community' &
git clone https://github.com/craftzdog/craftzdog-uses '/storage/nvme5/new_clones/Astro/craftzdog-uses' &
git clone https://github.com/Nicell/loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ng '/storage/nvme5/new_clones/Astro/loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.ng' &
git clone https://github.com/Tailus-UI/astro-theme '/storage/nvme5/new_clones/Astro/astro-theme' &
git clone https://github.com/robertguss/Astro-Theme-Creek '/storage/nvme5/new_clones/Astro/Astro-Theme-Creek' &
git clone https://github.com/withastro/houston.astro.build '/storage/nvme5/new_clones/Astro/houston.astro.build' &
git clone https://github.com/Charca/astro-movies '/storage/nvme5/new_clones/Astro/astro-movies' &
git clone https://github.com/fairsource/fair.io '/storage/nvme5/new_clones/Astro/fair.io' &
git clone https://github.com/shaunchander/astro-pwa-starter '/storage/nvme5/new_clones/Astro/astro-pwa-starter' &
git clone https://github.com/iammatthias/com '/storage/nvme5/new_clones/Astro/com' &
git clone https://github.com/haaarshsingh/www '/storage/nvme5/new_clones/Astro/www' &
git clone https://github.com/will-stone/plastic '/storage/nvme5/new_clones/Astro/plastic' &
git clone https://github.com/t3-oss/init.tips '/storage/nvme5/new_clones/Astro/init.tips' &
git clone https://github.com/withastro/blog-tutorial-demo '/storage/nvme5/new_clones/Astro/blog-tutorial-demo' &
git clone https://github.com/natemoo-re/astro-remote '/storage/nvme5/new_clones/Astro/astro-remote' &
git clone https://github.com/hellotham/hello-astro '/storage/nvme5/new_clones/Astro/hello-astro' &
git clone https://github.com/incluud/accessible-astro-dashboard '/storage/nvme5/new_clones/Astro/accessible-astro-dashboard' &
git clone https://github.com/jln13x/tailwindcss-highlights '/storage/nvme5/new_clones/Astro/tailwindcss-highlights' &
git clone https://github.com/VojtaStruhar/steam-review-template '/storage/nvme5/new_clones/Astro/steam-review-template' &
git clone https://github.com/JEverhart383/astro-wordpress-starter '/storage/nvme5/new_clones/Astro/astro-wordpress-starter' &
git clone https://github.com/midudev/midufest '/storage/nvme5/new_clones/Astro/midufest' &
git clone https://github.com/scriptin/kanji-frequency '/storage/nvme5/new_clones/Astro/kanji-frequency' &
git clone https://github.com/alexcarpenter/alexcarpenter.me '/storage/nvme5/new_clones/Astro/alexcarpenter.me' &
git clone https://github.com/stackbit/jamstack-wtf '/storage/nvme5/new_clones/Astro/jamstack-wtf' &
git clone https://github.com/evadecker/eva.town '/storage/nvme5/new_clones/Astro/eva.town' &
git clone https://github.com/jqapi/jqapi '/storage/nvme5/new_clones/Astro/jqapi' &
git clone https://github.com/jordienr/astro-design-system '/storage/nvme5/new_clones/Astro/astro-design-system' &
git clone https://github.com/Destiner/astro-analytics '/storage/nvme5/new_clones/Astro/astro-analytics' &
git clone https://github.com/JonasKruckenberg/tauri-astro-template '/storage/nvme5/new_clones/Astro/tauri-astro-template' &
git clone https://github.com/uzzii-21/astro-portfolio '/storage/nvme5/new_clones/Astro/astro-portfolio' &
git clone https://github.com/museapphq/infinitecanvas.tools '/storage/nvme5/new_clones/Astro/infinitecanvas.tools' &
git clone https://github.com/EmaSuriano/astro-art-portfolio '/storage/nvme5/new_clones/Astro/astro-art-portfolio' &
git clone https://github.com/wsafight/personBlog '/storage/nvme5/new_clones/Astro/personBlog' &
git clone https://github.com/treefarmstudio/astro-sanity-minimal-starter '/storage/nvme5/new_clones/Astro/astro-sanity-minimal-starter' &
git clone https://github.com/livebook-dev/livebook.dev '/storage/nvme5/new_clones/Astro/livebook.dev' &
git clone https://github.com/xuya227939/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/yuheiy/sdenv '/storage/nvme5/new_clones/Astro/sdenv' &
git clone https://github.com/lloydjatkinson/astro-snipcart '/storage/nvme5/new_clones/Astro/astro-snipcart' &
git clone https://github.com/cssninjaStudio/dokto '/storage/nvme5/new_clones/Astro/dokto' &
git clone https://github.com/netlify-templates/astro-toolbox '/storage/nvme5/new_clones/Astro/astro-toolbox' &
git clone https://github.com/rose-pine/rose-pine-site '/storage/nvme5/new_clones/Astro/rose-pine-site' &
git clone https://github.com/Princesseuh/erika.florist '/storage/nvme5/new_clones/Astro/erika.florist' &
git clone https://github.com/treefarmstudio/simple-blog-astro '/storage/nvme5/new_clones/Astro/simple-blog-astro' &
git clone https://github.com/delucis/astro-badge '/storage/nvme5/new_clones/Astro/astro-badge' &
git clone https://github.com/yoanbernabeu/LinkTreeFreeClone '/storage/nvme5/new_clones/Astro/LinkTreeFreeClone' &
git clone https://github.com/magnuswahlstrand/astro-supabase-vercel '/storage/nvme5/new_clones/Astro/astro-supabase-vercel' &
git clone https://github.com/aryankashyap7/CheatSheets-for-Developers '/storage/nvme5/new_clones/Astro/CheatSheets-for-Developers' &
git clone https://github.com/astro-reactive/astro-reactive '/storage/nvme5/new_clones/Astro/astro-reactive' &
git clone https://github.com/sondr3/astro-compressor '/storage/nvme5/new_clones/Astro/astro-compressor' &
git clone https://github.com/t3dotgg/t3-astro '/storage/nvme5/new_clones/Astro/t3-astro' &
git clone https://github.com/rebelchris/astropress '/storage/nvme5/new_clones/Astro/astropress' &
git clone https://github.com/catppuccin/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/EmaSuriano/astro-resume '/storage/nvme5/new_clones/Astro/astro-resume' &
git clone https://github.com/theisel/astro-portabletext '/storage/nvme5/new_clones/Astro/astro-portabletext' &
git clone https://github.com/kevincobain2000/email_extractor '/storage/nvme5/new_clones/Astro/email_extractor' &
git clone https://github.com/zougari47/portfolio-template '/storage/nvme5/new_clones/Astro/portfolio-template' &
git clone https://github.com/cassidoo/astro-netlify-starter '/storage/nvme5/new_clones/Astro/astro-netlify-starter' &
git clone https://github.com/onadrog/cmd_theme '/storage/nvme5/new_clones/Astro/cmd_theme' &
git clone https://github.com/kevinzunigacuellar/web '/storage/nvme5/new_clones/Astro/web' &
git clone https://github.com/BryceRussell/astro-headless-ui '/storage/nvme5/new_clones/Astro/astro-headless-ui' &
git clone https://github.com/ogzhanolguncu/ogzhanolguncu.com '/storage/nvme5/new_clones/Astro/ogzhanolguncu.com' &
git clone https://github.com/treefarmstudio/astro-minimal-starter '/storage/nvme5/new_clones/Astro/astro-minimal-starter' &
git clone https://github.com/midudev/frontend-mentor-challenges '/storage/nvme5/new_clones/Astro/frontend-mentor-challenges' &
git clone https://github.com/astro-community/icons '/storage/nvme5/new_clones/Astro/icons' &
git clone https://github.com/ryansolid/astro-solid-hackernews '/storage/nvme5/new_clones/Astro/astro-solid-hackernews' &
git clone https://github.com/hzoo/hopeinsource.com '/storage/nvme5/new_clones/Astro/hopeinsource.com' &
git clone https://github.com/saadeghi/daisy-blog '/storage/nvme5/new_clones/Astro/daisy-blog' &
git clone https://github.com/domin-mnd/profile-card '/storage/nvme5/new_clones/Astro/profile-card' &
git clone https://github.com/PhilDL/astro-starter-ghost '/storage/nvme5/new_clones/Astro/astro-starter-ghost' &
git clone https://github.com/kyr0/turbo-hybrid-astro-on-vercel '/storage/nvme5/new_clones/Astro/turbo-hybrid-astro-on-vercel' &
git clone https://github.com/kinsta/hello-world-astro '/storage/nvme5/new_clones/Astro/hello-world-astro' &
git clone https://github.com/endigo9740/endigo-design '/storage/nvme5/new_clones/Astro/endigo-design' &
git clone https://github.com/cosmicjs/simple-astro-blog '/storage/nvme5/new_clones/Astro/simple-astro-blog' &
git clone https://github.com/netlify-templates/astro-quickstart '/storage/nvme5/new_clones/Astro/astro-quickstart' &
git clone https://github.com/stackblitz/ilovecodeflow.com '/storage/nvme5/new_clones/Astro/ilovecodeflow.com' &
git clone https://github.com/Princesseuh/component-template '/storage/nvme5/new_clones/Astro/component-template' &
git clone https://github.com/onokumus/chaldene '/storage/nvme5/new_clones/Astro/chaldene' &
git clone https://github.com/aFuzzyBear/xelement '/storage/nvme5/new_clones/Astro/xelement' &
git clone https://github.com/mdwelsh/mdwelsh.github.io '/storage/nvme5/new_clones/Astro/mdwelshhub.io' &
git clone https://github.com/bdsqqq/psykip '/storage/nvme5/new_clones/Astro/psykip' &
git clone https://github.com/BryceRussell/astro-json-element '/storage/nvme5/new_clones/Astro/astro-json-element' &
git clone https://github.com/rachsmithcodes/rachsmith.com '/storage/nvme5/new_clones/Astro/rachsmith.com' &
git clone https://github.com/ElianCodes/ElianCodes-frontend '/storage/nvme5/new_clones/Astro/ElianCodes-frontend' &
git clone https://github.com/natemoo-re/feed '/storage/nvme5/new_clones/Astro/feed' &
git clone https://github.com/jamesqquick/jamesqquick-site '/storage/nvme5/new_clones/Astro/jamesqquick-site' &
git clone https://github.com/gd4Ark/gd4Ark.github.io '/storage/nvme5/new_clones/Astro/gd4Arkhub.io' &
git clone https://github.com/bowencool/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/iozcelik/SarissaBlogAstroStarter '/storage/nvme5/new_clones/Astro/SarissaBlogAstroStarter' &
git clone https://github.com/one-aalam/astro-me '/storage/nvme5/new_clones/Astro/astro-me' &
git clone https://github.com/yacosta738/yacosta738.github.io '/storage/nvme5/new_clones/Astro/yacosta738hub.io' &
git clone https://github.com/nrollr/EC2-timeline '/storage/nvme5/new_clones/Astro/EC2-timeline' &
git clone https://github.com/withastro/github-pages '/storage/nvme5/new_clones/Astro/github-pages' &
git clone https://github.com/justjavac/esowiki '/storage/nvme5/new_clones/Astro/esowiki' &
git clone https://github.com/Charca/astro-music '/storage/nvme5/new_clones/Astro/astro-music' &
git clone https://github.com/pro-tailwind/tutorials '/storage/nvme5/new_clones/Astro/tutorials' &
git clone https://github.com/akellbl4/akellbl4 '/storage/nvme5/new_clones/Astro/akellbl4' &
git clone https://github.com/treefarmstudio/cannonball '/storage/nvme5/new_clones/Astro/cannonball' &
git clone https://github.com/kufu/hello-world '/storage/nvme5/new_clones/Astro/hello-world' &
git clone https://github.com/aFuzzyBear/astro-ui '/storage/nvme5/new_clones/Astro/astro-ui' &
git clone https://github.com/edvinlinden/killedby.tech '/storage/nvme5/new_clones/Astro/killedby.tech' &
git clone https://github.com/ViorelMocanu/digital-resources '/storage/nvme5/new_clones/Astro/digital-resources' &
git clone https://github.com/amplitudesxd/amplitudes.me '/storage/nvme5/new_clones/Astro/amplitudes.me' &
git clone https://github.com/danilowoz/danilowoz.com '/storage/nvme5/new_clones/Astro/danilowoz.com' &
git clone https://github.com/delucis/astro-netlify-cms-starter '/storage/nvme5/new_clones/Astro/astro-netlify-cms-starter' &
git clone https://github.com/kognise/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/eteplus/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/philnash/philna.sh '/storage/nvme5/new_clones/Astro/philna.sh' &
git clone https://github.com/pengtikui/pengtikui.cn '/storage/nvme5/new_clones/Astro/pengtikui.cn' &
git clone https://github.com/sarasate/gate '/storage/nvme5/new_clones/Astro/gate' &
git clone https://github.com/ekafyi/astronotion-starter-ssg '/storage/nvme5/new_clones/Astro/astronotion-starter-ssg' &
git clone https://github.com/martin-liu/martin-liu.github.io '/storage/nvme5/new_clones/Astro/martin-liuhub.io' &
git clone https://github.com/QingXia-Ela/Shiina-Astro-Blog '/storage/nvme5/new_clones/Astro/Shiina-Astro-Blog' &
git clone https://github.com/Kodular/kodular.github.io '/storage/nvme5/new_clones/Astro/kodularhub.io' &
git clone https://github.com/GoogleChromeLabs/designcember '/storage/nvme5/new_clones/Astro/designcember' &
git clone https://github.com/withastro/astro.new '/storage/nvme5/new_clones/Astro/astro.new' &
git clone https://github.com/amandeepmittal/amanhimself.dev '/storage/nvme5/new_clones/Astro/amanhimself.dev' &
git clone https://github.com/lukeliasi/developer-portfolio '/storage/nvme5/new_clones/Astro/developer-portfolio' &
git clone https://github.com/whitep4nth3r/whattheframework '/storage/nvme5/new_clones/Astro/whattheframework' &
git clone https://github.com/codiume/the-tap-stack '/storage/nvme5/new_clones/Astro/the-tap-stack' &
git clone https://github.com/woliveiras/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/joe-bell/tenprinciples.design '/storage/nvme5/new_clones/Astro/tenprinciples.design' &
git clone https://github.com/AgnosticUI/AstroAgnosticUIStarter '/storage/nvme5/new_clones/Astro/AstroAgnosticUIStarter' &
git clone https://github.com/delucis/hyperdrive-speedometer '/storage/nvme5/new_clones/Astro/hyperdrive-speedometer' &
git clone https://github.com/trashhalo/astro-command '/storage/nvme5/new_clones/Astro/astro-command' &
git clone https://github.com/guardian/guardian-engineering-site '/storage/nvme5/new_clones/Astro/guardian-engineering-site' &
git clone https://github.com/lmammino/loige.co '/storage/nvme5/new_clones/Astro/loige.co' &
git clone https://github.com/jackmerrill/AstroForms '/storage/nvme5/new_clones/Astro/AstroForms' &
git clone https://github.com/npmrun/art-theme '/storage/nvme5/new_clones/Astro/art-theme' &
git clone https://github.com/leosvelperez/leosvel.dev '/storage/nvme5/new_clones/Astro/leosvel.dev' &
git clone https://github.com/pilcrowonpaper/pilcrow '/storage/nvme5/new_clones/Astro/pilcrow' &
git clone https://github.com/patdx/zustand-rx '/storage/nvme5/new_clones/Astro/zustand-rx' &
git clone https://github.com/candidosales/landing-page-book-astro-svelte-tailwind '/storage/nvme5/new_clones/Astro/landing-page-book-astro-svelte-tailwind' &
git clone https://github.com/alexanderhodes/astro-minimal-cv '/storage/nvme5/new_clones/Astro/astro-minimal-cv' &
git clone https://github.com/argyleink/2022-css-day_oh-snap '/storage/nvme5/new_clones/Astro/2022-css-day_oh-snap' &
git clone https://github.com/micheleriva/personal-website '/storage/nvme5/new_clones/Astro/personal-website' &
git clone https://github.com/petertait/petertait.com '/storage/nvme5/new_clones/Astro/petertait.com' &
git clone https://github.com/ruine-dev/ruine-ui-dashboard '/storage/nvme5/new_clones/Astro/ruine-ui-dashboard' &
git clone https://github.com/slamethendry/TinyRocket '/storage/nvme5/new_clones/Astro/TinyRocket' &
git clone https://github.com/haaarshsingh/cursor.js '/storage/nvme5/new_clones/Astro/cursor.js' &
git clone https://github.com/yjose/elazizi.com '/storage/nvme5/new_clones/Astro/elazizi.com' &
git clone https://github.com/rebelchris/astro-portfolio '/storage/nvme5/new_clones/Astro/astro-portfolio' &
git clone https://github.com/tusharsadhwani/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/alexanderhodes/astro-minimal-blog '/storage/nvme5/new_clones/Astro/astro-minimal-blog' &
git clone https://github.com/importantimport/gumori '/storage/nvme5/new_clones/Astro/gumori' &
git clone https://github.com/RafidMuhymin/astro-image-demo '/storage/nvme5/new_clones/Astro/astro-image-demo' &
git clone https://github.com/v2er-app/v2er.app '/storage/nvme5/new_clones/Astro/v2er.app' &
git clone https://github.com/SapphicMoe/sapphic.moe '/storage/nvme5/new_clones/Astro/sapphic.moe' &
git clone https://github.com/ifpb/projects '/storage/nvme5/new_clones/Astro/projects' &
git clone https://github.com/EuroPython/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/theisel/astro-toc '/storage/nvme5/new_clones/Astro/astro-toc' &
git clone https://github.com/faztcommunity/fazt-community-web '/storage/nvme5/new_clones/Astro/fazt-community-web' &
git clone https://github.com/aFuzzyBear/astro-component-book '/storage/nvme5/new_clones/Astro/astro-component-book' &
git clone https://github.com/enpitsuLin/enpitsuLin.xyz '/storage/nvme5/new_clones/Astro/enpitsuLin.xyz' &
git clone https://github.com/pablopunk/pablopunk.com '/storage/nvme5/new_clones/Astro/pablopunk.com' &
git clone https://github.com/igorskyflyer/npm-astro-post-excerpt '/storage/nvme5/new_clones/Astro/npm-astro-post-excerpt' &
git clone https://github.com/helmisatria/helmisatria '/storage/nvme5/new_clones/Astro/helmisatria' &
git clone https://github.com/manfredsteyer/astro-last-minute '/storage/nvme5/new_clones/Astro/astro-last-minute' &
git clone https://github.com/pro-tailwind/course-multi-theme-strategy '/storage/nvme5/new_clones/Astro/course-multi-theme-strategy' &
git clone https://github.com/OnWritingCode/simple-blog-template '/storage/nvme5/new_clones/Astro/simple-blog-template' &
git clone https://github.com/devinschulz/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/brandonroberts/astro-blog '/storage/nvme5/new_clones/Astro/astro-blog' &
git clone https://github.com/sarahetter/astro-netlify-edge-starter '/storage/nvme5/new_clones/Astro/astro-netlify-edge-starter' &
git clone https://github.com/chantastic/react.holiday '/storage/nvme5/new_clones/Astro/react.holiday' &
git clone https://github.com/CTNicholas/astro-collaborative-starter '/storage/nvme5/new_clones/Astro/astro-collaborative-starter' &
git clone https://github.com/g00glen00b/dimitri.codes '/storage/nvme5/new_clones/Astro/dimitri.codes' &
git clone https://github.com/xirf/xirf-portofolio '/storage/nvme5/new_clones/Astro/xirf-portofolio' &
git clone https://github.com/laymonage/isle '/storage/nvme5/new_clones/Astro/isle' &
git clone https://github.com/swift502/Web '/storage/nvme5/new_clones/Astro/Web' &
git clone https://github.com/MoofyWoofy/Bob-blog '/storage/nvme5/new_clones/Astro/Bob-blog' &
git clone https://github.com/umstek/astro-typescript-react-tailwind '/storage/nvme5/new_clones/Astro/astro-typescript-react-tailwind' &
git clone https://github.com/Erisa/erisa.uk '/storage/nvme5/new_clones/Astro/erisa.uk' &
git clone https://github.com/rebelchris/astro-tailwind '/storage/nvme5/new_clones/Astro/astro-tailwind' &
git clone https://github.com/SpinalCMS/astro-docs-template '/storage/nvme5/new_clones/Astro/astro-docs-template' &
git clone https://github.com/dofbi/astro-simple-blog-theme '/storage/nvme5/new_clones/Astro/astro-simple-blog-theme' &
git clone https://github.com/devenapuros/portfolio '/storage/nvme5/new_clones/Astro/portfolio' &
git clone https://github.com/brainrepo/gitbar-2023 '/storage/nvme5/new_clones/Astro/gitbar-2023' &
git clone https://github.com/purarue/exobrain '/storage/nvme5/new_clones/Astro/exobrain' &
git clone https://github.com/aleksa-codes/astro-portfolio '/storage/nvme5/new_clones/Astro/astro-portfolio' &
git clone https://github.com/rebelchris/astro-modal '/storage/nvme5/new_clones/Astro/astro-modal' &
git clone https://github.com/fazt/astro-landing '/storage/nvme5/new_clones/Astro/astro-landing' &
git clone https://github.com/reegodev/reego.dev '/storage/nvme5/new_clones/Astro/reego.dev' &
git clone https://github.com/Stratis-Dermanoutsos/Full-Stack-Notes '/storage/nvme5/new_clones/Astro/Full-Stack-Notes' &
git clone https://github.com/reacto11mecha/jadwal-ssg '/storage/nvme5/new_clones/Astro/jadwal-ssg' &
git clone https://github.com/leen-neel/astro-wordpress '/storage/nvme5/new_clones/Astro/astro-wordpress' &
git clone https://github.com/trashhalo/astro-pandoc '/storage/nvme5/new_clones/Astro/astro-pandoc' &
git clone https://github.com/djyde/blog-2022 '/storage/nvme5/new_clones/Astro/blog-2022' &
git clone https://github.com/markdalgleish/astro-vanilla-extract-demo '/storage/nvme5/new_clones/Astro/astro-vanilla-extract-demo' &
git clone https://github.com/geoparquet/geoparquet.github.io '/storage/nvme5/new_clones/Astro/geoparquethub.io' &
git clone https://github.com/UW-UPL/uw-upl.github.io '/storage/nvme5/new_clones/Astro/uw-uplhub.io' &
git clone https://github.com/Nikaidou-Shinku/PastePlz '/storage/nvme5/new_clones/Astro/PastePlz' &
git clone https://github.com/dotnize/nize.foo '/storage/nvme5/new_clones/Astro/nize.foo' &
git clone https://github.com/wanghaisheng/wanghaisheng.github.io '/storage/nvme5/new_clones/Astro/wanghaishenghub.io' &
git clone https://github.com/LasCC/Cyber-Security-Blog '/storage/nvme5/new_clones/Astro/Cyber-Security-Blog' &
git clone https://github.com/janlelis/character.construction '/storage/nvme5/new_clones/Astro/character.construction' &
git clone https://github.com/hswolff/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/imhlq/EldenRingCheatSheetCN '/storage/nvme5/new_clones/Astro/EldenRingCheatSheetCN' &
git clone https://github.com/comunidadev/comunida.dev '/storage/nvme5/new_clones/Astro/comunida.dev' &
git clone https://github.com/higress-group/higress-group.github.io '/storage/nvme5/new_clones/Astro/higress-grouphub.io' &
git clone https://github.com/ShayanTheNerd/image-editor '/storage/nvme5/new_clones/Astro/image-editor' &
git clone https://github.com/one-aalam/astro-starter-kit '/storage/nvme5/new_clones/Astro/astro-starter-kit' &
git clone https://github.com/Asvel/tacticsogre '/storage/nvme5/new_clones/Astro/tacticsogre' &
git clone https://github.com/Brendonovich/brendonovich.dev '/storage/nvme5/new_clones/Astro/brendonovich.dev' &
git clone https://github.com/christopher-kapic/astro-blanding '/storage/nvme5/new_clones/Astro/astro-blanding' &
git clone https://github.com/seattlejs/seattlejs.com '/storage/nvme5/new_clones/Astro/seattlejs.com' &
git clone https://github.com/adwinmbd/astro-blog-template '/storage/nvme5/new_clones/Astro/astro-blog-template' &
git clone https://github.com/brandonroberts/angular-astro-islands '/storage/nvme5/new_clones/Astro/angular-astro-islands' &
git clone https://github.com/patrick91/latest.cat '/storage/nvme5/new_clones/Astro/latest.cat' &
git clone https://github.com/kskwtnk/portfolio '/storage/nvme5/new_clones/Astro/portfolio' &
git clone https://github.com/kufu/product-design '/storage/nvme5/new_clones/Astro/product-design' &
git clone https://github.com/xhofe/homepage '/storage/nvme5/new_clones/Astro/homepage' &
git clone https://github.com/rayriffy/rayriffy-blog-next '/storage/nvme5/new_clones/Astro/rayriffy-blog-next' &
git clone https://github.com/Zhengqbbb/qbb.sh '/storage/nvme5/new_clones/Astro/qbb.sh' &
git clone https://github.com/X7md/x7md.github.io '/storage/nvme5/new_clones/Astro/x7mdhub.io' &
git clone https://github.com/treefarmstudio/astro-101 '/storage/nvme5/new_clones/Astro/astro-101' &
git clone https://github.com/bradhave94/nms '/storage/nvme5/new_clones/Astro/nms' &
git clone https://github.com/manuelschroederdev/manuelschroeder.dev '/storage/nvme5/new_clones/Astro/manuelschroeder.dev' &
git clone https://github.com/RocketCommunicationsInc/astro-www '/storage/nvme5/new_clones/Astro/astro-www' &
git clone https://github.com/Ultramarine-Linux/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/morceaudebois/bonjourr.fr '/storage/nvme5/new_clones/Astro/bonjourr.fr' &
git clone https://github.com/DerYeger/jan-mueller '/storage/nvme5/new_clones/Astro/jan-mueller' &
git clone https://github.com/AREA44/SYWYKE '/storage/nvme5/new_clones/Astro/SYWYKE' &
git clone https://github.com/kripod/astro-starter-strict '/storage/nvme5/new_clones/Astro/astro-starter-strict' &
git clone https://github.com/penrodlol/christianpenrod '/storage/nvme5/new_clones/Astro/christianpenrod' &
git clone https://github.com/conanak99/300-bai-code '/storage/nvme5/new_clones/Astro/300-bai-code' &
git clone https://github.com/ddev/ddev.com '/storage/nvme5/new_clones/Astro/ddev.com' &
git clone https://github.com/nikolai-shabalin/css-properties '/storage/nvme5/new_clones/Astro/css-properties' &
git clone https://github.com/nekochan0122/astro-blog '/storage/nvme5/new_clones/Astro/astro-blog' &
git clone https://github.com/o3LL/zzccmxtp '/storage/nvme5/new_clones/Astro/zzccmxtp' &
git clone https://github.com/Slashgear/personal-blog '/storage/nvme5/new_clones/Astro/personal-blog' &
git clone https://github.com/jsulpis/slides-template '/storage/nvme5/new_clones/Astro/slides-template' &
git clone https://github.com/onokumus/elektron '/storage/nvme5/new_clones/Astro/elektron' &
git clone https://github.com/natemoo-re/miles-of-code '/storage/nvme5/new_clones/Astro/miles-of-code' &
git clone https://github.com/mage-os/mage-os-website '/storage/nvme5/new_clones/Astro/mage-os-website' &
git clone https://github.com/PurpurMC/PurpurWebsite '/storage/nvme5/new_clones/Astro/PurpurWebsite' &
git clone https://github.com/mishmanners/mish-friendly-food '/storage/nvme5/new_clones/Astro/mish-friendly-food' &
git clone https://github.com/rosnovsky/rosnovsky.us '/storage/nvme5/new_clones/Astro/rosnovsky.us' &
git clone https://github.com/bholmesdev/whiteboard-the-web '/storage/nvme5/new_clones/Astro/whiteboard-the-web' &
git clone https://github.com/rwpod/rwpod.github.io '/storage/nvme5/new_clones/Astro/rwpodhub.io' &
git clone https://github.com/PassionZale/lovchun.com-next '/storage/nvme5/new_clones/Astro/lovchun.com-next' &
git clone https://github.com/houzyk/thephilosophicalcode '/storage/nvme5/new_clones/Astro/thephilosophicalcode' &
git clone https://github.com/murtuzaalisurti/murtuzaalisurti.github.io '/storage/nvme5/new_clones/Astro/murtuzaalisurtihub.io' &
git clone https://github.com/lkhrs/astro-simple '/storage/nvme5/new_clones/Astro/astro-simple' &
git clone https://github.com/sonicjhon1/sonicjhon1.github.io '/storage/nvme5/new_clones/Astro/sonicjhon1hub.io' &
git clone https://github.com/SIMITClub/simitclub.github.io '/storage/nvme5/new_clones/Astro/simitclubhub.io' &
git clone https://github.com/AllanChain/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/ChristianChiarulli/old_website '/storage/nvme5/new_clones/Astro/old_website' &
git clone https://github.com/mesinkasir/cute-blog '/storage/nvme5/new_clones/Astro/cute-blog' &
git clone https://github.com/piero-vic/pierolescano.com '/storage/nvme5/new_clones/Astro/pierolescano.com' &
git clone https://github.com/TrustedFirmwareWebsite/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/cybozu/frontend-monthly '/storage/nvme5/new_clones/Astro/frontend-monthly' &
git clone https://github.com/mortnod/instabart '/storage/nvme5/new_clones/Astro/instabart' &
git clone https://github.com/Navillus-BV/navillus-dev '/storage/nvme5/new_clones/Astro/navillus-dev' &
git clone https://github.com/rebelchris/astro-recipe-website '/storage/nvme5/new_clones/Astro/astro-recipe-website' &
git clone https://github.com/kernel-mod/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/lhermann/astro-firebase-example '/storage/nvme5/new_clones/Astro/astro-firebase-example' &
git clone https://github.com/OdinVerst/trybrew '/storage/nvme5/new_clones/Astro/trybrew' &
git clone https://github.com/hendriknielaender/double-trouble '/storage/nvme5/new_clones/Astro/double-trouble' &
git clone https://github.com/aFuzzyBear/astro-academy '/storage/nvme5/new_clones/Astro/astro-academy' &
git clone https://github.com/aitu-dk/webpage '/storage/nvme5/new_clones/Astro/webpage' &
git clone https://github.com/UndergraduateArtificialIntelligenceClub/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/LycheeOrg/LycheeOrg.github.io '/storage/nvme5/new_clones/Astro/LycheeOrghub.io' &
git clone https://github.com/serverlessworkflow/serverlessworkflow.github.io '/storage/nvme5/new_clones/Astro/serverlessworkflowhub.io' &
git clone https://github.com/adhrinae/rinae.dev '/storage/nvme5/new_clones/Astro/rinae.dev' &
git clone https://github.com/michaeljolley/baldbeardedbuilder.com '/storage/nvme5/new_clones/Astro/baldbeardedbuilder.com' &
git clone https://github.com/chriscoyier/breakfast-burritos '/storage/nvme5/new_clones/Astro/breakfast-burritos' &
git clone https://github.com/treefarmstudio/linked-up '/storage/nvme5/new_clones/Astro/linked-up' &
git clone https://github.com/graphme-app/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/angelikatyborska/css-art '/storage/nvme5/new_clones/Astro/css-art' &
git clone https://github.com/TomEverson/Astro-Firebase-Starter '/storage/nvme5/new_clones/Astro/Astro-Firebase-Starter' &
git clone https://github.com/Dxmentorship/dxmentorship '/storage/nvme5/new_clones/Astro/dxmentorship' &
git clone https://github.com/aarsxx/carbon '/storage/nvme5/new_clones/Astro/carbon' &
git clone https://github.com/BrockHerion/brockherion.dev '/storage/nvme5/new_clones/Astro/brockherion.dev' &
git clone https://github.com/victrme/portfolio '/storage/nvme5/new_clones/Astro/portfolio' &
git clone https://github.com/yupanquiah/portfolio '/storage/nvme5/new_clones/Astro/portfolio' &
git clone https://github.com/zyrouge/zyrouge.me '/storage/nvme5/new_clones/Astro/zyrouge.me' &
git clone https://github.com/Jinksi/ericjinks.com '/storage/nvme5/new_clones/Astro/ericjinks.com' &
git clone https://github.com/narze/basic-svelte-for-react-and-vue-developers '/storage/nvme5/new_clones/Astro/basic-svelte-for-react-and-vue-developers' &
git clone https://github.com/JuanM04/astro-on-the-edge '/storage/nvme5/new_clones/Astro/astro-on-the-edge' &
git clone https://github.com/zellwk/build-and-deploy-workshop '/storage/nvme5/new_clones/Astro/build-and-deploy-workshop' &
git clone https://github.com/tadeuzagallo/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/thwiki/touhou-group '/storage/nvme5/new_clones/Astro/touhou-group' &
git clone https://github.com/blackgirlbytes/blackgyalbites-astro '/storage/nvme5/new_clones/Astro/blackgyalbites-astro' &
git clone https://github.com/iozcelik/SarissaPagination '/storage/nvme5/new_clones/Astro/SarissaPagination' &
git clone https://github.com/rasendubi/oleksii.shmalko.com '/storage/nvme5/new_clones/Astro/oleksii.shmalko.com' &
git clone https://github.com/KumailP/kumails-blog '/storage/nvme5/new_clones/Astro/kumails-blog' &
git clone https://github.com/ritterim/rimdev-blog '/storage/nvme5/new_clones/Astro/rimdev-blog' &
git clone https://github.com/Mixtape-Sessions/Great-Economics-Writing '/storage/nvme5/new_clones/Astro/Great-Economics-Writing' &
git clone https://github.com/jmarlena/netlify-feature-tour '/storage/nvme5/new_clones/Astro/netlify-feature-tour' &
git clone https://github.com/scottkellum/scottkellum.com '/storage/nvme5/new_clones/Astro/scottkellum.com' &
git clone https://github.com/t3dotgg/pog.capital '/storage/nvme5/new_clones/Astro/pog.capital' &
git clone https://github.com/DominusKelvin/dominuskelvin.dev '/storage/nvme5/new_clones/Astro/dominuskelvin.dev' &
git clone https://github.com/akbaruddin/commit-emojis '/storage/nvme5/new_clones/Astro/commit-emojis' &
git clone https://github.com/kishanhitk/kishans.in '/storage/nvme5/new_clones/Astro/kishans.in' &
git clone https://github.com/jwngr/jwn.gr '/storage/nvme5/new_clones/Astro/jwn.gr' &
git clone https://github.com/kalwabed/kalwabed.com '/storage/nvme5/new_clones/Astro/kalwabed.com' &
git clone https://github.com/andrewn6/world '/storage/nvme5/new_clones/Astro/world' &
git clone https://github.com/yamanoku/yamanoku.github.io '/storage/nvme5/new_clones/Astro/yamanokuhub.io' &
git clone https://github.com/DanGeffroy/DanGeffroy.github.io '/storage/nvme5/new_clones/Astro/DanGeffroyhub.io' &
git clone https://github.com/xstevenyung/astro-session '/storage/nvme5/new_clones/Astro/astro-session' &
git clone https://github.com/sebiko3/proxima '/storage/nvme5/new_clones/Astro/proxima' &
git clone https://github.com/josefaidt/josef.dev '/storage/nvme5/new_clones/Astro/josef.dev' &
git clone https://github.com/rebelchris/astro-typesense-search '/storage/nvme5/new_clones/Astro/astro-typesense-search' &
git clone https://github.com/otoyo/notion-blog '/storage/nvme5/new_clones/Astro/notion-blog' &
git clone https://github.com/chantastic/reactcontext.com '/storage/nvme5/new_clones/Astro/reactcontext.com' &
git clone https://github.com/BryceRussell/astro-bryceguy '/storage/nvme5/new_clones/Astro/astro-bryceguy' &
git clone https://github.com/carlosjorger/carlosjorger.github.io '/storage/nvme5/new_clones/Astro/carlosjorgerhub.io' &
git clone https://github.com/andrewn6/janitor '/storage/nvme5/new_clones/Astro/janitor' &
git clone https://github.com/markteekman/easybank-landing-page '/storage/nvme5/new_clones/Astro/easybank-landing-page' &
git clone https://github.com/tejasag/blossom '/storage/nvme5/new_clones/Astro/blossom' &
git clone https://github.com/acanimal/acanimal.github.io '/storage/nvme5/new_clones/Astro/acanimalhub.io' &
git clone https://github.com/jensonhirst/rayfield-docs '/storage/nvme5/new_clones/Astro/rayfield-docs' &
git clone https://github.com/SublimeText/Astro '/storage/nvme5/new_clones/Astro/Astro' &
git clone https://github.com/erisly/moe '/storage/nvme5/new_clones/Astro/moe' &
git clone https://github.com/vitormiura/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/angelofallars/angelofallars.github.io '/storage/nvme5/new_clones/Astro/angelofallarshub.io' &
git clone https://github.com/yongzhenlow/astro-ghost-cms '/storage/nvme5/new_clones/Astro/astro-ghost-cms' &
git clone https://github.com/simse/mad-man '/storage/nvme5/new_clones/Astro/mad-man' &
git clone https://github.com/kevinzunigacuellar/astro-satori '/storage/nvme5/new_clones/Astro/astro-satori' &
git clone https://github.com/praveenjuge/praveenjuge '/storage/nvme5/new_clones/Astro/praveenjuge' &
git clone https://github.com/FaztWeb/astro-preview '/storage/nvme5/new_clones/Astro/astro-preview' &
git clone https://github.com/DreamStacks/food-geo-mapping '/storage/nvme5/new_clones/Astro/food-geo-mapping' &
git clone https://github.com/398noe/4cil '/storage/nvme5/new_clones/Astro/4cil' &
git clone https://github.com/simonswiss/simonswiss.com '/storage/nvme5/new_clones/Astro/simonswiss.com' &
git clone https://github.com/AcademySoftwareFoundation/dpel-website '/storage/nvme5/new_clones/Astro/dpel-website' &
git clone https://github.com/RafidMuhymin/astro-script '/storage/nvme5/new_clones/Astro/astro-script' &
git clone https://github.com/RafidMuhymin/softhardsystem '/storage/nvme5/new_clones/Astro/softhardsystem' &
git clone https://github.com/srikarg/srikarg.github.io '/storage/nvme5/new_clones/Astro/srikarghub.io' &
git clone https://github.com/eludris/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/shipshapecode/website-astro '/storage/nvme5/new_clones/Astro/website-astro' &
git clone https://github.com/AndreaPontrandolfo/super-performant-portfolio-website '/storage/nvme5/new_clones/Astro/super-performant-portfolio-website' &
git clone https://github.com/iansu/iansutherland.ca '/storage/nvme5/new_clones/Astro/iansutherland.ca' &
git clone https://github.com/netlesh/astro-business-template '/storage/nvme5/new_clones/Astro/astro-business-template' &
git clone https://github.com/ehkoo/web '/storage/nvme5/new_clones/Astro/web' &
git clone https://github.com/Navillus-BV/demo-astro-forestry '/storage/nvme5/new_clones/Astro/demo-astro-forestry' &
git clone https://github.com/brianmaierjr/long-haul-astro '/storage/nvme5/new_clones/Astro/long-haul-astro' &
git clone https://github.com/dwightjack/marco.solazzi.me '/storage/nvme5/new_clones/Astro/marco.solazzi.me' &
git clone https://github.com/vladilenm/astro-cc '/storage/nvme5/new_clones/Astro/astro-cc' &
git clone https://github.com/community-builders/community-builders.github-io '/storage/nvme5/new_clones/Astro/community-buildershub-io' &
git clone https://github.com/narze/9speech '/storage/nvme5/new_clones/Astro/9speech' &
git clone https://github.com/mayank99/webc-astro-demo '/storage/nvme5/new_clones/Astro/webc-astro-demo' &
git clone https://github.com/a-trost/astro-prismic-blog-starter '/storage/nvme5/new_clones/Astro/astro-prismic-blog-starter' &
git clone https://github.com/Tricked-dev/bun-docs '/storage/nvme5/new_clones/Astro/bun-docs' &
git clone https://github.com/KubeHuddle/KubeHuddle '/storage/nvme5/new_clones/Astro/KubeHuddle' &
git clone https://github.com/mralexsaavedra/mralexsaavedra.dev '/storage/nvme5/new_clones/Astro/mralexsaavedra.dev' &
git clone https://github.com/austincrim/austincrim.com-astro '/storage/nvme5/new_clones/Astro/austincrim.com-astro' &
git clone https://github.com/webpro/webpro.nl '/storage/nvme5/new_clones/Astro/webpro.nl' &
git clone https://github.com/jeffwllms/astro-openprops-starter '/storage/nvme5/new_clones/Astro/astro-openprops-starter' &
git clone https://github.com/Dot32Dev/dot32.dev-v6 '/storage/nvme5/new_clones/Astro/dot32.dev-v6' &
git clone https://github.com/pyohio/pyohio-static-website '/storage/nvme5/new_clones/Astro/pyohio-static-website' &
git clone https://github.com/KinectToVR/k2vr-docs '/storage/nvme5/new_clones/Astro/k2vr-docs' &
git clone https://github.com/CachyOS/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/domitriusclark/discord-forum-to-website '/storage/nvme5/new_clones/Astro/discord-forum-to-website' &
git clone https://github.com/EmNudge/site '/storage/nvme5/new_clones/Astro/site' &
git clone https://github.com/MicroWebStacks/astro-home-control '/storage/nvme5/new_clones/Astro/astro-home-control' &
git clone https://github.com/z-zahi/astroid '/storage/nvme5/new_clones/Astro/astroid' &
git clone https://github.com/davish/davi.sh '/storage/nvme5/new_clones/Astro/davi.sh' &
git clone https://github.com/bjerkio/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/josephearl/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/osmkerala/osmkerala.github.io '/storage/nvme5/new_clones/Astro/osmkeralahub.io' &
git clone https://github.com/liruifengv/sayhub '/storage/nvme5/new_clones/Astro/sayhub' &
git clone https://github.com/AREA44/astro-research-theme '/storage/nvme5/new_clones/Astro/astro-research-theme' &
git clone https://github.com/SapphicMoe/parallel.report '/storage/nvme5/new_clones/Astro/parallel.report' &
git clone https://github.com/moonlight-ng/independent-arts '/storage/nvme5/new_clones/Astro/independent-arts' &
git clone https://github.com/uchuuio/start '/storage/nvme5/new_clones/Astro/start' &
git clone https://github.com/xilaluna/xilaluna.com '/storage/nvme5/new_clones/Astro/xilaluna.com' &
git clone https://github.com/ronanru/resume '/storage/nvme5/new_clones/Astro/resume' &
git clone https://github.com/SerenModz21/seren.dev '/storage/nvme5/new_clones/Astro/seren.dev' &
git clone https://github.com/AzuraCast/azuracast.com '/storage/nvme5/new_clones/Astro/azuracast.com' &
git clone https://github.com/fazt/astro-devblog '/storage/nvme5/new_clones/Astro/astro-devblog' &
git clone https://github.com/jayperryworks/jayperryworks-site '/storage/nvme5/new_clones/Astro/jayperryworks-site' &
git clone https://github.com/Code-for-Senegal/joinDjolof '/storage/nvme5/new_clones/Astro/joinDjolof' &
git clone https://github.com/Namchee/site '/storage/nvme5/new_clones/Astro/site' &
git clone https://github.com/Ovyerus/site '/storage/nvme5/new_clones/Astro/site' &
git clone https://github.com/ispringle/sylvan '/storage/nvme5/new_clones/Astro/sylvan' &
git clone https://github.com/tonalmathew/hello-world '/storage/nvme5/new_clones/Astro/hello-world' &
git clone https://github.com/lachlanjc/catherine '/storage/nvme5/new_clones/Astro/catherine' &
git clone https://github.com/AnthonyNet/morbus_tschengi '/storage/nvme5/new_clones/Astro/morbus_tschengi' &
git clone https://github.com/adalbertopc/adal.dev '/storage/nvme5/new_clones/Astro/adal.dev' &
git clone https://github.com/Safi1012/filipesantoscorrea.com '/storage/nvme5/new_clones/Astro/filipesantoscorrea.com' &
git clone https://github.com/ParalelnaPolisKE/paralelnapoliskosice.sk '/storage/nvme5/new_clones/Astro/paralelnapoliskosice.sk' &
git clone https://github.com/timmo001/system-bridge-website '/storage/nvme5/new_clones/Astro/system-bridge-website' &
git clone https://github.com/starchildluke/astro '/storage/nvme5/new_clones/Astro/astro' &
git clone https://github.com/cassidoo/astro-redirects-example '/storage/nvme5/new_clones/Astro/astro-redirects-example' &
git clone https://github.com/NuroDev/satt '/storage/nvme5/new_clones/Astro/satt' &
git clone https://github.com/amithgeorge/astro-directus-authentication '/storage/nvme5/new_clones/Astro/astro-directus-authentication' &
git clone https://github.com/Njong392/Blog-astro '/storage/nvme5/new_clones/Astro/Blog-astro' &
git clone https://github.com/natemoo-re/astro-form '/storage/nvme5/new_clones/Astro/astro-form' &
git clone https://github.com/mertssmnoglu/mertsismanoglu.com '/storage/nvme5/new_clones/Astro/mertsismanoglu.com' &
git clone https://github.com/mrcaidev/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/iamhectorsosa/astrofordocs '/storage/nvme5/new_clones/Astro/astrofordocs' &
git clone https://github.com/leveluptuts/meteor-svelte-code '/storage/nvme5/new_clones/Astro/meteor-svelte-code' &
git clone https://github.com/mesinkasir/astro-website-template-themes-source-code-download '/storage/nvme5/new_clones/Astro/astro-website-template-themes-source-code-download' &
git clone https://github.com/Mixtape-Sessions/Mixtape-Website '/storage/nvme5/new_clones/Astro/Mixtape-Website' &
git clone https://github.com/martinklepsch/martinklepsch.org '/storage/nvme5/new_clones/Astro/martinklepsch.org' &
git clone https://github.com/imaginamundo/dio.dev '/storage/nvme5/new_clones/Astro/dio.dev' &
git clone https://github.com/crrashh1542/crash-homepage '/storage/nvme5/new_clones/Astro/crash-homepage' &
git clone https://github.com/jiripudil/jiripudil.cz '/storage/nvme5/new_clones/Astro/jiripudil.cz' &
git clone https://github.com/vkbansal/formula1-app '/storage/nvme5/new_clones/Astro/formula1-app' &
git clone https://github.com/williamhzo/williamhzo.me-v2 '/storage/nvme5/new_clones/Astro/williamhzo.me-v2' &
git clone https://github.com/MicroBenz/microbenz.in.th '/storage/nvme5/new_clones/Astro/microbenz.in.th' &
git clone https://github.com/astro-community/xelement '/storage/nvme5/new_clones/Astro/xelement' &
git clone https://github.com/ardillan/torlavega '/storage/nvme5/new_clones/Astro/torlavega' &
git clone https://github.com/psto/stojanow.com '/storage/nvme5/new_clones/Astro/stojanow.com' &
git clone https://github.com/MadHacks/MadHacks2023 '/storage/nvme5/new_clones/Astro/MadHacks2023' &
git clone https://github.com/sst/isserverlessready '/storage/nvme5/new_clones/Astro/isserverlessready' &
git clone https://github.com/felipejoq/validar-rut-chileno '/storage/nvme5/new_clones/Astro/validar-rut-chileno' &
git clone https://github.com/okTurtles/wordpress-to-astro '/storage/nvme5/new_clones/Astro/wordpress-to-astro' &
git clone https://github.com/norskeld/nrsk.dev '/storage/nvme5/new_clones/Astro/nrsk.dev' &
git clone https://github.com/ItzDerock/derock.dev '/storage/nvme5/new_clones/Astro/derock.dev' &
git clone https://github.com/madsouris/startpage '/storage/nvme5/new_clones/Astro/startpage' &
git clone https://github.com/tejasag/web '/storage/nvme5/new_clones/Astro/web' &
git clone https://github.com/anishshobithps/anishshobithps.com '/storage/nvme5/new_clones/Astro/anishshobithps.com' &
git clone https://github.com/email-markup-consortium/emailmarkup.org '/storage/nvme5/new_clones/Astro/emailmarkup.org' &
git clone https://github.com/serverlessdays-dublin/dublin.serverlessdays.io '/storage/nvme5/new_clones/Astro/dublin.serverlessdays.io' &
git clone https://github.com/narze/hacktober '/storage/nvme5/new_clones/Astro/hacktober' &
git clone https://github.com/brandon-carlisle/portfolio '/storage/nvme5/new_clones/Astro/portfolio' &
git clone https://github.com/cassidoo/testaroni '/storage/nvme5/new_clones/Astro/testaroni' &
git clone https://github.com/fangmarks/safeto-stream '/storage/nvme5/new_clones/Astro/safeto-stream' &
git clone https://github.com/JimniOS/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/tylergaw/colormix.site '/storage/nvme5/new_clones/Astro/colormix.site' &
git clone https://github.com/Lifeni/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/RoyalIcing/astro-crud '/storage/nvme5/new_clones/Astro/astro-crud' &
git clone https://github.com/EmaSuriano/astro-mate '/storage/nvme5/new_clones/Astro/astro-mate' &
git clone https://github.com/PaulieScanlon/pauliescanlon.github.io '/storage/nvme5/new_clones/Astro/pauliescanlonhub.io' &
git clone https://github.com/glaucia86/astro-swa-demo '/storage/nvme5/new_clones/Astro/astro-swa-demo' &
git clone https://github.com/BuilderIO/perf-experiments '/storage/nvme5/new_clones/Astro/perf-experiments' &
git clone https://github.com/arstnei0/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/manuelernestog/manuelernestog.github.io '/storage/nvme5/new_clones/Astro/manuelernestoghub.io' &
git clone https://github.com/FortuneStreetModding/fortunestreetmodding.github.io '/storage/nvme5/new_clones/Astro/fortunestreetmoddinghub.io' &
git clone https://github.com/3fuyang/fwio.me '/storage/nvme5/new_clones/Astro/fwio.me' &
git clone https://github.com/qjack001/Spotted '/storage/nvme5/new_clones/Astro/Spotted' &
git clone https://github.com/fersilva16/blog '/storage/nvme5/new_clones/Astro/blog' &
git clone https://github.com/alteredorange/astro-infinity '/storage/nvme5/new_clones/Astro/astro-infinity' &
git clone https://github.com/natemoo-re/astro-breadcrumbs '/storage/nvme5/new_clones/Astro/astro-breadcrumbs' &
git clone https://github.com/t3dotgg/pscalebench '/storage/nvme5/new_clones/Astro/pscalebench' &
git clone https://github.com/jpreecedev/developerhandbook '/storage/nvme5/new_clones/Astro/developerhandbook' &
git clone https://github.com/FAMNM/famnm-website '/storage/nvme5/new_clones/Astro/famnm-website' &
git clone https://github.com/goulvenclech/goulven-clech.dev '/storage/nvme5/new_clones/Astro/goulven-clech.dev' &
git clone https://github.com/ShivamJoker/Dad-jokes-SSR '/storage/nvme5/new_clones/Astro/Dad-jokes-SSR' &
git clone https://github.com/ruiokazaki-archive/ruiokazaki-blog '/storage/nvme5/new_clones/Astro/ruiokazaki-blog' &
git clone https://github.com/benadam11/personal-site '/storage/nvme5/new_clones/Astro/personal-site' &
git clone https://github.com/sadn1ck/sadn1ck '/storage/nvme5/new_clones/Astro/sadn1ck' &
git clone https://github.com/manuelfessen/manuelfessen.de '/storage/nvme5/new_clones/Astro/manuelfessen.de' &
git clone https://github.com/warpify/astro-theme '/storage/nvme5/new_clones/Astro/astro-theme' &
git clone https://github.com/suevalov/suevalov.com '/storage/nvme5/new_clones/Astro/suevalov.com' &
git clone https://github.com/lewisakura/lewisakura.moe '/storage/nvme5/new_clones/Astro/lewisakura.moe' &
git clone https://github.com/marksteve/marksteve.github.io '/storage/nvme5/new_clones/Astro/markstevehub.io' &
git clone https://github.com/hasparus/gradienty '/storage/nvme5/new_clones/Astro/gradienty' &
git clone https://github.com/HerIsDia/herisdia.me '/storage/nvme5/new_clones/Astro/herisdia.me' &
git clone https://github.com/AmanoTeam/site '/storage/nvme5/new_clones/Astro/site' &
git clone https://github.com/alexjustesen/alexjustesen-com '/storage/nvme5/new_clones/Astro/alexjustesen-com' &
git clone https://github.com/andr-ec/landing-blog '/storage/nvme5/new_clones/Astro/landing-blog' &
git clone https://github.com/arisris/arisris.com '/storage/nvme5/new_clones/Astro/arisris.com' &
git clone https://github.com/the-collab-lab/website '/storage/nvme5/new_clones/Astro/website' &
git clone https://github.com/tokencss/www '/storage/nvme5/new_clones/Astro/www' &
git clone https://github.com/mtwmt/mtwmt.github.io '/storage/nvme5/new_clones/Astro/mtwmthub.io' &
git clone https://github.com/c-ehrlich/personal-site-astro '/storage/nvme5/new_clones/Astro/personal-site-astro' &
git clone https://github.com/mirshko/reiner.systems '/storage/nvme5/new_clones/Astro/reiner.systems' &
git clone https://github.com/nexxeln/spotify-stats '/storage/nvme5/new_clones/Astro/spotify-stats' &
git clone https://github.com/ghostx31/spookyintheam '/storage/nvme5/new_clones/Astro/spookyintheam' &
git clone https://github.com/Merri/mellon.kontu.me '/storage/nvme5/new_clones/Astro/mellon.kontu.me' &
git clone https://github.com/brianmaierjr/147-colors-astro '/storage/nvme5/new_clones/Astro/147-colors-astro' &
git clone https://github.com/DSSD-Madison/website-framework '/storage/nvme5/new_clones/Astro/website-framework' &
git clone https://github.com/kwchang0831/demo-astro-swup '/storage/nvme5/new_clones/Astro/demo-astro-swup' &
git clone https://github.com/rootEnginear/gh-issues-cms '/storage/nvme5/new_clones/Astro/gh-issues-cms' &
git clone https://github.com/cjinhuo/cjinhuo.github.io '/storage/nvme5/new_clones/Astro/cjinhuohub.io' &
git clone https://github.com/treefarmstudio/astro-examples '/storage/nvme5/new_clones/Astro/astro-examples' &
git clone https://github.com/ElaBosak233/e23.dev '/storage/nvme5/new_clones/Astro/e23.dev' &
git clone https://github.com/pixelart7/chaiyapat-astro-site '/storage/nvme5/new_clones/Astro/chaiyapat-astro-site' &
git clone https://github.com/lirantal/no-secrets-env-vars-website '/storage/nvme5/new_clones/Astro/no-secrets-env-vars-website' &
git clone https://github.com/cake-cutter/docs '/storage/nvme5/new_clones/Astro/docs' &
