#!/bin/bash

git clone https://github.com/cw2k/Adobe-GenP '/storage/nvme5/new_clones/AutoIt/Adobe-GenP' &
git clone https://github.com/J2TEAM/idm-trial-reset '/storage/nvme5/new_clones/AutoIt/idm-trial-reset' &
git clone https://github.com/vboxme/Portable-VirtualBox '/storage/nvme5/new_clones/AutoIt/Portable-VirtualBox' &
git clone https://github.com/rcmaehl/NotCPUCores '/storage/nvme5/new_clones/AutoIt/NotCPUCores' &
git clone https://github.com/cnjackchen/my-chrome '/storage/nvme5/new_clones/AutoIt/my-chrome' &
git clone https://github.com/Enyby/APK-Info '/storage/nvme5/new_clones/AutoIt/APK-Info' &
git clone https://github.com/V1V1/OffensiveAutoIt '/storage/nvme5/new_clones/AutoIt/OffensiveAutoIt' &
git clone https://github.com/chall32/LDWin '/storage/nvme5/new_clones/AutoIt/LDWin' &
git clone https://github.com/jschicht/RunAsTI '/storage/nvme5/new_clones/AutoIt/RunAsTI' &
git clone https://github.com/igromanru/Dark-Souls-III-Cheat-Engine-Guide '/storage/nvme5/new_clones/AutoIt/Dark-Souls-III-Cheat-Engine-Guide' &
git clone https://github.com/jschicht/RawCopy '/storage/nvme5/new_clones/AutoIt/RawCopy' &
git clone https://github.com/bobsayshilol/luajit-decomp '/storage/nvme5/new_clones/AutoIt/luajit-decomp' &
git clone https://github.com/jschicht/Mft2Csv '/storage/nvme5/new_clones/AutoIt/Mft2Csv' &
git clone https://github.com/acalcutt/Vistumbler '/storage/nvme5/new_clones/AutoIt/Vistumbler' &
git clone https://github.com/sandwichdoge/MinimizeToTray '/storage/nvme5/new_clones/AutoIt/MinimizeToTray' &
git clone https://github.com/Universal-Rom-Tools/Universal-XML-Scraper '/storage/nvme5/new_clones/AutoIt/Universal-XML-Scraper' &
git clone https://github.com/jschicht/LogFileParser '/storage/nvme5/new_clones/AutoIt/LogFileParser' &
git clone https://github.com/broodplank/APKtoJava '/storage/nvme5/new_clones/AutoIt/APKtoJava' &
git clone https://github.com/ixjb94/ForceBindIP-Gui '/storage/nvme5/new_clones/AutoIt/ForceBindIP-Gui' &
git clone https://github.com/AJMartel/IRTriage '/storage/nvme5/new_clones/AutoIt/IRTriage' &
git clone https://github.com/sucresware/voicemeeter-activator-autoit '/storage/nvme5/new_clones/AutoIt/voicemeeter-activator-autoit' &
git clone https://github.com/fediaFedia/Omnimo '/storage/nvme5/new_clones/AutoIt/Omnimo' &
git clone https://github.com/jschicht/UsnJrnl2Csv '/storage/nvme5/new_clones/AutoIt/UsnJrnl2Csv' &
git clone https://github.com/Danp2/au3WebDriver '/storage/nvme5/new_clones/AutoIt/au3WebDriver' &
git clone https://github.com/jschicht/ExtractUsnJrnl '/storage/nvme5/new_clones/AutoIt/ExtractUsnJrnl' &
git clone https://github.com/9aylas/Shortcut-Payload-Generator '/storage/nvme5/new_clones/AutoIt/Shortcut-Payload-Generator' &
git clone https://github.com/xwxbug/autoit-cn '/storage/nvme5/new_clones/AutoIt/autoit-cn' &
git clone https://github.com/CodeSlinger69/ClAsHbOt '/storage/nvme5/new_clones/AutoIt/ClAsHbOt' &
git clone https://github.com/naver/guitar '/storage/nvme5/new_clones/AutoIt/guitar' &
git clone https://github.com/dragana-r/autoit-winhttp '/storage/nvme5/new_clones/AutoIt/autoit-winhttp' &
git clone https://github.com/chriv/dynephant '/storage/nvme5/new_clones/AutoIt/dynephant' &
git clone https://github.com/jmclaren7/windows-setup-helper '/storage/nvme5/new_clones/AutoIt/windows-setup-helper' &
git clone https://github.com/philpw99/Stash_Helper '/storage/nvme5/new_clones/AutoIt/Stash_Helper' &
git clone https://github.com/maxkingmax/OnekeyUnlock163music '/storage/nvme5/new_clones/AutoIt/OnekeyUnlock163music' &
git clone https://github.com/nonymoosee/CydiaImpactorLoader '/storage/nvme5/new_clones/AutoIt/CydiaImpactorLoader' &
git clone https://github.com/TheAlienDoctor/minecraft-resource-pack-converter '/storage/nvme5/new_clones/AutoIt/minecraft-resource-pack-converter' &
git clone https://github.com/angel333/infinimouse '/storage/nvme5/new_clones/AutoIt/infinimouse' &
git clone https://github.com/Kyromyr/D2Stats '/storage/nvme5/new_clones/AutoIt/D2Stats' &
git clone https://github.com/DcodingTheWeb/ProxAllium '/storage/nvme5/new_clones/AutoIt/ProxAllium' &
git clone https://github.com/Kirlovon/devil-backdoor '/storage/nvme5/new_clones/AutoIt/devil-backdoor' &
git clone https://github.com/xLinkOut/telegram-udf-autoit '/storage/nvme5/new_clones/AutoIt/telegram-udf-autoit' &
git clone https://github.com/jvanegmond/au3_uiautomation '/storage/nvme5/new_clones/AutoIt/au3_uiautomation' &
git clone https://github.com/sdoddler/D-D-Software-Suite '/storage/nvme5/new_clones/AutoIt/D-D-Software-Suite' &
git clone https://github.com/jschicht/SetMace '/storage/nvme5/new_clones/AutoIt/SetMace' &
git clone https://github.com/Lasse-B/Sx2vJoy-test '/storage/nvme5/new_clones/AutoIt/Sx2vJoy-test' &
git clone https://github.com/dmwyatt/soundswitch '/storage/nvme5/new_clones/AutoIt/soundswitch' &
git clone https://github.com/Pahiro/AutoIT-Scripts '/storage/nvme5/new_clones/AutoIt/AutoIT-Scripts' &
git clone https://github.com/KeshHere/POE-Timeless-Jewel-Finder '/storage/nvme5/new_clones/AutoIt/POE-Timeless-Jewel-Finder' &
git clone https://github.com/Devil4ngle/Idle_Slayer_Script '/storage/nvme5/new_clones/AutoIt/Idle_Slayer_Script' &
git clone https://github.com/Universal-Rom-Tools/Universal-ROM-Cleaner '/storage/nvme5/new_clones/AutoIt/Universal-ROM-Cleaner' &
git clone https://github.com/J2TEAM/AutoIt-UDF-Collection '/storage/nvme5/new_clones/AutoIt/AutoIt-UDF-Collection' &
git clone https://github.com/kost/rdpcmd '/storage/nvme5/new_clones/AutoIt/rdpcmd' &
git clone https://github.com/mosse-security/tactical-lab '/storage/nvme5/new_clones/AutoIt/tactical-lab' &
git clone https://github.com/yaseralnajjar/IDA-MSDN-helper '/storage/nvme5/new_clones/AutoIt/IDA-MSDN-helper' &
git clone https://github.com/jschicht/EaTools '/storage/nvme5/new_clones/AutoIt/EaTools' &
git clone https://github.com/cnjackchen/my-firefox '/storage/nvme5/new_clones/AutoIt/my-firefox' &
git clone https://github.com/crnlc/PlayHide '/storage/nvme5/new_clones/AutoIt/PlayHide' &
git clone https://github.com/3gstudent/AutoIt-Keylogger '/storage/nvme5/new_clones/AutoIt/AutoIt-Keylogger' &
git clone https://github.com/NYAN-x-CAT/AutoIt-PowerShell-Loader '/storage/nvme5/new_clones/AutoIt/AutoIt-PowerShell-Loader' &
git clone https://github.com/lamnhan066/HandleImgSearch '/storage/nvme5/new_clones/AutoIt/HandleImgSearch' &
git clone https://github.com/Lasse-B/Sx2vJoy '/storage/nvme5/new_clones/AutoIt/Sx2vJoy' &
git clone https://github.com/fortinet/ips-bph-framework '/storage/nvme5/new_clones/AutoIt/ips-bph-framework' &
git clone https://github.com/lanleft/CTF_Writeups '/storage/nvme5/new_clones/AutoIt/CTF_Writeups' &
git clone https://github.com/whatk233/FuckMythware '/storage/nvme5/new_clones/AutoIt/FuckMythware' &
git clone https://github.com/anadius/sims-4-tools '/storage/nvme5/new_clones/AutoIt/sims-4-tools' &
git clone https://github.com/CogentHub/HomeLoader '/storage/nvme5/new_clones/AutoIt/HomeLoader' &
git clone https://github.com/Bob74/TheHitchhikersHack '/storage/nvme5/new_clones/AutoIt/TheHitchhikersHack' &
git clone https://github.com/mcmilk/USB-Backup '/storage/nvme5/new_clones/AutoIt/USB-Backup' &
git clone https://github.com/jschicht/Indx2Csv '/storage/nvme5/new_clones/AutoIt/Indx2Csv' &
git clone https://github.com/ellysh/autoit-examples '/storage/nvme5/new_clones/AutoIt/autoit-examples' &
git clone https://github.com/tarreislam/Autoit-Socket-IO '/storage/nvme5/new_clones/AutoIt/Autoit-Socket-IO' &
git clone https://github.com/habohitron/habohitron '/storage/nvme5/new_clones/AutoIt/habohitron' &
git clone https://github.com/Lasse-B/GD-CPU-Affinity '/storage/nvme5/new_clones/AutoIt/GD-CPU-Affinity' &
git clone https://github.com/azuntik/Amidst-Seed-Hunter '/storage/nvme5/new_clones/AutoIt/Amidst-Seed-Hunter' &
git clone https://github.com/suppqt/KodiXBMCTextureTool '/storage/nvme5/new_clones/AutoIt/KodiXBMCTextureTool' &
git clone https://github.com/jschicht/PowerMft '/storage/nvme5/new_clones/AutoIt/PowerMft' &
git clone https://github.com/FarPerformance/UniversalRomSorter '/storage/nvme5/new_clones/AutoIt/UniversalRomSorter' &
git clone https://github.com/J2TEAM/chrome-extension-checker '/storage/nvme5/new_clones/AutoIt/chrome-extension-checker' &
git clone https://github.com/jesobreira/HTTP.au3 '/storage/nvme5/new_clones/AutoIt/HTTP.au3' &
git clone https://github.com/genius257/AutoIt-HTTP-Server '/storage/nvme5/new_clones/AutoIt/AutoIt-HTTP-Server' &
git clone https://github.com/haikejishu/APK-Info '/storage/nvme5/new_clones/AutoIt/APK-Info' &
git clone https://github.com/Revers3c-Team/CTF-writeups '/storage/nvme5/new_clones/AutoIt/CTF-writeups' &
git clone https://github.com/TheLazyGamer/MapleBot '/storage/nvme5/new_clones/AutoIt/MapleBot' &
git clone https://github.com/jschicht/Secure2Csv '/storage/nvme5/new_clones/AutoIt/Secure2Csv' &
git clone https://github.com/Twombs/GOGcli-GUI '/storage/nvme5/new_clones/AutoIt/GOGcli-GUI' &
git clone https://github.com/BigRedBot/NeverwinterInvokeBot '/storage/nvme5/new_clones/AutoIt/NeverwinterInvokeBot' &
git clone https://github.com/AetherCollective/PortableApps-App-Creation-Wizard '/storage/nvme5/new_clones/AutoIt/PortableApps-App-Creation-Wizard' &
git clone https://github.com/DanysysTeam/VirusTotal '/storage/nvme5/new_clones/AutoIt/VirusTotal' &
git clone https://github.com/AetherCollective/AndyRoot '/storage/nvme5/new_clones/AutoIt/AndyRoot' &
git clone https://github.com/jschicht/NtfsFileExtractor '/storage/nvme5/new_clones/AutoIt/NtfsFileExtractor' &
git clone https://github.com/J2TEAM/AutoIt-Imgur-UDF '/storage/nvme5/new_clones/AutoIt/AutoIt-Imgur-UDF' &
git clone https://github.com/DeeLMind/anVirus '/storage/nvme5/new_clones/AutoIt/anVirus' &
git clone https://github.com/Gianfranco753/Parsec-Shortcut '/storage/nvme5/new_clones/AutoIt/Parsec-Shortcut' &
git clone https://github.com/NetSPI/DataLoc '/storage/nvme5/new_clones/AutoIt/DataLoc' &
git clone https://github.com/ArsenalRecon/SdbaParser '/storage/nvme5/new_clones/AutoIt/SdbaParser' &
git clone https://github.com/htejera/AutoItMonkey '/storage/nvme5/new_clones/AutoIt/AutoItMonkey' &
git clone https://github.com/bustd86/bing-dork-scanner '/storage/nvme5/new_clones/AutoIt/bing-dork-scanner' &
git clone https://github.com/MingguiLu/Helpdesk_Automatic_configuration_Tool '/storage/nvme5/new_clones/AutoIt/Helpdesk_Automatic_configuration_Tool' &
git clone https://github.com/roustar31/RPK_USB_System '/storage/nvme5/new_clones/AutoIt/RPK_USB_System' &
git clone https://github.com/xlimit91/FastFindAutoIt '/storage/nvme5/new_clones/AutoIt/FastFindAutoIt' &
git clone https://github.com/ca-x/WindowsNT6-QuickSet '/storage/nvme5/new_clones/AutoIt/WindowsNT6-QuickSet' &
git clone https://github.com/jschicht/SetRegTime '/storage/nvme5/new_clones/AutoIt/SetRegTime' &
git clone https://github.com/AetherCollective/Parsec-Remote-Launcher '/storage/nvme5/new_clones/AutoIt/Parsec-Remote-Launcher' &
git clone https://github.com/jschicht/MftCarver '/storage/nvme5/new_clones/AutoIt/MftCarver' &
git clone https://github.com/taburineagle/MPC-HC-Looper '/storage/nvme5/new_clones/AutoIt/MPC-HC-Looper' &
git clone https://github.com/liagason/Standard-Keylogger '/storage/nvme5/new_clones/AutoIt/Standard-Keylogger' &
git clone https://github.com/tarreislam/Autoit-API-WS '/storage/nvme5/new_clones/AutoIt/Autoit-API-WS' &
git clone https://github.com/jschicht/HideAndProtect '/storage/nvme5/new_clones/AutoIt/HideAndProtect' &
git clone https://github.com/topcss/Aria2Downloader '/storage/nvme5/new_clones/AutoIt/Aria2Downloader' &
git clone https://github.com/DanysysTeam/UWPOCR '/storage/nvme5/new_clones/AutoIt/UWPOCR' &
git clone https://github.com/genius257/AutoItObject-Internal '/storage/nvme5/new_clones/AutoIt/AutoItObject-Internal' &
git clone https://github.com/Webschool-io/Ensino-Superior-de-Informatica-GRATUITO '/storage/nvme5/new_clones/AutoIt/Ensino-Superior-de-Informatica-GRATUITO' &
git clone https://github.com/phoenix125/DiscordSendWebhook '/storage/nvme5/new_clones/AutoIt/DiscordSendWebhook' &
git clone https://github.com/alexandruavadanii/USSF '/storage/nvme5/new_clones/AutoIt/USSF' &
git clone https://github.com/J2TEAM/autoit-updater '/storage/nvme5/new_clones/AutoIt/autoit-updater' &
git clone https://github.com/Adarma/DXL '/storage/nvme5/new_clones/AutoIt/DXL' &
git clone https://github.com/traversc/DDO-ML '/storage/nvme5/new_clones/AutoIt/DDO-ML' &
git clone https://github.com/Henry14all/Mr.Music '/storage/nvme5/new_clones/AutoIt/Mr.Music' &
git clone https://github.com/cystack/monero-mining-malware '/storage/nvme5/new_clones/AutoIt/monero-mining-malware' &
git clone https://github.com/tduyduc/lol-vs-bots-assist '/storage/nvme5/new_clones/AutoIt/lol-vs-bots-assist' &
git clone https://github.com/ftuyama/duel-links-bot '/storage/nvme5/new_clones/AutoIt/duel-links-bot' &
git clone https://github.com/dodaucy/auWin '/storage/nvme5/new_clones/AutoIt/auWin' &
git clone https://github.com/pyrroman/AutoLog '/storage/nvme5/new_clones/AutoIt/AutoLog' &
git clone https://github.com/PecuniaK/IDMRest '/storage/nvme5/new_clones/AutoIt/IDMRest' &
git clone https://github.com/Twombs/GOGRepo-GUI '/storage/nvme5/new_clones/AutoIt/GOGRepo-GUI' &
git clone https://github.com/simplymercurial/ObfuscatorSG '/storage/nvme5/new_clones/AutoIt/ObfuscatorSG' &
git clone https://github.com/jschicht/StegoMft '/storage/nvme5/new_clones/AutoIt/StegoMft' &
git clone https://github.com/admiralmachado/AutoIt-Uplay '/storage/nvme5/new_clones/AutoIt/AutoIt-Uplay' &
git clone https://github.com/sinky/runscreensaver '/storage/nvme5/new_clones/AutoIt/runscreensaver' &
git clone https://github.com/jesobreira/authread '/storage/nvme5/new_clones/AutoIt/authread' &
git clone https://github.com/jvanegmond/hotstrings '/storage/nvme5/new_clones/AutoIt/hotstrings' &
git clone https://github.com/jesobreira/thread.au3 '/storage/nvme5/new_clones/AutoIt/thread.au3' &
git clone https://github.com/darkdaddy/Lineage2RevBot '/storage/nvme5/new_clones/AutoIt/Lineage2RevBot' &
git clone https://github.com/Airi85/OsuMultiTool '/storage/nvme5/new_clones/AutoIt/OsuMultiTool' &
git clone https://github.com/lundbird/Recorder-Spy '/storage/nvme5/new_clones/AutoIt/Recorder-Spy' &
git clone https://github.com/tarreislam/TeenyScript '/storage/nvme5/new_clones/AutoIt/TeenyScript' &
git clone https://github.com/Mickosis/lrn2play '/storage/nvme5/new_clones/AutoIt/lrn2play' &
git clone https://github.com/edingc/autoit-scripts '/storage/nvme5/new_clones/AutoIt/autoit-scripts' &
git clone https://github.com/docToolchain/docs-as-co.de '/storage/nvme5/new_clones/AutoIt/docs-as-co.de' &
git clone https://github.com/jschicht/MftRcrd '/storage/nvme5/new_clones/AutoIt/MftRcrd' &
git clone https://github.com/ArsenalRecon/NetWireLogDecoder '/storage/nvme5/new_clones/AutoIt/NetWireLogDecoder' &
git clone https://github.com/phoenix125/AtlasServerUpdateUtility '/storage/nvme5/new_clones/AutoIt/AtlasServerUpdateUtility' &
git clone https://github.com/Universal-Rom-Tools/Universal-XML-Editor '/storage/nvme5/new_clones/AutoIt/Universal-XML-Editor' &
git clone https://github.com/9aylas/RDP-Checker '/storage/nvme5/new_clones/AutoIt/RDP-Checker' &
git clone https://github.com/mayankmetha/HackingTools '/storage/nvme5/new_clones/AutoIt/HackingTools' &
git clone https://github.com/jschicht/UsnJrnlCarver '/storage/nvme5/new_clones/AutoIt/UsnJrnlCarver' &
git clone https://github.com/Sylfaen2/Firemin '/storage/nvme5/new_clones/AutoIt/Firemin' &
git clone https://github.com/pulipulichen/AutoIt-Archive-Util '/storage/nvme5/new_clones/AutoIt/AutoIt-Archive-Util' &
git clone https://github.com/chunqiuyiyu/spotlight-wallpaper '/storage/nvme5/new_clones/AutoIt/spotlight-wallpaper' &
git clone https://github.com/elsemieni/RPGMaker2k3VarInspector '/storage/nvme5/new_clones/AutoIt/RPGMaker2k3VarInspector' &
git clone https://github.com/ADEOSec/PowerShellRAT '/storage/nvme5/new_clones/AutoIt/PowerShellRAT' &
git clone https://github.com/htejera/ImperiusAutoIt '/storage/nvme5/new_clones/AutoIt/ImperiusAutoIt' &
git clone https://github.com/shtrih/idea-for-autoit '/storage/nvme5/new_clones/AutoIt/idea-for-autoit' &
git clone https://github.com/voxvanhieu/kyts-font-viewer '/storage/nvme5/new_clones/AutoIt/kyts-font-viewer' &
git clone https://github.com/silentmonero/Monero-It '/storage/nvme5/new_clones/AutoIt/Monero-It' &
git clone https://github.com/FuatCemOzyazici/USBPasswordStealerVirus '/storage/nvme5/new_clones/AutoIt/USBPasswordStealerVirus' &
git clone https://github.com/MurageKabui/In2batch '/storage/nvme5/new_clones/AutoIt/In2batch' &
git clone https://github.com/NorddeutscherRundfunk/R128 '/storage/nvme5/new_clones/AutoIt/R128' &
git clone https://github.com/alex47exe/UniGame-Launcher '/storage/nvme5/new_clones/AutoIt/UniGame-Launcher' &
git clone https://github.com/Strydir/SSLoader '/storage/nvme5/new_clones/AutoIt/SSLoader' &
git clone https://github.com/J2TEAM/malware-scanner '/storage/nvme5/new_clones/AutoIt/malware-scanner' &
git clone https://github.com/rcmaehl/MumboOBS '/storage/nvme5/new_clones/AutoIt/MumboOBS' &
git clone https://github.com/gravitylens/CyberArkCPM-PSM-Customziations '/storage/nvme5/new_clones/AutoIt/CyberArkCPM-PSM-Customziations' &
git clone https://github.com/Se7enstars/AutoIt-SciTE-Theme '/storage/nvme5/new_clones/AutoIt/AutoIt-SciTE-Theme' &
git clone https://github.com/ulfgebhardt/autoit_wowfishingbot '/storage/nvme5/new_clones/AutoIt/autoit_wowfishingbot' &
git clone https://github.com/jschicht/IndxCarver '/storage/nvme5/new_clones/AutoIt/IndxCarver' &
git clone https://github.com/HongThatCong/Malware_Scripts_Sources '/storage/nvme5/new_clones/AutoIt/Malware_Scripts_Sources' &
git clone https://github.com/n0ot/nutils '/storage/nvme5/new_clones/AutoIt/nutils' &
git clone https://github.com/9aylas/UNkillable-Process '/storage/nvme5/new_clones/AutoIt/UNkillable-Process' &
git clone https://github.com/jesobreira/TCPServerUDF '/storage/nvme5/new_clones/AutoIt/TCPServerUDF' &
git clone https://github.com/nterl0k/CEF-Syslog-Canary '/storage/nvme5/new_clones/AutoIt/CEF-Syslog-Canary' &
git clone https://github.com/baorv/keylogger '/storage/nvme5/new_clones/AutoIt/keylogger' &
git clone https://github.com/Matze1985/GlucoTT '/storage/nvme5/new_clones/AutoIt/GlucoTT' &
git clone https://github.com/CrayonCodeGit/CrayonCode-BDO-Project '/storage/nvme5/new_clones/AutoIt/CrayonCode-BDO-Project' &
git clone https://github.com/uroesch/PlinkProxy '/storage/nvme5/new_clones/AutoIt/PlinkProxy' &
git clone https://github.com/Bioruebe/LevelUp '/storage/nvme5/new_clones/AutoIt/LevelUp' &
git clone https://github.com/pyrroman/au3-boilerplate '/storage/nvme5/new_clones/AutoIt/au3-boilerplate' &
git clone https://github.com/MoriceD3/D3ROS-ArreatCore '/storage/nvme5/new_clones/AutoIt/D3ROS-ArreatCore' &
git clone https://github.com/budm/IdleR '/storage/nvme5/new_clones/AutoIt/IdleR' &
git clone https://github.com/biodrone/AutoIt '/storage/nvme5/new_clones/AutoIt/AutoIt' &
git clone https://github.com/glyphx/WTC-MINER-PRO '/storage/nvme5/new_clones/AutoIt/WTC-MINER-PRO' &
git clone https://github.com/lxegs/bitwig '/storage/nvme5/new_clones/AutoIt/bitwig' &
git clone https://github.com/Silvernine0S/FolderMenu3EX '/storage/nvme5/new_clones/AutoIt/FolderMenu3EX' &
git clone https://github.com/svn2github/WSUSOfflineUpdate '/storage/nvme5/new_clones/AutoIt/WSUSOfflineUpdate' &
git clone https://github.com/pyrroman/Autoit '/storage/nvme5/new_clones/AutoIt/Autoit' &
git clone https://github.com/DanysysTeam/Loga '/storage/nvme5/new_clones/AutoIt/Loga' &
git clone https://github.com/Zodsmar/Amidst-Seed-Hunter-1.13 '/storage/nvme5/new_clones/AutoIt/Amidst-Seed-Hunter-1.13' &
git clone https://github.com/rcmaehl/SteamValidator '/storage/nvme5/new_clones/AutoIt/SteamValidator' &
git clone https://github.com/justaminer/hsrm-fork '/storage/nvme5/new_clones/AutoIt/hsrm-fork' &
git clone https://github.com/easonjim/Installed_Tools '/storage/nvme5/new_clones/AutoIt/Installed_Tools' &
git clone https://github.com/MattDiesel/au3-console '/storage/nvme5/new_clones/AutoIt/au3-console' &
git clone https://github.com/lamnhan066/Flickr-API '/storage/nvme5/new_clones/AutoIt/Flickr-API' &
git clone https://github.com/jschicht/MyDiskEraser '/storage/nvme5/new_clones/AutoIt/MyDiskEraser' &
git clone https://github.com/kadrim/PrimoCacheBackupDetect '/storage/nvme5/new_clones/AutoIt/PrimoCacheBackupDetect' &
git clone https://github.com/easonjim/Smart_Driver '/storage/nvme5/new_clones/AutoIt/Smart_Driver' &
git clone https://github.com/9aylas/PE-Binary-Dumper '/storage/nvme5/new_clones/AutoIt/PE-Binary-Dumper' &
git clone https://github.com/thesunRider/Utter '/storage/nvme5/new_clones/AutoIt/Utter' &
git clone https://github.com/GarethAyres/SU1X '/storage/nvme5/new_clones/AutoIt/SU1X' &
git clone https://github.com/wodim/hitchhiker '/storage/nvme5/new_clones/AutoIt/hitchhiker' &
git clone https://github.com/CremaFR/AutoClickerHeroes '/storage/nvme5/new_clones/AutoIt/AutoClickerHeroes' &
git clone https://github.com/opdo/autoit-msgbox '/storage/nvme5/new_clones/AutoIt/autoit-msgbox' &
git clone https://github.com/bdunlap9/CryptoWire-Ransomware '/storage/nvme5/new_clones/AutoIt/CryptoWire-Ransomware' &
git clone https://github.com/EVEHarvester/EVE-harvester '/storage/nvme5/new_clones/AutoIt/EVE-harvester' &
git clone https://github.com/Yanni79/PWDPaste '/storage/nvme5/new_clones/AutoIt/PWDPaste' &
git clone https://github.com/jcageman/d2itemreader '/storage/nvme5/new_clones/AutoIt/d2itemreader' &
git clone https://github.com/thedemons/demem '/storage/nvme5/new_clones/AutoIt/demem' &
git clone https://github.com/310ken1/AutoItSciTEj '/storage/nvme5/new_clones/AutoIt/AutoItSciTEj' &
git clone https://github.com/rcmaehl/PFUEL '/storage/nvme5/new_clones/AutoIt/PFUEL' &
git clone https://github.com/genius257/AutoIt-HTML-Parser '/storage/nvme5/new_clones/AutoIt/AutoIt-HTML-Parser' &
git clone https://github.com/jsRuner/wow-tool '/storage/nvme5/new_clones/AutoIt/wow-tool' &
git clone https://github.com/MattDiesel/Ault '/storage/nvme5/new_clones/AutoIt/Ault' &
git clone https://github.com/tduyduc/lol-teamfight-tactics-assist '/storage/nvme5/new_clones/AutoIt/lol-teamfight-tactics-assist' &
git clone https://github.com/genius257/au3json '/storage/nvme5/new_clones/AutoIt/au3json' &
git clone https://github.com/mcflythekid/hayday-wheater '/storage/nvme5/new_clones/AutoIt/hayday-wheater' &
git clone https://github.com/pokerregion/pokerstars-autoit '/storage/nvme5/new_clones/AutoIt/pokerstars-autoit' &
git clone https://github.com/valerium-labs/zx-unikeyboard '/storage/nvme5/new_clones/AutoIt/zx-unikeyboard' &
git clone https://github.com/Elm0D/AutoIT-Malware '/storage/nvme5/new_clones/AutoIt/AutoIT-Malware' &
git clone https://github.com/Findoss/Rainmeter-skin-configurator '/storage/nvme5/new_clones/AutoIt/Rainmeter-skin-configurator' &
git clone https://github.com/731942771/AutoitWorkingRecorder '/storage/nvme5/new_clones/AutoIt/AutoitWorkingRecorder' &
git clone https://github.com/Anh76PC/autoLOL '/storage/nvme5/new_clones/AutoIt/autoLOL' &
git clone https://github.com/feklee/external-exe '/storage/nvme5/new_clones/AutoIt/external-exe' &
git clone https://github.com/phoenix125/7dtdServerUpdateUtility '/storage/nvme5/new_clones/AutoIt/7dtdServerUpdateUtility' &
git clone https://github.com/Fliegerfaust33/SelectBot '/storage/nvme5/new_clones/AutoIt/SelectBot' &
git clone https://github.com/OneIdentity/SafeguardAutomation '/storage/nvme5/new_clones/AutoIt/SafeguardAutomation' &
git clone https://github.com/J2TEAM/autoit-about-udf '/storage/nvme5/new_clones/AutoIt/autoit-about-udf' &
git clone https://github.com/SymonGonthiez/SymonCrypter '/storage/nvme5/new_clones/AutoIt/SymonCrypter' &
git clone https://github.com/thedemons/AutoitSimpleDatabase '/storage/nvme5/new_clones/AutoIt/AutoitSimpleDatabase' &
git clone https://github.com/JoshuaDoes/TWLIt '/storage/nvme5/new_clones/AutoIt/TWLIt' &
git clone https://github.com/davidgaroro/ftool-by-garu '/storage/nvme5/new_clones/AutoIt/ftool-by-garu' &
git clone https://github.com/genius257/AutoIt-projects '/storage/nvme5/new_clones/AutoIt/AutoIt-projects' &
git clone https://github.com/genius257/au3pm '/storage/nvme5/new_clones/AutoIt/au3pm' &
git clone https://github.com/doublecmd/dcupdater '/storage/nvme5/new_clones/AutoIt/dcupdater' &
git clone https://github.com/danielgianni/urnaCIPA '/storage/nvme5/new_clones/AutoIt/urnaCIPA' &
git clone https://github.com/Twombs/Steam-Games-List '/storage/nvme5/new_clones/AutoIt/Steam-Games-List' &
git clone https://github.com/AutoItMicro/MicroUnitTestingFramework '/storage/nvme5/new_clones/AutoIt/MicroUnitTestingFramework' &
git clone https://github.com/kyawswarthwin/Huawei-Product-ID-Generator '/storage/nvme5/new_clones/AutoIt/Huawei-Product-ID-Generator' &
git clone https://github.com/MeltyLauncher/MeltyLauncher '/storage/nvme5/new_clones/AutoIt/MeltyLauncher' &
git clone https://github.com/chemicalfiber/Anti-DrvCeo '/storage/nvme5/new_clones/AutoIt/Anti-DrvCeo' &
git clone https://github.com/jesobreira/forceutf8_au3 '/storage/nvme5/new_clones/AutoIt/forceutf8_au3' &
git clone https://github.com/J2TEAM-dev/IDM-UDF '/storage/nvme5/new_clones/AutoIt/IDM-UDF' &
git clone https://github.com/ChrisAnd1998/Falcon10-AutoIt '/storage/nvme5/new_clones/AutoIt/Falcon10-AutoIt' &
git clone https://github.com/igromanru/UE-SDK-Offsets-Updater-AutoIt '/storage/nvme5/new_clones/AutoIt/UE-SDK-Offsets-Updater-AutoIt' &
git clone https://github.com/phoenix125/UniFiCameraImageArchiverFTPUploader '/storage/nvme5/new_clones/AutoIt/UniFiCameraImageArchiverFTPUploader' &
git clone https://github.com/tarreislam/Autoit-Serialize '/storage/nvme5/new_clones/AutoIt/Autoit-Serialize' &
git clone https://github.com/mrHalfer/The-Witcher-3-Ultrawide-NoBlackBars-Fix-NextGen '/storage/nvme5/new_clones/AutoIt/The-Witcher-3-Ultrawide-NoBlackBars-Fix-NextGen' &
git clone https://github.com/kyawswarthwin/Huawei-Unlocker '/storage/nvme5/new_clones/AutoIt/Huawei-Unlocker' &
git clone https://github.com/LeoSimp/ButtonClick_AutoIT '/storage/nvme5/new_clones/AutoIt/ButtonClick_AutoIT' &
git clone https://github.com/VJ-Duardo/Spamerino '/storage/nvme5/new_clones/AutoIt/Spamerino' &
git clone https://github.com/jschicht/RcrdCarver '/storage/nvme5/new_clones/AutoIt/RcrdCarver' &
git clone https://github.com/rcmaehl/IRC-UDFs '/storage/nvme5/new_clones/AutoIt/IRC-UDFs' &
git clone https://github.com/rheek123/GwBotApiPatcher '/storage/nvme5/new_clones/AutoIt/GwBotApiPatcher' &
git clone https://github.com/pedrowarlock/PandoraBox3-WindowsVersion '/storage/nvme5/new_clones/AutoIt/PandoraBox3-WindowsVersion' &
git clone https://github.com/jschicht/RegKeyFixer '/storage/nvme5/new_clones/AutoIt/RegKeyFixer' &
git clone https://github.com/MyBotRun/CoCBot '/storage/nvme5/new_clones/AutoIt/CoCBot' &
git clone https://github.com/rimoun-g/Autoit_WdReplacer-Autoit '/storage/nvme5/new_clones/AutoIt/Autoit_WdReplacer-Autoit' &
git clone https://github.com/jesobreira/TCPClient-UDF '/storage/nvme5/new_clones/AutoIt/TCPClient-UDF' &
git clone https://github.com/Legobas/HiLink '/storage/nvme5/new_clones/AutoIt/HiLink' &
git clone https://github.com/Pure-Battlefield/Seeding '/storage/nvme5/new_clones/AutoIt/Seeding' &
git clone https://github.com/Naviss53/MDT_AUTOLOGON '/storage/nvme5/new_clones/AutoIt/MDT_AUTOLOGON' &
git clone https://github.com/wsguest/LiveRobot '/storage/nvme5/new_clones/AutoIt/LiveRobot' &
git clone https://github.com/matwachich/autoit-guiutils '/storage/nvme5/new_clones/AutoIt/autoit-guiutils' &
