#!/bin/bash

git clone https://github.com/ballerina-platform/ballerina-lang '/storage/nvme5/new_clones/Ballerina/ballerina-lang' &
git clone https://github.com/ballerina-platform/module-ballerina-graphql '/storage/nvme5/new_clones/Ballerina/module-ballerina-graphql' &
git clone https://github.com/ballerina-platform/nballerina '/storage/nvme5/new_clones/Ballerina/nballerina' &
git clone https://github.com/ballerina-platform/ballerina-library '/storage/nvme5/new_clones/Ballerina/ballerina-library' &
git clone https://github.com/ballerina-platform/module-ballerina-jwt '/storage/nvme5/new_clones/Ballerina/module-ballerina-jwt' &
git clone https://github.com/ballerina-platform/module-ballerina-grpc '/storage/nvme5/new_clones/Ballerina/module-ballerina-grpc' &
git clone https://github.com/ballerina-platform/module-ballerinax-mongodb '/storage/nvme5/new_clones/Ballerina/module-ballerinax-mongodb' &
git clone https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail '/storage/nvme5/new_clones/Ballerina/module-ballerinax-googleapis.gmail' &
git clone https://github.com/ballerina-platform/openapi-connectors '/storage/nvme5/new_clones/Ballerina/openapi-connectors' &
git clone https://github.com/ballerina-platform/module-ballerinax-nats '/storage/nvme5/new_clones/Ballerina/module-ballerinax-nats' &
git clone https://github.com/ballerina-platform/module-ballerinax-github '/storage/nvme5/new_clones/Ballerina/module-ballerinax-github' &
git clone https://github.com/ballerina-platform/module-ballerina-oauth2 '/storage/nvme5/new_clones/Ballerina/module-ballerina-oauth2' &
git clone https://github.com/ballerina-platform/module-ballerina-io '/storage/nvme5/new_clones/Ballerina/module-ballerina-io' &
git clone https://github.com/ballerina-platform/ballerina-grammar '/storage/nvme5/new_clones/Ballerina/ballerina-grammar' &
git clone https://github.com/ballerina-platform/module-ballerina-websub '/storage/nvme5/new_clones/Ballerina/module-ballerina-websub' &
git clone https://github.com/ballerina-platform/module-ballerinax-kafka '/storage/nvme5/new_clones/Ballerina/module-ballerinax-kafka' &
git clone https://github.com/ballerina-platform/module-ballerina-crypto '/storage/nvme5/new_clones/Ballerina/module-ballerina-crypto' &
git clone https://github.com/ballerina-platform/module-ballerinax-azure-cosmosdb '/storage/nvme5/new_clones/Ballerina/module-ballerinax-azure-cosmosdb' &
git clone https://github.com/ballerina-platform/module-ballerinax-twilio '/storage/nvme5/new_clones/Ballerina/module-ballerinax-twilio' &
git clone https://github.com/ballerina-platform/module-ballerinax-twitter '/storage/nvme5/new_clones/Ballerina/module-ballerinax-twitter' &
git clone https://github.com/ballerina-platform/module-ballerinax-java.jdbc '/storage/nvme5/new_clones/Ballerina/module-ballerinax-java.jdbc' &
git clone https://github.com/ballerina-platform/module-ballerina-cache '/storage/nvme5/new_clones/Ballerina/module-ballerina-cache' &
git clone https://github.com/ballerina-platform/module-ballerinax-mysql '/storage/nvme5/new_clones/Ballerina/module-ballerinax-mysql' &
git clone https://github.com/ballerina-platform/module-ballerina-log '/storage/nvme5/new_clones/Ballerina/module-ballerina-log' &
git clone https://github.com/ballerina-platform/module-ballerinax-salesforce '/storage/nvme5/new_clones/Ballerina/module-ballerinax-salesforce' &
git clone https://github.com/ballerina-platform/module-ballerinax-netsuite '/storage/nvme5/new_clones/Ballerina/module-ballerinax-netsuite' &
git clone https://github.com/ballerina-platform/module-ballerinax-slack '/storage/nvme5/new_clones/Ballerina/module-ballerinax-slack' &
git clone https://github.com/ballerina-platform/module-ballerinax-googleapis.sheets '/storage/nvme5/new_clones/Ballerina/module-ballerinax-googleapis.sheets' &
git clone https://github.com/ballerina-platform/module-ballerina-soap '/storage/nvme5/new_clones/Ballerina/module-ballerina-soap' &
git clone https://github.com/ballerina-platform/module-ballerina-websubhub '/storage/nvme5/new_clones/Ballerina/module-ballerina-websubhub' &
git clone https://github.com/ballerina-platform/module-ballerina-uuid '/storage/nvme5/new_clones/Ballerina/module-ballerina-uuid' &
git clone https://github.com/ballerina-platform/module-ballerina-xmldata '/storage/nvme5/new_clones/Ballerina/module-ballerina-xmldata' &
git clone https://github.com/ballerina-platform/module-ballerinax-googleapis.calendar '/storage/nvme5/new_clones/Ballerina/module-ballerinax-googleapis.calendar' &
git clone https://github.com/ballerina-platform/module-ballerinax-postgresql '/storage/nvme5/new_clones/Ballerina/module-ballerinax-postgresql' &
git clone https://github.com/ballerina-platform/module-ballerina-file '/storage/nvme5/new_clones/Ballerina/module-ballerina-file' &
git clone https://github.com/ballerina-platform/module-ballerina-time '/storage/nvme5/new_clones/Ballerina/module-ballerina-time' &
git clone https://github.com/ballerina-platform/module-ballerinai-transaction '/storage/nvme5/new_clones/Ballerina/module-ballerinai-transaction' &
git clone https://github.com/ballerina-platform/module-ballerina-url '/storage/nvme5/new_clones/Ballerina/module-ballerina-url' &
git clone https://github.com/ballerina-platform/module-ballerinax-azure-storage-service '/storage/nvme5/new_clones/Ballerina/module-ballerinax-azure-storage-service' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.onedrive' &
git clone https://github.com/ballerina-platform/module-ballerinax-rabbitmq '/storage/nvme5/new_clones/Ballerina/module-ballerinax-rabbitmq' &
git clone https://github.com/ballerina-platform/module-ballerinax-mssql '/storage/nvme5/new_clones/Ballerina/module-ballerinax-mssql' &
git clone https://github.com/ballerina-attic/playground '/storage/nvme5/new_clones/Ballerina/playground' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.s3 '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.s3' &
git clone https://github.com/ballerina-platform/module-ballerinax-oracledb '/storage/nvme5/new_clones/Ballerina/module-ballerinax-oracledb' &
git clone https://github.com/ballerina-platform/module-ballerinax-java.jms '/storage/nvme5/new_clones/Ballerina/module-ballerinax-java.jms' &
git clone https://github.com/ballerina-platform/module-ballerinax-mysql.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-mysql.driver' &
git clone https://github.com/ballerina-platform/module-ballerina-constraint '/storage/nvme5/new_clones/Ballerina/module-ballerina-constraint' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.sqs '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.sqs' &
git clone https://github.com/ballerina-platform/module-ballerina-jballerina.java.arrays '/storage/nvme5/new_clones/Ballerina/module-ballerina-jballerina.java.arrays' &
git clone https://github.com/ballerina-platform/module-ballerina-regex '/storage/nvme5/new_clones/Ballerina/module-ballerina-regex' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.dynamodb '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.dynamodb' &
git clone https://github.com/ballerina-platform/module-ballerina-random '/storage/nvme5/new_clones/Ballerina/module-ballerina-random' &
git clone https://github.com/ballerina-platform/module-ballerinax-azure.eventhub '/storage/nvme5/new_clones/Ballerina/module-ballerinax-azure.eventhub' &
git clone https://github.com/ballerina-platform/module-ballerinax-googleapis.drive '/storage/nvme5/new_clones/Ballerina/module-ballerinax-googleapis.drive' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.excel '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.excel' &
git clone https://github.com/ballerina-platform/module-ballerinax-mssql.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-mssql.driver' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.ses '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.ses' &
git clone https://github.com/ballerina-platform/module-ballerinax-googleapis.people '/storage/nvme5/new_clones/Ballerina/module-ballerinax-googleapis.people' &
git clone https://github.com/ballerina-platform/module-ballerinax-peoplehr '/storage/nvme5/new_clones/Ballerina/module-ballerinax-peoplehr' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.sns '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.sns' &
git clone https://github.com/ballerina-platform/asyncapi-triggers '/storage/nvme5/new_clones/Ballerina/asyncapi-triggers' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.onenote '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.onenote' &
git clone https://github.com/ballerina-platform/module-ballerinax-azure.ad '/storage/nvme5/new_clones/Ballerina/module-ballerinax-azure.ad' &
git clone https://github.com/ballerina-platform/persist-tools '/storage/nvme5/new_clones/Ballerina/persist-tools' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.teams '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.teams' &
git clone https://github.com/ballerina-platform/module-ballerinax-oracledb.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-oracledb.driver' &
git clone https://github.com/ballerina-platform/module-ballerinax-aws.simpledb '/storage/nvme5/new_clones/Ballerina/module-ballerinax-aws.simpledb' &
git clone https://github.com/ballerina-platform/module-ballerinax-postgresql.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-postgresql.driver' &
git clone https://github.com/ballerina-platform/module-ballerinax-snowflake '/storage/nvme5/new_clones/Ballerina/module-ballerinax-snowflake' &
git clone https://github.com/ballerina-platform/module-ballerina-toml '/storage/nvme5/new_clones/Ballerina/module-ballerina-toml' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.outlook.calendar' &
git clone https://github.com/ballerina-platform/module-ballerinax-snowflake.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-snowflake.driver' &
git clone https://github.com/ballerina-platform/protoc-tools '/storage/nvme5/new_clones/Ballerina/protoc-tools' &
git clone https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.mail '/storage/nvme5/new_clones/Ballerina/module-ballerinax-microsoft.outlook.mail' &
git clone https://github.com/ballerina-platform/module-ballerinax-cdata.connect.driver '/storage/nvme5/new_clones/Ballerina/module-ballerinax-cdata.connect.driver' &
git clone https://github.com/ballerina-platform/module-ballerina-yaml '/storage/nvme5/new_clones/Ballerina/module-ballerina-yaml' &
git clone https://github.com/ballerina-platform/module-ballerinax-scim '/storage/nvme5/new_clones/Ballerina/module-ballerinax-scim' &
git clone https://github.com/ballerina-platform/module-ballerinax-client.config '/storage/nvme5/new_clones/Ballerina/module-ballerinax-client.config' &
git clone https://github.com/wso2/choreo-apim-mediation-policies '/storage/nvme5/new_clones/Ballerina/choreo-apim-mediation-policies' &
git clone https://github.com/oracle/ballerina-oci '/storage/nvme5/new_clones/Ballerina/ballerina-oci' &
git clone https://github.com/prabath/ballerina-security '/storage/nvme5/new_clones/Ballerina/ballerina-security' &
git clone https://github.com/ballerina-guides/gcp-microservices-demo '/storage/nvme5/new_clones/Ballerina/gcp-microservices-demo' &
git clone https://github.com/ballerina-attic/playground-hello-service '/storage/nvme5/new_clones/Ballerina/playground-hello-service' &
git clone https://github.com/ballerina-attic/ballerina-demo '/storage/nvme5/new_clones/Ballerina/ballerina-demo' &
git clone https://github.com/ECLK/Results-Dist '/storage/nvme5/new_clones/Ballerina/Results-Dist' &
git clone https://github.com/madusankanipunajith/Ballerina-JSON-RPC '/storage/nvme5/new_clones/Ballerina/Ballerina-JSON-RPC' &
git clone https://github.com/kaviththiranga/ballerina-day-tooling-tutorial '/storage/nvme5/new_clones/Ballerina/ballerina-day-tooling-tutorial' &
git clone https://github.com/lakwarus/microservices-with-grpc '/storage/nvme5/new_clones/Ballerina/microservices-with-grpc' &
git clone https://github.com/jclark/semtype '/storage/nvme5/new_clones/Ballerina/semtype' &
git clone https://github.com/ballerina-attic/restful-service '/storage/nvme5/new_clones/Ballerina/restful-service' &
git clone https://github.com/TRNSYSJP/TRNSYS.JP '/storage/nvme5/new_clones/Ballerina/TRNSYS.JP' &
git clone https://github.com/PacktPublishing/Practical-Site-Reliability-Engineering '/storage/nvme5/new_clones/Ballerina/Practical-Site-Reliability-Engineering' &
git clone https://github.com/lafernando/samples '/storage/nvme5/new_clones/Ballerina/samples' &
git clone https://github.com/ballerina-attic/messaging-with-kafka '/storage/nvme5/new_clones/Ballerina/messaging-with-kafka' &
git clone https://github.com/ballerina-attic/module-twitter '/storage/nvme5/new_clones/Ballerina/module-twitter' &
git clone https://github.com/ballerina-attic/ballerina-with-istio '/storage/nvme5/new_clones/Ballerina/ballerina-with-istio' &
git clone https://github.com/ballerina-attic/connectors '/storage/nvme5/new_clones/Ballerina/connectors' &
git clone https://github.com/wso2-attic/module-ethereum '/storage/nvme5/new_clones/Ballerina/module-ethereum' &
git clone https://github.com/exercism/ballerina '/storage/nvme5/new_clones/Ballerina/ballerina' &
git clone https://github.com/Apress/beginning-ballerina-programming '/storage/nvme5/new_clones/Ballerina/beginning-ballerina-programming' &
git clone https://github.com/Shan1024/simple-vm '/storage/nvme5/new_clones/Ballerina/simple-vm' &
git clone https://github.com/Kishanthan/SummerSOC-2019 '/storage/nvme5/new_clones/Ballerina/SummerSOC-2019' &
git clone https://github.com/yashodgayashan/environment_platform '/storage/nvme5/new_clones/Ballerina/environment_platform' &
