#!/bin/bash

git clone https://github.com/TheRenegadeCoder/sample-programs '/storage/nvme5/new_clones/BASIC/sample-programs' &
git clone https://github.com/coding-horror/donkey.bas '/storage/nvme5/new_clones/BASIC/donkey.bas' &
git clone https://github.com/tilleul/apple2 '/storage/nvme5/new_clones/BASIC/apple2' &
git clone https://github.com/linker3000/Z80-Board '/storage/nvme5/new_clones/BASIC/Z80-Board' &
git clone https://github.com/robhagemans/hoard-of-gwbasic '/storage/nvme5/new_clones/BASIC/hoard-of-gwbasic' &
git clone https://github.com/HudsonGTV/STILLALI '/storage/nvme5/new_clones/BASIC/STILLALI' &
git clone https://github.com/spiroharvey/c64 '/storage/nvme5/new_clones/BASIC/c64' &
git clone https://github.com/nviennot/reversing-mono4k '/storage/nvme5/new_clones/BASIC/reversing-mono4k' &
git clone https://github.com/guidol70/RunCPM_RPi_Pico '/storage/nvme5/new_clones/BASIC/RunCPM_RPi_Pico' &
git clone https://github.com/clintmoyer/oregon-trail '/storage/nvme5/new_clones/BASIC/oregon-trail' &
git clone https://github.com/FellippeHeitor/InForm '/storage/nvme5/new_clones/BASIC/InForm' &
git clone https://github.com/philspil66/Super-Star-Trek '/storage/nvme5/new_clones/BASIC/Super-Star-Trek' &
git clone https://github.com/jggames/trs80mc10 '/storage/nvme5/new_clones/BASIC/trs80mc10' &
git clone https://github.com/mmcgraw74/Tektronix-4051-4052-4054-Program-Files '/storage/nvme5/new_clones/BASIC/Tektronix-4051-4052-4054-Program-Files' &
git clone https://github.com/DualBrain/gw-basic '/storage/nvme5/new_clones/BASIC/gw-basic' &
git clone https://github.com/mcicolella/awesome-commodore-resources '/storage/nvme5/new_clones/BASIC/awesome-commodore-resources' &
git clone https://github.com/geneb/QuickPak-Pro-DOS '/storage/nvme5/new_clones/BASIC/QuickPak-Pro-DOS' &
git clone https://github.com/agn453/RSTS-E '/storage/nvme5/new_clones/BASIC/RSTS-E' &
git clone https://github.com/GReaperEx/bcg '/storage/nvme5/new_clones/BASIC/bcg' &
git clone https://github.com/fortran-gaming/oregon-trail-1975 '/storage/nvme5/new_clones/BASIC/oregon-trail-1975' &
git clone https://github.com/RC2014Z80/RC2014-BASIC-Programs '/storage/nvme5/new_clones/BASIC/RC2014-BASIC-Programs' &
git clone https://github.com/retro-software/B5500-software '/storage/nvme5/new_clones/BASIC/B5500-software' &
git clone https://github.com/Gagniuc/Binary-files-inside-EXCEL-VBA '/storage/nvme5/new_clones/BASIC/Binary-files-inside-EXCEL-VBA' &
git clone https://github.com/plattysoft/MSX '/storage/nvme5/new_clones/BASIC/MSX' &
git clone https://github.com/philspil66/Hamurabi '/storage/nvme5/new_clones/BASIC/Hamurabi' &
git clone https://github.com/mauroxavierneto/gauntlet_cmm2 '/storage/nvme5/new_clones/BASIC/gauntlet_cmm2' &
git clone https://github.com/jomag/stuga2020 '/storage/nvme5/new_clones/BASIC/stuga2020' &
git clone https://github.com/christianhujer/expensereport-level-2 '/storage/nvme5/new_clones/BASIC/expensereport-level-2' &
git clone https://github.com/Fabrizio-Caruso/CBM-BASIC-10-liners '/storage/nvme5/new_clones/BASIC/CBM-BASIC-10-liners' &
git clone https://github.com/thwill1000/cmm2-welcome '/storage/nvme5/new_clones/BASIC/cmm2-welcome' &
git clone https://github.com/thunderpoot/cliptoe '/storage/nvme5/new_clones/BASIC/cliptoe' &
git clone https://github.com/FellippeHeitor/QB64-interpreter '/storage/nvme5/new_clones/BASIC/QB64-interpreter' &
git clone https://github.com/fortran-gaming/lunar-lander-1969 '/storage/nvme5/new_clones/BASIC/lunar-lander-1969' &
git clone https://github.com/mauroxavierneto/wolf3d_cmm2 '/storage/nvme5/new_clones/BASIC/wolf3d_cmm2' &
git clone https://github.com/dukedougal/wilderness '/storage/nvme5/new_clones/BASIC/wilderness' &
git clone https://github.com/nfban/gigamix-msx '/storage/nvme5/new_clones/BASIC/gigamix-msx' &
git clone https://github.com/ryanwellsr/wellsrPRO '/storage/nvme5/new_clones/BASIC/wellsrPRO' &
git clone https://github.com/clasqm/QBASDOWN '/storage/nvme5/new_clones/BASIC/QBASDOWN' &
git clone https://github.com/hperaza/BASIC-11-Z80 '/storage/nvme5/new_clones/BASIC/BASIC-11-Z80' &
git clone https://github.com/galacticstudios/Trek52 '/storage/nvme5/new_clones/BASIC/Trek52' &
git clone https://github.com/jonatasdemello/gwbasic '/storage/nvme5/new_clones/BASIC/gwbasic' &
git clone https://github.com/bdestombe/python-flopy-parser '/storage/nvme5/new_clones/BASIC/python-flopy-parser' &
git clone https://github.com/foone/DOSPride '/storage/nvme5/new_clones/BASIC/DOSPride' &
git clone https://github.com/chaosotter/basic-games '/storage/nvme5/new_clones/BASIC/basic-games' &
git clone https://github.com/bozimmerman/Zelch128 '/storage/nvme5/new_clones/BASIC/Zelch128' &
git clone https://github.com/Utodev/ZXUC '/storage/nvme5/new_clones/BASIC/ZXUC' &
git clone https://github.com/option8/A2QR '/storage/nvme5/new_clones/BASIC/A2QR' &
git clone https://github.com/exrom/sd2iec-snoop '/storage/nvme5/new_clones/BASIC/sd2iec-snoop' &
git clone https://github.com/syxanash/retrocomputing '/storage/nvme5/new_clones/BASIC/retrocomputing' &
git clone https://github.com/civilware/artificer-nfa-standard '/storage/nvme5/new_clones/BASIC/artificer-nfa-standard' &
git clone https://github.com/mauroxavierneto/final_fight_cmm2 '/storage/nvme5/new_clones/BASIC/final_fight_cmm2' &
git clone https://github.com/deringenieur71/Adventures-in-LOCOMOTIVE-BASIC '/storage/nvme5/new_clones/BASIC/Adventures-in-LOCOMOTIVE-BASIC' &
git clone https://github.com/philspil66/Kevin-Toms-Football-Manager '/storage/nvme5/new_clones/BASIC/Kevin-Toms-Football-Manager' &
git clone https://github.com/wconrad/basic101 '/storage/nvme5/new_clones/BASIC/basic101' &
git clone https://github.com/mauroxavierneto/demox_cmm2 '/storage/nvme5/new_clones/BASIC/demox_cmm2' &
git clone https://github.com/thwill1000/cmm2-zmim '/storage/nvme5/new_clones/BASIC/cmm2-zmim' &
git clone https://github.com/DualBrain/QuickPakPro '/storage/nvme5/new_clones/BASIC/QuickPakPro' &
git clone https://github.com/galacticstudios/BASTREK '/storage/nvme5/new_clones/BASIC/BASTREK' &
git clone https://github.com/FoxCunning/akalabeth128 '/storage/nvme5/new_clones/BASIC/akalabeth128' &
git clone https://github.com/aouwt/PB95-Clone '/storage/nvme5/new_clones/BASIC/PB95-Clone' &
git clone https://github.com/philspil66/StarTrader '/storage/nvme5/new_clones/BASIC/StarTrader' &
git clone https://github.com/psychotimmy/RC2014 '/storage/nvme5/new_clones/BASIC/RC2014' &
git clone https://github.com/catseye/SITU-SOL '/storage/nvme5/new_clones/BASIC/SITU-SOL' &
git clone https://github.com/MODFLOW-USGS/mf2005 '/storage/nvme5/new_clones/BASIC/mf2005' &
git clone https://github.com/The-Young-Programmer/QBasic '/storage/nvme5/new_clones/BASIC/QBasic' &
git clone https://github.com/catseye/DiskSumo '/storage/nvme5/new_clones/BASIC/DiskSumo' &
git clone https://github.com/mauroxavierneto/mstudio_cmm '/storage/nvme5/new_clones/BASIC/mstudio_cmm' &
git clone https://github.com/Robert-van-Engelen/Enigma '/storage/nvme5/new_clones/BASIC/Enigma' &
git clone https://github.com/clasqm/amb-utils '/storage/nvme5/new_clones/BASIC/amb-utils' &
git clone https://github.com/aouwt/suscript '/storage/nvme5/new_clones/BASIC/suscript' &
git clone https://github.com/g45t345rt/DERO-SC-Standards '/storage/nvme5/new_clones/BASIC/DERO-SC-Standards' &
git clone https://github.com/mobluse/chargen-maker '/storage/nvme5/new_clones/BASIC/chargen-maker' &
git clone https://github.com/Sarah-C/ZX_Spectrum-Horizons '/storage/nvme5/new_clones/BASIC/ZX_Spectrum-Horizons' &
git clone https://github.com/Retronissen/Sinclair-ZX81-Software-in-hounor-for-Sir-Clive '/storage/nvme5/new_clones/BASIC/Sinclair-ZX81-Software-in-hounor-for-Sir-Clive' &
git clone https://github.com/MODFLOW-USGS/mfusg '/storage/nvme5/new_clones/BASIC/mfusg' &
git clone https://github.com/pslabs-ps/CMM2-DeluxeEdition-GEN2 '/storage/nvme5/new_clones/BASIC/CMM2-DeluxeEdition-GEN2' &
git clone https://github.com/Peppinux/redplaza-dero-marketplace '/storage/nvme5/new_clones/BASIC/redplaza-dero-marketplace' &
git clone https://github.com/Michaelangel007/apple2_softswitch '/storage/nvme5/new_clones/BASIC/apple2_softswitch' &
git clone https://github.com/EgonOlsen71/uberswap '/storage/nvme5/new_clones/BASIC/uberswap' &
git clone https://github.com/pramnora/qb64 '/storage/nvme5/new_clones/BASIC/qb64' &
git clone https://github.com/loudar/Vedit '/storage/nvme5/new_clones/BASIC/Vedit' &
git clone https://github.com/pkimbrel/kaypro '/storage/nvme5/new_clones/BASIC/kaypro' &
git clone https://github.com/rprouse/Commodore64 '/storage/nvme5/new_clones/BASIC/Commodore64' &
git clone https://github.com/dr-grim/vertigo '/storage/nvme5/new_clones/BASIC/vertigo' &
git clone https://github.com/frankrefischer/STTR '/storage/nvme5/new_clones/BASIC/STTR' &
git clone https://github.com/rodrivas78/MSX '/storage/nvme5/new_clones/BASIC/MSX' &
git clone https://github.com/coreWeaver/RAC-the.Radio.Alarm.Clock '/storage/nvme5/new_clones/BASIC/RAC-the.Radio.Alarm.Clock' &
git clone https://github.com/jensma-de/MM58167-ISA-RTC '/storage/nvme5/new_clones/BASIC/MM58167-ISA-RTC' &
git clone https://github.com/yggdrasilradio/shanghai '/storage/nvme5/new_clones/BASIC/shanghai' &
git clone https://github.com/thwill1000/mmbasic-sptools '/storage/nvme5/new_clones/BASIC/mmbasic-sptools' &
git clone https://github.com/kenmartin-unix/Bwbasic-3.20b '/storage/nvme5/new_clones/BASIC/Bwbasic-3.20b' &
git clone https://github.com/Thraka/xcb-ext '/storage/nvme5/new_clones/BASIC/xcb-ext' &
git clone https://github.com/FellippeHeitor/Snippets '/storage/nvme5/new_clones/BASIC/Snippets' &
git clone https://github.com/ahope1/Beeb-Pirate-Adventure '/storage/nvme5/new_clones/BASIC/Beeb-Pirate-Adventure' &
