#!/bin/bash

git clone https://github.com/Azure/azure-quickstart-templates '/storage/nvme5/new_clones/Bicep/azure-quickstart-templates' &
git clone https://github.com/Azure/bicep '/storage/nvme5/new_clones/Bicep/bicep' &
git clone https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies '/storage/nvme5/new_clones/Bicep/AZ500-AzureSecurityTechnologies' &
git clone https://github.com/mspnp/microservices-reference-implementation '/storage/nvme5/new_clones/Bicep/microservices-reference-implementation' &
git clone https://github.com/Azure/ALZ-Bicep '/storage/nvme5/new_clones/Bicep/ALZ-Bicep' &
git clone https://github.com/mspnp/aks-baseline '/storage/nvme5/new_clones/Bicep/aks-baseline' &
git clone https://github.com/Azure/bicep-registry-modules '/storage/nvme5/new_clones/Bicep/bicep-registry-modules' &
git clone https://github.com/Azure/reliable-web-app-pattern-dotnet '/storage/nvme5/new_clones/Bicep/reliable-web-app-pattern-dotnet' &
git clone https://github.com/microsoft/azure-container-apps '/storage/nvme5/new_clones/Bicep/azure-container-apps' &
git clone https://github.com/Azure/avdaccelerator '/storage/nvme5/new_clones/Bicep/avdaccelerator' &
git clone https://github.com/MicrosoftLearning/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions '/storage/nvme5/new_clones/Bicep/AZ-700-Designing-and-Implementing-Microsoft-Azure-Networking-Solutions' &
git clone https://github.com/microsoft/industry '/storage/nvme5/new_clones/Bicep/industry' &
git clone https://github.com/Azure/missionlz '/storage/nvme5/new_clones/Bicep/missionlz' &
git clone https://github.com/Azure/appservice-landing-zone-accelerator '/storage/nvme5/new_clones/Bicep/appservice-landing-zone-accelerator' &
git clone https://github.com/timothywarner/az104 '/storage/nvme5/new_clones/Bicep/az104' &
git clone https://github.com/Azure/aca-landing-zone-accelerator '/storage/nvme5/new_clones/Bicep/aca-landing-zone-accelerator' &
git clone https://github.com/Azure/azure-synapse-analytics-end2end '/storage/nvme5/new_clones/Bicep/azure-synapse-analytics-end2end' &
git clone https://github.com/Azure/alz-monitor '/storage/nvme5/new_clones/Bicep/alz-monitor' &
git clone https://github.com/Azure/data-management-zone '/storage/nvme5/new_clones/Bicep/data-management-zone' &
git clone https://github.com/Azure/data-landing-zone '/storage/nvme5/new_clones/Bicep/data-landing-zone' &
git clone https://github.com/brwilkinson/AzureDeploymentFramework '/storage/nvme5/new_clones/Bicep/AzureDeploymentFramework' &
git clone https://github.com/nehalineogi/azure-cross-solution-network-architectures '/storage/nvme5/new_clones/Bicep/azure-cross-solution-network-architectures' &
git clone https://github.com/tayganr/purviewlab '/storage/nvme5/new_clones/Bicep/purviewlab' &
git clone https://github.com/dmauser/opnazure '/storage/nvme5/new_clones/Bicep/opnazure' &
git clone https://github.com/mspnp/aks-fabrikam-dronedelivery '/storage/nvme5/new_clones/Bicep/aks-fabrikam-dronedelivery' &
git clone https://github.com/Azure-Samples/azure-opensource-labs '/storage/nvme5/new_clones/Bicep/azure-opensource-labs' &
git clone https://github.com/nicolgit/hub-and-spoke-playground '/storage/nvme5/new_clones/Bicep/hub-and-spoke-playground' &
git clone https://github.com/Azure/reddog-containerapps '/storage/nvme5/new_clones/Bicep/reddog-containerapps' &
git clone https://github.com/Azure/CanadaPubSecALZ '/storage/nvme5/new_clones/Bicep/CanadaPubSecALZ' &
git clone https://github.com/mspnp/samples '/storage/nvme5/new_clones/Bicep/samples' &
git clone https://github.com/Azure/bicep-lz-vending '/storage/nvme5/new_clones/Bicep/bicep-lz-vending' &
git clone https://github.com/Azure/aksArc '/storage/nvme5/new_clones/Bicep/aksArc' &
git clone https://github.com/mspnp/aks-baseline-regulated '/storage/nvme5/new_clones/Bicep/aks-baseline-regulated' &
git clone https://github.com/ProvisionGenie/ProvisionGenie '/storage/nvme5/new_clones/Bicep/ProvisionGenie' &
git clone https://github.com/Azure-Samples/fastapi-on-azure-functions '/storage/nvme5/new_clones/Bicep/fastapi-on-azure-functions' &
git clone https://github.com/Azure-Samples/sftp-creation-template '/storage/nvme5/new_clones/Bicep/sftp-creation-template' &
git clone https://github.com/Azure/deployment-stacks '/storage/nvme5/new_clones/Bicep/deployment-stacks' &
git clone https://github.com/Azure/azure-docs-bicep-samples '/storage/nvme5/new_clones/Bicep/azure-docs-bicep-samples' &
git clone https://github.com/Azure/AnalyticsinaBox '/storage/nvme5/new_clones/Bicep/AnalyticsinaBox' &
git clone https://github.com/Azure/aks-baseline-automation '/storage/nvme5/new_clones/Bicep/aks-baseline-automation' &
git clone https://github.com/Azure/azure-postgresql '/storage/nvme5/new_clones/Bicep/azure-postgresql' &
git clone https://github.com/aaronpowell/azure-remix-stack '/storage/nvme5/new_clones/Bicep/azure-remix-stack' &
git clone https://github.com/Azure/data-product-analytics '/storage/nvme5/new_clones/Bicep/data-product-analytics' &
git clone https://github.com/Azure-Samples/todo-csharp-cosmos-sql '/storage/nvme5/new_clones/Bicep/todo-csharp-cosmos-sql' &
git clone https://github.com/Azure-Samples/azure-cache-redis-samples '/storage/nvme5/new_clones/Bicep/azure-cache-redis-samples' &
git clone https://github.com/madebygps/serverless-resume-api '/storage/nvme5/new_clones/Bicep/serverless-resume-api' &
git clone https://github.com/timothywarner/frankenstein '/storage/nvme5/new_clones/Bicep/frankenstein' &
git clone https://github.com/Azure-Samples/azure-ml-federated-learning '/storage/nvme5/new_clones/Bicep/azure-ml-federated-learning' &
git clone https://github.com/Azure-Samples/todo-csharp-sql '/storage/nvme5/new_clones/Bicep/todo-csharp-sql' &
git clone https://github.com/Azure-Samples/dotNET-FrontEnd-to-BackEnd-on-Azure-Container-Apps '/storage/nvme5/new_clones/Bicep/dotNET-FrontEnd-to-BackEnd-on-Azure-Container-Apps' &
git clone https://github.com/Azure-Samples/msdocs-django-postgresql-sample-app '/storage/nvme5/new_clones/Bicep/msdocs-django-postgresql-sample-app' &
git clone https://github.com/ThorstenHans/azure-container-apps-samples '/storage/nvme5/new_clones/Bicep/azure-container-apps-samples' &
git clone https://github.com/Azure/Integration-Services-Landing-Zone-Accelerator '/storage/nvme5/new_clones/Bicep/Integration-Services-Landing-Zone-Accelerator' &
git clone https://github.com/StefanIvemo/vwan-playground '/storage/nvme5/new_clones/Bicep/vwan-playground' &
git clone https://github.com/tomkerkhove/azure-apim-on-container-apps '/storage/nvme5/new_clones/Bicep/azure-apim-on-container-apps' &
git clone https://github.com/microsoft/azure-health-data-services-workshop '/storage/nvme5/new_clones/Bicep/azure-health-data-services-workshop' &
git clone https://github.com/HoussemDellai/azure-bicep-course '/storage/nvme5/new_clones/Bicep/azure-bicep-course' &
git clone https://github.com/Azure-Samples/todo-python-mongo '/storage/nvme5/new_clones/Bicep/todo-python-mongo' &
git clone https://github.com/PieterbasNagengast/Azure-HubSpoke-LabBuilder '/storage/nvme5/new_clones/Bicep/Azure-HubSpoke-LabBuilder' &
git clone https://github.com/jamesatighe/AVD-BICEP '/storage/nvme5/new_clones/Bicep/AVD-BICEP' &
git clone https://github.com/CloudNativeGBB/webinars '/storage/nvme5/new_clones/Bicep/webinars' &
git clone https://github.com/pamelafox/fastapi-azure-function-apim '/storage/nvme5/new_clones/Bicep/fastapi-azure-function-apim' &
git clone https://github.com/Azure-Samples/msdocs-flask-postgresql-sample-app '/storage/nvme5/new_clones/Bicep/msdocs-flask-postgresql-sample-app' &
git clone https://github.com/Azure/ARO-Landing-Zone-Accelerator '/storage/nvme5/new_clones/Bicep/ARO-Landing-Zone-Accelerator' &
git clone https://github.com/andrewmatveychuk/azure.policy '/storage/nvme5/new_clones/Bicep/azure.policy' &
git clone https://github.com/Azure-Samples/container-apps-connect-multiple-apps '/storage/nvme5/new_clones/Bicep/container-apps-connect-multiple-apps' &
git clone https://github.com/matthiasguentert/azure-naming-convention-initiative '/storage/nvme5/new_clones/Bicep/azure-naming-convention-initiative' &
git clone https://github.com/jeffhollan/container-apps-dotnet-eventing '/storage/nvme5/new_clones/Bicep/container-apps-dotnet-eventing' &
git clone https://github.com/mspnp/container-apps-fabrikam-dronedelivery '/storage/nvme5/new_clones/Bicep/container-apps-fabrikam-dronedelivery' &
git clone https://github.com/Azure-Samples/todo-python-mongo-aca '/storage/nvme5/new_clones/Bicep/todo-python-mongo-aca' &
git clone https://github.com/PacktPublishing/Infrastructure-as-Code-with-Azure-Bicep '/storage/nvme5/new_clones/Bicep/Infrastructure-as-Code-with-Azure-Bicep' &
git clone https://github.com/Azure-Samples/serverless-web-application '/storage/nvme5/new_clones/Bicep/serverless-web-application' &
git clone https://github.com/Azure-Samples/todo-csharp-sql-swa-func '/storage/nvme5/new_clones/Bicep/todo-csharp-sql-swa-func' &
git clone https://github.com/PeterKlapwijk/Microsoft-Logic-Apps '/storage/nvme5/new_clones/Bicep/Microsoft-Logic-Apps' &
git clone https://github.com/Azure-Samples/todo-python-mongo-swa-func '/storage/nvme5/new_clones/Bicep/todo-python-mongo-swa-func' &
git clone https://github.com/Azure/gitops-flux2-kustomize-helm-mt '/storage/nvme5/new_clones/Bicep/gitops-flux2-kustomize-helm-mt' &
git clone https://github.com/ElYusubov/Learn-Bicep '/storage/nvme5/new_clones/Bicep/Learn-Bicep' &
git clone https://github.com/Azure-Samples/aks-workload-identity '/storage/nvme5/new_clones/Bicep/aks-workload-identity' &
git clone https://github.com/Azure/data-product-batch '/storage/nvme5/new_clones/Bicep/data-product-batch' &
git clone https://github.com/Azure-Samples/function-app-arm-templates '/storage/nvme5/new_clones/Bicep/function-app-arm-templates' &
git clone https://github.com/microsoft/OHDSIonAzure '/storage/nvme5/new_clones/Bicep/OHDSIonAzure' &
git clone https://github.com/Azure/data-product-streaming '/storage/nvme5/new_clones/Bicep/data-product-streaming' &
git clone https://github.com/daveRendon/azinsider '/storage/nvme5/new_clones/Bicep/azinsider' &
git clone https://github.com/kartben/thethingsstack-on-azure '/storage/nvme5/new_clones/Bicep/thethingsstack-on-azure' &
git clone https://github.com/Azure/PSRule.Rules.Azure-quickstart '/storage/nvme5/new_clones/Bicep/PSRule.Rules.Azure-quickstart' &
git clone https://github.com/azuredemoenvironment/ade '/storage/nvme5/new_clones/Bicep/ade' &
git clone https://github.com/pamelafox/django-quiz-app '/storage/nvme5/new_clones/Bicep/django-quiz-app' &
git clone https://github.com/francesco-sodano/AZNames-bicep '/storage/nvme5/new_clones/Bicep/AZNames-bicep' &
git clone https://github.com/tyconsulting/BlogPosts '/storage/nvme5/new_clones/Bicep/BlogPosts' &
git clone https://github.com/Azure-Samples/msdocs-nodejs-mongodb-azure-sample-app '/storage/nvme5/new_clones/Bicep/msdocs-nodejs-mongodb-azure-sample-app' &
git clone https://github.com/Azure-Samples/todo-nodejs-mongo '/storage/nvme5/new_clones/Bicep/todo-nodejs-mongo' &
git clone https://github.com/AErmie/DevSecOps '/storage/nvme5/new_clones/Bicep/DevSecOps' &
git clone https://github.com/lordlinus/databricks-all-in-one-bicep-template '/storage/nvme5/new_clones/Bicep/databricks-all-in-one-bicep-template' &
git clone https://github.com/evgenyb/aks-workshops '/storage/nvme5/new_clones/Bicep/aks-workshops' &
git clone https://github.com/microsoft/azure-redcap-paas '/storage/nvme5/new_clones/Bicep/azure-redcap-paas' &
git clone https://github.com/Azure-Samples/pubsub-dapr-csharp-servicebus '/storage/nvme5/new_clones/Bicep/pubsub-dapr-csharp-servicebus' &
git clone https://github.com/Azure/azure-devops-templates-iac '/storage/nvme5/new_clones/Bicep/azure-devops-templates-iac' &
git clone https://github.com/Azure/Hadoop-Migrations '/storage/nvme5/new_clones/Bicep/Hadoop-Migrations' &
git clone https://github.com/Azure/jp-akssecurity '/storage/nvme5/new_clones/Bicep/jp-akssecurity' &
git clone https://github.com/microsoft/Azure-Secure-Enclave-for-Research '/storage/nvme5/new_clones/Bicep/Azure-Secure-Enclave-for-Research' &
git clone https://github.com/shanselman/azure-friday '/storage/nvme5/new_clones/Bicep/azure-friday' &
git clone https://github.com/Azure/maximo '/storage/nvme5/new_clones/Bicep/maximo' &
git clone https://github.com/Azure4DevOps/check-azure-bicep '/storage/nvme5/new_clones/Bicep/check-azure-bicep' &
git clone https://github.com/Azure-Samples/azure-ad-workload-identity '/storage/nvme5/new_clones/Bicep/azure-ad-workload-identity' &
git clone https://github.com/Azure/vm-scale-sets '/storage/nvme5/new_clones/Bicep/vm-scale-sets' &
git clone https://github.com/tayganr/lakehouse '/storage/nvme5/new_clones/Bicep/lakehouse' &
git clone https://github.com/radius-project/docs '/storage/nvme5/new_clones/Bicep/docs' &
git clone https://github.com/dmauser/azure-gateway-lb '/storage/nvme5/new_clones/Bicep/azure-gateway-lb' &
git clone https://github.com/Azure-Samples/dotNET-Frontend-AB-Testing-on-Azure-Container-Apps '/storage/nvme5/new_clones/Bicep/dotNET-Frontend-AB-Testing-on-Azure-Container-Apps' &
git clone https://github.com/Azure/iotedge-vm-deploy '/storage/nvme5/new_clones/Bicep/iotedge-vm-deploy' &
git clone https://github.com/msdirtbag/MDC-Quickstart '/storage/nvme5/new_clones/Bicep/MDC-Quickstart' &
git clone https://github.com/fberson/Slidedecks '/storage/nvme5/new_clones/Bicep/Slidedecks' &
git clone https://github.com/cykreng/Enterprise-Scale-APIM '/storage/nvme5/new_clones/Bicep/Enterprise-Scale-APIM' &
git clone https://github.com/Ba4bes/Bicep-NamingConvention '/storage/nvme5/new_clones/Bicep/Bicep-NamingConvention' &
git clone https://github.com/scautomation/Bicep-AzureMonitor-Sentinel '/storage/nvme5/new_clones/Bicep/Bicep-AzureMonitor-Sentinel' &
git clone https://github.com/shaneochotny/Azure-Synapse-Analytics-PoC '/storage/nvme5/new_clones/Bicep/Azure-Synapse-Analytics-PoC' &
git clone https://github.com/gbaeke/aks-bicep '/storage/nvme5/new_clones/Bicep/aks-bicep' &
git clone https://github.com/Azure-Samples/todo-nodejs-mongo-aca '/storage/nvme5/new_clones/Bicep/todo-nodejs-mongo-aca' &
git clone https://github.com/jaydestro/aksbicep '/storage/nvme5/new_clones/Bicep/aksbicep' &
git clone https://github.com/Azure-Samples/app-service-networking-samples '/storage/nvme5/new_clones/Bicep/app-service-networking-samples' &
git clone https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.es-es '/storage/nvme5/new_clones/Bicep/AZ-104-MicrosoftAzureAdministrator.es-es' &
git clone https://github.com/ravi0130/azure-avs-microhack '/storage/nvme5/new_clones/Bicep/azure-avs-microhack' &
git clone https://github.com/tyconsulting/azure.policy.monitor '/storage/nvme5/new_clones/Bicep/azure.policy.monitor' &
git clone https://github.com/Azure-Samples/virtual-network-integration-recipes '/storage/nvme5/new_clones/Bicep/virtual-network-integration-recipes' &
git clone https://github.com/microsoft/Azure-PDF-Form-Processing-Automation-Solution-Accelerator '/storage/nvme5/new_clones/Bicep/Azure-PDF-Form-Processing-Automation-Solution-Accelerator' &
git clone https://github.com/sebafo/frontdoor-container-apps '/storage/nvme5/new_clones/Bicep/frontdoor-container-apps' &
git clone https://github.com/Azure-Samples/cosmos-aks-samples '/storage/nvme5/new_clones/Bicep/cosmos-aks-samples' &
git clone https://github.com/andrewmatveychuk/azure.ghost-web-app-for-containers '/storage/nvme5/new_clones/Bicep/azure.ghost-web-app-for-containers' &
git clone https://github.com/KaiWalter/container-apps-experimental '/storage/nvme5/new_clones/Bicep/container-apps-experimental' &
git clone https://github.com/rajyraman/PowerApps-Managed-Identity-Demo-Functions '/storage/nvme5/new_clones/Bicep/PowerApps-Managed-Identity-Demo-Functions' &
git clone https://github.com/sam-cogan/lambda-toys-api-infrastructure '/storage/nvme5/new_clones/Bicep/lambda-toys-api-infrastructure' &
git clone https://github.com/graemefoster/QuickStart '/storage/nvme5/new_clones/Bicep/QuickStart' &
git clone https://github.com/AzureIaCBook/book-templates '/storage/nvme5/new_clones/Bicep/book-templates' &
git clone https://github.com/mspnp/interruptible-workload-on-spot '/storage/nvme5/new_clones/Bicep/interruptible-workload-on-spot' &
git clone https://github.com/benc-uk/bicep-iac '/storage/nvme5/new_clones/Bicep/bicep-iac' &
git clone https://github.com/JFolberth/Azure_IaC_Flavors '/storage/nvme5/new_clones/Bicep/Azure_IaC_Flavors' &
git clone https://github.com/pamelafox/translation-telephone '/storage/nvme5/new_clones/Bicep/translation-telephone' &
git clone https://github.com/Azure/fta-networking '/storage/nvme5/new_clones/Bicep/fta-networking' &
git clone https://github.com/mimergel/sap-hana-vm '/storage/nvme5/new_clones/Bicep/sap-hana-vm' &
git clone https://github.com/Gordonby/servicebus-dotnet-functionapp '/storage/nvme5/new_clones/Bicep/servicebus-dotnet-functionapp' &
git clone https://github.com/zlatko-ms/az-capps-private '/storage/nvme5/new_clones/Bicep/az-capps-private' &
git clone https://github.com/ChristopherGLewis/vNet-Bicep '/storage/nvme5/new_clones/Bicep/vNet-Bicep' &
git clone https://github.com/vakappas/private-aks-bicep '/storage/nvme5/new_clones/Bicep/private-aks-bicep' &
git clone https://github.com/ehrnst/azure-infrastructure-as-code-series '/storage/nvme5/new_clones/Bicep/azure-infrastructure-as-code-series' &
git clone https://github.com/erudinsky/Azure-Bicep-Workshop '/storage/nvme5/new_clones/Bicep/Azure-Bicep-Workshop' &
git clone https://github.com/pauldotyu/azure-virtual-desktop-bicep '/storage/nvme5/new_clones/Bicep/azure-virtual-desktop-bicep' &
git clone https://github.com/Azure-Samples/containerapps-dapralbums '/storage/nvme5/new_clones/Bicep/containerapps-dapralbums' &
git clone https://github.com/stevedem/FormRecognizerAccelerator '/storage/nvme5/new_clones/Bicep/FormRecognizerAccelerator' &
git clone https://github.com/microsoft/powerplatform-dev-day '/storage/nvme5/new_clones/Bicep/powerplatform-dev-day' &
git clone https://github.com/Azure/mock-spacestation '/storage/nvme5/new_clones/Bicep/mock-spacestation' &
git clone https://github.com/Azure-Samples/todo-nodejs-mongo-swa-func '/storage/nvme5/new_clones/Bicep/todo-nodejs-mongo-swa-func' &
git clone https://github.com/Azure-Samples/selenium-grid-aks-keda '/storage/nvme5/new_clones/Bicep/selenium-grid-aks-keda' &
git clone https://github.com/codemillmatt/dotnetconfpizza '/storage/nvme5/new_clones/Bicep/dotnetconfpizza' &
git clone https://github.com/Azure/missionlz-edge '/storage/nvme5/new_clones/Bicep/missionlz-edge' &
git clone https://github.com/Azure/employee-retention-databricks-kubernetes-poc '/storage/nvme5/new_clones/Bicep/employee-retention-databricks-kubernetes-poc' &
git clone https://github.com/PacktPublishing/Azure-Architecture-Explained '/storage/nvme5/new_clones/Bicep/Azure-Architecture-Explained' &
git clone https://github.com/willvelida/azure-samples '/storage/nvme5/new_clones/Bicep/azure-samples' &
git clone https://github.com/Azure/APIManagement-Authorizations '/storage/nvme5/new_clones/Bicep/APIManagement-Authorizations' &
git clone https://github.com/matsest/az-bicep-roleassignment-multi-scope '/storage/nvme5/new_clones/Bicep/az-bicep-roleassignment-multi-scope' &
git clone https://github.com/Azure-Samples/bicep-github-actions '/storage/nvme5/new_clones/Bicep/bicep-github-actions' &
git clone https://github.com/Azure-Samples/app-templates-integration-services '/storage/nvme5/new_clones/Bicep/app-templates-integration-services' &
git clone https://github.com/matsest/bicep-registry-demo '/storage/nvme5/new_clones/Bicep/bicep-registry-demo' &
git clone https://github.com/Azure-Samples/github-runner-on-aks '/storage/nvme5/new_clones/Bicep/github-runner-on-aks' &
git clone https://github.com/aidanfinn/SharedAzureFirewall '/storage/nvme5/new_clones/Bicep/SharedAzureFirewall' &
git clone https://github.com/Azure-Samples/azure-private-link-service '/storage/nvme5/new_clones/Bicep/azure-private-link-service' &
git clone https://github.com/KietNhiTran/appmodernized-with-appservice-well-architected-accelerator '/storage/nvme5/new_clones/Bicep/appmodernized-with-appservice-well-architected-accelerator' &
git clone https://github.com/mattias-fjellstrom/azure-bicep-upload-data-to-storage '/storage/nvme5/new_clones/Bicep/azure-bicep-upload-data-to-storage' &
git clone https://github.com/mddazure/azure-route-server-lab '/storage/nvme5/new_clones/Bicep/azure-route-server-lab' &
git clone https://github.com/your-azure-coach/ftw-ventures '/storage/nvme5/new_clones/Bicep/ftw-ventures' &
git clone https://github.com/Azure-Samples/azure-data-factory-runtime-app-service '/storage/nvme5/new_clones/Bicep/azure-data-factory-runtime-app-service' &
git clone https://github.com/cwe1ss/microservices-template '/storage/nvme5/new_clones/Bicep/microservices-template' &
git clone https://github.com/nianton/bicep-starter '/storage/nvme5/new_clones/Bicep/bicep-starter' &
git clone https://github.com/mspnp/app-service-environments-ILB-deployments '/storage/nvme5/new_clones/Bicep/app-service-environments-ILB-deployments' &
git clone https://github.com/Azure-Samples/serverless-webapp-kotlin '/storage/nvme5/new_clones/Bicep/serverless-webapp-kotlin' &
git clone https://github.com/weeyin83/Presentations '/storage/nvme5/new_clones/Bicep/Presentations' &
git clone https://github.com/Azure/Azure-Orbital-STAC '/storage/nvme5/new_clones/Bicep/Azure-Orbital-STAC' &
git clone https://github.com/whiteducksoftware/azure-meetup-rosenheim '/storage/nvme5/new_clones/Bicep/azure-meetup-rosenheim' &
git clone https://github.com/Azure/CAE-Bits '/storage/nvme5/new_clones/Bicep/CAE-Bits' &
git clone https://github.com/fberson/Azure-Virtual-Desktop-as-a-gaming-console '/storage/nvme5/new_clones/Bicep/Azure-Virtual-Desktop-as-a-gaming-console' &
git clone https://github.com/Azure/IoTTrainingPack '/storage/nvme5/new_clones/Bicep/IoTTrainingPack' &
git clone https://github.com/Azure/AzLoadBalancerMigration '/storage/nvme5/new_clones/Bicep/AzLoadBalancerMigration' &
git clone https://github.com/microsoft/unreal-cloud-ddc-on-azure '/storage/nvme5/new_clones/Bicep/unreal-cloud-ddc-on-azure' &
git clone https://github.com/paolosalvatori/azure-private-link-service '/storage/nvme5/new_clones/Bicep/azure-private-link-service' &
git clone https://github.com/Azure-Samples/pubsub-dapr-python-servicebus '/storage/nvme5/new_clones/Bicep/pubsub-dapr-python-servicebus' &
git clone https://github.com/AxisCommunications/acap-integration-examples-azure '/storage/nvme5/new_clones/Bicep/acap-integration-examples-azure' &
git clone https://github.com/Azure-Samples/pubsub-dapr-nodejs-servicebus '/storage/nvme5/new_clones/Bicep/pubsub-dapr-nodejs-servicebus' &
git clone https://github.com/Hardstl/PrivateEndpoint '/storage/nvme5/new_clones/Bicep/PrivateEndpoint' &
git clone https://github.com/MassimoC/bicep-appgw-apim '/storage/nvme5/new_clones/Bicep/bicep-appgw-apim' &
git clone https://github.com/georgekosmidis/AzureFunction-CosmosDB-RBAC '/storage/nvme5/new_clones/Bicep/AzureFunction-CosmosDB-RBAC' &
git clone https://github.com/mikepfeiffer/azure-iac-bootcamp '/storage/nvme5/new_clones/Bicep/azure-iac-bootcamp' &
git clone https://github.com/Azure/hardened-webapp '/storage/nvme5/new_clones/Bicep/hardened-webapp' &
git clone https://github.com/vsuopys/SecureSynapse '/storage/nvme5/new_clones/Bicep/SecureSynapse' &
git clone https://github.com/MicrosoftLearning/AZ500-AzureSecurityTechnologies.es-es '/storage/nvme5/new_clones/Bicep/AZ500-AzureSecurityTechnologies.es-es' &
git clone https://github.com/kevball2/bicepadvanceddeployments '/storage/nvme5/new_clones/Bicep/bicepadvanceddeployments' &
git clone https://github.com/Welasco/Bicep '/storage/nvme5/new_clones/Bicep/Bicep' &
git clone https://github.com/mspnp/aks-jumpbox-imagebuilder '/storage/nvme5/new_clones/Bicep/aks-jumpbox-imagebuilder' &
git clone https://github.com/Azure-Samples/azure-ad-workload-identity-mi '/storage/nvme5/new_clones/Bicep/azure-ad-workload-identity-mi' &
git clone https://github.com/Jcardif/SerengetiDataLab '/storage/nvme5/new_clones/Bicep/SerengetiDataLab' &
git clone https://github.com/JCoreMS/AVDAlerts '/storage/nvme5/new_clones/Bicep/AVDAlerts' &
git clone https://github.com/paolosalvatori/azure-ad-workload-identity '/storage/nvme5/new_clones/Bicep/azure-ad-workload-identity' &
git clone https://github.com/metlo-labs/metlo-deploy '/storage/nvme5/new_clones/Bicep/metlo-deploy' &
git clone https://github.com/EirikHaughom/ADME '/storage/nvme5/new_clones/Bicep/ADME' &
git clone https://github.com/Cheranga/Demo.Bicep.Azure.Functions '/storage/nvme5/new_clones/Bicep/Demo.Bicep.Azure.Functions' &
git clone https://github.com/poomnupong/azure-networking '/storage/nvme5/new_clones/Bicep/azure-networking' &
git clone https://github.com/AgicCloud/Demo.Aks.Performance '/storage/nvme5/new_clones/Bicep/Demo.Aks.Performance' &
git clone https://github.com/cykreng/Enterprise-Scale-AppService '/storage/nvme5/new_clones/Bicep/Enterprise-Scale-AppService' &
git clone https://github.com/MicrosoftDocs/mslearn-manage-multiple-environments-using-bicep-github-actions '/storage/nvme5/new_clones/Bicep/mslearn-manage-multiple-environments-using-bicep-github-actions' &
git clone https://github.com/Azure-Samples/aks-api-server-vnet-integration-bicep '/storage/nvme5/new_clones/Bicep/aks-api-server-vnet-integration-bicep' &
git clone https://github.com/devkimchi/ASWA-AutoPilot-Sample '/storage/nvme5/new_clones/Bicep/ASWA-AutoPilot-Sample' &
git clone https://github.com/savannahostrowski/jupyter-mercury-aca '/storage/nvme5/new_clones/Bicep/jupyter-mercury-aca' &
git clone https://github.com/evgenyb/iac-workshops '/storage/nvme5/new_clones/Bicep/iac-workshops' &
git clone https://github.com/denniszielke/serverless-job-engine '/storage/nvme5/new_clones/Bicep/serverless-job-engine' &
git clone https://github.com/bridgecrewio/bicepgoat '/storage/nvme5/new_clones/Bicep/bicepgoat' &
git clone https://github.com/william-liebenberg/BicepFlex '/storage/nvme5/new_clones/Bicep/BicepFlex' &
git clone https://github.com/DaFitRobsta/ARM-Templates '/storage/nvme5/new_clones/Bicep/ARM-Templates' &
git clone https://github.com/AzureCloudWorkshops/ACW-ServerlessArchitecture '/storage/nvme5/new_clones/Bicep/ACW-ServerlessArchitecture' &
git clone https://github.com/appdevgbb/multiregion-aks '/storage/nvme5/new_clones/Bicep/multiregion-aks' &
git clone https://github.com/davidsntg/azure-quotas-monitoring-logicapp '/storage/nvme5/new_clones/Bicep/azure-quotas-monitoring-logicapp' &
git clone https://github.com/cmaneu/meilisearch-on-azure '/storage/nvme5/new_clones/Bicep/meilisearch-on-azure' &
git clone https://github.com/maikvandergaag/bicep '/storage/nvme5/new_clones/Bicep/bicep' &
git clone https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ko-kr '/storage/nvme5/new_clones/Bicep/AZ-104-MicrosoftAzureAdministrator.ko-kr' &
git clone https://github.com/alexandreweiss/gbb-emea-lab '/storage/nvme5/new_clones/Bicep/gbb-emea-lab' &
git clone https://github.com/nianton/azstorage-to-s3 '/storage/nvme5/new_clones/Bicep/azstorage-to-s3' &
git clone https://github.com/Azure-Samples/Tutorial-Deploy-Dapr-Microservices-ACA '/storage/nvme5/new_clones/Bicep/Tutorial-Deploy-Dapr-Microservices-ACA' &
git clone https://github.com/Azure-Samples/todo-java-mongo-aca '/storage/nvme5/new_clones/Bicep/todo-java-mongo-aca' &
git clone https://github.com/sinedied/azure-checkin '/storage/nvme5/new_clones/Bicep/azure-checkin' &
git clone https://github.com/weeyin83/Lab-Deployment-in-Azure '/storage/nvme5/new_clones/Bicep/Lab-Deployment-in-Azure' &
git clone https://github.com/garaio/AzureRecipes '/storage/nvme5/new_clones/Bicep/AzureRecipes' &
git clone https://github.com/antsok/ado-aca '/storage/nvme5/new_clones/Bicep/ado-aca' &
git clone https://github.com/johnlokerse/bicep-snippets '/storage/nvme5/new_clones/Bicep/bicep-snippets' &
git clone https://github.com/matt-FFFFFF/terraform-azuredevops-vmss-agent '/storage/nvme5/new_clones/Bicep/terraform-azuredevops-vmss-agent' &
git clone https://github.com/gbaeke/intro-bicep '/storage/nvme5/new_clones/Bicep/intro-bicep' &
git clone https://github.com/mddazure/dns-resolver-lab '/storage/nvme5/new_clones/Bicep/dns-resolver-lab' &
git clone https://github.com/Ba4bes/AzDo-Bicep '/storage/nvme5/new_clones/Bicep/AzDo-Bicep' &
git clone https://github.com/jamiemccrindle/bicep-app-service-container '/storage/nvme5/new_clones/Bicep/bicep-app-service-container' &
git clone https://github.com/cthoenes/azure-coredns-forwarder-sample '/storage/nvme5/new_clones/Bicep/azure-coredns-forwarder-sample' &
git clone https://github.com/davidsntg/lab-azuremigrate-hyperv-nestedvirtualization '/storage/nvme5/new_clones/Bicep/lab-azuremigrate-hyperv-nestedvirtualization' &
git clone https://github.com/jordanbean-msft/durable-func-aks-keda '/storage/nvme5/new_clones/Bicep/durable-func-aks-keda' &
git clone https://github.com/Azure-Samples/highly-available-zone-redundant-webapp '/storage/nvme5/new_clones/Bicep/highly-available-zone-redundant-webapp' &
git clone https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator.ja-jp '/storage/nvme5/new_clones/Bicep/AZ-104-MicrosoftAzureAdministrator.ja-jp' &
git clone https://github.com/huangyingting/glb-demo '/storage/nvme5/new_clones/Bicep/glb-demo' &
git clone https://github.com/JanneMattila/bicep-demos '/storage/nvme5/new_clones/Bicep/bicep-demos' &
git clone https://github.com/weslbo/dp-500 '/storage/nvme5/new_clones/Bicep/dp-500' &
git clone https://github.com/Azure-Samples/aks-ephemeral-os-disk '/storage/nvme5/new_clones/Bicep/aks-ephemeral-os-disk' &
git clone https://github.com/brwilkinson/BicepDemo '/storage/nvme5/new_clones/Bicep/BicepDemo' &
git clone https://github.com/skastberg/Integrate-2022 '/storage/nvme5/new_clones/Bicep/Integrate-2022' &
git clone https://github.com/tomwechsler/Azure_Bicep '/storage/nvme5/new_clones/Bicep/Azure_Bicep' &
git clone https://github.com/scottsauber/database-devops '/storage/nvme5/new_clones/Bicep/database-devops' &
git clone https://github.com/pamelafox/flask-db-quiz-example '/storage/nvme5/new_clones/Bicep/flask-db-quiz-example' &
git clone https://github.com/JanneMattila/azure-firewall-demo '/storage/nvme5/new_clones/Bicep/azure-firewall-demo' &
git clone https://github.com/therealjohn/TeamsToolkit-GitHubNotifications-Sample '/storage/nvme5/new_clones/Bicep/TeamsToolkit-GitHubNotifications-Sample' &
git clone https://github.com/mocelj/AzureBatch-Secured '/storage/nvme5/new_clones/Bicep/AzureBatch-Secured' &
git clone https://github.com/ahelland/Bicep-Landing-Zones '/storage/nvme5/new_clones/Bicep/Bicep-Landing-Zones' &
git clone https://github.com/pascalvanderheiden/ais-apim-copilot '/storage/nvme5/new_clones/Bicep/ais-apim-copilot' &
git clone https://github.com/pascalvanderheiden/ais-sync-pattern-la-std-vnet '/storage/nvme5/new_clones/Bicep/ais-sync-pattern-la-std-vnet' &
git clone https://github.com/devkimchi/APIM-OpenAPI-Sample '/storage/nvme5/new_clones/Bicep/APIM-OpenAPI-Sample' &
git clone https://github.com/rick-roche/azure-static-web-apps-sso '/storage/nvme5/new_clones/Bicep/azure-static-web-apps-sso' &
git clone https://github.com/TechSckoolByVijay/GitHubActions '/storage/nvme5/new_clones/Bicep/GitHubActions' &
git clone https://github.com/george-markou/Azure-Hyper-V-Lab '/storage/nvme5/new_clones/Bicep/Azure-Hyper-V-Lab' &
git clone https://github.com/radius-project/bicep '/storage/nvme5/new_clones/Bicep/bicep' &
git clone https://github.com/pamelafox/simple-flask-server-example '/storage/nvme5/new_clones/Bicep/simple-flask-server-example' &
git clone https://github.com/davmhelm/pafw-azvpngw-full-mesh-bgp '/storage/nvme5/new_clones/Bicep/pafw-azvpngw-full-mesh-bgp' &
git clone https://github.com/invictus-integration/docs-ifa '/storage/nvme5/new_clones/Bicep/docs-ifa' &
git clone https://github.com/azure-modern-apps/enterprise-integration-starter '/storage/nvme5/new_clones/Bicep/enterprise-integration-starter' &
git clone https://github.com/azureholic/aca-networking '/storage/nvme5/new_clones/Bicep/aca-networking' &
git clone https://github.com/tyconsulting/bicep.psrule.demo '/storage/nvme5/new_clones/Bicep/bicep.psrule.demo' &
git clone https://github.com/fsaleemm/Multi-Tenant-WebAPI '/storage/nvme5/new_clones/Bicep/Multi-Tenant-WebAPI' &
git clone https://github.com/Azure/CommercialConfidentialCompute '/storage/nvme5/new_clones/Bicep/CommercialConfidentialCompute' &
git clone https://github.com/microsoft/Dynamics365-Sensor-Data-Intelligence-ARMDeployments '/storage/nvme5/new_clones/Bicep/Dynamics365-Sensor-Data-Intelligence-ARMDeployments' &
git clone https://github.com/paulyuk/functions '/storage/nvme5/new_clones/Bicep/functions' &
git clone https://github.com/microsoftgraph/group-membership-management-tenant '/storage/nvme5/new_clones/Bicep/group-membership-management-tenant' &
git clone https://github.com/mattallford/globomantics-arm-learning '/storage/nvme5/new_clones/Bicep/globomantics-arm-learning' &
git clone https://github.com/skmkzyk/bicep-templates '/storage/nvme5/new_clones/Bicep/bicep-templates' &
