#!/bin/bash

git clone https://github.com/openbmc/openbmc '/storage/nvme5/new_clones/BitBake/openbmc' &
git clone https://github.com/balena-os/meta-balena '/storage/nvme5/new_clones/BitBake/meta-balena' &
git clone https://github.com/OE4T/meta-tegra '/storage/nvme5/new_clones/BitBake/meta-tegra' &
git clone https://github.com/openembedded/meta-openembedded '/storage/nvme5/new_clones/BitBake/meta-openembedded' &
git clone https://github.com/ros/meta-ros '/storage/nvme5/new_clones/BitBake/meta-ros' &
git clone https://github.com/openembedded/openembedded-core '/storage/nvme5/new_clones/BitBake/openembedded-core' &
git clone https://github.com/riscv/meta-riscv '/storage/nvme5/new_clones/BitBake/meta-riscv' &
git clone https://github.com/sifive/freedom-u-sdk '/storage/nvme5/new_clones/BitBake/freedom-u-sdk' &
git clone https://github.com/meta-qt5/meta-qt5 '/storage/nvme5/new_clones/BitBake/meta-qt5' &
git clone https://github.com/audeering/opensmile-python '/storage/nvme5/new_clones/BitBake/opensmile-python' &
git clone https://github.com/Aodrulez/blueTag '/storage/nvme5/new_clones/BitBake/blueTag' &
git clone https://github.com/meta-rust/meta-rust '/storage/nvme5/new_clones/BitBake/meta-rust' &
git clone https://github.com/jumpnow/meta-rpi '/storage/nvme5/new_clones/BitBake/meta-rpi' &
git clone https://github.com/YoeDistro/yoe-distro '/storage/nvme5/new_clones/BitBake/yoe-distro' &
git clone https://github.com/balena-os/balena-raspberrypi '/storage/nvme5/new_clones/BitBake/balena-raspberrypi' &
git clone https://github.com/OSSystems/meta-browser '/storage/nvme5/new_clones/BitBake/meta-browser' &
git clone https://github.com/Freescale/meta-freescale '/storage/nvme5/new_clones/BitBake/meta-freescale' &
git clone https://github.com/rauc/meta-rauc '/storage/nvme5/new_clones/BitBake/meta-rauc' &
git clone https://github.com/mendersoftware/meta-mender '/storage/nvme5/new_clones/BitBake/meta-mender' &
git clone https://github.com/kraj/meta-clang '/storage/nvme5/new_clones/BitBake/meta-clang' &
git clone https://github.com/sbabic/meta-swupdate '/storage/nvme5/new_clones/BitBake/meta-swupdate' &
git clone https://github.com/Xilinx/meta-xilinx '/storage/nvme5/new_clones/BitBake/meta-xilinx' &
git clone https://github.com/meta-flutter/meta-flutter '/storage/nvme5/new_clones/BitBake/meta-flutter' &
git clone https://github.com/OSSystems/meta-gstreamer1.0 '/storage/nvme5/new_clones/BitBake/meta-gstreamer1.0' &
git clone https://github.com/meta-debian/meta-debian '/storage/nvme5/new_clones/BitBake/meta-debian' &
git clone https://github.com/xer0times/BugBounty '/storage/nvme5/new_clones/BitBake/BugBounty' &
git clone https://github.com/SummerSec/BurpBountyProfiles '/storage/nvme5/new_clones/BitBake/BurpBountyProfiles' &
git clone https://github.com/STMicroelectronics/meta-st-stm32mp '/storage/nvme5/new_clones/BitBake/meta-st-stm32mp' &
git clone https://github.com/Freescale/meta-fsl-arm '/storage/nvme5/new_clones/BitBake/meta-fsl-arm' &
git clone https://github.com/Igalia/meta-webkit '/storage/nvme5/new_clones/BitBake/meta-webkit' &
git clone https://github.com/Intel-BMC/openbmc '/storage/nvme5/new_clones/BitBake/openbmc' &
git clone https://github.com/heneault/yocto-pitrezor '/storage/nvme5/new_clones/BitBake/yocto-pitrezor' &
git clone https://github.com/rust-embedded/meta-rust-bin '/storage/nvme5/new_clones/BitBake/meta-rust-bin' &
git clone https://github.com/kraj/meta-openwrt '/storage/nvme5/new_clones/BitBake/meta-openwrt' &
git clone https://github.com/superna9999/meta-meson '/storage/nvme5/new_clones/BitBake/meta-meson' &
git clone https://github.com/priv-kweihmann/meta-sca '/storage/nvme5/new_clones/BitBake/meta-sca' &
git clone https://github.com/sony/meta-flutter '/storage/nvme5/new_clones/BitBake/meta-flutter' &
git clone https://github.com/Freescale/meta-freescale-3rdparty '/storage/nvme5/new_clones/BitBake/meta-freescale-3rdparty' &
git clone https://github.com/linux4sam/meta-atmel '/storage/nvme5/new_clones/BitBake/meta-atmel' &
git clone https://github.com/Xilinx/meta-petalinux '/storage/nvme5/new_clones/BitBake/meta-petalinux' &
git clone https://github.com/jiazhang0/meta-secure-core '/storage/nvme5/new_clones/BitBake/meta-secure-core' &
git clone https://github.com/WebPlatformForEmbedded/meta-wpe '/storage/nvme5/new_clones/BitBake/meta-wpe' &
git clone https://github.com/qualcomm-linux/meta-qcom '/storage/nvme5/new_clones/BitBake/meta-qcom' &
git clone https://github.com/nxp-imx/meta-imx '/storage/nvme5/new_clones/BitBake/meta-imx' &
git clone https://github.com/intel-iot-devkit/meta-iot-cloud '/storage/nvme5/new_clones/BitBake/meta-iot-cloud' &
git clone https://github.com/Freescale/meta-freescale-distro '/storage/nvme5/new_clones/BitBake/meta-freescale-distro' &
git clone https://github.com/edison-fw/meta-intel-edison '/storage/nvme5/new_clones/BitBake/meta-intel-edison' &
git clone https://github.com/mendersoftware/meta-mender-community '/storage/nvme5/new_clones/BitBake/meta-mender-community' &
git clone https://github.com/rauc/meta-rauc-community '/storage/nvme5/new_clones/BitBake/meta-rauc-community' &
git clone https://github.com/renesas-rcar/meta-renesas '/storage/nvme5/new_clones/BitBake/meta-renesas' &
git clone https://github.com/sbabic/meta-swupdate-boards '/storage/nvme5/new_clones/BitBake/meta-swupdate-boards' &
git clone https://github.com/Azure/meta-iotedge '/storage/nvme5/new_clones/BitBake/meta-iotedge' &
git clone https://github.com/Xilinx/meta-xilinx-tools '/storage/nvme5/new_clones/BitBake/meta-xilinx-tools' &
git clone https://github.com/PacktPublishing/Embedded-Linux-Development-Using-Yocto-Project-Cookbook-Second-Edition '/storage/nvme5/new_clones/BitBake/Embedded-Linux-Development-Using-Yocto-Project-Cookbook-Second-Edition' &
git clone https://github.com/meta-erlang/meta-erlang '/storage/nvme5/new_clones/BitBake/meta-erlang' &
git clone https://github.com/digi-embedded/meta-digi '/storage/nvme5/new_clones/BitBake/meta-digi' &
git clone https://github.com/sifive/meta-sifive '/storage/nvme5/new_clones/BitBake/meta-sifive' &
git clone https://github.com/OpenAMP/meta-openamp '/storage/nvme5/new_clones/BitBake/meta-openamp' &
git clone https://github.com/polarfire-soc/meta-polarfire-soc-yocto-bsp '/storage/nvme5/new_clones/BitBake/meta-polarfire-soc-yocto-bsp' &
git clone https://github.com/FrankBau/meta-marsboard-bsp '/storage/nvme5/new_clones/BitBake/meta-marsboard-bsp' &
git clone https://github.com/balister/meta-sdr '/storage/nvme5/new_clones/BitBake/meta-sdr' &
git clone https://github.com/Angstrom-distribution/meta-angstrom '/storage/nvme5/new_clones/BitBake/meta-angstrom' &
git clone https://github.com/Kaiserreich/Kaiserreich-DH '/storage/nvme5/new_clones/BitBake/Kaiserreich-DH' &
git clone https://github.com/webosbrew/meta-lg-webos-ndk '/storage/nvme5/new_clones/BitBake/meta-lg-webos-ndk' &
git clone https://github.com/balena-os/balena-jetson '/storage/nvme5/new_clones/BitBake/balena-jetson' &
git clone https://github.com/jwinarske/meta-flutter '/storage/nvme5/new_clones/BitBake/meta-flutter' &
git clone https://github.com/foundriesio/meta-lmp '/storage/nvme5/new_clones/BitBake/meta-lmp' &
git clone https://github.com/mirzak/meta-coral '/storage/nvme5/new_clones/BitBake/meta-coral' &
git clone https://github.com/meta-homeassistant/meta-homeassistant '/storage/nvme5/new_clones/BitBake/meta-homeassistant' &
git clone https://github.com/96boards/meta-96boards '/storage/nvme5/new_clones/BitBake/meta-96boards' &
git clone https://github.com/Halolo/orange-pi-distro '/storage/nvme5/new_clones/BitBake/orange-pi-distro' &
git clone https://github.com/alzahraaelsallakh/Infotainment-System-Yocto '/storage/nvme5/new_clones/BitBake/Infotainment-System-Yocto' &
git clone https://github.com/analogdevicesinc/meta-adi '/storage/nvme5/new_clones/BitBake/meta-adi' &
git clone https://github.com/nxp-imx/meta-nxp-connectivity '/storage/nvme5/new_clones/BitBake/meta-nxp-connectivity' &
git clone https://github.com/NobuoTsukamoto/meta-tensorflow-lite '/storage/nvme5/new_clones/BitBake/meta-tensorflow-lite' &
git clone https://github.com/spietika/meta-rpi-bt-dac '/storage/nvme5/new_clones/BitBake/meta-rpi-bt-dac' &
git clone https://github.com/RDunkley/meta-dotnet-core '/storage/nvme5/new_clones/BitBake/meta-dotnet-core' &
git clone https://github.com/TimesysGit/meta-timesys '/storage/nvme5/new_clones/BitBake/meta-timesys' &
git clone https://github.com/IntelRealSense/meta-intel-realsense '/storage/nvme5/new_clones/BitBake/meta-intel-realsense' &
git clone https://github.com/balena-os/balena-intel '/storage/nvme5/new_clones/BitBake/balena-intel' &
git clone https://github.com/Quectel-Community/meta-quectel-community '/storage/nvme5/new_clones/BitBake/meta-quectel-community' &
git clone https://github.com/EttusResearch/meta-ettus '/storage/nvme5/new_clones/BitBake/meta-ettus' &
git clone https://github.com/graugans/meta-udoo '/storage/nvme5/new_clones/BitBake/meta-udoo' &
git clone https://github.com/schnitzeltony/meta-qt5-extra '/storage/nvme5/new_clones/BitBake/meta-qt5-extra' &
git clone https://github.com/ahcbb6/meta-freertos '/storage/nvme5/new_clones/BitBake/meta-freertos' &
git clone https://github.com/AsteroidOS/meta-smartwatch '/storage/nvme5/new_clones/BitBake/meta-smartwatch' &
git clone https://github.com/dev-0x7C6/meta-retro '/storage/nvme5/new_clones/BitBake/meta-retro' &
git clone https://github.com/conan-io/meta-conan '/storage/nvme5/new_clones/BitBake/meta-conan' &
git clone https://github.com/victronenergy/meta-victronenergy '/storage/nvme5/new_clones/BitBake/meta-victronenergy' &
git clone https://github.com/jumpnow/meta-rpi64 '/storage/nvme5/new_clones/BitBake/meta-rpi64' &
git clone https://github.com/Wind-River/meta-secure-core '/storage/nvme5/new_clones/BitBake/meta-secure-core' &
git clone https://github.com/ibm-openbmc/openbmc '/storage/nvme5/new_clones/BitBake/openbmc' &
git clone https://github.com/savoirfairelinux/meta-embedded-containers '/storage/nvme5/new_clones/BitBake/meta-embedded-containers' &
git clone https://github.com/intel/ref-os-iot '/storage/nvme5/new_clones/BitBake/ref-os-iot' &
git clone https://github.com/alistair23/meta-pine64 '/storage/nvme5/new_clones/BitBake/meta-pine64' &
git clone https://github.com/opendreambox/opendreambox '/storage/nvme5/new_clones/BitBake/opendreambox' &
git clone https://github.com/renesas-rz/meta-renesas '/storage/nvme5/new_clones/BitBake/meta-renesas' &
git clone https://github.com/morphis/meta-snappy '/storage/nvme5/new_clones/BitBake/meta-snappy' &
git clone https://github.com/toradex/meta-toradex-torizon '/storage/nvme5/new_clones/BitBake/meta-toradex-torizon' &
git clone https://github.com/AMDESE/OpenBMC '/storage/nvme5/new_clones/BitBake/OpenBMC' &
git clone https://github.com/balena-os/balena-beaglebone '/storage/nvme5/new_clones/BitBake/balena-beaglebone' &
git clone https://github.com/robseb/meta-intelfpga '/storage/nvme5/new_clones/BitBake/meta-intelfpga' &
git clone https://github.com/balena-os/balena-allwinner '/storage/nvme5/new_clones/BitBake/balena-allwinner' &
git clone https://github.com/flihp/meta-measured '/storage/nvme5/new_clones/BitBake/meta-measured' &
git clone https://github.com/nathanrossi/meta-parallella '/storage/nvme5/new_clones/BitBake/meta-parallella' &
git clone https://github.com/nnstreamer/meta-neural-network '/storage/nvme5/new_clones/BitBake/meta-neural-network' &
git clone https://github.com/phytec/meta-phytec '/storage/nvme5/new_clones/BitBake/meta-phytec' &
git clone https://github.com/joelguittet/meta-chip '/storage/nvme5/new_clones/BitBake/meta-chip' &
git clone https://github.com/voloviq/meta-licheepizero '/storage/nvme5/new_clones/BitBake/meta-licheepizero' &
git clone https://github.com/compulab-yokneam/meta-bsp-imx8mm '/storage/nvme5/new_clones/BitBake/meta-bsp-imx8mm' &
git clone https://github.com/aws4embeddedlinux/meta-aws-demos '/storage/nvme5/new_clones/BitBake/meta-aws-demos' &
git clone https://github.com/E2OpenPlugins/e2openplugins '/storage/nvme5/new_clones/BitBake/e2openplugins' &
git clone https://github.com/jonmason/meta-arm '/storage/nvme5/new_clones/BitBake/meta-arm' &
git clone https://github.com/shellhub-io/meta-shellhub '/storage/nvme5/new_clones/BitBake/meta-shellhub' &
git clone https://github.com/gpanders/meta-scipy '/storage/nvme5/new_clones/BitBake/meta-scipy' &
git clone https://github.com/OE4T/meta-tegra-community '/storage/nvme5/new_clones/BitBake/meta-tegra-community' &
git clone https://github.com/antmicro/meta-antmicro '/storage/nvme5/new_clones/BitBake/meta-antmicro' &
git clone https://github.com/DynamicDevices/meta-example '/storage/nvme5/new_clones/BitBake/meta-example' &
git clone https://github.com/nathanrossi/meta-hdl '/storage/nvme5/new_clones/BitBake/meta-hdl' &
git clone https://github.com/uptane/meta-updater '/storage/nvme5/new_clones/BitBake/meta-updater' &
git clone https://github.com/subgraph/citadel '/storage/nvme5/new_clones/BitBake/citadel' &
git clone https://github.com/starfive-tech/meta-starfive '/storage/nvme5/new_clones/BitBake/meta-starfive' &
git clone https://github.com/MarkusVolk/meta-wayland '/storage/nvme5/new_clones/BitBake/meta-wayland' &
git clone https://github.com/agherzan/meta-chip '/storage/nvme5/new_clones/BitBake/meta-chip' &
git clone https://github.com/digitallumens/meta-golang '/storage/nvme5/new_clones/BitBake/meta-golang' &
git clone https://github.com/ami-megarac/MORF-OpenBMC '/storage/nvme5/new_clones/BitBake/MORF-OpenBMC' &
git clone https://github.com/woglinde/meta-java '/storage/nvme5/new_clones/BitBake/meta-java' &
git clone https://github.com/virusvfv/BurpBounty-Profiles '/storage/nvme5/new_clones/BitBake/BurpBounty-Profiles' &
git clone https://github.com/DynamicDevices/meta-mono '/storage/nvme5/new_clones/BitBake/meta-mono' &
git clone https://github.com/webOS-ports/meta-webos-ports '/storage/nvme5/new_clones/BitBake/meta-webos-ports' &
git clone https://github.com/YoeDistro/meta-intel '/storage/nvme5/new_clones/BitBake/meta-intel' &
git clone https://github.com/cubicool/meta-jetson-tk1 '/storage/nvme5/new_clones/BitBake/meta-jetson-tk1' &
git clone https://github.com/yoctocookbook/meta-custom '/storage/nvme5/new_clones/BitBake/meta-custom' &
git clone https://github.com/Wind-River/meta-tensorflow '/storage/nvme5/new_clones/BitBake/meta-tensorflow' &
git clone https://github.com/kevinior/meta-kobo-clara-hd '/storage/nvme5/new_clones/BitBake/meta-kobo-clara-hd' &
git clone https://github.com/schnitzeltony/meta-musicians '/storage/nvme5/new_clones/BitBake/meta-musicians' &
git clone https://github.com/webOS-ports/meta-pine64-luneos '/storage/nvme5/new_clones/BitBake/meta-pine64-luneos' &
git clone https://github.com/t-kuha/recipes-ml '/storage/nvme5/new_clones/BitBake/recipes-ml' &
git clone https://github.com/ce-bu/meta-observability '/storage/nvme5/new_clones/BitBake/meta-observability' &
git clone https://github.com/jsbronder/meta-openrc '/storage/nvme5/new_clones/BitBake/meta-openrc' &
git clone https://github.com/geoffrey-vl/meta-doom '/storage/nvme5/new_clones/BitBake/meta-doom' &
git clone https://github.com/slint-ui/meta-slint '/storage/nvme5/new_clones/BitBake/meta-slint' &
git clone https://github.com/andestech/meta-andes '/storage/nvme5/new_clones/BitBake/meta-andes' &
git clone https://github.com/balena-os/balena-odroid '/storage/nvme5/new_clones/BitBake/balena-odroid' &
git clone https://github.com/balena-os/balena-radxa '/storage/nvme5/new_clones/BitBake/balena-radxa' &
git clone https://github.com/sergioprado/meta-game-emulators '/storage/nvme5/new_clones/BitBake/meta-game-emulators' &
git clone https://github.com/Pelagicore/meta-bistro '/storage/nvme5/new_clones/BitBake/meta-bistro' &
git clone https://github.com/embetrix/meta-stm32mp15x '/storage/nvme5/new_clones/BitBake/meta-stm32mp15x' &
git clone https://github.com/sailfish-on-dontbeevil/droid-config-pinephone '/storage/nvme5/new_clones/BitBake/droid-config-pinephone' &
git clone https://github.com/altera-opensource/meta-intel-fpga-refdes '/storage/nvme5/new_clones/BitBake/meta-intel-fpga-refdes' &
git clone https://github.com/compulab-yokneam/meta-bsp-imx8mp '/storage/nvme5/new_clones/BitBake/meta-bsp-imx8mp' &
git clone https://github.com/ds-hwang/yocto-chromium '/storage/nvme5/new_clones/BitBake/yocto-chromium' &
git clone https://github.com/EmbeddedAndroid/meta-rtlwifi '/storage/nvme5/new_clones/BitBake/meta-rtlwifi' &
git clone https://github.com/esven/meta-imx6-secure-boot '/storage/nvme5/new_clones/BitBake/meta-imx6-secure-boot' &
git clone https://github.com/KDE/yocto-meta-kde '/storage/nvme5/new_clones/BitBake/yocto-meta-kde' &
git clone https://github.com/jiazhang0/meta-efi-secure-boot '/storage/nvme5/new_clones/BitBake/meta-efi-secure-boot' &
git clone https://github.com/coreycothrum/meta-mender-luks '/storage/nvme5/new_clones/BitBake/meta-mender-luks' &
git clone https://github.com/nvidia-holoscan/meta-tegra-holoscan '/storage/nvme5/new_clones/BitBake/meta-tegra-holoscan' &
git clone https://github.com/UpdateHub/meta-updatehub '/storage/nvme5/new_clones/BitBake/meta-updatehub' &
git clone https://github.com/Dasharo/meta-dts '/storage/nvme5/new_clones/BitBake/meta-dts' &
git clone https://github.com/vladest/meta-qtautomotive '/storage/nvme5/new_clones/BitBake/meta-qtautomotive' &
git clone https://github.com/imyller/meta-nodejs-contrib '/storage/nvme5/new_clones/BitBake/meta-nodejs-contrib' &
git clone https://github.com/OSSystems/meta-miracast '/storage/nvme5/new_clones/BitBake/meta-miracast' &
git clone https://github.com/Tragetaschen/meta-aspnet '/storage/nvme5/new_clones/BitBake/meta-aspnet' &
git clone https://github.com/renesas-rz/meta-rzg2 '/storage/nvme5/new_clones/BitBake/meta-rzg2' &
git clone https://github.com/Wifx/lorix-os '/storage/nvme5/new_clones/BitBake/lorix-os' &
git clone https://github.com/MIPS/meta-img '/storage/nvme5/new_clones/BitBake/meta-img' &
git clone https://github.com/koenkooi/meta-kodi '/storage/nvme5/new_clones/BitBake/meta-kodi' &
git clone https://github.com/labgrid-project/meta-labgrid '/storage/nvme5/new_clones/BitBake/meta-labgrid' &
git clone https://github.com/tq-systems/meta-tq '/storage/nvme5/new_clones/BitBake/meta-tq' &
git clone https://github.com/jwinarske/meta-vulkan '/storage/nvme5/new_clones/BitBake/meta-vulkan' &
git clone https://github.com/jumpnow/meta-overo '/storage/nvme5/new_clones/BitBake/meta-overo' &
git clone https://github.com/openbmc/meta-phosphor '/storage/nvme5/new_clones/BitBake/meta-phosphor' &
git clone https://github.com/balena-os/balena-variscite-mx8 '/storage/nvme5/new_clones/BitBake/balena-variscite-mx8' &
git clone https://github.com/FullMetalUpdate/meta-fullmetalupdate '/storage/nvme5/new_clones/BitBake/meta-fullmetalupdate' &
git clone https://github.com/balena-os/meta-artik '/storage/nvme5/new_clones/BitBake/meta-artik' &
git clone https://github.com/pengutronix/meta-ptx '/storage/nvme5/new_clones/BitBake/meta-ptx' &
git clone https://github.com/openeuler-mirror/yocto-meta-openeuler '/storage/nvme5/new_clones/BitBake/yocto-meta-openeuler' &
git clone https://github.com/STMicroelectronics/meta-st-stm32mp-addons '/storage/nvme5/new_clones/BitBake/meta-st-stm32mp-addons' &
git clone https://github.com/canonical/meta-snapd '/storage/nvme5/new_clones/BitBake/meta-snapd' &
git clone https://github.com/karo-electronics/meta-karo '/storage/nvme5/new_clones/BitBake/meta-karo' &
git clone https://github.com/elisa-tech/meta-elisa '/storage/nvme5/new_clones/BitBake/meta-elisa' &
git clone https://github.com/deptofdefense/meta-darpahackfest '/storage/nvme5/new_clones/BitBake/meta-darpahackfest' &
git clone https://github.com/priv-kweihmann/meta-buildutils '/storage/nvme5/new_clones/BitBake/meta-buildutils' &
git clone https://github.com/thin-edge/meta-tedge '/storage/nvme5/new_clones/BitBake/meta-tedge' &
git clone https://github.com/mickey-happygolucky/meta-qt5-rpi-eglfs '/storage/nvme5/new_clones/BitBake/meta-qt5-rpi-eglfs' &
git clone https://github.com/balena-os/balena-generic '/storage/nvme5/new_clones/BitBake/balena-generic' &
git clone https://github.com/dl9pf/meta-spdxscanner '/storage/nvme5/new_clones/BitBake/meta-spdxscanner' &
git clone https://github.com/intel/meta-intel-camera '/storage/nvme5/new_clones/BitBake/meta-intel-camera' &
git clone https://github.com/bvarner/meta-bvarner-embedded '/storage/nvme5/new_clones/BitBake/meta-bvarner-embedded' &
git clone https://github.com/sarnold/meta-alt-desktop-extras '/storage/nvme5/new_clones/BitBake/meta-alt-desktop-extras' &
git clone https://github.com/OpenDDS/meta-opendds '/storage/nvme5/new_clones/BitBake/meta-opendds' &
git clone https://github.com/s-vincent/meta-raspberrypi-rt-sv '/storage/nvme5/new_clones/BitBake/meta-raspberrypi-rt-sv' &
git clone https://github.com/imyller/meta-micropython '/storage/nvme5/new_clones/BitBake/meta-micropython' &
git clone https://github.com/HULKs/meta-nao '/storage/nvme5/new_clones/BitBake/meta-nao' &
git clone https://github.com/munit-solutions/meta-azure-device-update '/storage/nvme5/new_clones/BitBake/meta-azure-device-update' &
git clone https://github.com/phytec/meta-ampliphy '/storage/nvme5/new_clones/BitBake/meta-ampliphy' &
git clone https://github.com/intel/meta-intel-sgx '/storage/nvme5/new_clones/BitBake/meta-intel-sgx' &
git clone https://github.com/xleng/meta-bananapi '/storage/nvme5/new_clones/BitBake/meta-bananapi' &
git clone https://github.com/willstott101/meta-mediapipe '/storage/nvme5/new_clones/BitBake/meta-mediapipe' &
git clone https://github.com/Xilinx/meta-jupyter '/storage/nvme5/new_clones/BitBake/meta-jupyter' &
git clone https://github.com/eclipse-leda/meta-leda '/storage/nvme5/new_clones/BitBake/meta-leda' &
git clone https://github.com/windelbouwman/meta-ros2-generator '/storage/nvme5/new_clones/BitBake/meta-ros2-generator' &
git clone https://github.com/menschel-d/meta-barebox '/storage/nvme5/new_clones/BitBake/meta-barebox' &
git clone https://github.com/miraclelinux/meta-debian-extended '/storage/nvme5/new_clones/BitBake/meta-debian-extended' &
git clone https://github.com/3mdeb/meta-rte '/storage/nvme5/new_clones/BitBake/meta-rte' &
git clone https://github.com/saininav/meta-zephyr '/storage/nvme5/new_clones/BitBake/meta-zephyr' &
git clone https://github.com/brocaar/loraserver-yocto '/storage/nvme5/new_clones/BitBake/loraserver-yocto' &
git clone https://github.com/sartura/meta-sysrepo '/storage/nvme5/new_clones/BitBake/meta-sysrepo' &
git clone https://github.com/meta-java/meta-java '/storage/nvme5/new_clones/BitBake/meta-java' &
git clone https://github.com/flatpak/freedesktop-sdk-base '/storage/nvme5/new_clones/BitBake/freedesktop-sdk-base' &
git clone https://github.com/balena-os/balena-fsl-arm '/storage/nvme5/new_clones/BitBake/balena-fsl-arm' &
git clone https://github.com/RidgeRun/meta-ridgerun '/storage/nvme5/new_clones/BitBake/meta-ridgerun' &
git clone https://github.com/Avnet/meta-rzboard '/storage/nvme5/new_clones/BitBake/meta-rzboard' &
git clone https://github.com/savoirfairelinux/meta-jami '/storage/nvme5/new_clones/BitBake/meta-jami' &
git clone https://github.com/nxp-auto-linux/meta-alb '/storage/nvme5/new_clones/BitBake/meta-alb' &
git clone https://github.com/alext-mkrs/meta-alext-edison '/storage/nvme5/new_clones/BitBake/meta-alext-edison' &
git clone https://github.com/lmajewski/meta-y2038 '/storage/nvme5/new_clones/BitBake/meta-y2038' &
git clone https://github.com/solettaproject/meta-soletta '/storage/nvme5/new_clones/BitBake/meta-soletta' &
git clone https://github.com/cloud-hypervisor/meta-cloud-hypervisor '/storage/nvme5/new_clones/BitBake/meta-cloud-hypervisor' &
git clone https://github.com/jumpnow/meta-jumpnow '/storage/nvme5/new_clones/BitBake/meta-jumpnow' &
git clone https://github.com/tiiuae/meta-sel4 '/storage/nvme5/new_clones/BitBake/meta-sel4' &
git clone https://github.com/YoctoForBeaglebone/meta-ybdevelop '/storage/nvme5/new_clones/BitBake/meta-ybdevelop' &
git clone https://github.com/Xilinx/meta-vitis '/storage/nvme5/new_clones/BitBake/meta-vitis' &
git clone https://github.com/MYiR-Dev/meta-myir-imx '/storage/nvme5/new_clones/BitBake/meta-myir-imx' &
git clone https://github.com/teamviewer/meta-teamviewer-iot-agent '/storage/nvme5/new_clones/BitBake/meta-teamviewer-iot-agent' &
git clone https://github.com/SolidRun/meta-solidrun-arm-imx6 '/storage/nvme5/new_clones/BitBake/meta-solidrun-arm-imx6' &
git clone https://github.com/seapath/meta-seapath '/storage/nvme5/new_clones/BitBake/meta-seapath' &
git clone https://github.com/alfonsotames/meta-kodi '/storage/nvme5/new_clones/BitBake/meta-kodi' &
git clone https://github.com/hamzamac/meta-splash '/storage/nvme5/new_clones/BitBake/meta-splash' &
git clone https://github.com/foxsen/meta-loongson '/storage/nvme5/new_clones/BitBake/meta-loongson' &
git clone https://github.com/EVerest/meta-everest '/storage/nvme5/new_clones/BitBake/meta-everest' &
git clone https://github.com/dl9pf/meta-codechecker '/storage/nvme5/new_clones/BitBake/meta-codechecker' &
git clone https://github.com/jluebbe/meta-code-signing '/storage/nvme5/new_clones/BitBake/meta-code-signing' &
git clone https://github.com/SOL-Space-Operating-Linux/meta-sol '/storage/nvme5/new_clones/BitBake/meta-sol' &
git clone https://github.com/TechNexion-customization/meta-scorpion '/storage/nvme5/new_clones/BitBake/meta-scorpion' &
git clone https://github.com/Seeed-Studio/meta-st-odyssey '/storage/nvme5/new_clones/BitBake/meta-st-odyssey' &
git clone https://github.com/toradex/meta-toradex-tezi '/storage/nvme5/new_clones/BitBake/meta-toradex-tezi' &
git clone https://github.com/YoeDistro/meta-ti '/storage/nvme5/new_clones/BitBake/meta-ti' &
git clone https://github.com/AGLExport/meta-jetson '/storage/nvme5/new_clones/BitBake/meta-jetson' &
git clone https://github.com/bluelightning/meta-handheld '/storage/nvme5/new_clones/BitBake/meta-handheld' &
git clone https://github.com/madscientist42/meta-runit '/storage/nvme5/new_clones/BitBake/meta-runit' &
git clone https://github.com/astarasikov/meta-aravis '/storage/nvme5/new_clones/BitBake/meta-aravis' &
git clone https://github.com/mhzawadi/docker-stash '/storage/nvme5/new_clones/BitBake/docker-stash' &
git clone https://github.com/balena-os/balena-up-board '/storage/nvme5/new_clones/BitBake/balena-up-board' &
git clone https://github.com/incandescant/meta-myhouse '/storage/nvme5/new_clones/BitBake/meta-myhouse' &
git clone https://github.com/slawr/renesas-rcar-gen3 '/storage/nvme5/new_clones/BitBake/renesas-rcar-gen3' &
git clone https://github.com/crosswalk-project/meta-crosswalk '/storage/nvme5/new_clones/BitBake/meta-crosswalk' &
git clone https://github.com/Seeed-Studio/meta-odyssey-x86 '/storage/nvme5/new_clones/BitBake/meta-odyssey-x86' &
git clone https://github.com/lgirdk/meta-virtualization '/storage/nvme5/new_clones/BitBake/meta-virtualization' &
git clone https://github.com/Cezarus27/meta-nezha '/storage/nvme5/new_clones/BitBake/meta-nezha' &
git clone https://github.com/rdanter/wrl-rpi-bsp '/storage/nvme5/new_clones/BitBake/wrl-rpi-bsp' &
git clone https://github.com/WaRP7/meta-warp7-distro '/storage/nvme5/new_clones/BitBake/meta-warp7-distro' &
git clone https://github.com/NXP/meta-nxp-avb '/storage/nvme5/new_clones/BitBake/meta-nxp-avb' &
git clone https://github.com/eclabs007/Yocto-Udemy '/storage/nvme5/new_clones/BitBake/Yocto-Udemy' &
git clone https://github.com/exein-io/meta-exein '/storage/nvme5/new_clones/BitBake/meta-exein' &
git clone https://github.com/enclustra/Mercury_XU5_ST1_Reference_Design '/storage/nvme5/new_clones/BitBake/Mercury_XU5_ST1_Reference_Design' &
git clone https://github.com/linux-automation/meta-lxatac '/storage/nvme5/new_clones/BitBake/meta-lxatac' &
git clone https://github.com/mon0theist/mon0meters '/storage/nvme5/new_clones/BitBake/mon0meters' &
git clone https://github.com/adrianalin/meta-aacs '/storage/nvme5/new_clones/BitBake/meta-aacs' &
git clone https://github.com/TechNexion/meta-tn-imx-bsp '/storage/nvme5/new_clones/BitBake/meta-tn-imx-bsp' &
git clone https://github.com/foss-for-synopsys-dwc-arc-processors/meta-synopsys '/storage/nvme5/new_clones/BitBake/meta-synopsys' &
git clone https://github.com/pauldotknopf/raspberry-pi-camera-source '/storage/nvme5/new_clones/BitBake/raspberry-pi-camera-source' &
git clone https://github.com/platisd/meta-dimitriOS '/storage/nvme5/new_clones/BitBake/meta-dimitriOS' &
