#!/bin/bash

git clone https://github.com/bluespec/Flute '/storage/nvme5/new_clones/Bluespec/Flute' &
git clone https://github.com/cambridgehackers/connectal '/storage/nvme5/new_clones/Bluespec/connectal' &
git clone https://github.com/csail-csg/riscy-OOO '/storage/nvme5/new_clones/Bluespec/riscy-OOO' &
git clone https://github.com/rsnikhil/Bluespec_BSV_Tutorial '/storage/nvme5/new_clones/Bluespec/Bluespec_BSV_Tutorial' &
git clone https://github.com/oxidecomputer/cobalt '/storage/nvme5/new_clones/Bluespec/cobalt' &
git clone https://github.com/p4fpga/p4fpga '/storage/nvme5/new_clones/Bluespec/p4fpga' &
git clone https://github.com/csail-csg/riscy '/storage/nvme5/new_clones/Bluespec/riscy' &
git clone https://github.com/sangwoojun/bluespecpcie '/storage/nvme5/new_clones/Bluespec/bluespecpcie' &
git clone https://github.com/maeri-project/MAERI_bsv '/storage/nvme5/new_clones/Bluespec/MAERI_bsv' &
git clone https://github.com/hyoukjun/OpenSMART '/storage/nvme5/new_clones/Bluespec/OpenSMART' &
git clone https://github.com/CTSRD-CHERI/bluecheck '/storage/nvme5/new_clones/Bluespec/bluecheck' &
git clone https://github.com/CTSRD-CHERI/beri '/storage/nvme5/new_clones/Bluespec/beri' &
git clone https://github.com/POETSII/tinsel '/storage/nvme5/new_clones/Bluespec/tinsel' &
git clone https://github.com/B-Lang-org/bsc-contrib '/storage/nvme5/new_clones/Bluespec/bsc-contrib' &
git clone https://github.com/maeri-project/MAERI_bsv_isca2018 '/storage/nvme5/new_clones/Bluespec/MAERI_bsv_isca2018' &
git clone https://github.com/hyoukjun/DesignCNNAccelerators '/storage/nvme5/new_clones/Bluespec/DesignCNNAccelerators' &
git clone https://github.com/HPC-Lab-IITB/Clarinet '/storage/nvme5/new_clones/Bluespec/Clarinet' &
git clone https://github.com/danderson/ulxs '/storage/nvme5/new_clones/Bluespec/ulxs' &
git clone https://github.com/rsnikhil/RISCV_ISA_Formal_Spec_in_BSV '/storage/nvme5/new_clones/Bluespec/RISCV_ISA_Formal_Spec_in_BSV' &
git clone https://github.com/CTSRD-CHERI/RVBS '/storage/nvme5/new_clones/Bluespec/RVBS' &
git clone https://github.com/chipsalliance/OmnixtendEndpoint '/storage/nvme5/new_clones/Bluespec/OmnixtendEndpoint' &
git clone https://github.com/q3k/qfc '/storage/nvme5/new_clones/Bluespec/qfc' &
git clone https://github.com/CTSRD-CHERI/BlueStuff '/storage/nvme5/new_clones/Bluespec/BlueStuff' &
git clone https://github.com/arpitp/ssd-controller '/storage/nvme5/new_clones/Bluespec/ssd-controller' &
git clone https://github.com/hanw/sonic-lite '/storage/nvme5/new_clones/Bluespec/sonic-lite' &
git clone https://github.com/FelixWinterstein/LEAP-HLS '/storage/nvme5/new_clones/Bluespec/LEAP-HLS' &
git clone https://github.com/dramforever/ixayoi '/storage/nvme5/new_clones/Bluespec/ixayoi' &
git clone https://github.com/sangwoojun/bluelib '/storage/nvme5/new_clones/Bluespec/bluelib' &
git clone https://github.com/fabatef/6.175 '/storage/nvme5/new_clones/Bluespec/6.175' &
git clone https://github.com/freecores/bluespec-h264 '/storage/nvme5/new_clones/Bluespec/bluespec-h264' &
git clone https://github.com/crossroadsfpga/connect '/storage/nvme5/new_clones/Bluespec/connect' &
git clone https://github.com/jeffreycassidy/BlueLink '/storage/nvme5/new_clones/Bluespec/BlueLink' &
git clone https://github.com/Raamakrishnan/bsv-for-vscode '/storage/nvme5/new_clones/Bluespec/bsv-for-vscode' &
git clone https://github.com/esa-tu-darmstadt/BlueAXI '/storage/nvme5/new_clones/Bluespec/BlueAXI' &
git clone https://github.com/sangwoojun/ulx3s_bsv '/storage/nvme5/new_clones/Bluespec/ulx3s_bsv' &
git clone https://github.com/iitm-sysdl/SHAKTIMAAN '/storage/nvme5/new_clones/Bluespec/SHAKTIMAAN' &
git clone https://github.com/freecores/bluespec-80211atransmitter '/storage/nvme5/new_clones/Bluespec/bluespec-80211atransmitter' &
git clone https://github.com/resource-disaggregation/Shoal '/storage/nvme5/new_clones/Bluespec/Shoal' &
git clone https://github.com/csail-csg/recycle-bsv-lib '/storage/nvme5/new_clones/Bluespec/recycle-bsv-lib' &
git clone https://github.com/freecores/bluespec-reedsolomon '/storage/nvme5/new_clones/Bluespec/bluespec-reedsolomon' &
git clone https://github.com/tudang/bluespec-tutorials '/storage/nvme5/new_clones/Bluespec/bluespec-tutorials' &
git clone https://github.com/CTSRD-CHERI/BID '/storage/nvme5/new_clones/Bluespec/BID' &
git clone https://github.com/bluespec/RISCV_Debug_Module '/storage/nvme5/new_clones/Bluespec/RISCV_Debug_Module' &
git clone https://github.com/CTSRD-CHERI/cheri-cap-lib '/storage/nvme5/new_clones/Bluespec/cheri-cap-lib' &
git clone https://github.com/Sooryakiran/Domain-Specific-Hardware-Accelerator-VLSI-CAD-Project '/storage/nvme5/new_clones/Bluespec/Domain-Specific-Hardware-Accelerator-VLSI-CAD-Project' &
git clone https://github.com/GTwhy/MIT_6.175 '/storage/nvme5/new_clones/Bluespec/MIT_6.175' &
git clone https://github.com/esa-tu-darmstadt/BlueLib '/storage/nvme5/new_clones/Bluespec/BlueLib' &
