#!/bin/bash

git clone https://github.com/kkrt-labs/kakarot '/storage/nvme5/new_clones/Cairo/kakarot' &
git clone https://github.com/starknet-edu/starknet-cairo-101 '/storage/nvme5/new_clones/Cairo/starknet-cairo-101' &
git clone https://github.com/ZeroSync/ZeroSync '/storage/nvme5/new_clones/Cairo/ZeroSync' &
git clone https://github.com/keep-starknet-strange/alexandria '/storage/nvme5/new_clones/Cairo/alexandria' &
git clone https://github.com/starknet-io/starkgate-contracts '/storage/nvme5/new_clones/Cairo/starkgate-contracts' &
git clone https://github.com/gizatechxyz/orion '/storage/nvme5/new_clones/Cairo/orion' &
git clone https://github.com/WTFAcademy/WTF-Cairo '/storage/nvme5/new_clones/Cairo/WTF-Cairo' &
git clone https://github.com/starknet-edu/starknet-messaging-bridge '/storage/nvme5/new_clones/Cairo/starknet-messaging-bridge' &
git clone https://github.com/snapshot-labs/sx-starknet '/storage/nvme5/new_clones/Cairo/sx-starknet' &
git clone https://github.com/dopedao/RYO '/storage/nvme5/new_clones/Cairo/RYO' &
git clone https://github.com/age-of-eykar/contract '/storage/nvme5/new_clones/Cairo/contract' &
git clone https://github.com/lfglabs-dev/old_identity '/storage/nvme5/new_clones/Cairo/old_identity' &
git clone https://github.com/starknet-edu/starknet-erc721 '/storage/nvme5/new_clones/Cairo/starknet-erc721' &
git clone https://github.com/jediswaplabs/JediSwap '/storage/nvme5/new_clones/Cairo/JediSwap' &
git clone https://github.com/eqlabs/starknet-multisig '/storage/nvme5/new_clones/Cairo/starknet-multisig' &
git clone https://github.com/starknet-edu/starknet-accounts '/storage/nvme5/new_clones/Cairo/starknet-accounts' &
git clone https://github.com/starknet-edu/starknet-erc20 '/storage/nvme5/new_clones/Cairo/starknet-erc20' &
git clone https://github.com/maxgillett/stark-attestations '/storage/nvme5/new_clones/Cairo/stark-attestations' &
git clone https://github.com/briqNFT/briq-protocol '/storage/nvme5/new_clones/Cairo/briq-protocol' &
git clone https://github.com/ExtropyIO/ZeroKnowledgeBootcamp '/storage/nvme5/new_clones/Cairo/ZeroKnowledgeBootcamp' &
git clone https://github.com/onlydustxyz/cairo-streams '/storage/nvme5/new_clones/Cairo/cairo-streams' &
git clone https://github.com/10k-swap/10k_swap-contracts '/storage/nvme5/new_clones/Cairo/10k_swap-contracts' &
git clone https://github.com/Carbonable/carbon-protocol '/storage/nvme5/new_clones/Cairo/carbon-protocol' &
git clone https://github.com/bitcoin-stark/khepri '/storage/nvme5/new_clones/Cairo/khepri' &
git clone https://github.com/starkware-libs/stark-perpetual '/storage/nvme5/new_clones/Cairo/stark-perpetual' &
git clone https://github.com/milancermak/cairo-4626 '/storage/nvme5/new_clones/Cairo/cairo-4626' &
git clone https://github.com/starknet-edu/starknet-debug '/storage/nvme5/new_clones/Cairo/starknet-debug' &
git clone https://github.com/StarkLinkVRF/VRF-StarkNet '/storage/nvme5/new_clones/Cairo/VRF-StarkNet' &
git clone https://github.com/sambarnes/cairo-multisig '/storage/nvme5/new_clones/Cairo/cairo-multisig' &
git clone https://github.com/sekai-studio/starknet-libs '/storage/nvme5/new_clones/Cairo/starknet-libs' &
git clone https://github.com/astraly-labs/astraly-contracts '/storage/nvme5/new_clones/Cairo/astraly-contracts' &
git clone https://github.com/Lev-Stambler/bulletproof-cairo '/storage/nvme5/new_clones/Cairo/bulletproof-cairo' &
git clone https://github.com/greenlucid/chess-cairo '/storage/nvme5/new_clones/Cairo/chess-cairo' &
git clone https://github.com/ChecksFinance/soul-moment '/storage/nvme5/new_clones/Cairo/soul-moment' &
git clone https://github.com/sambarnes/cairo-bloom '/storage/nvme5/new_clones/Cairo/cairo-bloom' &
git clone https://github.com/milancermak/xoroshiro-cairo '/storage/nvme5/new_clones/Cairo/xoroshiro-cairo' &
git clone https://github.com/spartucus/nistp256-cairo '/storage/nvme5/new_clones/Cairo/nistp256-cairo' &
git clone https://github.com/CarmineOptions/carmine-protocol '/storage/nvme5/new_clones/Cairo/carmine-protocol' &
git clone https://github.com/dhruvkelawala/cairo-base64 '/storage/nvme5/new_clones/Cairo/cairo-base64' &
git clone https://github.com/sambarnes/cairo-dutch '/storage/nvme5/new_clones/Cairo/cairo-dutch' &
git clone https://github.com/EulerSmile/common-ec-cairo '/storage/nvme5/new_clones/Cairo/common-ec-cairo' &
git clone https://github.com/lucadonnoh/graphiro '/storage/nvme5/new_clones/Cairo/graphiro' &
git clone https://github.com/Th0rgal/sphinx '/storage/nvme5/new_clones/Cairo/sphinx' &
git clone https://github.com/starknet-edu/walking-with-starknet '/storage/nvme5/new_clones/Cairo/walking-with-starknet' &
git clone https://github.com/lucadonnoh/axelrod '/storage/nvme5/new_clones/Cairo/axelrod' &
git clone https://github.com/onlydustxyz/starkonquest '/storage/nvme5/new_clones/Cairo/starkonquest' &
git clone https://github.com/ametel01/Ogame-Cairo '/storage/nvme5/new_clones/Cairo/Ogame-Cairo' &
git clone https://github.com/starkware-libs/starkex-for-spot-trading '/storage/nvme5/new_clones/Cairo/starkex-for-spot-trading' &
git clone https://github.com/enitrat/cairo-graphs '/storage/nvme5/new_clones/Cairo/cairo-graphs' &
git clone https://github.com/carbonable-labs/cairo-erc-3525 '/storage/nvme5/new_clones/Cairo/cairo-erc-3525' &
git clone https://github.com/tohrnii/flashloan-starknet '/storage/nvme5/new_clones/Cairo/flashloan-starknet' &
git clone https://github.com/CairOpen/cairopen-contracts '/storage/nvme5/new_clones/Cairo/cairopen-contracts' &
git clone https://github.com/gaetbout/starknet-array-manipulation '/storage/nvme5/new_clones/Cairo/starknet-array-manipulation' &
git clone https://github.com/lindy-labs/wadray '/storage/nvme5/new_clones/Cairo/wadray' &
git clone https://github.com/Starkdefi/StarkDefi '/storage/nvme5/new_clones/Cairo/StarkDefi' &
git clone https://github.com/udayj/starknet_prediction_market '/storage/nvme5/new_clones/Cairo/starknet_prediction_market' &
git clone https://github.com/0xKermo/Cairo-NFT-Lending-Auction '/storage/nvme5/new_clones/Cairo/Cairo-NFT-Lending-Auction' &
git clone https://github.com/pscott/StarknetCC-CTF '/storage/nvme5/new_clones/Cairo/StarknetCC-CTF' &
git clone https://github.com/CodeforDAO/cairo-contracts '/storage/nvme5/new_clones/Cairo/cairo-contracts' &
git clone https://github.com/gaetbout/starknet-felt-packing '/storage/nvme5/new_clones/Cairo/starknet-felt-packing' &
git clone https://github.com/samlaf/starknet-btc-lightclient '/storage/nvme5/new_clones/Cairo/starknet-btc-lightclient' &
git clone https://github.com/gaetbout/starknet-commit-reveal '/storage/nvme5/new_clones/Cairo/starknet-commit-reveal' &
git clone https://github.com/zkLend/zklend-v1-core '/storage/nvme5/new_clones/Cairo/zklend-v1-core' &
git clone https://github.com/ametel01/No-Game '/storage/nvme5/new_clones/Cairo/No-Game' &
git clone https://github.com/cartridge-gg/cairo-base64 '/storage/nvme5/new_clones/Cairo/cairo-base64' &
git clone https://github.com/Fibrous-Finance/fibrous-aggregator-contracts '/storage/nvme5/new_clones/Cairo/fibrous-aggregator-contracts' &
git clone https://github.com/bigsky77/hyperion '/storage/nvme5/new_clones/Cairo/hyperion' &
git clone https://github.com/udayj/token_gated_account '/storage/nvme5/new_clones/Cairo/token_gated_account' &
git clone https://github.com/NethermindEth/optimized_ecc_cairo '/storage/nvme5/new_clones/Cairo/optimized_ecc_cairo' &
git clone https://github.com/cartridge-gg/cairo-sha256 '/storage/nvme5/new_clones/Cairo/cairo-sha256' &
git clone https://github.com/ruleslabs/marketplace '/storage/nvme5/new_clones/Cairo/marketplace' &
git clone https://github.com/0xKermo/Solidity-vs-Cairo '/storage/nvme5/new_clones/Cairo/Solidity-vs-Cairo' &
git clone https://github.com/boli-bohan/cairo-jsonwebtoken '/storage/nvme5/new_clones/Cairo/cairo-jsonwebtoken' &
git clone https://github.com/starknet-edu/remix-game-day '/storage/nvme5/new_clones/Cairo/remix-game-day' &
git clone https://github.com/ruleslabs/core '/storage/nvme5/new_clones/Cairo/core' &
git clone https://github.com/greged93/bto-cairo '/storage/nvme5/new_clones/Cairo/bto-cairo' &
git clone https://github.com/tradeflows/v1-core-starknet '/storage/nvme5/new_clones/Cairo/v1-core-starknet' &
git clone https://github.com/milancermak/cairo-underhanded '/storage/nvme5/new_clones/Cairo/cairo-underhanded' &
git clone https://github.com/amanusk/cairo-paradigm-ctf '/storage/nvme5/new_clones/Cairo/cairo-paradigm-ctf' &
git clone https://github.com/BibliothecaDAO/DOJO '/storage/nvme5/new_clones/Cairo/DOJO' &
git clone https://github.com/nmalzieu/pxls-contracts '/storage/nvme5/new_clones/Cairo/pxls-contracts' &
git clone https://github.com/milancermak/experiments-in-cairo '/storage/nvme5/new_clones/Cairo/experiments-in-cairo' &
git clone https://github.com/0xtonysprocket/fixed_point '/storage/nvme5/new_clones/Cairo/fixed_point' &
git clone https://github.com/widroz/PokerDeck-Cairo '/storage/nvme5/new_clones/Cairo/PokerDeck-Cairo' &
git clone https://github.com/ZK-Graph/mirror-starknet-zkgraph-protocol '/storage/nvme5/new_clones/Cairo/mirror-starknet-zkgraph-protocol' &
git clone https://github.com/milancermak/onchain-js '/storage/nvme5/new_clones/Cairo/onchain-js' &
git clone https://github.com/chainstacklabs/starknet-cairo-odyssey '/storage/nvme5/new_clones/Cairo/starknet-cairo-odyssey' &
git clone https://github.com/pedrobergamini/starknet-staking '/storage/nvme5/new_clones/Cairo/starknet-staking' &
git clone https://github.com/lfglabs-dev/old_naming '/storage/nvme5/new_clones/Cairo/old_naming' &
git clone https://github.com/smchala/demultiplexer-wallet '/storage/nvme5/new_clones/Cairo/demultiplexer-wallet' &
git clone https://github.com/starknet-edu/ultimate-env '/storage/nvme5/new_clones/Cairo/ultimate-env' &
git clone https://github.com/tevrat-aksoy/saddle-cairo '/storage/nvme5/new_clones/Cairo/saddle-cairo' &
git clone https://github.com/albert-garreta/Example-keccak-in-starknet '/storage/nvme5/new_clones/Cairo/Example-keccak-in-starknet' &
git clone https://github.com/dpinones/pathfinders-ar '/storage/nvme5/new_clones/Cairo/pathfinders-ar' &
git clone https://github.com/shramee/creative-cairo '/storage/nvme5/new_clones/Cairo/creative-cairo' &
git clone https://github.com/beautyisourbusiness/fangcheng '/storage/nvme5/new_clones/Cairo/fangcheng' &
git clone https://github.com/CygnusDAO/starknet-core '/storage/nvme5/new_clones/Cairo/starknet-core' &
git clone https://github.com/guiltygyoza/cairo_exercises '/storage/nvme5/new_clones/Cairo/cairo_exercises' &
git clone https://github.com/raphaelDkhn/json-on-starknet '/storage/nvme5/new_clones/Cairo/json-on-starknet' &
git clone https://github.com/EulerSmile/ff-cairo '/storage/nvme5/new_clones/Cairo/ff-cairo' &
git clone https://github.com/grillolepic/almanacNFT_cairo '/storage/nvme5/new_clones/Cairo/almanacNFT_cairo' &
git clone https://github.com/lucidLuckylee/LightSync '/storage/nvme5/new_clones/Cairo/LightSync' &
git clone https://github.com/omarespejel/walking-with-starknet '/storage/nvme5/new_clones/Cairo/walking-with-starknet' &
git clone https://github.com/NethermindEth/research-basic-Cairo-operations-big-integers '/storage/nvme5/new_clones/Cairo/research-basic-Cairo-operations-big-integers' &
git clone https://github.com/sphinx-protocol/cairo-data-structures '/storage/nvme5/new_clones/Cairo/cairo-data-structures' &
git clone https://github.com/0xNonCents/multi-precision_cairo '/storage/nvme5/new_clones/Cairo/multi-precision_cairo' &
git clone https://github.com/Th0rgal/better-multicall '/storage/nvme5/new_clones/Cairo/better-multicall' &
git clone https://github.com/udayj/dynamic_voting_system '/storage/nvme5/new_clones/Cairo/dynamic_voting_system' &
git clone https://github.com/onlydustxyz/protostar-vs-nile '/storage/nvme5/new_clones/Cairo/protostar-vs-nile' &
git clone https://github.com/Flydexo/kakarot-eth-aa '/storage/nvme5/new_clones/Cairo/kakarot-eth-aa' &
git clone https://github.com/zoeAD/basic-solver '/storage/nvme5/new_clones/Cairo/basic-solver' &
git clone https://github.com/CodeforDAO/cairo-array-utils '/storage/nvme5/new_clones/Cairo/cairo-array-utils' &
git clone https://github.com/419Labs/starknet-cc-tdd '/storage/nvme5/new_clones/Cairo/starknet-cc-tdd' &
git clone https://github.com/cheikhfiteni/obsidian '/storage/nvme5/new_clones/Cairo/obsidian' &
git clone https://github.com/abstractnull/specialfunctions_cairo '/storage/nvme5/new_clones/Cairo/specialfunctions_cairo' &
git clone https://github.com/vmmuthu31/NFT_Craft '/storage/nvme5/new_clones/Cairo/NFT_Craft' &
git clone https://github.com/ClementWalter/degensplit '/storage/nvme5/new_clones/Cairo/degensplit' &
git clone https://github.com/Seraph-Labs/Cairo-Contracts '/storage/nvme5/new_clones/Cairo/Cairo-Contracts' &
git clone https://github.com/BrilliantBlocks/brilliantblocks-starknet-diamond '/storage/nvme5/new_clones/Cairo/brilliantblocks-starknet-diamond' &
git clone https://github.com/0xAurelou/flash-loan-starknet '/storage/nvme5/new_clones/Cairo/flash-loan-starknet' &
git clone https://github.com/onlydustxyz/imhotep '/storage/nvme5/new_clones/Cairo/imhotep' &
git clone https://github.com/PhilippeR26/AskYourParents-contracts '/storage/nvme5/new_clones/Cairo/AskYourParents-contracts' &
