#!/bin/bash

git clone https://github.com/gravitystorm/openstreetmap-carto '/storage/nvme5/new_clones/CartoCSS/openstreetmap-carto' &
git clone https://github.com/mapbox/osm-bright '/storage/nvme5/new_clones/CartoCSS/osm-bright' &
git clone https://github.com/stamen/toner-carto '/storage/nvme5/new_clones/CartoCSS/toner-carto' &
git clone https://github.com/migurski/HighRoad '/storage/nvme5/new_clones/CartoCSS/HighRoad' &
git clone https://github.com/cyclosm/cyclosm-cartocss-style '/storage/nvme5/new_clones/CartoCSS/cyclosm-cartocss-style' &
git clone https://github.com/CartoDB/basemap-styles '/storage/nvme5/new_clones/CartoCSS/basemap-styles' &
git clone https://github.com/klokantech/vector-tiles-sample '/storage/nvme5/new_clones/CartoCSS/vector-tiles-sample' &
git clone https://github.com/stamen/terrain-classic '/storage/nvme5/new_clones/CartoCSS/terrain-classic' &
git clone https://github.com/hotosm/HDM-CartoCSS '/storage/nvme5/new_clones/CartoCSS/HDM-CartoCSS' &
git clone https://github.com/aaronlidman/Toner-for-Tilemill '/storage/nvme5/new_clones/CartoCSS/Toner-for-Tilemill' &
git clone https://github.com/CartoDB/CartoDB-basemaps '/storage/nvme5/new_clones/CartoCSS/CartoDB-basemaps' &
git clone https://github.com/codeforamerica/Transit-Map-in-TileMill '/storage/nvme5/new_clones/CartoCSS/Transit-Map-in-TileMill' &
git clone https://github.com/mapbox/mapbox-studio-osm-bright.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-osm-bright.tm2' &
git clone https://github.com/stamen/spatial-dataviz-for-data-scientists '/storage/nvme5/new_clones/CartoCSS/spatial-dataviz-for-data-scientists' &
git clone https://github.com/lyrk/lyrk-mapstyle '/storage/nvme5/new_clones/CartoCSS/lyrk-mapstyle' &
git clone https://github.com/ajashton/pirate-map '/storage/nvme5/new_clones/CartoCSS/pirate-map' &
git clone https://github.com/andrewharvey/osm-hybrid-carto '/storage/nvme5/new_clones/CartoCSS/osm-hybrid-carto' &
git clone https://github.com/mapbox/mapbox-studio-emerald.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-emerald.tm2' &
git clone https://github.com/nobohan/OpenArdenneMap '/storage/nvme5/new_clones/CartoCSS/OpenArdenneMap' &
git clone https://github.com/tilery/OpenRiverboatMap '/storage/nvme5/new_clones/CartoCSS/OpenRiverboatMap' &
git clone https://github.com/tilery/pianoforte '/storage/nvme5/new_clones/CartoCSS/pianoforte' &
git clone https://github.com/mapbox/super-mario-world.tm2 '/storage/nvme5/new_clones/CartoCSS/super-mario-world.tm2' &
git clone https://github.com/wboykinm/redlines '/storage/nvme5/new_clones/CartoCSS/redlines' &
git clone https://github.com/yohanboniface/thank-you-map '/storage/nvme5/new_clones/CartoCSS/thank-you-map' &
git clone https://github.com/xyztobixyz/OSM-Swiss-Style '/storage/nvme5/new_clones/CartoCSS/OSM-Swiss-Style' &
git clone https://github.com/osmlab/mapbox-studio-humanitarian-print.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-humanitarian-print.tm2' &
git clone https://github.com/mapbox/mapbox-studio-satellite-outdoors.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-satellite-outdoors.tm2' &
git clone https://github.com/Zverik/veloroad '/storage/nvme5/new_clones/CartoCSS/veloroad' &
git clone https://github.com/karlwettin/carto-style-hydda '/storage/nvme5/new_clones/CartoCSS/carto-style-hydda' &
git clone https://github.com/mapbox/mapbox-studio-outdoors.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-outdoors.tm2' &
git clone https://github.com/geografa/orienteering.tm2 '/storage/nvme5/new_clones/CartoCSS/orienteering.tm2' &
git clone https://github.com/e-n-f/geotaggers '/storage/nvme5/new_clones/CartoCSS/geotaggers' &
git clone https://github.com/cyberang3l/osm-maps '/storage/nvme5/new_clones/CartoCSS/osm-maps' &
git clone https://github.com/mapbox/mapbox-studio-woodcut.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-woodcut.tm2' &
git clone https://github.com/Jauntful/jauntful_map.tm2 '/storage/nvme5/new_clones/CartoCSS/jauntful_map.tm2' &
git clone https://github.com/yogiks/osm-kn '/storage/nvme5/new_clones/CartoCSS/osm-kn' &
git clone https://github.com/OpenSnowMap-org/mapnik-opensnowmap.org '/storage/nvme5/new_clones/CartoCSS/mapnik-opensnowmap.org' &
git clone https://github.com/jonahadkins/weekendupdate '/storage/nvme5/new_clones/CartoCSS/weekendupdate' &
git clone https://github.com/AmericanRedCross/hdm-style.tm2 '/storage/nvme5/new_clones/CartoCSS/hdm-style.tm2' &
git clone https://github.com/reznikmm/ada-auth '/storage/nvme5/new_clones/CartoCSS/ada-auth' &
git clone https://github.com/MapSurferNET/MapSurfer.NET-Examples '/storage/nvme5/new_clones/CartoCSS/MapSurfer.NET-Examples' &
git clone https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT '/storage/nvme5/new_clones/CartoCSS/openstreetmap-carto-AJT' &
git clone https://github.com/mapbox/mapbox-studio-pencil.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-pencil.tm2' &
git clone https://github.com/posm/posm-carto '/storage/nvme5/new_clones/CartoCSS/posm-carto' &
git clone https://github.com/chelm/geodata '/storage/nvme5/new_clones/CartoCSS/geodata' &
git clone https://github.com/alexanno/kartkompetanse '/storage/nvme5/new_clones/CartoCSS/kartkompetanse' &
git clone https://github.com/devonzuegel/cs224w '/storage/nvme5/new_clones/CartoCSS/cs224w' &
git clone https://github.com/mbta/tile-server '/storage/nvme5/new_clones/CartoCSS/tile-server' &
git clone https://github.com/datadesk/osm-silent-la '/storage/nvme5/new_clones/CartoCSS/osm-silent-la' &
git clone https://github.com/iBurnApp/iBurn-Maps '/storage/nvme5/new_clones/CartoCSS/iBurn-Maps' &
git clone https://github.com/rinigus/mapnik-styles-sqlite '/storage/nvme5/new_clones/CartoCSS/mapnik-styles-sqlite' &
git clone https://github.com/brunob/earthquake '/storage/nvme5/new_clones/CartoCSS/earthquake' &
git clone https://github.com/buger404/Moristory '/storage/nvme5/new_clones/CartoCSS/Moristory' &
git clone https://github.com/geofabrik/shortbread-mapnik '/storage/nvme5/new_clones/CartoCSS/shortbread-mapnik' &
git clone https://github.com/mapbox/mapbox-studio-wheatpaste.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-wheatpaste.tm2' &
git clone https://github.com/ClearTables/osm-clear '/storage/nvme5/new_clones/CartoCSS/osm-clear' &
git clone https://github.com/kartotherian/brighmed '/storage/nvme5/new_clones/CartoCSS/brighmed' &
git clone https://github.com/mapbox/mapbox-studio-mars-terrain.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-mars-terrain.tm2' &
git clone https://github.com/linz/linz_basemaps '/storage/nvme5/new_clones/CartoCSS/linz_basemaps' &
git clone https://github.com/mapbox/mapbox-studio-pirates.tm2 '/storage/nvme5/new_clones/CartoCSS/mapbox-studio-pirates.tm2' &
