#!/bin/bash

git clone https://github.com/fabiomsr/from-java-to-kotlin '/storage/nvme5/new_clones/Cirru/from-java-to-kotlin' &
git clone https://github.com/Respo/respo.cljs '/storage/nvme5/new_clones/Cirru/respo.cljs' &
git clone https://github.com/Cirru/calcit-editor '/storage/nvme5/new_clones/Cirru/calcit-editor' &
git clone https://github.com/tiye/swift-is-like-go '/storage/nvme5/new_clones/Cirru/swift-is-like-go' &
git clone https://github.com/Cirru/stack-editor '/storage/nvme5/new_clones/Cirru/stack-editor' &
git clone https://github.com/Quamolit/quamolit.cljs '/storage/nvme5/new_clones/Cirru/quamolit.cljs' &
git clone https://github.com/Cirru/respo-cirru-editor.cljs '/storage/nvme5/new_clones/Cirru/respo-cirru-editor.cljs' &
git clone https://github.com/Cirru/sepal.clj '/storage/nvme5/new_clones/Cirru/sepal.clj' &
git clone https://github.com/Cirru/cirru-script-editor '/storage/nvme5/new_clones/Cirru/cirru-script-editor' &
git clone https://github.com/calcit-lang/editor '/storage/nvme5/new_clones/Cirru/editor' &
git clone https://github.com/Memkits/react-todolist '/storage/nvme5/new_clones/Cirru/react-todolist' &
git clone https://github.com/Cirru/hovenia-editor '/storage/nvme5/new_clones/Cirru/hovenia-editor' &
git clone https://github.com/Cirru/jiuzhang-lang '/storage/nvme5/new_clones/Cirru/jiuzhang-lang' &
git clone https://github.com/Phlox-GL/phlox.cljs '/storage/nvme5/new_clones/Cirru/phlox.cljs' &
git clone https://github.com/mvc-works/calcit-workflow '/storage/nvme5/new_clones/Cirru/calcit-workflow' &
git clone https://github.com/Memkits/pudica-schedule '/storage/nvme5/new_clones/Cirru/pudica-schedule' &
git clone https://github.com/Cirru/text.cirru.org '/storage/nvme5/new_clones/Cirru/text.cirru.org' &
git clone https://github.com/fp-china/fp-china.org '/storage/nvme5/new_clones/Cirru/fp-china.org' &
git clone https://github.com/react-china/collections '/storage/nvme5/new_clones/Cirru/collections' &
git clone https://github.com/Cumulo/cumulo-workflow '/storage/nvme5/new_clones/Cirru/cumulo-workflow' &
git clone https://github.com/mvc-works/lilac '/storage/nvme5/new_clones/Cirru/lilac' &
git clone https://github.com/mvc-works/cirruscript-workflow '/storage/nvme5/new_clones/Cirru/cirruscript-workflow' &
git clone https://github.com/Triadica/triadica-space '/storage/nvme5/new_clones/Cirru/triadica-space' &
git clone https://github.com/Termina/termina '/storage/nvme5/new_clones/Cirru/termina' &
git clone https://github.com/Memkits/hn-reader '/storage/nvme5/new_clones/Cirru/hn-reader' &
git clone https://github.com/Cirru/scirpus '/storage/nvme5/new_clones/Cirru/scirpus' &
git clone https://github.com/Termina/tab-searching '/storage/nvme5/new_clones/Cirru/tab-searching' &
git clone https://github.com/clojure-china/clojure-script.org '/storage/nvme5/new_clones/Cirru/clojure-script.org' &
git clone https://github.com/Quatrefoil-GL/quatrefoil.cljs '/storage/nvme5/new_clones/Cirru/quatrefoil.cljs' &
git clone https://github.com/mvc-works/edn-formatter '/storage/nvme5/new_clones/Cirru/edn-formatter' &
git clone https://github.com/Lumo/lumo-cljs.org '/storage/nvme5/new_clones/Cirru/lumo-cljs.org' &
git clone https://github.com/TopixIM/woodenlist '/storage/nvme5/new_clones/Cirru/woodenlist' &
git clone https://github.com/Memkits/wanderlist '/storage/nvme5/new_clones/Cirru/wanderlist' &
git clone https://github.com/Memkits/markdown-editor '/storage/nvme5/new_clones/Cirru/markdown-editor' &
