#!/bin/bash

git clone https://github.com/framework-one/fw1 '/storage/nvme5/new_clones/ColdFusion/fw1' &
git clone https://github.com/ColdBox/coldbox-platform '/storage/nvme5/new_clones/ColdFusion/coldbox-platform' &
git clone https://github.com/atuttle/Taffy '/storage/nvme5/new_clones/ColdFusion/Taffy' &
git clone https://github.com/cfwheels/cfwheels '/storage/nvme5/new_clones/ColdFusion/cfwheels' &
git clone https://github.com/foundeo/cfdocs '/storage/nvme5/new_clones/ColdFusion/cfdocs' &
git clone https://github.com/razuna/razuna '/storage/nvme5/new_clones/ColdFusion/razuna' &
git clone https://github.com/oarevalo/BugLogHQ '/storage/nvme5/new_clones/ColdFusion/BugLogHQ' &
git clone https://github.com/Ortus-Solutions/commandbox '/storage/nvme5/new_clones/ColdFusion/commandbox' &
git clone https://github.com/cfsimplicity/spreadsheet-cfml '/storage/nvme5/new_clones/ColdFusion/spreadsheet-cfml' &
git clone https://github.com/Ortus-Solutions/ContentBox '/storage/nvme5/new_clones/ColdFusion/ContentBox' &
git clone https://github.com/aarongreenlee/Hoth '/storage/nvme5/new_clones/ColdFusion/Hoth' &
git clone https://github.com/framework-one/di1 '/storage/nvme5/new_clones/ColdFusion/di1' &
git clone https://github.com/teamcfadvance/cfstatic '/storage/nvme5/new_clones/ColdFusion/cfstatic' &
git clone https://github.com/coldfumonkeh/oauth2 '/storage/nvme5/new_clones/ColdFusion/oauth2' &
git clone https://github.com/Mach-II/Mach-II-Framework '/storage/nvme5/new_clones/ColdFusion/Mach-II-Framework' &
git clone https://github.com/ghidinelli/cfpayment '/storage/nvme5/new_clones/ColdFusion/cfpayment' &
git clone https://github.com/russplaysguitar/UnderscoreCF '/storage/nvme5/new_clones/ColdFusion/UnderscoreCF' &
git clone https://github.com/mxunit/mxunit '/storage/nvme5/new_clones/ColdFusion/mxunit' &
git clone https://github.com/lucee/lucee-dockerfiles '/storage/nvme5/new_clones/ColdFusion/lucee-dockerfiles' &
git clone https://github.com/TheRealAgentK/facebook-cf-sdk '/storage/nvme5/new_clones/ColdFusion/facebook-cf-sdk' &
git clone https://github.com/teamcfadvance/CFSelenium '/storage/nvme5/new_clones/ColdFusion/CFSelenium' &
git clone https://github.com/jeffdupont/bootstrap-data-table '/storage/nvme5/new_clones/ColdFusion/bootstrap-data-table' &
git clone https://github.com/jcberquist/aws-cfml '/storage/nvme5/new_clones/ColdFusion/aws-cfml' &
git clone https://github.com/simonbingham/xindi '/storage/nvme5/new_clones/ColdFusion/xindi' &
git clone https://github.com/Ortus-Solutions/TestBox '/storage/nvme5/new_clones/ColdFusion/TestBox' &
git clone https://github.com/jcberquist/stripe-cfml '/storage/nvme5/new_clones/ColdFusion/stripe-cfml' &
git clone https://github.com/markmandel/JavaLoader '/storage/nvme5/new_clones/ColdFusion/JavaLoader' &
git clone https://github.com/bennadel/JSONWebTokens.cfc '/storage/nvme5/new_clones/ColdFusion/JSONWebTokens.cfc' &
git clone https://github.com/CFCommunity/CFScript-Community-Components '/storage/nvme5/new_clones/ColdFusion/CFScript-Community-Components' &
git clone https://github.com/nodoherty/ColdFusion-Koans '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Koans' &
git clone https://github.com/marcins/cf-google-authenticator '/storage/nvme5/new_clones/ColdFusion/cf-google-authenticator' &
git clone https://github.com/misterdai/cftracker '/storage/nvme5/new_clones/ColdFusion/cftracker' &
git clone https://github.com/carehart/awesome-cf-compose '/storage/nvme5/new_clones/ColdFusion/awesome-cf-compose' &
git clone https://github.com/pmcelhaney/Mustache.cfc '/storage/nvme5/new_clones/ColdFusion/Mustache.cfc' &
git clone https://github.com/bennadel/JsonSerializer.cfc '/storage/nvme5/new_clones/ColdFusion/JsonSerializer.cfc' &
git clone https://github.com/AlumnIQ/momentcfc '/storage/nvme5/new_clones/ColdFusion/momentcfc' &
git clone https://github.com/teamcfadvance/ValidateThis '/storage/nvme5/new_clones/ColdFusion/ValidateThis' &
git clone https://github.com/markmandel/ColdDoc '/storage/nvme5/new_clones/ColdFusion/ColdDoc' &
git clone https://github.com/abramadams/dao '/storage/nvme5/new_clones/ColdFusion/dao' &
git clone https://github.com/fusebox-framework/Fusebox-ColdFusion '/storage/nvme5/new_clones/ColdFusion/Fusebox-ColdFusion' &
git clone https://github.com/coldfumonkeh/cfml-ci '/storage/nvme5/new_clones/ColdFusion/cfml-ci' &
git clone https://github.com/jsteinshouer/cf-jwt-simple '/storage/nvme5/new_clones/ColdFusion/cf-jwt-simple' &
git clone https://github.com/coldbox-modules/qb '/storage/nvme5/new_clones/ColdFusion/qb' &
git clone https://github.com/virtix/cfmongodb '/storage/nvme5/new_clones/ColdFusion/cfmongodb' &
git clone https://github.com/mikesprague/vagrant-lemtl '/storage/nvme5/new_clones/ColdFusion/vagrant-lemtl' &
git clone https://github.com/markmandel/coldspring '/storage/nvme5/new_clones/ColdFusion/coldspring' &
git clone https://github.com/paypal/tech-talks '/storage/nvme5/new_clones/ColdFusion/tech-talks' &
git clone https://github.com/brianklaas/awsPlaybox '/storage/nvme5/new_clones/ColdFusion/awsPlaybox' &
git clone https://github.com/foundeo/cfml-security '/storage/nvme5/new_clones/ColdFusion/cfml-security' &
git clone https://github.com/jeisenlo/ColdFusion-Stripe-CFC '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Stripe-CFC' &
git clone https://github.com/nomadinjax/esapi4cf '/storage/nvme5/new_clones/ColdFusion/esapi4cf' &
git clone https://github.com/jcberquist/jwt-cfml '/storage/nvme5/new_clones/ColdFusion/jwt-cfml' &
git clone https://github.com/markmandel/Sesame '/storage/nvme5/new_clones/ColdFusion/Sesame' &
git clone https://github.com/bennadel/POIUtility.cfc '/storage/nvme5/new_clones/ColdFusion/POIUtility.cfc' &
git clone https://github.com/jasonfill/ColdFusion-ElasticSearch-Client '/storage/nvme5/new_clones/ColdFusion/ColdFusion-ElasticSearch-Client' &
git clone https://github.com/danvega/hyrule '/storage/nvme5/new_clones/ColdFusion/hyrule' &
git clone https://github.com/virtix/mxunit '/storage/nvme5/new_clones/ColdFusion/mxunit' &
git clone https://github.com/mschierberl/varscoper '/storage/nvme5/new_clones/ColdFusion/varscoper' &
git clone https://github.com/ddspringle/framework-one-secure-auth '/storage/nvme5/new_clones/ColdFusion/framework-one-secure-auth' &
git clone https://github.com/marcesher/cfconcurrent '/storage/nvme5/new_clones/ColdFusion/cfconcurrent' &
git clone https://github.com/camerahacks/canon-api '/storage/nvme5/new_clones/ColdFusion/canon-api' &
git clone https://github.com/teamcfadvance/BlogCFC5 '/storage/nvme5/new_clones/ColdFusion/BlogCFC5' &
git clone https://github.com/foundeo/bolthttp '/storage/nvme5/new_clones/ColdFusion/bolthttp' &
git clone https://github.com/s992/chromelogger-cf '/storage/nvme5/new_clones/ColdFusion/chromelogger-cf' &
git clone https://github.com/foundeo/cfml-security-training '/storage/nvme5/new_clones/ColdFusion/cfml-security-training' &
git clone https://github.com/coldbox-modules/cbwire '/storage/nvme5/new_clones/ColdFusion/cbwire' &
git clone https://github.com/wellercs/CodeChecker '/storage/nvme5/new_clones/ColdFusion/CodeChecker' &
git clone https://github.com/PAWECOGmbH/saaster '/storage/nvme5/new_clones/ColdFusion/saaster' &
git clone https://github.com/misterdai/cfbackport '/storage/nvme5/new_clones/ColdFusion/cfbackport' &
git clone https://github.com/stevewithington/MuraFW1 '/storage/nvme5/new_clones/ColdFusion/MuraFW1' &
git clone https://github.com/mjclemente/sendgrid.cfc '/storage/nvme5/new_clones/ColdFusion/sendgrid.cfc' &
git clone https://github.com/dswitzer/hashids.coldfusion '/storage/nvme5/new_clones/ColdFusion/hashids.coldfusion' &
git clone https://github.com/russjohnson/SplashCMS '/storage/nvme5/new_clones/ColdFusion/SplashCMS' &
git clone https://github.com/mso-net/lucee-aws '/storage/nvme5/new_clones/ColdFusion/lucee-aws' &
git clone https://github.com/CFCommunity/ramen '/storage/nvme5/new_clones/ColdFusion/ramen' &
git clone https://github.com/ColdBox/coldbox-zero-to-hero '/storage/nvme5/new_clones/ColdFusion/coldbox-zero-to-hero' &
git clone https://github.com/Leftbower/cfspreadsheet-lucee-5 '/storage/nvme5/new_clones/ColdFusion/cfspreadsheet-lucee-5' &
git clone https://github.com/MWers/cfredis '/storage/nvme5/new_clones/ColdFusion/cfredis' &
git clone https://github.com/mjclemente/pdfbox.cfc '/storage/nvme5/new_clones/ColdFusion/pdfbox.cfc' &
git clone https://github.com/teamcfadvance/cfspreadsheet-railo '/storage/nvme5/new_clones/ColdFusion/cfspreadsheet-railo' &
git clone https://github.com/GiancarloGomez/ColdFusion-OneLogin '/storage/nvme5/new_clones/ColdFusion/ColdFusion-OneLogin' &
git clone https://github.com/coldbox-modules/quick '/storage/nvme5/new_clones/ColdFusion/quick' &
git clone https://github.com/cfmaniac/CF-CertMan '/storage/nvme5/new_clones/ColdFusion/CF-CertMan' &
git clone https://github.com/jcberquist/commandbox-cfformat '/storage/nvme5/new_clones/ColdFusion/commandbox-cfformat' &
git clone https://github.com/abitdodgy/cfw-usermanager '/storage/nvme5/new_clones/ColdFusion/cfw-usermanager' &
git clone https://github.com/jasonfill/ColdFusion-Twilio-Library '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Twilio-Library' &
git clone https://github.com/jfrux/oauth2.cfc '/storage/nvme5/new_clones/ColdFusion/oauth2.cfc' &
git clone https://github.com/coldbox-modules/hyper '/storage/nvme5/new_clones/ColdFusion/hyper' &
git clone https://github.com/timsayshey/wheelie '/storage/nvme5/new_clones/ColdFusion/wheelie' &
git clone https://github.com/isapir/lucee-docker '/storage/nvme5/new_clones/ColdFusion/lucee-docker' &
git clone https://github.com/NathanStrutz/CFML-Complexity-Metric-Tool '/storage/nvme5/new_clones/ColdFusion/CFML-Complexity-Metric-Tool' &
git clone https://github.com/cfchris/Relaxation '/storage/nvme5/new_clones/ColdFusion/Relaxation' &
git clone https://github.com/adamcameron/cfml24h '/storage/nvme5/new_clones/ColdFusion/cfml24h' &
git clone https://github.com/dhumphreys/cfwheels-coldroute '/storage/nvme5/new_clones/ColdFusion/cfwheels-coldroute' &
git clone https://github.com/tdm00/cfwheels-dbmigrate-plugin '/storage/nvme5/new_clones/ColdFusion/cfwheels-dbmigrate-plugin' &
git clone https://github.com/philcruz/Stripe.cfc '/storage/nvme5/new_clones/ColdFusion/Stripe.cfc' &
git clone https://github.com/modelglue/modelglue-framework '/storage/nvme5/new_clones/ColdFusion/modelglue-framework' &
git clone https://github.com/coldbox-samples/coldbox-samples '/storage/nvme5/new_clones/ColdFusion/coldbox-samples' &
git clone https://github.com/framework-one/cfmljure '/storage/nvme5/new_clones/ColdFusion/cfmljure' &
git clone https://github.com/lmajano/messaging-polyglot '/storage/nvme5/new_clones/ColdFusion/messaging-polyglot' &
git clone https://github.com/bennadel/MVC-Learning '/storage/nvme5/new_clones/ColdFusion/MVC-Learning' &
git clone https://github.com/Ortus-Solutions/cfconfig '/storage/nvme5/new_clones/ColdFusion/cfconfig' &
git clone https://github.com/ryanguill/emit '/storage/nvme5/new_clones/ColdFusion/emit' &
git clone https://github.com/timblair/restfulcf '/storage/nvme5/new_clones/ColdFusion/restfulcf' &
git clone https://github.com/cfwheels/cfwheels-example-app '/storage/nvme5/new_clones/ColdFusion/cfwheels-example-app' &
git clone https://github.com/coldbox-modules/sentry '/storage/nvme5/new_clones/ColdFusion/sentry' &
git clone https://github.com/coldfumonkeh/oauth2server '/storage/nvme5/new_clones/ColdFusion/oauth2server' &
git clone https://github.com/cfsimplicity/AdaptiveImages '/storage/nvme5/new_clones/ColdFusion/AdaptiveImages' &
git clone https://github.com/bennadel/Pusher.cfc '/storage/nvme5/new_clones/ColdFusion/Pusher.cfc' &
git clone https://github.com/jalpino/collections '/storage/nvme5/new_clones/ColdFusion/collections' &
git clone https://github.com/RickGroenewegen/pusher '/storage/nvme5/new_clones/ColdFusion/pusher' &
git clone https://github.com/rickosborne/rickosborne '/storage/nvme5/new_clones/ColdFusion/rickosborne' &
git clone https://github.com/boltz/CFShorty '/storage/nvme5/new_clones/ColdFusion/CFShorty' &
git clone https://github.com/kwaschny/cf_dump '/storage/nvme5/new_clones/ColdFusion/cf_dump' &
git clone https://github.com/dominknow/powernap '/storage/nvme5/new_clones/ColdFusion/powernap' &
git clone https://github.com/rip747/TimeZone-CFC '/storage/nvme5/new_clones/ColdFusion/TimeZone-CFC' &
git clone https://github.com/tpryan/Apptacular '/storage/nvme5/new_clones/ColdFusion/Apptacular' &
git clone https://github.com/boltz/QRToad '/storage/nvme5/new_clones/ColdFusion/QRToad' &
git clone https://github.com/andyj/CFTextMate '/storage/nvme5/new_clones/ColdFusion/CFTextMate' &
git clone https://github.com/coldbox-modules/cbsecurity '/storage/nvme5/new_clones/ColdFusion/cbsecurity' &
git clone https://github.com/coreybutler/cfamazon '/storage/nvme5/new_clones/ColdFusion/cfamazon' &
git clone https://github.com/bennadel/Crypto.cfc '/storage/nvme5/new_clones/ColdFusion/Crypto.cfc' &
git clone https://github.com/Ortus-Solutions/cfcouchbase-sdk '/storage/nvme5/new_clones/ColdFusion/cfcouchbase-sdk' &
git clone https://github.com/GiancarloGomez/sentry-cfml '/storage/nvme5/new_clones/ColdFusion/sentry-cfml' &
git clone https://github.com/pixl8/sticker '/storage/nvme5/new_clones/ColdFusion/sticker' &
git clone https://github.com/MotorsportReg/sidecar '/storage/nvme5/new_clones/ColdFusion/sidecar' &
git clone https://github.com/bennadel/CFHTTPSession.cfc '/storage/nvme5/new_clones/ColdFusion/CFHTTPSession.cfc' &
git clone https://github.com/iknowkungfoo/cfquery-to-json '/storage/nvme5/new_clones/ColdFusion/cfquery-to-json' &
git clone https://github.com/foundeo/cfml-ci-examples '/storage/nvme5/new_clones/ColdFusion/cfml-ci-examples' &
git clone https://github.com/simonfree/cfAWSWrapper '/storage/nvme5/new_clones/ColdFusion/cfAWSWrapper' &
git clone https://github.com/pirategaspard/cftag2cfscript '/storage/nvme5/new_clones/ColdFusion/cftag2cfscript' &
git clone https://github.com/LoicMahieu/cf-wkhtmltopdf '/storage/nvme5/new_clones/ColdFusion/cf-wkhtmltopdf' &
git clone https://github.com/coldfumonkeh/GoogleAnalytics '/storage/nvme5/new_clones/ColdFusion/GoogleAnalytics' &
git clone https://github.com/dhumphreys/cfrel '/storage/nvme5/new_clones/ColdFusion/cfrel' &
git clone https://github.com/jmacul2/raven-cfml '/storage/nvme5/new_clones/ColdFusion/raven-cfml' &
git clone https://github.com/cfsilence/SlideSix '/storage/nvme5/new_clones/ColdFusion/SlideSix' &
git clone https://github.com/Ortus-Solutions/commandbox-cfconfig '/storage/nvme5/new_clones/ColdFusion/commandbox-cfconfig' &
git clone https://github.com/QuackFuzed/cfUniForm '/storage/nvme5/new_clones/ColdFusion/cfUniForm' &
git clone https://github.com/bennadel/Best-Of-ColdFusion-10 '/storage/nvme5/new_clones/ColdFusion/Best-Of-ColdFusion-10' &
git clone https://github.com/denuno/cfjasperreport '/storage/nvme5/new_clones/ColdFusion/cfjasperreport' &
git clone https://github.com/framework-one/aop1 '/storage/nvme5/new_clones/ColdFusion/aop1' &
git clone https://github.com/sebtools/Video-Converter '/storage/nvme5/new_clones/ColdFusion/Video-Converter' &
git clone https://github.com/bdcravens/railo-vagrant '/storage/nvme5/new_clones/ColdFusion/railo-vagrant' &
git clone https://github.com/bennadel/TinyTest '/storage/nvme5/new_clones/ColdFusion/TinyTest' &
git clone https://github.com/GiancarloGomez/ColdFusion-Realtime-With-WebSockets-Demo-Code '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Realtime-With-WebSockets-Demo-Code' &
git clone https://github.com/coldbox-modules/relax '/storage/nvme5/new_clones/ColdFusion/relax' &
git clone https://github.com/GiancarloGomez/ColdFusion-Realtime-With-WebSockets '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Realtime-With-WebSockets' &
git clone https://github.com/ColdBox/coldbox-sublime '/storage/nvme5/new_clones/ColdFusion/coldbox-sublime' &
git clone https://github.com/coldbox-modules/totp '/storage/nvme5/new_clones/ColdFusion/totp' &
git clone https://github.com/TezosRio/taps '/storage/nvme5/new_clones/ColdFusion/taps' &
git clone https://github.com/MitrahSoft/lucee-cfpdfform '/storage/nvme5/new_clones/ColdFusion/lucee-cfpdfform' &
git clone https://github.com/quetwo/railoWebSocketServer '/storage/nvme5/new_clones/ColdFusion/railoWebSocketServer' &
git clone https://github.com/coldbox-modules/cbvalidation '/storage/nvme5/new_clones/ColdFusion/cbvalidation' &
git clone https://github.com/raulriera/Remote-Form-Helpers '/storage/nvme5/new_clones/ColdFusion/Remote-Form-Helpers' &
git clone https://github.com/cfjedimaster/ColdFusion-Blog-Aggregator '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Blog-Aggregator' &
git clone https://github.com/grantcopley/cbwire-examples '/storage/nvme5/new_clones/ColdFusion/cbwire-examples' &
git clone https://github.com/rip747/cfml-liquid '/storage/nvme5/new_clones/ColdFusion/cfml-liquid' &
git clone https://github.com/tfoston/HubSpotMasterClass1 '/storage/nvme5/new_clones/ColdFusion/HubSpotMasterClass1' &
git clone https://github.com/gpickin/itb2020-fluentAPI '/storage/nvme5/new_clones/ColdFusion/itb2020-fluentAPI' &
git clone https://github.com/exercism/cfml '/storage/nvme5/new_clones/ColdFusion/cfml' &
git clone https://github.com/andreacfm/Redis-Cache-Extension '/storage/nvme5/new_clones/ColdFusion/Redis-Cache-Extension' &
git clone https://github.com/lmajano/to-the-future-with-cbFutures '/storage/nvme5/new_clones/ColdFusion/to-the-future-with-cbFutures' &
git clone https://github.com/coldbox-modules/s3sdk '/storage/nvme5/new_clones/ColdFusion/s3sdk' &
git clone https://github.com/Tropicalista/lucee-cfimap '/storage/nvme5/new_clones/ColdFusion/lucee-cfimap' &
git clone https://github.com/coldbox-modules/cffractal '/storage/nvme5/new_clones/ColdFusion/cffractal' &
git clone https://github.com/tonynelson19/ColdMVC '/storage/nvme5/new_clones/ColdFusion/ColdMVC' &
git clone https://github.com/timblair/coldfusion-airbrake-notifier '/storage/nvme5/new_clones/ColdFusion/coldfusion-airbrake-notifier' &
git clone https://github.com/henrylearn2rock/MongoCFC '/storage/nvme5/new_clones/ColdFusion/MongoCFC' &
git clone https://github.com/Pashkela/Cfm_Shell_v3.0_edition '/storage/nvme5/new_clones/ColdFusion/Cfm_Shell_v3.0_edition' &
git clone https://github.com/coldbox-modules/cbi18n '/storage/nvme5/new_clones/ColdFusion/cbi18n' &
git clone https://github.com/robrohan/coldfusion.tmbundle '/storage/nvme5/new_clones/ColdFusion/coldfusion.tmbundle' &
git clone https://github.com/OpenBD/openbd-administrator '/storage/nvme5/new_clones/ColdFusion/openbd-administrator' &
git clone https://github.com/blueriver/MuraUserBridge '/storage/nvme5/new_clones/ColdFusion/MuraUserBridge' &
git clone https://github.com/coldbox-modules/cbSwagger '/storage/nvme5/new_clones/ColdFusion/cbSwagger' &
git clone https://github.com/coldbox-modules/cbdebugger '/storage/nvme5/new_clones/ColdFusion/cbdebugger' &
git clone https://github.com/abramadams/wkhtml '/storage/nvme5/new_clones/ColdFusion/wkhtml' &
git clone https://github.com/cfmlprojects/cfssh '/storage/nvme5/new_clones/ColdFusion/cfssh' &
git clone https://github.com/henrylearn2rock/jQuery-File-Upload-CFC '/storage/nvme5/new_clones/ColdFusion/jQuery-File-Upload-CFC' &
git clone https://github.com/MindscapeHQ/raygun4cfml '/storage/nvme5/new_clones/ColdFusion/raygun4cfml' &
git clone https://github.com/Ortus-Solutions/firstDockerCompose '/storage/nvme5/new_clones/ColdFusion/firstDockerCompose' &
git clone https://github.com/andyj/FW-1-Security-Models '/storage/nvme5/new_clones/ColdFusion/FW-1-Security-Models' &
git clone https://github.com/seancorfield/ring-cfml '/storage/nvme5/new_clones/ColdFusion/ring-cfml' &
git clone https://github.com/bennadel/ColdFusion-JRegEx '/storage/nvme5/new_clones/ColdFusion/ColdFusion-JRegEx' &
git clone https://github.com/zefer/Combine '/storage/nvme5/new_clones/ColdFusion/Combine' &
git clone https://github.com/gregmoser/docker-lucee-mysql '/storage/nvme5/new_clones/ColdFusion/docker-lucee-mysql' &
git clone https://github.com/lucee/lucee-heroku '/storage/nvme5/new_clones/ColdFusion/lucee-heroku' &
git clone https://github.com/coldbox-modules/cfmigrations '/storage/nvme5/new_clones/ColdFusion/cfmigrations' &
git clone https://github.com/foundrycf/foundry '/storage/nvme5/new_clones/ColdFusion/foundry' &
git clone https://github.com/framework-one/fw1-commands '/storage/nvme5/new_clones/ColdFusion/fw1-commands' &
git clone https://github.com/sneiland/Crash-Course-In-MVC-With-FW-1 '/storage/nvme5/new_clones/ColdFusion/Crash-Course-In-MVC-With-FW-1' &
git clone https://github.com/GiancarloGomez/ColdFusion-MobileDetect '/storage/nvme5/new_clones/ColdFusion/ColdFusion-MobileDetect' &
git clone https://github.com/Fusegrid/fusegrid-sdk '/storage/nvme5/new_clones/ColdFusion/fusegrid-sdk' &
git clone https://github.com/mjclemente/mailgun.cfc '/storage/nvme5/new_clones/ColdFusion/mailgun.cfc' &
git clone https://github.com/pacificamitos/supermodel '/storage/nvme5/new_clones/ColdFusion/supermodel' &
git clone https://github.com/tonyjunkes/BCryptCFC '/storage/nvme5/new_clones/ColdFusion/BCryptCFC' &
git clone https://github.com/andreacfm/WebSocket-Gateway-Extension '/storage/nvme5/new_clones/ColdFusion/WebSocket-Gateway-Extension' &
git clone https://github.com/ksaini/Rancho_CFB '/storage/nvme5/new_clones/ColdFusion/Rancho_CFB' &
git clone https://github.com/gregmoser/MuraHoth '/storage/nvme5/new_clones/ColdFusion/MuraHoth' &
git clone https://github.com/DominicWatson/cfmailgun '/storage/nvme5/new_clones/ColdFusion/cfmailgun' &
git clone https://github.com/joelhill/cfScribe '/storage/nvme5/new_clones/ColdFusion/cfScribe' &
git clone https://github.com/rodionbykov/coldfusion-minute '/storage/nvme5/new_clones/ColdFusion/coldfusion-minute' &
git clone https://github.com/designfrontier/TokenizerCFC '/storage/nvme5/new_clones/ColdFusion/TokenizerCFC' &
git clone https://github.com/raulriera/Scaffold '/storage/nvme5/new_clones/ColdFusion/Scaffold' &
git clone https://github.com/DominicWatson/travis-testbox-skeleton '/storage/nvme5/new_clones/ColdFusion/travis-testbox-skeleton' &
git clone https://github.com/teamcfadvance/cfVideoScript '/storage/nvme5/new_clones/ColdFusion/cfVideoScript' &
git clone https://github.com/OrangeLark/MobileMura '/storage/nvme5/new_clones/ColdFusion/MobileMura' &
git clone https://github.com/akhil110/expensewatch-cf '/storage/nvme5/new_clones/ColdFusion/expensewatch-cf' &
git clone https://github.com/denuno/cfdistro '/storage/nvme5/new_clones/ColdFusion/cfdistro' &
git clone https://github.com/nmische/cf-ok '/storage/nvme5/new_clones/ColdFusion/cf-ok' &
git clone https://github.com/danvega/solitary '/storage/nvme5/new_clones/ColdFusion/solitary' &
git clone https://github.com/cybersonic/lucee-filecoverage-extension '/storage/nvme5/new_clones/ColdFusion/lucee-filecoverage-extension' &
git clone https://github.com/foundeo/cfml-compiler '/storage/nvme5/new_clones/ColdFusion/cfml-compiler' &
git clone https://github.com/jamiekrug/JavaLoaderFactory '/storage/nvme5/new_clones/ColdFusion/JavaLoaderFactory' &
git clone https://github.com/CFCommunity/jsonutil '/storage/nvme5/new_clones/ColdFusion/jsonutil' &
git clone https://github.com/atuttle/iQuery '/storage/nvme5/new_clones/ColdFusion/iQuery' &
git clone https://github.com/jensbits/CF-GA-service '/storage/nvme5/new_clones/ColdFusion/CF-GA-service' &
git clone https://github.com/gpickin/Coldfusion-Coldbox-Koans '/storage/nvme5/new_clones/ColdFusion/Coldfusion-Coldbox-Koans' &
git clone https://github.com/liquifusion/bootstrap-cfwheels '/storage/nvme5/new_clones/ColdFusion/bootstrap-cfwheels' &
git clone https://github.com/sebduggan/muraURLTools '/storage/nvme5/new_clones/ColdFusion/muraURLTools' &
git clone https://github.com/ksaini/Rancho_standalone '/storage/nvme5/new_clones/ColdFusion/Rancho_standalone' &
git clone https://github.com/lucee/extension-redis '/storage/nvme5/new_clones/ColdFusion/extension-redis' &
git clone https://github.com/brianklaas/ctlS3Utils '/storage/nvme5/new_clones/ColdFusion/ctlS3Utils' &
git clone https://github.com/murrah/ColdDuck '/storage/nvme5/new_clones/ColdFusion/ColdDuck' &
git clone https://github.com/andyj/CFGit '/storage/nvme5/new_clones/ColdFusion/CFGit' &
git clone https://github.com/coldbox-modules/rulebox '/storage/nvme5/new_clones/ColdFusion/rulebox' &
git clone https://github.com/chapmandu/cfwheels-htmx-crud '/storage/nvme5/new_clones/ColdFusion/cfwheels-htmx-crud' &
git clone https://github.com/cfsimplicity/luceeOsgiLoader '/storage/nvme5/new_clones/ColdFusion/luceeOsgiLoader' &
git clone https://github.com/CreativeNotice/CF-Google-Geocoding '/storage/nvme5/new_clones/ColdFusion/CF-Google-Geocoding' &
git clone https://github.com/cfvonner/Intro-to-MVC-ColdFusion '/storage/nvme5/new_clones/ColdFusion/Intro-to-MVC-ColdFusion' &
git clone https://github.com/coldbox-modules/cbmailservices '/storage/nvme5/new_clones/ColdFusion/cbmailservices' &
git clone https://github.com/ColdBox/coldbox-dashboard '/storage/nvme5/new_clones/ColdFusion/coldbox-dashboard' &
git clone https://github.com/chrisschmitz/commandbox-hostupdater '/storage/nvme5/new_clones/ColdFusion/commandbox-hostupdater' &
git clone https://github.com/gpickin/ocfm-2020-building-apis-part1 '/storage/nvme5/new_clones/ColdFusion/ocfm-2020-building-apis-part1' &
git clone https://github.com/jeffcoughlin/farcrysolrpro '/storage/nvme5/new_clones/ColdFusion/farcrysolrpro' &
git clone https://github.com/cybersonic/CFML-Mythbusters '/storage/nvme5/new_clones/ColdFusion/CFML-Mythbusters' &
git clone https://github.com/elpete/commandbox-githooks '/storage/nvme5/new_clones/ColdFusion/commandbox-githooks' &
git clone https://github.com/henrylearn2rock/BrowscapCFC '/storage/nvme5/new_clones/ColdFusion/BrowscapCFC' &
git clone https://github.com/bennadel/StringUtils.cfc '/storage/nvme5/new_clones/ColdFusion/StringUtils.cfc' &
git clone https://github.com/bennadel/AsyncTaskQueue.cfc '/storage/nvme5/new_clones/ColdFusion/AsyncTaskQueue.cfc' &
git clone https://github.com/gbuilt/railo-s3-java-api '/storage/nvme5/new_clones/ColdFusion/railo-s3-java-api' &
git clone https://github.com/johncblandii/cookingwheels '/storage/nvme5/new_clones/ColdFusion/cookingwheels' &
git clone https://github.com/blueriver/MuraSolr '/storage/nvme5/new_clones/ColdFusion/MuraSolr' &
git clone https://github.com/joedanz/cf-project-tracker '/storage/nvme5/new_clones/ColdFusion/cf-project-tracker' &
git clone https://github.com/jmohler1970/FormUtils '/storage/nvme5/new_clones/ColdFusion/FormUtils' &
git clone https://github.com/stevewithington/MuraPlugin '/storage/nvme5/new_clones/ColdFusion/MuraPlugin' &
git clone https://github.com/coldbox-modules/cbPlaywright '/storage/nvme5/new_clones/ColdFusion/cbPlaywright' &
git clone https://github.com/mikesprague/lucee5-heroku '/storage/nvme5/new_clones/ColdFusion/lucee5-heroku' &
git clone https://github.com/atuttle/CF-REST-Comparison '/storage/nvme5/new_clones/ColdFusion/CF-REST-Comparison' &
git clone https://github.com/inLeagueLLC/chartjs-cfc '/storage/nvme5/new_clones/ColdFusion/chartjs-cfc' &
git clone https://github.com/NathanStrutz/Write-LESS-CSS-Presentation-Material '/storage/nvme5/new_clones/ColdFusion/Write-LESS-CSS-Presentation-Material' &
git clone https://github.com/mjclemente/lambda.cfc '/storage/nvme5/new_clones/ColdFusion/lambda.cfc' &
git clone https://github.com/coldbox-modules/cbfs '/storage/nvme5/new_clones/ColdFusion/cbfs' &
git clone https://github.com/jlepage/cfFramework '/storage/nvme5/new_clones/ColdFusion/cfFramework' &
git clone https://github.com/DannyCork/ForecastCFML '/storage/nvme5/new_clones/ColdFusion/ForecastCFML' &
git clone https://github.com/eomedia/cfeoSocial '/storage/nvme5/new_clones/ColdFusion/cfeoSocial' &
git clone https://github.com/joedanz/cf-amazon-s3 '/storage/nvme5/new_clones/ColdFusion/cf-amazon-s3' &
git clone https://github.com/brianklaas/ctlCloudFrontUtils '/storage/nvme5/new_clones/ColdFusion/ctlCloudFrontUtils' &
git clone https://github.com/pmcelhaney/payflowpro-api-for-coldfusion '/storage/nvme5/new_clones/ColdFusion/payflowpro-api-for-coldfusion' &
git clone https://github.com/bennadel/ColdFusion-Rollout '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Rollout' &
git clone https://github.com/jensbits/Google-Analytics-Data-Export-API-with-ColdFusion '/storage/nvme5/new_clones/ColdFusion/Google-Analytics-Data-Export-API-with-ColdFusion' &
git clone https://github.com/strubenstein/RubensteinBilling '/storage/nvme5/new_clones/ColdFusion/RubensteinBilling' &
git clone https://github.com/lucee/script-runner '/storage/nvme5/new_clones/ColdFusion/script-runner' &
git clone https://github.com/JasPanesar/MuraConverter '/storage/nvme5/new_clones/ColdFusion/MuraConverter' &
git clone https://github.com/bdw429s/coldbox-legacy-app-demo '/storage/nvme5/new_clones/ColdFusion/coldbox-legacy-app-demo' &
git clone https://github.com/blambert/pusher-cfc '/storage/nvme5/new_clones/ColdFusion/pusher-cfc' &
git clone https://github.com/gregmoser/entitySmartList '/storage/nvme5/new_clones/ColdFusion/entitySmartList' &
git clone https://github.com/kabutotx/AuthNetToolsAPI '/storage/nvme5/new_clones/ColdFusion/AuthNetToolsAPI' &
git clone https://github.com/elpete/integrated '/storage/nvme5/new_clones/ColdFusion/integrated' &
git clone https://github.com/jlepage/CFQRCode '/storage/nvme5/new_clones/ColdFusion/CFQRCode' &
git clone https://github.com/timsayshey/Sublime-Text-CFWheels '/storage/nvme5/new_clones/ColdFusion/Sublime-Text-CFWheels' &
git clone https://github.com/ColdBox/depot-cbox-plugins '/storage/nvme5/new_clones/ColdFusion/depot-cbox-plugins' &
git clone https://github.com/Ortus-Solutions/REST-over-STOMP '/storage/nvme5/new_clones/ColdFusion/REST-over-STOMP' &
git clone https://github.com/ntunney/CFServant '/storage/nvme5/new_clones/ColdFusion/CFServant' &
git clone https://github.com/weejames/Facebook-Connect-Library-for-Cold-Fusion '/storage/nvme5/new_clones/ColdFusion/Facebook-Connect-Library-for-Cold-Fusion' &
git clone https://github.com/ColdBox/coldbox-platform-utilities '/storage/nvme5/new_clones/ColdFusion/coldbox-platform-utilities' &
git clone https://github.com/russplaysguitar/CouchDB-for-Coldfusion '/storage/nvme5/new_clones/ColdFusion/CouchDB-for-Coldfusion' &
git clone https://github.com/NUBIC/coldfusion-cas-client '/storage/nvme5/new_clones/ColdFusion/coldfusion-cas-client' &
git clone https://github.com/coldbox-modules/LaunchDarklySDK '/storage/nvme5/new_clones/ColdFusion/LaunchDarklySDK' &
git clone https://github.com/coldbox-modules/cbstreams '/storage/nvme5/new_clones/ColdFusion/cbstreams' &
git clone https://github.com/scottsteinbeck/json-diff '/storage/nvme5/new_clones/ColdFusion/json-diff' &
git clone https://github.com/bennadel/CFRedlock '/storage/nvme5/new_clones/ColdFusion/CFRedlock' &
git clone https://github.com/sebtools/DataMgr '/storage/nvme5/new_clones/ColdFusion/DataMgr' &
git clone https://github.com/sebtools/Neptune '/storage/nvme5/new_clones/ColdFusion/Neptune' &
git clone https://github.com/timblair/coldfusion-inflector '/storage/nvme5/new_clones/ColdFusion/coldfusion-inflector' &
git clone https://github.com/SimonHooker/lucee-promise '/storage/nvme5/new_clones/ColdFusion/lucee-promise' &
git clone https://github.com/stevewithington/MuraBanners '/storage/nvme5/new_clones/ColdFusion/MuraBanners' &
git clone https://github.com/coldbox-modules/twilio-sdk '/storage/nvme5/new_clones/ColdFusion/twilio-sdk' &
git clone https://github.com/Ortus-Solutions/commandbox-docbox '/storage/nvme5/new_clones/ColdFusion/commandbox-docbox' &
git clone https://github.com/ghidinelli/restconsumer '/storage/nvme5/new_clones/ColdFusion/restconsumer' &
git clone https://github.com/russjohnson/wheels_application_template '/storage/nvme5/new_clones/ColdFusion/wheels_application_template' &
git clone https://github.com/mjclemente/cloudflarecfc '/storage/nvme5/new_clones/ColdFusion/cloudflarecfc' &
git clone https://github.com/Ortus-Solutions/vscode-testbox '/storage/nvme5/new_clones/ColdFusion/vscode-testbox' &
git clone https://github.com/coldbox-modules/cborm '/storage/nvme5/new_clones/ColdFusion/cborm' &
git clone https://github.com/mhenke/javaloaderCFWheels '/storage/nvme5/new_clones/ColdFusion/javaloaderCFWheels' &
git clone https://github.com/inLeagueLLC/simple-cfml-complete '/storage/nvme5/new_clones/ColdFusion/simple-cfml-complete' &
git clone https://github.com/coldfumonkeh/cf_jwt '/storage/nvme5/new_clones/ColdFusion/cf_jwt' &
git clone https://github.com/bennadel/Plupload-S3-Imgix '/storage/nvme5/new_clones/ColdFusion/Plupload-S3-Imgix' &
git clone https://github.com/gregmoser/fw1AjaxAdapter '/storage/nvme5/new_clones/ColdFusion/fw1AjaxAdapter' &
git clone https://github.com/jordanclark/cfwheels-ValidatesRulesOf '/storage/nvme5/new_clones/ColdFusion/cfwheels-ValidatesRulesOf' &
git clone https://github.com/GiancarloGomez/ColdFusion-APIs-and-the-REST-is-easy '/storage/nvme5/new_clones/ColdFusion/ColdFusion-APIs-and-the-REST-is-easy' &
git clone https://github.com/robertdmunn/thumbnailmagic '/storage/nvme5/new_clones/ColdFusion/thumbnailmagic' &
git clone https://github.com/blueriver/MuraTranslations '/storage/nvme5/new_clones/ColdFusion/MuraTranslations' &
git clone https://github.com/commandbox-modules/commandbox-migrations '/storage/nvme5/new_clones/ColdFusion/commandbox-migrations' &
git clone https://github.com/XeroAPI/Xero-CFML '/storage/nvme5/new_clones/ColdFusion/Xero-CFML' &
git clone https://github.com/Ortus-Solutions/semanticVersion '/storage/nvme5/new_clones/ColdFusion/semanticVersion' &
git clone https://github.com/anujgakhar/AmazonSESCFC '/storage/nvme5/new_clones/ColdFusion/AmazonSESCFC' &
git clone https://github.com/shaynesweeney/coldfusion-routes '/storage/nvme5/new_clones/ColdFusion/coldfusion-routes' &
git clone https://github.com/andrew-dixon/cb-jwt '/storage/nvme5/new_clones/ColdFusion/cb-jwt' &
git clone https://github.com/Ortus-Solutions/up-and-running-with-quick '/storage/nvme5/new_clones/ColdFusion/up-and-running-with-quick' &
git clone https://github.com/coldbox-modules/cbelasticsearch '/storage/nvme5/new_clones/ColdFusion/cbelasticsearch' &
git clone https://github.com/finalcut/SaltAndHash '/storage/nvme5/new_clones/ColdFusion/SaltAndHash' &
git clone https://github.com/scahyono/multimodule '/storage/nvme5/new_clones/ColdFusion/multimodule' &
git clone https://github.com/bobsilverberg/MightyMock '/storage/nvme5/new_clones/ColdFusion/MightyMock' &
git clone https://github.com/iknowkungfoo/ArrayCollection '/storage/nvme5/new_clones/ColdFusion/ArrayCollection' &
git clone https://github.com/coldbox-modules/module-template '/storage/nvme5/new_clones/ColdFusion/module-template' &
git clone https://github.com/scottsteinbeck/jmespath '/storage/nvme5/new_clones/ColdFusion/jmespath' &
git clone https://github.com/jsteinshouer/commandbox-cflint '/storage/nvme5/new_clones/ColdFusion/commandbox-cflint' &
git clone https://github.com/coldbox-modules/cbantisamy '/storage/nvme5/new_clones/ColdFusion/cbantisamy' &
git clone https://github.com/bennadel/Fusion-Reactor-Alert '/storage/nvme5/new_clones/ColdFusion/Fusion-Reactor-Alert' &
git clone https://github.com/DominicWatson/cfelasticsearch '/storage/nvme5/new_clones/ColdFusion/cfelasticsearch' &
git clone https://github.com/raulriera/Localizer '/storage/nvme5/new_clones/ColdFusion/Localizer' &
git clone https://github.com/matthewriley/USPS-CFC '/storage/nvme5/new_clones/ColdFusion/USPS-CFC' &
git clone https://github.com/ten24/slatwall-mura '/storage/nvme5/new_clones/ColdFusion/slatwall-mura' &
git clone https://github.com/ryanguill/Cascade '/storage/nvme5/new_clones/ColdFusion/Cascade' &
git clone https://github.com/coldbox-modules/route-visualizer '/storage/nvme5/new_clones/ColdFusion/route-visualizer' &
git clone https://github.com/mhenke/DataTablesForWheels '/storage/nvme5/new_clones/ColdFusion/DataTablesForWheels' &
git clone https://github.com/blueriver/MuraFBConnect '/storage/nvme5/new_clones/ColdFusion/MuraFBConnect' &
git clone https://github.com/ddspringle/abuseipdb-CFML '/storage/nvme5/new_clones/ColdFusion/abuseipdb-CFML' &
git clone https://github.com/vperdigao/cf-msgraph '/storage/nvme5/new_clones/ColdFusion/cf-msgraph' &
git clone https://github.com/atuttle/semaphore '/storage/nvme5/new_clones/ColdFusion/semaphore' &
git clone https://github.com/pixl8/cfconcurrent '/storage/nvme5/new_clones/ColdFusion/cfconcurrent' &
git clone https://github.com/jmohler1970/WordExtractor '/storage/nvme5/new_clones/ColdFusion/WordExtractor' &
git clone https://github.com/bennadel/ColdFusion-Custom-Tag-Emails '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Custom-Tag-Emails' &
git clone https://github.com/elpete/str '/storage/nvme5/new_clones/ColdFusion/str' &
git clone https://github.com/denuno/railo-build '/storage/nvme5/new_clones/ColdFusion/railo-build' &
git clone https://github.com/Ortus-Solutions/codexwiki '/storage/nvme5/new_clones/ColdFusion/codexwiki' &
git clone https://github.com/coldbox-modules/cbq '/storage/nvme5/new_clones/ColdFusion/cbq' &
git clone https://github.com/coldbox-modules/cbstorages '/storage/nvme5/new_clones/ColdFusion/cbstorages' &
git clone https://github.com/bennadel/PatternMatcher.cfc '/storage/nvme5/new_clones/ColdFusion/PatternMatcher.cfc' &
git clone https://github.com/stevewithington/MuraLocations '/storage/nvme5/new_clones/ColdFusion/MuraLocations' &
git clone https://github.com/mjclemente/api-wrapper-template '/storage/nvme5/new_clones/ColdFusion/api-wrapper-template' &
git clone https://github.com/Ortus-Solutions/RabbitSDK '/storage/nvme5/new_clones/ColdFusion/RabbitSDK' &
git clone https://github.com/dkyadav/CF_PP '/storage/nvme5/new_clones/ColdFusion/CF_PP' &
git clone https://github.com/pirategaspard/AnythingToXML '/storage/nvme5/new_clones/ColdFusion/AnythingToXML' &
git clone https://github.com/mjclemente/algolia.cfc '/storage/nvme5/new_clones/ColdFusion/algolia.cfc' &
git clone https://github.com/andybellenie/cfwheels-authenticate-this '/storage/nvme5/new_clones/ColdFusion/cfwheels-authenticate-this' &
git clone https://github.com/coldfumonkeh/bit.ly '/storage/nvme5/new_clones/ColdFusion/bit.ly' &
git clone https://github.com/boltz/iTextCFC '/storage/nvme5/new_clones/ColdFusion/iTextCFC' &
git clone https://github.com/nolanerck/VueJS-and-CFML '/storage/nvme5/new_clones/ColdFusion/VueJS-and-CFML' &
git clone https://github.com/tonyjunkes/CFFormProtect-Revamp '/storage/nvme5/new_clones/ColdFusion/CFFormProtect-Revamp' &
git clone https://github.com/bennadel/PubNub.cfc '/storage/nvme5/new_clones/ColdFusion/PubNub.cfc' &
git clone https://github.com/bennadel/Snooper.cfc '/storage/nvme5/new_clones/ColdFusion/Snooper.cfc' &
git clone https://github.com/johnlwhiteman/bad-human-code '/storage/nvme5/new_clones/ColdFusion/bad-human-code' &
git clone https://github.com/cfwheels/wheels-cli '/storage/nvme5/new_clones/ColdFusion/wheels-cli' &
git clone https://github.com/orangexception/ColdFusion-Sprite-Generator '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Sprite-Generator' &
git clone https://github.com/robertz/cf_sesmail '/storage/nvme5/new_clones/ColdFusion/cf_sesmail' &
git clone https://github.com/richardherbert/cfpaymill '/storage/nvme5/new_clones/ColdFusion/cfpaymill' &
git clone https://github.com/bennadel/ColdFusion-Hotwire '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Hotwire' &
git clone https://github.com/JamoCA/cfml-nanoid '/storage/nvme5/new_clones/ColdFusion/cfml-nanoid' &
git clone https://github.com/tpryan/GoogleTranslationAPICFC '/storage/nvme5/new_clones/ColdFusion/GoogleTranslationAPICFC' &
git clone https://github.com/blueriver/MuraBootstrap4 '/storage/nvme5/new_clones/ColdFusion/MuraBootstrap4' &
git clone https://github.com/coldbox-modules/coda '/storage/nvme5/new_clones/ColdFusion/coda' &
git clone https://github.com/foundeo/fixinator-gui '/storage/nvme5/new_clones/ColdFusion/fixinator-gui' &
git clone https://github.com/davejlong/CFMarkdown '/storage/nvme5/new_clones/ColdFusion/CFMarkdown' &
git clone https://github.com/coldfumonkeh/Rhea-Rackspace-Cloud-API '/storage/nvme5/new_clones/ColdFusion/Rhea-Rackspace-Cloud-API' &
git clone https://github.com/liquifusion/icrm-sdk '/storage/nvme5/new_clones/ColdFusion/icrm-sdk' &
git clone https://github.com/contentbox-modules/slatwall-contentbox '/storage/nvme5/new_clones/ColdFusion/slatwall-contentbox' &
git clone https://github.com/grantcopley/cbwire-demo '/storage/nvme5/new_clones/ColdFusion/cbwire-demo' &
git clone https://github.com/JayIsPainting/CFML_HIBP '/storage/nvme5/new_clones/ColdFusion/CFML_HIBP' &
git clone https://github.com/coldbox-templates/rest '/storage/nvme5/new_clones/ColdFusion/rest' &
git clone https://github.com/asoltys/nstree '/storage/nvme5/new_clones/ColdFusion/nstree' &
git clone https://github.com/andybellenie/cfwheels-log-user-actions '/storage/nvme5/new_clones/ColdFusion/cfwheels-log-user-actions' &
git clone https://github.com/gregmoser/mura-docker-project '/storage/nvme5/new_clones/ColdFusion/mura-docker-project' &
git clone https://github.com/asfusion/mango '/storage/nvme5/new_clones/ColdFusion/mango' &
git clone https://github.com/bennadel/ColdFusion-ePub '/storage/nvme5/new_clones/ColdFusion/ColdFusion-ePub' &
git clone https://github.com/Ortus-Solutions/JSONPrettyPrint '/storage/nvme5/new_clones/ColdFusion/JSONPrettyPrint' &
git clone https://github.com/elpete/CFCollection '/storage/nvme5/new_clones/ColdFusion/CFCollection' &
git clone https://github.com/mikesprague/lucee-heroku '/storage/nvme5/new_clones/ColdFusion/lucee-heroku' &
git clone https://github.com/Nimesia/json-schema-validator '/storage/nvme5/new_clones/ColdFusion/json-schema-validator' &
git clone https://github.com/rip747/RocketUnit '/storage/nvme5/new_clones/ColdFusion/RocketUnit' &
git clone https://github.com/bennadel/StatsDGateway.cfc '/storage/nvme5/new_clones/ColdFusion/StatsDGateway.cfc' &
git clone https://github.com/pad/cfwheels-bigrig '/storage/nvme5/new_clones/ColdFusion/cfwheels-bigrig' &
git clone https://github.com/coldfumonkeh/CFWunderground '/storage/nvme5/new_clones/ColdFusion/CFWunderground' &
git clone https://github.com/bennadel/CUID-For-ColdFusion '/storage/nvme5/new_clones/ColdFusion/CUID-For-ColdFusion' &
git clone https://github.com/teamcfadvance/TimeZone '/storage/nvme5/new_clones/ColdFusion/TimeZone' &
git clone https://github.com/illuminerdi/DefaultScope '/storage/nvme5/new_clones/ColdFusion/DefaultScope' &
git clone https://github.com/blueriver/MuraProfile '/storage/nvme5/new_clones/ColdFusion/MuraProfile' &
git clone https://github.com/jfrux/Stripe-ColdFusion-SDK '/storage/nvme5/new_clones/ColdFusion/Stripe-ColdFusion-SDK' &
git clone https://github.com/nmische/cf-configmanager '/storage/nvme5/new_clones/ColdFusion/cf-configmanager' &
git clone https://github.com/ndintenfass/dbsugar '/storage/nvme5/new_clones/ColdFusion/dbsugar' &
git clone https://github.com/bittersweetryan/cfevernote '/storage/nvme5/new_clones/ColdFusion/cfevernote' &
git clone https://github.com/jordanclark/cfshopify '/storage/nvme5/new_clones/ColdFusion/cfshopify' &
git clone https://github.com/joshknutson/coldfusion-debug '/storage/nvme5/new_clones/ColdFusion/coldfusion-debug' &
git clone https://github.com/cfjquery/multiLogin '/storage/nvme5/new_clones/ColdFusion/multiLogin' &
git clone https://github.com/rfs-/coldfusion-mailchimp-api '/storage/nvme5/new_clones/ColdFusion/coldfusion-mailchimp-api' &
git clone https://github.com/mhenke/litepost '/storage/nvme5/new_clones/ColdFusion/litepost' &
git clone https://github.com/cfjedimaster/Soundings '/storage/nvme5/new_clones/ColdFusion/Soundings' &
git clone https://github.com/commandbox-modules/commandbox-template '/storage/nvme5/new_clones/ColdFusion/commandbox-template' &
git clone https://github.com/Ortus-Solutions/docker-contentbox '/storage/nvme5/new_clones/ColdFusion/docker-contentbox' &
git clone https://github.com/blueriver/MuraCache '/storage/nvme5/new_clones/ColdFusion/MuraCache' &
git clone https://github.com/bennadel/EmailYak.cfc '/storage/nvme5/new_clones/ColdFusion/EmailYak.cfc' &
git clone https://github.com/devnulled/cfakismet '/storage/nvme5/new_clones/ColdFusion/cfakismet' &
git clone https://github.com/stevewithington/MuraGoogleMaps '/storage/nvme5/new_clones/ColdFusion/MuraGoogleMaps' &
git clone https://github.com/mhenke/LessForWheels '/storage/nvme5/new_clones/ColdFusion/LessForWheels' &
git clone https://github.com/andreacfm/websockets_example_apps '/storage/nvme5/new_clones/ColdFusion/websockets_example_apps' &
git clone https://github.com/coldbox-modules/mementifier '/storage/nvme5/new_clones/ColdFusion/mementifier' &
git clone https://github.com/bennadel/ColdFusion-Circuit-Breaker '/storage/nvme5/new_clones/ColdFusion/ColdFusion-Circuit-Breaker' &
