#!/bin/bash

git clone https://github.com/AbsInt/CompCert '/storage/nvme5/new_clones/Coq/CompCert' &
git clone https://github.com/gustavo-depaula/stalin-sort '/storage/nvme5/new_clones/Coq/stalin-sort' &
git clone https://github.com/HoTT/Coq-HoTT '/storage/nvme5/new_clones/Coq/Coq-HoTT' &
git clone https://github.com/UniMath/UniMath '/storage/nvme5/new_clones/Coq/UniMath' &
git clone https://github.com/magmide/magmide '/storage/nvme5/new_clones/Coq/magmide' &
git clone https://github.com/jwiegley/category-theory '/storage/nvme5/new_clones/Coq/category-theory' &
git clone https://github.com/mit-plv/fiat-crypto '/storage/nvme5/new_clones/Coq/fiat-crypto' &
git clone https://github.com/achlipala/frap '/storage/nvme5/new_clones/Coq/frap' &
git clone https://github.com/math-comp/math-comp '/storage/nvme5/new_clones/Coq/math-comp' &
git clone https://github.com/uwplse/verdi '/storage/nvme5/new_clones/Coq/verdi' &
git clone https://github.com/coq-community/coq-tricks '/storage/nvme5/new_clones/Coq/coq-tricks' &
git clone https://github.com/riscv/sail-riscv '/storage/nvme5/new_clones/Coq/sail-riscv' &
git clone https://github.com/PrincetonUniversity/VST '/storage/nvme5/new_clones/Coq/VST' &
git clone https://github.com/MetaCoq/metacoq '/storage/nvme5/new_clones/Coq/metacoq' &
git clone https://github.com/mit-plv/bedrock2 '/storage/nvme5/new_clones/Coq/bedrock2' &
git clone https://github.com/stepchowfun/proofs '/storage/nvme5/new_clones/Coq/proofs' &
git clone https://github.com/antalsz/hs-to-coq '/storage/nvme5/new_clones/Coq/hs-to-coq' &
git clone https://github.com/jasmin-lang/jasmin '/storage/nvme5/new_clones/Coq/jasmin' &
git clone https://github.com/QuickChick/QuickChick '/storage/nvme5/new_clones/Coq/QuickChick' &
git clone https://github.com/hacspec/hacspec '/storage/nvme5/new_clones/Coq/hacspec' &
git clone https://github.com/UniMath/Foundations '/storage/nvme5/new_clones/Coq/Foundations' &
git clone https://github.com/mit-pdos/fscq '/storage/nvme5/new_clones/Coq/fscq' &
git clone https://github.com/lulinchen/cnn_open '/storage/nvme5/new_clones/Coq/cnn_open' &
git clone https://github.com/math-comp/analysis '/storage/nvme5/new_clones/Coq/analysis' &
git clone https://github.com/DeepSpec/InteractionTrees '/storage/nvme5/new_clones/Coq/InteractionTrees' &
git clone https://github.com/sifive/Kami '/storage/nvme5/new_clones/Coq/Kami' &
git clone https://github.com/jscert/jscert '/storage/nvme5/new_clones/Coq/jscert' &
git clone https://github.com/coq-community/fourcolor '/storage/nvme5/new_clones/Coq/fourcolor' &
git clone https://github.com/uwplse/verdi-raft '/storage/nvme5/new_clones/Coq/verdi-raft' &
git clone https://github.com/clarus/coq-chick-blog '/storage/nvme5/new_clones/Coq/coq-chick-blog' &
git clone https://github.com/mit-pdos/perennial '/storage/nvme5/new_clones/Coq/perennial' &
git clone https://github.com/jwiegley/coq-haskell '/storage/nvme5/new_clones/Coq/coq-haskell' &
git clone https://github.com/coq-community/math-classes '/storage/nvme5/new_clones/Coq/math-classes' &
git clone https://github.com/ilyasergey/pnp '/storage/nvme5/new_clones/Coq/pnp' &
git clone https://github.com/accordproject/ergo '/storage/nvme5/new_clones/Coq/ergo' &
git clone https://github.com/barry-jay-personal/tree-calculus '/storage/nvme5/new_clones/Coq/tree-calculus' &
git clone https://github.com/mit-plv/fiat '/storage/nvme5/new_clones/Coq/fiat' &
git clone https://github.com/mit-plv/kami '/storage/nvme5/new_clones/Coq/kami' &
git clone https://github.com/discus-lang/iron '/storage/nvme5/new_clones/Coq/iron' &
git clone https://github.com/Lysxia/advent-of-coq-2018 '/storage/nvme5/new_clones/Coq/advent-of-coq-2018' &
git clone https://github.com/CertiCoq/certicoq '/storage/nvme5/new_clones/Coq/certicoq' &
git clone https://github.com/coq-community/coq-ext-lib '/storage/nvme5/new_clones/Coq/coq-ext-lib' &
git clone https://github.com/rocq-archive/coq-serapi '/storage/nvme5/new_clones/Coq/coq-serapi' &
git clone https://github.com/project-oak/silveroak '/storage/nvme5/new_clones/Coq/silveroak' &
git clone https://github.com/AU-COBRA/ConCert '/storage/nvme5/new_clones/Coq/ConCert' &
git clone https://github.com/coq-community/coq-art '/storage/nvme5/new_clones/Coq/coq-art' &
git clone https://github.com/uds-psl/coq-library-undecidability '/storage/nvme5/new_clones/Coq/coq-library-undecidability' &
git clone https://github.com/UniMath/TypeTheory '/storage/nvme5/new_clones/Coq/TypeTheory' &
git clone https://github.com/mit-plv/riscv-coq '/storage/nvme5/new_clones/Coq/riscv-coq' &
git clone https://github.com/verse-lab/toychain '/storage/nvme5/new_clones/Coq/toychain' &
git clone https://github.com/Ptival/PeaCoq '/storage/nvme5/new_clones/Coq/PeaCoq' &
git clone https://github.com/jonleivent/mindless-coding '/storage/nvme5/new_clones/Coq/mindless-coding' &
git clone https://github.com/WasmCert/WasmCert-Coq '/storage/nvme5/new_clones/Coq/WasmCert-Coq' &
git clone https://github.com/jwiegley/coq-pipes '/storage/nvme5/new_clones/Coq/coq-pipes' &
git clone https://github.com/DistributedComponents/disel '/storage/nvme5/new_clones/Coq/disel' &
git clone https://github.com/inQWIRE/QWIRE '/storage/nvme5/new_clones/Coq/QWIRE' &
git clone https://github.com/amintimany/Categories '/storage/nvme5/new_clones/Coq/Categories' &
git clone https://github.com/clarus/falso '/storage/nvme5/new_clones/Coq/falso' &
git clone https://github.com/TheoWinterhalter/formal-type-theory '/storage/nvme5/new_clones/Coq/formal-type-theory' &
git clone https://github.com/robbertkrebbers/ch2o '/storage/nvme5/new_clones/Coq/ch2o' &
git clone https://github.com/TiarkRompf/collapsing-towers '/storage/nvme5/new_clones/Coq/collapsing-towers' &
git clone https://github.com/coq-concurrency/pluto '/storage/nvme5/new_clones/Coq/pluto' &
git clone https://github.com/uds-psl/MPCTT '/storage/nvme5/new_clones/Coq/MPCTT' &
git clone https://github.com/DeepSpec/dsss17 '/storage/nvme5/new_clones/Coq/dsss17' &
git clone https://github.com/TiarkRompf/minidot '/storage/nvme5/new_clones/Coq/minidot' &
git clone https://github.com/plclub/hs-to-coq '/storage/nvme5/new_clones/Coq/hs-to-coq' &
git clone https://github.com/inQWIRE/SQIR '/storage/nvme5/new_clones/Coq/SQIR' &
git clone https://github.com/UniMath/Schools '/storage/nvme5/new_clones/Coq/Schools' &
git clone https://github.com/pi8027/lambda-calculus '/storage/nvme5/new_clones/Coq/lambda-calculus' &
git clone https://github.com/IBM/FormalML '/storage/nvme5/new_clones/Coq/FormalML' &
git clone https://github.com/plclub/metalib '/storage/nvme5/new_clones/Coq/metalib' &
git clone https://github.com/bluerock-io/BRiCk '/storage/nvme5/new_clones/Coq/BRiCk' &
git clone https://github.com/gtjennings1/UPDuino_v2_0 '/storage/nvme5/new_clones/Coq/UPDuino_v2_0' &
git clone https://github.com/ml4tp/gamepad '/storage/nvme5/new_clones/Coq/gamepad' &
git clone https://github.com/sfja/sfja '/storage/nvme5/new_clones/Coq/sfja' &
git clone https://github.com/coq-community/hydra-battles '/storage/nvme5/new_clones/Coq/hydra-battles' &
git clone https://github.com/imdea-software/htt '/storage/nvme5/new_clones/Coq/htt' &
git clone https://github.com/coq-community/coqeal '/storage/nvme5/new_clones/Coq/coqeal' &
git clone https://github.com/INRIA/velus '/storage/nvme5/new_clones/Coq/velus' &
git clone https://github.com/coq-io/io '/storage/nvme5/new_clones/Coq/io' &
git clone https://github.com/sweirich/corespec '/storage/nvme5/new_clones/Coq/corespec' &
git clone https://github.com/TiarkRompf/scala-escape '/storage/nvme5/new_clones/Coq/scala-escape' &
git clone https://github.com/samuelgruetter/dot-calculus '/storage/nvme5/new_clones/Coq/dot-calculus' &
git clone https://github.com/codyroux/name-the-biggest-number '/storage/nvme5/new_clones/Coq/name-the-biggest-number' &
git clone https://github.com/SSProve/ssprove '/storage/nvme5/new_clones/Coq/ssprove' &
git clone https://github.com/choukh/Set-Theory '/storage/nvme5/new_clones/Coq/Set-Theory' &
git clone https://github.com/sigurdschneider/lvc '/storage/nvme5/new_clones/Coq/lvc' &
git clone https://github.com/mit-plv/bedrock '/storage/nvme5/new_clones/Coq/bedrock' &
git clone https://github.com/peterlefanulumsdaine/general-type-theories '/storage/nvme5/new_clones/Coq/general-type-theories' &
git clone https://github.com/querycert/qcert '/storage/nvme5/new_clones/Coq/qcert' &
git clone https://github.com/tcarstens/verlang '/storage/nvme5/new_clones/Coq/verlang' &
git clone https://github.com/coq-community/autosubst '/storage/nvme5/new_clones/Coq/autosubst' &
git clone https://github.com/anton-trunov/coq-lecture-notes '/storage/nvme5/new_clones/Coq/coq-lecture-notes' &
git clone https://github.com/philzook58/nand2coq '/storage/nvme5/new_clones/Coq/nand2coq' &
git clone https://github.com/sipa/safegcd-bounds '/storage/nvme5/new_clones/Coq/safegcd-bounds' &
git clone https://github.com/geohot/coq-hardy '/storage/nvme5/new_clones/Coq/coq-hardy' &
git clone https://github.com/MichaelBurge/pornview '/storage/nvme5/new_clones/Coq/pornview' &
git clone https://github.com/lthms/FreeSpec '/storage/nvme5/new_clones/Coq/FreeSpec' &
git clone https://github.com/Mtac2/Mtac2 '/storage/nvme5/new_clones/Coq/Mtac2' &
git clone https://github.com/mit-plv/rupicola '/storage/nvme5/new_clones/Coq/rupicola' &
git clone https://github.com/NVlabs/ptxmemorymodel '/storage/nvme5/new_clones/Coq/ptxmemorymodel' &
git clone https://github.com/jtassarotti/coq-proba '/storage/nvme5/new_clones/Coq/coq-proba' &
git clone https://github.com/adampetcher/fcf '/storage/nvme5/new_clones/Coq/fcf' &
git clone https://github.com/uwplse/pumpkin-pi '/storage/nvme5/new_clones/Coq/pumpkin-pi' &
git clone https://github.com/tchajed/iris-simp-lang '/storage/nvme5/new_clones/Coq/iris-simp-lang' &
git clone https://github.com/cmeiklejohn/distributed-data-structures '/storage/nvme5/new_clones/Coq/distributed-data-structures' &
git clone https://github.com/arthuraa/poleiro '/storage/nvme5/new_clones/Coq/poleiro' &
git clone https://github.com/Veridise/Coda '/storage/nvme5/new_clones/Coq/Coda' &
git clone https://github.com/math-comp/finmap '/storage/nvme5/new_clones/Coq/finmap' &
git clone https://github.com/coq-community/semantics '/storage/nvme5/new_clones/Coq/semantics' &
git clone https://github.com/coq-community/topology '/storage/nvme5/new_clones/Coq/topology' &
git clone https://github.com/foreverbell/verified '/storage/nvme5/new_clones/Coq/verified' &
git clone https://github.com/Lysxia/profunctor-monad '/storage/nvme5/new_clones/Coq/profunctor-monad' &
git clone https://github.com/coq-community/paramcoq '/storage/nvme5/new_clones/Coq/paramcoq' &
git clone https://github.com/coq-community/fav-ssr '/storage/nvme5/new_clones/Coq/fav-ssr' &
git clone https://github.com/snu-sf/paco '/storage/nvme5/new_clones/Coq/paco' &
git clone https://github.com/choukh/Baby-Set-Theory '/storage/nvme5/new_clones/Coq/Baby-Set-Theory' &
git clone https://github.com/pirapira/evmverif '/storage/nvme5/new_clones/Coq/evmverif' &
git clone https://github.com/sweirich/replib '/storage/nvme5/new_clones/Coq/replib' &
git clone https://github.com/TiarkRompf/reachability '/storage/nvme5/new_clones/Coq/reachability' &
git clone https://github.com/garrigue/certint '/storage/nvme5/new_clones/Coq/certint' &
git clone https://github.com/tchajed/ltac2-tutorial '/storage/nvme5/new_clones/Coq/ltac2-tutorial' &
git clone https://github.com/wouter-swierstra/xmonad '/storage/nvme5/new_clones/Coq/xmonad' &
git clone https://github.com/coq-community/dedekind-reals '/storage/nvme5/new_clones/Coq/dedekind-reals' &
git clone https://github.com/tchajed/coq-record-update '/storage/nvme5/new_clones/Coq/coq-record-update' &
git clone https://github.com/coq-community/parseque '/storage/nvme5/new_clones/Coq/parseque' &
git clone https://github.com/mit-plv/coqutil '/storage/nvme5/new_clones/Coq/coqutil' &
git clone https://github.com/plclub/cis670-16fa '/storage/nvme5/new_clones/Coq/cis670-16fa' &
git clone https://github.com/coq-community/reglang '/storage/nvme5/new_clones/Coq/reglang' &
git clone https://github.com/CertiCoq/VeriFFI '/storage/nvme5/new_clones/Coq/VeriFFI' &
git clone https://github.com/OUPL/MLCert '/storage/nvme5/new_clones/Coq/MLCert' &
git clone https://github.com/yugithub/OFDM-baseband '/storage/nvme5/new_clones/Coq/OFDM-baseband' &
git clone https://github.com/xavierleroy/cdf-program-logics '/storage/nvme5/new_clones/Coq/cdf-program-logics' &
git clone https://github.com/liufengyun/stoic '/storage/nvme5/new_clones/Coq/stoic' &
git clone https://github.com/Lysxia/advent-of-coq-2021 '/storage/nvme5/new_clones/Coq/advent-of-coq-2021' &
git clone https://github.com/charguer/tlc '/storage/nvme5/new_clones/Coq/tlc' &
git clone https://github.com/RSPwFPGAs/opae-xilinx '/storage/nvme5/new_clones/Coq/opae-xilinx' &
git clone https://github.com/dbp/howtoproveacompiler '/storage/nvme5/new_clones/Coq/howtoproveacompiler' &
git clone https://github.com/tlringer/proof-demos '/storage/nvme5/new_clones/Coq/proof-demos' &
git clone https://github.com/vlopezj/coq-course '/storage/nvme5/new_clones/Coq/coq-course' &
git clone https://github.com/awslabs/aws-lc-verification '/storage/nvme5/new_clones/Coq/aws-lc-verification' &
git clone https://github.com/HIPERFIT/contracts '/storage/nvme5/new_clones/Coq/contracts' &
git clone https://github.com/takanuva/cps '/storage/nvme5/new_clones/Coq/cps' &
git clone https://github.com/gangtan/CPUmodels '/storage/nvme5/new_clones/Coq/CPUmodels' &
git clone https://github.com/fblanqui/color '/storage/nvme5/new_clones/Coq/color' &
git clone https://github.com/inQWIRE/QuantumLib '/storage/nvme5/new_clones/Coq/QuantumLib' &
git clone https://github.com/smtcoq/sniper '/storage/nvme5/new_clones/Coq/sniper' &
git clone https://github.com/coq-community/graph-theory '/storage/nvme5/new_clones/Coq/graph-theory' &
git clone https://github.com/ChezJrk/verified-scheduling '/storage/nvme5/new_clones/Coq/verified-scheduling' &
git clone https://github.com/langston-barrett/coq-big-o '/storage/nvme5/new_clones/Coq/coq-big-o' &
git clone https://github.com/snu-sf/promising-coq '/storage/nvme5/new_clones/Coq/promising-coq' &
git clone https://github.com/bit-mips/bitmips_experiments '/storage/nvme5/new_clones/Coq/bitmips_experiments' &
git clone https://github.com/aa755/ROSCoq '/storage/nvme5/new_clones/Coq/ROSCoq' &
git clone https://github.com/Lysxia/system-F '/storage/nvme5/new_clones/Coq/system-F' &
git clone https://github.com/marshall-lee/software_foundations '/storage/nvme5/new_clones/Coq/software_foundations' &
git clone https://github.com/vellvm/vellvm-legacy '/storage/nvme5/new_clones/Coq/vellvm-legacy' &
git clone https://github.com/pedrotst/coquedille '/storage/nvme5/new_clones/Coq/coquedille' &
git clone https://github.com/EasyCrypt/certicrypt '/storage/nvme5/new_clones/Coq/certicrypt' &
git clone https://github.com/math-comp/algebra-tactics '/storage/nvme5/new_clones/Coq/algebra-tactics' &
git clone https://github.com/logsem/aneris '/storage/nvme5/new_clones/Coq/aneris' &
git clone https://github.com/coq-community/chapar '/storage/nvme5/new_clones/Coq/chapar' &
git clone https://github.com/bmsherman/topology '/storage/nvme5/new_clones/Coq/topology' &
git clone https://github.com/pedagand/MPRI-2.4-DTP '/storage/nvme5/new_clones/Coq/MPRI-2.4-DTP' &
git clone https://github.com/jwiegley/bytestring-fiat '/storage/nvme5/new_clones/Coq/bytestring-fiat' &
git clone https://github.com/Lysxia/coq-simple-io '/storage/nvme5/new_clones/Coq/coq-simple-io' &
git clone https://github.com/coq-community/coq-program-verification-template '/storage/nvme5/new_clones/Coq/coq-program-verification-template' &
git clone https://github.com/0xf3cd/CPU54-Pipeline '/storage/nvme5/new_clones/Coq/CPU54-Pipeline' &
git clone https://github.com/codyroux/broad-coq-tutorial '/storage/nvme5/new_clones/Coq/broad-coq-tutorial' &
git clone https://github.com/uds-psl/coq-library-complexity '/storage/nvme5/new_clones/Coq/coq-library-complexity' &
git clone https://github.com/pa-ba/calc-comp '/storage/nvme5/new_clones/Coq/calc-comp' &
git clone https://github.com/vafeiadis/hahn '/storage/nvme5/new_clones/Coq/hahn' &
git clone https://github.com/coq-community/gaia '/storage/nvme5/new_clones/Coq/gaia' &
git clone https://github.com/arthuraa/extructures '/storage/nvme5/new_clones/Coq/extructures' &
git clone https://github.com/math-comp/odd-order '/storage/nvme5/new_clones/Coq/odd-order' &
git clone https://github.com/ichistmeinname/free-proving '/storage/nvme5/new_clones/Coq/free-proving' &
git clone https://github.com/tezos/tezoscoq '/storage/nvme5/new_clones/Coq/tezoscoq' &
git clone https://github.com/coq-community/goedel '/storage/nvme5/new_clones/Coq/goedel' &
git clone https://github.com/imdea-software/fcsl-pcm '/storage/nvme5/new_clones/Coq/fcsl-pcm' &
git clone https://github.com/math-comp/Abel '/storage/nvme5/new_clones/Coq/Abel' &
git clone https://github.com/coq-community/lemma-overloading '/storage/nvme5/new_clones/Coq/lemma-overloading' &
git clone https://github.com/mit-plv/bbv '/storage/nvme5/new_clones/Coq/bbv' &
git clone https://github.com/acorrenson/SATurne '/storage/nvme5/new_clones/Coq/SATurne' &
git clone https://github.com/coq-ext-lib/coq-compile '/storage/nvme5/new_clones/Coq/coq-compile' &
git clone https://github.com/dboulytchev/miniKanren-coq '/storage/nvme5/new_clones/Coq/miniKanren-coq' &
git clone https://github.com/novifinancial/LibraChain '/storage/nvme5/new_clones/Coq/LibraChain' &
git clone https://github.com/tchajed/coq-tla '/storage/nvme5/new_clones/Coq/coq-tla' &
git clone https://github.com/affeldt-aist/coq-robot '/storage/nvme5/new_clones/Coq/coq-robot' &
git clone https://github.com/reynir/Brainfuck '/storage/nvme5/new_clones/Coq/Brainfuck' &
git clone https://github.com/runtimeverification/algorand-verification '/storage/nvme5/new_clones/Coq/algorand-verification' &
git clone https://github.com/math-comp/mczify '/storage/nvme5/new_clones/Coq/mczify' &
git clone https://github.com/AU-COBRA/PoS-NSB '/storage/nvme5/new_clones/Coq/PoS-NSB' &
git clone https://github.com/CategoricalData/HoTT-categories '/storage/nvme5/new_clones/Coq/HoTT-categories' &
git clone https://github.com/konne88/bagpipe '/storage/nvme5/new_clones/Coq/bagpipe' &
git clone https://github.com/lastland/ClairvoyanceMonad '/storage/nvme5/new_clones/Coq/ClairvoyanceMonad' &
git clone https://github.com/arthuraa/deriving '/storage/nvme5/new_clones/Coq/deriving' &
git clone https://github.com/QinxiangCao/UnifySL '/storage/nvme5/new_clones/Coq/UnifySL' &
git clone https://github.com/Javran/Thinking-dumps '/storage/nvme5/new_clones/Coq/Thinking-dumps' &
git clone https://github.com/weakmemory/imm '/storage/nvme5/new_clones/Coq/imm' &
git clone https://github.com/sweirich/graded-haskell '/storage/nvme5/new_clones/Coq/graded-haskell' &
git clone https://github.com/thery/hanoi '/storage/nvme5/new_clones/Coq/hanoi' &
git clone https://github.com/max2468tw/IC_Lab '/storage/nvme5/new_clones/Coq/IC_Lab' &
git clone https://github.com/vzaliva/helix '/storage/nvme5/new_clones/Coq/helix' &
git clone https://github.com/Zilliqa/scilla-coq '/storage/nvme5/new_clones/Coq/scilla-coq' &
git clone https://github.com/mit-frap/spring18 '/storage/nvme5/new_clones/Coq/spring18' &
git clone https://github.com/CoqHott/logrel-coq '/storage/nvme5/new_clones/Coq/logrel-coq' &
git clone https://github.com/coq-community/atbr '/storage/nvme5/new_clones/Coq/atbr' &
git clone https://github.com/dunnl/tealeaves '/storage/nvme5/new_clones/Coq/tealeaves' &
git clone https://github.com/dricketts/teaching-concurrency '/storage/nvme5/new_clones/Coq/teaching-concurrency' &
git clone https://github.com/coq-io/system '/storage/nvme5/new_clones/Coq/system' &
git clone https://github.com/uwplse/cheerios '/storage/nvme5/new_clones/Coq/cheerios' &
git clone https://github.com/yzyzsun/CP-next '/storage/nvme5/new_clones/Coq/CP-next' &
git clone https://github.com/pi8027/stablesort '/storage/nvme5/new_clones/Coq/stablesort' &
git clone https://github.com/Coq-Polyhedra/Coq-Polyhedra '/storage/nvme5/new_clones/Coq/Coq-Polyhedra' &
git clone https://github.com/bobatkey/system-f-parametricity-model '/storage/nvme5/new_clones/Coq/system-f-parametricity-model' &
git clone https://github.com/sifive/ProcKami '/storage/nvme5/new_clones/Coq/ProcKami' &
git clone https://github.com/coq-community/bits '/storage/nvme5/new_clones/Coq/bits' &
git clone https://github.com/ropas/zooberry '/storage/nvme5/new_clones/Coq/zooberry' &
git clone https://github.com/robbertkrebbers/compcert '/storage/nvme5/new_clones/Coq/compcert' &
git clone https://github.com/kunalg123/riscv_workshop_collaterals '/storage/nvme5/new_clones/Coq/riscv_workshop_collaterals' &
git clone https://github.com/mit-plv/rewriter '/storage/nvme5/new_clones/Coq/rewriter' &
git clone https://github.com/thery/T2048 '/storage/nvme5/new_clones/Coq/T2048' &
git clone https://github.com/maximedenes/coq-amd64 '/storage/nvme5/new_clones/Coq/coq-amd64' &
git clone https://github.com/Yosuke-Ito-345/Actuary '/storage/nvme5/new_clones/Coq/Actuary' &
git clone https://github.com/uwplse/StructTact '/storage/nvme5/new_clones/Coq/StructTact' &
git clone https://github.com/ankitku/TAL0 '/storage/nvme5/new_clones/Coq/TAL0' &
git clone https://github.com/CertiKOS/coqrel '/storage/nvme5/new_clones/Coq/coqrel' &
git clone https://github.com/ynot-harvard/ynot '/storage/nvme5/new_clones/Coq/ynot' &
git clone https://github.com/Matafou/LibHyps '/storage/nvme5/new_clones/Coq/LibHyps' &
git clone https://github.com/katydid/regex-deriv-coq '/storage/nvme5/new_clones/Coq/regex-deriv-coq' &
git clone https://github.com/mgrabovsky/fm-notes '/storage/nvme5/new_clones/Coq/fm-notes' &
git clone https://github.com/braibant/Synthesis '/storage/nvme5/new_clones/Coq/Synthesis' &
git clone https://github.com/Huxpro/WasmCert '/storage/nvme5/new_clones/Coq/WasmCert' &
git clone https://github.com/kai-qu/linear-logic '/storage/nvme5/new_clones/Coq/linear-logic' &
git clone https://github.com/jonsterling/coq-guarded-computational-type-theory '/storage/nvme5/new_clones/Coq/coq-guarded-computational-type-theory' &
git clone https://github.com/tymmym/software-foundations '/storage/nvme5/new_clones/Coq/software-foundations' &
git clone https://github.com/micro-policies/micro-policies-coq '/storage/nvme5/new_clones/Coq/micro-policies-coq' &
git clone https://github.com/picodma/picodma-fpga '/storage/nvme5/new_clones/Coq/picodma-fpga' &
git clone https://github.com/fredfeng/CS292C '/storage/nvme5/new_clones/Coq/CS292C' &
git clone https://github.com/logsem/clutch '/storage/nvme5/new_clones/Coq/clutch' &
git clone https://github.com/coq-quantum/CoqQ '/storage/nvme5/new_clones/Coq/CoqQ' &
git clone https://github.com/jonleivent/mindless-coding-phase2 '/storage/nvme5/new_clones/Coq/mindless-coding-phase2' &
git clone https://github.com/mit-frap/spring22 '/storage/nvme5/new_clones/Coq/spring22' &
git clone https://github.com/jwiegley/coq-lattice '/storage/nvme5/new_clones/Coq/coq-lattice' &
git clone https://github.com/coq-community/apery '/storage/nvme5/new_clones/Coq/apery' &
git clone https://github.com/mmcco/verified-parser-example '/storage/nvme5/new_clones/Coq/verified-parser-example' &
git clone https://github.com/mit-frap/spring17 '/storage/nvme5/new_clones/Coq/spring17' &
git clone https://github.com/arthuraa/memory-safe-language '/storage/nvme5/new_clones/Coq/memory-safe-language' &
git clone https://github.com/google/coq-bpf '/storage/nvme5/new_clones/Coq/coq-bpf' &
git clone https://github.com/xavierleroy/canonical-binary-tries '/storage/nvme5/new_clones/Coq/canonical-binary-tries' &
git clone https://github.com/l2ctsinghua/l2c '/storage/nvme5/new_clones/Coq/l2c' &
git clone https://github.com/gmalecha/mirror-core '/storage/nvme5/new_clones/Coq/mirror-core' &
git clone https://github.com/heades/System-F-Coq '/storage/nvme5/new_clones/Coq/System-F-Coq' &
git clone https://github.com/inQWIRE/VyZX '/storage/nvme5/new_clones/Coq/VyZX' &
git clone https://github.com/jwiegley/coq-cds4ltl '/storage/nvme5/new_clones/Coq/coq-cds4ltl' &
git clone https://github.com/rodrigogribeiro/unification '/storage/nvme5/new_clones/Coq/unification' &
git clone https://github.com/logsem/cerise '/storage/nvme5/new_clones/Coq/cerise' &
git clone https://github.com/mit-frap/spring20 '/storage/nvme5/new_clones/Coq/spring20' &
git clone https://github.com/rocq-archive/ltl '/storage/nvme5/new_clones/Coq/ltl' &
git clone https://github.com/julesjacobs/cgraphs '/storage/nvme5/new_clones/Coq/cgraphs' &
git clone https://github.com/atungare/coq-software-foundations '/storage/nvme5/new_clones/Coq/coq-software-foundations' &
git clone https://github.com/choukh/CategoryTheory '/storage/nvme5/new_clones/Coq/CategoryTheory' &
git clone https://github.com/gmalecha/coq-printf '/storage/nvme5/new_clones/Coq/coq-printf' &
git clone https://github.com/lpw25/shifted-names '/storage/nvme5/new_clones/Coq/shifted-names' &
git clone https://github.com/jonsterling/coq-domains '/storage/nvme5/new_clones/Coq/coq-domains' &
git clone https://github.com/Lysxia/coq-ceres '/storage/nvme5/new_clones/Coq/coq-ceres' &
git clone https://github.com/styzystyzy/Axiomatic_Set_Theory '/storage/nvme5/new_clones/Coq/Axiomatic_Set_Theory' &
git clone https://github.com/2xs/pipcore '/storage/nvme5/new_clones/Coq/pipcore' &
git clone https://github.com/itleigns/CoqLibrary '/storage/nvme5/new_clones/Coq/CoqLibrary' &
git clone https://github.com/kushti/flp '/storage/nvme5/new_clones/Coq/flp' &
git clone https://github.com/aslanix/SmallStepNI '/storage/nvme5/new_clones/Coq/SmallStepNI' &
git clone https://github.com/fetburner/coq-dijkstra '/storage/nvme5/new_clones/Coq/coq-dijkstra' &
git clone https://github.com/lastland/WebSpec '/storage/nvme5/new_clones/Coq/WebSpec' &
git clone https://github.com/mit-frap/spring21 '/storage/nvme5/new_clones/Coq/spring21' &
git clone https://github.com/CertiGraph/CertiGraph '/storage/nvme5/new_clones/Coq/CertiGraph' &
git clone https://github.com/coq-io/hello-world '/storage/nvme5/new_clones/Coq/hello-world' &
git clone https://github.com/fetburner/type-infer '/storage/nvme5/new_clones/Coq/type-infer' &
git clone https://github.com/gmalecha/coq-interaction-trees '/storage/nvme5/new_clones/Coq/coq-interaction-trees' &
git clone https://github.com/snu-sf-class/pp202202 '/storage/nvme5/new_clones/Coq/pp202202' &
git clone https://github.com/suharahiromichi/coq '/storage/nvme5/new_clones/Coq/coq' &
git clone https://github.com/pleiad/Refinements '/storage/nvme5/new_clones/Coq/Refinements' &
git clone https://github.com/math-comp/tutorial_material '/storage/nvme5/new_clones/Coq/tutorial_material' &
git clone https://github.com/hablapps/LensAlgebra '/storage/nvme5/new_clones/Coq/LensAlgebra' &
git clone https://github.com/nmvdw/Three-HITs '/storage/nvme5/new_clones/Coq/Three-HITs' &
git clone https://github.com/takanuva/coc '/storage/nvme5/new_clones/Coq/coc' &
git clone https://github.com/jwiegley/linearscan '/storage/nvme5/new_clones/Coq/linearscan' &
git clone https://github.com/liyishuai/coq-http '/storage/nvme5/new_clones/Coq/coq-http' &
git clone https://github.com/uwplse/oeuf '/storage/nvme5/new_clones/Coq/oeuf' &
git clone https://github.com/charguer/formalmetacoq '/storage/nvme5/new_clones/Coq/formalmetacoq' &
git clone https://github.com/matthesjh/coq-tal '/storage/nvme5/new_clones/Coq/coq-tal' &
git clone https://github.com/shwetasshinde24/BesFS '/storage/nvme5/new_clones/Coq/BesFS' &
git clone https://github.com/ekmett/homotopy '/storage/nvme5/new_clones/Coq/homotopy' &
git clone https://github.com/katamaran-project/katamaran '/storage/nvme5/new_clones/Coq/katamaran' &
git clone https://github.com/GaloisInc/cryptol-semantics '/storage/nvme5/new_clones/Coq/cryptol-semantics' &
git clone https://github.com/Coq-Math-Problems/Problems '/storage/nvme5/new_clones/Coq/Problems' &
git clone https://github.com/SimonBoulier/TypingFlags '/storage/nvme5/new_clones/Coq/TypingFlags' &
git clone https://github.com/bedrocksystems/coq-lens '/storage/nvme5/new_clones/Coq/coq-lens' &
git clone https://github.com/tchajed/coq-tactical '/storage/nvme5/new_clones/Coq/coq-tactical' &
git clone https://github.com/xnning/Consistent-Subtyping-for-All '/storage/nvme5/new_clones/Coq/Consistent-Subtyping-for-All' &
git clone https://github.com/imfd/GraphCoQL '/storage/nvme5/new_clones/Coq/GraphCoQL' &
git clone https://github.com/irinacake/notesMaster1 '/storage/nvme5/new_clones/Coq/notesMaster1' &
git clone https://github.com/DistributedComponents/InfSeqExt '/storage/nvme5/new_clones/Coq/InfSeqExt' &
git clone https://github.com/Event-Structures/event-struct '/storage/nvme5/new_clones/Coq/event-struct' &
git clone https://github.com/hephaestus-pl/coqfj '/storage/nvme5/new_clones/Coq/coqfj' &
git clone https://github.com/coq-community/coqtail-math '/storage/nvme5/new_clones/Coq/coqtail-math' &
git clone https://github.com/lkilcher/pyTurbSim '/storage/nvme5/new_clones/Coq/pyTurbSim' &
git clone https://github.com/roglo/banach_tarski '/storage/nvme5/new_clones/Coq/banach_tarski' &
git clone https://github.com/mattam82/Forcing '/storage/nvme5/new_clones/Coq/Forcing' &
git clone https://github.com/dbp/howtoprovefullabstraction '/storage/nvme5/new_clones/Coq/howtoprovefullabstraction' &
git clone https://github.com/fsieczkowski/System-T '/storage/nvme5/new_clones/Coq/System-T' &
git clone https://github.com/joscoh/why3-semantics '/storage/nvme5/new_clones/Coq/why3-semantics' &
git clone https://github.com/strub/elliptic-curves-ssr '/storage/nvme5/new_clones/Coq/elliptic-curves-ssr' &
git clone https://github.com/carliros/software-foundations-book '/storage/nvme5/new_clones/Coq/software-foundations-book' &
git clone https://github.com/jashug/FormalizedCompilerAlgorithms '/storage/nvme5/new_clones/Coq/FormalizedCompilerAlgorithms' &
git clone https://github.com/vellvm/ctrees '/storage/nvme5/new_clones/Coq/ctrees' &
git clone https://github.com/cpdt-japanese/cpdt-japanese '/storage/nvme5/new_clones/Coq/cpdt-japanese' &
git clone https://github.com/snu-sf/crellvm '/storage/nvme5/new_clones/Coq/crellvm' &
git clone https://github.com/vladoovtcharov/Software-Foundations-Solutions '/storage/nvme5/new_clones/Coq/Software-Foundations-Solutions' &
git clone https://github.com/bitemyapp/ledgertheory '/storage/nvme5/new_clones/Coq/ledgertheory' &
git clone https://github.com/bacam/coqjvm '/storage/nvme5/new_clones/Coq/coqjvm' &
git clone https://github.com/tuura/selective-theory-coq '/storage/nvme5/new_clones/Coq/selective-theory-coq' &
git clone https://github.com/coq-community/huffman '/storage/nvme5/new_clones/Coq/huffman' &
git clone https://github.com/atlanmod/coqtl '/storage/nvme5/new_clones/Coq/coqtl' &
git clone https://github.com/vsdip/vsdflow '/storage/nvme5/new_clones/Coq/vsdflow' &
git clone https://github.com/math-comp/multinomials '/storage/nvme5/new_clones/Coq/multinomials' &
git clone https://github.com/nbenton/x86proved '/storage/nvme5/new_clones/Coq/x86proved' &
git clone https://github.com/coq-community/tarjan '/storage/nvme5/new_clones/Coq/tarjan' &
git clone https://github.com/relrod/ct '/storage/nvme5/new_clones/Coq/ct' &
git clone https://github.com/ppashakhanloo/verilog-adders '/storage/nvme5/new_clones/Coq/verilog-adders' &
git clone https://github.com/acorrenson/minilog '/storage/nvme5/new_clones/Coq/minilog' &
git clone https://github.com/rocq-archive/group-theory '/storage/nvme5/new_clones/Coq/group-theory' &
git clone https://github.com/ivashkev/math-formalizations '/storage/nvme5/new_clones/Coq/math-formalizations' &
git clone https://github.com/arthuraa/coq-utils '/storage/nvme5/new_clones/Coq/coq-utils' &
git clone https://github.com/csgordon/coq-fsharp '/storage/nvme5/new_clones/Coq/coq-fsharp' &
git clone https://github.com/CategoricalData/catdb '/storage/nvme5/new_clones/Coq/catdb' &
git clone https://github.com/cmeiklejohn/vvclocks '/storage/nvme5/new_clones/Coq/vvclocks' &
git clone https://github.com/pi8027/efficient-finfun '/storage/nvme5/new_clones/Coq/efficient-finfun' &
git clone https://github.com/mit-plv/hemiola '/storage/nvme5/new_clones/Coq/hemiola' &
git clone https://github.com/nagaet/Garrigue-lecture-2018_AW '/storage/nvme5/new_clones/Coq/Garrigue-lecture-2018_AW' &
git clone https://github.com/volodeyka/trust-coq '/storage/nvme5/new_clones/Coq/trust-coq' &
git clone https://github.com/rfindler/395-2013 '/storage/nvme5/new_clones/Coq/395-2013' &
git clone https://github.com/CoqHott/Program-translations-CC-omega '/storage/nvme5/new_clones/Coq/Program-translations-CC-omega' &
git clone https://github.com/Delta456/ascii_robot '/storage/nvme5/new_clones/Coq/ascii_robot' &
git clone https://github.com/mit-pdos/6.826-2017-labs '/storage/nvme5/new_clones/Coq/6.826-2017-labs' &
git clone https://github.com/math-comp/real-closed '/storage/nvme5/new_clones/Coq/real-closed' &
git clone https://github.com/DistributedComponents/verdi-lockserv '/storage/nvme5/new_clones/Coq/verdi-lockserv' &
git clone https://github.com/anderslundstedt/pca-realizability '/storage/nvme5/new_clones/Coq/pca-realizability' &
git clone https://github.com/uds-psl/autosubst-ocaml '/storage/nvme5/new_clones/Coq/autosubst-ocaml' &
git clone https://github.com/mit-pdos/6.826-2020-labs '/storage/nvme5/new_clones/Coq/6.826-2020-labs' &
git clone https://github.com/yforster/coq-verified-extraction '/storage/nvme5/new_clones/Coq/coq-verified-extraction' &
git clone https://github.com/codyroux/hoare-toy '/storage/nvme5/new_clones/Coq/hoare-toy' &
git clone https://github.com/daniellustig/coatcheck '/storage/nvme5/new_clones/Coq/coatcheck' &
git clone https://github.com/xnning/Row-and-Bounded-via-Disjoint '/storage/nvme5/new_clones/Coq/Row-and-Bounded-via-Disjoint' &
git clone https://github.com/coq-community/regexp-Brzozowski '/storage/nvme5/new_clones/Coq/regexp-Brzozowski' &
git clone https://github.com/darshangm92/Implementation-of-OFDM-Transmitter-using-Intel-DE2i--150-FPGA-board '/storage/nvme5/new_clones/Coq/Implementation-of-OFDM-Transmitter-using-Intel-DE2i--150-FPGA-board' &
git clone https://github.com/jdoughertyii/hott-species '/storage/nvme5/new_clones/Coq/hott-species' &
git clone https://github.com/thery/grobner '/storage/nvme5/new_clones/Coq/grobner' &
git clone https://github.com/antalsz/urn-random '/storage/nvme5/new_clones/Coq/urn-random' &
git clone https://github.com/ekmett/comonad-transformers '/storage/nvme5/new_clones/Coq/comonad-transformers' &
git clone https://github.com/uds-psl/CoqTM '/storage/nvme5/new_clones/Coq/CoqTM' &
git clone https://github.com/serras/sf-exercises '/storage/nvme5/new_clones/Coq/sf-exercises' &
git clone https://github.com/shlevy/cat-fiat '/storage/nvme5/new_clones/Coq/cat-fiat' &
git clone https://github.com/acowley/LinearLogic '/storage/nvme5/new_clones/Coq/LinearLogic' &
git clone https://github.com/Whu-Lambda/Lambda-Cube '/storage/nvme5/new_clones/Coq/Lambda-Cube' &
git clone https://github.com/samuelgruetter/riscv-coq '/storage/nvme5/new_clones/Coq/riscv-coq' &
git clone https://github.com/formalize/coq-vyper '/storage/nvme5/new_clones/Coq/coq-vyper' &
git clone https://github.com/FFaissole/Valuations '/storage/nvme5/new_clones/Coq/Valuations' &
git clone https://github.com/raaz-crypto/verse-coq '/storage/nvme5/new_clones/Coq/verse-coq' &
git clone https://github.com/GaloisInc/saw-core-coq '/storage/nvme5/new_clones/Coq/saw-core-coq' &
git clone https://github.com/pi8027/formalized-postscript '/storage/nvme5/new_clones/Coq/formalized-postscript' &
git clone https://github.com/sutajiokousagi/betrusted-soc '/storage/nvme5/new_clones/Coq/betrusted-soc' &
git clone https://github.com/pa-ba/McCarthy-Painter '/storage/nvme5/new_clones/Coq/McCarthy-Painter' &
git clone https://github.com/PrincetonUniversity/compcomp '/storage/nvme5/new_clones/Coq/compcomp' &
git clone https://github.com/CoqHott/coq-forcing '/storage/nvme5/new_clones/Coq/coq-forcing' &
git clone https://github.com/mit-pdos/cspec '/storage/nvme5/new_clones/Coq/cspec' &
git clone https://github.com/QuickChick/IFC '/storage/nvme5/new_clones/Coq/IFC' &
git clone https://github.com/gmalecha/coq-ltac-iter '/storage/nvme5/new_clones/Coq/coq-ltac-iter' &
git clone https://github.com/rems-project/islaris '/storage/nvme5/new_clones/Coq/islaris' &
git clone https://github.com/UniMath/largecatmodules '/storage/nvme5/new_clones/Coq/largecatmodules' &
git clone https://github.com/olivierverdier/GeometricAlgebra '/storage/nvme5/new_clones/Coq/GeometricAlgebra' &
git clone https://github.com/ymanerka/pipeproof '/storage/nvme5/new_clones/Coq/pipeproof' &
git clone https://github.com/JetBrains/ot-coq '/storage/nvme5/new_clones/Coq/ot-coq' &
git clone https://github.com/y-taka-23/concepts-of-proglangs '/storage/nvme5/new_clones/Coq/concepts-of-proglangs' &
git clone https://github.com/tchajed/coq-ltac2-experiments '/storage/nvme5/new_clones/Coq/coq-ltac2-experiments' &
git clone https://github.com/drouhling/LaSalle '/storage/nvme5/new_clones/Coq/LaSalle' &
git clone https://github.com/kayceesrk/cs6225_s21_iitm '/storage/nvme5/new_clones/Coq/cs6225_s21_iitm' &
git clone https://github.com/ezyang/HoTT-coqex '/storage/nvme5/new_clones/Coq/HoTT-coqex' &
git clone https://github.com/snu-sf/Ordinal '/storage/nvme5/new_clones/Coq/Ordinal' &
git clone https://github.com/fabriceleal/Software-Foundations-Solutions '/storage/nvme5/new_clones/Coq/Software-Foundations-Solutions' &
git clone https://github.com/choukh/MetaZF '/storage/nvme5/new_clones/Coq/MetaZF' &
git clone https://github.com/JasonGross/coq-tactics '/storage/nvme5/new_clones/Coq/coq-tactics' &
git clone https://github.com/GaloisInc/BESSPIN-Voting-System-Demonstrator-2019 '/storage/nvme5/new_clones/Coq/BESSPIN-Voting-System-Demonstrator-2019' &
git clone https://github.com/jtassarotti/polaris '/storage/nvme5/new_clones/Coq/polaris' &
git clone https://github.com/plum-umd/checkedc '/storage/nvme5/new_clones/Coq/checkedc' &
git clone https://github.com/csvoss/coqingbird '/storage/nvme5/new_clones/Coq/coqingbird' &
git clone https://github.com/wkolowski/Type-Theory-Wishlist '/storage/nvme5/new_clones/Coq/Type-Theory-Wishlist' &
git clone https://github.com/tangentforks/FourColorTheorem '/storage/nvme5/new_clones/Coq/FourColorTheorem' &
git clone https://github.com/llelf/kex '/storage/nvme5/new_clones/Coq/kex' &
git clone https://github.com/wkolowski/Typonomikon '/storage/nvme5/new_clones/Coq/Typonomikon' &
git clone https://github.com/tlively/BrainCoqulus '/storage/nvme5/new_clones/Coq/BrainCoqulus' &
git clone https://github.com/pa-ba/reg-machine '/storage/nvme5/new_clones/Coq/reg-machine' &
git clone https://github.com/AdaCore/sparkformal '/storage/nvme5/new_clones/Coq/sparkformal' &
git clone https://github.com/peterlefanulumsdaine/hott-limits '/storage/nvme5/new_clones/Coq/hott-limits' &
git clone https://github.com/mit-pdos/argosy '/storage/nvme5/new_clones/Coq/argosy' &
git clone https://github.com/bollu/diffgeo '/storage/nvme5/new_clones/Coq/diffgeo' &
git clone https://github.com/uds-psl/coq-synthetic-computability '/storage/nvme5/new_clones/Coq/coq-synthetic-computability' &
git clone https://github.com/DistributedComponents/verdi-chord '/storage/nvme5/new_clones/Coq/verdi-chord' &
git clone https://github.com/quinn-dougherty/ladr '/storage/nvme5/new_clones/Coq/ladr' &
git clone https://github.com/benediktahrens/monads '/storage/nvme5/new_clones/Coq/monads' &
git clone https://github.com/michaelsproul/dblib-linear '/storage/nvme5/new_clones/Coq/dblib-linear' &
git clone https://github.com/styzystyzy/Axiom_of_Choice '/storage/nvme5/new_clones/Coq/Axiom_of_Choice' &
git clone https://github.com/arthuraa/cufp-2015-tutorial '/storage/nvme5/new_clones/Coq/cufp-2015-tutorial' &
git clone https://github.com/sftypes/software-foundations '/storage/nvme5/new_clones/Coq/software-foundations' &
git clone https://github.com/tchajed/coq-io '/storage/nvme5/new_clones/Coq/coq-io' &
git clone https://github.com/jdoughertyii/hott-exercises '/storage/nvme5/new_clones/Coq/hott-exercises' &
git clone https://github.com/akr/coq-html-escape '/storage/nvme5/new_clones/Coq/coq-html-escape' &
git clone https://github.com/thery/PolTac '/storage/nvme5/new_clones/Coq/PolTac' &
git clone https://github.com/kolya-vasiliev/logical-foundations-2018 '/storage/nvme5/new_clones/Coq/logical-foundations-2018' &
git clone https://github.com/eddywestbrook/predicate-monads '/storage/nvme5/new_clones/Coq/predicate-monads' &
git clone https://github.com/CTSRD-CHERI/sail-cheri-mips '/storage/nvme5/new_clones/Coq/sail-cheri-mips' &
git clone https://github.com/mit-pdos/6.826-2019-labs '/storage/nvme5/new_clones/Coq/6.826-2019-labs' &
git clone https://github.com/lawrie/pico_ram_soc '/storage/nvme5/new_clones/Coq/pico_ram_soc' &
git clone https://github.com/nmvdw/groupoids '/storage/nvme5/new_clones/Coq/groupoids' &
git clone https://github.com/coqtail/coqtail '/storage/nvme5/new_clones/Coq/coqtail' &
git clone https://github.com/Zdancewic/linearity '/storage/nvme5/new_clones/Coq/linearity' &
git clone https://github.com/arthuraa/beaq '/storage/nvme5/new_clones/Coq/beaq' &
git clone https://github.com/ipdl/ipdl '/storage/nvme5/new_clones/Coq/ipdl' &
git clone https://github.com/CertiKOS/compcert.old '/storage/nvme5/new_clones/Coq/compcert.old' &
git clone https://github.com/hablapps/LensStateIsYourFather '/storage/nvme5/new_clones/Coq/LensStateIsYourFather' &
git clone https://github.com/AU-COBRA/coq-rust-extraction '/storage/nvme5/new_clones/Coq/coq-rust-extraction' &
git clone https://github.com/rocq-archive/pi-calc '/storage/nvme5/new_clones/Coq/pi-calc' &
git clone https://github.com/harp-project/Core-Erlang-Formalization '/storage/nvme5/new_clones/Coq/Core-Erlang-Formalization' &
git clone https://github.com/mmcco/Verified-BPF '/storage/nvme5/new_clones/Coq/Verified-BPF' &
git clone https://github.com/nbenton/coqdomains '/storage/nvme5/new_clones/Coq/coqdomains' &
git clone https://github.com/VeriNum/VerifiedLeapfrog '/storage/nvme5/new_clones/Coq/VerifiedLeapfrog' &
git clone https://github.com/rocq-archive/pts '/storage/nvme5/new_clones/Coq/pts' &
git clone https://github.com/lthms/coq-MiniHTTPServer '/storage/nvme5/new_clones/Coq/coq-MiniHTTPServer' &
git clone https://github.com/epfl-lara/SystemFR '/storage/nvme5/new_clones/Coq/SystemFR' &
git clone https://github.com/Galaxies99/Logical-Foundations '/storage/nvme5/new_clones/Coq/Logical-Foundations' &
git clone https://github.com/tchajed/goedel-t '/storage/nvme5/new_clones/Coq/goedel-t' &
git clone https://github.com/mroman42/math-dgiim '/storage/nvme5/new_clones/Coq/math-dgiim' &
git clone https://github.com/rocq-archive/regexp '/storage/nvme5/new_clones/Coq/regexp' &
git clone https://github.com/arthuraa/cryptis '/storage/nvme5/new_clones/Coq/cryptis' &
git clone https://github.com/QinxiangCao/LOGIC '/storage/nvme5/new_clones/Coq/LOGIC' &
git clone https://github.com/decrn/tilogics '/storage/nvme5/new_clones/Coq/tilogics' &
git clone https://github.com/neshkeev/Logical-Foundations '/storage/nvme5/new_clones/Coq/Logical-Foundations' &
git clone https://github.com/nyu-acsys/template-proofs '/storage/nvme5/new_clones/Coq/template-proofs' &
git clone https://github.com/Operational-Transformation/ot.v '/storage/nvme5/new_clones/Coq/ot.v' &
git clone https://github.com/arthurbeggs/riscv-simpler '/storage/nvme5/new_clones/Coq/riscv-simpler' &
git clone https://github.com/Lysxia/coq-recursion-schemes '/storage/nvme5/new_clones/Coq/coq-recursion-schemes' &
git clone https://github.com/clayrat/coherence-spaces '/storage/nvme5/new_clones/Coq/coherence-spaces' &
git clone https://github.com/epfl-lara/scallion-proofs '/storage/nvme5/new_clones/Coq/scallion-proofs' &
git clone https://github.com/jasmin-lang/coqword '/storage/nvme5/new_clones/Coq/coqword' &
git clone https://github.com/readablesystems/cs260r-17 '/storage/nvme5/new_clones/Coq/cs260r-17' &
git clone https://github.com/JasonGross/coq-scripts '/storage/nvme5/new_clones/Coq/coq-scripts' &
git clone https://github.com/samuelgruetter/coq-smt-notations '/storage/nvme5/new_clones/Coq/coq-smt-notations' &
git clone https://github.com/PLSysSec/veriwasm-verification '/storage/nvme5/new_clones/Coq/veriwasm-verification' &
git clone https://github.com/herd/CoqCat '/storage/nvme5/new_clones/Coq/CoqCat' &
git clone https://github.com/logsem/free-theorems-sl '/storage/nvme5/new_clones/Coq/free-theorems-sl' &
git clone https://github.com/gstew5/games '/storage/nvme5/new_clones/Coq/games' &
git clone https://github.com/acorrenson/automatik '/storage/nvme5/new_clones/Coq/automatik' &
git clone https://github.com/jashug/IWTypes '/storage/nvme5/new_clones/Coq/IWTypes' &
git clone https://github.com/zhengyao-lin/sf-lf '/storage/nvme5/new_clones/Coq/sf-lf' &
git clone https://github.com/coq-community/comp-dec-modal '/storage/nvme5/new_clones/Coq/comp-dec-modal' &
git clone https://github.com/tabareau/Cocasse '/storage/nvme5/new_clones/Coq/Cocasse' &
git clone https://github.com/gmalecha/mirror-shard '/storage/nvme5/new_clones/Coq/mirror-shard' &
git clone https://github.com/logsem/melocoton '/storage/nvme5/new_clones/Coq/melocoton' &
git clone https://github.com/m0rphism/definitional '/storage/nvme5/new_clones/Coq/definitional' &
git clone https://github.com/KiJeong-Lim/DschingisKhan '/storage/nvme5/new_clones/Coq/DschingisKhan' &
git clone https://github.com/STFleming/StitchUp '/storage/nvme5/new_clones/Coq/StitchUp' &
git clone https://github.com/konne88/SpaceSearch '/storage/nvme5/new_clones/Coq/SpaceSearch' &
git clone https://github.com/MathiasVP/ni-formal-gc '/storage/nvme5/new_clones/Coq/ni-formal-gc' &
git clone https://github.com/phadej/lens-laws '/storage/nvme5/new_clones/Coq/lens-laws' &
git clone https://github.com/siraben/coq-wigderson '/storage/nvme5/new_clones/Coq/coq-wigderson' &
git clone https://github.com/kendroe/CoqPIE '/storage/nvme5/new_clones/Coq/CoqPIE' &
git clone https://github.com/aspiwack/finset '/storage/nvme5/new_clones/Coq/finset' &
git clone https://github.com/daveshah1/flow-examples '/storage/nvme5/new_clones/Coq/flow-examples' &
git clone https://github.com/snu-sf-class/sf202002 '/storage/nvme5/new_clones/Coq/sf202002' &
git clone https://github.com/CageW/COA2_FPGA '/storage/nvme5/new_clones/Coq/COA2_FPGA' &
git clone https://github.com/llbit/Pigeonhole-Principle '/storage/nvme5/new_clones/Coq/Pigeonhole-Principle' &
git clone https://github.com/verified-network-toolchain/leapfrog '/storage/nvme5/new_clones/Coq/leapfrog' &
git clone https://github.com/tmiya/coq '/storage/nvme5/new_clones/Coq/coq' &
git clone https://github.com/trommler/VeriGHC '/storage/nvme5/new_clones/Coq/VeriGHC' &
git clone https://github.com/CoqHott/univalent_parametricity '/storage/nvme5/new_clones/Coq/univalent_parametricity' &
git clone https://github.com/julbinb/concept-params '/storage/nvme5/new_clones/Coq/concept-params' &
git clone https://github.com/kit-ty-kate/why3 '/storage/nvme5/new_clones/Coq/why3' &
git clone https://github.com/wangpengmit/6887psets '/storage/nvme5/new_clones/Coq/6887psets' &
git clone https://github.com/sighingnow/amazing-coq '/storage/nvme5/new_clones/Coq/amazing-coq' &
git clone https://github.com/markisus/coq-ski '/storage/nvme5/new_clones/Coq/coq-ski' &
git clone https://github.com/amutake/coq-extensible-effects '/storage/nvme5/new_clones/Coq/coq-extensible-effects' &
git clone https://github.com/Orbis-Tertius/Coq-Arithmetization '/storage/nvme5/new_clones/Coq/Coq-Arithmetization' &
git clone https://github.com/lukaszcz/infinitary-confluence '/storage/nvme5/new_clones/Coq/infinitary-confluence' &
git clone https://github.com/lijia73/Experiments-in-Digital-Circuit '/storage/nvme5/new_clones/Coq/Experiments-in-Digital-Circuit' &
git clone https://github.com/OmarFasseh/Verilog-CNN '/storage/nvme5/new_clones/Coq/Verilog-CNN' &
git clone https://github.com/jalpuim/disjoint-intersection-types '/storage/nvme5/new_clones/Coq/disjoint-intersection-types' &
git clone https://github.com/mmaleki/LogicalDifferentiation '/storage/nvme5/new_clones/Coq/LogicalDifferentiation' &
git clone https://github.com/UniMath/SetHITs '/storage/nvme5/new_clones/Coq/SetHITs' &
git clone https://github.com/CoqHott/DICoq '/storage/nvme5/new_clones/Coq/DICoq' &
git clone https://github.com/normanrink/TensorIR '/storage/nvme5/new_clones/Coq/TensorIR' &
git clone https://github.com/roglo/coq_real '/storage/nvme5/new_clones/Coq/coq_real' &
git clone https://github.com/FreeProving/free-proving-code '/storage/nvme5/new_clones/Coq/free-proving-code' &
git clone https://github.com/joscoh/graph-proofs '/storage/nvme5/new_clones/Coq/graph-proofs' &
git clone https://github.com/secure-compilation/exploring-robust-property-preservation '/storage/nvme5/new_clones/Coq/exploring-robust-property-preservation' &
git clone https://github.com/SJTU-PLV/nominal-compcert-popl22-artifact '/storage/nvme5/new_clones/Coq/nominal-compcert-popl22-artifact' &
git clone https://github.com/juda/Recursive-Subtyping-for-All '/storage/nvme5/new_clones/Coq/Recursive-Subtyping-for-All' &
git clone https://github.com/GavinMendelGleason/code '/storage/nvme5/new_clones/Coq/code' &
git clone https://github.com/hyonzin/wallace-tree '/storage/nvme5/new_clones/Coq/wallace-tree' &
git clone https://github.com/kskkss1/CNN_ZYNQ_HLS '/storage/nvme5/new_clones/Coq/CNN_ZYNQ_HLS' &
git clone https://github.com/snu-sf-class/sf201902 '/storage/nvme5/new_clones/Coq/sf201902' &
git clone https://github.com/codyroux/tinymatch '/storage/nvme5/new_clones/Coq/tinymatch' &
git clone https://github.com/wjzz/Agda-small-developments-and-examples '/storage/nvme5/new_clones/Coq/Agda-small-developments-and-examples' &
git clone https://github.com/MihirShah10/BIST-for-DFT-Applications '/storage/nvme5/new_clones/Coq/BIST-for-DFT-Applications' &
git clone https://github.com/TyGuS/ssl-htt '/storage/nvme5/new_clones/Coq/ssl-htt' &
git clone https://github.com/clarus/cybele '/storage/nvme5/new_clones/Coq/cybele' &
git clone https://github.com/thoughtpolice/coq-skeleton '/storage/nvme5/new_clones/Coq/coq-skeleton' &
git clone https://github.com/ppedrot/ll-coq '/storage/nvme5/new_clones/Coq/ll-coq' &
git clone https://github.com/roglo/cauchy_schwarz '/storage/nvme5/new_clones/Coq/cauchy_schwarz' &
git clone https://github.com/nmvdw/RezkCompletion '/storage/nvme5/new_clones/Coq/RezkCompletion' &
git clone https://github.com/Lysxia/coq-mtl '/storage/nvme5/new_clones/Coq/coq-mtl' &
git clone https://github.com/cverified/cbench-vst '/storage/nvme5/new_clones/Coq/cbench-vst' &
git clone https://github.com/CoqHott/coq-effects '/storage/nvme5/new_clones/Coq/coq-effects' &
git clone https://github.com/gtanzer/verse '/storage/nvme5/new_clones/Coq/verse' &
git clone https://github.com/AshleyYakeley/maths '/storage/nvme5/new_clones/Coq/maths' &
git clone https://github.com/rocq-archive/gc '/storage/nvme5/new_clones/Coq/gc' &
git clone https://github.com/tchajed/iris-named-props '/storage/nvme5/new_clones/Coq/iris-named-props' &
git clone https://github.com/Ptival/extensible-nanopass-compiler '/storage/nvme5/new_clones/Coq/extensible-nanopass-compiler' &
git clone https://github.com/braibant/exploit-plugin '/storage/nvme5/new_clones/Coq/exploit-plugin' &
git clone https://github.com/FTRobbin/Ironwood '/storage/nvme5/new_clones/Coq/Ironwood' &
git clone https://github.com/AnandoUS/Phonon_scattering_frequency_dependence '/storage/nvme5/new_clones/Coq/Phonon_scattering_frequency_dependence' &
git clone https://github.com/secure-compilation/when-good-components-go-bad '/storage/nvme5/new_clones/Coq/when-good-components-go-bad' &
git clone https://github.com/ppedrot/coq-forcing '/storage/nvme5/new_clones/Coq/coq-forcing' &
git clone https://github.com/emeb/orangecrab_adc '/storage/nvme5/new_clones/Coq/orangecrab_adc' &
git clone https://github.com/LambdaQs/lambda-qs '/storage/nvme5/new_clones/Coq/lambda-qs' &
git clone https://github.com/verified-network-toolchain/VerifiableP4 '/storage/nvme5/new_clones/Coq/VerifiableP4' &
git clone https://github.com/LASER-UMASS/Diva '/storage/nvme5/new_clones/Coq/Diva' &
git clone https://github.com/xuanruiqi/categories '/storage/nvme5/new_clones/Coq/categories' &
git clone https://github.com/AU-COBRA/AUCurves '/storage/nvme5/new_clones/Coq/AUCurves' &
git clone https://github.com/mcopes73/FTA '/storage/nvme5/new_clones/Coq/FTA' &
git clone https://github.com/vmurali/SeqConsistency '/storage/nvme5/new_clones/Coq/SeqConsistency' &
git clone https://github.com/coq-community/coq-performance-tests '/storage/nvme5/new_clones/Coq/coq-performance-tests' &
git clone https://github.com/izgzhen/iris-c-coq '/storage/nvme5/new_clones/Coq/iris-c-coq' &
git clone https://github.com/CertiGraph/CertiGC '/storage/nvme5/new_clones/Coq/CertiGC' &
git clone https://github.com/anshumanmohan/CertiGraph-VST '/storage/nvme5/new_clones/Coq/CertiGraph-VST' &
git clone https://github.com/stanislaw/berlin-software-verification-meetup '/storage/nvme5/new_clones/Coq/berlin-software-verification-meetup' &
git clone https://github.com/jouvelot/mech.v '/storage/nvme5/new_clones/Coq/mech.v' &
git clone https://github.com/thery/lemonde '/storage/nvme5/new_clones/Coq/lemonde' &
git clone https://github.com/tchajed/coq-sep-logic '/storage/nvme5/new_clones/Coq/coq-sep-logic' &
git clone https://github.com/goldfirere/ott-tutorial '/storage/nvme5/new_clones/Coq/ott-tutorial' &
git clone https://github.com/hpbrown92/Coq-Solutions '/storage/nvme5/new_clones/Coq/Coq-Solutions' &
git clone https://github.com/xuanruiqi/commalg '/storage/nvme5/new_clones/Coq/commalg' &
git clone https://github.com/xuanruiqi/algebraic-geometry '/storage/nvme5/new_clones/Coq/algebraic-geometry' &
git clone https://github.com/emtst/zooid-cmpst '/storage/nvme5/new_clones/Coq/zooid-cmpst' &
git clone https://github.com/rocq-archive/euclidean-geometry '/storage/nvme5/new_clones/Coq/euclidean-geometry' &
git clone https://github.com/amintimany/CTDT '/storage/nvme5/new_clones/Coq/CTDT' &
git clone https://github.com/barras/cic-model '/storage/nvme5/new_clones/Coq/cic-model' &
git clone https://github.com/nmvdw/HITs-Examples '/storage/nvme5/new_clones/Coq/HITs-Examples' &
git clone https://github.com/math-comp/POPLmark '/storage/nvme5/new_clones/Coq/POPLmark' &
git clone https://github.com/wouter-swierstra/Bird '/storage/nvme5/new_clones/Coq/Bird' &
git clone https://github.com/snu-sf/CompCertM '/storage/nvme5/new_clones/Coq/CompCertM' &
git clone https://github.com/Gurkenglas/gpt3coq '/storage/nvme5/new_clones/Coq/gpt3coq' &
git clone https://github.com/dragonwasrobot/simpl-lang '/storage/nvme5/new_clones/Coq/simpl-lang' &
git clone https://github.com/coq-community/zorns-lemma '/storage/nvme5/new_clones/Coq/zorns-lemma' &
git clone https://github.com/lpw25/row-subtyping '/storage/nvme5/new_clones/Coq/row-subtyping' &
git clone https://github.com/gares/math-comp-school-2022 '/storage/nvme5/new_clones/Coq/math-comp-school-2022' &
git clone https://github.com/euisuny/icfp22-layered-monadic-interpreters '/storage/nvme5/new_clones/Coq/icfp22-layered-monadic-interpreters' &
git clone https://github.com/wangpengmit/ssmatrix-theory '/storage/nvme5/new_clones/Coq/ssmatrix-theory' &
git clone https://github.com/sifive/FpuKami '/storage/nvme5/new_clones/Coq/FpuKami' &
git clone https://github.com/thery/FlocqLecture '/storage/nvme5/new_clones/Coq/FlocqLecture' &
git clone https://github.com/bacam/handlers-in-ott '/storage/nvme5/new_clones/Coq/handlers-in-ott' &
git clone https://github.com/erikmd/docker-coq-github-action-demo '/storage/nvme5/new_clones/Coq/docker-coq-github-action-demo' &
git clone https://github.com/mkolosick/Software-Foundations-Exercises '/storage/nvme5/new_clones/Coq/Software-Foundations-Exercises' &
git clone https://github.com/TheoWinterhalter/ett-to-wtt '/storage/nvme5/new_clones/Coq/ett-to-wtt' &
git clone https://github.com/lukaszcz/COQ-IMP '/storage/nvme5/new_clones/Coq/COQ-IMP' &
git clone https://github.com/acorrenson/BF '/storage/nvme5/new_clones/Coq/BF' &
git clone https://github.com/UniMath/GrpdHITs '/storage/nvme5/new_clones/Coq/GrpdHITs' &
git clone https://github.com/t6s/qecc '/storage/nvme5/new_clones/Coq/qecc' &
git clone https://github.com/facebookresearch/shack '/storage/nvme5/new_clones/Coq/shack' &
git clone https://github.com/tinkerrobot/Software_Foundations_Solutions2 '/storage/nvme5/new_clones/Coq/Software_Foundations_Solutions2' &
git clone https://github.com/robdockins/domains '/storage/nvme5/new_clones/Coq/domains' &
git clone https://github.com/TheoWinterhalter/sirtt '/storage/nvme5/new_clones/Coq/sirtt' &
git clone https://github.com/txyyss/FormalMath '/storage/nvme5/new_clones/Coq/FormalMath' &
git clone https://github.com/formalize/coq-evm '/storage/nvme5/new_clones/Coq/coq-evm' &
git clone https://github.com/annenkov/futhark-extract '/storage/nvme5/new_clones/Coq/futhark-extract' &
git clone https://github.com/artart78/coq-bitset '/storage/nvme5/new_clones/Coq/coq-bitset' &
git clone https://github.com/jwiegley/set-theory '/storage/nvme5/new_clones/Coq/set-theory' &
git clone https://github.com/DmxLarchey/Introduction-to-Coq '/storage/nvme5/new_clones/Coq/Introduction-to-Coq' &
git clone https://github.com/brightfu/CertiuCOS2 '/storage/nvme5/new_clones/Coq/CertiuCOS2' &
git clone https://github.com/rocq-archive/fermat4 '/storage/nvme5/new_clones/Coq/fermat4' &
git clone https://github.com/inQWIRE/LinearTypingContexts '/storage/nvme5/new_clones/Coq/LinearTypingContexts' &
git clone https://github.com/samuelgruetter/coq-tricks '/storage/nvme5/new_clones/Coq/coq-tricks' &
git clone https://github.com/Barry-Jay/Tree-calculus '/storage/nvme5/new_clones/Coq/Tree-calculus' &
git clone https://github.com/tm507211/CoqPerceptron '/storage/nvme5/new_clones/Coq/CoqPerceptron' &
git clone https://github.com/DmxLarchey/Coq-Phase-Semantics '/storage/nvme5/new_clones/Coq/Coq-Phase-Semantics' &
git clone https://github.com/dbp/literatecoq '/storage/nvme5/new_clones/Coq/literatecoq' &
git clone https://github.com/uncomputable/natural-number-game '/storage/nvme5/new_clones/Coq/natural-number-game' &
git clone https://github.com/rocq-archive/propcalc '/storage/nvme5/new_clones/Coq/propcalc' &
git clone https://github.com/rocq-archive/containers '/storage/nvme5/new_clones/Coq/containers' &
git clone https://github.com/uwplse/analytics-data '/storage/nvme5/new_clones/Coq/analytics-data' &
git clone https://github.com/funcao/LML '/storage/nvme5/new_clones/Coq/LML' &
git clone https://github.com/sweirich/equations-ln '/storage/nvme5/new_clones/Coq/equations-ln' &
git clone https://github.com/verified-network-toolchain/Verified-FEC '/storage/nvme5/new_clones/Coq/Verified-FEC' &
git clone https://github.com/bmsherman/finite '/storage/nvme5/new_clones/Coq/finite' &
git clone https://github.com/mit-pdos/deepspec-pocs '/storage/nvme5/new_clones/Coq/deepspec-pocs' &
git clone https://github.com/wangjwchn/sparcv8-coq '/storage/nvme5/new_clones/Coq/sparcv8-coq' &
git clone https://github.com/sarahzrf/coq-depleted '/storage/nvme5/new_clones/Coq/coq-depleted' &
git clone https://github.com/lsils/date2020_experiments '/storage/nvme5/new_clones/Coq/date2020_experiments' &
git clone https://github.com/thery/Plouffe '/storage/nvme5/new_clones/Coq/Plouffe' &
git clone https://github.com/aa755/paramcoq-iff '/storage/nvme5/new_clones/Coq/paramcoq-iff' &
git clone https://github.com/palmskog/ocaml-light '/storage/nvme5/new_clones/Coq/ocaml-light' &
git clone https://github.com/TheoWinterhalter/ett-to-itt '/storage/nvme5/new_clones/Coq/ett-to-itt' &
git clone https://github.com/yforster/coq-synthetic-computability '/storage/nvme5/new_clones/Coq/coq-synthetic-computability' &
git clone https://github.com/holgerthies/coq-aern '/storage/nvme5/new_clones/Coq/coq-aern' &
git clone https://github.com/Eelis/hybrid '/storage/nvme5/new_clones/Coq/hybrid' &
git clone https://github.com/gstew5/cage '/storage/nvme5/new_clones/Coq/cage' &
git clone https://github.com/jbapple/priority-queues '/storage/nvme5/new_clones/Coq/priority-queues' &
git clone https://github.com/cornell-netlab/sigcomm21-tutorial '/storage/nvme5/new_clones/Coq/sigcomm21-tutorial' &
git clone https://github.com/progval/LambdaCert '/storage/nvme5/new_clones/Coq/LambdaCert' &
git clone https://github.com/Mbodin/coq-alternative-facts '/storage/nvme5/new_clones/Coq/coq-alternative-facts' &
git clone https://github.com/SrikanthGadde/KalmanFilter-FPGA '/storage/nvme5/new_clones/Coq/KalmanFilter-FPGA' &
git clone https://github.com/gmalecha/coq-extensible-records '/storage/nvme5/new_clones/Coq/coq-extensible-records' &
git clone https://github.com/martijnvermaat/infinitary-rewriting-coq '/storage/nvme5/new_clones/Coq/infinitary-rewriting-coq' &
git clone https://github.com/wricciot/nullSQL '/storage/nvme5/new_clones/Coq/nullSQL' &
git clone https://github.com/smunaut/ecp5-speed '/storage/nvme5/new_clones/Coq/ecp5-speed' &
git clone https://github.com/formal-land/coq-of-go '/storage/nvme5/new_clones/Coq/coq-of-go' &
git clone https://github.com/o29/n2o '/storage/nvme5/new_clones/Coq/n2o' &
