#!/bin/bash

git clone https://github.com/opendtrace/toolkit '/storage/nvme5/new_clones/DTrace/toolkit' &
git clone https://github.com/brendangregg/DTrace-tools '/storage/nvme5/new_clones/DTrace/DTrace-tools' &
git clone https://github.com/paulross/dtrace-py '/storage/nvme5/new_clones/DTrace/dtrace-py' &
git clone https://github.com/Gibberlings3/BG1NPC '/storage/nvme5/new_clones/DTrace/BG1NPC' &
git clone https://github.com/EugVV/PSTEE-russian '/storage/nvme5/new_clones/DTrace/PSTEE-russian' &
git clone https://github.com/kdavyd/dtrace '/storage/nvme5/new_clones/DTrace/dtrace' &
git clone https://github.com/evanmiller/tracewrite '/storage/nvme5/new_clones/DTrace/tracewrite' &
git clone https://github.com/Gibberlings3/EE_Fixpack '/storage/nvme5/new_clones/DTrace/EE_Fixpack' &
git clone https://github.com/Pocket-Plane-Group/UnfinishedBusiness '/storage/nvme5/new_clones/DTrace/UnfinishedBusiness' &
git clone https://github.com/UnearthedArcana/Scales_of_Balance '/storage/nvme5/new_clones/DTrace/Scales_of_Balance' &
git clone https://github.com/siebenmann/cks-dtrace '/storage/nvme5/new_clones/DTrace/cks-dtrace' &
git clone https://github.com/thlorenz/dox '/storage/nvme5/new_clones/DTrace/dox' &
git clone https://github.com/UnearthedArcana/NPC_EE '/storage/nvme5/new_clones/DTrace/NPC_EE' &
git clone https://github.com/Gibberlings3/BG2-Fixpack '/storage/nvme5/new_clones/DTrace/BG2-Fixpack' &
git clone https://github.com/Lehona/Ikarus '/storage/nvme5/new_clones/DTrace/Ikarus' &
git clone https://github.com/Argent77/A7-BagsOfTorment '/storage/nvme5/new_clones/DTrace/A7-BagsOfTorment' &
git clone https://github.com/Gibberlings3/BS_Baldurans_Seatower '/storage/nvme5/new_clones/DTrace/BS_Baldurans_Seatower' &
git clone https://github.com/RoxanneSHS/SandrahEET '/storage/nvme5/new_clones/DTrace/SandrahEET' &
git clone https://github.com/Pocket-Plane-Group/Item_Upgrade '/storage/nvme5/new_clones/DTrace/Item_Upgrade' &
git clone https://github.com/Argent77/A7-Achievements '/storage/nvme5/new_clones/DTrace/A7-Achievements' &
git clone https://github.com/Argent77/A7-TotLM-BG2EE '/storage/nvme5/new_clones/DTrace/A7-TotLM-BG2EE' &
git clone https://github.com/Gibberlings3/BG_Quests_And_Encounters '/storage/nvme5/new_clones/DTrace/BG_Quests_And_Encounters' &
git clone https://github.com/Argent77/DjinniCompanion '/storage/nvme5/new_clones/DTrace/DjinniCompanion' &
git clone https://github.com/UnearthedArcana/Faiths_and_Powers '/storage/nvme5/new_clones/DTrace/Faiths_and_Powers' &
git clone https://github.com/aquadrizzt/PowerOfBelief '/storage/nvme5/new_clones/DTrace/PowerOfBelief' &
git clone https://github.com/Gibberlings3/WheelsOfProphecy '/storage/nvme5/new_clones/DTrace/WheelsOfProphecy' &
git clone https://github.com/Spellhold-Studios/NTotSC '/storage/nvme5/new_clones/DTrace/NTotSC' &
git clone https://github.com/Gibberlings3/EndlessBG1 '/storage/nvme5/new_clones/DTrace/EndlessBG1' &
git clone https://github.com/Gibberlings3/CowledMenace '/storage/nvme5/new_clones/DTrace/CowledMenace' &
git clone https://github.com/Gibberlings3/SoD-to-BG2EE-Item-Upgrade '/storage/nvme5/new_clones/DTrace/SoD-to-BG2EE-Item-Upgrade' &
git clone https://github.com/afborchert/lilith-multipass-modula2-compiler '/storage/nvme5/new_clones/DTrace/lilith-multipass-modula2-compiler' &
git clone https://github.com/ArtemiusI/Bardic-Wonders '/storage/nvme5/new_clones/DTrace/Bardic-Wonders' &
git clone https://github.com/Pocket-Plane-Group/Branwen_for_BGII '/storage/nvme5/new_clones/DTrace/Branwen_for_BGII' &
git clone https://github.com/ahrens/dtrace '/storage/nvme5/new_clones/DTrace/dtrace' &
git clone https://github.com/InfinityMods/FishingForTrouble '/storage/nvme5/new_clones/DTrace/FishingForTrouble' &
git clone https://github.com/aquadrizzt/Undivided '/storage/nvme5/new_clones/DTrace/Undivided' &
git clone https://github.com/Renegade0/msfm '/storage/nvme5/new_clones/DTrace/msfm' &
git clone https://github.com/Pocket-Plane-Group/Banter_Pack '/storage/nvme5/new_clones/DTrace/Banter_Pack' &
git clone https://github.com/SpellholdStudios/Region_of_Terror '/storage/nvme5/new_clones/DTrace/Region_of_Terror' &
git clone https://github.com/cadets/dtrace-scripts '/storage/nvme5/new_clones/DTrace/dtrace-scripts' &
git clone https://github.com/Gibberlings3/The_Calling '/storage/nvme5/new_clones/DTrace/The_Calling' &
git clone https://github.com/SpellholdStudios/Shadows_over_Soubar '/storage/nvme5/new_clones/DTrace/Shadows_over_Soubar' &
git clone https://github.com/The-Gate-Project/IWD1_EET '/storage/nvme5/new_clones/DTrace/IWD1_EET' &
git clone https://github.com/RoxanneSHS/Corwin '/storage/nvme5/new_clones/DTrace/Corwin' &
git clone https://github.com/Gitjas/Ascalons_Questpack '/storage/nvme5/new_clones/DTrace/Ascalons_Questpack' &
git clone https://github.com/RoxanneSHS/SandrahToT '/storage/nvme5/new_clones/DTrace/SandrahToT' &
git clone https://github.com/CrevsDaak/thalan '/storage/nvme5/new_clones/DTrace/thalan' &
git clone https://github.com/subtledoctor/SubtleD_Spell_Tweaks '/storage/nvme5/new_clones/DTrace/SubtleD_Spell_Tweaks' &
git clone https://github.com/Spellhold-Studios/Adrian-NPC '/storage/nvme5/new_clones/DTrace/Adrian-NPC' &
git clone https://github.com/Spellhold-Studios/Edwin-Romance '/storage/nvme5/new_clones/DTrace/Edwin-Romance' &
git clone https://github.com/Pocket-Plane-Group/Xan_for_BGII '/storage/nvme5/new_clones/DTrace/Xan_for_BGII' &
git clone https://github.com/SpellholdStudios/Check_the_Bodies '/storage/nvme5/new_clones/DTrace/Check_the_Bodies' &
git clone https://github.com/AngelGryph/MadeInHeaven_ItemPack '/storage/nvme5/new_clones/DTrace/MadeInHeaven_ItemPack' &
git clone https://github.com/Austin-BG/HTaM '/storage/nvme5/new_clones/DTrace/HTaM' &
git clone https://github.com/Gibberlings3/Kivan_and_Deheriana '/storage/nvme5/new_clones/DTrace/Kivan_and_Deheriana' &
git clone https://github.com/ArtemiusI/Sirene-NPC '/storage/nvme5/new_clones/DTrace/Sirene-NPC' &
git clone https://github.com/Gibberlings3/transitions '/storage/nvme5/new_clones/DTrace/transitions' &
git clone https://github.com/UnearthedArcana/B_Spells '/storage/nvme5/new_clones/DTrace/B_Spells' &
git clone https://github.com/Pocket-Plane-Group/Back_to_Brynnlaw '/storage/nvme5/new_clones/DTrace/Back_to_Brynnlaw' &
git clone https://github.com/InfinityMods/LongerRoadEE '/storage/nvme5/new_clones/DTrace/LongerRoadEE' &
git clone https://github.com/TotalMilk90/gorgon '/storage/nvme5/new_clones/DTrace/gorgon' &
git clone https://github.com/SpellholdStudios/RuadRofhessaItemUpgrade '/storage/nvme5/new_clones/DTrace/RuadRofhessaItemUpgrade' &
git clone https://github.com/Argent77/A7-GolemConstruction '/storage/nvme5/new_clones/DTrace/A7-GolemConstruction' &
git clone https://github.com/ArtemiusI/House-Rule-Tweaks '/storage/nvme5/new_clones/DTrace/House-Rule-Tweaks' &
