#!/bin/bash

git clone https://github.com/kaienfr/Font '/storage/nvme5/new_clones/Eiffel/Font' &
git clone https://github.com/makenowjust/quine '/storage/nvme5/new_clones/Eiffel/quine' &
git clone https://github.com/gobo-eiffel/gobo '/storage/nvme5/new_clones/Eiffel/gobo' &
git clone https://github.com/MagerValp/ArcadeGameSelector '/storage/nvme5/new_clones/Eiffel/ArcadeGameSelector' &
git clone https://github.com/uobdv/Design-Verification '/storage/nvme5/new_clones/Eiffel/Design-Verification' &
git clone https://github.com/EiffelSoftware/EiffelStudio '/storage/nvme5/new_clones/Eiffel/EiffelStudio' &
git clone https://github.com/EiffelWebFramework/EWF '/storage/nvme5/new_clones/Eiffel/EWF' &
git clone https://github.com/shihyu/MyTool '/storage/nvme5/new_clones/Eiffel/MyTool' &
git clone https://github.com/ttencate/aoc2017 '/storage/nvme5/new_clones/Eiffel/aoc2017' &
git clone https://github.com/openEHR/adl-tools '/storage/nvme5/new_clones/Eiffel/adl-tools' &
git clone https://github.com/tioui/Eiffel_Game2 '/storage/nvme5/new_clones/Eiffel/Eiffel_Game2' &
git clone https://github.com/eiffelhub/json '/storage/nvme5/new_clones/Eiffel/json' &
git clone https://github.com/finnianr/Eiffel-Loop '/storage/nvme5/new_clones/Eiffel/Eiffel-Loop' &
git clone https://github.com/owencqueen/PolymerGNN '/storage/nvme5/new_clones/Eiffel/PolymerGNN' &
git clone https://github.com/tioui/eiffel_game_lib '/storage/nvme5/new_clones/Eiffel/eiffel_game_lib' &
git clone https://github.com/peberlein/WEE '/storage/nvme5/new_clones/Eiffel/WEE' &
git clone https://github.com/oligot/epm '/storage/nvme5/new_clones/Eiffel/epm' &
git clone https://github.com/jvelilla/EiffelWebNino '/storage/nvme5/new_clones/Eiffel/EiffelWebNino' &
git clone https://github.com/EiffelSoftware/libraries '/storage/nvme5/new_clones/Eiffel/libraries' &
git clone https://github.com/eiffelhub/Traffic3 '/storage/nvme5/new_clones/Eiffel/Traffic3' &
git clone https://github.com/berenddeboer/xplain2sql '/storage/nvme5/new_clones/Eiffel/xplain2sql' &
git clone https://github.com/jvelilla/RosettaCode '/storage/nvme5/new_clones/Eiffel/RosettaCode' &
git clone https://github.com/jocelyn/bricabrac '/storage/nvme5/new_clones/Eiffel/bricabrac' &
git clone https://github.com/nmaguirre/eiffel-2048 '/storage/nvme5/new_clones/Eiffel/eiffel-2048' &
git clone https://github.com/mapr/drill-test-framework '/storage/nvme5/new_clones/Eiffel/drill-test-framework' &
git clone https://github.com/jocelyn/eel '/storage/nvme5/new_clones/Eiffel/eel' &
git clone https://github.com/schoelle/algae '/storage/nvme5/new_clones/Eiffel/algae' &
git clone https://github.com/EiffelWebFramework/HAL '/storage/nvme5/new_clones/Eiffel/HAL' &
git clone https://github.com/scottgw/language-eiffel '/storage/nvme5/new_clones/Eiffel/language-eiffel' &
git clone https://github.com/EiffelSoftware/traffic '/storage/nvme5/new_clones/Eiffel/traffic' &
git clone https://github.com/rmatil/uzh-software-construction '/storage/nvme5/new_clones/Eiffel/uzh-software-construction' &
git clone https://github.com/safe-eiffel/lib '/storage/nvme5/new_clones/Eiffel/lib' &
git clone https://github.com/wolandscat/EOMF '/storage/nvme5/new_clones/Eiffel/EOMF' &
git clone https://github.com/safe-eiffel/ecli '/storage/nvme5/new_clones/Eiffel/ecli' &
git clone https://github.com/seventh/codemetre '/storage/nvme5/new_clones/Eiffel/codemetre' &
