#!/bin/bash

git clone https://github.com/LuxLang/lux '/storage/nvme5/new_clones/Emacs Lisp/lux' &
git clone https://github.com/abo-abo/lispy '/storage/nvme5/new_clones/Emacs Lisp/lispy' &
git clone https://github.com/emacs-tree-sitter/elisp-tree-sitter '/storage/nvme5/new_clones/Emacs Lisp/elisp-tree-sitter' &
git clone https://github.com/a-schaefers/systemE '/storage/nvme5/new_clones/Emacs Lisp/systemE' &
git clone https://github.com/magit/emacsql '/storage/nvme5/new_clones/Emacs Lisp/emacsql' &
git clone https://github.com/rememberYou/.emacs.d '/storage/nvme5/new_clones/Emacs Lisp/.emacs.d' &
git clone https://github.com/stanaka/dash-at-point '/storage/nvme5/new_clones/Emacs Lisp/dash-at-point' &
git clone https://github.com/susam/emacs4cl '/storage/nvme5/new_clones/Emacs Lisp/emacs4cl' &
git clone https://github.com/kiwanami/emacs-edbi '/storage/nvme5/new_clones/Emacs Lisp/emacs-edbi' &
git clone https://github.com/gongo/emacs-nes '/storage/nvme5/new_clones/Emacs Lisp/emacs-nes' &
git clone https://github.com/Fuco1/litable '/storage/nvme5/new_clones/Emacs Lisp/litable' &
git clone https://github.com/drym-org/symex.el '/storage/nvme5/new_clones/Emacs Lisp/symex.el' &
git clone https://github.com/radian-software/el-patch '/storage/nvme5/new_clones/Emacs Lisp/el-patch' &
git clone https://github.com/Malabarba/names '/storage/nvme5/new_clones/Emacs Lisp/names' &
git clone https://github.com/xuchunyang/elisp-demos '/storage/nvme5/new_clones/Emacs Lisp/elisp-demos' &
git clone https://github.com/skeeto/emacs-aio '/storage/nvme5/new_clones/Emacs Lisp/emacs-aio' &
git clone https://github.com/emacsorphanage/ov '/storage/nvme5/new_clones/Emacs Lisp/ov' &
git clone https://github.com/ch11ng/xelb '/storage/nvme5/new_clones/Emacs Lisp/xelb' &
git clone https://github.com/emacs-evil/evil-cleverparens '/storage/nvme5/new_clones/Emacs Lisp/evil-cleverparens' &
git clone https://github.com/clojure-emacs/clomacs '/storage/nvme5/new_clones/Emacs Lisp/clomacs' &
git clone https://github.com/tromey/el-compilador '/storage/nvme5/new_clones/Emacs Lisp/el-compilador' &
git clone https://github.com/kiwanami/emacs-epc '/storage/nvme5/new_clones/Emacs Lisp/emacs-epc' &
git clone https://github.com/rocky/elisp-bytecode '/storage/nvme5/new_clones/Emacs Lisp/elisp-bytecode' &
git clone https://github.com/jtmoulia/elisp-koans '/storage/nvme5/new_clones/Emacs Lisp/elisp-koans' &
git clone https://github.com/xiongtx/eros '/storage/nvme5/new_clones/Emacs Lisp/eros' &
git clone https://github.com/waymondo/frog-jump-buffer '/storage/nvme5/new_clones/Emacs Lisp/frog-jump-buffer' &
git clone https://github.com/Silex/elmacro '/storage/nvme5/new_clones/Emacs Lisp/elmacro' &
git clone https://github.com/purcell/elisp-slime-nav '/storage/nvme5/new_clones/Emacs Lisp/elisp-slime-nav' &
git clone https://github.com/hober/html5-el '/storage/nvme5/new_clones/Emacs Lisp/html5-el' &
git clone https://github.com/cute-jumper/parsec.el '/storage/nvme5/new_clones/Emacs Lisp/parsec.el' &
git clone https://github.com/Wilfred/elisp-refs '/storage/nvme5/new_clones/Emacs Lisp/elisp-refs' &
git clone https://github.com/nicferrier/elmarmalade '/storage/nvme5/new_clones/Emacs Lisp/elmarmalade' &
git clone https://github.com/oakmac/parinfer-elisp '/storage/nvme5/new_clones/Emacs Lisp/parinfer-elisp' &
git clone https://github.com/Wilfred/refine '/storage/nvme5/new_clones/Emacs Lisp/refine' &
git clone https://github.com/redraiment/wechat.el '/storage/nvme5/new_clones/Emacs Lisp/wechat.el' &
git clone https://github.com/cadadr/elisp '/storage/nvme5/new_clones/Emacs Lisp/elisp' &
git clone https://github.com/RenWenshan/emacs-lisp-intro-solutions '/storage/nvme5/new_clones/Emacs Lisp/emacs-lisp-intro-solutions' &
git clone https://github.com/Wilfred/tco.el '/storage/nvme5/new_clones/Emacs Lisp/tco.el' &
git clone https://github.com/cyrus-and/comb '/storage/nvme5/new_clones/Emacs Lisp/comb' &
git clone https://github.com/Malabarba/speed-of-thought-lisp '/storage/nvme5/new_clones/Emacs Lisp/speed-of-thought-lisp' &
git clone https://github.com/andreasjansson/language-detection.el '/storage/nvme5/new_clones/Emacs Lisp/language-detection.el' &
git clone https://github.com/aspiers/etrace '/storage/nvme5/new_clones/Emacs Lisp/etrace' &
git clone https://github.com/mishoo/elisp-reader.el '/storage/nvme5/new_clones/Emacs Lisp/elisp-reader.el' &
git clone https://github.com/skeeto/at-el '/storage/nvme5/new_clones/Emacs Lisp/at-el' &
git clone https://github.com/mmontone/lisp-system-browser '/storage/nvme5/new_clones/Emacs Lisp/lisp-system-browser' &
git clone https://github.com/gonewest818/elisp-lint '/storage/nvme5/new_clones/Emacs Lisp/elisp-lint' &
git clone https://github.com/tumashu/el2org '/storage/nvme5/new_clones/Emacs Lisp/el2org' &
git clone https://github.com/Wilfred/elisp-def '/storage/nvme5/new_clones/Emacs Lisp/elisp-def' &
git clone https://github.com/Fanael/highlight-defined '/storage/nvme5/new_clones/Emacs Lisp/highlight-defined' &
git clone https://github.com/rougier/emacs-splash '/storage/nvme5/new_clones/Emacs Lisp/emacs-splash' &
git clone https://github.com/clojure-emacs/parseedn '/storage/nvme5/new_clones/Emacs Lisp/parseedn' &
git clone https://github.com/AbstProcDo/Master-Emacs-Lisp-with-Solid-Procedures '/storage/nvme5/new_clones/Emacs Lisp/Master-Emacs-Lisp-with-Solid-Procedures' &
git clone https://github.com/tkf/emacs-python-environment '/storage/nvme5/new_clones/Emacs Lisp/emacs-python-environment' &
git clone https://github.com/positron-solutions/elisp-repo-kit '/storage/nvme5/new_clones/Emacs Lisp/elisp-repo-kit' &
git clone https://github.com/Lindydancer/lisp-extra-font-lock '/storage/nvme5/new_clones/Emacs Lisp/lisp-extra-font-lock' &
git clone https://github.com/rolandwalker/anaphora '/storage/nvme5/new_clones/Emacs Lisp/anaphora' &
