#!/bin/bash

git clone https://github.com/ggandor/leap.nvim '/storage/nvme5/new_clones/Fennel/leap.nvim' &
git clone https://github.com/bakpakin/Fennel '/storage/nvme5/new_clones/Fennel/Fennel' &
git clone https://github.com/Olical/conjure '/storage/nvme5/new_clones/Fennel/conjure' &
git clone https://github.com/ggandor/lightspeed.nvim '/storage/nvme5/new_clones/Fennel/lightspeed.nvim' &
git clone https://github.com/nyoom-engineering/nyoom.nvim '/storage/nvme5/new_clones/Fennel/nyoom.nvim' &
git clone https://github.com/nyoom-engineering/oxocarbon.nvim '/storage/nvme5/new_clones/Fennel/oxocarbon.nvim' &
git clone https://github.com/Olical/aniseed '/storage/nvme5/new_clones/Fennel/aniseed' &
git clone https://github.com/agzam/spacehammer '/storage/nvme5/new_clones/Fennel/spacehammer' &
git clone https://github.com/Olical/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/camspiers/snap '/storage/nvme5/new_clones/Fennel/snap' &
git clone https://github.com/rktjmp/hotpot.nvim '/storage/nvme5/new_clones/Fennel/hotpot.nvim' &
git clone https://github.com/udayvir-singh/tangerine.nvim '/storage/nvme5/new_clones/Fennel/tangerine.nvim' &
git clone https://github.com/gpanders/nvim-parinfer '/storage/nvme5/new_clones/Fennel/nvim-parinfer' &
git clone https://github.com/rafaeldelboni/cajus-nvim '/storage/nvme5/new_clones/Fennel/cajus-nvim' &
git clone https://github.com/Olical/magic-kit '/storage/nvme5/new_clones/Fennel/magic-kit' &
git clone https://github.com/udayvir-singh/hibiscus.nvim '/storage/nvme5/new_clones/Fennel/hibiscus.nvim' &
git clone https://github.com/alexaandru/nvim-lspupdate '/storage/nvme5/new_clones/Fennel/nvim-lspupdate' &
git clone https://github.com/rktjmp/paperplanes.nvim '/storage/nvme5/new_clones/Fennel/paperplanes.nvim' &
git clone https://github.com/rktjmp/highlight-current-n.nvim '/storage/nvme5/new_clones/Fennel/highlight-current-n.nvim' &
git clone https://github.com/m15a/flake-awesome-neovim-plugins '/storage/nvme5/new_clones/Fennel/flake-awesome-neovim-plugins' &
git clone https://github.com/rktjmp/shenzhen-solitaire.nvim '/storage/nvme5/new_clones/Fennel/shenzhen-solitaire.nvim' &
git clone https://github.com/Grazfather/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/rktjmp/pact.nvim '/storage/nvme5/new_clones/Fennel/pact.nvim' &
git clone https://github.com/practicalli/neovim-config-redux '/storage/nvme5/new_clones/Fennel/neovim-config-redux' &
git clone https://github.com/rafaeldelboni/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/hudclark/grpc-nvim '/storage/nvme5/new_clones/Fennel/grpc-nvim' &
git clone https://github.com/aileot/nvim-laurel '/storage/nvme5/new_clones/Fennel/nvim-laurel' &
git clone https://github.com/gbaptista/fnx '/storage/nvme5/new_clones/Fennel/fnx' &
git clone https://github.com/jhchabran/nvim-config '/storage/nvme5/new_clones/Fennel/nvim-config' &
git clone https://github.com/adelarsq/neovcs.vim '/storage/nvme5/new_clones/Fennel/neovcs.vim' &
git clone https://github.com/datwaft/themis.nvim '/storage/nvme5/new_clones/Fennel/themis.nvim' &
git clone https://github.com/gpanders/fennel-repl.nvim '/storage/nvme5/new_clones/Fennel/fennel-repl.nvim' &
git clone https://github.com/Dkendal/nvim-minor-mode '/storage/nvme5/new_clones/Fennel/nvim-minor-mode' &
git clone https://github.com/rinx/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/alexaandru/nvim-config '/storage/nvme5/new_clones/Fennel/nvim-config' &
git clone https://github.com/shtwzrd/awesome-wm-config '/storage/nvme5/new_clones/Fennel/awesome-wm-config' &
git clone https://github.com/TunkShif/nvim '/storage/nvme5/new_clones/Fennel/nvim' &
git clone https://github.com/mizlan/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/cljoly/bepo.nvim '/storage/nvme5/new_clones/Fennel/bepo.nvim' &
git clone https://github.com/gpanders/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/gbaptista/sublime-text-fennel '/storage/nvme5/new_clones/Fennel/sublime-text-fennel' &
git clone https://github.com/Sharparam/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/tjdevries/monkey.nvim '/storage/nvme5/new_clones/Fennel/monkey.nvim' &
git clone https://github.com/joaofnds/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/okkdev/dotnix '/storage/nvme5/new_clones/Fennel/dotnix' &
git clone https://github.com/aktersnurra/nvim '/storage/nvme5/new_clones/Fennel/nvim' &
git clone https://github.com/tssm/.config '/storage/nvme5/new_clones/Fennel/.config' &
git clone https://github.com/lrangell/theme-cycler.nvim '/storage/nvme5/new_clones/Fennel/theme-cycler.nvim' &
git clone https://github.com/Grazfather/blinker.nvim '/storage/nvme5/new_clones/Fennel/blinker.nvim' &
git clone https://github.com/fennec-nvim/fennec-nvim '/storage/nvme5/new_clones/Fennel/fennec-nvim' &
git clone https://github.com/Massolari/neovim '/storage/nvme5/new_clones/Fennel/neovim' &
git clone https://github.com/stefanvanburen/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/telent/slab '/storage/nvme5/new_clones/Fennel/slab' &
git clone https://github.com/davidmh/dot-files '/storage/nvme5/new_clones/Fennel/dot-files' &
git clone https://github.com/alexaandru/fennel-nvim '/storage/nvme5/new_clones/Fennel/fennel-nvim' &
git clone https://github.com/meh/neovimmeh '/storage/nvme5/new_clones/Fennel/neovimmeh' &
git clone https://github.com/steelsojka/dotfiles2 '/storage/nvme5/new_clones/Fennel/dotfiles2' &
git clone https://github.com/vloth/dotfiles '/storage/nvme5/new_clones/Fennel/dotfiles' &
git clone https://github.com/jaawerth/fnldocstor '/storage/nvme5/new_clones/Fennel/fnldocstor' &
git clone https://github.com/Cassin01/emacs-key-source.nvim '/storage/nvme5/new_clones/Fennel/emacs-key-source.nvim' &
git clone https://github.com/harrygallagher4/nvim-parinfer-rust '/storage/nvme5/new_clones/Fennel/nvim-parinfer-rust' &
git clone https://github.com/butterywombat/dotfileserino '/storage/nvme5/new_clones/Fennel/dotfileserino' &
git clone https://github.com/harrygallagher4/nvim '/storage/nvme5/new_clones/Fennel/nvim' &
git clone https://github.com/alexaandru/froggy '/storage/nvme5/new_clones/Fennel/froggy' &
git clone https://github.com/Cassin01/nvim-conf '/storage/nvme5/new_clones/Fennel/nvim-conf' &
git clone https://github.com/aktersnurra/minibar.nvim '/storage/nvme5/new_clones/Fennel/minibar.nvim' &
