#!/bin/bash

git clone https://github.com/mozilla/send '/storage/nvme5/new_clones/FreeMarker/send' &
git clone https://github.com/lenve/CoolMeeting '/storage/nvme5/new_clones/FreeMarker/CoolMeeting' &
git clone https://github.com/JessYanCoding/MVPArmsTemplate '/storage/nvme5/new_clones/FreeMarker/MVPArmsTemplate' &
git clone https://github.com/benoitletondor/Android-Studio-MVP-template '/storage/nvme5/new_clones/FreeMarker/Android-Studio-MVP-template' &
git clone https://github.com/mozilla-services/screenshots '/storage/nvme5/new_clones/FreeMarker/screenshots' &
git clone https://github.com/kanytu/Android-studio-material-template '/storage/nvme5/new_clones/FreeMarker/Android-studio-material-template' &
git clone https://github.com/Trendyol/android-guidelines '/storage/nvme5/new_clones/FreeMarker/android-guidelines' &
git clone https://github.com/ckdevrel/RecyclerViewTemplate '/storage/nvme5/new_clones/FreeMarker/RecyclerViewTemplate' &
git clone https://github.com/AweiLoveAndroid/The-pit-of-the-Android-Studio '/storage/nvme5/new_clones/FreeMarker/The-pit-of-the-Android-Studio' &
git clone https://github.com/chenchengyin/android-studio-template '/storage/nvme5/new_clones/FreeMarker/android-studio-template' &
git clone https://github.com/JessYanCoding/ArmsComponent-Template '/storage/nvme5/new_clones/FreeMarker/ArmsComponent-Template' &
git clone https://github.com/mozilla/testpilot '/storage/nvme5/new_clones/FreeMarker/testpilot' &
git clone https://github.com/JessYanCoding/MVPArms-Module-Template '/storage/nvme5/new_clones/FreeMarker/MVPArms-Module-Template' &
git clone https://github.com/hs-web/hsweb-demo '/storage/nvme5/new_clones/FreeMarker/hsweb-demo' &
git clone https://github.com/WanAndroid/AndroidStudioTemplates '/storage/nvme5/new_clones/FreeMarker/AndroidStudioTemplates' &
git clone https://github.com/monkeylord/XposedTemplateForAS '/storage/nvme5/new_clones/FreeMarker/XposedTemplateForAS' &
git clone https://github.com/RayeWang/easyadmin '/storage/nvme5/new_clones/FreeMarker/easyadmin' &
git clone https://github.com/Alfresco/alfresco-keycloak-theme '/storage/nvme5/new_clones/FreeMarker/alfresco-keycloak-theme' &
git clone https://github.com/UKHomeOffice/keycloak-theme-govuk '/storage/nvme5/new_clones/FreeMarker/keycloak-theme-govuk' &
git clone https://github.com/niujt/Hospital '/storage/nvme5/new_clones/FreeMarker/Hospital' &
git clone https://github.com/mintern-java/functions '/storage/nvme5/new_clones/FreeMarker/functions' &
git clone https://github.com/Goldorion/Fabric-Generator-MCreator '/storage/nvme5/new_clones/FreeMarker/Fabric-Generator-MCreator' &
git clone https://github.com/inferno0303/TestPapaerGen-WebApp '/storage/nvme5/new_clones/FreeMarker/TestPapaerGen-WebApp' &
git clone https://github.com/vsay01/Android-Studio-MVP-Template-Google-Architecture '/storage/nvme5/new_clones/FreeMarker/Android-Studio-MVP-Template-Google-Architecture' &
git clone https://github.com/vipbooks/TableGo '/storage/nvme5/new_clones/FreeMarker/TableGo' &
git clone https://github.com/ckdevrel/MaterialTabsTemplate '/storage/nvme5/new_clones/FreeMarker/MaterialTabsTemplate' &
git clone https://github.com/MAXIMUS-DeltaWare/material-keycloak-theme '/storage/nvme5/new_clones/FreeMarker/material-keycloak-theme' &
git clone https://github.com/CodeLunatic/halo-theme-simple-bootstrap '/storage/nvme5/new_clones/FreeMarker/halo-theme-simple-bootstrap' &
git clone https://github.com/DVDAndroid/XposedModuleTemplate '/storage/nvme5/new_clones/FreeMarker/XposedModuleTemplate' &
git clone https://github.com/kiuchikeisuke/Android-Studio-CleanArchitecture-template-forKotlin '/storage/nvme5/new_clones/FreeMarker/Android-Studio-CleanArchitecture-template-forKotlin' &
git clone https://github.com/xuebusi/xstrap '/storage/nvme5/new_clones/FreeMarker/xstrap' &
git clone https://github.com/kuhnpeng/halo-theme-fantastic '/storage/nvme5/new_clones/FreeMarker/halo-theme-fantastic' &
git clone https://github.com/javacc21/javacc21 '/storage/nvme5/new_clones/FreeMarker/javacc21' &
git clone https://github.com/kirtan403/android-studio-live-templates '/storage/nvme5/new_clones/FreeMarker/android-studio-live-templates' &
git clone https://github.com/liaocp666/halo-theme-daisy '/storage/nvme5/new_clones/FreeMarker/halo-theme-daisy' &
git clone https://github.com/keycloak/keycloak-web '/storage/nvme5/new_clones/FreeMarker/keycloak-web' &
git clone https://github.com/europeana/keycloak-theme '/storage/nvme5/new_clones/FreeMarker/keycloak-theme' &
git clone https://github.com/gxstrap/xstrap '/storage/nvme5/new_clones/FreeMarker/xstrap' &
git clone https://github.com/kidinov/Ads-Mvp-Templates '/storage/nvme5/new_clones/FreeMarker/Ads-Mvp-Templates' &
git clone https://github.com/burakeregar/KotlinMvpTemplateGenerator '/storage/nvme5/new_clones/FreeMarker/KotlinMvpTemplateGenerator' &
git clone https://github.com/Programming-With-Love/solo-nexmoe '/storage/nvme5/new_clones/FreeMarker/solo-nexmoe' &
git clone https://github.com/riggaroo/android-studio-group-templates-mvp '/storage/nvme5/new_clones/FreeMarker/android-studio-group-templates-mvp' &
git clone https://github.com/brandonbai/pdfDemo '/storage/nvme5/new_clones/FreeMarker/pdfDemo' &
git clone https://github.com/orangy/ktor-heroku-start '/storage/nvme5/new_clones/FreeMarker/ktor-heroku-start' &
git clone https://github.com/AlfrescoArchive/alfresco-support-tools '/storage/nvme5/new_clones/FreeMarker/alfresco-support-tools' &
git clone https://github.com/corona-warn-app/cwa-verification-iam '/storage/nvme5/new_clones/FreeMarker/cwa-verification-iam' &
git clone https://github.com/vanishma/mybatisPlusGenerator '/storage/nvme5/new_clones/FreeMarker/mybatisPlusGenerator' &
git clone https://github.com/harshcrop/Cyboinsect-Keycloak-theme '/storage/nvme5/new_clones/FreeMarker/Cyboinsect-Keycloak-theme' &
git clone https://github.com/alxrodav/keycloak-theme '/storage/nvme5/new_clones/FreeMarker/keycloak-theme' &
git clone https://github.com/qingmei2/MVVM-Rhine-Template '/storage/nvme5/new_clones/FreeMarker/MVVM-Rhine-Template' &
git clone https://github.com/yengjin/springboot-layui-admin '/storage/nvme5/new_clones/FreeMarker/springboot-layui-admin' &
git clone https://github.com/njwlzh/codetool '/storage/nvme5/new_clones/FreeMarker/codetool' &
git clone https://github.com/congo-cc/congo-parser-generator '/storage/nvme5/new_clones/FreeMarker/congo-parser-generator' &
git clone https://github.com/JAdmin-JAVA/dbToDoc '/storage/nvme5/new_clones/FreeMarker/dbToDoc' &
git clone https://github.com/moqui/moqui-runtime '/storage/nvme5/new_clones/FreeMarker/moqui-runtime' &
git clone https://github.com/lin-liem/weicarus '/storage/nvme5/new_clones/FreeMarker/weicarus' &
git clone https://github.com/prolificinteractive/android-studio-templates '/storage/nvme5/new_clones/FreeMarker/android-studio-templates' &
git clone https://github.com/hhru/android-style-guide '/storage/nvme5/new_clones/FreeMarker/android-style-guide' &
git clone https://github.com/ratherblue/freemarker-debugger '/storage/nvme5/new_clones/FreeMarker/freemarker-debugger' &
git clone https://github.com/tekgainers/keycloak-recipes '/storage/nvme5/new_clones/FreeMarker/keycloak-recipes' &
git clone https://github.com/jordanamorais/lfrgs-frontend-samples '/storage/nvme5/new_clones/FreeMarker/lfrgs-frontend-samples' &
git clone https://github.com/OpenPj/keycloak-docker-quickstart '/storage/nvme5/new_clones/FreeMarker/keycloak-docker-quickstart' &
git clone https://github.com/LiveTyping/u2020-mvp-android-studio-template '/storage/nvme5/new_clones/FreeMarker/u2020-mvp-android-studio-template' &
git clone https://github.com/dteleguin/keycloak-dynamic-branding '/storage/nvme5/new_clones/FreeMarker/keycloak-dynamic-branding' &
git clone https://github.com/ernesto1/monochrome '/storage/nvme5/new_clones/FreeMarker/monochrome' &
git clone https://github.com/shihuc/VideoConverter '/storage/nvme5/new_clones/FreeMarker/VideoConverter' &
git clone https://github.com/Tellsea/mybatis-plus-code '/storage/nvme5/new_clones/FreeMarker/mybatis-plus-code' &
git clone https://github.com/zyw/v5cmsjava '/storage/nvme5/new_clones/FreeMarker/v5cmsjava' &
git clone https://github.com/FullHuman/Kotlin-Android-Studio-Templates '/storage/nvme5/new_clones/FreeMarker/Kotlin-Android-Studio-Templates' &
git clone https://github.com/mozilla/activate.mozilla.community '/storage/nvme5/new_clones/FreeMarker/activate.mozilla.community' &
git clone https://github.com/xm-online/xm-online '/storage/nvme5/new_clones/FreeMarker/xm-online' &
git clone https://github.com/cross266/halo-theme-iwtwin '/storage/nvme5/new_clones/FreeMarker/halo-theme-iwtwin' &
git clone https://github.com/salesforce-misc/perfGenie '/storage/nvme5/new_clones/FreeMarker/perfGenie' &
git clone https://github.com/kupferwerk/AndroidStudio-Base-Template '/storage/nvme5/new_clones/FreeMarker/AndroidStudio-Base-Template' &
git clone https://github.com/EdoardoVignati/java-deserialization-of-untrusted-data-poc '/storage/nvme5/new_clones/FreeMarker/java-deserialization-of-untrusted-data-poc' &
git clone https://github.com/madreain/AACHulkTemplate '/storage/nvme5/new_clones/FreeMarker/AACHulkTemplate' &
git clone https://github.com/0xHexE/carbon-keycloak-theme '/storage/nvme5/new_clones/FreeMarker/carbon-keycloak-theme' &
git clone https://github.com/MCreator/Generator-Forge-1.12.2 '/storage/nvme5/new_clones/FreeMarker/Generator-Forge-1.12.2' &
git clone https://github.com/rock-app/AAMVVM '/storage/nvme5/new_clones/FreeMarker/AAMVVM' &
git clone https://github.com/v5zhu/export-doc '/storage/nvme5/new_clones/FreeMarker/export-doc' &
git clone https://github.com/czetsuyatech/ct-keycloak-iam '/storage/nvme5/new_clones/FreeMarker/ct-keycloak-iam' &
git clone https://github.com/Microchip-MPLAB-Harmony/bootloader '/storage/nvme5/new_clones/FreeMarker/bootloader' &
git clone https://github.com/cloud-iam/keycloak-cloud-iam-theme '/storage/nvme5/new_clones/FreeMarker/keycloak-cloud-iam-theme' &
git clone https://github.com/ckdevrel/LoginAndroidStudioTemplate '/storage/nvme5/new_clones/FreeMarker/LoginAndroidStudioTemplate' &
git clone https://github.com/moqui/SimpleScreens '/storage/nvme5/new_clones/FreeMarker/SimpleScreens' &
git clone https://github.com/xsocket/ksa '/storage/nvme5/new_clones/FreeMarker/ksa' &
git clone https://github.com/BeJUG/bejug.github.io '/storage/nvme5/new_clones/FreeMarker/bejughub.io' &
git clone https://github.com/halo-dev/halo-theme-quick-starter '/storage/nvme5/new_clones/FreeMarker/halo-theme-quick-starter' &
git clone https://github.com/nkelemen18/koreui '/storage/nvme5/new_clones/FreeMarker/koreui' &
git clone https://github.com/wang-y/spring-boot-project-builder '/storage/nvme5/new_clones/FreeMarker/spring-boot-project-builder' &
git clone https://github.com/halo-dev/halo-theme-pinghsu '/storage/nvme5/new_clones/FreeMarker/halo-theme-pinghsu' &
git clone https://github.com/DuebassLei/excel-poi '/storage/nvme5/new_clones/FreeMarker/excel-poi' &
git clone https://github.com/chrisshayan/TechLooper '/storage/nvme5/new_clones/FreeMarker/TechLooper' &
git clone https://github.com/Rich709394/Android-Templates '/storage/nvme5/new_clones/FreeMarker/Android-Templates' &
git clone https://github.com/marcosholgado/demo-plugin '/storage/nvme5/new_clones/FreeMarker/demo-plugin' &
git clone https://github.com/TanJiaJunBeyond/AndroidGenericFrameworkTemplate '/storage/nvme5/new_clones/FreeMarker/AndroidGenericFrameworkTemplate' &
git clone https://github.com/MoeOxygen/halo-theme-fantasy '/storage/nvme5/new_clones/FreeMarker/halo-theme-fantasy' &
git clone https://github.com/zhuchuangang/spring-cloud-genisys '/storage/nvme5/new_clones/FreeMarker/spring-cloud-genisys' &
git clone https://github.com/Microchip-MPLAB-Harmony/core '/storage/nvme5/new_clones/FreeMarker/core' &
git clone https://github.com/holisticon/keycloak-theme-sample '/storage/nvme5/new_clones/FreeMarker/keycloak-theme-sample' &
git clone https://github.com/adrien-bougouin/KeyBench '/storage/nvme5/new_clones/FreeMarker/KeyBench' &
git clone https://github.com/rainbowcake/rainbowcake-templates '/storage/nvme5/new_clones/FreeMarker/rainbowcake-templates' &
git clone https://github.com/openstandia/keycloak-dockerfiles '/storage/nvme5/new_clones/FreeMarker/keycloak-dockerfiles' &
git clone https://github.com/mao-yuwei/paper_download '/storage/nvme5/new_clones/FreeMarker/paper_download' &
git clone https://github.com/NHS-digital-website/hippo '/storage/nvme5/new_clones/FreeMarker/hippo' &
git clone https://github.com/varabyte/kobweb-templates '/storage/nvme5/new_clones/FreeMarker/kobweb-templates' &
git clone https://github.com/alanshaw/pagination-freemarker-macros '/storage/nvme5/new_clones/FreeMarker/pagination-freemarker-macros' &
git clone https://github.com/kmmraj/androidcleancode-generator '/storage/nvme5/new_clones/FreeMarker/androidcleancode-generator' &
git clone https://github.com/OSC/keycloak-theme '/storage/nvme5/new_clones/FreeMarker/keycloak-theme' &
git clone https://github.com/ZdzCoding/AndroidTemplates '/storage/nvme5/new_clones/FreeMarker/AndroidTemplates' &
git clone https://github.com/ARM-software/CMSIS-Zone '/storage/nvme5/new_clones/FreeMarker/CMSIS-Zone' &
git clone https://github.com/Microchip-MPLAB-Harmony/usb '/storage/nvme5/new_clones/FreeMarker/usb' &
git clone https://github.com/radhikayusuf/android-template '/storage/nvme5/new_clones/FreeMarker/android-template' &
git clone https://github.com/2425358736/webrtc_live '/storage/nvme5/new_clones/FreeMarker/webrtc_live' &
git clone https://github.com/zhenghuiy/AndroidStudioTemplateTest '/storage/nvme5/new_clones/FreeMarker/AndroidStudioTemplateTest' &
git clone https://github.com/j2go/kotlin-bbs '/storage/nvme5/new_clones/FreeMarker/kotlin-bbs' &
git clone https://github.com/WebMobTechnologies/AndroidTemplates '/storage/nvme5/new_clones/FreeMarker/AndroidTemplates' &
git clone https://github.com/adessoTurkey/android-guidelines '/storage/nvme5/new_clones/FreeMarker/android-guidelines' &
git clone https://github.com/MagikLau/WeChatPlatformApplication '/storage/nvme5/new_clones/FreeMarker/WeChatPlatformApplication' &
git clone https://github.com/masztalski/DaggerTemplate '/storage/nvme5/new_clones/FreeMarker/DaggerTemplate' &
git clone https://github.com/naver/svc-template '/storage/nvme5/new_clones/FreeMarker/svc-template' &
git clone https://github.com/BugAngel/SaisSpring '/storage/nvme5/new_clones/FreeMarker/SaisSpring' &
git clone https://github.com/bachhoan88/MVVM-Template '/storage/nvme5/new_clones/FreeMarker/MVVM-Template' &
git clone https://github.com/guiyunweb2023/halo-theme-flex-block '/storage/nvme5/new_clones/FreeMarker/halo-theme-flex-block' &
git clone https://github.com/hacker-and-painter/spring-boot-code-generator '/storage/nvme5/new_clones/FreeMarker/spring-boot-code-generator' &
git clone https://github.com/CORDEA/android-aac-template '/storage/nvme5/new_clones/FreeMarker/android-aac-template' &
git clone https://github.com/goodluckforme/muc_mvp '/storage/nvme5/new_clones/FreeMarker/muc_mvp' &
git clone https://github.com/liulingfeng/Template '/storage/nvme5/new_clones/FreeMarker/Template' &
git clone https://github.com/mkoslacz/MoviperTemplateGenerator '/storage/nvme5/new_clones/FreeMarker/MoviperTemplateGenerator' &
git clone https://github.com/freedommedal/tkcg '/storage/nvme5/new_clones/FreeMarker/tkcg' &
git clone https://github.com/HappyWjl/easy-code '/storage/nvme5/new_clones/FreeMarker/easy-code' &
git clone https://github.com/codechimp-org/Android-Studio-Templates '/storage/nvme5/new_clones/FreeMarker/Android-Studio-Templates' &
git clone https://github.com/p-goetz/arc42-gradle '/storage/nvme5/new_clones/FreeMarker/arc42-gradle' &
git clone https://github.com/androidstarters/androidstarters-template '/storage/nvme5/new_clones/FreeMarker/androidstarters-template' &
git clone https://github.com/aerobase/aerobase-keycloak-theme '/storage/nvme5/new_clones/FreeMarker/aerobase-keycloak-theme' &
git clone https://github.com/stotem/GGCode '/storage/nvme5/new_clones/FreeMarker/GGCode' &
git clone https://github.com/roixa/RoixArchitectureTemplates '/storage/nvme5/new_clones/FreeMarker/RoixArchitectureTemplates' &
git clone https://github.com/ld4l-labs/vitrolib '/storage/nvme5/new_clones/FreeMarker/vitrolib' &
git clone https://github.com/kiegroup/drools-website '/storage/nvme5/new_clones/FreeMarker/drools-website' &
git clone https://github.com/esden/stm32cube-database '/storage/nvme5/new_clones/FreeMarker/stm32cube-database' &
git clone https://github.com/halo-dev/halo-theme-story '/storage/nvme5/new_clones/FreeMarker/halo-theme-story' &
git clone https://github.com/kasir-barati/docker '/storage/nvme5/new_clones/FreeMarker/docker' &
git clone https://github.com/jpotts/share-announcements '/storage/nvme5/new_clones/FreeMarker/share-announcements' &
git clone https://github.com/RedMadRobot/AndroidStudioTemplates '/storage/nvme5/new_clones/FreeMarker/AndroidStudioTemplates' &
git clone https://github.com/anqi270024/jexam '/storage/nvme5/new_clones/FreeMarker/jexam' &
git clone https://github.com/jonesde/OFBizMigrate '/storage/nvme5/new_clones/FreeMarker/OFBizMigrate' &
git clone https://github.com/quanzhian/generate-code '/storage/nvme5/new_clones/FreeMarker/generate-code' &
git clone https://github.com/myanbin/keycloak-theme-material '/storage/nvme5/new_clones/FreeMarker/keycloak-theme-material' &
git clone https://github.com/zak905/extending-keycloak-udemy-course '/storage/nvme5/new_clones/FreeMarker/extending-keycloak-udemy-course' &
git clone https://github.com/Phyxius/keycloak-touchid-fix '/storage/nvme5/new_clones/FreeMarker/keycloak-touchid-fix' &
git clone https://github.com/jboss-gpe-ref-archs/bpms_rhsso '/storage/nvme5/new_clones/FreeMarker/bpms_rhsso' &
git clone https://github.com/naproche/FLib '/storage/nvme5/new_clones/FreeMarker/FLib' &
git clone https://github.com/xuejike/word-tpl '/storage/nvme5/new_clones/FreeMarker/word-tpl' &
git clone https://github.com/fuxdong/Java2Word '/storage/nvme5/new_clones/FreeMarker/Java2Word' &
git clone https://github.com/MCreator/DemoPlugin '/storage/nvme5/new_clones/FreeMarker/DemoPlugin' &
git clone https://github.com/Wave-SYJ/document-management '/storage/nvme5/new_clones/FreeMarker/document-management' &
git clone https://github.com/attiqrehman1991/Android-Template-Activity-with-MVP-and-Repository-Pattern '/storage/nvme5/new_clones/FreeMarker/Android-Template-Activity-with-MVP-and-Repository-Pattern' &
git clone https://github.com/cai3178940/youran-template-01 '/storage/nvme5/new_clones/FreeMarker/youran-template-01' &
git clone https://github.com/MattDiMu/google-maps-magnolia '/storage/nvme5/new_clones/FreeMarker/google-maps-magnolia' &
git clone https://github.com/543210188/MybatisBuilder '/storage/nvme5/new_clones/FreeMarker/MybatisBuilder' &
git clone https://github.com/ljunn/solo-aragaki '/storage/nvme5/new_clones/FreeMarker/solo-aragaki' &
git clone https://github.com/keensoft/alfresco-datalist-constraints '/storage/nvme5/new_clones/FreeMarker/alfresco-datalist-constraints' &
git clone https://github.com/msvoren/alfresco-datatable-property '/storage/nvme5/new_clones/FreeMarker/alfresco-datatable-property' &
git clone https://github.com/HexlDL/Mvp '/storage/nvme5/new_clones/FreeMarker/Mvp' &
git clone https://github.com/DmitryZagr/docker-spark-hive-zeppelin '/storage/nvme5/new_clones/FreeMarker/docker-spark-hive-zeppelin' &
git clone https://github.com/Theembers/RKES '/storage/nvme5/new_clones/FreeMarker/RKES' &
git clone https://github.com/FusionAuth/fusionauth-example-kickstart '/storage/nvme5/new_clones/FreeMarker/fusionauth-example-kickstart' &
git clone https://github.com/wwhai/EasyLinkerForStudy '/storage/nvme5/new_clones/FreeMarker/EasyLinkerForStudy' &
git clone https://github.com/haiCheng-76/db_doc '/storage/nvme5/new_clones/FreeMarker/db_doc' &
git clone https://github.com/xebialabs-community/xld-docker-plugin '/storage/nvme5/new_clones/FreeMarker/xld-docker-plugin' &
git clone https://github.com/qingmei2/MVI-Rhine-Template '/storage/nvme5/new_clones/FreeMarker/MVI-Rhine-Template' &
git clone https://github.com/yangchaojiang/AAcHelper '/storage/nvme5/new_clones/FreeMarker/AAcHelper' &
git clone https://github.com/NHSDigital/DataDictionaryPublication '/storage/nvme5/new_clones/FreeMarker/DataDictionaryPublication' &
git clone https://github.com/pcqpcq/AndroidStudioTemplates '/storage/nvme5/new_clones/FreeMarker/AndroidStudioTemplates' &
git clone https://github.com/stctheproducer/docker-containers '/storage/nvme5/new_clones/FreeMarker/docker-containers' &
git clone https://github.com/CasterWx/java-word-MassProduction '/storage/nvme5/new_clones/FreeMarker/java-word-MassProduction' &
git clone https://github.com/appitventures/AndroidAppArchitureTemplate '/storage/nvme5/new_clones/FreeMarker/AndroidAppArchitureTemplate' &
git clone https://github.com/sudargits/MVPTemplate '/storage/nvme5/new_clones/FreeMarker/MVPTemplate' &
git clone https://github.com/shendepu/moqui-react-ssr-demo '/storage/nvme5/new_clones/FreeMarker/moqui-react-ssr-demo' &
git clone https://github.com/Tasfa/XposedModule '/storage/nvme5/new_clones/FreeMarker/XposedModule' &
git clone https://github.com/Switch-vov/krpano '/storage/nvme5/new_clones/FreeMarker/krpano' &
git clone https://github.com/rma945/keycloack-saritasa-theme '/storage/nvme5/new_clones/FreeMarker/keycloack-saritasa-theme' &
git clone https://github.com/recordingblog/zhushan-shopp-parent '/storage/nvme5/new_clones/FreeMarker/zhushan-shopp-parent' &
git clone https://github.com/52North/common-xml '/storage/nvme5/new_clones/FreeMarker/common-xml' &
git clone https://github.com/FusionAuth/fusionauth-client-builder '/storage/nvme5/new_clones/FreeMarker/fusionauth-client-builder' &
git clone https://github.com/ZoolYe/dmdb-document '/storage/nvme5/new_clones/FreeMarker/dmdb-document' &
git clone https://github.com/minziappa/spring_sample '/storage/nvme5/new_clones/FreeMarker/spring_sample' &
git clone https://github.com/Max094Reikeb/ExtraProceduresPlugin '/storage/nvme5/new_clones/FreeMarker/ExtraProceduresPlugin' &
git clone https://github.com/BlackFlagBin/KCommonTemplate '/storage/nvme5/new_clones/FreeMarker/KCommonTemplate' &
git clone https://github.com/madreain/MVPHulkTemplate '/storage/nvme5/new_clones/FreeMarker/MVPHulkTemplate' &
git clone https://github.com/etychon/eCVD-Templates '/storage/nvme5/new_clones/FreeMarker/eCVD-Templates' &
git clone https://github.com/TACTfactory/harmony-core '/storage/nvme5/new_clones/FreeMarker/harmony-core' &
git clone https://github.com/ClothCreators/more-apis-support '/storage/nvme5/new_clones/FreeMarker/more-apis-support' &
git clone https://github.com/massivedisaster/kickoff '/storage/nvme5/new_clones/FreeMarker/kickoff' &
git clone https://github.com/mkdika/rexumee '/storage/nvme5/new_clones/FreeMarker/rexumee' &
git clone https://github.com/541211190/freemarker-excel '/storage/nvme5/new_clones/FreeMarker/freemarker-excel' &
git clone https://github.com/FifthSofa/code-generator '/storage/nvme5/new_clones/FreeMarker/code-generator' &
git clone https://github.com/stadler/hibernate-tools-maven-plugin-sample '/storage/nvme5/new_clones/FreeMarker/hibernate-tools-maven-plugin-sample' &
