#!/bin/bash

git clone https://github.com/freebasic/fbc '/storage/nvme5/new_clones/FreeBASIC/fbc' &
git clone https://github.com/XusinboyBekchanov/VisualFBEditor '/storage/nvme5/new_clones/FreeBASIC/VisualFBEditor' &
git clone https://github.com/doranchak/azdecrypt '/storage/nvme5/new_clones/FreeBASIC/azdecrypt' &
git clone https://github.com/coreWeaver/LC-Meter '/storage/nvme5/new_clones/FreeBASIC/LC-Meter' &
git clone https://github.com/ohrrpgce/ohrrpgce '/storage/nvme5/new_clones/FreeBASIC/ohrrpgce' &
git clone https://github.com/XusinboyBekchanov/MyFbFramework '/storage/nvme5/new_clones/FreeBASIC/MyFbFramework' &
git clone https://github.com/DTJF/libpruio '/storage/nvme5/new_clones/FreeBASIC/libpruio' &
git clone https://github.com/freebasic/fbfrog '/storage/nvme5/new_clones/FreeBASIC/fbfrog' &
git clone https://github.com/MyTDT-Mysoft/DllCompat '/storage/nvme5/new_clones/FreeBASIC/DllCompat' &
git clone https://github.com/eddavis2/Tiny-Basic '/storage/nvme5/new_clones/FreeBASIC/Tiny-Basic' &
git clone https://github.com/WIITD/raylib-freebasic '/storage/nvme5/new_clones/FreeBASIC/raylib-freebasic' &
git clone https://github.com/DualBrain/QB64 '/storage/nvme5/new_clones/FreeBASIC/QB64' &
git clone https://github.com/ImortisInglorian/fbrtLib '/storage/nvme5/new_clones/FreeBASIC/fbrtLib' &
git clone https://github.com/open-struct-engineer/Excel '/storage/nvme5/new_clones/FreeBASIC/Excel' &
git clone https://github.com/flukiluke/L-BASIC '/storage/nvme5/new_clones/FreeBASIC/L-BASIC' &
git clone https://github.com/thetrik/InjectAndManipulateVB '/storage/nvme5/new_clones/FreeBASIC/InjectAndManipulateVB' &
git clone https://github.com/antonioginer/crt_tools '/storage/nvme5/new_clones/FreeBASIC/crt_tools' &
git clone https://github.com/Sarania/StrawberryNES '/storage/nvme5/new_clones/FreeBASIC/StrawberryNES' &
git clone https://github.com/AshishKingdom/p5js.bas '/storage/nvme5/new_clones/FreeBASIC/p5js.bas' &
git clone https://github.com/professor-jonny/Xbox-AVIP-mod '/storage/nvme5/new_clones/FreeBASIC/Xbox-AVIP-mod' &
git clone https://github.com/StringEpsilon/fbJson '/storage/nvme5/new_clones/FreeBASIC/fbJson' &
git clone https://github.com/FreeBASIC-Extended-Library/fb-ext-lib '/storage/nvme5/new_clones/FreeBASIC/fb-ext-lib' &
git clone https://github.com/countingpine/PCEM_FB486 '/storage/nvme5/new_clones/FreeBASIC/PCEM_FB486' &
git clone https://github.com/freebasic/fbbindings '/storage/nvme5/new_clones/FreeBASIC/fbbindings' &
git clone https://github.com/fangcun010/BRPGEngine '/storage/nvme5/new_clones/FreeBASIC/BRPGEngine' &
git clone https://github.com/Democrito/repositorios '/storage/nvme5/new_clones/FreeBASIC/repositorios' &
git clone https://github.com/macthomasengineering/MteEVAL-b4x-library '/storage/nvme5/new_clones/FreeBASIC/MteEVAL-b4x-library' &
git clone https://github.com/antonioginer/ATOM-15 '/storage/nvme5/new_clones/FreeBASIC/ATOM-15' &
git clone https://github.com/MyTDT-Mysoft/COCO-FastLoader '/storage/nvme5/new_clones/FreeBASIC/COCO-FastLoader' &
git clone https://github.com/TorkamaniLab/Genotype_Imputation_Pipeline '/storage/nvme5/new_clones/FreeBASIC/Genotype_Imputation_Pipeline' &
git clone https://github.com/frnno967/maxiterm '/storage/nvme5/new_clones/FreeBASIC/maxiterm' &
git clone https://github.com/nsiatras/kiwi '/storage/nvme5/new_clones/FreeBASIC/kiwi' &
git clone https://github.com/gsfsoftware/Tutorials '/storage/nvme5/new_clones/FreeBASIC/Tutorials' &
git clone https://github.com/Sudo-VP/Vietnamese-Word-Segmentation-Python '/storage/nvme5/new_clones/FreeBASIC/Vietnamese-Word-Segmentation-Python' &
git clone https://github.com/gAndy50/Qb64Wrappers '/storage/nvme5/new_clones/FreeBASIC/Qb64Wrappers' &
git clone https://github.com/GaryLuck/LuckBasic '/storage/nvme5/new_clones/FreeBASIC/LuckBasic' &
git clone https://github.com/AnywhereSoftware/Web3X '/storage/nvme5/new_clones/FreeBASIC/Web3X' &
git clone https://github.com/felipebacelo/ModulesVBA '/storage/nvme5/new_clones/FreeBASIC/ModulesVBA' &
git clone https://github.com/VerbalExpressions/FreeBasicVerbalExpressions '/storage/nvme5/new_clones/FreeBASIC/FreeBasicVerbalExpressions' &
git clone https://github.com/SomeUnusualGames/Flag-Wars '/storage/nvme5/new_clones/FreeBASIC/Flag-Wars' &
git clone https://github.com/glasyalabolas/fb-collections '/storage/nvme5/new_clones/FreeBASIC/fb-collections' &
git clone https://github.com/glasyalabolas/fb-raylib '/storage/nvme5/new_clones/FreeBASIC/fb-raylib' &
git clone https://github.com/DTJF/FBeauty '/storage/nvme5/new_clones/FreeBASIC/FBeauty' &
git clone https://github.com/smallbasic/smallbasic.samples '/storage/nvme5/new_clones/FreeBASIC/smallbasic.samples' &
git clone https://github.com/creamcast/3D-Library-for-QB64 '/storage/nvme5/new_clones/FreeBASIC/3D-Library-for-QB64' &
git clone https://github.com/AnywhereSoftware/X2 '/storage/nvme5/new_clones/FreeBASIC/X2' &
git clone https://github.com/MODFLOW-USGS/modflow6-testmodels '/storage/nvme5/new_clones/FreeBASIC/modflow6-testmodels' &
git clone https://github.com/icculus/gradius '/storage/nvme5/new_clones/FreeBASIC/gradius' &
git clone https://github.com/jayrm/fbcunit '/storage/nvme5/new_clones/FreeBASIC/fbcunit' &
git clone https://github.com/grymmjack/DRAW '/storage/nvme5/new_clones/FreeBASIC/DRAW' &
git clone https://github.com/glasyalabolas/fb-imageproc '/storage/nvme5/new_clones/FreeBASIC/fb-imageproc' &
