#!/bin/bash

git clone https://github.com/CarlosGS/Cyclone-PCB-Factory '/storage/nvme5/new_clones/G-code/Cyclone-PCB-Factory' &
git clone https://github.com/dotnet-presentations/dotNETConf '/storage/nvme5/new_clones/G-code/dotNETConf' &
git clone https://github.com/FaqT0tum/Orbion_Space_Mouse_OLD '/storage/nvme5/new_clones/G-code/Orbion_Space_Mouse_OLD' &
git clone https://github.com/synthetos/TinyG '/storage/nvme5/new_clones/G-code/TinyG' &
git clone https://github.com/shiltemann/CTF-writeups-public '/storage/nvme5/new_clones/G-code/CTF-writeups-public' &
git clone https://github.com/sameer/svg2gcode '/storage/nvme5/new_clones/G-code/svg2gcode' &
git clone https://github.com/hoppuman/TikTokHacks '/storage/nvme5/new_clones/G-code/TikTokHacks' &
git clone https://github.com/Autodrop3d/serialTerminal.com '/storage/nvme5/new_clones/G-code/serialTerminal.com' &
git clone https://github.com/PacktPublishing/Learn-Three.js-Fourth-edition '/storage/nvme5/new_clones/G-code/Learn-Three.js-Fourth-edition' &
git clone https://github.com/RoyBerntsenDesign/V-King-CoreXY '/storage/nvme5/new_clones/G-code/V-King-CoreXY' &
git clone https://github.com/eried/Research '/storage/nvme5/new_clones/G-code/Research' &
git clone https://github.com/AlaaSaadAbdo/battoota '/storage/nvme5/new_clones/G-code/battoota' &
git clone https://github.com/fellesverkstedet/fabricatable-machines '/storage/nvme5/new_clones/G-code/fabricatable-machines' &
git clone https://github.com/bigtreetech/BIQU-B1 '/storage/nvme5/new_clones/G-code/BIQU-B1' &
git clone https://github.com/Caribou3d/CaribouCartesian '/storage/nvme5/new_clones/G-code/CaribouCartesian' &
git clone https://github.com/The-Royal/The_Royal_Open-Source-Projects '/storage/nvme5/new_clones/G-code/The_Royal_Open-Source-Projects' &
git clone https://github.com/nasa-jpl/COVID-19-respirators '/storage/nvme5/new_clones/G-code/COVID-19-respirators' &
git clone https://github.com/MoonCactus/gcode_postprocessors '/storage/nvme5/new_clones/G-code/gcode_postprocessors' &
git clone https://github.com/Cederb/Faceshield.nu '/storage/nvme5/new_clones/G-code/Faceshield.nu' &
git clone https://github.com/domoszlai/juicy-gcode '/storage/nvme5/new_clones/G-code/juicy-gcode' &
git clone https://github.com/Meebleeps/MeeBleeps-Freaq-FM-Synth '/storage/nvme5/new_clones/G-code/MeeBleeps-Freaq-FM-Synth' &
git clone https://github.com/MKme/Roomba '/storage/nvme5/new_clones/G-code/Roomba' &
git clone https://github.com/monero-project/kastelo '/storage/nvme5/new_clones/G-code/kastelo' &
git clone https://github.com/yorikvanhavre/FreeCAD-manual '/storage/nvme5/new_clones/G-code/FreeCAD-manual' &
git clone https://github.com/garethky/klipper-voron2.4-config '/storage/nvme5/new_clones/G-code/klipper-voron2.4-config' &
git clone https://github.com/jasminemoreira/3D_printing '/storage/nvme5/new_clones/G-code/3D_printing' &
git clone https://github.com/Kbreezy24/blackbox '/storage/nvme5/new_clones/G-code/blackbox' &
git clone https://github.com/ten-point-nine/freETarget '/storage/nvme5/new_clones/G-code/freETarget' &
git clone https://github.com/Michael-F-Bryan/gcode-rs '/storage/nvme5/new_clones/G-code/gcode-rs' &
git clone https://github.com/TheGuardDawg/print2a '/storage/nvme5/new_clones/G-code/print2a' &
git clone https://github.com/zhangyaqi1989/Gcode-Reader '/storage/nvme5/new_clones/G-code/Gcode-Reader' &
git clone https://github.com/dillonhuff/gpr '/storage/nvme5/new_clones/G-code/gpr' &
git clone https://github.com/robomechanics/MiniRHex '/storage/nvme5/new_clones/G-code/MiniRHex' &
git clone https://github.com/c0pperdragon/SIO2SD '/storage/nvme5/new_clones/G-code/SIO2SD' &
git clone https://github.com/MKme/Wemos-D1-ESP8266-PIR-Alarm '/storage/nvme5/new_clones/G-code/Wemos-D1-ESP8266-PIR-Alarm' &
git clone https://github.com/tripflex/MOD-t '/storage/nvme5/new_clones/G-code/MOD-t' &
git clone https://github.com/xreef/MKS_WIFI_upgrade_with_BeePrint_web_interface '/storage/nvme5/new_clones/G-code/MKS_WIFI_upgrade_with_BeePrint_web_interface' &
git clone https://github.com/ricardodeazambuja/Maple-Syrup-Pi-Camera '/storage/nvme5/new_clones/G-code/Maple-Syrup-Pi-Camera' &
git clone https://github.com/joshuartaylor/TheRecreator3D '/storage/nvme5/new_clones/G-code/TheRecreator3D' &
git clone https://github.com/verlab/hero_common '/storage/nvme5/new_clones/G-code/hero_common' &
git clone https://github.com/petercpark/The_Uni '/storage/nvme5/new_clones/G-code/The_Uni' &
git clone https://github.com/geoffrey-young/3D-Printing '/storage/nvme5/new_clones/G-code/3D-Printing' &
git clone https://github.com/BerkeleyCurtis/EECS249_HapticGlove '/storage/nvme5/new_clones/G-code/EECS249_HapticGlove' &
git clone https://github.com/CarlosGS/OpenBinaural '/storage/nvme5/new_clones/G-code/OpenBinaural' &
git clone https://github.com/AndrewSink/pltr_toolhead '/storage/nvme5/new_clones/G-code/pltr_toolhead' &
git clone https://github.com/Snipercaine/home_assistant_config '/storage/nvme5/new_clones/G-code/home_assistant_config' &
git clone https://github.com/bigtreetech/BTT-E3-RRF '/storage/nvme5/new_clones/G-code/BTT-E3-RRF' &
git clone https://github.com/pjgpetecodes/rpirobot '/storage/nvme5/new_clones/G-code/rpirobot' &
git clone https://github.com/jamescarruthers/PlotteRXY '/storage/nvme5/new_clones/G-code/PlotteRXY' &
git clone https://github.com/maplerainresearch/MRR_ESPA '/storage/nvme5/new_clones/G-code/MRR_ESPA' &
git clone https://github.com/rkolbi/My_Mars2Pro_Accessories '/storage/nvme5/new_clones/G-code/My_Mars2Pro_Accessories' &
git clone https://github.com/Duet3D/RRF-machine-config-files '/storage/nvme5/new_clones/G-code/RRF-machine-config-files' &
git clone https://github.com/ziv-lin/My_solidworks '/storage/nvme5/new_clones/G-code/My_solidworks' &
git clone https://github.com/MakerGear/M2 '/storage/nvme5/new_clones/G-code/M2' &
git clone https://github.com/seemecnc/RostockMAXv2 '/storage/nvme5/new_clones/G-code/RostockMAXv2' &
git clone https://github.com/siganberg/3D-printing '/storage/nvme5/new_clones/G-code/3D-printing' &
git clone https://github.com/mkellsy/rpi-case-model '/storage/nvme5/new_clones/G-code/rpi-case-model' &
git clone https://github.com/rwalkr/eskarp '/storage/nvme5/new_clones/G-code/eskarp' &
git clone https://github.com/jcarolinares/fpga-biorobots '/storage/nvme5/new_clones/G-code/fpga-biorobots' &
git clone https://github.com/eumorpurgo/TextileDrawingMachine '/storage/nvme5/new_clones/G-code/TextileDrawingMachine' &
git clone https://github.com/Ben-F111/Ben-F18-Sim-Pit '/storage/nvme5/new_clones/G-code/Ben-F18-Sim-Pit' &
git clone https://github.com/PotatoSociety/AndersonFirearms '/storage/nvme5/new_clones/G-code/AndersonFirearms' &
git clone https://github.com/GMTrevis/Homeassistant-NodeRed-Systemair-VTR300 '/storage/nvme5/new_clones/G-code/Homeassistant-NodeRed-Systemair-VTR300' &
git clone https://github.com/ManiacalLabs/Engravinator '/storage/nvme5/new_clones/G-code/Engravinator' &
git clone https://github.com/r00tstici/writeups '/storage/nvme5/new_clones/G-code/writeups' &
git clone https://github.com/PCBPrints/PCbPrints '/storage/nvme5/new_clones/G-code/PCbPrints' &
git clone https://github.com/Addy771/Hex-Cell-Holder '/storage/nvme5/new_clones/G-code/Hex-Cell-Holder' &
git clone https://github.com/pfn/EnragedRabbitOnRRF '/storage/nvme5/new_clones/G-code/EnragedRabbitOnRRF' &
git clone https://github.com/CRASHSpace/COVID-19-3dprints '/storage/nvme5/new_clones/G-code/COVID-19-3dprints' &
git clone https://github.com/khuong-nv/RobotSimulator '/storage/nvme5/new_clones/G-code/RobotSimulator' &
git clone https://github.com/Prutsium/3D-Druckerplausch-Klipper '/storage/nvme5/new_clones/G-code/3D-Druckerplausch-Klipper' &
git clone https://github.com/CoolNamesAllTaken/radar-speed-sign '/storage/nvme5/new_clones/G-code/radar-speed-sign' &
git clone https://github.com/rorosaurus/FurretTotem '/storage/nvme5/new_clones/G-code/FurretTotem' &
git clone https://github.com/InverseIntegral/ctf_writeups '/storage/nvme5/new_clones/G-code/ctf_writeups' &
git clone https://github.com/vigibot/vigicad '/storage/nvme5/new_clones/G-code/vigicad' &
git clone https://github.com/femtoduino/femu-hardware '/storage/nvme5/new_clones/G-code/femu-hardware' &
git clone https://github.com/bigtreetech/BIQU-B1-SE-PLUS '/storage/nvme5/new_clones/G-code/BIQU-B1-SE-PLUS' &
git clone https://github.com/gitaroktato/gcode-retraction-changer '/storage/nvme5/new_clones/G-code/gcode-retraction-changer' &
git clone https://github.com/barn53/CoinThing '/storage/nvme5/new_clones/G-code/CoinThing' &
git clone https://github.com/nppc/Heater12VControl '/storage/nvme5/new_clones/G-code/Heater12VControl' &
git clone https://github.com/danwerner21/we816 '/storage/nvme5/new_clones/G-code/we816' &
git clone https://github.com/DDeGonge/TicTacToe-Bot '/storage/nvme5/new_clones/G-code/TicTacToe-Bot' &
git clone https://github.com/danfoisy/flicker '/storage/nvme5/new_clones/G-code/flicker' &
git clone https://github.com/fritzw/xtm1_toolkit '/storage/nvme5/new_clones/G-code/xtm1_toolkit' &
git clone https://github.com/ukmaker/BassMate '/storage/nvme5/new_clones/G-code/BassMate' &
git clone https://github.com/3DPGVA/Prusa-Bear-MK3S-MINI---Ultra-Upgraded- '/storage/nvme5/new_clones/G-code/Prusa-Bear-MK3S-MINI---Ultra-Upgraded-' &
git clone https://github.com/andrewhodel/reprapweb '/storage/nvme5/new_clones/G-code/reprapweb' &
git clone https://github.com/seemecnc/Firmware '/storage/nvme5/new_clones/G-code/Firmware' &
git clone https://github.com/sanjithudupa/Embroidery-Digitizer '/storage/nvme5/new_clones/G-code/Embroidery-Digitizer' &
git clone https://github.com/chenhanpolyu/AutoFly-demo '/storage/nvme5/new_clones/G-code/AutoFly-demo' &
git clone https://github.com/cupsster/FLSUN-SR---Klipper-Config '/storage/nvme5/new_clones/G-code/FLSUN-SR---Klipper-Config' &
git clone https://github.com/aotta/RTO-Cart '/storage/nvme5/new_clones/G-code/RTO-Cart' &
git clone https://github.com/Octopusmode/Picaso3D '/storage/nvme5/new_clones/G-code/Picaso3D' &
git clone https://github.com/josefdolezal/fit-cvut '/storage/nvme5/new_clones/G-code/fit-cvut' &
git clone https://github.com/ZONESTAR3D/Firmware '/storage/nvme5/new_clones/G-code/Firmware' &
git clone https://github.com/linyuxuanlin/3D-print-library '/storage/nvme5/new_clones/G-code/3D-print-library' &
git clone https://github.com/MacNite/CorEssentials '/storage/nvme5/new_clones/G-code/CorEssentials' &
git clone https://github.com/FYSETC/FYSETC-BLV-MGN-CUBE '/storage/nvme5/new_clones/G-code/FYSETC-BLV-MGN-CUBE' &
git clone https://github.com/DAguirreAg/GCode-to-ABB '/storage/nvme5/new_clones/G-code/GCode-to-ABB' &
git clone https://github.com/ZONESTAR3D/Slicing-Guide '/storage/nvme5/new_clones/G-code/Slicing-Guide' &
git clone https://github.com/macchina/m2-enclosures '/storage/nvme5/new_clones/G-code/m2-enclosures' &
git clone https://github.com/pessimism/TronxyX1 '/storage/nvme5/new_clones/G-code/TronxyX1' &
git clone https://github.com/EmmeFreeze/Artillery-Hornet-Mods '/storage/nvme5/new_clones/G-code/Artillery-Hornet-Mods' &
git clone https://github.com/mkazimoto/ESP32_CNC '/storage/nvme5/new_clones/G-code/ESP32_CNC' &
git clone https://github.com/AMasetti/Bleeding-Edge-Duel-Disk-System '/storage/nvme5/new_clones/G-code/Bleeding-Edge-Duel-Disk-System' &
git clone https://github.com/campy/Hbot '/storage/nvme5/new_clones/G-code/Hbot' &
git clone https://github.com/bpcmusic/TXn '/storage/nvme5/new_clones/G-code/TXn' &
git clone https://github.com/xhoobin/LincoRobotArm '/storage/nvme5/new_clones/G-code/LincoRobotArm' &
git clone https://github.com/Cloud-CNC/vue-3d-viewer '/storage/nvme5/new_clones/G-code/vue-3d-viewer' &
git clone https://github.com/madskjeldgaard/mico '/storage/nvme5/new_clones/G-code/mico' &
git clone https://github.com/jadonmmiller/UltimateDuetMenuSystem '/storage/nvme5/new_clones/G-code/UltimateDuetMenuSystem' &
git clone https://github.com/nppc/HotAirGunController '/storage/nvme5/new_clones/G-code/HotAirGunController' &
git clone https://github.com/kolins-cz/antenna-tracker-mechanics '/storage/nvme5/new_clones/G-code/antenna-tracker-mechanics' &
git clone https://github.com/FYSETC/FYSETC-BIG_DIPPER '/storage/nvme5/new_clones/G-code/FYSETC-BIG_DIPPER' &
git clone https://github.com/awabom/3dprint '/storage/nvme5/new_clones/G-code/3dprint' &
git clone https://github.com/Tobi0892/esp8266-4051-multiplexer-plant-sensor '/storage/nvme5/new_clones/G-code/esp8266-4051-multiplexer-plant-sensor' &
git clone https://github.com/FUEL4EP/Creality_Ender_3_S1_Pro '/storage/nvme5/new_clones/G-code/Creality_Ender_3_S1_Pro' &
git clone https://github.com/renatobo/Ender3NozzleCleaner '/storage/nvme5/new_clones/G-code/Ender3NozzleCleaner' &
git clone https://github.com/ucl-casa-ce/Open-Gauges '/storage/nvme5/new_clones/G-code/Open-Gauges' &
git clone https://github.com/brianlow/plotter '/storage/nvme5/new_clones/G-code/plotter' &
git clone https://github.com/ZONESTAR3D/Document-and-User-Guide '/storage/nvme5/new_clones/G-code/Document-and-User-Guide' &
git clone https://github.com/seemecnc/Orion_Delta '/storage/nvme5/new_clones/G-code/Orion_Delta' &
git clone https://github.com/bbenchoff/SerialKeybard '/storage/nvme5/new_clones/G-code/SerialKeybard' &
git clone https://github.com/Cooper-8pTX/Valentine-ECM-Mod '/storage/nvme5/new_clones/G-code/Valentine-ECM-Mod' &
git clone https://github.com/Spiritdude/Nautilus_Thumbnailer_GCode '/storage/nvme5/new_clones/G-code/Nautilus_Thumbnailer_GCode' &
git clone https://github.com/CrazyRobMiles/dirtywave-m8-keyboard '/storage/nvme5/new_clones/G-code/dirtywave-m8-keyboard' &
git clone https://github.com/ithinuel/async-gcode '/storage/nvme5/new_clones/G-code/async-gcode' &
git clone https://github.com/OrgovanGeza/PET-to-Filament '/storage/nvme5/new_clones/G-code/PET-to-Filament' &
git clone https://github.com/CallMeSwal/OpenBelt3DPrinter '/storage/nvme5/new_clones/G-code/OpenBelt3DPrinter' &
git clone https://github.com/RandomPrototypes/MusicBoxMaker '/storage/nvme5/new_clones/G-code/MusicBoxMaker' &
git clone https://github.com/SeanyCash/TwinCAT_CNC '/storage/nvme5/new_clones/G-code/TwinCAT_CNC' &
git clone https://github.com/my3dltd/OMG-V2-Extruder '/storage/nvme5/new_clones/G-code/OMG-V2-Extruder' &
git clone https://github.com/ZONESTAR3D/Upgrade-kit-guide '/storage/nvme5/new_clones/G-code/Upgrade-kit-guide' &
git clone https://github.com/tanaes/BLV_MGN_cube-remix '/storage/nvme5/new_clones/G-code/BLV_MGN_cube-remix' &
git clone https://github.com/tobychui/DIY-60W-PD-Powerbank '/storage/nvme5/new_clones/G-code/DIY-60W-PD-Powerbank' &
git clone https://github.com/JS-RML/flexflip '/storage/nvme5/new_clones/G-code/flexflip' &
git clone https://github.com/uinika/UINIO-Cubic-Prism '/storage/nvme5/new_clones/G-code/UINIO-Cubic-Prism' &
git clone https://github.com/MKme/I3-Mega-3D-Printer-Settings-Resources '/storage/nvme5/new_clones/G-code/I3-Mega-3D-Printer-Settings-Resources' &
git clone https://github.com/hairymnstr/oggbox '/storage/nvme5/new_clones/G-code/oggbox' &
git clone https://github.com/makernexus/prusa-covid19-shield-remix '/storage/nvme5/new_clones/G-code/prusa-covid19-shield-remix' &
git clone https://github.com/unl-cchil/canine_precise_dispenser '/storage/nvme5/new_clones/G-code/canine_precise_dispenser' &
git clone https://github.com/nygma2004/beca_mqtt '/storage/nvme5/new_clones/G-code/beca_mqtt' &
git clone https://github.com/berry123/Lily-Bot '/storage/nvme5/new_clones/G-code/Lily-Bot' &
git clone https://github.com/Cloud-CNC/vue-gcode-viewer '/storage/nvme5/new_clones/G-code/vue-gcode-viewer' &
git clone https://github.com/my3dltd/OMG-V2s '/storage/nvme5/new_clones/G-code/OMG-V2s' &
git clone https://github.com/PrintM3D/Crane '/storage/nvme5/new_clones/G-code/Crane' &
git clone https://github.com/EddyBeaupre/Tronxy-XY2-Pro '/storage/nvme5/new_clones/G-code/Tronxy-XY2-Pro' &
git clone https://github.com/Rat-OS/RatOS-configurator '/storage/nvme5/new_clones/G-code/RatOS-configurator' &
git clone https://github.com/greghulette/PeriscopeLifter '/storage/nvme5/new_clones/G-code/PeriscopeLifter' &
git clone https://github.com/femtoduino/bomu-hardware '/storage/nvme5/new_clones/G-code/bomu-hardware' &
git clone https://github.com/BWLR/SMX-HLDR '/storage/nvme5/new_clones/G-code/SMX-HLDR' &
git clone https://github.com/Mellow-3D/FLY-RRF-E3 '/storage/nvme5/new_clones/G-code/FLY-RRF-E3' &
git clone https://github.com/rckTom/RTVC '/storage/nvme5/new_clones/G-code/RTVC' &
git clone https://github.com/hugokernel/OpenSCAD_Things '/storage/nvme5/new_clones/G-code/OpenSCAD_Things' &
git clone https://github.com/mrbeam/MrBeamPlugin '/storage/nvme5/new_clones/G-code/MrBeamPlugin' &
git clone https://github.com/aaronse/v1engineering-mods '/storage/nvme5/new_clones/G-code/v1engineering-mods' &
git clone https://github.com/AndreasReitberger/KlipperRestApiSharp '/storage/nvme5/new_clones/G-code/KlipperRestApiSharp' &
git clone https://github.com/ZONESTAR3D/Z9 '/storage/nvme5/new_clones/G-code/Z9' &
git clone https://github.com/mdwelsh/teamsidney '/storage/nvme5/new_clones/G-code/teamsidney' &
git clone https://github.com/lukeslaboratory/Stablebot-Core '/storage/nvme5/new_clones/G-code/Stablebot-Core' &
git clone https://github.com/00shtoobs/TronxyBrainFood '/storage/nvme5/new_clones/G-code/TronxyBrainFood' &
git clone https://github.com/KevWal/ESP32-Cam-Pico-Project '/storage/nvme5/new_clones/G-code/ESP32-Cam-Pico-Project' &
git clone https://github.com/softegg/Stylish-Trucker-Belt-Synthesizer '/storage/nvme5/new_clones/G-code/Stylish-Trucker-Belt-Synthesizer' &
git clone https://github.com/avmaisak/Gcode '/storage/nvme5/new_clones/G-code/Gcode' &
git clone https://github.com/nscale4by8/nscale4x8 '/storage/nvme5/new_clones/G-code/nscale4x8' &
git clone https://github.com/DragonRailway/EMD-Locomotives '/storage/nvme5/new_clones/G-code/EMD-Locomotives' &
git clone https://github.com/ldijkman/ART-ESP32-Touch-TFT-Thermostat '/storage/nvme5/new_clones/G-code/ART-ESP32-Touch-TFT-Thermostat' &
git clone https://github.com/Jeff-Birt/MOS8701_HB '/storage/nvme5/new_clones/G-code/MOS8701_HB' &
git clone https://github.com/DuncanLHS/SunluS8 '/storage/nvme5/new_clones/G-code/SunluS8' &
git clone https://github.com/shirnschall/HST-slider-project '/storage/nvme5/new_clones/G-code/HST-slider-project' &
git clone https://github.com/x0pherl/Filament-Bank '/storage/nvme5/new_clones/G-code/Filament-Bank' &
git clone https://github.com/youcangetme/Simplify3DProfilesTaz6 '/storage/nvme5/new_clones/G-code/Simplify3DProfilesTaz6' &
git clone https://github.com/reivaxy/iotinator '/storage/nvme5/new_clones/G-code/iotinator' &
git clone https://github.com/IowaScaledEngineering/mrbw-cst '/storage/nvme5/new_clones/G-code/mrbw-cst' &
git clone https://github.com/jscad/sample-files '/storage/nvme5/new_clones/G-code/sample-files' &
git clone https://github.com/sameer/g-code '/storage/nvme5/new_clones/G-code/g-code' &
git clone https://github.com/altaga/Facemask-Detector-ZCU104 '/storage/nvme5/new_clones/G-code/Facemask-Detector-ZCU104' &
git clone https://github.com/shodushi/gcode2png '/storage/nvme5/new_clones/G-code/gcode2png' &
git clone https://github.com/rmavrichev/freecad-projects '/storage/nvme5/new_clones/G-code/freecad-projects' &
git clone https://github.com/HuayraLinux/live-cd '/storage/nvme5/new_clones/G-code/live-cd' &
git clone https://github.com/seemecnc/slicing-profiles '/storage/nvme5/new_clones/G-code/slicing-profiles' &
git clone https://github.com/avirtuos/openscad '/storage/nvme5/new_clones/G-code/openscad' &
git clone https://github.com/ubruhin/hydro-battery-charger '/storage/nvme5/new_clones/G-code/hydro-battery-charger' &
git clone https://github.com/zipzit/Covid-Bluetooth-Stethoscope '/storage/nvme5/new_clones/G-code/Covid-Bluetooth-Stethoscope' &
git clone https://github.com/physiii/access-controller '/storage/nvme5/new_clones/G-code/access-controller' &
git clone https://github.com/nygma2004/word_clock_hun '/storage/nvme5/new_clones/G-code/word_clock_hun' &
git clone https://github.com/plangdon/3D-Printer-2018 '/storage/nvme5/new_clones/G-code/3D-Printer-2018' &
git clone https://github.com/FredJ21/KANI_Quadruped_Bot '/storage/nvme5/new_clones/G-code/KANI_Quadruped_Bot' &
git clone https://github.com/Tympan/Tympan_Rev_E_Hardware '/storage/nvme5/new_clones/G-code/Tympan_Rev_E_Hardware' &
git clone https://github.com/Samtech3D/FLSUN-SR-Klipper-Klipper-Screen-Neopixel-Theme '/storage/nvme5/new_clones/G-code/FLSUN-SR-Klipper-Klipper-Screen-Neopixel-Theme' &
git clone https://github.com/HummingbirdHammocks/rain-tarps '/storage/nvme5/new_clones/G-code/rain-tarps' &
git clone https://github.com/ybisk/robot '/storage/nvme5/new_clones/G-code/robot' &
git clone https://github.com/sparkfun/SparkFun_RTK_Surveyor '/storage/nvme5/new_clones/G-code/SparkFun_RTK_Surveyor' &
git clone https://github.com/woodcol/arduino_touch '/storage/nvme5/new_clones/G-code/arduino_touch' &
git clone https://github.com/gzalles/ambisonics-z-array '/storage/nvme5/new_clones/G-code/ambisonics-z-array' &
git clone https://github.com/tinkeringtech/scoutmakes '/storage/nvme5/new_clones/G-code/scoutmakes' &
git clone https://github.com/bigtreetech/BIQU-B2 '/storage/nvme5/new_clones/G-code/BIQU-B2' &
git clone https://github.com/wyolum/ultim8x8 '/storage/nvme5/new_clones/G-code/ultim8x8' &
git clone https://github.com/eightbitraptor/65_keyboard_untitled '/storage/nvme5/new_clones/G-code/65_keyboard_untitled' &
git clone https://github.com/medicationforall/cadqueryhelper '/storage/nvme5/new_clones/G-code/cadqueryhelper' &
git clone https://github.com/cam-cambridge/creality-part-remover '/storage/nvme5/new_clones/G-code/creality-part-remover' &
git clone https://github.com/AlliedToasters/ender_3_bed_level '/storage/nvme5/new_clones/G-code/ender_3_bed_level' &
git clone https://github.com/yandreev3/3dWiFiSend '/storage/nvme5/new_clones/G-code/3dWiFiSend' &
git clone https://github.com/jsaintrocc/myblvmgncube '/storage/nvme5/new_clones/G-code/myblvmgncube' &
git clone https://github.com/jhitesma/Modular-Synth-Build '/storage/nvme5/new_clones/G-code/Modular-Synth-Build' &
git clone https://github.com/kizza42/TevoLittleMonster '/storage/nvme5/new_clones/G-code/TevoLittleMonster' &
git clone https://github.com/tanvach/prettygood_dsp '/storage/nvme5/new_clones/G-code/prettygood_dsp' &
git clone https://github.com/radimkeseg/osmoZis '/storage/nvme5/new_clones/G-code/osmoZis' &
git clone https://github.com/harrycomeon/UR5-Drawing '/storage/nvme5/new_clones/G-code/UR5-Drawing' &
git clone https://github.com/xpix/XHTC '/storage/nvme5/new_clones/G-code/XHTC' &
git clone https://github.com/philstenning/madam3D '/storage/nvme5/new_clones/G-code/madam3D' &
git clone https://github.com/magicmaker3/magicmaker '/storage/nvme5/new_clones/G-code/magicmaker' &
git clone https://github.com/fpga-design-contest/ad-refkit '/storage/nvme5/new_clones/G-code/ad-refkit' &
git clone https://github.com/BCN3D/BCN3D-Utilities '/storage/nvme5/new_clones/G-code/BCN3D-Utilities' &
git clone https://github.com/Psyobilin/Anycubic-Predator-configuration.gcode '/storage/nvme5/new_clones/G-code/Anycubic-Predator-configuration.gcode' &
git clone https://github.com/vyacheslav-shubin/mks-robin-nano35-binary '/storage/nvme5/new_clones/G-code/mks-robin-nano35-binary' &
git clone https://github.com/CrazyRobMiles/chocolate-synthbox '/storage/nvme5/new_clones/G-code/chocolate-synthbox' &
git clone https://github.com/fly2mars/suCAM '/storage/nvme5/new_clones/G-code/suCAM' &
git clone https://github.com/1x-technologies/halodi-recruitment-challenges '/storage/nvme5/new_clones/G-code/halodi-recruitment-challenges' &
git clone https://github.com/gloworm-vision/gloworm '/storage/nvme5/new_clones/G-code/gloworm' &
git clone https://github.com/polygontwist/splinewriter '/storage/nvme5/new_clones/G-code/splinewriter' &
git clone https://github.com/IMADE3D/JellyBox '/storage/nvme5/new_clones/G-code/JellyBox' &
git clone https://github.com/osbock/RAF '/storage/nvme5/new_clones/G-code/RAF' &
git clone https://github.com/DoESLiverpool/covid19 '/storage/nvme5/new_clones/G-code/covid19' &
git clone https://github.com/zczcyc0201/CrabPixelClock '/storage/nvme5/new_clones/G-code/CrabPixelClock' &
git clone https://github.com/jes/pngcam '/storage/nvme5/new_clones/G-code/pngcam' &
git clone https://github.com/henninb/dotfiles '/storage/nvme5/new_clones/G-code/dotfiles' &
git clone https://github.com/beeverycreative/B2X300-resources '/storage/nvme5/new_clones/G-code/B2X300-resources' &
git clone https://github.com/dj0abr/QIDI_connect '/storage/nvme5/new_clones/G-code/QIDI_connect' &
git clone https://github.com/ZiniuLu/SmartConverter '/storage/nvme5/new_clones/G-code/SmartConverter' &
git clone https://github.com/ciniml/M5Stack_Gadgets '/storage/nvme5/new_clones/G-code/M5Stack_Gadgets' &
git clone https://github.com/Koichi-Sakata/pylib_sakata '/storage/nvme5/new_clones/G-code/pylib_sakata' &
git clone https://github.com/StrathAIS/Rocketry '/storage/nvme5/new_clones/G-code/Rocketry' &
git clone https://github.com/TeamGloomy/LPC-STM32-RRFUserConfigs '/storage/nvme5/new_clones/G-code/LPC-STM32-RRFUserConfigs' &
git clone https://github.com/mrpjevans/send2joto '/storage/nvme5/new_clones/G-code/send2joto' &
git clone https://github.com/TypQxQ/DuetBackup '/storage/nvme5/new_clones/G-code/DuetBackup' &
git clone https://github.com/kkr0kk/GNS530 '/storage/nvme5/new_clones/G-code/GNS530' &
git clone https://github.com/Deltaprintr/Rapid-Star '/storage/nvme5/new_clones/G-code/Rapid-Star' &
git clone https://github.com/tachoknight/xyz-zero-finder '/storage/nvme5/new_clones/G-code/xyz-zero-finder' &
git clone https://github.com/FYNCH-BIO/hardware '/storage/nvme5/new_clones/G-code/hardware' &
git clone https://github.com/anwarminarso/ESP32-SelfBalancing '/storage/nvme5/new_clones/G-code/ESP32-SelfBalancing' &
git clone https://github.com/x0rtrunks/RRF-Example-Macros '/storage/nvme5/new_clones/G-code/RRF-Example-Macros' &
git clone https://github.com/joe-rodgers/guns.team '/storage/nvme5/new_clones/G-code/guns.team' &
git clone https://github.com/seemecnc/Artemis '/storage/nvme5/new_clones/G-code/Artemis' &
git clone https://github.com/nionio6915/LPC1768-RepRapFirmware-Files '/storage/nvme5/new_clones/G-code/LPC1768-RepRapFirmware-Files' &
git clone https://github.com/wmmc88/PrusaSlicer-FlashForge '/storage/nvme5/new_clones/G-code/PrusaSlicer-FlashForge' &
git clone https://github.com/FreeSK8/Puck-Puck-Bruce '/storage/nvme5/new_clones/G-code/Puck-Puck-Bruce' &
git clone https://github.com/probonopd/marlin-for-ender-2 '/storage/nvme5/new_clones/G-code/marlin-for-ender-2' &
git clone https://github.com/EB3DPrinting/GCode_Files '/storage/nvme5/new_clones/G-code/GCode_Files' &
git clone https://github.com/queeriouslabs/ReFactor '/storage/nvme5/new_clones/G-code/ReFactor' &
git clone https://github.com/senwerks/lipo-battery-for-original-gameboy '/storage/nvme5/new_clones/G-code/lipo-battery-for-original-gameboy' &
git clone https://github.com/Cat5TV/ender3_v2 '/storage/nvme5/new_clones/G-code/ender3_v2' &
git clone https://github.com/BirdTho/rose-engine '/storage/nvme5/new_clones/G-code/rose-engine' &
git clone https://github.com/itzgoldenleonard/Craftbot-Plus-essentials '/storage/nvme5/new_clones/G-code/Craftbot-Plus-essentials' &
git clone https://github.com/ChipCE/3d-printing '/storage/nvme5/new_clones/G-code/3d-printing' &
git clone https://github.com/smith3d/3DPrinterFirmwareList '/storage/nvme5/new_clones/G-code/3DPrinterFirmwareList' &
git clone https://github.com/case06/upklib_v2 '/storage/nvme5/new_clones/G-code/upklib_v2' &
git clone https://github.com/LucaTomei/FlyingBear-Gost-5 '/storage/nvme5/new_clones/G-code/FlyingBear-Gost-5' &
git clone https://github.com/mah115/WEEDO_X40_files '/storage/nvme5/new_clones/G-code/WEEDO_X40_files' &
git clone https://github.com/hernancurras/blvmgncube '/storage/nvme5/new_clones/G-code/blvmgncube' &
git clone https://github.com/ResearcherOne/RobotTakimiRepo '/storage/nvme5/new_clones/G-code/RobotTakimiRepo' &
git clone https://github.com/wenzel-lab/modular-microfluidics-workstation-controller '/storage/nvme5/new_clones/G-code/modular-microfluidics-workstation-controller' &
git clone https://github.com/PNWS/PNWS '/storage/nvme5/new_clones/G-code/PNWS' &
git clone https://github.com/HummingbirdHammocks/parts-accessories '/storage/nvme5/new_clones/G-code/parts-accessories' &
git clone https://github.com/Fukthecrown/print2a '/storage/nvme5/new_clones/G-code/print2a' &
git clone https://github.com/mkellsy/reprap-delta '/storage/nvme5/new_clones/G-code/reprap-delta' &
git clone https://github.com/JHale716/ShieldsUpNZ '/storage/nvme5/new_clones/G-code/ShieldsUpNZ' &
git clone https://github.com/midoibrahim/Additive_Manufacturing_Using_Serial_Robot '/storage/nvme5/new_clones/G-code/Additive_Manufacturing_Using_Serial_Robot' &
git clone https://github.com/LasseCre/Open-Wing '/storage/nvme5/new_clones/G-code/Open-Wing' &
git clone https://github.com/seemecnc/RostockMAX-v4 '/storage/nvme5/new_clones/G-code/RostockMAX-v4' &
git clone https://github.com/Carbonoid/D1 '/storage/nvme5/new_clones/G-code/D1' &
git clone https://github.com/kkr0kk/bendix-kap-140-AutoPilot '/storage/nvme5/new_clones/G-code/bendix-kap-140-AutoPilot' &
git clone https://github.com/Jardal/A10M-Slic3r-profile '/storage/nvme5/new_clones/G-code/A10M-Slic3r-profile' &
git clone https://github.com/jegamboafuentes/Train_schedule_board '/storage/nvme5/new_clones/G-code/Train_schedule_board' &
git clone https://github.com/dgatwood/VISCAPTZ '/storage/nvme5/new_clones/G-code/VISCAPTZ' &
git clone https://github.com/Photonsters/CBD-based-printers-list '/storage/nvme5/new_clones/G-code/CBD-based-printers-list' &
git clone https://github.com/zayn07/Ender-3-Auto-Print-Removal-Gcode-Condensed- '/storage/nvme5/new_clones/G-code/Ender-3-Auto-Print-Removal-Gcode-Condensed-' &
git clone https://github.com/medicationforall/skirmishbunker '/storage/nvme5/new_clones/G-code/skirmishbunker' &
git clone https://github.com/jorisroovers/window-opener '/storage/nvme5/new_clones/G-code/window-opener' &
git clone https://github.com/elegoogroup/ELEGOO-Mars-Machine-Parameters '/storage/nvme5/new_clones/G-code/ELEGOO-Mars-Machine-Parameters' &
git clone https://github.com/cr8ivecodesmith/ender3_v2_assisted_bed_leveling '/storage/nvme5/new_clones/G-code/ender3_v2_assisted_bed_leveling' &
git clone https://github.com/cretells/ender5plus-klipper '/storage/nvme5/new_clones/G-code/ender5plus-klipper' &
git clone https://github.com/MetaIdea/OpenDroneProject '/storage/nvme5/new_clones/G-code/OpenDroneProject' &
git clone https://github.com/FunOrange/osr-to-gcode '/storage/nvme5/new_clones/G-code/osr-to-gcode' &
git clone https://github.com/SecKit/SK-Cube '/storage/nvme5/new_clones/G-code/SK-Cube' &
git clone https://github.com/WeirdConstructor/3DPrining_MakerGrid '/storage/nvme5/new_clones/G-code/3DPrining_MakerGrid' &
git clone https://github.com/3d-printing-canada/Creality-CP-01-Resources '/storage/nvme5/new_clones/G-code/Creality-CP-01-Resources' &
git clone https://github.com/dgabbe/monoprice-maker-ultimate-3D-printer '/storage/nvme5/new_clones/G-code/monoprice-maker-ultimate-3D-printer' &
git clone https://github.com/mitwelten/mitwelten-iot-hardware-poc '/storage/nvme5/new_clones/G-code/mitwelten-iot-hardware-poc' &
git clone https://github.com/Spiritdude/GCodeToolbox '/storage/nvme5/new_clones/G-code/GCodeToolbox' &
git clone https://github.com/kkr0kk/c172-xpndr '/storage/nvme5/new_clones/G-code/c172-xpndr' &
git clone https://github.com/0x49b/diy-kangal '/storage/nvme5/new_clones/G-code/diy-kangal' &
git clone https://github.com/WPIRoboticsEngineering/RBELabCustomParts '/storage/nvme5/new_clones/G-code/RBELabCustomParts' &
git clone https://github.com/ZONESTAR3D/Z8T '/storage/nvme5/new_clones/G-code/Z8T' &
git clone https://github.com/kostasl/pipettingRobot '/storage/nvme5/new_clones/G-code/pipettingRobot' &
git clone https://github.com/RobotLL/Flipbot '/storage/nvme5/new_clones/G-code/Flipbot' &
git clone https://github.com/mallcong/Therms-Up '/storage/nvme5/new_clones/G-code/Therms-Up' &
git clone https://github.com/ThomasHeb/2AxisLaserCutter '/storage/nvme5/new_clones/G-code/2AxisLaserCutter' &
git clone https://github.com/CSAWHACK3D/Competition '/storage/nvme5/new_clones/G-code/Competition' &
git clone https://github.com/SmittyHalibut/DoubleDeltaSlotAntenna '/storage/nvme5/new_clones/G-code/DoubleDeltaSlotAntenna' &
git clone https://github.com/Xpikuos/Mindnetions '/storage/nvme5/new_clones/G-code/Mindnetions' &
git clone https://github.com/plastibot/nenemiz '/storage/nvme5/new_clones/G-code/nenemiz' &
git clone https://github.com/MKme/face-shield '/storage/nvme5/new_clones/G-code/face-shield' &
git clone https://github.com/pigatron-industries/xen_daisy_dsp '/storage/nvme5/new_clones/G-code/xen_daisy_dsp' &
git clone https://github.com/numberformat/noami3 '/storage/nvme5/new_clones/G-code/noami3' &
git clone https://github.com/pmotch/surgical-mask-clip '/storage/nvme5/new_clones/G-code/surgical-mask-clip' &
git clone https://github.com/Tractorou24/F14-Tomcat-Home-Cockpit '/storage/nvme5/new_clones/G-code/F14-Tomcat-Home-Cockpit' &
git clone https://github.com/ZONESTAR3D/Z6 '/storage/nvme5/new_clones/G-code/Z6' &
git clone https://github.com/jtimon/reprope '/storage/nvme5/new_clones/G-code/reprope' &
git clone https://github.com/publiclab/community-microscope '/storage/nvme5/new_clones/G-code/community-microscope' &
git clone https://github.com/AlyonaMinina/SPIRO.Hardware '/storage/nvme5/new_clones/G-code/SPIRO.Hardware' &
git clone https://github.com/tommy-vaux/Snapmaker_2_PCB_Milling_Process '/storage/nvme5/new_clones/G-code/Snapmaker_2_PCB_Milling_Process' &
git clone https://github.com/ToddZhouFeng/Woodpecker---writing-machine '/storage/nvme5/new_clones/G-code/Woodpecker---writing-machine' &
git clone https://github.com/neilgupta/prusa-octoprint-setup '/storage/nvme5/new_clones/G-code/prusa-octoprint-setup' &
git clone https://github.com/MakeICT/electronic-door '/storage/nvme5/new_clones/G-code/electronic-door' &
git clone https://github.com/susisstrolch/Vertex-Delta-Mods '/storage/nvme5/new_clones/G-code/Vertex-Delta-Mods' &
git clone https://github.com/fellesverkstedet/1810-CNC-Addons '/storage/nvme5/new_clones/G-code/1810-CNC-Addons' &
git clone https://github.com/bryhasagithub/3D-printing '/storage/nvme5/new_clones/G-code/3D-printing' &
git clone https://github.com/petercpark/uni-case '/storage/nvme5/new_clones/G-code/uni-case' &
git clone https://github.com/Autodrop3d/autodrop3dClient '/storage/nvme5/new_clones/G-code/autodrop3dClient' &
git clone https://github.com/AIWerkstatt/SensorBox '/storage/nvme5/new_clones/G-code/SensorBox' &
git clone https://github.com/just-trey/elegoo-neptune-2-tensioner '/storage/nvme5/new_clones/G-code/elegoo-neptune-2-tensioner' &
git clone https://github.com/Shteeeeeve/AB-BN-30-Mod '/storage/nvme5/new_clones/G-code/AB-BN-30-Mod' &
git clone https://github.com/maxx-ukoo/esp32-modbus-tcp2rtu '/storage/nvme5/new_clones/G-code/esp32-modbus-tcp2rtu' &
git clone https://github.com/swindonmakers/LogoBot '/storage/nvme5/new_clones/G-code/LogoBot' &
git clone https://github.com/Charlotte-MEDI/Faceshields '/storage/nvme5/new_clones/G-code/Faceshields' &
git clone https://github.com/cryptobeat/Tronxy-x5sa-pro '/storage/nvme5/new_clones/G-code/Tronxy-x5sa-pro' &
git clone https://github.com/ymm135/shuttlecock '/storage/nvme5/new_clones/G-code/shuttlecock' &
git clone https://github.com/MKme/XtoolD1 '/storage/nvme5/new_clones/G-code/XtoolD1' &
git clone https://github.com/B20bob/sv04 '/storage/nvme5/new_clones/G-code/sv04' &
git clone https://github.com/GendarmerieNationale/Borne-Passe-Sanitaire '/storage/nvme5/new_clones/G-code/Borne-Passe-Sanitaire' &
git clone https://github.com/RichiH/3d_printing '/storage/nvme5/new_clones/G-code/3d_printing' &
git clone https://github.com/manticorp/GcodeWoodener '/storage/nvme5/new_clones/G-code/GcodeWoodener' &
git clone https://github.com/linyuxuanlin/CASTIC '/storage/nvme5/new_clones/G-code/CASTIC' &
git clone https://github.com/fede2cr/circuitpython-braille '/storage/nvme5/new_clones/G-code/circuitpython-braille' &
