#!/bin/bash

git clone https://github.com/sdkman/sdkman-cli '/storage/nvme5/new_clones/Gherkin/sdkman-cli' &
git clone https://github.com/inukshuk/jekyll-scholar '/storage/nvme5/new_clones/Gherkin/jekyll-scholar' &
git clone https://github.com/keygen-sh/keygen-api '/storage/nvme5/new_clones/Gherkin/keygen-api' &
git clone https://github.com/opencypher/openCypher '/storage/nvme5/new_clones/Gherkin/openCypher' &
git clone https://github.com/serverlessworkflow/specification '/storage/nvme5/new_clones/Gherkin/specification' &
git clone https://github.com/scality/Zenko '/storage/nvme5/new_clones/Gherkin/Zenko' &
git clone https://github.com/FriendsOfBehat/SymfonyExtension '/storage/nvme5/new_clones/Gherkin/SymfonyExtension' &
git clone https://github.com/elastic/apm '/storage/nvme5/new_clones/Gherkin/apm' &
git clone https://github.com/Behatch/contexts '/storage/nvme5/new_clones/Gherkin/contexts' &
git clone https://github.com/wildlyinaccurate/jekyll-responsive-image '/storage/nvme5/new_clones/Gherkin/jekyll-responsive-image' &
git clone https://github.com/middleman/middleman-blog '/storage/nvme5/new_clones/Gherkin/middleman-blog' &
git clone https://github.com/reitzig/sdkman-for-fish '/storage/nvme5/new_clones/Gherkin/sdkman-for-fish' &
git clone https://github.com/trema/trema '/storage/nvme5/new_clones/Gherkin/trema' &
git clone https://github.com/hoppinger/advanced-custom-fields-wpcli '/storage/nvme5/new_clones/Gherkin/advanced-custom-fields-wpcli' &
git clone https://github.com/psalm/psalm-plugin-symfony '/storage/nvme5/new_clones/Gherkin/psalm-plugin-symfony' &
git clone https://github.com/FriendsOfBehat/VariadicExtension '/storage/nvme5/new_clones/Gherkin/VariadicExtension' &
git clone https://github.com/FriendsOfBehat/SuiteSettingsExtension '/storage/nvme5/new_clones/Gherkin/SuiteSettingsExtension' &
git clone https://github.com/SAP-archive/BUILD '/storage/nvme5/new_clones/Gherkin/BUILD' &
git clone https://github.com/owasp-cloud-security/owasp-cloud-security '/storage/nvme5/new_clones/Gherkin/owasp-cloud-security' &
git clone https://github.com/iphoting/ovpnmcgen.rb '/storage/nvme5/new_clones/Gherkin/ovpnmcgen.rb' &
git clone https://github.com/wp-cli/scaffold-command '/storage/nvme5/new_clones/Gherkin/scaffold-command' &
git clone https://github.com/Xe/when-then-zen '/storage/nvme5/new_clones/Gherkin/when-then-zen' &
git clone https://github.com/wp-cli/doctor-command '/storage/nvme5/new_clones/Gherkin/doctor-command' &
git clone https://github.com/bbc/bbc-a11y '/storage/nvme5/new_clones/Gherkin/bbc-a11y' &
git clone https://github.com/waterlink/rspec-json_expectations '/storage/nvme5/new_clones/Gherkin/rspec-json_expectations' &
git clone https://github.com/p0deje/vagrant-exec '/storage/nvme5/new_clones/Gherkin/vagrant-exec' &
git clone https://github.com/ChrisChinchilla/Openly '/storage/nvme5/new_clones/Gherkin/Openly' &
git clone https://github.com/jason-johnson/azure-pipelines-tasks-terraform '/storage/nvme5/new_clones/Gherkin/azure-pipelines-tasks-terraform' &
git clone https://github.com/salad/salad '/storage/nvme5/new_clones/Gherkin/salad' &
git clone https://github.com/FriendsOfBehat/ServiceContainerExtension '/storage/nvme5/new_clones/Gherkin/ServiceContainerExtension' &
git clone https://github.com/p0deje/yard-doctest '/storage/nvme5/new_clones/Gherkin/yard-doctest' &
git clone https://github.com/ac3cloud/ript '/storage/nvme5/new_clones/Gherkin/ript' &
git clone https://github.com/apiaryio/gavel-spec '/storage/nvme5/new_clones/Gherkin/gavel-spec' &
git clone https://github.com/wp-cli/i18n-command '/storage/nvme5/new_clones/Gherkin/i18n-command' &
git clone https://github.com/BBVA/patton '/storage/nvme5/new_clones/Gherkin/patton' &
git clone https://github.com/selenium-cucumber/selenium-cucumber-java-maven-example '/storage/nvme5/new_clones/Gherkin/selenium-cucumber-java-maven-example' &
git clone https://github.com/danielbayerlein/middleman-google-analytics '/storage/nvme5/new_clones/Gherkin/middleman-google-analytics' &
git clone https://github.com/rejeep/ruby-tools.el '/storage/nvme5/new_clones/Gherkin/ruby-tools.el' &
git clone https://github.com/errata-ai/Microsoft '/storage/nvme5/new_clones/Gherkin/Microsoft' &
git clone https://github.com/psalm/psalm-plugin-doctrine '/storage/nvme5/new_clones/Gherkin/psalm-plugin-doctrine' &
git clone https://github.com/wp-cli/wp-cli-bundle '/storage/nvme5/new_clones/Gherkin/wp-cli-bundle' &
git clone https://github.com/samueltbrown/gradle-cucumber-plugin '/storage/nvme5/new_clones/Gherkin/gradle-cucumber-plugin' &
git clone https://github.com/psalm/psalm-plugin-phpunit '/storage/nvme5/new_clones/Gherkin/psalm-plugin-phpunit' &
git clone https://github.com/awendt/poet '/storage/nvme5/new_clones/Gherkin/poet' &
git clone https://github.com/minishift/minishift-addons '/storage/nvme5/new_clones/Gherkin/minishift-addons' &
git clone https://github.com/errata-ai/Google '/storage/nvme5/new_clones/Gherkin/Google' &
git clone https://github.com/wp-cli/scaffold-package-command '/storage/nvme5/new_clones/Gherkin/scaffold-package-command' &
git clone https://github.com/middleman/middleman-sprockets '/storage/nvme5/new_clones/Gherkin/middleman-sprockets' &
git clone https://github.com/lvbag/BAG-API '/storage/nvme5/new_clones/Gherkin/BAG-API' &
git clone https://github.com/wp-cli/search-replace-command '/storage/nvme5/new_clones/Gherkin/search-replace-command' &
git clone https://github.com/wp-cli/dist-archive-command '/storage/nvme5/new_clones/Gherkin/dist-archive-command' &
git clone https://github.com/wp-cli/core-command '/storage/nvme5/new_clones/Gherkin/core-command' &
git clone https://github.com/jboss-openshift/cct_module '/storage/nvme5/new_clones/Gherkin/cct_module' &
git clone https://github.com/Xray-App/xray-postman-collections '/storage/nvme5/new_clones/Gherkin/xray-postman-collections' &
git clone https://github.com/camaraproject/QualityOnDemand '/storage/nvme5/new_clones/Gherkin/QualityOnDemand' &
git clone https://github.com/wp-cli/media-command '/storage/nvme5/new_clones/Gherkin/media-command' &
git clone https://github.com/CloudCannon/rosey '/storage/nvme5/new_clones/Gherkin/rosey' &
git clone https://github.com/jboss-container-images/jboss-eap-7-openshift-image '/storage/nvme5/new_clones/Gherkin/jboss-eap-7-openshift-image' &
git clone https://github.com/splattael/minitest-around '/storage/nvme5/new_clones/Gherkin/minitest-around' &
git clone https://github.com/b-yond-infinite-network/md-to-adf '/storage/nvme5/new_clones/Gherkin/md-to-adf' &
git clone https://github.com/camiloribeiro/cucumber-gradle-parallel '/storage/nvme5/new_clones/Gherkin/cucumber-gradle-parallel' &
git clone https://github.com/DigitalState/Platform '/storage/nvme5/new_clones/Gherkin/Platform' &
git clone https://github.com/ShittySoft/symfony-live-berlin-2018-doctrine-tutorial '/storage/nvme5/new_clones/Gherkin/symfony-live-berlin-2018-doctrine-tutorial' &
git clone https://github.com/wp-cli/config-command '/storage/nvme5/new_clones/Gherkin/config-command' &
git clone https://github.com/alsaydi/sarf '/storage/nvme5/new_clones/Gherkin/sarf' &
git clone https://github.com/hedongxiao-tju/HOG-GCN '/storage/nvme5/new_clones/Gherkin/HOG-GCN' &
git clone https://github.com/funkwerk/gherkin_lint '/storage/nvme5/new_clones/Gherkin/gherkin_lint' &
git clone https://github.com/BRP-API/Haal-Centraal-BRP-bevragen '/storage/nvme5/new_clones/Gherkin/Haal-Centraal-BRP-bevragen' &
git clone https://github.com/allure-framework/allure-cucumber '/storage/nvme5/new_clones/Gherkin/allure-cucumber' &
git clone https://github.com/adambullmer/USDLRegex '/storage/nvme5/new_clones/Gherkin/USDLRegex' &
git clone https://github.com/ShittySoft/fwdays-2018-doctrine-tutorial '/storage/nvme5/new_clones/Gherkin/fwdays-2018-doctrine-tutorial' &
git clone https://github.com/hpatoio/bitly-api '/storage/nvme5/new_clones/Gherkin/bitly-api' &
git clone https://github.com/errata-ai/write-good '/storage/nvme5/new_clones/Gherkin/write-good' &
git clone https://github.com/DoublesunRUS/devscripts '/storage/nvme5/new_clones/Gherkin/devscripts' &
git clone https://github.com/techservicesillinois/terraform-aws-ecs-service '/storage/nvme5/new_clones/Gherkin/terraform-aws-ecs-service' &
git clone https://github.com/camaraproject/SimSwap '/storage/nvme5/new_clones/Gherkin/SimSwap' &
git clone https://github.com/keelerm84/php-refactor-mode.el '/storage/nvme5/new_clones/Gherkin/php-refactor-mode.el' &
git clone https://github.com/gojuno/jrg '/storage/nvme5/new_clones/Gherkin/jrg' &
git clone https://github.com/camaraproject/DeviceLocation '/storage/nvme5/new_clones/Gherkin/DeviceLocation' &
git clone https://github.com/vl-lit/DevelopingAndTestingWithVanessa '/storage/nvme5/new_clones/Gherkin/DevelopingAndTestingWithVanessa' &
git clone https://github.com/middleman/middleman-asciidoc '/storage/nvme5/new_clones/Gherkin/middleman-asciidoc' &
git clone https://github.com/Soluto/containers-security-project '/storage/nvme5/new_clones/Gherkin/containers-security-project' &
git clone https://github.com/ducminh-phan/reformat-gherkin '/storage/nvme5/new_clones/Gherkin/reformat-gherkin' &
git clone https://github.com/jgsheffer/glyptic_training_materials '/storage/nvme5/new_clones/Gherkin/glyptic_training_materials' &
git clone https://github.com/ye-kyaw-thu/Tutorials '/storage/nvme5/new_clones/Gherkin/Tutorials' &
git clone https://github.com/errata-ai/IBM '/storage/nvme5/new_clones/Gherkin/IBM' &
git clone https://github.com/Magicianred/React_Examples '/storage/nvme5/new_clones/Gherkin/React_Examples' &
git clone https://github.com/errata-ai/proselint '/storage/nvme5/new_clones/Gherkin/proselint' &
git clone https://github.com/Corvusoft/restq '/storage/nvme5/new_clones/Gherkin/restq' &
git clone https://github.com/dhis2/design-system '/storage/nvme5/new_clones/Gherkin/design-system' &
git clone https://github.com/bondar-artem/karate-dsl-class '/storage/nvme5/new_clones/Gherkin/karate-dsl-class' &
git clone https://github.com/algorand/algorand-sdk-testing '/storage/nvme5/new_clones/Gherkin/algorand-sdk-testing' &
git clone https://github.com/andrii/devise-specs '/storage/nvme5/new_clones/Gherkin/devise-specs' &
git clone https://github.com/inukshuk/citeproc '/storage/nvme5/new_clones/Gherkin/citeproc' &
git clone https://github.com/databinding-gmbh/T4.FileManager.VisualStudio '/storage/nvme5/new_clones/Gherkin/T4.FileManager.VisualStudio' &
git clone https://github.com/ptrthomas/karate-gatling-demo '/storage/nvme5/new_clones/Gherkin/karate-gatling-demo' &
git clone https://github.com/silverbulleters/whereismythirty '/storage/nvme5/new_clones/Gherkin/whereismythirty' &
git clone https://github.com/mdsol/dice_bag '/storage/nvme5/new_clones/Gherkin/dice_bag' &
git clone https://github.com/kadaster/BRK-bevragen '/storage/nvme5/new_clones/Gherkin/BRK-bevragen' &
git clone https://github.com/Leirunlin/EvenNet '/storage/nvme5/new_clones/Gherkin/EvenNet' &
git clone https://github.com/camaraproject/NumberVerification '/storage/nvme5/new_clones/Gherkin/NumberVerification' &
git clone https://github.com/rahulrathore44/KarateFrameworkTutorial '/storage/nvme5/new_clones/Gherkin/KarateFrameworkTutorial' &
git clone https://github.com/wp-cli/google-sitemap-generator-cli '/storage/nvme5/new_clones/Gherkin/google-sitemap-generator-cli' &
git clone https://github.com/camaraproject/EdgeCloud '/storage/nvme5/new_clones/Gherkin/EdgeCloud' &
git clone https://github.com/lakmeer/zbalermorna '/storage/nvme5/new_clones/Gherkin/zbalermorna' &
git clone https://github.com/f103a26/lustin-sticker-pack '/storage/nvme5/new_clones/Gherkin/lustin-sticker-pack' &
git clone https://github.com/mapado/prettier-plugin-gherkin '/storage/nvme5/new_clones/Gherkin/prettier-plugin-gherkin' &
git clone https://github.com/uestc-lese/SPGRL '/storage/nvme5/new_clones/Gherkin/SPGRL' &
git clone https://github.com/bddbooks/bddbooks-formulation-wimp '/storage/nvme5/new_clones/Gherkin/bddbooks-formulation-wimp' &
git clone https://github.com/errata-ai/alex '/storage/nvme5/new_clones/Gherkin/alex' &
git clone https://github.com/ernestio/ernest '/storage/nvme5/new_clones/Gherkin/ernest' &
git clone https://github.com/enroute-mobi/ara '/storage/nvme5/new_clones/Gherkin/ara' &
git clone https://github.com/cheezy/testgen '/storage/nvme5/new_clones/Gherkin/testgen' &
git clone https://github.com/vivekaka/testleaf_code '/storage/nvme5/new_clones/Gherkin/testleaf_code' &
git clone https://github.com/keveridge/WolframAlphaKit '/storage/nvme5/new_clones/Gherkin/WolframAlphaKit' &
git clone https://github.com/pantheon-systems/pantheon-wordpress-upstream-tests '/storage/nvme5/new_clones/Gherkin/pantheon-wordpress-upstream-tests' &
git clone https://github.com/vccw-team/boilerplate-behat-wordpress '/storage/nvme5/new_clones/Gherkin/boilerplate-behat-wordpress' &
git clone https://github.com/jvking/bp-lda '/storage/nvme5/new_clones/Gherkin/bp-lda' &
git clone https://github.com/Vanguard-oss/behave-asl '/storage/nvme5/new_clones/Gherkin/behave-asl' &
git clone https://github.com/mdsol/skyfire '/storage/nvme5/new_clones/Gherkin/skyfire' &
git clone https://github.com/ashmaroli/jekyll-tagories '/storage/nvme5/new_clones/Gherkin/jekyll-tagories' &
git clone https://github.com/leeonky/jfactory '/storage/nvme5/new_clones/Gherkin/jfactory' &
git clone https://github.com/epam-deik-cooperation/epam-deik-java-dev '/storage/nvme5/new_clones/Gherkin/epam-deik-java-dev' &
git clone https://github.com/qavajs/demo '/storage/nvme5/new_clones/Gherkin/demo' &
git clone https://github.com/actiontech/dble-test-suite '/storage/nvme5/new_clones/Gherkin/dble-test-suite' &
git clone https://github.com/DigitalState/Services '/storage/nvme5/new_clones/Gherkin/Services' &
git clone https://github.com/camaraproject/DeviceStatus '/storage/nvme5/new_clones/Gherkin/DeviceStatus' &
git clone https://github.com/tkotosz/BehatMagento2Extension '/storage/nvme5/new_clones/Gherkin/BehatMagento2Extension' &
git clone https://github.com/wp-cli/super-admin-command '/storage/nvme5/new_clones/Gherkin/super-admin-command' &
git clone https://github.com/PacktPublishing/Writing-API-Tests-with-Karate '/storage/nvme5/new_clones/Gherkin/Writing-API-Tests-with-Karate' &
git clone https://github.com/shunsunsun/GraphModel '/storage/nvme5/new_clones/Gherkin/GraphModel' &
git clone https://github.com/typedb/typedb-behaviour '/storage/nvme5/new_clones/Gherkin/typedb-behaviour' &
git clone https://github.com/camaraproject/CarrierBillingCheckOut '/storage/nvme5/new_clones/Gherkin/CarrierBillingCheckOut' &
git clone https://github.com/ShittySoft/symfony-live-berlin-2019-doctrine-tutorial '/storage/nvme5/new_clones/Gherkin/symfony-live-berlin-2019-doctrine-tutorial' &
git clone https://github.com/bemusic/bmspec '/storage/nvme5/new_clones/Gherkin/bmspec' &
git clone https://github.com/wokas36/DFNets '/storage/nvme5/new_clones/Gherkin/DFNets' &
git clone https://github.com/crdoconnor/orji '/storage/nvme5/new_clones/Gherkin/orji' &
git clone https://github.com/Cybertek-B15Local/fall-2019-va-karate-framework '/storage/nvme5/new_clones/Gherkin/fall-2019-va-karate-framework' &
git clone https://github.com/jialei0701/ANN '/storage/nvme5/new_clones/Gherkin/ANN' &
git clone https://github.com/pawelWritesCode/godog-http-api '/storage/nvme5/new_clones/Gherkin/godog-http-api' &
git clone https://github.com/errata-ai/Joblint '/storage/nvme5/new_clones/Gherkin/Joblint' &
git clone https://github.com/cyclelabscloud/cycle-cloud '/storage/nvme5/new_clones/Gherkin/cycle-cloud' &
git clone https://github.com/hiromia006/reqresKarateApiWithMaven '/storage/nvme5/new_clones/Gherkin/reqresKarateApiWithMaven' &
git clone https://github.com/ernilambar/database-command '/storage/nvme5/new_clones/Gherkin/database-command' &
git clone https://github.com/Practically/PsalmPluginYii2 '/storage/nvme5/new_clones/Gherkin/PsalmPluginYii2' &
git clone https://github.com/danbuckland/crudecumber '/storage/nvme5/new_clones/Gherkin/crudecumber' &
git clone https://github.com/serenity-bdd/serenity-banking-demo '/storage/nvme5/new_clones/Gherkin/serenity-banking-demo' &
git clone https://github.com/wearefriday/eyemask '/storage/nvme5/new_clones/Gherkin/eyemask' &
git clone https://github.com/wp-cli/eval-command '/storage/nvme5/new_clones/Gherkin/eval-command' &
git clone https://github.com/fkupper/psalm-laravel-collections '/storage/nvme5/new_clones/Gherkin/psalm-laravel-collections' &
git clone https://github.com/apitestingco/KarateAPIAutomation '/storage/nvme5/new_clones/Gherkin/KarateAPIAutomation' &
git clone https://github.com/abruzzi/pre-iteration-zero '/storage/nvme5/new_clones/Gherkin/pre-iteration-zero' &
git clone https://github.com/jboss-container-images/jboss-openjdk-image '/storage/nvme5/new_clones/Gherkin/jboss-openjdk-image' &
git clone https://github.com/Sahamati/certification-framework '/storage/nvme5/new_clones/Gherkin/certification-framework' &
git clone https://github.com/VadimMustyatsa/three_trips '/storage/nvme5/new_clones/Gherkin/three_trips' &
git clone https://github.com/ShittySoft/php-ce-2018-doctrine-tutorial '/storage/nvme5/new_clones/Gherkin/php-ce-2018-doctrine-tutorial' &
git clone https://github.com/camaraproject/OTPValidation '/storage/nvme5/new_clones/Gherkin/OTPValidation' &
git clone https://github.com/Sv-Vik/MeetUp '/storage/nvme5/new_clones/Gherkin/MeetUp' &
git clone https://github.com/jboss-container-images/jboss-eap-modules '/storage/nvme5/new_clones/Gherkin/jboss-eap-modules' &
git clone https://github.com/Blodwynn/.feature-file-syntax-highlight-Cucumber- '/storage/nvme5/new_clones/Gherkin/.feature-file-syntax-highlight-Cucumber-' &
git clone https://github.com/startupemulator/challenges '/storage/nvme5/new_clones/Gherkin/challenges' &
git clone https://github.com/yoshuawuyts/plan '/storage/nvme5/new_clones/Gherkin/plan' &
git clone https://github.com/cucumber/cucumber-ruby-wire '/storage/nvme5/new_clones/Gherkin/cucumber-ruby-wire' &
git clone https://github.com/grasshopper7/cuke7-extent-adapter-report '/storage/nvme5/new_clones/Gherkin/cuke7-extent-adapter-report' &
git clone https://github.com/maxuechaogao/demo-cucumber '/storage/nvme5/new_clones/Gherkin/demo-cucumber' &
git clone https://github.com/sodper/mi-afu-vt18 '/storage/nvme5/new_clones/Gherkin/mi-afu-vt18' &
git clone https://github.com/vishalm/behave_parallel_demo '/storage/nvme5/new_clones/Gherkin/behave_parallel_demo' &
git clone https://github.com/geeksam/poker-dice '/storage/nvme5/new_clones/Gherkin/poker-dice' &
git clone https://github.com/solid-contrib/specification-tests '/storage/nvme5/new_clones/Gherkin/specification-tests' &
git clone https://github.com/feduxorg-attic/proxy_rb '/storage/nvme5/new_clones/Gherkin/proxy_rb' &
git clone https://github.com/libre-devops/azure-naming-convention '/storage/nvme5/new_clones/Gherkin/azure-naming-convention' &
git clone https://github.com/wp-cli/embed-command '/storage/nvme5/new_clones/Gherkin/embed-command' &
git clone https://github.com/YuetongXU/Cropgbm-genomebiology '/storage/nvme5/new_clones/Gherkin/Cropgbm-genomebiology' &
git clone https://github.com/zhoushengisnoob/DGE '/storage/nvme5/new_clones/Gherkin/DGE' &
git clone https://github.com/Crown-Commercial-Service/digitalmarketplace-functional-tests '/storage/nvme5/new_clones/Gherkin/digitalmarketplace-functional-tests' &
git clone https://github.com/NCATS-Tangerine/translator-testing-framework '/storage/nvme5/new_clones/Gherkin/translator-testing-framework' &
git clone https://github.com/samlucax/karate-example '/storage/nvme5/new_clones/Gherkin/karate-example' &
git clone https://github.com/charleseff/git-blame-game '/storage/nvme5/new_clones/Gherkin/git-blame-game' &
git clone https://github.com/HL7/fhir-project-mhealth '/storage/nvme5/new_clones/Gherkin/fhir-project-mhealth' &
git clone https://github.com/SUSE/spacewalk-testsuite-base '/storage/nvme5/new_clones/Gherkin/spacewalk-testsuite-base' &
git clone https://github.com/DigitalState/Authentication '/storage/nvme5/new_clones/Gherkin/Authentication' &
git clone https://github.com/ShittySoft/symfony-live-phantasialand-2018-doctrine-tutorial '/storage/nvme5/new_clones/Gherkin/symfony-live-phantasialand-2018-doctrine-tutorial' &
git clone https://github.com/yazidisme/karate-api-testing '/storage/nvme5/new_clones/Gherkin/karate-api-testing' &
git clone https://github.com/stepushchenko/developer '/storage/nvme5/new_clones/Gherkin/developer' &
git clone https://github.com/Tavalik/VA-Tests-UH32-Smoke '/storage/nvme5/new_clones/Gherkin/VA-Tests-UH32-Smoke' &
git clone https://github.com/SkillsFundingAgency/das-paymentsacceptancetesting '/storage/nvme5/new_clones/Gherkin/das-paymentsacceptancetesting' &
git clone https://github.com/Holo-Host/holo-api-test-template '/storage/nvme5/new_clones/Gherkin/holo-api-test-template' &
git clone https://github.com/dayane-rosas/O-dia-a-dia-de-um-QA '/storage/nvme5/new_clones/Gherkin/O-dia-a-dia-de-um-QA' &
git clone https://github.com/zhengjingwei/cluster_GCN '/storage/nvme5/new_clones/Gherkin/cluster_GCN' &
git clone https://github.com/spriteCloud/ecommerce-cucumber-web-test-automation-suite '/storage/nvme5/new_clones/Gherkin/ecommerce-cucumber-web-test-automation-suite' &
git clone https://github.com/neillfontes/karate-sample '/storage/nvme5/new_clones/Gherkin/karate-sample' &
git clone https://github.com/openshift-integration/camel-k-example-api '/storage/nvme5/new_clones/Gherkin/camel-k-example-api' &
git clone https://github.com/mikeparcewski/aws-openapi '/storage/nvme5/new_clones/Gherkin/aws-openapi' &
git clone https://github.com/deepstreamIO/deepstream.io-client-specs '/storage/nvme5/new_clones/Gherkin/deepstream.io-client-specs' &
git clone https://github.com/ptrthomas/karate-sikulix-demo '/storage/nvme5/new_clones/Gherkin/karate-sikulix-demo' &
git clone https://github.com/weltraumpirat/ws_test_driving_your_domain_core_js '/storage/nvme5/new_clones/Gherkin/ws_test_driving_your_domain_core_js' &
git clone https://github.com/KrapivinAndrey/infostart2020-DevOps1c-Mockdemo '/storage/nvme5/new_clones/Gherkin/infostart2020-DevOps1c-Mockdemo' &
git clone https://github.com/VNG-Realisatie/API-Kennisbank '/storage/nvme5/new_clones/Gherkin/API-Kennisbank' &
git clone https://github.com/VadimMustyatsa/subbotnik.by '/storage/nvme5/new_clones/Gherkin/subbotnik.by' &
