#!/bin/bash

git clone https://github.com/fossasia/pslab-grove-shield '/storage/nvme5/new_clones/Gnuplot/pslab-grove-shield' &
git clone https://github.com/karlrupp/microprocessor-trend-data '/storage/nvme5/new_clones/Gnuplot/microprocessor-trend-data' &
git clone https://github.com/quinntaylor/CHDataStructures '/storage/nvme5/new_clones/Gnuplot/CHDataStructures' &
git clone https://github.com/aschn/gnuplot-colorbrewer '/storage/nvme5/new_clones/Gnuplot/gnuplot-colorbrewer' &
git clone https://github.com/quantumNerd/Quantum-Espresso-Tutorial-2019-Projects '/storage/nvme5/new_clones/Gnuplot/Quantum-Espresso-Tutorial-2019-Projects' &
git clone https://github.com/chinanf-boy/tokei-zh '/storage/nvme5/new_clones/Gnuplot/tokei-zh' &
git clone https://github.com/ThomasVDD/SmartSupply '/storage/nvme5/new_clones/Gnuplot/SmartSupply' &
git clone https://github.com/TheFox/gnuplot-examples '/storage/nvme5/new_clones/Gnuplot/gnuplot-examples' &
git clone https://github.com/aliireza/packetmill '/storage/nvme5/new_clones/Gnuplot/packetmill' &
git clone https://github.com/royrobotiks/Graffomat '/storage/nvme5/new_clones/Gnuplot/Graffomat' &
git clone https://github.com/karlrupp/cpu-gpu-mic-comparison '/storage/nvme5/new_clones/Gnuplot/cpu-gpu-mic-comparison' &
git clone https://github.com/eurostat/econowcast '/storage/nvme5/new_clones/Gnuplot/econowcast' &
git clone https://github.com/96boards/mezzanine-community '/storage/nvme5/new_clones/Gnuplot/mezzanine-community' &
git clone https://github.com/halohyx/MatMec '/storage/nvme5/new_clones/Gnuplot/MatMec' &
git clone https://github.com/agentzh/mysql-driver-benchmark '/storage/nvme5/new_clones/Gnuplot/mysql-driver-benchmark' &
git clone https://github.com/rehnd/MoS2-band-structure '/storage/nvme5/new_clones/Gnuplot/MoS2-band-structure' &
git clone https://github.com/ekfoury/iperf3_plotter '/storage/nvme5/new_clones/Gnuplot/iperf3_plotter' &
git clone https://github.com/hamidgh09/Reframer '/storage/nvme5/new_clones/Gnuplot/Reframer' &
git clone https://github.com/rfonseca/xkcd-gnuplot '/storage/nvme5/new_clones/Gnuplot/xkcd-gnuplot' &
git clone https://github.com/odo/quantile_estimator '/storage/nvme5/new_clones/Gnuplot/quantile_estimator' &
git clone https://github.com/materialscloud-org/hubbard-koopmans-2022 '/storage/nvme5/new_clones/Gnuplot/hubbard-koopmans-2022' &
git clone https://github.com/swayli94/cst-modeling3d '/storage/nvme5/new_clones/Gnuplot/cst-modeling3d' &
git clone https://github.com/MicroBlocksCN/smallvm '/storage/nvme5/new_clones/Gnuplot/smallvm' &
git clone https://github.com/npuljc/RL_control_Nek5000 '/storage/nvme5/new_clones/Gnuplot/RL_control_Nek5000' &
git clone https://github.com/OkanKoeksal/Spin-Texture-VASP '/storage/nvme5/new_clones/Gnuplot/Spin-Texture-VASP' &
git clone https://github.com/gcr/pdf-read '/storage/nvme5/new_clones/Gnuplot/pdf-read' &
git clone https://github.com/hesstobi/Gnuplot-Templates '/storage/nvme5/new_clones/Gnuplot/Gnuplot-Templates' &
git clone https://github.com/ADC-TEAM2020/avsdadc_3v3 '/storage/nvme5/new_clones/Gnuplot/avsdadc_3v3' &
git clone https://github.com/ChaoHuang2018/POLAR_Tool '/storage/nvme5/new_clones/Gnuplot/POLAR_Tool' &
git clone https://github.com/ebugger/Empirical-Roofline-Toolkit '/storage/nvme5/new_clones/Gnuplot/Empirical-Roofline-Toolkit' &
git clone https://github.com/jhmaloney/GP-Mods '/storage/nvme5/new_clones/Gnuplot/GP-Mods' &
git clone https://github.com/oktat/tan '/storage/nvme5/new_clones/Gnuplot/tan' &
git clone https://github.com/blackcata/1D-RANS '/storage/nvme5/new_clones/Gnuplot/1D-RANS' &
git clone https://github.com/cirosantilli/gnuplot-cheat '/storage/nvme5/new_clones/Gnuplot/gnuplot-cheat' &
git clone https://github.com/XuanLi728/Mining-Pattern '/storage/nvme5/new_clones/Gnuplot/Mining-Pattern' &
git clone https://github.com/K4ys4r/BoltzGnu '/storage/nvme5/new_clones/Gnuplot/BoltzGnu' &
git clone https://github.com/susilehtola/fosschemistry '/storage/nvme5/new_clones/Gnuplot/fosschemistry' &
git clone https://github.com/ob/cache '/storage/nvme5/new_clones/Gnuplot/cache' &
git clone https://github.com/Gnuplotting/gnuplot-basics '/storage/nvme5/new_clones/Gnuplot/gnuplot-basics' &
git clone https://github.com/pritam001/ns3-dumbell-topology-simulation '/storage/nvme5/new_clones/Gnuplot/ns3-dumbell-topology-simulation' &
git clone https://github.com/ThomasVDD/SmartSupplyMini '/storage/nvme5/new_clones/Gnuplot/SmartSupplyMini' &
git clone https://github.com/aptech/gauss_blog '/storage/nvme5/new_clones/Gnuplot/gauss_blog' &
git clone https://github.com/ttahsin-bey/FCC64 '/storage/nvme5/new_clones/Gnuplot/FCC64' &
git clone https://github.com/ucdavis-bioinformatics-training/2020-Advanced_Single_Cell_RNA_Seq '/storage/nvme5/new_clones/Gnuplot/2020-Advanced_Single_Cell_RNA_Seq' &
git clone https://github.com/shekfeh/gromacs-tutorials '/storage/nvme5/new_clones/Gnuplot/gromacs-tutorials' &
git clone https://github.com/excamera/salsify-results '/storage/nvme5/new_clones/Gnuplot/salsify-results' &
git clone https://github.com/Gnuplotting/blog-entries '/storage/nvme5/new_clones/Gnuplot/blog-entries' &
git clone https://github.com/micb25/RKI_COVID19_DATA '/storage/nvme5/new_clones/Gnuplot/RKI_COVID19_DATA' &
git clone https://github.com/MartyMacGyver/memristor-modeling '/storage/nvme5/new_clones/Gnuplot/memristor-modeling' &
git clone https://github.com/syncsynchalt/illustrated-x25519 '/storage/nvme5/new_clones/Gnuplot/illustrated-x25519' &
git clone https://github.com/shaneson0/GeoLifeDataMining '/storage/nvme5/new_clones/Gnuplot/GeoLifeDataMining' &
git clone https://github.com/rmojgani/CFD_AUT '/storage/nvme5/new_clones/Gnuplot/CFD_AUT' &
git clone https://github.com/tdaede/toshiba-64mbit-adapter '/storage/nvme5/new_clones/Gnuplot/toshiba-64mbit-adapter' &
git clone https://github.com/Chengcheng-Xiao/TB_play '/storage/nvme5/new_clones/Gnuplot/TB_play' &
git clone https://github.com/envido32/rfid-zapper '/storage/nvme5/new_clones/Gnuplot/rfid-zapper' &
git clone https://github.com/bourdin/VPFHF '/storage/nvme5/new_clones/Gnuplot/VPFHF' &
git clone https://github.com/CRGreathouse/PARI-extensions '/storage/nvme5/new_clones/Gnuplot/PARI-extensions' &
git clone https://github.com/kkonradpl/mpx-power '/storage/nvme5/new_clones/Gnuplot/mpx-power' &
git clone https://github.com/1z2s3e4v/3d-placer '/storage/nvme5/new_clones/Gnuplot/3d-placer' &
git clone https://github.com/PanderMusubi/umik-1 '/storage/nvme5/new_clones/Gnuplot/umik-1' &
git clone https://github.com/XiaogangHe/Princeton-CEE306 '/storage/nvme5/new_clones/Gnuplot/Princeton-CEE306' &
git clone https://github.com/higgicd/LSGI545_2019 '/storage/nvme5/new_clones/Gnuplot/LSGI545_2019' &
git clone https://github.com/blackcata/SEM '/storage/nvme5/new_clones/Gnuplot/SEM' &
git clone https://github.com/dingzhw/RotorTrim '/storage/nvme5/new_clones/Gnuplot/RotorTrim' &
git clone https://github.com/jshorstman/Analog-XY-Plotter-Output-to-HPGL-Translator '/storage/nvme5/new_clones/Gnuplot/Analog-XY-Plotter-Output-to-HPGL-Translator' &
git clone https://github.com/iselab-dearborn/gnuplot-scripts '/storage/nvme5/new_clones/Gnuplot/gnuplot-scripts' &
git clone https://github.com/Ckath/k8split '/storage/nvme5/new_clones/Gnuplot/k8split' &
git clone https://github.com/ltalirz/epw-school-2021 '/storage/nvme5/new_clones/Gnuplot/epw-school-2021' &
git clone https://github.com/vlcampos/OpenPhantom '/storage/nvme5/new_clones/Gnuplot/OpenPhantom' &
git clone https://github.com/Chengcheng-Xiao/VASP_DF2-C09 '/storage/nvme5/new_clones/Gnuplot/VASP_DF2-C09' &
git clone https://github.com/janert/gnuplot-in-action-2e '/storage/nvme5/new_clones/Gnuplot/gnuplot-in-action-2e' &
git clone https://github.com/ccicconetti/queer '/storage/nvme5/new_clones/Gnuplot/queer' &
git clone https://github.com/warrickball/tomso '/storage/nvme5/new_clones/Gnuplot/tomso' &
git clone https://github.com/MarcNeveu/ExoCcycleGeo '/storage/nvme5/new_clones/Gnuplot/ExoCcycleGeo' &
git clone https://github.com/RazorX/Positronic_Color_Palette_for_Python_Wing_IDE '/storage/nvme5/new_clones/Gnuplot/Positronic_Color_Palette_for_Python_Wing_IDE' &
git clone https://github.com/ervanalb/lux '/storage/nvme5/new_clones/Gnuplot/lux' &
git clone https://github.com/steger123/Lawn-mower-robot '/storage/nvme5/new_clones/Gnuplot/Lawn-mower-robot' &
git clone https://github.com/tangophi/iot_wall_socket '/storage/nvme5/new_clones/Gnuplot/iot_wall_socket' &
git clone https://github.com/thepranab/DFT-MASTANI-School-IISER-Pune-2014 '/storage/nvme5/new_clones/Gnuplot/DFT-MASTANI-School-IISER-Pune-2014' &
git clone https://github.com/khueue/prolog-bson '/storage/nvme5/new_clones/Gnuplot/prolog-bson' &
git clone https://github.com/EvanKrall/minipcie_nvme_adapter '/storage/nvme5/new_clones/Gnuplot/minipcie_nvme_adapter' &
git clone https://github.com/DrBenEvans/Boltzmann-BGK '/storage/nvme5/new_clones/Gnuplot/Boltzmann-BGK' &
git clone https://github.com/yychenleslie/SoftMatterDiscuss '/storage/nvme5/new_clones/Gnuplot/SoftMatterDiscuss' &
git clone https://github.com/danielpetri1/complex-number-plotter '/storage/nvme5/new_clones/Gnuplot/complex-number-plotter' &
git clone https://github.com/jaemolihm/WannierFunctions.jl '/storage/nvme5/new_clones/Gnuplot/WannierFunctions.jl' &
git clone https://github.com/jze/ocropus-model_cyrillic '/storage/nvme5/new_clones/Gnuplot/ocropus-model_cyrillic' &
git clone https://github.com/mamad60/TEACH-2E-CFD-CODE '/storage/nvme5/new_clones/Gnuplot/TEACH-2E-CFD-CODE' &
git clone https://github.com/nlfiedler/pcgeos-apps '/storage/nvme5/new_clones/Gnuplot/pcgeos-apps' &
git clone https://github.com/purohit/chinese-ngram-stats '/storage/nvme5/new_clones/Gnuplot/chinese-ngram-stats' &
git clone https://github.com/OpenWALAS/OpenWALAS.github.io '/storage/nvme5/new_clones/Gnuplot/OpenWALAShub.io' &
git clone https://github.com/adenchfi/electron-phonon-coupling '/storage/nvme5/new_clones/Gnuplot/electron-phonon-coupling' &
git clone https://github.com/hiroloquy/inverted-pendulum-simulation '/storage/nvme5/new_clones/Gnuplot/inverted-pendulum-simulation' &
git clone https://github.com/model-checking/kani-verifier-blog '/storage/nvme5/new_clones/Gnuplot/kani-verifier-blog' &
git clone https://github.com/Clloud/MostPopularRoute '/storage/nvme5/new_clones/Gnuplot/MostPopularRoute' &
