#!/bin/bash

git clone https://github.com/rust-unofficial/patterns '/storage/nvme5/new_clones/Handlebars/patterns' &
git clone https://github.com/rust-lang/rust-by-example '/storage/nvme5/new_clones/Handlebars/rust-by-example' &
git clone https://github.com/yeun/open-color '/storage/nvme5/new_clones/Handlebars/open-color' &
git clone https://github.com/ibeatai/beat-ai '/storage/nvme5/new_clones/Handlebars/beat-ai' &
git clone https://github.com/rustwasm/book '/storage/nvme5/new_clones/Handlebars/book' &
git clone https://github.com/wet-boew/wet-boew '/storage/nvme5/new_clones/Handlebars/wet-boew' &
git clone https://github.com/electron/electronjs.org-old '/storage/nvme5/new_clones/Handlebars/electronjs.org-old' &
git clone https://github.com/rtorr/vim-cheat-sheet '/storage/nvme5/new_clones/Handlebars/vim-cheat-sheet' &
git clone https://github.com/flatlogic/sing-app '/storage/nvme5/new_clones/Handlebars/sing-app' &
git clone https://github.com/ActiveCampaign/mailmason '/storage/nvme5/new_clones/Handlebars/mailmason' &
git clone https://github.com/microsoft/vscode-codicons '/storage/nvme5/new_clones/Handlebars/vscode-codicons' &
git clone https://github.com/Differential/meteor-boilerplate '/storage/nvme5/new_clones/Handlebars/meteor-boilerplate' &
git clone https://github.com/bestony/EasyWordPressBook '/storage/nvme5/new_clones/Handlebars/EasyWordPressBook' &
git clone https://github.com/ghinda/css-toggle-switch '/storage/nvme5/new_clones/Handlebars/css-toggle-switch' &
git clone https://github.com/rust-lang-cn/nomicon-zh-Hans '/storage/nvme5/new_clones/Handlebars/nomicon-zh-Hans' &
git clone https://github.com/kathyqian/crisp '/storage/nvme5/new_clones/Handlebars/crisp' &
git clone https://github.com/hathora/builder '/storage/nvme5/new_clones/Handlebars/builder' &
git clone https://github.com/rithvikvibhu/GHLocalApi '/storage/nvme5/new_clones/Handlebars/GHLocalApi' &
git clone https://github.com/weijiew/everystep '/storage/nvme5/new_clones/Handlebars/everystep' &
git clone https://github.com/gnu4cn/ccna60d '/storage/nvme5/new_clones/Handlebars/ccna60d' &
git clone https://github.com/DannyDainton/newman-reporter-htmlextra '/storage/nvme5/new_clones/Handlebars/newman-reporter-htmlextra' &
git clone https://github.com/bloomberg/foml '/storage/nvme5/new_clones/Handlebars/foml' &
git clone https://github.com/huggingface/hub-docs '/storage/nvme5/new_clones/Handlebars/hub-docs' &
git clone https://github.com/iamakulov/googlefonts-font-display-helper '/storage/nvme5/new_clones/Handlebars/googlefonts-font-display-helper' &
git clone https://github.com/brettchalupa/projectbook '/storage/nvme5/new_clones/Handlebars/projectbook' &
git clone https://github.com/DashboardPack/architectui-html-theme-free '/storage/nvme5/new_clones/Handlebars/architectui-html-theme-free' &
git clone https://github.com/daaain/Handlebars '/storage/nvme5/new_clones/Handlebars/Handlebars' &
git clone https://github.com/huangyuzhang/Fizzy-Theme '/storage/nvme5/new_clones/Handlebars/Fizzy-Theme' &
git clone https://github.com/fe-cool/news '/storage/nvme5/new_clones/Handlebars/news' &
git clone https://github.com/elastic/integrations '/storage/nvme5/new_clones/Handlebars/integrations' &
git clone https://github.com/fazt/nodejs-notes-app '/storage/nvme5/new_clones/Handlebars/nodejs-notes-app' &
git clone https://github.com/TryGhost/London '/storage/nvme5/new_clones/Handlebars/London' &
git clone https://github.com/Esri/cedar '/storage/nvme5/new_clones/Handlebars/cedar' &
git clone https://github.com/haim-io/cypress-image-diff '/storage/nvme5/new_clones/Handlebars/cypress-image-diff' &
git clone https://github.com/straker/livingcss '/storage/nvme5/new_clones/Handlebars/livingcss' &
git clone https://github.com/juice-shop/pwning-juice-shop '/storage/nvme5/new_clones/Handlebars/pwning-juice-shop' &
git clone https://github.com/fazt/nodejs-mysql-links '/storage/nvme5/new_clones/Handlebars/nodejs-mysql-links' &
git clone https://github.com/Kamona-WD/starter-dashboard-layout '/storage/nvme5/new_clones/Handlebars/starter-dashboard-layout' &
git clone https://github.com/xiaoyang-sde/knowledge-base '/storage/nvme5/new_clones/Handlebars/knowledge-base' &
git clone https://github.com/srcery-colors/srcery-terminal '/storage/nvme5/new_clones/Handlebars/srcery-terminal' &
git clone https://github.com/CrunchyData/postgres-operator-examples '/storage/nvme5/new_clones/Handlebars/postgres-operator-examples' &
git clone https://github.com/vincentmorneau/material-apex '/storage/nvme5/new_clones/Handlebars/material-apex' &
git clone https://github.com/cr0mll/cyberclopaedia '/storage/nvme5/new_clones/Handlebars/cyberclopaedia' &
git clone https://github.com/nikomatsakis/rustacean-principles '/storage/nvme5/new_clones/Handlebars/rustacean-principles' &
git clone https://github.com/ericwbailey/accessible-html-content-patterns '/storage/nvme5/new_clones/Handlebars/accessible-html-content-patterns' &
git clone https://github.com/fbbergamo/gerador-pix '/storage/nvme5/new_clones/Handlebars/gerador-pix' &
git clone https://github.com/moegi-design/ghost-theme-Moegi '/storage/nvme5/new_clones/Handlebars/ghost-theme-Moegi' &
git clone https://github.com/iqonicdesignofficial/hope-ui-design-system '/storage/nvme5/new_clones/Handlebars/hope-ui-design-system' &
git clone https://github.com/bpmn-io/bpmn.io '/storage/nvme5/new_clones/Handlebars/bpmn.io' &
git clone https://github.com/catppuccin/mdBook '/storage/nvme5/new_clones/Handlebars/mdBook' &
git clone https://github.com/miguelsolorio/vscode-fluent-icons '/storage/nvme5/new_clones/Handlebars/vscode-fluent-icons' &
git clone https://github.com/flatlogic/light-blue-dashboard '/storage/nvme5/new_clones/Handlebars/light-blue-dashboard' &
git clone https://github.com/nodemailer/wildduck-webmail '/storage/nvme5/new_clones/Handlebars/wildduck-webmail' &
git clone https://github.com/phoinixi/jsonresume-theme-stackoverflow '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-stackoverflow' &
git clone https://github.com/sunface/SRE-course '/storage/nvme5/new_clones/Handlebars/SRE-course' &
git clone https://github.com/sourcemeta/awesome-jsonschema '/storage/nvme5/new_clones/Handlebars/awesome-jsonschema' &
git clone https://github.com/GavickPro/Portfolio-Free-Ghost-Theme '/storage/nvme5/new_clones/Handlebars/Portfolio-Free-Ghost-Theme' &
git clone https://github.com/alexey-goloburdin/typed-python-book '/storage/nvme5/new_clones/Handlebars/typed-python-book' &
git clone https://github.com/shakrmedia/petal '/storage/nvme5/new_clones/Handlebars/petal' &
git clone https://github.com/guilhermecapitao/nlw3-discovery-happy '/storage/nvme5/new_clones/Handlebars/nlw3-discovery-happy' &
git clone https://github.com/AdoptOpenJDK/openjdk-website '/storage/nvme5/new_clones/Handlebars/openjdk-website' &
git clone https://github.com/zepochs/nestjs-mailer '/storage/nvme5/new_clones/Handlebars/nestjs-mailer' &
git clone https://github.com/ghinda/gridlayout '/storage/nvme5/new_clones/Handlebars/gridlayout' &
git clone https://github.com/FaztWeb/express-mongodb-crud '/storage/nvme5/new_clones/Handlebars/express-mongodb-crud' &
git clone https://github.com/haxball/haxball-issues '/storage/nvme5/new_clones/Handlebars/haxball-issues' &
git clone https://github.com/TryGhost/Alto '/storage/nvme5/new_clones/Handlebars/Alto' &
git clone https://github.com/kelyvin/jsonresume-theme-caffeine '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-caffeine' &
git clone https://github.com/mike-works/modern-seo '/storage/nvme5/new_clones/Handlebars/modern-seo' &
git clone https://github.com/jeffjewiss/ember-cli-postcss '/storage/nvme5/new_clones/Handlebars/ember-cli-postcss' &
git clone https://github.com/wuyanxin/chatapp-demo '/storage/nvme5/new_clones/Handlebars/chatapp-demo' &
git clone https://github.com/zendesk/copenhagen_theme '/storage/nvme5/new_clones/Handlebars/copenhagen_theme' &
git clone https://github.com/RobbieTheWagner/ember-math-helpers '/storage/nvme5/new_clones/Handlebars/ember-math-helpers' &
git clone https://github.com/chuxiuhong/chuxiuhong-rust-patterns-zh '/storage/nvme5/new_clones/Handlebars/chuxiuhong-rust-patterns-zh' &
git clone https://github.com/PracticalBooks/Practical-Nest '/storage/nvme5/new_clones/Handlebars/Practical-Nest' &
git clone https://github.com/geneasy/nav '/storage/nvme5/new_clones/Handlebars/nav' &
git clone https://github.com/JorelAli/mdBook-pagetoc '/storage/nvme5/new_clones/Handlebars/mdBook-pagetoc' &
git clone https://github.com/snollygolly/koa-starter '/storage/nvme5/new_clones/Handlebars/koa-starter' &
git clone https://github.com/TryGhost/Edge '/storage/nvme5/new_clones/Handlebars/Edge' &
git clone https://github.com/CoreLine76/OTP-BYPASS-and-SMS-BOT-V-3 '/storage/nvme5/new_clones/Handlebars/OTP-BYPASS-and-SMS-BOT-V-3' &
git clone https://github.com/TelegramBots/book '/storage/nvme5/new_clones/Handlebars/book' &
git clone https://github.com/curiositry/undefined-ghost-theme '/storage/nvme5/new_clones/Handlebars/undefined-ghost-theme' &
git clone https://github.com/TryGhost/Ease '/storage/nvme5/new_clones/Handlebars/Ease' &
git clone https://github.com/Esri/esri-leaflet-doc '/storage/nvme5/new_clones/Handlebars/esri-leaflet-doc' &
git clone https://github.com/TryGhost/Themes '/storage/nvme5/new_clones/Handlebars/Themes' &
git clone https://github.com/SLMT/google-cpp-style-guide-zh-tw '/storage/nvme5/new_clones/Handlebars/google-cpp-style-guide-zh-tw' &
git clone https://github.com/MaedahBatool/pudl '/storage/nvme5/new_clones/Handlebars/pudl' &
git clone https://github.com/alexk111/One-Time-Address '/storage/nvme5/new_clones/Handlebars/One-Time-Address' &
git clone https://github.com/raucao/webmarks '/storage/nvme5/new_clones/Handlebars/webmarks' &
git clone https://github.com/Git-it-App/git-it-electron '/storage/nvme5/new_clones/Handlebars/git-it-electron' &
git clone https://github.com/TryGhost/Wave '/storage/nvme5/new_clones/Handlebars/Wave' &
git clone https://github.com/GavickPro/Perfetta-Free-Ghost-Theme '/storage/nvme5/new_clones/Handlebars/Perfetta-Free-Ghost-Theme' &
git clone https://github.com/hashirpm/github-resume '/storage/nvme5/new_clones/Handlebars/github-resume' &
git clone https://github.com/Defcon27/Autorizz-Car-Dealership-System-using-NodeJS-Express-MongoDB '/storage/nvme5/new_clones/Handlebars/Autorizz-Car-Dealership-System-using-NodeJS-Express-MongoDB' &
git clone https://github.com/MarcosEllys/awesome-newman-html-template '/storage/nvme5/new_clones/Handlebars/awesome-newman-html-template' &
git clone https://github.com/felipecastrosales/Happy '/storage/nvme5/new_clones/Handlebars/Happy' &
git clone https://github.com/filamentgroup/gulpicon '/storage/nvme5/new_clones/Handlebars/gulpicon' &
git clone https://github.com/Defcon27/Real-Estate-Management-System-using-NodeJS-Express-MongoDB '/storage/nvme5/new_clones/Handlebars/Real-Estate-Management-System-using-NodeJS-Express-MongoDB' &
git clone https://github.com/rust-lang-ru/rust-by-example '/storage/nvme5/new_clones/Handlebars/rust-by-example' &
git clone https://github.com/digitalnsw/nsw-design-system '/storage/nvme5/new_clones/Handlebars/nsw-design-system' &
git clone https://github.com/notiz-dev/nestjs-mailer '/storage/nvme5/new_clones/Handlebars/nestjs-mailer' &
git clone https://github.com/FaztWeb/nodejs-firebase-example '/storage/nvme5/new_clones/Handlebars/nodejs-firebase-example' &
git clone https://github.com/marxjmoura/admin4b '/storage/nvme5/new_clones/Handlebars/admin4b' &
git clone https://github.com/TypeStrong/typedoc-default-themes '/storage/nvme5/new_clones/Handlebars/typedoc-default-themes' &
git clone https://github.com/TryGhost/Ruby '/storage/nvme5/new_clones/Handlebars/Ruby' &
git clone https://github.com/jimbobbennett/FauxGhost '/storage/nvme5/new_clones/Handlebars/FauxGhost' &
git clone https://github.com/fermyon/developer '/storage/nvme5/new_clones/Handlebars/developer' &
git clone https://github.com/roapi/docs '/storage/nvme5/new_clones/Handlebars/docs' &
git clone https://github.com/eventOneHQ/npm-audit-html '/storage/nvme5/new_clones/Handlebars/npm-audit-html' &
git clone https://github.com/TryGhost/Journal '/storage/nvme5/new_clones/Handlebars/Journal' &
git clone https://github.com/GetPublii/theme-Blank '/storage/nvme5/new_clones/Handlebars/theme-Blank' &
git clone https://github.com/TryGhost/Headline '/storage/nvme5/new_clones/Handlebars/Headline' &
git clone https://github.com/browsermt/students '/storage/nvme5/new_clones/Handlebars/students' &
git clone https://github.com/lacke/Orre-Theme-for-Ghost '/storage/nvme5/new_clones/Handlebars/Orre-Theme-for-Ghost' &
git clone https://github.com/brightthemes/biron-ghost-theme '/storage/nvme5/new_clones/Handlebars/biron-ghost-theme' &
git clone https://github.com/jonroig/finger.farm '/storage/nvme5/new_clones/Handlebars/finger.farm' &
git clone https://github.com/kennethkalmer/ember-cli-nouislider '/storage/nvme5/new_clones/Handlebars/ember-cli-nouislider' &
git clone https://github.com/futurestudio/futureflix-starter-kit '/storage/nvme5/new_clones/Handlebars/futureflix-starter-kit' &
git clone https://github.com/zone-eu/zmta-webadmin '/storage/nvme5/new_clones/Handlebars/zmta-webadmin' &
git clone https://github.com/kevinlacotaco/yuidoc-bootstrap-theme '/storage/nvme5/new_clones/Handlebars/yuidoc-bootstrap-theme' &
git clone https://github.com/redhat-scholars/openshift-starter-guides '/storage/nvme5/new_clones/Handlebars/openshift-starter-guides' &
git clone https://github.com/bestony/self-quantification '/storage/nvme5/new_clones/Handlebars/self-quantification' &
git clone https://github.com/DannyDainton/basic-newman-slack-bot '/storage/nvme5/new_clones/Handlebars/basic-newman-slack-bot' &
git clone https://github.com/Inoryum-Ltd/aesto '/storage/nvme5/new_clones/Handlebars/aesto' &
git clone https://github.com/youngjuning/vscode-api-cn.js.org '/storage/nvme5/new_clones/Handlebars/vscode-api-cn.js.org' &
git clone https://github.com/awesome-kusion/kusion-cookbook '/storage/nvme5/new_clones/Handlebars/kusion-cookbook' &
git clone https://github.com/RaddyTheBrand/Nodejs-UserManagement-Express-Hbs-MySQL '/storage/nvme5/new_clones/Handlebars/Nodejs-UserManagement-Express-Hbs-MySQL' &
git clone https://github.com/hodfords-solutions/nestjs-mocker '/storage/nvme5/new_clones/Handlebars/nestjs-mocker' &
git clone https://github.com/Cloudhuset/Zendesk-Guide-Theme-Boilerplate '/storage/nvme5/new_clones/Handlebars/Zendesk-Guide-Theme-Boilerplate' &
git clone https://github.com/DenysVuika/angular-book '/storage/nvme5/new_clones/Handlebars/angular-book' &
git clone https://github.com/vtex/vtex-emails '/storage/nvme5/new_clones/Handlebars/vtex-emails' &
git clone https://github.com/thibaudcolas/jsonresume-theme-eloquent '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-eloquent' &
git clone https://github.com/TryGhost/Solo '/storage/nvme5/new_clones/Handlebars/Solo' &
git clone https://github.com/jkasun/stack-abuse-express-authentication '/storage/nvme5/new_clones/Handlebars/stack-abuse-express-authentication' &
git clone https://github.com/freeCodeCamp/news-theme '/storage/nvme5/new_clones/Handlebars/news-theme' &
git clone https://github.com/akeneo/pim-api-docs '/storage/nvme5/new_clones/Handlebars/pim-api-docs' &
git clone https://github.com/pinceladasdaweb/nodejs-boilerplate '/storage/nvme5/new_clones/Handlebars/nodejs-boilerplate' &
git clone https://github.com/immersive-web/immersive-web-weekly '/storage/nvme5/new_clones/Handlebars/immersive-web-weekly' &
git clone https://github.com/ivyhungtw/expense-tracker '/storage/nvme5/new_clones/Handlebars/expense-tracker' &
git clone https://github.com/metafizzy/metafizzy.co '/storage/nvme5/new_clones/Handlebars/metafizzy.co' &
git clone https://github.com/shradha-khapra/Online-Library-System '/storage/nvme5/new_clones/Handlebars/Online-Library-System' &
git clone https://github.com/4ch1m/huElectron '/storage/nvme5/new_clones/Handlebars/huElectron' &
git clone https://github.com/0-vortex/cf-workers-url-shortener '/storage/nvme5/new_clones/Handlebars/cf-workers-url-shortener' &
git clone https://github.com/metafizzy/flickity-docs '/storage/nvme5/new_clones/Handlebars/flickity-docs' &
git clone https://github.com/jMonkeyEngine/wiki '/storage/nvme5/new_clones/Handlebars/wiki' &
git clone https://github.com/flipperdevices/Casper-flipper-blog-theme '/storage/nvme5/new_clones/Handlebars/Casper-flipper-blog-theme' &
git clone https://github.com/omnip620/material '/storage/nvme5/new_clones/Handlebars/material' &
git clone https://github.com/CaptainFreak/Web-CTF-Challenges '/storage/nvme5/new_clones/Handlebars/Web-CTF-Challenges' &
git clone https://github.com/jrjparks/unofficial-unifi-guide '/storage/nvme5/new_clones/Handlebars/unofficial-unifi-guide' &
git clone https://github.com/geneasy/links '/storage/nvme5/new_clones/Handlebars/links' &
git clone https://github.com/GoogleChromeLabs/shared-storage-demo '/storage/nvme5/new_clones/Handlebars/shared-storage-demo' &
git clone https://github.com/evoko/zendesk-theme '/storage/nvme5/new_clones/Handlebars/zendesk-theme' &
git clone https://github.com/flatlogic/one-bootstrap-template '/storage/nvme5/new_clones/Handlebars/one-bootstrap-template' &
git clone https://github.com/coding-blocks/boss '/storage/nvme5/new_clones/Handlebars/boss' &
git clone https://github.com/lukencode/GhostSolo '/storage/nvme5/new_clones/Handlebars/GhostSolo' &
git clone https://github.com/Wybxc/git-remake-guide '/storage/nvme5/new_clones/Handlebars/git-remake-guide' &
git clone https://github.com/RoboticsBrno/RB0005-UniversalStepDown '/storage/nvme5/new_clones/Handlebars/RB0005-UniversalStepDown' &
git clone https://github.com/semeano/DayAndNight '/storage/nvme5/new_clones/Handlebars/DayAndNight' &
git clone https://github.com/CrisFeit/vtex-email-framework '/storage/nvme5/new_clones/Handlebars/vtex-email-framework' &
git clone https://github.com/Rapha-Borges/containers-docs '/storage/nvme5/new_clones/Handlebars/containers-docs' &
git clone https://github.com/ianrose/typesettings-site '/storage/nvme5/new_clones/Handlebars/typesettings-site' &
git clone https://github.com/satisfactorymodding/Documentation '/storage/nvme5/new_clones/Handlebars/Documentation' &
git clone https://github.com/stefanbc/Asgar '/storage/nvme5/new_clones/Handlebars/Asgar' &
git clone https://github.com/DavidJKTofan/CyberSec-resources '/storage/nvme5/new_clones/Handlebars/CyberSec-resources' &
git clone https://github.com/jerrod-lankford/hassgalaxy '/storage/nvme5/new_clones/Handlebars/hassgalaxy' &
git clone https://github.com/Bahrul-Rozak/Belajar-Node-JS '/storage/nvme5/new_clones/Handlebars/Belajar-Node-JS' &
git clone https://github.com/pcaffa/Happy '/storage/nvme5/new_clones/Handlebars/Happy' &
git clone https://github.com/JustGoodThemes/Scriptor-Ghost-Theme '/storage/nvme5/new_clones/Handlebars/Scriptor-Ghost-Theme' &
git clone https://github.com/SameerBadriddinov/express-application-boom-shop '/storage/nvme5/new_clones/Handlebars/express-application-boom-shop' &
git clone https://github.com/diogosouza/node-grpc-crud '/storage/nvme5/new_clones/Handlebars/node-grpc-crud' &
git clone https://github.com/austincunningham/keycloak-express '/storage/nvme5/new_clones/Handlebars/keycloak-express' &
git clone https://github.com/saemhco/nestjs-html-pdf '/storage/nvme5/new_clones/Handlebars/nestjs-html-pdf' &
git clone https://github.com/loopDelicious/docker-extension '/storage/nvme5/new_clones/Handlebars/docker-extension' &
git clone https://github.com/funkill/mdbook-i18n '/storage/nvme5/new_clones/Handlebars/mdbook-i18n' &
git clone https://github.com/OneBusAway/docker '/storage/nvme5/new_clones/Handlebars/docker' &
git clone https://github.com/Love-and-Tolerance/guide-site-dev '/storage/nvme5/new_clones/Handlebars/guide-site-dev' &
git clone https://github.com/karlvr/openapi-generator-plus-generators '/storage/nvme5/new_clones/Handlebars/openapi-generator-plus-generators' &
git clone https://github.com/hieuwu/learning-website '/storage/nvme5/new_clones/Handlebars/learning-website' &
git clone https://github.com/Ayolland/borksy '/storage/nvme5/new_clones/Handlebars/borksy' &
git clone https://github.com/italia/design-comuni-pagine-statiche '/storage/nvme5/new_clones/Handlebars/design-comuni-pagine-statiche' &
git clone https://github.com/jsonresume/jsonresume-theme-class '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-class' &
git clone https://github.com/desandro/masonry-docs '/storage/nvme5/new_clones/Handlebars/masonry-docs' &
git clone https://github.com/bestony/remoteok '/storage/nvme5/new_clones/Handlebars/remoteok' &
git clone https://github.com/aurerua/goals-tracker '/storage/nvme5/new_clones/Handlebars/goals-tracker' &
git clone https://github.com/NTHU-CP/NTHU-CPP '/storage/nvme5/new_clones/Handlebars/NTHU-CPP' &
git clone https://github.com/SmartBear/awesome '/storage/nvme5/new_clones/Handlebars/awesome' &
git clone https://github.com/metafizzy/zdog-docs '/storage/nvme5/new_clones/Handlebars/zdog-docs' &
git clone https://github.com/Rosettea/Bon '/storage/nvme5/new_clones/Handlebars/Bon' &
git clone https://github.com/salsalvm/gadgetquebackend '/storage/nvme5/new_clones/Handlebars/gadgetquebackend' &
git clone https://github.com/pingidentity/pf-authn-js-widget '/storage/nvme5/new_clones/Handlebars/pf-authn-js-widget' &
git clone https://github.com/CaterpillarStudyGroup/mathematics_basic_for_ML '/storage/nvme5/new_clones/Handlebars/mathematics_basic_for_ML' &
git clone https://github.com/widaT/learning-go '/storage/nvme5/new_clones/Handlebars/learning-go' &
git clone https://github.com/davvvvvvvy/streaming-website '/storage/nvme5/new_clones/Handlebars/streaming-website' &
git clone https://github.com/KingsleyUbah/Nodejs-form '/storage/nvme5/new_clones/Handlebars/Nodejs-form' &
git clone https://github.com/meowomancer/spooky-slate '/storage/nvme5/new_clones/Handlebars/spooky-slate' &
git clone https://github.com/djalmaoliveira/djf-danfe '/storage/nvme5/new_clones/Handlebars/djf-danfe' &
git clone https://github.com/mythsman/mno '/storage/nvme5/new_clones/Handlebars/mno' &
git clone https://github.com/perfectsense/training '/storage/nvme5/new_clones/Handlebars/training' &
git clone https://github.com/atomicdata-dev/atomic-data-docs '/storage/nvme5/new_clones/Handlebars/atomic-data-docs' &
git clone https://github.com/iqonicdesignofficial/hope-ui-html-admin-dashboard '/storage/nvme5/new_clones/Handlebars/hope-ui-html-admin-dashboard' &
git clone https://github.com/developer239/create-opinionated-app '/storage/nvme5/new_clones/Handlebars/create-opinionated-app' &
git clone https://github.com/julienbourdeau/signal-theme '/storage/nvme5/new_clones/Handlebars/signal-theme' &
git clone https://github.com/engineer-man/mydogchase '/storage/nvme5/new_clones/Handlebars/mydogchase' &
git clone https://github.com/viswajithka97/menskart_backend '/storage/nvme5/new_clones/Handlebars/menskart_backend' &
git clone https://github.com/FreeMusicNinja/freemusic.ninja '/storage/nvme5/new_clones/Handlebars/freemusic.ninja' &
git clone https://github.com/louisvilletech/louisvilletech.org '/storage/nvme5/new_clones/Handlebars/louisvilletech.org' &
git clone https://github.com/FiliSantillan/filisantillan.com '/storage/nvme5/new_clones/Handlebars/filisantillan.com' &
git clone https://github.com/fermyon/bartholomew-site-template '/storage/nvme5/new_clones/Handlebars/bartholomew-site-template' &
git clone https://github.com/shakiliitju/Student-Management-System-Using-Nodejs '/storage/nvme5/new_clones/Handlebars/Student-Management-System-Using-Nodejs' &
git clone https://github.com/biosan/jsonresume-theme-macchiato '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-macchiato' &
git clone https://github.com/ZUGFeRD/ZUGFeRD.github.io '/storage/nvme5/new_clones/Handlebars/ZUGFeRDhub.io' &
git clone https://github.com/divshot/quick-deck '/storage/nvme5/new_clones/Handlebars/quick-deck' &
git clone https://github.com/nguyenphucminh/node_basic '/storage/nvme5/new_clones/Handlebars/node_basic' &
git clone https://github.com/mathieudutour/jsonresume-theme-github '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-github' &
git clone https://github.com/clupprich/starter-snowpack-tailwind '/storage/nvme5/new_clones/Handlebars/starter-snowpack-tailwind' &
git clone https://github.com/dipo0x/Ranode '/storage/nvme5/new_clones/Handlebars/Ranode' &
git clone https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet '/storage/nvme5/new_clones/Handlebars/foundryvtt-compactBeyond5eSheet' &
git clone https://github.com/IliaIdakiev/softuni-node-express '/storage/nvme5/new_clones/Handlebars/softuni-node-express' &
git clone https://github.com/docusign/sample-app-loanco-nodejs '/storage/nvme5/new_clones/Handlebars/sample-app-loanco-nodejs' &
git clone https://github.com/holochain-open-dev/templates '/storage/nvme5/new_clones/Handlebars/templates' &
git clone https://github.com/johno/ember-cli-loading '/storage/nvme5/new_clones/Handlebars/ember-cli-loading' &
git clone https://github.com/anasmullappally/userManagement '/storage/nvme5/new_clones/Handlebars/userManagement' &
git clone https://github.com/trevorsaint/rural-payments-styleguide '/storage/nvme5/new_clones/Handlebars/rural-payments-styleguide' &
git clone https://github.com/sammibadriddinov/Full-Stack-Project '/storage/nvme5/new_clones/Handlebars/Full-Stack-Project' &
git clone https://github.com/lifeofsoumya/StockAlert '/storage/nvme5/new_clones/Handlebars/StockAlert' &
git clone https://github.com/simevo/fattura-elettronica-json '/storage/nvme5/new_clones/Handlebars/fattura-elettronica-json' &
git clone https://github.com/metafizzy/isotope-docs '/storage/nvme5/new_clones/Handlebars/isotope-docs' &
git clone https://github.com/zeta-chain/zeta-examples '/storage/nvme5/new_clones/Handlebars/zeta-examples' &
git clone https://github.com/ARUN-M-S/Photo-Galerry '/storage/nvme5/new_clones/Handlebars/Photo-Galerry' &
git clone https://github.com/DekodeInteraktiv/localwp-projectbase-addon '/storage/nvme5/new_clones/Handlebars/localwp-projectbase-addon' &
git clone https://github.com/thapatechnical/webproject '/storage/nvme5/new_clones/Handlebars/webproject' &
git clone https://github.com/ThaiHoang-newbie/NodeJS '/storage/nvme5/new_clones/Handlebars/NodeJS' &
git clone https://github.com/Zazama/TrueStyle '/storage/nvme5/new_clones/Handlebars/TrueStyle' &
git clone https://github.com/DrOgres/tftloop '/storage/nvme5/new_clones/Handlebars/tftloop' &
git clone https://github.com/TryGhost/Bulletin '/storage/nvme5/new_clones/Handlebars/Bulletin' &
git clone https://github.com/superlin/cross-demos '/storage/nvme5/new_clones/Handlebars/cross-demos' &
git clone https://github.com/polarityio/shodan '/storage/nvme5/new_clones/Handlebars/shodan' &
git clone https://github.com/mhshajib/node_authentication '/storage/nvme5/new_clones/Handlebars/node_authentication' &
git clone https://github.com/chirpstack/chirpstack-docs '/storage/nvme5/new_clones/Handlebars/chirpstack-docs' &
git clone https://github.com/ehamiter/ipython-book '/storage/nvme5/new_clones/Handlebars/ipython-book' &
git clone https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template '/storage/nvme5/new_clones/Handlebars/carbon-for-ibm-dotcom-web-components-template' &
git clone https://github.com/KaplunMaxym/node_js_app_temp_ToDo '/storage/nvme5/new_clones/Handlebars/node_js_app_temp_ToDo' &
git clone https://github.com/cabrerafrancisco/OrganizerIT '/storage/nvme5/new_clones/Handlebars/OrganizerIT' &
git clone https://github.com/topaxi/ember-img-lazy '/storage/nvme5/new_clones/Handlebars/ember-img-lazy' &
git clone https://github.com/adoptium/obsolete---adoptium.net '/storage/nvme5/new_clones/Handlebars/obsolete---adoptium.net' &
git clone https://github.com/mskian/santhosh-veer-blog '/storage/nvme5/new_clones/Handlebars/santhosh-veer-blog' &
git clone https://github.com/Jandysang/webpack-mpa '/storage/nvme5/new_clones/Handlebars/webpack-mpa' &
git clone https://github.com/rushabhkela/EZ-Shopping '/storage/nvme5/new_clones/Handlebars/EZ-Shopping' &
git clone https://github.com/chaosarium/PhotoArchive '/storage/nvme5/new_clones/Handlebars/PhotoArchive' &
git clone https://github.com/CyrexEnterprise/ghostsheet '/storage/nvme5/new_clones/Handlebars/ghostsheet' &
git clone https://github.com/magalhini/goodreads-currently '/storage/nvme5/new_clones/Handlebars/goodreads-currently' &
git clone https://github.com/dendrofen/vitejs-tailwind-handlebars '/storage/nvme5/new_clones/Handlebars/vitejs-tailwind-handlebars' &
git clone https://github.com/pythonbrasil/pybr2020-site '/storage/nvme5/new_clones/Handlebars/pybr2020-site' &
git clone https://github.com/proteusthemes/wp-theme-docs '/storage/nvme5/new_clones/Handlebars/wp-theme-docs' &
git clone https://github.com/amiryusupov/Restaurant '/storage/nvme5/new_clones/Handlebars/Restaurant' &
git clone https://github.com/oktadev/okta-node-express-15-minute-auth-example '/storage/nvme5/new_clones/Handlebars/okta-node-express-15-minute-auth-example' &
git clone https://github.com/segunadebayo/oss-monorepo-starter '/storage/nvme5/new_clones/Handlebars/oss-monorepo-starter' &
git clone https://github.com/prowebdev119/fmwsoftware '/storage/nvme5/new_clones/Handlebars/fmwsoftware' &
git clone https://github.com/ArmandPhilippot/coldark '/storage/nvme5/new_clones/Handlebars/coldark' &
git clone https://github.com/Lumenita/abfalter '/storage/nvme5/new_clones/Handlebars/abfalter' &
git clone https://github.com/netspective/graphql-codegen-csharp '/storage/nvme5/new_clones/Handlebars/graphql-codegen-csharp' &
git clone https://github.com/ElfFriend-DnD/foundryvtt-5eOGLCharacterSheet '/storage/nvme5/new_clones/Handlebars/foundryvtt-5eOGLCharacterSheet' &
git clone https://github.com/learnable-content/nodejs-mysql '/storage/nvme5/new_clones/Handlebars/nodejs-mysql' &
git clone https://github.com/dbofmmbt/rust-handbook '/storage/nvme5/new_clones/Handlebars/rust-handbook' &
git clone https://github.com/elf-pavlik/webprofiled '/storage/nvme5/new_clones/Handlebars/webprofiled' &
git clone https://github.com/wintermeyer/elixir-phoenix-ash '/storage/nvme5/new_clones/Handlebars/elixir-phoenix-ash' &
git clone https://github.com/meSingh/UsingDeno.com '/storage/nvme5/new_clones/Handlebars/UsingDeno.com' &
git clone https://github.com/mr-mig/originate-frontend-lib '/storage/nvme5/new_clones/Handlebars/originate-frontend-lib' &
git clone https://github.com/barberscore/barberscore-web '/storage/nvme5/new_clones/Handlebars/barberscore-web' &
git clone https://github.com/codrkai/node_express_handlebars '/storage/nvme5/new_clones/Handlebars/node_express_handlebars' &
git clone https://github.com/meltmedia/notconf '/storage/nvme5/new_clones/Handlebars/notconf' &
git clone https://github.com/121onto/sec-diff '/storage/nvme5/new_clones/Handlebars/sec-diff' &
git clone https://github.com/Ozodbek16/Severyanochka '/storage/nvme5/new_clones/Handlebars/Severyanochka' &
git clone https://github.com/nypublicradio/nypr-design-system '/storage/nvme5/new_clones/Handlebars/nypr-design-system' &
git clone https://github.com/hendisantika/crud-bootstrap-mysql-nodejs '/storage/nvme5/new_clones/Handlebars/crud-bootstrap-mysql-nodejs' &
git clone https://github.com/nathaneastwood/fablore '/storage/nvme5/new_clones/Handlebars/fablore' &
git clone https://github.com/pednucci/donaro '/storage/nvme5/new_clones/Handlebars/donaro' &
git clone https://github.com/calebanthony/spook '/storage/nvme5/new_clones/Handlebars/spook' &
git clone https://github.com/syamprakash94/shoppie '/storage/nvme5/new_clones/Handlebars/shoppie' &
git clone https://github.com/RoboticsBrno/RB0004-NeopixelBooster '/storage/nvme5/new_clones/Handlebars/RB0004-NeopixelBooster' &
git clone https://github.com/osmc/website '/storage/nvme5/new_clones/Handlebars/website' &
git clone https://github.com/srcery-colors/srcery.sh '/storage/nvme5/new_clones/Handlebars/srcery.sh' &
git clone https://github.com/kphilemon/knowyourzone '/storage/nvme5/new_clones/Handlebars/knowyourzone' &
git clone https://github.com/aeologictech/email-template-using-nodejs '/storage/nvme5/new_clones/Handlebars/email-template-using-nodejs' &
git clone https://github.com/db-ui/base '/storage/nvme5/new_clones/Handlebars/base' &
git clone https://github.com/flatlogic/light-blue-html5 '/storage/nvme5/new_clones/Handlebars/light-blue-html5' &
git clone https://github.com/TomDoesTech/t3-generate '/storage/nvme5/new_clones/Handlebars/t3-generate' &
git clone https://github.com/redhat-scholars/helm-tutorial '/storage/nvme5/new_clones/Handlebars/helm-tutorial' &
git clone https://github.com/cathysarisky/Ruby-sales '/storage/nvme5/new_clones/Handlebars/Ruby-sales' &
git clone https://github.com/standrewsdigital/digital-pattern-library '/storage/nvme5/new_clones/Handlebars/digital-pattern-library' &
git clone https://github.com/aws-samples/mapper-for-fhir '/storage/nvme5/new_clones/Handlebars/mapper-for-fhir' &
git clone https://github.com/darksoil-studio/mutual-credit '/storage/nvme5/new_clones/Handlebars/mutual-credit' &
git clone https://github.com/prowebdev119/20201557kR-fwm_deploy_ready '/storage/nvme5/new_clones/Handlebars/20201557kR-fwm_deploy_ready' &
git clone https://github.com/hazelcast/hazelcast-docs-ui '/storage/nvme5/new_clones/Handlebars/hazelcast-docs-ui' &
git clone https://github.com/tmpim/shitty.dl '/storage/nvme5/new_clones/Handlebars/shitty.dl' &
git clone https://github.com/jhartzell42/rust-c-book '/storage/nvme5/new_clones/Handlebars/rust-c-book' &
git clone https://github.com/PaulaMarcella/Gig-Connect '/storage/nvme5/new_clones/Handlebars/Gig-Connect' &
git clone https://github.com/EmaSuriano/jsonresume-theme-standard-resume '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-standard-resume' &
git clone https://github.com/Ajaxsoap/meteor-sample-csv-importer '/storage/nvme5/new_clones/Handlebars/meteor-sample-csv-importer' &
git clone https://github.com/karlitos/jsonresume-theme-mocha-responsive '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-mocha-responsive' &
git clone https://github.com/JulienTD/nestjs-kratos '/storage/nvme5/new_clones/Handlebars/nestjs-kratos' &
git clone https://github.com/Jobin-S/CLASS-ROOM-MANAGEMENT-SYSTEM '/storage/nvme5/new_clones/Handlebars/CLASS-ROOM-MANAGEMENT-SYSTEM' &
git clone https://github.com/ftlabs/single-frame-video '/storage/nvme5/new_clones/Handlebars/single-frame-video' &
git clone https://github.com/mhdyaseen8841/Techio-Ecommerce-Website '/storage/nvme5/new_clones/Handlebars/Techio-Ecommerce-Website' &
git clone https://github.com/nomics-crypto/nomics-api-docs '/storage/nvme5/new_clones/Handlebars/nomics-api-docs' &
git clone https://github.com/jsonresume/jsonresume-theme-business-card '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-business-card' &
git clone https://github.com/adarshu2001/node.js-ecommerce-project '/storage/nvme5/new_clones/Handlebars/node.js-ecommerce-project' &
git clone https://github.com/HaeckDesign/triangle '/storage/nvme5/new_clones/Handlebars/triangle' &
git clone https://github.com/jfoyarzo/SkateparkApp '/storage/nvme5/new_clones/Handlebars/SkateparkApp' &
git clone https://github.com/TryGhost/Digest '/storage/nvme5/new_clones/Handlebars/Digest' &
git clone https://github.com/mattmitchell6/sa-takehome-project-node '/storage/nvme5/new_clones/Handlebars/sa-takehome-project-node' &
git clone https://github.com/stormdotcom/mykart '/storage/nvme5/new_clones/Handlebars/mykart' &
git clone https://github.com/sonnguyenhong/tinker-bell-garden '/storage/nvme5/new_clones/Handlebars/tinker-bell-garden' &
git clone https://github.com/SchildiChat/website '/storage/nvme5/new_clones/Handlebars/website' &
git clone https://github.com/7PH/haxball-battle-royal '/storage/nvme5/new_clones/Handlebars/haxball-battle-royal' &
git clone https://github.com/hunghg255/nodejs '/storage/nvme5/new_clones/Handlebars/nodejs' &
git clone https://github.com/adavila0703/jsonresume-theme-slickoverflow '/storage/nvme5/new_clones/Handlebars/jsonresume-theme-slickoverflow' &
git clone https://github.com/vividus-framework/docs.vividus.dev '/storage/nvme5/new_clones/Handlebars/docs.vividus.dev' &
git clone https://github.com/SameerBadriddinov/E-Commerce-Rest-Api.-NodeJS '/storage/nvme5/new_clones/Handlebars/E-Commerce-Rest-Api.-NodeJS' &
git clone https://github.com/SeaQL/sea-orm-cookbook '/storage/nvme5/new_clones/Handlebars/sea-orm-cookbook' &
git clone https://github.com/postmanlabs/postman-zendesk-support-theme '/storage/nvme5/new_clones/Handlebars/postman-zendesk-support-theme' &
git clone https://github.com/tfstam/happy-discovery '/storage/nvme5/new_clones/Handlebars/happy-discovery' &
git clone https://github.com/waryjack/fiveparsecs '/storage/nvme5/new_clones/Handlebars/fiveparsecs' &
git clone https://github.com/matheuspython/semana-next-level-projeto '/storage/nvme5/new_clones/Handlebars/semana-next-level-projeto' &
git clone https://github.com/medram/AI_theme_template '/storage/nvme5/new_clones/Handlebars/AI_theme_template' &
git clone https://github.com/zdoom-docs/staging '/storage/nvme5/new_clones/Handlebars/staging' &
git clone https://github.com/ascott1/Pliny '/storage/nvme5/new_clones/Handlebars/Pliny' &
git clone https://github.com/evoactivity/ember-fast-marquee '/storage/nvme5/new_clones/Handlebars/ember-fast-marquee' &
git clone https://github.com/synyx/cosy '/storage/nvme5/new_clones/Handlebars/cosy' &
git clone https://github.com/berrabe/nodejs-whatsapp-automation '/storage/nvme5/new_clones/Handlebars/nodejs-whatsapp-automation' &
git clone https://github.com/WorldAfterCapital/worldaftercapital.github.io '/storage/nvme5/new_clones/Handlebars/worldaftercapitalhub.io' &
git clone https://github.com/SLMT/atp-3-21-8-zh-tw '/storage/nvme5/new_clones/Handlebars/atp-3-21-8-zh-tw' &
git clone https://github.com/Ozodbek16/my-links.github.io '/storage/nvme5/new_clones/Handlebars/my-linkshub.io' &
git clone https://github.com/PawanGulati/Weather-App '/storage/nvme5/new_clones/Handlebars/Weather-App' &
git clone https://github.com/stormdotcom/user-management '/storage/nvme5/new_clones/Handlebars/user-management' &
git clone https://github.com/flatlogic/sing-app-html5 '/storage/nvme5/new_clones/Handlebars/sing-app-html5' &
git clone https://github.com/intel-iot-devkit/doxygen2jsdoc '/storage/nvme5/new_clones/Handlebars/doxygen2jsdoc' &
git clone https://github.com/mateustozoni/danfe-simplificada '/storage/nvme5/new_clones/Handlebars/danfe-simplificada' &
git clone https://github.com/gnppro/react-cli-components '/storage/nvme5/new_clones/Handlebars/react-cli-components' &
git clone https://github.com/lencx/book '/storage/nvme5/new_clones/Handlebars/book' &
git clone https://github.com/NativeScript/nativescript-typedoc-theme '/storage/nvme5/new_clones/Handlebars/nativescript-typedoc-theme' &
git clone https://github.com/polarityio/mandiant-threat-intelligence '/storage/nvme5/new_clones/Handlebars/mandiant-threat-intelligence' &
git clone https://github.com/uvexz/ghost-theme-1ite '/storage/nvme5/new_clones/Handlebars/ghost-theme-1ite' &
git clone https://github.com/stefanbc/Ingia '/storage/nvme5/new_clones/Handlebars/Ingia' &
git clone https://github.com/handlebars-lang/allow-prototype-access '/storage/nvme5/new_clones/Handlebars/allow-prototype-access' &
git clone https://github.com/ALI-8089/My-first-E-coomerce-project '/storage/nvme5/new_clones/Handlebars/My-first-E-coomerce-project' &
git clone https://github.com/neomorons/Weather-Forcasting '/storage/nvme5/new_clones/Handlebars/Weather-Forcasting' &
git clone https://github.com/MicroBlocksCN/microblocks-site '/storage/nvme5/new_clones/Handlebars/microblocks-site' &
git clone https://github.com/The-Velvet-Room/web-overlay '/storage/nvme5/new_clones/Handlebars/web-overlay' &
git clone https://github.com/Ozodbek16/Fruits '/storage/nvme5/new_clones/Handlebars/Fruits' &
git clone https://github.com/Explosion-Scratch/notes '/storage/nvme5/new_clones/Handlebars/notes' &
git clone https://github.com/HipsterBrown/the-other-side-of-empathy '/storage/nvme5/new_clones/Handlebars/the-other-side-of-empathy' &
git clone https://github.com/vborjap/grupo2-encuestas '/storage/nvme5/new_clones/Handlebars/grupo2-encuestas' &
git clone https://github.com/AdvisorySG/ghost-advisory-theme '/storage/nvme5/new_clones/Handlebars/ghost-advisory-theme' &
git clone https://github.com/Gladsonms/User_Managment '/storage/nvme5/new_clones/Handlebars/User_Managment' &
git clone https://github.com/froheel/EcoChange '/storage/nvme5/new_clones/Handlebars/EcoChange' &
git clone https://github.com/rdai10/zendesk '/storage/nvme5/new_clones/Handlebars/zendesk' &
git clone https://github.com/cozy/cozy-ghost-theme '/storage/nvme5/new_clones/Handlebars/cozy-ghost-theme' &
git clone https://github.com/rushabhkela/XChange '/storage/nvme5/new_clones/Handlebars/XChange' &
git clone https://github.com/jsreport/jsreport-typescript-example '/storage/nvme5/new_clones/Handlebars/jsreport-typescript-example' &
git clone https://github.com/sauravhiremath/ctf '/storage/nvme5/new_clones/Handlebars/ctf' &
git clone https://github.com/DarrenPaulWright/dmd-readable '/storage/nvme5/new_clones/Handlebars/dmd-readable' &
git clone https://github.com/cunhasbia/nlw3-happy '/storage/nvme5/new_clones/Handlebars/nlw3-happy' &
git clone https://github.com/Lernwerkstatt/site '/storage/nvme5/new_clones/Handlebars/site' &
git clone https://github.com/Ozodbek16/simple-online-shop '/storage/nvme5/new_clones/Handlebars/simple-online-shop' &
git clone https://github.com/Ozodbek16/students '/storage/nvme5/new_clones/Handlebars/students' &
git clone https://github.com/jatinbharadwaj/blog-app '/storage/nvme5/new_clones/Handlebars/blog-app' &
git clone https://github.com/feelcoder-20/nodejsmysqlcrud '/storage/nvme5/new_clones/Handlebars/nodejsmysqlcrud' &
git clone https://github.com/GoUpNumber/gun.fun '/storage/nvme5/new_clones/Handlebars/gun.fun' &
git clone https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de '/storage/nvme5/new_clones/Handlebars/intellij-asciidoc-plugin.ahus1.de' &
git clone https://github.com/evilboss/verso-sample '/storage/nvme5/new_clones/Handlebars/verso-sample' &
git clone https://github.com/MONEI/monei-payments-demo '/storage/nvme5/new_clones/Handlebars/monei-payments-demo' &
git clone https://github.com/Hamza-Qureshi09/web-project01 '/storage/nvme5/new_clones/Handlebars/web-project01' &
git clone https://github.com/saostad/sql-ts-knex-generator '/storage/nvme5/new_clones/Handlebars/sql-ts-knex-generator' &
git clone https://github.com/Choirless/Application-Server '/storage/nvme5/new_clones/Handlebars/Application-Server' &
git clone https://github.com/element-hq/ems-docs '/storage/nvme5/new_clones/Handlebars/ems-docs' &
git clone https://github.com/chec/example-store-boilerplate '/storage/nvme5/new_clones/Handlebars/example-store-boilerplate' &
git clone https://github.com/mclemente/party-overview '/storage/nvme5/new_clones/Handlebars/party-overview' &
git clone https://github.com/128technology/128t-icons '/storage/nvme5/new_clones/Handlebars/128t-icons' &
git clone https://github.com/ashinack/fashion_hub '/storage/nvme5/new_clones/Handlebars/fashion_hub' &
git clone https://github.com/yusufisbilir/LoginRegister '/storage/nvme5/new_clones/Handlebars/LoginRegister' &
git clone https://github.com/akash-akya/ex_mustache '/storage/nvme5/new_clones/Handlebars/ex_mustache' &
