#!/bin/bash

git clone https://github.com/cia-foundation/TempleOS '/storage/nvme5/new_clones/HolyC/TempleOS' &
git clone https://github.com/Zeal-Operating-System/ZealOS '/storage/nvme5/new_clones/HolyC/ZealOS' &
git clone https://github.com/minexew/Shrine '/storage/nvme5/new_clones/HolyC/Shrine' &
git clone https://github.com/tinkeros/TinkerOS '/storage/nvme5/new_clones/HolyC/TinkerOS' &
git clone https://github.com/SkienaBook/Algorithm-Design-Manual-Programs-V3 '/storage/nvme5/new_clones/HolyC/Algorithm-Design-Manual-Programs-V3' &
git clone https://github.com/bagnalla/holyc_mal '/storage/nvme5/new_clones/HolyC/holyc_mal' &
git clone https://github.com/barrettotte/TempleOS-and-HolyC '/storage/nvme5/new_clones/HolyC/TempleOS-and-HolyC' &
git clone https://github.com/jq2/erythros '/storage/nvme5/new_clones/HolyC/erythros' &
git clone https://github.com/minexew/Lsh '/storage/nvme5/new_clones/HolyC/Lsh' &
git clone https://github.com/PasqualeLivecchi/ZenithOS '/storage/nvme5/new_clones/HolyC/ZenithOS' &
git clone https://github.com/Zeal-Operating-System/HolyGL '/storage/nvme5/new_clones/HolyC/HolyGL' &
git clone https://github.com/cia-foundation/base-os '/storage/nvme5/new_clones/HolyC/base-os' &
git clone https://github.com/Francesco149/TempleOSGit '/storage/nvme5/new_clones/HolyC/TempleOSGit' &
git clone https://github.com/bbielsa/TempleTiler '/storage/nvme5/new_clones/HolyC/TempleTiler' &
git clone https://github.com/Rion96/GKey '/storage/nvme5/new_clones/HolyC/GKey' &
git clone https://github.com/shawnanastasio/TempleShell '/storage/nvme5/new_clones/HolyC/TempleShell' &
git clone https://github.com/cia-foundation/TempleOS-Screenfetch '/storage/nvme5/new_clones/HolyC/TempleOS-Screenfetch' &
git clone https://github.com/mne-tools/mne-testing-data '/storage/nvme5/new_clones/HolyC/mne-testing-data' &
git clone https://github.com/Sleepwalking/libgvps '/storage/nvme5/new_clones/HolyC/libgvps' &
git clone https://github.com/tobeypeters/dotfiles '/storage/nvme5/new_clones/HolyC/dotfiles' &
git clone https://github.com/GuidoDipietro/TP-SO-2021 '/storage/nvme5/new_clones/HolyC/TP-SO-2021' &
git clone https://github.com/ProfJski/TempleOS '/storage/nvme5/new_clones/HolyC/TempleOS' &
git clone https://github.com/eversinc33/OffensiveHolyC '/storage/nvme5/new_clones/HolyC/OffensiveHolyC' &
git clone https://github.com/cabbruzzese/gameoftomes '/storage/nvme5/new_clones/HolyC/gameoftomes' &
git clone https://github.com/Zeal-Operating-System/CHIP8 '/storage/nvme5/new_clones/HolyC/CHIP8' &
git clone https://github.com/jmarshall23/Hexen2 '/storage/nvme5/new_clones/HolyC/Hexen2' &
git clone https://github.com/JeffIrwin/temple-viewer '/storage/nvme5/new_clones/HolyC/temple-viewer' &
git clone https://github.com/Gulkbag/BrainfuckTOS '/storage/nvme5/new_clones/HolyC/BrainfuckTOS' &
git clone https://github.com/genericx64/ZOS '/storage/nvme5/new_clones/HolyC/ZOS' &
git clone https://github.com/tinkeros/OT1975 '/storage/nvme5/new_clones/HolyC/OT1975' &
git clone https://github.com/Zeal-Operating-System/PCIDeviceList '/storage/nvme5/new_clones/HolyC/PCIDeviceList' &
git clone https://github.com/tinkeros/SpyHunt '/storage/nvme5/new_clones/HolyC/SpyHunt' &
git clone https://github.com/TempleProgramming/HolyMath '/storage/nvme5/new_clones/HolyC/HolyMath' &
