#!/bin/bash

git clone https://github.com/allison-casey/HyREPL '/storage/nvme5/new_clones/Hy/HyREPL' &
git clone https://github.com/brandonwillard/loghyc '/storage/nvme5/new_clones/Hy/loghyc' &
git clone https://github.com/hylang/hydiomatic '/storage/nvme5/new_clones/Hy/hydiomatic' &
git clone https://github.com/chr15m/blender-hylang-live-code '/storage/nvme5/new_clones/Hy/blender-hylang-live-code' &
git clone https://github.com/pyx/hymn '/storage/nvme5/new_clones/Hy/hymn' &
git clone https://github.com/h2non/siringa '/storage/nvme5/new_clones/Hy/siringa' &
git clone https://github.com/refi64/hyskell '/storage/nvme5/new_clones/Hy/hyskell' &
git clone https://github.com/hylang/hyrule '/storage/nvme5/new_clones/Hy/hyrule' &
git clone https://github.com/ekaschalk/jedhy '/storage/nvme5/new_clones/Hy/jedhy' &
git clone https://github.com/ntestoc3/norecon '/storage/nvme5/new_clones/Hy/norecon' &
git clone https://github.com/svetlyak40wt/python-processor '/storage/nvme5/new_clones/Hy/python-processor' &
git clone https://github.com/mark-watson/hy-lisp-python '/storage/nvme5/new_clones/Hy/hy-lisp-python' &
git clone https://github.com/refi64/hytest '/storage/nvme5/new_clones/Hy/hytest' &
git clone https://github.com/Rahix/spacestation '/storage/nvme5/new_clones/Hy/spacestation' &
git clone https://github.com/koji-kojiro/hylang-hycc '/storage/nvme5/new_clones/Hy/hylang-hycc' &
git clone https://github.com/hylang/hygdrop '/storage/nvme5/new_clones/Hy/hygdrop' &
git clone https://github.com/sakuraiyuta/hyuga '/storage/nvme5/new_clones/Hy/hyuga' &
git clone https://github.com/rinx/hy-language-server '/storage/nvme5/new_clones/Hy/hy-language-server' &
git clone https://github.com/bryangarza/spectre '/storage/nvme5/new_clones/Hy/spectre' &
git clone https://github.com/Kodiologist/Rogue-TV '/storage/nvme5/new_clones/Hy/Rogue-TV' &
git clone https://github.com/pyx/hyer '/storage/nvme5/new_clones/Hy/hyer' &
git clone https://github.com/danneu/hyclops '/storage/nvme5/new_clones/Hy/hyclops' &
git clone https://github.com/chr15m/drillbit '/storage/nvme5/new_clones/Hy/drillbit' &
git clone https://github.com/riktor/hycl '/storage/nvme5/new_clones/Hy/hycl' &
git clone https://github.com/tuturto/archimedes '/storage/nvme5/new_clones/Hy/archimedes' &
git clone https://github.com/Kodiologist/Kodhy '/storage/nvme5/new_clones/Hy/Kodhy' &
git clone https://github.com/hackeryarn/hy-django '/storage/nvme5/new_clones/Hy/hy-django' &
git clone https://github.com/Hylands/macros '/storage/nvme5/new_clones/Hy/macros' &
git clone https://github.com/paultag/snitch '/storage/nvme5/new_clones/Hy/snitch' &
git clone https://github.com/taddeimania/hykoans '/storage/nvme5/new_clones/Hy/hykoans' &
git clone https://github.com/brandonwillard/monaxhyd '/storage/nvme5/new_clones/Hy/monaxhyd' &
git clone https://github.com/pkulev/tanki '/storage/nvme5/new_clones/Hy/tanki' &
git clone https://github.com/brackendev/scikit-learn-Hy '/storage/nvme5/new_clones/Hy/scikit-learn-Hy' &
git clone https://github.com/mlegls/hyjax '/storage/nvme5/new_clones/Hy/hyjax' &
git clone https://github.com/nerdbeard/livesort '/storage/nvme5/new_clones/Hy/livesort' &
git clone https://github.com/hylang/hyhomepage '/storage/nvme5/new_clones/Hy/hyhomepage' &
git clone https://github.com/guanyilun/hylab '/storage/nvme5/new_clones/Hy/hylab' &
git clone https://github.com/ben-denham/lemma '/storage/nvme5/new_clones/Hy/lemma' &
git clone https://github.com/AugustUnderground/gace '/storage/nvme5/new_clones/Hy/gace' &
git clone https://github.com/falloutphil/aoc_2019 '/storage/nvme5/new_clones/Hy/aoc_2019' &
