#!/bin/bash

git clone https://github.com/krschultz/android-proguard-snippets '/storage/nvme5/new_clones/IDL/android-proguard-snippets' &
git clone https://github.com/web-dom/web-dom '/storage/nvme5/new_clones/IDL/web-dom' &
git clone https://github.com/wlandsman/IDLAstro '/storage/nvme5/new_clones/IDL/IDLAstro' &
git clone https://github.com/msdx/android-proguard-cn '/storage/nvme5/new_clones/IDL/android-proguard-cn' &
git clone https://github.com/mrkindustries/bldc '/storage/nvme5/new_clones/IDL/bldc' &
git clone https://github.com/riverloopsec/apimote '/storage/nvme5/new_clones/IDL/apimote' &
git clone https://github.com/jmeyers314/linmix '/storage/nvme5/new_clones/IDL/linmix' &
git clone https://github.com/Galvant/gpibusb-pcb '/storage/nvme5/new_clones/IDL/gpibusb-pcb' &
git clone https://github.com/guanix/boards '/storage/nvme5/new_clones/IDL/boards' &
git clone https://github.com/idl-coyote/coyote '/storage/nvme5/new_clones/IDL/coyote' &
git clone https://github.com/dawhite/MCTK '/storage/nvme5/new_clones/IDL/MCTK' &
git clone https://github.com/AndroidKnife/proguard-config '/storage/nvme5/new_clones/IDL/proguard-config' &
git clone https://github.com/quangctkm9207/template-files '/storage/nvme5/new_clones/IDL/template-files' &
git clone https://github.com/jdeast/EXOFASTv2 '/storage/nvme5/new_clones/IDL/EXOFASTv2' &
git clone https://github.com/KennedyResearch/LandTrendr-2012 '/storage/nvme5/new_clones/IDL/LandTrendr-2012' &
git clone https://github.com/mgalloy/mglib '/storage/nvme5/new_clones/IDL/mglib' &
git clone https://github.com/pcbsd/pbi '/storage/nvme5/new_clones/IDL/pbi' &
git clone https://github.com/makestuff/lx9 '/storage/nvme5/new_clones/IDL/lx9' &
git clone https://github.com/simonmonk/eagle '/storage/nvme5/new_clones/IDL/eagle' &
git clone https://github.com/desertstsung/Snowy-Dove '/storage/nvme5/new_clones/IDL/Snowy-Dove' &
git clone https://github.com/phenoptix/AVRISP '/storage/nvme5/new_clones/IDL/AVRISP' &
git clone https://github.com/mortcanty/CRCENVI '/storage/nvme5/new_clones/IDL/CRCENVI' &
git clone https://github.com/Galvant/usb_wrapper-pcb '/storage/nvme5/new_clones/IDL/usb_wrapper-pcb' &
git clone https://github.com/amnh/HackTheSolarSystem '/storage/nvme5/new_clones/IDL/HackTheSolarSystem' &
git clone https://github.com/ossicode/OSSI-1Electronics '/storage/nvme5/new_clones/IDL/OSSI-1Electronics' &
git clone https://github.com/piranha32/FlyingBone '/storage/nvme5/new_clones/IDL/FlyingBone' &
git clone https://github.com/birgander2/RAT '/storage/nvme5/new_clones/IDL/RAT' &
git clone https://github.com/envi-idl/UAVToolkit '/storage/nvme5/new_clones/IDL/UAVToolkit' &
git clone https://github.com/dominicgs/BeagleDancer '/storage/nvme5/new_clones/IDL/BeagleDancer' &
git clone https://github.com/RasmusB/CANPi '/storage/nvme5/new_clones/IDL/CANPi' &
git clone https://github.com/regack/4x6 '/storage/nvme5/new_clones/IDL/4x6' &
git clone https://github.com/EoRImaging/FHD '/storage/nvme5/new_clones/IDL/FHD' &
git clone https://github.com/Miceuz/VFD '/storage/nvme5/new_clones/IDL/VFD' &
git clone https://github.com/myriadrf/Parallella-RF '/storage/nvme5/new_clones/IDL/Parallella-RF' &
git clone https://github.com/LGalaxiesPublicRelease/LGalaxies_PublicRepository '/storage/nvme5/new_clones/IDL/LGalaxies_PublicRepository' &
git clone https://github.com/ct6502/vscode-idl '/storage/nvme5/new_clones/IDL/vscode-idl' &
git clone https://github.com/FSund/qtcreator-project-structure '/storage/nvme5/new_clones/IDL/qtcreator-project-structure' &
git clone https://github.com/VenomVendor/DeduplicateSMS '/storage/nvme5/new_clones/IDL/DeduplicateSMS' &
git clone https://github.com/lynnbwilsoniii/wind_3dp_pros '/storage/nvme5/new_clones/IDL/wind_3dp_pros' &
git clone https://github.com/desertstsung/Project_JiaoTang '/storage/nvme5/new_clones/IDL/Project_JiaoTang' &
git clone https://github.com/fengqiaobeihang/Remote-Sensing-Image-Processing-IDL- '/storage/nvme5/new_clones/IDL/Remote-Sensing-Image-Processing-IDL-' &
git clone https://github.com/Keck-DataReductionPipelines/OsirisDRP '/storage/nvme5/new_clones/IDL/OsirisDRP' &
git clone https://github.com/Banno/banno-powerons '/storage/nvme5/new_clones/IDL/banno-powerons' &
git clone https://github.com/HaxeFoundation/html-externs '/storage/nvme5/new_clones/IDL/html-externs' &
git clone https://github.com/hyves42/kicad-proto-pcb '/storage/nvme5/new_clones/IDL/kicad-proto-pcb' &
git clone https://github.com/mgalloy/mgunit '/storage/nvme5/new_clones/IDL/mgunit' &
git clone https://github.com/autistic-symposium/interstellar-idl '/storage/nvme5/new_clones/IDL/interstellar-idl' &
git clone https://github.com/MegaMorph/galapagos '/storage/nvme5/new_clones/IDL/galapagos' &
git clone https://github.com/loxodes/mr_radar '/storage/nvme5/new_clones/IDL/mr_radar' &
git clone https://github.com/PaulJWright/ColourBlind '/storage/nvme5/new_clones/IDL/ColourBlind' &
git clone https://github.com/i4Ds/STIX-GSW '/storage/nvme5/new_clones/IDL/STIX-GSW' &
git clone https://github.com/regack/depot '/storage/nvme5/new_clones/IDL/depot' &
git clone https://github.com/freetronics/EtherDue '/storage/nvme5/new_clones/IDL/EtherDue' &
git clone https://github.com/zehome/autoaudioswitcher '/storage/nvme5/new_clones/IDL/autoaudioswitcher' &
git clone https://github.com/jdbcode/LLR-LandTrendr '/storage/nvme5/new_clones/IDL/LLR-LandTrendr' &
git clone https://github.com/emusan/FPGA_HDMI-pcb '/storage/nvme5/new_clones/IDL/FPGA_HDMI-pcb' &
git clone https://github.com/dnidever/PHOTRED '/storage/nvme5/new_clones/IDL/PHOTRED' &
git clone https://github.com/JianhangMa/optimized-ESTARFM '/storage/nvme5/new_clones/IDL/optimized-ESTARFM' &
git clone https://github.com/makestuff/umdkv2-lx9 '/storage/nvme5/new_clones/IDL/umdkv2-lx9' &
git clone https://github.com/jdhenshaw/SCOUSE '/storage/nvme5/new_clones/IDL/SCOUSE' &
git clone https://github.com/awmann/M_-M_K- '/storage/nvme5/new_clones/IDL/M_-M_K-' &
git clone https://github.com/bruceyoung01/program '/storage/nvme5/new_clones/IDL/program' &
git clone https://github.com/davidgrier/features '/storage/nvme5/new_clones/IDL/features' &
git clone https://github.com/BasilioRuiz/SIR-code '/storage/nvme5/new_clones/IDL/SIR-code' &
git clone https://github.com/rheingoldheavy/Design-For-Assembly-In-KiCad '/storage/nvme5/new_clones/IDL/Design-For-Assembly-In-KiCad' &
git clone https://github.com/OpenElectronicsLab/ads1298-breakout '/storage/nvme5/new_clones/IDL/ads1298-breakout' &
git clone https://github.com/BitKnitting/RFM69BreakoutBoard '/storage/nvme5/new_clones/IDL/RFM69BreakoutBoard' &
git clone https://github.com/FozzTexx/SeaGeelog '/storage/nvme5/new_clones/IDL/SeaGeelog' &
git clone https://github.com/mdruett/COCOPLOT '/storage/nvme5/new_clones/IDL/COCOPLOT' &
git clone https://github.com/nasa/MISR-View '/storage/nvme5/new_clones/IDL/MISR-View' &
git clone https://github.com/ChrisBeaumont/beaumont-idl-library '/storage/nvme5/new_clones/IDL/beaumont-idl-library' &
git clone https://github.com/jradavenport/jradavenport_idl '/storage/nvme5/new_clones/IDL/jradavenport_idl' &
git clone https://github.com/hylandg/Minimum-Area-Circumscribing-K-Gon '/storage/nvme5/new_clones/IDL/Minimum-Area-Circumscribing-K-Gon' &
git clone https://github.com/iitbtushar/dynamic-fracture '/storage/nvme5/new_clones/IDL/dynamic-fracture' &
git clone https://github.com/mgalloy/cpu-vs-gpu '/storage/nvme5/new_clones/IDL/cpu-vs-gpu' &
git clone https://github.com/abansemer/soda2 '/storage/nvme5/new_clones/IDL/soda2' &
git clone https://github.com/maskedinterrupt/BareBoneCape '/storage/nvme5/new_clones/IDL/BareBoneCape' &
git clone https://github.com/low-sky/cprops '/storage/nvme5/new_clones/IDL/cprops' &
git clone https://github.com/rice-solar-physics/EBTEL '/storage/nvme5/new_clones/IDL/EBTEL' &
git clone https://github.com/Galvant/usb_isolator-pcb '/storage/nvme5/new_clones/IDL/usb_isolator-pcb' &
git clone https://github.com/rafaeleufrasio/lightning '/storage/nvme5/new_clones/IDL/lightning' &
git clone https://github.com/zonca/paperplots '/storage/nvme5/new_clones/IDL/paperplots' &
git clone https://github.com/envi-idl/FXExtras '/storage/nvme5/new_clones/IDL/FXExtras' &
git clone https://github.com/othree/webidl '/storage/nvme5/new_clones/IDL/webidl' &
git clone https://github.com/snj33v/ofqmake '/storage/nvme5/new_clones/IDL/ofqmake' &
git clone https://github.com/foxsi/foxsi-science '/storage/nvme5/new_clones/IDL/foxsi-science' &
git clone https://github.com/ITA-Solar/solo-spice-ql '/storage/nvme5/new_clones/IDL/solo-spice-ql' &
git clone https://github.com/BackupTheBerlios/radartools-svn '/storage/nvme5/new_clones/IDL/radartools-svn' &
git clone https://github.com/profxj/xidl '/storage/nvme5/new_clones/IDL/xidl' &
git clone https://github.com/spedas/bleeding_edge '/storage/nvme5/new_clones/IDL/bleeding_edge' &
git clone https://github.com/freetronics/PiLeven '/storage/nvme5/new_clones/IDL/PiLeven' &
git clone https://github.com/akleroy/galbase '/storage/nvme5/new_clones/IDL/galbase' &
git clone https://github.com/max19951001/ESTARFM_by_xiaolinzhu '/storage/nvme5/new_clones/IDL/ESTARFM_by_xiaolinzhu' &
git clone https://github.com/zkhorrami/MYOSOTIS '/storage/nvme5/new_clones/IDL/MYOSOTIS' &
git clone https://github.com/NuSTAR/nuskybgd '/storage/nvme5/new_clones/IDL/nuskybgd' &
git clone https://github.com/jfaherty17/ETZ '/storage/nvme5/new_clones/IDL/ETZ' &
git clone https://github.com/geodynamics/mag '/storage/nvme5/new_clones/IDL/mag' &
git clone https://github.com/afteriwoof/CORIMP '/storage/nvme5/new_clones/IDL/CORIMP' &
git clone https://github.com/lyhkop/IDLusingENVI '/storage/nvme5/new_clones/IDL/IDLusingENVI' &
git clone https://github.com/anthonyyoud/gpe '/storage/nvme5/new_clones/IDL/gpe' &
git clone https://github.com/jradavenport/plx_gif '/storage/nvme5/new_clones/IDL/plx_gif' &
git clone https://github.com/leonf88/envi-spectrum '/storage/nvme5/new_clones/IDL/envi-spectrum' &
git clone https://github.com/EarthObservation/RVT '/storage/nvme5/new_clones/IDL/RVT' &
git clone https://github.com/NCAR/ucomp-pipeline '/storage/nvme5/new_clones/IDL/ucomp-pipeline' &
git clone https://github.com/wangtotang/ProGuardRules '/storage/nvme5/new_clones/IDL/ProGuardRules' &
