#!/bin/bash

git clone https://github.com/ethereum/execution-apis '/storage/nvme5/new_clones/Io/execution-apis' &
git clone https://github.com/pki-io/pki-io '/storage/nvme5/new_clones/Io/pki-io' &
git clone https://github.com/cdcarter/backpacking '/storage/nvme5/new_clones/Io/backpacking' &
git clone https://github.com/ethereumproject/volunteer '/storage/nvme5/new_clones/Io/volunteer' &
git clone https://github.com/whymirror/yown '/storage/nvme5/new_clones/Io/yown' &
git clone https://github.com/coviciva/Drone-hijacking-using-Arduino-and-HackRF-One '/storage/nvme5/new_clones/Io/Drone-hijacking-using-Arduino-and-HackRF-One' &
git clone https://github.com/tyler/iota '/storage/nvme5/new_clones/Io/iota' &
git clone https://github.com/jeremytregunna/IoSpec '/storage/nvme5/new_clones/Io/IoSpec' &
git clone https://github.com/bekkopen/jasmineio '/storage/nvme5/new_clones/Io/jasmineio' &
git clone https://github.com/defunkt/ike '/storage/nvme5/new_clones/Io/ike' &
git clone https://github.com/IoLanguage/eerie '/storage/nvme5/new_clones/Io/eerie' &
git clone https://github.com/oleganza/io-snippets '/storage/nvme5/new_clones/Io/io-snippets' &
git clone https://github.com/vangberg/iodis '/storage/nvme5/new_clones/Io/iodis' &
git clone https://github.com/josip/eerie '/storage/nvme5/new_clones/Io/eerie' &
git clone https://github.com/quag/io-json '/storage/nvme5/new_clones/Io/io-json' &
git clone https://github.com/maniartech/InternetObject-vs-JSON-benchmark '/storage/nvme5/new_clones/Io/InternetObject-vs-JSON-benchmark' &
git clone https://github.com/gatesphere/demi-16 '/storage/nvme5/new_clones/Io/demi-16' &
git clone https://github.com/oleganza/iopackage '/storage/nvme5/new_clones/Io/iopackage' &
git clone https://github.com/quag/iospec2 '/storage/nvme5/new_clones/Io/iospec2' &
git clone https://github.com/fredreichbier/iorm '/storage/nvme5/new_clones/Io/iorm' &
git clone https://github.com/josip/generys '/storage/nvme5/new_clones/Io/generys' &
git clone https://github.com/baasio/baas.io-sdk-ios '/storage/nvme5/new_clones/Io/baas.io-sdk-ios' &
git clone https://github.com/pgregory/blackpool '/storage/nvme5/new_clones/Io/blackpool' &
git clone https://github.com/imownbey/jim '/storage/nvme5/new_clones/Io/jim' &
git clone https://github.com/jdp/io-scgi '/storage/nvme5/new_clones/Io/io-scgi' &
git clone https://github.com/jdp/boid '/storage/nvme5/new_clones/Io/boid' &
git clone https://github.com/fredreichbier/netz '/storage/nvme5/new_clones/Io/netz' &
git clone https://github.com/qxjit/icis '/storage/nvme5/new_clones/Io/icis' &
git clone https://github.com/lightclient/rpctests '/storage/nvme5/new_clones/Io/rpctests' &
git clone https://github.com/anthem/muun '/storage/nvme5/new_clones/Io/muun' &
git clone https://github.com/Squidly271/AppFeed '/storage/nvme5/new_clones/Io/AppFeed' &
git clone https://github.com/rbxbx/higher_order_Io '/storage/nvme5/new_clones/Io/higher_order_Io' &
git clone https://github.com/josip/kano '/storage/nvme5/new_clones/Io/kano' &
git clone https://github.com/superbobry/io-OptionParser '/storage/nvme5/new_clones/Io/io-OptionParser' &
git clone https://github.com/fredreichbier/io-stuff '/storage/nvme5/new_clones/Io/io-stuff' &
git clone https://github.com/kevinclark/chordal '/storage/nvme5/new_clones/Io/chordal' &
git clone https://github.com/quag/io-pack '/storage/nvme5/new_clones/Io/io-pack' &
git clone https://github.com/gatesphere/pila '/storage/nvme5/new_clones/Io/pila' &
git clone https://github.com/Philiphackerzx/phishinator '/storage/nvme5/new_clones/Io/phishinator' &
git clone https://github.com/benmills/willful '/storage/nvme5/new_clones/Io/willful' &
git clone https://github.com/ethereumclassic/volunteer '/storage/nvme5/new_clones/Io/volunteer' &
git clone https://github.com/mil/mustache.io '/storage/nvme5/new_clones/Io/mustache.io' &
git clone https://github.com/tafsiri/7languages '/storage/nvme5/new_clones/Io/7languages' &
git clone https://github.com/patrickdolloso/MCNP6-Criticality-Primer '/storage/nvme5/new_clones/Io/MCNP6-Criticality-Primer' &
git clone https://github.com/smosher/IoSetting '/storage/nvme5/new_clones/Io/IoSetting' &
