#!/bin/bash

git clone https://github.com/rems-project/sail '/storage/nvme5/new_clones/Isabelle/sail' &
git clone https://github.com/seL4/l4v '/storage/nvme5/new_clones/Isabelle/l4v' &
git clone https://github.com/pirapira/eth-isabelle '/storage/nvme5/new_clones/Isabelle/eth-isabelle' &
git clone https://github.com/elastic/elasticsearch-formal-models '/storage/nvme5/new_clones/Isabelle/elasticsearch-formal-models' &
git clone https://github.com/input-output-hk/marlowe '/storage/nvme5/new_clones/Isabelle/marlowe' &
git clone https://github.com/au-ts/cogent '/storage/nvme5/new_clones/Isabelle/cogent' &
git clone https://github.com/seL4/isabelle '/storage/nvme5/new_clones/Isabelle/isabelle' &
git clone https://github.com/diekmann/Iptables_Semantics '/storage/nvme5/new_clones/Isabelle/Iptables_Semantics' &
git clone https://github.com/TartanLlama/non-binary '/storage/nvme5/new_clones/Isabelle/non-binary' &
git clone https://github.com/rems-project/sail-arm '/storage/nvme5/new_clones/Isabelle/sail-arm' &
git clone https://github.com/data61/PSL '/storage/nvme5/new_clones/Isabelle/PSL' &
git clone https://github.com/isabelle-prover/mirror-isabelle '/storage/nvme5/new_clones/Isabelle/mirror-isabelle' &
git clone https://github.com/CTSRD-CHERI/sail-cheri-riscv '/storage/nvme5/new_clones/Isabelle/sail-cheri-riscv' &
git clone https://github.com/jix/sortnetopt '/storage/nvme5/new_clones/Isabelle/sortnetopt' &
git clone https://github.com/ethereum/yul-isabelle '/storage/nvme5/new_clones/Isabelle/yul-isabelle' &
git clone https://github.com/bzhan/auto2 '/storage/nvme5/new_clones/Isabelle/auto2' &
git clone https://github.com/isabelle-utp/utp-main '/storage/nvme5/new_clones/Isabelle/utp-main' &
git clone https://github.com/johnwickerson/HSV '/storage/nvme5/new_clones/Isabelle/HSV' &
git clone https://github.com/nipkow/fds_ss20 '/storage/nvme5/new_clones/Isabelle/fds_ss20' &
git clone https://github.com/m-fleury/isabelle-emacs '/storage/nvme5/new_clones/Isabelle/isabelle-emacs' &
git clone https://github.com/lammich/isabelle_llvm '/storage/nvme5/new_clones/Isabelle/isabelle_llvm' &
git clone https://github.com/kolya-vasiliev/concrete-semantics '/storage/nvme5/new_clones/Isabelle/concrete-semantics' &
git clone https://github.com/pandaman64/sabi '/storage/nvme5/new_clones/Isabelle/sabi' &
git clone https://github.com/WasmCert/WasmCert-Isabelle '/storage/nvme5/new_clones/Isabelle/WasmCert-Isabelle' &
git clone https://github.com/moajohansson/IsaHipster '/storage/nvme5/new_clones/Isabelle/IsaHipster' &
git clone https://github.com/ekpyron/AOT '/storage/nvme5/new_clones/Isabelle/AOT' &
git clone https://github.com/mmalvarez/Gazelle '/storage/nvme5/new_clones/Isabelle/Gazelle' &
git clone https://github.com/SKolodynski/IsarMathLib '/storage/nvme5/new_clones/Isabelle/IsarMathLib' &
git clone https://github.com/wimmers/munta '/storage/nvme5/new_clones/Isabelle/munta' &
git clone https://github.com/LVPGroup/fpp '/storage/nvme5/new_clones/Isabelle/fpp' &
git clone https://github.com/isabelle-prover/cookbook '/storage/nvme5/new_clones/Isabelle/cookbook' &
git clone https://github.com/logic-tools/nadea '/storage/nvme5/new_clones/Isabelle/nadea' &
git clone https://github.com/cbenzmueller/LogiKEy '/storage/nvme5/new_clones/Isabelle/LogiKEy' &
git clone https://github.com/lawrencecpaulson/lawrencecpaulson.github.io '/storage/nvme5/new_clones/Isabelle/lawrencecpaulsonhub.io' &
git clone https://github.com/trvedata/opsets '/storage/nvme5/new_clones/Isabelle/opsets' &
git clone https://github.com/BarrelfishOS/Isabelle-hardware-models '/storage/nvme5/new_clones/Isabelle/Isabelle-hardware-models' &
git clone https://github.com/EduPH/concrete-semantics-Sols '/storage/nvme5/new_clones/Isabelle/concrete-semantics-Sols' &
git clone https://github.com/avigad/arwm '/storage/nvme5/new_clones/Isabelle/arwm' &
git clone https://github.com/prathamesh-t/Tangle-Isabelle '/storage/nvme5/new_clones/Isabelle/Tangle-Isabelle' &
git clone https://github.com/uqcyber/veriopt-releases '/storage/nvme5/new_clones/Isabelle/veriopt-releases' &
git clone https://github.com/echronos/echronos-proofs '/storage/nvme5/new_clones/Isabelle/echronos-proofs' &
git clone https://github.com/jvanbruegge/isabelle-lambda-calculus '/storage/nvme5/new_clones/Isabelle/isabelle-lambda-calculus' &
git clone https://github.com/jabocken/SSM-Construction '/storage/nvme5/new_clones/Isabelle/SSM-Construction' &
git clone https://github.com/filipmaric/IMO '/storage/nvme5/new_clones/Isabelle/IMO' &
git clone https://github.com/rohitdureja/isabelle-practice '/storage/nvme5/new_clones/Isabelle/isabelle-practice' &
git clone https://github.com/NICTA/l4v '/storage/nvme5/new_clones/Isabelle/l4v' &
git clone https://github.com/leouk/VDM_Toolkit '/storage/nvme5/new_clones/Isabelle/VDM_Toolkit' &
git clone https://github.com/theoremprover-museum/OMEGA '/storage/nvme5/new_clones/Isabelle/OMEGA' &
git clone https://github.com/pirapira/cbc_casper '/storage/nvme5/new_clones/Isabelle/cbc_casper' &
git clone https://github.com/AlexeyAkhunov/isabelle '/storage/nvme5/new_clones/Isabelle/isabelle' &
git clone https://github.com/michaelsproul/slashing-proofs '/storage/nvme5/new_clones/Isabelle/slashing-proofs' &
git clone https://github.com/Kuniwak/isabelle-range '/storage/nvme5/new_clones/Isabelle/isabelle-range' &
git clone https://github.com/yoshinao-isobe/CSP-Prover '/storage/nvme5/new_clones/Isabelle/CSP-Prover' &
git clone https://github.com/AnthonyBordg/Isabelle_marries_Dirac '/storage/nvme5/new_clones/Isabelle/Isabelle_marries_Dirac' &
git clone https://github.com/xqyww123/phi-system '/storage/nvme5/new_clones/Isabelle/phi-system' &
git clone https://github.com/isabelle-utp/interaction-trees '/storage/nvme5/new_clones/Isabelle/interaction-trees' &
git clone https://github.com/mrsmkl/ethereum-lem '/storage/nvme5/new_clones/Isabelle/ethereum-lem' &
git clone https://github.com/ioannad/NBG_HOL '/storage/nvme5/new_clones/Isabelle/NBG_HOL' &
git clone https://github.com/DeVilhena-Paulo/GaloisCVC4 '/storage/nvme5/new_clones/Isabelle/GaloisCVC4' &
git clone https://github.com/thomas-genet/abstEVM '/storage/nvme5/new_clones/Isabelle/abstEVM' &
git clone https://github.com/input-output-hk/cardano-ledger-high-assurance '/storage/nvme5/new_clones/Isabelle/cardano-ledger-high-assurance' &
