#!/bin/bash

git clone https://github.com/openj/core '/storage/nvme5/new_clones/J/core' &
git clone https://github.com/jonghough/jlearn '/storage/nvme5/new_clones/J/jlearn' &
git clone https://github.com/wyc/snippets '/storage/nvme5/new_clones/J/snippets' &
git clone https://github.com/jsoftware/jandroid '/storage/nvme5/new_clones/J/jandroid' &
git clone https://github.com/jsoftware/base9 '/storage/nvme5/new_clones/J/base9' &
git clone https://github.com/dankilman/j-cheat-sheet '/storage/nvme5/new_clones/J/j-cheat-sheet' &
git clone https://github.com/mlochbaum/JtoLaTeX '/storage/nvme5/new_clones/J/JtoLaTeX' &
git clone https://github.com/tangentstorm/jprez '/storage/nvme5/new_clones/J/jprez' &
git clone https://github.com/tangentstorm/syndir '/storage/nvme5/new_clones/J/syndir' &
git clone https://github.com/vmchale/coronavirus '/storage/nvme5/new_clones/J/coronavirus' &
git clone https://github.com/jsoftware/data_jd '/storage/nvme5/new_clones/J/data_jd' &
git clone https://github.com/tangentstorm/j-kvm '/storage/nvme5/new_clones/J/j-kvm' &
git clone https://github.com/jsoftware/labs_labs '/storage/nvme5/new_clones/J/labs_labs' &
git clone https://github.com/VincentToups/jkmeans '/storage/nvme5/new_clones/J/jkmeans' &
git clone https://github.com/moon-chilled/j '/storage/nvme5/new_clones/J/j' &
git clone https://github.com/jsoftware/ide_jhs '/storage/nvme5/new_clones/J/ide_jhs' &
git clone https://github.com/interregna/JArrow '/storage/nvme5/new_clones/J/JArrow' &
git clone https://github.com/locklin/j-zeromq '/storage/nvme5/new_clones/J/j-zeromq' &
git clone https://github.com/tangentstorm/mandelbrowse '/storage/nvme5/new_clones/J/mandelbrowse' &
git clone https://github.com/bakerjd99/jod '/storage/nvme5/new_clones/J/jod' &
git clone https://github.com/jonghough/PermuJ '/storage/nvme5/new_clones/J/PermuJ' &
git clone https://github.com/DevonMcC/JUtilities '/storage/nvme5/new_clones/J/JUtilities' &
git clone https://github.com/mlochbaum/JSound '/storage/nvme5/new_clones/J/JSound' &
git clone https://github.com/vmchale/perceptual-hash '/storage/nvme5/new_clones/J/perceptual-hash' &
git clone https://github.com/Pascal-J/jpp '/storage/nvme5/new_clones/J/jpp' &
git clone https://github.com/jsoftware/stats_base '/storage/nvme5/new_clones/J/stats_base' &
git clone https://github.com/jsoftware/base8 '/storage/nvme5/new_clones/J/base8' &
git clone https://github.com/exercism/j '/storage/nvme5/new_clones/J/j' &
git clone https://github.com/jsoftware/math_calculus '/storage/nvme5/new_clones/J/math_calculus' &
git clone https://github.com/Rscho314/mk '/storage/nvme5/new_clones/J/mk' &
git clone https://github.com/locklin/j-nearest-neighbor '/storage/nvme5/new_clones/J/j-nearest-neighbor' &
git clone https://github.com/mlliarm/apl-in-bcn '/storage/nvme5/new_clones/J/apl-in-bcn' &
git clone https://github.com/ajcr/doomsday '/storage/nvme5/new_clones/J/doomsday' &
git clone https://github.com/tikkanz/jdataframe '/storage/nvme5/new_clones/J/jdataframe' &
git clone https://github.com/ndpar/j '/storage/nvme5/new_clones/J/j' &
git clone https://github.com/jdan/j-by-example '/storage/nvme5/new_clones/J/j-by-example' &
git clone https://github.com/ajnirp/j-scripts '/storage/nvme5/new_clones/J/j-scripts' &
