#!/bin/bash

git clone https://github.com/google/jsonnet '/storage/nvme5/new_clones/Jsonnet/jsonnet' &
git clone https://github.com/prometheus-operator/kube-prometheus '/storage/nvme5/new_clones/Jsonnet/kube-prometheus' &
git clone https://github.com/PipelineAI/pipeline '/storage/nvme5/new_clones/Jsonnet/pipeline' &
git clone https://github.com/kubernetes-monitoring/kubernetes-mixin '/storage/nvme5/new_clones/Jsonnet/kubernetes-mixin' &
git clone https://github.com/argoproj/argocd-example-apps '/storage/nvme5/new_clones/Jsonnet/argocd-example-apps' &
git clone https://github.com/kubeflow/examples '/storage/nvme5/new_clones/Jsonnet/examples' &
git clone https://github.com/grafana/grafonnet-lib '/storage/nvme5/new_clones/Jsonnet/grafonnet-lib' &
git clone https://github.com/vmware-archive/kube-prod-runtime '/storage/nvme5/new_clones/Jsonnet/kube-prod-runtime' &
git clone https://github.com/carlosedp/cluster-monitoring '/storage/nvme5/new_clones/Jsonnet/cluster-monitoring' &
git clone https://github.com/grafana/jsonnet-libs '/storage/nvme5/new_clones/Jsonnet/jsonnet-libs' &
git clone https://github.com/thanos-io/kube-thanos '/storage/nvme5/new_clones/Jsonnet/kube-thanos' &
git clone https://github.com/ksonnet/ksonnet-lib '/storage/nvme5/new_clones/Jsonnet/ksonnet-lib' &
git clone https://github.com/aws-samples/aws-microservices-deploy-options '/storage/nvme5/new_clones/Jsonnet/aws-microservices-deploy-options' &
git clone https://github.com/rux616/karabiner-windows-mode '/storage/nvme5/new_clones/Jsonnet/karabiner-windows-mode' &
git clone https://github.com/kubeflow/fairing '/storage/nvme5/new_clones/Jsonnet/fairing' &
git clone https://github.com/kubeflow/pytorch-operator '/storage/nvme5/new_clones/Jsonnet/pytorch-operator' &
git clone https://github.com/brancz/kubernetes-grafana '/storage/nvme5/new_clones/Jsonnet/kubernetes-grafana' &
git clone https://github.com/grafana/tns '/storage/nvme5/new_clones/Jsonnet/tns' &
git clone https://github.com/StonyBrookNLP/ircot '/storage/nvme5/new_clones/Jsonnet/ircot' &
git clone https://github.com/jsonnet-libs/k8s-libsonnet '/storage/nvme5/new_clones/Jsonnet/k8s-libsonnet' &
git clone https://github.com/jsonnet-libs/k8s '/storage/nvme5/new_clones/Jsonnet/k8s' &
git clone https://github.com/bitnami/kube-libsonnet '/storage/nvme5/new_clones/Jsonnet/kube-libsonnet' &
git clone https://github.com/kubeflow/community '/storage/nvme5/new_clones/Jsonnet/community' &
git clone https://github.com/DFKI-NLP/thermostat '/storage/nvme5/new_clones/Jsonnet/thermostat' &
git clone https://github.com/vmware-archive/kube-manifests '/storage/nvme5/new_clones/Jsonnet/kube-manifests' &
git clone https://github.com/openthings/kubernetes-tools '/storage/nvme5/new_clones/Jsonnet/kubernetes-tools' &
git clone https://github.com/metalmatze/slo-libsonnet '/storage/nvme5/new_clones/Jsonnet/slo-libsonnet' &
git clone https://github.com/buildbarn/bb-deployments '/storage/nvme5/new_clones/Jsonnet/bb-deployments' &
git clone https://github.com/google/earthengine-catalog '/storage/nvme5/new_clones/Jsonnet/earthengine-catalog' &
git clone https://github.com/masashi-y/depccg '/storage/nvme5/new_clones/Jsonnet/depccg' &
git clone https://github.com/kubeflow/kubebench '/storage/nvme5/new_clones/Jsonnet/kubebench' &
git clone https://github.com/thaum-xyz/ankhmorpork '/storage/nvme5/new_clones/Jsonnet/ankhmorpork' &
git clone https://github.com/grafana/cortex-jsonnet '/storage/nvme5/new_clones/Jsonnet/cortex-jsonnet' &
git clone https://github.com/adamwg/grafana-dashboards '/storage/nvme5/new_clones/Jsonnet/grafana-dashboards' &
git clone https://github.com/jsonnet-libs/k8s-alpha '/storage/nvme5/new_clones/Jsonnet/k8s-alpha' &
git clone https://github.com/GoogleCloudPlatform/ml-testing-accelerators '/storage/nvme5/new_clones/Jsonnet/ml-testing-accelerators' &
git clone https://github.com/netology-code/sysadm-homeworks '/storage/nvme5/new_clones/Jsonnet/sysadm-homeworks' &
git clone https://github.com/jupyterhub/grafana-dashboards '/storage/nvme5/new_clones/Jsonnet/grafana-dashboards' &
git clone https://github.com/adinhodovic/django-mixin '/storage/nvme5/new_clones/Jsonnet/django-mixin' &
git clone https://github.com/yanghongfei/Kubernetes '/storage/nvme5/new_clones/Jsonnet/Kubernetes' &
git clone https://github.com/anguslees/kustomize-libsonnet '/storage/nvme5/new_clones/Jsonnet/kustomize-libsonnet' &
git clone https://github.com/mkmik/udig '/storage/nvme5/new_clones/Jsonnet/udig' &
git clone https://github.com/EmbarkStudios/k8s-buildkite-plugin '/storage/nvme5/new_clones/Jsonnet/k8s-buildkite-plugin' &
git clone https://github.com/WarpCloud/walm '/storage/nvme5/new_clones/Jsonnet/walm' &
git clone https://github.com/anguslees/k8s-home '/storage/nvme5/new_clones/Jsonnet/k8s-home' &
git clone https://github.com/tarantool/grafana-dashboard '/storage/nvme5/new_clones/Jsonnet/grafana-dashboard' &
git clone https://github.com/MacroPower/homelab '/storage/nvme5/new_clones/Jsonnet/homelab' &
git clone https://github.com/GoogleCloudPlatform/guest-test-infra '/storage/nvme5/new_clones/Jsonnet/guest-test-infra' &
git clone https://github.com/povilasv/kubernetes-grafana-mixin '/storage/nvme5/new_clones/Jsonnet/kubernetes-grafana-mixin' &
git clone https://github.com/h2oai/h2o-kubeflow '/storage/nvme5/new_clones/Jsonnet/h2o-kubeflow' &
git clone https://github.com/openebs/monitoring '/storage/nvme5/new_clones/Jsonnet/monitoring' &
git clone https://github.com/calebdoxsey/kubernetes-config '/storage/nvme5/new_clones/Jsonnet/kubernetes-config' &
git clone https://github.com/Taipei-HUG/workshop '/storage/nvme5/new_clones/Jsonnet/workshop' &
git clone https://github.com/fiberplane/quickstart '/storage/nvme5/new_clones/Jsonnet/quickstart' &
git clone https://github.com/rawkode/influxdb-examples '/storage/nvme5/new_clones/Jsonnet/influxdb-examples' &
git clone https://github.com/rhobs/configuration '/storage/nvme5/new_clones/Jsonnet/configuration' &
git clone https://github.com/alphagov/govuk-content-schemas '/storage/nvme5/new_clones/Jsonnet/govuk-content-schemas' &
git clone https://github.com/adinhodovic/blackbox-exporter-mixin '/storage/nvme5/new_clones/Jsonnet/blackbox-exporter-mixin' &
git clone https://github.com/jsonnet-libs/xtd '/storage/nvme5/new_clones/Jsonnet/xtd' &
git clone https://github.com/spinnaker/sponnet '/storage/nvme5/new_clones/Jsonnet/sponnet' &
git clone https://github.com/dNationCloud/kubernetes-monitoring '/storage/nvme5/new_clones/Jsonnet/kubernetes-monitoring' &
git clone https://github.com/HO-CTO/sre-monitoring-as-code '/storage/nvme5/new_clones/Jsonnet/sre-monitoring-as-code' &
git clone https://github.com/povilasv/coredns-mixin '/storage/nvme5/new_clones/Jsonnet/coredns-mixin' &
git clone https://github.com/rakam-io/recipes '/storage/nvme5/new_clones/Jsonnet/recipes' &
git clone https://github.com/adinhodovic/ingress-nginx-mixin '/storage/nvme5/new_clones/Jsonnet/ingress-nginx-mixin' &
git clone https://github.com/adinhodovic/tanka-argocd-demo '/storage/nvme5/new_clones/Jsonnet/tanka-argocd-demo' &
git clone https://github.com/sbarzowski/jsonnet-modifiers '/storage/nvme5/new_clones/Jsonnet/jsonnet-modifiers' &
git clone https://github.com/grafana/writers-toolkit '/storage/nvme5/new_clones/Jsonnet/writers-toolkit' &
git clone https://github.com/tf-libsonnet/core '/storage/nvme5/new_clones/Jsonnet/core' &
git clone https://github.com/jsonnet-libs/testonnet '/storage/nvme5/new_clones/Jsonnet/testonnet' &
git clone https://github.com/giantswarm/dashboards '/storage/nvme5/new_clones/Jsonnet/dashboards' &
git clone https://github.com/crdsonnet/crdsonnet '/storage/nvme5/new_clones/Jsonnet/crdsonnet' &
git clone https://github.com/moleike/haskell-jsonnet '/storage/nvme5/new_clones/Jsonnet/haskell-jsonnet' &
git clone https://github.com/cloud-bulldozer/performance-dashboards '/storage/nvme5/new_clones/Jsonnet/performance-dashboards' &
git clone https://github.com/nelson-liu/inoculation-by-finetuning '/storage/nvme5/new_clones/Jsonnet/inoculation-by-finetuning' &
git clone https://github.com/nlamirault/monitoring-mixins '/storage/nvme5/new_clones/Jsonnet/monitoring-mixins' &
git clone https://github.com/jsonnet-libs/jsonnet-training-course '/storage/nvme5/new_clones/Jsonnet/jsonnet-training-course' &
git clone https://github.com/kubeflow/chainer-operator '/storage/nvme5/new_clones/Jsonnet/chainer-operator' &
git clone https://github.com/Taipei-HUG/Prometheus-workshop '/storage/nvme5/new_clones/Jsonnet/Prometheus-workshop' &
git clone https://github.com/povilasv/nodelocaldns-mixin '/storage/nvme5/new_clones/Jsonnet/nodelocaldns-mixin' &
git clone https://github.com/metalmatze/loki-kube-prometheus '/storage/nvme5/new_clones/Jsonnet/loki-kube-prometheus' &
git clone https://github.com/aquaproj/aqua-renovate-config '/storage/nvme5/new_clones/Jsonnet/aqua-renovate-config' &
git clone https://github.com/jessesuen/ksonnet-examples '/storage/nvme5/new_clones/Jsonnet/ksonnet-examples' &
git clone https://github.com/DFKI-NLP/RelEx '/storage/nvme5/new_clones/Jsonnet/RelEx' &
git clone https://github.com/satyanash/promql-jsonnet '/storage/nvme5/new_clones/Jsonnet/promql-jsonnet' &
git clone https://github.com/appleboy/ansible-drone '/storage/nvme5/new_clones/Jsonnet/ansible-drone' &
git clone https://github.com/theplant/plantbuild '/storage/nvme5/new_clones/Jsonnet/plantbuild' &
git clone https://github.com/jdbaldry/helm-jsonnet '/storage/nvme5/new_clones/Jsonnet/helm-jsonnet' &
git clone https://github.com/ramaro/kapitan-examples '/storage/nvme5/new_clones/Jsonnet/kapitan-examples' &
git clone https://github.com/ethersphere/grafana-dashboards '/storage/nvme5/new_clones/Jsonnet/grafana-dashboards' &
git clone https://github.com/vadv/pg_gatherer '/storage/nvme5/new_clones/Jsonnet/pg_gatherer' &
git clone https://github.com/MycroftAI/snapcraft-mycroft-core '/storage/nvme5/new_clones/Jsonnet/snapcraft-mycroft-core' &
git clone https://github.com/cloudnativedaysjp/dreamkast-infra '/storage/nvme5/new_clones/Jsonnet/dreamkast-infra' &
git clone https://github.com/sbarzowski/jsonnet-parser-combinators '/storage/nvme5/new_clones/Jsonnet/jsonnet-parser-combinators' &
git clone https://github.com/andrew-waters/linkerd2-mixin '/storage/nvme5/new_clones/Jsonnet/linkerd2-mixin' &
git clone https://github.com/fluxcd-community/flux-mixin '/storage/nvme5/new_clones/Jsonnet/flux-mixin' &
git clone https://github.com/uneeq-oss/spinnaker-mixin '/storage/nvme5/new_clones/Jsonnet/spinnaker-mixin' &
git clone https://github.com/jjo/talks '/storage/nvme5/new_clones/Jsonnet/talks' &
git clone https://github.com/allenai/better-promptability '/storage/nvme5/new_clones/Jsonnet/better-promptability' &
git clone https://github.com/m-lab/k8s-support '/storage/nvme5/new_clones/Jsonnet/k8s-support' &
git clone https://github.com/kube-jsonnet/k '/storage/nvme5/new_clones/Jsonnet/k' &
git clone https://github.com/JeppeKlitgaard/barista '/storage/nvme5/new_clones/Jsonnet/barista' &
git clone https://github.com/kubeflow/kfserving-lts '/storage/nvme5/new_clones/Jsonnet/kfserving-lts' &
git clone https://github.com/ncabatoff/grafana-dashboards '/storage/nvme5/new_clones/Jsonnet/grafana-dashboards' &
git clone https://github.com/lukas-vlcek/elasticsearch-mixin '/storage/nvme5/new_clones/Jsonnet/elasticsearch-mixin' &
git clone https://github.com/reachyu/kubeflow-0.7.0 '/storage/nvme5/new_clones/Jsonnet/kubeflow-0.7.0' &
git clone https://github.com/openfun/potsie '/storage/nvme5/new_clones/Jsonnet/potsie' &
git clone https://github.com/cznewt/nasa-swpc-exporter '/storage/nvme5/new_clones/Jsonnet/nasa-swpc-exporter' &
git clone https://github.com/drone-plugins/drone-cache '/storage/nvme5/new_clones/Jsonnet/drone-cache' &
git clone https://github.com/akamai-contrib/postman-jsonnet '/storage/nvme5/new_clones/Jsonnet/postman-jsonnet' &
git clone https://github.com/microsoft/nlu-incremental-symbol-learning '/storage/nvme5/new_clones/Jsonnet/nlu-incremental-symbol-learning' &
git clone https://github.com/jsonnet-libs/crossplane-libsonnet '/storage/nvme5/new_clones/Jsonnet/crossplane-libsonnet' &
git clone https://github.com/marcusolsson/vscode-theme-enough '/storage/nvme5/new_clones/Jsonnet/vscode-theme-enough' &
git clone https://github.com/jsonnet-libs/fluxcd-libsonnet '/storage/nvme5/new_clones/Jsonnet/fluxcd-libsonnet' &
git clone https://github.com/knative/infra '/storage/nvme5/new_clones/Jsonnet/infra' &
git clone https://github.com/jetstack/tekton-demo '/storage/nvme5/new_clones/Jsonnet/tekton-demo' &
git clone https://github.com/community-config/observe '/storage/nvme5/new_clones/Jsonnet/observe' &
git clone https://github.com/yvrhdn/tempo-local-dev '/storage/nvme5/new_clones/Jsonnet/tempo-local-dev' &
git clone https://github.com/agilestacks/components '/storage/nvme5/new_clones/Jsonnet/components' &
git clone https://github.com/cznewt/esphome-libsonnet '/storage/nvme5/new_clones/Jsonnet/esphome-libsonnet' &
git clone https://github.com/esteng/miso_uds '/storage/nvme5/new_clones/Jsonnet/miso_uds' &
git clone https://github.com/cloudflightio/cloudflight-libsonnet '/storage/nvme5/new_clones/Jsonnet/cloudflight-libsonnet' &
git clone https://github.com/influxdata/k8s-jsonnet-libs '/storage/nvme5/new_clones/Jsonnet/k8s-jsonnet-libs' &
git clone https://github.com/Unity-Technologies/jsonnet-libs '/storage/nvme5/new_clones/Jsonnet/jsonnet-libs' &
git clone https://github.com/Nick-0314/kubernetes '/storage/nvme5/new_clones/Jsonnet/kubernetes' &
git clone https://github.com/DFKI-NLP/emp-exp '/storage/nvme5/new_clones/Jsonnet/emp-exp' &
git clone https://github.com/onprem/thanos-exemplars-demo '/storage/nvme5/new_clones/Jsonnet/thanos-exemplars-demo' &
git clone https://github.com/agrahamlincoln/jsonnet-patterns '/storage/nvme5/new_clones/Jsonnet/jsonnet-patterns' &
git clone https://github.com/dwlmt/knowledgeable-stories '/storage/nvme5/new_clones/Jsonnet/knowledgeable-stories' &
git clone https://github.com/akshayjshah/dotfiles '/storage/nvme5/new_clones/Jsonnet/dotfiles' &
git clone https://github.com/zhuchance/prometheus-operatorAlert '/storage/nvme5/new_clones/Jsonnet/prometheus-operatorAlert' &
git clone https://github.com/stackql/stackql-demo '/storage/nvme5/new_clones/Jsonnet/stackql-demo' &
git clone https://github.com/brancz/loki-jsonnet '/storage/nvme5/new_clones/Jsonnet/loki-jsonnet' &
git clone https://github.com/arosh/machete '/storage/nvme5/new_clones/Jsonnet/machete' &
git clone https://github.com/stackql/stackql-gcp-foundations '/storage/nvme5/new_clones/Jsonnet/stackql-gcp-foundations' &
git clone https://github.com/adinhodovic/rabbitmq-mixin '/storage/nvme5/new_clones/Jsonnet/rabbitmq-mixin' &
git clone https://github.com/walnuts1018/infra '/storage/nvme5/new_clones/Jsonnet/infra' &
git clone https://github.com/agola-io/agola-example-go '/storage/nvme5/new_clones/Jsonnet/agola-example-go' &
git clone https://github.com/xunleii/vector_jsonnet '/storage/nvme5/new_clones/Jsonnet/vector_jsonnet' &
git clone https://github.com/malcolmholmes/tanka-grafanacon-2020 '/storage/nvme5/new_clones/Jsonnet/tanka-grafanacon-2020' &
git clone https://github.com/tmax-cloud/argocd-installer '/storage/nvme5/new_clones/Jsonnet/argocd-installer' &
git clone https://github.com/jlewi/kubeflow-dev '/storage/nvme5/new_clones/Jsonnet/kubeflow-dev' &
git clone https://github.com/letsbuilders/jsonnet-libs '/storage/nvme5/new_clones/Jsonnet/jsonnet-libs' &
git clone https://github.com/crdsonnet/drone-libsonnet '/storage/nvme5/new_clones/Jsonnet/drone-libsonnet' &
git clone https://github.com/rrreeeyyy/docker-prometheus-mixin '/storage/nvme5/new_clones/Jsonnet/docker-prometheus-mixin' &
git clone https://github.com/cakehappens/lonely-mountain '/storage/nvme5/new_clones/Jsonnet/lonely-mountain' &
git clone https://github.com/chongchuanbing/kubeflow-manifests '/storage/nvme5/new_clones/Jsonnet/kubeflow-manifests' &
git clone https://github.com/mjpitz/mjpitz '/storage/nvme5/new_clones/Jsonnet/mjpitz' &
