#!/bin/bash

git clone https://github.com/upptime/upptime '/storage/nvme5/new_clones/JSON/upptime' &
git clone https://github.com/mdn/browser-compat-data '/storage/nvme5/new_clones/JSON/browser-compat-data' &
git clone https://github.com/microsoft/Application-Insights-Workbooks '/storage/nvme5/new_clones/JSON/Application-Insights-Workbooks' &
git clone https://github.com/SUSTech-Application/SUSTechapplication '/storage/nvme5/new_clones/JSON/SUSTechapplication' &
git clone https://github.com/OpenLightingProject/open-fixture-library '/storage/nvme5/new_clones/JSON/open-fixture-library' &
git clone https://github.com/timurkanaz/Russia_geojson_OSM '/storage/nvme5/new_clones/JSON/Russia_geojson_OSM' &
git clone https://github.com/KSP-CKAN/CKAN-meta '/storage/nvme5/new_clones/JSON/CKAN-meta' &
git clone https://github.com/Blockception/Minecraft-bedrock-json-schemas '/storage/nvme5/new_clones/JSON/Minecraft-bedrock-json-schemas' &
git clone https://github.com/blackbirdtheme/vscode '/storage/nvme5/new_clones/JSON/vscode' &
git clone https://github.com/Kichura/MCWine '/storage/nvme5/new_clones/JSON/MCWine' &
git clone https://github.com/AnandChowdhary/okrs '/storage/nvme5/new_clones/JSON/okrs' &
git clone https://github.com/Kichura/Minecraft_ARM '/storage/nvme5/new_clones/JSON/Minecraft_ARM' &
git clone https://github.com/barrettotte/vscode-ibmi-languages '/storage/nvme5/new_clones/JSON/vscode-ibmi-languages' &
git clone https://github.com/radium-theme/vsc '/storage/nvme5/new_clones/JSON/vsc' &
git clone https://github.com/TeamPiped/piped-uptime '/storage/nvme5/new_clones/JSON/piped-uptime' &
git clone https://github.com/w3c/mdn-spec-links '/storage/nvme5/new_clones/JSON/mdn-spec-links' &
git clone https://github.com/FastGitORG/uptime '/storage/nvme5/new_clones/JSON/uptime' &
git clone https://github.com/fox-projects/vscode-assorted-languages '/storage/nvme5/new_clones/JSON/vscode-assorted-languages' &
git clone https://github.com/rainzee/RiotSkin4CN-Status '/storage/nvme5/new_clones/JSON/RiotSkin4CN-Status' &
git clone https://github.com/NonlinearFruit/Creeds.json '/storage/nvme5/new_clones/JSON/Creeds.json' &
git clone https://github.com/bellinitte/uxntal-vscode '/storage/nvme5/new_clones/JSON/uxntal-vscode' &
git clone https://github.com/NordeaOB/swaggers '/storage/nvme5/new_clones/JSON/swaggers' &
git clone https://github.com/sabertazimi/LaTeX-snippets '/storage/nvme5/new_clones/JSON/LaTeX-snippets' &
git clone https://github.com/unascribed/SymbolicControllerDB '/storage/nvme5/new_clones/JSON/SymbolicControllerDB' &
git clone https://github.com/Ferruslogic/PhotonJSON '/storage/nvme5/new_clones/JSON/PhotonJSON' &
git clone https://github.com/nxvvvv/uptime '/storage/nvme5/new_clones/JSON/uptime' &
git clone https://github.com/sadra1f/minimal-dark-vscode-theme '/storage/nvme5/new_clones/JSON/minimal-dark-vscode-theme' &
git clone https://github.com/ShivamJoker/Monitor '/storage/nvme5/new_clones/JSON/Monitor' &
git clone https://github.com/TheAlienDoctor/minecraft-updated-1.8-textures '/storage/nvme5/new_clones/JSON/minecraft-updated-1.8-textures' &
git clone https://github.com/HXL-CPLP/Auxilium-Humanitarium-API '/storage/nvme5/new_clones/JSON/Auxilium-Humanitarium-API' &
git clone https://github.com/gadmln/gabstatus '/storage/nvme5/new_clones/JSON/gabstatus' &
git clone https://github.com/AnandChowdhary/everything '/storage/nvme5/new_clones/JSON/everything' &
git clone https://github.com/HaJuegos/Permadeath-SMP-Originals '/storage/nvme5/new_clones/JSON/Permadeath-SMP-Originals' &
git clone https://github.com/okankocyigit/upptime '/storage/nvme5/new_clones/JSON/upptime' &
git clone https://github.com/SparkScratch-P/profile-visiting-cards '/storage/nvme5/new_clones/JSON/profile-visiting-cards' &
git clone https://github.com/HaJuegos/The-Last-15-Days '/storage/nvme5/new_clones/JSON/The-Last-15-Days' &
