#!/bin/bash

git clone https://github.com/pop-os/cosmic-epoch '/storage/nvme5/new_clones/Just/cosmic-epoch' &
git clone https://github.com/erebe/personal-server '/storage/nvme5/new_clones/Just/personal-server' &
git clone https://github.com/catppuccin/kitty '/storage/nvme5/new_clones/Just/kitty' &
git clone https://github.com/kissgyorgy/redbean-docker '/storage/nvme5/new_clones/Just/redbean-docker' &
git clone https://github.com/catppuccin/fish '/storage/nvme5/new_clones/Just/fish' &
git clone https://github.com/catppuccin/hyprland '/storage/nvme5/new_clones/Just/hyprland' &
git clone https://github.com/catppuccin/btop '/storage/nvme5/new_clones/Just/btop' &
git clone https://github.com/catppuccin/dark-reader '/storage/nvme5/new_clones/Just/dark-reader' &
git clone https://github.com/jefftriplett/django-startproject '/storage/nvme5/new_clones/Just/django-startproject' &
git clone https://github.com/catppuccin/i3 '/storage/nvme5/new_clones/Just/i3' &
git clone https://github.com/catppuccin/warp '/storage/nvme5/new_clones/Just/warp' &
git clone https://github.com/tomodachi94/awesome-computercraft '/storage/nvme5/new_clones/Just/awesome-computercraft' &
git clone https://github.com/catppuccin/helix '/storage/nvme5/new_clones/Just/helix' &
git clone https://github.com/IndianBoy42/tree-sitter-just '/storage/nvme5/new_clones/Just/tree-sitter-just' &
git clone https://github.com/catppuccin/konsole '/storage/nvme5/new_clones/Just/konsole' &
git clone https://github.com/catppuccin/k9s '/storage/nvme5/new_clones/Just/k9s' &
git clone https://github.com/catppuccin/zellij '/storage/nvme5/new_clones/Just/zellij' &
git clone https://github.com/catppuccin/obs '/storage/nvme5/new_clones/Just/obs' &
git clone https://github.com/catppuccin/fcitx5 '/storage/nvme5/new_clones/Just/fcitx5' &
git clone https://github.com/catppuccin/termux '/storage/nvme5/new_clones/Just/termux' &
git clone https://github.com/catppuccin/tty '/storage/nvme5/new_clones/Just/tty' &
git clone https://github.com/catppuccin/polybar '/storage/nvme5/new_clones/Just/polybar' &
git clone https://github.com/catppuccin/Kvantum '/storage/nvme5/new_clones/Just/Kvantum' &
git clone https://github.com/nschloe/action-cached-lfs-checkout '/storage/nvme5/new_clones/Just/action-cached-lfs-checkout' &
git clone https://github.com/catppuccin/xcode '/storage/nvme5/new_clones/Just/xcode' &
git clone https://github.com/catppuccin/florisboard '/storage/nvme5/new_clones/Just/florisboard' &
git clone https://github.com/catppuccin/qt5ct '/storage/nvme5/new_clones/Just/qt5ct' &
git clone https://github.com/catppuccin/gitui '/storage/nvme5/new_clones/Just/gitui' &
git clone https://github.com/skywardmc/additive '/storage/nvme5/new_clones/Just/additive' &
git clone https://github.com/martinpitt/ostree-pitti-workstation '/storage/nvme5/new_clones/Just/ostree-pitti-workstation' &
git clone https://github.com/catppuccin/spotify-player '/storage/nvme5/new_clones/Just/spotify-player' &
git clone https://github.com/dougmasten/awesome-coco '/storage/nvme5/new_clones/Just/awesome-coco' &
git clone https://github.com/catppuccin/mako '/storage/nvme5/new_clones/Just/mako' &
git clone https://github.com/skywardmc/adrenaline '/storage/nvme5/new_clones/Just/adrenaline' &
git clone https://github.com/catppuccin/spotify-tui '/storage/nvme5/new_clones/Just/spotify-tui' &
git clone https://github.com/miguno/golang-docker-build-tutorial '/storage/nvme5/new_clones/Just/golang-docker-build-tutorial' &
git clone https://github.com/catppuccin/xresources '/storage/nvme5/new_clones/Just/xresources' &
git clone https://github.com/catppuccin/aliucord '/storage/nvme5/new_clones/Just/aliucord' &
git clone https://github.com/catppuccin/plymouth '/storage/nvme5/new_clones/Just/plymouth' &
git clone https://github.com/catppuccin/element '/storage/nvme5/new_clones/Just/element' &
git clone https://github.com/jefftriplett/scripts-to-rule-them-all '/storage/nvme5/new_clones/Just/scripts-to-rule-them-all' &
git clone https://github.com/catppuccin/misskey '/storage/nvme5/new_clones/Just/misskey' &
git clone https://github.com/Holo5/nitro-docker '/storage/nvme5/new_clones/Just/nitro-docker' &
git clone https://github.com/catppuccin/xfce4-terminal '/storage/nvme5/new_clones/Just/xfce4-terminal' &
git clone https://github.com/catppuccin/bottom '/storage/nvme5/new_clones/Just/bottom' &
git clone https://github.com/catppuccin/tilix '/storage/nvme5/new_clones/Just/tilix' &
git clone https://github.com/catppuccin/plank '/storage/nvme5/new_clones/Just/plank' &
git clone https://github.com/catppuccin/openbox '/storage/nvme5/new_clones/Just/openbox' &
git clone https://github.com/catppuccin/mattermost '/storage/nvme5/new_clones/Just/mattermost' &
git clone https://github.com/mihaigalos/pass '/storage/nvme5/new_clones/Just/pass' &
git clone https://github.com/catppuccin/enmity '/storage/nvme5/new_clones/Just/enmity' &
git clone https://github.com/catppuccin/foliate '/storage/nvme5/new_clones/Just/foliate' &
git clone https://github.com/catppuccin/lxqt '/storage/nvme5/new_clones/Just/lxqt' &
git clone https://github.com/catppuccin/terminator '/storage/nvme5/new_clones/Just/terminator' &
git clone https://github.com/deverte/awesome-science '/storage/nvme5/new_clones/Just/awesome-science' &
git clone https://github.com/catppuccin/bitburner '/storage/nvme5/new_clones/Just/bitburner' &
git clone https://github.com/simonmichael/hledger_finance '/storage/nvme5/new_clones/Just/hledger_finance' &
git clone https://github.com/catppuccin/xed '/storage/nvme5/new_clones/Just/xed' &
git clone https://github.com/catppuccin/noir '/storage/nvme5/new_clones/Just/noir' &
git clone https://github.com/barklan/luabyexample '/storage/nvme5/new_clones/Just/luabyexample' &
git clone https://github.com/eshepelyuk/apicurio-registry-helm '/storage/nvme5/new_clones/Just/apicurio-registry-helm' &
git clone https://github.com/skywardmc/adrenaserver '/storage/nvme5/new_clones/Just/adrenaserver' &
git clone https://github.com/catppuccin/contour '/storage/nvme5/new_clones/Just/contour' &
git clone https://github.com/luander/k3s-cluster '/storage/nvme5/new_clones/Just/k3s-cluster' &
git clone https://github.com/chevdor/srtool-actions '/storage/nvme5/new_clones/Just/srtool-actions' &
git clone https://github.com/halostatue/fish-rust '/storage/nvme5/new_clones/Just/fish-rust' &
git clone https://github.com/catppuccin/spyder '/storage/nvme5/new_clones/Just/spyder' &
git clone https://github.com/linux-china/kotlin-platform-bom '/storage/nvme5/new_clones/Just/kotlin-platform-bom' &
git clone https://github.com/halostatue/fish-haskell '/storage/nvme5/new_clones/Just/fish-haskell' &
git clone https://github.com/catppuccin/qterminal '/storage/nvme5/new_clones/Just/qterminal' &
git clone https://github.com/halostatue/fish-go '/storage/nvme5/new_clones/Just/fish-go' &
git clone https://github.com/steven-terrana/jte-library-scaffold '/storage/nvme5/new_clones/Just/jte-library-scaffold' &
git clone https://github.com/catppuccin/pyradio '/storage/nvme5/new_clones/Just/pyradio' &
git clone https://github.com/catppuccin/lxterminal '/storage/nvme5/new_clones/Just/lxterminal' &
git clone https://github.com/tranzystorekk/ChimeraWSL '/storage/nvme5/new_clones/Just/ChimeraWSL' &
git clone https://github.com/halostatue/fish-elixir '/storage/nvme5/new_clones/Just/fish-elixir' &
git clone https://github.com/iacopy/cleanpython '/storage/nvme5/new_clones/Just/cleanpython' &
git clone https://github.com/maidsafe/sn_testnet_tool '/storage/nvme5/new_clones/Just/sn_testnet_tool' &
git clone https://github.com/nvim-computercraft/ide-config '/storage/nvme5/new_clones/Just/ide-config' &
