#!/bin/bash

git clone https://github.com/ruanqizhen/labview_book '/storage/nvme5/new_clones/LabVIEW/labview_book' &
git clone https://github.com/xiaoyuan1996/labview2018-tutorial '/storage/nvme5/new_clones/LabVIEW/labview2018-tutorial' &
git clone https://github.com/REVrobotics/SPARK-MAX-Examples '/storage/nvme5/new_clones/LabVIEW/SPARK-MAX-Examples' &
git clone https://github.com/Rompil/LabVIEW '/storage/nvme5/new_clones/LabVIEW/LabVIEW' &
git clone https://github.com/tomsoftware/VI-Explorer-VI '/storage/nvme5/new_clones/LabVIEW/VI-Explorer-VI' &
git clone https://github.com/JKISoftware/JKI-State-Machine-Objects '/storage/nvme5/new_clones/LabVIEW/JKI-State-Machine-Objects' &
git clone https://github.com/lhb5883/LabVIEW '/storage/nvme5/new_clones/LabVIEW/LabVIEW' &
git clone https://github.com/ni/grpc-labview '/storage/nvme5/new_clones/LabVIEW/grpc-labview' &
git clone https://github.com/unipsycho/Graph-Extensions-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Graph-Extensions-LabVIEW' &
git clone https://github.com/unipsycho/LabVIEWdotNetDataGrid '/storage/nvme5/new_clones/LabVIEW/LabVIEWdotNetDataGrid' &
git clone https://github.com/DAQIO/LVMQTT '/storage/nvme5/new_clones/LabVIEW/LVMQTT' &
git clone https://github.com/G-CLI/G-CLI '/storage/nvme5/new_clones/LabVIEW/G-CLI' &
git clone https://github.com/NISystemsEngineering/LabVIEW-Modbus-API '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Modbus-API' &
git clone https://github.com/vipm-io/caraya '/storage/nvme5/new_clones/LabVIEW/caraya' &
git clone https://github.com/opengds/OpenGDS '/storage/nvme5/new_clones/LabVIEW/OpenGDS' &
git clone https://github.com/tuftsBaxter/ROS-for-LabVIEW-Software '/storage/nvme5/new_clones/LabVIEW/ROS-for-LabVIEW-Software' &
git clone https://github.com/xgithubzh/-Labview- '/storage/nvme5/new_clones/LabVIEW/-Labview-' &
git clone https://github.com/LabVIEW-Open-Source/LV-MQTT-Broker '/storage/nvme5/new_clones/LabVIEW/LV-MQTT-Broker' &
git clone https://github.com/CrossTheRoadElec/FRC-Examples-STEAMWORKS '/storage/nvme5/new_clones/LabVIEW/FRC-Examples-STEAMWORKS' &
git clone https://github.com/picotech/picosdk-ni-labview-examples '/storage/nvme5/new_clones/LabVIEW/picosdk-ni-labview-examples' &
git clone https://github.com/JKISoftware/JKI-State-Machine '/storage/nvme5/new_clones/LabVIEW/JKI-State-Machine' &
git clone https://github.com/labviewforRaspi/LabVIEWforRasPi '/storage/nvme5/new_clones/LabVIEW/LabVIEWforRasPi' &
git clone https://github.com/juchong/ADIS16448-RoboRIO-Driver '/storage/nvme5/new_clones/LabVIEW/ADIS16448-RoboRIO-Driver' &
git clone https://github.com/smithed/vicompare '/storage/nvme5/new_clones/LabVIEW/vicompare' &
git clone https://github.com/JKISoftware/HAL-Webinar '/storage/nvme5/new_clones/LabVIEW/HAL-Webinar' &
git clone https://github.com/TomsLabVIEWAdventure/DQMH-Tutorial-Series '/storage/nvme5/new_clones/LabVIEW/DQMH-Tutorial-Series' &
git clone https://github.com/rcpacini/LabVIEW-VI-Hacker '/storage/nvme5/new_clones/LabVIEW/LabVIEW-VI-Hacker' &
git clone https://github.com/rfporter/Modbus-Master '/storage/nvme5/new_clones/LabVIEW/Modbus-Master' &
git clone https://github.com/MuSAELab/MuLES '/storage/nvme5/new_clones/LabVIEW/MuLES' &
git clone https://github.com/IgorTitov/LabVIEW-Advanced-Encryption-Standard '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Advanced-Encryption-Standard' &
git clone https://github.com/marcomauro/Arduino-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Arduino-LabVIEW' &
git clone https://github.com/vipm-io/http-rest-client '/storage/nvme5/new_clones/LabVIEW/http-rest-client' &
git clone https://github.com/NEVSTOP-LAB/LabVIEW-UI-XCtl '/storage/nvme5/new_clones/LabVIEW/LabVIEW-UI-XCtl' &
git clone https://github.com/cowen71/mqtt-LabVIEW '/storage/nvme5/new_clones/LabVIEW/mqtt-LabVIEW' &
git clone https://github.com/MediaMongrels-Ltd/LabVIEW-WebSockets-API '/storage/nvme5/new_clones/LabVIEW/LabVIEW-WebSockets-API' &
git clone https://github.com/vipm-io/vi-tester '/storage/nvme5/new_clones/LabVIEW/vi-tester' &
git clone https://github.com/LabVIEW-Open-Source/ConfigurationManager '/storage/nvme5/new_clones/LabVIEW/ConfigurationManager' &
git clone https://github.com/Benji667/LabVIEW_NPOI '/storage/nvme5/new_clones/LabVIEW/LabVIEW_NPOI' &
git clone https://github.com/properprinting/PPC '/storage/nvme5/new_clones/LabVIEW/PPC' &
git clone https://github.com/wireddown/VIKit '/storage/nvme5/new_clones/LabVIEW/VIKit' &
git clone https://github.com/jovianarts/LVSolutionBuilder '/storage/nvme5/new_clones/LabVIEW/LVSolutionBuilder' &
git clone https://github.com/TomsLabVIEWAdventure/SubPanel-Actor-Framework '/storage/nvme5/new_clones/LabVIEW/SubPanel-Actor-Framework' &
git clone https://github.com/LabVIEW-Open-Source/MQTT-Client '/storage/nvme5/new_clones/LabVIEW/MQTT-Client' &
git clone https://github.com/REVrobotics/Color-Sensor-v3-Examples '/storage/nvme5/new_clones/LabVIEW/Color-Sensor-v3-Examples' &
git clone https://github.com/yildi1337/DAQv2 '/storage/nvme5/new_clones/LabVIEW/DAQv2' &
git clone https://github.com/weaddquality/gsharp '/storage/nvme5/new_clones/LabVIEW/gsharp' &
git clone https://github.com/JKISoftware/JKI-EasyXML '/storage/nvme5/new_clones/LabVIEW/JKI-EasyXML' &
git clone https://github.com/JKISoftware/JKI-JSON-Serialization '/storage/nvme5/new_clones/LabVIEW/JKI-JSON-Serialization' &
git clone https://github.com/JSerwatka/Acoustic-Source-Localization-System '/storage/nvme5/new_clones/LabVIEW/Acoustic-Source-Localization-System' &
git clone https://github.com/ismet55555/LabVIEW-OOP-Classes '/storage/nvme5/new_clones/LabVIEW/LabVIEW-OOP-Classes' &
git clone https://github.com/johanvandenbroek/InfluxDB-Client-LabVIEW '/storage/nvme5/new_clones/LabVIEW/InfluxDB-Client-LabVIEW' &
git clone https://github.com/MuSAELab/BLE-Toolkit-LabVIEW '/storage/nvme5/new_clones/LabVIEW/BLE-Toolkit-LabVIEW' &
git clone https://github.com/HelioScan/HelioScan '/storage/nvme5/new_clones/LabVIEW/HelioScan' &
git clone https://github.com/SoftwareMinimalist/Event-Source-Actor '/storage/nvme5/new_clones/LabVIEW/Event-Source-Actor' &
git clone https://github.com/chrylarson/LabVIEW-HMI '/storage/nvme5/new_clones/LabVIEW/LabVIEW-HMI' &
git clone https://github.com/fieldrndservices/libssh2-labview '/storage/nvme5/new_clones/LabVIEW/libssh2-labview' &
git clone https://github.com/MediaMongrels-Ltd/RPi-LINX-Addons '/storage/nvme5/new_clones/LabVIEW/RPi-LINX-Addons' &
git clone https://github.com/clan4456/CSTK_Icon_Creator '/storage/nvme5/new_clones/LabVIEW/CSTK_Icon_Creator' &
git clone https://github.com/linomp/acoustic-cam-usfq '/storage/nvme5/new_clones/LabVIEW/acoustic-cam-usfq' &
git clone https://github.com/NarrownessSmasher/-LabVIEW-Online-Laboratory- '/storage/nvme5/new_clones/LabVIEW/-LabVIEW-Online-Laboratory-' &
git clone https://github.com/HopeHarrison/PaneRelief '/storage/nvme5/new_clones/LabVIEW/PaneRelief' &
git clone https://github.com/kleinsimon/LV-WebView2 '/storage/nvme5/new_clones/LabVIEW/LV-WebView2' &
git clone https://github.com/ni/labview-memory-management-tools '/storage/nvme5/new_clones/LabVIEW/labview-memory-management-tools' &
git clone https://github.com/Astemes/astemes-lunit '/storage/nvme5/new_clones/LabVIEW/astemes-lunit' &
git clone https://github.com/AeroQuad/AeroQuadConfigurator '/storage/nvme5/new_clones/LabVIEW/AeroQuadConfigurator' &
git clone https://github.com/ni/niveristand-custom-device-build-tools '/storage/nvme5/new_clones/LabVIEW/niveristand-custom-device-build-tools' &
git clone https://github.com/xiaoyun94/OFDM-Framework-LabVIEW '/storage/nvme5/new_clones/LabVIEW/OFDM-Framework-LabVIEW' &
git clone https://github.com/LabVIEW-DCAF/buildsystem '/storage/nvme5/new_clones/LabVIEW/buildsystem' &
git clone https://github.com/JKISoftware/JKI-Simple-Localization '/storage/nvme5/new_clones/LabVIEW/JKI-Simple-Localization' &
git clone https://github.com/fpganow/CryptoCurrencies '/storage/nvme5/new_clones/LabVIEW/CryptoCurrencies' &
git clone https://github.com/ni/niveristand-custom-device-development-tools '/storage/nvme5/new_clones/LabVIEW/niveristand-custom-device-development-tools' &
git clone https://github.com/LabVIEW-Open-Source/ui-tools '/storage/nvme5/new_clones/LabVIEW/ui-tools' &
git clone https://github.com/NIVeriStandAdd-Ons/Jenkins-Autobuild '/storage/nvme5/new_clones/LabVIEW/Jenkins-Autobuild' &
git clone https://github.com/TomsLabVIEWAdventure/Chat-Window-Tutorial-Series '/storage/nvme5/new_clones/LabVIEW/Chat-Window-Tutorial-Series' &
git clone https://github.com/rcpacini/LabVIEW-Hashlib '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Hashlib' &
git clone https://github.com/JKISoftware/JKI-State-Machine-Editor '/storage/nvme5/new_clones/LabVIEW/JKI-State-Machine-Editor' &
git clone https://github.com/jsimpso81/WPIlibMathLabVIEW '/storage/nvme5/new_clones/LabVIEW/WPIlibMathLabVIEW' &
git clone https://github.com/TomsLabVIEWAdventure/Interfaces-in-G-HAL- '/storage/nvme5/new_clones/LabVIEW/Interfaces-in-G-HAL-' &
git clone https://github.com/Yizhiping/Labview-UartHelper '/storage/nvme5/new_clones/LabVIEW/Labview-UartHelper' &
git clone https://github.com/PicoG/PicoG '/storage/nvme5/new_clones/LabVIEW/PicoG' &
git clone https://github.com/TomsLabVIEWAdventure/ChatRoom '/storage/nvme5/new_clones/LabVIEW/ChatRoom' &
git clone https://github.com/LabVIEW-Open-Source/DataManipulation '/storage/nvme5/new_clones/LabVIEW/DataManipulation' &
git clone https://github.com/DaniJobe/facial-recognition-example-labview '/storage/nvme5/new_clones/LabVIEW/facial-recognition-example-labview' &
git clone https://github.com/ni/niveristand-scan-engine-ethercat-custom-device '/storage/nvme5/new_clones/LabVIEW/niveristand-scan-engine-ethercat-custom-device' &
git clone https://github.com/TomsLabVIEWAdventure/IntroToOOP '/storage/nvme5/new_clones/LabVIEW/IntroToOOP' &
git clone https://github.com/CrossTheRoadElec/Phoenix5-Examples-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Phoenix5-Examples-LabVIEW' &
git clone https://github.com/LabVIEW-DCAF/Documentation '/storage/nvme5/new_clones/LabVIEW/Documentation' &
git clone https://github.com/fpganow/MarketData '/storage/nvme5/new_clones/LabVIEW/MarketData' &
git clone https://github.com/FloresFelipe/LabVIEW-OOP-Design-Patterns '/storage/nvme5/new_clones/LabVIEW/LabVIEW-OOP-Design-Patterns' &
git clone https://github.com/flarn2006/VILab '/storage/nvme5/new_clones/LabVIEW/VILab' &
git clone https://github.com/SoftwareMinimalist/LabVIEW-User-Interface-Manager '/storage/nvme5/new_clones/LabVIEW/LabVIEW-User-Interface-Manager' &
git clone https://github.com/juchong/ADIS16470-RoboRIO-Driver '/storage/nvme5/new_clones/LabVIEW/ADIS16470-RoboRIO-Driver' &
git clone https://github.com/rfporter/LV-muParser '/storage/nvme5/new_clones/LabVIEW/LV-muParser' &
git clone https://github.com/Tom-Lu/TestLite '/storage/nvme5/new_clones/LabVIEW/TestLite' &
git clone https://github.com/XDRM-IRobot/upper-computer '/storage/nvme5/new_clones/LabVIEW/upper-computer' &
git clone https://github.com/SoftwareMinimalist/Tree-Map-API '/storage/nvme5/new_clones/LabVIEW/Tree-Map-API' &
git clone https://github.com/Frisbeeee/rust-labview-examples '/storage/nvme5/new_clones/LabVIEW/rust-labview-examples' &
git clone https://github.com/LVMakerHub/Toolbox '/storage/nvme5/new_clones/LabVIEW/Toolbox' &
git clone https://github.com/NISystemsEngineering/CEF '/storage/nvme5/new_clones/LabVIEW/CEF' &
git clone https://github.com/NIVeriStandAdd-Ons/Diagnostics-Custom-Device '/storage/nvme5/new_clones/LabVIEW/Diagnostics-Custom-Device' &
git clone https://github.com/solitontech/SLL-Drona '/storage/nvme5/new_clones/LabVIEW/SLL-Drona' &
git clone https://github.com/PantherLAB/PantherDashboard '/storage/nvme5/new_clones/LabVIEW/PantherDashboard' &
git clone https://github.com/shuai132/SimpleOscillograph_For_LabVIEW '/storage/nvme5/new_clones/LabVIEW/SimpleOscillograph_For_LabVIEW' &
git clone https://github.com/prabubharathi85/LabVIEW-BLE-Driver '/storage/nvme5/new_clones/LabVIEW/LabVIEW-BLE-Driver' &
git clone https://github.com/clan4456/CSTK_Enum_Creator '/storage/nvme5/new_clones/LabVIEW/CSTK_Enum_Creator' &
git clone https://github.com/DanMoriarty/Model-Predictive-Control '/storage/nvme5/new_clones/LabVIEW/Model-Predictive-Control' &
git clone https://github.com/TomsLabVIEWAdventure/Creating-your-first-actor '/storage/nvme5/new_clones/LabVIEW/Creating-your-first-actor' &
git clone https://github.com/Microndgt/DataAcquisitionXiDian '/storage/nvme5/new_clones/LabVIEW/DataAcquisitionXiDian' &
git clone https://github.com/ni/niveristand-custom-device-wizard '/storage/nvme5/new_clones/LabVIEW/niveristand-custom-device-wizard' &
git clone https://github.com/levylabpitt/Multichannel-Lockin '/storage/nvme5/new_clones/LabVIEW/Multichannel-Lockin' &
git clone https://github.com/ni/niveristand-instrument-addon-custom-device '/storage/nvme5/new_clones/LabVIEW/niveristand-instrument-addon-custom-device' &
git clone https://github.com/JQIamo/SetList '/storage/nvme5/new_clones/LabVIEW/SetList' &
git clone https://github.com/unipsycho/Graph-Extensions-LabVIEW-MSChart '/storage/nvme5/new_clones/LabVIEW/Graph-Extensions-LabVIEW-MSChart' &
git clone https://github.com/fisothemes/LabVIEW-TwinCAT-ADS '/storage/nvme5/new_clones/LabVIEW/LabVIEW-TwinCAT-ADS' &
git clone https://github.com/LabVIEW-Open-Source/Epoch-Time '/storage/nvme5/new_clones/LabVIEW/Epoch-Time' &
git clone https://github.com/4201VitruvianBots/LabView2016Code '/storage/nvme5/new_clones/LabVIEW/LabView2016Code' &
git clone https://github.com/NEVSTOP-LAB/LabVIEW-GlobalStop-Library '/storage/nvme5/new_clones/LabVIEW/LabVIEW-GlobalStop-Library' &
git clone https://github.com/mVi-Academy/LabVIEW-ViPrjDevPrcts-PurpleBook '/storage/nvme5/new_clones/LabVIEW/LabVIEW-ViPrjDevPrcts-PurpleBook' &
git clone https://github.com/ORNLPES/CSEISMIC '/storage/nvme5/new_clones/LabVIEW/CSEISMIC' &
git clone https://github.com/etfovac/WinAPI-LV '/storage/nvme5/new_clones/LabVIEW/WinAPI-LV' &
git clone https://github.com/ni/measurement-plugin-labview '/storage/nvme5/new_clones/LabVIEW/measurement-plugin-labview' &
git clone https://github.com/LV-APT/lvCICD '/storage/nvme5/new_clones/LabVIEW/lvCICD' &
git clone https://github.com/solitontech/SLL-Toolkit '/storage/nvme5/new_clones/LabVIEW/SLL-Toolkit' &
git clone https://github.com/TomsLabVIEWAdventure/DQMH-Vending-Machine '/storage/nvme5/new_clones/LabVIEW/DQMH-Vending-Machine' &
git clone https://github.com/allenh-ni/nipm-feed-manager-gui-labview '/storage/nvme5/new_clones/LabVIEW/nipm-feed-manager-gui-labview' &
git clone https://github.com/TomsLabVIEWAdventure/SnakeGameOOP '/storage/nvme5/new_clones/LabVIEW/SnakeGameOOP' &
git clone https://github.com/TomsLabVIEWAdventure/InterfaceMessagesActorFramework '/storage/nvme5/new_clones/LabVIEW/InterfaceMessagesActorFramework' &
git clone https://github.com/christiandbf/ControlPID-PositionVelocity-MotorDC '/storage/nvme5/new_clones/LabVIEW/ControlPID-PositionVelocity-MotorDC' &
git clone https://github.com/ni/aws-toolkit '/storage/nvme5/new_clones/LabVIEW/aws-toolkit' &
git clone https://github.com/NIVeriStandAdd-Ons/NI-VeriStand-Tutorial '/storage/nvme5/new_clones/LabVIEW/NI-VeriStand-Tutorial' &
git clone https://github.com/fpganow/MicroBlaze_UART '/storage/nvme5/new_clones/LabVIEW/MicroBlaze_UART' &
git clone https://github.com/LabVIEW-DCAF/Scan-Engine-Module '/storage/nvme5/new_clones/LabVIEW/Scan-Engine-Module' &
git clone https://github.com/NISystemsEngineering/LinuxRT-IPC '/storage/nvme5/new_clones/LabVIEW/LinuxRT-IPC' &
git clone https://github.com/properprinting/MID '/storage/nvme5/new_clones/LabVIEW/MID' &
git clone https://github.com/DBTaylor/lv-scripting '/storage/nvme5/new_clones/LabVIEW/lv-scripting' &
git clone https://github.com/NISystemsEngineering/TLB-Prime '/storage/nvme5/new_clones/LabVIEW/TLB-Prime' &
git clone https://github.com/ni/labview-gdrive '/storage/nvme5/new_clones/LabVIEW/labview-gdrive' &
git clone https://github.com/yzhang34/Instant-FLIM-Control '/storage/nvme5/new_clones/LabVIEW/Instant-FLIM-Control' &
git clone https://github.com/krtzer/WPA2-Wireless-Network-LabVIEW-FPGA-Testing '/storage/nvme5/new_clones/LabVIEW/WPA2-Wireless-Network-LabVIEW-FPGA-Testing' &
git clone https://github.com/ni/rad '/storage/nvme5/new_clones/LabVIEW/rad' &
git clone https://github.com/LabVIEW-DCAF/ModbusModules '/storage/nvme5/new_clones/LabVIEW/ModbusModules' &
git clone https://github.com/juncaofish/NI-LabVIEWInterfaceforBlynk '/storage/nvme5/new_clones/LabVIEW/NI-LabVIEWInterfaceforBlynk' &
git clone https://github.com/NEVSTOP-LAB/LabVIEW-OPCUA-XML-Library '/storage/nvme5/new_clones/LabVIEW/LabVIEW-OPCUA-XML-Library' &
git clone https://github.com/ni/data-record-ad '/storage/nvme5/new_clones/LabVIEW/data-record-ad' &
git clone https://github.com/jsimpso81/FRC_Secret_Book_Of_FRC_LabVIEW_2 '/storage/nvme5/new_clones/LabVIEW/FRC_Secret_Book_Of_FRC_LabVIEW_2' &
git clone https://github.com/VITechnologies/RemoteLabVIEWInterface '/storage/nvme5/new_clones/LabVIEW/RemoteLabVIEWInterface' &
git clone https://github.com/20087843/lv_-actor_-analysis '/storage/nvme5/new_clones/LabVIEW/lv_-actor_-analysis' &
git clone https://github.com/crossrulz/SerialPortNuggets '/storage/nvme5/new_clones/LabVIEW/SerialPortNuggets' &
git clone https://github.com/TEAM2137/2137-2014-roboRIO-Labview '/storage/nvme5/new_clones/LabVIEW/2137-2014-roboRIO-Labview' &
git clone https://github.com/kurtafriday/ViPER '/storage/nvme5/new_clones/LabVIEW/ViPER' &
git clone https://github.com/logmanoriginal/LabVIEW-Composition '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Composition' &
git clone https://github.com/illuminated-g/lv-http-server '/storage/nvme5/new_clones/LabVIEW/lv-http-server' &
git clone https://github.com/rfporter/Robust-CSV '/storage/nvme5/new_clones/LabVIEW/Robust-CSV' &
git clone https://github.com/chinghwayu/Command-Line-Tools '/storage/nvme5/new_clones/LabVIEW/Command-Line-Tools' &
git clone https://github.com/Andreas-Siemens/InfluxDB-v2-LabVIEW-Client '/storage/nvme5/new_clones/LabVIEW/InfluxDB-v2-LabVIEW-Client' &
git clone https://github.com/NISystemsEngineering/LVTools-Palettes '/storage/nvme5/new_clones/LabVIEW/LVTools-Palettes' &
git clone https://github.com/Dawgma-1712/new-FRC-2018 '/storage/nvme5/new_clones/LabVIEW/new-FRC-2018' &
git clone https://github.com/NEVSTOP-LAB/LabVIEW-QuickDrops-Manager '/storage/nvme5/new_clones/LabVIEW/LabVIEW-QuickDrops-Manager' &
git clone https://github.com/LabVIEW-DCAF/TagEditorCore '/storage/nvme5/new_clones/LabVIEW/TagEditorCore' &
git clone https://github.com/ladikvadim/Telegram-Bot '/storage/nvme5/new_clones/LabVIEW/Telegram-Bot' &
git clone https://github.com/metsrl/twincat-lv-ads-library '/storage/nvme5/new_clones/LabVIEW/twincat-lv-ads-library' &
git clone https://github.com/Indie-Energy/AWS-IoT-RESTful '/storage/nvme5/new_clones/LabVIEW/AWS-IoT-RESTful' &
git clone https://github.com/gb119/LabVIEW-Bits '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Bits' &
git clone https://github.com/NISystemsEngineering/AsynchronousMessageCommunication '/storage/nvme5/new_clones/LabVIEW/AsynchronousMessageCommunication' &
git clone https://github.com/3esmit/LabVIEW-MongoDB '/storage/nvme5/new_clones/LabVIEW/LabVIEW-MongoDB' &
git clone https://github.com/navinsubramani/LabVIEW-Script-Language '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Script-Language' &
git clone https://github.com/JKISoftware/jki-labview-python-server '/storage/nvme5/new_clones/LabVIEW/jki-labview-python-server' &
git clone https://github.com/fpganow/FIXParser '/storage/nvme5/new_clones/LabVIEW/FIXParser' &
git clone https://github.com/rajsite/i3-json '/storage/nvme5/new_clones/LabVIEW/i3-json' &
git clone https://github.com/jasonrorr/ActorFrameworkAbstractMessages '/storage/nvme5/new_clones/LabVIEW/ActorFrameworkAbstractMessages' &
git clone https://github.com/weizhaopeng/ghostImaging '/storage/nvme5/new_clones/LabVIEW/ghostImaging' &
git clone https://github.com/ni/labview-gmaps '/storage/nvme5/new_clones/LabVIEW/labview-gmaps' &
git clone https://github.com/digiajay/LogAnyLabVIEWdata '/storage/nvme5/new_clones/LabVIEW/LogAnyLabVIEWdata' &
git clone https://github.com/roboime/SSL_AI '/storage/nvme5/new_clones/LabVIEW/SSL_AI' &
git clone https://github.com/PacktPublishing/Data-Acquisition-Using-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Data-Acquisition-Using-LabVIEW' &
git clone https://github.com/Bas-vE/LabviewJenkinsExample '/storage/nvme5/new_clones/LabVIEW/LabviewJenkinsExample' &
git clone https://github.com/Sylphe88/UI-Box '/storage/nvme5/new_clones/LabVIEW/UI-Box' &
git clone https://github.com/NISystemsEngineering/FrontPanelLayout '/storage/nvme5/new_clones/LabVIEW/FrontPanelLayout' &
git clone https://github.com/carlosandroni/RedisLabviewPubSub '/storage/nvme5/new_clones/LabVIEW/RedisLabviewPubSub' &
git clone https://github.com/rcpacini/labview_json '/storage/nvme5/new_clones/LabVIEW/labview_json' &
git clone https://github.com/laserengineer/LabVIEW-Study '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Study' &
git clone https://github.com/JKISoftware/JKI-SMO-Templates '/storage/nvme5/new_clones/LabVIEW/JKI-SMO-Templates' &
git clone https://github.com/LabVIEW-DCAF/EIPModule '/storage/nvme5/new_clones/LabVIEW/EIPModule' &
git clone https://github.com/talent518/LabViewDemo '/storage/nvme5/new_clones/LabVIEW/LabViewDemo' &
git clone https://github.com/ni/niveristand-custom-device-testing-tools '/storage/nvme5/new_clones/LabVIEW/niveristand-custom-device-testing-tools' &
git clone https://github.com/LabVIEW-DCAF/StandardEngine '/storage/nvme5/new_clones/LabVIEW/StandardEngine' &
git clone https://github.com/Technologies-de-France/Formation-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Formation-LabVIEW' &
git clone https://github.com/canlasd/Labview-Projects '/storage/nvme5/new_clones/LabVIEW/Labview-Projects' &
git clone https://github.com/LabVIEW-DCAF/DCAF-Examples '/storage/nvme5/new_clones/LabVIEW/DCAF-Examples' &
git clone https://github.com/DaniJobe/LabVIEW2018-Python-Integration-Example '/storage/nvme5/new_clones/LabVIEW/LabVIEW2018-Python-Integration-Example' &
git clone https://github.com/MediaMongrels-Ltd/LabVIEW-Secure-WebSockets-Addon '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Secure-WebSockets-Addon' &
git clone https://github.com/matrixx567/LabView_QuickDrop_AlignElements '/storage/nvme5/new_clones/LabVIEW/LabView_QuickDrop_AlignElements' &
git clone https://github.com/ni/niveristand-fpga-addon-custom-device '/storage/nvme5/new_clones/LabVIEW/niveristand-fpga-addon-custom-device' &
git clone https://github.com/erisir/MMicroscopy '/storage/nvme5/new_clones/LabVIEW/MMicroscopy' &
git clone https://github.com/justiceb/BlueSerialization '/storage/nvme5/new_clones/LabVIEW/BlueSerialization' &
git clone https://github.com/LabVIEW-DCAF/UTF-Test '/storage/nvme5/new_clones/LabVIEW/UTF-Test' &
git clone https://github.com/LabVIEW-DCAF/OPC-UA '/storage/nvme5/new_clones/LabVIEW/OPC-UA' &
git clone https://github.com/mrhappyasthma/Snake '/storage/nvme5/new_clones/LabVIEW/Snake' &
git clone https://github.com/levylabpitt/AFM-Lithography '/storage/nvme5/new_clones/LabVIEW/AFM-Lithography' &
git clone https://github.com/erdosmiller/lv-toml '/storage/nvme5/new_clones/LabVIEW/lv-toml' &
git clone https://github.com/SynapseProgramming/ros2labview_lvprograms '/storage/nvme5/new_clones/LabVIEW/ros2labview_lvprograms' &
git clone https://github.com/SoftwareMinimalist/LabVIEW-SOLID-Examples '/storage/nvme5/new_clones/LabVIEW/LabVIEW-SOLID-Examples' &
git clone https://github.com/neilpate/3DEngine '/storage/nvme5/new_clones/LabVIEW/3DEngine' &
git clone https://github.com/NIVeriStandAdd-Ons/UDP-Data-Link-Custom-Device '/storage/nvme5/new_clones/LabVIEW/UDP-Data-Link-Custom-Device' &
git clone https://github.com/NIVeriStandAdd-Ons/J1939-Custom-Device '/storage/nvme5/new_clones/LabVIEW/J1939-Custom-Device' &
git clone https://github.com/LabVIEW-DCAF/CVTModule '/storage/nvme5/new_clones/LabVIEW/CVTModule' &
git clone https://github.com/rfporter/SET-Toolkit '/storage/nvme5/new_clones/LabVIEW/SET-Toolkit' &
git clone https://github.com/bewersdorflab/isoSTED '/storage/nvme5/new_clones/LabVIEW/isoSTED' &
git clone https://github.com/NIVeriStandAdd-Ons/CAN-Frame-Protection-Custom-Device '/storage/nvme5/new_clones/LabVIEW/CAN-Frame-Protection-Custom-Device' &
git clone https://github.com/Hopperpop/LV_HackRF_FMreceiver '/storage/nvme5/new_clones/LabVIEW/LV_HackRF_FMreceiver' &
git clone https://github.com/FRC4048/Swerve-Drive-Example-2019-LabVIEW '/storage/nvme5/new_clones/LabVIEW/Swerve-Drive-Example-2019-LabVIEW' &
git clone https://github.com/mbilyk/NIPM-Tutorial '/storage/nvme5/new_clones/LabVIEW/NIPM-Tutorial' &
git clone https://github.com/k-ying/LabVIEW-BLE-Examples '/storage/nvme5/new_clones/LabVIEW/LabVIEW-BLE-Examples' &
git clone https://github.com/VITechnologies/DataGridView '/storage/nvme5/new_clones/LabVIEW/DataGridView' &
git clone https://github.com/samangh/wamplv '/storage/nvme5/new_clones/LabVIEW/wamplv' &
git clone https://github.com/keale/Viewable_Actor '/storage/nvme5/new_clones/LabVIEW/Viewable_Actor' &
git clone https://github.com/SilverLabUCL/SilverLab-Microscope-Software '/storage/nvme5/new_clones/LabVIEW/SilverLab-Microscope-Software' &
git clone https://github.com/oxyoung/Quanser-Active-Suspension-System-Design-LQR-MPC-Controller- '/storage/nvme5/new_clones/LabVIEW/Quanser-Active-Suspension-System-Design-LQR-MPC-Controller-' &
git clone https://github.com/LabVIEW-DCAF/TDMSModule '/storage/nvme5/new_clones/LabVIEW/TDMSModule' &
git clone https://github.com/NIVeriStandAdd-Ons/AIT-ARINC-429 '/storage/nvme5/new_clones/LabVIEW/AIT-ARINC-429' &
git clone https://github.com/logmanoriginal/JSONtext-Object-Serialization '/storage/nvme5/new_clones/LabVIEW/JSONtext-Object-Serialization' &
git clone https://github.com/Eben60/LabVIEW0.jl '/storage/nvme5/new_clones/LabVIEW/LabVIEW0.jl' &
git clone https://github.com/mikeroyal/LabVIEW-Guide '/storage/nvme5/new_clones/LabVIEW/LabVIEW-Guide' &
git clone https://github.com/jsimpso81/PhotonVisionLabVIEW '/storage/nvme5/new_clones/LabVIEW/PhotonVisionLabVIEW' &
git clone https://github.com/viafcccy/CSU_labview '/storage/nvme5/new_clones/LabVIEW/CSU_labview' &
git clone https://github.com/benmanthey/Power-Requests '/storage/nvme5/new_clones/LabVIEW/Power-Requests' &
git clone https://github.com/JKISoftware/NIWeek2016-AI_With_LabVIEW '/storage/nvme5/new_clones/LabVIEW/NIWeek2016-AI_With_LabVIEW' &
git clone https://github.com/elijah286/Extensible-Config-Dialog '/storage/nvme5/new_clones/LabVIEW/Extensible-Config-Dialog' &
git clone https://github.com/coyote259/LV_Servo_Motor_Driver '/storage/nvme5/new_clones/LabVIEW/LV_Servo_Motor_Driver' &
git clone https://github.com/NISystemsEngineering/rfic-reference-design-libraries-labview '/storage/nvme5/new_clones/LabVIEW/rfic-reference-design-libraries-labview' &
git clone https://github.com/jmor2000/LV-OMRON-FINS '/storage/nvme5/new_clones/LabVIEW/LV-OMRON-FINS' &
git clone https://github.com/ni/niveristand-ballard-arinc429-custom-device '/storage/nvme5/new_clones/LabVIEW/niveristand-ballard-arinc429-custom-device' &
git clone https://github.com/jcnossen/BeadTracker '/storage/nvme5/new_clones/LabVIEW/BeadTracker' &
git clone https://github.com/NI-Powertrain-Controls/ECS '/storage/nvme5/new_clones/LabVIEW/ECS' &
git clone https://github.com/NISystemsEngineering/USRP-Streaming-Examples '/storage/nvme5/new_clones/LabVIEW/USRP-Streaming-Examples' &
git clone https://github.com/LabVIEW-DCAF/syslog '/storage/nvme5/new_clones/LabVIEW/syslog' &
git clone https://github.com/jimkring/a-version-explorer-for-labview '/storage/nvme5/new_clones/LabVIEW/a-version-explorer-for-labview' &
git clone https://github.com/Sylphe88/PromVIEW '/storage/nvme5/new_clones/LabVIEW/PromVIEW' &
git clone https://github.com/rcpacini/LabVIEW-VI-Snippet '/storage/nvme5/new_clones/LabVIEW/LabVIEW-VI-Snippet' &
git clone https://github.com/levylabpitt/Instrument-Framework '/storage/nvme5/new_clones/LabVIEW/Instrument-Framework' &
git clone https://github.com/LabVIEW-Open-Source/Serializer.Addons '/storage/nvme5/new_clones/LabVIEW/Serializer.Addons' &
git clone https://github.com/Benji667/Custom-Controls '/storage/nvme5/new_clones/LabVIEW/Custom-Controls' &
