#!/bin/bash

git clone https://github.com/kinverarity1/lasio '/storage/nvme5/new_clones/Lasso/lasio' &
git clone https://github.com/andymcdgeo/Petrophysics-Python-Series '/storage/nvme5/new_clones/Lasso/Petrophysics-Python-Series' &
git clone https://github.com/bolgebrygg/Force-2020-Machine-Learning-competition '/storage/nvme5/new_clones/Lasso/Force-2020-Machine-Learning-competition' &
git clone https://github.com/yohanesnuwara/MLGeo '/storage/nvme5/new_clones/Lasso/MLGeo' &
git clone https://github.com/yohanesnuwara/carbon-capture-and-storage '/storage/nvme5/new_clones/Lasso/carbon-capture-and-storage' &
git clone https://github.com/openBIMstandards/Archive-DataSetSchependomlaan '/storage/nvme5/new_clones/Lasso/Archive-DataSetSchependomlaan' &
git clone https://github.com/jessepisel/5minutesofpython '/storage/nvme5/new_clones/Lasso/5minutesofpython' &
git clone https://github.com/921kiyo/symbolic-rl '/storage/nvme5/new_clones/Lasso/symbolic-rl' &
git clone https://github.com/dnicolasespinoza/GeomechanicsJupyter '/storage/nvme5/new_clones/Lasso/GeomechanicsJupyter' &
git clone https://github.com/yohanesnuwara/formation-evaluation '/storage/nvme5/new_clones/Lasso/formation-evaluation' &
git clone https://github.com/potokrm/oil-and-gas '/storage/nvme5/new_clones/Lasso/oil-and-gas' &
git clone https://github.com/mardani72/Synthetic_Seismogram '/storage/nvme5/new_clones/Lasso/Synthetic_Seismogram' &
git clone https://github.com/Lanica/Platform-platino '/storage/nvme5/new_clones/Lasso/Platform-platino' &
git clone https://github.com/dlseis/dlseis_well_tie '/storage/nvme5/new_clones/Lasso/dlseis_well_tie' &
git clone https://github.com/Zabamund/transform2020-getting-started-python '/storage/nvme5/new_clones/Lasso/transform2020-getting-started-python' &
git clone https://github.com/laslibs/las-js '/storage/nvme5/new_clones/Lasso/las-js' &
git clone https://github.com/spike-imperial/FastLAS '/storage/nvme5/new_clones/Lasso/FastLAS' &
git clone https://github.com/explorerai/open-basemap '/storage/nvme5/new_clones/Lasso/open-basemap' &
git clone https://github.com/knop-project/knop '/storage/nvme5/new_clones/Lasso/knop' &
git clone https://github.com/dapson2real/Well_log_Prediction '/storage/nvme5/new_clones/Lasso/Well_log_Prediction' &
git clone https://github.com/ThomasMGeo/Transform2020 '/storage/nvme5/new_clones/Lasso/Transform2020' &
git clone https://github.com/ariewjy/triple_combo_web_plotter '/storage/nvme5/new_clones/Lasso/triple_combo_web_plotter' &
git clone https://github.com/FRI-Energy-Analytics/alaska '/storage/nvme5/new_clones/Lasso/alaska' &
git clone https://github.com/yohanesnuwara/geostatistics '/storage/nvme5/new_clones/Lasso/geostatistics' &
git clone https://github.com/mardani72/LAS_Pandas '/storage/nvme5/new_clones/Lasso/LAS_Pandas' &
git clone https://github.com/Rocks-n-Code/PythonCourse '/storage/nvme5/new_clones/Lasso/PythonCourse' &
git clone https://github.com/agusphd/geopython '/storage/nvme5/new_clones/Lasso/geopython' &
git clone https://github.com/MattJones82/Modeling-NMR-Derived-T2-Porosity-using-Conventional-Open-Hole-Logs '/storage/nvme5/new_clones/Lasso/Modeling-NMR-Derived-T2-Porosity-using-Conventional-Open-Hole-Logs' &
git clone https://github.com/wellstorm/las2witsml '/storage/nvme5/new_clones/Lasso/las2witsml' &
git clone https://github.com/jfoshee/rockhack '/storage/nvme5/new_clones/Lasso/rockhack' &
git clone https://github.com/Zeroloop/ds '/storage/nvme5/new_clones/Lasso/ds' &
git clone https://github.com/tobi-ore/Well-Log-Visualization-and-Interpretation '/storage/nvme5/new_clones/Lasso/Well-Log-Visualization-and-Interpretation' &
git clone https://github.com/n-riesco/lastodash '/storage/nvme5/new_clones/Lasso/lastodash' &
git clone https://github.com/Amanbhandula/Prediction-of-reservoir-properties-using-Neural-Network '/storage/nvme5/new_clones/Lasso/Prediction-of-reservoir-properties-using-Neural-Network' &
git clone https://github.com/awgeo/Volve_field_data '/storage/nvme5/new_clones/Lasso/Volve_field_data' &
git clone https://github.com/smathermather/postgis-cookbook-data '/storage/nvme5/new_clones/Lasso/postgis-cookbook-data' &
git clone https://github.com/nathangeology/geoviz '/storage/nvme5/new_clones/Lasso/geoviz' &
git clone https://github.com/mlbelobraydi/t21-hack-SwellCorr '/storage/nvme5/new_clones/Lasso/t21-hack-SwellCorr' &
git clone https://github.com/cleveland-metroparks/tree-interpolator '/storage/nvme5/new_clones/Lasso/tree-interpolator' &
git clone https://github.com/Philliec459/Estimations-of-Mode-of-Pore-Throat-Distribution-using-Tensorflow '/storage/nvme5/new_clones/Lasso/Estimations-of-Mode-of-Pore-Throat-Distribution-using-Tensorflow' &
git clone https://github.com/giecaruff/stoneforge '/storage/nvme5/new_clones/Lasso/stoneforge' &
git clone https://github.com/LassoSoft/Memcached '/storage/nvme5/new_clones/Lasso/Memcached' &
git clone https://github.com/CeetronSolutions/resinsight-tutorials '/storage/nvme5/new_clones/Lasso/resinsight-tutorials' &
git clone https://github.com/jessepisel/geohack '/storage/nvme5/new_clones/Lasso/geohack' &
git clone https://github.com/kwinkunks/hacksaw '/storage/nvme5/new_clones/Lasso/hacksaw' &
git clone https://github.com/dianaceroallard/UtahForge_logdata '/storage/nvme5/new_clones/Lasso/UtahForge_logdata' &
git clone https://github.com/bfad/Lasso-HTTP '/storage/nvme5/new_clones/Lasso/Lasso-HTTP' &
git clone https://github.com/polyrabbit/polyglot '/storage/nvme5/new_clones/Lasso/polyglot' &
