#!/bin/bash

git clone https://github.com/baoyongzhang/BigBang '/storage/nvme5/new_clones/Lex/BigBang' &
git clone https://github.com/ysc/cws_evaluation '/storage/nvme5/new_clones/Lex/cws_evaluation' &
git clone https://github.com/TALP-UPC/FreeLing '/storage/nvme5/new_clones/Lex/FreeLing' &
git clone https://github.com/Yale-LILY/dart '/storage/nvme5/new_clones/Lex/dart' &
git clone https://github.com/smc/mlmorph '/storage/nvme5/new_clones/Lex/mlmorph' &
git clone https://github.com/lucasb-eyer/flex-bison-indentation '/storage/nvme5/new_clones/Lex/flex-bison-indentation' &
git clone https://github.com/manexagirrezabal/zeuscansion '/storage/nvme5/new_clones/Lex/zeuscansion' &
git clone https://github.com/amir-zeldes/HebPipe '/storage/nvme5/new_clones/Lex/HebPipe' &
git clone https://github.com/zeeeyang/lexicon_rnn '/storage/nvme5/new_clones/Lex/lexicon_rnn' &
git clone https://github.com/DoctorWkt/4bsd-uucp '/storage/nvme5/new_clones/Lex/4bsd-uucp' &
git clone https://github.com/amir-zeldes/RFTokenizer '/storage/nvme5/new_clones/Lex/RFTokenizer' &
git clone https://github.com/LeonCrashCode/AttentionTargetSentiment '/storage/nvme5/new_clones/Lex/AttentionTargetSentiment' &
git clone https://github.com/EagleW/Stage-wise-Fine-tuning '/storage/nvme5/new_clones/Lex/Stage-wise-Fine-tuning' &
git clone https://github.com/bohana/sentlex '/storage/nvme5/new_clones/Lex/sentlex' &
git clone https://github.com/GreekPerspective/glem '/storage/nvme5/new_clones/Lex/glem' &
git clone https://github.com/antonkarl/icecorpus '/storage/nvme5/new_clones/Lex/icecorpus' &
git clone https://github.com/enhuiz/phoenix-datasets '/storage/nvme5/new_clones/Lex/phoenix-datasets' &
git clone https://github.com/luoyesiqiu/Lexer '/storage/nvme5/new_clones/Lex/Lexer' &
git clone https://github.com/hrafnl/icenlp '/storage/nvme5/new_clones/Lex/icenlp' &
git clone https://github.com/hectormartinez/ud_unsup_parser '/storage/nvme5/new_clones/Lex/ud_unsup_parser' &
git clone https://github.com/tifaniwarnita/indonesian-asr '/storage/nvme5/new_clones/Lex/indonesian-asr' &
git clone https://github.com/Shan1024/Simple-Intellij-Plugin '/storage/nvme5/new_clones/Lex/Simple-Intellij-Plugin' &
git clone https://github.com/o11c/parser-demo '/storage/nvme5/new_clones/Lex/parser-demo' &
git clone https://github.com/human-divanshu/Text-to-Sign-Language '/storage/nvme5/new_clones/Lex/Text-to-Sign-Language' &
git clone https://github.com/studychen/SeeNewsServer '/storage/nvme5/new_clones/Lex/SeeNewsServer' &
git clone https://github.com/alan-turing-institute/defoe '/storage/nvme5/new_clones/Lex/defoe' &
git clone https://github.com/cisocrgroup/Resources '/storage/nvme5/new_clones/Lex/Resources' &
git clone https://github.com/justinscript/term.jcseg '/storage/nvme5/new_clones/Lex/term.jcseg' &
git clone https://github.com/leonardoaraujosantos/Matlab_LLVM_Frontend '/storage/nvme5/new_clones/Lex/Matlab_LLVM_Frontend' &
git clone https://github.com/rickydebojeet/compiler-programs '/storage/nvme5/new_clones/Lex/compiler-programs' &
git clone https://github.com/drawshield/Blazon-Parser '/storage/nvme5/new_clones/Lex/Blazon-Parser' &
git clone https://github.com/NikSWE/lex-samples '/storage/nvme5/new_clones/Lex/lex-samples' &
git clone https://github.com/eugener/highlight.fx '/storage/nvme5/new_clones/Lex/highlight.fx' &
git clone https://github.com/lothelanor/actib '/storage/nvme5/new_clones/Lex/actib' &
git clone https://github.com/comp520/Examples '/storage/nvme5/new_clones/Lex/Examples' &
git clone https://github.com/tim70036/c99-scanner '/storage/nvme5/new_clones/Lex/c99-scanner' &
git clone https://github.com/nraynaud/ada-intellij '/storage/nvme5/new_clones/Lex/ada-intellij' &
git clone https://github.com/Nicoleqwerty/RDF-to-Text '/storage/nvme5/new_clones/Lex/RDF-to-Text' &
git clone https://github.com/ELENA-LANG/tutorials '/storage/nvme5/new_clones/Lex/tutorials' &
git clone https://github.com/khadidjasm/TP-Compil '/storage/nvme5/new_clones/Lex/TP-Compil' &
git clone https://github.com/2817748290/gxtj '/storage/nvme5/new_clones/Lex/gxtj' &
git clone https://github.com/boneill02/md2roff '/storage/nvme5/new_clones/Lex/md2roff' &
git clone https://github.com/krishnodey/Lexical_Analyzer '/storage/nvme5/new_clones/Lex/Lexical_Analyzer' &
git clone https://github.com/Woseseltops/fowlt '/storage/nvme5/new_clones/Lex/fowlt' &
git clone https://github.com/svenpanne/tiger '/storage/nvme5/new_clones/Lex/tiger' &
git clone https://github.com/fluorumlabs/asciidocj '/storage/nvme5/new_clones/Lex/asciidocj' &
git clone https://github.com/kmurray/libvcdparse '/storage/nvme5/new_clones/Lex/libvcdparse' &
git clone https://github.com/shaoran/flex_and_bison_updated_examples '/storage/nvme5/new_clones/Lex/flex_and_bison_updated_examples' &
git clone https://github.com/woodbri/address-standardizer '/storage/nvme5/new_clones/Lex/address-standardizer' &
git clone https://github.com/sinaahmadi/KurdishTokenization '/storage/nvme5/new_clones/Lex/KurdishTokenization' &
git clone https://github.com/FrankLhota56/fortran66-flex '/storage/nvme5/new_clones/Lex/fortran66-flex' &
git clone https://github.com/qingtianxt/IQAA-Maven '/storage/nvme5/new_clones/Lex/IQAA-Maven' &
git clone https://github.com/abhi16180/lex '/storage/nvme5/new_clones/Lex/lex' &
git clone https://github.com/CleLex/CleLex '/storage/nvme5/new_clones/Lex/CleLex' &
git clone https://github.com/begriffs/lexyacc '/storage/nvme5/new_clones/Lex/lexyacc' &
