#!/bin/bash

git clone https://github.com/MutopiaProject/MutopiaProject '/storage/nvme5/new_clones/LilyPond/MutopiaProject' &
git clone https://github.com/grame-cncm/libmusicxml '/storage/nvme5/new_clones/LilyPond/libmusicxml' &
git clone https://github.com/cellist/Lilypond-Sheet-Music '/storage/nvme5/new_clones/LilyPond/Lilypond-Sheet-Music' &
git clone https://github.com/openlilylib/snippets '/storage/nvme5/new_clones/LilyPond/snippets' &
git clone https://github.com/horndude77/open-scores '/storage/nvme5/new_clones/LilyPond/open-scores' &
git clone https://github.com/wbsoft/lilymusic '/storage/nvme5/new_clones/LilyPond/lilymusic' &
git clone https://github.com/OpenLilyPondFonts/lilyjazz '/storage/nvme5/new_clones/LilyPond/lilyjazz' &
git clone https://github.com/nsceaux/nenuvar '/storage/nvme5/new_clones/LilyPond/nenuvar' &
git clone https://github.com/bbloomf/christmas-carols '/storage/nvme5/new_clones/LilyPond/christmas-carols' &
git clone https://github.com/pianomanfrazier/lilypond-in-markdown '/storage/nvme5/new_clones/LilyPond/lilypond-in-markdown' &
git clone https://github.com/magdalenesacredmusic/English-Hymns '/storage/nvme5/new_clones/LilyPond/English-Hymns' &
git clone https://github.com/uliska/lilyglyphs '/storage/nvme5/new_clones/LilyPond/lilyglyphs' &
git clone https://github.com/svenax/bagpipemusic '/storage/nvme5/new_clones/LilyPond/bagpipemusic' &
git clone https://github.com/luminr/xiao-ge '/storage/nvme5/new_clones/LilyPond/xiao-ge' &
git clone https://github.com/Zulko/-sheet-music--Gerhswin-Limehouse-Nights '/storage/nvme5/new_clones/LilyPond/-sheet-music--Gerhswin-Limehouse-Nights' &
git clone https://github.com/davidnalesnik/lilypond-roman-numeral-tool '/storage/nvme5/new_clones/LilyPond/lilypond-roman-numeral-tool' &
git clone https://github.com/kshaffer/musicianship '/storage/nvme5/new_clones/LilyPond/musicianship' &
git clone https://github.com/noteflakes/music '/storage/nvme5/new_clones/LilyPond/music' &
git clone https://github.com/patacrep/patadata '/storage/nvme5/new_clones/LilyPond/patadata' &
git clone https://github.com/nybbs2003/lilypond-Jianpu '/storage/nvme5/new_clones/LilyPond/lilypond-Jianpu' &
git clone https://github.com/openlilylib/openlilylib '/storage/nvme5/new_clones/LilyPond/openlilylib' &
git clone https://github.com/bbloomf/lilypond-songs '/storage/nvme5/new_clones/LilyPond/lilypond-songs' &
git clone https://github.com/madrisan/open-scores '/storage/nvme5/new_clones/LilyPond/open-scores' &
git clone https://github.com/MusicExMachina/MxM '/storage/nvme5/new_clones/LilyPond/MxM' &
git clone https://github.com/thSoft/elysium '/storage/nvme5/new_clones/LilyPond/elysium' &
git clone https://github.com/JedBartlett/OrthodoxLiturgics '/storage/nvme5/new_clones/LilyPond/OrthodoxLiturgics' &
git clone https://github.com/kenakofer/hymnsinger '/storage/nvme5/new_clones/LilyPond/hymnsinger' &
git clone https://github.com/openlilylib/LO-ly '/storage/nvme5/new_clones/LilyPond/LO-ly' &
git clone https://github.com/OOoLilyPond/OOoLilyPond '/storage/nvme5/new_clones/LilyPond/OOoLilyPond' &
git clone https://github.com/soundsfromsound/lemon-pond '/storage/nvme5/new_clones/LilyPond/lemon-pond' &
git clone https://github.com/uliska/lilyponds-scheme '/storage/nvme5/new_clones/LilyPond/lilyponds-scheme' &
git clone https://github.com/dunstad/lilypond '/storage/nvme5/new_clones/LilyPond/lilypond' &
git clone https://github.com/deanrad/music_utils '/storage/nvme5/new_clones/LilyPond/music_utils' &
git clone https://github.com/ananthp/carnatic_scores '/storage/nvme5/new_clones/LilyPond/carnatic_scores' &
git clone https://github.com/941design/realbook '/storage/nvme5/new_clones/LilyPond/realbook' &
git clone https://github.com/jollyjinx/kinder-wollen-singen '/storage/nvme5/new_clones/LilyPond/kinder-wollen-singen' &
git clone https://github.com/kastdeur/lilydrum '/storage/nvme5/new_clones/LilyPond/lilydrum' &
git clone https://github.com/PaulMorris/LilyPond-Clairnote '/storage/nvme5/new_clones/LilyPond/LilyPond-Clairnote' &
git clone https://github.com/threedaymonk/lilypond-shamisen '/storage/nvme5/new_clones/LilyPond/lilypond-shamisen' &
git clone https://github.com/igneus/In-adiutorium '/storage/nvme5/new_clones/LilyPond/In-adiutorium' &
git clone https://github.com/eleprocha/Benford-s-Law_python_code '/storage/nvme5/new_clones/LilyPond/Benford-s-Law_python_code' &
git clone https://github.com/lyp-packages/lilyjazz '/storage/nvme5/new_clones/LilyPond/lilyjazz' &
git clone https://github.com/msikma/beethoven-op111-ly '/storage/nvme5/new_clones/LilyPond/beethoven-op111-ly' &
git clone https://github.com/fanhongtao/music '/storage/nvme5/new_clones/LilyPond/music' &
git clone https://github.com/joram-berger/visualindex '/storage/nvme5/new_clones/LilyPond/visualindex' &
git clone https://github.com/pianomanfrazier/lilypond-in-markdown-v2 '/storage/nvme5/new_clones/LilyPond/lilypond-in-markdown-v2' &
git clone https://github.com/openlilylib/notation-fonts '/storage/nvme5/new_clones/LilyPond/notation-fonts' &
git clone https://github.com/xaviershay/sheets '/storage/nvme5/new_clones/LilyPond/sheets' &
git clone https://github.com/jirihon/pslm '/storage/nvme5/new_clones/LilyPond/pslm' &
git clone https://github.com/alter-kaker/liderbukh '/storage/nvme5/new_clones/LilyPond/liderbukh' &
git clone https://github.com/ykarikos/sheet-music '/storage/nvme5/new_clones/LilyPond/sheet-music' &
git clone https://github.com/artasparks/lilyscores '/storage/nvme5/new_clones/LilyPond/lilyscores' &
git clone https://github.com/dbenjaminmiller/bmusicfonts '/storage/nvme5/new_clones/LilyPond/bmusicfonts' &
git clone https://github.com/semperos/kliros '/storage/nvme5/new_clones/LilyPond/kliros' &
git clone https://github.com/LilyBin/lambda-compile '/storage/nvme5/new_clones/LilyPond/lambda-compile' &
git clone https://github.com/nathanaelmeister/Piano_-_First_two_hand_exercises '/storage/nvme5/new_clones/LilyPond/Piano_-_First_two_hand_exercises' &
git clone https://github.com/benkuhn/carols '/storage/nvme5/new_clones/LilyPond/carols' &
git clone https://github.com/ukely/ukely '/storage/nvme5/new_clones/LilyPond/ukely' &
