#!/bin/bash

git clone https://github.com/Shopify/dawn '/storage/nvme5/new_clones/Liquid/dawn' &
git clone https://github.com/Shopify/Timber '/storage/nvme5/new_clones/Liquid/Timber' &
git clone https://github.com/sylhare/Type-on-Strap '/storage/nvme5/new_clones/Liquid/Type-on-Strap' &
git clone https://github.com/freakdesign/Shopify-code-snippets '/storage/nvme5/new_clones/Liquid/Shopify-code-snippets' &
git clone https://github.com/cmod/craigstarter '/storage/nvme5/new_clones/Liquid/craigstarter' &
git clone https://github.com/allejo/jekyll-toc '/storage/nvme5/new_clones/Liquid/jekyll-toc' &
git clone https://github.com/Shopify/starter-theme '/storage/nvme5/new_clones/Liquid/starter-theme' &
git clone https://github.com/microsoft/FHIR-Converter '/storage/nvme5/new_clones/Liquid/FHIR-Converter' &
git clone https://github.com/the-couch/slater '/storage/nvme5/new_clones/Liquid/slater' &
git clone https://github.com/uicrooks/shopify-foundation-theme '/storage/nvme5/new_clones/Liquid/shopify-foundation-theme' &
git clone https://github.com/TrellisCommerce/shopify-tailwind-starter-base '/storage/nvme5/new_clones/Liquid/shopify-tailwind-starter-base' &
git clone https://github.com/vikrantnegi/shopify-code-snippets '/storage/nvme5/new_clones/Liquid/shopify-code-snippets' &
git clone https://github.com/Shopify/skeleton-theme '/storage/nvme5/new_clones/Liquid/skeleton-theme' &
git clone https://github.com/EvgeniyMukhamedjanov/liquid-ajax-cart '/storage/nvme5/new_clones/Liquid/liquid-ajax-cart' &
git clone https://github.com/mirceapiturca/Sections '/storage/nvme5/new_clones/Liquid/Sections' &
git clone https://github.com/huphtur/tailwind-theme-switcher '/storage/nvme5/new_clones/Liquid/tailwind-theme-switcher' &
git clone https://github.com/lucidnz/bootstrapify-1 '/storage/nvme5/new_clones/Liquid/bootstrapify-1' &
git clone https://github.com/allejo/jekyll-anchor-headings '/storage/nvme5/new_clones/Liquid/jekyll-anchor-headings' &
git clone https://github.com/krjo/shopify-webpack-dev-workflow '/storage/nvme5/new_clones/Liquid/shopify-webpack-dev-workflow' &
git clone https://github.com/dmccuskey/shopify-modern '/storage/nvme5/new_clones/Liquid/shopify-modern' &
git clone https://github.com/VienDinhCom/bootstrap-shopify-theme '/storage/nvme5/new_clones/Liquid/bootstrap-shopify-theme' &
git clone https://github.com/panoply/syncify '/storage/nvme5/new_clones/Liquid/syncify' &
git clone https://github.com/bamos/presentations '/storage/nvme5/new_clones/Liquid/presentations' &
git clone https://github.com/kondasoft/ks-bootshop '/storage/nvme5/new_clones/Liquid/ks-bootshop' &
git clone https://github.com/Shaddix/react-query-swagger '/storage/nvme5/new_clones/Liquid/react-query-swagger' &
git clone https://github.com/montalvomiguelo/hydrogen-theme '/storage/nvme5/new_clones/Liquid/hydrogen-theme' &
git clone https://github.com/blanklob/helium '/storage/nvme5/new_clones/Liquid/helium' &
git clone https://github.com/Czarto/ShopifyScripts '/storage/nvme5/new_clones/Liquid/ShopifyScripts' &
git clone https://github.com/gocomet/snippets '/storage/nvme5/new_clones/Liquid/snippets' &
git clone https://github.com/yegor256/blog '/storage/nvme5/new_clones/Liquid/blog' &
git clone https://github.com/roblabs/xyz-raster-sources '/storage/nvme5/new_clones/Liquid/xyz-raster-sources' &
git clone https://github.com/culturekings/shopify-shortcodes '/storage/nvme5/new_clones/Liquid/shopify-shortcodes' &
git clone https://github.com/Shopify/theme-extension-getting-started '/storage/nvme5/new_clones/Liquid/theme-extension-getting-started' &
git clone https://github.com/Hujjat/shopify-sunrise '/storage/nvme5/new_clones/Liquid/shopify-sunrise' &
git clone https://github.com/KittyGiraudel/site '/storage/nvme5/new_clones/Liquid/site' &
git clone https://github.com/Cam/Shopify-Theme-Framework '/storage/nvme5/new_clones/Liquid/Shopify-Theme-Framework' &
git clone https://github.com/keirwhitaker/shopify-birthday-suit '/storage/nvme5/new_clones/Liquid/shopify-birthday-suit' &
git clone https://github.com/culturekings/shopify-json-parser '/storage/nvme5/new_clones/Liquid/shopify-json-parser' &
git clone https://github.com/polidario/Elizabeth_Clean '/storage/nvme5/new_clones/Liquid/Elizabeth_Clean' &
git clone https://github.com/carolineschnapp/ajaxify-cart '/storage/nvme5/new_clones/Liquid/ajaxify-cart' &
git clone https://github.com/Hujjat/shopify-starter-theme '/storage/nvme5/new_clones/Liquid/shopify-starter-theme' &
git clone https://github.com/kohrongying/11ty-blog-starter '/storage/nvme5/new_clones/Liquid/11ty-blog-starter' &
git clone https://github.com/Shopify/shopify-css-import '/storage/nvme5/new_clones/Liquid/shopify-css-import' &
git clone https://github.com/christopherdodd/Skillshare '/storage/nvme5/new_clones/Liquid/Skillshare' &
git clone https://github.com/jaredkc/shopify-starter-theme '/storage/nvme5/new_clones/Liquid/shopify-starter-theme' &
git clone https://github.com/redhat-cop/openshift-migration-best-practices '/storage/nvme5/new_clones/Liquid/openshift-migration-best-practices' &
git clone https://github.com/james0r/slayed '/storage/nvme5/new_clones/Liquid/slayed' &
git clone https://github.com/devtees/shopify-product-filter '/storage/nvme5/new_clones/Liquid/shopify-product-filter' &
git clone https://github.com/zakhardage/Shopify-Wish-List '/storage/nvme5/new_clones/Liquid/Shopify-Wish-List' &
git clone https://github.com/kikobr/UXVIDEOS '/storage/nvme5/new_clones/Liquid/UXVIDEOS' &
git clone https://github.com/HaxeFlixel/haxeflixel.com '/storage/nvme5/new_clones/Liquid/haxeflixel.com' &
git clone https://github.com/carolineschnapp/add-product-to-cart-automatically '/storage/nvme5/new_clones/Liquid/add-product-to-cart-automatically' &
git clone https://github.com/lukebussey/foundationify '/storage/nvme5/new_clones/Liquid/foundationify' &
git clone https://github.com/thisiscapra/shopify-naked '/storage/nvme5/new_clones/Liquid/shopify-naked' &
git clone https://github.com/patrickbolle/shopify-snippets '/storage/nvme5/new_clones/Liquid/shopify-snippets' &
git clone https://github.com/3daddict/themekit-webpack '/storage/nvme5/new_clones/Liquid/themekit-webpack' &
git clone https://github.com/nitin00709/Shopify-collection-filters-with-working-example '/storage/nvme5/new_clones/Liquid/Shopify-collection-filters-with-working-example' &
git clone https://github.com/strongself/generamba-catalog '/storage/nvme5/new_clones/Liquid/generamba-catalog' &
git clone https://github.com/pixelcabin/shopify_theme_integration_tests '/storage/nvme5/new_clones/Liquid/shopify_theme_integration_tests' &
git clone https://github.com/the-couch/slater-theme '/storage/nvme5/new_clones/Liquid/slater-theme' &
git clone https://github.com/joemasilotti/masilotti.com '/storage/nvme5/new_clones/Liquid/masilotti.com' &
git clone https://github.com/clarityglobal/shopify-gtm-ga '/storage/nvme5/new_clones/Liquid/shopify-gtm-ga' &
git clone https://github.com/zakhardage/Shopify-Wholesale '/storage/nvme5/new_clones/Liquid/Shopify-Wholesale' &
git clone https://github.com/andreasdevjs/shopify_OS20_boilerplate '/storage/nvme5/new_clones/Liquid/shopify_OS20_boilerplate' &
git clone https://github.com/AleksandrHovhannisyan/11ty-sass-images-seo '/storage/nvme5/new_clones/Liquid/11ty-sass-images-seo' &
git clone https://github.com/human-nyc/shopify-theme-starter '/storage/nvme5/new_clones/Liquid/shopify-theme-starter' &
git clone https://github.com/avocadotoastlive/avocadotoast.live '/storage/nvme5/new_clones/Liquid/avocadotoast.live' &
git clone https://github.com/freyum/shopify-workflow-poc '/storage/nvme5/new_clones/Liquid/shopify-workflow-poc' &
git clone https://github.com/leemunroe/shopify-email-templates '/storage/nvme5/new_clones/Liquid/shopify-email-templates' &
git clone https://github.com/brohlson/parcel-themekit '/storage/nvme5/new_clones/Liquid/parcel-themekit' &
git clone https://github.com/timmyomahony/shopify-email-templates '/storage/nvme5/new_clones/Liquid/shopify-email-templates' &
git clone https://github.com/gavinballard/skillshare-examples '/storage/nvme5/new_clones/Liquid/skillshare-examples' &
git clone https://github.com/PacktPublishing/Shopify-Theme-Customization-with-Liquid '/storage/nvme5/new_clones/Liquid/Shopify-Theme-Customization-with-Liquid' &
git clone https://github.com/lucidnz/Bootstrapify-4 '/storage/nvme5/new_clones/Liquid/Bootstrapify-4' &
git clone https://github.com/heliumdevelopment/shopify-boiler '/storage/nvme5/new_clones/Liquid/shopify-boiler' &
git clone https://github.com/mmarienko/debut '/storage/nvme5/new_clones/Liquid/debut' &
git clone https://github.com/ColorlibHQ/Fashe '/storage/nvme5/new_clones/Liquid/Fashe' &
git clone https://github.com/locomotivecms/site '/storage/nvme5/new_clones/Liquid/site' &
git clone https://github.com/iskurbanov/Shopify-Vue-Theme-Full '/storage/nvme5/new_clones/Liquid/Shopify-Vue-Theme-Full' &
git clone https://github.com/t-kelly/shopipoints.com '/storage/nvme5/new_clones/Liquid/shopipoints.com' &
git clone https://github.com/carolineschnapp/donation '/storage/nvme5/new_clones/Liquid/donation' &
git clone https://github.com/mrdexters1/videoBackground.liquid '/storage/nvme5/new_clones/Liquid/videoBackground.liquid' &
git clone https://github.com/werf/website '/storage/nvme5/new_clones/Liquid/website' &
git clone https://github.com/contentful/11ty-contentful-gallery '/storage/nvme5/new_clones/Liquid/11ty-contentful-gallery' &
git clone https://github.com/technologiestiftung/berlin-open-source-portal '/storage/nvme5/new_clones/Liquid/berlin-open-source-portal' &
git clone https://github.com/markustripp/shopify-lang '/storage/nvme5/new_clones/Liquid/shopify-lang' &
git clone https://github.com/pgrimaud/shopify-snippets '/storage/nvme5/new_clones/Liquid/shopify-snippets' &
git clone https://github.com/Kazuki-tam/shopify-email-notification '/storage/nvme5/new_clones/Liquid/shopify-email-notification' &
git clone https://github.com/hta218/shopify-theme-starter '/storage/nvme5/new_clones/Liquid/shopify-theme-starter' &
git clone https://github.com/fatmakiraz/personal-blog-template '/storage/nvme5/new_clones/Liquid/personal-blog-template' &
git clone https://github.com/lucky110209/shopify-recent-viewed-products '/storage/nvme5/new_clones/Liquid/shopify-recent-viewed-products' &
git clone https://github.com/ryanburnette/grunt-shopify-theme '/storage/nvme5/new_clones/Liquid/grunt-shopify-theme' &
git clone https://github.com/Nordic-Dev/shopify-product-image-slider '/storage/nvme5/new_clones/Liquid/shopify-product-image-slider' &
git clone https://github.com/cobalt-org/cobalt-org.github.io '/storage/nvme5/new_clones/Liquid/cobalt-orghub.io' &
git clone https://github.com/manifoldxyz/manifold-templates '/storage/nvme5/new_clones/Liquid/manifold-templates' &
git clone https://github.com/huphtur/hella-simple-eleventy-tailwind-starter '/storage/nvme5/new_clones/Liquid/hella-simple-eleventy-tailwind-starter' &
git clone https://github.com/mortendk/saga11 '/storage/nvme5/new_clones/Liquid/saga11' &
git clone https://github.com/spiral/shopify-starter-kit '/storage/nvme5/new_clones/Liquid/shopify-starter-kit' &
git clone https://github.com/LkeMitchll/interroban.gg '/storage/nvme5/new_clones/Liquid/interroban.gg' &
git clone https://github.com/ergophobe/shopify-breadcrumbs '/storage/nvme5/new_clones/Liquid/shopify-breadcrumbs' &
git clone https://github.com/SidNewman/shopify-transitions '/storage/nvme5/new_clones/Liquid/shopify-transitions' &
git clone https://github.com/stylehatch/hatch '/storage/nvme5/new_clones/Liquid/hatch' &
git clone https://github.com/WorldHealthOrganization/smart-anc '/storage/nvme5/new_clones/Liquid/smart-anc' &
git clone https://github.com/gavinballard/defguide-theme '/storage/nvme5/new_clones/Liquid/defguide-theme' &
git clone https://github.com/itsoli91/OpenApiToRefit '/storage/nvme5/new_clones/Liquid/OpenApiToRefit' &
git clone https://github.com/fatmakiraz/alivedomain-saas-landing-page-template '/storage/nvme5/new_clones/Liquid/alivedomain-saas-landing-page-template' &
git clone https://github.com/3daddict/webpack-shopify-cli '/storage/nvme5/new_clones/Liquid/webpack-shopify-cli' &
git clone https://github.com/t-kurasawa/shopify_dev_template '/storage/nvme5/new_clones/Liquid/shopify_dev_template' &
git clone https://github.com/cameroncowden/debut-drop-ins '/storage/nvme5/new_clones/Liquid/debut-drop-ins' &
git clone https://github.com/carolineschnapp/make-image-change-variant '/storage/nvme5/new_clones/Liquid/make-image-change-variant' &
git clone https://github.com/nairdairda/Shopify-Font-Awesome '/storage/nvme5/new_clones/Liquid/Shopify-Font-Awesome' &
git clone https://github.com/bryanchapel/shopify-debut-color-swatches '/storage/nvme5/new_clones/Liquid/shopify-debut-color-swatches' &
git clone https://github.com/Misterio77/website '/storage/nvme5/new_clones/Liquid/website' &
git clone https://github.com/zoerooney/shopify-starter-theme '/storage/nvme5/new_clones/Liquid/shopify-starter-theme' &
git clone https://github.com/meraki/webhook-payload-templates '/storage/nvme5/new_clones/Liquid/webhook-payload-templates' &
git clone https://github.com/jholl/shopify-product-tabs '/storage/nvme5/new_clones/Liquid/shopify-product-tabs' &
git clone https://github.com/neckerson/slate-bootstrap-theme '/storage/nvme5/new_clones/Liquid/slate-bootstrap-theme' &
git clone https://github.com/mdyd-dev/product-marketplace-template '/storage/nvme5/new_clones/Liquid/product-marketplace-template' &
git clone https://github.com/FernandoCalmet/Tantra '/storage/nvme5/new_clones/Liquid/Tantra' &
git clone https://github.com/fronteers/website '/storage/nvme5/new_clones/Liquid/website' &
git clone https://github.com/wg-d/commercial-shopify-theme-third '/storage/nvme5/new_clones/Liquid/commercial-shopify-theme-third' &
git clone https://github.com/HL7/cqf-measures '/storage/nvme5/new_clones/Liquid/cqf-measures' &
git clone https://github.com/jlengstorf/11ty-examples '/storage/nvme5/new_clones/Liquid/11ty-examples' &
git clone https://github.com/DrLina/Shopify-AMP-Theme '/storage/nvme5/new_clones/Liquid/Shopify-AMP-Theme' &
git clone https://github.com/tensworth/Shopify-Facebook-Pixel '/storage/nvme5/new_clones/Liquid/Shopify-Facebook-Pixel' &
git clone https://github.com/11ty/demo-eleventy-edge '/storage/nvme5/new_clones/Liquid/demo-eleventy-edge' &
git clone https://github.com/neckerson/slate-bootstrap '/storage/nvme5/new_clones/Liquid/slate-bootstrap' &
git clone https://github.com/CeibaWeb/shopify-tailwind-template '/storage/nvme5/new_clones/Liquid/shopify-tailwind-template' &
git clone https://github.com/cqframework/content-ig-walkthrough '/storage/nvme5/new_clones/Liquid/content-ig-walkthrough' &
git clone https://github.com/KeithBradley/Shopify_Collection_Filters '/storage/nvme5/new_clones/Liquid/Shopify_Collection_Filters' &
git clone https://github.com/alfa-laboratory/YARCH-Template '/storage/nvme5/new_clones/Liquid/YARCH-Template' &
git clone https://github.com/airthemeone/Shopify '/storage/nvme5/new_clones/Liquid/Shopify' &
git clone https://github.com/devmoek/recently-viewed-section-dawn '/storage/nvme5/new_clones/Liquid/recently-viewed-section-dawn' &
git clone https://github.com/brohlson/themekit-webpack-tailwind '/storage/nvme5/new_clones/Liquid/themekit-webpack-tailwind' &
git clone https://github.com/wickcreative/shopify-code-nuggets '/storage/nvme5/new_clones/Liquid/shopify-code-nuggets' &
git clone https://github.com/Platform-OS/platformos-documentation '/storage/nvme5/new_clones/Liquid/platformos-documentation' &
git clone https://github.com/Tricky3/Shopify-Checkout-Customizer '/storage/nvme5/new_clones/Liquid/Shopify-Checkout-Customizer' &
git clone https://github.com/BoldizArt/Shopify-Image-Gallery '/storage/nvme5/new_clones/Liquid/Shopify-Image-Gallery' &
git clone https://github.com/carolineschnapp/cart-attributes-validation '/storage/nvme5/new_clones/Liquid/cart-attributes-validation' &
git clone https://github.com/VirtoCommerce/vc-theme-b2b '/storage/nvme5/new_clones/Liquid/vc-theme-b2b' &
git clone https://github.com/RichDom2185/jekyll-fancy-tables '/storage/nvme5/new_clones/Liquid/jekyll-fancy-tables' &
git clone https://github.com/Mendeo/jekyll-minifier '/storage/nvme5/new_clones/Liquid/jekyll-minifier' &
git clone https://github.com/alexcasche/shopify-vue-cart '/storage/nvme5/new_clones/Liquid/shopify-vue-cart' &
git clone https://github.com/SpectralDragon/viperSwift '/storage/nvme5/new_clones/Liquid/viperSwift' &
git clone https://github.com/odestry/shopify-cli-3-workshop '/storage/nvme5/new_clones/Liquid/shopify-cli-3-workshop' &
git clone https://github.com/zakhardage/Sourdough '/storage/nvme5/new_clones/Liquid/Sourdough' &
git clone https://github.com/tccpro/Shopify-IN8 '/storage/nvme5/new_clones/Liquid/Shopify-IN8' &
git clone https://github.com/mwt/matthewthom.as '/storage/nvme5/new_clones/Liquid/matthewthom.as' &
git clone https://github.com/tccpro/IN8-theme_08.01 '/storage/nvme5/new_clones/Liquid/IN8-theme_08.01' &
git clone https://github.com/dainemawer/sneakerlab '/storage/nvme5/new_clones/Liquid/sneakerlab' &
git clone https://github.com/tccpro/IN8_Shopify_Dawn_5.0.0 '/storage/nvme5/new_clones/Liquid/IN8_Shopify_Dawn_5.0.0' &
git clone https://github.com/tccpro/TB_Shopify_on '/storage/nvme5/new_clones/Liquid/TB_Shopify_on' &
git clone https://github.com/tccpro/theme_08_27---upgrading '/storage/nvme5/new_clones/Liquid/theme_08_27---upgrading' &
git clone https://github.com/carolineschnapp/carolineschnapp-gift-wrap '/storage/nvme5/new_clones/Liquid/carolineschnapp-gift-wrap' &
git clone https://github.com/gil--/frontify '/storage/nvme5/new_clones/Liquid/frontify' &
git clone https://github.com/zuixjs/zuix-web-starter '/storage/nvme5/new_clones/Liquid/zuix-web-starter' &
git clone https://github.com/QubitProducts/shopify-qubit-asset '/storage/nvme5/new_clones/Liquid/shopify-qubit-asset' &
git clone https://github.com/socotra/public '/storage/nvme5/new_clones/Liquid/public' &
git clone https://github.com/arteagabriel/slatestrap '/storage/nvme5/new_clones/Liquid/slatestrap' &
git clone https://github.com/tccpro/theme_06_30 '/storage/nvme5/new_clones/Liquid/theme_06_30' &
git clone https://github.com/jzelaya0/Shopify-Debut-Theme-Instagram-Feed '/storage/nvme5/new_clones/Liquid/Shopify-Debut-Theme-Instagram-Feed' &
git clone https://github.com/Huniko519/Shop-Theme-Shopify '/storage/nvme5/new_clones/Liquid/Shop-Theme-Shopify' &
git clone https://github.com/Dezhao-Huang/Lammps-shear-viscosity-calculation '/storage/nvme5/new_clones/Liquid/Lammps-shear-viscosity-calculation' &
git clone https://github.com/UseAllFive/slater-base '/storage/nvme5/new_clones/Liquid/slater-base' &
git clone https://github.com/tccpro/theme_08_19 '/storage/nvme5/new_clones/Liquid/theme_08_19' &
git clone https://github.com/CloudCannon/eleventy-bookshop-starter '/storage/nvme5/new_clones/Liquid/eleventy-bookshop-starter' &
git clone https://github.com/webprofusion/acme-clients '/storage/nvme5/new_clones/Liquid/acme-clients' &
git clone https://github.com/Twigs-for-Timber/popup-ajax-subscribe-form '/storage/nvme5/new_clones/Liquid/popup-ajax-subscribe-form' &
git clone https://github.com/non-standardworld/hello-shopify-themes '/storage/nvme5/new_clones/Liquid/hello-shopify-themes' &
git clone https://github.com/saraamote/Shopify-Development '/storage/nvme5/new_clones/Liquid/Shopify-Development' &
git clone https://github.com/iShopifyExpert/custom-slider '/storage/nvme5/new_clones/Liquid/custom-slider' &
git clone https://github.com/johndigital/shopify-boilerplate '/storage/nvme5/new_clones/Liquid/shopify-boilerplate' &
git clone https://github.com/edlaver/cloudflare-worker-partytown-shopify-app-proxy '/storage/nvme5/new_clones/Liquid/cloudflare-worker-partytown-shopify-app-proxy' &
git clone https://github.com/devwhodevs/blank-shopify-theme '/storage/nvme5/new_clones/Liquid/blank-shopify-theme' &
git clone https://github.com/gravyhtx/shopify_product-tear-sheet '/storage/nvme5/new_clones/Liquid/shopify_product-tear-sheet' &
git clone https://github.com/kmacoders/Shopify-Theme-Starter-Vue3 '/storage/nvme5/new_clones/Liquid/Shopify-Theme-Starter-Vue3' &
git clone https://github.com/wpfreelance/vegfresh '/storage/nvme5/new_clones/Liquid/vegfresh' &
git clone https://github.com/haroldao/haroldao-v2021 '/storage/nvme5/new_clones/Liquid/haroldao-v2021' &
git clone https://github.com/WeeklyHow/Elizabeth '/storage/nvme5/new_clones/Liquid/Elizabeth' &
git clone https://github.com/VienDinhCom/shopify-theme-customizer '/storage/nvme5/new_clones/Liquid/shopify-theme-customizer' &
git clone https://github.com/Mach30/dof '/storage/nvme5/new_clones/Liquid/dof' &
git clone https://github.com/rosberry/Rosberry-Generamba-Templates '/storage/nvme5/new_clones/Liquid/Rosberry-Generamba-Templates' &
git clone https://github.com/Kajabi/theme-cornerstone-page '/storage/nvme5/new_clones/Liquid/theme-cornerstone-page' &
git clone https://github.com/workatease/directus-api '/storage/nvme5/new_clones/Liquid/directus-api' &
git clone https://github.com/bt-rb/bridgetown-theme-bootstrap-blog '/storage/nvme5/new_clones/Liquid/bridgetown-theme-bootstrap-blog' &
git clone https://github.com/christopherdodd/vue-class-theme '/storage/nvme5/new_clones/Liquid/vue-class-theme' &
git clone https://github.com/Helperbird/website '/storage/nvme5/new_clones/Liquid/website' &
git clone https://github.com/jamestrenda/dusk '/storage/nvme5/new_clones/Liquid/dusk' &
git clone https://github.com/Ready-Set-Go-Design/dawn-theme '/storage/nvme5/new_clones/Liquid/dawn-theme' &
git clone https://github.com/theotrain/dawn-with-gocart '/storage/nvme5/new_clones/Liquid/dawn-with-gocart' &
git clone https://github.com/workeffortwaste/seoslides '/storage/nvme5/new_clones/Liquid/seoslides' &
git clone https://github.com/wg-d/commercial-shopify-theme '/storage/nvme5/new_clones/Liquid/commercial-shopify-theme' &
git clone https://github.com/adrien2p/shopify-debut-swatch '/storage/nvme5/new_clones/Liquid/shopify-debut-swatch' &
git clone https://github.com/mitchuman/danshari '/storage/nvme5/new_clones/Liquid/danshari' &
git clone https://github.com/shopinvader/shopinvader-template '/storage/nvme5/new_clones/Liquid/shopinvader-template' &
git clone https://github.com/deepcodeshopify/shopify_bundles '/storage/nvme5/new_clones/Liquid/shopify_bundles' &
git clone https://github.com/dojo-engineering/Dojo.Net '/storage/nvme5/new_clones/Liquid/Dojo.Net' &
git clone https://github.com/alexgaudiosi/Multify '/storage/nvme5/new_clones/Liquid/Multify' &
git clone https://github.com/zahid3d29/Shopify-Mega-Menu-Dawn-2.0-theme '/storage/nvme5/new_clones/Liquid/Shopify-Mega-Menu-Dawn-2.0-theme' &
git clone https://github.com/lukaszmargielewski/ViperTabbar '/storage/nvme5/new_clones/Liquid/ViperTabbar' &
git clone https://github.com/aaronsmulktis/flyelyfe-theme '/storage/nvme5/new_clones/Liquid/flyelyfe-theme' &
git clone https://github.com/Shoplazza/shoplazza-cli '/storage/nvme5/new_clones/Liquid/shoplazza-cli' &
git clone https://github.com/rocklss/shopify_section '/storage/nvme5/new_clones/Liquid/shopify_section' &
git clone https://github.com/uxhacks/shopify-tutorial '/storage/nvme5/new_clones/Liquid/shopify-tutorial' &
git clone https://github.com/IsaAliev/TableViper '/storage/nvme5/new_clones/Liquid/TableViper' &
git clone https://github.com/markmead/shopify-skeleton '/storage/nvme5/new_clones/Liquid/shopify-skeleton' &
git clone https://github.com/kamenarov/shopify-snippets '/storage/nvme5/new_clones/Liquid/shopify-snippets' &
git clone https://github.com/Azure/aimazure '/storage/nvme5/new_clones/Liquid/aimazure' &
git clone https://github.com/sharp46311/Debut-main '/storage/nvme5/new_clones/Liquid/Debut-main' &
git clone https://github.com/w3c/wai-authoring-tools-list '/storage/nvme5/new_clones/Liquid/wai-authoring-tools-list' &
git clone https://github.com/neckerson/shopify-bootstrap-theme '/storage/nvme5/new_clones/Liquid/shopify-bootstrap-theme' &
git clone https://github.com/JoshTag/shopify-2.0-dev-course '/storage/nvme5/new_clones/Liquid/shopify-2.0-dev-course' &
git clone https://github.com/kevprice83/Custom-signup-flows-3scale-Dev-portal '/storage/nvme5/new_clones/Liquid/Custom-signup-flows-3scale-Dev-portal' &
git clone https://github.com/dilloninstruments/shopify-autofill-discount-from-url '/storage/nvme5/new_clones/Liquid/shopify-autofill-discount-from-url' &
git clone https://github.com/xplosionmind/tommi.space '/storage/nvme5/new_clones/Liquid/tommi.space' &
git clone https://github.com/md604/vue-shopify '/storage/nvme5/new_clones/Liquid/vue-shopify' &
git clone https://github.com/mateusfmachado/shopify-sections '/storage/nvme5/new_clones/Liquid/shopify-sections' &
git clone https://github.com/bachloxo/venture-shopify-themes '/storage/nvme5/new_clones/Liquid/venture-shopify-themes' &
git clone https://github.com/Kajabi/theme-cornerstone-site '/storage/nvme5/new_clones/Liquid/theme-cornerstone-site' &
git clone https://github.com/we-make-websites/wmw-advanced-technical-test '/storage/nvme5/new_clones/Liquid/wmw-advanced-technical-test' &
git clone https://github.com/loveshopify/volte-wetsuits '/storage/nvme5/new_clones/Liquid/volte-wetsuits' &
git clone https://github.com/1aurabrown/shopify-boilerplate '/storage/nvme5/new_clones/Liquid/shopify-boilerplate' &
git clone https://github.com/FinetuneDevelopment/mannequin '/storage/nvme5/new_clones/Liquid/mannequin' &
git clone https://github.com/EtchUK/Etch.OrchardCore.Widgets '/storage/nvme5/new_clones/Liquid/Etch.OrchardCore.Widgets' &
git clone https://github.com/josephdadams/PlanningCenterServicesReports '/storage/nvme5/new_clones/Liquid/PlanningCenterServicesReports' &
git clone https://github.com/themefisher/elite-shop-shopify '/storage/nvme5/new_clones/Liquid/elite-shop-shopify' &
git clone https://github.com/shadowtime2000/11ty-notes '/storage/nvme5/new_clones/Liquid/11ty-notes' &
git clone https://github.com/christopherkarger/vue-shopify-filter '/storage/nvme5/new_clones/Liquid/vue-shopify-filter' &
git clone https://github.com/superior57/shopify-cafe--new-them '/storage/nvme5/new_clones/Liquid/shopify-cafe--new-them' &
git clone https://github.com/loveshopify/steele-rewards '/storage/nvme5/new_clones/Liquid/steele-rewards' &
git clone https://github.com/loveshopify/pink-stork '/storage/nvme5/new_clones/Liquid/pink-stork' &
git clone https://github.com/profDevA/sneaker123 '/storage/nvme5/new_clones/Liquid/sneaker123' &
git clone https://github.com/Dermah/blog.dermah.com '/storage/nvme5/new_clones/Liquid/blog.dermah.com' &
git clone https://github.com/martinclason123/Shopify-Customs-Sections-Template '/storage/nvme5/new_clones/Liquid/Shopify-Customs-Sections-Template' &
git clone https://github.com/SLTWTR-Creative-Agency/advancedthemebuilder '/storage/nvme5/new_clones/Liquid/advancedthemebuilder' &
git clone https://github.com/loveshopify/orium '/storage/nvme5/new_clones/Liquid/orium' &
git clone https://github.com/alaydeliwala/debutify-hacks '/storage/nvme5/new_clones/Liquid/debutify-hacks' &
git clone https://github.com/loveshopify/wuffes '/storage/nvme5/new_clones/Liquid/wuffes' &
git clone https://github.com/ishithemes/instafeed_shopify '/storage/nvme5/new_clones/Liquid/instafeed_shopify' &
git clone https://github.com/loveshopify/lafoi '/storage/nvme5/new_clones/Liquid/lafoi' &
git clone https://github.com/loveshopify/cerchionero '/storage/nvme5/new_clones/Liquid/cerchionero' &
git clone https://github.com/lucidnz/lucid-one '/storage/nvme5/new_clones/Liquid/lucid-one' &
git clone https://github.com/sharp46311/slater-master '/storage/nvme5/new_clones/Liquid/slater-master' &
git clone https://github.com/OnefoursevenLabs/Orchard-AdminKit-Free '/storage/nvme5/new_clones/Liquid/Orchard-AdminKit-Free' &
git clone https://github.com/loveshopify/ONL '/storage/nvme5/new_clones/Liquid/ONL' &
git clone https://github.com/loveshopify/supermarket '/storage/nvme5/new_clones/Liquid/supermarket' &
git clone https://github.com/kmcandersen/fitra-theme '/storage/nvme5/new_clones/Liquid/fitra-theme' &
git clone https://github.com/rockorager/11ndieWeb '/storage/nvme5/new_clones/Liquid/11ndieWeb' &
git clone https://github.com/loveshopify/blueshift '/storage/nvme5/new_clones/Liquid/blueshift' &
git clone https://github.com/cqframework/cqf-ccc '/storage/nvme5/new_clones/Liquid/cqf-ccc' &
git clone https://github.com/loveshopify/trojan-fragrances '/storage/nvme5/new_clones/Liquid/trojan-fragrances' &
git clone https://github.com/nikolaitur/Shopify-Boilerplate-Theme '/storage/nvme5/new_clones/Liquid/Shopify-Boilerplate-Theme' &
git clone https://github.com/loveshopify/ann-page '/storage/nvme5/new_clones/Liquid/ann-page' &
git clone https://github.com/lirantal/public-speaking-archive '/storage/nvme5/new_clones/Liquid/public-speaking-archive' &
git clone https://github.com/kennyalmendral/skeletore '/storage/nvme5/new_clones/Liquid/skeletore' &
git clone https://github.com/Luccifer/ramba '/storage/nvme5/new_clones/Liquid/ramba' &
git clone https://github.com/loveshopify/marquet '/storage/nvme5/new_clones/Liquid/marquet' &
git clone https://github.com/RodrigoDornelles/rodrigodornelles.github.io '/storage/nvme5/new_clones/Liquid/rodrigodornelleshub.io' &
git clone https://github.com/markustripp/dawn-mext-1 '/storage/nvme5/new_clones/Liquid/dawn-mext-1' &
git clone https://github.com/lucasaraujo45/notch-shopify-snippets '/storage/nvme5/new_clones/Liquid/notch-shopify-snippets' &
git clone https://github.com/loveshopify/colorboxsa '/storage/nvme5/new_clones/Liquid/colorboxsa' &
git clone https://github.com/loveshopify/viewtique '/storage/nvme5/new_clones/Liquid/viewtique' &
git clone https://github.com/superior57/Cafesenork-shopify-theme '/storage/nvme5/new_clones/Liquid/Cafesenork-shopify-theme' &
git clone https://github.com/DozenPixels/shopify-free-shipping-bar '/storage/nvme5/new_clones/Liquid/shopify-free-shipping-bar' &
git clone https://github.com/loveshopify/vape-and-juice '/storage/nvme5/new_clones/Liquid/vape-and-juice' &
git clone https://github.com/ekwoka/Daybreak '/storage/nvme5/new_clones/Liquid/Daybreak' &
git clone https://github.com/loveshopify/better-cbd '/storage/nvme5/new_clones/Liquid/better-cbd' &
git clone https://github.com/loveshopify/club-hearing '/storage/nvme5/new_clones/Liquid/club-hearing' &
git clone https://github.com/loveshopify/alphaprime '/storage/nvme5/new_clones/Liquid/alphaprime' &
git clone https://github.com/youcan-shop/cod-theme '/storage/nvme5/new_clones/Liquid/cod-theme' &
git clone https://github.com/superhi/fitra '/storage/nvme5/new_clones/Liquid/fitra' &
git clone https://github.com/loveshopify/wingstincture '/storage/nvme5/new_clones/Liquid/wingstincture' &
git clone https://github.com/loveshopify/saddlestitches '/storage/nvme5/new_clones/Liquid/saddlestitches' &
git clone https://github.com/loveshopify/dreamvet '/storage/nvme5/new_clones/Liquid/dreamvet' &
git clone https://github.com/loveshopify/zooki '/storage/nvme5/new_clones/Liquid/zooki' &
git clone https://github.com/jonathanmoore/LiquidColor '/storage/nvme5/new_clones/Liquid/LiquidColor' &
git clone https://github.com/robinsimonklein/shopify-vite '/storage/nvme5/new_clones/Liquid/shopify-vite' &
