#!/bin/bash

git clone https://github.com/llvm/llvm-project '/storage/nvme5/new_clones/LLVM/llvm-project' &
git clone https://github.com/llvm-mirror/llvm '/storage/nvme5/new_clones/LLVM/llvm' &
git clone https://github.com/Evian-Zhang/llvm-ir-tutorial '/storage/nvme5/new_clones/LLVM/llvm-ir-tutorial' &
git clone https://github.com/EnzymeAD/Enzyme '/storage/nvme5/new_clones/LLVM/Enzyme' &
git clone https://github.com/intel/llvm '/storage/nvme5/new_clones/LLVM/llvm' &
git clone https://github.com/hughperkins/coriander '/storage/nvme5/new_clones/LLVM/coriander' &
git clone https://github.com/bluesadi/Pluto '/storage/nvme5/new_clones/LLVM/Pluto' &
git clone https://github.com/JonathanSalwan/Tigress_protection '/storage/nvme5/new_clones/LLVM/Tigress_protection' &
git clone https://github.com/apple/swift-llvm '/storage/nvme5/new_clones/LLVM/swift-llvm' &
git clone https://github.com/google/clspv '/storage/nvme5/new_clones/LLVM/clspv' &
git clone https://github.com/f0rki/mapping-high-level-constructs-to-llvm-ir '/storage/nvme5/new_clones/LLVM/mapping-high-level-constructs-to-llvm-ir' &
git clone https://github.com/cdisselkoen/llvm-ir '/storage/nvme5/new_clones/LLVM/llvm-ir' &
git clone https://github.com/Markakd/DirtyCred '/storage/nvme5/new_clones/LLVM/DirtyCred' &
git clone https://github.com/llvm-hs/llvm-hs '/storage/nvme5/new_clones/LLVM/llvm-hs' &
git clone https://github.com/KhronosGroup/SPIRV-LLVM-Translator '/storage/nvme5/new_clones/LLVM/SPIRV-LLVM-Translator' &
git clone https://github.com/KomiMoe/Arkari '/storage/nvme5/new_clones/LLVM/Arkari' &
git clone https://github.com/llvm-mos/llvm-mos '/storage/nvme5/new_clones/LLVM/llvm-mos' &
git clone https://github.com/llvm/clangir '/storage/nvme5/new_clones/LLVM/clangir' &
git clone https://github.com/vellvm/vellvm '/storage/nvme5/new_clones/LLVM/vellvm' &
git clone https://github.com/GaloisInc/reopt '/storage/nvme5/new_clones/LLVM/reopt' &
git clone https://github.com/oneapi-src/SYCLomatic '/storage/nvme5/new_clones/LLVM/SYCLomatic' &
git clone https://github.com/smlsharp/smlsharp '/storage/nvme5/new_clones/LLVM/smlsharp' &
git clone https://github.com/ahmedbougacha/dagger '/storage/nvme5/new_clones/LLVM/dagger' &
git clone https://github.com/picolisp/pil21 '/storage/nvme5/new_clones/LLVM/pil21' &
git clone https://github.com/emscripten-core/emscripten-fastcomp '/storage/nvme5/new_clones/LLVM/emscripten-fastcomp' &
git clone https://github.com/leaningtech/cheerp-llvm '/storage/nvme5/new_clones/LLVM/cheerp-llvm' &
git clone https://github.com/microsoft/llvm '/storage/nvme5/new_clones/LLVM/llvm' &
git clone https://github.com/Lakr233/TreeNewBee '/storage/nvme5/new_clones/LLVM/TreeNewBee' &
git clone https://github.com/LLVMParty/TicklingVMProtect '/storage/nvme5/new_clones/LLVM/TicklingVMProtect' &
git clone https://github.com/grinisrit/noa '/storage/nvme5/new_clones/LLVM/noa' &
git clone https://github.com/wsmoses/Tapir-LLVM '/storage/nvme5/new_clones/LLVM/Tapir-LLVM' &
git clone https://github.com/evanmak/savior-source '/storage/nvme5/new_clones/LLVM/savior-source' &
git clone https://github.com/dubek/malc '/storage/nvme5/new_clones/LLVM/malc' &
git clone https://github.com/earl/llvm-mirror '/storage/nvme5/new_clones/LLVM/llvm-mirror' &
git clone https://github.com/praeclarum/Iril '/storage/nvme5/new_clones/LLVM/Iril' &
git clone https://github.com/OpenCilk/opencilk-project '/storage/nvme5/new_clones/LLVM/opencilk-project' &
git clone https://github.com/schism-dev/schism '/storage/nvme5/new_clones/LLVM/schism' &
git clone https://github.com/microsoft/checkedc-llvm '/storage/nvme5/new_clones/LLVM/checkedc-llvm' &
git clone https://github.com/IITH-Compilers/IR2Vec '/storage/nvme5/new_clones/LLVM/IR2Vec' &
git clone https://github.com/lifting-bits/fennec '/storage/nvme5/new_clones/LLVM/fennec' &
git clone https://github.com/Sparrow-lang/sparrow '/storage/nvme5/new_clones/LLVM/sparrow' &
git clone https://github.com/biometrics/likely '/storage/nvme5/new_clones/LLVM/likely' &
git clone https://github.com/zhuowei/MetalShaderTools '/storage/nvme5/new_clones/LLVM/MetalShaderTools' &
git clone https://github.com/preames/public-notes '/storage/nvme5/new_clones/LLVM/public-notes' &
git clone https://github.com/Chocopy-LLVM/chocopy-llvm '/storage/nvme5/new_clones/LLVM/chocopy-llvm' &
git clone https://github.com/M680x0/M680x0-llvm '/storage/nvme5/new_clones/LLVM/M680x0-llvm' &
git clone https://github.com/melvinzhang/scheme2llvm '/storage/nvme5/new_clones/LLVM/scheme2llvm' &
git clone https://github.com/llvm-hs/llvm-hs-pretty '/storage/nvme5/new_clones/LLVM/llvm-hs-pretty' &
git clone https://github.com/ISRC-CAS/c910-llvm '/storage/nvme5/new_clones/LLVM/c910-llvm' &
git clone https://github.com/GaloisInc/llvm-pretty-bc-parser '/storage/nvme5/new_clones/LLVM/llvm-pretty-bc-parser' &
git clone https://github.com/pacxx/pacxx-llvm '/storage/nvme5/new_clones/LLVM/pacxx-llvm' &
git clone https://github.com/penguin-wwy/replace_function_name '/storage/nvme5/new_clones/LLVM/replace_function_name' &
git clone https://github.com/pretzelhammer/brainfuck_compilers '/storage/nvme5/new_clones/LLVM/brainfuck_compilers' &
git clone https://github.com/SRI-CSL/llvm2smt '/storage/nvme5/new_clones/LLVM/llvm2smt' &
git clone https://github.com/sdasgup3/validating-binary-decompilation '/storage/nvme5/new_clones/LLVM/validating-binary-decompilation' &
git clone https://github.com/redstar/llvm-m88k '/storage/nvme5/new_clones/LLVM/llvm-m88k' &
git clone https://github.com/metalift/metalift '/storage/nvme5/new_clones/LLVM/metalift' &
git clone https://github.com/kframework/llvm-semantics '/storage/nvme5/new_clones/LLVM/llvm-semantics' &
git clone https://github.com/luizperes/llvm-to-snes '/storage/nvme5/new_clones/LLVM/llvm-to-snes' &
git clone https://github.com/capstone-engine/llvm-capstone '/storage/nvme5/new_clones/LLVM/llvm-capstone' &
git clone https://github.com/mfarhadi/CNNIOT '/storage/nvme5/new_clones/LLVM/CNNIOT' &
git clone https://github.com/davidlazar/llvm-semantics '/storage/nvme5/new_clones/LLVM/llvm-semantics' &
git clone https://github.com/processwarp/processwarp '/storage/nvme5/new_clones/LLVM/processwarp' &
git clone https://github.com/frankwang0818/AI_compiler_development_guide '/storage/nvme5/new_clones/LLVM/AI_compiler_development_guide' &
git clone https://github.com/UCLA-VAST/GNN-DSE '/storage/nvme5/new_clones/LLVM/GNN-DSE' &
git clone https://github.com/Bevinsky/llvm-gbz80 '/storage/nvme5/new_clones/LLVM/llvm-gbz80' &
git clone https://github.com/pgarba/Saturn_Results '/storage/nvme5/new_clones/LLVM/Saturn_Results' &
git clone https://github.com/trailofbits/KRFAnalysis '/storage/nvme5/new_clones/LLVM/KRFAnalysis' &
git clone https://github.com/alibaba/sionnx '/storage/nvme5/new_clones/LLVM/sionnx' &
git clone https://github.com/Virtual-Machine/ir-examples '/storage/nvme5/new_clones/LLVM/ir-examples' &
git clone https://github.com/HexHive/GLeeFuzz '/storage/nvme5/new_clones/LLVM/GLeeFuzz' &
git clone https://github.com/argonne-lcf/ATPESC_MachineLearning '/storage/nvme5/new_clones/LLVM/ATPESC_MachineLearning' &
git clone https://github.com/vortexgpgpu/NVPTX-SPIRV-Translator '/storage/nvme5/new_clones/LLVM/NVPTX-SPIRV-Translator' &
git clone https://github.com/bagel99/esl '/storage/nvme5/new_clones/LLVM/esl' &
git clone https://github.com/revec/llvm-revec '/storage/nvme5/new_clones/LLVM/llvm-revec' &
git clone https://github.com/pointer-authentication/parts-llvm '/storage/nvme5/new_clones/LLVM/parts-llvm' &
git clone https://github.com/tpunix/AC632Nuke '/storage/nvme5/new_clones/LLVM/AC632Nuke' &
git clone https://github.com/za233/AilProtect '/storage/nvme5/new_clones/LLVM/AilProtect' &
git clone https://github.com/kcc/fuzzing-with-sanitizers '/storage/nvme5/new_clones/LLVM/fuzzing-with-sanitizers' &
git clone https://github.com/liuzix/ticompile '/storage/nvme5/new_clones/LLVM/ticompile' &
git clone https://github.com/anhnguyen1618/Tiger-ocaml-llvm-compiler '/storage/nvme5/new_clones/LLVM/Tiger-ocaml-llvm-compiler' &
git clone https://github.com/lihebi/LLVMCallGraph '/storage/nvme5/new_clones/LLVM/LLVMCallGraph' &
git clone https://github.com/sammy17/vivado_hls_tutorial '/storage/nvme5/new_clones/LLVM/vivado_hls_tutorial' &
git clone https://github.com/David-Durst/embeddedHaskellAetherling '/storage/nvme5/new_clones/LLVM/embeddedHaskellAetherling' &
git clone https://github.com/Komorebi660/SysYF-Compiler '/storage/nvme5/new_clones/LLVM/SysYF-Compiler' &
git clone https://github.com/ephsec/llvm-forth '/storage/nvme5/new_clones/LLVM/llvm-forth' &
git clone https://github.com/syreal17/Cardinal '/storage/nvme5/new_clones/LLVM/Cardinal' &
git clone https://github.com/francisvm/j2-llvm '/storage/nvme5/new_clones/LLVM/j2-llvm' &
git clone https://github.com/sinistersnare/SinScheme '/storage/nvme5/new_clones/LLVM/SinScheme' &
git clone https://github.com/vandaltool/vandalir '/storage/nvme5/new_clones/LLVM/vandalir' &
git clone https://github.com/toshipiazza/Tigress_angr '/storage/nvme5/new_clones/LLVM/Tigress_angr' &
git clone https://github.com/umnsec/linux-bitcode '/storage/nvme5/new_clones/LLVM/linux-bitcode' &
git clone https://github.com/zhanghb55/parallel-and-distributed-computing-homework '/storage/nvme5/new_clones/LLVM/parallel-and-distributed-computing-homework' &
git clone https://github.com/Life4gal/adworld.xctf-REVERSE '/storage/nvme5/new_clones/LLVM/adworld.xctf-REVERSE' &
git clone https://github.com/archercreat/llvm_stuff '/storage/nvme5/new_clones/LLVM/llvm_stuff' &
git clone https://github.com/gthparch/NVPTX-SPIRV-Translator '/storage/nvme5/new_clones/LLVM/NVPTX-SPIRV-Translator' &
git clone https://github.com/flang-compiler/classic-flang-llvm-project '/storage/nvme5/new_clones/LLVM/classic-flang-llvm-project' &
git clone https://github.com/lsds/CubicleOS '/storage/nvme5/new_clones/LLVM/CubicleOS' &
git clone https://github.com/avast/llvm '/storage/nvme5/new_clones/LLVM/llvm' &
git clone https://github.com/shumaikunkun/Hanoi '/storage/nvme5/new_clones/LLVM/Hanoi' &
git clone https://github.com/cornell-zhang/datuner '/storage/nvme5/new_clones/LLVM/datuner' &
git clone https://github.com/benwilliamgraham/tree-sitter-llvm '/storage/nvme5/new_clones/LLVM/tree-sitter-llvm' &
git clone https://github.com/svv232/Kleenex '/storage/nvme5/new_clones/LLVM/Kleenex' &
git clone https://github.com/cop3402fall19/syllabus '/storage/nvme5/new_clones/LLVM/syllabus' &
git clone https://github.com/douggilliland/FPGA_Games '/storage/nvme5/new_clones/LLVM/FPGA_Games' &
git clone https://github.com/sx-aurora-dev/llvm-project '/storage/nvme5/new_clones/LLVM/llvm-project' &
git clone https://github.com/chipsalliance/f4pga-xc7-bram-patch '/storage/nvme5/new_clones/LLVM/f4pga-xc7-bram-patch' &
git clone https://github.com/pwwpche/CSE231-LLVM_Program_Analysis '/storage/nvme5/new_clones/LLVM/CSE231-LLVM_Program_Analysis' &
git clone https://github.com/PacktPublishing/Clean-Code-with-CSharp-Second-Edition '/storage/nvme5/new_clones/LLVM/Clean-Code-with-CSharp-Second-Edition' &
git clone https://github.com/tattn/llvm-boehmgc-sample '/storage/nvme5/new_clones/LLVM/llvm-boehmgc-sample' &
git clone https://github.com/ithemal/DiffTune '/storage/nvme5/new_clones/LLVM/DiffTune' &
git clone https://github.com/824728350/Clara '/storage/nvme5/new_clones/LLVM/Clara' &
git clone https://github.com/wuzhanglin/llvm-pass-examples '/storage/nvme5/new_clones/LLVM/llvm-pass-examples' &
git clone https://github.com/yeqingyan/LLVM-obf '/storage/nvme5/new_clones/LLVM/LLVM-obf' &
git clone https://github.com/bollu/lz '/storage/nvme5/new_clones/LLVM/lz' &
git clone https://github.com/upenn-acg/gpuDranoDynamicAnalysis '/storage/nvme5/new_clones/LLVM/gpuDranoDynamicAnalysis' &
git clone https://github.com/qir-alliance/nwqsim '/storage/nvme5/new_clones/LLVM/nwqsim' &
git clone https://github.com/nimrodpar/Obfvious '/storage/nvme5/new_clones/LLVM/Obfvious' &
git clone https://github.com/georgesittas/minijava-compiler '/storage/nvme5/new_clones/LLVM/minijava-compiler' &
git clone https://github.com/nullhook/ollvm-14.x '/storage/nvme5/new_clones/LLVM/ollvm-14.x' &
git clone https://github.com/oneapi-src/SYCLomatic-test '/storage/nvme5/new_clones/LLVM/SYCLomatic-test' &
git clone https://github.com/rogerioag/llvm-gencode-samples '/storage/nvme5/new_clones/LLVM/llvm-gencode-samples' &
git clone https://github.com/heterosys/mlir-vitis '/storage/nvme5/new_clones/LLVM/mlir-vitis' &
git clone https://github.com/Azurewyl/llvm_upt '/storage/nvme5/new_clones/LLVM/llvm_upt' &
git clone https://github.com/connorjan/llvm-cjg '/storage/nvme5/new_clones/LLVM/llvm-cjg' &
git clone https://github.com/rssys/shard '/storage/nvme5/new_clones/LLVM/shard' &
git clone https://github.com/CTSRD-CHERI/llvm '/storage/nvme5/new_clones/LLVM/llvm' &
git clone https://github.com/kateinoigakukun/llvm-next-function-merging '/storage/nvme5/new_clones/LLVM/llvm-next-function-merging' &
git clone https://github.com/nebulasio/nvm '/storage/nvme5/new_clones/LLVM/nvm' &
git clone https://github.com/shadowmydx/Simulee '/storage/nvme5/new_clones/LLVM/Simulee' &
git clone https://github.com/seahorn/seahorn-tutorial '/storage/nvme5/new_clones/LLVM/seahorn-tutorial' &
git clone https://github.com/UniHD-CEG/cuda-memtrace '/storage/nvme5/new_clones/LLVM/cuda-memtrace' &
git clone https://github.com/WOLVS/HOG_ZYNQ '/storage/nvme5/new_clones/LLVM/HOG_ZYNQ' &
git clone https://github.com/divanburger/fragbyte '/storage/nvme5/new_clones/LLVM/fragbyte' &
git clone https://github.com/akothen/Hydride '/storage/nvme5/new_clones/LLVM/Hydride' &
git clone https://github.com/tuxfan/ska '/storage/nvme5/new_clones/LLVM/ska' &
git clone https://github.com/wsmoses/Enzyme-GPU-Tests '/storage/nvme5/new_clones/LLVM/Enzyme-GPU-Tests' &
git clone https://github.com/LuoRongLuoRong/llvm_clang_instrument_example '/storage/nvme5/new_clones/LLVM/llvm_clang_instrument_example' &
git clone https://github.com/spiralman/llisp '/storage/nvme5/new_clones/LLVM/llisp' &
git clone https://github.com/lewis-revill/agc-llvm '/storage/nvme5/new_clones/LLVM/agc-llvm' &
git clone https://github.com/nsumner/callgraph-profiler-template '/storage/nvme5/new_clones/LLVM/callgraph-profiler-template' &
git clone https://github.com/cs131-chocopy/cs131-chocopy4 '/storage/nvme5/new_clones/LLVM/cs131-chocopy4' &
git clone https://github.com/PolyJIT/polli '/storage/nvme5/new_clones/LLVM/polli' &
git clone https://github.com/cachelot/llvm_playground '/storage/nvme5/new_clones/LLVM/llvm_playground' &
git clone https://github.com/renan061/aria '/storage/nvme5/new_clones/LLVM/aria' &
git clone https://github.com/baziotis/minijava-testsuite '/storage/nvme5/new_clones/LLVM/minijava-testsuite' &
git clone https://github.com/anonymous8923/occlum '/storage/nvme5/new_clones/LLVM/occlum' &
git clone https://github.com/xathrya/slides '/storage/nvme5/new_clones/LLVM/slides' &
git clone https://github.com/AQuickBlackFox/amdgpu-code '/storage/nvme5/new_clones/LLVM/amdgpu-code' &
git clone https://github.com/qir-alliance/qir-book '/storage/nvme5/new_clones/LLVM/qir-book' &
git clone https://github.com/csMOOC/CSE231 '/storage/nvme5/new_clones/LLVM/CSE231' &
git clone https://github.com/Lebronmydx/Simulee '/storage/nvme5/new_clones/LLVM/Simulee' &
git clone https://github.com/tum-i4/sip-oblivious-hashing '/storage/nvme5/new_clones/LLVM/sip-oblivious-hashing' &
git clone https://github.com/pine/wasm-sample '/storage/nvme5/new_clones/LLVM/wasm-sample' &
git clone https://github.com/0xDouze/abstract_vuln_finder '/storage/nvme5/new_clones/LLVM/abstract_vuln_finder' &
git clone https://github.com/canesche/Mirai-Family '/storage/nvme5/new_clones/LLVM/Mirai-Family' &
git clone https://github.com/colinyoyo26/mlir-standalone-toy '/storage/nvme5/new_clones/LLVM/mlir-standalone-toy' &
git clone https://github.com/d3xter-lab/llvm-obfuscator '/storage/nvme5/new_clones/LLVM/llvm-obfuscator' &
git clone https://github.com/kix6lj/HLS-lab1 '/storage/nvme5/new_clones/LLVM/HLS-lab1' &
git clone https://github.com/cyruliu/darksea '/storage/nvme5/new_clones/LLVM/darksea' &
git clone https://github.com/gavz/TicklingVMProtect '/storage/nvme5/new_clones/LLVM/TicklingVMProtect' &
git clone https://github.com/CQCL/pytket-qir '/storage/nvme5/new_clones/LLVM/pytket-qir' &
git clone https://github.com/colejcummins/llvm-syntax-highlighting '/storage/nvme5/new_clones/LLVM/llvm-syntax-highlighting' &
git clone https://github.com/SNSystems/llvm-prepo '/storage/nvme5/new_clones/LLVM/llvm-prepo' &
git clone https://github.com/0----0/Terra-3d-Experiments '/storage/nvme5/new_clones/LLVM/Terra-3d-Experiments' &
git clone https://github.com/gandhi56-zz/betterIR '/storage/nvme5/new_clones/LLVM/betterIR' &
git clone https://github.com/embecosm/aap-llvm '/storage/nvme5/new_clones/LLVM/aap-llvm' &
git clone https://github.com/na2co3-ftw/llvm-2003f '/storage/nvme5/new_clones/LLVM/llvm-2003f' &
git clone https://github.com/MQTTactic/MQTTactic '/storage/nvme5/new_clones/LLVM/MQTTactic' &
git clone https://github.com/auxon/bonsai '/storage/nvme5/new_clones/LLVM/bonsai' &
git clone https://github.com/maybegreat48/SC-CL '/storage/nvme5/new_clones/LLVM/SC-CL' &
git clone https://github.com/dberlin/llvm-gvn-rewrite '/storage/nvme5/new_clones/LLVM/llvm-gvn-rewrite' &
git clone https://github.com/coffezhou/OverCG '/storage/nvme5/new_clones/LLVM/OverCG' &
git clone https://github.com/TrustworthySystemLab/LostInTranslation '/storage/nvme5/new_clones/LLVM/LostInTranslation' &
git clone https://github.com/Ariyn/cloud-computer '/storage/nvme5/new_clones/LLVM/cloud-computer' &
git clone https://github.com/diegovalverde/funk '/storage/nvme5/new_clones/LLVM/funk' &
