#!/bin/bash

git clone https://github.com/rojo-rbx/rojo '/storage/nvme5/new_clones/Luau/rojo' &
git clone https://github.com/dphfox/Fusion '/storage/nvme5/new_clones/Luau/Fusion' &
git clone https://github.com/Sleitnick/Knit '/storage/nvme5/new_clones/Luau/Knit' &
git clone https://github.com/Epix-Incorporated/Adonis '/storage/nvme5/new_clones/Luau/Adonis' &
git clone https://github.com/JohnnyMorganz/luau-lsp '/storage/nvme5/new_clones/Luau/luau-lsp' &
git clone https://github.com/Sleitnick/RbxUtil '/storage/nvme5/new_clones/Luau/RbxUtil' &
git clone https://github.com/SirMallard/Iris '/storage/nvme5/new_clones/Luau/Iris' &
git clone https://github.com/howmanysmall/Janitor '/storage/nvme5/new_clones/Luau/Janitor' &
git clone https://github.com/flipbook-labs/flipbook '/storage/nvme5/new_clones/Luau/flipbook' &
git clone https://github.com/MaximumADHD/sm64-roblox '/storage/nvme5/new_clones/Luau/sm64-roblox' &
git clone https://github.com/TheNexusAvenger/Nexus-VR-Character-Model '/storage/nvme5/new_clones/Luau/Nexus-VR-Character-Model' &
git clone https://github.com/ffrostfall/BridgeNet2 '/storage/nvme5/new_clones/Luau/BridgeNet2' &
git clone https://github.com/nezuo/lapis '/storage/nvme5/new_clones/Luau/lapis' &
git clone https://github.com/sircfenner/StudioComponents '/storage/nvme5/new_clones/Luau/StudioComponents' &
git clone https://github.com/centau/ecr '/storage/nvme5/new_clones/Luau/ecr' &
git clone https://github.com/latte-soft/maui '/storage/nvme5/new_clones/Luau/maui' &
git clone https://github.com/tacheometry/Rostar '/storage/nvme5/new_clones/Luau/Rostar' &
git clone https://github.com/Epix-Incorporated/Adonis-Plugins '/storage/nvme5/new_clones/Luau/Adonis-Plugins' &
git clone https://github.com/nightcycle/synthetic '/storage/nvme5/new_clones/Luau/synthetic' &
git clone https://github.com/Blupo/ColorPane '/storage/nvme5/new_clones/Luau/ColorPane' &
git clone https://github.com/TheNexusAvenger/Nexus-Admin '/storage/nvme5/new_clones/Luau/Nexus-Admin' &
git clone https://github.com/TheNexusAvenger/Nexus-VR-Core '/storage/nvme5/new_clones/Luau/Nexus-VR-Core' &
git clone https://github.com/fewkz/studio-wally '/storage/nvme5/new_clones/Luau/studio-wally' &
git clone https://github.com/MaximumADHD/cage-mesh-deformer '/storage/nvme5/new_clones/Luau/cage-mesh-deformer' &
git clone https://github.com/matter-ecs/matter-types '/storage/nvme5/new_clones/Luau/matter-types' &
git clone https://github.com/devSparkle/Overture '/storage/nvme5/new_clones/Luau/Overture' &
git clone https://github.com/Infinite-Store/Infinite-Store '/storage/nvme5/new_clones/Luau/Infinite-Store' &
git clone https://github.com/typedwaves/Rongo '/storage/nvme5/new_clones/Luau/Rongo' &
git clone https://github.com/TheNexusAvenger/Nexus-Data-Store '/storage/nvme5/new_clones/Luau/Nexus-Data-Store' &
git clone https://github.com/Redon-Tech/Emergency-Vehicle-Creator '/storage/nvme5/new_clones/Luau/Emergency-Vehicle-Creator' &
git clone https://github.com/TheNexusAvenger/Module3D '/storage/nvme5/new_clones/Luau/Module3D' &
git clone https://github.com/EncodedVenom/RemoteComponent '/storage/nvme5/new_clones/Luau/RemoteComponent' &
git clone https://github.com/TheNexusAvenger/Nexus-Instance '/storage/nvme5/new_clones/Luau/Nexus-Instance' &
git clone https://github.com/dig1t/red '/storage/nvme5/new_clones/Luau/red' &
git clone https://github.com/nezuo/data-store-service-mock '/storage/nvme5/new_clones/Luau/data-store-service-mock' &
git clone https://github.com/IITPP-Roblox/LocalAudio-Subtitles '/storage/nvme5/new_clones/Luau/LocalAudio-Subtitles' &
git clone https://github.com/ImAvafe/Moonlets '/storage/nvme5/new_clones/Luau/Moonlets' &
