#!/bin/bash

git clone https://github.com/Museum-of-Art-and-Digital-Entertainment/habitat '/storage/nvme5/new_clones/M/habitat' &
git clone https://github.com/InfinitApps/InfColorPicker '/storage/nvme5/new_clones/M/InfColorPicker' &
git clone https://github.com/aligrudi/neatroff_make '/storage/nvme5/new_clones/M/neatroff_make' &
git clone https://github.com/RoboDesignLab/HOPPY-Project '/storage/nvme5/new_clones/M/HOPPY-Project' &
git clone https://github.com/robtweed/node-mdb '/storage/nvme5/new_clones/M/node-mdb' &
git clone https://github.com/programarivm/mumps-examples '/storage/nvme5/new_clones/M/mumps-examples' &
git clone https://github.com/WorldVistA/VistA-M '/storage/nvme5/new_clones/M/VistA-M' &
git clone https://github.com/ansilove/AnsiLove.framework '/storage/nvme5/new_clones/M/AnsiLove.framework' &
git clone https://github.com/iphysresearch/CQT_toolbox_python '/storage/nvme5/new_clones/M/CQT_toolbox_python' &
git clone https://github.com/kangxue/How-do-I-render-point-clouds '/storage/nvme5/new_clones/M/How-do-I-render-point-clouds' &
git clone https://github.com/robtweed/EWD '/storage/nvme5/new_clones/M/EWD' &
git clone https://github.com/colour-science/MunsellAndKubelkaMunkToolbox '/storage/nvme5/new_clones/M/MunsellAndKubelkaMunkToolbox' &
git clone https://github.com/m-a-y-a-n-k/Weather-Prediction-Using-Neural-Networks '/storage/nvme5/new_clones/M/Weather-Prediction-Using-Neural-Networks' &
git clone https://github.com/shabiel/M-Web-Server '/storage/nvme5/new_clones/M/M-Web-Server' &
git clone https://github.com/thevinchi/firebase-titanium '/storage/nvme5/new_clones/M/firebase-titanium' &
git clone https://github.com/FloppySoft/EOS-M100-Clean-HDMI '/storage/nvme5/new_clones/M/EOS-M100-Clean-HDMI' &
git clone https://github.com/etalab/calculette-impots-m-source-code '/storage/nvme5/new_clones/M/calculette-impots-m-source-code' &
git clone https://github.com/ermin-sakic/second-order-dpa '/storage/nvme5/new_clones/M/second-order-dpa' &
git clone https://github.com/jishanshaikh4/image-recognition-matlab '/storage/nvme5/new_clones/M/image-recognition-matlab' &
git clone https://github.com/askfind/strannik '/storage/nvme5/new_clones/M/strannik' &
git clone https://github.com/layumi/matlab_email_demo '/storage/nvme5/new_clones/M/matlab_email_demo' &
git clone https://github.com/chrisemunt/mgsql '/storage/nvme5/new_clones/M/mgsql' &
git clone https://github.com/akshaybabloo/Emotiv-Matlab '/storage/nvme5/new_clones/M/Emotiv-Matlab' &
git clone https://github.com/skyeong/Lectures_on_Neuroimaging '/storage/nvme5/new_clones/M/Lectures_on_Neuroimaging' &
git clone https://github.com/SAP-samples/data-warehouse-cloud-connectors '/storage/nvme5/new_clones/M/data-warehouse-cloud-connectors' &
git clone https://github.com/JakubOsmic/WTD-Library '/storage/nvme5/new_clones/M/WTD-Library' &
git clone https://github.com/chenpengseu/RIS-ADMM '/storage/nvme5/new_clones/M/RIS-ADMM' &
git clone https://github.com/zick/Oberon2Lisp '/storage/nvme5/new_clones/M/Oberon2Lisp' &
git clone https://github.com/shabiel/VPE '/storage/nvme5/new_clones/M/VPE' &
git clone https://github.com/hfiennes/arcbbs '/storage/nvme5/new_clones/M/arcbbs' &
git clone https://github.com/WorldVistA/SKIDS '/storage/nvme5/new_clones/M/SKIDS' &
git clone https://github.com/carandraug/histthresh '/storage/nvme5/new_clones/M/histthresh' &
git clone https://github.com/fewnew/art74-fall2018 '/storage/nvme5/new_clones/M/art74-fall2018' &
git clone https://github.com/robtweed/rest-secure '/storage/nvme5/new_clones/M/rest-secure' &
git clone https://github.com/GayatriBehara/-Face-and-Facial-Expression-detection-based-Authenticated-ZigBee-Based-Robo '/storage/nvme5/new_clones/M/-Face-and-Facial-Expression-detection-based-Authenticated-ZigBee-Based-Robo' &
git clone https://github.com/corani/oberon-stdlib '/storage/nvme5/new_clones/M/oberon-stdlib' &
git clone https://github.com/ovidiualexandru/DOAToolbox '/storage/nvme5/new_clones/M/DOAToolbox' &
git clone https://github.com/nzikos/L-SLAM '/storage/nvme5/new_clones/M/L-SLAM' &
git clone https://github.com/MargeritPierre/ESPRIT '/storage/nvme5/new_clones/M/ESPRIT' &
git clone https://github.com/haskell-implementations/hbc '/storage/nvme5/new_clones/M/hbc' &
git clone https://github.com/eccarson/ir3 '/storage/nvme5/new_clones/M/ir3' &
git clone https://github.com/ParaxialTechnologies/SAMI-VAPALS-ELCAP '/storage/nvme5/new_clones/M/SAMI-VAPALS-ELCAP' &
git clone https://github.com/edgarcosta/hilbertmodularforms '/storage/nvme5/new_clones/M/hilbertmodularforms' &
git clone https://github.com/Beingink/Load-flow-analysis-in-Power-systems '/storage/nvme5/new_clones/M/Load-flow-analysis-in-Power-systems' &
git clone https://github.com/chouj/MoveEddiesIntoAtlantic '/storage/nvme5/new_clones/M/MoveEddiesIntoAtlantic' &
git clone https://github.com/Hulkido/Fisheriris_MATLAB '/storage/nvme5/new_clones/M/Fisheriris_MATLAB' &
git clone https://github.com/dezanche/MRI_distortion_phantom '/storage/nvme5/new_clones/M/MRI_distortion_phantom' &
git clone https://github.com/GorrieXIV/Magma '/storage/nvme5/new_clones/M/Magma' &
git clone https://github.com/Ensembl/plant_tools '/storage/nvme5/new_clones/M/plant_tools' &
git clone https://github.com/Tsingzao/Semi_Supervised_Multi_Label_Learning '/storage/nvme5/new_clones/M/Semi_Supervised_Multi_Label_Learning' &
git clone https://github.com/borochris/CLinUiP '/storage/nvme5/new_clones/M/CLinUiP' &
git clone https://github.com/whitten/m-adventure '/storage/nvme5/new_clones/M/m-adventure' &
git clone https://github.com/qingyang1014/BeidouProessing '/storage/nvme5/new_clones/M/BeidouProessing' &
git clone https://github.com/robmcrosby/Cuda-Rasterizer '/storage/nvme5/new_clones/M/Cuda-Rasterizer' &
git clone https://github.com/JonHoy/Matlab_DSLR_Camera_Control '/storage/nvme5/new_clones/M/Matlab_DSLR_Camera_Control' &
git clone https://github.com/holybin/facerec_based_on_hog '/storage/nvme5/new_clones/M/facerec_based_on_hog' &
git clone https://github.com/rajesh3699/Snake-locomotion-analysis. '/storage/nvme5/new_clones/M/Snake-locomotion-analysis.' &
git clone https://github.com/oslocyclotronlab/oslo-method-software '/storage/nvme5/new_clones/M/oslo-method-software' &
git clone https://github.com/AbreoJ/Tumor-Growth-Simulation '/storage/nvme5/new_clones/M/Tumor-Growth-Simulation' &
git clone https://github.com/DuncanMC/test '/storage/nvme5/new_clones/M/test' &
git clone https://github.com/Maheshchakkarwar/image_fusion '/storage/nvme5/new_clones/M/image_fusion' &
git clone https://github.com/cloudygoose/latex-example '/storage/nvme5/new_clones/M/latex-example' &
git clone https://github.com/robtweed/mgweb-server '/storage/nvme5/new_clones/M/mgweb-server' &
git clone https://github.com/ssalevan/habiclient '/storage/nvme5/new_clones/M/habiclient' &
git clone https://github.com/jcchin/TTECTrA_dev '/storage/nvme5/new_clones/M/TTECTrA_dev' &
git clone https://github.com/deerzq/Unsupervised-multi-metric-fusion-for-FR-IQA '/storage/nvme5/new_clones/M/Unsupervised-multi-metric-fusion-for-FR-IQA' &
git clone https://github.com/YottaDB/YDBTest '/storage/nvme5/new_clones/M/YDBTest' &
git clone https://github.com/toshiakit/Analyzing-Fitness-Data-from-Wearable-Devices-in-MATLAB '/storage/nvme5/new_clones/M/Analyzing-Fitness-Data-from-Wearable-Devices-in-MATLAB' &
git clone https://github.com/GrauLab/SDCM '/storage/nvme5/new_clones/M/SDCM' &
git clone https://github.com/adamlukomski/iva '/storage/nvme5/new_clones/M/iva' &
git clone https://github.com/ChristopherEdwards/FOIA-RPMS '/storage/nvme5/new_clones/M/FOIA-RPMS' &
git clone https://github.com/shabiel/fis-gtm-plugins '/storage/nvme5/new_clones/M/fis-gtm-plugins' &
