#!/bin/bash

git clone https://github.com/codecrafters-io/build-your-own-x '/storage/nvme5/new_clones/Markdown/build-your-own-x' &
git clone https://github.com/labuladong/fucking-algorithm '/storage/nvme5/new_clones/Markdown/fucking-algorithm' &
git clone https://github.com/tldr-pages/tldr '/storage/nvme5/new_clones/Markdown/tldr' &
git clone https://github.com/jaywcjlove/linux-command '/storage/nvme5/new_clones/Markdown/linux-command' &
git clone https://github.com/OAI/OpenAPI-Specification '/storage/nvme5/new_clones/Markdown/OpenAPI-Specification' &
git clone https://github.com/swiftlang/swift-evolution '/storage/nvme5/new_clones/Markdown/swift-evolution' &
git clone https://github.com/ellisonleao/magictools '/storage/nvme5/new_clones/Markdown/magictools' &
git clone https://github.com/adambard/learnxinyminutes-docs '/storage/nvme5/new_clones/Markdown/learnxinyminutes-docs' &
git clone https://github.com/alexandresanlim/Badges4-README.md-Profile '/storage/nvme5/new_clones/Markdown/Badges4-README.md-Profile' &
git clone https://github.com/MicrosoftDocs/azure-docs '/storage/nvme5/new_clones/Markdown/azure-docs' &
git clone https://github.com/mdn/content '/storage/nvme5/new_clones/Markdown/content' &
git clone https://github.com/JoseDeFreitas/awesome-youtubers '/storage/nvme5/new_clones/Markdown/awesome-youtubers' &
git clone https://github.com/rust-lang/rfcs '/storage/nvme5/new_clones/Markdown/rfcs' &
git clone https://github.com/microsoft/vscode-docs '/storage/nvme5/new_clones/Markdown/vscode-docs' &
git clone https://github.com/ethereum/ethereum-org-website '/storage/nvme5/new_clones/Markdown/ethereum-org-website' &
git clone https://github.com/Schweinepriester/github-profile-achievements '/storage/nvme5/new_clones/Markdown/github-profile-achievements' &
git clone https://github.com/Evavic44/portfolio-ideas '/storage/nvme5/new_clones/Markdown/portfolio-ideas' &
git clone https://github.com/walkccc/CLRS '/storage/nvme5/new_clones/Markdown/CLRS' &
git clone https://github.com/KaiserY/trpl-zh-cn '/storage/nvme5/new_clones/Markdown/trpl-zh-cn' &
git clone https://github.com/jaywcjlove/handbook '/storage/nvme5/new_clones/Markdown/handbook' &
git clone https://github.com/docker/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/Kotlin/KEEP '/storage/nvme5/new_clones/Markdown/KEEP' &
git clone https://github.com/Bogdanp/awesome-advent-of-code '/storage/nvme5/new_clones/Markdown/awesome-advent-of-code' &
git clone https://github.com/privacyguides/privacyguides.org '/storage/nvme5/new_clones/Markdown/privacyguides.org' &
git clone https://github.com/coderjojo/creative-profile-readme '/storage/nvme5/new_clones/Markdown/creative-profile-readme' &
git clone https://github.com/airbnb/swift '/storage/nvme5/new_clones/Markdown/swift' &
git clone https://github.com/lightning/bolts '/storage/nvme5/new_clones/Markdown/bolts' &
git clone https://github.com/drknzz/GitHub-Achievements '/storage/nvme5/new_clones/Markdown/GitHub-Achievements' &
git clone https://github.com/MicrosoftDocs/architecture-center '/storage/nvme5/new_clones/Markdown/architecture-center' &
git clone https://github.com/swiftlang/swift-book '/storage/nvme5/new_clones/Markdown/swift-book' &
git clone https://github.com/Caerind/AwesomeCppGameDev '/storage/nvme5/new_clones/Markdown/AwesomeCppGameDev' &
git clone https://github.com/mdn/translated-content '/storage/nvme5/new_clones/Markdown/translated-content' &
git clone https://github.com/KaiserY/rust-book-chinese '/storage/nvme5/new_clones/Markdown/rust-book-chinese' &
git clone https://github.com/SAP/styleguides '/storage/nvme5/new_clones/Markdown/styleguides' &
git clone https://github.com/raphamorim/awesome-canvas '/storage/nvme5/new_clones/Markdown/awesome-canvas' &
git clone https://github.com/adr/madr '/storage/nvme5/new_clones/Markdown/madr' &
git clone https://github.com/satoshilabs/slips '/storage/nvme5/new_clones/Markdown/slips' &
git clone https://github.com/wangyongjie-ntu/Awesome-explainable-AI '/storage/nvme5/new_clones/Markdown/Awesome-explainable-AI' &
git clone https://github.com/frankiefab100/Blockchain-Development-Resources '/storage/nvme5/new_clones/Markdown/Blockchain-Development-Resources' &
git clone https://github.com/nsriram/lambda-the-terraform-way '/storage/nvme5/new_clones/Markdown/lambda-the-terraform-way' &
git clone https://github.com/raspibolt/raspibolt '/storage/nvme5/new_clones/Markdown/raspibolt' &
git clone https://github.com/JetBrains/intellij-sdk-docs '/storage/nvme5/new_clones/Markdown/intellij-sdk-docs' &
git clone https://github.com/analysis-tools-dev/dynamic-analysis '/storage/nvme5/new_clones/Markdown/dynamic-analysis' &
git clone https://github.com/project-trans/MtF-wiki '/storage/nvme5/new_clones/Markdown/MtF-wiki' &
git clone https://github.com/antfu/antfu.me '/storage/nvme5/new_clones/Markdown/antfu.me' &
git clone https://github.com/ChessMax/awesome-programming-languages '/storage/nvme5/new_clones/Markdown/awesome-programming-languages' &
git clone https://github.com/badges/awesome-badges '/storage/nvme5/new_clones/Markdown/awesome-badges' &
git clone https://github.com/dreamportdev/Osdev-Notes '/storage/nvme5/new_clones/Markdown/Osdev-Notes' &
git clone https://github.com/gbdev/pandocs '/storage/nvme5/new_clones/Markdown/pandocs' &
git clone https://github.com/NixOS/rfcs '/storage/nvme5/new_clones/Markdown/rfcs' &
git clone https://github.com/Gabriella439/nixos-in-production '/storage/nvme5/new_clones/Markdown/nixos-in-production' &
git clone https://github.com/ppy/osu-wiki '/storage/nvme5/new_clones/Markdown/osu-wiki' &
git clone https://github.com/nolebase/nolebase '/storage/nvme5/new_clones/Markdown/nolebase' &
git clone https://github.com/guilyx/guilyx '/storage/nvme5/new_clones/Markdown/guilyx' &
git clone https://github.com/zhaoshenzhai/mathwiki '/storage/nvme5/new_clones/Markdown/mathwiki' &
git clone https://github.com/jaywcjlove/git-tips '/storage/nvme5/new_clones/Markdown/git-tips' &
git clone https://github.com/itsnebulalol/ios15-tweaks '/storage/nvme5/new_clones/Markdown/ios15-tweaks' &
git clone https://github.com/trinib/trinib '/storage/nvme5/new_clones/Markdown/trinib' &
git clone https://github.com/sobolevbel/jdg '/storage/nvme5/new_clones/Markdown/jdg' &
git clone https://github.com/OpenXiangShan/XiangShan-doc '/storage/nvme5/new_clones/Markdown/XiangShan-doc' &
git clone https://github.com/mthri/dfp-persian '/storage/nvme5/new_clones/Markdown/dfp-persian' &
git clone https://github.com/stn1slv/awesome-integration '/storage/nvme5/new_clones/Markdown/awesome-integration' &
git clone https://github.com/adr/adr.github.io '/storage/nvme5/new_clones/Markdown/adrhub.io' &
git clone https://github.com/iflytek/HFL-Anthology '/storage/nvme5/new_clones/Markdown/HFL-Anthology' &
git clone https://github.com/Chaoses-Ib/DirectoryOpus '/storage/nvme5/new_clones/Markdown/DirectoryOpus' &
git clone https://github.com/ponylang/pony-tutorial '/storage/nvme5/new_clones/Markdown/pony-tutorial' &
git clone https://github.com/hetzneronline/community-content '/storage/nvme5/new_clones/Markdown/community-content' &
git clone https://github.com/FastGitORG/document '/storage/nvme5/new_clones/Markdown/document' &
git clone https://github.com/bitcoinops/bitcoinops.github.io '/storage/nvme5/new_clones/Markdown/bitcoinopshub.io' &
git clone https://github.com/mxmnk/mxmnk '/storage/nvme5/new_clones/Markdown/mxmnk' &
git clone https://github.com/yfosp/start-here '/storage/nvme5/new_clones/Markdown/start-here' &
git clone https://github.com/TonyCrane/note '/storage/nvme5/new_clones/Markdown/note' &
git clone https://github.com/TuringLang/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/saveweb/review-2022 '/storage/nvme5/new_clones/Markdown/review-2022' &
git clone https://github.com/ftg-iran/dfa-persian '/storage/nvme5/new_clones/Markdown/dfa-persian' &
git clone https://github.com/selwynpolit/d9book '/storage/nvme5/new_clones/Markdown/d9book' &
git clone https://github.com/sublimetext-io/docs.sublimetext.io '/storage/nvme5/new_clones/Markdown/docs.sublimetext.io' &
git clone https://github.com/nsriram/lambda-the-cli-way '/storage/nvme5/new_clones/Markdown/lambda-the-cli-way' &
git clone https://github.com/eleev/soft-skills '/storage/nvme5/new_clones/Markdown/soft-skills' &
git clone https://github.com/input-output-hk/adrestia '/storage/nvme5/new_clones/Markdown/adrestia' &
git clone https://github.com/rubyaustralia/roro '/storage/nvme5/new_clones/Markdown/roro' &
git clone https://github.com/bedtimenews/bedtimenews-archive-contents '/storage/nvme5/new_clones/Markdown/bedtimenews-archive-contents' &
git clone https://github.com/MicrosoftDocs/azure-dev-docs '/storage/nvme5/new_clones/Markdown/azure-dev-docs' &
git clone https://github.com/NVIDIA/cloud-native-stack '/storage/nvme5/new_clones/Markdown/cloud-native-stack' &
git clone https://github.com/mendix/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/Irrational-Encoding-Wizardry/guide.encode.moe '/storage/nvme5/new_clones/Markdown/guide.encode.moe' &
git clone https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects '/storage/nvme5/new_clones/Markdown/Awesome-Illustrations-4Projects' &
git clone https://github.com/OAI/learn.openapis.org '/storage/nvme5/new_clones/Markdown/learn.openapis.org' &
git clone https://github.com/IsshikiHugh/notebook '/storage/nvme5/new_clones/Markdown/notebook' &
git clone https://github.com/highlightink/sqlmap-wiki-zhcn '/storage/nvme5/new_clones/Markdown/sqlmap-wiki-zhcn' &
git clone https://github.com/Alhadis/OSC8-Adoption '/storage/nvme5/new_clones/Markdown/OSC8-Adoption' &
git clone https://github.com/Clearloveyuan/awesome-active-learning-New '/storage/nvme5/new_clones/Markdown/awesome-active-learning-New' &
git clone https://github.com/cheesits456/cheesits456 '/storage/nvme5/new_clones/Markdown/cheesits456' &
git clone https://github.com/rust-lang-de/rustbook-de '/storage/nvme5/new_clones/Markdown/rustbook-de' &
git clone https://github.com/bmpi-dev/bmpi.dev '/storage/nvme5/new_clones/Markdown/bmpi.dev' &
git clone https://github.com/yoshi389111/kinokobooks '/storage/nvme5/new_clones/Markdown/kinokobooks' &
git clone https://github.com/HDVinnie/TrackerHub '/storage/nvme5/new_clones/Markdown/TrackerHub' &
git clone https://github.com/practicalli/clojure '/storage/nvme5/new_clones/Markdown/clojure' &
git clone https://github.com/bitcoinops/scaling-book '/storage/nvme5/new_clones/Markdown/scaling-book' &
git clone https://github.com/doongz/notes '/storage/nvme5/new_clones/Markdown/notes' &
git clone https://github.com/nats-io/nats-site '/storage/nvme5/new_clones/Markdown/nats-site' &
git clone https://github.com/openlawteam/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/docsforadobe/after-effects-scripting-guide '/storage/nvme5/new_clones/Markdown/after-effects-scripting-guide' &
git clone https://github.com/ponylang/ponylang-website '/storage/nvme5/new_clones/Markdown/ponylang-website' &
git clone https://github.com/TonyCrane/slide-template '/storage/nvme5/new_clones/Markdown/slide-template' &
git clone https://github.com/srid/neuron-template '/storage/nvme5/new_clones/Markdown/neuron-template' &
git clone https://github.com/ChristoWolf/awesome-testing-blogs '/storage/nvme5/new_clones/Markdown/awesome-testing-blogs' &
git clone https://github.com/kinnay/Nintendo-File-Formats '/storage/nvme5/new_clones/Markdown/Nintendo-File-Formats' &
git clone https://github.com/0xcaffebabe/note '/storage/nvme5/new_clones/Markdown/note' &
git clone https://github.com/minibolt-guide/minibolt '/storage/nvme5/new_clones/Markdown/minibolt' &
git clone https://github.com/magestacks/house-note '/storage/nvme5/new_clones/Markdown/house-note' &
git clone https://github.com/Lruihao/hugo-blog '/storage/nvme5/new_clones/Markdown/hugo-blog' &
git clone https://github.com/gledos/ggame '/storage/nvme5/new_clones/Markdown/ggame' &
git clone https://github.com/ustc-zzzz/HOCON-CN-Translation '/storage/nvme5/new_clones/Markdown/HOCON-CN-Translation' &
git clone https://github.com/hugo-fixit/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/ponylang/pony-patterns '/storage/nvme5/new_clones/Markdown/pony-patterns' &
git clone https://github.com/HyperionCSharp/EpicGamesAPIDocs '/storage/nvme5/new_clones/Markdown/EpicGamesAPIDocs' &
git clone https://github.com/hackclub/awesome-hackclub '/storage/nvme5/new_clones/Markdown/awesome-hackclub' &
git clone https://github.com/lightninglabs/docs.lightning.engineering '/storage/nvme5/new_clones/Markdown/docs.lightning.engineering' &
git clone https://github.com/ponylang/rfcs '/storage/nvme5/new_clones/Markdown/rfcs' &
git clone https://github.com/brunosimon/threejs-journey-uptime '/storage/nvme5/new_clones/Markdown/threejs-journey-uptime' &
git clone https://github.com/privacy-noarch/privacy '/storage/nvme5/new_clones/Markdown/privacy' &
git clone https://github.com/Anmol-Baranwal/Hack-Your-Growth '/storage/nvme5/new_clones/Markdown/Hack-Your-Growth' &
git clone https://github.com/kongying-tavern/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/chengpeiquan/cooking-cookbook '/storage/nvme5/new_clones/Markdown/cooking-cookbook' &
git clone https://github.com/0xdevalias/devalias.net '/storage/nvme5/new_clones/Markdown/devalias.net' &
git clone https://github.com/Booodaness/Scientific-Notes '/storage/nvme5/new_clones/Markdown/Scientific-Notes' &
git clone https://github.com/srid/emanote-template '/storage/nvme5/new_clones/Markdown/emanote-template' &
git clone https://github.com/rcarubbi/awesome-brazilian-youtubers '/storage/nvme5/new_clones/Markdown/awesome-brazilian-youtubers' &
git clone https://github.com/mautrix/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/walkccc/CS '/storage/nvme5/new_clones/Markdown/CS' &
git clone https://github.com/Kuratoro/zk.zettel.page '/storage/nvme5/new_clones/Markdown/zk.zettel.page' &
git clone https://github.com/erhant/crypto-notes '/storage/nvme5/new_clones/Markdown/crypto-notes' &
git clone https://github.com/blu3r4y/python-for-java-developers '/storage/nvme5/new_clones/Markdown/python-for-java-developers' &
git clone https://github.com/chawyehsu/chawyehsu.com '/storage/nvme5/new_clones/Markdown/chawyehsu.com' &
git clone https://github.com/REBELinBLUE/kube-guide '/storage/nvme5/new_clones/Markdown/kube-guide' &
git clone https://github.com/imaarov/imaarov '/storage/nvme5/new_clones/Markdown/imaarov' &
git clone https://github.com/TomasHubelbauer/raspi-mouse-jiggler '/storage/nvme5/new_clones/Markdown/raspi-mouse-jiggler' &
git clone https://github.com/BlackIQ/markdown '/storage/nvme5/new_clones/Markdown/markdown' &
git clone https://github.com/xiyou-linuxer/Plan '/storage/nvme5/new_clones/Markdown/Plan' &
git clone https://github.com/rstudio/helm '/storage/nvme5/new_clones/Markdown/helm' &
git clone https://github.com/Igigog/anomaly-modding-book '/storage/nvme5/new_clones/Markdown/anomaly-modding-book' &
git clone https://github.com/delphidabbler/ddab-lib-docs '/storage/nvme5/new_clones/Markdown/ddab-lib-docs' &
git clone https://github.com/ilcpm/cqu-thesis-markdown '/storage/nvme5/new_clones/Markdown/cqu-thesis-markdown' &
git clone https://github.com/docsforadobe/premiere-scripting-guide '/storage/nvme5/new_clones/Markdown/premiere-scripting-guide' &
git clone https://github.com/daczarne/mosh_docker '/storage/nvme5/new_clones/Markdown/mosh_docker' &
git clone https://github.com/webdoky/content '/storage/nvme5/new_clones/Markdown/content' &
git clone https://github.com/docsforadobe/after-effects-expression-reference '/storage/nvme5/new_clones/Markdown/after-effects-expression-reference' &
git clone https://github.com/privacyguides/blog.privacyguides.org '/storage/nvme5/new_clones/Markdown/blog.privacyguides.org' &
git clone https://github.com/muziing/domm '/storage/nvme5/new_clones/Markdown/domm' &
git clone https://github.com/docsforadobe/after-effects-plugin-guide '/storage/nvme5/new_clones/Markdown/after-effects-plugin-guide' &
git clone https://github.com/TomasHubelbauer/workers-formdata '/storage/nvme5/new_clones/Markdown/workers-formdata' &
git clone https://github.com/CSRG-Group/dcs-notes.github.io '/storage/nvme5/new_clones/Markdown/dcs-noteshub.io' &
git clone https://github.com/llvm/clangd-www '/storage/nvme5/new_clones/Markdown/clangd-www' &
git clone https://github.com/ggorlen/resources '/storage/nvme5/new_clones/Markdown/resources' &
git clone https://github.com/TigersWay/eleventy-classic-blog-starter '/storage/nvme5/new_clones/Markdown/eleventy-classic-blog-starter' &
git clone https://github.com/TomasHubelbauer/akai-apc-mini '/storage/nvme5/new_clones/Markdown/akai-apc-mini' &
git clone https://github.com/forwardemail/status.forwardemail.net '/storage/nvme5/new_clones/Markdown/status.forwardemail.net' &
git clone https://github.com/chatwoot/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/ahmadalwareh/Python_Interview_Questions '/storage/nvme5/new_clones/Markdown/Python_Interview_Questions' &
git clone https://github.com/thomasgtaylor/how.wtf '/storage/nvme5/new_clones/Markdown/how.wtf' &
git clone https://github.com/GeyserMC/GeyserWiki '/storage/nvme5/new_clones/Markdown/GeyserWiki' &
git clone https://github.com/ory/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/glhrmoura/js-quiz '/storage/nvme5/new_clones/Markdown/js-quiz' &
git clone https://github.com/tiekoettercom/searx-instances-uptime '/storage/nvme5/new_clones/Markdown/searx-instances-uptime' &
git clone https://github.com/BlackIQ/BlackIQ '/storage/nvme5/new_clones/Markdown/BlackIQ' &
git clone https://github.com/Androz2091/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/FreeBSD-Ask/Handbook '/storage/nvme5/new_clones/Markdown/Handbook' &
git clone https://github.com/Joeyh021/notes '/storage/nvme5/new_clones/Markdown/notes' &
git clone https://github.com/TAbdiukov/CISSP-mnemonics '/storage/nvme5/new_clones/Markdown/CISSP-mnemonics' &
git clone https://github.com/bringmetheaugust/welcome_to_TE '/storage/nvme5/new_clones/Markdown/welcome_to_TE' &
git clone https://github.com/joshuatz/video-test-file-links '/storage/nvme5/new_clones/Markdown/video-test-file-links' &
git clone https://github.com/The-Shivam-garg/Github-badges '/storage/nvme5/new_clones/Markdown/Github-badges' &
git clone https://github.com/searxng/searx-instances-uptime '/storage/nvme5/new_clones/Markdown/searx-instances-uptime' &
git clone https://github.com/tbobm/etna-uptime '/storage/nvme5/new_clones/Markdown/etna-uptime' &
git clone https://github.com/BlackIQ/animal-farm '/storage/nvme5/new_clones/Markdown/animal-farm' &
git clone https://github.com/Kaho-WONG/myNotes '/storage/nvme5/new_clones/Markdown/myNotes' &
git clone https://github.com/BlackIQ/fa.BlackIQ.ir '/storage/nvme5/new_clones/Markdown/fa.BlackIQ.ir' &
git clone https://github.com/magistermaks/fabric '/storage/nvme5/new_clones/Markdown/fabric' &
git clone https://github.com/tfausak/haskell-knowledge-base '/storage/nvme5/new_clones/Markdown/haskell-knowledge-base' &
git clone https://github.com/EddieHubCommunity/monitoring '/storage/nvme5/new_clones/Markdown/monitoring' &
git clone https://github.com/lit/rfcs '/storage/nvme5/new_clones/Markdown/rfcs' &
git clone https://github.com/simple-login/uptime '/storage/nvme5/new_clones/Markdown/uptime' &
git clone https://github.com/Sulstice/Uptime-Cheminformatics '/storage/nvme5/new_clones/Markdown/Uptime-Cheminformatics' &
git clone https://github.com/BlackIQ/the-great-gatsby '/storage/nvme5/new_clones/Markdown/the-great-gatsby' &
git clone https://github.com/sean-chester/exploiting-modern-hardware '/storage/nvme5/new_clones/Markdown/exploiting-modern-hardware' &
git clone https://github.com/flare-foundation/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/nanarino/nanarinonote '/storage/nvme5/new_clones/Markdown/nanarinonote' &
git clone https://github.com/magestacks/framework '/storage/nvme5/new_clones/Markdown/framework' &
git clone https://github.com/UWCS/rs118 '/storage/nvme5/new_clones/Markdown/rs118' &
git clone https://github.com/DragunWF/DragunWF '/storage/nvme5/new_clones/Markdown/DragunWF' &
git clone https://github.com/Sigmanificient/Sigmanificient '/storage/nvme5/new_clones/Markdown/Sigmanificient' &
git clone https://github.com/docsforadobe/premiere-plugin-guide '/storage/nvme5/new_clones/Markdown/premiere-plugin-guide' &
git clone https://github.com/TCastus/TChelp '/storage/nvme5/new_clones/Markdown/TChelp' &
git clone https://github.com/QuentinRa/blog.quentinra.dev '/storage/nvme5/new_clones/Markdown/blog.quentinra.dev' &
git clone https://github.com/tictactrip/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/ljun20160606/blog '/storage/nvme5/new_clones/Markdown/blog' &
git clone https://github.com/Correia-jpv/fucking-magictools '/storage/nvme5/new_clones/Markdown/fucking-magictools' &
git clone https://github.com/bipou/markdown-guide '/storage/nvme5/new_clones/Markdown/markdown-guide' &
git clone https://github.com/BlackIQ/Zahra-Moti '/storage/nvme5/new_clones/Markdown/Zahra-Moti' &
git clone https://github.com/RisingInIris2017/Tadokoro-Teatime '/storage/nvme5/new_clones/Markdown/Tadokoro-Teatime' &
git clone https://github.com/Dungeons-and-Pi/EncounterModuleList '/storage/nvme5/new_clones/Markdown/EncounterModuleList' &
git clone https://github.com/shijuro/OpenCore-Install-Guide '/storage/nvme5/new_clones/Markdown/OpenCore-Install-Guide' &
git clone https://github.com/Mikaela/mikaela.github.io '/storage/nvme5/new_clones/Markdown/mikaelahub.io' &
git clone https://github.com/schollz/upptime '/storage/nvme5/new_clones/Markdown/upptime' &
git clone https://github.com/Gabriella439/political-notes '/storage/nvme5/new_clones/Markdown/political-notes' &
git clone https://github.com/BlackIQ/cdn.BlackIQ.ir '/storage/nvme5/new_clones/Markdown/cdn.BlackIQ.ir' &
git clone https://github.com/Chaoses-Ib/ConcurrentComputing '/storage/nvme5/new_clones/Markdown/ConcurrentComputing' &
git clone https://github.com/hackmdio/status.hackmd.io '/storage/nvme5/new_clones/Markdown/status.hackmd.io' &
git clone https://github.com/binary-ho/TIL-public '/storage/nvme5/new_clones/Markdown/TIL-public' &
git clone https://github.com/melvincwng/melvincwng '/storage/nvme5/new_clones/Markdown/melvincwng' &
git clone https://github.com/HorlogeSkynet/awesome-thinkerview '/storage/nvme5/new_clones/Markdown/awesome-thinkerview' &
git clone https://github.com/kaffarell/vault-5bt '/storage/nvme5/new_clones/Markdown/vault-5bt' &
git clone https://github.com/rectcircle/rectcircle-blog '/storage/nvme5/new_clones/Markdown/rectcircle-blog' &
git clone https://github.com/4rlenrey/Notes '/storage/nvme5/new_clones/Markdown/Notes' &
git clone https://github.com/Sukritact/Civilization-VI-Modding-Knowledge-Base '/storage/nvme5/new_clones/Markdown/Civilization-VI-Modding-Knowledge-Base' &
git clone https://github.com/TomasHubelbauer/onewheel-charger '/storage/nvme5/new_clones/Markdown/onewheel-charger' &
git clone https://github.com/stalomeow/note '/storage/nvme5/new_clones/Markdown/note' &
git clone https://github.com/dexpota/cheatsheets '/storage/nvme5/new_clones/Markdown/cheatsheets' &
git clone https://github.com/shilangyu/uni-notes '/storage/nvme5/new_clones/Markdown/uni-notes' &
git clone https://github.com/prayogaea/installation '/storage/nvme5/new_clones/Markdown/installation' &
git clone https://github.com/TonyCrane/MarkdownLecture '/storage/nvme5/new_clones/Markdown/MarkdownLecture' &
git clone https://github.com/Sigmanificient/Notes '/storage/nvme5/new_clones/Markdown/Notes' &
git clone https://github.com/mue/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/TimGrt/Ansible-Best-Practices '/storage/nvme5/new_clones/Markdown/Ansible-Best-Practices' &
git clone https://github.com/qwerty541/qwerty541 '/storage/nvme5/new_clones/Markdown/qwerty541' &
git clone https://github.com/Jackiexiao/blog '/storage/nvme5/new_clones/Markdown/blog' &
git clone https://github.com/SparkScratch-P/SparkScratch-P '/storage/nvme5/new_clones/Markdown/SparkScratch-P' &
git clone https://github.com/safe-global/safe-services-status '/storage/nvme5/new_clones/Markdown/safe-services-status' &
git clone https://github.com/clustergarage/argus '/storage/nvme5/new_clones/Markdown/argus' &
git clone https://github.com/jestenough/learning '/storage/nvme5/new_clones/Markdown/learning' &
git clone https://github.com/AnandChowdhary/readme '/storage/nvme5/new_clones/Markdown/readme' &
git clone https://github.com/TomasHubelbauer/brother-p-touch-d600 '/storage/nvme5/new_clones/Markdown/brother-p-touch-d600' &
git clone https://github.com/lensapp/k8slens-status '/storage/nvme5/new_clones/Markdown/k8slens-status' &
git clone https://github.com/aben20807/blog-post-issues '/storage/nvme5/new_clones/Markdown/blog-post-issues' &
git clone https://github.com/weblate-status-bot/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/OpenBB-finance/uptime '/storage/nvme5/new_clones/Markdown/uptime' &
git clone https://github.com/DeNepo/precourse '/storage/nvme5/new_clones/Markdown/precourse' &
git clone https://github.com/intsuc/blog '/storage/nvme5/new_clones/Markdown/blog' &
git clone https://github.com/iagoleal/iagoleal.github.io '/storage/nvme5/new_clones/Markdown/iagolealhub.io' &
git clone https://github.com/z-shell/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/gideonshaked/learn-git '/storage/nvme5/new_clones/Markdown/learn-git' &
git clone https://github.com/open-aviation/aviationbook '/storage/nvme5/new_clones/Markdown/aviationbook' &
git clone https://github.com/Bryan-Herrera-DEV/status-for-my-web-pages '/storage/nvme5/new_clones/Markdown/status-for-my-web-pages' &
git clone https://github.com/viperML/neohome '/storage/nvme5/new_clones/Markdown/neohome' &
git clone https://github.com/TomasHubelbauer/onewheel '/storage/nvme5/new_clones/Markdown/onewheel' &
git clone https://github.com/readloud/Github-Profile-Badges '/storage/nvme5/new_clones/Markdown/Github-Profile-Badges' &
git clone https://github.com/drolbr/overpass-doc '/storage/nvme5/new_clones/Markdown/overpass-doc' &
git clone https://github.com/carbon-design-system/uptime '/storage/nvme5/new_clones/Markdown/uptime' &
git clone https://github.com/peterroe/peterroe.icu '/storage/nvme5/new_clones/Markdown/peterroe.icu' &
git clone https://github.com/canonical/upptime '/storage/nvme5/new_clones/Markdown/upptime' &
git clone https://github.com/kube-rs/website '/storage/nvme5/new_clones/Markdown/website' &
git clone https://github.com/kmaasrud/wiki '/storage/nvme5/new_clones/Markdown/wiki' &
git clone https://github.com/tjsky/upptime '/storage/nvme5/new_clones/Markdown/upptime' &
git clone https://github.com/CuteReimu/gobang '/storage/nvme5/new_clones/Markdown/gobang' &
git clone https://github.com/Chaoses-Ib/Networks '/storage/nvme5/new_clones/Markdown/Networks' &
git clone https://github.com/ShonHarsh/hello-world '/storage/nvme5/new_clones/Markdown/hello-world' &
git clone https://github.com/malijani/linux-essentials '/storage/nvme5/new_clones/Markdown/linux-essentials' &
git clone https://github.com/Cog-Creators/Red-Status '/storage/nvme5/new_clones/Markdown/Red-Status' &
git clone https://github.com/Chaoses-Ib/VisualComputing '/storage/nvme5/new_clones/Markdown/VisualComputing' &
git clone https://github.com/skfit-uni-luebeck/ontoserver-keycloak '/storage/nvme5/new_clones/Markdown/ontoserver-keycloak' &
git clone https://github.com/Pradumnasaraf/Monitoring '/storage/nvme5/new_clones/Markdown/Monitoring' &
git clone https://github.com/webments/Webments '/storage/nvme5/new_clones/Markdown/Webments' &
git clone https://github.com/Nimor111/notebook '/storage/nvme5/new_clones/Markdown/notebook' &
git clone https://github.com/andatoshiki/toshiki-notebook '/storage/nvme5/new_clones/Markdown/toshiki-notebook' &
git clone https://github.com/DeNepo/workflows '/storage/nvme5/new_clones/Markdown/workflows' &
git clone https://github.com/stn1slv/kong-mindmap '/storage/nvme5/new_clones/Markdown/kong-mindmap' &
git clone https://github.com/stormkit-io/stormkit-status '/storage/nvme5/new_clones/Markdown/stormkit-status' &
git clone https://github.com/TomasHubelbauer/markdown-webp '/storage/nvme5/new_clones/Markdown/markdown-webp' &
git clone https://github.com/maduc238/open5gs-docker '/storage/nvme5/new_clones/Markdown/open5gs-docker' &
git clone https://github.com/seanpm2001/Widevine-l3-decryptor-wiki '/storage/nvme5/new_clones/Markdown/Widevine-l3-decryptor-wiki' &
git clone https://github.com/andersthemagi/magicalmusings.github.io '/storage/nvme5/new_clones/Markdown/magicalmusingshub.io' &
git clone https://github.com/Chaoses-Ib/Windows '/storage/nvme5/new_clones/Markdown/Windows' &
git clone https://github.com/stethoscope-js/status '/storage/nvme5/new_clones/Markdown/status' &
git clone https://github.com/Chaoses-Ib/PersonalComputing '/storage/nvme5/new_clones/Markdown/PersonalComputing' &
git clone https://github.com/alchemyrpg/upptime '/storage/nvme5/new_clones/Markdown/upptime' &
git clone https://github.com/vue-youtube/docs '/storage/nvme5/new_clones/Markdown/docs' &
git clone https://github.com/cake-tech/upptime-cakewallet '/storage/nvme5/new_clones/Markdown/upptime-cakewallet' &
git clone https://github.com/kxxt/kxxt-website '/storage/nvme5/new_clones/Markdown/kxxt-website' &
git clone https://github.com/Chaoses-Ib/ComputerHardware '/storage/nvme5/new_clones/Markdown/ComputerHardware' &
git clone https://github.com/TomasHubelbauer/ps-ntlite '/storage/nvme5/new_clones/Markdown/ps-ntlite' &
git clone https://github.com/Abeautifulsnow/awesomeLibrary '/storage/nvme5/new_clones/Markdown/awesomeLibrary' &
git clone https://github.com/TomasHubelbauer/github-actions '/storage/nvme5/new_clones/Markdown/github-actions' &
git clone https://github.com/Fijxu/justlog-instances-uptime '/storage/nvme5/new_clones/Markdown/justlog-instances-uptime' &
git clone https://github.com/snapwiki/SnapWikiUptime '/storage/nvme5/new_clones/Markdown/SnapWikiUptime' &
git clone https://github.com/Dilant/B2METutorial '/storage/nvme5/new_clones/Markdown/B2METutorial' &
git clone https://github.com/stormkit-io/stormkit-status '/storage/nvme5/new_clones/Markdown/stormkit-status' &
