#!/bin/bash

git clone https://github.com/KhronosGroup/glTF-Sample-Models '/storage/nvme5/new_clones/Mathematica/glTF-Sample-Models' &
git clone https://github.com/Eikanya/Live2d-model '/storage/nvme5/new_clones/Mathematica/Live2d-model' &
git clone https://github.com/dzhang314/YouTubeDrive '/storage/nvme5/new_clones/Mathematica/YouTubeDrive' &
git clone https://github.com/TheBloodthirster/BUAA_Course_Sharing '/storage/nvme5/new_clones/Mathematica/BUAA_Course_Sharing' &
git clone https://github.com/WolframResearch/WolframLanguageForJupyter '/storage/nvme5/new_clones/Mathematica/WolframLanguageForJupyter' &
git clone https://github.com/WolframResearch/Arrival-Movie-Live-Coding '/storage/nvme5/new_clones/Mathematica/Arrival-Movie-Live-Coding' &
git clone https://github.com/game-ci/unity-actions '/storage/nvme5/new_clones/Mathematica/unity-actions' &
git clone https://github.com/jhorikawa/HoudiniHowtos '/storage/nvme5/new_clones/Mathematica/HoudiniHowtos' &
git clone https://github.com/PlamenStilyianov/FinMathematics '/storage/nvme5/new_clones/Mathematica/FinMathematics' &
git clone https://github.com/WebGLSamples/WebGLSamples.github.io '/storage/nvme5/new_clones/Mathematica/WebGLSampleshub.io' &
git clone https://github.com/Autodesk/maya-usd '/storage/nvme5/new_clones/Mathematica/maya-usd' &
git clone https://github.com/Azure/CCOInsights '/storage/nvme5/new_clones/Mathematica/CCOInsights' &
git clone https://github.com/ColinKennedy/USD-Cookbook '/storage/nvme5/new_clones/Mathematica/USD-Cookbook' &
git clone https://github.com/BabylonJS/Exporters '/storage/nvme5/new_clones/Mathematica/Exporters' &
git clone https://github.com/lsw9021/MASS '/storage/nvme5/new_clones/Mathematica/MASS' &
git clone https://github.com/EpicGames/MetaHuman-DNA-Calibration '/storage/nvme5/new_clones/Mathematica/MetaHuman-DNA-Calibration' &
git clone https://github.com/kayru/Probulator '/storage/nvme5/new_clones/Mathematica/Probulator' &
git clone https://github.com/FXyz/FXyz '/storage/nvme5/new_clones/Mathematica/FXyz' &
git clone https://github.com/Unity-Technologies/com.unity.multiplayer.samples.bitesize '/storage/nvme5/new_clones/Mathematica/com.unity.multiplayer.samples.bitesize' &
git clone https://github.com/corywalker/expreduce '/storage/nvme5/new_clones/Mathematica/expreduce' &
git clone https://github.com/szhorvat/MaTeX '/storage/nvme5/new_clones/Mathematica/MaTeX' &
git clone https://github.com/tagtime/TagTime '/storage/nvme5/new_clones/Mathematica/TagTime' &
git clone https://github.com/iimachines/Maya2glTF '/storage/nvme5/new_clones/Mathematica/Maya2glTF' &
git clone https://github.com/dilmerv/UnityVFXMillionsOfParticles '/storage/nvme5/new_clones/Mathematica/UnityVFXMillionsOfParticles' &
git clone https://github.com/Unity-Technologies/ShaderGraph-Custom-Lighting '/storage/nvme5/new_clones/Mathematica/ShaderGraph-Custom-Lighting' &
git clone https://github.com/name99-org/AArch64-Explore '/storage/nvme5/new_clones/Mathematica/AArch64-Explore' &
git clone https://github.com/Patapom/GodComplex '/storage/nvme5/new_clones/Mathematica/GodComplex' &
git clone https://github.com/alexanderrichtertd/plex '/storage/nvme5/new_clones/Mathematica/plex' &
git clone https://github.com/pierremtb/PINNs-TF2.0 '/storage/nvme5/new_clones/Mathematica/PINNs-TF2.0' &
git clone https://github.com/sebh/HLSL-Spherical-Harmonics '/storage/nvme5/new_clones/Mathematica/HLSL-Spherical-Harmonics' &
git clone https://github.com/RuleBasedIntegration/Rubi '/storage/nvme5/new_clones/Mathematica/Rubi' &
git clone https://github.com/maxitg/SetReplace '/storage/nvme5/new_clones/Mathematica/SetReplace' &
git clone https://github.com/kenkangxgwe/lsp-wl '/storage/nvme5/new_clones/Mathematica/lsp-wl' &
git clone https://github.com/cyrillef/FBX-glTF '/storage/nvme5/new_clones/Mathematica/FBX-glTF' &
git clone https://github.com/usnistgov/REFPROP-wrappers '/storage/nvme5/new_clones/Mathematica/REFPROP-wrappers' &
git clone https://github.com/romeric/fastapprox '/storage/nvme5/new_clones/Mathematica/fastapprox' &
git clone https://github.com/bartwronski/BlueNoiseGenerator '/storage/nvme5/new_clones/Mathematica/BlueNoiseGenerator' &
git clone https://github.com/gillescastel/masterthesis '/storage/nvme5/new_clones/Mathematica/masterthesis' &
git clone https://github.com/EverettYou/Mathematica-for-physics '/storage/nvme5/new_clones/Mathematica/Mathematica-for-physics' &
git clone https://github.com/Unity-Technologies/animation-rigging-workshop-siggraph2019 '/storage/nvme5/new_clones/Mathematica/animation-rigging-workshop-siggraph2019' &
git clone https://github.com/daniel-ilett/water-urp '/storage/nvme5/new_clones/Mathematica/water-urp' &
git clone https://github.com/Hopsan/hopsan '/storage/nvme5/new_clones/Mathematica/hopsan' &
git clone https://github.com/EarthSalamander42/dota_imba '/storage/nvme5/new_clones/Mathematica/dota_imba' &
git clone https://github.com/Theigrams/Mathematical-optimization '/storage/nvme5/new_clones/Mathematica/Mathematical-optimization' &
git clone https://github.com/daniel-ilett/shaders-botw-grass '/storage/nvme5/new_clones/Mathematica/shaders-botw-grass' &
git clone https://github.com/ericjang/svd3 '/storage/nvme5/new_clones/Mathematica/svd3' &
git clone https://github.com/togucchi/HDToon '/storage/nvme5/new_clones/Mathematica/HDToon' &
git clone https://github.com/assimp/assimp-mdb '/storage/nvme5/new_clones/Mathematica/assimp-mdb' &
git clone https://github.com/robinvista/Mathematica '/storage/nvme5/new_clones/Mathematica/Mathematica' &
git clone https://github.com/zicher3d-org/domemaster-stereo-shader '/storage/nvme5/new_clones/Mathematica/domemaster-stereo-shader' &
git clone https://github.com/Foohy/jazztronauts '/storage/nvme5/new_clones/Mathematica/jazztronauts' &
git clone https://github.com/ncsu-eda/FreePDK3 '/storage/nvme5/new_clones/Mathematica/FreePDK3' &
git clone https://github.com/dgovil/MLDeform '/storage/nvme5/new_clones/Mathematica/MLDeform' &
git clone https://github.com/mmacklin/sandbox '/storage/nvme5/new_clones/Mathematica/sandbox' &
git clone https://github.com/SQL-Server-projects/Reporting-Services-examples '/storage/nvme5/new_clones/Mathematica/Reporting-Services-examples' &
git clone https://github.com/MirageYM/3DModels '/storage/nvme5/new_clones/Mathematica/3DModels' &
git clone https://github.com/InertialObservr/twitter_gifs '/storage/nvme5/new_clones/Mathematica/twitter_gifs' &
git clone https://github.com/bshoshany/OGRe '/storage/nvme5/new_clones/Mathematica/OGRe' &
git clone https://github.com/BlockchainCommons/Research '/storage/nvme5/new_clones/Mathematica/Research' &
git clone https://github.com/gustavoeb/ikrig '/storage/nvme5/new_clones/Mathematica/ikrig' &
git clone https://github.com/gasc/Clojuratica '/storage/nvme5/new_clones/Mathematica/Clojuratica' &
git clone https://github.com/daniel-ilett/shaders-botw-cel-shading '/storage/nvme5/new_clones/Mathematica/shaders-botw-cel-shading' &
git clone https://github.com/PorktoberRevolution/ReStocked '/storage/nvme5/new_clones/Mathematica/ReStocked' &
git clone https://github.com/alindmanUnity/ShaderGraph-FeatureDemo-2018-2 '/storage/nvme5/new_clones/Mathematica/ShaderGraph-FeatureDemo-2018-2' &
git clone https://github.com/Toolchefs/kiko '/storage/nvme5/new_clones/Mathematica/kiko' &
git clone https://github.com/daniel-ilett/dither-transparency-urp '/storage/nvme5/new_clones/Mathematica/dither-transparency-urp' &
git clone https://github.com/greenfrvr/rubber-loader '/storage/nvme5/new_clones/Mathematica/rubber-loader' &
git clone https://github.com/szhorvat/IGraphM '/storage/nvme5/new_clones/Mathematica/IGraphM' &
git clone https://github.com/eugenedeon/hitchhikersscatter '/storage/nvme5/new_clones/Mathematica/hitchhikersscatter' &
git clone https://github.com/PKU-GeekGame/geekgame-2nd '/storage/nvme5/new_clones/Mathematica/geekgame-2nd' &
git clone https://github.com/sal55/langs '/storage/nvme5/new_clones/Mathematica/langs' &
git clone https://github.com/xAct-contrib/examples '/storage/nvme5/new_clones/Mathematica/examples' &
git clone https://github.com/clfrenchgit/gdax-bot '/storage/nvme5/new_clones/Mathematica/gdax-bot' &
git clone https://github.com/JonathanGorard/Gravitas '/storage/nvme5/new_clones/Mathematica/Gravitas' &
git clone https://github.com/merpheus-dev/FakeInteriorsShader '/storage/nvme5/new_clones/Mathematica/FakeInteriorsShader' &
git clone https://github.com/emptymalei/WhyMathematica '/storage/nvme5/new_clones/Mathematica/WhyMathematica' &
git clone https://github.com/Brackeys/Health-Bar '/storage/nvme5/new_clones/Mathematica/Health-Bar' &
git clone https://github.com/robertjoosten/maya-dem-bones '/storage/nvme5/new_clones/Mathematica/maya-dem-bones' &
git clone https://github.com/MarcosCarreira/StatisticalConsequencesOfFatTails '/storage/nvme5/new_clones/Mathematica/StatisticalConsequencesOfFatTails' &
git clone https://github.com/j2kun/neural-networks '/storage/nvme5/new_clones/Mathematica/neural-networks' &
git clone https://github.com/pkouassi/CQF '/storage/nvme5/new_clones/Mathematica/CQF' &
git clone https://github.com/jpmaus/running-man '/storage/nvme5/new_clones/Mathematica/running-man' &
git clone https://github.com/BlockchainCommons/LifeHash '/storage/nvme5/new_clones/Mathematica/LifeHash' &
git clone https://github.com/QuantumUtils/quantum-utils-mathematica '/storage/nvme5/new_clones/Mathematica/quantum-utils-mathematica' &
git clone https://github.com/daniel-ilett/shaders-impossible-geom '/storage/nvme5/new_clones/Mathematica/shaders-impossible-geom' &
git clone https://github.com/ythea/repulsive-surfaces '/storage/nvme5/new_clones/Mathematica/repulsive-surfaces' &
git clone https://github.com/zscircuits/zs1100a '/storage/nvme5/new_clones/Mathematica/zs1100a' &
git clone https://github.com/jeremynewlin/Accel '/storage/nvme5/new_clones/Mathematica/Accel' &
git clone https://github.com/AndrewHazelden/Panoramic_Geometry_Collection '/storage/nvme5/new_clones/Mathematica/Panoramic_Geometry_Collection' &
git clone https://github.com/marko-vasic/crnPlusPlus '/storage/nvme5/new_clones/Mathematica/crnPlusPlus' &
git clone https://github.com/dtlindsey/bifrost-dl-core '/storage/nvme5/new_clones/Mathematica/bifrost-dl-core' &
git clone https://github.com/oovm/Mathpix '/storage/nvme5/new_clones/Mathematica/Mathpix' &
git clone https://github.com/djmonkeyuk/nms-base-builder '/storage/nvme5/new_clones/Mathematica/nms-base-builder' &
git clone https://github.com/daniel-ilett/dissolve-urp '/storage/nvme5/new_clones/Mathematica/dissolve-urp' &
git clone https://github.com/hpd/DigitalEmily '/storage/nvme5/new_clones/Mathematica/DigitalEmily' &
git clone https://github.com/ezequielmastrasso/EZLookdevTools '/storage/nvme5/new_clones/Mathematica/EZLookdevTools' &
git clone https://github.com/sienaiwun/unity_lwrp_shadowmask_demo '/storage/nvme5/new_clones/Mathematica/unity_lwrp_shadowmask_demo' &
git clone https://github.com/rsmenon/MATLink '/storage/nvme5/new_clones/Mathematica/MATLink' &
git clone https://github.com/monte-language/typhon '/storage/nvme5/new_clones/Mathematica/typhon' &
git clone https://github.com/sparks-baird/auto-paper '/storage/nvme5/new_clones/Mathematica/auto-paper' &
git clone https://github.com/Q-Compiler/UniversalQCompiler '/storage/nvme5/new_clones/Mathematica/UniversalQCompiler' &
git clone https://github.com/coderDarren/Unity3D-Cars '/storage/nvme5/new_clones/Mathematica/Unity3D-Cars' &
git clone https://github.com/WolframResearch/codeinspector '/storage/nvme5/new_clones/Mathematica/codeinspector' &
git clone https://github.com/stride3d/Starbreach '/storage/nvme5/new_clones/Mathematica/Starbreach' &
git clone https://github.com/daniel-ilett/shaders-hologram '/storage/nvme5/new_clones/Mathematica/shaders-hologram' &
git clone https://github.com/mfroeling/QMRITools '/storage/nvme5/new_clones/Mathematica/QMRITools' &
git clone https://github.com/GameDevChef/CarController '/storage/nvme5/new_clones/Mathematica/CarController' &
git clone https://github.com/kattkieru/grim_IK '/storage/nvme5/new_clones/Mathematica/grim_IK' &
git clone https://github.com/cardosoandre/Animation-Rigging-Examples '/storage/nvme5/new_clones/Mathematica/Animation-Rigging-Examples' &
git clone https://github.com/iamc/ML-CM-2019 '/storage/nvme5/new_clones/Mathematica/ML-CM-2019' &
git clone https://github.com/oovm/Geass '/storage/nvme5/new_clones/Mathematica/Geass' &
git clone https://github.com/daniel-ilett/cel-shading-urp '/storage/nvme5/new_clones/Mathematica/cel-shading-urp' &
git clone https://github.com/algal/TouchVisualizer '/storage/nvme5/new_clones/Mathematica/TouchVisualizer' &
git clone https://github.com/WolframResearch/FEMAddOns '/storage/nvme5/new_clones/Mathematica/FEMAddOns' &
git clone https://github.com/stackmma/stylesheets '/storage/nvme5/new_clones/Mathematica/stylesheets' &
git clone https://github.com/jkuczm/MathematicaCellsToTeX '/storage/nvme5/new_clones/Mathematica/MathematicaCellsToTeX' &
git clone https://github.com/bryango/PKUModernPhyLabReport_LaTeX '/storage/nvme5/new_clones/Mathematica/PKUModernPhyLabReport_LaTeX' &
git clone https://github.com/tkweizhong/CustomURP '/storage/nvme5/new_clones/Mathematica/CustomURP' &
git clone https://github.com/zfc-zfc/HITsz-Automation-Open-Source '/storage/nvme5/new_clones/Mathematica/HITsz-Automation-Open-Source' &
git clone https://github.com/RomboDev/Miscellaneous '/storage/nvme5/new_clones/Mathematica/Miscellaneous' &
git clone https://github.com/cuckon/scratched '/storage/nvme5/new_clones/Mathematica/scratched' &
git clone https://github.com/b-shields/auto-QChem '/storage/nvme5/new_clones/Mathematica/auto-QChem' &
git clone https://github.com/wjxway/Realistic_Blackhole_Accretion_Disk '/storage/nvme5/new_clones/Mathematica/Realistic_Blackhole_Accretion_Disk' &
git clone https://github.com/s9lucas/URP-Equirectangular-Camera '/storage/nvme5/new_clones/Mathematica/URP-Equirectangular-Camera' &
git clone https://github.com/taliesinb/spatial-game-theory '/storage/nvme5/new_clones/Mathematica/spatial-game-theory' &
git clone https://github.com/andrejbauer/mathematics-and-computation '/storage/nvme5/new_clones/Mathematica/mathematics-and-computation' &
git clone https://github.com/klavinslab/gro '/storage/nvme5/new_clones/Mathematica/gro' &
git clone https://github.com/WolframResearch/LSPServer '/storage/nvme5/new_clones/Mathematica/LSPServer' &
git clone https://github.com/ValveSoftware/openxr_engine_plugins '/storage/nvme5/new_clones/Mathematica/openxr_engine_plugins' &
git clone https://github.com/Mirebeau/HamiltonFastMarching '/storage/nvme5/new_clones/Mathematica/HamiltonFastMarching' &
git clone https://github.com/haggi/OpenMaya '/storage/nvme5/new_clones/Mathematica/OpenMaya' &
git clone https://github.com/halirutan/Mathematica-Source-Highlighting '/storage/nvme5/new_clones/Mathematica/Mathematica-Source-Highlighting' &
git clone https://github.com/paulknysh/sym '/storage/nvme5/new_clones/Mathematica/sym' &
git clone https://github.com/NathanKell/RealSolarSystem '/storage/nvme5/new_clones/Mathematica/RealSolarSystem' &
git clone https://github.com/Minghou-Lei/Realtime-point-light-shadows-in-unity-URP '/storage/nvme5/new_clones/Mathematica/Realtime-point-light-shadows-in-unity-URP' &
git clone https://github.com/microsoft/Dynamics-365-for-Marketing---Power-BI-Reporting '/storage/nvme5/new_clones/Mathematica/Dynamics-365-for-Marketing---Power-BI-Reporting' &
git clone https://github.com/b3m2a1/mathematica-BTools '/storage/nvme5/new_clones/Mathematica/mathematica-BTools' &
git clone https://github.com/NickQian/Robi-Transform-Project '/storage/nvme5/new_clones/Mathematica/Robi-Transform-Project' &
git clone https://github.com/SilangQuan/Illustrative-Rendering-with-Unity '/storage/nvme5/new_clones/Mathematica/Illustrative-Rendering-with-Unity' &
git clone https://github.com/croningp/assemblyphysics '/storage/nvme5/new_clones/Mathematica/assemblyphysics' &
git clone https://github.com/jlaragonvera/Geometric-Algebra '/storage/nvme5/new_clones/Mathematica/Geometric-Algebra' &
git clone https://github.com/blab/rt-from-frequency-dynamics '/storage/nvme5/new_clones/Mathematica/rt-from-frequency-dynamics' &
git clone https://github.com/LePtC/AlphaChord '/storage/nvme5/new_clones/Mathematica/AlphaChord' &
git clone https://github.com/kubaPod/M2MD '/storage/nvme5/new_clones/Mathematica/M2MD' &
git clone https://github.com/WolframResearch/codeformatter '/storage/nvme5/new_clones/Mathematica/codeformatter' &
git clone https://github.com/Unity-Technologies/TimelineSignalsTutorial '/storage/nvme5/new_clones/Mathematica/TimelineSignalsTutorial' &
git clone https://github.com/hcrypt-project/libScarab '/storage/nvme5/new_clones/Mathematica/libScarab' &
git clone https://github.com/motion-twin/hammerfest '/storage/nvme5/new_clones/Mathematica/hammerfest' &
git clone https://github.com/Autodesk/bifrost-usd '/storage/nvme5/new_clones/Mathematica/bifrost-usd' &
git clone https://github.com/cekdahl/jSoupLink '/storage/nvme5/new_clones/Mathematica/jSoupLink' &
git clone https://github.com/daniel-ilett/rain-urp '/storage/nvme5/new_clones/Mathematica/rain-urp' &
git clone https://github.com/adamtuliper/ZombiePumpkinSlayer '/storage/nvme5/new_clones/Mathematica/ZombiePumpkinSlayer' &
git clone https://github.com/likangning93/HRBF-Skin '/storage/nvme5/new_clones/Mathematica/HRBF-Skin' &
git clone https://github.com/skidvision/wolfram-language '/storage/nvme5/new_clones/Mathematica/wolfram-language' &
git clone https://github.com/mottosso/docker-deadline '/storage/nvme5/new_clones/Mathematica/docker-deadline' &
git clone https://github.com/ghorvath78/iltcme '/storage/nvme5/new_clones/Mathematica/iltcme' &
git clone https://github.com/cmendl/hubbard-dqmc '/storage/nvme5/new_clones/Mathematica/hubbard-dqmc' &
git clone https://github.com/GoldenArmor/HostileKingdom '/storage/nvme5/new_clones/Mathematica/HostileKingdom' &
git clone https://github.com/wjxway/PKU-shuakeji '/storage/nvme5/new_clones/Mathematica/PKU-shuakeji' &
git clone https://github.com/zhuwenzhen/instance-segmentation '/storage/nvme5/new_clones/Mathematica/instance-segmentation' &
git clone https://github.com/rogercolbeck/QI '/storage/nvme5/new_clones/Mathematica/QI' &
git clone https://github.com/intelligide/assimp-unity '/storage/nvme5/new_clones/Mathematica/assimp-unity' &
git clone https://github.com/hpd/PBRTForMaya '/storage/nvme5/new_clones/Mathematica/PBRTForMaya' &
git clone https://github.com/ssmit1986/BayesianInference '/storage/nvme5/new_clones/Mathematica/BayesianInference' &
git clone https://github.com/Raphael2048/URPTAA '/storage/nvme5/new_clones/Mathematica/URPTAA' &
git clone https://github.com/kattkieru/medium_def_layers '/storage/nvme5/new_clones/Mathematica/medium_def_layers' &
git clone https://github.com/VictorYudin/switch '/storage/nvme5/new_clones/Mathematica/switch' &
git clone https://github.com/ValdemarOrn/SharpSoundPlugins '/storage/nvme5/new_clones/Mathematica/SharpSoundPlugins' &
git clone https://github.com/msg-byu/autoGR '/storage/nvme5/new_clones/Mathematica/autoGR' &
git clone https://github.com/peter8rabit/TokyoTech-Graduate-Exam '/storage/nvme5/new_clones/Mathematica/TokyoTech-Graduate-Exam' &
git clone https://github.com/daniel-ilett/metaballs-urp '/storage/nvme5/new_clones/Mathematica/metaballs-urp' &
git clone https://github.com/dracula/wolfram-notebooks '/storage/nvme5/new_clones/Mathematica/wolfram-notebooks' &
git clone https://github.com/modelingcovid/covidmodel '/storage/nvme5/new_clones/Mathematica/covidmodel' &
git clone https://github.com/daniel-ilett/shaders-wall-cutout '/storage/nvme5/new_clones/Mathematica/shaders-wall-cutout' &
git clone https://github.com/arnoudbuzing/wolfram-coronavirus '/storage/nvme5/new_clones/Mathematica/wolfram-coronavirus' &
git clone https://github.com/RuleBasedIntegration/Rubi-5 '/storage/nvme5/new_clones/Mathematica/Rubi-5' &
git clone https://github.com/correlllab/cu-droplet '/storage/nvme5/new_clones/Mathematica/cu-droplet' &
git clone https://github.com/ITensor/ITensorInfiniteMPS.jl '/storage/nvme5/new_clones/Mathematica/ITensorInfiniteMPS.jl' &
git clone https://github.com/KostasAAA/FeaxRenderer '/storage/nvme5/new_clones/Mathematica/FeaxRenderer' &
git clone https://github.com/dgerosa/precession '/storage/nvme5/new_clones/Mathematica/precession' &
git clone https://github.com/erocarrera/pythonika '/storage/nvme5/new_clones/Mathematica/pythonika' &
git clone https://github.com/joshburkart/mathematica-mcmc '/storage/nvme5/new_clones/Mathematica/mathematica-mcmc' &
git clone https://github.com/nielsw2/ACM20030-Examples '/storage/nvme5/new_clones/Mathematica/ACM20030-Examples' &
git clone https://github.com/arnoudbuzing/webtools '/storage/nvme5/new_clones/Mathematica/webtools' &
git clone https://github.com/WolframResearch/draw '/storage/nvme5/new_clones/Mathematica/draw' &
git clone https://github.com/b3m2a1/mathematica-tools '/storage/nvme5/new_clones/Mathematica/mathematica-tools' &
git clone https://github.com/MMA-ForScience/ForScience '/storage/nvme5/new_clones/Mathematica/ForScience' &
git clone https://github.com/cmendl/LBM-classic '/storage/nvme5/new_clones/Mathematica/LBM-classic' &
git clone https://github.com/yxlllc/Mathematica-Voice-Kernel-Codes '/storage/nvme5/new_clones/Mathematica/Mathematica-Voice-Kernel-Codes' &
git clone https://github.com/daniel-ilett/shaders-snow-layers '/storage/nvme5/new_clones/Mathematica/shaders-snow-layers' &
git clone https://github.com/Khev/swarmalators '/storage/nvme5/new_clones/Mathematica/swarmalators' &
git clone https://github.com/sienaiwun/unity_lightcookie_caustic '/storage/nvme5/new_clones/Mathematica/unity_lightcookie_caustic' &
git clone https://github.com/hogjonny/Maya-PBR-BRDF-VP2 '/storage/nvme5/new_clones/Mathematica/Maya-PBR-BRDF-VP2' &
git clone https://github.com/RavEngine/Samples '/storage/nvme5/new_clones/Mathematica/Samples' &
git clone https://github.com/WolframChinaWL/WLProgramingTraining '/storage/nvme5/new_clones/Mathematica/WLProgramingTraining' &
git clone https://github.com/AUMAG/magcode '/storage/nvme5/new_clones/Mathematica/magcode' &
git clone https://github.com/gvarnavi/generative-art-iap '/storage/nvme5/new_clones/Mathematica/generative-art-iap' &
git clone https://github.com/PeterOvermann/TriadicMemory '/storage/nvme5/new_clones/Mathematica/TriadicMemory' &
git clone https://github.com/daniel-ilett/shaders-ice '/storage/nvme5/new_clones/Mathematica/shaders-ice' &
git clone https://github.com/ViktorQvarfordt/Sublime-WolframLanguage '/storage/nvme5/new_clones/Mathematica/Sublime-WolframLanguage' &
git clone https://github.com/openjdk/duke '/storage/nvme5/new_clones/Mathematica/duke' &
git clone https://github.com/Viktor286/FMCR '/storage/nvme5/new_clones/Mathematica/FMCR' &
git clone https://github.com/arnoudbuzing/prototypes '/storage/nvme5/new_clones/Mathematica/prototypes' &
git clone https://github.com/JonathanGorard/Categorica '/storage/nvme5/new_clones/Mathematica/Categorica' &
git clone https://github.com/Technical-Incerto-Reading-Club/code-examples '/storage/nvme5/new_clones/Mathematica/code-examples' &
git clone https://github.com/daniel-ilett/glitter-urp '/storage/nvme5/new_clones/Mathematica/glitter-urp' &
git clone https://github.com/paclets/PacletServer '/storage/nvme5/new_clones/Mathematica/PacletServer' &
git clone https://github.com/n1ckfg/ITP_OpenSourceAnimation '/storage/nvme5/new_clones/Mathematica/ITP_OpenSourceAnimation' &
git clone https://github.com/QTechTheory/QuESTlink '/storage/nvme5/new_clones/Mathematica/QuESTlink' &
git clone https://github.com/chriswolfram/OpenAILink '/storage/nvme5/new_clones/Mathematica/OpenAILink' &
git clone https://github.com/anabrid/pyanalog '/storage/nvme5/new_clones/Mathematica/pyanalog' &
git clone https://github.com/disasteroftheuniverse/SuperQuest '/storage/nvme5/new_clones/Mathematica/SuperQuest' &
git clone https://github.com/jmlopez-rod/ApplicationMaker '/storage/nvme5/new_clones/Mathematica/ApplicationMaker' &
git clone https://github.com/c3m-labs/MeshTools '/storage/nvme5/new_clones/Mathematica/MeshTools' &
git clone https://github.com/kubaPod/DevTools '/storage/nvme5/new_clones/Mathematica/DevTools' &
git clone https://github.com/baseapp/wordpress-malware-scanner '/storage/nvme5/new_clones/Mathematica/wordpress-malware-scanner' &
git clone https://github.com/league1991/MpmMaya '/storage/nvme5/new_clones/Mathematica/MpmMaya' &
git clone https://github.com/kenrube/Esopoly '/storage/nvme5/new_clones/Mathematica/Esopoly' &
git clone https://github.com/yantor3d/mechCatRig '/storage/nvme5/new_clones/Mathematica/mechCatRig' &
git clone https://github.com/dlfivefifty/RHPackage '/storage/nvme5/new_clones/Mathematica/RHPackage' &
git clone https://github.com/rat-pac/rat-pac '/storage/nvme5/new_clones/Mathematica/rat-pac' &
git clone https://github.com/jcowles/AutoPaintVFX '/storage/nvme5/new_clones/Mathematica/AutoPaintVFX' &
git clone https://github.com/APJansen/QNMspectral '/storage/nvme5/new_clones/Mathematica/QNMspectral' &
git clone https://github.com/subing85/subins_tutorials '/storage/nvme5/new_clones/Mathematica/subins_tutorials' &
git clone https://github.com/daniel-ilett/shaders-halftone '/storage/nvme5/new_clones/Mathematica/shaders-halftone' &
git clone https://github.com/bitcraftlab/Principia-Textilica-Course '/storage/nvme5/new_clones/Mathematica/Principia-Textilica-Course' &
git clone https://github.com/BlackHolePerturbationToolkit/KerrGeodesics '/storage/nvme5/new_clones/Mathematica/KerrGeodesics' &
git clone https://github.com/xslittlegrass/POVRayRender-For-Mathematica '/storage/nvme5/new_clones/Mathematica/POVRayRender-For-Mathematica' &
git clone https://github.com/mfroeling/UNET '/storage/nvme5/new_clones/Mathematica/UNET' &
git clone https://github.com/hoffmannjordan/insect-wing-venation-patterns '/storage/nvme5/new_clones/Mathematica/insect-wing-venation-patterns' &
git clone https://github.com/quantum-mob/QuantumPlaybook '/storage/nvme5/new_clones/Mathematica/QuantumPlaybook' &
git clone https://github.com/fengkan/Yuno_HDRP '/storage/nvme5/new_clones/Mathematica/Yuno_HDRP' &
git clone https://github.com/renaudll/omtk '/storage/nvme5/new_clones/Mathematica/omtk' &
git clone https://github.com/DsixTools/DsixTools '/storage/nvme5/new_clones/Mathematica/DsixTools' &
git clone https://github.com/Hexlet/QF101 '/storage/nvme5/new_clones/Mathematica/QF101' &
git clone https://github.com/valkyrie-language/valkyrie-document '/storage/nvme5/new_clones/Mathematica/valkyrie-document' &
git clone https://github.com/oovm/Deus '/storage/nvme5/new_clones/Mathematica/Deus' &
git clone https://github.com/yxlllc/SMSP-Compiler-For-Mathematica '/storage/nvme5/new_clones/Mathematica/SMSP-Compiler-For-Mathematica' &
git clone https://github.com/WolframResearch/AWSLambda-WolframLanguage '/storage/nvme5/new_clones/Mathematica/AWSLambda-WolframLanguage' &
git clone https://github.com/pierrexyz/pybird '/storage/nvme5/new_clones/Mathematica/pybird' &
git clone https://github.com/faysou/MTools '/storage/nvme5/new_clones/Mathematica/MTools' &
git clone https://github.com/Nevensky/plotly-mathematica '/storage/nvme5/new_clones/Mathematica/plotly-mathematica' &
git clone https://github.com/njpipeorgan/L1000-bayesian '/storage/nvme5/new_clones/Mathematica/L1000-bayesian' &
git clone https://github.com/matrixbud/Road-To-Reality '/storage/nvme5/new_clones/Mathematica/Road-To-Reality' &
git clone https://github.com/joshburkart/mathematica-autobackup '/storage/nvme5/new_clones/Mathematica/mathematica-autobackup' &
git clone https://github.com/muigaiunaka/AR-Game '/storage/nvme5/new_clones/Mathematica/AR-Game' &
git clone https://github.com/ssmit1986/DualNumbers '/storage/nvme5/new_clones/Mathematica/DualNumbers' &
git clone https://github.com/wjxway/EasyEinsteinSummation '/storage/nvme5/new_clones/Mathematica/EasyEinsteinSummation' &
git clone https://github.com/parzival-roethlein/prmaya '/storage/nvme5/new_clones/Mathematica/prmaya' &
git clone https://github.com/Stianpr20/MaXrd '/storage/nvme5/new_clones/Mathematica/MaXrd' &
git clone https://github.com/smrfeld/Total-Variation-Regularization-Derivative-Python '/storage/nvme5/new_clones/Mathematica/Total-Variation-Regularization-Derivative-Python' &
git clone https://github.com/oovm/CV_List '/storage/nvme5/new_clones/Mathematica/CV_List' &
git clone https://github.com/DrapeTester/ClothDrapeTester '/storage/nvme5/new_clones/Mathematica/ClothDrapeTester' &
git clone https://github.com/daniel-ilett/ps1-affine-shader '/storage/nvme5/new_clones/Mathematica/ps1-affine-shader' &
git clone https://github.com/mo-geometry/hopf_fibration '/storage/nvme5/new_clones/Mathematica/hopf_fibration' &
git clone https://github.com/miketon/Maya_Tools '/storage/nvme5/new_clones/Mathematica/Maya_Tools' &
git clone https://github.com/jmkendallbar/VisualizingLifeintheDeep '/storage/nvme5/new_clones/Mathematica/VisualizingLifeintheDeep' &
git clone https://github.com/unkaval/VHH '/storage/nvme5/new_clones/Mathematica/VHH' &
git clone https://github.com/WolframResearch/WL-FunctionCompile-CI-Template '/storage/nvme5/new_clones/Mathematica/WL-FunctionCompile-CI-Template' &
git clone https://github.com/Bozenton/Robotics_Matlab '/storage/nvme5/new_clones/Mathematica/Robotics_Matlab' &
git clone https://github.com/mjmvisser/studiolibrary '/storage/nvme5/new_clones/Mathematica/studiolibrary' &
git clone https://github.com/lookbothways/vfxTools '/storage/nvme5/new_clones/Mathematica/vfxTools' &
git clone https://github.com/LePtC/MaticaGuokr '/storage/nvme5/new_clones/Mathematica/MaticaGuokr' &
git clone https://github.com/brismu/klesi '/storage/nvme5/new_clones/Mathematica/klesi' &
git clone https://github.com/kmisiunas/ffmpeg-mathematica '/storage/nvme5/new_clones/Mathematica/ffmpeg-mathematica' &
git clone https://github.com/jasongrout/linear-algebra '/storage/nvme5/new_clones/Mathematica/linear-algebra' &
git clone https://github.com/kaist-silab/arcsim '/storage/nvme5/new_clones/Mathematica/arcsim' &
git clone https://github.com/misho104/FeynLecture '/storage/nvme5/new_clones/Mathematica/FeynLecture' &
git clone https://github.com/b3m2a1/EasyIDE '/storage/nvme5/new_clones/Mathematica/EasyIDE' &
git clone https://github.com/blab/global-migration '/storage/nvme5/new_clones/Mathematica/global-migration' &
git clone https://github.com/Ludwiggle/JWLX '/storage/nvme5/new_clones/Mathematica/JWLX' &
git clone https://github.com/halirutan/Mathematica-SE-Tools '/storage/nvme5/new_clones/Mathematica/Mathematica-SE-Tools' &
git clone https://github.com/BlackHolePerturbationToolkit/Teukolsky '/storage/nvme5/new_clones/Mathematica/Teukolsky' &
git clone https://github.com/abduld/WebGPU '/storage/nvme5/new_clones/Mathematica/WebGPU' &
git clone https://github.com/evangelism/DevCon-School '/storage/nvme5/new_clones/Mathematica/DevCon-School' &
git clone https://github.com/HeyMaslo/companion-server '/storage/nvme5/new_clones/Mathematica/companion-server' &
git clone https://github.com/jdechalendar/pnm-generation '/storage/nvme5/new_clones/Mathematica/pnm-generation' &
git clone https://github.com/bazhenov/twitter-spam-detector '/storage/nvme5/new_clones/Mathematica/twitter-spam-detector' &
git clone https://github.com/arkulo56/thought '/storage/nvme5/new_clones/Mathematica/thought' &
git clone https://github.com/taliesinb/MathTools '/storage/nvme5/new_clones/Mathematica/MathTools' &
git clone https://github.com/zhou13/arcsim '/storage/nvme5/new_clones/Mathematica/arcsim' &
git clone https://github.com/1ucasvb/interleaver '/storage/nvme5/new_clones/Mathematica/interleaver' &
git clone https://github.com/oovm/polynomial-roots-fractal '/storage/nvme5/new_clones/Mathematica/polynomial-roots-fractal' &
git clone https://github.com/gwiederhecker/ToPython '/storage/nvme5/new_clones/Mathematica/ToPython' &
git clone https://github.com/dbridges/mea-tools '/storage/nvme5/new_clones/Mathematica/mea-tools' &
git clone https://github.com/Seilim/CaffeLink '/storage/nvme5/new_clones/Mathematica/CaffeLink' &
git clone https://github.com/WolframResearch/GitLink-Talk '/storage/nvme5/new_clones/Mathematica/GitLink-Talk' &
git clone https://github.com/RoboticSwarmControl/robotica '/storage/nvme5/new_clones/Mathematica/robotica' &
git clone https://github.com/jmiszczak/qi '/storage/nvme5/new_clones/Mathematica/qi' &
git clone https://github.com/gallicchio/basicSDR '/storage/nvme5/new_clones/Mathematica/basicSDR' &
git clone https://github.com/trvrb/antigen '/storage/nvme5/new_clones/Mathematica/antigen' &
git clone https://github.com/carlwoll/MatrixD '/storage/nvme5/new_clones/Mathematica/MatrixD' &
git clone https://github.com/leijurv/reverse-fizzbuzz '/storage/nvme5/new_clones/Mathematica/reverse-fizzbuzz' &
git clone https://github.com/tyleryzhu/course-notes '/storage/nvme5/new_clones/Mathematica/course-notes' &
git clone https://github.com/marissa-graham/network-similarity '/storage/nvme5/new_clones/Mathematica/network-similarity' &
git clone https://github.com/blab/ncov-phylodynamics '/storage/nvme5/new_clones/Mathematica/ncov-phylodynamics' &
git clone https://github.com/oovm/WLNet-ModelZoo '/storage/nvme5/new_clones/Mathematica/WLNet-ModelZoo' &
git clone https://github.com/QuantumLiquids/Ising-model-on-lattice-of-C60 '/storage/nvme5/new_clones/Mathematica/Ising-model-on-lattice-of-C60' &
git clone https://github.com/lyc0930/AI-Homework '/storage/nvme5/new_clones/Mathematica/AI-Homework' &
git clone https://github.com/daniel-ilett/shaders-stylised-shield '/storage/nvme5/new_clones/Mathematica/shaders-stylised-shield' &
git clone https://github.com/pmolodo/pmHeatWeight '/storage/nvme5/new_clones/Mathematica/pmHeatWeight' &
git clone https://github.com/daniel-ilett/shaders-stealth-vision '/storage/nvme5/new_clones/Mathematica/shaders-stealth-vision' &
git clone https://github.com/yxli8023/yxli8023.github.io '/storage/nvme5/new_clones/Mathematica/yxli8023hub.io' &
git clone https://github.com/cklausme/EcoEvo '/storage/nvme5/new_clones/Mathematica/EcoEvo' &
git clone https://github.com/carltape/mtbeach '/storage/nvme5/new_clones/Mathematica/mtbeach' &
git clone https://github.com/daniel-ilett/sm64-painting-urp '/storage/nvme5/new_clones/Mathematica/sm64-painting-urp' &
git clone https://github.com/adamsingle/OmnidirectionalShaderGraph '/storage/nvme5/new_clones/Mathematica/OmnidirectionalShaderGraph' &
git clone https://github.com/daniel-ilett/bytesize-refraction '/storage/nvme5/new_clones/Mathematica/bytesize-refraction' &
git clone https://github.com/mark-caprio/CustomTicks '/storage/nvme5/new_clones/Mathematica/CustomTicks' &
git clone https://github.com/sienaiwun/Unity_Underwater_Lighting '/storage/nvme5/new_clones/Mathematica/Unity_Underwater_Lighting' &
git clone https://github.com/mgear-dev/Data-centric_rigging_sample_data '/storage/nvme5/new_clones/Mathematica/Data-centric_rigging_sample_data' &
git clone https://github.com/peeterjoot/mathematica '/storage/nvme5/new_clones/Mathematica/mathematica' &
git clone https://github.com/italic-r/maya-prefs '/storage/nvme5/new_clones/Mathematica/maya-prefs' &
git clone https://github.com/WolframResearch/CSSTools '/storage/nvme5/new_clones/Mathematica/CSSTools' &
git clone https://github.com/NCCA/Renderman '/storage/nvme5/new_clones/Mathematica/Renderman' &
git clone https://github.com/fbuessen/PhysicsLattice '/storage/nvme5/new_clones/Mathematica/PhysicsLattice' &
git clone https://github.com/miRoox/wolfram-action '/storage/nvme5/new_clones/Mathematica/wolfram-action' &
git clone https://github.com/libwaifu/BilibiliLink '/storage/nvme5/new_clones/Mathematica/BilibiliLink' &
git clone https://github.com/Richbabe/NPR_Lab '/storage/nvme5/new_clones/Mathematica/NPR_Lab' &
git clone https://github.com/abogatskiy/collatz '/storage/nvme5/new_clones/Mathematica/collatz' &
git clone https://github.com/zbjornson/MongoDBLink '/storage/nvme5/new_clones/Mathematica/MongoDBLink' &
git clone https://github.com/EverettYou/MatsubaraSum '/storage/nvme5/new_clones/Mathematica/MatsubaraSum' &
git clone https://github.com/divyekapoor/wifilocator '/storage/nvme5/new_clones/Mathematica/wifilocator' &
git clone https://github.com/jyotivasu/ARCore-Android '/storage/nvme5/new_clones/Mathematica/ARCore-Android' &
git clone https://github.com/solaAnt/SolaEngine '/storage/nvme5/new_clones/Mathematica/SolaEngine' &
git clone https://github.com/Haoran-Zhao/Jerk-continuous-online-trajectory-generator-with-constraints '/storage/nvme5/new_clones/Mathematica/Jerk-continuous-online-trajectory-generator-with-constraints' &
git clone https://github.com/Ra-Na/C3D4C1-Abaqus-UEL '/storage/nvme5/new_clones/Mathematica/C3D4C1-Abaqus-UEL' &
git clone https://github.com/daniel-ilett/shaders-pmd '/storage/nvme5/new_clones/Mathematica/shaders-pmd' &
git clone https://github.com/FishWoWater/ARCSim-For-SMPL '/storage/nvme5/new_clones/Mathematica/ARCSim-For-SMPL' &
git clone https://github.com/yoninazarathy/MATH7501-2021 '/storage/nvme5/new_clones/Mathematica/MATH7501-2021' &
git clone https://github.com/EverettYou/everettyou.github.io '/storage/nvme5/new_clones/Mathematica/everettyouhub.io' &
git clone https://github.com/daniel-ilett/shaders-botw-bomb '/storage/nvme5/new_clones/Mathematica/shaders-botw-bomb' &
git clone https://github.com/WolframResearch/MongoLink '/storage/nvme5/new_clones/Mathematica/MongoLink' &
git clone https://github.com/Riebart/EmpyrionGSTools '/storage/nvme5/new_clones/Mathematica/EmpyrionGSTools' &
git clone https://github.com/InterImm/exoplanets '/storage/nvme5/new_clones/Mathematica/exoplanets' &
git clone https://github.com/rebcabin/kalman-folding '/storage/nvme5/new_clones/Mathematica/kalman-folding' &
git clone https://github.com/hsayama/COVID-19-geographical-animations '/storage/nvme5/new_clones/Mathematica/COVID-19-geographical-animations' &
git clone https://github.com/NetLogo/Mathematica-Link '/storage/nvme5/new_clones/Mathematica/Mathematica-Link' &
git clone https://github.com/zuchengchen/Mathematica_Tutorials '/storage/nvme5/new_clones/Mathematica/Mathematica_Tutorials' &
git clone https://github.com/drybalka/SimpleTensor '/storage/nvme5/new_clones/Mathematica/SimpleTensor' &
git clone https://github.com/szhorvat/BoolEval '/storage/nvme5/new_clones/Mathematica/BoolEval' &
git clone https://github.com/ithilwing/MIPT-LABS '/storage/nvme5/new_clones/Mathematica/MIPT-LABS' &
git clone https://github.com/geyang/deep_learning_papers_TLDR '/storage/nvme5/new_clones/Mathematica/deep_learning_papers_TLDR' &
git clone https://github.com/maziarraissi/DeepTurbulence '/storage/nvme5/new_clones/Mathematica/DeepTurbulence' &
git clone https://github.com/adendek/DeepLaetitia '/storage/nvme5/new_clones/Mathematica/DeepLaetitia' &
git clone https://github.com/catrasca/RadarChart '/storage/nvme5/new_clones/Mathematica/RadarChart' &
git clone https://github.com/reggiebernardo/notebooks '/storage/nvme5/new_clones/Mathematica/notebooks' &
git clone https://github.com/WolframResearch/semantic-math '/storage/nvme5/new_clones/Mathematica/semantic-math' &
git clone https://github.com/andrew-yule/ggplot '/storage/nvme5/new_clones/Mathematica/ggplot' &
git clone https://github.com/magv/alibrary '/storage/nvme5/new_clones/Mathematica/alibrary' &
git clone https://github.com/t3kt/experiments '/storage/nvme5/new_clones/Mathematica/experiments' &
git clone https://github.com/FeynCalc/feynonium '/storage/nvme5/new_clones/Mathematica/feynonium' &
git clone https://github.com/mwkmwkmwk/cpuadventure2 '/storage/nvme5/new_clones/Mathematica/cpuadventure2' &
git clone https://github.com/heitorc7/oDMRG '/storage/nvme5/new_clones/Mathematica/oDMRG' &
git clone https://github.com/lair001/rosen-discrete-math-materials '/storage/nvme5/new_clones/Mathematica/rosen-discrete-math-materials' &
git clone https://github.com/Nekhaevalex/Labs '/storage/nvme5/new_clones/Mathematica/Labs' &
git clone https://github.com/2youyou2/shader-graph-examples '/storage/nvme5/new_clones/Mathematica/shader-graph-examples' &
git clone https://github.com/daniel-ilett/shaders-retro '/storage/nvme5/new_clones/Mathematica/shaders-retro' &
git clone https://github.com/c3m-labs/ImportMesh '/storage/nvme5/new_clones/Mathematica/ImportMesh' &
git clone https://github.com/kubaPod/MPM '/storage/nvme5/new_clones/Mathematica/MPM' &
git clone https://github.com/KendallPark/cxr-ct '/storage/nvme5/new_clones/Mathematica/cxr-ct' &
git clone https://github.com/williamjturkel/Digital-Research-Methods-2nd-Ed '/storage/nvme5/new_clones/Mathematica/Digital-Research-Methods-2nd-Ed' &
git clone https://github.com/juanklopper/Deep-learning-using-R '/storage/nvme5/new_clones/Mathematica/Deep-learning-using-R' &
git clone https://github.com/williamjturkel/Digital-Research-Methods '/storage/nvme5/new_clones/Mathematica/Digital-Research-Methods' &
git clone https://github.com/asdasd1dsadsa/RubiSteps '/storage/nvme5/new_clones/Mathematica/RubiSteps' &
git clone https://github.com/charapennikaurm/BSU '/storage/nvme5/new_clones/Mathematica/BSU' &
git clone https://github.com/jmalonzo/tl-wordlist '/storage/nvme5/new_clones/Mathematica/tl-wordlist' &
git clone https://github.com/peraro/finiteflow-mathtools '/storage/nvme5/new_clones/Mathematica/finiteflow-mathtools' &
git clone https://github.com/laifuyu/curveDeformer '/storage/nvme5/new_clones/Mathematica/curveDeformer' &
git clone https://github.com/AlephAlpha/LifeFind '/storage/nvme5/new_clones/Mathematica/LifeFind' &
git clone https://github.com/rquintero-88/eomccgen '/storage/nvme5/new_clones/Mathematica/eomccgen' &
git clone https://github.com/jnoronhahostler/Neutron_Star_EOS '/storage/nvme5/new_clones/Mathematica/Neutron_Star_EOS' &
git clone https://github.com/wjxway/Small_Projects_With_Mathematica '/storage/nvme5/new_clones/Mathematica/Small_Projects_With_Mathematica' &
git clone https://github.com/BioMedBigDataCenter/VENAS '/storage/nvme5/new_clones/Mathematica/VENAS' &
git clone https://github.com/Unity-Technologies/ziva-vfx-utils '/storage/nvme5/new_clones/Mathematica/ziva-vfx-utils' &
git clone https://github.com/freedoom/attic '/storage/nvme5/new_clones/Mathematica/attic' &
git clone https://github.com/data-gymnasia/courses '/storage/nvme5/new_clones/Mathematica/courses' &
git clone https://github.com/dbigham/ARC '/storage/nvme5/new_clones/Mathematica/ARC' &
git clone https://github.com/vasilsaroka/TBpack '/storage/nvme5/new_clones/Mathematica/TBpack' &
git clone https://github.com/felixchenfy/API_for_Simulating_Multi-Link_System '/storage/nvme5/new_clones/Mathematica/API_for_Simulating_Multi-Link_System' &
git clone https://github.com/SuZhangs/MathModel-From-0-To-Inf '/storage/nvme5/new_clones/Mathematica/MathModel-From-0-To-Inf' &
git clone https://github.com/tomrunia/arcsim '/storage/nvme5/new_clones/Mathematica/arcsim' &
git clone https://github.com/AndreHAM/Thermodynamics-and-Statistical-Physics '/storage/nvme5/new_clones/Mathematica/Thermodynamics-and-Statistical-Physics' &
git clone https://github.com/UnityAnthony/Native_GPU_Profiling '/storage/nvme5/new_clones/Mathematica/Native_GPU_Profiling' &
git clone https://github.com/cmendl/tensor_networks '/storage/nvme5/new_clones/Mathematica/tensor_networks' &
git clone https://github.com/ssmit1986/lazyLists '/storage/nvme5/new_clones/Mathematica/lazyLists' &
git clone https://github.com/JYNi16/MatheMatica-Solution-for-Hubbard-model '/storage/nvme5/new_clones/Mathematica/MatheMatica-Solution-for-Hubbard-model' &
git clone https://github.com/wjxway/WSA-Presentation '/storage/nvme5/new_clones/Mathematica/WSA-Presentation' &
git clone https://github.com/SEULinuxClub/DaLaoZiLiao '/storage/nvme5/new_clones/Mathematica/DaLaoZiLiao' &
git clone https://github.com/rodluger/Limbdark.jl '/storage/nvme5/new_clones/Mathematica/Limbdark.jl' &
git clone https://github.com/trvrb/PACT '/storage/nvme5/new_clones/Mathematica/PACT' &
git clone https://github.com/AlexeyPopkov/PolygonPlotMarkers '/storage/nvme5/new_clones/Mathematica/PolygonPlotMarkers' &
git clone https://github.com/alihashmiii/UNet-Segmentation-Wolfram '/storage/nvme5/new_clones/Mathematica/UNet-Segmentation-Wolfram' &
git clone https://github.com/BJTU-MIMO/RIS_Practical '/storage/nvme5/new_clones/Mathematica/RIS_Practical' &
git clone https://github.com/blab/ncov-wa-d614g '/storage/nvme5/new_clones/Mathematica/ncov-wa-d614g' &
git clone https://github.com/episanty/RB-SFA '/storage/nvme5/new_clones/Mathematica/RB-SFA' &
git clone https://github.com/yycho0108/GraphSlam3D '/storage/nvme5/new_clones/Mathematica/GraphSlam3D' &
git clone https://github.com/llamacademy/urp-decal-projector '/storage/nvme5/new_clones/Mathematica/urp-decal-projector' &
git clone https://github.com/obstudio/ThuliumMusic-WL '/storage/nvme5/new_clones/Mathematica/ThuliumMusic-WL' &
git clone https://github.com/jpmaus/deep-learning-sndbx '/storage/nvme5/new_clones/Mathematica/deep-learning-sndbx' &
git clone https://github.com/Antenna-Genesis/EM_Journey '/storage/nvme5/new_clones/Mathematica/EM_Journey' &
git clone https://github.com/mresources/tutorial '/storage/nvme5/new_clones/Mathematica/tutorial' &
git clone https://github.com/WolframChinaWL/MachineLearningBasic '/storage/nvme5/new_clones/Mathematica/MachineLearningBasic' &
git clone https://github.com/EdinburghNLP/mtm19 '/storage/nvme5/new_clones/Mathematica/mtm19' &
git clone https://github.com/alihashmiii/Elliptical-Fourier-Descriptors '/storage/nvme5/new_clones/Mathematica/Elliptical-Fourier-Descriptors' &
git clone https://github.com/oovm/ChineseNLP '/storage/nvme5/new_clones/Mathematica/ChineseNLP' &
git clone https://github.com/wdas/shell-obstacle-course '/storage/nvme5/new_clones/Mathematica/shell-obstacle-course' &
git clone https://github.com/GeoffCope/Gravitational_Wave '/storage/nvme5/new_clones/Mathematica/Gravitational_Wave' &
git clone https://github.com/GZHoffie/VE401-recitation-class '/storage/nvme5/new_clones/Mathematica/VE401-recitation-class' &
git clone https://github.com/kenkangxgwe/Matypetica '/storage/nvme5/new_clones/Mathematica/Matypetica' &
git clone https://github.com/regymm/USTCcomputer '/storage/nvme5/new_clones/Mathematica/USTCcomputer' &
git clone https://github.com/jfrancis71/CognitoNet '/storage/nvme5/new_clones/Mathematica/CognitoNet' &
git clone https://github.com/BlackHolePerturbationToolkit/MathematicaToolkitExamples '/storage/nvme5/new_clones/Mathematica/MathematicaToolkitExamples' &
git clone https://github.com/ChenYangyao/computationalphysics_N2013301020169 '/storage/nvme5/new_clones/Mathematica/computationalphysics_N2013301020169' &
git clone https://github.com/paolofinelli/Theoretical-and-Numerical-Nuclear-Physics-Course '/storage/nvme5/new_clones/Mathematica/Theoretical-and-Numerical-Nuclear-Physics-Course' &
git clone https://github.com/dishmint/Markdown2WL '/storage/nvme5/new_clones/Mathematica/Markdown2WL' &
git clone https://github.com/web-archive-group/WAHR '/storage/nvme5/new_clones/Mathematica/WAHR' &
git clone https://github.com/erashed/ForkNet '/storage/nvme5/new_clones/Mathematica/ForkNet' &
git clone https://github.com/frex-e/jmssTools '/storage/nvme5/new_clones/Mathematica/jmssTools' &
git clone https://github.com/lr94/NumPyArray '/storage/nvme5/new_clones/Mathematica/NumPyArray' &
git clone https://github.com/nr-codes/BipedalGaitGeneration '/storage/nvme5/new_clones/Mathematica/BipedalGaitGeneration' &
git clone https://github.com/stared/qubism '/storage/nvme5/new_clones/Mathematica/qubism' &
git clone https://github.com/hizzlehoff/FaceCapCustomAvatarExporter '/storage/nvme5/new_clones/Mathematica/FaceCapCustomAvatarExporter' &
git clone https://github.com/Swaddle/nnQcompiler '/storage/nvme5/new_clones/Mathematica/nnQcompiler' &
git clone https://github.com/UT-team/INITIAL '/storage/nvme5/new_clones/Mathematica/INITIAL' &
git clone https://github.com/shizuo-kaji/Kaleidocycle '/storage/nvme5/new_clones/Mathematica/Kaleidocycle' &
git clone https://github.com/WolframResearch/Data-Curation-Training '/storage/nvme5/new_clones/Mathematica/Data-Curation-Training' &
git clone https://github.com/HEPcodes/FeynRules '/storage/nvme5/new_clones/Mathematica/FeynRules' &
git clone https://github.com/mincongzhang/3D_Retrieval_scan2search '/storage/nvme5/new_clones/Mathematica/3D_Retrieval_scan2search' &
git clone https://github.com/dilmerv/UnityClothEffectsHDRP '/storage/nvme5/new_clones/Mathematica/UnityClothEffectsHDRP' &
git clone https://github.com/tpfto/MoleculeViewer '/storage/nvme5/new_clones/Mathematica/MoleculeViewer' &
git clone https://github.com/AGL-web-applications/webapp-samples '/storage/nvme5/new_clones/Mathematica/webapp-samples' &
git clone https://github.com/ahrvoje/numerics '/storage/nvme5/new_clones/Mathematica/numerics' &
git clone https://github.com/mit-plv/reification-by-parametricity '/storage/nvme5/new_clones/Mathematica/reification-by-parametricity' &
git clone https://github.com/amoraglio/GSGP '/storage/nvme5/new_clones/Mathematica/GSGP' &
git clone https://github.com/vallis/lisatools '/storage/nvme5/new_clones/Mathematica/lisatools' &
git clone https://github.com/rsmenon/ColorBar '/storage/nvme5/new_clones/Mathematica/ColorBar' &
git clone https://github.com/AccelerationMethods/AccelerationMonograph '/storage/nvme5/new_clones/Mathematica/AccelerationMonograph' &
git clone https://github.com/ConnorGray/wolfram-cli '/storage/nvme5/new_clones/Mathematica/wolfram-cli' &
git clone https://github.com/yumayanagisawa/Unity-Visual-Effects-Graph-Practice '/storage/nvme5/new_clones/Mathematica/Unity-Visual-Effects-Graph-Practice' &
git clone https://github.com/ianhinder/EccentricIMR '/storage/nvme5/new_clones/Mathematica/EccentricIMR' &
git clone https://github.com/WolframResearch/PacletCICD '/storage/nvme5/new_clones/Mathematica/PacletCICD' &
git clone https://github.com/oovm/WolframFunctionRepository '/storage/nvme5/new_clones/Mathematica/WolframFunctionRepository' &
git clone https://github.com/JamelSaadaoui/EconMacroBlog '/storage/nvme5/new_clones/Mathematica/EconMacroBlog' &
git clone https://github.com/drfuzzyness/Simple-City '/storage/nvme5/new_clones/Mathematica/Simple-City' &
git clone https://github.com/mpoulshock/HammurabiProject '/storage/nvme5/new_clones/Mathematica/HammurabiProject' &
git clone https://github.com/gmiaslab/mathiomica '/storage/nvme5/new_clones/Mathematica/mathiomica' &
git clone https://github.com/himeinhardt/TuGames '/storage/nvme5/new_clones/Mathematica/TuGames' &
git clone https://github.com/empyriumz/Numerical-Berry-curvature '/storage/nvme5/new_clones/Mathematica/Numerical-Berry-curvature' &
git clone https://github.com/dzungpng/brick-optimization-builder '/storage/nvme5/new_clones/Mathematica/brick-optimization-builder' &
git clone https://github.com/lab-cosmo/nice '/storage/nvme5/new_clones/Mathematica/nice' &
git clone https://github.com/litinski/magicstates '/storage/nvme5/new_clones/Mathematica/magicstates' &
git clone https://github.com/Shovan-Physics/cDMRG '/storage/nvme5/new_clones/Mathematica/cDMRG' &
git clone https://github.com/azagoruyko/rigpp_tentacle '/storage/nvme5/new_clones/Mathematica/rigpp_tentacle' &
git clone https://github.com/rolfmertig/Shortcuts '/storage/nvme5/new_clones/Mathematica/Shortcuts' &
git clone https://github.com/squibbylinux/LibreGreek '/storage/nvme5/new_clones/Mathematica/LibreGreek' &
git clone https://github.com/BlackHolePerturbationToolkit/SpinWeightedSpheroidalHarmonics '/storage/nvme5/new_clones/Mathematica/SpinWeightedSpheroidalHarmonics' &
git clone https://github.com/JarekDuda/SGD-OGR-Hessian-estimator '/storage/nvme5/new_clones/Mathematica/SGD-OGR-Hessian-estimator' &
git clone https://github.com/iitis/IntU '/storage/nvme5/new_clones/Mathematica/IntU' &
git clone https://github.com/BerSerK/notes '/storage/nvme5/new_clones/Mathematica/notes' &
git clone https://github.com/angelsophia1/Grass-Sway '/storage/nvme5/new_clones/Mathematica/Grass-Sway' &
git clone https://github.com/LRLVEC/BlackHoleRendering '/storage/nvme5/new_clones/Mathematica/BlackHoleRendering' &
git clone https://github.com/Dario-Rosa85/QuantumManyBody '/storage/nvme5/new_clones/Mathematica/QuantumManyBody' &
git clone https://github.com/QTechTheory/VQD '/storage/nvme5/new_clones/Mathematica/VQD' &
git clone https://github.com/francisco-chavez/SunTemple-Unity-HDRP '/storage/nvme5/new_clones/Mathematica/SunTemple-Unity-HDRP' &
git clone https://github.com/RobertFont/AlphaProject '/storage/nvme5/new_clones/Mathematica/AlphaProject' &
git clone https://github.com/To-Fujita/Babylon.js_3D_Graphics '/storage/nvme5/new_clones/Mathematica/Babylon.js_3D_Graphics' &
git clone https://github.com/JQIamo/eagle-config '/storage/nvme5/new_clones/Mathematica/eagle-config' &
git clone https://github.com/halirutan/MathematicaAutocompletionTweaker '/storage/nvme5/new_clones/Mathematica/MathematicaAutocompletionTweaker' &
git clone https://github.com/opencobra/MASS-Toolbox '/storage/nvme5/new_clones/Mathematica/MASS-Toolbox' &
git clone https://github.com/wasimk/maya-pole-vector-constaint '/storage/nvme5/new_clones/Mathematica/maya-pole-vector-constaint' &
git clone https://github.com/KMDaily/FlappyBird_WolframLanguage '/storage/nvme5/new_clones/Mathematica/FlappyBird_WolframLanguage' &
git clone https://github.com/amapoplar/Tzor '/storage/nvme5/new_clones/Mathematica/Tzor' &
git clone https://github.com/leixingyu/assetManager '/storage/nvme5/new_clones/Mathematica/assetManager' &
git clone https://github.com/maxisi/gwpols '/storage/nvme5/new_clones/Mathematica/gwpols' &
git clone https://github.com/decentraland/documentation '/storage/nvme5/new_clones/Mathematica/documentation' &
git clone https://github.com/sgbaird/LatticePlane '/storage/nvme5/new_clones/Mathematica/LatticePlane' &
git clone https://github.com/gerac83/clifford_toolbox '/storage/nvme5/new_clones/Mathematica/clifford_toolbox' &
git clone https://github.com/daniel-ilett/vfx-portal '/storage/nvme5/new_clones/Mathematica/vfx-portal' &
git clone https://github.com/XyhwX/particle '/storage/nvme5/new_clones/Mathematica/particle' &
git clone https://github.com/kacpertopol/printable_paper '/storage/nvme5/new_clones/Mathematica/printable_paper' &
git clone https://github.com/libwaifu/Waifu-X '/storage/nvme5/new_clones/Mathematica/Waifu-X' &
git clone https://github.com/tpfto/Carlson '/storage/nvme5/new_clones/Mathematica/Carlson' &
git clone https://github.com/bburky/mathematica-ctf-writeups '/storage/nvme5/new_clones/Mathematica/mathematica-ctf-writeups' &
git clone https://github.com/b3m2a1/SimpleDocs '/storage/nvme5/new_clones/Mathematica/SimpleDocs' &
git clone https://github.com/xenos1984/xPPN '/storage/nvme5/new_clones/Mathematica/xPPN' &
git clone https://github.com/UNAM-FESAc/Advncd_Prgrmmng '/storage/nvme5/new_clones/Mathematica/Advncd_Prgrmmng' &
git clone https://github.com/Dih5/TgBot '/storage/nvme5/new_clones/Mathematica/TgBot' &
git clone https://github.com/huvers/reservoir_computing '/storage/nvme5/new_clones/Mathematica/reservoir_computing' &
git clone https://github.com/WenchaoDing/kinodynamic_replanning '/storage/nvme5/new_clones/Mathematica/kinodynamic_replanning' &
git clone https://github.com/McDo/arcsim-smpl '/storage/nvme5/new_clones/Mathematica/arcsim-smpl' &
git clone https://github.com/andyyuan78/books '/storage/nvme5/new_clones/Mathematica/books' &
git clone https://github.com/paul-jean/wolfdown '/storage/nvme5/new_clones/Mathematica/wolfdown' &
git clone https://github.com/digamma-ai/weather-similarity '/storage/nvme5/new_clones/Mathematica/weather-similarity' &
git clone https://github.com/tdhopper/smo-svm '/storage/nvme5/new_clones/Mathematica/smo-svm' &
git clone https://github.com/subing85/subins-toolkits '/storage/nvme5/new_clones/Mathematica/subins-toolkits' &
git clone https://github.com/ddbaumann/cosmo-book '/storage/nvme5/new_clones/Mathematica/cosmo-book' &
git clone https://github.com/Diderot-Language/examples '/storage/nvme5/new_clones/Mathematica/examples' &
git clone https://github.com/mpoulshock/DataPrivacyComplianceAPI '/storage/nvme5/new_clones/Mathematica/DataPrivacyComplianceAPI' &
git clone https://github.com/panbaoxiang/RADA '/storage/nvme5/new_clones/Mathematica/RADA' &
git clone https://github.com/Dejavu0709/Plane-Shadow-For-URP '/storage/nvme5/new_clones/Mathematica/Plane-Shadow-For-URP' &
git clone https://github.com/SimonWoods/MathMF '/storage/nvme5/new_clones/Mathematica/MathMF' &
git clone https://github.com/radiatoryang/nyu_studio_spring2015 '/storage/nvme5/new_clones/Mathematica/nyu_studio_spring2015' &
git clone https://github.com/slashdotfield/SpectralBP '/storage/nvme5/new_clones/Mathematica/SpectralBP' &
git clone https://github.com/cekdahl/wl-wordpress-xmlrpc-client '/storage/nvme5/new_clones/Mathematica/wl-wordpress-xmlrpc-client' &
git clone https://github.com/BJTU-MIMO/mmWave_RIS_Performance_Optimization '/storage/nvme5/new_clones/Mathematica/mmWave_RIS_Performance_Optimization' &
git clone https://github.com/xAct-contrib/xPand '/storage/nvme5/new_clones/Mathematica/xPand' &
git clone https://github.com/accettullihuber/SpinorHelicity4D '/storage/nvme5/new_clones/Mathematica/SpinorHelicity4D' &
git clone https://github.com/zouharvi/ptakopet '/storage/nvme5/new_clones/Mathematica/ptakopet' &
git clone https://github.com/anaseinea/Fortnite-Effect-in-Unity-Shader-Graph '/storage/nvme5/new_clones/Mathematica/Fortnite-Effect-in-Unity-Shader-Graph' &
git clone https://github.com/gremdon/DLC_Shared_Project_2022 '/storage/nvme5/new_clones/Mathematica/DLC_Shared_Project_2022' &
git clone https://github.com/Kokenishii/Mario64Final '/storage/nvme5/new_clones/Mathematica/Mario64Final' &
git clone https://github.com/arnoudbuzing/wolfram-ansi-terminal '/storage/nvme5/new_clones/Mathematica/wolfram-ansi-terminal' &
git clone https://github.com/jkuczm/MathematicaTeXUtilities '/storage/nvme5/new_clones/Mathematica/MathematicaTeXUtilities' &
git clone https://github.com/BlackHolePerturbationToolkit/QuasiNormalModes '/storage/nvme5/new_clones/Mathematica/QuasiNormalModes' &
git clone https://github.com/WolframChinaWL/SymbolicComputation '/storage/nvme5/new_clones/Mathematica/SymbolicComputation' &
git clone https://github.com/jerryxyx/ExplicitImpliedVolatility '/storage/nvme5/new_clones/Mathematica/ExplicitImpliedVolatility' &
git clone https://github.com/lullcant/ECE4010J '/storage/nvme5/new_clones/Mathematica/ECE4010J' &
git clone https://github.com/DapperDino/UI-Toolkit-Tutorials '/storage/nvme5/new_clones/Mathematica/UI-Toolkit-Tutorials' &
git clone https://github.com/JHeimrath/TableTop '/storage/nvme5/new_clones/Mathematica/TableTop' &
git clone https://github.com/alihashmiii/3D-Vertex-Model '/storage/nvme5/new_clones/Mathematica/3D-Vertex-Model' &
git clone https://github.com/carlwoll/TensorSimplify '/storage/nvme5/new_clones/Mathematica/TensorSimplify' &
git clone https://github.com/garrett361/cmbpy '/storage/nvme5/new_clones/Mathematica/cmbpy' &
git clone https://github.com/NiraOfficial/niraclient '/storage/nvme5/new_clones/Mathematica/niraclient' &
git clone https://github.com/fredrikaverpil/fredrikaverpil.github.io '/storage/nvme5/new_clones/Mathematica/fredrikaverpilhub.io' &
git clone https://github.com/Braeden261/kendoSchool '/storage/nvme5/new_clones/Mathematica/kendoSchool' &
git clone https://github.com/dilmerv/OculusQuestUniversalRP '/storage/nvme5/new_clones/Mathematica/OculusQuestUniversalRP' &
git clone https://github.com/chuyiyao/Q-MAT '/storage/nvme5/new_clones/Mathematica/Q-MAT' &
git clone https://github.com/arturgower/MultipleScattering-Mathematica '/storage/nvme5/new_clones/Mathematica/MultipleScattering-Mathematica' &
git clone https://github.com/daneshtarapore/gazebo-asv '/storage/nvme5/new_clones/Mathematica/gazebo-asv' &
git clone https://github.com/zbjornson/MYaml '/storage/nvme5/new_clones/Mathematica/MYaml' &
git clone https://github.com/sameer/orient-stl '/storage/nvme5/new_clones/Mathematica/orient-stl' &
git clone https://github.com/RuthAndRoth/Reference '/storage/nvme5/new_clones/Mathematica/Reference' &
git clone https://github.com/mtw75/switch_qt '/storage/nvme5/new_clones/Mathematica/switch_qt' &
git clone https://github.com/b3m2a1/Ems '/storage/nvme5/new_clones/Mathematica/Ems' &
git clone https://github.com/saullocastro/panels '/storage/nvme5/new_clones/Mathematica/panels' &
git clone https://github.com/Harish-Research-Lab/FEAP-AceGen '/storage/nvme5/new_clones/Mathematica/FEAP-AceGen' &
git clone https://github.com/njculpin/agisoft_photogrametry '/storage/nvme5/new_clones/Mathematica/agisoft_photogrametry' &
git clone https://github.com/HighPT/HighPT '/storage/nvme5/new_clones/Mathematica/HighPT' &
git clone https://github.com/mjsottile/hsgep '/storage/nvme5/new_clones/Mathematica/hsgep' &
git clone https://github.com/hl-ren/Nonlocal_elasticity '/storage/nvme5/new_clones/Mathematica/Nonlocal_elasticity' &
git clone https://github.com/autistic-symposium/solar '/storage/nvme5/new_clones/Mathematica/solar' &
git clone https://github.com/lu-yu01/Unity_HDRP_Demo '/storage/nvme5/new_clones/Mathematica/Unity_HDRP_Demo' &
git clone https://github.com/RussellRuffolo/VoxelZombieWebGL '/storage/nvme5/new_clones/Mathematica/VoxelZombieWebGL' &
git clone https://github.com/game-ci/unity3d-appveyor-proof-of-concept '/storage/nvme5/new_clones/Mathematica/unity3d-appveyor-proof-of-concept' &
git clone https://github.com/philngo/ble-mathematica '/storage/nvme5/new_clones/Mathematica/ble-mathematica' &
git clone https://github.com/Latios96/redshift_playblast '/storage/nvme5/new_clones/Mathematica/redshift_playblast' &
git clone https://github.com/xuhao1/dSim '/storage/nvme5/new_clones/Mathematica/dSim' &
git clone https://github.com/oovm/EulerProject '/storage/nvme5/new_clones/Mathematica/EulerProject' &
git clone https://github.com/erashed/CondNet '/storage/nvme5/new_clones/Mathematica/CondNet' &
git clone https://github.com/ssmit1986/FunctionRepositoryFunctions '/storage/nvme5/new_clones/Mathematica/FunctionRepositoryFunctions' &
git clone https://github.com/johannesgerer/jburkardt-math '/storage/nvme5/new_clones/Mathematica/jburkardt-math' &
git clone https://github.com/BlackHolePerturbationToolkit/GeneralRelativityTensors '/storage/nvme5/new_clones/Mathematica/GeneralRelativityTensors' &
git clone https://github.com/jasondbiggs/DivergentColorMaps '/storage/nvme5/new_clones/Mathematica/DivergentColorMaps' &
git clone https://github.com/empter/DMRGwithMPSandMPO '/storage/nvme5/new_clones/Mathematica/DMRGwithMPSandMPO' &
git clone https://github.com/StanfordSNR/puffer-statistics '/storage/nvme5/new_clones/Mathematica/puffer-statistics' &
git clone https://github.com/yxlllc/WAPlayer '/storage/nvme5/new_clones/Mathematica/WAPlayer' &
git clone https://github.com/swccgpc/holotable '/storage/nvme5/new_clones/Mathematica/holotable' &
git clone https://github.com/sergisl/ringdown-calculations '/storage/nvme5/new_clones/Mathematica/ringdown-calculations' &
git clone https://github.com/QTechTheory/QuEST-ProjectQ-benchmarking '/storage/nvme5/new_clones/Mathematica/QuEST-ProjectQ-benchmarking' &
git clone https://github.com/comp-physics/QBMMlib '/storage/nvme5/new_clones/Mathematica/QBMMlib' &
git clone https://github.com/Schraiber/continuity '/storage/nvme5/new_clones/Mathematica/continuity' &
git clone https://github.com/RuleBasedIntegration/IntegrationRules '/storage/nvme5/new_clones/Mathematica/IntegrationRules' &
git clone https://github.com/jsyony37/thermoelectricbandmodel '/storage/nvme5/new_clones/Mathematica/thermoelectricbandmodel' &
git clone https://github.com/aqlaboratory/sh2-cancer '/storage/nvme5/new_clones/Mathematica/sh2-cancer' &
git clone https://github.com/demiurghg/FusionFramework '/storage/nvme5/new_clones/Mathematica/FusionFramework' &
git clone https://github.com/alexisakov/Economica '/storage/nvme5/new_clones/Mathematica/Economica' &
git clone https://github.com/WH57/lipid_covid19 '/storage/nvme5/new_clones/Mathematica/lipid_covid19' &
git clone https://github.com/frrad/optimization-368 '/storage/nvme5/new_clones/Mathematica/optimization-368' &
git clone https://github.com/akaanzo/2D_bloch_wave_propagation_metamaterial '/storage/nvme5/new_clones/Mathematica/2D_bloch_wave_propagation_metamaterial' &
git clone https://github.com/Genius-Society/mathematica_music_pack '/storage/nvme5/new_clones/Mathematica/mathematica_music_pack' &
git clone https://github.com/carlwoll/GraphicsInformation '/storage/nvme5/new_clones/Mathematica/GraphicsInformation' &
git clone https://github.com/ohnorobo/gibberish '/storage/nvme5/new_clones/Mathematica/gibberish' &
git clone https://github.com/Ludwiggle/wolfram-geany '/storage/nvme5/new_clones/Mathematica/wolfram-geany' &
git clone https://github.com/Raphael2048/URP_ForwardPlus '/storage/nvme5/new_clones/Mathematica/URP_ForwardPlus' &
git clone https://github.com/aethomsen/RGBeta '/storage/nvme5/new_clones/Mathematica/RGBeta' &
git clone https://github.com/superman-t/SoftRasterization '/storage/nvme5/new_clones/Mathematica/SoftRasterization' &
git clone https://github.com/antononcube/NIntegrateTheMissingManual-book '/storage/nvme5/new_clones/Mathematica/NIntegrateTheMissingManual-book' &
git clone https://github.com/ermo/s2u_ucp '/storage/nvme5/new_clones/Mathematica/s2u_ucp' &
git clone https://github.com/PostQuantum/Buckyball-Ising-Model '/storage/nvme5/new_clones/Mathematica/Buckyball-Ising-Model' &
git clone https://github.com/kubaPod/MoreCalculus '/storage/nvme5/new_clones/Mathematica/MoreCalculus' &
git clone https://github.com/kosmosmo/3D_NFT_Art_Generator_Maya '/storage/nvme5/new_clones/Mathematica/3D_NFT_Art_Generator_Maya' &
git clone https://github.com/kmisiunas/mathematica-comsol '/storage/nvme5/new_clones/Mathematica/mathematica-comsol' &
git clone https://github.com/jkuczm/SpinorsExtras '/storage/nvme5/new_clones/Mathematica/SpinorsExtras' &
git clone https://github.com/InterImm/marsCalendar '/storage/nvme5/new_clones/Mathematica/marsCalendar' &
git clone https://github.com/GriffinLab/BIFs '/storage/nvme5/new_clones/Mathematica/BIFs' &
git clone https://github.com/libwaifu/Waifu-SR '/storage/nvme5/new_clones/Mathematica/Waifu-SR' &
git clone https://github.com/szhorvat/MatchGraphics '/storage/nvme5/new_clones/Mathematica/MatchGraphics' &
git clone https://github.com/vimaec/au2019-unity-fbx-bim '/storage/nvme5/new_clones/Mathematica/au2019-unity-fbx-bim' &
git clone https://github.com/b3m2a1/mathematica-ChemTools '/storage/nvme5/new_clones/Mathematica/mathematica-ChemTools' &
git clone https://github.com/JonyEpsilon/flow '/storage/nvme5/new_clones/Mathematica/flow' &
git clone https://github.com/anchpop/endless-sea '/storage/nvme5/new_clones/Mathematica/endless-sea' &
git clone https://github.com/uwu/uwu.network '/storage/nvme5/new_clones/Mathematica/uwu.network' &
git clone https://github.com/HyperGroups/MathematicaMachineLearning '/storage/nvme5/new_clones/Mathematica/MathematicaMachineLearning' &
git clone https://github.com/lennrt/Interstellar-Wormhole-Ray-Tracing '/storage/nvme5/new_clones/Mathematica/Interstellar-Wormhole-Ray-Tracing' &
git clone https://github.com/KirillBelovTest/Objects '/storage/nvme5/new_clones/Mathematica/Objects' &
git clone https://github.com/bshoshany/spacetime-diagrams '/storage/nvme5/new_clones/Mathematica/spacetime-diagrams' &
git clone https://github.com/CloudCoders/AdventOfCode2017 '/storage/nvme5/new_clones/Mathematica/AdventOfCode2017' &
git clone https://github.com/radiatoryang/spring2017_intermediate '/storage/nvme5/new_clones/Mathematica/spring2017_intermediate' &
git clone https://github.com/VojtechW/Action-Angle-Schwarzschild '/storage/nvme5/new_clones/Mathematica/Action-Angle-Schwarzschild' &
git clone https://github.com/daniel-ilett/bytesize-enchantment '/storage/nvme5/new_clones/Mathematica/bytesize-enchantment' &
git clone https://github.com/rsouza01/tovsolver '/storage/nvme5/new_clones/Mathematica/tovsolver' &
git clone https://github.com/FeynCalc/feynknowledge '/storage/nvme5/new_clones/Mathematica/feynknowledge' &
git clone https://github.com/dlfivefifty/Ultraspherical '/storage/nvme5/new_clones/Mathematica/Ultraspherical' &
git clone https://github.com/richbrito/QNM_EMD '/storage/nvme5/new_clones/Mathematica/QNM_EMD' &
git clone https://github.com/AndreHAM/Quantum-Mechanics '/storage/nvme5/new_clones/Mathematica/Quantum-Mechanics' &
git clone https://github.com/szhorvat/IGraphR '/storage/nvme5/new_clones/Mathematica/IGraphR' &
git clone https://github.com/WMT-QE-Task/wmt-qe-2022-data '/storage/nvme5/new_clones/Mathematica/wmt-qe-2022-data' &
git clone https://github.com/Minghou-Lei/Deferred-Rendering-SSAO-in-unity-URP '/storage/nvme5/new_clones/Mathematica/Deferred-Rendering-SSAO-in-unity-URP' &
git clone https://github.com/chaoticbob/Cinder-3DTools '/storage/nvme5/new_clones/Mathematica/Cinder-3DTools' &
git clone https://github.com/shuichih/oreoren '/storage/nvme5/new_clones/Mathematica/oreoren' &
git clone https://github.com/xAct-contrib/Spinors '/storage/nvme5/new_clones/Mathematica/Spinors' &
git clone https://github.com/sho3la/Opengl-3D-Level-Editor '/storage/nvme5/new_clones/Mathematica/Opengl-3D-Level-Editor' &
git clone https://github.com/F-Feng/APart '/storage/nvme5/new_clones/Mathematica/APart' &
git clone https://github.com/bcolloran/tlmpm '/storage/nvme5/new_clones/Mathematica/tlmpm' &
git clone https://github.com/Dih5/ErrorPlot '/storage/nvme5/new_clones/Mathematica/ErrorPlot' &
git clone https://github.com/wjxway/InteractiveOptics-Mathematica '/storage/nvme5/new_clones/Mathematica/InteractiveOptics-Mathematica' &
git clone https://github.com/JulesOpp/Tanabe-Sugano '/storage/nvme5/new_clones/Mathematica/Tanabe-Sugano' &
git clone https://github.com/tientienyu/QEdark '/storage/nvme5/new_clones/Mathematica/QEdark' &
git clone https://github.com/RasoulAlaee/exact_multipoles '/storage/nvme5/new_clones/Mathematica/exact_multipoles' &
git clone https://github.com/PerAlexandersson/Mathematica-packages '/storage/nvme5/new_clones/Mathematica/Mathematica-packages' &
git clone https://github.com/hansolxryu/CPG_biped_walker_Ryu_Kuo '/storage/nvme5/new_clones/Mathematica/CPG_biped_walker_Ryu_Kuo' &
git clone https://github.com/mariaref/Random_Features '/storage/nvme5/new_clones/Mathematica/Random_Features' &
git clone https://github.com/kecosz/EcohNet '/storage/nvme5/new_clones/Mathematica/EcohNet' &
git clone https://github.com/tchronis/MSE-Mathematica '/storage/nvme5/new_clones/Mathematica/MSE-Mathematica' &
git clone https://github.com/bshoshany/WormholeParadoxSimulation '/storage/nvme5/new_clones/Mathematica/WormholeParadoxSimulation' &
git clone https://github.com/ckorikov/wolfram_ss_projects '/storage/nvme5/new_clones/Mathematica/wolfram_ss_projects' &
git clone https://github.com/lpantano/mypubs '/storage/nvme5/new_clones/Mathematica/mypubs' &
git clone https://github.com/kubaPod/MVue '/storage/nvme5/new_clones/Mathematica/MVue' &
git clone https://github.com/ConnorGray/NotebookWebsiteTools '/storage/nvme5/new_clones/Mathematica/NotebookWebsiteTools' &
git clone https://github.com/jschrier/HuckelTheory '/storage/nvme5/new_clones/Mathematica/HuckelTheory' &
git clone https://github.com/MKAbdElrahman/Scientific-Computing-with-Mathematica '/storage/nvme5/new_clones/Mathematica/Scientific-Computing-with-Mathematica' &
git clone https://github.com/mahdipc/Mathematica-source-codes-for-various-Numerical-Analysis-papers '/storage/nvme5/new_clones/Mathematica/Mathematica-source-codes-for-various-Numerical-Analysis-papers' &
git clone https://github.com/tylertaewook/project-orbitron '/storage/nvme5/new_clones/Mathematica/project-orbitron' &
git clone https://github.com/sorgerlab/palmer-cell-2017 '/storage/nvme5/new_clones/Mathematica/palmer-cell-2017' &
git clone https://github.com/joebentley/simba '/storage/nvme5/new_clones/Mathematica/simba' &
git clone https://github.com/maxitg/PostTagSystem '/storage/nvme5/new_clones/Mathematica/PostTagSystem' &
git clone https://github.com/bajracha71/Quandl-Mathematica-QuandlLink '/storage/nvme5/new_clones/Mathematica/Quandl-Mathematica-QuandlLink' &
git clone https://github.com/asukaminato0721/Effective-Mathematica '/storage/nvme5/new_clones/Mathematica/Effective-Mathematica' &
git clone https://github.com/RiggingDojo/Python_101 '/storage/nvme5/new_clones/Mathematica/Python_101' &
git clone https://github.com/kenjinote/REDUCE '/storage/nvme5/new_clones/Mathematica/REDUCE' &
git clone https://github.com/stevestavropoulos/elspell '/storage/nvme5/new_clones/Mathematica/elspell' &
git clone https://github.com/mverardo/CATemplates '/storage/nvme5/new_clones/Mathematica/CATemplates' &
git clone https://github.com/mtcq/channel_discrimination '/storage/nvme5/new_clones/Mathematica/channel_discrimination' &
git clone https://github.com/TYLeavome/Double-pendulum '/storage/nvme5/new_clones/Mathematica/Double-pendulum' &
git clone https://github.com/xAct-contrib/xTerior '/storage/nvme5/new_clones/Mathematica/xTerior' &
git clone https://github.com/stblake/algebraic_integration '/storage/nvme5/new_clones/Mathematica/algebraic_integration' &
git clone https://github.com/poeschko/WolframCloudBlogGenerator '/storage/nvme5/new_clones/Mathematica/WolframCloudBlogGenerator' &
git clone https://github.com/jfrancis71/Machine-Vision '/storage/nvme5/new_clones/Mathematica/Machine-Vision' &
git clone https://github.com/nud3l/balance '/storage/nvme5/new_clones/Mathematica/balance' &
git clone https://github.com/mcfefa/scRNAseq '/storage/nvme5/new_clones/Mathematica/scRNAseq' &
git clone https://github.com/renphysics/spNDSolve '/storage/nvme5/new_clones/Mathematica/spNDSolve' &
git clone https://github.com/scorza/pluginsRepo '/storage/nvme5/new_clones/Mathematica/pluginsRepo' &
git clone https://github.com/twdb/sonde '/storage/nvme5/new_clones/Mathematica/sonde' &
git clone https://github.com/danielscarvalho/Insper-DS-Dicas '/storage/nvme5/new_clones/Mathematica/Insper-DS-Dicas' &
git clone https://github.com/EverettYou/EmergentClassicality '/storage/nvme5/new_clones/Mathematica/EmergentClassicality' &
git clone https://github.com/oovm/ZhihuLink '/storage/nvme5/new_clones/Mathematica/ZhihuLink' &
git clone https://github.com/antononcube/SoftwareDesignMethodsWithWL-book '/storage/nvme5/new_clones/Mathematica/SoftwareDesignMethodsWithWL-book' &
git clone https://github.com/simchunyou/TubxFace '/storage/nvme5/new_clones/Mathematica/TubxFace' &
git clone https://github.com/jasongrout/webwork-national-problem-library '/storage/nvme5/new_clones/Mathematica/webwork-national-problem-library' &
git clone https://github.com/Apress/beginning-mathematica-wolfram-data-science '/storage/nvme5/new_clones/Mathematica/beginning-mathematica-wolfram-data-science' &
git clone https://github.com/denfrost/ARTv2.01 '/storage/nvme5/new_clones/Mathematica/ARTv2.01' &
git clone https://github.com/tensojka/cshyphen '/storage/nvme5/new_clones/Mathematica/cshyphen' &
git clone https://github.com/alihashmiii/2D-vertex-model '/storage/nvme5/new_clones/Mathematica/2D-vertex-model' &
git clone https://github.com/AstricleGames5411/CustomProceduralUrpSkyboxShaderGraph '/storage/nvme5/new_clones/Mathematica/CustomProceduralUrpSkyboxShaderGraph' &
git clone https://github.com/darkreactions/platipus '/storage/nvme5/new_clones/Mathematica/platipus' &
git clone https://github.com/episanty/PhD-Thesis '/storage/nvme5/new_clones/Mathematica/PhD-Thesis' &
git clone https://github.com/NotCamelCase/Arcade-Racing '/storage/nvme5/new_clones/Mathematica/Arcade-Racing' &
git clone https://github.com/Harry-Chen/CUMCM-2017 '/storage/nvme5/new_clones/Mathematica/CUMCM-2017' &
git clone https://github.com/avigliotti/3DLattices '/storage/nvme5/new_clones/Mathematica/3DLattices' &
git clone https://github.com/jkuczm/MathematicaOptionsValidation '/storage/nvme5/new_clones/Mathematica/MathematicaOptionsValidation' &
git clone https://github.com/id-bioinfo/GWTCLR '/storage/nvme5/new_clones/Mathematica/GWTCLR' &
git clone https://github.com/shhschilling/MasterTwo '/storage/nvme5/new_clones/Mathematica/MasterTwo' &
git clone https://github.com/hadoge/ArnoldHarold '/storage/nvme5/new_clones/Mathematica/ArnoldHarold' &
git clone https://github.com/afung-git/margipose '/storage/nvme5/new_clones/Mathematica/margipose' &
git clone https://github.com/uupers/ACSpider '/storage/nvme5/new_clones/Mathematica/ACSpider' &
git clone https://github.com/EinsteinToolkit/et2021uiuc '/storage/nvme5/new_clones/Mathematica/et2021uiuc' &
git clone https://github.com/jlykken/TASI2020-quantum '/storage/nvme5/new_clones/Mathematica/TASI2020-quantum' &
git clone https://github.com/alzabone/selfconsistent-schordinger-poisson '/storage/nvme5/new_clones/Mathematica/selfconsistent-schordinger-poisson' &
git clone https://github.com/JYNi16/Tight-Binding-Model '/storage/nvme5/new_clones/Mathematica/Tight-Binding-Model' &
git clone https://github.com/OPM/IFEM-Elasticity '/storage/nvme5/new_clones/Mathematica/IFEM-Elasticity' &
git clone https://github.com/CentralHarlemAnonymous/bloomberg-to-mathematica '/storage/nvme5/new_clones/Mathematica/bloomberg-to-mathematica' &
git clone https://github.com/McSaks/wl-init '/storage/nvme5/new_clones/Mathematica/wl-init' &
git clone https://github.com/WolframSummerSchool/Summer2018Starter '/storage/nvme5/new_clones/Mathematica/Summer2018Starter' &
git clone https://github.com/c3sr/scope '/storage/nvme5/new_clones/Mathematica/scope' &
git clone https://github.com/WinteryFox/VixenEngineVulkan '/storage/nvme5/new_clones/Mathematica/VixenEngineVulkan' &
git clone https://github.com/atridave/Automatic-Rigging-for-3D-Characters-ARC- '/storage/nvme5/new_clones/Mathematica/Automatic-Rigging-for-3D-Characters-ARC-' &
git clone https://github.com/ikemmm/rust-spectre '/storage/nvme5/new_clones/Mathematica/rust-spectre' &
git clone https://github.com/miRoox/HIT-DigitalSignalProcessing '/storage/nvme5/new_clones/Mathematica/HIT-DigitalSignalProcessing' &
git clone https://github.com/billderose-zz/DropConnect '/storage/nvme5/new_clones/Mathematica/DropConnect' &
git clone https://github.com/paul-jean/blog-this '/storage/nvme5/new_clones/Mathematica/blog-this' &
git clone https://github.com/Riebart/MathematicaSSHKernels '/storage/nvme5/new_clones/Mathematica/MathematicaSSHKernels' &
git clone https://github.com/Bsuniverse/NWPU-CFD '/storage/nvme5/new_clones/Mathematica/NWPU-CFD' &
git clone https://github.com/AndresOtalora92/CursoEpanetBasico-Intermedio '/storage/nvme5/new_clones/Mathematica/CursoEpanetBasico-Intermedio' &
git clone https://github.com/RolphWoggom/shr.tar '/storage/nvme5/new_clones/Mathematica/shr.tar' &
git clone https://github.com/bcynuaa/GalerkinLearn '/storage/nvme5/new_clones/Mathematica/GalerkinLearn' &
git clone https://github.com/justincfeng/PoMiN '/storage/nvme5/new_clones/Mathematica/PoMiN' &
git clone https://github.com/GameAcademy-school/BoltIntro '/storage/nvme5/new_clones/Mathematica/BoltIntro' &
git clone https://github.com/reclojure/clojure-wolfram-bridge '/storage/nvme5/new_clones/Mathematica/clojure-wolfram-bridge' &
git clone https://github.com/kubaPod/Meh '/storage/nvme5/new_clones/Mathematica/Meh' &
git clone https://github.com/carlwoll/Stack-Exchange-Stylesheet '/storage/nvme5/new_clones/Mathematica/Stack-Exchange-Stylesheet' &
git clone https://github.com/SimonWoods/shadow '/storage/nvme5/new_clones/Mathematica/shadow' &
git clone https://github.com/rebcabin/RecurrentLeastSquares '/storage/nvme5/new_clones/Mathematica/RecurrentLeastSquares' &
git clone https://github.com/ZhenYangIACAS/HJQE '/storage/nvme5/new_clones/Mathematica/HJQE' &
git clone https://github.com/Mackaber/BlockyWL '/storage/nvme5/new_clones/Mathematica/BlockyWL' &
git clone https://github.com/thorsilver/Emulating-ABMs-with-ML '/storage/nvme5/new_clones/Mathematica/Emulating-ABMs-with-ML' &
git clone https://github.com/0xBADCA7/timing-attacks '/storage/nvme5/new_clones/Mathematica/timing-attacks' &
git clone https://github.com/JasonTheCoderMichael/URP_Shadowmask '/storage/nvme5/new_clones/Mathematica/URP_Shadowmask' &
git clone https://github.com/k1242/notes_4sem '/storage/nvme5/new_clones/Mathematica/notes_4sem' &
git clone https://github.com/thong3le/Speedup-Matrix-Chain-Multiplication '/storage/nvme5/new_clones/Mathematica/Speedup-Matrix-Chain-Multiplication' &
git clone https://github.com/317431629/Maya_Assets_Library '/storage/nvme5/new_clones/Mathematica/Maya_Assets_Library' &
git clone https://github.com/SlideZero/urp-shockwave-shader '/storage/nvme5/new_clones/Mathematica/urp-shockwave-shader' &
git clone https://github.com/tpfto/Wright '/storage/nvme5/new_clones/Mathematica/Wright' &
git clone https://github.com/hoppet-code/hoppet '/storage/nvme5/new_clones/Mathematica/hoppet' &
git clone https://github.com/RobertBoganKang/piano_tuning '/storage/nvme5/new_clones/Mathematica/piano_tuning' &
git clone https://github.com/effExTeam/CoDEx-1.0.0 '/storage/nvme5/new_clones/Mathematica/CoDEx-1.0.0' &
git clone https://github.com/cphys/Nernst-effect-in-Dirac-and-inversion-asymmetric-Weyl-semimetals '/storage/nvme5/new_clones/Mathematica/Nernst-effect-in-Dirac-and-inversion-asymmetric-Weyl-semimetals' &
git clone https://github.com/nitpum/KMUTT-CPE '/storage/nvme5/new_clones/Mathematica/KMUTT-CPE' &
git clone https://github.com/oovm/TrigonometricRadicals '/storage/nvme5/new_clones/Mathematica/TrigonometricRadicals' &
git clone https://github.com/QLNUxu/Cold-atom '/storage/nvme5/new_clones/Mathematica/Cold-atom' &
git clone https://github.com/mbabiuc/MathScripts '/storage/nvme5/new_clones/Mathematica/MathScripts' &
git clone https://github.com/danflapjax/GeometricAlgebraForMathematica '/storage/nvme5/new_clones/Mathematica/GeometricAlgebraForMathematica' &
git clone https://github.com/catarina-moreira/QuLBiT '/storage/nvme5/new_clones/Mathematica/QuLBiT' &
git clone https://github.com/jonathanSS/ClassImbalanceStudies '/storage/nvme5/new_clones/Mathematica/ClassImbalanceStudies' &
git clone https://github.com/PyryKuusela/GammaMaP '/storage/nvme5/new_clones/Mathematica/GammaMaP' &
git clone https://github.com/c3m-labs/HeatTrans '/storage/nvme5/new_clones/Mathematica/HeatTrans' &
git clone https://github.com/BlockySurvival/bls_mods '/storage/nvme5/new_clones/Mathematica/bls_mods' &
git clone https://github.com/aaiyer/fastapprox '/storage/nvme5/new_clones/Mathematica/fastapprox' &
git clone https://github.com/sovicak/AnonymniAnalytici '/storage/nvme5/new_clones/Mathematica/AnonymniAnalytici' &
git clone https://github.com/yangyongkang2000/Wolfram '/storage/nvme5/new_clones/Mathematica/Wolfram' &
git clone https://github.com/KienHuynh/multi-agent-delivery '/storage/nvme5/new_clones/Mathematica/multi-agent-delivery' &
git clone https://github.com/artigee/Maya-Rigging-Example '/storage/nvme5/new_clones/Mathematica/Maya-Rigging-Example' &
git clone https://github.com/rhennigan/CodeEquivalenceUtilities '/storage/nvme5/new_clones/Mathematica/CodeEquivalenceUtilities' &
git clone https://github.com/msdrigg/RayTracing '/storage/nvme5/new_clones/Mathematica/RayTracing' &
git clone https://github.com/stone-zeng/toys '/storage/nvme5/new_clones/Mathematica/toys' &
git clone https://github.com/jkuczm/MathematicaSyntaxAnnotations '/storage/nvme5/new_clones/Mathematica/MathematicaSyntaxAnnotations' &
git clone https://github.com/seweissman/wikiduper '/storage/nvme5/new_clones/Mathematica/wikiduper' &
git clone https://github.com/mhguo321/Two-Quadrotors-load-system '/storage/nvme5/new_clones/Mathematica/Two-Quadrotors-load-system' &
git clone https://github.com/sw1sh/GeometricAlgebra '/storage/nvme5/new_clones/Mathematica/GeometricAlgebra' &
git clone https://github.com/alejandrogarces/JuliaScripts '/storage/nvme5/new_clones/Mathematica/JuliaScripts' &
git clone https://github.com/Cobord/Quantum-Computer-Things '/storage/nvme5/new_clones/Mathematica/Quantum-Computer-Things' &
git clone https://github.com/the-other-mariana/code-journal '/storage/nvme5/new_clones/Mathematica/code-journal' &
git clone https://github.com/rharper2/EfficientLearningDataSet '/storage/nvme5/new_clones/Mathematica/EfficientLearningDataSet' &
git clone https://github.com/midhun-varghese/Robotics-Kinematics_Dynamics_Control '/storage/nvme5/new_clones/Mathematica/Robotics-Kinematics_Dynamics_Control' &
git clone https://github.com/drmayerson/FOORT '/storage/nvme5/new_clones/Mathematica/FOORT' &
git clone https://github.com/halirutan/HeyexImport '/storage/nvme5/new_clones/Mathematica/HeyexImport' &
git clone https://github.com/jfrancis71/CognitoZoo '/storage/nvme5/new_clones/Mathematica/CognitoZoo' &
git clone https://github.com/minchaowu/mm-lean '/storage/nvme5/new_clones/Mathematica/mm-lean' &
git clone https://github.com/jazzboysc/SERiggingTools '/storage/nvme5/new_clones/Mathematica/SERiggingTools' &
git clone https://github.com/EskenderTamrat/DSSM-LSTM '/storage/nvme5/new_clones/Mathematica/DSSM-LSTM' &
git clone https://github.com/ladderDGA/ladderDGA '/storage/nvme5/new_clones/Mathematica/ladderDGA' &
git clone https://github.com/sergiobd/FractalNoise '/storage/nvme5/new_clones/Mathematica/FractalNoise' &
git clone https://github.com/file-format/Docs '/storage/nvme5/new_clones/Mathematica/Docs' &
git clone https://github.com/PrincetonUniversity/3D3A-Mathematica-Toolbox '/storage/nvme5/new_clones/Mathematica/3D3A-Mathematica-Toolbox' &
git clone https://github.com/floklimm/graphon '/storage/nvme5/new_clones/Mathematica/graphon' &
git clone https://github.com/mgear-dev/sample_data '/storage/nvme5/new_clones/Mathematica/sample_data' &
git clone https://github.com/BlackHolePerturbationToolkit/ReggeWheeler '/storage/nvme5/new_clones/Mathematica/ReggeWheeler' &
git clone https://github.com/loonaticx/ColoringBook '/storage/nvme5/new_clones/Mathematica/ColoringBook' &
git clone https://github.com/RuleBasedIntegration/RuleBasedIntegration.github.io '/storage/nvme5/new_clones/Mathematica/RuleBasedIntegrationhub.io' &
git clone https://github.com/RaewynD/IsingModel '/storage/nvme5/new_clones/Mathematica/IsingModel' &
git clone https://github.com/ORNL-Fusion/aorsa2d '/storage/nvme5/new_clones/Mathematica/aorsa2d' &
git clone https://github.com/radiatoryang/fall2019_gamedev '/storage/nvme5/new_clones/Mathematica/fall2019_gamedev' &
git clone https://github.com/Stuja/stuja '/storage/nvme5/new_clones/Mathematica/stuja' &
git clone https://github.com/jiongchen/arcsim '/storage/nvme5/new_clones/Mathematica/arcsim' &
git clone https://github.com/sguzman/MathematicaMathFun '/storage/nvme5/new_clones/Mathematica/MathematicaMathFun' &
git clone https://github.com/skalarproduktraum/UnitTest '/storage/nvme5/new_clones/Mathematica/UnitTest' &
git clone https://github.com/MarkGreenberg/Chicken-Scratch '/storage/nvme5/new_clones/Mathematica/Chicken-Scratch' &
git clone https://github.com/ypleong/SeALS '/storage/nvme5/new_clones/Mathematica/SeALS' &
git clone https://github.com/c3m-labs/GmshLink '/storage/nvme5/new_clones/Mathematica/GmshLink' &
git clone https://github.com/pmocz/Smoluchowski '/storage/nvme5/new_clones/Mathematica/Smoluchowski' &
git clone https://github.com/phantomas1234/BICBpy '/storage/nvme5/new_clones/Mathematica/BICBpy' &
git clone https://github.com/matrixbud/Geometric-Algebra '/storage/nvme5/new_clones/Mathematica/Geometric-Algebra' &
git clone https://github.com/BrianSwift/JunoCam '/storage/nvme5/new_clones/Mathematica/JunoCam' &
git clone https://github.com/mmadsenxyz/SmartMap '/storage/nvme5/new_clones/Mathematica/SmartMap' &
git clone https://github.com/chriswolfram/ForeignFunctionInterface '/storage/nvme5/new_clones/Mathematica/ForeignFunctionInterface' &
git clone https://github.com/leixingyu/pokerSpring '/storage/nvme5/new_clones/Mathematica/pokerSpring' &
git clone https://github.com/varunvai/LatticeScripts '/storage/nvme5/new_clones/Mathematica/LatticeScripts' &
git clone https://github.com/arnoudbuzing/wolfram-python-package-manager '/storage/nvme5/new_clones/Mathematica/wolfram-python-package-manager' &
git clone https://github.com/bradkav/EarthShadow '/storage/nvme5/new_clones/Mathematica/EarthShadow' &
git clone https://github.com/bastovd/DMDFinalProject '/storage/nvme5/new_clones/Mathematica/DMDFinalProject' &
git clone https://github.com/mshroyer/msp430-morse '/storage/nvme5/new_clones/Mathematica/msp430-morse' &
git clone https://github.com/marcduque/AnimationProject '/storage/nvme5/new_clones/Mathematica/AnimationProject' &
git clone https://github.com/ondrejkrejci/MathemticaForDFTnSPM '/storage/nvme5/new_clones/Mathematica/MathemticaForDFTnSPM' &
git clone https://github.com/selpoG/autoboot '/storage/nvme5/new_clones/Mathematica/autoboot' &
git clone https://github.com/we-taper/Draft '/storage/nvme5/new_clones/Mathematica/Draft' &
git clone https://github.com/CarlosManuelRodr/Fisica-Python '/storage/nvme5/new_clones/Mathematica/Fisica-Python' &
git clone https://github.com/b3m2a1/mathematica-PyTools '/storage/nvme5/new_clones/Mathematica/mathematica-PyTools' &
git clone https://github.com/epnavarrob/Photonic_Crystals '/storage/nvme5/new_clones/Mathematica/Photonic_Crystals' &
git clone https://github.com/chipiki/PXFmini_v2 '/storage/nvme5/new_clones/Mathematica/PXFmini_v2' &
git clone https://github.com/croningp/NanoDiscovery '/storage/nvme5/new_clones/Mathematica/NanoDiscovery' &
git clone https://github.com/phreeza/ml-music '/storage/nvme5/new_clones/Mathematica/ml-music' &
git clone https://github.com/ComputationalScienceLaboratory/Integreat '/storage/nvme5/new_clones/Mathematica/Integreat' &
git clone https://github.com/alecGraves/WolframNotebookDarculaTheme '/storage/nvme5/new_clones/Mathematica/WolframNotebookDarculaTheme' &
git clone https://github.com/gkanwar/lattlib '/storage/nvme5/new_clones/Mathematica/lattlib' &
git clone https://github.com/munuxi/Multiple-Polylogarithm '/storage/nvme5/new_clones/Mathematica/Multiple-Polylogarithm' &
git clone https://github.com/trevorsgallen/ComputationalEcon '/storage/nvme5/new_clones/Mathematica/ComputationalEcon' &
git clone https://github.com/maxitg/InflationSimulator '/storage/nvme5/new_clones/Mathematica/InflationSimulator' &
git clone https://github.com/LQG-Florida-Atlantic-University/Classical-EOM '/storage/nvme5/new_clones/Mathematica/Classical-EOM' &
git clone https://github.com/Kenjor97/KriticGamesProject '/storage/nvme5/new_clones/Mathematica/KriticGamesProject' &
git clone https://github.com/MozillaReality/mr-social-assets '/storage/nvme5/new_clones/Mathematica/mr-social-assets' &
git clone https://github.com/MathOnco/scRNAseqITH '/storage/nvme5/new_clones/Mathematica/scRNAseqITH' &
git clone https://github.com/LHCfitNikhef/ML4EFT '/storage/nvme5/new_clones/Mathematica/ML4EFT' &
git clone https://github.com/SipRadius/Qemu-USB-Tablet-Driver '/storage/nvme5/new_clones/Mathematica/Qemu-USB-Tablet-Driver' &
git clone https://github.com/ramiromagno/rdml '/storage/nvme5/new_clones/Mathematica/rdml' &
git clone https://github.com/thearchitector/Mathematica-MATLAB '/storage/nvme5/new_clones/Mathematica/Mathematica-MATLAB' &
git clone https://github.com/motion-twin/mtypes '/storage/nvme5/new_clones/Mathematica/mtypes' &
git clone https://github.com/dhidas/WSTPExample '/storage/nvme5/new_clones/Mathematica/WSTPExample' &
git clone https://github.com/radiatoryang/nyu_studio_fall2015 '/storage/nvme5/new_clones/Mathematica/nyu_studio_fall2015' &
git clone https://github.com/orome/qr-puzzles-ma '/storage/nvme5/new_clones/Mathematica/qr-puzzles-ma' &
git clone https://github.com/XyhwX/articles_codes '/storage/nvme5/new_clones/Mathematica/articles_codes' &
git clone https://github.com/Harindulk/winter-in-unity '/storage/nvme5/new_clones/Mathematica/winter-in-unity' &
git clone https://github.com/sanjitsbatra/Wolfram-Summer-School '/storage/nvme5/new_clones/Mathematica/Wolfram-Summer-School' &
git clone https://github.com/rhennigan/ResourceFunctions '/storage/nvme5/new_clones/Mathematica/ResourceFunctions' &
git clone https://github.com/XingyuZhang2018/AD-Kitaev '/storage/nvme5/new_clones/Mathematica/AD-Kitaev' &
git clone https://github.com/akerbos/sesketches '/storage/nvme5/new_clones/Mathematica/sesketches' &
git clone https://github.com/oleksandrr/NelderMeadMinimize '/storage/nvme5/new_clones/Mathematica/NelderMeadMinimize' &
git clone https://github.com/dourouc05/OptimisationTeachingKit '/storage/nvme5/new_clones/Mathematica/OptimisationTeachingKit' &
git clone https://github.com/amirubin87/NetStruct_Hierarchy '/storage/nvme5/new_clones/Mathematica/NetStruct_Hierarchy' &
git clone https://github.com/aabecker/RoboticSwarmControlLab '/storage/nvme5/new_clones/Mathematica/RoboticSwarmControlLab' &
git clone https://github.com/HyperGroups/Mathematica '/storage/nvme5/new_clones/Mathematica/Mathematica' &
git clone https://github.com/lucainnocenti/QM '/storage/nvme5/new_clones/Mathematica/QM' &
git clone https://github.com/sustainable-computing/benchmarking-state-estimators '/storage/nvme5/new_clones/Mathematica/benchmarking-state-estimators' &
git clone https://github.com/reinholtz/hershey-fonts-with-unicode '/storage/nvme5/new_clones/Mathematica/hershey-fonts-with-unicode' &
git clone https://github.com/pascalwasser/DlogBasis '/storage/nvme5/new_clones/Mathematica/DlogBasis' &
git clone https://github.com/g3n1uss/StringTheoryTools '/storage/nvme5/new_clones/Mathematica/StringTheoryTools' &
git clone https://github.com/10manjunath/Wolfram-Challenges '/storage/nvme5/new_clones/Mathematica/Wolfram-Challenges' &
git clone https://github.com/chengshul/QSL_kagome '/storage/nvme5/new_clones/Mathematica/QSL_kagome' &
git clone https://github.com/yqchen-research/MMA-Quantum-Computing '/storage/nvme5/new_clones/Mathematica/MMA-Quantum-Computing' &
git clone https://github.com/agnostiQ/DQC1-knots '/storage/nvme5/new_clones/Mathematica/DQC1-knots' &
git clone https://github.com/rjmercier1/CyclesForMaya '/storage/nvme5/new_clones/Mathematica/CyclesForMaya' &
git clone https://github.com/jacobmarks/Original-Wolfram-Quantum-Framework '/storage/nvme5/new_clones/Mathematica/Original-Wolfram-Quantum-Framework' &
git clone https://github.com/miRoox/ProjectEuler '/storage/nvme5/new_clones/Mathematica/ProjectEuler' &
git clone https://github.com/VELA-CLARA-software/Software '/storage/nvme5/new_clones/Mathematica/Software' &
git clone https://github.com/narongtum/nmTools '/storage/nvme5/new_clones/Mathematica/nmTools' &
git clone https://github.com/TysonRayJones/VariationalImagTimeSimmer '/storage/nvme5/new_clones/Mathematica/VariationalImagTimeSimmer' &
git clone https://github.com/ustc-zzzz/Mathematica-Uncertainty '/storage/nvme5/new_clones/Mathematica/Mathematica-Uncertainty' &
git clone https://github.com/mtholder/TreeTopoTestingTalks '/storage/nvme5/new_clones/Mathematica/TreeTopoTestingTalks' &
git clone https://github.com/Refridgerator/Wolfram '/storage/nvme5/new_clones/Mathematica/Wolfram' &
git clone https://github.com/nxt-dev/examples '/storage/nvme5/new_clones/Mathematica/examples' &
git clone https://github.com/FormLink/formlink '/storage/nvme5/new_clones/Mathematica/formlink' &
git clone https://github.com/popersson/math124files '/storage/nvme5/new_clones/Mathematica/math124files' &
git clone https://github.com/peixinshen/DeepQuantumNeuralNetworks-Mathematica '/storage/nvme5/new_clones/Mathematica/DeepQuantumNeuralNetworks-Mathematica' &
