#!/bin/bash

git clone https://github.com/TitusLVR/BMAX_Connector '/storage/nvme5/new_clones/MAXScript/BMAX_Connector' &
git clone https://github.com/davestewart/maxscript '/storage/nvme5/new_clones/MAXScript/maxscript' &
git clone https://github.com/gkmotu/OSL-Shaders '/storage/nvme5/new_clones/MAXScript/OSL-Shaders' &
git clone https://github.com/Autodesk-Forge/forge-tutorial-postman '/storage/nvme5/new_clones/MAXScript/forge-tutorial-postman' &
git clone https://github.com/Makiah/BotW-SBFRES-to-FBX '/storage/nvme5/new_clones/MAXScript/BotW-SBFRES-to-FBX' &
git clone https://github.com/nnngrach/AnyGIS_maps '/storage/nvme5/new_clones/MAXScript/AnyGIS_maps' &
git clone https://github.com/dave-newson/ninja-ripper-ms '/storage/nvme5/new_clones/MAXScript/ninja-ripper-ms' &
git clone https://github.com/blueskythlikesclouds/SkythTools '/storage/nvme5/new_clones/MAXScript/SkythTools' &
git clone https://github.com/binarysudoku/NormalMagic '/storage/nvme5/new_clones/MAXScript/NormalMagic' &
git clone https://github.com/AniBullet/BsKeyTools '/storage/nvme5/new_clones/MAXScript/BsKeyTools' &
git clone https://github.com/NeilJed/3DSMax-SMD-Exporter-Plugin '/storage/nvme5/new_clones/MAXScript/3DSMax-SMD-Exporter-Plugin' &
git clone https://github.com/autodesk-platform-services/aps-tutorial-postman '/storage/nvme5/new_clones/MAXScript/aps-tutorial-postman' &
git clone https://github.com/ADN-DevTech/3dsMax-MCG-Samples '/storage/nvme5/new_clones/MAXScript/3dsMax-MCG-Samples' &
git clone https://github.com/markulie/3dsmax-wirecolor-pro '/storage/nvme5/new_clones/MAXScript/3dsmax-wirecolor-pro' &
git clone https://github.com/gkmotu/ArnoldSceneConverterScripts3DSMAX '/storage/nvme5/new_clones/MAXScript/ArnoldSceneConverterScripts3DSMAX' &
git clone https://github.com/HAG87/maxscript-assorted '/storage/nvme5/new_clones/MAXScript/maxscript-assorted' &
git clone https://github.com/doublec/shen-wasp '/storage/nvme5/new_clones/MAXScript/shen-wasp' &
git clone https://github.com/HaloMods/HaloContentToolScripts '/storage/nvme5/new_clones/MAXScript/HaloContentToolScripts' &
git clone https://github.com/johanberonius/custom-map-source '/storage/nvme5/new_clones/MAXScript/custom-map-source' &
git clone https://github.com/JoeStrout/minimicro-sysdisk '/storage/nvme5/new_clones/MAXScript/minimicro-sysdisk' &
git clone https://github.com/svenfraeys/totex '/storage/nvme5/new_clones/MAXScript/totex' &
git clone https://github.com/markulie/3dsmax-maya-xcalc '/storage/nvme5/new_clones/MAXScript/3dsmax-maya-xcalc' &
git clone https://github.com/huibinshen/fingerid '/storage/nvme5/new_clones/MAXScript/fingerid' &
git clone https://github.com/markulie/3dsmax-randomx '/storage/nvme5/new_clones/MAXScript/3dsmax-randomx' &
git clone https://github.com/TaylorMouse/warcraft_III_reforged_tools '/storage/nvme5/new_clones/MAXScript/warcraft_III_reforged_tools' &
git clone https://github.com/CesiumGS/cesium-ion-3ds-max-plugin '/storage/nvme5/new_clones/MAXScript/cesium-ion-3ds-max-plugin' &
git clone https://github.com/pudingus/Max4dsTools '/storage/nvme5/new_clones/MAXScript/Max4dsTools' &
git clone https://github.com/metallicafan212/HarryPotterUnrealWiki '/storage/nvme5/new_clones/MAXScript/HarryPotterUnrealWiki' &
git clone https://github.com/markulie/3dsmax-anim-layer-cleaner '/storage/nvme5/new_clones/MAXScript/3dsmax-anim-layer-cleaner' &
git clone https://github.com/TheOnlyAaron/Debris_Maker2 '/storage/nvme5/new_clones/MAXScript/Debris_Maker2' &
git clone https://github.com/superrune/3dsmaxSeuratExport '/storage/nvme5/new_clones/MAXScript/3dsmaxSeuratExport' &
git clone https://github.com/unitycoder/3dsMaxAndUnity '/storage/nvme5/new_clones/MAXScript/3dsMaxAndUnity' &
git clone https://github.com/TaylorMouse/warcraft_iii_tools '/storage/nvme5/new_clones/MAXScript/warcraft_iii_tools' &
git clone https://github.com/davetyner/scripts '/storage/nvme5/new_clones/MAXScript/scripts' &
git clone https://github.com/GTAmodding/gta_studio_max '/storage/nvme5/new_clones/MAXScript/gta_studio_max' &
git clone https://github.com/jlankitus/Easy-MZP-Plugin '/storage/nvme5/new_clones/MAXScript/Easy-MZP-Plugin' &
git clone https://github.com/PDP-10/microcode '/storage/nvme5/new_clones/MAXScript/microcode' &
git clone https://github.com/AlexKimov/seadogs-file-formats '/storage/nvme5/new_clones/MAXScript/seadogs-file-formats' &
git clone https://github.com/AlexKimov/HardTruck-RignRoll-file-formats '/storage/nvme5/new_clones/MAXScript/HardTruck-RignRoll-file-formats' &
git clone https://github.com/Shadowth117/Phantasy-Star-Online-2-Model-Tools '/storage/nvme5/new_clones/MAXScript/Phantasy-Star-Online-2-Model-Tools' &
git clone https://github.com/takano32/bfbf '/storage/nvme5/new_clones/MAXScript/bfbf' &
git clone https://github.com/aws/thinkbox-krakatoa-mx '/storage/nvme5/new_clones/MAXScript/thinkbox-krakatoa-mx' &
git clone https://github.com/mxdsa/populateTerrain '/storage/nvme5/new_clones/MAXScript/populateTerrain' &
git clone https://github.com/ShadeAnimator/ShadeAnimator_Fallout4_AnimationKit '/storage/nvme5/new_clones/MAXScript/ShadeAnimator_Fallout4_AnimationKit' &
git clone https://github.com/Avatarus-one/MaxBMD '/storage/nvme5/new_clones/MAXScript/MaxBMD' &
git clone https://github.com/cb109/interactive-universal-renamer '/storage/nvme5/new_clones/MAXScript/interactive-universal-renamer' &
git clone https://github.com/CaptainD001/M3_Import '/storage/nvme5/new_clones/MAXScript/M3_Import' &
git clone https://github.com/PseudoKnight/FinalScoreMC '/storage/nvme5/new_clones/MAXScript/FinalScoreMC' &
git clone https://github.com/404craft/101max '/storage/nvme5/new_clones/MAXScript/101max' &
git clone https://github.com/SAP/software-documentation-data-set-for-machine-translation '/storage/nvme5/new_clones/MAXScript/software-documentation-data-set-for-machine-translation' &
git clone https://github.com/AlternativaPlatform/3DSMaxExportToUnity3D '/storage/nvme5/new_clones/MAXScript/3DSMaxExportToUnity3D' &
git clone https://github.com/piyanggoon/InfestMS '/storage/nvme5/new_clones/MAXScript/InfestMS' &
git clone https://github.com/malonnnn/ServerConfig '/storage/nvme5/new_clones/MAXScript/ServerConfig' &
git clone https://github.com/daz3d/DazTo3dsMax '/storage/nvme5/new_clones/MAXScript/DazTo3dsMax' &
git clone https://github.com/corvusw/GHPublic '/storage/nvme5/new_clones/MAXScript/GHPublic' &
git clone https://github.com/aws/thinkbox-stoke-mx '/storage/nvme5/new_clones/MAXScript/thinkbox-stoke-mx' &
git clone https://github.com/AniBullet/BulletTools '/storage/nvme5/new_clones/MAXScript/BulletTools' &
git clone https://github.com/nicolasboselli/Maxscript '/storage/nvme5/new_clones/MAXScript/Maxscript' &
git clone https://github.com/Daria-Maltseva/pajek '/storage/nvme5/new_clones/MAXScript/pajek' &
git clone https://github.com/ShaggEw/AnotherAnimationHelper '/storage/nvme5/new_clones/MAXScript/AnotherAnimationHelper' &
git clone https://github.com/hbartle/CSTStudio_NFScanner '/storage/nvme5/new_clones/MAXScript/CSTStudio_NFScanner' &
git clone https://github.com/aap/pdp10 '/storage/nvme5/new_clones/MAXScript/pdp10' &
git clone https://github.com/NerdNu/nerdCH '/storage/nvme5/new_clones/MAXScript/nerdCH' &
git clone https://github.com/joqqy/CryImport '/storage/nvme5/new_clones/MAXScript/CryImport' &
git clone https://github.com/lkareeml/Beta-FreeCodeCamp '/storage/nvme5/new_clones/MAXScript/Beta-FreeCodeCamp' &
git clone https://github.com/bugai66/3ds-Max-Batch-Import-Export-Tool '/storage/nvme5/new_clones/MAXScript/3ds-Max-Batch-Import-Export-Tool' &
git clone https://github.com/cb109/maxtest '/storage/nvme5/new_clones/MAXScript/maxtest' &
git clone https://github.com/4698to/Biped-Key-Tool '/storage/nvme5/new_clones/MAXScript/Biped-Key-Tool' &
git clone https://github.com/PanteleevS/mxseditor_calltips '/storage/nvme5/new_clones/MAXScript/mxseditor_calltips' &
git clone https://github.com/TheOnlyAaron/AE_Transform_Exporter '/storage/nvme5/new_clones/MAXScript/AE_Transform_Exporter' &
git clone https://github.com/XaBerr/3dsmax-toolbox '/storage/nvme5/new_clones/MAXScript/3dsmax-toolbox' &
git clone https://github.com/aalto-ics-kepaco/msms_rt_score_integration '/storage/nvme5/new_clones/MAXScript/msms_rt_score_integration' &
git clone https://github.com/3d-io/UV-Copy-MaxScript '/storage/nvme5/new_clones/MAXScript/UV-Copy-MaxScript' &
git clone https://github.com/aaandres/maxLINQ '/storage/nvme5/new_clones/MAXScript/maxLINQ' &
git clone https://github.com/EmanueleLecchi/Lele-s-V-Ray-MaxScript-Tools '/storage/nvme5/new_clones/MAXScript/Lele-s-V-Ray-MaxScript-Tools' &
git clone https://github.com/pegasus1982/maxscript-dynamic-projection '/storage/nvme5/new_clones/MAXScript/maxscript-dynamic-projection' &
git clone https://github.com/troydm/mymalloc '/storage/nvme5/new_clones/MAXScript/mymalloc' &
git clone https://github.com/RDTG/HKX-to-FBX-Batch-MaxScript '/storage/nvme5/new_clones/MAXScript/HKX-to-FBX-Batch-MaxScript' &
git clone https://github.com/Michael-K-GH/CABAL-Online-3ds-Scripts '/storage/nvme5/new_clones/MAXScript/CABAL-Online-3ds-Scripts' &
git clone https://github.com/JoeStrout/minimicro-fonts '/storage/nvme5/new_clones/MAXScript/minimicro-fonts' &
git clone https://github.com/imaoki/FlexUI '/storage/nvme5/new_clones/MAXScript/FlexUI' &
git clone https://github.com/gtvfx/mxs_bundle '/storage/nvme5/new_clones/MAXScript/mxs_bundle' &
git clone https://github.com/Mino-is-me/ScriptSet '/storage/nvme5/new_clones/MAXScript/ScriptSet' &
git clone https://github.com/mrp149/DUBNA '/storage/nvme5/new_clones/MAXScript/DUBNA' &
git clone https://github.com/knsii/mzp-creator '/storage/nvme5/new_clones/MAXScript/mzp-creator' &
git clone https://github.com/defrost256/SplineExport '/storage/nvme5/new_clones/MAXScript/SplineExport' &
