#!/bin/bash

git clone https://github.com/AmberWat/NegativeSpaceFont '/storage/nvme5/new_clones/mcfunction/NegativeSpaceFont' &
git clone https://github.com/slicedlime/examples '/storage/nvme5/new_clones/mcfunction/examples' &
git clone https://github.com/Stardust-Labs-MC/Terralith '/storage/nvme5/new_clones/mcfunction/Terralith' &
git clone https://github.com/Legacy-Edition-Minigames/Minigames '/storage/nvme5/new_clones/mcfunction/Minigames' &
git clone https://github.com/ICY105/Mechanization '/storage/nvme5/new_clones/mcfunction/Mechanization' &
git clone https://github.com/BigPapi13/Delta '/storage/nvme5/new_clones/mcfunction/Delta' &
git clone https://github.com/LunarEclipseStudios/From-The-Fog '/storage/nvme5/new_clones/mcfunction/From-The-Fog' &
git clone https://github.com/NeunEinser/bingo '/storage/nvme5/new_clones/mcfunction/bingo' &
git clone https://github.com/ICY105/Datapack-Utilities '/storage/nvme5/new_clones/mcfunction/Datapack-Utilities' &
git clone https://github.com/GoldenDelicios/world-pregen '/storage/nvme5/new_clones/mcfunction/world-pregen' &
git clone https://github.com/McTsts/Minecraft-String-Utilities '/storage/nvme5/new_clones/mcfunction/Minecraft-String-Utilities' &
git clone https://github.com/ProjectTSB/TheSkyBlessing '/storage/nvme5/new_clones/mcfunction/TheSkyBlessing' &
git clone https://github.com/tryashtar/shulker-preview '/storage/nvme5/new_clones/mcfunction/shulker-preview' &
git clone https://github.com/mcbookshelf/Bookshelf '/storage/nvme5/new_clones/mcfunction/Bookshelf' &
git clone https://github.com/Stardust-Labs-MC/Incendium '/storage/nvme5/new_clones/mcfunction/Incendium' &
git clone https://github.com/CreeperMagnet/the-creepers-code '/storage/nvme5/new_clones/mcfunction/the-creepers-code' &
git clone https://github.com/HamaSSH/RPG-Datapack '/storage/nvme5/new_clones/mcfunction/RPG-Datapack' &
git clone https://github.com/MinecraftPhi/MinecraftPhi-modules '/storage/nvme5/new_clones/mcfunction/MinecraftPhi-modules' &
git clone https://github.com/5uso/String-Parser '/storage/nvme5/new_clones/mcfunction/String-Parser' &
git clone https://github.com/TUSB/TheUnusualSkyBlock '/storage/nvme5/new_clones/mcfunction/TheUnusualSkyBlock' &
git clone https://github.com/jhuckaby/magic-sorting-system '/storage/nvme5/new_clones/mcfunction/magic-sorting-system' &
git clone https://github.com/gibbsly/gm '/storage/nvme5/new_clones/mcfunction/gm' &
git clone https://github.com/wifi-left/Map-MiniGames '/storage/nvme5/new_clones/mcfunction/Map-MiniGames' &
git clone https://github.com/BPR02/SkyBlock_Collection '/storage/nvme5/new_clones/mcfunction/SkyBlock_Collection' &
git clone https://github.com/Ai-Akaishi/OhMyDat '/storage/nvme5/new_clones/mcfunction/OhMyDat' &
git clone https://github.com/K-bai/Minecraft-Ray-Collision-Detector '/storage/nvme5/new_clones/mcfunction/Minecraft-Ray-Collision-Detector' &
git clone https://github.com/Elemend/Vein-Miner-Unified '/storage/nvme5/new_clones/mcfunction/Vein-Miner-Unified' &
git clone https://github.com/LanternMC/load '/storage/nvme5/new_clones/mcfunction/load' &
git clone https://github.com/TheWii/immersive-soundscapes '/storage/nvme5/new_clones/mcfunction/immersive-soundscapes' &
git clone https://github.com/QuantumXenon/origins-plus-plus '/storage/nvme5/new_clones/mcfunction/origins-plus-plus' &
git clone https://github.com/Aeldrion/Iris '/storage/nvme5/new_clones/mcfunction/Iris' &
git clone https://github.com/GDColon/MC2GD '/storage/nvme5/new_clones/mcfunction/MC2GD' &
git clone https://github.com/Zungrysoft/The-Escher-Dimension '/storage/nvme5/new_clones/mcfunction/The-Escher-Dimension' &
git clone https://github.com/AjjMC/ajjgui '/storage/nvme5/new_clones/mcfunction/ajjgui' &
git clone https://github.com/slicedlime/Sacrifice '/storage/nvme5/new_clones/mcfunction/Sacrifice' &
git clone https://github.com/Scommander/ExplosionRebuilderDatapack '/storage/nvme5/new_clones/mcfunction/ExplosionRebuilderDatapack' &
git clone https://github.com/Dominexis/Doms-Nexus '/storage/nvme5/new_clones/mcfunction/Doms-Nexus' &
git clone https://github.com/Tschipcraft/dynamiclights '/storage/nvme5/new_clones/mcfunction/dynamiclights' &
git clone https://github.com/Aeldrion/AESTD '/storage/nvme5/new_clones/mcfunction/AESTD' &
git clone https://github.com/Arcensoth/tickbuster-datapack '/storage/nvme5/new_clones/mcfunction/tickbuster-datapack' &
git clone https://github.com/ICY105/CaveBiomes '/storage/nvme5/new_clones/mcfunction/CaveBiomes' &
git clone https://github.com/CloudWolfYT/MC-GUIFramework '/storage/nvme5/new_clones/mcfunction/MC-GUIFramework' &
git clone https://github.com/DeadlyMC/Skyblock-datapack '/storage/nvme5/new_clones/mcfunction/Skyblock-datapack' &
git clone https://github.com/Aeldrion/Minecraft-Random '/storage/nvme5/new_clones/mcfunction/Minecraft-Random' &
git clone https://github.com/zeinlol/Witchcraft-and-Wizardry-in-Russian '/storage/nvme5/new_clones/mcfunction/Witchcraft-and-Wizardry-in-Russian' &
git clone https://github.com/DMBuce/bucepack '/storage/nvme5/new_clones/mcfunction/bucepack' &
git clone https://github.com/MadCatHoG/OnePlayerSleepV3-Data-Pack '/storage/nvme5/new_clones/mcfunction/OnePlayerSleepV3-Data-Pack' &
git clone https://github.com/slicedlime/LimesAdvancements '/storage/nvme5/new_clones/mcfunction/LimesAdvancements' &
git clone https://github.com/hanmindev/Hmmm '/storage/nvme5/new_clones/mcfunction/Hmmm' &
git clone https://github.com/tml104/-Minecraft-Dou-Dizhu '/storage/nvme5/new_clones/mcfunction/-Minecraft-Dou-Dizhu' &
git clone https://github.com/Hex-Dragon/LTW3 '/storage/nvme5/new_clones/mcfunction/LTW3' &
git clone https://github.com/rarula/Sketch '/storage/nvme5/new_clones/mcfunction/Sketch' &
git clone https://github.com/xwjcool123/BlockTuner '/storage/nvme5/new_clones/mcfunction/BlockTuner' &
git clone https://github.com/Nishitox/KCDK '/storage/nvme5/new_clones/mcfunction/KCDK' &
git clone https://github.com/Seeloewen/Random-Item-Giver-Datapack '/storage/nvme5/new_clones/mcfunction/Random-Item-Giver-Datapack' &
git clone https://github.com/GrantGryczan/Miroware '/storage/nvme5/new_clones/mcfunction/Miroware' &
git clone https://github.com/Chuzume/Chuzume-s-Toolbox '/storage/nvme5/new_clones/mcfunction/Chuzume-s-Toolbox' &
git clone https://github.com/oOBoomberOo/armor_stand_editor '/storage/nvme5/new_clones/mcfunction/armor_stand_editor' &
git clone https://github.com/ChenCMD/MCCMD-ScoreDamage '/storage/nvme5/new_clones/mcfunction/MCCMD-ScoreDamage' &
git clone https://github.com/SteveKunG/Datapacks-1.16 '/storage/nvme5/new_clones/mcfunction/Datapacks-1.16' &
git clone https://github.com/Chuzume/Momentum-Hookshot '/storage/nvme5/new_clones/mcfunction/Momentum-Hookshot' &
git clone https://github.com/NOPEname/nn_math '/storage/nvme5/new_clones/mcfunction/nn_math' &
git clone https://github.com/Chuzume/Chuzume-s-Items '/storage/nvme5/new_clones/mcfunction/Chuzume-s-Items' &
git clone https://github.com/CodeMouse92/no-monster-minecraft '/storage/nvme5/new_clones/mcfunction/no-monster-minecraft' &
git clone https://github.com/slicedlime/EpicWeapons '/storage/nvme5/new_clones/mcfunction/EpicWeapons' &
git clone https://github.com/flashteens/FTMCRailBuilder13 '/storage/nvme5/new_clones/mcfunction/FTMCRailBuilder13' &
git clone https://github.com/Tschipcraft/spawnanimations '/storage/nvme5/new_clones/mcfunction/spawnanimations' &
git clone https://github.com/CloudWolfYT/WASD-Detection '/storage/nvme5/new_clones/mcfunction/WASD-Detection' &
git clone https://github.com/5uso/Mod-Warnings '/storage/nvme5/new_clones/mcfunction/Mod-Warnings' &
git clone https://github.com/mokkkk/nukk_mh_dp '/storage/nvme5/new_clones/mcfunction/nukk_mh_dp' &
git clone https://github.com/K-bai/Terrain-Creator '/storage/nvme5/new_clones/mcfunction/Terrain-Creator' &
git clone https://github.com/GamuKamui/Extra-tag-player-addon '/storage/nvme5/new_clones/mcfunction/Extra-tag-player-addon' &
git clone https://github.com/DrHaid/bible-in-minecraft '/storage/nvme5/new_clones/mcfunction/bible-in-minecraft' &
git clone https://github.com/theomorphic/Lagan '/storage/nvme5/new_clones/mcfunction/Lagan' &
git clone https://github.com/MinervaMc/Datapacks '/storage/nvme5/new_clones/mcfunction/Datapacks' &
git clone https://github.com/oOBoomberOo/veinminer '/storage/nvme5/new_clones/mcfunction/veinminer' &
git clone https://github.com/hanmindev/cloth_physics '/storage/nvme5/new_clones/mcfunction/cloth_physics' &
git clone https://github.com/osfanbuff63/minecraft-datapack '/storage/nvme5/new_clones/mcfunction/minecraft-datapack' &
git clone https://github.com/Smithed-MC/Libraries '/storage/nvme5/new_clones/mcfunction/Libraries' &
git clone https://github.com/Ai-Akaishi/ScoreToHealth '/storage/nvme5/new_clones/mcfunction/ScoreToHealth' &
git clone https://github.com/Elemend/Builders-Wand '/storage/nvme5/new_clones/mcfunction/Builders-Wand' &
git clone https://github.com/ICY105/PlayerAction '/storage/nvme5/new_clones/mcfunction/PlayerAction' &
git clone https://github.com/tempestsbox/ttb '/storage/nvme5/new_clones/mcfunction/ttb' &
git clone https://github.com/slicedlime/MobDash '/storage/nvme5/new_clones/mcfunction/MobDash' &
git clone https://github.com/MadCatHoG/OnePlayerSleepV4-Data-Pack '/storage/nvme5/new_clones/mcfunction/OnePlayerSleepV4-Data-Pack' &
git clone https://github.com/Medacorp/Luigi-s-Mansion '/storage/nvme5/new_clones/mcfunction/Luigi-s-Mansion' &
git clone https://github.com/picarrow/hit-match '/storage/nvme5/new_clones/mcfunction/hit-match' &
git clone https://github.com/Chuzume/True-Crafter-Mode '/storage/nvme5/new_clones/mcfunction/True-Crafter-Mode' &
git clone https://github.com/SL0ANE/ChatBox '/storage/nvme5/new_clones/mcfunction/ChatBox' &
git clone https://github.com/Ai-Akaishi/AiMath '/storage/nvme5/new_clones/mcfunction/AiMath' &
git clone https://github.com/ZeroniaServer/RocketRiders '/storage/nvme5/new_clones/mcfunction/RocketRiders' &
git clone https://github.com/ANightDazingZoroark/Prehistoric-Rift-Addon '/storage/nvme5/new_clones/mcfunction/Prehistoric-Rift-Addon' &
git clone https://github.com/JesKi13567/BedWars '/storage/nvme5/new_clones/mcfunction/BedWars' &
git clone https://github.com/misode/Skymode4 '/storage/nvme5/new_clones/mcfunction/Skymode4' &
git clone https://github.com/Frektip/Technical-Enchant-Renewed '/storage/nvme5/new_clones/mcfunction/Technical-Enchant-Renewed' &
git clone https://github.com/Mr-k-bear/MCPack-DoggySurvival '/storage/nvme5/new_clones/mcfunction/MCPack-DoggySurvival' &
git clone https://github.com/Tschipcraft/deathanimations_test '/storage/nvme5/new_clones/mcfunction/deathanimations_test' &
git clone https://github.com/AllTheMods/ATM-Fabric '/storage/nvme5/new_clones/mcfunction/ATM-Fabric' &
git clone https://github.com/McTsts/inv-manipulation '/storage/nvme5/new_clones/mcfunction/inv-manipulation' &
git clone https://github.com/LTHC-s-Datapack/LTHC-s-Magic-And-Spells-Universe '/storage/nvme5/new_clones/mcfunction/LTHC-s-Magic-And-Spells-Universe' &
git clone https://github.com/Ellivers/WorldTool '/storage/nvme5/new_clones/mcfunction/WorldTool' &
git clone https://github.com/b01lers/b01lers-ctf-2021 '/storage/nvme5/new_clones/mcfunction/b01lers-ctf-2021' &
git clone https://github.com/Moesh/Calamity '/storage/nvme5/new_clones/mcfunction/Calamity' &
git clone https://github.com/LeonidMem/CoreM '/storage/nvme5/new_clones/mcfunction/CoreM' &
git clone https://github.com/Stoupy51/SimplEnergy '/storage/nvme5/new_clones/mcfunction/SimplEnergy' &
git clone https://github.com/hampfh/Datapack_SurvivalGames '/storage/nvme5/new_clones/mcfunction/Datapack_SurvivalGames' &
git clone https://github.com/TheWii/auto-utilities-vein-mining '/storage/nvme5/new_clones/mcfunction/auto-utilities-vein-mining' &
git clone https://github.com/moxvallix/moxlib '/storage/nvme5/new_clones/mcfunction/moxlib' &
git clone https://github.com/ICY105/DatapackEnergy '/storage/nvme5/new_clones/mcfunction/DatapackEnergy' &
git clone https://github.com/tryashtar/datapacks '/storage/nvme5/new_clones/mcfunction/datapacks' &
git clone https://github.com/BigPapi13/NBT-Crafting-API '/storage/nvme5/new_clones/mcfunction/NBT-Crafting-API' &
git clone https://github.com/CiscuLog/Survivor-s-Elegy '/storage/nvme5/new_clones/mcfunction/Survivor-s-Elegy' &
git clone https://github.com/Chuzume/Craftsman_Arms '/storage/nvme5/new_clones/mcfunction/Craftsman_Arms' &
git clone https://github.com/teaconmc/Puer '/storage/nvme5/new_clones/mcfunction/Puer' &
git clone https://github.com/5uso/SidebarDisplayExample '/storage/nvme5/new_clones/mcfunction/SidebarDisplayExample' &
git clone https://github.com/uran247/voxel-planes-datapack '/storage/nvme5/new_clones/mcfunction/voxel-planes-datapack' &
git clone https://github.com/ICY105/CombatPlus '/storage/nvme5/new_clones/mcfunction/CombatPlus' &
git clone https://github.com/slicedlime/Distancing '/storage/nvme5/new_clones/mcfunction/Distancing' &
git clone https://github.com/dhouck/anti-creeper-grief '/storage/nvme5/new_clones/mcfunction/anti-creeper-grief' &
git clone https://github.com/oOBoomberOo/carpet_on_stairs '/storage/nvme5/new_clones/mcfunction/carpet_on_stairs' &
git clone https://github.com/MukiTanuki/armor-statues '/storage/nvme5/new_clones/mcfunction/armor-statues' &
git clone https://github.com/gibbsly/ltos '/storage/nvme5/new_clones/mcfunction/ltos' &
git clone https://github.com/bongbongsaysbong/Manic '/storage/nvme5/new_clones/mcfunction/Manic' &
git clone https://github.com/daenvil/vegancraft '/storage/nvme5/new_clones/mcfunction/vegancraft' &
git clone https://github.com/Stoupy51/StardustFragment '/storage/nvme5/new_clones/mcfunction/StardustFragment' &
git clone https://github.com/Irohamaru/SmartMotion '/storage/nvme5/new_clones/mcfunction/SmartMotion' &
git clone https://github.com/r0hkx/vine-ssg-practice '/storage/nvme5/new_clones/mcfunction/vine-ssg-practice' &
git clone https://github.com/MSpaceDev/HermitcraftDatapacks '/storage/nvme5/new_clones/mcfunction/HermitcraftDatapacks' &
git clone https://github.com/txkodo/FloatCalc '/storage/nvme5/new_clones/mcfunction/FloatCalc' &
git clone https://github.com/rx-modules/EnderChestPlus '/storage/nvme5/new_clones/mcfunction/EnderChestPlus' &
git clone https://github.com/adambyle/ultima '/storage/nvme5/new_clones/mcfunction/ultima' &
git clone https://github.com/PeerHeer/minecraft-brainfuck '/storage/nvme5/new_clones/mcfunction/minecraft-brainfuck' &
git clone https://github.com/RedSparr0w/hunters_and_runners '/storage/nvme5/new_clones/mcfunction/hunters_and_runners' &
git clone https://github.com/Sir-Chi/MCBingo '/storage/nvme5/new_clones/mcfunction/MCBingo' &
git clone https://github.com/lpsmods/more-food '/storage/nvme5/new_clones/mcfunction/more-food' &
git clone https://github.com/Loweredgames/Skyblock-Classic-Edition '/storage/nvme5/new_clones/mcfunction/Skyblock-Classic-Edition' &
git clone https://github.com/skztr/xopt '/storage/nvme5/new_clones/mcfunction/xopt' &
git clone https://github.com/Marcono1234/light-level-datapack '/storage/nvme5/new_clones/mcfunction/light-level-datapack' &
git clone https://github.com/Gunivers/Blazing-Scaffolding '/storage/nvme5/new_clones/mcfunction/Blazing-Scaffolding' &
git clone https://github.com/Uziuukky/Minecraft-Factory '/storage/nvme5/new_clones/mcfunction/Minecraft-Factory' &
git clone https://github.com/Tristan-Magers/dueltnt '/storage/nvme5/new_clones/mcfunction/dueltnt' &
git clone https://github.com/LogicalGeekBoy/logical-crafting '/storage/nvme5/new_clones/mcfunction/logical-crafting' &
git clone https://github.com/DBTDerpbox/LCE-LargePlus '/storage/nvme5/new_clones/mcfunction/LCE-LargePlus' &
git clone https://github.com/edayot/SimpleDrawer '/storage/nvme5/new_clones/mcfunction/SimpleDrawer' &
git clone https://github.com/BPR02/MC-Advent-of-Code-2022 '/storage/nvme5/new_clones/mcfunction/MC-Advent-of-Code-2022' &
git clone https://github.com/RedstoneChicken/Krafted '/storage/nvme5/new_clones/mcfunction/Krafted' &
git clone https://github.com/slicedlime/HalfHearted '/storage/nvme5/new_clones/mcfunction/HalfHearted' &
git clone https://github.com/seesee777/LemonTea '/storage/nvme5/new_clones/mcfunction/LemonTea' &
git clone https://github.com/xuetaolu/minecraft-function-builder '/storage/nvme5/new_clones/mcfunction/minecraft-function-builder' &
git clone https://github.com/rx-modules/ListDB '/storage/nvme5/new_clones/mcfunction/ListDB' &
git clone https://github.com/Moesh-zz/Calamity '/storage/nvme5/new_clones/mcfunction/Calamity' &
git clone https://github.com/Irohamaru/SoundSample '/storage/nvme5/new_clones/mcfunction/SoundSample' &
git clone https://github.com/ps-dps/KeepSomeInventory '/storage/nvme5/new_clones/mcfunction/KeepSomeInventory' &
git clone https://github.com/RedSparr0w/player_tracker '/storage/nvme5/new_clones/mcfunction/player_tracker' &
git clone https://github.com/RedSparr0w/block_shuffle '/storage/nvme5/new_clones/mcfunction/block_shuffle' &
git clone https://github.com/Scommander/AnimatedDoubleDoorsDatapack '/storage/nvme5/new_clones/mcfunction/AnimatedDoubleDoorsDatapack' &
git clone https://github.com/maxheyn/miniblock_traders '/storage/nvme5/new_clones/mcfunction/miniblock_traders' &
git clone https://github.com/ICY105/Immersive-Cooking '/storage/nvme5/new_clones/mcfunction/Immersive-Cooking' &
git clone https://github.com/Stardust-Labs-MC/Structory-Towers '/storage/nvme5/new_clones/mcfunction/Structory-Towers' &
git clone https://github.com/Noryea/manhunt-datapack '/storage/nvme5/new_clones/mcfunction/manhunt-datapack' &
git clone https://github.com/KiloCraft/KiloPack '/storage/nvme5/new_clones/mcfunction/KiloPack' &
git clone https://github.com/Chuzume/Disc_Gun '/storage/nvme5/new_clones/mcfunction/Disc_Gun' &
git clone https://github.com/Robified0/Classes '/storage/nvme5/new_clones/mcfunction/Classes' &
git clone https://github.com/MaxPastushkov/MinecraftComputer '/storage/nvme5/new_clones/mcfunction/MinecraftComputer' &
git clone https://github.com/Leumas2/Outside-Addon '/storage/nvme5/new_clones/mcfunction/Outside-Addon' &
git clone https://github.com/LTHCTheMaster/Magical-Elementalization '/storage/nvme5/new_clones/mcfunction/Magical-Elementalization' &
git clone https://github.com/Zefyro/Extended-Beacon-Range '/storage/nvme5/new_clones/mcfunction/Extended-Beacon-Range' &
git clone https://github.com/Flubberschnub/light-cycles '/storage/nvme5/new_clones/mcfunction/light-cycles' &
git clone https://github.com/MadCatHoG/ShulkerRespawn-DataPack '/storage/nvme5/new_clones/mcfunction/ShulkerRespawn-DataPack' &
git clone https://github.com/ephf/datapacks '/storage/nvme5/new_clones/mcfunction/datapacks' &
git clone https://github.com/dthigpen/dtcraft-datapacks '/storage/nvme5/new_clones/mcfunction/dtcraft-datapacks' &
git clone https://github.com/Ai-Akaishi/CloseDetector '/storage/nvme5/new_clones/mcfunction/CloseDetector' &
git clone https://github.com/cda94581/open-source-chunk-loaders '/storage/nvme5/new_clones/mcfunction/open-source-chunk-loaders' &
git clone https://github.com/TheWii/auto-utilities-crops '/storage/nvme5/new_clones/mcfunction/auto-utilities-crops' &
git clone https://github.com/Nincodedo/rhc-ocw '/storage/nvme5/new_clones/mcfunction/rhc-ocw' &
git clone https://github.com/Mihro/MNAF-Senary-Saloon '/storage/nvme5/new_clones/mcfunction/MNAF-Senary-Saloon' &
git clone https://github.com/MadCatHoG/MobHeadDropsV5 '/storage/nvme5/new_clones/mcfunction/MobHeadDropsV5' &
git clone https://github.com/slicedlime/Entrapment '/storage/nvme5/new_clones/mcfunction/Entrapment' &
git clone https://github.com/Daily-Datapackers/datapack '/storage/nvme5/new_clones/mcfunction/datapack' &
