#!/bin/bash

git clone https://github.com/OpenModelica/OpenModelica '/storage/nvme5/new_clones/Modelica/OpenModelica' &
git clone https://github.com/modelica/ModelicaStandardLibrary '/storage/nvme5/new_clones/Modelica/ModelicaStandardLibrary' &
git clone https://github.com/lbl-srg/modelica-buildings '/storage/nvme5/new_clones/Modelica/modelica-buildings' &
git clone https://github.com/RWTH-EBC/AixLib '/storage/nvme5/new_clones/Modelica/AixLib' &
git clone https://github.com/ibpsa/modelica-ibpsa '/storage/nvme5/new_clones/Modelica/modelica-ibpsa' &
git clone https://github.com/open-ideas/IDEAS '/storage/nvme5/new_clones/Modelica/IDEAS' &
git clone https://github.com/ibpsa/project1-boptest '/storage/nvme5/new_clones/Modelica/project1-boptest' &
git clone https://github.com/DFINITY-Education/blockchain-and-cryptocurrency '/storage/nvme5/new_clones/Modelica/blockchain-and-cryptocurrency' &
git clone https://github.com/modelica-3rdparty/Modelica_DeviceDrivers '/storage/nvme5/new_clones/Modelica/Modelica_DeviceDrivers' &
git clone https://github.com/hyumo/ModelicaPrimer '/storage/nvme5/new_clones/Modelica/ModelicaPrimer' &
git clone https://github.com/UdK-VPT/BuildingSystems '/storage/nvme5/new_clones/Modelica/BuildingSystems' &
git clone https://github.com/DLR-SR/ThermofluidStream '/storage/nvme5/new_clones/Modelica/ThermofluidStream' &
git clone https://github.com/modelica-3rdparty/PowerSystems '/storage/nvme5/new_clones/Modelica/PowerSystems' &
git clone https://github.com/ORNL-Modelica/TRANSFORM-Library '/storage/nvme5/new_clones/Modelica/TRANSFORM-Library' &
git clone https://github.com/JModelica/JModelica '/storage/nvme5/new_clones/Modelica/JModelica' &
git clone https://github.com/modelica-3rdparty/WasteWater '/storage/nvme5/new_clones/Modelica/WasteWater' &
git clone https://github.com/Zverik/Level0 '/storage/nvme5/new_clones/Modelica/Level0' &
git clone https://github.com/thermocycle/Thermocycle-library '/storage/nvme5/new_clones/Modelica/Thermocycle-library' &
git clone https://github.com/OpenModelica/OMCompiler '/storage/nvme5/new_clones/Modelica/OMCompiler' &
git clone https://github.com/ibpsa/project1 '/storage/nvme5/new_clones/Modelica/project1' &
git clone https://github.com/MarekMatejak/Chemical '/storage/nvme5/new_clones/Modelica/Chemical' &
git clone https://github.com/queraltab/Greenhouses-Library '/storage/nvme5/new_clones/Modelica/Greenhouses-Library' &
git clone https://github.com/ALSETLab/Modelica-Drone-3D-FMI '/storage/nvme5/new_clones/Modelica/Modelica-Drone-3D-FMI' &
git clone https://github.com/modelica-3rdparty/ElectricalEnergyStorage '/storage/nvme5/new_clones/Modelica/ElectricalEnergyStorage' &
git clone https://github.com/modelica/VehicleInterfaces '/storage/nvme5/new_clones/Modelica/VehicleInterfaces' &
git clone https://github.com/casella/ThermoPower '/storage/nvme5/new_clones/Modelica/ThermoPower' &
git clone https://github.com/EDF-Lab/BuildSysPro '/storage/nvme5/new_clones/Modelica/BuildSysPro' &
git clone https://github.com/modelica-3rdparty/OpenHydraulics '/storage/nvme5/new_clones/Modelica/OpenHydraulics' &
git clone https://github.com/FOSSEE/OMChemSim '/storage/nvme5/new_clones/Modelica/OMChemSim' &
git clone https://github.com/PowerGrids/PowerGrids '/storage/nvme5/new_clones/Modelica/PowerGrids' &
git clone https://github.com/DFINITY-Education/protocol-design '/storage/nvme5/new_clones/Modelica/protocol-design' &
git clone https://github.com/thorade/HelmholtzMedia '/storage/nvme5/new_clones/Modelica/HelmholtzMedia' &
git clone https://github.com/MarekMatejak/Physiolibrary '/storage/nvme5/new_clones/Modelica/Physiolibrary' &
git clone https://github.com/DFINITY-Education/data-structures '/storage/nvme5/new_clones/Modelica/data-structures' &
git clone https://github.com/open-ideas/FastBuildings '/storage/nvme5/new_clones/Modelica/FastBuildings' &
git clone https://github.com/Virtual-FCS/VirtualFCS '/storage/nvme5/new_clones/Modelica/VirtualFCS' &
git clone https://github.com/raulrpearson/PVSystems '/storage/nvme5/new_clones/Modelica/PVSystems' &
git clone https://github.com/ThermoSysPro/ThermoSysPro '/storage/nvme5/new_clones/Modelica/ThermoSysPro' &
git clone https://github.com/kritzcreek/motoko-library-template '/storage/nvme5/new_clones/Modelica/motoko-library-template' &
git clone https://github.com/Web3NL/motoko-book '/storage/nvme5/new_clones/Modelica/motoko-book' &
git clone https://github.com/dzimmer/PlanarMechanics '/storage/nvme5/new_clones/Modelica/PlanarMechanics' &
git clone https://github.com/Metroscope-dev/metroscope-modeling-library '/storage/nvme5/new_clones/Modelica/metroscope-modeling-library' &
git clone https://github.com/christiankral/HanserModelica '/storage/nvme5/new_clones/Modelica/HanserModelica' &
git clone https://github.com/henze-research-group/MODRLC '/storage/nvme5/new_clones/Modelica/MODRLC' &
git clone https://github.com/christiankral/PhotoVoltaics '/storage/nvme5/new_clones/Modelica/PhotoVoltaics' &
git clone https://github.com/JKRT/OM.jl '/storage/nvme5/new_clones/Modelica/OM.jl' &
git clone https://github.com/matthewhammer/motoko-crud '/storage/nvme5/new_clones/Modelica/motoko-crud' &
git clone https://github.com/eyyi/dymrl '/storage/nvme5/new_clones/Modelica/dymrl' &
git clone https://github.com/jonathanshum/Integrated-Tool-Suite '/storage/nvme5/new_clones/Modelica/Integrated-Tool-Suite' &
git clone https://github.com/bslMS/BusinessSimulation '/storage/nvme5/new_clones/Modelica/BusinessSimulation' &
git clone https://github.com/itesla/ipsl '/storage/nvme5/new_clones/Modelica/ipsl' &
git clone https://github.com/christiankral/WindPowerPlants '/storage/nvme5/new_clones/Modelica/WindPowerPlants' &
git clone https://github.com/OpenSimHub/OpenHPL '/storage/nvme5/new_clones/Modelica/OpenHPL' &
git clone https://github.com/modelica/Modelica_LinearSystems2 '/storage/nvme5/new_clones/Modelica/Modelica_LinearSystems2' &
git clone https://github.com/lbl-srg/soep '/storage/nvme5/new_clones/Modelica/soep' &
git clone https://github.com/Toniq-Labs/wrapped_cycles '/storage/nvme5/new_clones/Modelica/wrapped_cycles' &
git clone https://github.com/tgalal/motoko-bitcoin '/storage/nvme5/new_clones/Modelica/motoko-bitcoin' &
git clone https://github.com/enzoh/motoko-qr '/storage/nvme5/new_clones/Modelica/motoko-qr' &
git clone https://github.com/casella/ScalableTestSuite '/storage/nvme5/new_clones/Modelica/ScalableTestSuite' &
git clone https://github.com/SuddenlyHazel/DIP721 '/storage/nvme5/new_clones/Modelica/DIP721' &
git clone https://github.com/mbonvini/IndustrialControlSystems '/storage/nvme5/new_clones/Modelica/IndustrialControlSystems' &
git clone https://github.com/UdK-VPT/BIM2Modelica '/storage/nvme5/new_clones/Modelica/BIM2Modelica' &
git clone https://github.com/RWTH-EBC/BESMod '/storage/nvme5/new_clones/Modelica/BESMod' &
git clone https://github.com/DFINITY-Education/distributed-systems '/storage/nvme5/new_clones/Modelica/distributed-systems' &
git clone https://github.com/justnielsen/ModelicaTutorials '/storage/nvme5/new_clones/Modelica/ModelicaTutorials' &
git clone https://github.com/ORIGYN-SA/motoko_top_up_canister '/storage/nvme5/new_clones/Modelica/motoko_top_up_canister' &
git clone https://github.com/ClaRaLibrary/ClaRa '/storage/nvme5/new_clones/Modelica/ClaRa' &
git clone https://github.com/modelica/Modelica-Compliance '/storage/nvme5/new_clones/Modelica/Modelica-Compliance' &
git clone https://github.com/DFINITY-Education/governance '/storage/nvme5/new_clones/Modelica/governance' &
git clone https://github.com/matthewhammer/motoko-graph '/storage/nvme5/new_clones/Modelica/motoko-graph' &
git clone https://github.com/nomeata/motoko-certified-http '/storage/nvme5/new_clones/Modelica/motoko-certified-http' &
git clone https://github.com/enzoh/motoko-sha '/storage/nvme5/new_clones/Modelica/motoko-sha' &
git clone https://github.com/xogeny/XogenyTest '/storage/nvme5/new_clones/Modelica/XogenyTest' &
git clone https://github.com/BasilioPV/ShipSIM '/storage/nvme5/new_clones/Modelica/ShipSIM' &
git clone https://github.com/enzoh/chronosphere '/storage/nvme5/new_clones/Modelica/chronosphere' &
git clone https://github.com/AIT-IES/DisHeatLib '/storage/nvme5/new_clones/Modelica/DisHeatLib' &
git clone https://github.com/ClaRaLibrary/TransiEnt '/storage/nvme5/new_clones/Modelica/TransiEnt' &
git clone https://github.com/sungwookwi/VIC-ASSIST '/storage/nvme5/new_clones/Modelica/VIC-ASSIST' &
git clone https://github.com/SysMLModelicaIntegration/edu.gatech.mbse.mdsysmlmodelica '/storage/nvme5/new_clones/Modelica/edu.gatech.mbse.mdsysmlmodelica' &
git clone https://github.com/matthewhammer/candid-spaces '/storage/nvme5/new_clones/Modelica/candid-spaces' &
git clone https://github.com/OpenModelica/OMSens '/storage/nvme5/new_clones/Modelica/OMSens' &
git clone https://github.com/AMIT-HSBI/PNlib '/storage/nvme5/new_clones/Modelica/PNlib' &
git clone https://github.com/TechnicalBuildingSystems/BuildingControlLib '/storage/nvme5/new_clones/Modelica/BuildingControlLib' &
git clone https://github.com/modelica-3rdparty/Modelica_Requirements '/storage/nvme5/new_clones/Modelica/Modelica_Requirements' &
git clone https://github.com/SuddenlyHazel/dfinity_nft '/storage/nvme5/new_clones/Modelica/dfinity_nft' &
git clone https://github.com/ClaRaLibrary/TILMedia '/storage/nvme5/new_clones/Modelica/TILMedia' &
git clone https://github.com/DLR-SR/AdvancedNoise '/storage/nvme5/new_clones/Modelica/AdvancedNoise' &
git clone https://github.com/matthewhammer/motoko-bigtest '/storage/nvme5/new_clones/Modelica/motoko-bigtest' &
git clone https://github.com/metamorph-inc/metamorphosys-desktop '/storage/nvme5/new_clones/Modelica/metamorphosys-desktop' &
git clone https://github.com/MoSDH/MoSDH '/storage/nvme5/new_clones/Modelica/MoSDH' &
git clone https://github.com/rocklabs-io/dtoken '/storage/nvme5/new_clones/Modelica/dtoken' &
git clone https://github.com/physiology/Physiomodel '/storage/nvme5/new_clones/Modelica/Physiomodel' &
git clone https://github.com/modelica-deprecated/Modelica_Synchronous '/storage/nvme5/new_clones/Modelica/Modelica_Synchronous' &
git clone https://github.com/ClaRaLibrary/FluidDissipation '/storage/nvme5/new_clones/Modelica/FluidDissipation' &
git clone https://github.com/matthewhammer/cleansheets '/storage/nvme5/new_clones/Modelica/cleansheets' &
git clone https://github.com/jorgenbuilder/ext-nft-example '/storage/nvme5/new_clones/Modelica/ext-nft-example' &
git clone https://github.com/upb-lea/OpenModelica_Microgrids '/storage/nvme5/new_clones/Modelica/OpenModelica_Microgrids' &
git clone https://github.com/DLR-SR/FaultTriggering '/storage/nvme5/new_clones/Modelica/FaultTriggering' &
git clone https://github.com/souradipp76/OpenModelica-HIL '/storage/nvme5/new_clones/Modelica/OpenModelica-HIL' &
git clone https://github.com/OpenModelica/OpenModelica-testsuite '/storage/nvme5/new_clones/Modelica/OpenModelica-testsuite' &
git clone https://github.com/UedaShigenori/OpenModelica_Tutorials_Ja '/storage/nvme5/new_clones/Modelica/OpenModelica_Tutorials_Ja' &
git clone https://github.com/TransiEnt-official/transient-lib '/storage/nvme5/new_clones/Modelica/transient-lib' &
git clone https://github.com/ATAEngineering/RotorAeroLib '/storage/nvme5/new_clones/Modelica/RotorAeroLib' &
git clone https://github.com/DLR-SR/Noise '/storage/nvme5/new_clones/Modelica/Noise' &
git clone https://github.com/ibpsa/project1-wp-2-2-bim '/storage/nvme5/new_clones/Modelica/project1-wp-2-2-bim' &
git clone https://github.com/ibpsa/modelica-ibpsa-mpc '/storage/nvme5/new_clones/Modelica/modelica-ibpsa-mpc' &
git clone https://github.com/jobehrendt/OpenWasteWater '/storage/nvme5/new_clones/Modelica/OpenWasteWater' &
git clone https://github.com/NnsDao/ICTexas-UI '/storage/nvme5/new_clones/Modelica/ICTexas-UI' &
git clone https://github.com/SuddenlyHazel/dfinity-blog '/storage/nvme5/new_clones/Modelica/dfinity-blog' &
git clone https://github.com/ThummeTo/FMIZoo.jl '/storage/nvme5/new_clones/Modelica/FMIZoo.jl' &
git clone https://github.com/modelica-3rdparty/LinearMPC '/storage/nvme5/new_clones/Modelica/LinearMPC' &
git clone https://github.com/fiber-miniapp/ntchem-mini '/storage/nvme5/new_clones/Modelica/ntchem-mini' &
git clone https://github.com/ATAEngineering/DeployStructLib '/storage/nvme5/new_clones/Modelica/DeployStructLib' &
git clone https://github.com/gheralb/Soltermica '/storage/nvme5/new_clones/Modelica/Soltermica' &
git clone https://github.com/esensconsulting/KanbanIC '/storage/nvme5/new_clones/Modelica/KanbanIC' &
git clone https://github.com/DTU-TES/Hydrogen-Fuelling-Station '/storage/nvme5/new_clones/Modelica/Hydrogen-Fuelling-Station' &
git clone https://github.com/lenaRB/crml-compiler '/storage/nvme5/new_clones/Modelica/crml-compiler' &
git clone https://github.com/mbonvini/CFDModelica '/storage/nvme5/new_clones/Modelica/CFDModelica' &
git clone https://github.com/nomeata/ic-barrier '/storage/nvme5/new_clones/Modelica/ic-barrier' &
git clone https://github.com/yinliang1978/exergy '/storage/nvme5/new_clones/Modelica/exergy' &
git clone https://github.com/modelica-3rdparty/RealTimeCoordinationLibrary '/storage/nvme5/new_clones/Modelica/RealTimeCoordinationLibrary' &
git clone https://github.com/AIT-TES/slPCMlib '/storage/nvme5/new_clones/Modelica/slPCMlib' &
git clone https://github.com/dzimmer/ZimmersModelicaTutorial '/storage/nvme5/new_clones/Modelica/ZimmersModelicaTutorial' &
git clone https://github.com/ModelicaLibraryStudyMeeting/ModelicaLibraryStudyMeeting_ja '/storage/nvme5/new_clones/Modelica/ModelicaLibraryStudyMeeting_ja' &
git clone https://github.com/beutlich/LastLib '/storage/nvme5/new_clones/Modelica/LastLib' &
git clone https://github.com/letmejustputthishere/game_of_life '/storage/nvme5/new_clones/Modelica/game_of_life' &
git clone https://github.com/looms-polimi/IndustrialControlSystems '/storage/nvme5/new_clones/Modelica/IndustrialControlSystems' &
git clone https://github.com/LBNL-ETA/ESL '/storage/nvme5/new_clones/Modelica/ESL' &
git clone https://github.com/SenHuang19/BuildingHVAC '/storage/nvme5/new_clones/Modelica/BuildingHVAC' &
git clone https://github.com/jdominguezj/EVLibrary '/storage/nvme5/new_clones/Modelica/EVLibrary' &
git clone https://github.com/kritzcreek/motoko-regex '/storage/nvme5/new_clones/Modelica/motoko-regex' &
git clone https://github.com/OpenModelica/BioChem '/storage/nvme5/new_clones/Modelica/BioChem' &
git clone https://github.com/ModROS/ROS_Bridge '/storage/nvme5/new_clones/Modelica/ROS_Bridge' &
git clone https://github.com/AHaumer/EMOTH '/storage/nvme5/new_clones/Modelica/EMOTH' &
git clone https://github.com/modelica-3rdparty/ObjectStab '/storage/nvme5/new_clones/Modelica/ObjectStab' &
git clone https://github.com/akashdeepsinghal/openmodelica-chemical '/storage/nvme5/new_clones/Modelica/openmodelica-chemical' &
git clone https://github.com/Heineken/BrineProp '/storage/nvme5/new_clones/Modelica/BrineProp' &
git clone https://github.com/egeyar/wochonecha '/storage/nvme5/new_clones/Modelica/wochonecha' &
git clone https://github.com/quintolet/randomness-oracle '/storage/nvme5/new_clones/Modelica/randomness-oracle' &
git clone https://github.com/ORNL-Modelica/TRANSFORM-Training '/storage/nvme5/new_clones/Modelica/TRANSFORM-Training' &
git clone https://github.com/sailfish-app/proposals '/storage/nvme5/new_clones/Modelica/proposals' &
git clone https://github.com/Toniq-Labs/ic-fungible-token '/storage/nvme5/new_clones/Modelica/ic-fungible-token' &
git clone https://github.com/matthewhammer/motoko-adapton '/storage/nvme5/new_clones/Modelica/motoko-adapton' &
git clone https://github.com/modelica-3rdparty/TechThermo '/storage/nvme5/new_clones/Modelica/TechThermo' &
git clone https://github.com/ModelicaLibraryStudyMeeting/ModelicaFluidTraining '/storage/nvme5/new_clones/Modelica/ModelicaFluidTraining' &
git clone https://github.com/modelica-3rdparty/Spot '/storage/nvme5/new_clones/Modelica/Spot' &
git clone https://github.com/wubonian/Modelica_TDL '/storage/nvme5/new_clones/Modelica/Modelica_TDL' &
git clone https://github.com/ic-rocks/metrics '/storage/nvme5/new_clones/Modelica/metrics' &
git clone https://github.com/FOSSEE/Chemical-Simulator-GUI '/storage/nvme5/new_clones/Modelica/Chemical-Simulator-GUI' &
git clone https://github.com/ALSETLab/RocketLanding '/storage/nvme5/new_clones/Modelica/RocketLanding' &
git clone https://github.com/yeus/mokalman '/storage/nvme5/new_clones/Modelica/mokalman' &
git clone https://github.com/RPI-CASE/RPI_CASE_ICS_Modelica '/storage/nvme5/new_clones/Modelica/RPI_CASE_ICS_Modelica' &
git clone https://github.com/SSModelGit/PowerGrab '/storage/nvme5/new_clones/Modelica/PowerGrab' &
git clone https://github.com/oestersoetebier/IdealizedContact '/storage/nvme5/new_clones/Modelica/IdealizedContact' &
git clone https://github.com/OpenModelica/OMWebEdit_archived '/storage/nvme5/new_clones/Modelica/OMWebEdit_archived' &
git clone https://github.com/metamorph-inc/openmeta-spacecraft-study '/storage/nvme5/new_clones/Modelica/openmeta-spacecraft-study' &
