#!/bin/bash

git clone https://github.com/lboasso/oberonc '/storage/nvme5/new_clones/Modula-2/oberonc' &
git clone https://github.com/andreaspirklbauer/Oberon-extended '/storage/nvme5/new_clones/Modula-2/Oberon-extended' &
git clone https://github.com/Spirit-of-Oberon/ProjectOberon2013 '/storage/nvme5/new_clones/Modula-2/ProjectOberon2013' &
git clone https://github.com/btreut/a2 '/storage/nvme5/new_clones/Modula-2/a2' &
git clone https://github.com/excelsior-oss/xds '/storage/nvme5/new_clones/Modula-2/xds' &
git clone https://github.com/congdm/Patchouli-Compiler '/storage/nvme5/new_clones/Modula-2/Patchouli-Compiler' &
git clone https://github.com/metacore/A2OS '/storage/nvme5/new_clones/Modula-2/A2OS' &
git clone https://github.com/Vostok-space/vostok '/storage/nvme5/new_clones/Modula-2/vostok' &
git clone https://github.com/jtempl/ofront '/storage/nvme5/new_clones/Modula-2/ofront' &
git clone https://github.com/Oric4ever/Turbo-Modula-2-Reloaded '/storage/nvme5/new_clones/Modula-2/Turbo-Modula-2-Reloaded' &
git clone https://github.com/pdewacht/project-norebo '/storage/nvme5/new_clones/Modula-2/project-norebo' &
git clone https://github.com/excelsior-oss/xds-2.60 '/storage/nvme5/new_clones/Modula-2/xds-2.60' &
git clone https://github.com/aixp/O7 '/storage/nvme5/new_clones/Modula-2/O7' &
git clone https://github.com/GunterMueller/N.Wirth_Compiler_Construction_Archived '/storage/nvme5/new_clones/Modula-2/N.Wirth_Compiler_Construction_Archived' &
git clone https://github.com/andreaspirklbauer/Oberon-building-tools '/storage/nvme5/new_clones/Modula-2/Oberon-building-tools' &
git clone https://github.com/trijezdci/MOCKA '/storage/nvme5/new_clones/Modula-2/MOCKA' &
git clone https://github.com/m2sf/m2bsk '/storage/nvme5/new_clones/Modula-2/m2bsk' &
git clone https://github.com/lboasso/oberon0 '/storage/nvme5/new_clones/Modula-2/oberon0' &
git clone https://github.com/k-john-gough/gpmclr '/storage/nvme5/new_clones/Modula-2/gpmclr' &
git clone https://github.com/pkclsoft/ORCA-Modula-2 '/storage/nvme5/new_clones/Modula-2/ORCA-Modula-2' &
git clone https://github.com/GunterMueller/Modula-2_Libraries '/storage/nvme5/new_clones/Modula-2/Modula-2_Libraries' &
git clone https://github.com/hansklav/Oberon-07 '/storage/nvme5/new_clones/Modula-2/Oberon-07' &
git clone https://github.com/metacore/A2Community '/storage/nvme5/new_clones/Modula-2/A2Community' &
git clone https://github.com/andreaspirklbauer/Oberon-retro-compiler '/storage/nvme5/new_clones/Modula-2/Oberon-retro-compiler' &
git clone https://github.com/illuria/manush '/storage/nvme5/new_clones/Modula-2/manush' &
git clone https://github.com/dcwbrown/O7 '/storage/nvme5/new_clones/Modula-2/O7' &
git clone https://github.com/andreaspirklbauer/Oberon-generic-heap-allocation '/storage/nvme5/new_clones/Modula-2/Oberon-generic-heap-allocation' &
git clone https://github.com/harrisonpartch/spasim '/storage/nvme5/new_clones/Modula-2/spasim' &
git clone https://github.com/trijezdci/m2cc '/storage/nvme5/new_clones/Modula-2/m2cc' &
git clone https://github.com/GunterMueller/DEC-Modula-2 '/storage/nvme5/new_clones/Modula-2/DEC-Modula-2' &
git clone https://github.com/sgreenhill/aria '/storage/nvme5/new_clones/Modula-2/aria' &
git clone https://github.com/turgu1/esp32-oberon-compiler '/storage/nvme5/new_clones/Modula-2/esp32-oberon-compiler' &
git clone https://github.com/GunterMueller/Corona_Modula2_Tutorial '/storage/nvme5/new_clones/Modula-2/Corona_Modula2_Tutorial' &
git clone https://github.com/GunterMueller/ETHZ-Modula-2_Compilers '/storage/nvme5/new_clones/Modula-2/ETHZ-Modula-2_Compilers' &
git clone https://github.com/vishapoberon/pio '/storage/nvme5/new_clones/Modula-2/pio' &
git clone https://github.com/solbjorg/oberon-riscv-overlays '/storage/nvme5/new_clones/Modula-2/oberon-riscv-overlays' &
git clone https://github.com/hgeisse/THM-Oberon '/storage/nvme5/new_clones/Modula-2/THM-Oberon' &
git clone https://github.com/rsdoiel/oberonv4 '/storage/nvme5/new_clones/Modula-2/oberonv4' &
git clone https://github.com/thutt/oberon '/storage/nvme5/new_clones/Modula-2/oberon' &
git clone https://github.com/schierlm/NativeOberon-2.3.6-Extracted '/storage/nvme5/new_clones/Modula-2/NativeOberon-2.3.6-Extracted' &
git clone https://github.com/andreaspirklbauer/Oberon-module-contexts '/storage/nvme5/new_clones/Modula-2/Oberon-module-contexts' &
git clone https://github.com/Oric4ever/Reversing-Turbo-Modula2 '/storage/nvme5/new_clones/Modula-2/Reversing-Turbo-Modula2' &
git clone https://github.com/lboasso/oberon0vm '/storage/nvme5/new_clones/Modula-2/oberon0vm' &
git clone https://github.com/sam-falvo/OberonSystem2013-srcs '/storage/nvme5/new_clones/Modula-2/OberonSystem2013-srcs' &
git clone https://github.com/andreaspirklbauer/Oberon-forward-references-of-procedures '/storage/nvme5/new_clones/Modula-2/Oberon-forward-references-of-procedures' &
git clone https://github.com/norayr/armdicto-hack '/storage/nvme5/new_clones/Modula-2/armdicto-hack' &
git clone https://github.com/valexey/bigbench '/storage/nvme5/new_clones/Modula-2/bigbench' &
git clone https://github.com/andreaspirklbauer/Oberon-module-imports '/storage/nvme5/new_clones/Modula-2/Oberon-module-imports' &
git clone https://github.com/norayr/o7c '/storage/nvme5/new_clones/Modula-2/o7c' &
git clone https://github.com/bobbl/oberon-riscv '/storage/nvme5/new_clones/Modula-2/oberon-riscv' &
git clone https://github.com/andreaspirklbauer/Oberon-no-access-to-intermediate-objects '/storage/nvme5/new_clones/Modula-2/Oberon-no-access-to-intermediate-objects' &
git clone https://github.com/schierlm/Oberon-Linux-Revival '/storage/nvme5/new_clones/Modula-2/Oberon-Linux-Revival' &
git clone https://github.com/andreaspirklbauer/Oberon-enhanced-Oberon07-compiler '/storage/nvme5/new_clones/Modula-2/Oberon-enhanced-Oberon07-compiler' &
git clone https://github.com/norayr/diaspora2hugo '/storage/nvme5/new_clones/Modula-2/diaspora2hugo' &
