#!/bin/bash

git clone https://github.com/borela/naomi '/storage/nvme5/new_clones/MQL4/naomi' &
git clone https://github.com/rosasurfer/mt4-mql-framework '/storage/nvme5/new_clones/MQL4/mt4-mql-framework' &
git clone https://github.com/dingmaotu/mt4-server '/storage/nvme5/new_clones/MQL4/mt4-server' &
git clone https://github.com/jiowcl/MQL-CopyTrade '/storage/nvme5/new_clones/MQL4/MQL-CopyTrade' &
git clone https://github.com/chaipat-ncm/learn2trade '/storage/nvme5/new_clones/MQL4/learn2trade' &
git clone https://github.com/Yumerain/EA-MQL4 '/storage/nvme5/new_clones/MQL4/EA-MQL4' &
git clone https://github.com/dennislwm/FX-Git '/storage/nvme5/new_clones/MQL4/FX-Git' &
git clone https://github.com/davejlin/trading '/storage/nvme5/new_clones/MQL4/trading' &
git clone https://github.com/BonneVoyager/MetaTrader4-Bridge '/storage/nvme5/new_clones/MQL4/MetaTrader4-Bridge' &
git clone https://github.com/mrhewitt/metatrader '/storage/nvme5/new_clones/MQL4/metatrader' &
git clone https://github.com/vivazzi/mql_requests '/storage/nvme5/new_clones/MQL4/mql_requests' &
git clone https://github.com/tanvird3/TradingRobot '/storage/nvme5/new_clones/MQL4/TradingRobot' &
git clone https://github.com/dingmaotu/mql4-lib-examples '/storage/nvme5/new_clones/MQL4/mql4-lib-examples' &
git clone https://github.com/nuric/mt4-tcp '/storage/nvme5/new_clones/MQL4/mt4-tcp' &
git clone https://github.com/goncaloe/nnfx-backtest-c1 '/storage/nvme5/new_clones/MQL4/nnfx-backtest-c1' &
git clone https://github.com/ersingencturk/FreeExpertAdvisor '/storage/nvme5/new_clones/MQL4/FreeExpertAdvisor' &
git clone https://github.com/peterszombati/metatrader4 '/storage/nvme5/new_clones/MQL4/metatrader4' &
git clone https://github.com/xszyou/Easy-Deal '/storage/nvme5/new_clones/MQL4/Easy-Deal' &
git clone https://github.com/frkn2076/XAUUSD-Forex '/storage/nvme5/new_clones/MQL4/XAUUSD-Forex' &
git clone https://github.com/gemgin/ExpertAdvisors '/storage/nvme5/new_clones/MQL4/ExpertAdvisors' &
git clone https://github.com/Financial-ML/Market-Analysis '/storage/nvme5/new_clones/MQL4/Market-Analysis' &
git clone https://github.com/CoeJoder/metatrader4-server '/storage/nvme5/new_clones/MQL4/metatrader4-server' &
git clone https://github.com/XC3S/MetaTrade2NodeJS '/storage/nvme5/new_clones/MQL4/MetaTrade2NodeJS' &
git clone https://github.com/vzhomeexperiments/FALCON_A '/storage/nvme5/new_clones/MQL4/FALCON_A' &
git clone https://github.com/Lucas170/Bonus-Chapter '/storage/nvme5/new_clones/MQL4/Bonus-Chapter' &
git clone https://github.com/Shk0da/Mt4 '/storage/nvme5/new_clones/MQL4/Mt4' &
git clone https://github.com/tickelton/mql4 '/storage/nvme5/new_clones/MQL4/mql4' &
git clone https://github.com/Lucas170/Chapter-3-All-Files '/storage/nvme5/new_clones/MQL4/Chapter-3-All-Files' &
git clone https://github.com/Syakyr/My-Trading-Project '/storage/nvme5/new_clones/MQL4/My-Trading-Project' &
git clone https://github.com/jbax7635/MQL4codeSamples '/storage/nvme5/new_clones/MQL4/MQL4codeSamples' &
git clone https://github.com/MShokry/Mansour_Bot_MQL4 '/storage/nvme5/new_clones/MQL4/Mansour_Bot_MQL4' &
git clone https://github.com/viktorzhong/mt4 '/storage/nvme5/new_clones/MQL4/mt4' &
git clone https://github.com/TobiahRex/EA '/storage/nvme5/new_clones/MQL4/EA' &
git clone https://github.com/hung96ad/MQL4_Experts '/storage/nvme5/new_clones/MQL4/MQL4_Experts' &
git clone https://github.com/TalaikisInc/data_server '/storage/nvme5/new_clones/MQL4/data_server' &
git clone https://github.com/altredo18/MQL4-ALTREDO '/storage/nvme5/new_clones/MQL4/MQL4-ALTREDO' &
git clone https://github.com/vivazzi/mql_unit_test '/storage/nvme5/new_clones/MQL4/mql_unit_test' &
git clone https://github.com/icefx/drawprofit '/storage/nvme5/new_clones/MQL4/drawprofit' &
git clone https://github.com/OwaisQuadri/SR-Expert '/storage/nvme5/new_clones/MQL4/SR-Expert' &
git clone https://github.com/koswag/metatrader-4-bot '/storage/nvme5/new_clones/MQL4/metatrader-4-bot' &
git clone https://github.com/aijy/MQL4_TUT '/storage/nvme5/new_clones/MQL4/MQL4_TUT' &
git clone https://github.com/Lucas170/The-Falcon '/storage/nvme5/new_clones/MQL4/The-Falcon' &
git clone https://github.com/vandyand/MetaTrader-EAs '/storage/nvme5/new_clones/MQL4/MetaTrader-EAs' &
git clone https://github.com/Oluwasakin-Tobi/MT4_Expert-Advisor '/storage/nvme5/new_clones/MQL4/MT4_Expert-Advisor' &
git clone https://github.com/JarvisLee0423/Chaotic_Quantum_Finance_AI_Predicted_Trading_System '/storage/nvme5/new_clones/MQL4/Chaotic_Quantum_Finance_AI_Predicted_Trading_System' &
git clone https://github.com/CDrosos/TradingSignals '/storage/nvme5/new_clones/MQL4/TradingSignals' &
git clone https://github.com/PranavSonar/mt4 '/storage/nvme5/new_clones/MQL4/mt4' &
git clone https://github.com/EA31337/EA31337-indicators-other '/storage/nvme5/new_clones/MQL4/EA31337-indicators-other' &
git clone https://github.com/EarnForex/RoundLevels '/storage/nvme5/new_clones/MQL4/RoundLevels' &
git clone https://github.com/vzhomeexperiments/FALCON_F2 '/storage/nvme5/new_clones/MQL4/FALCON_F2' &
git clone https://github.com/ehabyahia/MT4-Martingale-Bot-With-Reinforcement-Learning '/storage/nvme5/new_clones/MQL4/MT4-Martingale-Bot-With-Reinforcement-Learning' &
git clone https://github.com/spespe/Algo_trad_dev '/storage/nvme5/new_clones/MQL4/Algo_trad_dev' &
git clone https://github.com/alexvin8/metatrader4-harm_pets '/storage/nvme5/new_clones/MQL4/metatrader4-harm_pets' &
git clone https://github.com/Icus2/MT4-Expert-Advisors-and-Indie '/storage/nvme5/new_clones/MQL4/MT4-Expert-Advisors-and-Indie' &
git clone https://github.com/alexvin8/metatrader4-currencies-switcher '/storage/nvme5/new_clones/MQL4/metatrader4-currencies-switcher' &
git clone https://github.com/Yahao277/NNFX-EA-mql4 '/storage/nvme5/new_clones/MQL4/NNFX-EA-mql4' &
git clone https://github.com/LeonardoCiaccio/Position-Size-Calculator '/storage/nvme5/new_clones/MQL4/Position-Size-Calculator' &
git clone https://github.com/jiunnhwa/MT4TradeCopier '/storage/nvme5/new_clones/MQL4/MT4TradeCopier' &
git clone https://github.com/ling007/MQL4 '/storage/nvme5/new_clones/MQL4/MQL4' &
git clone https://github.com/pr1266/PR_PIVOTS_EXPERT_ADVISOR '/storage/nvme5/new_clones/MQL4/PR_PIVOTS_EXPERT_ADVISOR' &
git clone https://github.com/yfjelley/Desphilboy-trading-system '/storage/nvme5/new_clones/MQL4/Desphilboy-trading-system' &
git clone https://github.com/OwaisQuadri/ThreeBarPlayExpertAdvisor '/storage/nvme5/new_clones/MQL4/ThreeBarPlayExpertAdvisor' &
git clone https://github.com/Lucas170/Chapter-7-All-Files '/storage/nvme5/new_clones/MQL4/Chapter-7-All-Files' &
git clone https://github.com/chriswang2006/Forex_MT4_Indicator_Ichimoku_All_Signals '/storage/nvme5/new_clones/MQL4/Forex_MT4_Indicator_Ichimoku_All_Signals' &
git clone https://github.com/Lucas170/Chapter-20-All-Files '/storage/nvme5/new_clones/MQL4/Chapter-20-All-Files' &
git clone https://github.com/lorne-luo/MQL4 '/storage/nvme5/new_clones/MQL4/MQL4' &
git clone https://github.com/vzhomeexperiments/FALCON_S '/storage/nvme5/new_clones/MQL4/FALCON_S' &
git clone https://github.com/inceabdullah/MQL4-iCustom-Mode-Shift-Numbers-Detector '/storage/nvme5/new_clones/MQL4/MQL4-iCustom-Mode-Shift-Numbers-Detector' &
git clone https://github.com/OwaisQuadri/MT4-code '/storage/nvme5/new_clones/MQL4/MT4-code' &
git clone https://github.com/investflow/mql4 '/storage/nvme5/new_clones/MQL4/mql4' &
git clone https://github.com/rahuldhangar/learn-mql4 '/storage/nvme5/new_clones/MQL4/learn-mql4' &
git clone https://github.com/zobad16/Zobad_EA '/storage/nvme5/new_clones/MQL4/Zobad_EA' &
git clone https://github.com/Lucas170/Chapter-16-All-Files '/storage/nvme5/new_clones/MQL4/Chapter-16-All-Files' &
git clone https://github.com/mofostopheles/dev '/storage/nvme5/new_clones/MQL4/dev' &
git clone https://github.com/KeisukeIwabuchi/MQL4-Price '/storage/nvme5/new_clones/MQL4/MQL4-Price' &
git clone https://github.com/JoeG777/MT4_Forex_Trading_Bot_Template '/storage/nvme5/new_clones/MQL4/MT4_Forex_Trading_Bot_Template' &
git clone https://github.com/vuvivov/forexTrading-mt4 '/storage/nvme5/new_clones/MQL4/forexTrading-mt4' &
git clone https://github.com/yuriodilon/ea-HiLo '/storage/nvme5/new_clones/MQL4/ea-HiLo' &
git clone https://github.com/reuniware/MQL4-ZeroMQ-ZMQ-Basic-Working-Configuration '/storage/nvme5/new_clones/MQL4/MQL4-ZeroMQ-ZMQ-Basic-Working-Configuration' &
git clone https://github.com/AlanWong-1992/forex-factory-calendar-history '/storage/nvme5/new_clones/MQL4/forex-factory-calendar-history' &
git clone https://github.com/nasimalsajjad/PriceActionExpert '/storage/nvme5/new_clones/MQL4/PriceActionExpert' &
