#!/bin/bash

git clone https://github.com/tinyos/tinyos-main '/storage/nvme5/new_clones/nesC/tinyos-main' &
git clone https://github.com/selfcustody/krux '/storage/nvme5/new_clones/nesC/krux' &
git clone https://github.com/leonvandenbeukel/CNC-Machine-V3 '/storage/nvme5/new_clones/nesC/CNC-Machine-V3' &
git clone https://github.com/NikodemBartnik/Mini-Mars-Rover '/storage/nvme5/new_clones/nesC/Mini-Mars-Rover' &
git clone https://github.com/bdring/Polar-Coaster '/storage/nvme5/new_clones/nesC/Polar-Coaster' &
git clone https://github.com/bdring/Grbl_ESP32_MPCNC_Controller '/storage/nvme5/new_clones/nesC/Grbl_ESP32_MPCNC_Controller' &
git clone https://github.com/rahulsarchive/4AxisFoamCutter '/storage/nvme5/new_clones/nesC/4AxisFoamCutter' &
git clone https://github.com/zjor/inverted-pendulum '/storage/nvme5/new_clones/nesC/inverted-pendulum' &
git clone https://github.com/nicolasfauchereau/NIWA_Python_seminars '/storage/nvme5/new_clones/nesC/NIWA_Python_seminars' &
git clone https://github.com/briandorey/DIY-Pick-and-Place-Hardware '/storage/nvme5/new_clones/nesC/DIY-Pick-and-Place-Hardware' &
git clone https://github.com/robEllenberg/gcode-syntax '/storage/nvme5/new_clones/nesC/gcode-syntax' &
git clone https://github.com/CuriousMotor/Onyx-Stepper-Motherboard '/storage/nvme5/new_clones/nesC/Onyx-Stepper-Motherboard' &
git clone https://github.com/mattwach/cnc_pcb_tools '/storage/nvme5/new_clones/nesC/cnc_pcb_tools' &
git clone https://github.com/cody82/grblgui '/storage/nvme5/new_clones/nesC/grblgui' &
git clone https://github.com/NikodemBartnik/Pico-Watering-System '/storage/nvme5/new_clones/nesC/Pico-Watering-System' &
git clone https://github.com/azasypkin/kroneum '/storage/nvme5/new_clones/nesC/kroneum' &
git clone https://github.com/mattwach/epaper_clock '/storage/nvme5/new_clones/nesC/epaper_clock' &
git clone https://github.com/Spark-Concepts/xPro-V5 '/storage/nvme5/new_clones/nesC/xPro-V5' &
git clone https://github.com/shihaipeng03/Walldraw '/storage/nvme5/new_clones/nesC/Walldraw' &
git clone https://github.com/kiyoka/nendo '/storage/nvme5/new_clones/nesC/nendo' &
git clone https://github.com/OSHChip/OSHChip_V1.0_Docs '/storage/nvme5/new_clones/nesC/OSHChip_V1.0_Docs' &
git clone https://github.com/NikodemBartnik/Overpowered-Robotic-Chassis '/storage/nvme5/new_clones/nesC/Overpowered-Robotic-Chassis' &
git clone https://github.com/fab-machines/Fabulaser-Mini '/storage/nvme5/new_clones/nesC/Fabulaser-Mini' &
git clone https://github.com/chuyskywalker/cncjs-macros '/storage/nvme5/new_clones/nesC/cncjs-macros' &
git clone https://github.com/jakplugg/m-Brane '/storage/nvme5/new_clones/nesC/m-Brane' &
git clone https://github.com/jakplugg/uBurst '/storage/nvme5/new_clones/nesC/uBurst' &
git clone https://github.com/jakplugg/uGrids '/storage/nvme5/new_clones/nesC/uGrids' &
git clone https://github.com/flyandi/BitsyOSD '/storage/nvme5/new_clones/nesC/BitsyOSD' &
git clone https://github.com/Stypox/text-to-gcode '/storage/nvme5/new_clones/nesC/text-to-gcode' &
git clone https://github.com/mccloudaero/goliath-quadcopter '/storage/nvme5/new_clones/nesC/goliath-quadcopter' &
git clone https://github.com/ooici/coi-services '/storage/nvme5/new_clones/nesC/coi-services' &
git clone https://github.com/SienciLabs/Sienci-Mill-One '/storage/nvme5/new_clones/nesC/Sienci-Mill-One' &
git clone https://github.com/ErikOostveen/UberClock '/storage/nvme5/new_clones/nesC/UberClock' &
git clone https://github.com/marksidell/wordclock '/storage/nvme5/new_clones/nesC/wordclock' &
git clone https://github.com/Xav83130/Mini-CNC '/storage/nvme5/new_clones/nesC/Mini-CNC' &
git clone https://github.com/NikodemBartnik/Pico-Plotter '/storage/nvme5/new_clones/nesC/Pico-Plotter' &
git clone https://github.com/usnistgov/smstestbed '/storage/nvme5/new_clones/nesC/smstestbed' &
git clone https://github.com/andymasteroffish/inktober_2020 '/storage/nvme5/new_clones/nesC/inktober_2020' &
git clone https://github.com/xpix/XLCD '/storage/nvme5/new_clones/nesC/XLCD' &
git clone https://github.com/zxzhaixiang/Laser_engraver_system_RaspberryPI '/storage/nvme5/new_clones/nesC/Laser_engraver_system_RaspberryPI' &
git clone https://github.com/guiglass/AnimationPrepStudio-ArduGlove '/storage/nvme5/new_clones/nesC/AnimationPrepStudio-ArduGlove' &
git clone https://github.com/UCMAndesLab/CSE160-Project-Skeleton-Code '/storage/nvme5/new_clones/nesC/CSE160-Project-Skeleton-Code' &
git clone https://github.com/LHSRobotics/gdmux '/storage/nvme5/new_clones/nesC/gdmux' &
git clone https://github.com/lukelabs/analog-synthesizer-panels '/storage/nvme5/new_clones/nesC/analog-synthesizer-panels' &
git clone https://github.com/Exprezz0/F-18C_Simulator '/storage/nvme5/new_clones/nesC/F-18C_Simulator' &
git clone https://github.com/jbeuckm/AtTiny_MIDI_CV '/storage/nvme5/new_clones/nesC/AtTiny_MIDI_CV' &
git clone https://github.com/mwasilew/boxzy '/storage/nvme5/new_clones/nesC/boxzy' &
git clone https://github.com/ShimmerResearch/tinyos-shimmer '/storage/nvme5/new_clones/nesC/tinyos-shimmer' &
git clone https://github.com/NikodemBartnik/WDCS '/storage/nvme5/new_clones/nesC/WDCS' &
git clone https://github.com/alnwlsn/scratchpad '/storage/nvme5/new_clones/nesC/scratchpad' &
git clone https://github.com/lspaula/Nextion-background-for-HASwitchPlate '/storage/nvme5/new_clones/nesC/Nextion-background-for-HASwitchPlate' &
git clone https://github.com/mattvenn/eagle-circuit-designs '/storage/nvme5/new_clones/nesC/eagle-circuit-designs' &
git clone https://github.com/tgtakaoka/tinyos-msp430 '/storage/nvme5/new_clones/nesC/tinyos-msp430' &
git clone https://github.com/MaslowCommunityGarden/Fold-Flat-Chair '/storage/nvme5/new_clones/nesC/Fold-Flat-Chair' &
git clone https://github.com/MKme/3018 '/storage/nvme5/new_clones/nesC/3018' &
git clone https://github.com/csimmerling/ff19SB_201907 '/storage/nvme5/new_clones/nesC/ff19SB_201907' &
git clone https://github.com/jbeuckm/PG328 '/storage/nvme5/new_clones/nesC/PG328' &
git clone https://github.com/jetperch/joulescope_front_panels '/storage/nvme5/new_clones/nesC/joulescope_front_panels' &
git clone https://github.com/OSHChip/OSHChip_CMSIS_DAP_V1.0_Docs '/storage/nvme5/new_clones/nesC/OSHChip_CMSIS_DAP_V1.0_Docs' &
git clone https://github.com/jbeuckm/808-MidTom-MidConga '/storage/nvme5/new_clones/nesC/808-MidTom-MidConga' &
git clone https://github.com/jakplugg/plancksII '/storage/nvme5/new_clones/nesC/plancksII' &
git clone https://github.com/brainstorm/carvey_board '/storage/nvme5/new_clones/nesC/carvey_board' &
git clone https://github.com/jbeuckm/808-Cymbale '/storage/nvme5/new_clones/nesC/808-Cymbale' &
git clone https://github.com/jbeuckm/808-LowTom-LowConga '/storage/nvme5/new_clones/nesC/808-LowTom-LowConga' &
git clone https://github.com/jbeuckm/808_Cowbell '/storage/nvme5/new_clones/nesC/808_Cowbell' &
git clone https://github.com/johnwu130/LabVIEW-GCode-Parser '/storage/nvme5/new_clones/nesC/LabVIEW-GCode-Parser' &
git clone https://github.com/briandorey/Asus-Tinker-Board-Fan-Controller '/storage/nvme5/new_clones/nesC/Asus-Tinker-Board-Fan-Controller' &
git clone https://github.com/jbeuckm/atmega_midi_x0x_heart '/storage/nvme5/new_clones/nesC/atmega_midi_x0x_heart' &
git clone https://github.com/jbeuckm/hip_bass_drum '/storage/nvme5/new_clones/nesC/hip_bass_drum' &
git clone https://github.com/nothinglabs/chainringgen '/storage/nvme5/new_clones/nesC/chainringgen' &
git clone https://github.com/ab25cq/clover3 '/storage/nvme5/new_clones/nesC/clover3' &
git clone https://github.com/jbeuckm/808-Diginoise '/storage/nvme5/new_clones/nesC/808-Diginoise' &
git clone https://github.com/whitecatboard/whitecat-hardware '/storage/nvme5/new_clones/nesC/whitecat-hardware' &
git clone https://github.com/doug-harriman/3018-Mill '/storage/nvme5/new_clones/nesC/3018-Mill' &
git clone https://github.com/jbeuckm/808_Noise '/storage/nvme5/new_clones/nesC/808_Noise' &
git clone https://github.com/nicholasdelrio/visko '/storage/nvme5/new_clones/nesC/visko' &
git clone https://github.com/jakplugg/twist '/storage/nvme5/new_clones/nesC/twist' &
git clone https://github.com/pfroysdon/projects '/storage/nvme5/new_clones/nesC/projects' &
git clone https://github.com/jbeuckm/Mike-Sims-VCA '/storage/nvme5/new_clones/nesC/Mike-Sims-VCA' &
git clone https://github.com/jacobclarke92/canvas-gcode '/storage/nvme5/new_clones/nesC/canvas-gcode' &
git clone https://github.com/aguegu/lonworks-demo '/storage/nvme5/new_clones/nesC/lonworks-demo' &
git clone https://github.com/jbeuckm/atmega_midi_cv_basic '/storage/nvme5/new_clones/nesC/atmega_midi_cv_basic' &
git clone https://github.com/jbeuckm/atmega_midi_cv_drums '/storage/nvme5/new_clones/nesC/atmega_midi_cv_drums' &
git clone https://github.com/moeC137/stepper_driver_pcb '/storage/nvme5/new_clones/nesC/stepper_driver_pcb' &
git clone https://github.com/Jackhammer88/Visu '/storage/nvme5/new_clones/nesC/Visu' &
git clone https://github.com/AchimPieters/CNC-Mini-Laser-Engraver '/storage/nvme5/new_clones/nesC/CNC-Mini-Laser-Engraver' &
git clone https://github.com/TGit-Tech/RPieces-TableTopXYZ '/storage/nvme5/new_clones/nesC/RPieces-TableTopXYZ' &
git clone https://github.com/schultek/CNC-Halftone-Generator '/storage/nvme5/new_clones/nesC/CNC-Halftone-Generator' &
git clone https://github.com/frankNiessen/CAM2FIB '/storage/nvme5/new_clones/nesC/CAM2FIB' &
git clone https://github.com/MaslowCommunityGarden/The-Meticulous-Z-Axis '/storage/nvme5/new_clones/nesC/The-Meticulous-Z-Axis' &
git clone https://github.com/MaslowCommunityGarden/Maslow-Ring-System '/storage/nvme5/new_clones/nesC/Maslow-Ring-System' &
git clone https://github.com/MaslowCommunityGarden/Working-Desk- '/storage/nvme5/new_clones/nesC/Working-Desk-' &
