#!/bin/bash

git clone https://github.com/NetLogo/models '/storage/nvme5/new_clones/NetLogo/models' &
git clone https://github.com/NetLogo/Galapagos '/storage/nvme5/new_clones/NetLogo/Galapagos' &
git clone https://github.com/huangyz0918/TankLogo '/storage/nvme5/new_clones/NetLogo/TankLogo' &
git clone https://github.com/JTHooker/COVIDModel '/storage/nvme5/new_clones/NetLogo/COVIDModel' &
git clone https://github.com/fsancho/IA '/storage/nvme5/new_clones/NetLogo/IA' &
git clone https://github.com/fsancho/Complex-Networks-Toolbox '/storage/nvme5/new_clones/NetLogo/Complex-Networks-Toolbox' &
git clone https://github.com/psmaldino/modsoc '/storage/nvme5/new_clones/NetLogo/modsoc' &
git clone https://github.com/armostafizi/EvacuationModel '/storage/nvme5/new_clones/NetLogo/EvacuationModel' &
git clone https://github.com/comses/intro-to-abm '/storage/nvme5/new_clones/NetLogo/intro-to-abm' &
git clone https://github.com/shingkid/crowd-evacuation-simulation '/storage/nvme5/new_clones/NetLogo/crowd-evacuation-simulation' &
git clone https://github.com/NetLogo/LevelSpace '/storage/nvme5/new_clones/NetLogo/LevelSpace' &
git clone https://github.com/nknorg/nkn-simulation '/storage/nvme5/new_clones/NetLogo/nkn-simulation' &
git clone https://github.com/SethTisue/lens-examples '/storage/nvme5/new_clones/NetLogo/lens-examples' &
git clone https://github.com/JuliaDynamics/ABMFrameworksComparison '/storage/nvme5/new_clones/NetLogo/ABMFrameworksComparison' &
git clone https://github.com/EmbraceLife/NetLogo-Modeling '/storage/nvme5/new_clones/NetLogo/NetLogo-Modeling' &
git clone https://github.com/YangZhouCSS/roads '/storage/nvme5/new_clones/NetLogo/roads' &
git clone https://github.com/InnovationNetworks/skin '/storage/nvme5/new_clones/NetLogo/skin' &
git clone https://github.com/DOSull/model-zoo '/storage/nvme5/new_clones/NetLogo/model-zoo' &
git clone https://github.com/Luminoid/urban-transportation-system '/storage/nvme5/new_clones/NetLogo/urban-transportation-system' &
git clone https://github.com/jihegao/The-Evolution-of-Cooperation '/storage/nvme5/new_clones/NetLogo/The-Evolution-of-Cooperation' &
git clone https://github.com/acrooks2/ClassModels '/storage/nvme5/new_clones/NetLogo/ClassModels' &
git clone https://github.com/UKDataServiceOpen/agent-based-modelling '/storage/nvme5/new_clones/NetLogo/agent-based-modelling' &
git clone https://github.com/g4v4g4i/ArgABM '/storage/nvme5/new_clones/NetLogo/ArgABM' &
git clone https://github.com/jchanlauimf/ABBA '/storage/nvme5/new_clones/NetLogo/ABBA' &
git clone https://github.com/joshuaballoch/talent-vs-luck-recreated '/storage/nvme5/new_clones/NetLogo/talent-vs-luck-recreated' &
git clone https://github.com/openmole/openmole-market '/storage/nvme5/new_clones/NetLogo/openmole-market' &
git clone https://github.com/alexplatasl/BAMmodel '/storage/nvme5/new_clones/NetLogo/BAMmodel' &
git clone https://github.com/fsancho/NetLogo-AModelingTool '/storage/nvme5/new_clones/NetLogo/NetLogo-AModelingTool' &
git clone https://github.com/jurnix/netlogo-cluster '/storage/nvme5/new_clones/NetLogo/netlogo-cluster' &
git clone https://github.com/albert-espin/stock-market-multi-agent '/storage/nvme5/new_clones/NetLogo/stock-market-multi-agent' &
git clone https://github.com/NetLogo/Teletortoise '/storage/nvme5/new_clones/NetLogo/Teletortoise' &
git clone https://github.com/jschwarzrock/uavs-swarm-gap '/storage/nvme5/new_clones/NetLogo/uavs-swarm-gap' &
git clone https://github.com/jallison7/kintrade-model '/storage/nvme5/new_clones/NetLogo/kintrade-model' &
git clone https://github.com/NetLogo/Sample-Scala-Extension '/storage/nvme5/new_clones/NetLogo/Sample-Scala-Extension' &
git clone https://github.com/janlorenz/Schelling_on_GIS '/storage/nvme5/new_clones/NetLogo/Schelling_on_GIS' &
git clone https://github.com/bezirg/hlogo '/storage/nvme5/new_clones/NetLogo/hlogo' &
git clone https://github.com/shrimperrie/homeless-abm '/storage/nvme5/new_clones/NetLogo/homeless-abm' &
git clone https://github.com/NetLogo/Goo-Extension '/storage/nvme5/new_clones/NetLogo/Goo-Extension' &
git clone https://github.com/tamer-abdulghani/train-evaucation-model '/storage/nvme5/new_clones/NetLogo/train-evaucation-model' &
git clone https://github.com/tabookey/credo '/storage/nvme5/new_clones/NetLogo/credo' &
git clone https://github.com/wccarleton/abm_waste '/storage/nvme5/new_clones/NetLogo/abm_waste' &
git clone https://github.com/gsurma/game_of_life '/storage/nvme5/new_clones/NetLogo/game_of_life' &
git clone https://github.com/mars0i/bali '/storage/nvme5/new_clones/NetLogo/bali' &
git clone https://github.com/He-Ze/Cooperative-Multi-Quadrotor-Pursuit-with-NetLogo '/storage/nvme5/new_clones/NetLogo/Cooperative-Multi-Quadrotor-Pursuit-with-NetLogo' &
git clone https://github.com/suroFr/CogLogo '/storage/nvme5/new_clones/NetLogo/CogLogo' &
git clone https://github.com/LABSS/NetLogo2Mesa '/storage/nvme5/new_clones/NetLogo/NetLogo2Mesa' &
git clone https://github.com/lorenzovngl/agent-based-football '/storage/nvme5/new_clones/NetLogo/agent-based-football' &
git clone https://github.com/BCLab-UNM/netlogo-swarmathon '/storage/nvme5/new_clones/NetLogo/netlogo-swarmathon' &
