#!/bin/bash

git clone https://github.com/nf-core/rnaseq '/storage/nvme5/new_clones/Nextflow/rnaseq' &
git clone https://github.com/bactopia/bactopia '/storage/nvme5/new_clones/Nextflow/bactopia' &
git clone https://github.com/nf-core/sarek '/storage/nvme5/new_clones/Nextflow/sarek' &
git clone https://github.com/nextflow-io/patterns '/storage/nvme5/new_clones/Nextflow/patterns' &
git clone https://github.com/nf-core/modules '/storage/nvme5/new_clones/Nextflow/modules' &
git clone https://github.com/nf-core/scrnaseq '/storage/nvme5/new_clones/Nextflow/scrnaseq' &
git clone https://github.com/nf-core/mag '/storage/nvme5/new_clones/Nextflow/mag' &
git clone https://github.com/nf-core/chipseq '/storage/nvme5/new_clones/Nextflow/chipseq' &
git clone https://github.com/nf-core/atacseq '/storage/nvme5/new_clones/Nextflow/atacseq' &
git clone https://github.com/nf-core/nanoseq '/storage/nvme5/new_clones/Nextflow/nanoseq' &
git clone https://github.com/nf-core/ampliseq '/storage/nvme5/new_clones/Nextflow/ampliseq' &
git clone https://github.com/nf-core/fetchngs '/storage/nvme5/new_clones/Nextflow/fetchngs' &
git clone https://github.com/nf-core/eager '/storage/nvme5/new_clones/Nextflow/eager' &
git clone https://github.com/nf-core/methylseq '/storage/nvme5/new_clones/Nextflow/methylseq' &
git clone https://github.com/nf-core/rnafusion '/storage/nvme5/new_clones/Nextflow/rnafusion' &
git clone https://github.com/nextflow-io/training '/storage/nvme5/new_clones/Nextflow/training' &
git clone https://github.com/nf-core/taxprofiler '/storage/nvme5/new_clones/Nextflow/taxprofiler' &
git clone https://github.com/CRG-CNAG/CalliNGS-NF '/storage/nvme5/new_clones/Nextflow/CalliNGS-NF' &
git clone https://github.com/nf-core/viralrecon '/storage/nvme5/new_clones/Nextflow/viralrecon' &
git clone https://github.com/PGScatalog/pgsc_calc '/storage/nvme5/new_clones/Nextflow/pgsc_calc' &
git clone https://github.com/labsyspharm/mcmicro '/storage/nvme5/new_clones/Nextflow/mcmicro' &
git clone https://github.com/epi2me-labs/wf-human-variation '/storage/nvme5/new_clones/Nextflow/wf-human-variation' &
git clone https://github.com/h3abionet/h3agwas '/storage/nvme5/new_clones/Nextflow/h3agwas' &
git clone https://github.com/genomicsITER/NanoCLUST '/storage/nvme5/new_clones/Nextflow/NanoCLUST' &
git clone https://github.com/biocorecrg/master_of_pores '/storage/nvme5/new_clones/Nextflow/master_of_pores' &
git clone https://github.com/nf-core/hic '/storage/nvme5/new_clones/Nextflow/hic' &
git clone https://github.com/nf-core/raredisease '/storage/nvme5/new_clones/Nextflow/raredisease' &
git clone https://github.com/nf-core/configs '/storage/nvme5/new_clones/Nextflow/configs' &
git clone https://github.com/nf-core/cutandrun '/storage/nvme5/new_clones/Nextflow/cutandrun' &
git clone https://github.com/epi2me-labs/wf-transcriptomes '/storage/nvme5/new_clones/Nextflow/wf-transcriptomes' &
git clone https://github.com/nf-core/pangenome '/storage/nvme5/new_clones/Nextflow/pangenome' &
git clone https://github.com/nf-core/funcscan '/storage/nvme5/new_clones/Nextflow/funcscan' &
git clone https://github.com/nf-core/smrnaseq '/storage/nvme5/new_clones/Nextflow/smrnaseq' &
git clone https://github.com/nextflow-io/rnaseq-nf '/storage/nvme5/new_clones/Nextflow/rnaseq-nf' &
git clone https://github.com/nf-core/differentialabundance '/storage/nvme5/new_clones/Nextflow/differentialabundance' &
git clone https://github.com/nf-core/proteinfold '/storage/nvme5/new_clones/Nextflow/proteinfold' &
git clone https://github.com/icbi-lab/nextNEOpi '/storage/nvme5/new_clones/Nextflow/nextNEOpi' &
git clone https://github.com/PacificBiosciences/HiFi-16S-workflow '/storage/nvme5/new_clones/Nextflow/HiFi-16S-workflow' &
git clone https://github.com/nf-core/bacass '/storage/nvme5/new_clones/Nextflow/bacass' &
git clone https://github.com/nf-core/hlatyping '/storage/nvme5/new_clones/Nextflow/hlatyping' &
git clone https://github.com/genepi/nf-gwas '/storage/nvme5/new_clones/Nextflow/nf-gwas' &
git clone https://github.com/brentp/rare-disease-wf '/storage/nvme5/new_clones/Nextflow/rare-disease-wf' &
git clone https://github.com/nf-core/airrflow '/storage/nvme5/new_clones/Nextflow/airrflow' &
git clone https://github.com/nf-core/oncoanalyser '/storage/nvme5/new_clones/Nextflow/oncoanalyser' &
git clone https://github.com/evotools/nf-LO '/storage/nvme5/new_clones/Nextflow/nf-LO' &
git clone https://github.com/nf-core/spatialvi '/storage/nvme5/new_clones/Nextflow/spatialvi' &
git clone https://github.com/gencorefacility/variant-calling-pipeline-gatk4 '/storage/nvme5/new_clones/Nextflow/variant-calling-pipeline-gatk4' &
git clone https://github.com/scilus/tractoflow '/storage/nvme5/new_clones/Nextflow/tractoflow' &
git clone https://github.com/nf-core/bactmap '/storage/nvme5/new_clones/Nextflow/bactmap' &
git clone https://github.com/nf-core/rnasplice '/storage/nvme5/new_clones/Nextflow/rnasplice' &
git clone https://github.com/nf-core/circrna '/storage/nvme5/new_clones/Nextflow/circrna' &
git clone https://github.com/UPHL-BioNGS/Cecret '/storage/nvme5/new_clones/Nextflow/Cecret' &
git clone https://github.com/epi2me-labs/wf-artic '/storage/nvme5/new_clones/Nextflow/wf-artic' &
git clone https://github.com/nf-core/demultiplex '/storage/nvme5/new_clones/Nextflow/demultiplex' &
git clone https://github.com/CDCgov/mycosnp-nf '/storage/nvme5/new_clones/Nextflow/mycosnp-nf' &
git clone https://github.com/nf-core/epitopeprediction '/storage/nvme5/new_clones/Nextflow/epitopeprediction' &
git clone https://github.com/rki-mf1/clean '/storage/nvme5/new_clones/Nextflow/clean' &
git clone https://github.com/nf-core/rnavar '/storage/nvme5/new_clones/Nextflow/rnavar' &
git clone https://github.com/nf-core/crisprseq '/storage/nvme5/new_clones/Nextflow/crisprseq' &
git clone https://github.com/Arcadia-Science/metagenomics '/storage/nvme5/new_clones/Nextflow/metagenomics' &
git clone https://github.com/canceromics/MeRIPseqPipe '/storage/nvme5/new_clones/Nextflow/MeRIPseqPipe' &
git clone https://github.com/herobd/NAF_dataset '/storage/nvme5/new_clones/Nextflow/NAF_dataset' &
git clone https://github.com/epi2me-labs/wf-basecalling '/storage/nvme5/new_clones/Nextflow/wf-basecalling' &
git clone https://github.com/bigbio/quantms '/storage/nvme5/new_clones/Nextflow/quantms' &
git clone https://github.com/nf-core/isoseq '/storage/nvme5/new_clones/Nextflow/isoseq' &
git clone https://github.com/SystemsGenetics/GEMmaker '/storage/nvme5/new_clones/Nextflow/GEMmaker' &
git clone https://github.com/nextflow-io/rnatoy '/storage/nvme5/new_clones/Nextflow/rnatoy' &
git clone https://github.com/nf-core/mhcquant '/storage/nvme5/new_clones/Nextflow/mhcquant' &
git clone https://github.com/nf-core/proteomicslfq '/storage/nvme5/new_clones/Nextflow/proteomicslfq' &
git clone https://github.com/nextflow-io/nf-hack17-tutorial '/storage/nvme5/new_clones/Nextflow/nf-hack17-tutorial' &
git clone https://github.com/qbic-pipelines/rnadeseq '/storage/nvme5/new_clones/Nextflow/rnadeseq' &
git clone https://github.com/lifebit-ai/DeepVariant '/storage/nvme5/new_clones/Nextflow/DeepVariant' &
git clone https://github.com/cfarkas/annotate_my_genomes '/storage/nvme5/new_clones/Nextflow/annotate_my_genomes' &
git clone https://github.com/CAMI-challenge/CAMITAX '/storage/nvme5/new_clones/Nextflow/CAMITAX' &
git clone https://github.com/nextflow-io/nfcamp-tutorial '/storage/nvme5/new_clones/Nextflow/nfcamp-tutorial' &
git clone https://github.com/Golob-Minot/geneshot '/storage/nvme5/new_clones/Nextflow/geneshot' &
git clone https://github.com/deng-lab/viroprofiler '/storage/nvme5/new_clones/Nextflow/viroprofiler' &
git clone https://github.com/Plant-Food-Research-Open/assemblyqc '/storage/nvme5/new_clones/Nextflow/assemblyqc' &
git clone https://github.com/epi2me-labs/wf-alignment '/storage/nvme5/new_clones/Nextflow/wf-alignment' &
git clone https://github.com/UMCUGenetics/NextflowModules '/storage/nvme5/new_clones/Nextflow/NextflowModules' &
git clone https://github.com/nf-core/genomeannotator '/storage/nvme5/new_clones/Nextflow/genomeannotator' &
git clone https://github.com/PalMuc/TransPi '/storage/nvme5/new_clones/Nextflow/TransPi' &
git clone https://github.com/carpentries-incubator/workflows-nextflow '/storage/nvme5/new_clones/Nextflow/workflows-nextflow' &
git clone https://github.com/peterk87/nf-flu '/storage/nvme5/new_clones/Nextflow/nf-flu' &
git clone https://github.com/telatin/nextflow-example '/storage/nvme5/new_clones/Nextflow/nextflow-example' &
git clone https://github.com/FAANG/analysis-TAGADA '/storage/nvme5/new_clones/Nextflow/analysis-TAGADA' &
git clone https://github.com/nf-core/hgtseq '/storage/nvme5/new_clones/Nextflow/hgtseq' &
git clone https://github.com/nf-core/gwas '/storage/nvme5/new_clones/Nextflow/gwas' &
git clone https://github.com/nf-core/scnanoseq '/storage/nvme5/new_clones/Nextflow/scnanoseq' &
git clone https://github.com/bzhanglab/neoflow '/storage/nvme5/new_clones/Nextflow/neoflow' &
git clone https://github.com/biocorecrg/MOP2 '/storage/nvme5/new_clones/Nextflow/MOP2' &
git clone https://github.com/sanger-tol/treeval '/storage/nvme5/new_clones/Nextflow/treeval' &
git clone https://github.com/nf-core/metatdenovo '/storage/nvme5/new_clones/Nextflow/metatdenovo' &
git clone https://github.com/nf-core/bamtofastq '/storage/nvme5/new_clones/Nextflow/bamtofastq' &
git clone https://github.com/cbcrg/kallisto-nf '/storage/nvme5/new_clones/Nextflow/kallisto-nf' &
git clone https://github.com/jgolob/maliampi '/storage/nvme5/new_clones/Nextflow/maliampi' &
git clone https://github.com/TRON-Bioinformatics/tronflow-mutect2 '/storage/nvme5/new_clones/Nextflow/tronflow-mutect2' &
git clone https://github.com/biocorecrg/ExOrthist '/storage/nvme5/new_clones/Nextflow/ExOrthist' &
git clone https://github.com/lazyky/meripseqpipe '/storage/nvme5/new_clones/Nextflow/meripseqpipe' &
git clone https://github.com/nf-core/fastquorum '/storage/nvme5/new_clones/Nextflow/fastquorum' &
git clone https://github.com/nf-core/clipseq '/storage/nvme5/new_clones/Nextflow/clipseq' &
git clone https://github.com/TheJacksonLaboratory/cs-nf-pipelines '/storage/nvme5/new_clones/Nextflow/cs-nf-pipelines' &
git clone https://github.com/sanger-tol/genomeassembly '/storage/nvme5/new_clones/Nextflow/genomeassembly' &
git clone https://github.com/ablab/metaGT '/storage/nvme5/new_clones/Nextflow/metaGT' &
git clone https://github.com/h3abionet/chipimputation '/storage/nvme5/new_clones/Nextflow/chipimputation' &
git clone https://github.com/nf-core/kmermaid '/storage/nvme5/new_clones/Nextflow/kmermaid' &
git clone https://github.com/h3abionet/TADA '/storage/nvme5/new_clones/Nextflow/TADA' &
git clone https://github.com/seqeralabs/wave-showcase '/storage/nvme5/new_clones/Nextflow/wave-showcase' &
git clone https://github.com/nf-core/dualrnaseq '/storage/nvme5/new_clones/Nextflow/dualrnaseq' &
git clone https://github.com/angelovangel/nxf-kraken2 '/storage/nvme5/new_clones/Nextflow/nxf-kraken2' &
git clone https://github.com/nf-core/cookiecutter '/storage/nvme5/new_clones/Nextflow/cookiecutter' &
git clone https://github.com/nf-cmgg/structural '/storage/nvme5/new_clones/Nextflow/structural' &
git clone https://github.com/HPCBio/16S-rDNA-dada2-pipeline '/storage/nvme5/new_clones/Nextflow/16S-rDNA-dada2-pipeline' &
git clone https://github.com/TRON-Bioinformatics/covigator-ngs-pipeline '/storage/nvme5/new_clones/Nextflow/covigator-ngs-pipeline' &
git clone https://github.com/nf-core/nascent '/storage/nvme5/new_clones/Nextflow/nascent' &
git clone https://github.com/nextflow-io/nf-hack18 '/storage/nvme5/new_clones/Nextflow/nf-hack18' &
git clone https://github.com/nf-core/metaboigniter '/storage/nvme5/new_clones/Nextflow/metaboigniter' &
git clone https://github.com/isugifNF/polishCLR '/storage/nvme5/new_clones/Nextflow/polishCLR' &
git clone https://github.com/nextflow-io/hello '/storage/nvme5/new_clones/Nextflow/hello' &
git clone https://github.com/nf-core/diaproteomics '/storage/nvme5/new_clones/Nextflow/diaproteomics' &
git clone https://github.com/FredHutch/nf-anvio-pangenome '/storage/nvme5/new_clones/Nextflow/nf-anvio-pangenome' &
git clone https://github.com/guigolab/chip-nf '/storage/nvme5/new_clones/Nextflow/chip-nf' &
git clone https://github.com/epi2me-labs/wf-flu '/storage/nvme5/new_clones/Nextflow/wf-flu' &
git clone https://github.com/seqeralabs/nf-training-advanced '/storage/nvme5/new_clones/Nextflow/nf-training-advanced' &
git clone https://github.com/nf-core/genomeassembler '/storage/nvme5/new_clones/Nextflow/genomeassembler' &
git clone https://github.com/nf-core/exoseq '/storage/nvme5/new_clones/Nextflow/exoseq' &
git clone https://github.com/micans/nextflow-idioms '/storage/nvme5/new_clones/Nextflow/nextflow-idioms' &
git clone https://github.com/jsalignon/cactus '/storage/nvme5/new_clones/Nextflow/cactus' &
git clone https://github.com/TheJacksonLaboratory/STQ '/storage/nvme5/new_clones/Nextflow/STQ' &
git clone https://github.com/UPHL-BioNGS/Donut_Falls '/storage/nvme5/new_clones/Nextflow/Donut_Falls' &
git clone https://github.com/imgag/plasmIDent '/storage/nvme5/new_clones/Nextflow/plasmIDent' &
git clone https://github.com/nf-core/vipr '/storage/nvme5/new_clones/Nextflow/vipr' &
git clone https://github.com/WarrenLab/hic-scaffolding-nf '/storage/nvme5/new_clones/Nextflow/hic-scaffolding-nf' &
git clone https://github.com/JaneliaSciComp/nextflow-spark '/storage/nvme5/new_clones/Nextflow/nextflow-spark' &
git clone https://github.com/TheJacksonLaboratory/splicing-pipelines-nf '/storage/nvme5/new_clones/Nextflow/splicing-pipelines-nf' &
git clone https://github.com/luslab/luslab-nf-modules '/storage/nvme5/new_clones/Nextflow/luslab-nf-modules' &
git clone https://github.com/statgen/pheweb-rg-pipeline '/storage/nvme5/new_clones/Nextflow/pheweb-rg-pipeline' &
git clone https://github.com/agalitsyna/RedClib '/storage/nvme5/new_clones/Nextflow/RedClib' &
git clone https://github.com/rikenbit/ramdaq '/storage/nvme5/new_clones/Nextflow/ramdaq' &
git clone https://github.com/nf-core/nanostring '/storage/nvme5/new_clones/Nextflow/nanostring' &
git clone https://github.com/elyadlezmi/RNA2CM '/storage/nvme5/new_clones/Nextflow/RNA2CM' &
git clone https://github.com/JaneliaSciComp/exllsm-circuit-reconstruction '/storage/nvme5/new_clones/Nextflow/exllsm-circuit-reconstruction' &
git clone https://github.com/ConesaLab/TCR_nextflow '/storage/nvme5/new_clones/Nextflow/TCR_nextflow' &
git clone https://github.com/FredHutch/microbial-rnaseq '/storage/nvme5/new_clones/Nextflow/microbial-rnaseq' &
git clone https://github.com/genomicsITER/NanoRTax '/storage/nvme5/new_clones/Nextflow/NanoRTax' &
git clone https://github.com/angelovangel/nxf-fastqc '/storage/nvme5/new_clones/Nextflow/nxf-fastqc' &
git clone https://github.com/TRON-Bioinformatics/tronflow-alignment '/storage/nvme5/new_clones/Nextflow/tronflow-alignment' &
git clone https://github.com/FredHutch/octapus '/storage/nvme5/new_clones/Nextflow/octapus' &
git clone https://github.com/ifremer-bioinformatics/samba '/storage/nvme5/new_clones/Nextflow/samba' &
git clone https://github.com/genomic-medicine-sweden/tomte '/storage/nvme5/new_clones/Nextflow/tomte' &
git clone https://github.com/xmuyulab/scRNAseq_pipelines '/storage/nvme5/new_clones/Nextflow/scRNAseq_pipelines' &
git clone https://github.com/isugifNF/GATK-flow '/storage/nvme5/new_clones/Nextflow/GATK-flow' &
git clone https://github.com/alemenze/bact-builder '/storage/nvme5/new_clones/Nextflow/bact-builder' &
git clone https://github.com/seqeralabs/gatk4-germline-snps-indels '/storage/nvme5/new_clones/Nextflow/gatk4-germline-snps-indels' &
git clone https://github.com/qbic-pipelines/cellranger '/storage/nvme5/new_clones/Nextflow/cellranger' &
git clone https://github.com/sanger-tol/readmapping '/storage/nvme5/new_clones/Nextflow/readmapping' &
git clone https://github.com/NorwegianVeterinaryInstitute/ALPPACA '/storage/nvme5/new_clones/Nextflow/ALPPACA' &
git clone https://github.com/Gibbons-Lab/pipelines '/storage/nvme5/new_clones/Nextflow/pipelines' &
git clone https://github.com/murphycj/manuscripts '/storage/nvme5/new_clones/Nextflow/manuscripts' &
git clone https://github.com/TARGENE/targene-pipeline '/storage/nvme5/new_clones/Nextflow/targene-pipeline' &
git clone https://github.com/aws-samples/aws-gatk-recipe-nextflow-pipeline '/storage/nvme5/new_clones/Nextflow/aws-gatk-recipe-nextflow-pipeline' &
git clone https://github.com/maxemil/PhyloMagnet '/storage/nvme5/new_clones/Nextflow/PhyloMagnet' &
git clone https://github.com/nf-core/metapep '/storage/nvme5/new_clones/Nextflow/metapep' &
git clone https://github.com/CFSAN-Biostatistics/bettercallsal '/storage/nvme5/new_clones/Nextflow/bettercallsal' &
git clone https://github.com/seqeralabs/nf-dragen '/storage/nvme5/new_clones/Nextflow/nf-dragen' &
git clone https://github.com/wbazant/CORRAL '/storage/nvme5/new_clones/Nextflow/CORRAL' &
git clone https://github.com/pblaney/mgp1000 '/storage/nvme5/new_clones/Nextflow/mgp1000' &
git clone https://github.com/evanfloden/lncRNA-Annotation-nf '/storage/nvme5/new_clones/Nextflow/lncRNA-Annotation-nf' &
git clone https://github.com/lifebit-ai/prs '/storage/nvme5/new_clones/Nextflow/prs' &
git clone https://github.com/nf-core/cageseq '/storage/nvme5/new_clones/Nextflow/cageseq' &
git clone https://github.com/sanger-tol/blobtoolkit '/storage/nvme5/new_clones/Nextflow/blobtoolkit' &
git clone https://github.com/TRON-Bioinformatics/tronflow-hla-hd '/storage/nvme5/new_clones/Nextflow/tronflow-hla-hd' &
git clone https://github.com/BioRadOpenSource/omnition '/storage/nvme5/new_clones/Nextflow/omnition' &
git clone https://github.com/kaizhang/single-cell-benchmark '/storage/nvme5/new_clones/Nextflow/single-cell-benchmark' &
git clone https://github.com/PengNi/ccsmethphase '/storage/nvme5/new_clones/Nextflow/ccsmethphase' &
git clone https://github.com/nextflow-io/blast-example '/storage/nvme5/new_clones/Nextflow/blast-example' &
git clone https://github.com/qMRLab/qMRFlow '/storage/nvme5/new_clones/Nextflow/qMRFlow' &
git clone https://github.com/evanfloden/tuxedo-nf '/storage/nvme5/new_clones/Nextflow/tuxedo-nf' &
git clone https://github.com/nf-core/mnaseseq '/storage/nvme5/new_clones/Nextflow/mnaseseq' &
git clone https://github.com/cbcrg/nf-phdcourse19 '/storage/nvme5/new_clones/Nextflow/nf-phdcourse19' &
git clone https://github.com/vibbits/nextflow-workshop '/storage/nvme5/new_clones/Nextflow/nextflow-workshop' &
git clone https://github.com/biocorecrg/allele_specific_RNAseq '/storage/nvme5/new_clones/Nextflow/allele_specific_RNAseq' &
git clone https://github.com/mribeirodantas/nf-whisper '/storage/nvme5/new_clones/Nextflow/nf-whisper' &
git clone https://github.com/lmtani/wf-human-mito '/storage/nvme5/new_clones/Nextflow/wf-human-mito' &
git clone https://github.com/nf-core/variantcatalogue '/storage/nvme5/new_clones/Nextflow/variantcatalogue' &
git clone https://github.com/Aveglia/vAMPirus '/storage/nvme5/new_clones/Nextflow/vAMPirus' &
git clone https://github.com/hmkim/workflow '/storage/nvme5/new_clones/Nextflow/workflow' &
git clone https://github.com/lindenb/gazoduc-nf '/storage/nvme5/new_clones/Nextflow/gazoduc-nf' &
git clone https://github.com/adamd3/BactSeq '/storage/nvme5/new_clones/Nextflow/BactSeq' &
git clone https://github.com/czbiohub-sf/utilities '/storage/nvme5/new_clones/Nextflow/utilities' &
git clone https://github.com/DHQP/SNVPhyl_Nextflow '/storage/nvme5/new_clones/Nextflow/SNVPhyl_Nextflow' &
git clone https://github.com/nf-core/coproid '/storage/nvme5/new_clones/Nextflow/coproid' &
git clone https://github.com/ikmb-denbi/genome-annotation '/storage/nvme5/new_clones/Nextflow/genome-annotation' &
git clone https://github.com/ChristinaVasil/snpQT '/storage/nvme5/new_clones/Nextflow/snpQT' &
git clone https://github.com/sje30/neuRo '/storage/nvme5/new_clones/Nextflow/neuRo' &
git clone https://github.com/lifebit-ai/kallisto-sra '/storage/nvme5/new_clones/Nextflow/kallisto-sra' &
git clone https://github.com/InformaticsMatters/docking-validation '/storage/nvme5/new_clones/Nextflow/docking-validation' &
git clone https://github.com/COMBINE-lab/quantaf '/storage/nvme5/new_clones/Nextflow/quantaf' &
git clone https://github.com/ablab/graphamr '/storage/nvme5/new_clones/Nextflow/graphamr' &
git clone https://github.com/Dowell-Lab/RNAseq-Flow '/storage/nvme5/new_clones/Nextflow/RNAseq-Flow' &
git clone https://github.com/Dowell-Lab/Nascent-Flow '/storage/nvme5/new_clones/Nextflow/Nascent-Flow' &
git clone https://github.com/nf-core/pixelator '/storage/nvme5/new_clones/Nextflow/pixelator' &
git clone https://github.com/biocorecrg/goodbioinfo2018 '/storage/nvme5/new_clones/Nextflow/goodbioinfo2018' &
git clone https://github.com/icbi-lab/downloader '/storage/nvme5/new_clones/Nextflow/downloader' &
git clone https://github.com/BarryDigby/nf-pcgr '/storage/nvme5/new_clones/Nextflow/nf-pcgr' &
git clone https://github.com/mycobactopia-org/MTBseq-nf '/storage/nvme5/new_clones/Nextflow/MTBseq-nf' &
git clone https://github.com/avantonder/bovisanalyzer '/storage/nvme5/new_clones/Nextflow/bovisanalyzer' &
git clone https://github.com/nf-cmgg/germline '/storage/nvme5/new_clones/Nextflow/germline' &
git clone https://github.com/UMCUGenetics/RNASeq-NF '/storage/nvme5/new_clones/Nextflow/RNASeq-NF' &
git clone https://github.com/mahesh-panchal/NBIS_project_template '/storage/nvme5/new_clones/Nextflow/NBIS_project_template' &
git clone https://github.com/grbot/varcall '/storage/nvme5/new_clones/Nextflow/varcall' &
git clone https://github.com/biocorecrg/CoursesCRG_Containers_Nextflow_May_2021 '/storage/nvme5/new_clones/Nextflow/CoursesCRG_Containers_Nextflow_May_2021' &
git clone https://github.com/kzeglinski/nabseq_nf '/storage/nvme5/new_clones/Nextflow/nabseq_nf' &
git clone https://github.com/jhayer/baargin '/storage/nvme5/new_clones/Nextflow/baargin' &
git clone https://github.com/theislab/spapros-pipeline '/storage/nvme5/new_clones/Nextflow/spapros-pipeline' &
git clone https://github.com/KevinMenden/hybrid-assembly '/storage/nvme5/new_clones/Nextflow/hybrid-assembly' &
git clone https://github.com/HuffordLab/Maize_WGS_Build '/storage/nvme5/new_clones/Nextflow/Maize_WGS_Build' &
git clone https://github.com/combiz/nf-core-scflow '/storage/nvme5/new_clones/Nextflow/nf-core-scflow' &
git clone https://github.com/tobsecret/BADAS_Nextflow_Tutorial '/storage/nvme5/new_clones/Nextflow/BADAS_Nextflow_Tutorial' &
git clone https://github.com/nf-core/hicar '/storage/nvme5/new_clones/Nextflow/hicar' &
git clone https://github.com/jianhong/16S_pipeline '/storage/nvme5/new_clones/Nextflow/16S_pipeline' &
git clone https://github.com/BU-ISCIII/SARS_Cov2_consensus-nf '/storage/nvme5/new_clones/Nextflow/SARS_Cov2_consensus-nf' &
git clone https://github.com/biocorecrg/CoursesCRG_Containers_Nextflow_May_2022 '/storage/nvme5/new_clones/Nextflow/CoursesCRG_Containers_Nextflow_May_2022' &
git clone https://github.com/mskcc/forte '/storage/nvme5/new_clones/Nextflow/forte' &
git clone https://github.com/bbi-lab/bbi-sci '/storage/nvme5/new_clones/Nextflow/bbi-sci' &
git clone https://github.com/keoughkath/AcceleratedRegionsNF '/storage/nvme5/new_clones/Nextflow/AcceleratedRegionsNF' &
git clone https://github.com/crickbabs/BABS-RNASeq '/storage/nvme5/new_clones/Nextflow/BABS-RNASeq' &
git clone https://github.com/cmbi/SUsPECT '/storage/nvme5/new_clones/Nextflow/SUsPECT' &
git clone https://github.com/staphopia/staphopia-ap '/storage/nvme5/new_clones/Nextflow/staphopia-ap' &
git clone https://github.com/brwnj/freebayes-nf '/storage/nvme5/new_clones/Nextflow/freebayes-nf' &
git clone https://github.com/EpiDiverse/wgbs '/storage/nvme5/new_clones/Nextflow/wgbs' &
git clone https://github.com/phelelani/nf-tut-2020 '/storage/nvme5/new_clones/Nextflow/nf-tut-2020' &
git clone https://github.com/phelelani/nf-rnaSeqMetagen '/storage/nvme5/new_clones/Nextflow/nf-rnaSeqMetagen' &
git clone https://github.com/danforthcenter/bioinformatics '/storage/nvme5/new_clones/Nextflow/bioinformatics' &
git clone https://github.com/seandavi/curatedMetagenomicsNextflow '/storage/nvme5/new_clones/Nextflow/curatedMetagenomicsNextflow' &
git clone https://github.com/CINECA-project/wp4-federated-joint-cohort-analysis '/storage/nvme5/new_clones/Nextflow/wp4-federated-joint-cohort-analysis' &
git clone https://github.com/nf-core/marsseq '/storage/nvme5/new_clones/Nextflow/marsseq' &
git clone https://github.com/nf-core/rnadnavar '/storage/nvme5/new_clones/Nextflow/rnadnavar' &
git clone https://github.com/nextstrain/zika-tutorial-nextflow '/storage/nvme5/new_clones/Nextflow/zika-tutorial-nextflow' &
git clone https://github.com/rikenbit/RamDAQ-prototype '/storage/nvme5/new_clones/Nextflow/RamDAQ-prototype' &
git clone https://github.com/CFIA-NCFAD/nf-virontus '/storage/nvme5/new_clones/Nextflow/nf-virontus' &
git clone https://github.com/pbelmann/sra-download '/storage/nvme5/new_clones/Nextflow/sra-download' &
git clone https://github.com/EpiDiverse/ewas '/storage/nvme5/new_clones/Nextflow/ewas' &
git clone https://github.com/nf-core/radseq '/storage/nvme5/new_clones/Nextflow/radseq' &
git clone https://github.com/didrikolofsson/rmappet '/storage/nvme5/new_clones/Nextflow/rmappet' &
git clone https://github.com/bzhanglab/DeepRescore '/storage/nvme5/new_clones/Nextflow/DeepRescore' &
git clone https://github.com/ebi-gene-expression-group/scanpy-workflow '/storage/nvme5/new_clones/Nextflow/scanpy-workflow' &
git clone https://github.com/medforomics/school '/storage/nvme5/new_clones/Nextflow/school' &
git clone https://github.com/FlyCellAtlas/data_processing '/storage/nvme5/new_clones/Nextflow/data_processing' &
git clone https://github.com/mahesh-panchal/Nextflow_sandbox '/storage/nvme5/new_clones/Nextflow/Nextflow_sandbox' &
git clone https://github.com/biocorecrg/indrop '/storage/nvme5/new_clones/Nextflow/indrop' &
git clone https://github.com/TalusBio/nf-encyclopedia '/storage/nvme5/new_clones/Nextflow/nf-encyclopedia' &
git clone https://github.com/CommonMindConsortium/RAPiD-nf '/storage/nvme5/new_clones/Nextflow/RAPiD-nf' &
git clone https://github.com/vmikk/NextITS '/storage/nvme5/new_clones/Nextflow/NextITS' &
git clone https://github.com/alexyfyf/atac_nf '/storage/nvme5/new_clones/Nextflow/atac_nf' &
git clone https://github.com/UMCUGenetics/DxNextflowWES '/storage/nvme5/new_clones/Nextflow/DxNextflowWES' &
git clone https://github.com/hclimente/nori '/storage/nvme5/new_clones/Nextflow/nori' &
git clone https://github.com/ikmb/dragen-variant-calling '/storage/nvme5/new_clones/Nextflow/dragen-variant-calling' &
git clone https://github.com/epi2me-labs/wf-cas9 '/storage/nvme5/new_clones/Nextflow/wf-cas9' &
git clone https://github.com/nextflow-io/gccbosc18-training '/storage/nvme5/new_clones/Nextflow/gccbosc18-training' &
git clone https://github.com/maxulysse/compile-latex '/storage/nvme5/new_clones/Nextflow/compile-latex' &
