#!/bin/bash

git clone https://github.com/bmatzelle/gow '/storage/nvme5/new_clones/NSIS/gow' &
git clone https://github.com/da2x/EdgeDeflector '/storage/nvme5/new_clones/NSIS/EdgeDeflector' &
git clone https://github.com/voicemxil/TS2-Starter-Pack '/storage/nvme5/new_clones/NSIS/TS2-Starter-Pack' &
git clone https://github.com/sihorton/appjs-deskshell '/storage/nvme5/new_clones/NSIS/appjs-deskshell' &
git clone https://github.com/SwiftForWindows/SwiftForWindows '/storage/nvme5/new_clones/NSIS/SwiftForWindows' &
git clone https://github.com/devkitPro/installer '/storage/nvme5/new_clones/NSIS/installer' &
git clone https://github.com/kaylh/old-RetroBat-obsolete '/storage/nvme5/new_clones/NSIS/old-RetroBat-obsolete' &
git clone https://github.com/evshiron/nwjs-builder-phoenix '/storage/nvme5/new_clones/NSIS/nwjs-builder-phoenix' &
git clone https://github.com/hilanmiao/NSIS-UI '/storage/nvme5/new_clones/NSIS/NSIS-UI' &
git clone https://github.com/electron-userland/electron-builder-binaries '/storage/nvme5/new_clones/NSIS/electron-builder-binaries' &
git clone https://github.com/gdzx/chernobyl-simulator '/storage/nvme5/new_clones/NSIS/chernobyl-simulator' &
git clone https://github.com/bajins/NSIS_SetupSkin '/storage/nvme5/new_clones/NSIS/NSIS_SetupSkin' &
git clone https://github.com/coolstar/driverinstallers '/storage/nvme5/new_clones/NSIS/driverinstallers' &
git clone https://github.com/TASEmulators/BizHawk-Prereqs '/storage/nvme5/new_clones/NSIS/BizHawk-Prereqs' &
git clone https://github.com/adafruit/Adafruit_Windows_Drivers '/storage/nvme5/new_clones/NSIS/Adafruit_Windows_Drivers' &
git clone https://github.com/StarLabsLtd/firmware '/storage/nvme5/new_clones/NSIS/firmware' &
git clone https://github.com/holoto/efi_shell_flash_bios '/storage/nvme5/new_clones/NSIS/efi_shell_flash_bios' &
git clone https://github.com/cosmomill/SourceTreePortable '/storage/nvme5/new_clones/NSIS/SourceTreePortable' &
git clone https://github.com/backuppc/cygwin-rsyncd '/storage/nvme5/new_clones/NSIS/cygwin-rsyncd' &
git clone https://github.com/theodo/electron-boilerplate '/storage/nvme5/new_clones/NSIS/electron-boilerplate' &
git clone https://github.com/LKedward/quickstart-fortran '/storage/nvme5/new_clones/NSIS/quickstart-fortran' &
git clone https://github.com/jimpark/unsis '/storage/nvme5/new_clones/NSIS/unsis' &
git clone https://github.com/alpha-rudy/taiwan-topo '/storage/nvme5/new_clones/NSIS/taiwan-topo' &
git clone https://github.com/jdredd87/NeatoToolio '/storage/nvme5/new_clones/NSIS/NeatoToolio' &
git clone https://github.com/gaodeng/BiuSetup '/storage/nvme5/new_clones/NSIS/BiuSetup' &
git clone https://github.com/Drizin/NsisMultiUser '/storage/nvme5/new_clones/NSIS/NsisMultiUser' &
git clone https://github.com/KiCad/kicad-winbuilder '/storage/nvme5/new_clones/NSIS/kicad-winbuilder' &
git clone https://github.com/interfect/cjdns-installer '/storage/nvme5/new_clones/NSIS/cjdns-installer' &
git clone https://github.com/daemondevin/DiscordPortable '/storage/nvme5/new_clones/NSIS/DiscordPortable' &
git clone https://github.com/gigi81/elk-windows-installer '/storage/nvme5/new_clones/NSIS/elk-windows-installer' &
git clone https://github.com/lordmulder/mplayer-setup-win32 '/storage/nvme5/new_clones/NSIS/mplayer-setup-win32' &
git clone https://github.com/bituq/Roshade '/storage/nvme5/new_clones/NSIS/Roshade' &
git clone https://github.com/ligfietser/mkgmap-style-sheets '/storage/nvme5/new_clones/NSIS/mkgmap-style-sheets' &
git clone https://github.com/MuertoGB/SMCTool '/storage/nvme5/new_clones/NSIS/SMCTool' &
git clone https://github.com/loup99/WtWSMS '/storage/nvme5/new_clones/NSIS/WtWSMS' &
git clone https://github.com/sunflover/SunPlayer_DuiLib '/storage/nvme5/new_clones/NSIS/SunPlayer_DuiLib' &
git clone https://github.com/dAppServer/wails-build-action '/storage/nvme5/new_clones/NSIS/wails-build-action' &
git clone https://github.com/GameMakerDiscord/blur-shaders '/storage/nvme5/new_clones/NSIS/blur-shaders' &
git clone https://github.com/freizeitkarte/fzk-mde-garmin '/storage/nvme5/new_clones/NSIS/fzk-mde-garmin' &
git clone https://github.com/aiten/CNCLib '/storage/nvme5/new_clones/NSIS/CNCLib' &
git clone https://github.com/daemondevin/7-ZipPortable '/storage/nvme5/new_clones/NSIS/7-ZipPortable' &
git clone https://github.com/sverrirs/XboxBigButton '/storage/nvme5/new_clones/NSIS/XboxBigButton' &
git clone https://github.com/nicecai/nsissource '/storage/nvme5/new_clones/NSIS/nsissource' &
git clone https://github.com/SuperPat45/UltraModernUI '/storage/nvme5/new_clones/NSIS/UltraModernUI' &
git clone https://github.com/dosinabox/g2_steam_fix '/storage/nvme5/new_clones/NSIS/g2_steam_fix' &
git clone https://github.com/ARMmbed/mbed-cli-windows-installer '/storage/nvme5/new_clones/NSIS/mbed-cli-windows-installer' &
git clone https://github.com/akane2002/GMS_TUT '/storage/nvme5/new_clones/NSIS/GMS_TUT' &
git clone https://github.com/daemondevin/pac-man '/storage/nvme5/new_clones/NSIS/pac-man' &
git clone https://github.com/daliansky/minisforum-Elitemini-B550-Hackintosh '/storage/nvme5/new_clones/NSIS/minisforum-Elitemini-B550-Hackintosh' &
git clone https://github.com/acalcutt/Releases '/storage/nvme5/new_clones/NSIS/Releases' &
git clone https://github.com/cnlohr/tinycc-win64-installer '/storage/nvme5/new_clones/NSIS/tinycc-win64-installer' &
git clone https://github.com/darealshinji/qpdfview '/storage/nvme5/new_clones/NSIS/qpdfview' &
git clone https://github.com/shaggyze/uotiara '/storage/nvme5/new_clones/NSIS/uotiara' &
git clone https://github.com/dosinabox/g1_steam_fix '/storage/nvme5/new_clones/NSIS/g1_steam_fix' &
git clone https://github.com/Apress/gamemaker-studio-100-prog-challenges '/storage/nvme5/new_clones/NSIS/gamemaker-studio-100-prog-challenges' &
git clone https://github.com/PortableApps/AppConfigs '/storage/nvme5/new_clones/NSIS/AppConfigs' &
git clone https://github.com/rfinnie/hlulsl '/storage/nvme5/new_clones/NSIS/hlulsl' &
git clone https://github.com/AlbinoDrought/wails-android-test '/storage/nvme5/new_clones/NSIS/wails-android-test' &
git clone https://github.com/omaha-consulting/auto-update-windows-service '/storage/nvme5/new_clones/NSIS/auto-update-windows-service' &
git clone https://github.com/Extravi/Installer '/storage/nvme5/new_clones/NSIS/Installer' &
git clone https://github.com/AkmalFairuz/packencryptor '/storage/nvme5/new_clones/NSIS/packencryptor' &
git clone https://github.com/thep0y/up2b-gui '/storage/nvme5/new_clones/NSIS/up2b-gui' &
git clone https://github.com/BaseXdb/basex-dist '/storage/nvme5/new_clones/NSIS/basex-dist' &
git clone https://github.com/CoolProp/GUI '/storage/nvme5/new_clones/NSIS/GUI' &
git clone https://github.com/centreon/centreon-nsclient-build '/storage/nvme5/new_clones/NSIS/centreon-nsclient-build' &
git clone https://github.com/Aloft-Lab/CTeX-Installer '/storage/nvme5/new_clones/NSIS/CTeX-Installer' &
git clone https://github.com/mikecentola/cmder_inst '/storage/nvme5/new_clones/NSIS/cmder_inst' &
git clone https://github.com/OSVR/OSVR-HDK-Windows-Drivers '/storage/nvme5/new_clones/NSIS/OSVR-HDK-Windows-Drivers' &
git clone https://github.com/aboutflash/StarCitizen-WarthogScript '/storage/nvme5/new_clones/NSIS/StarCitizen-WarthogScript' &
git clone https://github.com/Red5/installer '/storage/nvme5/new_clones/NSIS/installer' &
git clone https://github.com/dlo9/LSI-9211-8i-IT-USB '/storage/nvme5/new_clones/NSIS/LSI-9211-8i-IT-USB' &
git clone https://github.com/qnighy/satysfi-cross-windows '/storage/nvme5/new_clones/NSIS/satysfi-cross-windows' &
git clone https://github.com/mazeyqian/go-run-wechat-demo '/storage/nvme5/new_clones/NSIS/go-run-wechat-demo' &
git clone https://github.com/UMATracker/UMATracker '/storage/nvme5/new_clones/NSIS/UMATracker' &
git clone https://github.com/boundary/winpcap-installer '/storage/nvme5/new_clones/NSIS/winpcap-installer' &
git clone https://github.com/sverrirs/CorsairK95 '/storage/nvme5/new_clones/NSIS/CorsairK95' &
git clone https://github.com/ocenaudio/ocenaudio-translations '/storage/nvme5/new_clones/NSIS/ocenaudio-translations' &
git clone https://github.com/dedSyn4ps3/wails-react-demo '/storage/nvme5/new_clones/NSIS/wails-react-demo' &
git clone https://github.com/SoftwareNetwork/binaries '/storage/nvme5/new_clones/NSIS/binaries' &
git clone https://github.com/rddim/GoogleEarthProPortable '/storage/nvme5/new_clones/NSIS/GoogleEarthProPortable' &
git clone https://github.com/moebiussurfing/OF_Windows_Installer '/storage/nvme5/new_clones/NSIS/OF_Windows_Installer' &
git clone https://github.com/2wayne/EclipsePortable '/storage/nvme5/new_clones/NSIS/EclipsePortable' &
git clone https://github.com/o8x/spirit '/storage/nvme5/new_clones/NSIS/spirit' &
git clone https://github.com/liamlife/nsis-tutorial '/storage/nvme5/new_clones/NSIS/nsis-tutorial' &
git clone https://github.com/AnonymerNiklasistanonym/NsiWindowsInstallerExamples '/storage/nvme5/new_clones/NSIS/NsiWindowsInstallerExamples' &
git clone https://github.com/PinguinoIDE/pinguino-installers '/storage/nvme5/new_clones/NSIS/pinguino-installers' &
git clone https://github.com/groovy/groovy-windows-installer '/storage/nvme5/new_clones/NSIS/groovy-windows-installer' &
git clone https://github.com/OCSInventory-NG/Packager-for-Windows '/storage/nvme5/new_clones/NSIS/Packager-for-Windows' &
git clone https://github.com/filebot/filebot-installer '/storage/nvme5/new_clones/NSIS/filebot-installer' &
git clone https://github.com/xmcy0011/CoffeeChat-Win '/storage/nvme5/new_clones/NSIS/CoffeeChat-Win' &
git clone https://github.com/nQuake/client-win32 '/storage/nvme5/new_clones/NSIS/client-win32' &
git clone https://github.com/mumblepins/ParticleToolchainInstaller '/storage/nvme5/new_clones/NSIS/ParticleToolchainInstaller' &
git clone https://github.com/kingsunc/Nsis_Duilib '/storage/nvme5/new_clones/NSIS/Nsis_Duilib' &
git clone https://github.com/OleksandrBlack/ukita_installer '/storage/nvme5/new_clones/NSIS/ukita_installer' &
git clone https://github.com/joncloud/makensis-action-test '/storage/nvme5/new_clones/NSIS/makensis-action-test' &
git clone https://github.com/Shair17/wannabemygf '/storage/nvme5/new_clones/NSIS/wannabemygf' &
git clone https://github.com/GameMakerDiscord/wind-shader '/storage/nvme5/new_clones/NSIS/wind-shader' &
git clone https://github.com/WeebDataHoarder/p2pool-nsis '/storage/nvme5/new_clones/NSIS/p2pool-nsis' &
git clone https://github.com/daemondevin/Notepad-Deux-Plus-Portable '/storage/nvme5/new_clones/NSIS/Notepad-Deux-Plus-Portable' &
git clone https://github.com/MFCer/EasySetup '/storage/nvme5/new_clones/NSIS/EasySetup' &
git clone https://github.com/pynickle/PureWriter-Desktop-Setup '/storage/nvme5/new_clones/NSIS/PureWriter-Desktop-Setup' &
git clone https://github.com/jaenicke/usermanager '/storage/nvme5/new_clones/NSIS/usermanager' &
git clone https://github.com/DKMS-LSL/typeloader '/storage/nvme5/new_clones/NSIS/typeloader' &
git clone https://github.com/baasgeo/mapproxywindows '/storage/nvme5/new_clones/NSIS/mapproxywindows' &
git clone https://github.com/lorenzo-zurini/PALSymLink '/storage/nvme5/new_clones/NSIS/PALSymLink' &
git clone https://github.com/papamas/udin '/storage/nvme5/new_clones/NSIS/udin' &
git clone https://github.com/achabdo/Secret-Mario-Engine '/storage/nvme5/new_clones/NSIS/Secret-Mario-Engine' &
git clone https://github.com/unixbhaskar/UEFI_Linux_Boot_Process_From_Userland '/storage/nvme5/new_clones/NSIS/UEFI_Linux_Boot_Process_From_Userland' &
git clone https://github.com/adobe/UST-Install-Scripts '/storage/nvme5/new_clones/NSIS/UST-Install-Scripts' &
git clone https://github.com/elementbound/gms-dijkstra-gpu '/storage/nvme5/new_clones/NSIS/gms-dijkstra-gpu' &
git clone https://github.com/arx/ArxPackages '/storage/nvme5/new_clones/NSIS/ArxPackages' &
git clone https://github.com/mcosta74/game-of-life '/storage/nvme5/new_clones/NSIS/game-of-life' &
git clone https://github.com/ngudbhav/Webkiosk-Wrapper '/storage/nvme5/new_clones/NSIS/Webkiosk-Wrapper' &
git clone https://github.com/AButton117/GameMaker-Studio-Tutorial- '/storage/nvme5/new_clones/NSIS/GameMaker-Studio-Tutorial-' &
git clone https://github.com/openlvc/hperf '/storage/nvme5/new_clones/NSIS/hperf' &
git clone https://github.com/osyu/EdgeDeflectorSlim '/storage/nvme5/new_clones/NSIS/EdgeDeflectorSlim' &
git clone https://github.com/Hope-IT-Works/Explorestart '/storage/nvme5/new_clones/NSIS/Explorestart' &
git clone https://github.com/bigtweekx/h2pc_installer '/storage/nvme5/new_clones/NSIS/h2pc_installer' &
git clone https://github.com/FoldingAtHome/fah-client-win-installer '/storage/nvme5/new_clones/NSIS/fah-client-win-installer' &
git clone https://github.com/8cH9azbsFifZ/garmin-opentopo '/storage/nvme5/new_clones/NSIS/garmin-opentopo' &
git clone https://github.com/langmo/gradle-nsis '/storage/nvme5/new_clones/NSIS/gradle-nsis' &
git clone https://github.com/lordmulder/Chromium-Updater '/storage/nvme5/new_clones/NSIS/Chromium-Updater' &
git clone https://github.com/dleidert/bde-lock '/storage/nvme5/new_clones/NSIS/bde-lock' &
git clone https://github.com/daemondevin/IcoFXPortable '/storage/nvme5/new_clones/NSIS/IcoFXPortable' &
git clone https://github.com/labjack/windows_example_installer '/storage/nvme5/new_clones/NSIS/windows_example_installer' &
git clone https://github.com/joachimvandekerckhove/jags-cddm '/storage/nvme5/new_clones/NSIS/jags-cddm' &
git clone https://github.com/FortressOne/windows-installer '/storage/nvme5/new_clones/NSIS/windows-installer' &
git clone https://github.com/billyc/cwrsync-installer '/storage/nvme5/new_clones/NSIS/cwrsync-installer' &
git clone https://github.com/dbanet/tws '/storage/nvme5/new_clones/NSIS/tws' &
