#!/bin/bash

git clone https://github.com/h5bp/Front-end-Developer-Interview-Questions '/storage/nvme5/new_clones/Nunjucks/Front-end-Developer-Interview-Questions' &
git clone https://github.com/a11yproject/a11yproject.com '/storage/nvme5/new_clones/Nunjucks/a11yproject.com' &
git clone https://github.com/GoogleChrome/web.dev '/storage/nvme5/new_clones/Nunjucks/web.dev' &
git clone https://github.com/duffn/dumb-password-rules '/storage/nvme5/new_clones/Nunjucks/dumb-password-rules' &
git clone https://github.com/jamstack/jamstack.org '/storage/nvme5/new_clones/Nunjucks/jamstack.org' &
git clone https://github.com/ksylor/ohshitgit '/storage/nvme5/new_clones/Nunjucks/ohshitgit' &
git clone https://github.com/ipld/ipld '/storage/nvme5/new_clones/Nunjucks/ipld' &
git clone https://github.com/stefanjudis/tiny-helpers '/storage/nvme5/new_clones/Nunjucks/tiny-helpers' &
git clone https://github.com/Andy-set-studio/hylia '/storage/nvme5/new_clones/Nunjucks/hylia' &
git clone https://github.com/typlog/china-indie-podcasts '/storage/nvme5/new_clones/Nunjucks/china-indie-podcasts' &
git clone https://github.com/5t3ph/smolcss '/storage/nvme5/new_clones/Nunjucks/smolcss' &
git clone https://github.com/xdesro/personalsit.es '/storage/nvme5/new_clones/Nunjucks/personalsit.es' &
git clone https://github.com/nhsuk/nhsuk-frontend '/storage/nvme5/new_clones/Nunjucks/nhsuk-frontend' &
git clone https://github.com/bigskysoftware/hypermedia-systems-old '/storage/nvme5/new_clones/Nunjucks/hypermedia-systems-old' &
git clone https://github.com/matuzo/HTMHell '/storage/nvme5/new_clones/Nunjucks/HTMHell' &
git clone https://github.com/alphagov/govuk-design-system '/storage/nvme5/new_clones/Nunjucks/govuk-design-system' &
git clone https://github.com/danurbanowicz/eleventy-netlify-boilerplate '/storage/nvme5/new_clones/Nunjucks/eleventy-netlify-boilerplate' &
git clone https://github.com/11ty/11ty-website '/storage/nvme5/new_clones/Nunjucks/11ty-website' &
git clone https://github.com/madrilene/eleventy-excellent '/storage/nvme5/new_clones/Nunjucks/eleventy-excellent' &
git clone https://github.com/daviddarnes/mac-cursors '/storage/nvme5/new_clones/Nunjucks/mac-cursors' &
git clone https://github.com/shadeed/rtl-styling '/storage/nvme5/new_clones/Nunjucks/rtl-styling' &
git clone https://github.com/TryGhost/eleventy-starter-ghost '/storage/nvme5/new_clones/Nunjucks/eleventy-starter-ghost' &
git clone https://github.com/chrissy-dev/eleventy-web-starter '/storage/nvme5/new_clones/Nunjucks/eleventy-web-starter' &
git clone https://github.com/maxboeck/webring '/storage/nvme5/new_clones/Nunjucks/webring' &
git clone https://github.com/5t3ph/11ty-sass-skeleton '/storage/nvme5/new_clones/Nunjucks/11ty-sass-skeleton' &
git clone https://github.com/CSS-Tricks/conferences '/storage/nvme5/new_clones/Nunjucks/conferences' &
git clone https://github.com/maxboeck/whimsical '/storage/nvme5/new_clones/Nunjucks/whimsical' &
git clone https://github.com/gregwolanski/eleventy-tailwindcss-alpinejs-starter '/storage/nvme5/new_clones/Nunjucks/eleventy-tailwindcss-alpinejs-starter' &
git clone https://github.com/joshuacc/prose-for-programmers '/storage/nvme5/new_clones/Nunjucks/prose-for-programmers' &
git clone https://github.com/jsdoc/jsdoc.github.io '/storage/nvme5/new_clones/Nunjucks/jsdochub.io' &
git clone https://github.com/daflh/vredeburg '/storage/nvme5/new_clones/Nunjucks/vredeburg' &
git clone https://github.com/rafaelconde/rafaelconde '/storage/nvme5/new_clones/Nunjucks/rafaelconde' &
git clone https://github.com/hooozen/hexo-theme-tranquility '/storage/nvme5/new_clones/Nunjucks/hexo-theme-tranquility' &
git clone https://github.com/bigskysoftware/grugbrain.dev '/storage/nvme5/new_clones/Nunjucks/grugbrain.dev' &
git clone https://github.com/metalsmith/metalsmith.io '/storage/nvme5/new_clones/Nunjucks/metalsmith.io' &
git clone https://github.com/huangdarren1106/huangdarren1106.github.io '/storage/nvme5/new_clones/Nunjucks/huangdarren1106hub.io' &
git clone https://github.com/reeseschultz/11r '/storage/nvme5/new_clones/Nunjucks/11r' &
git clone https://github.com/5t3ph/moderncss-dot-dev '/storage/nvme5/new_clones/Nunjucks/moderncss-dot-dev' &
git clone https://github.com/5t3ph/htmlrecipes '/storage/nvme5/new_clones/Nunjucks/htmlrecipes' &
git clone https://github.com/penpot/penpot-docs '/storage/nvme5/new_clones/Nunjucks/penpot-docs' &
git clone https://github.com/ffoodd/chaarts '/storage/nvme5/new_clones/Nunjucks/chaarts' &
git clone https://github.com/tomreinert/minimal-11ty-tailwind-starter '/storage/nvme5/new_clones/Nunjucks/minimal-11ty-tailwind-starter' &
git clone https://github.com/11ta/11ta-template '/storage/nvme5/new_clones/Nunjucks/11ta-template' &
git clone https://github.com/hidde/eleventy-wcag-reporter '/storage/nvme5/new_clones/Nunjucks/eleventy-wcag-reporter' &
git clone https://github.com/philhawksworth/hawksworx.com '/storage/nvme5/new_clones/Nunjucks/hawksworx.com' &
git clone https://github.com/lumeland/base-blog '/storage/nvme5/new_clones/Nunjucks/base-blog' &
git clone https://github.com/iGuan7u/Acetolog '/storage/nvme5/new_clones/Nunjucks/Acetolog' &
git clone https://github.com/Andy-set-studio/11ty-base '/storage/nvme5/new_clones/Nunjucks/11ty-base' &
git clone https://github.com/nhoizey/1y '/storage/nvme5/new_clones/Nunjucks/1y' &
git clone https://github.com/netlify/templates '/storage/nvme5/new_clones/Nunjucks/templates' &
git clone https://github.com/ineffyble/genders.wtf '/storage/nvme5/new_clones/Nunjucks/genders.wtf' &
git clone https://github.com/henrycatalinismith/wargames '/storage/nvme5/new_clones/Nunjucks/wargames' &
git clone https://github.com/muenzpraeger/eleventy-chirpy-blog-template '/storage/nvme5/new_clones/Nunjucks/eleventy-chirpy-blog-template' &
git clone https://github.com/orbit-love/orbit-web '/storage/nvme5/new_clones/Nunjucks/orbit-web' &
git clone https://github.com/maeligg/my-online-cookbook '/storage/nvme5/new_clones/Nunjucks/my-online-cookbook' &
git clone https://github.com/nhsuk/nhsuk-service-manual '/storage/nvme5/new_clones/Nunjucks/nhsuk-service-manual' &
git clone https://github.com/Orange-OpenSource/a11y-guidelines '/storage/nvme5/new_clones/Nunjucks/a11y-guidelines' &
git clone https://github.com/ar363/eleventy-stylus-blog-theme '/storage/nvme5/new_clones/Nunjucks/eleventy-stylus-blog-theme' &
git clone https://github.com/jayehernandez/jayehernandez '/storage/nvme5/new_clones/Nunjucks/jayehernandez' &
git clone https://github.com/webpixels/bootstrap-dashboard-kit '/storage/nvme5/new_clones/Nunjucks/bootstrap-dashboard-kit' &
git clone https://github.com/ericwbailey/ericwbailey.website '/storage/nvme5/new_clones/Nunjucks/ericwbailey.website' &
git clone https://github.com/kevin-powell/new-website '/storage/nvme5/new_clones/Nunjucks/new-website' &
git clone https://github.com/codegouvfr/eleventy-dsfr '/storage/nvme5/new_clones/Nunjucks/eleventy-dsfr' &
git clone https://github.com/pure-dns/puredns '/storage/nvme5/new_clones/Nunjucks/puredns' &
git clone https://github.com/indiana-university/rivet-source '/storage/nvme5/new_clones/Nunjucks/rivet-source' &
git clone https://github.com/webpixels/bootstrap-starter-kit '/storage/nvme5/new_clones/Nunjucks/bootstrap-starter-kit' &
git clone https://github.com/oddbird/css-sandbox '/storage/nvme5/new_clones/Nunjucks/css-sandbox' &
git clone https://github.com/StaticMania/roxo-eleventy '/storage/nvme5/new_clones/Nunjucks/roxo-eleventy' &
git clone https://github.com/junioralcant/sistema-entrada-saida '/storage/nvme5/new_clones/Nunjucks/sistema-entrada-saida' &
git clone https://github.com/edheltzel/vscode-better-solarized '/storage/nvme5/new_clones/Nunjucks/vscode-better-solarized' &
git clone https://github.com/netlify/petsofnetlify '/storage/nvme5/new_clones/Nunjucks/petsofnetlify' &
git clone https://github.com/claudia-rndrs/eleventy-not-so-minimal-blog-starter '/storage/nvme5/new_clones/Nunjucks/eleventy-not-so-minimal-blog-starter' &
git clone https://github.com/getkirby/eleventykit '/storage/nvme5/new_clones/Nunjucks/eleventykit' &
git clone https://github.com/philhawksworth/html-time '/storage/nvme5/new_clones/Nunjucks/html-time' &
git clone https://github.com/peruvianidol/11ty-recipes '/storage/nvme5/new_clones/Nunjucks/11ty-recipes' &
git clone https://github.com/MarcoMicale/Minimalism '/storage/nvme5/new_clones/Nunjucks/Minimalism' &
git clone https://github.com/EllyLoel/ellyloel.com '/storage/nvme5/new_clones/Nunjucks/ellyloel.com' &
git clone https://github.com/sophiekoonin/localghost '/storage/nvme5/new_clones/Nunjucks/localghost' &
git clone https://github.com/vycke/crinkles.dev '/storage/nvme5/new_clones/Nunjucks/crinkles.dev' &
git clone https://github.com/stefanjudis/browsers.fyi '/storage/nvme5/new_clones/Nunjucks/browsers.fyi' &
git clone https://github.com/Speed-Patterns/speed-patterns '/storage/nvme5/new_clones/Nunjucks/speed-patterns' &
git clone https://github.com/ONSdigital/design-system '/storage/nvme5/new_clones/Nunjucks/design-system' &
git clone https://github.com/sunuazizrahayu/free-mediumish-blogger-template '/storage/nvme5/new_clones/Nunjucks/free-mediumish-blogger-template' &
git clone https://github.com/soyHenry/Math4Data '/storage/nvme5/new_clones/Nunjucks/Math4Data' &
git clone https://github.com/gc-da11yn/gc-da11yn.github.io '/storage/nvme5/new_clones/Nunjucks/gc-da11ynhub.io' &
git clone https://github.com/jeremydaly/eleventy-tailwind-template '/storage/nvme5/new_clones/Nunjucks/eleventy-tailwind-template' &
git clone https://github.com/kevin-powell/11ty-blog-site '/storage/nvme5/new_clones/Nunjucks/11ty-blog-site' &
git clone https://github.com/pwa-builder/pwabuilder-blog '/storage/nvme5/new_clones/Nunjucks/pwabuilder-blog' &
git clone https://github.com/djyde/AMAzingTalk '/storage/nvme5/new_clones/Nunjucks/AMAzingTalk' &
git clone https://github.com/ts-dev-inc/ts.dev '/storage/nvme5/new_clones/Nunjucks/ts.dev' &
git clone https://github.com/mandrasch/11ty-plain-bootstrap5 '/storage/nvme5/new_clones/Nunjucks/11ty-plain-bootstrap5' &
git clone https://github.com/lkhrs/eleventy-simple '/storage/nvme5/new_clones/Nunjucks/eleventy-simple' &
git clone https://github.com/robinrendle/robinrendle.com '/storage/nvme5/new_clones/Nunjucks/robinrendle.com' &
git clone https://github.com/nodejs-design-patterns-book/nodejsdesignpatterns.com '/storage/nvme5/new_clones/Nunjucks/nodejsdesignpatterns.com' &
git clone https://github.com/app-generator/eleventy-soft-ui-design '/storage/nvme5/new_clones/Nunjucks/eleventy-soft-ui-design' &
git clone https://github.com/lwojcik/mastodon-poradnik.pl '/storage/nvme5/new_clones/Nunjucks/mastodon-poradnik.pl' &
git clone https://github.com/SpinalCMS/11ty-docs-template '/storage/nvme5/new_clones/Nunjucks/11ty-docs-template' &
git clone https://github.com/rqh656418510/hexo-next-darkmode '/storage/nvme5/new_clones/Nunjucks/hexo-next-darkmode' &
git clone https://github.com/fword-dev/f-word.dev '/storage/nvme5/new_clones/Nunjucks/f-word.dev' &
git clone https://github.com/shanerobinson/linkist '/storage/nvme5/new_clones/Nunjucks/linkist' &
git clone https://github.com/mirisuzanne/mia '/storage/nvme5/new_clones/Nunjucks/mia' &
git clone https://github.com/JasonEtco/jasonet.co '/storage/nvme5/new_clones/Nunjucks/jasonet.co' &
git clone https://github.com/rustfoundation/foundation.rust-lang.org '/storage/nvme5/new_clones/Nunjucks/foundation.rust-lang.org' &
git clone https://github.com/cloudflare/research.cloudflare.com '/storage/nvme5/new_clones/Nunjucks/research.cloudflare.com' &
git clone https://github.com/x-govuk/govuk-design-history-template '/storage/nvme5/new_clones/Nunjucks/govuk-design-history-template' &
git clone https://github.com/VLCTechHub/VLCTechHub-site '/storage/nvme5/new_clones/Nunjucks/VLCTechHub-site' &
git clone https://github.com/rknightuk/rknight.me '/storage/nvme5/new_clones/Nunjucks/rknight.me' &
git clone https://github.com/jsconf/festival-x.jsconf.eu '/storage/nvme5/new_clones/Nunjucks/festival-x.jsconf.eu' &
git clone https://github.com/next-theme/hexo-next-giscus '/storage/nvme5/new_clones/Nunjucks/hexo-next-giscus' &
git clone https://github.com/siakaramalegos/sia.codes-eleventy '/storage/nvme5/new_clones/Nunjucks/sia.codes-eleventy' &
git clone https://github.com/FlowFuse/website '/storage/nvme5/new_clones/Nunjucks/website' &
git clone https://github.com/visual-framework/vf-core '/storage/nvme5/new_clones/Nunjucks/vf-core' &
git clone https://github.com/AlynxZhou/hikaru-theme-aria '/storage/nvme5/new_clones/Nunjucks/hikaru-theme-aria' &
git clone https://github.com/LinkedInLearning/serverless-jamstack-eleventy-2824238 '/storage/nvme5/new_clones/Nunjucks/serverless-jamstack-eleventy-2824238' &
git clone https://github.com/brycewray/eleventy_solo_starter_njk '/storage/nvme5/new_clones/Nunjucks/eleventy_solo_starter_njk' &
git clone https://github.com/jeromecoupe/11ty-paginate-taxonomies '/storage/nvme5/new_clones/Nunjucks/11ty-paginate-taxonomies' &
git clone https://github.com/aarongarciah/parcel-static-boilerplate '/storage/nvme5/new_clones/Nunjucks/parcel-static-boilerplate' &
git clone https://github.com/DiversityCorp/companies-on-blm '/storage/nvme5/new_clones/Nunjucks/companies-on-blm' &
git clone https://github.com/brycewray/eleventy_solo '/storage/nvme5/new_clones/Nunjucks/eleventy_solo' &
git clone https://github.com/stopnoanime/11ty-no-style-please '/storage/nvme5/new_clones/Nunjucks/11ty-no-style-please' &
git clone https://github.com/agility/agilitycms-eleventy-starter-2020 '/storage/nvme5/new_clones/Nunjucks/agilitycms-eleventy-starter-2020' &
git clone https://github.com/dvsa/front-end '/storage/nvme5/new_clones/Nunjucks/front-end' &
git clone https://github.com/Andy-set-studio/11ty-pattern-library '/storage/nvme5/new_clones/Nunjucks/11ty-pattern-library' &
git clone https://github.com/malgamves/11ty-x-strapi '/storage/nvme5/new_clones/Nunjucks/11ty-x-strapi' &
git clone https://github.com/jalibu/MMM-BoschSmartHome '/storage/nvme5/new_clones/Nunjucks/MMM-BoschSmartHome' &
git clone https://github.com/oddbird/sliiides '/storage/nvme5/new_clones/Nunjucks/sliiides' &
git clone https://github.com/Thomasorus/Ronbun '/storage/nvme5/new_clones/Nunjucks/Ronbun' &
git clone https://github.com/stefanjudis/tiny-teachers '/storage/nvme5/new_clones/Nunjucks/tiny-teachers' &
git clone https://github.com/mirisuzanne/teacup '/storage/nvme5/new_clones/Nunjucks/teacup' &
git clone https://github.com/jeromecoupe/multilingual_eleventy '/storage/nvme5/new_clones/Nunjucks/multilingual_eleventy' &
git clone https://github.com/nhoizey/nicolas-hoizey.photo '/storage/nvme5/new_clones/Nunjucks/nicolas-hoizey.photo' &
git clone https://github.com/charlesLoder/hebrewTransliteration '/storage/nvme5/new_clones/Nunjucks/hebrewTransliteration' &
git clone https://github.com/alex-page/harmonograph.art '/storage/nvme5/new_clones/Nunjucks/harmonograph.art' &
git clone https://github.com/fs-tw/FS.Abp '/storage/nvme5/new_clones/Nunjucks/FS.Abp' &
git clone https://github.com/mainmatter/mainmatter.com '/storage/nvme5/new_clones/Nunjucks/mainmatter.com' &
git clone https://github.com/trys/11ty-component-macro '/storage/nvme5/new_clones/Nunjucks/11ty-component-macro' &
git clone https://github.com/huangyuzhang/Fizzy-Jam '/storage/nvme5/new_clones/Nunjucks/Fizzy-Jam' &
git clone https://github.com/dwp/design-system '/storage/nvme5/new_clones/Nunjucks/design-system' &
git clone https://github.com/matuzo/accessibility-cookbook '/storage/nvme5/new_clones/Nunjucks/accessibility-cookbook' &
git clone https://github.com/tylergaw/tylergaw.com '/storage/nvme5/new_clones/Nunjucks/tylergaw.com' &
git clone https://github.com/soyHenry/Datathon '/storage/nvme5/new_clones/Nunjucks/Datathon' &
git clone https://github.com/EmptyWork/emptywork.github.io '/storage/nvme5/new_clones/Nunjucks/emptyworkhub.io' &
git clone https://github.com/siakaramalegos/sia.studio '/storage/nvme5/new_clones/Nunjucks/sia.studio' &
git clone https://github.com/XYQuadrat/polyring '/storage/nvme5/new_clones/Nunjucks/polyring' &
git clone https://github.com/erikkroes/erikkroes-nl '/storage/nvme5/new_clones/Nunjucks/erikkroes-nl' &
git clone https://github.com/flamedfury/flamedfury.com '/storage/nvme5/new_clones/Nunjucks/flamedfury.com' &
git clone https://github.com/MarkBuskbjerg/ta11y '/storage/nvme5/new_clones/Nunjucks/ta11y' &
git clone https://github.com/Wilto/hire.wil.to '/storage/nvme5/new_clones/Nunjucks/hire.wil.to' &
git clone https://github.com/mkbdfr/website '/storage/nvme5/new_clones/Nunjucks/website' &
git clone https://github.com/codomposer/Front-end-Developer-Interview-Questions '/storage/nvme5/new_clones/Nunjucks/Front-end-Developer-Interview-Questions' &
git clone https://github.com/frctl/demo.fractal.build '/storage/nvme5/new_clones/Nunjucks/demo.fractal.build' &
git clone https://github.com/collapsology/collapsology '/storage/nvme5/new_clones/Nunjucks/collapsology' &
git clone https://github.com/querkmachine/beeps.website '/storage/nvme5/new_clones/Nunjucks/beeps.website' &
git clone https://github.com/JavaScriptMN/javascriptmn.github.io '/storage/nvme5/new_clones/Nunjucks/javascriptmnhub.io' &
git clone https://github.com/Accudio/alistair-shepherd '/storage/nvme5/new_clones/Nunjucks/alistair-shepherd' &
git clone https://github.com/brob/plug11ty.com '/storage/nvme5/new_clones/Nunjucks/plug11ty.com' &
git clone https://github.com/gerhynes/eleventy-portfolio '/storage/nvme5/new_clones/Nunjucks/eleventy-portfolio' &
git clone https://github.com/bmeurer/benediktmeurer.de '/storage/nvme5/new_clones/Nunjucks/benediktmeurer.de' &
git clone https://github.com/TigersWay/fruits-express '/storage/nvme5/new_clones/Nunjucks/fruits-express' &
git clone https://github.com/stackbit/stackbit-theme-spectral '/storage/nvme5/new_clones/Nunjucks/stackbit-theme-spectral' &
git clone https://github.com/fylgja/11ty-starter-template '/storage/nvme5/new_clones/Nunjucks/11ty-starter-template' &
git clone https://github.com/indutny/blog '/storage/nvme5/new_clones/Nunjucks/blog' &
git clone https://github.com/vipickering/vincentp '/storage/nvme5/new_clones/Nunjucks/vincentp' &
git clone https://github.com/julianduque/julianduque.co '/storage/nvme5/new_clones/Nunjucks/julianduque.co' &
git clone https://github.com/cathydutton/cathydutton.co.uk '/storage/nvme5/new_clones/Nunjucks/cathydutton.co.uk' &
git clone https://github.com/empatheticbot/the-traveler-times '/storage/nvme5/new_clones/Nunjucks/the-traveler-times' &
git clone https://github.com/defront/defront.ru '/storage/nvme5/new_clones/Nunjucks/defront.ru' &
git clone https://github.com/kgpmask/MASK '/storage/nvme5/new_clones/Nunjucks/MASK' &
git clone https://github.com/pizidavi/Trakt-Widgets-2 '/storage/nvme5/new_clones/Nunjucks/Trakt-Widgets-2' &
git clone https://github.com/mesinkasir/11ty-shop '/storage/nvme5/new_clones/Nunjucks/11ty-shop' &
git clone https://github.com/domenic/blog.domenic.me '/storage/nvme5/new_clones/Nunjucks/blog.domenic.me' &
git clone https://github.com/vajename/ML '/storage/nvme5/new_clones/Nunjucks/ML' &
git clone https://github.com/Duosmium/duosmium '/storage/nvme5/new_clones/Nunjucks/duosmium' &
git clone https://github.com/newjersey/njwds '/storage/nvme5/new_clones/Nunjucks/njwds' &
git clone https://github.com/jacebenson/jace-ty '/storage/nvme5/new_clones/Nunjucks/jace-ty' &
git clone https://github.com/jamesdoc/jamesdoc.com '/storage/nvme5/new_clones/Nunjucks/jamesdoc.com' &
git clone https://github.com/HackClubRAIT/Frontend-Owls '/storage/nvme5/new_clones/Nunjucks/Frontend-Owls' &
git clone https://github.com/CloudCannon/justice-eleventy-template '/storage/nvme5/new_clones/Nunjucks/justice-eleventy-template' &
git clone https://github.com/fluid-project/trivet '/storage/nvme5/new_clones/Nunjucks/trivet' &
git clone https://github.com/Level0gamedev/fdisk-site '/storage/nvme5/new_clones/Nunjucks/fdisk-site' &
git clone https://github.com/Waqf-DZ/waqf '/storage/nvme5/new_clones/Nunjucks/waqf' &
git clone https://github.com/11ty/api-explorer '/storage/nvme5/new_clones/Nunjucks/api-explorer' &
git clone https://github.com/alanmosely/teatime-starter '/storage/nvme5/new_clones/Nunjucks/teatime-starter' &
git clone https://github.com/Psypher1/learneleventy '/storage/nvme5/new_clones/Nunjucks/learneleventy' &
git clone https://github.com/jeromecoupe/eleventy_starter '/storage/nvme5/new_clones/Nunjucks/eleventy_starter' &
git clone https://github.com/fission-codes/landing-page '/storage/nvme5/new_clones/Nunjucks/landing-page' &
git clone https://github.com/DFE-Digital/bat-design-history '/storage/nvme5/new_clones/Nunjucks/bat-design-history' &
git clone https://github.com/andrew--r/forweb.dev '/storage/nvme5/new_clones/Nunjucks/forweb.dev' &
git clone https://github.com/zachleat/rainglow '/storage/nvme5/new_clones/Nunjucks/rainglow' &
git clone https://github.com/larryhudson/11ty-prince-pdf-example '/storage/nvme5/new_clones/Nunjucks/11ty-prince-pdf-example' &
git clone https://github.com/hidde/books '/storage/nvme5/new_clones/Nunjucks/books' &
git clone https://github.com/thedavedavies/Headless-WordPress-11ty '/storage/nvme5/new_clones/Nunjucks/Headless-WordPress-11ty' &
git clone https://github.com/visidata/visidata.org '/storage/nvme5/new_clones/Nunjucks/visidata.org' &
git clone https://github.com/leicesterjs/site '/storage/nvme5/new_clones/Nunjucks/site' &
git clone https://github.com/eevajonnapanula/neule.art '/storage/nvme5/new_clones/Nunjucks/neule.art' &
git clone https://github.com/saadatm/navees '/storage/nvme5/new_clones/Nunjucks/navees' &
git clone https://github.com/oyanqazaqstan/website '/storage/nvme5/new_clones/Nunjucks/website' &
git clone https://github.com/planetoftheweb/planetoftheweb.github.io '/storage/nvme5/new_clones/Nunjucks/planetofthewebhub.io' &
git clone https://github.com/shanerobinson/tea-base-template '/storage/nvme5/new_clones/Nunjucks/tea-base-template' &
git clone https://github.com/mesinkasir/thisis-11ty '/storage/nvme5/new_clones/Nunjucks/thisis-11ty' &
git clone https://github.com/officialrajdeepsingh/Minimalist-blog '/storage/nvme5/new_clones/Nunjucks/Minimalist-blog' &
git clone https://github.com/TNRIS/tnris.org '/storage/nvme5/new_clones/Nunjucks/tnris.org' &
git clone https://github.com/alexk111/DeBitpay-Directory '/storage/nvme5/new_clones/Nunjucks/DeBitpay-Directory' &
git clone https://github.com/httpsterio/11ty-blog-njk-starter '/storage/nvme5/new_clones/Nunjucks/11ty-blog-njk-starter' &
git clone https://github.com/Eleventy-Meetup/website '/storage/nvme5/new_clones/Nunjucks/website' &
git clone https://github.com/GoogleForCreators/wp.stories.google '/storage/nvme5/new_clones/Nunjucks/wp.stories.google' &
git clone https://github.com/djyde/blog-2020 '/storage/nvme5/new_clones/Nunjucks/blog-2020' &
git clone https://github.com/mesinkasir/cuteblog11ty '/storage/nvme5/new_clones/Nunjucks/cuteblog11ty' &
git clone https://github.com/mattlehrer/eleventy-alpine-tailwind-snowpack '/storage/nvme5/new_clones/Nunjucks/eleventy-alpine-tailwind-snowpack' &
git clone https://github.com/chriskirknielsen/2020 '/storage/nvme5/new_clones/Nunjucks/2020' &
git clone https://github.com/ongov/Ontario.ca-Jamstack-Toolkit '/storage/nvme5/new_clones/Nunjucks/Ontario.ca-Jamstack-Toolkit' &
git clone https://github.com/afnizarnur/afnizarnur.com '/storage/nvme5/new_clones/Nunjucks/afnizarnur.com' &
git clone https://github.com/haxtheweb/hax11ty '/storage/nvme5/new_clones/Nunjucks/hax11ty' &
git clone https://github.com/StarfallProjects/obsidian-netlify-monorepo '/storage/nvme5/new_clones/Nunjucks/obsidian-netlify-monorepo' &
git clone https://github.com/Ted2xmen/eleventree.app '/storage/nvme5/new_clones/Nunjucks/eleventree.app' &
git clone https://github.com/chriskirknielsen/chriskirknielsen.com '/storage/nvme5/new_clones/Nunjucks/chriskirknielsen.com' &
git clone https://github.com/hmmlsystems/11ty-IIIF-Manifest-Generator '/storage/nvme5/new_clones/Nunjucks/11ty-IIIF-Manifest-Generator' &
git clone https://github.com/benjifs/benji '/storage/nvme5/new_clones/Nunjucks/benji' &
git clone https://github.com/disjfa/eleventy-encore '/storage/nvme5/new_clones/Nunjucks/eleventy-encore' &
git clone https://github.com/erwald/blog '/storage/nvme5/new_clones/Nunjucks/blog' &
git clone https://github.com/govuk-one-login/onboarding-product-page '/storage/nvme5/new_clones/Nunjucks/onboarding-product-page' &
git clone https://github.com/BrianMitchL/brianm.me '/storage/nvme5/new_clones/Nunjucks/brianm.me' &
git clone https://github.com/fedsa/front-end-conf-website '/storage/nvme5/new_clones/Nunjucks/front-end-conf-website' &
git clone https://github.com/regenrek/regenrek-blog-11ty '/storage/nvme5/new_clones/Nunjucks/regenrek-blog-11ty' &
git clone https://github.com/oddbird/oddleventy '/storage/nvme5/new_clones/Nunjucks/oddleventy' &
git clone https://github.com/rstacruz/eleventy-parcel-demo '/storage/nvme5/new_clones/Nunjucks/eleventy-parcel-demo' &
git clone https://github.com/gerwitz/hgc-v12 '/storage/nvme5/new_clones/Nunjucks/hgc-v12' &
git clone https://github.com/jmhobbs/jmhobbs.github.com '/storage/nvme5/new_clones/Nunjucks/jmhobbshub.com' &
git clone https://github.com/rizkhal/ayuwind '/storage/nvme5/new_clones/Nunjucks/ayuwind' &
git clone https://github.com/DFE-Digital/register-trainee-teachers-prototype '/storage/nvme5/new_clones/Nunjucks/register-trainee-teachers-prototype' &
git clone https://github.com/mesinkasir/mobile11ty '/storage/nvme5/new_clones/Nunjucks/mobile11ty' &
git clone https://github.com/mesinkasir/eleventyblog '/storage/nvme5/new_clones/Nunjucks/eleventyblog' &
git clone https://github.com/nus-cs2103/website-base '/storage/nvme5/new_clones/Nunjucks/website-base' &
git clone https://github.com/mvllow/mellow-site '/storage/nvme5/new_clones/Nunjucks/mellow-site' &
git clone https://github.com/MoldyMacaroniX/dashword.net '/storage/nvme5/new_clones/Nunjucks/dashword.net' &
git clone https://github.com/jedworkshop/jed2022 '/storage/nvme5/new_clones/Nunjucks/jed2022' &
git clone https://github.com/delineas/reactiver-profile-starter '/storage/nvme5/new_clones/Nunjucks/reactiver-profile-starter' &
git clone https://github.com/brycewray/eleventy_vite '/storage/nvme5/new_clones/Nunjucks/eleventy_vite' &
git clone https://github.com/DISIC/MiNumEco '/storage/nvme5/new_clones/Nunjucks/MiNumEco' &
git clone https://github.com/ravynsoft/website '/storage/nvme5/new_clones/Nunjucks/website' &
git clone https://github.com/PyCampES/pycampes '/storage/nvme5/new_clones/Nunjucks/pycampes' &
git clone https://github.com/supertanuki/techologieWeb '/storage/nvme5/new_clones/Nunjucks/techologieWeb' &
git clone https://github.com/mesinkasir/cool11ty '/storage/nvme5/new_clones/Nunjucks/cool11ty' &
git clone https://github.com/DFE-Digital/ucd-manual '/storage/nvme5/new_clones/Nunjucks/ucd-manual' &
git clone https://github.com/codeforjapan/socialhackday '/storage/nvme5/new_clones/Nunjucks/socialhackday' &
git clone https://github.com/jlefkoff/NUWireless-Site '/storage/nvme5/new_clones/Nunjucks/NUWireless-Site' &
git clone https://github.com/JoyceQuerubino/Site-Rocktseat '/storage/nvme5/new_clones/Nunjucks/Site-Rocktseat' &
git clone https://github.com/hiiruki/eleventy-blog '/storage/nvme5/new_clones/Nunjucks/eleventy-blog' &
git clone https://github.com/alexcarpenter/us-coffee-roasters '/storage/nvme5/new_clones/Nunjucks/us-coffee-roasters' &
git clone https://github.com/barryf/barryfrost '/storage/nvme5/new_clones/Nunjucks/barryfrost' &
git clone https://github.com/melanierichards/palindrome '/storage/nvme5/new_clones/Nunjucks/palindrome' &
git clone https://github.com/kingdom-code/kingdom-code '/storage/nvme5/new_clones/Nunjucks/kingdom-code' &
git clone https://github.com/DFE-Digital/manage-teacher-training-applications-prototype '/storage/nvme5/new_clones/Nunjucks/manage-teacher-training-applications-prototype' &
git clone https://github.com/ourfuturehealth/design-system-toolkit '/storage/nvme5/new_clones/Nunjucks/design-system-toolkit' &
git clone https://github.com/jacebenson/sn '/storage/nvme5/new_clones/Nunjucks/sn' &
git clone https://github.com/RevolutionUC/revolutionuc-emails '/storage/nvme5/new_clones/Nunjucks/revolutionuc-emails' &
git clone https://github.com/mesinkasir/text11ty '/storage/nvme5/new_clones/Nunjucks/text11ty' &
git clone https://github.com/openjs-foundation/standards-ed-site '/storage/nvme5/new_clones/Nunjucks/standards-ed-site' &
git clone https://github.com/nhsbsa/research-playbook '/storage/nvme5/new_clones/Nunjucks/research-playbook' &
git clone https://github.com/uillinois-community/uillinois-community.github.io '/storage/nvme5/new_clones/Nunjucks/uillinois-communityhub.io' &
