#!/bin/bash

git clone https://github.com/tolmasky/language '/storage/nvme5/new_clones/Objective-J/language' &
git clone https://github.com/SMUnlimited/AMAI '/storage/nvme5/new_clones/Objective-J/AMAI' &
git clone https://github.com/luddep/LPKit '/storage/nvme5/new_clones/Objective-J/LPKit' &
git clone https://github.com/saikat/DrawTogether '/storage/nvme5/new_clones/Objective-J/DrawTogether' &
git clone https://github.com/cappuccino/issues '/storage/nvme5/new_clones/Objective-J/issues' &
git clone https://github.com/jerodsanto/CappuccinoResource '/storage/nvme5/new_clones/Objective-J/CappuccinoResource' &
git clone https://github.com/actboy168/jass2lua '/storage/nvme5/new_clones/Objective-J/jass2lua' &
git clone https://github.com/ChiefOfGxBxL/WC3MapTranslator '/storage/nvme5/new_clones/Objective-J/WC3MapTranslator' &
git clone https://github.com/nickjs/Cappuccino-Extensions '/storage/nvme5/new_clones/Objective-J/Cappuccino-Extensions' &
git clone https://github.com/jfahrenkrug/Raphuccino '/storage/nvme5/new_clones/Objective-J/Raphuccino' &
git clone https://github.com/cappuccino/cappuccino-demos '/storage/nvme5/new_clones/Objective-J/cappuccino-demos' &
git clone https://github.com/topfunky/cappuccino-couchdb '/storage/nvme5/new_clones/Objective-J/cappuccino-couchdb' &
git clone https://github.com/malkomalko/Cappuccino.tmbundle '/storage/nvme5/new_clones/Objective-J/Cappuccino.tmbundle' &
git clone https://github.com/davidcann/deepDropUpload '/storage/nvme5/new_clones/Objective-J/deepDropUpload' &
git clone https://github.com/saikat/SCAuth '/storage/nvme5/new_clones/Objective-J/SCAuth' &
git clone https://github.com/austinsarner/Frappuccino '/storage/nvme5/new_clones/Objective-J/Frappuccino' &
git clone https://github.com/rbartolome/CoreData-Cappuccino '/storage/nvme5/new_clones/Objective-J/CoreData-Cappuccino' &
git clone https://github.com/eliaskg/Cappuccino-X-Tornado '/storage/nvme5/new_clones/Objective-J/Cappuccino-X-Tornado' &
git clone https://github.com/lep/jassdoc '/storage/nvme5/new_clones/Objective-J/jassdoc' &
git clone https://github.com/wireload/WKTextView '/storage/nvme5/new_clones/Objective-J/WKTextView' &
git clone https://github.com/austinsarner/RunKit '/storage/nvme5/new_clones/Objective-J/RunKit' &
git clone https://github.com/UnryzeC/MemHackAPI '/storage/nvme5/new_clones/Objective-J/MemHackAPI' &
git clone https://github.com/wireload/Ratatosk '/storage/nvme5/new_clones/Objective-J/Ratatosk' &
git clone https://github.com/naichabaobao/jass '/storage/nvme5/new_clones/Objective-J/jass' &
git clone https://github.com/jfahrenkrug/MapKit '/storage/nvme5/new_clones/Objective-J/MapKit' &
git clone https://github.com/tbalthazar-archives/cappuccinocasts-episodes '/storage/nvme5/new_clones/Objective-J/cappuccinocasts-episodes' &
git clone https://github.com/Me1000/CappuTweetie '/storage/nvme5/new_clones/Objective-J/CappuTweetie' &
git clone https://github.com/ryanjafari/CSRichTextEditor '/storage/nvme5/new_clones/Objective-J/CSRichTextEditor' &
git clone https://github.com/fernyb/Sequel-J '/storage/nvme5/new_clones/Objective-J/Sequel-J' &
git clone https://github.com/nestharus/JASS '/storage/nvme5/new_clones/Objective-J/JASS' &
git clone https://github.com/SinZ163/w3x-to-vmf '/storage/nvme5/new_clones/Objective-J/w3x-to-vmf' &
git clone https://github.com/island-troll-tribes/island-troll-tribes '/storage/nvme5/new_clones/Objective-J/island-troll-tribes' &
git clone https://github.com/Me1000/RLOfflineDataStore '/storage/nvme5/new_clones/Objective-J/RLOfflineDataStore' &
git clone https://github.com/cappuccino/OJTest '/storage/nvme5/new_clones/Objective-J/OJTest' &
git clone https://github.com/MCF/FileUpload '/storage/nvme5/new_clones/Objective-J/FileUpload' &
git clone https://github.com/nvs/gem '/storage/nvme5/new_clones/Objective-J/gem' &
git clone https://github.com/eliaskg/EKActivityIndicatorView '/storage/nvme5/new_clones/Objective-J/EKActivityIndicatorView' &
git clone https://github.com/tartiflop/ojgl '/storage/nvme5/new_clones/Objective-J/ojgl' &
git clone https://github.com/saikat/socket-logger '/storage/nvme5/new_clones/Objective-J/socket-logger' &
git clone https://github.com/amari/UIKit '/storage/nvme5/new_clones/Objective-J/UIKit' &
git clone https://github.com/antoniogarrote/clj-r2rml '/storage/nvme5/new_clones/Objective-J/clj-r2rml' &
git clone https://github.com/jerodsanto/CappResourceExample '/storage/nvme5/new_clones/Objective-J/CappResourceExample' &
git clone https://github.com/Me1000/Cappuccino-datepicker '/storage/nvme5/new_clones/Objective-J/Cappuccino-datepicker' &
git clone https://github.com/UnryzeC/UjAPI '/storage/nvme5/new_clones/Objective-J/UjAPI' &
git clone https://github.com/h-vjass/h-vjass '/storage/nvme5/new_clones/Objective-J/h-vjass' &
git clone https://github.com/nickjs/CappuGeo '/storage/nvme5/new_clones/Objective-J/CappuGeo' &
git clone https://github.com/cappuccino/FacebookKit '/storage/nvme5/new_clones/Objective-J/FacebookKit' &
git clone https://github.com/cappuccino/ojunit '/storage/nvme5/new_clones/Objective-J/ojunit' &
git clone https://github.com/luddep/LPKit-Examples '/storage/nvme5/new_clones/Objective-J/LPKit-Examples' &
git clone https://github.com/jfahrenkrug/CPVideoKit '/storage/nvme5/new_clones/Objective-J/CPVideoKit' &
git clone https://github.com/meirtsvi/WazeWP7 '/storage/nvme5/new_clones/Objective-J/WazeWP7' &
git clone https://github.com/dparnell/cucapp '/storage/nvme5/new_clones/Objective-J/cucapp' &
git clone https://github.com/Blimba/PyWC3 '/storage/nvme5/new_clones/Objective-J/PyWC3' &
git clone https://github.com/Mononofu/julia-plot '/storage/nvme5/new_clones/Objective-J/julia-plot' &
git clone https://github.com/hunzsig/h-war3 '/storage/nvme5/new_clones/Objective-J/h-war3' &
git clone https://github.com/dpp/Frothy '/storage/nvme5/new_clones/Objective-J/Frothy' &
git clone https://github.com/lsinger/Play-Push '/storage/nvme5/new_clones/Objective-J/Play-Push' &
git clone https://github.com/quile/Womble '/storage/nvme5/new_clones/Objective-J/Womble' &
git clone https://github.com/ofosho/ChartPlotter '/storage/nvme5/new_clones/Objective-J/ChartPlotter' &
git clone https://github.com/Alos/xyzradio '/storage/nvme5/new_clones/Objective-J/xyzradio' &
git clone https://github.com/eliaskg/EKSpinner '/storage/nvme5/new_clones/Objective-J/EKSpinner' &
git clone https://github.com/Me1000/CappInventory '/storage/nvme5/new_clones/Objective-J/CappInventory' &
git clone https://github.com/aparajita/Cup '/storage/nvme5/new_clones/Objective-J/Cup' &
git clone https://github.com/Frotty/EBR '/storage/nvme5/new_clones/Objective-J/EBR' &
git clone https://github.com/jfahrenkrug/CPOperation '/storage/nvme5/new_clones/Objective-J/CPOperation' &
git clone https://github.com/samsonjs/cpwebsocket '/storage/nvme5/new_clones/Objective-J/cpwebsocket' &
git clone https://github.com/eliaskg/EKSound '/storage/nvme5/new_clones/Objective-J/EKSound' &
git clone https://github.com/Me1000/Githubissues '/storage/nvme5/new_clones/Objective-J/Githubissues' &
git clone https://github.com/cappuccino/socratic '/storage/nvme5/new_clones/Objective-J/socratic' &
git clone https://github.com/klaaspieter/KPUIKit '/storage/nvme5/new_clones/Objective-J/KPUIKit' &
git clone https://github.com/aparajita/SCKit '/storage/nvme5/new_clones/Objective-J/SCKit' &
git clone https://github.com/jfahrenkrug/CappuccinoLocations1 '/storage/nvme5/new_clones/Objective-J/CappuccinoLocations1' &
git clone https://github.com/eliaskg/EKImageReflection '/storage/nvme5/new_clones/Objective-J/EKImageReflection' &
git clone https://github.com/chandlerkent/CKKit '/storage/nvme5/new_clones/Objective-J/CKKit' &
git clone https://github.com/actboy168/jass_for_everedit '/storage/nvme5/new_clones/Objective-J/jass_for_everedit' &
git clone https://github.com/eliaskg/EKShakeAnimation '/storage/nvme5/new_clones/Objective-J/EKShakeAnimation' &
git clone https://github.com/jfahrenkrug/iphonedevcon2010-sproutcore-demo '/storage/nvme5/new_clones/Objective-J/iphonedevcon2010-sproutcore-demo' &
git clone https://github.com/Shadowfiend/ojspec '/storage/nvme5/new_clones/Objective-J/ojspec' &
git clone https://github.com/jfahrenkrug/MacRubyRemote '/storage/nvme5/new_clones/Objective-J/MacRubyRemote' &
git clone https://github.com/davisml/chinchilla '/storage/nvme5/new_clones/Objective-J/chinchilla' &
git clone https://github.com/davidcann/FastStartLogin '/storage/nvme5/new_clones/Objective-J/FastStartLogin' &
git clone https://github.com/jgarth/MCResource '/storage/nvme5/new_clones/Objective-J/MCResource' &
git clone https://github.com/Me1000/Cappuccino-iChat-Table-Demo '/storage/nvme5/new_clones/Objective-J/Cappuccino-iChat-Table-Demo' &
git clone https://github.com/mrcarlberg/LightObject '/storage/nvme5/new_clones/Objective-J/LightObject' &
git clone https://github.com/lhing17/juezhan '/storage/nvme5/new_clones/Objective-J/juezhan' &
git clone https://github.com/Frotty/Frentity '/storage/nvme5/new_clones/Objective-J/Frentity' &
git clone https://github.com/natemartinsf/NMValidatedObject '/storage/nvme5/new_clones/Objective-J/NMValidatedObject' &
git clone https://github.com/jfahrenkrug/MapKit-HelloWorld '/storage/nvme5/new_clones/Objective-J/MapKit-HelloWorld' &
git clone https://github.com/cockatoo-org/Cockatoo '/storage/nvme5/new_clones/Objective-J/Cockatoo' &
git clone https://github.com/juvian/wc3-translate '/storage/nvme5/new_clones/Objective-J/wc3-translate' &
git clone https://github.com/orlaqp/RestfulCappuccino '/storage/nvme5/new_clones/Objective-J/RestfulCappuccino' &
git clone https://github.com/jparkerweb/wdw-adr-checker '/storage/nvme5/new_clones/Objective-J/wdw-adr-checker' &
git clone https://github.com/Son-Guhun/Titan-Land-Lands-of-Plenty '/storage/nvme5/new_clones/Objective-J/Titan-Land-Lands-of-Plenty' &
git clone https://github.com/boucher/tdparsekit '/storage/nvme5/new_clones/Objective-J/tdparsekit' &
git clone https://github.com/artisonian/atlas-price-list '/storage/nvme5/new_clones/Objective-J/atlas-price-list' &
git clone https://github.com/aldrinmartoq/AldrinKit '/storage/nvme5/new_clones/Objective-J/AldrinKit' &
git clone https://github.com/tdauth/wowr '/storage/nvme5/new_clones/Objective-J/wowr' &
git clone https://github.com/MetalfOxXer/Naruto_Ninpou '/storage/nvme5/new_clones/Objective-J/Naruto_Ninpou' &
git clone https://github.com/zach-cloud/JAST '/storage/nvme5/new_clones/Objective-J/JAST' &
git clone https://github.com/Cokemonkey11/execute-wurst '/storage/nvme5/new_clones/Objective-J/execute-wurst' &
git clone https://github.com/tbalthazar-archives/devdiari.es '/storage/nvme5/new_clones/Objective-J/devdiari.es' &
git clone https://github.com/jfahrenkrug/ObjjSafariExtension '/storage/nvme5/new_clones/Objective-J/ObjjSafariExtension' &
git clone https://github.com/pieceable/thrift-cappuccino-rails-example '/storage/nvme5/new_clones/Objective-J/thrift-cappuccino-rails-example' &
git clone https://github.com/jlfarris91/TheLastStand '/storage/nvme5/new_clones/Objective-J/TheLastStand' &
git clone https://github.com/benlangfeld/CappuccinoTalk '/storage/nvme5/new_clones/Objective-J/CappuccinoTalk' &
git clone https://github.com/tuxedout/Font-and-Text-Framework-for-Cappucino '/storage/nvme5/new_clones/Objective-J/Font-and-Text-Framework-for-Cappucino' &
git clone https://github.com/boog/CloudTunes '/storage/nvme5/new_clones/Objective-J/CloudTunes' &
git clone https://github.com/escaco95/Warcraft-III-Libraries '/storage/nvme5/new_clones/Objective-J/Warcraft-III-Libraries' &
git clone https://github.com/nuagenetworks/nukit '/storage/nvme5/new_clones/Objective-J/nukit' &
git clone https://github.com/daboe01/Clinical '/storage/nvme5/new_clones/Objective-J/Clinical' &
git clone https://github.com/marick/critter4us '/storage/nvme5/new_clones/Objective-J/critter4us' &
git clone https://github.com/NELMVN/Warcraft3-Script '/storage/nvme5/new_clones/Objective-J/Warcraft3-Script' &
git clone https://github.com/saikat/SCSocket '/storage/nvme5/new_clones/Objective-J/SCSocket' &
git clone https://github.com/daboe01/CPTextView '/storage/nvme5/new_clones/Objective-J/CPTextView' &
git clone https://github.com/davidcann/DCPathControl '/storage/nvme5/new_clones/Objective-J/DCPathControl' &
git clone https://github.com/cipherxof/war3-types '/storage/nvme5/new_clones/Objective-J/war3-types' &
git clone https://github.com/Ruk33/vrJASS '/storage/nvme5/new_clones/Objective-J/vrJASS' &
git clone https://github.com/ConnorD/Cappuccino-On-Titanium '/storage/nvme5/new_clones/Objective-J/Cappuccino-On-Titanium' &
git clone https://github.com/slevenbits/cappuccino-rounded-box '/storage/nvme5/new_clones/Objective-J/cappuccino-rounded-box' &
git clone https://github.com/Frotty/wurst-table-layout '/storage/nvme5/new_clones/Objective-J/wurst-table-layout' &
git clone https://github.com/tlrobinson/ojrpc '/storage/nvme5/new_clones/Objective-J/ojrpc' &
git clone https://github.com/mafis/Cappuccino-Bindings-Demo '/storage/nvme5/new_clones/Objective-J/Cappuccino-Bindings-Demo' &
git clone https://github.com/tbalthazar-archives/cappuccinoitunesexample '/storage/nvme5/new_clones/Objective-J/cappuccinoitunesexample' &
git clone https://github.com/evadne/irInterfaceKit '/storage/nvme5/new_clones/Objective-J/irInterfaceKit' &
git clone https://github.com/melezov/gruj '/storage/nvme5/new_clones/Objective-J/gruj' &
git clone https://github.com/ShahriyarB/Icecrown '/storage/nvme5/new_clones/Objective-J/Icecrown' &
git clone https://github.com/Overkane/gods-arena '/storage/nvme5/new_clones/Objective-J/gods-arena' &
git clone https://github.com/Frotty/ForestDef '/storage/nvme5/new_clones/Objective-J/ForestDef' &
git clone https://github.com/sethmachine/mmrpg '/storage/nvme5/new_clones/Objective-J/mmrpg' &
git clone https://github.com/appden/collectionview '/storage/nvme5/new_clones/Objective-J/collectionview' &
git clone https://github.com/flowtsohg/jass-minifier '/storage/nvme5/new_clones/Objective-J/jass-minifier' &
git clone https://github.com/jfahrenkrug/CPVideoKitDemo '/storage/nvme5/new_clones/Objective-J/CPVideoKitDemo' &
