#!/bin/bash

git clone https://github.com/odin-lang/Odin '/storage/nvme5/new_clones/Odin/Odin' &
git clone https://github.com/DanielGavin/ols '/storage/nvme5/new_clones/Odin/ols' &
git clone https://github.com/colrdavidson/spall-web '/storage/nvme5/new_clones/Odin/spall-web' &
git clone https://github.com/odin-lang/examples '/storage/nvme5/new_clones/Odin/examples' &
git clone https://github.com/jakubtomsu/dungeon-of-quake '/storage/nvme5/new_clones/Odin/dungeon-of-quake' &
git clone https://github.com/oskarnp/odin-tracy '/storage/nvme5/new_clones/Odin/odin-tracy' &
git clone https://github.com/gingerBill/blaise '/storage/nvme5/new_clones/Odin/blaise' &
git clone https://github.com/jakubtomsu/odin-steamworks '/storage/nvme5/new_clones/Odin/odin-steamworks' &
git clone https://github.com/ThisDevDane/odin-imgui '/storage/nvme5/new_clones/Odin/odin-imgui' &
git clone https://github.com/JoshuaManton/workbench '/storage/nvme5/new_clones/Odin/workbench' &
git clone https://github.com/Skytrias/todool '/storage/nvme5/new_clones/Odin/todool' &
git clone https://github.com/kcvinker/Winforms '/storage/nvme5/new_clones/Odin/Winforms' &
git clone https://github.com/NoahR02/odin-ecs '/storage/nvme5/new_clones/Odin/odin-ecs' &
git clone https://github.com/Breush/odin-binding-generator '/storage/nvme5/new_clones/Odin/odin-binding-generator' &
git clone https://github.com/Akselmo/artificial-rage '/storage/nvme5/new_clones/Odin/artificial-rage' &
git clone https://github.com/mattt-b/odin-mode '/storage/nvme5/new_clones/Odin/odin-mode' &
git clone https://github.com/patrickodacre/odin-space-shooter '/storage/nvme5/new_clones/Odin/odin-space-shooter' &
git clone https://github.com/bg-thompson/OpenGL-Tutorials-In-Odin '/storage/nvme5/new_clones/Odin/OpenGL-Tutorials-In-Odin' &
git clone https://github.com/colbyhall/newport_odin '/storage/nvme5/new_clones/Odin/newport_odin' &
git clone https://github.com/oskarnp/microui-odin '/storage/nvme5/new_clones/Odin/microui-odin' &
git clone https://github.com/Skytrias/odin-sqlite '/storage/nvme5/new_clones/Odin/odin-sqlite' &
git clone https://github.com/DragosPopse/mani '/storage/nvme5/new_clones/Odin/mani' &
git clone https://github.com/vassvik/odin-glfw '/storage/nvme5/new_clones/Odin/odin-glfw' &
git clone https://github.com/JoshuaManton/odin-sdl2 '/storage/nvme5/new_clones/Odin/odin-sdl2' &
git clone https://github.com/vassvik/odin-gl '/storage/nvme5/new_clones/Odin/odin-gl' &
git clone https://github.com/terickson001/bind-odin-port '/storage/nvme5/new_clones/Odin/bind-odin-port' &
git clone https://github.com/UsiTarek/wgpu-odin '/storage/nvme5/new_clones/Odin/wgpu-odin' &
git clone https://github.com/DaseinPhaos/pdb '/storage/nvme5/new_clones/Odin/pdb' &
git clone https://github.com/DanielGavin/odin-vma '/storage/nvme5/new_clones/Odin/odin-vma' &
git clone https://github.com/brainwo/teach-yourself-odin '/storage/nvme5/new_clones/Odin/teach-yourself-odin' &
git clone https://github.com/gingerBill/LD47 '/storage/nvme5/new_clones/Odin/LD47' &
git clone https://github.com/foxik0169/imgui-odin '/storage/nvme5/new_clones/Odin/imgui-odin' &
git clone https://github.com/WalterPlinge/odin-graphics-playground '/storage/nvme5/new_clones/Odin/odin-graphics-playground' &
git clone https://github.com/odin-lang/pkg.odin-lang.org '/storage/nvme5/new_clones/Odin/pkg.odin-lang.org' &
git clone https://github.com/vassvik/odin-gl_font '/storage/nvme5/new_clones/Odin/odin-gl_font' &
git clone https://github.com/DragosPopse/odin-build '/storage/nvme5/new_clones/Odin/odin-build' &
git clone https://github.com/gingerBill/Midgard '/storage/nvme5/new_clones/Odin/Midgard' &
git clone https://github.com/Kelimion/compress-odin '/storage/nvme5/new_clones/Odin/compress-odin' &
git clone https://github.com/OrigamiDev-Pete/odinLox '/storage/nvme5/new_clones/Odin/odinLox' &
git clone https://github.com/ThisDevDane/otime '/storage/nvme5/new_clones/Odin/otime' &
git clone https://github.com/raith-hamzah/odin-flecs '/storage/nvme5/new_clones/Odin/odin-flecs' &
git clone https://github.com/Skytrias/heimdall '/storage/nvme5/new_clones/Odin/heimdall' &
git clone https://github.com/J-Revel/Ether-Engine '/storage/nvme5/new_clones/Odin/Ether-Engine' &
git clone https://github.com/nico-barbas/lily '/storage/nvme5/new_clones/Odin/lily' &
git clone https://github.com/HardcoreCodinOrg/HandmadeRunes '/storage/nvme5/new_clones/Odin/HandmadeRunes' &
git clone https://github.com/desdeux/Odin-TIGR '/storage/nvme5/new_clones/Odin/Odin-TIGR' &
git clone https://github.com/DanielGavin/odin-meshoptimizer '/storage/nvme5/new_clones/Odin/odin-meshoptimizer' &
git clone https://github.com/JoshuaManton/lang '/storage/nvme5/new_clones/Odin/lang' &
git clone https://github.com/Hadopire/adventofcode_2022 '/storage/nvme5/new_clones/Odin/adventofcode_2022' &
git clone https://github.com/englerj/odin-freetype '/storage/nvme5/new_clones/Odin/odin-freetype' &
git clone https://github.com/ThisDevDane/libbrew '/storage/nvme5/new_clones/Odin/libbrew' &
git clone https://github.com/sumofat/odin_cgltf '/storage/nvme5/new_clones/Odin/odin_cgltf' &
git clone https://github.com/contextfreecode/jai-comparisons '/storage/nvme5/new_clones/Odin/jai-comparisons' &
git clone https://github.com/DanB91/Dreamcast-Burner-for-macOS '/storage/nvme5/new_clones/Odin/Dreamcast-Burner-for-macOS' &
git clone https://github.com/ChuuniMage/odin-hot-reload '/storage/nvme5/new_clones/Odin/odin-hot-reload' &
git clone https://github.com/TheMoxyFoxy/avian '/storage/nvme5/new_clones/Odin/avian' &
git clone https://github.com/Platin21/odin-objc '/storage/nvme5/new_clones/Odin/odin-objc' &
git clone https://github.com/TheMoxyFoxy/odin-sprawl '/storage/nvme5/new_clones/Odin/odin-sprawl' &
git clone https://github.com/fendevel/odin-wasapi '/storage/nvme5/new_clones/Odin/odin-wasapi' &
git clone https://github.com/anthony-63/lvo '/storage/nvme5/new_clones/Odin/lvo' &
git clone https://github.com/thePHTest/odin-physac '/storage/nvme5/new_clones/Odin/odin-physac' &
git clone https://github.com/patrickodacre/sdl2-odin-examples '/storage/nvme5/new_clones/Odin/sdl2-odin-examples' &
git clone https://github.com/DrProfesor/odin-dx '/storage/nvme5/new_clones/Odin/odin-dx' &
git clone https://github.com/gingerBill/odin-sdl2 '/storage/nvme5/new_clones/Odin/odin-sdl2' &
git clone https://github.com/ThisDevDane/agitclient '/storage/nvme5/new_clones/Odin/agitclient' &
git clone https://github.com/beastmatser/cli '/storage/nvme5/new_clones/Odin/cli' &
git clone https://github.com/terickson001/odin-bindings '/storage/nvme5/new_clones/Odin/odin-bindings' &
git clone https://github.com/jockus/odin-portaudio '/storage/nvme5/new_clones/Odin/odin-portaudio' &
git clone https://github.com/renehsz/odin-miniz '/storage/nvme5/new_clones/Odin/odin-miniz' &
