#!/bin/bash

git clone https://github.com/chinnonsantos/sql-paises-estados-cidades '/storage/nvme5/new_clones/PLSQL/sql-paises-estados-cidades' &
git clone https://github.com/mortenbra/alexandria-plsql-utils '/storage/nvme5/new_clones/PLSQL/alexandria-plsql-utils' &
git clone https://github.com/oracle-samples/db-sample-schemas '/storage/nvme5/new_clones/PLSQL/db-sample-schemas' &
git clone https://github.com/tanelpoder/tpt-oracle '/storage/nvme5/new_clones/PLSQL/tpt-oracle' &
git clone https://github.com/statickidz/TemarioDAW '/storage/nvme5/new_clones/PLSQL/TemarioDAW' &
git clone https://github.com/utPLSQL/utPLSQL '/storage/nvme5/new_clones/PLSQL/utPLSQL' &
git clone https://github.com/bgkatz/3phase_integrated '/storage/nvme5/new_clones/PLSQL/3phase_integrated' &
git clone https://github.com/pljson/pljson '/storage/nvme5/new_clones/PLSQL/pljson' &
git clone https://github.com/Sythenz/UE4Minimal '/storage/nvme5/new_clones/PLSQL/UE4Minimal' &
git clone https://github.com/cocos/cocos-example-dark-slash '/storage/nvme5/new_clones/PLSQL/cocos-example-dark-slash' &
git clone https://github.com/TexanInParis/Effective-SQL '/storage/nvme5/new_clones/PLSQL/Effective-SQL' &
git clone https://github.com/OraOpenSource/oos-utils '/storage/nvme5/new_clones/PLSQL/oos-utils' &
git clone https://github.com/bwack/Versa64Cart '/storage/nvme5/new_clones/PLSQL/Versa64Cart' &
git clone https://github.com/jkstill/oracle-script-lib '/storage/nvme5/new_clones/PLSQL/oracle-script-lib' &
git clone https://github.com/socratica/sql '/storage/nvme5/new_clones/PLSQL/sql' &
git clone https://github.com/ScalefreeCOM/datavault4dbt '/storage/nvme5/new_clones/PLSQL/datavault4dbt' &
git clone https://github.com/oracle/analytical-sql-examples '/storage/nvme5/new_clones/PLSQL/analytical-sql-examples' &
git clone https://github.com/sqldb360/sqldb360 '/storage/nvme5/new_clones/PLSQL/sqldb360' &
git clone https://github.com/liangjingbin99/shouhuo '/storage/nvme5/new_clones/PLSQL/shouhuo' &
git clone https://github.com/OraOpenSource/OXAR '/storage/nvme5/new_clones/PLSQL/OXAR' &
git clone https://github.com/jonrainier/DayZ-Private-Server '/storage/nvme5/new_clones/PLSQL/DayZ-Private-Server' &
git clone https://github.com/carlos-sierra/cscripts '/storage/nvme5/new_clones/PLSQL/cscripts' &
git clone https://github.com/alto-io/decentralized-game-template '/storage/nvme5/new_clones/PLSQL/decentralized-game-template' &
git clone https://github.com/godweiyang/chatbot '/storage/nvme5/new_clones/PLSQL/chatbot' &
git clone https://github.com/srikanthpragada/plsql '/storage/nvme5/new_clones/PLSQL/plsql' &
git clone https://github.com/Shayshez/EuroScope '/storage/nvme5/new_clones/PLSQL/EuroScope' &
git clone https://github.com/Dani3lSun/apex-plugin-dropzone '/storage/nvme5/new_clones/PLSQL/apex-plugin-dropzone' &
git clone https://github.com/jprjr/internet-radio-streams '/storage/nvme5/new_clones/PLSQL/internet-radio-streams' &
git clone https://github.com/khailey-zz/ashmasters '/storage/nvme5/new_clones/PLSQL/ashmasters' &
git clone https://github.com/themosis/bookstore '/storage/nvme5/new_clones/PLSQL/bookstore' &
git clone https://github.com/NorbertKrupa/vertica-kit '/storage/nvme5/new_clones/PLSQL/vertica-kit' &
git clone https://github.com/deltaDNA/sql-cookbook '/storage/nvme5/new_clones/PLSQL/sql-cookbook' &
git clone https://github.com/Adaxry/GCDT '/storage/nvme5/new_clones/PLSQL/GCDT' &
git clone https://github.com/ApexSQL/Article-scripts '/storage/nvme5/new_clones/PLSQL/Article-scripts' &
git clone https://github.com/patilankita79/Airport-Management-System-Database-Design '/storage/nvme5/new_clones/PLSQL/Airport-Management-System-Database-Design' &
git clone https://github.com/mauropagano/sqld360 '/storage/nvme5/new_clones/PLSQL/sqld360' &
git clone https://github.com/jkairys/growatt-esp8266 '/storage/nvme5/new_clones/PLSQL/growatt-esp8266' &
git clone https://github.com/osalvador/tePLSQL '/storage/nvme5/new_clones/PLSQL/tePLSQL' &
git clone https://github.com/SolariusScorch/XComFiles '/storage/nvme5/new_clones/PLSQL/XComFiles' &
git clone https://github.com/hyee/dbcli '/storage/nvme5/new_clones/PLSQL/dbcli' &
git clone https://github.com/kicksat/sprite '/storage/nvme5/new_clones/PLSQL/sprite' &
git clone https://github.com/tin-robot/RTMP-Playlist '/storage/nvme5/new_clones/PLSQL/RTMP-Playlist' &
git clone https://github.com/McRange/Material-Kanban-Board '/storage/nvme5/new_clones/PLSQL/Material-Kanban-Board' &
git clone https://github.com/antonscheffer/as_sftp '/storage/nvme5/new_clones/PLSQL/as_sftp' &
git clone https://github.com/ReneNyffenegger/oracle-patterns '/storage/nvme5/new_clones/PLSQL/oracle-patterns' &
git clone https://github.com/bigsinger/Farm '/storage/nvme5/new_clones/PLSQL/Farm' &
git clone https://github.com/Enginatics/Oracle-EBS-SQL '/storage/nvme5/new_clones/PLSQL/Oracle-EBS-SQL' &
git clone https://github.com/cartershanklin/hive-scd-examples '/storage/nvme5/new_clones/PLSQL/hive-scd-examples' &
git clone https://github.com/Lexpartizan/Go_MakeHuman_dot '/storage/nvme5/new_clones/PLSQL/Go_MakeHuman_dot' &
git clone https://github.com/zorantica/plsql-qr-code '/storage/nvme5/new_clones/PLSQL/plsql-qr-code' &
git clone https://github.com/connormcd/audit_utility '/storage/nvme5/new_clones/PLSQL/audit_utility' &
git clone https://github.com/MisterHW/LEDCard '/storage/nvme5/new_clones/PLSQL/LEDCard' &
git clone https://github.com/Apress/practical-oracle-sql '/storage/nvme5/new_clones/PLSQL/practical-oracle-sql' &
git clone https://github.com/OraMUC/table-api-generator '/storage/nvme5/new_clones/PLSQL/table-api-generator' &
git clone https://github.com/doberkofler/PLSQL-JSON '/storage/nvme5/new_clones/PLSQL/PLSQL-JSON' &
git clone https://github.com/gmgyan/Bank-Database-Design_MS-SQL '/storage/nvme5/new_clones/PLSQL/Bank-Database-Design_MS-SQL' &
git clone https://github.com/connormcd/misc-scripts '/storage/nvme5/new_clones/PLSQL/misc-scripts' &
git clone https://github.com/radar/railsbot '/storage/nvme5/new_clones/PLSQL/railsbot' &
git clone https://github.com/pioro/orasash '/storage/nvme5/new_clones/PLSQL/orasash' &
git clone https://github.com/mbleron/ExcelTable '/storage/nvme5/new_clones/PLSQL/ExcelTable' &
git clone https://github.com/mbleron/ExcelGen '/storage/nvme5/new_clones/PLSQL/ExcelGen' &
git clone https://github.com/CodeAndWeb/phaser-sprite-sheet-example '/storage/nvme5/new_clones/PLSQL/phaser-sprite-sheet-example' &
git clone https://github.com/Pilooz/pl_fpdf '/storage/nvme5/new_clones/PLSQL/pl_fpdf' &
git clone https://github.com/esprfid/esp-rfid-relay-board '/storage/nvme5/new_clones/PLSQL/esp-rfid-relay-board' &
git clone https://github.com/mennooo/orclapex-modal-lov '/storage/nvme5/new_clones/PLSQL/orclapex-modal-lov' &
git clone https://github.com/JasonBenn/nips-scraper '/storage/nvme5/new_clones/PLSQL/nips-scraper' &
git clone https://github.com/denglt/oracleMonitor '/storage/nvme5/new_clones/PLSQL/oracleMonitor' &
git clone https://github.com/dursunkoc/kafka_connect_sample '/storage/nvme5/new_clones/PLSQL/kafka_connect_sample' &
git clone https://github.com/smart4solutions/apex_oauth '/storage/nvme5/new_clones/PLSQL/apex_oauth' &
git clone https://github.com/MarisElsins/TOOLS '/storage/nvme5/new_clones/PLSQL/TOOLS' &
git clone https://github.com/zorantica/plsql-word '/storage/nvme5/new_clones/PLSQL/plsql-word' &
git clone https://github.com/dbsid/moats_rac '/storage/nvme5/new_clones/PLSQL/moats_rac' &
git clone https://github.com/randypitcherii/cloud_cost_monitoring '/storage/nvme5/new_clones/PLSQL/cloud_cost_monitoring' &
git clone https://github.com/chenhuang-learn/ftrl '/storage/nvme5/new_clones/PLSQL/ftrl' &
git clone https://github.com/cmoore-sp/plsql-aws-s3 '/storage/nvme5/new_clones/PLSQL/plsql-aws-s3' &
git clone https://github.com/kerbelp/redshift-utils '/storage/nvme5/new_clones/PLSQL/redshift-utils' &
git clone https://github.com/Dani3lSun/apex-websocket-notify-bundle '/storage/nvme5/new_clones/PLSQL/apex-websocket-notify-bundle' &
git clone https://github.com/PhilippSalvisberg/plscope-utils '/storage/nvme5/new_clones/PLSQL/plscope-utils' &
git clone https://github.com/Study4/study4love-2018 '/storage/nvme5/new_clones/PLSQL/study4love-2018' &
git clone https://github.com/gilbutITbook/006696 '/storage/nvme5/new_clones/PLSQL/006696' &
git clone https://github.com/ReneNyffenegger/oracle_scriptlets '/storage/nvme5/new_clones/PLSQL/oracle_scriptlets' &
git clone https://github.com/oracle-developer/moats '/storage/nvme5/new_clones/PLSQL/moats' &
git clone https://github.com/Apress/exp-oracle-db-architecture '/storage/nvme5/new_clones/PLSQL/exp-oracle-db-architecture' &
git clone https://github.com/nasa/NPSS-Power-System-Library '/storage/nvme5/new_clones/PLSQL/NPSS-Power-System-Library' &
git clone https://github.com/oracle/dw-vldb-samples '/storage/nvme5/new_clones/PLSQL/dw-vldb-samples' &
git clone https://github.com/helena-project/imix '/storage/nvme5/new_clones/PLSQL/imix' &
git clone https://github.com/zhanghenry/Trust_DWBI '/storage/nvme5/new_clones/PLSQL/Trust_DWBI' &
git clone https://github.com/CodeAndWeb/uikit-sprite-sheet-example '/storage/nvme5/new_clones/PLSQL/uikit-sprite-sheet-example' &
git clone https://github.com/gameDNAstudio/Crashlytics '/storage/nvme5/new_clones/PLSQL/Crashlytics' &
git clone https://github.com/exosports/BART '/storage/nvme5/new_clones/PLSQL/BART' &
git clone https://github.com/jeffreykemp/mailgun-plsql-api '/storage/nvme5/new_clones/PLSQL/mailgun-plsql-api' &
git clone https://github.com/exercism/plsql '/storage/nvme5/new_clones/PLSQL/plsql' &
git clone https://github.com/CodeAndWeb/spritekit-objc-sprite-sheet-example '/storage/nvme5/new_clones/PLSQL/spritekit-objc-sprite-sheet-example' &
git clone https://github.com/Dani3lSun/apex-plugin-templates '/storage/nvme5/new_clones/PLSQL/apex-plugin-templates' &
git clone https://github.com/Evdlaar/sp_WhatsupQueryStore '/storage/nvme5/new_clones/PLSQL/sp_WhatsupQueryStore' &
git clone https://github.com/iusoltsev/sqlplus '/storage/nvme5/new_clones/PLSQL/sqlplus' &
git clone https://github.com/antonscheffer/as_crypto '/storage/nvme5/new_clones/PLSQL/as_crypto' &
git clone https://github.com/meob/MySAT '/storage/nvme5/new_clones/PLSQL/MySAT' &
git clone https://github.com/FranckPachot/scripts '/storage/nvme5/new_clones/PLSQL/scripts' &
git clone https://github.com/windwiny/Oracle-DBA-tips-scripts '/storage/nvme5/new_clones/PLSQL/Oracle-DBA-tips-scripts' &
git clone https://github.com/Holic75/Baldurs-gate-dnd-3.5 '/storage/nvme5/new_clones/PLSQL/Baldurs-gate-dnd-3.5' &
git clone https://github.com/exasol/database-migration '/storage/nvme5/new_clones/PLSQL/database-migration' &
git clone https://github.com/antonscheffer/as_barcode '/storage/nvme5/new_clones/PLSQL/as_barcode' &
git clone https://github.com/SRKabir/Rapid_FloodModelling_CNN '/storage/nvme5/new_clones/PLSQL/Rapid_FloodModelling_CNN' &
git clone https://github.com/mortenbra/apex-plugins '/storage/nvme5/new_clones/PLSQL/apex-plugins' &
git clone https://github.com/anshul1004/AmazonDatabaseDesign '/storage/nvme5/new_clones/PLSQL/AmazonDatabaseDesign' &
git clone https://github.com/utPLSQL/utPLSQL-demo-project '/storage/nvme5/new_clones/PLSQL/utPLSQL-demo-project' &
git clone https://github.com/SeYoungLee/oredis '/storage/nvme5/new_clones/PLSQL/oredis' &
git clone https://github.com/vincentmorneau/oracle-rwd-email-template-api '/storage/nvme5/new_clones/PLSQL/oracle-rwd-email-template-api' &
git clone https://github.com/oradbsec/AskTomDBSecurity '/storage/nvme5/new_clones/PLSQL/AskTomDBSecurity' &
git clone https://github.com/jesterret/DBDPakTrack '/storage/nvme5/new_clones/PLSQL/DBDPakTrack' &
git clone https://github.com/abdulirfan3/Oracle_SQL_Scripts '/storage/nvme5/new_clones/PLSQL/Oracle_SQL_Scripts' &
git clone https://github.com/vyper/fonetica-sql '/storage/nvme5/new_clones/PLSQL/fonetica-sql' &
git clone https://github.com/ogobrecht/plex '/storage/nvme5/new_clones/PLSQL/plex' &
git clone https://github.com/BelaPlatform/bela-hardware '/storage/nvme5/new_clones/PLSQL/bela-hardware' &
git clone https://github.com/j-sieben/PIT '/storage/nvme5/new_clones/PLSQL/PIT' &
git clone https://github.com/pmcfadin/killrvideo-sample-schema '/storage/nvme5/new_clones/PLSQL/killrvideo-sample-schema' &
git clone https://github.com/oracle-developer/xplan '/storage/nvme5/new_clones/PLSQL/xplan' &
git clone https://github.com/aws-samples/amazon-redshift-query-patterns-and-optimizations '/storage/nvme5/new_clones/PLSQL/amazon-redshift-query-patterns-and-optimizations' &
git clone https://github.com/juancondorijara/Cursores_PL-SQL '/storage/nvme5/new_clones/PLSQL/Cursores_PL-SQL' &
git clone https://github.com/jariolaine/apex-blog '/storage/nvme5/new_clones/PLSQL/apex-blog' &
git clone https://github.com/ogobrecht/d3-force-apex-plugin '/storage/nvme5/new_clones/PLSQL/d3-force-apex-plugin' &
git clone https://github.com/osalvador/tapiGen2 '/storage/nvme5/new_clones/PLSQL/tapiGen2' &
git clone https://github.com/ogobrecht/console '/storage/nvme5/new_clones/PLSQL/console' &
git clone https://github.com/ourcade/phaser3-typescript-examples '/storage/nvme5/new_clones/PLSQL/phaser3-typescript-examples' &
git clone https://github.com/ProOracleSQL/space '/storage/nvme5/new_clones/PLSQL/space' &
git clone https://github.com/ljcan/Hive_Project '/storage/nvme5/new_clones/PLSQL/Hive_Project' &
git clone https://github.com/arthur-vieira/sqlzoo '/storage/nvme5/new_clones/PLSQL/sqlzoo' &
git clone https://github.com/RonnyWeiss/Material-Dashboard-Cards-as-HTML-or-for-Apex '/storage/nvme5/new_clones/PLSQL/Material-Dashboard-Cards-as-HTML-or-for-Apex' &
git clone https://github.com/marcelmotta/IMSports-ETL '/storage/nvme5/new_clones/PLSQL/IMSports-ETL' &
git clone https://github.com/NikoNeugebauer/MOSL '/storage/nvme5/new_clones/PLSQL/MOSL' &
git clone https://github.com/morten-egan/jwt_ninja '/storage/nvme5/new_clones/PLSQL/jwt_ninja' &
git clone https://github.com/searceinc/RStoolKit '/storage/nvme5/new_clones/PLSQL/RStoolKit' &
git clone https://github.com/CodeAndWeb/phaser2-sprite-sheet-example '/storage/nvme5/new_clones/PLSQL/phaser2-sprite-sheet-example' &
git clone https://github.com/Dani3lSun/apex-plugin-apextooltip '/storage/nvme5/new_clones/PLSQL/apex-plugin-apextooltip' &
git clone https://github.com/CodeAndWeb/spritekit-sprite-sheet-example '/storage/nvme5/new_clones/PLSQL/spritekit-sprite-sheet-example' &
git clone https://github.com/dfhawthorne/Data_Model_Resource_Book '/storage/nvme5/new_clones/PLSQL/Data_Model_Resource_Book' &
git clone https://github.com/vincentmorneau/oracle-geo-data '/storage/nvme5/new_clones/PLSQL/oracle-geo-data' &
git clone https://github.com/GroovySunday/doit-oracle '/storage/nvme5/new_clones/PLSQL/doit-oracle' &
git clone https://github.com/1newstar/Oracle '/storage/nvme5/new_clones/PLSQL/Oracle' &
git clone https://github.com/sko71/hands-on-with-redshift '/storage/nvme5/new_clones/PLSQL/hands-on-with-redshift' &
git clone https://github.com/Jinglin-LI/SQL-Query '/storage/nvme5/new_clones/PLSQL/SQL-Query' &
git clone https://github.com/OraOpenSource/apex-plugin-clob-load '/storage/nvme5/new_clones/PLSQL/apex-plugin-clob-load' &
git clone https://github.com/ainielse/rando '/storage/nvme5/new_clones/PLSQL/rando' &
git clone https://github.com/jockel71/RGB_HDMI_A600 '/storage/nvme5/new_clones/PLSQL/RGB_HDMI_A600' &
git clone https://github.com/vincentmorneau/apex-theme-boilerplate '/storage/nvme5/new_clones/PLSQL/apex-theme-boilerplate' &
git clone https://github.com/svetka17/make_qr '/storage/nvme5/new_clones/PLSQL/make_qr' &
git clone https://github.com/antonscheffer/as_zip '/storage/nvme5/new_clones/PLSQL/as_zip' &
git clone https://github.com/method5/plsql_lexer '/storage/nvme5/new_clones/PLSQL/plsql_lexer' &
git clone https://github.com/marliesvanderwees/dds-nmt '/storage/nvme5/new_clones/PLSQL/dds-nmt' &
git clone https://github.com/OraOpenSource/language-oracle '/storage/nvme5/new_clones/PLSQL/language-oracle' &
git clone https://github.com/reduardo7/TableTruncate '/storage/nvme5/new_clones/PLSQL/TableTruncate' &
git clone https://github.com/ferreiro/SQL-Oracle-databases '/storage/nvme5/new_clones/PLSQL/SQL-Oracle-databases' &
git clone https://github.com/Apress/expert-sql-server-transactions-and-locking '/storage/nvme5/new_clones/PLSQL/expert-sql-server-transactions-and-locking' &
git clone https://github.com/gregrahn/oracle-scripts '/storage/nvme5/new_clones/PLSQL/oracle-scripts' &
git clone https://github.com/kaushikjnayak/SQL_PLSQL '/storage/nvme5/new_clones/PLSQL/SQL_PLSQL' &
git clone https://github.com/Snowflake-Labs/sfguide-financial-asset-management '/storage/nvme5/new_clones/PLSQL/sfguide-financial-asset-management' &
git clone https://github.com/ThiagoCF05/DeepNLG '/storage/nvme5/new_clones/PLSQL/DeepNLG' &
git clone https://github.com/dhoogfr/toolbox '/storage/nvme5/new_clones/PLSQL/toolbox' &
git clone https://github.com/HowdPrescott/Lob_Over_DBLink '/storage/nvme5/new_clones/PLSQL/Lob_Over_DBLink' &
git clone https://github.com/FritsHoogland/tools '/storage/nvme5/new_clones/PLSQL/tools' &
git clone https://github.com/Dani3lSun/oracle-blockchain '/storage/nvme5/new_clones/PLSQL/oracle-blockchain' &
git clone https://github.com/karlarao/scripts '/storage/nvme5/new_clones/PLSQL/scripts' &
git clone https://github.com/megagonlabs/ebe-dataset '/storage/nvme5/new_clones/PLSQL/ebe-dataset' &
git clone https://github.com/pascallaliberte/built-with-roots '/storage/nvme5/new_clones/PLSQL/built-with-roots' &
git clone https://github.com/LitKnd/BabbyNames '/storage/nvme5/new_clones/PLSQL/BabbyNames' &
git clone https://github.com/jzagelbaum/OlaHallengrenRestoreScript '/storage/nvme5/new_clones/PLSQL/OlaHallengrenRestoreScript' &
git clone https://github.com/RonnyWeiss/APEX-Material-BI-Dashboard '/storage/nvme5/new_clones/PLSQL/APEX-Material-BI-Dashboard' &
git clone https://github.com/serenity-is/common-features '/storage/nvme5/new_clones/PLSQL/common-features' &
git clone https://github.com/khailey-zz/sqltuning '/storage/nvme5/new_clones/PLSQL/sqltuning' &
git clone https://github.com/raminorujov/hackerrank '/storage/nvme5/new_clones/PLSQL/hackerrank' &
git clone https://github.com/openlibraryenvironment/ole '/storage/nvme5/new_clones/PLSQL/ole' &
git clone https://github.com/ci1xgk/Fellowship_Webpage '/storage/nvme5/new_clones/PLSQL/Fellowship_Webpage' &
git clone https://github.com/rajbhatta/PL-SQL '/storage/nvme5/new_clones/PLSQL/PL-SQL' &
git clone https://github.com/CANA-Dan/ParEdit '/storage/nvme5/new_clones/PLSQL/ParEdit' &
git clone https://github.com/vicboma1/streetFighter1 '/storage/nvme5/new_clones/PLSQL/streetFighter1' &
git clone https://github.com/ahliana/SQLTableOrViewToJSON '/storage/nvme5/new_clones/PLSQL/SQLTableOrViewToJSON' &
git clone https://github.com/VTHoop/Oracle-EBS-SQL '/storage/nvme5/new_clones/PLSQL/Oracle-EBS-SQL' &
git clone https://github.com/Apress/exp-oracle-db-architecture-14 '/storage/nvme5/new_clones/PLSQL/exp-oracle-db-architecture-14' &
git clone https://github.com/Qualtagh/OracleDBUtils '/storage/nvme5/new_clones/PLSQL/OracleDBUtils' &
git clone https://github.com/wanghy8166/orabbix '/storage/nvme5/new_clones/PLSQL/orabbix' &
git clone https://github.com/danishpruthi/deceptive-attention '/storage/nvme5/new_clones/PLSQL/deceptive-attention' &
git clone https://github.com/mattdennewitz/retrosheet-sql-queries '/storage/nvme5/new_clones/PLSQL/retrosheet-sql-queries' &
git clone https://github.com/antonscheffer/excel2collections '/storage/nvme5/new_clones/PLSQL/excel2collections' &
git clone https://github.com/ClariFit/apex_plugins '/storage/nvme5/new_clones/PLSQL/apex_plugins' &
git clone https://github.com/Phil-Factor/SQLMetaPhone '/storage/nvme5/new_clones/PLSQL/SQLMetaPhone' &
git clone https://github.com/CloudBreadProject/CloudBread-DB-Install-Script '/storage/nvme5/new_clones/PLSQL/CloudBread-DB-Install-Script' &
git clone https://github.com/SolariusScorch/Final-Mod-Pack '/storage/nvme5/new_clones/PLSQL/Final-Mod-Pack' &
git clone https://github.com/oracle-livelabs/apex '/storage/nvme5/new_clones/PLSQL/apex' &
git clone https://github.com/mauropagano/tunas360 '/storage/nvme5/new_clones/PLSQL/tunas360' &
git clone https://github.com/aykutakin/pkg_table_to_html '/storage/nvme5/new_clones/PLSQL/pkg_table_to_html' &
git clone https://github.com/ftldb/ftldb '/storage/nvme5/new_clones/PLSQL/ftldb' &
git clone https://github.com/revaturelabs/trackforce '/storage/nvme5/new_clones/PLSQL/trackforce' &
git clone https://github.com/jeffreykemp/clicksend-plsql-api '/storage/nvme5/new_clones/PLSQL/clicksend-plsql-api' &
git clone https://github.com/aldocano29/AmandaDocxPrinter '/storage/nvme5/new_clones/PLSQL/AmandaDocxPrinter' &
git clone https://github.com/pig-mesh/nacos-datasource-plugin-oracle '/storage/nvme5/new_clones/PLSQL/nacos-datasource-plugin-oracle' &
git clone https://github.com/Apress/expert-oracle-db-architecture-4e '/storage/nvme5/new_clones/PLSQL/expert-oracle-db-architecture-4e' &
git clone https://github.com/juan-bol/Modelado '/storage/nvme5/new_clones/PLSQL/Modelado' &
git clone https://github.com/ogobrecht/markdown-apex-plugin '/storage/nvme5/new_clones/PLSQL/markdown-apex-plugin' &
git clone https://github.com/vishaldesai/Oracle_Scripts '/storage/nvme5/new_clones/PLSQL/Oracle_Scripts' &
git clone https://github.com/Doag/Forms '/storage/nvme5/new_clones/PLSQL/Forms' &
git clone https://github.com/JQIamo/ad9910-dds '/storage/nvme5/new_clones/PLSQL/ad9910-dds' &
git clone https://github.com/nostradomus/LabTools_100MHz-Differential-Probe '/storage/nvme5/new_clones/PLSQL/LabTools_100MHz-Differential-Probe' &
git clone https://github.com/Apress/beg-oracle-pl-sql '/storage/nvme5/new_clones/PLSQL/beg-oracle-pl-sql' &
git clone https://github.com/NordPerfEngg/OracleDBALite '/storage/nvme5/new_clones/PLSQL/OracleDBALite' &
git clone https://github.com/Dani3lSun/apex-plugin-analytics '/storage/nvme5/new_clones/PLSQL/apex-plugin-analytics' &
git clone https://github.com/kfatkin/Convert_ETF_SMC_HTF_Levels '/storage/nvme5/new_clones/PLSQL/Convert_ETF_SMC_HTF_Levels' &
git clone https://github.com/mgoricki/presentation-apex-18-hidden-features '/storage/nvme5/new_clones/PLSQL/presentation-apex-18-hidden-features' &
git clone https://github.com/mauropagano/pathfinder '/storage/nvme5/new_clones/PLSQL/pathfinder' &
git clone https://github.com/oracle-developer/runstats '/storage/nvme5/new_clones/PLSQL/runstats' &
git clone https://github.com/MarcoAntonini/RepRapLcd4D '/storage/nvme5/new_clones/PLSQL/RepRapLcd4D' &
git clone https://github.com/mt-ag/apex-excel-gateway '/storage/nvme5/new_clones/PLSQL/apex-excel-gateway' &
git clone https://github.com/Pretius/pretius-developer-tool '/storage/nvme5/new_clones/PLSQL/pretius-developer-tool' &
git clone https://github.com/sokolsaiti/as_xlsx '/storage/nvme5/new_clones/PLSQL/as_xlsx' &
git clone https://github.com/franklingjr/oracle-forms-migration '/storage/nvme5/new_clones/PLSQL/oracle-forms-migration' &
git clone https://github.com/mortenbra/quick-plsql '/storage/nvme5/new_clones/PLSQL/quick-plsql' &
git clone https://github.com/connormcd/plugzilla '/storage/nvme5/new_clones/PLSQL/plugzilla' &
git clone https://github.com/davidkurtz/psscripts '/storage/nvme5/new_clones/PLSQL/psscripts' &
git clone https://github.com/Epivaral/sql-table-to-html '/storage/nvme5/new_clones/PLSQL/sql-table-to-html' &
git clone https://github.com/k1aus/parallelsql '/storage/nvme5/new_clones/PLSQL/parallelsql' &
git clone https://github.com/commi235/xlsx_builder '/storage/nvme5/new_clones/PLSQL/xlsx_builder' &
git clone https://github.com/Apress/oracle-core-esntl-internals-for-dbas-devs '/storage/nvme5/new_clones/PLSQL/oracle-core-esntl-internals-for-dbas-devs' &
git clone https://github.com/mbleron/oracle '/storage/nvme5/new_clones/PLSQL/oracle' &
git clone https://github.com/carlos-sierra/eadam '/storage/nvme5/new_clones/PLSQL/eadam' &
git clone https://github.com/Apress/pro-oracle-sql-dev '/storage/nvme5/new_clones/PLSQL/pro-oracle-sql-dev' &
git clone https://github.com/NHSDigital/data-viz-community-of-practice '/storage/nvme5/new_clones/PLSQL/data-viz-community-of-practice' &
git clone https://github.com/ruchi15/e-commerce-website-database-design '/storage/nvme5/new_clones/PLSQL/e-commerce-website-database-design' &
git clone https://github.com/schunt1/ATAF '/storage/nvme5/new_clones/PLSQL/ATAF' &
git clone https://github.com/demasylabs/Point-Of-Sale '/storage/nvme5/new_clones/PLSQL/Point-Of-Sale' &
git clone https://github.com/sbelectronics/z80sbc '/storage/nvme5/new_clones/PLSQL/z80sbc' &
git clone https://github.com/mgoricki/apex-plugin-extend-ig-toolbar '/storage/nvme5/new_clones/PLSQL/apex-plugin-extend-ig-toolbar' &
git clone https://github.com/BrenPatF/sql_demos '/storage/nvme5/new_clones/PLSQL/sql_demos' &
git clone https://github.com/lukelavin/Cluebase '/storage/nvme5/new_clones/PLSQL/Cluebase' &
git clone https://github.com/EgonMadsen/PL-SQL-Chess '/storage/nvme5/new_clones/PLSQL/PL-SQL-Chess' &
git clone https://github.com/maclochlainn/plsql-12c-programming '/storage/nvme5/new_clones/PLSQL/plsql-12c-programming' &
git clone https://github.com/nkarag/oracle_ready2run_scripts '/storage/nvme5/new_clones/PLSQL/oracle_ready2run_scripts' &
git clone https://github.com/pauldzy/DZ_JSON '/storage/nvme5/new_clones/PLSQL/DZ_JSON' &
git clone https://github.com/agebullhu/AgebullDesigner '/storage/nvme5/new_clones/PLSQL/AgebullDesigner' &
git clone https://github.com/tmuth/splunking-oracle '/storage/nvme5/new_clones/PLSQL/splunking-oracle' &
git clone https://github.com/ahmedkhan847/customcms '/storage/nvme5/new_clones/PLSQL/customcms' &
git clone https://github.com/chameleon82/oracle-scripts '/storage/nvme5/new_clones/PLSQL/oracle-scripts' &
git clone https://github.com/bjarteb/oracle-apex-ords '/storage/nvme5/new_clones/PLSQL/oracle-apex-ords' &
git clone https://github.com/j-sieben/FSM '/storage/nvme5/new_clones/PLSQL/FSM' &
git clone https://github.com/zhagan/Synth-Circuits '/storage/nvme5/new_clones/PLSQL/Synth-Circuits' &
git clone https://github.com/nakicam/70-761 '/storage/nvme5/new_clones/PLSQL/70-761' &
git clone https://github.com/phartenfeller/apex-off-grid '/storage/nvme5/new_clones/PLSQL/apex-off-grid' &
git clone https://github.com/jeffreykemp/jk64-plugin-simplemap '/storage/nvme5/new_clones/PLSQL/jk64-plugin-simplemap' &
git clone https://github.com/commi235/APEX_IR_XLSX '/storage/nvme5/new_clones/PLSQL/APEX_IR_XLSX' &
git clone https://github.com/hhudson/mailchimp_plsql_api '/storage/nvme5/new_clones/PLSQL/mailchimp_plsql_api' &
git clone https://github.com/grlicaa/GEN_PDF '/storage/nvme5/new_clones/PLSQL/GEN_PDF' &
git clone https://github.com/fuzziebrain/orclapex-tfa-demo '/storage/nvme5/new_clones/PLSQL/orclapex-tfa-demo' &
git clone https://github.com/jkvetina/CORE '/storage/nvme5/new_clones/PLSQL/CORE' &
git clone https://github.com/OakAcademy/Oracle '/storage/nvme5/new_clones/PLSQL/Oracle' &
git clone https://github.com/krumboeck/oracle-alfresco '/storage/nvme5/new_clones/PLSQL/oracle-alfresco' &
git clone https://github.com/ribafs/assets '/storage/nvme5/new_clones/PLSQL/assets' &
git clone https://github.com/benqmamun/POS-SOFTWARE-Oracle-APEX '/storage/nvme5/new_clones/PLSQL/POS-SOFTWARE-Oracle-APEX' &
git clone https://github.com/cmoore-sp/plsql-markdown-2-html '/storage/nvme5/new_clones/PLSQL/plsql-markdown-2-html' &
git clone https://github.com/OraOpenSource/apex-plugin-templates '/storage/nvme5/new_clones/PLSQL/apex-plugin-templates' &
git clone https://github.com/Testudinate/SQL '/storage/nvme5/new_clones/PLSQL/SQL' &
git clone https://github.com/morten-egan/oraclegit '/storage/nvme5/new_clones/PLSQL/oraclegit' &
git clone https://github.com/oracle-developer/mystats '/storage/nvme5/new_clones/PLSQL/mystats' &
git clone https://github.com/CSHoggard/-gmm_liverpool_2020 '/storage/nvme5/new_clones/PLSQL/-gmm_liverpool_2020' &
git clone https://github.com/avhrst/apex_telegramm '/storage/nvme5/new_clones/PLSQL/apex_telegramm' &
git clone https://github.com/karlarao/run_awr-quickextract '/storage/nvme5/new_clones/PLSQL/run_awr-quickextract' &
git clone https://github.com/windwiny/Oracle-DBA-scripts '/storage/nvme5/new_clones/PLSQL/Oracle-DBA-scripts' &
git clone https://github.com/Apress/secrets-of-oracle-db '/storage/nvme5/new_clones/PLSQL/secrets-of-oracle-db' &
git clone https://github.com/Apress/exp-oracle-sql '/storage/nvme5/new_clones/PLSQL/exp-oracle-sql' &
git clone https://github.com/facebookarchive/NACS '/storage/nvme5/new_clones/PLSQL/NACS' &
git clone https://github.com/Apress/oracle-pl-sql-recipes '/storage/nvme5/new_clones/PLSQL/oracle-pl-sql-recipes' &
git clone https://github.com/arcticmatt/CS121 '/storage/nvme5/new_clones/PLSQL/CS121' &
git clone https://github.com/rimblas/jtlitem '/storage/nvme5/new_clones/PLSQL/jtlitem' &
git clone https://github.com/RonnyWeiss/APEX-How-to-create-a-Region-Chart-Plug-in '/storage/nvme5/new_clones/PLSQL/APEX-How-to-create-a-Region-Chart-Plug-in' &
git clone https://github.com/webcaetano/gulp-texturepacker '/storage/nvme5/new_clones/PLSQL/gulp-texturepacker' &
git clone https://github.com/method5/method4 '/storage/nvme5/new_clones/PLSQL/method4' &
git clone https://github.com/MikhailVAS/Oracle-EBS '/storage/nvme5/new_clones/PLSQL/Oracle-EBS' &
git clone https://github.com/Dani3lSun/apex-plugin-videoplayer '/storage/nvme5/new_clones/PLSQL/apex-plugin-videoplayer' &
git clone https://github.com/jeffreykemp/sample '/storage/nvme5/new_clones/PLSQL/sample' &
git clone https://github.com/dragino/motherboard-hardware '/storage/nvme5/new_clones/PLSQL/motherboard-hardware' &
git clone https://github.com/jkvetina/Kvido '/storage/nvme5/new_clones/PLSQL/Kvido' &
git clone https://github.com/intelligent-agent/replicape '/storage/nvme5/new_clones/PLSQL/replicape' &
git clone https://github.com/CultofRobots/radio-streams '/storage/nvme5/new_clones/PLSQL/radio-streams' &
git clone https://github.com/shabanali-faghani/cascadelete '/storage/nvme5/new_clones/PLSQL/cascadelete' &
git clone https://github.com/andorei/atop-plsql '/storage/nvme5/new_clones/PLSQL/atop-plsql' &
git clone https://github.com/rbawden/Large-contrastive-pronoun-testset-EN-FR '/storage/nvme5/new_clones/PLSQL/Large-contrastive-pronoun-testset-EN-FR' &
git clone https://github.com/insum-labs/apex-plugin-google-places-autocomplete '/storage/nvme5/new_clones/PLSQL/apex-plugin-google-places-autocomplete' &
git clone https://github.com/Apress/dynamic-oracle-perf-analytics '/storage/nvme5/new_clones/PLSQL/dynamic-oracle-perf-analytics' &
git clone https://github.com/mennooo/apex-modular-js '/storage/nvme5/new_clones/PLSQL/apex-modular-js' &
git clone https://github.com/paulzip-dev/Base64 '/storage/nvme5/new_clones/PLSQL/Base64' &
git clone https://github.com/marinfotache/Database-Logic-in-Business-Applications '/storage/nvme5/new_clones/PLSQL/Database-Logic-in-Business-Applications' &
git clone https://github.com/ase2sprkkr/ase2sprkkr '/storage/nvme5/new_clones/PLSQL/ase2sprkkr' &
git clone https://github.com/DeveloperArthur/Programacao-PLSQL '/storage/nvme5/new_clones/PLSQL/Programacao-PLSQL' &
git clone https://github.com/connormcd/instrumentation '/storage/nvme5/new_clones/PLSQL/instrumentation' &
git clone https://github.com/Apress/pro-oracle-sql '/storage/nvme5/new_clones/PLSQL/pro-oracle-sql' &
git clone https://github.com/carlos-sierra/esp_collect '/storage/nvme5/new_clones/PLSQL/esp_collect' &
git clone https://github.com/erisata/ora-gen-ddl '/storage/nvme5/new_clones/PLSQL/ora-gen-ddl' &
git clone https://github.com/tobiasarnhold/svg-in-apex '/storage/nvme5/new_clones/PLSQL/svg-in-apex' &
git clone https://github.com/liuenci/OracleDemo '/storage/nvme5/new_clones/PLSQL/OracleDemo' &
git clone https://github.com/matitaweb/oracle-plsql-logger '/storage/nvme5/new_clones/PLSQL/oracle-plsql-logger' &
git clone https://github.com/mt-ag/quasto '/storage/nvme5/new_clones/PLSQL/quasto' &
git clone https://github.com/oracle-developer/utilities '/storage/nvme5/new_clones/PLSQL/utilities' &
git clone https://github.com/dmateusp/dbt-steampipe '/storage/nvme5/new_clones/PLSQL/dbt-steampipe' &
git clone https://github.com/strongloop/loopback-connector-db2iseries '/storage/nvme5/new_clones/PLSQL/loopback-connector-db2iseries' &
git clone https://github.com/Apress/pro-sql-server-rel-db-design-impl '/storage/nvme5/new_clones/PLSQL/pro-sql-server-rel-db-design-impl' &
git clone https://github.com/prashuk/SQL-Taxi-Management '/storage/nvme5/new_clones/PLSQL/SQL-Taxi-Management' &
git clone https://github.com/grlicaa/D3CollapsibleTreeChart '/storage/nvme5/new_clones/PLSQL/D3CollapsibleTreeChart' &
git clone https://github.com/DougAGault/SQL-and-PLSQL-tools '/storage/nvme5/new_clones/PLSQL/SQL-and-PLSQL-tools' &
git clone https://github.com/gilbutITbook/080202 '/storage/nvme5/new_clones/PLSQL/080202' &
git clone https://github.com/Apress/oracle-db-12c-perf-tuning-recipes '/storage/nvme5/new_clones/PLSQL/oracle-db-12c-perf-tuning-recipes' &
git clone https://github.com/yedincel/How-to-Write-PLSQL '/storage/nvme5/new_clones/PLSQL/How-to-Write-PLSQL' &
git clone https://github.com/rinodrummer/EsameBasiDiDati '/storage/nvme5/new_clones/PLSQL/EsameBasiDiDati' &
git clone https://github.com/Dani3lSun/apex-voice-control '/storage/nvme5/new_clones/PLSQL/apex-voice-control' &
git clone https://github.com/binkley/oracle-plsql-unit-testing '/storage/nvme5/new_clones/PLSQL/oracle-plsql-unit-testing' &
git clone https://github.com/mcmarius/pbd '/storage/nvme5/new_clones/PLSQL/pbd' &
git clone https://github.com/Roenbaeck/tempodim '/storage/nvme5/new_clones/PLSQL/tempodim' &
git clone https://github.com/t3chm4n/plsql-lambda '/storage/nvme5/new_clones/PLSQL/plsql-lambda' &
git clone https://github.com/alangibson/log4plsql '/storage/nvme5/new_clones/PLSQL/log4plsql' &
git clone https://github.com/antonscheffer/APEX2XLSX '/storage/nvme5/new_clones/PLSQL/APEX2XLSX' &
git clone https://github.com/Dual-Life/Devel-PPPort '/storage/nvme5/new_clones/PLSQL/Devel-PPPort' &
git clone https://github.com/yallie/as_zip '/storage/nvme5/new_clones/PLSQL/as_zip' &
git clone https://github.com/riboseinc/dnsconformance '/storage/nvme5/new_clones/PLSQL/dnsconformance' &
git clone https://github.com/zahlio/Gamers-Live '/storage/nvme5/new_clones/PLSQL/Gamers-Live' &
git clone https://github.com/Jpub/PLSQLProgramming '/storage/nvme5/new_clones/PLSQL/PLSQLProgramming' &
git clone https://github.com/morten-egan/promises_ninja '/storage/nvme5/new_clones/PLSQL/promises_ninja' &
git clone https://github.com/kivilev/oracle_dbd '/storage/nvme5/new_clones/PLSQL/oracle_dbd' &
git clone https://github.com/15Galan/asignatura-305 '/storage/nvme5/new_clones/PLSQL/asignatura-305' &
git clone https://github.com/morten-egan/ninja '/storage/nvme5/new_clones/PLSQL/ninja' &
git clone https://github.com/SasankVemana/PS-Portal-Menu-Navigation-Queries '/storage/nvme5/new_clones/PLSQL/PS-Portal-Menu-Navigation-Queries' &
git clone https://github.com/carlos-sierra/meta360 '/storage/nvme5/new_clones/PLSQL/meta360' &
git clone https://github.com/g4bao/23cm-45W-PA '/storage/nvme5/new_clones/PLSQL/23cm-45W-PA' &
git clone https://github.com/lilinkai/CocosCreator-TTKP '/storage/nvme5/new_clones/PLSQL/CocosCreator-TTKP' &
git clone https://github.com/bjut-MrZhang/CadenceLib '/storage/nvme5/new_clones/PLSQL/CadenceLib' &
git clone https://github.com/codetricity/leena2_tutorial '/storage/nvme5/new_clones/PLSQL/leena2_tutorial' &
git clone https://github.com/WaderManasi/TE-DBMSLab-Assignments '/storage/nvme5/new_clones/PLSQL/TE-DBMSLab-Assignments' &
git clone https://github.com/Apress/oracle-exadata-survival-guide '/storage/nvme5/new_clones/PLSQL/oracle-exadata-survival-guide' &
git clone https://github.com/foex-open-source/fos-redirect '/storage/nvme5/new_clones/PLSQL/fos-redirect' &
git clone https://github.com/eddML/core '/storage/nvme5/new_clones/PLSQL/core' &
git clone https://github.com/saikumar92/Database-Design-for-Customer-Loyalty-Management-System '/storage/nvme5/new_clones/PLSQL/Database-Design-for-Customer-Loyalty-Management-System' &
git clone https://github.com/Clarivate-LSPS/tMDataLoader '/storage/nvme5/new_clones/PLSQL/tMDataLoader' &
git clone https://github.com/mgoricki/apex-plugin-advanced-slider '/storage/nvme5/new_clones/PLSQL/apex-plugin-advanced-slider' &
git clone https://github.com/mennooo/orcl-multimedia '/storage/nvme5/new_clones/PLSQL/orcl-multimedia' &
git clone https://github.com/ophelipecamilo/HelpScripts '/storage/nvme5/new_clones/PLSQL/HelpScripts' &
git clone https://github.com/mio-edition/floyds-puzzle '/storage/nvme5/new_clones/PLSQL/floyds-puzzle' &
git clone https://github.com/miktim/AM_FILL '/storage/nvme5/new_clones/PLSQL/AM_FILL' &
git clone https://github.com/noduino/OpenPlug '/storage/nvme5/new_clones/PLSQL/OpenPlug' &
git clone https://github.com/CSLT-THU/CSLT_NMT '/storage/nvme5/new_clones/PLSQL/CSLT_NMT' &
git clone https://github.com/dbarj/OraTOtP '/storage/nvme5/new_clones/PLSQL/OraTOtP' &
git clone https://github.com/ogobrecht/sample-data-sets-for-oracle '/storage/nvme5/new_clones/PLSQL/sample-data-sets-for-oracle' &
git clone https://github.com/kaanozbudak/databaseCourses '/storage/nvme5/new_clones/PLSQL/databaseCourses' &
git clone https://github.com/martindsouza/pres-open-source-apex '/storage/nvme5/new_clones/PLSQL/pres-open-source-apex' &
git clone https://github.com/saeedutsha/Bloodbank-Database-Project- '/storage/nvme5/new_clones/PLSQL/Bloodbank-Database-Project-' &
git clone https://github.com/Abastro/Funcy '/storage/nvme5/new_clones/PLSQL/Funcy' &
git clone https://github.com/CyberDex/ZombieLand '/storage/nvme5/new_clones/PLSQL/ZombieLand' &
git clone https://github.com/Azure-Samples/elastic-jobs-samples '/storage/nvme5/new_clones/PLSQL/elastic-jobs-samples' &
git clone https://github.com/jeffreykemp/jk64-plugin-heatmap '/storage/nvme5/new_clones/PLSQL/jk64-plugin-heatmap' &
git clone https://github.com/Dani3lSun/apex-app-crappybird '/storage/nvme5/new_clones/PLSQL/apex-app-crappybird' &
git clone https://github.com/AlbertCQY/scripts '/storage/nvme5/new_clones/PLSQL/scripts' &
git clone https://github.com/Hobbes74/XCOM-Terrain-Pack '/storage/nvme5/new_clones/PLSQL/XCOM-Terrain-Pack' &
git clone https://github.com/kayla-louise/SQL-City-Jail-Database '/storage/nvme5/new_clones/PLSQL/SQL-City-Jail-Database' &
git clone https://github.com/domgiles/ORDS_Example '/storage/nvme5/new_clones/PLSQL/ORDS_Example' &
git clone https://github.com/Gui-Lima/ccGradSubjects '/storage/nvme5/new_clones/PLSQL/ccGradSubjects' &
git clone https://github.com/EckisWelt/WhereScape '/storage/nvme5/new_clones/PLSQL/WhereScape' &
git clone https://github.com/soccermetrics/marcotti-summary '/storage/nvme5/new_clones/PLSQL/marcotti-summary' &
git clone https://github.com/gt-health/omop_etl_public '/storage/nvme5/new_clones/PLSQL/omop_etl_public' &
git clone https://github.com/mbleron/JSONUtilities '/storage/nvme5/new_clones/PLSQL/JSONUtilities' &
git clone https://github.com/ryancor/HWT-Verilog '/storage/nvme5/new_clones/PLSQL/HWT-Verilog' &
git clone https://github.com/viniciusribeiroti/sankhya '/storage/nvme5/new_clones/PLSQL/sankhya' &
git clone https://github.com/BeatAroundTheBuscher/ROSIGMA '/storage/nvme5/new_clones/PLSQL/ROSIGMA' &
git clone https://github.com/Filipstrozik/oracle '/storage/nvme5/new_clones/PLSQL/oracle' &
git clone https://github.com/mbleron/PLCalc '/storage/nvme5/new_clones/PLSQL/PLCalc' &
git clone https://github.com/exosports/MARGE '/storage/nvme5/new_clones/PLSQL/MARGE' &
git clone https://github.com/alexnuijten/loggerutil '/storage/nvme5/new_clones/PLSQL/loggerutil' &
git clone https://github.com/edugca/xlDESSAZ '/storage/nvme5/new_clones/PLSQL/xlDESSAZ' &
git clone https://github.com/CodeAndWeb/phaser3-matterjs-physics-demo '/storage/nvme5/new_clones/PLSQL/phaser3-matterjs-physics-demo' &
git clone https://github.com/antonscheffer/Excel2APEX '/storage/nvme5/new_clones/PLSQL/Excel2APEX' &
git clone https://github.com/areuser/plsql-commons '/storage/nvme5/new_clones/PLSQL/plsql-commons' &
git clone https://github.com/SkillBuilders/session-timeout '/storage/nvme5/new_clones/PLSQL/session-timeout' &
git clone https://github.com/jiangnanboy/chatbot_chinese '/storage/nvme5/new_clones/PLSQL/chatbot_chinese' &
git clone https://github.com/ziaa/SqlPersianDateDimension '/storage/nvme5/new_clones/PLSQL/SqlPersianDateDimension' &
git clone https://github.com/csbence/searkt '/storage/nvme5/new_clones/PLSQL/searkt' &
git clone https://github.com/rafael-trevisan/apex-plugin-peekaboo '/storage/nvme5/new_clones/PLSQL/apex-plugin-peekaboo' &
git clone https://github.com/bparlayan/oracle '/storage/nvme5/new_clones/PLSQL/oracle' &
git clone https://github.com/neutmute/ScriptDiagram '/storage/nvme5/new_clones/PLSQL/ScriptDiagram' &
git clone https://github.com/Ashwanikumarkashyap/amazon-database-system-plsql '/storage/nvme5/new_clones/PLSQL/amazon-database-system-plsql' &
git clone https://github.com/stefansiegl/docker-introscope '/storage/nvme5/new_clones/PLSQL/docker-introscope' &
git clone https://github.com/Apress/exp-pl-sql-practices '/storage/nvme5/new_clones/PLSQL/exp-pl-sql-practices' &
git clone https://github.com/sbelectronics/ps2-tandy '/storage/nvme5/new_clones/PLSQL/ps2-tandy' &
git clone https://github.com/CodeAndWeb/Phaser3-Lighting '/storage/nvme5/new_clones/PLSQL/Phaser3-Lighting' &
git clone https://github.com/rimblas/apex-report-templates-demo '/storage/nvme5/new_clones/PLSQL/apex-report-templates-demo' &
git clone https://github.com/Cyberster/Wipro-Training-JDBC---Assignments-for-Using-CallableStatement-and-Transactions '/storage/nvme5/new_clones/PLSQL/Wipro-Training-JDBC---Assignments-for-Using-CallableStatement-and-Transactions' &
git clone https://github.com/foex-open-source/fos-interactive-grid-process-rows '/storage/nvme5/new_clones/PLSQL/fos-interactive-grid-process-rows' &
git clone https://github.com/hychen39/angular_teach_notes '/storage/nvme5/new_clones/PLSQL/angular_teach_notes' &
git clone https://github.com/rovshan-b/oraexp '/storage/nvme5/new_clones/PLSQL/oraexp' &
git clone https://github.com/planetapex/apex-plugin-dynamicDateTimePicker '/storage/nvme5/new_clones/PLSQL/apex-plugin-dynamicDateTimePicker' &
git clone https://github.com/wtPLSQL/wtPLSQL '/storage/nvme5/new_clones/PLSQL/wtPLSQL' &
git clone https://github.com/trifangrobert/Database-Project '/storage/nvme5/new_clones/PLSQL/Database-Project' &
git clone https://github.com/dtseiler/sql '/storage/nvme5/new_clones/PLSQL/sql' &
git clone https://github.com/chenhuang-learn/adPredictor '/storage/nvme5/new_clones/PLSQL/adPredictor' &
git clone https://github.com/rimblas/apex-freeze-col-headers '/storage/nvme5/new_clones/PLSQL/apex-freeze-col-headers' &
git clone https://github.com/chandankr7/DBA-Scripts '/storage/nvme5/new_clones/PLSQL/DBA-Scripts' &
git clone https://github.com/Apress/pro-oracle-sql-13 '/storage/nvme5/new_clones/PLSQL/pro-oracle-sql-13' &
git clone https://github.com/palladiumkenya/kenyaEMR-ETL '/storage/nvme5/new_clones/PLSQL/kenyaEMR-ETL' &
git clone https://github.com/Apress/rman-recipes-for-oracle-db-12c '/storage/nvme5/new_clones/PLSQL/rman-recipes-for-oracle-db-12c' &
git clone https://github.com/Apress/oracle-sql-revealed '/storage/nvme5/new_clones/PLSQL/oracle-sql-revealed' &
git clone https://github.com/GoogleCloudPlatform/datastream-diagnostic-toolkit '/storage/nvme5/new_clones/PLSQL/datastream-diagnostic-toolkit' &
git clone https://github.com/KqSMea8/program_world '/storage/nvme5/new_clones/PLSQL/program_world' &
git clone https://github.com/wakamsha/wordpress_docker-compose '/storage/nvme5/new_clones/PLSQL/wordpress_docker-compose' &
git clone https://github.com/OraOpenSource/apex-text-messages '/storage/nvme5/new_clones/PLSQL/apex-text-messages' &
git clone https://github.com/jeffreykemp/jk64-plugin-passwordstrength '/storage/nvme5/new_clones/PLSQL/jk64-plugin-passwordstrength' &
git clone https://github.com/haoyuan336/shouhuhuahua-bilibili '/storage/nvme5/new_clones/PLSQL/shouhuhuahua-bilibili' &
git clone https://github.com/darklordgrep/Mapbits '/storage/nvme5/new_clones/PLSQL/Mapbits' &
git clone https://github.com/Apress/programmer-guide-to-sql '/storage/nvme5/new_clones/PLSQL/programmer-guide-to-sql' &
git clone https://github.com/mikesmithers/crudo '/storage/nvme5/new_clones/PLSQL/crudo' &
git clone https://github.com/CSHoggard/-cologne_workshop '/storage/nvme5/new_clones/PLSQL/-cologne_workshop' &
git clone https://github.com/cyberkhalil/University_Data_Base '/storage/nvme5/new_clones/PLSQL/University_Data_Base' &
git clone https://github.com/foex-open-source/fos-clientside-condition '/storage/nvme5/new_clones/PLSQL/fos-clientside-condition' &
git clone https://github.com/nowshad7/SalaryManagementSystem '/storage/nvme5/new_clones/PLSQL/SalaryManagementSystem' &
git clone https://github.com/benruijl/forcer '/storage/nvme5/new_clones/PLSQL/forcer' &
git clone https://github.com/nna01/PL_SQL_Project '/storage/nvme5/new_clones/PLSQL/PL_SQL_Project' &
git clone https://github.com/qiwi/postgres_partitioning '/storage/nvme5/new_clones/PLSQL/postgres_partitioning' &
git clone https://github.com/twcamper/grammar-cards '/storage/nvme5/new_clones/PLSQL/grammar-cards' &
git clone https://github.com/foobarbaz-pl/apex-plugin-floating-scrollbar '/storage/nvme5/new_clones/PLSQL/apex-plugin-floating-scrollbar' &
git clone https://github.com/cichlidx/ronco_et_al '/storage/nvme5/new_clones/PLSQL/ronco_et_al' &
git clone https://github.com/java4less/ApexPDFRenderer '/storage/nvme5/new_clones/PLSQL/ApexPDFRenderer' &
git clone https://github.com/boyddensmore/Maximo-Oracle-SQL-Public '/storage/nvme5/new_clones/PLSQL/Maximo-Oracle-SQL-Public' &
git clone https://github.com/alistairuk/CultureCode-Data '/storage/nvme5/new_clones/PLSQL/CultureCode-Data' &
git clone https://github.com/araczkowski/MultiRangeSlider '/storage/nvme5/new_clones/PLSQL/MultiRangeSlider' &
git clone https://github.com/hanspo/PTF '/storage/nvme5/new_clones/PLSQL/PTF' &
git clone https://github.com/lucatume/cmb2-tad-fields '/storage/nvme5/new_clones/PLSQL/cmb2-tad-fields' &
git clone https://github.com/foex-open-source/fos-download-files-da '/storage/nvme5/new_clones/PLSQL/fos-download-files-da' &
git clone https://github.com/BianZhongMing/SQL-Server-monitoring-and-maintenance '/storage/nvme5/new_clones/PLSQL/SQL-Server-monitoring-and-maintenance' &
git clone https://github.com/DavidDeLille/writeups '/storage/nvme5/new_clones/PLSQL/writeups' &
git clone https://github.com/papayaah/treasurehunt '/storage/nvme5/new_clones/PLSQL/treasurehunt' &
git clone https://github.com/RonnyWeiss/APEX-Oracle-and-OSM-Maps '/storage/nvme5/new_clones/PLSQL/APEX-Oracle-and-OSM-Maps' &
git clone https://github.com/mortenbra/plsql-sample-code '/storage/nvme5/new_clones/PLSQL/plsql-sample-code' &
git clone https://github.com/OpenWebinarsNet/Curso-PL-SQL-OpenWebinars '/storage/nvme5/new_clones/PLSQL/Curso-PL-SQL-OpenWebinars' &
git clone https://github.com/samuelrponce/Bases-de-datos-2 '/storage/nvme5/new_clones/PLSQL/Bases-de-datos-2' &
git clone https://github.com/godwinleo/OracleDatabase '/storage/nvme5/new_clones/PLSQL/OracleDatabase' &
git clone https://github.com/hali/Performance-data-processing '/storage/nvme5/new_clones/PLSQL/Performance-data-processing' &
git clone https://github.com/casuistry/ieml '/storage/nvme5/new_clones/PLSQL/ieml' &
git clone https://github.com/abesto/abesto-net-chef '/storage/nvme5/new_clones/PLSQL/abesto-net-chef' &
git clone https://github.com/majumderb/sanskrit-ocr '/storage/nvme5/new_clones/PLSQL/sanskrit-ocr' &
git clone https://github.com/nicetheory/PL-Scope '/storage/nvme5/new_clones/PLSQL/PL-Scope' &
git clone https://github.com/textshuttle/exploiting-bias-to-debias '/storage/nvme5/new_clones/PLSQL/exploiting-bias-to-debias' &
git clone https://github.com/robyndahl/AdvancedPaleobiology '/storage/nvme5/new_clones/PLSQL/AdvancedPaleobiology' &
git clone https://github.com/damianmelson/WLAN-RGBW-LED-Controller '/storage/nvme5/new_clones/PLSQL/WLAN-RGBW-LED-Controller' &
git clone https://github.com/wilburli/oracleDataTransfer '/storage/nvme5/new_clones/PLSQL/oracleDataTransfer' &
git clone https://github.com/TjFish/markdown-region '/storage/nvme5/new_clones/PLSQL/markdown-region' &
git clone https://github.com/acomjetu/sample-database-online-electronics-store '/storage/nvme5/new_clones/PLSQL/sample-database-online-electronics-store' &
git clone https://github.com/ARCH-commons/arch-utils '/storage/nvme5/new_clones/PLSQL/arch-utils' &
git clone https://github.com/teotiger/pldocu '/storage/nvme5/new_clones/PLSQL/pldocu' &
git clone https://github.com/msotov/SPECIES '/storage/nvme5/new_clones/PLSQL/SPECIES' &
git clone https://github.com/planetapex/apex-plugin-contextualToolbar '/storage/nvme5/new_clones/PLSQL/apex-plugin-contextualToolbar' &
git clone https://github.com/jon-dixon/cn_blog_demos '/storage/nvme5/new_clones/PLSQL/cn_blog_demos' &
git clone https://github.com/AlanBurstein/SQL-Library '/storage/nvme5/new_clones/PLSQL/SQL-Library' &
git clone https://github.com/ourcade/phaser3-sword-swing-attack '/storage/nvme5/new_clones/PLSQL/phaser3-sword-swing-attack' &
git clone https://github.com/aperveyev/booru_processor '/storage/nvme5/new_clones/PLSQL/booru_processor' &
git clone https://github.com/Dark-Athena/pl4py '/storage/nvme5/new_clones/PLSQL/pl4py' &
git clone https://github.com/qwertyvipul/e-attendance '/storage/nvme5/new_clones/PLSQL/e-attendance' &
git clone https://github.com/rzuniga64/pl_sql '/storage/nvme5/new_clones/PLSQL/pl_sql' &
git clone https://github.com/bspauld/PostGISfortheGeographer '/storage/nvme5/new_clones/PLSQL/PostGISfortheGeographer' &
git clone https://github.com/Saeed-Hassanpour/ModalLOVIG '/storage/nvme5/new_clones/PLSQL/ModalLOVIG' &
git clone https://github.com/nerdalize/swan '/storage/nvme5/new_clones/PLSQL/swan' &
git clone https://github.com/RonnyWeiss/APEX-D3-Dashboard-Charts '/storage/nvme5/new_clones/PLSQL/APEX-D3-Dashboard-Charts' &
git clone https://github.com/alibahmanyar/Activity-recognition-2.0 '/storage/nvme5/new_clones/PLSQL/Activity-recognition-2.0' &
git clone https://github.com/cesarcrfilho/DBS301_Labs '/storage/nvme5/new_clones/PLSQL/DBS301_Labs' &
git clone https://github.com/jpfuentesv/jpfuentesv89-Programacion_BBDD_PL-SQL- '/storage/nvme5/new_clones/PLSQL/jpfuentesv89-Programacion_BBDD_PL-SQL-' &
git clone https://github.com/iamabrom/TradingView-Indicators '/storage/nvme5/new_clones/PLSQL/TradingView-Indicators' &
git clone https://github.com/SkillBuilders/sb-timeline '/storage/nvme5/new_clones/PLSQL/sb-timeline' &
git clone https://github.com/fuzziebrain/plsql-tweet-starter '/storage/nvme5/new_clones/PLSQL/plsql-tweet-starter' &
git clone https://github.com/nikitsky/heatmap_calendar_apex_plugin '/storage/nvme5/new_clones/PLSQL/heatmap_calendar_apex_plugin' &
git clone https://github.com/dbarj/oracle_patch_loop '/storage/nvme5/new_clones/PLSQL/oracle_patch_loop' &
git clone https://github.com/foex-open-source/fos-download-files '/storage/nvme5/new_clones/PLSQL/fos-download-files' &
git clone https://github.com/mcgee-analytics/My-Tableau-Repository-Addins '/storage/nvme5/new_clones/PLSQL/My-Tableau-Repository-Addins' &
git clone https://github.com/Dani3lSun/apex-onlyoffice-integration '/storage/nvme5/new_clones/PLSQL/apex-onlyoffice-integration' &
git clone https://github.com/pavithraks/ML_Labs '/storage/nvme5/new_clones/PLSQL/ML_Labs' &
git clone https://github.com/yusufanilakduygu/Oracle-DB-Security-Checks '/storage/nvme5/new_clones/PLSQL/Oracle-DB-Security-Checks' &
git clone https://github.com/Khaligufzel/NuclearWorld '/storage/nvme5/new_clones/PLSQL/NuclearWorld' &
git clone https://github.com/sadam-99/Uber-Database-Design-System '/storage/nvme5/new_clones/PLSQL/Uber-Database-Design-System' &
git clone https://github.com/kivilev/oracle_lections_examples_qiwi '/storage/nvme5/new_clones/PLSQL/oracle_lections_examples_qiwi' &
git clone https://github.com/radwanromy/Procedural-Language-for-SQL-Query '/storage/nvme5/new_clones/PLSQL/Procedural-Language-for-SQL-Query' &
git clone https://github.com/hellrazor4223/hardmode-expansion '/storage/nvme5/new_clones/PLSQL/hardmode-expansion' &
git clone https://github.com/YahooArchive/yamall '/storage/nvme5/new_clones/PLSQL/yamall' &
git clone https://github.com/Apress/mastering-snowflake-solutions '/storage/nvme5/new_clones/PLSQL/mastering-snowflake-solutions' &
git clone https://github.com/loop333/oracle_unwrap '/storage/nvme5/new_clones/PLSQL/oracle_unwrap' &
git clone https://github.com/loiclefevre/dbone '/storage/nvme5/new_clones/PLSQL/dbone' &
git clone https://github.com/lancezhange/MAB '/storage/nvme5/new_clones/PLSQL/MAB' &
git clone https://github.com/RonnyWeiss/Apex-D3-Organization-Chart '/storage/nvme5/new_clones/PLSQL/Apex-D3-Organization-Chart' &
git clone https://github.com/CSopiko/ExamBase '/storage/nvme5/new_clones/PLSQL/ExamBase' &
git clone https://github.com/tanzirulnayan/Restaurant-Database '/storage/nvme5/new_clones/PLSQL/Restaurant-Database' &
git clone https://github.com/TimNanos/HCC-ORDER-BY-Advisor '/storage/nvme5/new_clones/PLSQL/HCC-ORDER-BY-Advisor' &
git clone https://github.com/newdigate/sqlserver-revision-tables '/storage/nvme5/new_clones/PLSQL/sqlserver-revision-tables' &
git clone https://github.com/dgielis/blog '/storage/nvme5/new_clones/PLSQL/blog' &
git clone https://github.com/oraclebase/liquibase_sqlcl_apex_demo '/storage/nvme5/new_clones/PLSQL/liquibase_sqlcl_apex_demo' &
git clone https://github.com/jonheller1/SQL_Activity_Chart '/storage/nvme5/new_clones/PLSQL/SQL_Activity_Chart' &
git clone https://github.com/satyarthiabhay/Hackerrank-SQL-Challenges '/storage/nvme5/new_clones/PLSQL/Hackerrank-SQL-Challenges' &
git clone https://github.com/ceyhunkerti/pl '/storage/nvme5/new_clones/PLSQL/pl' &
git clone https://github.com/davidwfranco/sql '/storage/nvme5/new_clones/PLSQL/sql' &
git clone https://github.com/senai-desenvolvimento/1s2019-t2-sprint-1-bd '/storage/nvme5/new_clones/PLSQL/1s2019-t2-sprint-1-bd' &
git clone https://github.com/raekins/oracle18xe-ords-apex '/storage/nvme5/new_clones/PLSQL/oracle18xe-ords-apex' &
git clone https://github.com/callor/Biz-DBMS-505-2022-05 '/storage/nvme5/new_clones/PLSQL/Biz-DBMS-505-2022-05' &
git clone https://github.com/omenmicro/kilo '/storage/nvme5/new_clones/PLSQL/kilo' &
git clone https://github.com/shughuangQQQ/MySql_Select_Test_Demo '/storage/nvme5/new_clones/PLSQL/MySql_Select_Test_Demo' &
git clone https://github.com/DustinLedbetter/T-SQL-Fundamentals-Third-Edition-Book-Work '/storage/nvme5/new_clones/PLSQL/T-SQL-Fundamentals-Third-Edition-Book-Work' &
git clone https://github.com/martindsouza/oracle-project-template '/storage/nvme5/new_clones/PLSQL/oracle-project-template' &
git clone https://github.com/2XUID/FIT2094-FIT3171 '/storage/nvme5/new_clones/PLSQL/FIT2094-FIT3171' &
