#!/bin/bash

git clone https://github.com/WallarooLabs/wally '/storage/nvme5/new_clones/Pony/wally' &
git clone https://github.com/ponylang/ponyup '/storage/nvme5/new_clones/Pony/ponyup' &
git clone https://github.com/ponylang/corral '/storage/nvme5/new_clones/Pony/corral' &
git clone https://github.com/ponylang/pony-stable '/storage/nvme5/new_clones/Pony/pony-stable' &
git clone https://github.com/aturley/pony-workshop '/storage/nvme5/new_clones/Pony/pony-workshop' &
git clone https://github.com/Theodus/jennet '/storage/nvme5/new_clones/Pony/jennet' &
git clone https://github.com/jemc/jylis '/storage/nvme5/new_clones/Pony/jylis' &
git clone https://github.com/jemc/pony-zmq '/storage/nvme5/new_clones/Pony/pony-zmq' &
git clone https://github.com/ponylang/ponycheck '/storage/nvme5/new_clones/Pony/ponycheck' &
git clone https://github.com/WallarooLabs/pony-kafka '/storage/nvme5/new_clones/Pony/pony-kafka' &
git clone https://github.com/oraoto/pony-websocket '/storage/nvme5/new_clones/Pony/pony-websocket' &
git clone https://github.com/jtfmumm/pony-functional-data '/storage/nvme5/new_clones/Pony/pony-functional-data' &
git clone https://github.com/npruehs/pony-game '/storage/nvme5/new_clones/Pony/pony-game' &
git clone https://github.com/ponylang/http '/storage/nvme5/new_clones/Pony/http' &
git clone https://github.com/ponylang/reactive_streams '/storage/nvme5/new_clones/Pony/reactive_streams' &
git clone https://github.com/jemc/pony-crdt '/storage/nvme5/new_clones/Pony/pony-crdt' &
git clone https://github.com/exercism/pony '/storage/nvme5/new_clones/Pony/pony' &
git clone https://github.com/jemc/ponycc '/storage/nvme5/new_clones/Pony/ponycc' &
git clone https://github.com/ponylang/http_server '/storage/nvme5/new_clones/Pony/http_server' &
git clone https://github.com/seantallen-org/msgpack '/storage/nvme5/new_clones/Pony/msgpack' &
git clone https://github.com/jemc/pony-inspect '/storage/nvme5/new_clones/Pony/pony-inspect' &
git clone https://github.com/jemc/pony-sodium '/storage/nvme5/new_clones/Pony/pony-sodium' &
git clone https://github.com/dougmacdoug/ponylang-linal '/storage/nvme5/new_clones/Pony/ponylang-linal' &
git clone https://github.com/ponylang/pony-language-server '/storage/nvme5/new_clones/Pony/pony-language-server' &
git clone https://github.com/d-led/DDDwithActorsPony '/storage/nvme5/new_clones/Pony/DDDwithActorsPony' &
git clone https://github.com/jemc/pony-capnp '/storage/nvme5/new_clones/Pony/pony-capnp' &
git clone https://github.com/chalcolith/kiuatan '/storage/nvme5/new_clones/Pony/kiuatan' &
git clone https://github.com/ponylang/peg '/storage/nvme5/new_clones/Pony/peg' &
git clone https://github.com/lisael/pony-postgres '/storage/nvme5/new_clones/Pony/pony-postgres' &
git clone https://github.com/ponylang/lori '/storage/nvme5/new_clones/Pony/lori' &
git clone https://github.com/autodidaddict/ponychat '/storage/nvme5/new_clones/Pony/ponychat' &
git clone https://github.com/ponylang/postgres '/storage/nvme5/new_clones/Pony/postgres' &
git clone https://github.com/ponylang/changelog-tool '/storage/nvme5/new_clones/Pony/changelog-tool' &
git clone https://github.com/mfelsche/ponyfmt '/storage/nvme5/new_clones/Pony/ponyfmt' &
git clone https://github.com/andrenth/pony-mysql '/storage/nvme5/new_clones/Pony/pony-mysql' &
git clone https://github.com/autodidaddict/ponymud '/storage/nvme5/new_clones/Pony/ponymud' &
git clone https://github.com/ponylang/crypto '/storage/nvme5/new_clones/Pony/crypto' &
git clone https://github.com/moesol/pony-advent-2016 '/storage/nvme5/new_clones/Pony/pony-advent-2016' &
git clone https://github.com/murgatroid99/pony-http2 '/storage/nvme5/new_clones/Pony/pony-http2' &
git clone https://github.com/SeanTAllen/pony-echo-server '/storage/nvme5/new_clones/Pony/pony-echo-server' &
git clone https://github.com/krig/tinyhorse '/storage/nvme5/new_clones/Pony/tinyhorse' &
git clone https://github.com/aturley/follow-the-plot '/storage/nvme5/new_clones/Pony/follow-the-plot' &
git clone https://github.com/jemc/pony-llvm '/storage/nvme5/new_clones/Pony/pony-llvm' &
git clone https://github.com/jemc/pony-jason '/storage/nvme5/new_clones/Pony/pony-jason' &
git clone https://github.com/Krognol/ponyjson '/storage/nvme5/new_clones/Pony/ponyjson' &
git clone https://github.com/jemc/pony-pegasus '/storage/nvme5/new_clones/Pony/pony-pegasus' &
git clone https://github.com/ponylang/fork_join '/storage/nvme5/new_clones/Pony/fork_join' &
git clone https://github.com/ponylang/semver '/storage/nvme5/new_clones/Pony/semver' &
git clone https://github.com/jemc/pony-redis '/storage/nvme5/new_clones/Pony/pony-redis' &
git clone https://github.com/ponylang/appdirs '/storage/nvme5/new_clones/Pony/appdirs' &
git clone https://github.com/tmmcguire/shetland '/storage/nvme5/new_clones/Pony/shetland' &
git clone https://github.com/MoebiusSolutions/graphql-pony '/storage/nvme5/new_clones/Pony/graphql-pony' &
git clone https://github.com/hibnico/pony-yaml '/storage/nvme5/new_clones/Pony/pony-yaml' &
git clone https://github.com/chalcolith/pony-kanren '/storage/nvme5/new_clones/Pony/pony-kanren' &
git clone https://github.com/d-led/otp_pony_node '/storage/nvme5/new_clones/Pony/otp_pony_node' &
git clone https://github.com/ponylang/github_rest_api '/storage/nvme5/new_clones/Pony/github_rest_api' &
git clone https://github.com/darach/hdr_histogram_pony '/storage/nvme5/new_clones/Pony/hdr_histogram_pony' &
git clone https://github.com/nogginly/termax.pony '/storage/nvme5/new_clones/Pony/termax.pony' &
git clone https://github.com/ponylang/templates '/storage/nvme5/new_clones/Pony/templates' &
git clone https://github.com/mfelsche/pony-maybe '/storage/nvme5/new_clones/Pony/pony-maybe' &
git clone https://github.com/LouJo/PonyCsv '/storage/nvme5/new_clones/Pony/PonyCsv' &
git clone https://github.com/EpicEric/pony-mqtt '/storage/nvme5/new_clones/Pony/pony-mqtt' &
git clone https://github.com/ergl/pony-protobuf '/storage/nvme5/new_clones/Pony/pony-protobuf' &
git clone https://github.com/lisael/pony-raft '/storage/nvme5/new_clones/Pony/pony-raft' &
git clone https://github.com/ii8/pony-cbor '/storage/nvme5/new_clones/Pony/pony-cbor' &
git clone https://github.com/doublec/pony-sdl-example '/storage/nvme5/new_clones/Pony/pony-sdl-example' &
