#!/bin/bash

git clone https://github.com/kenjihiranabe/The-Art-of-Linear-Algebra '/storage/nvme5/new_clones/PostScript/The-Art-of-Linear-Algebra' &
git clone https://github.com/django/djangoproject.com '/storage/nvme5/new_clones/PostScript/djangoproject.com' &
git clone https://github.com/adobe-fonts/source-han-code-jp '/storage/nvme5/new_clones/PostScript/source-han-code-jp' &
git clone https://github.com/fossasia/sciencehack-artwork '/storage/nvme5/new_clones/PostScript/sciencehack-artwork' &
git clone https://github.com/ryanoasis/powerline-extra-symbols '/storage/nvme5/new_clones/PostScript/powerline-extra-symbols' &
git clone https://github.com/voodootikigod/logo.js '/storage/nvme5/new_clones/PostScript/logo.js' &
git clone https://github.com/EasyChart/Beautiful-Visualization-with-R '/storage/nvme5/new_clones/PostScript/Beautiful-Visualization-with-R' &
git clone https://github.com/cooplab/popgen-notes '/storage/nvme5/new_clones/PostScript/popgen-notes' &
git clone https://github.com/dair-iitd/OpenIE-standalone '/storage/nvme5/new_clones/PostScript/OpenIE-standalone' &
git clone https://github.com/djnavarro/rbook '/storage/nvme5/new_clones/PostScript/rbook' &
git clone https://github.com/lmthang/thesis '/storage/nvme5/new_clones/PostScript/thesis' &
git clone https://github.com/bwipp/postscriptbarcode '/storage/nvme5/new_clones/PostScript/postscriptbarcode' &
git clone https://github.com/tLDP/LDP '/storage/nvme5/new_clones/PostScript/LDP' &
git clone https://github.com/daly/axiom '/storage/nvme5/new_clones/PostScript/axiom' &
git clone https://github.com/im-tomu/tomu-hardware '/storage/nvme5/new_clones/PostScript/tomu-hardware' &
git clone https://github.com/easystats/effectsize '/storage/nvme5/new_clones/PostScript/effectsize' &
git clone https://github.com/barrracud4/image-upload-exploits '/storage/nvme5/new_clones/PostScript/image-upload-exploits' &
git clone https://github.com/konsav/social-icons '/storage/nvme5/new_clones/PostScript/social-icons' &
git clone https://github.com/dectalk/dectalk '/storage/nvme5/new_clones/PostScript/dectalk' &
git clone https://github.com/cerebrobr/adesivos '/storage/nvme5/new_clones/PostScript/adesivos' &
git clone https://github.com/MagerValp/CreateUserPkg '/storage/nvme5/new_clones/PostScript/CreateUserPkg' &
git clone https://github.com/angea/PDF101 '/storage/nvme5/new_clones/PostScript/PDF101' &
git clone https://github.com/openwebwork/webwork-open-problem-library '/storage/nvme5/new_clones/PostScript/webwork-open-problem-library' &
git clone https://github.com/john-b-schneider/uFDTD '/storage/nvme5/new_clones/PostScript/uFDTD' &
git clone https://github.com/Euterpea/Euterpea '/storage/nvme5/new_clones/PostScript/Euterpea' &
git clone https://github.com/adobe-fonts/adobe-blank '/storage/nvme5/new_clones/PostScript/adobe-blank' &
git clone https://github.com/liuchengxu/szuthesis '/storage/nvme5/new_clones/PostScript/szuthesis' &
git clone https://github.com/csev/net-intro '/storage/nvme5/new_clones/PostScript/net-intro' &
git clone https://github.com/nodecopter/nodecopter.com '/storage/nvme5/new_clones/PostScript/nodecopter.com' &
git clone https://github.com/noppa/text-security '/storage/nvme5/new_clones/PostScript/text-security' &
git clone https://github.com/mattiasvillani/BayesLearnCourse '/storage/nvme5/new_clones/PostScript/BayesLearnCourse' &
git clone https://github.com/Znuff/consolas-powerline '/storage/nvme5/new_clones/PostScript/consolas-powerline' &
git clone https://github.com/mariuszostrowski/gesty '/storage/nvme5/new_clones/PostScript/gesty' &
git clone https://github.com/CrumpLab/statistics '/storage/nvme5/new_clones/PostScript/statistics' &
git clone https://github.com/shuwei1204/ZJUthesis '/storage/nvme5/new_clones/PostScript/ZJUthesis' &
git clone https://github.com/adamchainz/treepoem '/storage/nvme5/new_clones/PostScript/treepoem' &
git clone https://github.com/AllenDowney/ThinkCPP '/storage/nvme5/new_clones/PostScript/ThinkCPP' &
git clone https://github.com/ARM-software/ebbr '/storage/nvme5/new_clones/PostScript/ebbr' &
git clone https://github.com/mmattamala/LogosFCFM '/storage/nvme5/new_clones/PostScript/LogosFCFM' &
git clone https://github.com/m-takagi/aosa-ja '/storage/nvme5/new_clones/PostScript/aosa-ja' &
git clone https://github.com/cristoper/wav2vec '/storage/nvme5/new_clones/PostScript/wav2vec' &
git clone https://github.com/mohamedameen93/CS-6210-Advanced-Operating-Systems-Notes '/storage/nvme5/new_clones/PostScript/CS-6210-Advanced-Operating-Systems-Notes' &
git clone https://github.com/drewnoakes/metadata-extractor-images '/storage/nvme5/new_clones/PostScript/metadata-extractor-images' &
git clone https://github.com/tl3shi/THUBeamer '/storage/nvme5/new_clones/PostScript/THUBeamer' &
git clone https://github.com/hushidong/biblatex-solution-to-latex-bibliography '/storage/nvme5/new_clones/PostScript/biblatex-solution-to-latex-bibliography' &
git clone https://github.com/python-xmp-toolkit/python-xmp-toolkit '/storage/nvme5/new_clones/PostScript/python-xmp-toolkit' &
git clone https://github.com/Azure/dev-community '/storage/nvme5/new_clones/PostScript/dev-community' &
git clone https://github.com/braverock/PortfolioAnalytics '/storage/nvme5/new_clones/PostScript/PortfolioAnalytics' &
git clone https://github.com/RIVeR-Lab/apriltags_ros '/storage/nvme5/new_clones/PostScript/apriltags_ros' &
git clone https://github.com/duojs/duojs.org '/storage/nvme5/new_clones/PostScript/duojs.org' &
git clone https://github.com/masaleiro/HacKeyboard '/storage/nvme5/new_clones/PostScript/HacKeyboard' &
git clone https://github.com/kalanda/photoduino '/storage/nvme5/new_clones/PostScript/photoduino' &
git clone https://github.com/summitgao/OUC-LaTex-bachelor '/storage/nvme5/new_clones/PostScript/OUC-LaTex-bachelor' &
git clone https://github.com/tzaiyang/NEUBachelorThesis '/storage/nvme5/new_clones/PostScript/NEUBachelorThesis' &
git clone https://github.com/foodfight/showz '/storage/nvme5/new_clones/PostScript/showz' &
git clone https://github.com/introocean/introocean-en '/storage/nvme5/new_clones/PostScript/introocean-en' &
git clone https://github.com/adobe-fonts/adobe-notdef '/storage/nvme5/new_clones/PostScript/adobe-notdef' &
git clone https://github.com/kljensen/mit-phd-thesis '/storage/nvme5/new_clones/PostScript/mit-phd-thesis' &
git clone https://github.com/kokonior/Pascal-Projects '/storage/nvme5/new_clones/PostScript/Pascal-Projects' &
git clone https://github.com/mattiasvillani/AdvBayesLearnCourse '/storage/nvme5/new_clones/PostScript/AdvBayesLearnCourse' &
git clone https://github.com/ethz-asl/asl-student-templates '/storage/nvme5/new_clones/PostScript/asl-student-templates' &
git clone https://github.com/ksyang2013/aimsgb '/storage/nvme5/new_clones/PostScript/aimsgb' &
git clone https://github.com/rsmith-nl/stltools '/storage/nvme5/new_clones/PostScript/stltools' &
git clone https://github.com/tohojo/bufferbloat-net '/storage/nvme5/new_clones/PostScript/bufferbloat-net' &
git clone https://github.com/SGL-UT/gnsstk-apps '/storage/nvme5/new_clones/PostScript/gnsstk-apps' &
git clone https://github.com/open-ephys/acquisition-board '/storage/nvme5/new_clones/PostScript/acquisition-board' &
git clone https://github.com/a-yiorgos/wambook '/storage/nvme5/new_clones/PostScript/wambook' &
git clone https://github.com/arnoldrobbins/dformat '/storage/nvme5/new_clones/PostScript/dformat' &
git clone https://github.com/FOSDEM/website '/storage/nvme5/new_clones/PostScript/website' &
git clone https://github.com/muellerberndt/rektosaurus '/storage/nvme5/new_clones/PostScript/rektosaurus' &
git clone https://github.com/acsl-language/acsl '/storage/nvme5/new_clones/PostScript/acsl' &
git clone https://github.com/tmieno2/R-as-GIS-for-Economists '/storage/nvme5/new_clones/PostScript/R-as-GIS-for-Economists' &
git clone https://github.com/XenBG/bulgarian-city-coat-of-arms '/storage/nvme5/new_clones/PostScript/bulgarian-city-coat-of-arms' &
git clone https://github.com/meh/miserve '/storage/nvme5/new_clones/PostScript/miserve' &
git clone https://github.com/thomasWeise/ustcSlides '/storage/nvme5/new_clones/PostScript/ustcSlides' &
git clone https://github.com/OSOUC/UndergraduateThesisLaTeXTemplate '/storage/nvme5/new_clones/PostScript/UndergraduateThesisLaTeXTemplate' &
git clone https://github.com/hackerb9/vt340test '/storage/nvme5/new_clones/PostScript/vt340test' &
git clone https://github.com/hamsterwk/whucs-beamer '/storage/nvme5/new_clones/PostScript/whucs-beamer' &
git clone https://github.com/RingoSeeber/Petrona '/storage/nvme5/new_clones/PostScript/Petrona' &
git clone https://github.com/akaziuna/cnc-standing-height-workbench '/storage/nvme5/new_clones/PostScript/cnc-standing-height-workbench' &
git clone https://github.com/gogameguru/go-problems '/storage/nvme5/new_clones/PostScript/go-problems' &
git clone https://github.com/lazharkhelifi/deeplearning_changedetection_remotesensing_review '/storage/nvme5/new_clones/PostScript/deeplearning_changedetection_remotesensing_review' &
git clone https://github.com/graveja0/health-care-markets '/storage/nvme5/new_clones/PostScript/health-care-markets' &
git clone https://github.com/Peteysoft/libmsci '/storage/nvme5/new_clones/PostScript/libmsci' &
git clone https://github.com/OpenPrinting/ps-printer-app '/storage/nvme5/new_clones/PostScript/ps-printer-app' &
git clone https://github.com/voc/intro-outro-generator '/storage/nvme5/new_clones/PostScript/intro-outro-generator' &
git clone https://github.com/veg/hyphy-analyses '/storage/nvme5/new_clones/PostScript/hyphy-analyses' &
git clone https://github.com/personalrobotics/apriltags '/storage/nvme5/new_clones/PostScript/apriltags' &
git clone https://github.com/tanz0119/thesis '/storage/nvme5/new_clones/PostScript/thesis' &
git clone https://github.com/vierstralab/motif-clustering '/storage/nvme5/new_clones/PostScript/motif-clustering' &
git clone https://github.com/rjw57/cambridge-beamer '/storage/nvme5/new_clones/PostScript/cambridge-beamer' &
git clone https://github.com/alexschiller/file-format-commons '/storage/nvme5/new_clones/PostScript/file-format-commons' &
git clone https://github.com/StevensDeptECE/CPE553-CPP '/storage/nvme5/new_clones/PostScript/CPE553-CPP' &
git clone https://github.com/hzeller/postscript-hacks '/storage/nvme5/new_clones/PostScript/postscript-hacks' &
git clone https://github.com/OxCGRT/covid-policy-scratchpad '/storage/nvme5/new_clones/PostScript/covid-policy-scratchpad' &
git clone https://github.com/OpenPrinting/ghostscript-printer-app '/storage/nvme5/new_clones/PostScript/ghostscript-printer-app' &
git clone https://github.com/berndporr/digital_signal_processing '/storage/nvme5/new_clones/PostScript/digital_signal_processing' &
git clone https://github.com/kholsinger/Lecture-Notes-in-Population-Genetics '/storage/nvme5/new_clones/PostScript/Lecture-Notes-in-Population-Genetics' &
git clone https://github.com/adobe-fonts/adobe-blank-2 '/storage/nvme5/new_clones/PostScript/adobe-blank-2' &
git clone https://github.com/matthiaskramm/gfxpoly '/storage/nvme5/new_clones/PostScript/gfxpoly' &
git clone https://github.com/jamoma/Jamoma '/storage/nvme5/new_clones/PostScript/Jamoma' &
git clone https://github.com/zrecore/freeIMU '/storage/nvme5/new_clones/PostScript/freeIMU' &
git clone https://github.com/longqianh/ZJU-experiment-report-template '/storage/nvme5/new_clones/PostScript/ZJU-experiment-report-template' &
git clone https://github.com/EmaroLab/docs '/storage/nvme5/new_clones/PostScript/docs' &
git clone https://github.com/steiza/postscript_fractals '/storage/nvme5/new_clones/PostScript/postscript_fractals' &
git clone https://github.com/e-n-f/ascii '/storage/nvme5/new_clones/PostScript/ascii' &
git clone https://github.com/Project-Oberon/Source-Code '/storage/nvme5/new_clones/PostScript/Source-Code' &
git clone https://github.com/pradip-interra/PineScripts '/storage/nvme5/new_clones/PostScript/PineScripts' &
git clone https://github.com/bhdicaire/dataLossPrevention '/storage/nvme5/new_clones/PostScript/dataLossPrevention' &
git clone https://github.com/voidrank/FDUThss '/storage/nvme5/new_clones/PostScript/FDUThss' &
git clone https://github.com/eth-cscs/SummerSchool2021 '/storage/nvme5/new_clones/PostScript/SummerSchool2021' &
git clone https://github.com/CIShell/CIShell '/storage/nvme5/new_clones/PostScript/CIShell' &
git clone https://github.com/HaizhaoYang/SST_compare '/storage/nvme5/new_clones/PostScript/SST_compare' &
git clone https://github.com/Cryptosaurus/iacrtrans '/storage/nvme5/new_clones/PostScript/iacrtrans' &
git clone https://github.com/SueDNymme/emacs-calc-qref '/storage/nvme5/new_clones/PostScript/emacs-calc-qref' &
git clone https://github.com/jasper-software/xv '/storage/nvme5/new_clones/PostScript/xv' &
git clone https://github.com/AskNowQA/AskNowNQS '/storage/nvme5/new_clones/PostScript/AskNowNQS' &
git clone https://github.com/sjbeckett/weighted-modularity-LPAwbPLUS '/storage/nvme5/new_clones/PostScript/weighted-modularity-LPAwbPLUS' &
git clone https://github.com/berndporr/realtime_cpp_coding '/storage/nvme5/new_clones/PostScript/realtime_cpp_coding' &
git clone https://github.com/sftcd/cs7053 '/storage/nvme5/new_clones/PostScript/cs7053' &
git clone https://github.com/adamcavendish/Deep-Image-Steganography '/storage/nvme5/new_clones/PostScript/Deep-Image-Steganography' &
git clone https://github.com/GiantVM/giantvm.github.io '/storage/nvme5/new_clones/PostScript/giantvmhub.io' &
git clone https://github.com/ellioman/Twitter-Sentiment-Analysis '/storage/nvme5/new_clones/PostScript/Twitter-Sentiment-Analysis' &
git clone https://github.com/Coleridge-Initiative/big-data-and-social-science '/storage/nvme5/new_clones/PostScript/big-data-and-social-science' &
git clone https://github.com/makhtardiouf/d2d '/storage/nvme5/new_clones/PostScript/d2d' &
git clone https://github.com/rbkettlewell/trollstigen-fpga '/storage/nvme5/new_clones/PostScript/trollstigen-fpga' &
git clone https://github.com/CTeX-DEV/CTeX '/storage/nvme5/new_clones/PostScript/CTeX' &
git clone https://github.com/kragen/laserboot '/storage/nvme5/new_clones/PostScript/laserboot' &
git clone https://github.com/mrsquig/calendar-generator '/storage/nvme5/new_clones/PostScript/calendar-generator' &
git clone https://github.com/ramalho/kaminpy '/storage/nvme5/new_clones/PostScript/kaminpy' &
git clone https://github.com/simpeg/transform-2020-simpeg '/storage/nvme5/new_clones/PostScript/transform-2020-simpeg' &
git clone https://github.com/cusbg/traveler '/storage/nvme5/new_clones/PostScript/traveler' &
git clone https://github.com/liuqinya/py_cap '/storage/nvme5/new_clones/PostScript/py_cap' &
git clone https://github.com/EmyLibrary/emy '/storage/nvme5/new_clones/PostScript/emy' &
git clone https://github.com/arechnitzer/CLP3 '/storage/nvme5/new_clones/PostScript/CLP3' &
git clone https://github.com/lemoxiao/Awesome-Beamer-Collection '/storage/nvme5/new_clones/PostScript/Awesome-Beamer-Collection' &
git clone https://github.com/PureDarwin/Hexley '/storage/nvme5/new_clones/PostScript/Hexley' &
git clone https://github.com/eth-cscs/SummerUniversity2022 '/storage/nvme5/new_clones/PostScript/SummerUniversity2022' &
git clone https://github.com/gregoriorobles/plantilla-memoria '/storage/nvme5/new_clones/PostScript/plantilla-memoria' &
git clone https://github.com/GabrielDosReis/open-axiom '/storage/nvme5/new_clones/PostScript/open-axiom' &
git clone https://github.com/alexarje/A-NIME-Reader '/storage/nvme5/new_clones/PostScript/A-NIME-Reader' &
git clone https://github.com/danluu/dump '/storage/nvme5/new_clones/PostScript/dump' &
git clone https://github.com/microcai/gentoo-handbook '/storage/nvme5/new_clones/PostScript/gentoo-handbook' &
git clone https://github.com/RegressionAndOtherStoriesJulia/RegressionAndOtherStories.jl '/storage/nvme5/new_clones/PostScript/RegressionAndOtherStories.jl' &
git clone https://github.com/teaguemiller/mxw '/storage/nvme5/new_clones/PostScript/mxw' &
git clone https://github.com/itomato/lubu '/storage/nvme5/new_clones/PostScript/lubu' &
git clone https://github.com/keyboardio/Model01-Legends '/storage/nvme5/new_clones/PostScript/Model01-Legends' &
git clone https://github.com/RafaelMarinheiro/RotationAveraging '/storage/nvme5/new_clones/PostScript/RotationAveraging' &
git clone https://github.com/msrconf/msrconf '/storage/nvme5/new_clones/PostScript/msrconf' &
git clone https://github.com/Grantlab/bio3d '/storage/nvme5/new_clones/PostScript/bio3d' &
git clone https://github.com/siscia/intro-to-distributed-system '/storage/nvme5/new_clones/PostScript/intro-to-distributed-system' &
git clone https://github.com/mindboard/indesign-extendscript '/storage/nvme5/new_clones/PostScript/indesign-extendscript' &
git clone https://github.com/lbl-srg/GenOpt '/storage/nvme5/new_clones/PostScript/GenOpt' &
git clone https://github.com/adobe-fonts/kenten-generic '/storage/nvme5/new_clones/PostScript/kenten-generic' &
git clone https://github.com/SCD-Aix-Marseille-Universite/latexamu '/storage/nvme5/new_clones/PostScript/latexamu' &
git clone https://github.com/tjmahr/GelmanHill '/storage/nvme5/new_clones/PostScript/GelmanHill' &
git clone https://github.com/mgmax/inkscape-roland-cutstudio '/storage/nvme5/new_clones/PostScript/inkscape-roland-cutstudio' &
git clone https://github.com/STIMALiU/BayesLearnCourse '/storage/nvme5/new_clones/PostScript/BayesLearnCourse' &
git clone https://github.com/ncborcherding/ccRCC '/storage/nvme5/new_clones/PostScript/ccRCC' &
git clone https://github.com/OpenPrinting/gutenprint-printer-app '/storage/nvme5/new_clones/PostScript/gutenprint-printer-app' &
git clone https://github.com/audrey617/CS6210-Advanced-Operating-Systems-Notes '/storage/nvme5/new_clones/PostScript/CS6210-Advanced-Operating-Systems-Notes' &
git clone https://github.com/elsys/oop2017-2018 '/storage/nvme5/new_clones/PostScript/oop2017-2018' &
git clone https://github.com/czeps-org/factsheets '/storage/nvme5/new_clones/PostScript/factsheets' &
git clone https://github.com/hduffddybz/HDU-thesis '/storage/nvme5/new_clones/PostScript/HDU-thesis' &
git clone https://github.com/muzimuzhi/Qbook '/storage/nvme5/new_clones/PostScript/Qbook' &
git clone https://github.com/davidgiven/pcemu '/storage/nvme5/new_clones/PostScript/pcemu' &
git clone https://github.com/rOpenHealth/ClinicalCodes '/storage/nvme5/new_clones/PostScript/ClinicalCodes' &
git clone https://github.com/hemokosa/caex '/storage/nvme5/new_clones/PostScript/caex' &
git clone https://github.com/JinfanChris/TJU-2022-TCP-Computer-Network-Lab '/storage/nvme5/new_clones/PostScript/TJU-2022-TCP-Computer-Network-Lab' &
git clone https://github.com/opendesk/smartdesk '/storage/nvme5/new_clones/PostScript/smartdesk' &
git clone https://github.com/cbourjau/frederiksberg_beamer '/storage/nvme5/new_clones/PostScript/frederiksberg_beamer' &
git clone https://github.com/babzcraig/free-nigerian-based-icons '/storage/nvme5/new_clones/PostScript/free-nigerian-based-icons' &
git clone https://github.com/ashokpant/masters-thesis-latex '/storage/nvme5/new_clones/PostScript/masters-thesis-latex' &
git clone https://github.com/NeoSmartpen/Ncode-SDK2.0 '/storage/nvme5/new_clones/PostScript/Ncode-SDK2.0' &
git clone https://github.com/usgs/earthquake-website '/storage/nvme5/new_clones/PostScript/earthquake-website' &
git clone https://github.com/cannin/snp_plotter '/storage/nvme5/new_clones/PostScript/snp_plotter' &
git clone https://github.com/YANGZHAO233/Ambient-Noise-Adjoint-Tomography '/storage/nvme5/new_clones/PostScript/Ambient-Noise-Adjoint-Tomography' &
git clone https://github.com/arechnitzer/CLP4 '/storage/nvme5/new_clones/PostScript/CLP4' &
git clone https://github.com/selinger/linear-algebra '/storage/nvme5/new_clones/PostScript/linear-algebra' &
git clone https://github.com/stormeddy/Reversible-Data-Hiding '/storage/nvme5/new_clones/PostScript/Reversible-Data-Hiding' &
git clone https://github.com/luser-dr00g/debug.ps '/storage/nvme5/new_clones/PostScript/debug.ps' &
git clone https://github.com/marius311/cosmohome '/storage/nvme5/new_clones/PostScript/cosmohome' &
git clone https://github.com/Wiladams/lj2ps '/storage/nvme5/new_clones/PostScript/lj2ps' &
git clone https://github.com/joaomoura24/InformaticsSlidesBeamer '/storage/nvme5/new_clones/PostScript/InformaticsSlidesBeamer' &
git clone https://github.com/arjundatta23/disp_codes '/storage/nvme5/new_clones/PostScript/disp_codes' &
git clone https://github.com/penelopy/daycare_finder_app '/storage/nvme5/new_clones/PostScript/daycare_finder_app' &
git clone https://github.com/ruby-sapporo/ruby-sapporo.org '/storage/nvme5/new_clones/PostScript/ruby-sapporo.org' &
git clone https://github.com/JamesHeinrich/getID3-testfiles '/storage/nvme5/new_clones/PostScript/getID3-testfiles' &
git clone https://github.com/joeblau/context-symbol '/storage/nvme5/new_clones/PostScript/context-symbol' &
git clone https://github.com/DillonGrech/Tradingview-Strategies '/storage/nvme5/new_clones/PostScript/Tradingview-Strategies' &
git clone https://github.com/OxCGRT/Brazil-covid-policy '/storage/nvme5/new_clones/PostScript/Brazil-covid-policy' &
git clone https://github.com/stonerlab/Thesis-template '/storage/nvme5/new_clones/PostScript/Thesis-template' &
git clone https://github.com/ckenst/images-catalog '/storage/nvme5/new_clones/PostScript/images-catalog' &
git clone https://github.com/OWASP/www-committee-chapter '/storage/nvme5/new_clones/PostScript/www-committee-chapter' &
git clone https://github.com/GodzikLab/FATCAT-dist '/storage/nvme5/new_clones/PostScript/FATCAT-dist' &
git clone https://github.com/xzlashutosh/avsddac_3v3 '/storage/nvme5/new_clones/PostScript/avsddac_3v3' &
git clone https://github.com/etherkit/OpenBeacon '/storage/nvme5/new_clones/PostScript/OpenBeacon' &
git clone https://github.com/EurasianEagleOwl/TJU-LaTeX-Beamer-Template '/storage/nvme5/new_clones/PostScript/TJU-LaTeX-Beamer-Template' &
git clone https://github.com/UTCompSeismo/GRD_CMT3D '/storage/nvme5/new_clones/PostScript/GRD_CMT3D' &
git clone https://github.com/socallinuxexpo/SCALE-Planning '/storage/nvme5/new_clones/PostScript/SCALE-Planning' &
git clone https://github.com/measuringhumancapital/MHC '/storage/nvme5/new_clones/PostScript/MHC' &
git clone https://github.com/eda-ricercatore/Modica-SRAM '/storage/nvme5/new_clones/PostScript/Modica-SRAM' &
git clone https://github.com/Jace-Yang/bank-marketing-strategy-analysis '/storage/nvme5/new_clones/PostScript/bank-marketing-strategy-analysis' &
git clone https://github.com/adobe-fonts/tally-marks '/storage/nvme5/new_clones/PostScript/tally-marks' &
git clone https://github.com/OpenDiscreteMath/ibl-combinatorics '/storage/nvme5/new_clones/PostScript/ibl-combinatorics' &
git clone https://github.com/surberj/Vision '/storage/nvme5/new_clones/PostScript/Vision' &
git clone https://github.com/hhc0null/GhostRule '/storage/nvme5/new_clones/PostScript/GhostRule' &
git clone https://github.com/ram8647/javajavajava '/storage/nvme5/new_clones/PostScript/javajavajava' &
git clone https://github.com/MichiganTech/LaTeX_MSPhDTemplate '/storage/nvme5/new_clones/PostScript/LaTeX_MSPhDTemplate' &
git clone https://github.com/spond/gb_taxonomy_tools '/storage/nvme5/new_clones/PostScript/gb_taxonomy_tools' &
git clone https://github.com/AlongWY/Latex-Template '/storage/nvme5/new_clones/PostScript/Latex-Template' &
git clone https://github.com/harrydragon/MATLAB '/storage/nvme5/new_clones/PostScript/MATLAB' &
git clone https://github.com/jefferislab/pnaslatex '/storage/nvme5/new_clones/PostScript/pnaslatex' &
git clone https://github.com/FelixHenninger/mousetrap-web '/storage/nvme5/new_clones/PostScript/mousetrap-web' &
git clone https://github.com/active-calculus/active-calculus-single-mbx '/storage/nvme5/new_clones/PostScript/active-calculus-single-mbx' &
git clone https://github.com/NoiseCIEI/AFTAN '/storage/nvme5/new_clones/PostScript/AFTAN' &
git clone https://github.com/lipan6461188/IPyRSSA '/storage/nvme5/new_clones/PostScript/IPyRSSA' &
git clone https://github.com/JinfanChris/TJU-2022-Socket-Computer-Network-Lab '/storage/nvme5/new_clones/PostScript/TJU-2022-Socket-Computer-Network-Lab' &
git clone https://github.com/caiogondim/javascript-environments-logos '/storage/nvme5/new_clones/PostScript/javascript-environments-logos' &
git clone https://github.com/carltape/surfacevel2strain '/storage/nvme5/new_clones/PostScript/surfacevel2strain' &
git clone https://github.com/lessthanoptimal/BoofCV-Data '/storage/nvme5/new_clones/PostScript/BoofCV-Data' &
git clone https://github.com/juntuu/advent_of_code_2021 '/storage/nvme5/new_clones/PostScript/advent_of_code_2021' &
git clone https://github.com/wlxiong/TrafficAssign '/storage/nvme5/new_clones/PostScript/TrafficAssign' &
git clone https://github.com/wurstbrot/docker-security-workshop '/storage/nvme5/new_clones/PostScript/docker-security-workshop' &
git clone https://github.com/EngreitzLab/ABC-GWAS-Paper '/storage/nvme5/new_clones/PostScript/ABC-GWAS-Paper' &
git clone https://github.com/devicetree-org/devicetree-website '/storage/nvme5/new_clones/PostScript/devicetree-website' &
git clone https://github.com/Raz0r/evil-nft '/storage/nvme5/new_clones/PostScript/evil-nft' &
git clone https://github.com/elsys/oop '/storage/nvme5/new_clones/PostScript/oop' &
git clone https://github.com/TurtleThread/TurtleThread '/storage/nvme5/new_clones/PostScript/TurtleThread' &
git clone https://github.com/XQuartz/xquartz-old-tickets '/storage/nvme5/new_clones/PostScript/xquartz-old-tickets' &
git clone https://github.com/MaZhengg/NKUthesis '/storage/nvme5/new_clones/PostScript/NKUthesis' &
git clone https://github.com/cyphar/talks '/storage/nvme5/new_clones/PostScript/talks' &
git clone https://github.com/darrenjw/djwhacks '/storage/nvme5/new_clones/PostScript/djwhacks' &
git clone https://github.com/zick/Lisp-on-Printers '/storage/nvme5/new_clones/PostScript/Lisp-on-Printers' &
git clone https://github.com/NCAR/RadarAnalysisTools '/storage/nvme5/new_clones/PostScript/RadarAnalysisTools' &
git clone https://github.com/FreeFem/FreeFem-days '/storage/nvme5/new_clones/PostScript/FreeFem-days' &
git clone https://github.com/adobe-fonts/locl-test '/storage/nvme5/new_clones/PostScript/locl-test' &
git clone https://github.com/adobe-fonts/tombo-sp '/storage/nvme5/new_clones/PostScript/tombo-sp' &
git clone https://github.com/ProfTuan/AMIA-Latex-Template '/storage/nvme5/new_clones/PostScript/AMIA-Latex-Template' &
git clone https://github.com/vcaldas/Groningen-thesis-template '/storage/nvme5/new_clones/PostScript/Groningen-thesis-template' &
git clone https://github.com/veromary/littleOffice '/storage/nvme5/new_clones/PostScript/littleOffice' &
git clone https://github.com/18xx/ps18xx '/storage/nvme5/new_clones/PostScript/ps18xx' &
git clone https://github.com/hskang0906/DTI-Prediction '/storage/nvme5/new_clones/PostScript/DTI-Prediction' &
git clone https://github.com/MaOEA/DMOES '/storage/nvme5/new_clones/PostScript/DMOES' &
git clone https://github.com/mHealthGroup/MIMSunit '/storage/nvme5/new_clones/PostScript/MIMSunit' &
git clone https://github.com/tyokoyama/golangcafe '/storage/nvme5/new_clones/PostScript/golangcafe' &
git clone https://github.com/ivansostarko/postscript-examples '/storage/nvme5/new_clones/PostScript/postscript-examples' &
git clone https://github.com/blmoore/pdf2eps-osx '/storage/nvme5/new_clones/PostScript/pdf2eps-osx' &
git clone https://github.com/karlrupp/spgemm-mkl-benchmark '/storage/nvme5/new_clones/PostScript/spgemm-mkl-benchmark' &
git clone https://github.com/DingGuohui/R-for-beginer '/storage/nvme5/new_clones/PostScript/R-for-beginer' &
git clone https://github.com/lewdlime/SublimeTextSyntaxes '/storage/nvme5/new_clones/PostScript/SublimeTextSyntaxes' &
git clone https://github.com/Cuiyingzhe/OUC-Physical-Oceanography-Notes '/storage/nvme5/new_clones/PostScript/OUC-Physical-Oceanography-Notes' &
git clone https://github.com/OpenBazaar/PressKit '/storage/nvme5/new_clones/PostScript/PressKit' &
git clone https://github.com/zardam/nw-external-apps '/storage/nvme5/new_clones/PostScript/nw-external-apps' &
git clone https://github.com/CenterForOpenScience/rpp '/storage/nvme5/new_clones/PostScript/rpp' &
git clone https://github.com/ranzhaocgu/Empirical-Asset-Pricing '/storage/nvme5/new_clones/PostScript/Empirical-Asset-Pricing' &
git clone https://github.com/naseeihity/xmu-latex-temple '/storage/nvme5/new_clones/PostScript/xmu-latex-temple' &
git clone https://github.com/code4lib/2016.code4lib.org '/storage/nvme5/new_clones/PostScript/2016.code4lib.org' &
git clone https://github.com/javierblasco/repipy '/storage/nvme5/new_clones/PostScript/repipy' &
git clone https://github.com/SchlossLab/Hannigan_CRCVirome_mBio_2018 '/storage/nvme5/new_clones/PostScript/Hannigan_CRCVirome_mBio_2018' &
git clone https://github.com/flightaware/piaware-support '/storage/nvme5/new_clones/PostScript/piaware-support' &
git clone https://github.com/usnistgov/SVClassify '/storage/nvme5/new_clones/PostScript/SVClassify' &
git clone https://github.com/aaschwanden/uaf-beamer '/storage/nvme5/new_clones/PostScript/uaf-beamer' &
git clone https://github.com/scgt/l1magic '/storage/nvme5/new_clones/PostScript/l1magic' &
git clone https://github.com/ibillxia/zjuthesis '/storage/nvme5/new_clones/PostScript/zjuthesis' &
git clone https://github.com/BrianEnigma/Arduino '/storage/nvme5/new_clones/PostScript/Arduino' &
git clone https://github.com/thelfer/tfel-doc '/storage/nvme5/new_clones/PostScript/tfel-doc' &
git clone https://github.com/834810071/NEUBachelorThesis2019 '/storage/nvme5/new_clones/PostScript/NEUBachelorThesis2019' &
git clone https://github.com/KupinFB/Adobe-HTML-Extension-Drag-and-Drop '/storage/nvme5/new_clones/PostScript/Adobe-HTML-Extension-Drag-and-Drop' &
git clone https://github.com/fukushimalab/AFXW '/storage/nvme5/new_clones/PostScript/AFXW' &
git clone https://github.com/hairymnstr/Z80-Project-Mark-2 '/storage/nvme5/new_clones/PostScript/Z80-Project-Mark-2' &
git clone https://github.com/aishfenton/thesis '/storage/nvme5/new_clones/PostScript/thesis' &
git clone https://github.com/emir-munoz/tesis-usach '/storage/nvme5/new_clones/PostScript/tesis-usach' &
git clone https://github.com/lpatters/pdfspin '/storage/nvme5/new_clones/PostScript/pdfspin' &
git clone https://github.com/kcufId/eps-CVE-2017-0261 '/storage/nvme5/new_clones/PostScript/eps-CVE-2017-0261' &
git clone https://github.com/astrosonnen/pygalaxev '/storage/nvme5/new_clones/PostScript/pygalaxev' &
git clone https://github.com/vbatts/slackbook '/storage/nvme5/new_clones/PostScript/slackbook' &
git clone https://github.com/adobe-fonts/ivs-test '/storage/nvme5/new_clones/PostScript/ivs-test' &
git clone https://github.com/rnowling/bigpetstore-data-generator '/storage/nvme5/new_clones/PostScript/bigpetstore-data-generator' &
git clone https://github.com/mashengcheng/URLLC '/storage/nvme5/new_clones/PostScript/URLLC' &
git clone https://github.com/chkummer/PunchedCard '/storage/nvme5/new_clones/PostScript/PunchedCard' &
git clone https://github.com/usgs/pager '/storage/nvme5/new_clones/PostScript/pager' &
git clone https://github.com/vsdip/avsdbgp_3v3_sky130_v1 '/storage/nvme5/new_clones/PostScript/avsdbgp_3v3_sky130_v1' &
git clone https://github.com/stiber/Signal-Computing '/storage/nvme5/new_clones/PostScript/Signal-Computing' &
git clone https://github.com/BitLaunchIO/docker-electrum-personal-server '/storage/nvme5/new_clones/PostScript/docker-electrum-personal-server' &
git clone https://github.com/ssanner/xadd-inference '/storage/nvme5/new_clones/PostScript/xadd-inference' &
git clone https://github.com/steverweber/influxdb-metrics-vmware '/storage/nvme5/new_clones/PostScript/influxdb-metrics-vmware' &
git clone https://github.com/punkdit/categories '/storage/nvme5/new_clones/PostScript/categories' &
git clone https://github.com/shouguicai/SCFNN '/storage/nvme5/new_clones/PostScript/SCFNN' &
git clone https://github.com/MaOEA/DN-MMOES '/storage/nvme5/new_clones/PostScript/DN-MMOES' &
git clone https://github.com/op3/latex-pdfa-howto '/storage/nvme5/new_clones/PostScript/latex-pdfa-howto' &
git clone https://github.com/nalimcos/VibComp '/storage/nvme5/new_clones/PostScript/VibComp' &
git clone https://github.com/metaphori/Template-LaTeX-MDPI '/storage/nvme5/new_clones/PostScript/Template-LaTeX-MDPI' &
git clone https://github.com/dsandwell/fftfault '/storage/nvme5/new_clones/PostScript/fftfault' &
git clone https://github.com/SwordYork/MachineLearning '/storage/nvme5/new_clones/PostScript/MachineLearning' &
git clone https://github.com/psu-libraries/contentdmtools '/storage/nvme5/new_clones/PostScript/contentdmtools' &
git clone https://github.com/jayrichardjohnson/utdiss3 '/storage/nvme5/new_clones/PostScript/utdiss3' &
git clone https://github.com/davidaustinm/ula '/storage/nvme5/new_clones/PostScript/ula' &
git clone https://github.com/dockimbel/printer-driver '/storage/nvme5/new_clones/PostScript/printer-driver' &
git clone https://github.com/jiedxu/WindPowerForecast '/storage/nvme5/new_clones/PostScript/WindPowerForecast' &
git clone https://github.com/blake5634/Models_of_Robot_Manipulation '/storage/nvme5/new_clones/PostScript/Models_of_Robot_Manipulation' &
git clone https://github.com/saketkc/moca '/storage/nvme5/new_clones/PostScript/moca' &
git clone https://github.com/edamame-course/2018-Tutorials '/storage/nvme5/new_clones/PostScript/2018-Tutorials' &
git clone https://github.com/voxpupuli/puppet-amanda '/storage/nvme5/new_clones/PostScript/puppet-amanda' &
git clone https://github.com/applitools/ImageTester '/storage/nvme5/new_clones/PostScript/ImageTester' &
git clone https://github.com/kajboj/plotter '/storage/nvme5/new_clones/PostScript/plotter' &
git clone https://github.com/arnoldrobbins/cstr100 '/storage/nvme5/new_clones/PostScript/cstr100' &
git clone https://github.com/fvicente/bios-hack '/storage/nvme5/new_clones/PostScript/bios-hack' &
git clone https://github.com/elsys/oop-2016-2017 '/storage/nvme5/new_clones/PostScript/oop-2016-2017' &
git clone https://github.com/pcayuela/oldftpETHZOberon '/storage/nvme5/new_clones/PostScript/oldftpETHZOberon' &
git clone https://github.com/henryseg/Fibonacci_designs '/storage/nvme5/new_clones/PostScript/Fibonacci_designs' &
git clone https://github.com/lvyu-imech/PyVT '/storage/nvme5/new_clones/PostScript/PyVT' &
git clone https://github.com/scriptituk/pslutils '/storage/nvme5/new_clones/PostScript/pslutils' &
git clone https://github.com/saraivacode/framework_its_sdn '/storage/nvme5/new_clones/PostScript/framework_its_sdn' &
git clone https://github.com/ltauxe/Essentials-of-Paleomagnetism '/storage/nvme5/new_clones/PostScript/Essentials-of-Paleomagnetism' &
git clone https://github.com/ETCE-LAB/teaching-material '/storage/nvme5/new_clones/PostScript/teaching-material' &
git clone https://github.com/b2slab/genedise '/storage/nvme5/new_clones/PostScript/genedise' &
git clone https://github.com/lawrennd/mltools '/storage/nvme5/new_clones/PostScript/mltools' &
git clone https://github.com/dimitri/pgconfs '/storage/nvme5/new_clones/PostScript/pgconfs' &
git clone https://github.com/jbrussell/Simple_X '/storage/nvme5/new_clones/PostScript/Simple_X' &
git clone https://github.com/PavelStransky/Chaos '/storage/nvme5/new_clones/PostScript/Chaos' &
git clone https://github.com/xinmeng/metahdl '/storage/nvme5/new_clones/PostScript/metahdl' &
git clone https://github.com/TAMS-Group/tams_apriltags '/storage/nvme5/new_clones/PostScript/tams_apriltags' &
git clone https://github.com/rossb34/PortfolioAnalytics '/storage/nvme5/new_clones/PostScript/PortfolioAnalytics' &
git clone https://github.com/john77eipe/DeepQA '/storage/nvme5/new_clones/PostScript/DeepQA' &
git clone https://github.com/nsbasic-archive/NS-Basic-for-Newton-OS '/storage/nvme5/new_clones/PostScript/NS-Basic-for-Newton-OS' &
git clone https://github.com/AgFlore/GeneralPhysicsLab '/storage/nvme5/new_clones/PostScript/GeneralPhysicsLab' &
git clone https://github.com/MarioniLab/PlateEffects2016 '/storage/nvme5/new_clones/PostScript/PlateEffects2016' &
git clone https://github.com/ehpale/elaphe '/storage/nvme5/new_clones/PostScript/elaphe' &
git clone https://github.com/leboudec/netcal '/storage/nvme5/new_clones/PostScript/netcal' &
git clone https://github.com/flwyd/adventofcode '/storage/nvme5/new_clones/PostScript/adventofcode' &
git clone https://github.com/dubilava/theguessproject '/storage/nvme5/new_clones/PostScript/theguessproject' &
git clone https://github.com/maminian/uncmathbeamer '/storage/nvme5/new_clones/PostScript/uncmathbeamer' &
git clone https://github.com/active-calculus/prep '/storage/nvme5/new_clones/PostScript/prep' &
git clone https://github.com/uafgeotools/capuaf '/storage/nvme5/new_clones/PostScript/capuaf' &
git clone https://github.com/postgresqlfr/pgfr_materials '/storage/nvme5/new_clones/PostScript/pgfr_materials' &
git clone https://github.com/lyk6756/XFEM_2D '/storage/nvme5/new_clones/PostScript/XFEM_2D' &
git clone https://github.com/MarczalTSIGP/latex-utfpr-proposta-tcc '/storage/nvme5/new_clones/PostScript/latex-utfpr-proposta-tcc' &
git clone https://github.com/notengrafik/fdf2xfdf '/storage/nvme5/new_clones/PostScript/fdf2xfdf' &
git clone https://github.com/hbhat4000/sdeinference '/storage/nvme5/new_clones/PostScript/sdeinference' &
git clone https://github.com/roblehmann/NinjaPBR '/storage/nvme5/new_clones/PostScript/NinjaPBR' &
git clone https://github.com/SigurdAngenent/WisconsinCalculus '/storage/nvme5/new_clones/PostScript/WisconsinCalculus' &
git clone https://github.com/stephaneguindon/fitmodel '/storage/nvme5/new_clones/PostScript/fitmodel' &
git clone https://github.com/andrew-edwards/fitting-size-spectra '/storage/nvme5/new_clones/PostScript/fitting-size-spectra' &
git clone https://github.com/phrb/legup-tuner '/storage/nvme5/new_clones/PostScript/legup-tuner' &
git clone https://github.com/dcoeurjo/lectureDG '/storage/nvme5/new_clones/PostScript/lectureDG' &
git clone https://github.com/dylanmikesell/BSU_LaTeX_Thesis_Template '/storage/nvme5/new_clones/PostScript/BSU_LaTeX_Thesis_Template' &
git clone https://github.com/robvandenbrink/windows_log_gaps '/storage/nvme5/new_clones/PostScript/windows_log_gaps' &
git clone https://github.com/indraastra/designs '/storage/nvme5/new_clones/PostScript/designs' &
git clone https://github.com/digitalmacgyver/quant '/storage/nvme5/new_clones/PostScript/quant' &
git clone https://github.com/baogegeJiang/jPicker '/storage/nvme5/new_clones/PostScript/jPicker' &
git clone https://github.com/adobe-fonts/cjk-radicals '/storage/nvme5/new_clones/PostScript/cjk-radicals' &
git clone https://github.com/ULVZ-Database/ULVZ-Database '/storage/nvme5/new_clones/PostScript/ULVZ-Database' &
git clone https://github.com/paircolumbus/paircolumbus.github.io '/storage/nvme5/new_clones/PostScript/paircolumbushub.io' &
git clone https://github.com/applied-numerical-algorithms-group-lbnl/Chombo_4 '/storage/nvme5/new_clones/PostScript/Chombo_4' &
git clone https://github.com/adobe-fonts/css-orientation-test '/storage/nvme5/new_clones/PostScript/css-orientation-test' &
git clone https://github.com/scriptituk/ttf2pscid2 '/storage/nvme5/new_clones/PostScript/ttf2pscid2' &
git clone https://github.com/RobArthan/pp '/storage/nvme5/new_clones/PostScript/pp' &
git clone https://github.com/mxstbr/old-personal-website '/storage/nvme5/new_clones/PostScript/old-personal-website' &
git clone https://github.com/jbush001/DrawWaveform '/storage/nvme5/new_clones/PostScript/DrawWaveform' &
git clone https://github.com/MaOEA/MMO-MOES '/storage/nvme5/new_clones/PostScript/MMO-MOES' &
git clone https://github.com/mcoia/webpacs-swan '/storage/nvme5/new_clones/PostScript/webpacs-swan' &
git clone https://github.com/kerrydu/xtplfc_Stata '/storage/nvme5/new_clones/PostScript/xtplfc_Stata' &
git clone https://github.com/mpascariu/MortalityEstimate '/storage/nvme5/new_clones/PostScript/MortalityEstimate' &
git clone https://github.com/HFUT-BinChen/HFUT-Beamer '/storage/nvme5/new_clones/PostScript/HFUT-Beamer' &
git clone https://github.com/RobbinBouwmeester/tRPredictionOverview '/storage/nvme5/new_clones/PostScript/tRPredictionOverview' &
git clone https://github.com/f-klubben/sangbog '/storage/nvme5/new_clones/PostScript/sangbog' &
git clone https://github.com/osgeouk/website '/storage/nvme5/new_clones/PostScript/website' &
git clone https://github.com/tigoe/timepieces '/storage/nvme5/new_clones/PostScript/timepieces' &
git clone https://github.com/jbreitenbucher/exampleis '/storage/nvme5/new_clones/PostScript/exampleis' &
git clone https://github.com/mdsumner/utas_latex_thesis '/storage/nvme5/new_clones/PostScript/utas_latex_thesis' &
git clone https://github.com/jwcxz/ACRIS '/storage/nvme5/new_clones/PostScript/ACRIS' &
git clone https://github.com/tpf/marketing-materials '/storage/nvme5/new_clones/PostScript/marketing-materials' &
git clone https://github.com/data-lessons/dh-openrefine '/storage/nvme5/new_clones/PostScript/dh-openrefine' &
git clone https://github.com/rlutz/voctoknopf '/storage/nvme5/new_clones/PostScript/voctoknopf' &
git clone https://github.com/28shambhavi/Quantum-Espresso-DOP '/storage/nvme5/new_clones/PostScript/Quantum-Espresso-DOP' &
git clone https://github.com/k16shikano/new-year-cards '/storage/nvme5/new_clones/PostScript/new-year-cards' &
git clone https://github.com/Ondiz/academicWriting '/storage/nvme5/new_clones/PostScript/academicWriting' &
git clone https://github.com/lqbrin/tea-time-linear '/storage/nvme5/new_clones/PostScript/tea-time-linear' &
git clone https://github.com/hbueno/eage2016-avo '/storage/nvme5/new_clones/PostScript/eage2016-avo' &
git clone https://github.com/ichibha/setupMaezono '/storage/nvme5/new_clones/PostScript/setupMaezono' &
git clone https://github.com/AllenDowney/complexity '/storage/nvme5/new_clones/PostScript/complexity' &
git clone https://github.com/n8upham/MamPhy_v1 '/storage/nvme5/new_clones/PostScript/MamPhy_v1' &
git clone https://github.com/zimmerrol/rcp_spatio_temporal '/storage/nvme5/new_clones/PostScript/rcp_spatio_temporal' &
git clone https://github.com/NERC-CEH/ebms-app '/storage/nvme5/new_clones/PostScript/ebms-app' &
git clone https://github.com/fronchetti/SANER-2018 '/storage/nvme5/new_clones/PostScript/SANER-2018' &
git clone https://github.com/AkshitOstwal/Resume-sorter-BOT '/storage/nvme5/new_clones/PostScript/Resume-sorter-BOT' &
git clone https://github.com/juba/intro-r '/storage/nvme5/new_clones/PostScript/intro-r' &
git clone https://github.com/davidstutz/iccv2021-robust-flatness '/storage/nvme5/new_clones/PostScript/iccv2021-robust-flatness' &
git clone https://github.com/decentespresso/de1plus_psd '/storage/nvme5/new_clones/PostScript/de1plus_psd' &
git clone https://github.com/lzhbrian/MCMC '/storage/nvme5/new_clones/PostScript/MCMC' &
git clone https://github.com/adithyasunil26/2.87GHz-MWG-MPW5 '/storage/nvme5/new_clones/PostScript/2.87GHz-MWG-MPW5' &
git clone https://github.com/gtkfi/MapWizard '/storage/nvme5/new_clones/PostScript/MapWizard' &
git clone https://github.com/emilyyt/tamagotchi-arduino '/storage/nvme5/new_clones/PostScript/tamagotchi-arduino' &
git clone https://github.com/marcelgoh/organic-trees '/storage/nvme5/new_clones/PostScript/organic-trees' &
git clone https://github.com/zotherstupidguy/algo '/storage/nvme5/new_clones/PostScript/algo' &
git clone https://github.com/eitanf/sysconf '/storage/nvme5/new_clones/PostScript/sysconf' &
git clone https://github.com/mgrzy/Maize_Genetic_Variants_v5 '/storage/nvme5/new_clones/PostScript/Maize_Genetic_Variants_v5' &
git clone https://github.com/jtorrents/thesis '/storage/nvme5/new_clones/PostScript/thesis' &
git clone https://github.com/tr1813/migresurvey '/storage/nvme5/new_clones/PostScript/migresurvey' &
git clone https://github.com/thtuerk/ITP-course '/storage/nvme5/new_clones/PostScript/ITP-course' &
git clone https://github.com/ShadeLab/PAPER_Shade_CurrOpinMicro '/storage/nvme5/new_clones/PostScript/PAPER_Shade_CurrOpinMicro' &
git clone https://github.com/blab/antigenic-clustering '/storage/nvme5/new_clones/PostScript/antigenic-clustering' &
git clone https://github.com/khorton/POH '/storage/nvme5/new_clones/PostScript/POH' &
git clone https://github.com/ashwinvis/phd-thesis '/storage/nvme5/new_clones/PostScript/phd-thesis' &
git clone https://github.com/calvinwhealton/SensitivityAnalysisPlots '/storage/nvme5/new_clones/PostScript/SensitivityAnalysisPlots' &
git clone https://github.com/luser-dr00g/cv '/storage/nvme5/new_clones/PostScript/cv' &
git clone https://github.com/OMDoc/OMDoc '/storage/nvme5/new_clones/PostScript/OMDoc' &
git clone https://github.com/ireapps/nicar18-intro-to-r '/storage/nvme5/new_clones/PostScript/nicar18-intro-to-r' &
git clone https://github.com/kks32/phd-thesis '/storage/nvme5/new_clones/PostScript/phd-thesis' &
git clone https://github.com/witness/Conducting-Interviews-with-Survivors-of-Gender-Based-Violence '/storage/nvme5/new_clones/PostScript/Conducting-Interviews-with-Survivors-of-Gender-Based-Violence' &
git clone https://github.com/S120/benchmark '/storage/nvme5/new_clones/PostScript/benchmark' &
git clone https://github.com/NCAR/lrose-cedric '/storage/nvme5/new_clones/PostScript/lrose-cedric' &
git clone https://github.com/james2doyle/xdebug-devtools '/storage/nvme5/new_clones/PostScript/xdebug-devtools' &
git clone https://github.com/project-trident/trident-artwork '/storage/nvme5/new_clones/PostScript/trident-artwork' &
git clone https://github.com/joeroe/SWAsiaNeolithicFounderCrops '/storage/nvme5/new_clones/PostScript/SWAsiaNeolithicFounderCrops' &
git clone https://github.com/mit212/me212lab3 '/storage/nvme5/new_clones/PostScript/me212lab3' &
git clone https://github.com/cunxi1992/turtle_American_shield '/storage/nvme5/new_clones/PostScript/turtle_American_shield' &
git clone https://github.com/altanai/webrtcsignaller '/storage/nvme5/new_clones/PostScript/webrtcsignaller' &
git clone https://github.com/rcslab/cs350 '/storage/nvme5/new_clones/PostScript/cs350' &
git clone https://github.com/kpzoo/model-selection-for-epidemic-renewal-models '/storage/nvme5/new_clones/PostScript/model-selection-for-epidemic-renewal-models' &
git clone https://github.com/rejecta/mathematica '/storage/nvme5/new_clones/PostScript/mathematica' &
git clone https://github.com/gruvin/gruvin9x '/storage/nvme5/new_clones/PostScript/gruvin9x' &
git clone https://github.com/HIPERCUBE/ReturnA '/storage/nvme5/new_clones/PostScript/ReturnA' &
git clone https://github.com/eriu/beamer-ovgu '/storage/nvme5/new_clones/PostScript/beamer-ovgu' &
git clone https://github.com/sambhipiyush/Crash-Course-on-Python-Google '/storage/nvme5/new_clones/PostScript/Crash-Course-on-Python-Google' &
