#!/bin/bash

git clone https://github.com/nasa-jpl/open-source-rover '/storage/nvme5/new_clones/Prolog/open-source-rover' &
git clone https://github.com/terminusdb/terminusdb '/storage/nvme5/new_clones/Prolog/terminusdb' &
git clone https://github.com/fossasia/pslab-hardware '/storage/nvme5/new_clones/Prolog/pslab-hardware' &
git clone https://github.com/Anniepoo/prolog-examples '/storage/nvme5/new_clones/Prolog/prolog-examples' &
git clone https://github.com/ccurtsinger/stabilizer '/storage/nvme5/new_clones/Prolog/stabilizer' &
git clone https://github.com/bitlaw-jp/the-constitution-of-japan '/storage/nvme5/new_clones/Prolog/the-constitution-of-japan' &
git clone https://github.com/magda-io/magda '/storage/nvme5/new_clones/Prolog/magda' &
git clone https://github.com/SWI-Prolog/swish '/storage/nvme5/new_clones/Prolog/swish' &
git clone https://github.com/LogtalkDotOrg/logtalk3 '/storage/nvme5/new_clones/Prolog/logtalk3' &
git clone https://github.com/larsyencken/marelle '/storage/nvme5/new_clones/Prolog/marelle' &
git clone https://github.com/ronilaukkarinen/weed '/storage/nvme5/new_clones/Prolog/weed' &
git clone https://github.com/dragonwasrobot/learn-prolog-now-exercises '/storage/nvme5/new_clones/Prolog/learn-prolog-now-exercises' &
git clone https://github.com/c-cube/datalog '/storage/nvme5/new_clones/Prolog/datalog' &
git clone https://github.com/pebri86/esplay_micro_hardware '/storage/nvme5/new_clones/Prolog/esplay_micro_hardware' &
git clone https://github.com/sebschub/FontPro '/storage/nvme5/new_clones/Prolog/FontPro' &
git clone https://github.com/metagol/metagol '/storage/nvme5/new_clones/Prolog/metagol' &
git clone https://github.com/Emeryth/iPad3_lcd '/storage/nvme5/new_clones/Prolog/iPad3_lcd' &
git clone https://github.com/Attempto/APE '/storage/nvme5/new_clones/Prolog/APE' &
git clone https://github.com/triska/clpz '/storage/nvme5/new_clones/Prolog/clpz' &
git clone https://github.com/strangeloop/StrangeLoop2014 '/storage/nvme5/new_clones/Prolog/StrangeLoop2014' &
git clone https://github.com/triska/clpfd '/storage/nvme5/new_clones/Prolog/clpfd' &
git clone https://github.com/dtonhofer/prolog_notes '/storage/nvme5/new_clones/Prolog/prolog_notes' &
git clone https://github.com/gooofy/zamia-ai '/storage/nvme5/new_clones/Prolog/zamia-ai' &
git clone https://github.com/fnogatz/xsd2json '/storage/nvme5/new_clones/Prolog/xsd2json' &
git clone https://github.com/triska/lisprolog '/storage/nvme5/new_clones/Prolog/lisprolog' &
git clone https://github.com/simply-logical/simply-logical '/storage/nvme5/new_clones/Prolog/simply-logical' &
git clone https://github.com/openpst/openpst '/storage/nvme5/new_clones/Prolog/openpst' &
git clone https://github.com/jgilfillan/Niz-Plum-84EC-S-Pro-Ble-Non-RGB-manual '/storage/nvme5/new_clones/Prolog/Niz-Plum-84EC-S-Pro-Ble-Non-RGB-manual' &
git clone https://github.com/motools/musicontology '/storage/nvme5/new_clones/Prolog/musicontology' &
git clone https://github.com/stassa/louise '/storage/nvme5/new_clones/Prolog/louise' &
git clone https://github.com/JCumin/Brachylog '/storage/nvme5/new_clones/Prolog/Brachylog' &
git clone https://github.com/kovvalsky/LangPro '/storage/nvme5/new_clones/Prolog/LangPro' &
git clone https://github.com/Anniepoo/swiplwebtut '/storage/nvme5/new_clones/Prolog/swiplwebtut' &
git clone https://github.com/vangelisv/thea '/storage/nvme5/new_clones/Prolog/thea' &
git clone https://github.com/geohot/twitchcoq '/storage/nvme5/new_clones/Prolog/twitchcoq' &
git clone https://github.com/evoldoers/biomake '/storage/nvme5/new_clones/Prolog/biomake' &
git clone https://github.com/brunohorta82/BH_OnOfre '/storage/nvme5/new_clones/Prolog/BH_OnOfre' &
git clone https://github.com/math-comp/hierarchy-builder '/storage/nvme5/new_clones/Prolog/hierarchy-builder' &
git clone https://github.com/HackerUniverse/Reconcobra '/storage/nvme5/new_clones/Prolog/Reconcobra' &
git clone https://github.com/aarroyoc/postgresql-prolog '/storage/nvme5/new_clones/Prolog/postgresql-prolog' &
git clone https://github.com/jamesnvc/lsp_server '/storage/nvme5/new_clones/Prolog/lsp_server' &
git clone https://github.com/stassa/Gleemin '/storage/nvme5/new_clones/Prolog/Gleemin' &
git clone https://github.com/wouterbeek/prolog_library_collection '/storage/nvme5/new_clones/Prolog/prolog_library_collection' &
git clone https://github.com/csplib/csplib '/storage/nvme5/new_clones/Prolog/csplib' &
git clone https://github.com/cubewise-code/bedrock '/storage/nvme5/new_clones/Prolog/bedrock' &
git clone https://github.com/ianthehenry/mixologician '/storage/nvme5/new_clones/Prolog/mixologician' &
git clone https://github.com/xmonader/prolog-rands '/storage/nvme5/new_clones/Prolog/prolog-rands' &
git clone https://github.com/friguzzi/cplint '/storage/nvme5/new_clones/Prolog/cplint' &
git clone https://github.com/alhassy/PrologCheatSheet '/storage/nvme5/new_clones/Prolog/PrologCheatSheet' &
git clone https://github.com/rachelwiles/GoT-Check '/storage/nvme5/new_clones/Prolog/GoT-Check' &
git clone https://github.com/spectector/spectector '/storage/nvme5/new_clones/Prolog/spectector' &
git clone https://github.com/OldUnreal/Unreal-testing '/storage/nvme5/new_clones/Prolog/Unreal-testing' &
git clone https://github.com/LHNCBC/SemRep '/storage/nvme5/new_clones/Prolog/SemRep' &
git clone https://github.com/OpenSprinkler/OpenSprinkler-Hardware '/storage/nvme5/new_clones/Prolog/OpenSprinkler-Hardware' &
git clone https://github.com/CarlosGS/Open-Radiation-Detector '/storage/nvme5/new_clones/Prolog/Open-Radiation-Detector' &
git clone https://github.com/kikito/7-languages-in-7-weeks '/storage/nvme5/new_clones/Prolog/7-languages-in-7-weeks' &
git clone https://github.com/akiym/akictf2013 '/storage/nvme5/new_clones/Prolog/akictf2013' &
git clone https://github.com/kiedtl/dotfiles '/storage/nvme5/new_clones/Prolog/dotfiles' &
git clone https://github.com/LOD-Laundromat/LOD-Laundromat '/storage/nvme5/new_clones/Prolog/LOD-Laundromat' &
git clone https://github.com/ClioPatria/ClioPatria '/storage/nvme5/new_clones/Prolog/ClioPatria' &
git clone https://github.com/YanaRGeorgieva/Logic-programming '/storage/nvme5/new_clones/Prolog/Logic-programming' &
git clone https://github.com/hairykiwi/OTM-02 '/storage/nvme5/new_clones/Prolog/OTM-02' &
git clone https://github.com/mrkkrp/lpnes '/storage/nvme5/new_clones/Prolog/lpnes' &
git clone https://github.com/cmungall/sparqlprog '/storage/nvme5/new_clones/Prolog/sparqlprog' &
git clone https://github.com/Ttreintaysiete/chaves '/storage/nvme5/new_clones/Prolog/chaves' &
git clone https://github.com/khueue/prolongo '/storage/nvme5/new_clones/Prolog/prolongo' &
git clone https://github.com/friguzzi/aleph '/storage/nvme5/new_clones/Prolog/aleph' &
git clone https://github.com/Wilm0rien/EveOnlineMiningYield '/storage/nvme5/new_clones/Prolog/EveOnlineMiningYield' &
git clone https://github.com/linkyndy/expert-systems '/storage/nvme5/new_clones/Prolog/expert-systems' &
git clone https://github.com/norswap/prolog-dry '/storage/nvme5/new_clones/Prolog/prolog-dry' &
git clone https://github.com/mndrix/microkanren-prolog '/storage/nvme5/new_clones/Prolog/microkanren-prolog' &
git clone https://github.com/Vulwsztyn/prolog-for-dummies '/storage/nvme5/new_clones/Prolog/prolog-for-dummies' &
git clone https://github.com/ridgeworks/clpBNR '/storage/nvme5/new_clones/Prolog/clpBNR' &
git clone https://github.com/AAAI-DISIM-UnivAQ/DALI '/storage/nvme5/new_clones/Prolog/DALI' &
git clone https://github.com/triska/clpb '/storage/nvme5/new_clones/Prolog/clpb' &
git clone https://github.com/jbschooley/MCSLI '/storage/nvme5/new_clones/Prolog/MCSLI' &
git clone https://github.com/fcampanini/Motorized-Fader-as-DAW-Mixer-Controller-BOARD-DESIGN- '/storage/nvme5/new_clones/Prolog/Motorized-Fader-as-DAW-Mixer-Controller-BOARD-DESIGN-' &
git clone https://github.com/triska/letswicrypt '/storage/nvme5/new_clones/Prolog/letswicrypt' &
git clone https://github.com/kernd/LIT-Eagle '/storage/nvme5/new_clones/Prolog/LIT-Eagle' &
git clone https://github.com/mikeroyal/Expert-Systems-Guide '/storage/nvme5/new_clones/Prolog/Expert-Systems-Guide' &
git clone https://github.com/Kaljurand/owl-verbalizer '/storage/nvme5/new_clones/Prolog/owl-verbalizer' &
git clone https://github.com/FICS/BigMAC '/storage/nvme5/new_clones/Prolog/BigMAC' &
git clone https://github.com/pdep-utn/enunciados-miercoles-noche '/storage/nvme5/new_clones/Prolog/enunciados-miercoles-noche' &
git clone https://github.com/npe9/aop '/storage/nvme5/new_clones/Prolog/aop' &
git clone https://github.com/Anniepoo/swipldcgtut '/storage/nvme5/new_clones/Prolog/swipldcgtut' &
git clone https://github.com/Duke-PL-Course/Prolog '/storage/nvme5/new_clones/Prolog/Prolog' &
git clone https://github.com/jamespwilliams/prolog-isolation-checker '/storage/nvme5/new_clones/Prolog/prolog-isolation-checker' &
git clone https://github.com/shift-crops/CTFWriteups '/storage/nvme5/new_clones/Prolog/CTFWriteups' &
git clone https://github.com/ptarau/TypesAndProofs '/storage/nvme5/new_clones/Prolog/TypesAndProofs' &
git clone https://github.com/rla/simple-template '/storage/nvme5/new_clones/Prolog/simple-template' &
git clone https://github.com/mrkindustries/openPSU '/storage/nvme5/new_clones/Prolog/openPSU' &
git clone https://github.com/exercism/prolog '/storage/nvme5/new_clones/Prolog/prolog' &
git clone https://github.com/nicoladileo/NephroDoctor '/storage/nvme5/new_clones/Prolog/NephroDoctor' &
git clone https://github.com/LogicalContracts/LogicalEnglish '/storage/nvme5/new_clones/Prolog/LogicalEnglish' &
git clone https://github.com/SWI-Prolog/packages-semweb '/storage/nvme5/new_clones/Prolog/packages-semweb' &
git clone https://github.com/jamesbvaughan/httppl '/storage/nvme5/new_clones/Prolog/httppl' &
git clone https://github.com/openmeddev/MobilECG-II '/storage/nvme5/new_clones/Prolog/MobilECG-II' &
git clone https://github.com/ekaf/wordnet-prolog '/storage/nvme5/new_clones/Prolog/wordnet-prolog' &
git clone https://github.com/logicmoo/prologmud '/storage/nvme5/new_clones/Prolog/prologmud' &
git clone https://github.com/maths/PRESS '/storage/nvme5/new_clones/Prolog/PRESS' &
git clone https://github.com/EricLu1218/Physical_Design_Automation '/storage/nvme5/new_clones/Prolog/Physical_Design_Automation' &
git clone https://github.com/dcnorris/precautionary '/storage/nvme5/new_clones/Prolog/precautionary' &
git clone https://github.com/dmkfasi/nus-cpu '/storage/nvme5/new_clones/Prolog/nus-cpu' &
git clone https://github.com/kyledewey/typed-prolog '/storage/nvme5/new_clones/Prolog/typed-prolog' &
git clone https://github.com/fifth-postulate/julian '/storage/nvme5/new_clones/Prolog/julian' &
git clone https://github.com/jinwookjungs/lefdef_util '/storage/nvme5/new_clones/Prolog/lefdef_util' &
git clone https://github.com/cmungall/blipkit '/storage/nvme5/new_clones/Prolog/blipkit' &
git clone https://github.com/aarroyoc/doclog '/storage/nvme5/new_clones/Prolog/doclog' &
git clone https://github.com/Dead2/stabilizer '/storage/nvme5/new_clones/Prolog/stabilizer' &
git clone https://github.com/ForoughA/CORGI '/storage/nvme5/new_clones/Prolog/CORGI' &
git clone https://github.com/bme-db-lab/Functional-Dependency-Calculator '/storage/nvme5/new_clones/Prolog/Functional-Dependency-Calculator' &
git clone https://github.com/triska/simsttab '/storage/nvme5/new_clones/Prolog/simsttab' &
git clone https://github.com/SWI-Prolog/packages-http '/storage/nvme5/new_clones/Prolog/packages-http' &
git clone https://github.com/SWI-Prolog/sCASP '/storage/nvme5/new_clones/Prolog/sCASP' &
git clone https://github.com/maciej-nowak/DP-Film-Expert-System '/storage/nvme5/new_clones/Prolog/DP-Film-Expert-System' &
git clone https://github.com/SWI-Prolog/packages-chr '/storage/nvme5/new_clones/Prolog/packages-chr' &
git clone https://github.com/mihaits/Qt-CUDA-example '/storage/nvme5/new_clones/Prolog/Qt-CUDA-example' &
git clone https://github.com/egryaznov/prolog-poetry '/storage/nvme5/new_clones/Prolog/prolog-poetry' &
git clone https://github.com/rlegendi/wumpus-prolog '/storage/nvme5/new_clones/Prolog/wumpus-prolog' &
git clone https://github.com/nicoabie/quickcheck '/storage/nvme5/new_clones/Prolog/quickcheck' &
git clone https://github.com/m-danya/prolog-testing-system '/storage/nvme5/new_clones/Prolog/prolog-testing-system' &
git clone https://github.com/NikolajSchlej/RushSPI '/storage/nvme5/new_clones/Prolog/RushSPI' &
git clone https://github.com/Rootex/99-prolog-problems '/storage/nvme5/new_clones/Prolog/99-prolog-problems' &
git clone https://github.com/triska/bitcoinolog '/storage/nvme5/new_clones/Prolog/bitcoinolog' &
git clone https://github.com/msramalho/feup-iart-summary '/storage/nvme5/new_clones/Prolog/feup-iart-summary' &
git clone https://github.com/SmartDataAnalytics/SML-Bench '/storage/nvme5/new_clones/Prolog/SML-Bench' &
git clone https://github.com/simularity/SimGen '/storage/nvme5/new_clones/Prolog/SimGen' &
git clone https://github.com/har-in-air/ESP32-WROOM32-Eagle-Breakout '/storage/nvme5/new_clones/Prolog/ESP32-WROOM32-Eagle-Breakout' &
git clone https://github.com/hsfl/artemis-hardware '/storage/nvme5/new_clones/Prolog/artemis-hardware' &
git clone https://github.com/mndrix/edcg '/storage/nvme5/new_clones/Prolog/edcg' &
git clone https://github.com/terminusdb/terminus_store_prolog '/storage/nvme5/new_clones/Prolog/terminus_store_prolog' &
git clone https://github.com/JanWielemaker/chat80 '/storage/nvme5/new_clones/Prolog/chat80' &
git clone https://github.com/logic-and-learning-lab/ilp-experiments '/storage/nvme5/new_clones/Prolog/ilp-experiments' &
git clone https://github.com/vmosoti/lung-disease-diagnosis '/storage/nvme5/new_clones/Prolog/lung-disease-diagnosis' &
git clone https://github.com/ryancdotorg/dnsstore '/storage/nvme5/new_clones/Prolog/dnsstore' &
git clone https://github.com/jariazavalverde/fasill '/storage/nvme5/new_clones/Prolog/fasill' &
git clone https://github.com/Blog-Core/blog-core '/storage/nvme5/new_clones/Prolog/blog-core' &
git clone https://github.com/tboronczyk/LearnPrologNow '/storage/nvme5/new_clones/Prolog/LearnPrologNow' &
git clone https://github.com/edisonm/refactor '/storage/nvme5/new_clones/Prolog/refactor' &
git clone https://github.com/cbaziotis/prolog-cfg-parser '/storage/nvme5/new_clones/Prolog/prolog-cfg-parser' &
git clone https://github.com/eazar001/yesbot '/storage/nvme5/new_clones/Prolog/yesbot' &
git clone https://github.com/rla/prolog-markdown '/storage/nvme5/new_clones/Prolog/prolog-markdown' &
git clone https://github.com/nickmain/cchr '/storage/nvme5/new_clones/Prolog/cchr' &
git clone https://github.com/eshelyaron/debug_adapter '/storage/nvme5/new_clones/Prolog/debug_adapter' &
git clone https://github.com/StetsonMathCS/alpaca '/storage/nvme5/new_clones/Prolog/alpaca' &
git clone https://github.com/Anniepoo/swiplclpfd '/storage/nvme5/new_clones/Prolog/swiplclpfd' &
git clone https://github.com/softlang/yas '/storage/nvme5/new_clones/Prolog/yas' &
git clone https://github.com/leuschel/logen '/storage/nvme5/new_clones/Prolog/logen' &
git clone https://github.com/roboticslab-cseiitg/ProjectTartarus '/storage/nvme5/new_clones/Prolog/ProjectTartarus' &
git clone https://github.com/Anniepoo/strangeloop '/storage/nvme5/new_clones/Prolog/strangeloop' &
git clone https://github.com/JanWielemaker/swi-chat '/storage/nvme5/new_clones/Prolog/swi-chat' &
git clone https://github.com/regack/40Pct '/storage/nvme5/new_clones/Prolog/40Pct' &
git clone https://github.com/JUrban/MPTP2 '/storage/nvme5/new_clones/Prolog/MPTP2' &
git clone https://github.com/arcadio/data-logic '/storage/nvme5/new_clones/Prolog/data-logic' &
git clone https://github.com/mndrix/func '/storage/nvme5/new_clones/Prolog/func' &
git clone https://github.com/triska/proloxy '/storage/nvme5/new_clones/Prolog/proloxy' &
git clone https://github.com/cmungall/cltools '/storage/nvme5/new_clones/Prolog/cltools' &
git clone https://github.com/ianhorswill/MKULTRA '/storage/nvme5/new_clones/Prolog/MKULTRA' &
git clone https://github.com/hbrouwer/dfs-tools '/storage/nvme5/new_clones/Prolog/dfs-tools' &
git clone https://github.com/jlsalmon/chatbot '/storage/nvme5/new_clones/Prolog/chatbot' &
git clone https://github.com/tkuhn/AceRules '/storage/nvme5/new_clones/Prolog/AceRules' &
git clone https://github.com/stassa/metasplain '/storage/nvme5/new_clones/Prolog/metasplain' &
git clone https://github.com/hhu-stups/prolog-jupyter-kernel '/storage/nvme5/new_clones/Prolog/prolog-jupyter-kernel' &
git clone https://github.com/martinmogusu/course_advisor '/storage/nvme5/new_clones/Prolog/course_advisor' &
git clone https://github.com/meskarune/.scripts '/storage/nvme5/new_clones/Prolog/.scripts' &
git clone https://github.com/Kartoffel/BareDuino '/storage/nvme5/new_clones/Prolog/BareDuino' &
git clone https://github.com/SWI-Prolog/plweb '/storage/nvme5/new_clones/Prolog/plweb' &
git clone https://github.com/geeknik/cve-fuzzing-poc '/storage/nvme5/new_clones/Prolog/cve-fuzzing-poc' &
git clone https://github.com/logicmoo/logicmoo_clif '/storage/nvme5/new_clones/Prolog/logicmoo_clif' &
git clone https://github.com/JorgeAparicio/F4Dev '/storage/nvme5/new_clones/Prolog/F4Dev' &
git clone https://github.com/celinehocquette/magicpopper '/storage/nvme5/new_clones/Prolog/magicpopper' &
git clone https://github.com/davidwfanning/idl-coyote '/storage/nvme5/new_clones/Prolog/idl-coyote' &
git clone https://github.com/fifth-postulate/functional-geometry-in-prolog '/storage/nvme5/new_clones/Prolog/functional-geometry-in-prolog' &
git clone https://github.com/monarch-initiative/monarch-disease-ontology-RETIRED '/storage/nvme5/new_clones/Prolog/monarch-disease-ontology-RETIRED' &
git clone https://github.com/JoseCSantos/GILPS '/storage/nvme5/new_clones/Prolog/GILPS' &
git clone https://github.com/tiantiangao7/kalm '/storage/nvme5/new_clones/Prolog/kalm' &
git clone https://github.com/anwarmamat/cmsc330 '/storage/nvme5/new_clones/Prolog/cmsc330' &
git clone https://github.com/jamesnvc/vuelog '/storage/nvme5/new_clones/Prolog/vuelog' &
git clone https://github.com/mndrix/regex '/storage/nvme5/new_clones/Prolog/regex' &
git clone https://github.com/madworm/8x8_RGB_LED_Matrix_Controller '/storage/nvme5/new_clones/Prolog/8x8_RGB_LED_Matrix_Controller' &
git clone https://github.com/wouterbeek/prolog_rdf '/storage/nvme5/new_clones/Prolog/prolog_rdf' &
git clone https://github.com/larsyencken/marelle-deps '/storage/nvme5/new_clones/Prolog/marelle-deps' &
git clone https://github.com/cpldcpu/LPC812breakout '/storage/nvme5/new_clones/Prolog/LPC812breakout' &
git clone https://github.com/JanWielemaker/ffi '/storage/nvme5/new_clones/Prolog/ffi' &
git clone https://github.com/pchampio/othello-prolog '/storage/nvme5/new_clones/Prolog/othello-prolog' &
git clone https://github.com/j9650/MedusaNet '/storage/nvme5/new_clones/Prolog/MedusaNet' &
git clone https://github.com/logicmoo/logicmoo_ec '/storage/nvme5/new_clones/Prolog/logicmoo_ec' &
git clone https://github.com/khueue/prolog-json '/storage/nvme5/new_clones/Prolog/prolog-json' &
git clone https://github.com/leaflabs/oak '/storage/nvme5/new_clones/Prolog/oak' &
git clone https://github.com/triska/trs '/storage/nvme5/new_clones/Prolog/trs' &
git clone https://github.com/fatuhoku/prolog-sudoku '/storage/nvme5/new_clones/Prolog/prolog-sudoku' &
git clone https://github.com/he7850/Prolog-chess-game '/storage/nvme5/new_clones/Prolog/Prolog-chess-game' &
git clone https://github.com/khueue/crisp '/storage/nvme5/new_clones/Prolog/crisp' &
git clone https://github.com/chemkg/chemrof '/storage/nvme5/new_clones/Prolog/chemrof' &
git clone https://github.com/max19951001/EFSDAF '/storage/nvme5/new_clones/Prolog/EFSDAF' &
git clone https://github.com/HokieGeek/expresscard-breakout '/storage/nvme5/new_clones/Prolog/expresscard-breakout' &
git clone https://github.com/joes-esolangs/cassette '/storage/nvme5/new_clones/Prolog/cassette' &
git clone https://github.com/emacstheviking/gnuprolog-redisclient '/storage/nvme5/new_clones/Prolog/gnuprolog-redisclient' &
git clone https://github.com/SWI-Prolog/bench '/storage/nvme5/new_clones/Prolog/bench' &
git clone https://github.com/aarroyoc/teruel '/storage/nvme5/new_clones/Prolog/teruel' &
git clone https://github.com/VanHakobyan/SWI-Prolog '/storage/nvme5/new_clones/Prolog/SWI-Prolog' &
git clone https://github.com/RadostinaIvanova/Expert-system-in-Prolog '/storage/nvme5/new_clones/Prolog/Expert-system-in-Prolog' &
git clone https://github.com/chen1415-UNSW/COMP9414 '/storage/nvme5/new_clones/Prolog/COMP9414' &
git clone https://github.com/qt/qtwebkit-examples '/storage/nvme5/new_clones/Prolog/qtwebkit-examples' &
git clone https://github.com/diyaudiocircuits/eagle-cad-files '/storage/nvme5/new_clones/Prolog/eagle-cad-files' &
git clone https://github.com/JanWielemaker/sCASP '/storage/nvme5/new_clones/Prolog/sCASP' &
git clone https://github.com/wouterbeek/prolog_graphviz '/storage/nvme5/new_clones/Prolog/prolog_graphviz' &
git clone https://github.com/logicmoo/programk '/storage/nvme5/new_clones/Prolog/programk' &
git clone https://github.com/matchilling/brexit '/storage/nvme5/new_clones/Prolog/brexit' &
git clone https://github.com/fnogatz/plammar '/storage/nvme5/new_clones/Prolog/plammar' &
git clone https://github.com/DonaldKellett/Einsteins-Riddle-Prolog '/storage/nvme5/new_clones/Prolog/Einsteins-Riddle-Prolog' &
git clone https://github.com/jdswalker/Interpreter-in-Prolog '/storage/nvme5/new_clones/Prolog/Interpreter-in-Prolog' &
git clone https://github.com/macpod/lasershark_hardware '/storage/nvme5/new_clones/Prolog/lasershark_hardware' &
git clone https://github.com/bitboxelectronics/R2C2_Hardware '/storage/nvme5/new_clones/Prolog/R2C2_Hardware' &
git clone https://github.com/andrewcropper/mlj18-metaopt '/storage/nvme5/new_clones/Prolog/mlj18-metaopt' &
git clone https://github.com/fj/cheryls-birthday-prolog '/storage/nvme5/new_clones/Prolog/cheryls-birthday-prolog' &
git clone https://github.com/motib/mathematical-logic '/storage/nvme5/new_clones/Prolog/mathematical-logic' &
git clone https://github.com/MartimVideira/PFL-Exercises '/storage/nvme5/new_clones/Prolog/PFL-Exercises' &
git clone https://github.com/celinehocquette/numsynth-aaai23 '/storage/nvme5/new_clones/Prolog/numsynth-aaai23' &
git clone https://github.com/IvanLJF/My_InSAR_Codes '/storage/nvme5/new_clones/Prolog/My_InSAR_Codes' &
git clone https://github.com/DanieElectronics/DetectiveBoysWT '/storage/nvme5/new_clones/Prolog/DetectiveBoysWT' &
git clone https://github.com/terminusdb/tus '/storage/nvme5/new_clones/Prolog/tus' &
git clone https://github.com/mndrix/spawn '/storage/nvme5/new_clones/Prolog/spawn' &
git clone https://github.com/Anniepoo/declswiplweb '/storage/nvme5/new_clones/Prolog/declswiplweb' &
git clone https://github.com/rzese/trill '/storage/nvme5/new_clones/Prolog/trill' &
git clone https://github.com/VivoMind/unicode_data '/storage/nvme5/new_clones/Prolog/unicode_data' &
git clone https://github.com/saraswat/NeuralProgrammerAsProbProg '/storage/nvme5/new_clones/Prolog/NeuralProgrammerAsProbProg' &
git clone https://github.com/TopherMan/Ramps2Due '/storage/nvme5/new_clones/Prolog/Ramps2Due' &
git clone https://github.com/aindilis/financial-planning '/storage/nvme5/new_clones/Prolog/financial-planning' &
git clone https://github.com/hehao1999/ENVI_IDL '/storage/nvme5/new_clones/Prolog/ENVI_IDL' &
git clone https://github.com/emacstheviking/gnuprolog-json '/storage/nvme5/new_clones/Prolog/gnuprolog-json' &
git clone https://github.com/agodinhost/KiCad '/storage/nvme5/new_clones/Prolog/KiCad' &
git clone https://github.com/slazav/map_podm '/storage/nvme5/new_clones/Prolog/map_podm' &
git clone https://github.com/garciparedes/prolog-examples '/storage/nvme5/new_clones/Prolog/prolog-examples' &
git clone https://github.com/lxcode/dotfiles '/storage/nvme5/new_clones/Prolog/dotfiles' &
git clone https://github.com/araneforseti/prolog-koans '/storage/nvme5/new_clones/Prolog/prolog-koans' &
git clone https://github.com/MuhammadSulaiman001/prolog-lab '/storage/nvme5/new_clones/Prolog/prolog-lab' &
git clone https://github.com/mndrix/jolog '/storage/nvme5/new_clones/Prolog/jolog' &
git clone https://github.com/JanWielemaker/todo-backend-swi-prolog '/storage/nvme5/new_clones/Prolog/todo-backend-swi-prolog' &
git clone https://github.com/mbenke/labjpp '/storage/nvme5/new_clones/Prolog/labjpp' &
git clone https://github.com/curry0622/VLSI-Physical-Design-Automation '/storage/nvme5/new_clones/Prolog/VLSI-Physical-Design-Automation' &
git clone https://github.com/Makerflux/Home-Automation '/storage/nvme5/new_clones/Prolog/Home-Automation' &
git clone https://github.com/eiffelqiu/obfuscate-clojure-project-demo '/storage/nvme5/new_clones/Prolog/obfuscate-clojure-project-demo' &
git clone https://github.com/friguzzi/matrix '/storage/nvme5/new_clones/Prolog/matrix' &
git clone https://github.com/JensNevens/Prolog-Scheduling-Problem '/storage/nvme5/new_clones/Prolog/Prolog-Scheduling-Problem' &
git clone https://github.com/eftsilio/Incremental_RTEC '/storage/nvme5/new_clones/Prolog/Incremental_RTEC' &
git clone https://github.com/jaseg/openmind '/storage/nvme5/new_clones/Prolog/openmind' &
git clone https://github.com/friguzzi/trill-on-swish '/storage/nvme5/new_clones/Prolog/trill-on-swish' &
git clone https://github.com/SWI-Prolog-Education/talespin-annie '/storage/nvme5/new_clones/Prolog/talespin-annie' &
git clone https://github.com/universitymarr/Artificial-Intelligence '/storage/nvme5/new_clones/Prolog/Artificial-Intelligence' &
git clone https://github.com/andrewcropper/iggp '/storage/nvme5/new_clones/Prolog/iggp' &
git clone https://github.com/NebraLtd/nebra-lora-hardware '/storage/nvme5/new_clones/Prolog/nebra-lora-hardware' &
git clone https://github.com/mitsuchi/ron '/storage/nvme5/new_clones/Prolog/ron' &
git clone https://github.com/fnogatz/tap '/storage/nvme5/new_clones/Prolog/tap' &
git clone https://github.com/SWI-Prolog/packages-pengines '/storage/nvme5/new_clones/Prolog/packages-pengines' &
git clone https://github.com/nasa/MINX '/storage/nvme5/new_clones/Prolog/MINX' &
git clone https://github.com/sunilnandihalli/99-problems-in-prolog '/storage/nvme5/new_clones/Prolog/99-problems-in-prolog' &
git clone https://github.com/shonfeder/tokenize '/storage/nvme5/new_clones/Prolog/tokenize' &
git clone https://github.com/xpix/XStepper '/storage/nvme5/new_clones/Prolog/XStepper' &
git clone https://github.com/LearnPrologNow/lpn-swish-proxy '/storage/nvme5/new_clones/Prolog/lpn-swish-proxy' &
git clone https://github.com/JanWielemaker/swi-erlang '/storage/nvme5/new_clones/Prolog/swi-erlang' &
git clone https://github.com/mndrix/mavis '/storage/nvme5/new_clones/Prolog/mavis' &
git clone https://github.com/voodoos/mlts '/storage/nvme5/new_clones/Prolog/mlts' &
git clone https://github.com/rali-udem/gophi '/storage/nvme5/new_clones/Prolog/gophi' &
git clone https://github.com/JanWielemaker/rits '/storage/nvme5/new_clones/Prolog/rits' &
git clone https://github.com/bekk/seven-languages '/storage/nvme5/new_clones/Prolog/seven-languages' &
git clone https://github.com/di-unipi-socc/EdgeUsher '/storage/nvme5/new_clones/Prolog/EdgeUsher' &
git clone https://github.com/mndrix/list_util '/storage/nvme5/new_clones/Prolog/list_util' &
git clone https://github.com/fnogatz/dcg4pt '/storage/nvme5/new_clones/Prolog/dcg4pt' &
git clone https://github.com/meditans/reif '/storage/nvme5/new_clones/Prolog/reif' &
git clone https://github.com/HouariZegai/PrologExercise '/storage/nvme5/new_clones/Prolog/PrologExercise' &
git clone https://github.com/ANSSI-FR/ProTIP '/storage/nvme5/new_clones/Prolog/ProTIP' &
git clone https://github.com/SamEA/CC3200_Breakout '/storage/nvme5/new_clones/Prolog/CC3200_Breakout' &
git clone https://github.com/finin/pfc '/storage/nvme5/new_clones/Prolog/pfc' &
git clone https://github.com/FredMesnard/lptp '/storage/nvme5/new_clones/Prolog/lptp' &
git clone https://github.com/sebgod/physics '/storage/nvme5/new_clones/Prolog/physics' &
git clone https://github.com/jaunerc/minimax-prolog '/storage/nvme5/new_clones/Prolog/minimax-prolog' &
git clone https://github.com/brilacasck/wumpus-prolog '/storage/nvme5/new_clones/Prolog/wumpus-prolog' &
git clone https://github.com/rla/alternative-router '/storage/nvme5/new_clones/Prolog/alternative-router' &
git clone https://github.com/leuschel/ecce '/storage/nvme5/new_clones/Prolog/ecce' &
git clone https://github.com/SWI-Prolog/packages-clpqr '/storage/nvme5/new_clones/Prolog/packages-clpqr' &
git clone https://github.com/lorenzo-stoakes/learn-prolog-now '/storage/nvme5/new_clones/Prolog/learn-prolog-now' &
git clone https://github.com/Jnber/ZombieCows '/storage/nvme5/new_clones/Prolog/ZombieCows' &
git clone https://github.com/MagnificentPako/Marami '/storage/nvme5/new_clones/Prolog/Marami' &
git clone https://github.com/rla/docstore '/storage/nvme5/new_clones/Prolog/docstore' &
git clone https://github.com/adkelley/prolog-starter '/storage/nvme5/new_clones/Prolog/prolog-starter' &
git clone https://github.com/nirantak/wsiwn '/storage/nvme5/new_clones/Prolog/wsiwn' &
git clone https://github.com/migafgarcia/prolog-checkers '/storage/nvme5/new_clones/Prolog/prolog-checkers' &
git clone https://github.com/akulagrawal/File-Search-Engine '/storage/nvme5/new_clones/Prolog/File-Search-Engine' &
git clone https://github.com/amarchen/Wikipedia '/storage/nvme5/new_clones/Prolog/Wikipedia' &
git clone https://github.com/stassa/thelma '/storage/nvme5/new_clones/Prolog/thelma' &
git clone https://github.com/mndrix/dcg_util '/storage/nvme5/new_clones/Prolog/dcg_util' &
git clone https://github.com/barcelonapm/Acme-PM-Barcelona '/storage/nvme5/new_clones/Prolog/Acme-PM-Barcelona' &
git clone https://github.com/JakubGrobelny/aurox-lang '/storage/nvme5/new_clones/Prolog/aurox-lang' &
git clone https://github.com/benvial/pytheas '/storage/nvme5/new_clones/Prolog/pytheas' &
git clone https://github.com/JanWielemaker/openapi '/storage/nvme5/new_clones/Prolog/openapi' &
git clone https://github.com/codyps/mm '/storage/nvme5/new_clones/Prolog/mm' &
git clone https://github.com/mndrix/miser '/storage/nvme5/new_clones/Prolog/miser' &
git clone https://github.com/JorgeAparicio/uJTAG '/storage/nvme5/new_clones/Prolog/uJTAG' &
git clone https://github.com/jrvosse/amalgame '/storage/nvme5/new_clones/Prolog/amalgame' &
git clone https://github.com/ReedOei/achelois '/storage/nvme5/new_clones/Prolog/achelois' &
git clone https://github.com/SWI-Prolog/rclswi '/storage/nvme5/new_clones/Prolog/rclswi' &
git clone https://github.com/geminiplanetimager/gpi_pipeline '/storage/nvme5/new_clones/Prolog/gpi_pipeline' &
git clone https://github.com/jamesconstable/99-prolog-problems '/storage/nvme5/new_clones/Prolog/99-prolog-problems' &
git clone https://github.com/SWI-Prolog/packages-plunit '/storage/nvme5/new_clones/Prolog/packages-plunit' &
git clone https://github.com/projectgus/novepad '/storage/nvme5/new_clones/Prolog/novepad' &
git clone https://github.com/edechter/open_dicts '/storage/nvme5/new_clones/Prolog/open_dicts' &
git clone https://github.com/aarroyoc/marquete '/storage/nvme5/new_clones/Prolog/marquete' &
git clone https://github.com/matyjas/share-bear '/storage/nvme5/new_clones/Prolog/share-bear' &
git clone https://github.com/rskew/lindenmayer '/storage/nvme5/new_clones/Prolog/lindenmayer' &
git clone https://github.com/lee-naish/Pawns '/storage/nvme5/new_clones/Prolog/Pawns' &
git clone https://github.com/PlayingWithProlog/alexa '/storage/nvme5/new_clones/Prolog/alexa' &
git clone https://github.com/wouterbeek/prolog_jwt '/storage/nvme5/new_clones/Prolog/prolog_jwt' &
git clone https://github.com/nbassili/SWRL2SHACL '/storage/nvme5/new_clones/Prolog/SWRL2SHACL' &
git clone https://github.com/tylergreen/PLisp '/storage/nvme5/new_clones/Prolog/PLisp' &
git clone https://github.com/euphy/polarshieldv3_hardware '/storage/nvme5/new_clones/Prolog/polarshieldv3_hardware' &
git clone https://github.com/Average-user/adventofcode-pl-2017 '/storage/nvme5/new_clones/Prolog/adventofcode-pl-2017' &
git clone https://github.com/Anniepoo/amziexpertsystemsinprolog '/storage/nvme5/new_clones/Prolog/amziexpertsystemsinprolog' &
git clone https://github.com/rla/dict-schema '/storage/nvme5/new_clones/Prolog/dict-schema' &
git clone https://github.com/averykatko/buffalo '/storage/nvme5/new_clones/Prolog/buffalo' &
git clone https://github.com/anglus/fizzbuzz '/storage/nvme5/new_clones/Prolog/fizzbuzz' &
git clone https://github.com/gavanelli/sldnfdraw '/storage/nvme5/new_clones/Prolog/sldnfdraw' &
git clone https://github.com/paulfaget/PlasmaArcSpeaker '/storage/nvme5/new_clones/Prolog/PlasmaArcSpeaker' &
git clone https://github.com/aarroyoc/blog-ejemplos '/storage/nvme5/new_clones/Prolog/blog-ejemplos' &
git clone https://github.com/wjur/sym-diff-prolog '/storage/nvme5/new_clones/Prolog/sym-diff-prolog' &
git clone https://github.com/cmungall/sparqlprog_wikidata '/storage/nvme5/new_clones/Prolog/sparqlprog_wikidata' &
git clone https://github.com/jamj2000/HolaMundo '/storage/nvme5/new_clones/Prolog/HolaMundo' &
git clone https://github.com/tiantiangao7/kalm-qa '/storage/nvme5/new_clones/Prolog/kalm-qa' &
git clone https://github.com/bennycheung/bennycheung.github.io '/storage/nvme5/new_clones/Prolog/bennycheunghub.io' &
git clone https://github.com/wenkokke/swillprover '/storage/nvme5/new_clones/Prolog/swillprover' &
git clone https://github.com/ptarau/LogicTransformers '/storage/nvme5/new_clones/Prolog/LogicTransformers' &
git clone https://github.com/JanWielemaker/tabling_library '/storage/nvme5/new_clones/Prolog/tabling_library' &
git clone https://github.com/Paradigmas-2-2017/akinator-of-thrones '/storage/nvme5/new_clones/Prolog/akinator-of-thrones' &
git clone https://github.com/fabriziogaliano/docker-snort-ids '/storage/nvme5/new_clones/Prolog/docker-snort-ids' &
git clone https://github.com/EricssonResearch/plasticsearch '/storage/nvme5/new_clones/Prolog/plasticsearch' &
git clone https://github.com/zeko868/schedule-generator '/storage/nvme5/new_clones/Prolog/schedule-generator' &
git clone https://github.com/sparkfun/Qwiic_GPS-RTK '/storage/nvme5/new_clones/Prolog/Qwiic_GPS-RTK' &
git clone https://github.com/cmungall/sql_compiler '/storage/nvme5/new_clones/Prolog/sql_compiler' &
git clone https://github.com/aarroyoc/advent-of-code-2020 '/storage/nvme5/new_clones/Prolog/advent-of-code-2020' &
git clone https://github.com/hermie64/tm1-sublime '/storage/nvme5/new_clones/Prolog/tm1-sublime' &
git clone https://github.com/christian-vigh/prolog-experiments '/storage/nvme5/new_clones/Prolog/prolog-experiments' &
git clone https://github.com/SWI-Prolog/packages-inclpr '/storage/nvme5/new_clones/Prolog/packages-inclpr' &
git clone https://github.com/KistCloudRobot/context_reasoning '/storage/nvme5/new_clones/Prolog/context_reasoning' &
git clone https://github.com/R-White-0/Medical-Expert-System '/storage/nvme5/new_clones/Prolog/Medical-Expert-System' &
git clone https://github.com/rla/prolog-vdom '/storage/nvme5/new_clones/Prolog/prolog-vdom' &
git clone https://github.com/SWI-Prolog/contrib-protobufs '/storage/nvme5/new_clones/Prolog/contrib-protobufs' &
git clone https://github.com/ptarau/play '/storage/nvme5/new_clones/Prolog/play' &
git clone https://github.com/SWI-Prolog/packages-R '/storage/nvme5/new_clones/Prolog/packages-R' &
git clone https://github.com/jfbaltazar/pfl-prolog-exs '/storage/nvme5/new_clones/Prolog/pfl-prolog-exs' &
git clone https://github.com/cheery/prolog-tic-tac-toe '/storage/nvme5/new_clones/Prolog/prolog-tic-tac-toe' &
git clone https://github.com/caomxin/GNN-toolbox '/storage/nvme5/new_clones/Prolog/GNN-toolbox' &
git clone https://github.com/noahp/swdiso '/storage/nvme5/new_clones/Prolog/swdiso' &
git clone https://github.com/Moriumnasa-Mim/Artificial_Inteligence '/storage/nvme5/new_clones/Prolog/Artificial_Inteligence' &
git clone https://github.com/lunixbochs/project-euler '/storage/nvme5/new_clones/Prolog/project-euler' &
git clone https://github.com/AtnNn/tomy '/storage/nvme5/new_clones/Prolog/tomy' &
git clone https://github.com/kenegozi/kalah-prolog '/storage/nvme5/new_clones/Prolog/kalah-prolog' &
git clone https://github.com/ioana-vlad/NLP---SICStus '/storage/nvme5/new_clones/Prolog/NLP---SICStus' &
git clone https://github.com/LucidOne/TurtleBot '/storage/nvme5/new_clones/Prolog/TurtleBot' &
git clone https://github.com/pdepjm/bitacoras '/storage/nvme5/new_clones/Prolog/bitacoras' &
git clone https://github.com/theresasturn/plow '/storage/nvme5/new_clones/Prolog/plow' &
git clone https://github.com/bennaaym/adventure-game-prolog '/storage/nvme5/new_clones/Prolog/adventure-game-prolog' &
git clone https://github.com/mndrix/djson '/storage/nvme5/new_clones/Prolog/djson' &
git clone https://github.com/RedWn/Prolog-Akari '/storage/nvme5/new_clones/Prolog/Prolog-Akari' &
git clone https://github.com/HackBo/DroneCore '/storage/nvme5/new_clones/Prolog/DroneCore' &
git clone https://github.com/mndrix/delay '/storage/nvme5/new_clones/Prolog/delay' &
git clone https://github.com/andrewcropper/aaai20-forgetgol '/storage/nvme5/new_clones/Prolog/aaai20-forgetgol' &
git clone https://github.com/rzach/multlog '/storage/nvme5/new_clones/Prolog/multlog' &
git clone https://github.com/danieldk/brainfuck-pl '/storage/nvme5/new_clones/Prolog/brainfuck-pl' &
git clone https://github.com/Anniepoo/identity '/storage/nvme5/new_clones/Prolog/identity' &
git clone https://github.com/whitestarballoon/Iridium-Shield '/storage/nvme5/new_clones/Prolog/Iridium-Shield' &
git clone https://github.com/ridgeworks/pPEGpl '/storage/nvme5/new_clones/Prolog/pPEGpl' &
git clone https://github.com/logicmoo/sigma_ace '/storage/nvme5/new_clones/Prolog/sigma_ace' &
git clone https://github.com/jariazavalverde/prolog-smtlib '/storage/nvme5/new_clones/Prolog/prolog-smtlib' &
git clone https://github.com/jarble/adaptive_parser '/storage/nvme5/new_clones/Prolog/adaptive_parser' &
git clone https://github.com/hsk/simpletapl '/storage/nvme5/new_clones/Prolog/simpletapl' &
git clone https://github.com/triska/presprover '/storage/nvme5/new_clones/Prolog/presprover' &
git clone https://github.com/blatyo/wumpus '/storage/nvme5/new_clones/Prolog/wumpus' &
git clone https://github.com/zauguin/luapstricks '/storage/nvme5/new_clones/Prolog/luapstricks' &
git clone https://github.com/maresmar/eliza '/storage/nvme5/new_clones/Prolog/eliza' &
git clone https://github.com/ilario-pierbattista/prolog-utils '/storage/nvme5/new_clones/Prolog/prolog-utils' &
git clone https://github.com/ffagerholm/peano '/storage/nvme5/new_clones/Prolog/peano' &
git clone https://github.com/gsbelarus/gedemin-prolog '/storage/nvme5/new_clones/Prolog/gedemin-prolog' &
git clone https://github.com/da-poodle/react-and-prolog-demo '/storage/nvme5/new_clones/Prolog/react-and-prolog-demo' &
git clone https://github.com/videobrick/vb_hardware '/storage/nvme5/new_clones/Prolog/vb_hardware' &
git clone https://github.com/T3P3/IceBlueStepstick '/storage/nvme5/new_clones/Prolog/IceBlueStepstick' &
git clone https://github.com/CoryMcCartan/PL94171 '/storage/nvme5/new_clones/Prolog/PL94171' &
git clone https://github.com/PranitaSethiya/Weather-Expert-System-Prolog '/storage/nvme5/new_clones/Prolog/Weather-Expert-System-Prolog' &
git clone https://github.com/arcchitjain/SafeLearner '/storage/nvme5/new_clones/Prolog/SafeLearner' &
git clone https://github.com/Hack3rOneness/Prolog-Problems '/storage/nvme5/new_clones/Prolog/Prolog-Problems' &
git clone https://github.com/callumenator/idl '/storage/nvme5/new_clones/Prolog/idl' &
git clone https://github.com/jiahuang/avr-isp-shield '/storage/nvme5/new_clones/Prolog/avr-isp-shield' &
git clone https://github.com/samwalrus/twitter_pack '/storage/nvme5/new_clones/Prolog/twitter_pack' &
git clone https://github.com/Root41-Gifu/Root41-Hardware '/storage/nvme5/new_clones/Prolog/Root41-Hardware' &
git clone https://github.com/nbassili/SWRL2SPIN '/storage/nvme5/new_clones/Prolog/SWRL2SPIN' &
git clone https://github.com/dayfundora/Azul_Board_Game '/storage/nvme5/new_clones/Prolog/Azul_Board_Game' &
git clone https://github.com/skbaek/tesc '/storage/nvme5/new_clones/Prolog/tesc' &
git clone https://github.com/athieriot/irssi-ascii-image '/storage/nvme5/new_clones/Prolog/irssi-ascii-image' &
git clone https://github.com/Small-Bodies-Node/PDS4-IDL '/storage/nvme5/new_clones/Prolog/PDS4-IDL' &
git clone https://github.com/memgonzales/medical-expert-ehrlich '/storage/nvme5/new_clones/Prolog/medical-expert-ehrlich' &
git clone https://github.com/swi-to-yap/slack_prolog '/storage/nvme5/new_clones/Prolog/slack_prolog' &
git clone https://github.com/Hann1bal/Logic-Programming '/storage/nvme5/new_clones/Prolog/Logic-Programming' &
git clone https://github.com/AndreaInfUFSM/elc117-2020a '/storage/nvme5/new_clones/Prolog/elc117-2020a' &
git clone https://github.com/BigZaphod/Whirl '/storage/nvme5/new_clones/Prolog/Whirl' &
git clone https://github.com/leandrosansilva/prolog_toy_gameoflife '/storage/nvme5/new_clones/Prolog/prolog_toy_gameoflife' &
git clone https://github.com/SWI-Prolog/packages-cql '/storage/nvme5/new_clones/Prolog/packages-cql' &
git clone https://github.com/bnjbvr/Knights-Tour '/storage/nvme5/new_clones/Prolog/Knights-Tour' &
git clone https://github.com/SWI-PrologTeamLudumDare32/prolog-ludumdare44 '/storage/nvme5/new_clones/Prolog/prolog-ludumdare44' &
git clone https://github.com/FabioMiguel2000/LEIC-PFL-2021-22 '/storage/nvme5/new_clones/Prolog/LEIC-PFL-2021-22' &
git clone https://github.com/semaj/hammurabi '/storage/nvme5/new_clones/Prolog/hammurabi' &
git clone https://github.com/raydac/java-prolog-parser '/storage/nvme5/new_clones/Prolog/java-prolog-parser' &
git clone https://github.com/dagosi/Prolog '/storage/nvme5/new_clones/Prolog/Prolog' &
git clone https://github.com/joyheron/brainf_prolog_interpreter '/storage/nvme5/new_clones/Prolog/brainf_prolog_interpreter' &
git clone https://github.com/timhunter/ccpc '/storage/nvme5/new_clones/Prolog/ccpc' &
git clone https://github.com/soynerdito/WifIco '/storage/nvme5/new_clones/Prolog/WifIco' &
git clone https://github.com/benhuds/wangs-algorithm '/storage/nvme5/new_clones/Prolog/wangs-algorithm' &
git clone https://github.com/pulmro/martelli-montanari '/storage/nvme5/new_clones/Prolog/martelli-montanari' &
git clone https://github.com/NorthernWidget/ALog-BottleLogger '/storage/nvme5/new_clones/Prolog/ALog-BottleLogger' &
git clone https://github.com/cth/sdcg '/storage/nvme5/new_clones/Prolog/sdcg' &
git clone https://github.com/UnBParadigmas2022-1/2022.1_G3_Logico_Chess '/storage/nvme5/new_clones/Prolog/2022.1_G3_Logico_Chess' &
git clone https://github.com/TOTBWF/MLogic '/storage/nvme5/new_clones/Prolog/MLogic' &
git clone https://github.com/stigtsp/nix-cpan '/storage/nvme5/new_clones/Prolog/nix-cpan' &
git clone https://github.com/costarc/MSX_FPGA_Hat '/storage/nvme5/new_clones/Prolog/MSX_FPGA_Hat' &
git clone https://github.com/opendrone/flymaple-pcb '/storage/nvme5/new_clones/Prolog/flymaple-pcb' &
git clone https://github.com/mistupv/rev-rewriting '/storage/nvme5/new_clones/Prolog/rev-rewriting' &
git clone https://github.com/RobAntcliff/JSCSExamMaterial '/storage/nvme5/new_clones/Prolog/JSCSExamMaterial' &
git clone https://github.com/triska/scc '/storage/nvme5/new_clones/Prolog/scc' &
git clone https://github.com/knielsen/pcb_stm32f4_sram '/storage/nvme5/new_clones/Prolog/pcb_stm32f4_sram' &
git clone https://github.com/code-iai/robot_scenarios_sim '/storage/nvme5/new_clones/Prolog/robot_scenarios_sim' &
git clone https://github.com/mjones-credera/prolog-samples '/storage/nvme5/new_clones/Prolog/prolog-samples' &
git clone https://github.com/dustinandrews/Red-Soul '/storage/nvme5/new_clones/Prolog/Red-Soul' &
git clone https://github.com/logicmoo/flux '/storage/nvme5/new_clones/Prolog/flux' &
git clone https://github.com/EricssonResearch/oslc_prolog '/storage/nvme5/new_clones/Prolog/oslc_prolog' &
git clone https://github.com/DiamondLightSource/cs-web-proto '/storage/nvme5/new_clones/Prolog/cs-web-proto' &
git clone https://github.com/okanvk/Prolog-Exercises '/storage/nvme5/new_clones/Prolog/Prolog-Exercises' &
git clone https://github.com/stassa/wh40ksim '/storage/nvme5/new_clones/Prolog/wh40ksim' &
git clone https://github.com/Gariben/Prolog '/storage/nvme5/new_clones/Prolog/Prolog' &
git clone https://github.com/mistupv/rever '/storage/nvme5/new_clones/Prolog/rever' &
git clone https://github.com/ptarau/PrologTutorial '/storage/nvme5/new_clones/Prolog/PrologTutorial' &
git clone https://github.com/fnogatz/date_time '/storage/nvme5/new_clones/Prolog/date_time' &
git clone https://github.com/andrewcropper/ijcai16-metagolai '/storage/nvme5/new_clones/Prolog/ijcai16-metagolai' &
git clone https://github.com/logicmoo/tauchain_prolog '/storage/nvme5/new_clones/Prolog/tauchain_prolog' &
git clone https://github.com/bishoksan/RAHFT '/storage/nvme5/new_clones/Prolog/RAHFT' &
git clone https://github.com/Yakushima/NSM-DALIA '/storage/nvme5/new_clones/Prolog/NSM-DALIA' &
git clone https://github.com/nicos-angelopoulos/prosqlite '/storage/nvme5/new_clones/Prolog/prosqlite' &
git clone https://github.com/sparkfunX/Three_Phase_Motor_Driver-TMC6300 '/storage/nvme5/new_clones/Prolog/Three_Phase_Motor_Driver-TMC6300' &
git clone https://github.com/fusiongyro/conlang '/storage/nvme5/new_clones/Prolog/conlang' &
git clone https://github.com/Atarity/totoro-synth '/storage/nvme5/new_clones/Prolog/totoro-synth' &
git clone https://github.com/atreyasha/clingo-solvers '/storage/nvme5/new_clones/Prolog/clingo-solvers' &
git clone https://github.com/georgesittas/jobshop-scheduling '/storage/nvme5/new_clones/Prolog/jobshop-scheduling' &
git clone https://github.com/cau-placc/pakcs '/storage/nvme5/new_clones/Prolog/pakcs' &
git clone https://github.com/m-labs/board-m1 '/storage/nvme5/new_clones/Prolog/board-m1' &
git clone https://github.com/noahmartinwilliams/Creativity-augmenter '/storage/nvme5/new_clones/Prolog/Creativity-augmenter' &
git clone https://github.com/AndreaInfUFSM/elc117-2021a '/storage/nvme5/new_clones/Prolog/elc117-2021a' &
git clone https://github.com/InzamamRahaman/COMP3608-2019 '/storage/nvme5/new_clones/Prolog/COMP3608-2019' &
git clone https://github.com/TheWiseCoder/Dynworks '/storage/nvme5/new_clones/Prolog/Dynworks' &
git clone https://github.com/SWI-Prolog/packages-pldoc '/storage/nvme5/new_clones/Prolog/packages-pldoc' &
git clone https://github.com/dominicgs/PS2_tap '/storage/nvme5/new_clones/Prolog/PS2_tap' &
git clone https://github.com/andrewknight/winrt '/storage/nvme5/new_clones/Prolog/winrt' &
git clone https://github.com/leosmolas/peronautas '/storage/nvme5/new_clones/Prolog/peronautas' &
git clone https://github.com/wysiib/plspec '/storage/nvme5/new_clones/Prolog/plspec' &
git clone https://github.com/theoremprover-museum/clam3 '/storage/nvme5/new_clones/Prolog/clam3' &
git clone https://github.com/anamestre/FIB-LI-Labs '/storage/nvme5/new_clones/Prolog/FIB-LI-Labs' &
git clone https://github.com/Risto-Stevcev/prolog-monty-python '/storage/nvme5/new_clones/Prolog/prolog-monty-python' &
git clone https://github.com/NaohiroTamura/faasshell '/storage/nvme5/new_clones/Prolog/faasshell' &
git clone https://github.com/Anniepoo/terfblocklist '/storage/nvme5/new_clones/Prolog/terfblocklist' &
git clone https://github.com/calphool/Apple_IIGS_MemExpansion '/storage/nvme5/new_clones/Prolog/Apple_IIGS_MemExpansion' &
git clone https://github.com/mndrix/bencode '/storage/nvme5/new_clones/Prolog/bencode' &
git clone https://github.com/SWI-Prolog/packages-RDF '/storage/nvme5/new_clones/Prolog/packages-RDF' &
git clone https://github.com/gusmanb/unicvmod '/storage/nvme5/new_clones/Prolog/unicvmod' &
git clone https://github.com/CharlesJB/rTANDEM '/storage/nvme5/new_clones/Prolog/rTANDEM' &
git clone https://github.com/cui-unige/semantique '/storage/nvme5/new_clones/Prolog/semantique' &
git clone https://github.com/verypluming/systematicity '/storage/nvme5/new_clones/Prolog/systematicity' &
git clone https://github.com/motools/audiofeaturesonto '/storage/nvme5/new_clones/Prolog/audiofeaturesonto' &
git clone https://github.com/formare/community '/storage/nvme5/new_clones/Prolog/community' &
git clone https://github.com/rla/prolog-yamltiny '/storage/nvme5/new_clones/Prolog/prolog-yamltiny' &
git clone https://github.com/paulh002/SoapyHifiBerry '/storage/nvme5/new_clones/Prolog/SoapyHifiBerry' &
git clone https://github.com/mndrix/sweet '/storage/nvme5/new_clones/Prolog/sweet' &
git clone https://github.com/bishoksan/LHornSolver '/storage/nvme5/new_clones/Prolog/LHornSolver' &
git clone https://github.com/laplaceyc/Physical-Design-Automation '/storage/nvme5/new_clones/Prolog/Physical-Design-Automation' &
git clone https://github.com/Jumpsu/klondike '/storage/nvme5/new_clones/Prolog/klondike' &
git clone https://github.com/tobischo/mine-prolog-tba '/storage/nvme5/new_clones/Prolog/mine-prolog-tba' &
git clone https://github.com/3bru/PrologExamples '/storage/nvme5/new_clones/Prolog/PrologExamples' &
git clone https://github.com/jasonfilippou/Prob-EC '/storage/nvme5/new_clones/Prolog/Prob-EC' &
git clone https://github.com/unic0rn/eezoterial '/storage/nvme5/new_clones/Prolog/eezoterial' &
git clone https://github.com/zunath/SWLOR_Haks '/storage/nvme5/new_clones/Prolog/SWLOR_Haks' &
git clone https://github.com/francoscarselli/Graph-Neural-Networks '/storage/nvme5/new_clones/Prolog/Graph-Neural-Networks' &
git clone https://github.com/thetrime/prolog-getting-started '/storage/nvme5/new_clones/Prolog/prolog-getting-started' &
git clone https://github.com/mndrix/condition '/storage/nvme5/new_clones/Prolog/condition' &
git clone https://github.com/wuzeshixp/COMP9414 '/storage/nvme5/new_clones/Prolog/COMP9414' &
git clone https://github.com/calmesam01/Career-Counseling-System '/storage/nvme5/new_clones/Prolog/Career-Counseling-System' &
git clone https://github.com/dmeoli/PESAD '/storage/nvme5/new_clones/Prolog/PESAD' &
git clone https://github.com/andrewcropper/mlj19-iggp '/storage/nvme5/new_clones/Prolog/mlj19-iggp' &
git clone https://github.com/andrewcropper/mlj19-metaho '/storage/nvme5/new_clones/Prolog/mlj19-metaho' &
git clone https://github.com/di-unipi-socc/daplacer '/storage/nvme5/new_clones/Prolog/daplacer' &
git clone https://github.com/ai-krml-uoft/indigolog '/storage/nvme5/new_clones/Prolog/indigolog' &
git clone https://github.com/cmungall/wikidata_ontomatcher '/storage/nvme5/new_clones/Prolog/wikidata_ontomatcher' &
git clone https://github.com/sjbushra/Medical-Diagnosis-system-using-Prolog '/storage/nvme5/new_clones/Prolog/Medical-Diagnosis-system-using-Prolog' &
git clone https://github.com/aryan-harsh/Prolog-Codes '/storage/nvme5/new_clones/Prolog/Prolog-Codes' &
git clone https://github.com/ned2/crosswordsmith '/storage/nvme5/new_clones/Prolog/crosswordsmith' &
git clone https://github.com/mndrix/term_diff '/storage/nvme5/new_clones/Prolog/term_diff' &
git clone https://github.com/arnans/pitopping '/storage/nvme5/new_clones/Prolog/pitopping' &
git clone https://github.com/YuriDomingos/Prolog-Arvore-Familiar-Pinheiro '/storage/nvme5/new_clones/Prolog/Prolog-Arvore-Familiar-Pinheiro' &
git clone https://github.com/Cuttlerat/prolog_bot '/storage/nvme5/new_clones/Prolog/prolog_bot' &
git clone https://github.com/jfcloutier/karma_agency '/storage/nvme5/new_clones/Prolog/karma_agency' &
git clone https://github.com/jocap/russian-numbers '/storage/nvme5/new_clones/Prolog/russian-numbers' &
git clone https://github.com/roblaing/checkers-webapp '/storage/nvme5/new_clones/Prolog/checkers-webapp' &
git clone https://github.com/ewels/ngi_visualizations '/storage/nvme5/new_clones/Prolog/ngi_visualizations' &
git clone https://github.com/davidgrier/rayleighsommerfeld '/storage/nvme5/new_clones/Prolog/rayleighsommerfeld' &
git clone https://github.com/logicmoo/prologmud_I7 '/storage/nvme5/new_clones/Prolog/prologmud_I7' &
git clone https://github.com/magyarm/beaglebone-fpga '/storage/nvme5/new_clones/Prolog/beaglebone-fpga' &
git clone https://github.com/SallySoul/regexc '/storage/nvme5/new_clones/Prolog/regexc' &
git clone https://github.com/fnogatz/race '/storage/nvme5/new_clones/Prolog/race' &
git clone https://github.com/texttheater/xlci '/storage/nvme5/new_clones/Prolog/xlci' &
git clone https://github.com/GavinMendelGleason/typo '/storage/nvme5/new_clones/Prolog/typo' &
git clone https://github.com/max19951001/IDL_learning '/storage/nvme5/new_clones/Prolog/IDL_learning' &
git clone https://github.com/bendudson/eqdsk2helena '/storage/nvme5/new_clones/Prolog/eqdsk2helena' &
git clone https://github.com/FigBug/scheme '/storage/nvme5/new_clones/Prolog/scheme' &
git clone https://github.com/SoM-Boards/SoM-allwinnerA10 '/storage/nvme5/new_clones/Prolog/SoM-allwinnerA10' &
git clone https://github.com/houli/A-Star-Search '/storage/nvme5/new_clones/Prolog/A-Star-Search' &
git clone https://github.com/remexre/hm-prolog '/storage/nvme5/new_clones/Prolog/hm-prolog' &
git clone https://github.com/Pufcorina/Functional-and-Logic-Programming '/storage/nvme5/new_clones/Prolog/Functional-and-Logic-Programming' &
git clone https://github.com/honnix/kubepl '/storage/nvme5/new_clones/Prolog/kubepl' &
git clone https://github.com/ad52825196/8-puzzle '/storage/nvme5/new_clones/Prolog/8-puzzle' &
git clone https://github.com/aistrate/ClocksinMellish '/storage/nvme5/new_clones/Prolog/ClocksinMellish' &
git clone https://github.com/Kuniwak/ddsv-prolog '/storage/nvme5/new_clones/Prolog/ddsv-prolog' &
git clone https://github.com/SWI-Prolog/packages-regex '/storage/nvme5/new_clones/Prolog/packages-regex' &
