#!/bin/bash

git clone https://github.com/anders94/blockchain-demo '/storage/nvme5/new_clones/Pug/blockchain-demo' &
git clone https://github.com/Bttstrp/bootstrap-switch '/storage/nvme5/new_clones/Pug/bootstrap-switch' &
git clone https://github.com/gudh/ihover '/storage/nvme5/new_clones/Pug/ihover' &
git clone https://github.com/StartBootstrap/startbootstrap-sb-admin '/storage/nvme5/new_clones/Pug/startbootstrap-sb-admin' &
git clone https://github.com/StartBootstrap/startbootstrap-freelancer '/storage/nvme5/new_clones/Pug/startbootstrap-freelancer' &
git clone https://github.com/StartBootstrap/startbootstrap-resume '/storage/nvme5/new_clones/Pug/startbootstrap-resume' &
git clone https://github.com/pronist/hello '/storage/nvme5/new_clones/Pug/hello' &
git clone https://github.com/StartBootstrap/startbootstrap-creative '/storage/nvme5/new_clones/Pug/startbootstrap-creative' &
git clone https://github.com/StartBootstrap/startbootstrap-agency '/storage/nvme5/new_clones/Pug/startbootstrap-agency' &
git clone https://github.com/StartBootstrap/startbootstrap-clean-blog '/storage/nvme5/new_clones/Pug/startbootstrap-clean-blog' &
git clone https://github.com/StartBootstrap/startbootstrap-landing-page '/storage/nvme5/new_clones/Pug/startbootstrap-landing-page' &
git clone https://github.com/pratikborsadiya/vali-admin '/storage/nvme5/new_clones/Pug/vali-admin' &
git clone https://github.com/StartBootstrap/startbootstrap-grayscale '/storage/nvme5/new_clones/Pug/startbootstrap-grayscale' &
git clone https://github.com/StartBootstrap/startbootstrap-new-age '/storage/nvme5/new_clones/Pug/startbootstrap-new-age' &
git clone https://github.com/StartBootstrap/startbootstrap-modern-business '/storage/nvme5/new_clones/Pug/startbootstrap-modern-business' &
git clone https://github.com/frontend-rescue/keep-up-to-date '/storage/nvme5/new_clones/Pug/keep-up-to-date' &
git clone https://github.com/nigelpoulton/TheK8sBook '/storage/nvme5/new_clones/Pug/TheK8sBook' &
git clone https://github.com/angular/angular-cn '/storage/nvme5/new_clones/Pug/angular-cn' &
git clone https://github.com/nicothin/NTH-start-project '/storage/nvme5/new_clones/Pug/NTH-start-project' &
git clone https://github.com/denysvitali/thebestmotherfuckingwebsite '/storage/nvme5/new_clones/Pug/thebestmotherfuckingwebsite' &
git clone https://github.com/StartBootstrap/startbootstrap-shop-homepage '/storage/nvme5/new_clones/Pug/startbootstrap-shop-homepage' &
git clone https://github.com/Azure/actions-workflow-samples '/storage/nvme5/new_clones/Pug/actions-workflow-samples' &
git clone https://github.com/Kong/apiembed '/storage/nvme5/new_clones/Pug/apiembed' &
git clone https://github.com/nigelpoulton/getting-started-k8s '/storage/nvme5/new_clones/Pug/getting-started-k8s' &
git clone https://github.com/MorFansLab/LiteWebChat_Frame '/storage/nvme5/new_clones/Pug/LiteWebChat_Frame' &
git clone https://github.com/StartBootstrap/startbootstrap-business-casual '/storage/nvme5/new_clones/Pug/startbootstrap-business-casual' &
git clone https://github.com/wolfgang42/yaml-multiline '/storage/nvme5/new_clones/Pug/yaml-multiline' &
git clone https://github.com/StartBootstrap/startbootstrap-blog-home '/storage/nvme5/new_clones/Pug/startbootstrap-blog-home' &
git clone https://github.com/noraj/rawsec-cybersecurity-inventory '/storage/nvme5/new_clones/Pug/rawsec-cybersecurity-inventory' &
git clone https://github.com/zoxon/gulp-front '/storage/nvme5/new_clones/Pug/gulp-front' &
git clone https://github.com/random-yang/paper '/storage/nvme5/new_clones/Pug/paper' &
git clone https://github.com/StartBootstrap/startbootstrap-blog-post '/storage/nvme5/new_clones/Pug/startbootstrap-blog-post' &
git clone https://github.com/StartBootstrap/startbootstrap-business-frontpage '/storage/nvme5/new_clones/Pug/startbootstrap-business-frontpage' &
git clone https://github.com/pug-bootstrap/PUG-Bootstrap '/storage/nvme5/new_clones/Pug/PUG-Bootstrap' &
git clone https://github.com/feathericon/feathericon '/storage/nvme5/new_clones/Pug/feathericon' &
git clone https://github.com/g0v/g0v.tw '/storage/nvme5/new_clones/Pug/g0v.tw' &
git clone https://github.com/nigelpoulton/psweb '/storage/nvme5/new_clones/Pug/psweb' &
git clone https://github.com/karl-chan/google-drive-torrent '/storage/nvme5/new_clones/Pug/google-drive-torrent' &
git clone https://github.com/lazysheep666/terminal_theme '/storage/nvme5/new_clones/Pug/terminal_theme' &
git clone https://github.com/acro5piano/resume '/storage/nvme5/new_clones/Pug/resume' &
git clone https://github.com/StartBootstrap/startbootstrap-shop-item '/storage/nvme5/new_clones/Pug/startbootstrap-shop-item' &
git clone https://github.com/StartBootstrap/startbootstrap-personal '/storage/nvme5/new_clones/Pug/startbootstrap-personal' &
git clone https://github.com/phonegap/phonegap-docs '/storage/nvme5/new_clones/Pug/phonegap-docs' &
git clone https://github.com/primaryobjects/Node.js-Bootstrap-Starter-Template '/storage/nvme5/new_clones/Pug/Node.js-Bootstrap-Starter-Template' &
git clone https://github.com/effortlessdevsec/ninjasworkout '/storage/nvme5/new_clones/Pug/ninjasworkout' &
git clone https://github.com/lynnandtonic/lynnandtonic.com '/storage/nvme5/new_clones/Pug/lynnandtonic.com' &
git clone https://github.com/fitodac/bsnav '/storage/nvme5/new_clones/Pug/bsnav' &
git clone https://github.com/yearbook/extendscript-api-documentation '/storage/nvme5/new_clones/Pug/extendscript-api-documentation' &
git clone https://github.com/nmaggioni/Kanbanion '/storage/nvme5/new_clones/Pug/Kanbanion' &
git clone https://github.com/rajasegar/htmx-trello '/storage/nvme5/new_clones/Pug/htmx-trello' &
git clone https://github.com/tutRPi/Raspberry-Pi-Simple-Web-GPIO-GUI '/storage/nvme5/new_clones/Pug/Raspberry-Pi-Simple-Web-GPIO-GUI' &
git clone https://github.com/janoside/lndash '/storage/nvme5/new_clones/Pug/lndash' &
git clone https://github.com/app-generator/tailwind-css-components '/storage/nvme5/new_clones/Pug/tailwind-css-components' &
git clone https://github.com/pqvst/cafeandcowork '/storage/nvme5/new_clones/Pug/cafeandcowork' &
git clone https://github.com/taichunmin/liff-businesscard '/storage/nvme5/new_clones/Pug/liff-businesscard' &
git clone https://github.com/ferreiro/website '/storage/nvme5/new_clones/Pug/website' &
git clone https://github.com/maximzhurkin/jquery-scrolla '/storage/nvme5/new_clones/Pug/jquery-scrolla' &
git clone https://github.com/atConf/atswift2016 '/storage/nvme5/new_clones/Pug/atswift2016' &
git clone https://github.com/yuheiy/shifted '/storage/nvme5/new_clones/Pug/shifted' &
git clone https://github.com/janoside/lightning-rpc-explorer '/storage/nvme5/new_clones/Pug/lightning-rpc-explorer' &
git clone https://github.com/davidrios/pug-tmbundle '/storage/nvme5/new_clones/Pug/pug-tmbundle' &
git clone https://github.com/uloco/syntax-highlighting-samples '/storage/nvme5/new_clones/Pug/syntax-highlighting-samples' &
git clone https://github.com/Level/leveljs.org '/storage/nvme5/new_clones/Pug/leveljs.org' &
git clone https://github.com/Inflectra/ui-test-automation-playground '/storage/nvme5/new_clones/Pug/ui-test-automation-playground' &
git clone https://github.com/contradictioned/areweideyet '/storage/nvme5/new_clones/Pug/areweideyet' &
git clone https://github.com/lightning-login/lnurl-auth-demo '/storage/nvme5/new_clones/Pug/lnurl-auth-demo' &
git clone https://github.com/tarkhov/postboot '/storage/nvme5/new_clones/Pug/postboot' &
git clone https://github.com/microsoft/project-nodejs-express-webapp '/storage/nvme5/new_clones/Pug/project-nodejs-express-webapp' &
git clone https://github.com/prismicio/nodejs-sdk '/storage/nvme5/new_clones/Pug/nodejs-sdk' &
git clone https://github.com/kayserifserif/wakingandsleeping '/storage/nvme5/new_clones/Pug/wakingandsleeping' &
git clone https://github.com/untsop/idea-app-site '/storage/nvme5/new_clones/Pug/idea-app-site' &
git clone https://github.com/XadillaX/hexo-xnew '/storage/nvme5/new_clones/Pug/hexo-xnew' &
git clone https://github.com/snipcart/node-js-ecommerce-koajs '/storage/nvme5/new_clones/Pug/node-js-ecommerce-koajs' &
git clone https://github.com/keystonejs/keystonejs-site '/storage/nvme5/new_clones/Pug/keystonejs-site' &
git clone https://github.com/Lissy93/md-cv-maker '/storage/nvme5/new_clones/Pug/md-cv-maker' &
git clone https://github.com/govex/datastandards.directory '/storage/nvme5/new_clones/Pug/datastandards.directory' &
git clone https://github.com/marionettejs/marionettejs.com '/storage/nvme5/new_clones/Pug/marionettejs.com' &
git clone https://github.com/lynnandtonic/usflags.design '/storage/nvme5/new_clones/Pug/usflags.design' &
git clone https://github.com/milligram/milligram.github.io '/storage/nvme5/new_clones/Pug/milligramhub.io' &
git clone https://github.com/Einundzwanzig-Podcast/einundzwanzig.space '/storage/nvme5/new_clones/Pug/einundzwanzig.space' &
git clone https://github.com/whatadewitt/yahoofantasysandbox '/storage/nvme5/new_clones/Pug/yahoofantasysandbox' &
git clone https://github.com/linemanjs/lineman-blog-template '/storage/nvme5/new_clones/Pug/lineman-blog-template' &
git clone https://github.com/azernov/open-crm '/storage/nvme5/new_clones/Pug/open-crm' &
git clone https://github.com/niltea/hanarisa-button '/storage/nvme5/new_clones/Pug/hanarisa-button' &
git clone https://github.com/fiftin/siteboilerplate '/storage/nvme5/new_clones/Pug/siteboilerplate' &
git clone https://github.com/KUoslab/HF_custom '/storage/nvme5/new_clones/Pug/HF_custom' &
git clone https://github.com/lynnandtonic/davidrose.style '/storage/nvme5/new_clones/Pug/davidrose.style' &
git clone https://github.com/yudppp/simple-sendgrid-mock-server '/storage/nvme5/new_clones/Pug/simple-sendgrid-mock-server' &
git clone https://github.com/buildbot/buildbot-website '/storage/nvme5/new_clones/Pug/buildbot-website' &
git clone https://github.com/molly/website-v2 '/storage/nvme5/new_clones/Pug/website-v2' &
git clone https://github.com/CenturyLink/Chi '/storage/nvme5/new_clones/Pug/Chi' &
git clone https://github.com/lynnandtonic/thefoodplace.cafe '/storage/nvme5/new_clones/Pug/thefoodplace.cafe' &
git clone https://github.com/primaryobjects/Node.js-Material-Starter-Template '/storage/nvme5/new_clones/Pug/Node.js-Material-Starter-Template' &
git clone https://github.com/MAGGIx1404/awwward-rebuild-SOTD--1 '/storage/nvme5/new_clones/Pug/awwward-rebuild-SOTD--1' &
git clone https://github.com/Lidemy/mtr-4th-web '/storage/nvme5/new_clones/Pug/mtr-4th-web' &
git clone https://github.com/larsiusprime/georgism '/storage/nvme5/new_clones/Pug/georgism' &
git clone https://github.com/jayliu50/qmk-cheatsheet '/storage/nvme5/new_clones/Pug/qmk-cheatsheet' &
git clone https://github.com/videoder/main '/storage/nvme5/new_clones/Pug/main' &
git clone https://github.com/siketyan/siketyan.dev '/storage/nvme5/new_clones/Pug/siketyan.dev' &
git clone https://github.com/jh3y/stationery-cabinet '/storage/nvme5/new_clones/Pug/stationery-cabinet' &
git clone https://github.com/LibrariesHacked/catalogues-api '/storage/nvme5/new_clones/Pug/catalogues-api' &
git clone https://github.com/rajasegar/htmx-dropbox '/storage/nvme5/new_clones/Pug/htmx-dropbox' &
git clone https://github.com/binlist/www '/storage/nvme5/new_clones/Pug/www' &
git clone https://github.com/rajasegar/htmx-calendar '/storage/nvme5/new_clones/Pug/htmx-calendar' &
git clone https://github.com/computer-lab/computerlab.io '/storage/nvme5/new_clones/Pug/computerlab.io' &
git clone https://github.com/dev-tips/dev-tips '/storage/nvme5/new_clones/Pug/dev-tips' &
git clone https://github.com/SoarLin/pug-sass-template '/storage/nvme5/new_clones/Pug/pug-sass-template' &
git clone https://github.com/Kos-M/RpiTracker '/storage/nvme5/new_clones/Pug/RpiTracker' &
git clone https://github.com/amaitou/TrueFix '/storage/nvme5/new_clones/Pug/TrueFix' &
git clone https://github.com/nat-davydova/password-strength '/storage/nvme5/new_clones/Pug/password-strength' &
git clone https://github.com/csscoder/Responsive-Email-Template-Builder '/storage/nvme5/new_clones/Pug/Responsive-Email-Template-Builder' &
git clone https://github.com/plotdb/xfl '/storage/nvme5/new_clones/Pug/xfl' &
git clone https://github.com/tsparticles/jquery '/storage/nvme5/new_clones/Pug/jquery' &
git clone https://github.com/kbrgl/mebut.online '/storage/nvme5/new_clones/Pug/mebut.online' &
git clone https://github.com/jsconf/jsconf.com '/storage/nvme5/new_clones/Pug/jsconf.com' &
git clone https://github.com/oninross/firestarter '/storage/nvme5/new_clones/Pug/firestarter' &
git clone https://github.com/qwertyuu/quebec-achat-local '/storage/nvme5/new_clones/Pug/quebec-achat-local' &
git clone https://github.com/auth0-blog/auth0-express-pug-sample '/storage/nvme5/new_clones/Pug/auth0-express-pug-sample' &
git clone https://github.com/dmorenogogoleva/rr-web '/storage/nvme5/new_clones/Pug/rr-web' &
git clone https://github.com/slowli/ed25519-quirks '/storage/nvme5/new_clones/Pug/ed25519-quirks' &
git clone https://github.com/nat-davydova/easter-icons-svg '/storage/nvme5/new_clones/Pug/easter-icons-svg' &
git clone https://github.com/p-knot/hinano-button '/storage/nvme5/new_clones/Pug/hinano-button' &
git clone https://github.com/nanobox-io/nanobox-guides '/storage/nvme5/new_clones/Pug/nanobox-guides' &
git clone https://github.com/Fmstrat/traccar-notifier '/storage/nvme5/new_clones/Pug/traccar-notifier' &
git clone https://github.com/CenturyLinkCloud/ux-chi '/storage/nvme5/new_clones/Pug/ux-chi' &
git clone https://github.com/improving-minnesota/react-redux-workshop '/storage/nvme5/new_clones/Pug/react-redux-workshop' &
git clone https://github.com/fingerprintjs/fingerprintjs-paywall-example '/storage/nvme5/new_clones/Pug/fingerprintjs-paywall-example' &
git clone https://github.com/clocklimited/Parts '/storage/nvme5/new_clones/Pug/Parts' &
git clone https://github.com/noeldelgado/share-url '/storage/nvme5/new_clones/Pug/share-url' &
git clone https://github.com/oktadev/header-app-tester '/storage/nvme5/new_clones/Pug/header-app-tester' &
git clone https://github.com/podrivo/movimentoux '/storage/nvme5/new_clones/Pug/movimentoux' &
git clone https://github.com/kunruch/mm.css '/storage/nvme5/new_clones/Pug/mm.css' &
git clone https://github.com/kir-dev/tanulo-next '/storage/nvme5/new_clones/Pug/tanulo-next' &
git clone https://github.com/c3r5b8/StartPage '/storage/nvme5/new_clones/Pug/StartPage' &
git clone https://github.com/loadingio/ldcolorpicker '/storage/nvme5/new_clones/Pug/ldcolorpicker' &
git clone https://github.com/beefyfinance/beefy-landing '/storage/nvme5/new_clones/Pug/beefy-landing' &
git clone https://github.com/glenpierce/UBHub '/storage/nvme5/new_clones/Pug/UBHub' &
git clone https://github.com/edemaine/talk-yin-yang '/storage/nvme5/new_clones/Pug/talk-yin-yang' &
git clone https://github.com/lynnandtonic/top-chef-stats '/storage/nvme5/new_clones/Pug/top-chef-stats' &
git clone https://github.com/s-pyadyshev/disciples-site '/storage/nvme5/new_clones/Pug/disciples-site' &
git clone https://github.com/ghaschel/vscode-angular-pug '/storage/nvme5/new_clones/Pug/vscode-angular-pug' &
git clone https://github.com/themagicteeth/ttwoee '/storage/nvme5/new_clones/Pug/ttwoee' &
git clone https://github.com/takaneichinose/css-room-escape '/storage/nvme5/new_clones/Pug/css-room-escape' &
git clone https://github.com/citizenos/citizenos-web '/storage/nvme5/new_clones/Pug/citizenos-web' &
git clone https://github.com/liuliangsir/periodic-table-of-the-html5-elements '/storage/nvme5/new_clones/Pug/periodic-table-of-the-html5-elements' &
git clone https://github.com/rohit-gohri/inno '/storage/nvme5/new_clones/Pug/inno' &
git clone https://github.com/sandboxis/sandbox-website '/storage/nvme5/new_clones/Pug/sandbox-website' &
git clone https://github.com/kimth007kim/everyTime_clone_nodejs '/storage/nvme5/new_clones/Pug/everyTime_clone_nodejs' &
git clone https://github.com/lazarnarcis/box-shadow-generator '/storage/nvme5/new_clones/Pug/box-shadow-generator' &
git clone https://github.com/rajasegar/htmx-tabular '/storage/nvme5/new_clones/Pug/htmx-tabular' &
git clone https://github.com/Kudostoy0u/portfolio '/storage/nvme5/new_clones/Pug/portfolio' &
git clone https://github.com/fuddl/pIqaDqoq '/storage/nvme5/new_clones/Pug/pIqaDqoq' &
git clone https://github.com/KynaAcademy/security-demos '/storage/nvme5/new_clones/Pug/security-demos' &
git clone https://github.com/Guille0197/agenciaViajes_deployment '/storage/nvme5/new_clones/Pug/agenciaViajes_deployment' &
git clone https://github.com/pillarsjs/pillars.docs '/storage/nvme5/new_clones/Pug/pillars.docs' &
git clone https://github.com/azlkiniue/stevia '/storage/nvme5/new_clones/Pug/stevia' &
git clone https://github.com/wopian/wopian.me '/storage/nvme5/new_clones/Pug/wopian.me' &
git clone https://github.com/nknagent/nknag '/storage/nvme5/new_clones/Pug/nknag' &
git clone https://github.com/nigelpoulton/gsk-workshop '/storage/nvme5/new_clones/Pug/gsk-workshop' &
git clone https://github.com/aj0strow/ajostrow.me '/storage/nvme5/new_clones/Pug/ajostrow.me' &
git clone https://github.com/Apnoea/gulp-bem-template '/storage/nvme5/new_clones/Pug/gulp-bem-template' &
git clone https://github.com/clairefro/website '/storage/nvme5/new_clones/Pug/website' &
git clone https://github.com/EbiseLutica/simpkey '/storage/nvme5/new_clones/Pug/simpkey' &
git clone https://github.com/OkuriSae/Meish '/storage/nvme5/new_clones/Pug/Meish' &
git clone https://github.com/griffinmyers/pony-express '/storage/nvme5/new_clones/Pug/pony-express' &
git clone https://github.com/questbook/ethcontract.app '/storage/nvme5/new_clones/Pug/ethcontract.app' &
git clone https://github.com/CatChen/catchen.me '/storage/nvme5/new_clones/Pug/catchen.me' &
git clone https://github.com/SpeckyYT/specky.one '/storage/nvme5/new_clones/Pug/specky.one' &
git clone https://github.com/akash4-sys/AnimeZone-app '/storage/nvme5/new_clones/Pug/AnimeZone-app' &
git clone https://github.com/inputlabs/website '/storage/nvme5/new_clones/Pug/website' &
git clone https://github.com/plibither8/mihir.ch '/storage/nvme5/new_clones/Pug/mihir.ch' &
git clone https://github.com/pzcuong/QuanLyHocSinh '/storage/nvme5/new_clones/Pug/QuanLyHocSinh' &
git clone https://github.com/troygoode/dice-logger '/storage/nvme5/new_clones/Pug/dice-logger' &
git clone https://github.com/jesterb0206/natours '/storage/nvme5/new_clones/Pug/natours' &
git clone https://github.com/Ozodbek16/Pug '/storage/nvme5/new_clones/Pug/Pug' &
git clone https://github.com/h3y6e/arcard '/storage/nvme5/new_clones/Pug/arcard' &
git clone https://github.com/caligrafy/caligrafy-course '/storage/nvme5/new_clones/Pug/caligrafy-course' &
git clone https://github.com/ubports/ubuntu-touch.io '/storage/nvme5/new_clones/Pug/ubuntu-touch.io' &
git clone https://github.com/intuition-team/layer-0 '/storage/nvme5/new_clones/Pug/layer-0' &
git clone https://github.com/wbawakate/wbawakate.jp '/storage/nvme5/new_clones/Pug/wbawakate.jp' &
git clone https://github.com/scist-tw/scist-tw.github.io '/storage/nvme5/new_clones/Pug/scist-twhub.io' &
