#!/bin/bash

git clone https://github.com/alibaba/x-deeplearning '/storage/nvme5/new_clones/PureBasic/x-deeplearning' &
git clone https://github.com/deseven/iCanHazShortcut '/storage/nvme5/new_clones/PureBasic/iCanHazShortcut' &
git clone https://github.com/facebookresearch/DeepFovea '/storage/nvme5/new_clones/PureBasic/DeepFovea' &
git clone https://github.com/alyssaxuu/ecosnap '/storage/nvme5/new_clones/PureBasic/ecosnap' &
git clone https://github.com/sydney222/Python_CsiNet '/storage/nvme5/new_clones/PureBasic/Python_CsiNet' &
git clone https://github.com/etiennepinchon/aframe-fonts '/storage/nvme5/new_clones/PureBasic/aframe-fonts' &
git clone https://github.com/andrew-paglinawan/QuicksandFamily '/storage/nvme5/new_clones/PureBasic/QuicksandFamily' &
git clone https://github.com/MrV2K/WHDLoad-Download-Tool '/storage/nvme5/new_clones/PureBasic/WHDLoad-Download-Tool' &
git clone https://github.com/jvitkauskas/Altera-Cyclone-IV-board-V3.0 '/storage/nvme5/new_clones/PureBasic/Altera-Cyclone-IV-board-V3.0' &
git clone https://github.com/Ouxiaolong/ZigBee '/storage/nvme5/new_clones/PureBasic/ZigBee' &
git clone https://github.com/lisawray/fiftyshades '/storage/nvme5/new_clones/PureBasic/fiftyshades' &
git clone https://github.com/google/digitalassetlinks '/storage/nvme5/new_clones/PureBasic/digitalassetlinks' &
git clone https://github.com/HamedMP/tensorflow_export_cpp_example '/storage/nvme5/new_clones/PureBasic/tensorflow_export_cpp_example' &
git clone https://github.com/menelaoskanakis/ZippyPoint '/storage/nvme5/new_clones/PureBasic/ZippyPoint' &
git clone https://github.com/amjltc295/VITON_realtime '/storage/nvme5/new_clones/PureBasic/VITON_realtime' &
git clone https://github.com/SicroAtGit/PB-CodeArchiv-Rebirth '/storage/nvme5/new_clones/PureBasic/PB-CodeArchiv-Rebirth' &
git clone https://github.com/jungdj/AI-Effects '/storage/nvme5/new_clones/PureBasic/AI-Effects' &
git clone https://github.com/HauyuChen/Parking-System '/storage/nvme5/new_clones/PureBasic/Parking-System' &
git clone https://github.com/marpie/signed-loaders '/storage/nvme5/new_clones/PureBasic/signed-loaders' &
git clone https://github.com/DanysysTeam/SFTA '/storage/nvme5/new_clones/PureBasic/SFTA' &
git clone https://github.com/redis-developer/redis-nvidia-recsys '/storage/nvme5/new_clones/PureBasic/redis-nvidia-recsys' &
git clone https://github.com/Etayson/BSGS-cuda '/storage/nvme5/new_clones/PureBasic/BSGS-cuda' &
git clone https://github.com/satyaborg/pose-estimation-detection '/storage/nvme5/new_clones/PureBasic/pose-estimation-detection' &
git clone https://github.com/KnollFrank/HowBadIsMyBatch '/storage/nvme5/new_clones/PureBasic/HowBadIsMyBatch' &
git clone https://github.com/SestoAle/DeepCrawl '/storage/nvme5/new_clones/PureBasic/DeepCrawl' &
git clone https://github.com/dina-lab3D/NanoNet '/storage/nvme5/new_clones/PureBasic/NanoNet' &
git clone https://github.com/susiegriggo/Phynteny '/storage/nvme5/new_clones/PureBasic/Phynteny' &
git clone https://github.com/MonicaRizzolli/Tomorrow '/storage/nvme5/new_clones/PureBasic/Tomorrow' &
git clone https://github.com/Aksoylu/AI-DRAW '/storage/nvme5/new_clones/PureBasic/AI-DRAW' &
git clone https://github.com/mjpramirez/Volvo-DataX '/storage/nvme5/new_clones/PureBasic/Volvo-DataX' &
git clone https://github.com/kenmo-pb/includes '/storage/nvme5/new_clones/PureBasic/includes' &
git clone https://github.com/jwkanggist/tf-tiny-pose-estimation '/storage/nvme5/new_clones/PureBasic/tf-tiny-pose-estimation' &
git clone https://github.com/Hoeppner1867/PureBasic '/storage/nvme5/new_clones/PureBasic/PureBasic' &
git clone https://github.com/keremvaris/NewGenFramework '/storage/nvme5/new_clones/PureBasic/NewGenFramework' &
git clone https://github.com/galliot-us/models '/storage/nvme5/new_clones/PureBasic/models' &
git clone https://github.com/deseven/iCanHazMusic '/storage/nvme5/new_clones/PureBasic/iCanHazMusic' &
git clone https://github.com/raymondlo84/nvidia-jetson-ai-monitor '/storage/nvme5/new_clones/PureBasic/nvidia-jetson-ai-monitor' &
git clone https://github.com/bmvandoren/Nighthawk '/storage/nvme5/new_clones/PureBasic/Nighthawk' &
git clone https://github.com/Dadido3/WebSocket_Server '/storage/nvme5/new_clones/PureBasic/WebSocket_Server' &
git clone https://github.com/a-ws-m/unlockNN '/storage/nvme5/new_clones/PureBasic/unlockNN' &
git clone https://github.com/vincent1bt/Real-ESRGAN-TensorFlow '/storage/nvme5/new_clones/PureBasic/Real-ESRGAN-TensorFlow' &
git clone https://github.com/tajmone/name-that-color '/storage/nvme5/new_clones/PureBasic/name-that-color' &
git clone https://github.com/duty1g/dty '/storage/nvme5/new_clones/PureBasic/dty' &
git clone https://github.com/RocketRider/GreenForce-Player '/storage/nvme5/new_clones/PureBasic/GreenForce-Player' &
git clone https://github.com/jono-m/OrganoID '/storage/nvme5/new_clones/PureBasic/OrganoID' &
git clone https://github.com/ShadowPic/PublicTestProjects '/storage/nvme5/new_clones/PureBasic/PublicTestProjects' &
git clone https://github.com/cristiklein/stateless-workstation-config '/storage/nvme5/new_clones/PureBasic/stateless-workstation-config' &
git clone https://github.com/PacktPublishing/Hands-on-Tensorflow-Lite-for-Intelligent-Mobile-Apps '/storage/nvme5/new_clones/PureBasic/Hands-on-Tensorflow-Lite-for-Intelligent-Mobile-Apps' &
git clone https://github.com/mohit9949/Pose-Estimation-Similarity-With-TensorFlow '/storage/nvme5/new_clones/PureBasic/Pose-Estimation-Similarity-With-TensorFlow' &
git clone https://github.com/amirpandi/Deep_AMP '/storage/nvme5/new_clones/PureBasic/Deep_AMP' &
git clone https://github.com/shenrunzhang/forex '/storage/nvme5/new_clones/PureBasic/forex' &
git clone https://github.com/mpaillassa/MaxiMask '/storage/nvme5/new_clones/PureBasic/MaxiMask' &
git clone https://github.com/deseven/pbsamples '/storage/nvme5/new_clones/PureBasic/pbsamples' &
git clone https://github.com/Jerri1977/___core48 '/storage/nvme5/new_clones/PureBasic/___core48' &
git clone https://github.com/jdevfullstack/PureBasic-FileExplorer '/storage/nvme5/new_clones/PureBasic/PureBasic-FileExplorer' &
git clone https://github.com/nightwalker89/Collider '/storage/nvme5/new_clones/PureBasic/Collider' &
git clone https://github.com/keremvaris/CleanCodeDemo '/storage/nvme5/new_clones/PureBasic/CleanCodeDemo' &
git clone https://github.com/omegakode/PBWebview2 '/storage/nvme5/new_clones/PureBasic/PBWebview2' &
git clone https://github.com/alexgavs/arm-iar-ts100-mod2.12 '/storage/nvme5/new_clones/PureBasic/arm-iar-ts100-mod2.12' &
git clone https://github.com/D-a-n-i-l-o/raylib-purebasic '/storage/nvme5/new_clones/PureBasic/raylib-purebasic' &
git clone https://github.com/Mirda81/Sudoku '/storage/nvme5/new_clones/PureBasic/Sudoku' &
git clone https://github.com/globalpolicy/PureBasicRAT '/storage/nvme5/new_clones/PureBasic/PureBasicRAT' &
git clone https://github.com/Jan125/pb.chordian '/storage/nvme5/new_clones/PureBasic/pb.chordian' &
git clone https://github.com/chinmayembedded/Human-Activity-Recognition '/storage/nvme5/new_clones/PureBasic/Human-Activity-Recognition' &
git clone https://github.com/Henry00IS/PureBasic '/storage/nvme5/new_clones/PureBasic/PureBasic' &
git clone https://github.com/Digital-Umuganda/Deepspeech-Kinyarwanda '/storage/nvme5/new_clones/PureBasic/Deepspeech-Kinyarwanda' &
git clone https://github.com/Jithsaavvy/Deploying-an-end-to-end-keyword-spotting-model-into-cloud-server-by-integrating-CI-CD-pipeline '/storage/nvme5/new_clones/PureBasic/Deploying-an-end-to-end-keyword-spotting-model-into-cloud-server-by-integrating-CI-CD-pipeline' &
git clone https://github.com/startnew/dance_score_android '/storage/nvme5/new_clones/PureBasic/dance_score_android' &
git clone https://github.com/ONSdigital/highcharts-export-docker '/storage/nvme5/new_clones/PureBasic/highcharts-export-docker' &
git clone https://github.com/ChrisRfr/SweetyVD '/storage/nvme5/new_clones/PureBasic/SweetyVD' &
git clone https://github.com/Planet-AI-GmbH/tfaip-hybrid-ctc-s2s '/storage/nvme5/new_clones/PureBasic/tfaip-hybrid-ctc-s2s' &
git clone https://github.com/epfl-ml4ed/evaluating-explainers '/storage/nvme5/new_clones/PureBasic/evaluating-explainers' &
git clone https://github.com/Sri-vatsa/Unit '/storage/nvme5/new_clones/PureBasic/Unit' &
git clone https://github.com/patrik-ha/explainable-minichess '/storage/nvme5/new_clones/PureBasic/explainable-minichess' &
git clone https://github.com/Guevara-chan/Xors3D-for-PB '/storage/nvme5/new_clones/PureBasic/Xors3D-for-PB' &
git clone https://github.com/bluemix/vibes-typeface '/storage/nvme5/new_clones/PureBasic/vibes-typeface' &
git clone https://github.com/djes/PBMap '/storage/nvme5/new_clones/PureBasic/PBMap' &
git clone https://github.com/typesafehub/fdp-tensorflow-python-examples '/storage/nvme5/new_clones/PureBasic/fdp-tensorflow-python-examples' &
git clone https://github.com/jdevfullstack/PureBasic-Scrabble '/storage/nvme5/new_clones/PureBasic/PureBasic-Scrabble' &
git clone https://github.com/HauyuChen/ZigBee-WirelessFan '/storage/nvme5/new_clones/PureBasic/ZigBee-WirelessFan' &
git clone https://github.com/Dadido3/Lua-PureBasic '/storage/nvme5/new_clones/PureBasic/Lua-PureBasic' &
git clone https://github.com/asujaykk/Road-segmentation-UNET-model '/storage/nvme5/new_clones/PureBasic/Road-segmentation-UNET-model' &
git clone https://github.com/ToniPB/distorm-PB '/storage/nvme5/new_clones/PureBasic/distorm-PB' &
git clone https://github.com/rakanarmoush1/FaceMaskDetector '/storage/nvme5/new_clones/PureBasic/FaceMaskDetector' &
git clone https://github.com/marpie/a12d404.net-files '/storage/nvme5/new_clones/PureBasic/a12d404.net-files' &
git clone https://github.com/AnkushMalaker/speech-emotion-recognition '/storage/nvme5/new_clones/PureBasic/speech-emotion-recognition' &
git clone https://github.com/jdevfullstack/PureBasic-2D-Game '/storage/nvme5/new_clones/PureBasic/PureBasic-2D-Game' &
git clone https://github.com/imos/rainynine '/storage/nvme5/new_clones/PureBasic/rainynine' &
git clone https://github.com/Jieli12/AutoCPD '/storage/nvme5/new_clones/PureBasic/AutoCPD' &
git clone https://github.com/spiderbytes/SpiderBite '/storage/nvme5/new_clones/PureBasic/SpiderBite' &
git clone https://github.com/bgeraghty/RunProcessAsUser-ScreenConnect '/storage/nvme5/new_clones/PureBasic/RunProcessAsUser-ScreenConnect' &
git clone https://github.com/miranthajayatilake/Pose_Estimator '/storage/nvme5/new_clones/PureBasic/Pose_Estimator' &
git clone https://github.com/AlexanderNaehring/TPFMM '/storage/nvme5/new_clones/PureBasic/TPFMM' &
git clone https://github.com/upes-open/OSC-Medical-Analysis-Application-Using-ML '/storage/nvme5/new_clones/PureBasic/OSC-Medical-Analysis-Application-Using-ML' &
git clone https://github.com/rektide/compfuzor '/storage/nvme5/new_clones/PureBasic/compfuzor' &
git clone https://github.com/saswat0/Workout-buddy '/storage/nvme5/new_clones/PureBasic/Workout-buddy' &
git clone https://github.com/mehrdad-dev/anxiety-predict '/storage/nvme5/new_clones/PureBasic/anxiety-predict' &
git clone https://github.com/jlacombe/learning-to-generate-wasserstein-barycenters '/storage/nvme5/new_clones/PureBasic/learning-to-generate-wasserstein-barycenters' &
git clone https://github.com/kosmosmo/StandGen_mrcnn '/storage/nvme5/new_clones/PureBasic/StandGen_mrcnn' &
git clone https://github.com/Guevara-chan/Difference-Engine '/storage/nvme5/new_clones/PureBasic/Difference-Engine' &
git clone https://github.com/PrudhvirajuChekuri/EmoViz '/storage/nvme5/new_clones/PureBasic/EmoViz' &
git clone https://github.com/niraljshah/Fall_Detection '/storage/nvme5/new_clones/PureBasic/Fall_Detection' &
git clone https://github.com/A-Stangeland/SolarDetection '/storage/nvme5/new_clones/PureBasic/SolarDetection' &
git clone https://github.com/JulienLeprince/hierarchicallearning '/storage/nvme5/new_clones/PureBasic/hierarchicallearning' &
git clone https://github.com/athevinha/capcha-detection '/storage/nvme5/new_clones/PureBasic/capcha-detection' &
git clone https://github.com/Syr0/Joe-s-Purebasic-Automation-Lib '/storage/nvme5/new_clones/PureBasic/Joe-s-Purebasic-Automation-Lib' &
git clone https://github.com/kochlisGit/Deep-Trainer '/storage/nvme5/new_clones/PureBasic/Deep-Trainer' &
git clone https://github.com/silvialava/Deep_quadratic_hedging '/storage/nvme5/new_clones/PureBasic/Deep_quadratic_hedging' &
git clone https://github.com/tajmone/PBasmUI '/storage/nvme5/new_clones/PureBasic/PBasmUI' &
git clone https://github.com/nomad-software/purebasic-a-beginners-guide '/storage/nvme5/new_clones/PureBasic/purebasic-a-beginners-guide' &
git clone https://github.com/Fonthausen/Pacifico '/storage/nvme5/new_clones/PureBasic/Pacifico' &
git clone https://github.com/ChrisRfr/ObjectColor-Dark-Mode '/storage/nvme5/new_clones/PureBasic/ObjectColor-Dark-Mode' &
git clone https://github.com/akamicah/puresilo '/storage/nvme5/new_clones/PureBasic/puresilo' &
git clone https://github.com/anishreddy3/tf-openpose-baseball-pitcher '/storage/nvme5/new_clones/PureBasic/tf-openpose-baseball-pitcher' &
git clone https://github.com/mestnyi33/widget '/storage/nvme5/new_clones/PureBasic/widget' &
git clone https://github.com/tunerok/milandr_vscode_win_ocd '/storage/nvme5/new_clones/PureBasic/milandr_vscode_win_ocd' &
git clone https://github.com/Guevara-chan/Slippery-Clip '/storage/nvme5/new_clones/PureBasic/Slippery-Clip' &
git clone https://github.com/Heribert17/PureBasic_libraries '/storage/nvme5/new_clones/PureBasic/PureBasic_libraries' &
git clone https://github.com/drkostas/LSTMs-Training-Demo '/storage/nvme5/new_clones/PureBasic/LSTMs-Training-Demo' &
git clone https://github.com/asperti/MicroRacer '/storage/nvme5/new_clones/PureBasic/MicroRacer' &
git clone https://github.com/codeperfectplus/autoEncoders '/storage/nvme5/new_clones/PureBasic/autoEncoders' &
git clone https://github.com/ECNUSR/PureConvSR-AIM2022 '/storage/nvme5/new_clones/PureBasic/PureConvSR-AIM2022' &
git clone https://github.com/gabzai/Conditional-Variational-Autoencoder-based-Stochastic-Attacks '/storage/nvme5/new_clones/PureBasic/Conditional-Variational-Autoencoder-based-Stochastic-Attacks' &
git clone https://github.com/cyrealtype/Marmelad-Cyrillic '/storage/nvme5/new_clones/PureBasic/Marmelad-Cyrillic' &
git clone https://github.com/codeprof/small-PureBasic-projects '/storage/nvme5/new_clones/PureBasic/small-PureBasic-projects' &
git clone https://github.com/PurePortable/PurePortable '/storage/nvme5/new_clones/PureBasic/PurePortable' &
git clone https://github.com/SicroAtGit/RegEx-Engine '/storage/nvme5/new_clones/PureBasic/RegEx-Engine' &
git clone https://github.com/ognjenkundacina/graph-neural-network-state-estimation '/storage/nvme5/new_clones/PureBasic/graph-neural-network-state-estimation' &
git clone https://github.com/LastLifeLeft/Inputify '/storage/nvme5/new_clones/PureBasic/Inputify' &
git clone https://github.com/mirkousuelli/CNN-Leaves-Classifier '/storage/nvme5/new_clones/PureBasic/CNN-Leaves-Classifier' &
git clone https://github.com/jzhang-github/HECC_phase_prediction '/storage/nvme5/new_clones/PureBasic/HECC_phase_prediction' &
git clone https://github.com/kpzhang/ImageEmotionDetection '/storage/nvme5/new_clones/PureBasic/ImageEmotionDetection' &
git clone https://github.com/neha191091/human-segmentation '/storage/nvme5/new_clones/PureBasic/human-segmentation' &
git clone https://github.com/TroaX/PBExpress '/storage/nvme5/new_clones/PureBasic/PBExpress' &
git clone https://github.com/umut-demirhan/Radar-aided-blockage-prediction '/storage/nvme5/new_clones/PureBasic/Radar-aided-blockage-prediction' &
git clone https://github.com/Iagea/DECIMER-Image-Classifier '/storage/nvme5/new_clones/PureBasic/DECIMER-Image-Classifier' &
git clone https://github.com/TechPrimers/gradle-custom-plugin-example '/storage/nvme5/new_clones/PureBasic/gradle-custom-plugin-example' &
git clone https://github.com/xinluo2018/Earth-Engine-with-Deep-Learning '/storage/nvme5/new_clones/PureBasic/Earth-Engine-with-Deep-Learning' &
git clone https://github.com/cd-athena/MoViDNN '/storage/nvme5/new_clones/PureBasic/MoViDNN' &
git clone https://github.com/loucass003/futura-face-server '/storage/nvme5/new_clones/PureBasic/futura-face-server' &
git clone https://github.com/dhis2/dhis2-identity '/storage/nvme5/new_clones/PureBasic/dhis2-identity' &
git clone https://github.com/Dadido3/D3classic '/storage/nvme5/new_clones/PureBasic/D3classic' &
git clone https://github.com/aziascreations/PB-Utils '/storage/nvme5/new_clones/PureBasic/PB-Utils' &
git clone https://github.com/flaith-nycd/bcob-ide '/storage/nvme5/new_clones/PureBasic/bcob-ide' &
git clone https://github.com/Kron4ek/releases-downloader '/storage/nvme5/new_clones/PureBasic/releases-downloader' &
git clone https://github.com/JDonaldM/Matryoshka '/storage/nvme5/new_clones/PureBasic/Matryoshka' &
git clone https://github.com/OishikGuha/Vegetable-Plant-Blight-Disease-Classifier '/storage/nvme5/new_clones/PureBasic/Vegetable-Plant-Blight-Disease-Classifier' &
git clone https://github.com/growly/bfg '/storage/nvme5/new_clones/PureBasic/bfg' &
git clone https://github.com/princefr/DaNet-Human-3D-Pose '/storage/nvme5/new_clones/PureBasic/DaNet-Human-3D-Pose' &
git clone https://github.com/universidad-zaragoza/BNN_for_hyperspectral_datasets_analysis '/storage/nvme5/new_clones/PureBasic/BNN_for_hyperspectral_datasets_analysis' &
git clone https://github.com/nueh/ciphersaber '/storage/nvme5/new_clones/PureBasic/ciphersaber' &
git clone https://github.com/TheSun00000/facial_recognition_optimization '/storage/nvme5/new_clones/PureBasic/facial_recognition_optimization' &
git clone https://github.com/brian386/ScanChess '/storage/nvme5/new_clones/PureBasic/ScanChess' &
git clone https://github.com/hehlinge42/nlp_consulting_project '/storage/nvme5/new_clones/PureBasic/nlp_consulting_project' &
git clone https://github.com/falsam/MediaPlayer '/storage/nvme5/new_clones/PureBasic/MediaPlayer' &
git clone https://github.com/dadamaowang/TempHumiLightQT '/storage/nvme5/new_clones/PureBasic/TempHumiLightQT' &
git clone https://github.com/qingqingnailao/STM32_FOC2.0_ENCODER '/storage/nvme5/new_clones/PureBasic/STM32_FOC2.0_ENCODER' &
git clone https://github.com/CYBERDEVILZ/Stock-Market-Prediction '/storage/nvme5/new_clones/PureBasic/Stock-Market-Prediction' &
git clone https://github.com/kenmo-pb/TabBarGadget '/storage/nvme5/new_clones/PureBasic/TabBarGadget' &
git clone https://github.com/jayam-joshi/Hand-Gesture-recognition '/storage/nvme5/new_clones/PureBasic/Hand-Gesture-recognition' &
git clone https://github.com/eldarkg/emdr1986x-std-per-lib-doc '/storage/nvme5/new_clones/PureBasic/emdr1986x-std-per-lib-doc' &
git clone https://github.com/JGSalgueiro/RBS-NeuralNetwork '/storage/nvme5/new_clones/PureBasic/RBS-NeuralNetwork' &
git clone https://github.com/collectordave/PureBasic-Password-Database '/storage/nvme5/new_clones/PureBasic/PureBasic-Password-Database' &
git clone https://github.com/00laboratories/PBHGEN '/storage/nvme5/new_clones/PureBasic/PBHGEN' &
git clone https://github.com/polimi-ispl/deep_learning_soundfield_synthesis_irregular_array '/storage/nvme5/new_clones/PureBasic/deep_learning_soundfield_synthesis_irregular_array' &
git clone https://github.com/Dadido3/D3HT '/storage/nvme5/new_clones/PureBasic/D3HT' &
git clone https://github.com/Guevara-chan/Flow '/storage/nvme5/new_clones/PureBasic/Flow' &
git clone https://github.com/Calamari-OCR/calamari_models_experimental '/storage/nvme5/new_clones/PureBasic/calamari_models_experimental' &
git clone https://github.com/microdevweb/TreeView '/storage/nvme5/new_clones/PureBasic/TreeView' &
git clone https://github.com/aziascreations/PB-DLL-Icons-Templates '/storage/nvme5/new_clones/PureBasic/PB-DLL-Icons-Templates' &
git clone https://github.com/afonsocastro/larcc_interface '/storage/nvme5/new_clones/PureBasic/larcc_interface' &
git clone https://github.com/zsano1/fall_down_pose_estimation '/storage/nvme5/new_clones/PureBasic/fall_down_pose_estimation' &
git clone https://github.com/drkostas/Tensorflow-Training-Demo '/storage/nvme5/new_clones/PureBasic/Tensorflow-Training-Demo' &
git clone https://github.com/GPIforGit/SDL_For_PB '/storage/nvme5/new_clones/PureBasic/SDL_For_PB' &
git clone https://github.com/Anand-av/Gait-Analysis-using-3D-Pose-Estimation-with-GUI '/storage/nvme5/new_clones/PureBasic/Gait-Analysis-using-3D-Pose-Estimation-with-GUI' &
git clone https://github.com/alecxcode/cdsign '/storage/nvme5/new_clones/PureBasic/cdsign' &
git clone https://github.com/jwkanggist/tf-cnn-model '/storage/nvme5/new_clones/PureBasic/tf-cnn-model' &
git clone https://github.com/lucasjinreal/tf_pose_realtime '/storage/nvme5/new_clones/PureBasic/tf_pose_realtime' &
git clone https://github.com/DeeCamp-Demo/HDMapProject '/storage/nvme5/new_clones/PureBasic/HDMapProject' &
git clone https://github.com/dlphay/m430_dcdc_2015 '/storage/nvme5/new_clones/PureBasic/m430_dcdc_2015' &
git clone https://github.com/deseven/pb-win-notify '/storage/nvme5/new_clones/PureBasic/pb-win-notify' &
git clone https://github.com/gamepress/jsons '/storage/nvme5/new_clones/PureBasic/jsons' &
git clone https://github.com/GboardThemes/PackRepoBeta '/storage/nvme5/new_clones/PureBasic/PackRepoBeta' &
git clone https://github.com/said7/PureBasic '/storage/nvme5/new_clones/PureBasic/PureBasic' &
