#!/bin/bash

git clone https://github.com/dwavesystems/qbsolv '/storage/nvme5/new_clones/q/qbsolv' &
git clone https://github.com/sambacha/q-evm '/storage/nvme5/new_clones/q/q-evm' &
git clone https://github.com/DataIntellectTech/TorQ '/storage/nvme5/new_clones/q/TorQ' &
git clone https://github.com/AvensLab/OcrKing '/storage/nvme5/new_clones/q/OcrKing' &
git clone https://github.com/psaris/qtips '/storage/nvme5/new_clones/q/qtips' &
git clone https://github.com/psaris/funq '/storage/nvme5/new_clones/q/funq' &
git clone https://github.com/qbists/studyq '/storage/nvme5/new_clones/q/studyq' &
git clone https://github.com/KxSystems/kdb-tick '/storage/nvme5/new_clones/q/kdb-tick' &
git clone https://github.com/DataIntellectTech/TorQ-Finance-Starter-Pack '/storage/nvme5/new_clones/q/TorQ-Finance-Starter-Pack' &
git clone https://github.com/KxSystems/ml '/storage/nvme5/new_clones/q/ml' &
git clone https://github.com/BuaBook/kdb-common '/storage/nvme5/new_clones/q/kdb-common' &
git clone https://github.com/finos/kdb '/storage/nvme5/new_clones/q/kdb' &
git clone https://github.com/uiocompcat/tmQM '/storage/nvme5/new_clones/q/tmQM' &
git clone https://github.com/jonathonmcmurray/reQ '/storage/nvme5/new_clones/q/reQ' &
git clone https://github.com/LeslieGoldsmith/qprof '/storage/nvme5/new_clones/q/qprof' &
git clone https://github.com/poetiq/poetiq '/storage/nvme5/new_clones/q/poetiq' &
git clone https://github.com/breuleux/quaint '/storage/nvme5/new_clones/q/quaint' &
git clone https://github.com/LeslieGoldsmith/ws '/storage/nvme5/new_clones/q/ws' &
git clone https://github.com/microsoft/QBASHER '/storage/nvme5/new_clones/q/QBASHER' &
git clone https://github.com/nugend/qspec '/storage/nvme5/new_clones/q/qspec' &
git clone https://github.com/jonathonmcmurray/ws.q '/storage/nvme5/new_clones/q/ws.q' &
git clone https://github.com/psaris/q4q '/storage/nvme5/new_clones/q/q4q' &
git clone https://github.com/jlas/ml.q '/storage/nvme5/new_clones/q/ml.q' &
git clone https://github.com/jbrussell/MATnoise '/storage/nvme5/new_clones/q/MATnoise' &
git clone https://github.com/LeslieGoldsmith/dpy '/storage/nvme5/new_clones/q/dpy' &
git clone https://github.com/KxSystems/automl '/storage/nvme5/new_clones/q/automl' &
git clone https://github.com/donnaken15/FastGH3 '/storage/nvme5/new_clones/q/FastGH3' &
git clone https://github.com/quintanar401/q2c '/storage/nvme5/new_clones/q/q2c' &
git clone https://github.com/KxSystems/analyst-training '/storage/nvme5/new_clones/q/analyst-training' &
git clone https://github.com/asatirahul/cryptoq '/storage/nvme5/new_clones/q/cryptoq' &
git clone https://github.com/sandybradley/qMachineTrader '/storage/nvme5/new_clones/q/qMachineTrader' &
git clone https://github.com/DataIntellectTech/kdb-fix-adaptor '/storage/nvme5/new_clones/q/kdb-fix-adaptor' &
git clone https://github.com/KxSystems/nlp '/storage/nvme5/new_clones/q/nlp' &
git clone https://github.com/jasraj/q-doc '/storage/nvme5/new_clones/q/q-doc' &
git clone https://github.com/patmok/unparse '/storage/nvme5/new_clones/q/unparse' &
git clone https://github.com/picoDoc/betfair-data-capture '/storage/nvme5/new_clones/q/betfair-data-capture' &
git clone https://github.com/bradleyboyuyang/FTEC5530-Algo-Trading '/storage/nvme5/new_clones/q/FTEC5530-Algo-Trading' &
git clone https://github.com/mkeenan-kdb/snpDive '/storage/nvme5/new_clones/q/snpDive' &
git clone https://github.com/KxSystems/prometheus-kdb-exporter '/storage/nvme5/new_clones/q/prometheus-kdb-exporter' &
git clone https://github.com/prodrive11/log4q '/storage/nvme5/new_clones/q/log4q' &
git clone https://github.com/adavies42/qist '/storage/nvme5/new_clones/q/qist' &
git clone https://github.com/DataIntellectTech/TorQ-CME '/storage/nvme5/new_clones/q/TorQ-CME' &
git clone https://github.com/KxSystems/kdb-taq '/storage/nvme5/new_clones/q/kdb-taq' &
git clone https://github.com/fateplayer/WoWAutoFishing '/storage/nvme5/new_clones/q/WoWAutoFishing' &
git clone https://github.com/KxSystems/nano '/storage/nvme5/new_clones/q/nano' &
git clone https://github.com/adotsch/aoc '/storage/nvme5/new_clones/q/aoc' &
git clone https://github.com/simongarland/tick '/storage/nvme5/new_clones/q/tick' &
git clone https://github.com/t-martin/qmail '/storage/nvme5/new_clones/q/qmail' &
git clone https://github.com/jonathonmcmurray/kdbslack '/storage/nvme5/new_clones/q/kdbslack' &
git clone https://github.com/kdbcn/kdb '/storage/nvme5/new_clones/q/kdb' &
git clone https://github.com/simongarland/csvguess '/storage/nvme5/new_clones/q/csvguess' &
git clone https://github.com/sandybradley/qMonitor '/storage/nvme5/new_clones/q/qMonitor' &
git clone https://github.com/mkst/aoc '/storage/nvme5/new_clones/q/aoc' &
git clone https://github.com/samkennerly/q_practice '/storage/nvme5/new_clones/q/q_practice' &
git clone https://github.com/LeslieGoldsmith/ed '/storage/nvme5/new_clones/q/ed' &
git clone https://github.com/robmoore-i/JsonRestApi '/storage/nvme5/new_clones/q/JsonRestApi' &
git clone https://github.com/aa1024/learnQ '/storage/nvme5/new_clones/q/learnQ' &
git clone https://github.com/jonathonmcmurray/qwebapi '/storage/nvme5/new_clones/q/qwebapi' &
git clone https://github.com/aa1024/strQ '/storage/nvme5/new_clones/q/strQ' &
git clone https://github.com/amr4i/Query-Biased-Multi-Document-Abstractive-Summarisation '/storage/nvme5/new_clones/q/Query-Biased-Multi-Document-Abstractive-Summarisation' &
git clone https://github.com/quintanar401/qll '/storage/nvme5/new_clones/q/qll' &
git clone https://github.com/drzwz/qbitmex '/storage/nvme5/new_clones/q/qbitmex' &
git clone https://github.com/sandybradley/qSignals '/storage/nvme5/new_clones/q/qSignals' &
git clone https://github.com/nicholasferguson/kdb.q.kalman.filter.beta.ETFs '/storage/nvme5/new_clones/q/kdb.q.kalman.filter.beta.ETFs' &
git clone https://github.com/virola/yys '/storage/nvme5/new_clones/q/yys' &
git clone https://github.com/DEIS-Tools/uppaal-models '/storage/nvme5/new_clones/q/uppaal-models' &
git clone https://github.com/DataIntellectTech/TorQ-Crypto '/storage/nvme5/new_clones/q/TorQ-Crypto' &
git clone https://github.com/awilson-kx/nlp '/storage/nvme5/new_clones/q/nlp' &
git clone https://github.com/aa1024/datetimeQ '/storage/nvme5/new_clones/q/datetimeQ' &
git clone https://github.com/farkasrebus/XtaBenchmarkSuite '/storage/nvme5/new_clones/q/XtaBenchmarkSuite' &
git clone https://github.com/anton-dovzhenko/advent-of-code '/storage/nvme5/new_clones/q/advent-of-code' &
git clone https://github.com/eda-ricercatore/qubos-solvers '/storage/nvme5/new_clones/q/qubos-solvers' &
git clone https://github.com/KxSystems/man '/storage/nvme5/new_clones/q/man' &
git clone https://github.com/danielkrizian/qlearn '/storage/nvme5/new_clones/q/qlearn' &
git clone https://github.com/mkst/perch '/storage/nvme5/new_clones/q/perch' &
git clone https://github.com/aa1024/sphinxQ '/storage/nvme5/new_clones/q/sphinxQ' &
git clone https://github.com/gyorokpeter/puzzle_solutions '/storage/nvme5/new_clones/q/puzzle_solutions' &
git clone https://github.com/ontop/ontop-tutorial '/storage/nvme5/new_clones/q/ontop-tutorial' &
git clone https://github.com/gyorokpeter/public '/storage/nvme5/new_clones/q/public' &
git clone https://github.com/ontop/npd-benchmark '/storage/nvme5/new_clones/q/npd-benchmark' &
git clone https://github.com/skeptiqos/qsl '/storage/nvme5/new_clones/q/qsl' &
git clone https://github.com/adotsch/datasets '/storage/nvme5/new_clones/q/datasets' &
git clone https://github.com/stevewirts/kdb-vnc '/storage/nvme5/new_clones/q/kdb-vnc' &
git clone https://github.com/psaris/mm '/storage/nvme5/new_clones/q/mm' &
git clone https://github.com/t-martin/qremote '/storage/nvme5/new_clones/q/qremote' &
git clone https://github.com/quintanar401/qchk '/storage/nvme5/new_clones/q/qchk' &
git clone https://github.com/agoodquant/qr '/storage/nvme5/new_clones/q/qr' &
git clone https://github.com/krish240574/embedPyMLAI '/storage/nvme5/new_clones/q/embedPyMLAI' &
git clone https://github.com/sandybradley/qMiner '/storage/nvme5/new_clones/q/qMiner' &
