#!/bin/bash

git clone https://github.com/Swordfish90/cool-retro-term '/storage/nvme5/new_clones/QML/cool-retro-term' &
git clone https://github.com/jaredtao/TaoQuick '/storage/nvme5/new_clones/QML/TaoQuick' &
git clone https://github.com/zhengtianzuo/QtQuickExamples '/storage/nvme5/new_clones/QML/QtQuickExamples' &
git clone https://github.com/ShowFL/Toou-2D '/storage/nvme5/new_clones/QML/Toou-2D' &
git clone https://github.com/lirios/fluid '/storage/nvme5/new_clones/QML/fluid' &
git clone https://github.com/Zren/plasma-applet-eventcalendar '/storage/nvme5/new_clones/QML/plasma-applet-eventcalendar' &
git clone https://github.com/brexis/qml-bootstrap '/storage/nvme5/new_clones/QML/qml-bootstrap' &
git clone https://github.com/je00/Vodka '/storage/nvme5/new_clones/QML/Vodka' &
git clone https://github.com/mengps/QmlControls '/storage/nvme5/new_clones/QML/QmlControls' &
git clone https://github.com/catppuccin/sddm '/storage/nvme5/new_clones/QML/sddm' &
git clone https://github.com/rschiang/material '/storage/nvme5/new_clones/QML/material' &
git clone https://github.com/Furkanzmc/QML-UI-Animations '/storage/nvme5/new_clones/QML/QML-UI-Animations' &
git clone https://github.com/OlivierLDff/Qaterial '/storage/nvme5/new_clones/QML/Qaterial' &
git clone https://github.com/status-im/status-desktop '/storage/nvme5/new_clones/QML/status-desktop' &
git clone https://github.com/amlwwalker/got-qt '/storage/nvme5/new_clones/QML/got-qt' &
git clone https://github.com/penk/terrarium-app '/storage/nvme5/new_clones/QML/terrarium-app' &
git clone https://github.com/Furkanzmc/QML-Loaders '/storage/nvme5/new_clones/QML/QML-Loaders' &
git clone https://github.com/KDE/kirigami '/storage/nvme5/new_clones/QML/kirigami' &
git clone https://github.com/MidoriYakumo/learnopengl-qt3d '/storage/nvme5/new_clones/QML/learnopengl-qt3d' &
git clone https://github.com/Yubico/yubikey-manager-qt '/storage/nvme5/new_clones/QML/yubikey-manager-qt' &
git clone https://github.com/g-fb/haruna '/storage/nvme5/new_clones/QML/haruna' &
git clone https://github.com/benlau/quickandroid '/storage/nvme5/new_clones/QML/quickandroid' &
git clone https://github.com/gcompris/GCompris-qt '/storage/nvme5/new_clones/QML/GCompris-qt' &
git clone https://github.com/StratifyLabs/StratifyQML '/storage/nvme5/new_clones/QML/StratifyQML' &
git clone https://github.com/lirios/browser '/storage/nvme5/new_clones/QML/browser' &
git clone https://github.com/dps/remarkable-keywriter '/storage/nvme5/new_clones/QML/remarkable-keywriter' &
git clone https://github.com/GDPURJYFS/WellChat '/storage/nvme5/new_clones/QML/WellChat' &
git clone https://github.com/qyvlik/Flat.qml '/storage/nvme5/new_clones/QML/Flat.qml' &
git clone https://github.com/FRC-Utilities/QDriverStation '/storage/nvme5/new_clones/QML/QDriverStation' &
git clone https://github.com/muesli/telephant '/storage/nvme5/new_clones/QML/telephant' &
git clone https://github.com/benlau/quickpromise '/storage/nvme5/new_clones/QML/quickpromise' &
git clone https://github.com/KDE/plasma-mobile '/storage/nvme5/new_clones/QML/plasma-mobile' &
git clone https://github.com/benlau/quickios '/storage/nvme5/new_clones/QML/quickios' &
git clone https://github.com/limetext/lime-qml '/storage/nvme5/new_clones/QML/lime-qml' &
git clone https://github.com/kromain/qml-utils '/storage/nvme5/new_clones/QML/qml-utils' &
git clone https://github.com/esjeon/kwin-forceblur '/storage/nvme5/new_clones/QML/kwin-forceblur' &
git clone https://github.com/charleyglynn/OSM-Shapefile-QGIS-stylesheets '/storage/nvme5/new_clones/QML/OSM-Shapefile-QGIS-stylesheets' &
git clone https://github.com/alamminsalo/qmlnotify '/storage/nvme5/new_clones/QML/qmlnotify' &
git clone https://github.com/lll2yu/sddm-lain-wired-theme '/storage/nvme5/new_clones/QML/sddm-lain-wired-theme' &
git clone https://github.com/dps/remarkable-wikipedia '/storage/nvme5/new_clones/QML/remarkable-wikipedia' &
git clone https://github.com/olegyadrov/qmlcreator '/storage/nvme5/new_clones/QML/qmlcreator' &
git clone https://github.com/Zren/plasma-applet-tiledmenu '/storage/nvme5/new_clones/QML/plasma-applet-tiledmenu' &
git clone https://github.com/KDE/plasma-bigscreen '/storage/nvme5/new_clones/QML/plasma-bigscreen' &
git clone https://github.com/qyvlik/Chart.qml '/storage/nvme5/new_clones/QML/Chart.qml' &
git clone https://github.com/luoyayun361/Qt-QML-Example '/storage/nvme5/new_clones/QML/Qt-QML-Example' &
git clone https://github.com/paju1986/PlasmaConfSaver '/storage/nvme5/new_clones/QML/PlasmaConfSaver' &
git clone https://github.com/pansinm/CleanPlayer '/storage/nvme5/new_clones/QML/CleanPlayer' &
git clone https://github.com/15th/qmlStyle '/storage/nvme5/new_clones/QML/qmlStyle' &
git clone https://github.com/KDE/haruna '/storage/nvme5/new_clones/QML/haruna' &
git clone https://github.com/arunpkio/RadialBarDemo '/storage/nvme5/new_clones/QML/RadialBarDemo' &
git clone https://github.com/QMLCommunity/font-awesome-qml '/storage/nvme5/new_clones/QML/font-awesome-qml' &
git clone https://github.com/nhanb/com.nerdyweekly.animated '/storage/nvme5/new_clones/QML/com.nerdyweekly.animated' &
git clone https://github.com/qt/qtvirtualkeyboard '/storage/nvme5/new_clones/QML/qtvirtualkeyboard' &
git clone https://github.com/andreatta/config '/storage/nvme5/new_clones/QML/config' &
git clone https://github.com/Wanderson-Magalhaes/App_Bank_GUI_v01_PySide_Or_PyQt_Qt_Quick_QML '/storage/nvme5/new_clones/QML/App_Bank_GUI_v01_PySide_Or_PyQt_Qt_Quick_QML' &
git clone https://github.com/aeagean/DeployQt '/storage/nvme5/new_clones/QML/DeployQt' &
git clone https://github.com/xerolinux/xero-layan-git '/storage/nvme5/new_clones/QML/xero-layan-git' &
git clone https://github.com/jaredtao/TableEdit '/storage/nvme5/new_clones/QML/TableEdit' &
git clone https://github.com/MichaelVoelkel/ChartJs2QML '/storage/nvme5/new_clones/QML/ChartJs2QML' &
git clone https://github.com/kokernutz/traktor-kontrol-screens '/storage/nvme5/new_clones/QML/traktor-kontrol-screens' &
git clone https://github.com/stuomas/delicious-sddm-theme '/storage/nvme5/new_clones/QML/delicious-sddm-theme' &
git clone https://github.com/EricKotato/sddm-slice '/storage/nvme5/new_clones/QML/sddm-slice' &
git clone https://github.com/ErikMinekus/traktor-kontrol-screens '/storage/nvme5/new_clones/QML/traktor-kontrol-screens' &
git clone https://github.com/OlivierLDff/QaterialGallery '/storage/nvme5/new_clones/QML/QaterialGallery' &
git clone https://github.com/arunpkio/CircularSlider '/storage/nvme5/new_clones/QML/CircularSlider' &
git clone https://github.com/alex-adam/Tesla '/storage/nvme5/new_clones/QML/Tesla' &
git clone https://github.com/Esri/arcgis-appstudio-samples '/storage/nvme5/new_clones/QML/arcgis-appstudio-samples' &
git clone https://github.com/halverneus/org.kde.video '/storage/nvme5/new_clones/QML/org.kde.video' &
git clone https://github.com/johanhelsing/qt-csd-demo '/storage/nvme5/new_clones/QML/qt-csd-demo' &
git clone https://github.com/p-connor/plasma-drawer '/storage/nvme5/new_clones/QML/plasma-drawer' &
git clone https://github.com/ndesai/sqlite-editor-qtqml '/storage/nvme5/new_clones/QML/sqlite-editor-qtqml' &
git clone https://github.com/buttleofx/ButtleOFX '/storage/nvme5/new_clones/QML/ButtleOFX' &
git clone https://github.com/kasra-hosseini/obspyDMT '/storage/nvme5/new_clones/QML/obspyDMT' &
git clone https://github.com/FelgoSDK/FlappyBird '/storage/nvme5/new_clones/QML/FlappyBird' &
git clone https://github.com/KDE/qqc2-desktop-style '/storage/nvme5/new_clones/QML/qqc2-desktop-style' &
git clone https://github.com/Miker2808/Robot-Contorl-Qt-GUI-With-ROS '/storage/nvme5/new_clones/QML/Robot-Contorl-Qt-GUI-With-ROS' &
git clone https://github.com/aeagean/QmlUI '/storage/nvme5/new_clones/QML/QmlUI' &
git clone https://github.com/seanwu1105/neural-network-sandbox '/storage/nvme5/new_clones/QML/neural-network-sandbox' &
git clone https://github.com/goplayegg/AcfunQml '/storage/nvme5/new_clones/QML/AcfunQml' &
git clone https://github.com/alamminsalo/qml-launcher '/storage/nvme5/new_clones/QML/qml-launcher' &
git clone https://github.com/emericg/QmlAppTemplate '/storage/nvme5/new_clones/QML/QmlAppTemplate' &
git clone https://github.com/qyvlik/QtQuickAppDemo '/storage/nvme5/new_clones/QML/QtQuickAppDemo' &
git clone https://github.com/ycdxsb/LibraryManageDesktopApp '/storage/nvme5/new_clones/QML/LibraryManageDesktopApp' &
git clone https://github.com/kbroulik/lottie-qml '/storage/nvme5/new_clones/QML/lottie-qml' &
git clone https://github.com/ErikMinekus/traktor-api-client '/storage/nvme5/new_clones/QML/traktor-api-client' &
git clone https://github.com/DrewNaylor/Retiled '/storage/nvme5/new_clones/QML/Retiled' &
git clone https://github.com/kartoza/docker-qgis-server '/storage/nvme5/new_clones/QML/docker-qgis-server' &
git clone https://github.com/MarcinOrlowski/html-clock-plasmoid '/storage/nvme5/new_clones/QML/html-clock-plasmoid' &
git clone https://github.com/astatide/kwinOverview '/storage/nvme5/new_clones/QML/kwinOverview' &
git clone https://github.com/jaredtao/TreeEdit '/storage/nvme5/new_clones/QML/TreeEdit' &
git clone https://github.com/xiaoyong/2048-Qt '/storage/nvme5/new_clones/QML/2048-Qt' &
git clone https://github.com/Einswilli/KivymdStudio '/storage/nvme5/new_clones/QML/KivymdStudio' &
git clone https://github.com/obeezzy/FlatUI '/storage/nvme5/new_clones/QML/FlatUI' &
git clone https://github.com/berkbavas/QmlFlightInstruments '/storage/nvme5/new_clones/QML/QmlFlightInstruments' &
git clone https://github.com/qmlnet/qmlnet-examples '/storage/nvme5/new_clones/QML/qmlnet-examples' &
git clone https://github.com/reHackable/reHackable-HelloWorld '/storage/nvme5/new_clones/QML/reHackable-HelloWorld' &
git clone https://github.com/lxqt/sddm-config-editor '/storage/nvme5/new_clones/QML/sddm-config-editor' &
git clone https://github.com/surfsky/QmlExplorer '/storage/nvme5/new_clones/QML/QmlExplorer' &
git clone https://github.com/cbartsch/Slippipedia '/storage/nvme5/new_clones/QML/Slippipedia' &
git clone https://github.com/Zren/plasma-applet-todolist '/storage/nvme5/new_clones/QML/plasma-applet-todolist' &
git clone https://github.com/HelloVolla/android-launcher-qt '/storage/nvme5/new_clones/QML/android-launcher-qt' &
git clone https://github.com/qt/qtquickcontrols '/storage/nvme5/new_clones/QML/qtquickcontrols' &
git clone https://github.com/nx-desktop/nx-plasma-look-and-feel '/storage/nvme5/new_clones/QML/nx-plasma-look-and-feel' &
git clone https://github.com/KDE/plasma-systemmonitor '/storage/nvme5/new_clones/QML/plasma-systemmonitor' &
git clone https://github.com/wonder-sk/qt3d-experiments '/storage/nvme5/new_clones/QML/qt3d-experiments' &
git clone https://github.com/219-design/qt-qml-project-template-with-ci '/storage/nvme5/new_clones/QML/qt-qml-project-template-with-ci' &
git clone https://github.com/Wanderson-Magalhaes/Python_Discord_PySide_Or_PyQt_Qt_Quick_QML '/storage/nvme5/new_clones/QML/Python_Discord_PySide_Or_PyQt_Qt_Quick_QML' &
git clone https://github.com/Elleo/cutespotify '/storage/nvme5/new_clones/QML/cutespotify' &
git clone https://github.com/Match-Yang/sddm-deepin '/storage/nvme5/new_clones/QML/sddm-deepin' &
git clone https://github.com/mivoligo/Zeegaree '/storage/nvme5/new_clones/QML/Zeegaree' &
git clone https://github.com/OrdnanceSurvey/OSMM-Topography-Layer-stylesheets '/storage/nvme5/new_clones/QML/OSMM-Topography-Layer-stylesheets' &
git clone https://github.com/foxoman/pdftoword '/storage/nvme5/new_clones/QML/pdftoword' &
git clone https://github.com/IndeemaSoftware/QDashBoard '/storage/nvme5/new_clones/QML/QDashBoard' &
git clone https://github.com/patrickelectric/SLAM_Qt '/storage/nvme5/new_clones/QML/SLAM_Qt' &
git clone https://github.com/Ableton/aqt-cassowary '/storage/nvme5/new_clones/QML/aqt-cassowary' &
git clone https://github.com/0smr/neumorphism '/storage/nvme5/new_clones/QML/neumorphism' &
git clone https://github.com/FelgoSDK/Demos-Examples '/storage/nvme5/new_clones/QML/Demos-Examples' &
git clone https://github.com/benlau/fontawesome.pri '/storage/nvme5/new_clones/QML/fontawesome.pri' &
git clone https://github.com/larpon/DeadAscend '/storage/nvme5/new_clones/QML/DeadAscend' &
git clone https://github.com/storeman-developers/harbour-storeman '/storage/nvme5/new_clones/QML/harbour-storeman' &
git clone https://github.com/OML-NPA/EasyML.jl '/storage/nvme5/new_clones/QML/EasyML.jl' &
git clone https://github.com/erpas/rgis '/storage/nvme5/new_clones/QML/rgis' &
git clone https://github.com/dobokirisame/qml-filedialog '/storage/nvme5/new_clones/QML/qml-filedialog' &
git clone https://github.com/pledi/EmberControl '/storage/nvme5/new_clones/QML/EmberControl' &
git clone https://github.com/XuChaoChi/SmartHouse '/storage/nvme5/new_clones/QML/SmartHouse' &
git clone https://github.com/arunpkio/UserLoginApp '/storage/nvme5/new_clones/QML/UserLoginApp' &
git clone https://github.com/AsteroidOS/unofficial-watchfaces '/storage/nvme5/new_clones/QML/unofficial-watchfaces' &
git clone https://github.com/Karry/osmscout-sailfish '/storage/nvme5/new_clones/QML/osmscout-sailfish' &
git clone https://github.com/rshest/qml-colorpicker '/storage/nvme5/new_clones/QML/qml-colorpicker' &
git clone https://github.com/vvzen/pyside2-qml-examples '/storage/nvme5/new_clones/QML/pyside2-qml-examples' &
git clone https://github.com/go-qamel/json-to-go '/storage/nvme5/new_clones/QML/json-to-go' &
git clone https://github.com/OrdnanceSurvey/OS-Open-Zoomstack-Stylesheets '/storage/nvme5/new_clones/QML/OS-Open-Zoomstack-Stylesheets' &
git clone https://github.com/jemc/qml-sockets '/storage/nvme5/new_clones/QML/qml-sockets' &
git clone https://github.com/gpodder/gpodder-sailfish '/storage/nvme5/new_clones/QML/gpodder-sailfish' &
git clone https://github.com/koldbyte/termoid '/storage/nvme5/new_clones/QML/termoid' &
git clone https://github.com/mixedbredie/QGIS-styles '/storage/nvme5/new_clones/QML/QGIS-styles' &
git clone https://github.com/QGEP/QGEP '/storage/nvme5/new_clones/QML/QGEP' &
git clone https://github.com/Zren/mpvz '/storage/nvme5/new_clones/QML/mpvz' &
git clone https://github.com/analogdevicesinc/Pixelpulse2 '/storage/nvme5/new_clones/QML/Pixelpulse2' &
git clone https://github.com/qt-labs/qml-presentation-system '/storage/nvme5/new_clones/QML/qml-presentation-system' &
git clone https://github.com/patrickelectric/mini-qml '/storage/nvme5/new_clones/QML/mini-qml' &
git clone https://github.com/qewer33/ClearClock '/storage/nvme5/new_clones/QML/ClearClock' &
git clone https://github.com/zjgo007/QmlDemo '/storage/nvme5/new_clones/QML/QmlDemo' &
git clone https://github.com/AsteroidOS/asteroid-launcher '/storage/nvme5/new_clones/QML/asteroid-launcher' &
git clone https://github.com/OlivierLDff/QaterialHotReload '/storage/nvme5/new_clones/QML/QaterialHotReload' &
git clone https://github.com/Zren/plasma-wallpapers '/storage/nvme5/new_clones/QML/plasma-wallpapers' &
git clone https://github.com/cjmdaixi/DarkSwitch '/storage/nvme5/new_clones/QML/DarkSwitch' &
git clone https://github.com/Open-UAV/openuav-turbovnc '/storage/nvme5/new_clones/QML/openuav-turbovnc' &
git clone https://github.com/ipbc-dev/bittube-wallet-gui '/storage/nvme5/new_clones/QML/bittube-wallet-gui' &
git clone https://github.com/ekke/drawer_nav_x '/storage/nvme5/new_clones/QML/drawer_nav_x' &
git clone https://github.com/KDE/gcompris '/storage/nvme5/new_clones/QML/gcompris' &
git clone https://github.com/OpenMAR/PiTool '/storage/nvme5/new_clones/QML/PiTool' &
git clone https://github.com/jaredtao/Qt3D-learn '/storage/nvme5/new_clones/QML/Qt3D-learn' &
git clone https://github.com/alcroito/qt_world_summit_2019_cmake_vcpkg_app '/storage/nvme5/new_clones/QML/qt_world_summit_2019_cmake_vcpkg_app' &
git clone https://github.com/hahn-kev/QmlGrid '/storage/nvme5/new_clones/QML/QmlGrid' &
git clone https://github.com/MidoriYakumo/qml-virtualkey '/storage/nvme5/new_clones/QML/qml-virtualkey' &
git clone https://github.com/bog-dan-ro/spectacol '/storage/nvme5/new_clones/QML/spectacol' &
git clone https://github.com/cossatot/gem-global-active-faults '/storage/nvme5/new_clones/QML/gem-global-active-faults' &
git clone https://github.com/KDE/plasma-mycroft '/storage/nvme5/new_clones/QML/plasma-mycroft' &
git clone https://github.com/mariusmotea/qtHue '/storage/nvme5/new_clones/QML/qtHue' &
git clone https://github.com/djfumberger/retromega '/storage/nvme5/new_clones/QML/retromega' &
git clone https://github.com/RSATom/QmlVlcDemo '/storage/nvme5/new_clones/QML/QmlVlcDemo' &
git clone https://github.com/M4rtinK/universal-components '/storage/nvme5/new_clones/QML/universal-components' &
git clone https://github.com/richardmg/qtdd13_qmlapp '/storage/nvme5/new_clones/QML/qtdd13_qmlapp' &
git clone https://github.com/AllegorithmicSAS/painter-plugin-dcc-live-link '/storage/nvme5/new_clones/QML/painter-plugin-dcc-live-link' &
git clone https://github.com/arthurtaborda/Tomatoid '/storage/nvme5/new_clones/QML/Tomatoid' &
git clone https://github.com/calamares/calamares-extensions '/storage/nvme5/new_clones/QML/calamares-extensions' &
git clone https://github.com/qt/qtlocation '/storage/nvme5/new_clones/QML/qtlocation' &
git clone https://github.com/peihaowang/QmlTreeWidget '/storage/nvme5/new_clones/QML/QmlTreeWidget' &
git clone https://github.com/mohammadhasanzadeh/yacalendar '/storage/nvme5/new_clones/QML/yacalendar' &
git clone https://github.com/mohammadhasanzadeh/pulltorefreshhandler '/storage/nvme5/new_clones/QML/pulltorefreshhandler' &
git clone https://github.com/FabriceSalvaire/qt5-vector-graphic-shaders '/storage/nvme5/new_clones/QML/qt5-vector-graphic-shaders' &
git clone https://github.com/BLumia/pineapple-calendar '/storage/nvme5/new_clones/QML/pineapple-calendar' &
git clone https://github.com/TheCompez/CuteMobile '/storage/nvme5/new_clones/QML/CuteMobile' &
git clone https://github.com/sailfishos-open/waydroid '/storage/nvme5/new_clones/QML/waydroid' &
git clone https://github.com/mkoenigb/OSM-Geofabrik_Universal-QML-Style '/storage/nvme5/new_clones/QML/OSM-Geofabrik_Universal-QML-Style' &
git clone https://github.com/Michal-Szczepaniak/sddm-theme-amadeus '/storage/nvme5/new_clones/QML/sddm-theme-amadeus' &
git clone https://github.com/Furkanzmc/Everyday-QML '/storage/nvme5/new_clones/QML/Everyday-QML' &
git clone https://github.com/larpon/QtFirebaseExample '/storage/nvme5/new_clones/QML/QtFirebaseExample' &
git clone https://github.com/KDE/tok '/storage/nvme5/new_clones/QML/tok' &
git clone https://github.com/KhoaTranProgrammer/ProgressBarCollection '/storage/nvme5/new_clones/QML/ProgressBarCollection' &
git clone https://github.com/HanGee/Hankathon '/storage/nvme5/new_clones/QML/Hankathon' &
git clone https://github.com/varlesh/rounded '/storage/nvme5/new_clones/QML/rounded' &
git clone https://github.com/victronenergy/gui-v2 '/storage/nvme5/new_clones/QML/gui-v2' &
git clone https://github.com/musescore/harmonica_tablature '/storage/nvme5/new_clones/QML/harmonica_tablature' &
git clone https://github.com/adhec/plasma_tweaks '/storage/nvme5/new_clones/QML/plasma_tweaks' &
git clone https://github.com/oKcerG/QuickBehaviors '/storage/nvme5/new_clones/QML/QuickBehaviors' &
git clone https://github.com/axionl/OhMyQt '/storage/nvme5/new_clones/QML/OhMyQt' &
git clone https://github.com/plaidman/retromega-next '/storage/nvme5/new_clones/QML/retromega-next' &
git clone https://github.com/robbibt/australian-rivers '/storage/nvme5/new_clones/QML/australian-rivers' &
git clone https://github.com/dudantas/tibia-client '/storage/nvme5/new_clones/QML/tibia-client' &
git clone https://github.com/nokka/slashdiablo-launcher '/storage/nvme5/new_clones/QML/slashdiablo-launcher' &
git clone https://github.com/tilorenz/compact_pager '/storage/nvme5/new_clones/QML/compact_pager' &
git clone https://github.com/scytheStudio/qt_add_qml_module_example '/storage/nvme5/new_clones/QML/qt_add_qml_module_example' &
git clone https://github.com/ubuntu/snap-tutorials-code '/storage/nvme5/new_clones/QML/snap-tutorials-code' &
git clone https://github.com/oKcerG/SFPMShowcase '/storage/nvme5/new_clones/QML/SFPMShowcase' &
git clone https://github.com/ekke/ekkesBTLEexample '/storage/nvme5/new_clones/QML/ekkesBTLEexample' &
git clone https://github.com/jeetee/MuseScore_TempoChanges '/storage/nvme5/new_clones/QML/MuseScore_TempoChanges' &
git clone https://github.com/CODeRUS/better-sailfishos-qmltypes '/storage/nvme5/new_clones/QML/better-sailfishos-qmltypes' &
git clone https://github.com/ruinivist/NowPlaying '/storage/nvme5/new_clones/QML/NowPlaying' &
git clone https://github.com/KDE/kirigami-gallery '/storage/nvme5/new_clones/QML/kirigami-gallery' &
git clone https://github.com/KDE/plasma-sdk '/storage/nvme5/new_clones/QML/plasma-sdk' &
git clone https://github.com/tworaz/sailfish-ytplayer '/storage/nvme5/new_clones/QML/sailfish-ytplayer' &
git clone https://github.com/Jojo-Schmitz/batch_export '/storage/nvme5/new_clones/QML/batch_export' &
git clone https://github.com/dmitrio95/fretboard-plugin '/storage/nvme5/new_clones/QML/fretboard-plugin' &
git clone https://github.com/chadmv/qmlmaya '/storage/nvme5/new_clones/QML/qmlmaya' &
git clone https://github.com/GDPURJYFS/Sparrow '/storage/nvme5/new_clones/QML/Sparrow' &
git clone https://github.com/qyvlik/Sparrow.2 '/storage/nvme5/new_clones/QML/Sparrow.2' &
git clone https://github.com/Pixep/qt-quick-responsive-helper '/storage/nvme5/new_clones/QML/qt-quick-responsive-helper' &
git clone https://github.com/lcoandrade/OSMDownloader '/storage/nvme5/new_clones/QML/OSMDownloader' &
git clone https://github.com/KDE/mauikit '/storage/nvme5/new_clones/QML/mauikit' &
git clone https://github.com/unau-thorized/edi-tableview '/storage/nvme5/new_clones/QML/edi-tableview' &
git clone https://github.com/EXL/BezierClock '/storage/nvme5/new_clones/QML/BezierClock' &
git clone https://github.com/lehklu/Vallpaper '/storage/nvme5/new_clones/QML/Vallpaper' &
git clone https://github.com/pkobrien/sudoku-qml '/storage/nvme5/new_clones/QML/sudoku-qml' &
git clone https://github.com/dark-eye/com.darkeye.animatedImage '/storage/nvme5/new_clones/QML/com.darkeye.animatedImage' &
git clone https://github.com/nautilor/nord-sddm '/storage/nvme5/new_clones/QML/nord-sddm' &
git clone https://github.com/AgoraIO/Agora-with-QT '/storage/nvme5/new_clones/QML/Agora-with-QT' &
git clone https://github.com/AmirHosseinCH/CreditCardForm '/storage/nvme5/new_clones/QML/CreditCardForm' &
git clone https://github.com/olegyadrov/qmlparticleeditor '/storage/nvme5/new_clones/QML/qmlparticleeditor' &
git clone https://github.com/AmericanRedCross/qgis-styles '/storage/nvme5/new_clones/QML/qgis-styles' &
git clone https://github.com/KDE/plasma-phone-components '/storage/nvme5/new_clones/QML/plasma-phone-components' &
git clone https://github.com/Esri/TilePackageKreator '/storage/nvme5/new_clones/QML/TilePackageKreator' &
git clone https://github.com/scala-network/TorqueGUI '/storage/nvme5/new_clones/QML/TorqueGUI' &
git clone https://github.com/NOAA-OWP/hydrofabric '/storage/nvme5/new_clones/QML/hydrofabric' &
git clone https://github.com/chengjianxi/Weather '/storage/nvme5/new_clones/QML/Weather' &
git clone https://github.com/status-im/StatusQ '/storage/nvme5/new_clones/QML/StatusQ' &
git clone https://github.com/AmirHosseinCH/SideBar '/storage/nvme5/new_clones/QML/SideBar' &
git clone https://github.com/kgjenkins/ophz '/storage/nvme5/new_clones/QML/ophz' &
git clone https://github.com/KDE/plasma-active-window-control '/storage/nvme5/new_clones/QML/plasma-active-window-control' &
git clone https://github.com/SublimeText/QML '/storage/nvme5/new_clones/QML/QML' &
git clone https://github.com/riquenunes/pegasus-theme-npe '/storage/nvme5/new_clones/QML/pegasus-theme-npe' &
git clone https://github.com/HighEloDevs/Analysis-Tool-for-Undergrad-Students '/storage/nvme5/new_clones/QML/Analysis-Tool-for-Undergrad-Students' &
git clone https://github.com/Wanderson-Magalhaes/Login_With_PySide6_And_VSCode '/storage/nvme5/new_clones/QML/Login_With_PySide6_And_VSCode' &
git clone https://github.com/THMonster/kde-stuffs '/storage/nvme5/new_clones/QML/kde-stuffs' &
git clone https://github.com/BeamMW/beam-ui '/storage/nvme5/new_clones/QML/beam-ui' &
git clone https://github.com/gongjianbo/QmlModelView '/storage/nvme5/new_clones/QML/QmlModelView' &
git clone https://github.com/CrimsonAS/qmlbench '/storage/nvme5/new_clones/QML/qmlbench' &
git clone https://github.com/KhoaTranProgrammer/QtQml_Dashboard '/storage/nvme5/new_clones/QML/QtQml_Dashboard' &
git clone https://github.com/llelectronics/videoPlayer '/storage/nvme5/new_clones/QML/videoPlayer' &
git clone https://github.com/AIIX/Mycroft-Ai-QtApplication '/storage/nvme5/new_clones/QML/Mycroft-Ai-QtApplication' &
git clone https://github.com/CODeRUS/harbour-lgremote-webos '/storage/nvme5/new_clones/QML/harbour-lgremote-webos' &
git clone https://github.com/toby20130333/stackedpages '/storage/nvme5/new_clones/QML/stackedpages' &
git clone https://github.com/confidentFeng/QML_Demo '/storage/nvme5/new_clones/QML/QML_Demo' &
git clone https://github.com/basilesimon/interactive-journalism-module '/storage/nvme5/new_clones/QML/interactive-journalism-module' &
git clone https://github.com/tmpsantos/qmapboxglapp '/storage/nvme5/new_clones/QML/qmapboxglapp' &
git clone https://github.com/abandonware/qt5-cinematic-experience '/storage/nvme5/new_clones/QML/qt5-cinematic-experience' &
git clone https://github.com/GISsymbology/symbols '/storage/nvme5/new_clones/QML/symbols' &
git clone https://github.com/PlayingKarrde/switchOS '/storage/nvme5/new_clones/QML/switchOS' &
git clone https://github.com/Wanderson-Magalhaes/Circular_ProgressBar '/storage/nvme5/new_clones/QML/Circular_ProgressBar' &
git clone https://github.com/MarcinOrlowski/crypto-tracker-plasmoid '/storage/nvme5/new_clones/QML/crypto-tracker-plasmoid' &
git clone https://github.com/rxlacroix/CarteTopo '/storage/nvme5/new_clones/QML/CarteTopo' &
git clone https://github.com/Zren/plasma-applet-githubissues '/storage/nvme5/new_clones/QML/plasma-applet-githubissues' &
git clone https://github.com/joe-easton/s4mk3 '/storage/nvme5/new_clones/QML/s4mk3' &
git clone https://github.com/zjgo007/QtQuick3D '/storage/nvme5/new_clones/QML/QtQuick3D' &
git clone https://github.com/Aarontheissueguy/WaydroidHelper '/storage/nvme5/new_clones/QML/WaydroidHelper' &
git clone https://github.com/Witekio/qt-and-android-whitepaper-apps '/storage/nvme5/new_clones/QML/qt-and-android-whitepaper-apps' &
git clone https://github.com/OrdnanceSurvey/OS-VectorMap-District-stylesheets '/storage/nvme5/new_clones/QML/OS-VectorMap-District-stylesheets' &
git clone https://github.com/nemomobile-ux/glacier-home '/storage/nvme5/new_clones/QML/glacier-home' &
git clone https://github.com/m-wynn/sddm_wynn-theme '/storage/nvme5/new_clones/QML/sddm_wynn-theme' &
git clone https://github.com/sirsoweird/jianpu-plugin '/storage/nvme5/new_clones/QML/jianpu-plugin' &
git clone https://github.com/XTRABYTES/XCITE.OLD '/storage/nvme5/new_clones/QML/XCITE.OLD' &
git clone https://github.com/newflydd/nodejs-fingure '/storage/nvme5/new_clones/QML/nodejs-fingure' &
git clone https://github.com/pureqml/controls '/storage/nvme5/new_clones/QML/controls' &
git clone https://github.com/qyvlik/ShaderToy.qml '/storage/nvme5/new_clones/QML/ShaderToy.qml' &
git clone https://github.com/milosolutions/mcharts '/storage/nvme5/new_clones/QML/mcharts' &
git clone https://github.com/savavel/qt-instrument-cluster '/storage/nvme5/new_clones/QML/qt-instrument-cluster' &
git clone https://github.com/rnanclares/Taller-pgRouting '/storage/nvme5/new_clones/QML/Taller-pgRouting' &
git clone https://github.com/ionicc/Youtube-mp3-downloader-light '/storage/nvme5/new_clones/QML/Youtube-mp3-downloader-light' &
git clone https://github.com/bigtreetech/BigtreeDesignAssistant '/storage/nvme5/new_clones/QML/BigtreeDesignAssistant' &
git clone https://github.com/HelloZB/QtAndroidFTDI '/storage/nvme5/new_clones/QML/QtAndroidFTDI' &
git clone https://github.com/evonove/mut '/storage/nvme5/new_clones/QML/mut' &
git clone https://github.com/3liz/osm-in-qgis '/storage/nvme5/new_clones/QML/osm-in-qgis' &
git clone https://github.com/0smr/qomponent '/storage/nvme5/new_clones/QML/qomponent' &
git clone https://github.com/kevelyn1/qgis_styles '/storage/nvme5/new_clones/QML/qgis_styles' &
git clone https://github.com/KDE/index-fm '/storage/nvme5/new_clones/QML/index-fm' &
git clone https://github.com/aaronsnoswell/QMLVirtualJoystick '/storage/nvme5/new_clones/QML/QMLVirtualJoystick' &
git clone https://github.com/spmdrd/plasma-applet-cryptocurrency-price '/storage/nvme5/new_clones/QML/plasma-applet-cryptocurrency-price' &
git clone https://github.com/FONQRI/MaterialUiSamplesQtQml '/storage/nvme5/new_clones/QML/MaterialUiSamplesQtQml' &
git clone https://github.com/Siecje/qml-explorer '/storage/nvme5/new_clones/QML/qml-explorer' &
git clone https://github.com/bunistack/awesome-qml-controls '/storage/nvme5/new_clones/QML/awesome-qml-controls' &
git clone https://github.com/RedL0tus/Activate-Plasma '/storage/nvme5/new_clones/QML/Activate-Plasma' &
git clone https://github.com/oclero/luna '/storage/nvme5/new_clones/QML/luna' &
git clone https://github.com/FireController1847/musescore-rich-presence '/storage/nvme5/new_clones/QML/musescore-rich-presence' &
git clone https://github.com/andreagen0r/ColorPicker '/storage/nvme5/new_clones/QML/ColorPicker' &
git clone https://github.com/Reverier-Xu/typrua '/storage/nvme5/new_clones/QML/typrua' &
git clone https://github.com/qtproject/learning-guides '/storage/nvme5/new_clones/QML/learning-guides' &
git clone https://github.com/larpon/qak '/storage/nvme5/new_clones/QML/qak' &
git clone https://github.com/kacebe/AtlantGIS '/storage/nvme5/new_clones/QML/AtlantGIS' &
git clone https://github.com/gabretana/simplicity-sddm-theme '/storage/nvme5/new_clones/QML/simplicity-sddm-theme' &
git clone https://github.com/iBelieve/quickpaper '/storage/nvme5/new_clones/QML/quickpaper' &
git clone https://github.com/KDE/plasma-angelfish '/storage/nvme5/new_clones/QML/plasma-angelfish' &
git clone https://github.com/pkoretic/LetiHome '/storage/nvme5/new_clones/QML/LetiHome' &
git clone https://github.com/avivace/breeze2-sddm-theme '/storage/nvme5/new_clones/QML/breeze2-sddm-theme' &
git clone https://github.com/qtproject/qt-apps-neptune3-ui '/storage/nvme5/new_clones/QML/qt-apps-neptune3-ui' &
git clone https://github.com/diracsbracket/qmltreeview2 '/storage/nvme5/new_clones/QML/qmltreeview2' &
git clone https://github.com/Luc-S/Toon-HASS '/storage/nvme5/new_clones/QML/Toon-HASS' &
git clone https://github.com/Jahirg/QML_Dashbord '/storage/nvme5/new_clones/QML/QML_Dashbord' &
git clone https://github.com/vigasan/RpiGpio '/storage/nvme5/new_clones/QML/RpiGpio' &
git clone https://github.com/gabrielchristo/qml-tableview '/storage/nvme5/new_clones/QML/qml-tableview' &
git clone https://github.com/anatolyk82/SlideMenu '/storage/nvme5/new_clones/QML/SlideMenu' &
git clone https://github.com/agateau/listviewdragitem '/storage/nvme5/new_clones/QML/listviewdragitem' &
git clone https://github.com/perericr/night-trains-map '/storage/nvme5/new_clones/QML/night-trains-map' &
git clone https://github.com/ekke/biz_data_x '/storage/nvme5/new_clones/QML/biz_data_x' &
git clone https://github.com/olpeh/wht '/storage/nvme5/new_clones/QML/wht' &
git clone https://github.com/skvark/Textractor '/storage/nvme5/new_clones/QML/Textractor' &
git clone https://github.com/pureqml/pureqml-web '/storage/nvme5/new_clones/QML/pureqml-web' &
git clone https://github.com/chsterz/isoworld '/storage/nvme5/new_clones/QML/isoworld' &
git clone https://github.com/akrutzler/plasma-audio-device-switcher '/storage/nvme5/new_clones/QML/plasma-audio-device-switcher' &
git clone https://github.com/sailfishos/python-sample '/storage/nvme5/new_clones/QML/python-sample' &
git clone https://github.com/qtrest/qtrest-example '/storage/nvme5/new_clones/QML/qtrest-example' &
git clone https://github.com/ubports/messaging-app '/storage/nvme5/new_clones/QML/messaging-app' &
git clone https://github.com/Jojo-Schmitz/notenames '/storage/nvme5/new_clones/QML/notenames' &
git clone https://github.com/sailfish-spotify/hutspot '/storage/nvme5/new_clones/QML/hutspot' &
git clone https://github.com/AllegorithmicSAS/painter-plugin-console '/storage/nvme5/new_clones/QML/painter-plugin-console' &
git clone https://github.com/amarula/cutekeyboard '/storage/nvme5/new_clones/QML/cutekeyboard' &
git clone https://github.com/JayTwoLab/qt-dashboard '/storage/nvme5/new_clones/QML/qt-dashboard' &
git clone https://github.com/Duoslow/zerotierIndicator '/storage/nvme5/new_clones/QML/zerotierIndicator' &
git clone https://github.com/shinas101/Anime-sddm-theme '/storage/nvme5/new_clones/QML/Anime-sddm-theme' &
git clone https://github.com/houmain/QML-NodeGraph '/storage/nvme5/new_clones/QML/QML-NodeGraph' &
git clone https://github.com/barche/QmlJuliaExamples '/storage/nvme5/new_clones/QML/QmlJuliaExamples' &
git clone https://github.com/Wanderson-Magalhaes/Splash_Screen_With_Login_Pyhton_And_QtQuick '/storage/nvme5/new_clones/QML/Splash_Screen_With_Login_Pyhton_And_QtQuick' &
git clone https://github.com/zhitko/speech-rate-meter '/storage/nvme5/new_clones/QML/speech-rate-meter' &
git clone https://github.com/quey-project/quey-ui '/storage/nvme5/new_clones/QML/quey-ui' &
git clone https://github.com/retifrav/translating-qml '/storage/nvme5/new_clones/QML/translating-qml' &
git clone https://github.com/KDE/plasma-settings '/storage/nvme5/new_clones/QML/plasma-settings' &
git clone https://github.com/yasser-sobhy/Gurra '/storage/nvme5/new_clones/QML/Gurra' &
git clone https://github.com/llelectronics/webcat '/storage/nvme5/new_clones/QML/webcat' &
git clone https://github.com/FOSS4GAcademy/GST104FOSS4GLabs '/storage/nvme5/new_clones/QML/GST104FOSS4GLabs' &
git clone https://github.com/ubports/dialer-app '/storage/nvme5/new_clones/QML/dialer-app' &
git clone https://github.com/olegyadrov/qmlplane '/storage/nvme5/new_clones/QML/qmlplane' &
git clone https://github.com/josshad/Glatop '/storage/nvme5/new_clones/QML/Glatop' &
git clone https://github.com/qtproject/qt-apps-neptune-ui '/storage/nvme5/new_clones/QML/qt-apps-neptune-ui' &
git clone https://github.com/capisce/motionblur '/storage/nvme5/new_clones/QML/motionblur' &
git clone https://github.com/AmirHosseinCH/EmojiPicker '/storage/nvme5/new_clones/QML/EmojiPicker' &
git clone https://github.com/Graph-ICS/Graph-ICS '/storage/nvme5/new_clones/QML/Graph-ICS' &
git clone https://github.com/geostyler/geostyler-qgis-parser '/storage/nvme5/new_clones/QML/geostyler-qgis-parser' &
git clone https://github.com/vigasan/MotorizedCam '/storage/nvme5/new_clones/QML/MotorizedCam' &
git clone https://github.com/pwuertz/QtQuickPlotScene '/storage/nvme5/new_clones/QML/QtQuickPlotScene' &
git clone https://github.com/cjmdaixi/FlipAnimation '/storage/nvme5/new_clones/QML/FlipAnimation' &
git clone https://github.com/stephenquan/qmlonline6 '/storage/nvme5/new_clones/QML/qmlonline6' &
git clone https://github.com/cnigfr/StaR-Eau '/storage/nvme5/new_clones/QML/StaR-Eau' &
git clone https://github.com/GDPURJYFS/StandardQtOnAndroid '/storage/nvme5/new_clones/QML/StandardQtOnAndroid' &
git clone https://github.com/ldanzinger/PyOtherSideForArcGIS '/storage/nvme5/new_clones/QML/PyOtherSideForArcGIS' &
git clone https://github.com/oniongarlic/qtquick-flickable-image-zoom '/storage/nvme5/new_clones/QML/qtquick-flickable-image-zoom' &
git clone https://github.com/OrdnanceSurvey/OS-OpenMap-Local-stylesheets '/storage/nvme5/new_clones/QML/OS-OpenMap-Local-stylesheets' &
git clone https://github.com/comexpertise/plasma-kdeconnect-sms '/storage/nvme5/new_clones/QML/plasma-kdeconnect-sms' &
git clone https://github.com/qyvlik/GLSL.qml '/storage/nvme5/new_clones/QML/GLSL.qml' &
git clone https://github.com/gpodder/gpodder-ui-qml '/storage/nvme5/new_clones/QML/gpodder-ui-qml' &
git clone https://github.com/ndesai/qtworldsummit '/storage/nvme5/new_clones/QML/qtworldsummit' &
git clone https://github.com/anatolyk82/ShaderTransitionView '/storage/nvme5/new_clones/QML/ShaderTransitionView' &
git clone https://github.com/webosbrew/custom-screensaver '/storage/nvme5/new_clones/QML/custom-screensaver' &
git clone https://github.com/PlayingKarrde/prosperoOS '/storage/nvme5/new_clones/QML/prosperoOS' &
git clone https://github.com/ddh4r4m/Stone '/storage/nvme5/new_clones/QML/Stone' &
git clone https://github.com/fauzie811/plasma-applet-simple10menu '/storage/nvme5/new_clones/QML/plasma-applet-simple10menu' &
git clone https://github.com/KDE/kirigami-addons '/storage/nvme5/new_clones/QML/kirigami-addons' &
git clone https://github.com/MarkoStanojevic12/ComponentLibrary '/storage/nvme5/new_clones/QML/ComponentLibrary' &
git clone https://github.com/pyclyy/project_test '/storage/nvme5/new_clones/QML/project_test' &
git clone https://github.com/fferri/qt3d-transform-gizmo '/storage/nvme5/new_clones/QML/qt3d-transform-gizmo' &
git clone https://github.com/kacpi2442/plasma-applet-covid-19 '/storage/nvme5/new_clones/QML/plasma-applet-covid-19' &
git clone https://github.com/xcaeag/Dem-Slicer-Qgis-Plugin '/storage/nvme5/new_clones/QML/Dem-Slicer-Qgis-Plugin' &
git clone https://github.com/unseon/QQuickDock '/storage/nvme5/new_clones/QML/QQuickDock' &
git clone https://github.com/berteh/musescore-chordsToNotes '/storage/nvme5/new_clones/QML/musescore-chordsToNotes' &
git clone https://github.com/kastravec/risipapp '/storage/nvme5/new_clones/QML/risipapp' &
git clone https://github.com/spuschhof/QMLTable '/storage/nvme5/new_clones/QML/QMLTable' &
git clone https://github.com/OrdnanceSurvey/OS-VectorMap-Local-stylesheets '/storage/nvme5/new_clones/QML/OS-VectorMap-Local-stylesheets' &
git clone https://github.com/djselbeck/smpc '/storage/nvme5/new_clones/QML/smpc' &
git clone https://github.com/demitov/dashApp '/storage/nvme5/new_clones/QML/dashApp' &
git clone https://github.com/Joker/timekeeper '/storage/nvme5/new_clones/QML/timekeeper' &
git clone https://github.com/machinekoder/QRemoteControl-Client '/storage/nvme5/new_clones/QML/QRemoteControl-Client' &
git clone https://github.com/Guidobelix/archlinux-themes-sddm '/storage/nvme5/new_clones/QML/archlinux-themes-sddm' &
git clone https://github.com/Ashifta/QtMobileApp '/storage/nvme5/new_clones/QML/QtMobileApp' &
git clone https://github.com/AIIX/youtube-skill '/storage/nvme5/new_clones/QML/youtube-skill' &
git clone https://github.com/philxan/WalkingBass '/storage/nvme5/new_clones/QML/WalkingBass' &
git clone https://github.com/chen-xiaoyao/WeTalk '/storage/nvme5/new_clones/QML/WeTalk' &
git clone https://github.com/AllegorithmicSAS/materialx_utils '/storage/nvme5/new_clones/QML/materialx_utils' &
git clone https://github.com/Parnassius/SysDVR-Qt '/storage/nvme5/new_clones/QML/SysDVR-Qt' &
git clone https://github.com/Zren/plasma-applet-presentwindows '/storage/nvme5/new_clones/QML/plasma-applet-presentwindows' &
git clone https://github.com/berkbavas/QmlJoystick '/storage/nvme5/new_clones/QML/QmlJoystick' &
git clone https://github.com/mshobeyri/DemonPresentationBoard '/storage/nvme5/new_clones/QML/DemonPresentationBoard' &
git clone https://github.com/0xebef/qube '/storage/nvme5/new_clones/QML/qube' &
git clone https://github.com/wbt729/quickdock '/storage/nvme5/new_clones/QML/quickdock' &
git clone https://github.com/JiepengTan/SubstancePainter-Plugin-Tutorial '/storage/nvme5/new_clones/QML/SubstancePainter-Plugin-Tutorial' &
git clone https://github.com/KDE/kweather '/storage/nvme5/new_clones/QML/kweather' &
git clone https://github.com/MakG10/plasma-applet-bitcoin-price '/storage/nvme5/new_clones/QML/plasma-applet-bitcoin-price' &
git clone https://github.com/rschiang/coscup-bidder '/storage/nvme5/new_clones/QML/coscup-bidder' &
git clone https://github.com/krruzic/Reader-YC '/storage/nvme5/new_clones/QML/Reader-YC' &
git clone https://github.com/AmericanRedCross/redcross_qgis_styles '/storage/nvme5/new_clones/QML/redcross_qgis_styles' &
git clone https://github.com/anpho/one3.0 '/storage/nvme5/new_clones/QML/one3.0' &
git clone https://github.com/RPG-18/SimpleGPSTracker '/storage/nvme5/new_clones/QML/SimpleGPSTracker' &
git clone https://github.com/toby20130333/qmlpathview '/storage/nvme5/new_clones/QML/qmlpathview' &
git clone https://github.com/rohitsinghsengar/qml-audio-player '/storage/nvme5/new_clones/QML/qml-audio-player' &
git clone https://github.com/qyvlik/Metro.qml '/storage/nvme5/new_clones/QML/Metro.qml' &
git clone https://github.com/penk/UbunTuTu '/storage/nvme5/new_clones/QML/UbunTuTu' &
git clone https://github.com/Match-Yang/Gbyzanz '/storage/nvme5/new_clones/QML/Gbyzanz' &
git clone https://github.com/ray-cast/mmd-export '/storage/nvme5/new_clones/QML/mmd-export' &
git clone https://github.com/qyvlik/GooeyEffects.qml '/storage/nvme5/new_clones/QML/GooeyEffects.qml' &
git clone https://github.com/miladdavoodi/Dragon '/storage/nvme5/new_clones/QML/Dragon' &
git clone https://github.com/KDE/krecorder '/storage/nvme5/new_clones/QML/krecorder' &
git clone https://github.com/maotingwei/QML '/storage/nvme5/new_clones/QML/QML' &
git clone https://github.com/rekomerio/qt-led-app '/storage/nvme5/new_clones/QML/qt-led-app' &
git clone https://github.com/SC-One/DropDownInputQML '/storage/nvme5/new_clones/QML/DropDownInputQML' &
git clone https://github.com/KDE/plasma-nano '/storage/nvme5/new_clones/QML/plasma-nano' &
git clone https://github.com/tubbadu/Scriptinator '/storage/nvme5/new_clones/QML/Scriptinator' &
git clone https://github.com/MontyTheSoftwareEngineer/CoolQMLButton '/storage/nvme5/new_clones/QML/CoolQMLButton' &
git clone https://github.com/FollowMyVote/BlockchainDemo '/storage/nvme5/new_clones/QML/BlockchainDemo' &
git clone https://github.com/lasconic/CustomBusyIndicator-QML '/storage/nvme5/new_clones/QML/CustomBusyIndicator-QML' &
git clone https://github.com/mivoligo/Zeegaree-Lite '/storage/nvme5/new_clones/QML/Zeegaree-Lite' &
git clone https://github.com/IvanSafonov/plasma-wallpaper-snow '/storage/nvme5/new_clones/QML/plasma-wallpaper-snow' &
git clone https://github.com/musescore/musescore_comments '/storage/nvme5/new_clones/QML/musescore_comments' &
git clone https://github.com/neversun/Slackfish '/storage/nvme5/new_clones/QML/Slackfish' &
git clone https://github.com/xdarklight/keystate-plasmoid '/storage/nvme5/new_clones/QML/keystate-plasmoid' &
git clone https://github.com/calaos/calaos_mobile '/storage/nvme5/new_clones/QML/calaos_mobile' &
git clone https://github.com/qyvlik/sqml '/storage/nvme5/new_clones/QML/sqml' &
git clone https://github.com/leamus/MakerFrame '/storage/nvme5/new_clones/QML/MakerFrame' &
git clone https://github.com/jaredtao/TaoShaderToy '/storage/nvme5/new_clones/QML/TaoShaderToy' &
git clone https://github.com/raspad-tablet/raspad-launcher '/storage/nvme5/new_clones/QML/raspad-launcher' &
git clone https://github.com/Daguerreo/QML-Dynamic-Material-Theme '/storage/nvme5/new_clones/QML/QML-Dynamic-Material-Theme' &
git clone https://github.com/heqro/stupid-simple-launcher '/storage/nvme5/new_clones/QML/stupid-simple-launcher' &
git clone https://github.com/PlayingKarrde/clearOS '/storage/nvme5/new_clones/QML/clearOS' &
git clone https://github.com/Furkanzmc/QML-for-Designers '/storage/nvme5/new_clones/QML/QML-for-Designers' &
git clone https://github.com/mengps/MChat '/storage/nvme5/new_clones/QML/MChat' &
git clone https://github.com/lutraconsulting/qgis-vectortiles-styles '/storage/nvme5/new_clones/QML/qgis-vectortiles-styles' &
git clone https://github.com/Furkanzmc/QML-Cpp-Access-Speed-Test '/storage/nvme5/new_clones/QML/QML-Cpp-Access-Speed-Test' &
git clone https://github.com/dmitrylis/ShaderEditor '/storage/nvme5/new_clones/QML/ShaderEditor' &
git clone https://github.com/eminfedar/debins '/storage/nvme5/new_clones/QML/debins' &
git clone https://github.com/mauikit/index '/storage/nvme5/new_clones/QML/index' &
git clone https://github.com/bojidar-bg/plasma-parallax-wallpaper '/storage/nvme5/new_clones/QML/plasma-parallax-wallpaper' &
git clone https://github.com/pigreco/COVID-19_ITA '/storage/nvme5/new_clones/QML/COVID-19_ITA' &
git clone https://github.com/scytheStudio/NFC-Demo '/storage/nvme5/new_clones/QML/NFC-Demo' &
git clone https://github.com/zl0i/QtAutoTools '/storage/nvme5/new_clones/QML/QtAutoTools' &
git clone https://github.com/HanGee/OwaViewer '/storage/nvme5/new_clones/QML/OwaViewer' &
git clone https://github.com/maxhora/ToDoList '/storage/nvme5/new_clones/QML/ToDoList' &
git clone https://github.com/matengxiao/QMLAutoResize '/storage/nvme5/new_clones/QML/QMLAutoResize' &
git clone https://github.com/Tarostar/QMLGalaxyPortal '/storage/nvme5/new_clones/QML/QMLGalaxyPortal' &
git clone https://github.com/Pelagicore/QmlAssetExporter '/storage/nvme5/new_clones/QML/QmlAssetExporter' &
git clone https://github.com/FelgoSDK/ParticleEditor '/storage/nvme5/new_clones/QML/ParticleEditor' &
git clone https://github.com/absturztaube/sddm-archlinux-theme '/storage/nvme5/new_clones/QML/sddm-archlinux-theme' &
git clone https://github.com/iBelieve/taskly '/storage/nvme5/new_clones/QML/taskly' &
git clone https://github.com/tolszak/MockupVirtualKeyboard '/storage/nvme5/new_clones/QML/MockupVirtualKeyboard' &
git clone https://github.com/brunoluvizotto/BattleCityQt '/storage/nvme5/new_clones/QML/BattleCityQt' &
git clone https://github.com/trolleway/osmot '/storage/nvme5/new_clones/QML/osmot' &
git clone https://github.com/PaulC91/gedotmap '/storage/nvme5/new_clones/QML/gedotmap' &
git clone https://github.com/custodian/orn-warehouse '/storage/nvme5/new_clones/QML/orn-warehouse' &
git clone https://github.com/Skycoder42/QuickExtras '/storage/nvme5/new_clones/QML/QuickExtras' &
git clone https://github.com/alpqr/quickmwtest '/storage/nvme5/new_clones/QML/quickmwtest' &
git clone https://github.com/charlesmillet/qgis_osm_styles '/storage/nvme5/new_clones/QML/qgis_osm_styles' &
git clone https://github.com/micuintus/harbour-Berlin-Vegan '/storage/nvme5/new_clones/QML/harbour-Berlin-Vegan' &
git clone https://github.com/doppioandante/kakoune-qml '/storage/nvme5/new_clones/QML/kakoune-qml' &
git clone https://github.com/quickly/quickly-skeleton '/storage/nvme5/new_clones/QML/quickly-skeleton' &
git clone https://github.com/xsjqqq123/MvGather-qml '/storage/nvme5/new_clones/QML/MvGather-qml' &
git clone https://github.com/azizka85/qDock '/storage/nvme5/new_clones/QML/qDock' &
git clone https://github.com/ghuntley/denon-prime4 '/storage/nvme5/new_clones/QML/denon-prime4' &
git clone https://github.com/pico-wizard/pico-wizard '/storage/nvme5/new_clones/QML/pico-wizard' &
git clone https://github.com/patrickelectric/qml-rules '/storage/nvme5/new_clones/QML/qml-rules' &
git clone https://github.com/polyeffects/digit_ui '/storage/nvme5/new_clones/QML/digit_ui' &
git clone https://github.com/kholodilinivan/DemoUnityandTIAPortal '/storage/nvme5/new_clones/QML/DemoUnityandTIAPortal' &
git clone https://github.com/Wanderson-Magalhaes/System_Info_With_Python '/storage/nvme5/new_clones/QML/System_Info_With_Python' &
git clone https://github.com/Zren/plasma-applet-sysmonitordash '/storage/nvme5/new_clones/QML/plasma-applet-sysmonitordash' &
git clone https://github.com/dragoonDorise/RP-Switch '/storage/nvme5/new_clones/QML/RP-Switch' &
git clone https://github.com/alasdairrae/gb-places '/storage/nvme5/new_clones/QML/gb-places' &
git clone https://github.com/alesarrett/PEBAmap '/storage/nvme5/new_clones/QML/PEBAmap' &
git clone https://github.com/rschiang/lit-app '/storage/nvme5/new_clones/QML/lit-app' &
git clone https://github.com/hualet/NeteaseMusicForLinux '/storage/nvme5/new_clones/QML/NeteaseMusicForLinux' &
git clone https://github.com/sailfishos/sailfish-components-webview '/storage/nvme5/new_clones/QML/sailfish-components-webview' &
git clone https://github.com/anpho/PaperBird '/storage/nvme5/new_clones/QML/PaperBird' &
git clone https://github.com/woboq/canvas_shadereffect_animations '/storage/nvme5/new_clones/QML/canvas_shadereffect_animations' &
git clone https://github.com/OrdnanceSurvey/Boundary-Line-stylesheets '/storage/nvme5/new_clones/QML/Boundary-Line-stylesheets' &
git clone https://github.com/paulojraposo/FlowMaps '/storage/nvme5/new_clones/QML/FlowMaps' &
git clone https://github.com/jpetrell/codesnippets-joona '/storage/nvme5/new_clones/QML/codesnippets-joona' &
git clone https://github.com/charleyglynn/OSOpenMapLocal-QGIS-stylesheets '/storage/nvme5/new_clones/QML/OSOpenMapLocal-QGIS-stylesheets' &
git clone https://github.com/lowbees/FramlessWindowHelper '/storage/nvme5/new_clones/QML/FramlessWindowHelper' &
git clone https://github.com/michaelvlach/qbs-autoproject '/storage/nvme5/new_clones/QML/qbs-autoproject' &
git clone https://github.com/paulovap/bacon2d-flappybird '/storage/nvme5/new_clones/QML/bacon2d-flappybird' &
git clone https://github.com/ekke/tab_pages_x '/storage/nvme5/new_clones/QML/tab_pages_x' &
git clone https://github.com/nathanielhourt/SteemPressure '/storage/nvme5/new_clones/QML/SteemPressure' &
git clone https://github.com/KDE/koko '/storage/nvme5/new_clones/QML/koko' &
git clone https://github.com/cjmdaixi/QtRODemos '/storage/nvme5/new_clones/QML/QtRODemos' &
git clone https://github.com/fairdirect/foodrescue-app '/storage/nvme5/new_clones/QML/foodrescue-app' &
git clone https://github.com/JunoNgx/kde-currently-playing '/storage/nvme5/new_clones/QML/kde-currently-playing' &
git clone https://github.com/Zren/plasma-applet-gitlabissues '/storage/nvme5/new_clones/QML/plasma-applet-gitlabissues' &
git clone https://github.com/NL-TCH/Frame.Work_SplashScreen-KDE '/storage/nvme5/new_clones/QML/Frame.Work_SplashScreen-KDE' &
git clone https://github.com/Eeems/oxidize '/storage/nvme5/new_clones/QML/oxidize' &
git clone https://github.com/edurojasr/QGIS-Geometry-Generator '/storage/nvme5/new_clones/QML/QGIS-Geometry-Generator' &
git clone https://github.com/aureyoboss/ArcadeFlashWeb '/storage/nvme5/new_clones/QML/ArcadeFlashWeb' &
git clone https://github.com/7bitcoder/SharpsenBox '/storage/nvme5/new_clones/QML/SharpsenBox' &
git clone https://github.com/rutura/Qt6QMLBeginnersCode '/storage/nvme5/new_clones/QML/Qt6QMLBeginnersCode' &
git clone https://github.com/Unibugs/UniHome '/storage/nvme5/new_clones/QML/UniHome' &
git clone https://github.com/TiunovIgor/round-interfaces-library-qml '/storage/nvme5/new_clones/QML/round-interfaces-library-qml' &
git clone https://github.com/Mr17MG/QDatePicker '/storage/nvme5/new_clones/QML/QDatePicker' &
git clone https://github.com/tinvaan/qtquick-mapview '/storage/nvme5/new_clones/QML/qtquick-mapview' &
git clone https://github.com/TLMichael/Perceptron '/storage/nvme5/new_clones/QML/Perceptron' &
git clone https://github.com/webosose/qml-webos-framework '/storage/nvme5/new_clones/QML/qml-webos-framework' &
git clone https://github.com/AmirHosseinCH/TabBar '/storage/nvme5/new_clones/QML/TabBar' &
git clone https://github.com/lgvr123/musescore-durationeditor '/storage/nvme5/new_clones/QML/musescore-durationeditor' &
git clone https://github.com/milikhin/seabass2 '/storage/nvme5/new_clones/QML/seabass2' &
git clone https://github.com/johanhelsing/qtws17-compositor '/storage/nvme5/new_clones/QML/qtws17-compositor' &
git clone https://github.com/dtoebe/qml_markdown '/storage/nvme5/new_clones/QML/qml_markdown' &
git clone https://github.com/qtproject/qt-apps-multiscreen-demo '/storage/nvme5/new_clones/QML/qt-apps-multiscreen-demo' &
git clone https://github.com/thurask/bbdownloader '/storage/nvme5/new_clones/QML/bbdownloader' &
git clone https://github.com/dschopf/plasma-applet-qalculate '/storage/nvme5/new_clones/QML/plasma-applet-qalculate' &
git clone https://github.com/mixedbredie/itn-for-pgrouting '/storage/nvme5/new_clones/QML/itn-for-pgrouting' &
git clone https://github.com/tardypad/sailfishos-daily-comics '/storage/nvme5/new_clones/QML/sailfishos-daily-comics' &
git clone https://github.com/qmlbook/qmlapps '/storage/nvme5/new_clones/QML/qmlapps' &
git clone https://github.com/KDE/milou '/storage/nvme5/new_clones/QML/milou' &
git clone https://github.com/MrEricSir/QMLRearrangeableTreeView '/storage/nvme5/new_clones/QML/QMLRearrangeableTreeView' &
git clone https://github.com/ubports/address-book-app '/storage/nvme5/new_clones/QML/address-book-app' &
git clone https://github.com/AmirHosseinCH/GlassmorphismAnalogClock '/storage/nvme5/new_clones/QML/GlassmorphismAnalogClock' &
git clone https://github.com/girishlande/QMLProjects '/storage/nvme5/new_clones/QML/QMLProjects' &
git clone https://github.com/go-qamel/qamel-hn '/storage/nvme5/new_clones/QML/qamel-hn' &
git clone https://github.com/JingOS-team/videoplayer '/storage/nvme5/new_clones/QML/videoplayer' &
git clone https://github.com/KDE/ktrip '/storage/nvme5/new_clones/QML/ktrip' &
git clone https://github.com/uPlexa/uplexa-gui '/storage/nvme5/new_clones/QML/uplexa-gui' &
git clone https://github.com/schnitzeltony/fontawesome-qml '/storage/nvme5/new_clones/QML/fontawesome-qml' &
git clone https://github.com/work4blue/qml-tabbar '/storage/nvme5/new_clones/QML/qml-tabbar' &
git clone https://github.com/Zren/plasma-applet-alphablackcontrol '/storage/nvme5/new_clones/QML/plasma-applet-alphablackcontrol' &
git clone https://github.com/astize/redrock '/storage/nvme5/new_clones/QML/redrock' &
git clone https://github.com/0kzh/mac-inline-battery '/storage/nvme5/new_clones/QML/mac-inline-battery' &
git clone https://github.com/MisterGC/clayground '/storage/nvme5/new_clones/QML/clayground' &
git clone https://github.com/popelnuh/osm-pink-shp-qml-sld '/storage/nvme5/new_clones/QML/osm-pink-shp-qml-sld' &
git clone https://github.com/ichlubna/mind '/storage/nvme5/new_clones/QML/mind' &
git clone https://github.com/Zren/plasma-applet-lib '/storage/nvme5/new_clones/QML/plasma-applet-lib' &
git clone https://github.com/amoh-godwin/youtube-source '/storage/nvme5/new_clones/QML/youtube-source' &
git clone https://github.com/iampby/MyQQ '/storage/nvme5/new_clones/QML/MyQQ' &
git clone https://github.com/BlitzGLEP1326/vehicle-can-daq '/storage/nvme5/new_clones/QML/vehicle-can-daq' &
git clone https://github.com/wisoltech/qt-virt-keyboard '/storage/nvme5/new_clones/QML/qt-virt-keyboard' &
git clone https://github.com/OMerkel/tin_whistle '/storage/nvme5/new_clones/QML/tin_whistle' &
git clone https://github.com/zchydem/qt-examples '/storage/nvme5/new_clones/QML/qt-examples' &
git clone https://github.com/cizum/sweeper-madness '/storage/nvme5/new_clones/QML/sweeper-madness' &
git clone https://github.com/quickly/sphere '/storage/nvme5/new_clones/QML/sphere' &
git clone https://github.com/chaoz/QGIS-LM-Terrain-Styles '/storage/nvme5/new_clones/QML/QGIS-LM-Terrain-Styles' &
git clone https://github.com/1900Zachary/Live-Link-Substance-Painter---Unity '/storage/nvme5/new_clones/QML/Live-Link-Substance-Painter---Unity' &
git clone https://github.com/hat3ck/Persian-Calendar-Qt '/storage/nvme5/new_clones/QML/Persian-Calendar-Qt' &
git clone https://github.com/Mogara/GameHall '/storage/nvme5/new_clones/QML/GameHall' &
git clone https://github.com/kartoza/QGISTrainingWorkshop '/storage/nvme5/new_clones/QML/QGISTrainingWorkshop' &
git clone https://github.com/klakar/geosupportsystem '/storage/nvme5/new_clones/QML/geosupportsystem' &
git clone https://github.com/mmatyas/pegasus-theme-flixnet '/storage/nvme5/new_clones/QML/pegasus-theme-flixnet' &
git clone https://github.com/AllegorithmicSAS/painter-plugin-resources-updater '/storage/nvme5/new_clones/QML/painter-plugin-resources-updater' &
git clone https://github.com/MicheleTobias/QGIS-Cartography-Resources '/storage/nvme5/new_clones/QML/QGIS-Cartography-Resources' &
git clone https://github.com/qt-users-jp/silk '/storage/nvme5/new_clones/QML/silk' &
git clone https://github.com/dant3/qmlcompletionbox '/storage/nvme5/new_clones/QML/qmlcompletionbox' &
git clone https://github.com/jozo/docker-pyqt5-qml-qtmultimedia '/storage/nvme5/new_clones/QML/docker-pyqt5-qml-qtmultimedia' &
git clone https://github.com/OrdnanceSurvey/OS-Terrain-50-stylesheets '/storage/nvme5/new_clones/QML/OS-Terrain-50-stylesheets' &
git clone https://github.com/KDE/plasma-redshift-control '/storage/nvme5/new_clones/QML/plasma-redshift-control' &
git clone https://github.com/kimmoli/paint '/storage/nvme5/new_clones/QML/paint' &
git clone https://github.com/bebu/FlatUi '/storage/nvme5/new_clones/QML/FlatUi' &
git clone https://github.com/MartinBriza/2048.qml '/storage/nvme5/new_clones/QML/2048.qml' &
git clone https://github.com/teleshoes/n9-config '/storage/nvme5/new_clones/QML/n9-config' &
git clone https://github.com/andredla/win_audio '/storage/nvme5/new_clones/QML/win_audio' &
git clone https://github.com/KDE/qqc2-breeze-style '/storage/nvme5/new_clones/QML/qqc2-breeze-style' &
git clone https://github.com/ZhongYic00/QtQuick-DTK-style '/storage/nvme5/new_clones/QML/QtQuick-DTK-style' &
git clone https://github.com/cjmdaixi/QuickSplashDemo '/storage/nvme5/new_clones/QML/QuickSplashDemo' &
git clone https://github.com/mohsenD98/QmlComponentGallery '/storage/nvme5/new_clones/QML/QmlComponentGallery' &
git clone https://github.com/rahul-badgujar/QtMusicPlayer '/storage/nvme5/new_clones/QML/QtMusicPlayer' &
git clone https://github.com/seyyedBagherMusavi/qmlFilterTable '/storage/nvme5/new_clones/QML/qmlFilterTable' &
git clone https://github.com/FelgoSDK/BasicApp-Example '/storage/nvme5/new_clones/QML/BasicApp-Example' &
git clone https://github.com/scopchanov/cute-scope '/storage/nvme5/new_clones/QML/cute-scope' &
git clone https://github.com/KDE/maui-station '/storage/nvme5/new_clones/QML/maui-station' &
git clone https://github.com/ekoooo/ZhihuDaily-Cascades '/storage/nvme5/new_clones/QML/ZhihuDaily-Cascades' &
git clone https://github.com/StephSaephan/QGIS-USGS-TNM-Style-Template '/storage/nvme5/new_clones/QML/QGIS-USGS-TNM-Style-Template' &
git clone https://github.com/KDE/maui-pix '/storage/nvme5/new_clones/QML/maui-pix' &
git clone https://github.com/goplayegg/QmlDemo '/storage/nvme5/new_clones/QML/QmlDemo' &
git clone https://github.com/anupam-git/fingerboard '/storage/nvme5/new_clones/QML/fingerboard' &
git clone https://github.com/KDE/plasma-phonebook '/storage/nvme5/new_clones/QML/plasma-phonebook' &
git clone https://github.com/ic005k/Knot '/storage/nvme5/new_clones/QML/Knot' &
git clone https://github.com/makerinchina-iot/raspberry_pyside_notes '/storage/nvme5/new_clones/QML/raspberry_pyside_notes' &
git clone https://github.com/andywuest/harbour-watchlist '/storage/nvme5/new_clones/QML/harbour-watchlist' &
git clone https://github.com/berkbavas/MercedesGaugeCluster '/storage/nvme5/new_clones/QML/MercedesGaugeCluster' &
git clone https://github.com/qtchina/qt.go.demos '/storage/nvme5/new_clones/QML/qt.go.demos' &
git clone https://github.com/HamedMasafi/qml-data-grid-view '/storage/nvme5/new_clones/QML/qml-data-grid-view' &
git clone https://github.com/RP335/NegativeHarmonyGenerator '/storage/nvme5/new_clones/QML/NegativeHarmonyGenerator' &
git clone https://github.com/TomRvr/qt-planets-ci-cd '/storage/nvme5/new_clones/QML/qt-planets-ci-cd' &
git clone https://github.com/ekke/stacked_pages_x '/storage/nvme5/new_clones/QML/stacked_pages_x' &
git clone https://github.com/ccppbrasil/encontro11 '/storage/nvme5/new_clones/QML/encontro11' &
git clone https://github.com/artemvmin/traktor_s5_mod '/storage/nvme5/new_clones/QML/traktor_s5_mod' &
git clone https://github.com/188080501/QmlDesignerPlus '/storage/nvme5/new_clones/QML/QmlDesignerPlus' &
git clone https://github.com/sletta/stuff '/storage/nvme5/new_clones/QML/stuff' &
git clone https://github.com/Zren/kwin-tabbox-thumbnail_grid '/storage/nvme5/new_clones/QML/kwin-tabbox-thumbnail_grid' &
git clone https://github.com/sniper1720/elegant-sddm-archlinux-theme '/storage/nvme5/new_clones/QML/elegant-sddm-archlinux-theme' &
git clone https://github.com/nemomobile/qtquickcontrols-nemo '/storage/nvme5/new_clones/QML/qtquickcontrols-nemo' &
git clone https://github.com/qt-labs/qt5-everywhere-demo '/storage/nvme5/new_clones/QML/qt5-everywhere-demo' &
git clone https://github.com/mitchcurtis/robot-faces '/storage/nvme5/new_clones/QML/robot-faces' &
git clone https://github.com/pkobrien/game-of-life-qml '/storage/nvme5/new_clones/QML/game-of-life-qml' &
git clone https://github.com/Ecohnoch/Mota-Editor '/storage/nvme5/new_clones/QML/Mota-Editor' &
git clone https://github.com/Esri/Trek2There '/storage/nvme5/new_clones/QML/Trek2There' &
git clone https://github.com/balta3/sailfish-gpsinfo '/storage/nvme5/new_clones/QML/sailfish-gpsinfo' &
git clone https://github.com/alpqr/q3dpostproc '/storage/nvme5/new_clones/QML/q3dpostproc' &
git clone https://github.com/charnacrypto/charnacoin-gui '/storage/nvme5/new_clones/QML/charnacoin-gui' &
git clone https://github.com/emmanueltouzery/projectpad '/storage/nvme5/new_clones/QML/projectpad' &
git clone https://github.com/cfsghost/brig-example-app '/storage/nvme5/new_clones/QML/brig-example-app' &
git clone https://github.com/KDE/plasma-simplemenu '/storage/nvme5/new_clones/QML/plasma-simplemenu' &
git clone https://github.com/benlau/viewstack.pri '/storage/nvme5/new_clones/QML/viewstack.pri' &
git clone https://github.com/qtproject/qt-apps-boot2qt-demos '/storage/nvme5/new_clones/QML/qt-apps-boot2qt-demos' &
git clone https://github.com/SammyEnigma/qt-quick-ui-elements '/storage/nvme5/new_clones/QML/qt-quick-ui-elements' &
git clone https://github.com/xuin-net/Toou2D-Gallery '/storage/nvme5/new_clones/QML/Toou2D-Gallery' &
git clone https://github.com/dreavjr/qt_quick_fixes '/storage/nvme5/new_clones/QML/qt_quick_fixes' &
git clone https://github.com/mapninja/QGIS-101 '/storage/nvme5/new_clones/QML/QGIS-101' &
git clone https://github.com/simonqin09/QtQMLMultimedia '/storage/nvme5/new_clones/QML/QtQMLMultimedia' &
git clone https://github.com/BioGearsEngine/ui '/storage/nvme5/new_clones/QML/ui' &
git clone https://github.com/MartinGurasvili/Calculator '/storage/nvme5/new_clones/QML/Calculator' &
git clone https://github.com/tahnik/qDownload '/storage/nvme5/new_clones/QML/qDownload' &
git clone https://github.com/NICHOLAS85/dotfiles '/storage/nvme5/new_clones/QML/dotfiles' &
git clone https://github.com/KDE/kalk '/storage/nvme5/new_clones/QML/kalk' &
git clone https://github.com/KDABLabs/KDBoatDemo '/storage/nvme5/new_clones/QML/KDBoatDemo' &
git clone https://github.com/amar-laksh/ros2qt_demo '/storage/nvme5/new_clones/QML/ros2qt_demo' &
git clone https://github.com/MaksymTymkovych/BrainDICOM '/storage/nvme5/new_clones/QML/BrainDICOM' &
git clone https://github.com/caiorss/qtquick-examples '/storage/nvme5/new_clones/QML/qtquick-examples' &
git clone https://github.com/GPBeta/ZeldaFadeScene '/storage/nvme5/new_clones/QML/ZeldaFadeScene' &
git clone https://github.com/trolleway/OSMTram '/storage/nvme5/new_clones/QML/OSMTram' &
git clone https://github.com/foolsbazar/sailfish-ease-vkb '/storage/nvme5/new_clones/QML/sailfish-ease-vkb' &
git clone https://github.com/lesliefish/QMLInAction '/storage/nvme5/new_clones/QML/QMLInAction' &
git clone https://github.com/mutolisp/distrmap_tw.qgis '/storage/nvme5/new_clones/QML/distrmap_tw.qgis' &
git clone https://github.com/wkler/OpenRespiratorGUI '/storage/nvme5/new_clones/QML/OpenRespiratorGUI' &
git clone https://github.com/asdfgasfhsn/pegasus-theme-homage '/storage/nvme5/new_clones/QML/pegasus-theme-homage' &
git clone https://github.com/barche/juliacon2020-qml '/storage/nvme5/new_clones/QML/juliacon2020-qml' &
git clone https://github.com/ichthyosaurus/harbour-file-browser '/storage/nvme5/new_clones/QML/harbour-file-browser' &
git clone https://github.com/ginuerzh/gchat '/storage/nvme5/new_clones/QML/gchat' &
git clone https://github.com/lesbg/ansible '/storage/nvme5/new_clones/QML/ansible' &
git clone https://github.com/FelgoSDK/QtWorldSummit2016-V-Play '/storage/nvme5/new_clones/QML/QtWorldSummit2016-V-Play' &
git clone https://github.com/cfsghost/FishFarmingBrowser '/storage/nvme5/new_clones/QML/FishFarmingBrowser' &
git clone https://github.com/klakar/LM_Open_QGIS_Styles '/storage/nvme5/new_clones/QML/LM_Open_QGIS_Styles' &
git clone https://github.com/hhartz/fontawesome '/storage/nvme5/new_clones/QML/fontawesome' &
git clone https://github.com/MidoriYakumo/ShaderPlot '/storage/nvme5/new_clones/QML/ShaderPlot' &
git clone https://github.com/liri-archive/qbs-shared '/storage/nvme5/new_clones/QML/qbs-shared' &
git clone https://github.com/RealworldSystems/qml-widgets-library '/storage/nvme5/new_clones/QML/qml-widgets-library' &
git clone https://github.com/charleyglynn/EuroGlobalMap-QGIS-stylesheets '/storage/nvme5/new_clones/QML/EuroGlobalMap-QGIS-stylesheets' &
git clone https://github.com/igemsoftware/UESTC_Software2015 '/storage/nvme5/new_clones/QML/UESTC_Software2015' &
git clone https://github.com/qtproject/qt-apps-stb-demo '/storage/nvme5/new_clones/QML/qt-apps-stb-demo' &
git clone https://github.com/ekke/swiped_pages_x '/storage/nvme5/new_clones/QML/swiped_pages_x' &
git clone https://github.com/ekke/one_page_x '/storage/nvme5/new_clones/QML/one_page_x' &
git clone https://github.com/kimmoli/i2ctool '/storage/nvme5/new_clones/QML/i2ctool' &
git clone https://github.com/hefanbo/arch_macbook '/storage/nvme5/new_clones/QML/arch_macbook' &
git clone https://github.com/Shourov1/Speed-gauge-with-virtual-CAN-bus '/storage/nvme5/new_clones/QML/Speed-gauge-with-virtual-CAN-bus' &
git clone https://github.com/vigasan/CameraRpi '/storage/nvme5/new_clones/QML/CameraRpi' &
git clone https://github.com/maptiler/maptiler-qml-demo '/storage/nvme5/new_clones/QML/maptiler-qml-demo' &
git clone https://github.com/zuozl1992/FQFPlayer '/storage/nvme5/new_clones/QML/FQFPlayer' &
git clone https://github.com/DavideRoss/SubstanceBatchExport '/storage/nvme5/new_clones/QML/SubstanceBatchExport' &
git clone https://github.com/julien-hdev-archives/Smoke '/storage/nvme5/new_clones/QML/Smoke' &
git clone https://github.com/JameScottX/QML-Multiple-windows '/storage/nvme5/new_clones/QML/QML-Multiple-windows' &
git clone https://github.com/minitigri/Bogot-una-pintura '/storage/nvme5/new_clones/QML/Bogot-una-pintura' &
git clone https://github.com/rdunlocked18/JailbreakBRCheckm8 '/storage/nvme5/new_clones/QML/JailbreakBRCheckm8' &
git clone https://github.com/FelgoSDK/QtRestClient '/storage/nvme5/new_clones/QML/QtRestClient' &
git clone https://github.com/eichenberger/qt-dual-screen-compositor '/storage/nvme5/new_clones/QML/qt-dual-screen-compositor' &
git clone https://github.com/JackDesBwa/PhereoRoll3D '/storage/nvme5/new_clones/QML/PhereoRoll3D' &
git clone https://github.com/nortexoid/LargeIconList '/storage/nvme5/new_clones/QML/LargeIconList' &
git clone https://github.com/allankoechke/QML-Android-Music-App '/storage/nvme5/new_clones/QML/QML-Android-Music-App' &
git clone https://github.com/danbuliduo/QtCube '/storage/nvme5/new_clones/QML/QtCube' &
git clone https://github.com/mengps/Weather '/storage/nvme5/new_clones/QML/Weather' &
git clone https://github.com/glisteningly/retrofans-hd '/storage/nvme5/new_clones/QML/retrofans-hd' &
git clone https://github.com/black-sheep-dev/harbour-hafenschau '/storage/nvme5/new_clones/QML/harbour-hafenschau' &
git clone https://github.com/znarf94/MuseScore_Barbershop_Harmonizer '/storage/nvme5/new_clones/QML/MuseScore_Barbershop_Harmonizer' &
git clone https://github.com/KartikSindura/kuro '/storage/nvme5/new_clones/QML/kuro' &
git clone https://github.com/Vitaee/AutomotiveCluster '/storage/nvme5/new_clones/QML/AutomotiveCluster' &
git clone https://github.com/sihuan/genshin-daily-plasmoid '/storage/nvme5/new_clones/QML/genshin-daily-plasmoid' &
git clone https://github.com/kevinqqnj/qml_weather '/storage/nvme5/new_clones/QML/qml_weather' &
git clone https://github.com/Esri/QuickCapture '/storage/nvme5/new_clones/QML/QuickCapture' &
git clone https://github.com/cnigfr/DDU-SG5-SYMBOLISATION '/storage/nvme5/new_clones/QML/DDU-SG5-SYMBOLISATION' &
git clone https://github.com/Cutehacks/qml-pusher '/storage/nvme5/new_clones/QML/qml-pusher' &
git clone https://github.com/custodian/harbour-systemmonitor '/storage/nvme5/new_clones/QML/harbour-systemmonitor' &
git clone https://github.com/CODeRUS/harbour-screentapshot '/storage/nvme5/new_clones/QML/harbour-screentapshot' &
git clone https://github.com/a-team-fr/QtQML-BaaS '/storage/nvme5/new_clones/QML/QtQML-BaaS' &
git clone https://github.com/gil9red/AudioPlayer_qml '/storage/nvme5/new_clones/QML/AudioPlayer_qml' &
git clone https://github.com/lowbees/CirCleView '/storage/nvme5/new_clones/QML/CirCleView' &
git clone https://github.com/crazysoldier/ipfs-browser '/storage/nvme5/new_clones/QML/ipfs-browser' &
git clone https://github.com/llelectronics/noto '/storage/nvme5/new_clones/QML/noto' &
git clone https://github.com/OrdnanceSurvey/Meridian2-stylesheets '/storage/nvme5/new_clones/QML/Meridian2-stylesheets' &
git clone https://github.com/ditcoin/ditcoin-gui '/storage/nvme5/new_clones/QML/ditcoin-gui' &
git clone https://github.com/rinigus/systemdatascope '/storage/nvme5/new_clones/QML/systemdatascope' &
git clone https://github.com/spatialdude/HockeySDK-QML '/storage/nvme5/new_clones/QML/HockeySDK-QML' &
git clone https://github.com/qtproject/qt-apps-qtwebbrowser '/storage/nvme5/new_clones/QML/qt-apps-qtwebbrowser' &
git clone https://github.com/florianwittmann/sailgrande '/storage/nvme5/new_clones/QML/sailgrande' &
git clone https://github.com/bgr/qml_hot_reload '/storage/nvme5/new_clones/QML/qml_hot_reload' &
git clone https://github.com/SiberianProgrammers/sp_examples '/storage/nvme5/new_clones/QML/sp_examples' &
git clone https://github.com/D-BookeR/GUI_en_Python_avec_PyQt_5 '/storage/nvme5/new_clones/QML/GUI_en_Python_avec_PyQt_5' &
git clone https://github.com/leouieda/geofisica2 '/storage/nvme5/new_clones/QML/geofisica2' &
git clone https://github.com/OrdnanceSurvey/OS-MasterMap-Highways-Network-stylesheets '/storage/nvme5/new_clones/QML/OS-MasterMap-Highways-Network-stylesheets' &
git clone https://github.com/pavelvasev/qmlweb.components '/storage/nvme5/new_clones/QML/qmlweb.components' &
git clone https://github.com/GIPdA/ArduinoQbs '/storage/nvme5/new_clones/QML/ArduinoQbs' &
git clone https://github.com/RikudouSage/mangastream-downloader '/storage/nvme5/new_clones/QML/mangastream-downloader' &
git clone https://github.com/bckmnn/qml-qt-snippets '/storage/nvme5/new_clones/QML/qml-qt-snippets' &
git clone https://github.com/qgissverige/kartografi '/storage/nvme5/new_clones/QML/kartografi' &
git clone https://github.com/mshobeyri/PersianCalendar '/storage/nvme5/new_clones/QML/PersianCalendar' &
git clone https://github.com/Jojo-Schmitz/ColorVoices '/storage/nvme5/new_clones/QML/ColorVoices' &
git clone https://github.com/benlau/junkcode '/storage/nvme5/new_clones/QML/junkcode' &
git clone https://github.com/weswu8/stockwatcher '/storage/nvme5/new_clones/QML/stockwatcher' &
git clone https://github.com/RicardoRagel/qt-qml-sample-app '/storage/nvme5/new_clones/QML/qt-qml-sample-app' &
git clone https://github.com/grumpycat3051/harbour-phillis '/storage/nvme5/new_clones/QML/harbour-phillis' &
git clone https://github.com/fancyop/Getting-started-with-Qt5-programming '/storage/nvme5/new_clones/QML/Getting-started-with-Qt5-programming' &
git clone https://github.com/MycroftAI/skill-mark-2 '/storage/nvme5/new_clones/QML/skill-mark-2' &
git clone https://github.com/ohmbre/ohmstudio '/storage/nvme5/new_clones/QML/ohmstudio' &
git clone https://github.com/programmerkm/coffeeplace '/storage/nvme5/new_clones/QML/coffeeplace' &
git clone https://github.com/Segs/Segs-Client '/storage/nvme5/new_clones/QML/Segs-Client' &
git clone https://github.com/KDE/documentation-develop-kde-org '/storage/nvme5/new_clones/QML/documentation-develop-kde-org' &
git clone https://github.com/SUNET/tugpgp '/storage/nvme5/new_clones/QML/tugpgp' &
git clone https://github.com/reworled/qtvc2020 '/storage/nvme5/new_clones/QML/qtvc2020' &
git clone https://github.com/FionaPrudhomme/Stylesheet-QGIS-OpenTopoMap '/storage/nvme5/new_clones/QML/Stylesheet-QGIS-OpenTopoMap' &
git clone https://github.com/haknkayaa/MusicDashboard '/storage/nvme5/new_clones/QML/MusicDashboard' &
git clone https://github.com/dotnet9/CTKQuickPluginApp '/storage/nvme5/new_clones/QML/CTKQuickPluginApp' &
git clone https://github.com/0smr/snow-white '/storage/nvme5/new_clones/QML/snow-white' &
git clone https://github.com/ZJU-RoboCup/Crazy '/storage/nvme5/new_clones/QML/Crazy' &
git clone https://github.com/komorebithrowsatable/twitchindicator '/storage/nvme5/new_clones/QML/twitchindicator' &
git clone https://github.com/KDE/francis '/storage/nvme5/new_clones/QML/francis' &
git clone https://github.com/Tereius/TilesGrid '/storage/nvme5/new_clones/QML/TilesGrid' &
git clone https://github.com/mbahrololoum/connectToDB '/storage/nvme5/new_clones/QML/connectToDB' &
git clone https://github.com/nxp-imx-support/nxp-demo-experience '/storage/nvme5/new_clones/QML/nxp-demo-experience' &
git clone https://github.com/pureqml/pureosd '/storage/nvme5/new_clones/QML/pureosd' &
git clone https://github.com/mmatyas/pegasus-theme-grid '/storage/nvme5/new_clones/QML/pegasus-theme-grid' &
git clone https://github.com/MarcinOrlowski/weekday-plasmoid '/storage/nvme5/new_clones/QML/weekday-plasmoid' &
git clone https://github.com/allankoechke/QML-Charts-Updating '/storage/nvme5/new_clones/QML/QML-Charts-Updating' &
git clone https://github.com/sshuair/Geovisualization-Tutorial '/storage/nvme5/new_clones/QML/Geovisualization-Tutorial' &
git clone https://github.com/emrehaninci/Appa-Flight-Dashboard '/storage/nvme5/new_clones/QML/Appa-Flight-Dashboard' &
git clone https://github.com/myebstudios/Fast_Food_Login '/storage/nvme5/new_clones/QML/Fast_Food_Login' &
git clone https://github.com/alefnode/ubports-apps '/storage/nvme5/new_clones/QML/ubports-apps' &
git clone https://github.com/pragmaticQt/ClusterTutorial '/storage/nvme5/new_clones/QML/ClusterTutorial' &
git clone https://github.com/easyscience/EasyReflectometryApp '/storage/nvme5/new_clones/QML/EasyReflectometryApp' &
git clone https://github.com/gustavosbarreto/qml-recreations-showcase '/storage/nvme5/new_clones/QML/qml-recreations-showcase' &
git clone https://github.com/qewer33/simple-plasmoid-template '/storage/nvme5/new_clones/QML/simple-plasmoid-template' &
git clone https://github.com/MycroftAI/skill-camera '/storage/nvme5/new_clones/QML/skill-camera' &
git clone https://github.com/7bitcoder/FramelessQmlWindow '/storage/nvme5/new_clones/QML/FramelessQmlWindow' &
git clone https://github.com/LCBHSStudent/delivery-term-work-BUPT '/storage/nvme5/new_clones/QML/delivery-term-work-BUPT' &
git clone https://github.com/R1tschY/harbour-sailify '/storage/nvme5/new_clones/QML/harbour-sailify' &
git clone https://github.com/alexyalinc/krudio-qml '/storage/nvme5/new_clones/QML/krudio-qml' &
git clone https://github.com/RicardoRagel/drawer-translate '/storage/nvme5/new_clones/QML/drawer-translate' &
git clone https://github.com/qyvlik/QtQuickHotFix '/storage/nvme5/new_clones/QML/QtQuickHotFix' &
git clone https://github.com/Maledictus/harbour-linksbag '/storage/nvme5/new_clones/QML/harbour-linksbag' &
git clone https://github.com/arunpkio/AnimatedListViewSelector '/storage/nvme5/new_clones/QML/AnimatedListViewSelector' &
git clone https://github.com/jbache/circularimage '/storage/nvme5/new_clones/QML/circularimage' &
git clone https://github.com/pozi/GIS-on-a-Stick '/storage/nvme5/new_clones/QML/GIS-on-a-Stick' &
git clone https://github.com/lowbees/CloudMusic '/storage/nvme5/new_clones/QML/CloudMusic' &
git clone https://github.com/jemc/qml-zmq '/storage/nvme5/new_clones/QML/qml-zmq' &
git clone https://github.com/FloodRiskGroup/FloodRisk-doc '/storage/nvme5/new_clones/QML/FloodRisk-doc' &
git clone https://github.com/MidoriYakumo/qml_cascadeflow_demo '/storage/nvme5/new_clones/QML/qml_cascadeflow_demo' &
git clone https://github.com/RStravinsky/CarsAndroid '/storage/nvme5/new_clones/QML/CarsAndroid' &
git clone https://github.com/e-fever/backpressure '/storage/nvme5/new_clones/QML/backpressure' &
git clone https://github.com/Siecje/qml-testing '/storage/nvme5/new_clones/QML/qml-testing' &
git clone https://github.com/e-fever/twowaybinding '/storage/nvme5/new_clones/QML/twowaybinding' &
git clone https://github.com/ldanzinger/arcgis-runtime-qt-projects-10.2 '/storage/nvme5/new_clones/QML/arcgis-runtime-qt-projects-10.2' &
git clone https://github.com/openfoodfacts/openfoodfacts-ubuntu '/storage/nvme5/new_clones/QML/openfoodfacts-ubuntu' &
git clone https://github.com/tace/jolla2gether '/storage/nvme5/new_clones/QML/jolla2gether' &
git clone https://github.com/uCtrl/Software '/storage/nvme5/new_clones/QML/Software' &
git clone https://github.com/Iktwo/musicgear '/storage/nvme5/new_clones/QML/musicgear' &
git clone https://github.com/kartoza/topostyle '/storage/nvme5/new_clones/QML/topostyle' &
git clone https://github.com/benlau/material2 '/storage/nvme5/new_clones/QML/material2' &
git clone https://github.com/CODeRUS/harbour-mitakuuluu2 '/storage/nvme5/new_clones/QML/harbour-mitakuuluu2' &
git clone https://github.com/Jollailija/nettiradio '/storage/nvme5/new_clones/QML/nettiradio' &
git clone https://github.com/unixzii/QtMaterialDesignComponents '/storage/nvme5/new_clones/QML/QtMaterialDesignComponents' &
git clone https://github.com/igeofr/qgis_styles '/storage/nvme5/new_clones/QML/qgis_styles' &
git clone https://github.com/KhoaTranProgrammer/QtQml_Clock '/storage/nvme5/new_clones/QML/QtQml_Clock' &
git clone https://github.com/emmilinux/neon-painel '/storage/nvme5/new_clones/QML/neon-painel' &
git clone https://github.com/TheCompez/Modern-Examples '/storage/nvme5/new_clones/QML/Modern-Examples' &
git clone https://github.com/RomanHuBoss/QmlGraphicEditor '/storage/nvme5/new_clones/QML/QmlGraphicEditor' &
git clone https://github.com/matgnt/mobos-gui '/storage/nvme5/new_clones/QML/mobos-gui' &
git clone https://github.com/NthElse/trackball '/storage/nvme5/new_clones/QML/trackball' &
git clone https://github.com/pavelprosto94/uHome '/storage/nvme5/new_clones/QML/uHome' &
git clone https://github.com/lgvr123/musescore-workoutbuilder '/storage/nvme5/new_clones/QML/musescore-workoutbuilder' &
git clone https://github.com/joonne/harbour-nayttamo '/storage/nvme5/new_clones/QML/harbour-nayttamo' &
git clone https://github.com/MycroftAI/mycroft-gui-mark-2 '/storage/nvme5/new_clones/QML/mycroft-gui-mark-2' &
git clone https://github.com/MarcinOrlowski/octoprint-monitor '/storage/nvme5/new_clones/QML/octoprint-monitor' &
git clone https://github.com/caixa-magica-software/lite-linux-caixa-magica '/storage/nvme5/new_clones/QML/lite-linux-caixa-magica' &
git clone https://github.com/General-Infinity/pigs '/storage/nvme5/new_clones/QML/pigs' &
git clone https://github.com/trolleway/russian-railways-simplegeodata '/storage/nvme5/new_clones/QML/russian-railways-simplegeodata' &
git clone https://github.com/mirabilos/mscore-plugins '/storage/nvme5/new_clones/QML/mscore-plugins' &
git clone https://github.com/Zren/plasma-applet-volumeslider '/storage/nvme5/new_clones/QML/plasma-applet-volumeslider' &
git clone https://github.com/JayTwoLab/qt-automotive '/storage/nvme5/new_clones/QML/qt-automotive' &
git clone https://github.com/oltodo/prettier-plugin-qml '/storage/nvme5/new_clones/QML/prettier-plugin-qml' &
git clone https://github.com/joshuakraemer/sddm-theme-dialog '/storage/nvme5/new_clones/QML/sddm-theme-dialog' &
git clone https://github.com/SadkDemr/QtSqLiteProject '/storage/nvme5/new_clones/QML/QtSqLiteProject' &
git clone https://github.com/allankoechke/SalamaPOS '/storage/nvme5/new_clones/QML/SalamaPOS' &
git clone https://github.com/cedoduarte/QML_StackView_example '/storage/nvme5/new_clones/QML/QML_StackView_example' &
git clone https://github.com/amlwwalker/pdf-editor '/storage/nvme5/new_clones/QML/pdf-editor' &
git clone https://github.com/sailfishos-applications/flowplayer '/storage/nvme5/new_clones/QML/flowplayer' &
git clone https://github.com/edelhirsch/cachingloader '/storage/nvme5/new_clones/QML/cachingloader' &
git clone https://github.com/pubudu-ranasinghe/turnip '/storage/nvme5/new_clones/QML/turnip' &
git clone https://github.com/lingtjien/Opacity-Control-KWin '/storage/nvme5/new_clones/QML/Opacity-Control-KWin' &
git clone https://github.com/qq574582775/Qml-Frameless-application-framework '/storage/nvme5/new_clones/QML/Qml-Frameless-application-framework' &
git clone https://github.com/krishremya/Unit-Converter '/storage/nvme5/new_clones/QML/Unit-Converter' &
git clone https://github.com/OVOSHatchery/ovos-skill-baresip '/storage/nvme5/new_clones/QML/ovos-skill-baresip' &
git clone https://github.com/liefyuan/QtQML_3D_OBJ_Loader '/storage/nvme5/new_clones/QML/QtQML_3D_OBJ_Loader' &
git clone https://github.com/PratyushTripathy/Land-Cover-Using-Machine-Learning '/storage/nvme5/new_clones/QML/Land-Cover-Using-Machine-Learning' &
git clone https://github.com/allankoechke/ToDo-App-in-QML '/storage/nvme5/new_clones/QML/ToDo-App-in-QML' &
git clone https://github.com/ichthyosaurus/sailfish-public-patch-sources '/storage/nvme5/new_clones/QML/sailfish-public-patch-sources' &
git clone https://github.com/dsgoficial/ferramentas_edicao '/storage/nvme5/new_clones/QML/ferramentas_edicao' &
git clone https://github.com/mireq/WeatherQML '/storage/nvme5/new_clones/QML/WeatherQML' &
git clone https://github.com/my3rs/QPhoto '/storage/nvme5/new_clones/QML/QPhoto' &
git clone https://github.com/stepanzubkov/sddm-zust '/storage/nvme5/new_clones/QML/sddm-zust' &
git clone https://github.com/naderi/nextcloud-client-portable '/storage/nvme5/new_clones/QML/nextcloud-client-portable' &
git clone https://github.com/Zren/QmlDevTools '/storage/nvme5/new_clones/QML/QmlDevTools' &
git clone https://github.com/haknkayaa/TermiteClone '/storage/nvme5/new_clones/QML/TermiteClone' &
git clone https://github.com/sshmakov/JKanban '/storage/nvme5/new_clones/QML/JKanban' &
git clone https://github.com/Gustry/qgis-roadmap-project '/storage/nvme5/new_clones/QML/qgis-roadmap-project' &
git clone https://github.com/dragoonDorise/RP-epic-noir '/storage/nvme5/new_clones/QML/RP-epic-noir' &
git clone https://github.com/lgvr123/musescore-elementanalyser '/storage/nvme5/new_clones/QML/musescore-elementanalyser' &
git clone https://github.com/chiyuki0325/kwin-fix-wine-wechat-shadow '/storage/nvme5/new_clones/QML/kwin-fix-wine-wechat-shadow' &
git clone https://github.com/daniel-heinz/qtQuick-calculator '/storage/nvme5/new_clones/QML/qtQuick-calculator' &
git clone https://github.com/qq574582775/Cloud-Music '/storage/nvme5/new_clones/QML/Cloud-Music' &
git clone https://github.com/antiguaMob/qt_speed_gauge '/storage/nvme5/new_clones/QML/qt_speed_gauge' &
git clone https://github.com/gongjianbo/HelloQtQuick3D '/storage/nvme5/new_clones/QML/HelloQtQuick3D' &
git clone https://github.com/xyz32/timekeeper-evolution '/storage/nvme5/new_clones/QML/timekeeper-evolution' &
git clone https://github.com/haipengyu1013/PaletteDemo '/storage/nvme5/new_clones/QML/PaletteDemo' &
git clone https://github.com/Michal-Szczepaniak/amadeus-kde-splashscreen '/storage/nvme5/new_clones/QML/amadeus-kde-splashscreen' &
git clone https://github.com/realmahdi/balloon-slider '/storage/nvme5/new_clones/QML/balloon-slider' &
git clone https://github.com/zwieberl/harbour-fishtheke '/storage/nvme5/new_clones/QML/harbour-fishtheke' &
git clone https://github.com/lubansoft-developer-platform/MotorDesktopGraphicsEngine '/storage/nvme5/new_clones/QML/MotorDesktopGraphicsEngine' &
git clone https://github.com/ZeiP/harbour-paketti '/storage/nvme5/new_clones/QML/harbour-paketti' &
git clone https://github.com/yjg30737/qml-rounded-shadow-framelesswindow '/storage/nvme5/new_clones/QML/qml-rounded-shadow-framelesswindow' &
git clone https://github.com/ramonnr/AeroFanControl '/storage/nvme5/new_clones/QML/AeroFanControl' &
git clone https://github.com/Rakabidaasta/desktop-crypto-tool '/storage/nvme5/new_clones/QML/desktop-crypto-tool' &
git clone https://github.com/heafox/learnqml '/storage/nvme5/new_clones/QML/learnqml' &
git clone https://github.com/Rain92/kobo-qt-dev-docker '/storage/nvme5/new_clones/QML/kobo-qt-dev-docker' &
git clone https://github.com/y673893131/qmlTableView5_12 '/storage/nvme5/new_clones/QML/qmlTableView5_12' &
git clone https://github.com/hanxiaoluo/360qml '/storage/nvme5/new_clones/QML/360qml' &
git clone https://github.com/GENIVI/HVAC '/storage/nvme5/new_clones/QML/HVAC' &
git clone https://github.com/endarthur/brgeo_qgis '/storage/nvme5/new_clones/QML/brgeo_qgis' &
git clone https://github.com/makerhero/qt5-raspberrypi-filipeflop '/storage/nvme5/new_clones/QML/qt5-raspberrypi-filipeflop' &
git clone https://github.com/zccrs/ithome '/storage/nvme5/new_clones/QML/ithome' &
git clone https://github.com/johanhelsing/kitchen-compositor '/storage/nvme5/new_clones/QML/kitchen-compositor' &
git clone https://github.com/birdwellmusic/PruneStack '/storage/nvme5/new_clones/QML/PruneStack' &
git clone https://github.com/ZerronLabs/Mantar '/storage/nvme5/new_clones/QML/Mantar' &
git clone https://github.com/FelgoSDK/Squaby '/storage/nvme5/new_clones/QML/Squaby' &
git clone https://github.com/webOS-ports/luna-next-cardshell '/storage/nvme5/new_clones/QML/luna-next-cardshell' &
git clone https://github.com/goestreicher/harbour-wallaread '/storage/nvme5/new_clones/QML/harbour-wallaread' &
git clone https://github.com/j-tag/chocal-chat-server '/storage/nvme5/new_clones/QML/chocal-chat-server' &
git clone https://github.com/anyks/MessageDialogIOSQml '/storage/nvme5/new_clones/QML/MessageDialogIOSQml' &
git clone https://github.com/jrgdre/dbus-inspector '/storage/nvme5/new_clones/QML/dbus-inspector' &
git clone https://github.com/Airtau/3dDashBoard '/storage/nvme5/new_clones/QML/3dDashBoard' &
git clone https://github.com/pureqml/earth-online '/storage/nvme5/new_clones/QML/earth-online' &
git clone https://github.com/nx-desktop/nx-clock-applet '/storage/nvme5/new_clones/QML/nx-clock-applet' &
git clone https://github.com/TheCompez/QR-Generator '/storage/nvme5/new_clones/QML/QR-Generator' &
git clone https://github.com/sofa-framework/SofaQtQuick '/storage/nvme5/new_clones/QML/SofaQtQuick' &
git clone https://github.com/ITU-MindMapper/MindMapper '/storage/nvme5/new_clones/QML/MindMapper' &
git clone https://github.com/jkcdarunday/minotaur-plasmoid '/storage/nvme5/new_clones/QML/minotaur-plasmoid' &
git clone https://github.com/TTcheng/APKtool '/storage/nvme5/new_clones/QML/APKtool' &
git clone https://github.com/donaggio/harbour-feedhaven '/storage/nvme5/new_clones/QML/harbour-feedhaven' &
git clone https://github.com/Sturmflut/ubuntu-html5-webview-template '/storage/nvme5/new_clones/QML/ubuntu-html5-webview-template' &
git clone https://github.com/RockJesus/TOOL '/storage/nvme5/new_clones/QML/TOOL' &
git clone https://github.com/yangrw9/ray-simple '/storage/nvme5/new_clones/QML/ray-simple' &
git clone https://github.com/CrimsonAS/qmlstuff '/storage/nvme5/new_clones/QML/qmlstuff' &
git clone https://github.com/Psi57/Archiso '/storage/nvme5/new_clones/QML/Archiso' &
git clone https://github.com/asztalosdani/substance-painter-to-deadline '/storage/nvme5/new_clones/QML/substance-painter-to-deadline' &
git clone https://github.com/MycroftAI/skill-playback-control '/storage/nvme5/new_clones/QML/skill-playback-control' &
git clone https://github.com/qtproject/qt-apps-kria-cluster-2d-demo '/storage/nvme5/new_clones/QML/qt-apps-kria-cluster-2d-demo' &
git clone https://github.com/OrdnanceSurvey/OS-Terrain-5-stylesheets '/storage/nvme5/new_clones/QML/OS-Terrain-5-stylesheets' &
git clone https://github.com/QtRoS/ameditation '/storage/nvme5/new_clones/QML/ameditation' &
git clone https://github.com/RPCS3/rsx-debugger '/storage/nvme5/new_clones/QML/rsx-debugger' &
git clone https://github.com/zhengtianzuo/QtAndroidExamples '/storage/nvme5/new_clones/QML/QtAndroidExamples' &
git clone https://github.com/Andlon/sonetta '/storage/nvme5/new_clones/QML/sonetta' &
git clone https://github.com/trolleway/osm-mostrans '/storage/nvme5/new_clones/QML/osm-mostrans' &
git clone https://github.com/kimmoli/maira '/storage/nvme5/new_clones/QML/maira' &
git clone https://github.com/e-minor/MrRobot '/storage/nvme5/new_clones/QML/MrRobot' &
git clone https://github.com/probonopd/QtQuickApp '/storage/nvme5/new_clones/QML/QtQuickApp' &
git clone https://github.com/GENIVI/BluetoothPairingApp '/storage/nvme5/new_clones/QML/BluetoothPairingApp' &
git clone https://github.com/nx-desktop/nx-systemtray-applet '/storage/nvme5/new_clones/QML/nx-systemtray-applet' &
git clone https://github.com/ioncodes/MaterialMessageBox '/storage/nvme5/new_clones/QML/MaterialMessageBox' &
git clone https://github.com/mikkeloscar/sddm-gracilis-theme '/storage/nvme5/new_clones/QML/sddm-gracilis-theme' &
git clone https://github.com/jemc/QmlSpec '/storage/nvme5/new_clones/QML/QmlSpec' &
