#!/bin/bash

git clone https://github.com/spotify/web-api '/storage/nvme5/new_clones/RAML/web-api' &
git clone https://github.com/qingmang-team/docs '/storage/nvme5/new_clones/RAML/docs' &
git clone https://github.com/jdiegodcp/ramlfications '/storage/nvme5/new_clones/RAML/ramlfications' &
git clone https://github.com/raml-org/raml-examples '/storage/nvme5/new_clones/RAML/raml-examples' &
git clone https://github.com/SalesforceCommerceCloud/commerce-sdk '/storage/nvme5/new_clones/RAML/commerce-sdk' &
git clone https://github.com/raml-org/raml-js-parser-2 '/storage/nvme5/new_clones/RAML/raml-js-parser-2' &
git clone https://github.com/coub/raml_ruby '/storage/nvme5/new_clones/RAML/raml_ruby' &
git clone https://github.com/chatwork/api '/storage/nvme5/new_clones/RAML/api' &
git clone https://github.com/OpenBankingUK/opendata-api-spec-compiled '/storage/nvme5/new_clones/RAML/opendata-api-spec-compiled' &
git clone https://github.com/mikestowe/php-raml2html '/storage/nvme5/new_clones/RAML/php-raml2html' &
git clone https://github.com/commercetools/commercetools-api-reference '/storage/nvme5/new_clones/RAML/commercetools-api-reference' &
git clone https://github.com/mulesoft-labs/raml-sublime-plugin '/storage/nvme5/new_clones/RAML/raml-sublime-plugin' &
git clone https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic '/storage/nvme5/new_clones/RAML/commerce-sdk-isomorphic' &
git clone https://github.com/AMWA-TV/is-04 '/storage/nvme5/new_clones/RAML/is-04' &
git clone https://github.com/lynn/trans-pride '/storage/nvme5/new_clones/RAML/trans-pride' &
git clone https://github.com/mulesoft-labs/raml-generator '/storage/nvme5/new_clones/RAML/raml-generator' &
git clone https://github.com/mojaloop/mojaloop-specification '/storage/nvme5/new_clones/RAML/mojaloop-specification' &
git clone https://github.com/yuanshenjian/restful-api-raml '/storage/nvme5/new_clones/RAML/restful-api-raml' &
git clone https://github.com/AMWA-TV/is-05 '/storage/nvme5/new_clones/RAML/is-05' &
git clone https://github.com/mulesoft-labs/exchange-documentation-samples '/storage/nvme5/new_clones/RAML/exchange-documentation-samples' &
git clone https://github.com/ramses-tech/ramses-example '/storage/nvme5/new_clones/RAML/ramses-example' &
git clone https://github.com/commercetools/commercetools-docs-kit '/storage/nvme5/new_clones/RAML/commercetools-docs-kit' &
git clone https://github.com/raml-org/raml-dotnet-parser-2 '/storage/nvme5/new_clones/RAML/raml-dotnet-parser-2' &
git clone https://github.com/qingmang-team/raml-sdk-android '/storage/nvme5/new_clones/RAML/raml-sdk-android' &
git clone https://github.com/axel-sirota/mulesoft4-fundamentals '/storage/nvme5/new_clones/RAML/mulesoft4-fundamentals' &
git clone https://github.com/scaganoff/example-eventlog-api '/storage/nvme5/new_clones/RAML/example-eventlog-api' &
git clone https://github.com/AMWA-TV/is-06 '/storage/nvme5/new_clones/RAML/is-06' &
git clone https://github.com/communitiesuk/waste-service-standards '/storage/nvme5/new_clones/RAML/waste-service-standards' &
git clone https://github.com/n2ygk/raml-snippets '/storage/nvme5/new_clones/RAML/raml-snippets' &
git clone https://github.com/MyTraining2019/MuleSoft '/storage/nvme5/new_clones/RAML/MuleSoft' &
git clone https://github.com/WHISHWORKS/mule-api-recipes '/storage/nvme5/new_clones/RAML/mule-api-recipes' &
git clone https://github.com/AMWA-TV/is-08 '/storage/nvme5/new_clones/RAML/is-08' &
git clone https://github.com/commercetools/scraml '/storage/nvme5/new_clones/RAML/scraml' &
git clone https://github.com/gpe-mw-training/3scale_onpremise_implementation_labs '/storage/nvme5/new_clones/RAML/3scale_onpremise_implementation_labs' &
git clone https://github.com/MITA-Governance-Board/Poplin '/storage/nvme5/new_clones/RAML/Poplin' &
git clone https://github.com/openapis/api-specs '/storage/nvme5/new_clones/RAML/api-specs' &
git clone https://github.com/ePages-de/epages-docs '/storage/nvme5/new_clones/RAML/epages-docs' &
git clone https://github.com/mulesoft-catalyst/common-raml-traits-fragment '/storage/nvme5/new_clones/RAML/common-raml-traits-fragment' &
git clone https://github.com/manikmagar/mule-battlesnake-starter '/storage/nvme5/new_clones/RAML/mule-battlesnake-starter' &
git clone https://github.com/raml-org/raml-tck '/storage/nvme5/new_clones/RAML/raml-tck' &
git clone https://github.com/mulespaceprogram/mulespaceprogram.github.io '/storage/nvme5/new_clones/RAML/mulespaceprogramhub.io' &
git clone https://github.com/pegasystems/pega-api '/storage/nvme5/new_clones/RAML/pega-api' &
git clone https://github.com/folio-org/raml '/storage/nvme5/new_clones/RAML/raml' &
git clone https://github.com/mulesoft-catalyst/api-specification-template '/storage/nvme5/new_clones/RAML/api-specification-template' &
git clone https://github.com/scottslowe/polyglot '/storage/nvme5/new_clones/RAML/polyglot' &
git clone https://github.com/nogates/brujula '/storage/nvme5/new_clones/RAML/brujula' &
git clone https://github.com/javaduke/ACME_API '/storage/nvme5/new_clones/RAML/ACME_API' &
git clone https://github.com/timofurrer/ramlient '/storage/nvme5/new_clones/RAML/ramlient' &
git clone https://github.com/raml-org/raml-by-example '/storage/nvme5/new_clones/RAML/raml-by-example' &
git clone https://github.com/mulesoft-catalyst/health-check-pattern-example '/storage/nvme5/new_clones/RAML/health-check-pattern-example' &
git clone https://github.com/srinivaskolaparthi/MuleSoft '/storage/nvme5/new_clones/RAML/MuleSoft' &
