#!/bin/bash

git clone https://github.com/EricZimmerman/RECmd '/storage/nvme5/new_clones/Rebol/RECmd' &
git clone https://github.com/waldronlab/Statistical-Rethinking '/storage/nvme5/new_clones/Rebol/Statistical-Rethinking' &
git clone https://github.com/hostilefork/whitespacers '/storage/nvme5/new_clones/Rebol/whitespacers' &
git clone https://github.com/astuder/Inside-EZRadioPRO '/storage/nvme5/new_clones/Rebol/Inside-EZRadioPRO' &
git clone https://github.com/dockimbel/cheyenne '/storage/nvme5/new_clones/Rebol/cheyenne' &
git clone https://github.com/hostilefork/rebmu '/storage/nvme5/new_clones/Rebol/rebmu' &
git clone https://github.com/rebolek/lest '/storage/nvme5/new_clones/Rebol/lest' &
git clone https://github.com/rgchris/Scripts '/storage/nvme5/new_clones/Rebol/Scripts' &
git clone https://github.com/gchiu/Rebol3 '/storage/nvme5/new_clones/Rebol/Rebol3' &
git clone https://github.com/cpsievert/bbscrapeR '/storage/nvme5/new_clones/Rebol/bbscrapeR' &
git clone https://github.com/rebolsource/rebol-syntax '/storage/nvme5/new_clones/Rebol/rebol-syntax' &
git clone https://github.com/NoiseCIEI/SensKernel '/storage/nvme5/new_clones/Rebol/SensKernel' &
git clone https://github.com/gchiu/rebolbot '/storage/nvme5/new_clones/Rebol/rebolbot' &
git clone https://github.com/hi-a/annepro-key '/storage/nvme5/new_clones/Rebol/annepro-key' &
git clone https://github.com/rebolsource/rebol-test '/storage/nvme5/new_clones/Rebol/rebol-test' &
git clone https://github.com/hostilefork/draem '/storage/nvme5/new_clones/Rebol/draem' &
git clone https://github.com/jankom/RebToStatic '/storage/nvme5/new_clones/Rebol/RebToStatic' &
git clone https://github.com/radareorg/radare2-testbins '/storage/nvme5/new_clones/Rebol/radare2-testbins' &
git clone https://github.com/Oldes/rs '/storage/nvme5/new_clones/Rebol/rs' &
git clone https://github.com/earl/rebol3 '/storage/nvme5/new_clones/Rebol/rebol3' &
git clone https://github.com/zsx/mysql-r3 '/storage/nvme5/new_clones/Rebol/mysql-r3' &
git clone https://github.com/saphirion/r3-gui '/storage/nvme5/new_clones/Rebol/r3-gui' &
git clone https://github.com/nchopin/py-smc2 '/storage/nvme5/new_clones/Rebol/py-smc2' &
git clone https://github.com/henrikmk/VID-Extension-Kit '/storage/nvme5/new_clones/Rebol/VID-Extension-Kit' &
git clone https://github.com/SAKET-SK/Semester6-SPPU-Data-Analysis-Lab '/storage/nvme5/new_clones/Rebol/Semester6-SPPU-Data-Analysis-Lab' &
git clone https://github.com/blalpert/best_ex '/storage/nvme5/new_clones/Rebol/best_ex' &
git clone https://github.com/hostilefork/rubol '/storage/nvme5/new_clones/Rebol/rubol' &
git clone https://github.com/astheeggeggs/UKBB_ldsc_r2 '/storage/nvme5/new_clones/Rebol/UKBB_ldsc_r2' &
git clone https://github.com/ldci/RedEdit '/storage/nvme5/new_clones/Rebol/RedEdit' &
git clone https://github.com/gchiu/Rebol2 '/storage/nvme5/new_clones/Rebol/Rebol2' &
git clone https://github.com/BrianHawley/rebol-patches '/storage/nvme5/new_clones/Rebol/rebol-patches' &
git clone https://github.com/rgchris/QuarterMaster '/storage/nvme5/new_clones/Rebol/QuarterMaster' &
git clone https://github.com/rgchris/StyleTalk '/storage/nvme5/new_clones/Rebol/StyleTalk' &
git clone https://github.com/PetteriAimonen/crs-c500c-utils '/storage/nvme5/new_clones/Rebol/crs-c500c-utils' &
git clone https://github.com/brentonk/merge-cow-polity '/storage/nvme5/new_clones/Rebol/merge-cow-polity' &
git clone https://github.com/angerangel/LCR3D '/storage/nvme5/new_clones/Rebol/LCR3D' &
git clone https://github.com/greggirwin/OpenME '/storage/nvme5/new_clones/Rebol/OpenME' &
git clone https://github.com/jjchern/geocorr '/storage/nvme5/new_clones/Rebol/geocorr' &
git clone https://github.com/moliad/liquid-libs '/storage/nvme5/new_clones/Rebol/liquid-libs' &
git clone https://github.com/sajattack/c64-asm-labels '/storage/nvme5/new_clones/Rebol/c64-asm-labels' &
git clone https://github.com/rebolek/prot-redis '/storage/nvme5/new_clones/Rebol/prot-redis' &
git clone https://github.com/Mark-hi/Rebol-Lexer '/storage/nvme5/new_clones/Rebol/Rebol-Lexer' &
git clone https://github.com/giuliolunati/rebol3-sl4a '/storage/nvme5/new_clones/Rebol/rebol3-sl4a' &
git clone https://github.com/PeterWAWood/UnicodeOutOfTheBoxTests '/storage/nvme5/new_clones/Rebol/UnicodeOutOfTheBoxTests' &
git clone https://github.com/gchiu/rebol-misc '/storage/nvme5/new_clones/Rebol/rebol-misc' &
git clone https://github.com/dockimbel/curecode '/storage/nvme5/new_clones/Rebol/curecode' &
git clone https://github.com/SteeveGit/R3-CODE-EDITOR '/storage/nvme5/new_clones/Rebol/R3-CODE-EDITOR' &
git clone https://github.com/Siskin-framework/Builder '/storage/nvme5/new_clones/Rebol/Builder' &
git clone https://github.com/001cat/pySurfInv '/storage/nvme5/new_clones/Rebol/pySurfInv' &
git clone https://github.com/r3n/renclib '/storage/nvme5/new_clones/Rebol/renclib' &
git clone https://github.com/rgchris/Red-Lang.org '/storage/nvme5/new_clones/Rebol/Red-Lang.org' &
git clone https://github.com/rebolek/MarkyMark '/storage/nvme5/new_clones/Rebol/MarkyMark' &
