#!/bin/bash

git clone https://github.com/red/red '/storage/nvme5/new_clones/Red/red' &
git clone https://github.com/red/code '/storage/nvme5/new_clones/Red/code' &
git clone https://github.com/ldci/redCV '/storage/nvme5/new_clones/Red/redCV' &
git clone https://github.com/rebolek/red-tools '/storage/nvme5/new_clones/Red/red-tools' &
git clone https://github.com/red/community '/storage/nvme5/new_clones/Red/community' &
git clone https://github.com/Crystal-RainSlide/AdditionalFiltersCN '/storage/nvme5/new_clones/Red/AdditionalFiltersCN' &
git clone https://github.com/red/wallet '/storage/nvme5/new_clones/Red/wallet' &
git clone https://github.com/honix/Redraw '/storage/nvme5/new_clones/Red/Redraw' &
git clone https://github.com/rebolek/gritter '/storage/nvme5/new_clones/Red/gritter' &
git clone https://github.com/djkovrik/CP77Mods '/storage/nvme5/new_clones/Red/CP77Mods' &
git clone https://github.com/rodrigosetti/corewar '/storage/nvme5/new_clones/Red/corewar' &
git clone https://github.com/endo64/mockup '/storage/nvme5/new_clones/Red/mockup' &
git clone https://github.com/kealist/RS-fossil-mirror '/storage/nvme5/new_clones/Red/RS-fossil-mirror' &
git clone https://github.com/hako/lines '/storage/nvme5/new_clones/Red/lines' &
git clone https://github.com/mikeyaunish/direct-code '/storage/nvme5/new_clones/Red/direct-code' &
git clone https://github.com/CDPR-Modding-Documentation/Cyberpunk-Modding-Docs '/storage/nvme5/new_clones/Red/Cyberpunk-Modding-Docs' &
git clone https://github.com/toomasv/drawing '/storage/nvme5/new_clones/Red/drawing' &
git clone https://github.com/exercism/red '/storage/nvme5/new_clones/Red/red' &
git clone https://github.com/GalenIvanov/Graphics-Red '/storage/nvme5/new_clones/Red/Graphics-Red' &
git clone https://github.com/psiberx/cp2077-playground '/storage/nvme5/new_clones/Red/cp2077-playground' &
git clone https://github.com/konglinglong/3gppDecoder '/storage/nvme5/new_clones/Red/3gppDecoder' &
git clone https://github.com/9214/daruma '/storage/nvme5/new_clones/Red/daruma' &
git clone https://github.com/webcpu/HaskellRed '/storage/nvme5/new_clones/Red/HaskellRed' &
git clone https://github.com/toomasv/regex '/storage/nvme5/new_clones/Red/regex' &
git clone https://github.com/toomasv/learning '/storage/nvme5/new_clones/Red/learning' &
git clone https://github.com/PeterWAWood/Red-System-Libs '/storage/nvme5/new_clones/Red/Red-System-Libs' &
git clone https://github.com/ldci/glfw-red '/storage/nvme5/new_clones/Red/glfw-red' &
git clone https://github.com/Pebaz/RGB '/storage/nvme5/new_clones/Red/RGB' &
git clone https://github.com/toomasv/syntax-highlighter '/storage/nvme5/new_clones/Red/syntax-highlighter' &
git clone https://github.com/greggirwin/red-formatting '/storage/nvme5/new_clones/Red/red-formatting' &
git clone https://github.com/GalenIvanov/Games '/storage/nvme5/new_clones/Red/Games' &
git clone https://github.com/flibdev/cyberpunk-mods '/storage/nvme5/new_clones/Red/cyberpunk-mods' &
git clone https://github.com/toomasv/query '/storage/nvme5/new_clones/Red/query' &
git clone https://github.com/koba-yu/RedOCR '/storage/nvme5/new_clones/Red/RedOCR' &
git clone https://github.com/planetsizecpu/forms '/storage/nvme5/new_clones/Red/forms' &
git clone https://github.com/AlexanderBaggett/RedIDE '/storage/nvme5/new_clones/Red/RedIDE' &
git clone https://github.com/planetsizecpu/Cave-In '/storage/nvme5/new_clones/Red/Cave-In' &
git clone https://github.com/hiiamboris/red-pure-fun '/storage/nvme5/new_clones/Red/red-pure-fun' &
git clone https://github.com/bitbegin/redlangserver '/storage/nvme5/new_clones/Red/redlangserver' &
git clone https://github.com/jocko-jc/red-tts '/storage/nvme5/new_clones/Red/red-tts' &
git clone https://github.com/martinus/YaceReloaded '/storage/nvme5/new_clones/Red/YaceReloaded' &
git clone https://github.com/giesse/red-topaz-parse '/storage/nvme5/new_clones/Red/red-topaz-parse' &
git clone https://github.com/schwarzbox/EmptyCore '/storage/nvme5/new_clones/Red/EmptyCore' &
git clone https://github.com/gltewalt/parse-caddy '/storage/nvme5/new_clones/Red/parse-caddy' &
git clone https://github.com/nodrygo/DemosRed '/storage/nvme5/new_clones/Red/DemosRed' &
git clone https://github.com/L-M-Sherlock/ChineseCentury '/storage/nvme5/new_clones/Red/ChineseCentury' &
git clone https://github.com/abdllhygt/coz '/storage/nvme5/new_clones/Red/coz' &
git clone https://github.com/toomasv/fourier '/storage/nvme5/new_clones/Red/fourier' &
git clone https://github.com/RenaudG/red-utilities '/storage/nvme5/new_clones/Red/red-utilities' &
git clone https://github.com/lepinekong/readablehumanformat '/storage/nvme5/new_clones/Red/readablehumanformat' &
git clone https://github.com/iArnold/Xiangqi '/storage/nvme5/new_clones/Red/Xiangqi' &
git clone https://github.com/rsheehan/Remix '/storage/nvme5/new_clones/Red/Remix' &
git clone https://github.com/ldci/ffmpeg '/storage/nvme5/new_clones/Red/ffmpeg' &
git clone https://github.com/q60/mursa '/storage/nvme5/new_clones/Red/mursa' &
git clone https://github.com/pbaille/redu '/storage/nvme5/new_clones/Red/redu' &
git clone https://github.com/toomasv/diagram '/storage/nvme5/new_clones/Red/diagram' &
git clone https://github.com/GalenIvanov/Animation-tests '/storage/nvme5/new_clones/Red/Animation-tests' &
git clone https://github.com/toomasv/table-template '/storage/nvme5/new_clones/Red/table-template' &
git clone https://github.com/hyzwhu/redbox '/storage/nvme5/new_clones/Red/redbox' &
git clone https://github.com/WayneCui/re-scripts '/storage/nvme5/new_clones/Red/re-scripts' &
git clone https://github.com/CFTheMaster/discord.red '/storage/nvme5/new_clones/Red/discord.red' &
git clone https://github.com/ldci/NeuralNetwork '/storage/nvme5/new_clones/Red/NeuralNetwork' &
git clone https://github.com/9214/7guis-red '/storage/nvme5/new_clones/Red/7guis-red' &
git clone https://github.com/toomasv/makedoc '/storage/nvme5/new_clones/Red/makedoc' &
git clone https://github.com/cloutiy/elipses '/storage/nvme5/new_clones/Red/elipses' &
git clone https://github.com/rcqls/red-gtk '/storage/nvme5/new_clones/Red/red-gtk' &
git clone https://github.com/toomasv/units '/storage/nvme5/new_clones/Red/units' &
git clone https://github.com/greggirwin/red-json '/storage/nvme5/new_clones/Red/red-json' &
git clone https://github.com/toomasv/red-graphviz '/storage/nvme5/new_clones/Red/red-graphviz' &
git clone https://github.com/quan-nh/rgit '/storage/nvme5/new_clones/Red/rgit' &
git clone https://github.com/cyb3rpsych0s1s/4ddicted '/storage/nvme5/new_clones/Red/4ddicted' &
git clone https://github.com/greggirwin/red-hof '/storage/nvme5/new_clones/Red/red-hof' &
git clone https://github.com/abdllhygt/red-zenity '/storage/nvme5/new_clones/Red/red-zenity' &
git clone https://github.com/ldci/Red-System '/storage/nvme5/new_clones/Red/Red-System' &
