#!/bin/bash

git clone https://github.com/renpy/renpy '/storage/nvme5/new_clones/Ren'Py/renpy' &
git clone https://github.com/Monika-After-Story/MonikaModDev '/storage/nvme5/new_clones/Ren'Py/MonikaModDev' &
git clone https://github.com/freeCodeCamp/LearnToCodeRPG '/storage/nvme5/new_clones/Ren'Py/LearnToCodeRPG' &
git clone https://github.com/CensoredUsername/unrpyc '/storage/nvme5/new_clones/Ren'Py/unrpyc' &
git clone https://github.com/MewX/cross-channel_chinese-localization_project '/storage/nvme5/new_clones/Ren'Py/cross-channel_chinese-localization_project' &
git clone https://github.com/kyouryuukunn/renpy-ActionEditor3 '/storage/nvme5/new_clones/Ren'Py/renpy-ActionEditor3' &
git clone https://github.com/SecondThundeR/DokiDoki-RenPy '/storage/nvme5/new_clones/Ren'Py/DokiDoki-RenPy' &
git clone https://github.com/luckykeeper/LOVE69_renpy_remaster '/storage/nvme5/new_clones/Ren'Py/LOVE69_renpy_remaster' &
git clone https://github.com/Monika-After-Story/DDLCModTemplate '/storage/nvme5/new_clones/Ren'Py/DDLCModTemplate' &
git clone https://github.com/saber-nyan/ddlc-android '/storage/nvme5/new_clones/Ren'Py/ddlc-android' &
git clone https://github.com/OlegWock/Roselia-achievements '/storage/nvme5/new_clones/Ren'Py/Roselia-achievements' &
git clone https://github.com/SoDaRa/Kinetic-Text-Tags '/storage/nvme5/new_clones/Ren'Py/Kinetic-Text-Tags' &
git clone https://github.com/Habitacle/battle-engine '/storage/nvme5/new_clones/Ren'Py/battle-engine' &
git clone https://github.com/fleetingheart/ksre '/storage/nvme5/new_clones/Ren'Py/ksre' &
git clone https://github.com/Skull220/DDLCtVN '/storage/nvme5/new_clones/Ren'Py/DDLCtVN' &
git clone https://github.com/lolbot-iichan/decompile.rpy '/storage/nvme5/new_clones/Ren'Py/decompile.rpy' &
git clone https://github.com/Bronya-Rand/DDLCModTemplate2.0 '/storage/nvme5/new_clones/Ren'Py/DDLCModTemplate2.0' &
git clone https://github.com/nyaatrap/renpy-utilities '/storage/nvme5/new_clones/Ren'Py/renpy-utilities' &
git clone https://github.com/judge2020/DokiDoki-Decompile '/storage/nvme5/new_clones/Ren'Py/DokiDoki-Decompile' &
git clone https://github.com/kyouryuukunn/renpy-ActionEditor '/storage/nvme5/new_clones/Ren'Py/renpy-ActionEditor' &
git clone https://github.com/zer0fixer/MAS-Extraplus '/storage/nvme5/new_clones/Ren'Py/MAS-Extraplus' &
git clone https://github.com/NickWildish/Mas-NSFW-Submod '/storage/nvme5/new_clones/Ren'Py/Mas-NSFW-Submod' &
git clone https://github.com/renpy/dse '/storage/nvme5/new_clones/Ren'Py/dse' &
git clone https://github.com/proudust/ddlc-jp-patch '/storage/nvme5/new_clones/Ren'Py/ddlc-jp-patch' &
git clone https://github.com/ColoradoStark/Renpy_Shooter '/storage/nvme5/new_clones/Ren'Py/Renpy_Shooter' &
git clone https://github.com/shawna-p/EasyRenPyGui '/storage/nvme5/new_clones/Ren'Py/EasyRenPyGui' &
git clone https://github.com/RenpyRemix/speech-bubbles '/storage/nvme5/new_clones/Ren'Py/speech-bubbles' &
git clone https://github.com/RuolinZheng08/renpy-minigames101 '/storage/nvme5/new_clones/Ren'Py/renpy-minigames101' &
git clone https://github.com/DRincs-Productions/DS-toolkit '/storage/nvme5/new_clones/Ren'Py/DS-toolkit' &
git clone https://github.com/DRincs-Productions/NQTR-System '/storage/nvme5/new_clones/Ren'Py/NQTR-System' &
git clone https://github.com/yakui-lover/eroge-dopil '/storage/nvme5/new_clones/Ren'Py/eroge-dopil' &
git clone https://github.com/Elckarow/Better-EMR-Phone '/storage/nvme5/new_clones/Ren'Py/Better-EMR-Phone' &
git clone https://github.com/selectivepaperclip/rpgm2renpy '/storage/nvme5/new_clones/Ren'Py/rpgm2renpy' &
git clone https://github.com/A-Soul-GameMaker-Project/ZhiJiang '/storage/nvme5/new_clones/Ren'Py/ZhiJiang' &
git clone https://github.com/shawna-p/mysterious-messenger '/storage/nvme5/new_clones/Ren'Py/mysterious-messenger' &
git clone https://github.com/VimislikArt/renpy_samplescript '/storage/nvme5/new_clones/Ren'Py/renpy_samplescript' &
git clone https://github.com/Barsonvenus/Memories-of-Self-Care-and-Literature '/storage/nvme5/new_clones/Ren'Py/Memories-of-Self-Care-and-Literature' &
git clone https://github.com/yukinogatari/Ren-Py-FancyText '/storage/nvme5/new_clones/Ren'Py/Ren-Py-FancyText' &
git clone https://github.com/nomnomnami/syrup-lite-rpg-framework '/storage/nvme5/new_clones/Ren'Py/syrup-lite-rpg-framework' &
git clone https://github.com/gcammisa/KatawaShoujo-RenPy8 '/storage/nvme5/new_clones/Ren'Py/KatawaShoujo-RenPy8' &
git clone https://github.com/stg-annon/BT-Silver-Base '/storage/nvme5/new_clones/Ren'Py/BT-Silver-Base' &
git clone https://github.com/mikoim/yamayami '/storage/nvme5/new_clones/Ren'Py/yamayami' &
git clone https://github.com/lunalucid/Keri-Dressup-RenPy-Template '/storage/nvme5/new_clones/Ren'Py/Keri-Dressup-RenPy-Template' &
git clone https://github.com/NathanGuilhot/yet-another-phone-for-renpy '/storage/nvme5/new_clones/Ren'Py/yet-another-phone-for-renpy' &
git clone https://github.com/qirien/personal-space '/storage/nvme5/new_clones/Ren'Py/personal-space' &
git clone https://github.com/XyMinxin/Brothel-King-Chinese-Translate '/storage/nvme5/new_clones/Ren'Py/Brothel-King-Chinese-Translate' &
git clone https://github.com/XelaPy/PyTFall '/storage/nvme5/new_clones/Ren'Py/PyTFall' &
git clone https://github.com/portalers/ABLocalization '/storage/nvme5/new_clones/Ren'Py/ABLocalization' &
git clone https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change '/storage/nvme5/new_clones/Ren'Py/MAS-Submod-Auto-Outfit-Change' &
git clone https://github.com/UnscriptedVN/candella '/storage/nvme5/new_clones/Ren'Py/candella' &
git clone https://github.com/Outland-Wanderer/simplified-chinese '/storage/nvme5/new_clones/Ren'Py/simplified-chinese' &
git clone https://github.com/libudu/renpy-deepl '/storage/nvme5/new_clones/Ren'Py/renpy-deepl' &
git clone https://github.com/stanriders/ksalpha-repair '/storage/nvme5/new_clones/Ren'Py/ksalpha-repair' &
git clone https://github.com/shawna-p/renpy-achievement '/storage/nvme5/new_clones/Ren'Py/renpy-achievement' &
git clone https://github.com/jsfehler/renpy-radarchart '/storage/nvme5/new_clones/Ren'Py/renpy-radarchart' &
git clone https://github.com/Gouvernathor/renpy-SWHolo '/storage/nvme5/new_clones/Ren'Py/renpy-SWHolo' &
git clone https://github.com/AgentAlpha81/RenPyParticles '/storage/nvme5/new_clones/Ren'Py/RenPyParticles' &
git clone https://github.com/DatCaptainHorse/MAS-Additions '/storage/nvme5/new_clones/Ren'Py/MAS-Additions' &
git clone https://github.com/Booplicate/MAS-Submods-SubmodUpdaterPlugin '/storage/nvme5/new_clones/Ren'Py/MAS-Submods-SubmodUpdaterPlugin' &
git clone https://github.com/CrossCouloir/renpy-blend-modes '/storage/nvme5/new_clones/Ren'Py/renpy-blend-modes' &
git clone https://github.com/Tsukuyami-TLs/higumei-engine-public '/storage/nvme5/new_clones/Ren'Py/higumei-engine-public' &
git clone https://github.com/GarnetSunset/DDLC-Purist-Mod '/storage/nvme5/new_clones/Ren'Py/DDLC-Purist-Mod' &
git clone https://github.com/wwcodemanila/WWCodeManila-Python '/storage/nvme5/new_clones/Ren'Py/WWCodeManila-Python' &
git clone https://github.com/jsfehler/renpy-freehand-draw '/storage/nvme5/new_clones/Ren'Py/renpy-freehand-draw' &
git clone https://github.com/RuolinZheng08/renpy-chess-engine '/storage/nvme5/new_clones/Ren'Py/renpy-chess-engine' &
git clone https://github.com/DmitrySenpai/everlasting_summer_sources '/storage/nvme5/new_clones/Ren'Py/everlasting_summer_sources' &
git clone https://github.com/MAS-Submod-MoyuTeam/dialogue-packs '/storage/nvme5/new_clones/Ren'Py/dialogue-packs' &
git clone https://github.com/Bronya-Rand/DDLC-ModMaker '/storage/nvme5/new_clones/Ren'Py/DDLC-ModMaker' &
git clone https://github.com/Lezalith/RenPy-Discord-Presence '/storage/nvme5/new_clones/Ren'Py/RenPy-Discord-Presence' &
git clone https://github.com/Tinymanhood/Rouge-Like-Expanded '/storage/nvme5/new_clones/Ren'Py/Rouge-Like-Expanded' &
git clone https://github.com/SoGu/renpyper '/storage/nvme5/new_clones/Ren'Py/renpyper' &
git clone https://github.com/imgradeone/DDLCModTemplate-Chinese-next '/storage/nvme5/new_clones/Ren'Py/DDLCModTemplate-Chinese-next' &
git clone https://github.com/red-moon-tea-party/renpy '/storage/nvme5/new_clones/Ren'Py/renpy' &
git clone https://github.com/Friends-of-Monika/otter-spritepacks '/storage/nvme5/new_clones/Ren'Py/otter-spritepacks' &
git clone https://github.com/stanriders/ks-summersclover '/storage/nvme5/new_clones/Ren'Py/ks-summersclover' &
git clone https://github.com/mtr-static-official/MonikaAfterStory-Chinese '/storage/nvme5/new_clones/Ren'Py/MonikaAfterStory-Chinese' &
git clone https://github.com/SynedraAcus/ShipsAndShits '/storage/nvme5/new_clones/Ren'Py/ShipsAndShits' &
git clone https://github.com/Friends-of-Monika/mas-presence '/storage/nvme5/new_clones/Ren'Py/mas-presence' &
git clone https://github.com/VimislikArt/rpg_fight '/storage/nvme5/new_clones/Ren'Py/rpg_fight' &
git clone https://github.com/alexkrob/dynamicsprites '/storage/nvme5/new_clones/Ren'Py/dynamicsprites' &
git clone https://github.com/DeXP/onemangaday '/storage/nvme5/new_clones/Ren'Py/onemangaday' &
git clone https://github.com/mayday-mayjay/MJ-MAS-selector-city '/storage/nvme5/new_clones/Ren'Py/MJ-MAS-selector-city' &
git clone https://github.com/renpy/id '/storage/nvme5/new_clones/Ren'Py/id' &
git clone https://github.com/ProjectAliceDev/aliceos '/storage/nvme5/new_clones/Ren'Py/aliceos' &
git clone https://github.com/AgentAlpha81/RGB-Split '/storage/nvme5/new_clones/Ren'Py/RGB-Split' &
git clone https://github.com/E-Lee-Za/Double-Edged-Blade-Game '/storage/nvme5/new_clones/Ren'Py/Double-Edged-Blade-Game' &
git clone https://github.com/Quandong-Zhang/movie2galagame '/storage/nvme5/new_clones/Ren'Py/movie2galagame' &
git clone https://github.com/abduelhamit/renpy-ingame-console '/storage/nvme5/new_clones/Ren'Py/renpy-ingame-console' &
git clone https://github.com/firelightning13/DDLC-MCRevengeMod '/storage/nvme5/new_clones/Ren'Py/DDLC-MCRevengeMod' &
git clone https://github.com/koroshiya/python-calendar '/storage/nvme5/new_clones/Ren'Py/python-calendar' &
git clone https://github.com/CompleteMonochrome/ddlctrueroute '/storage/nvme5/new_clones/Ren'Py/ddlctrueroute' &
git clone https://github.com/trajano/renpy-portrait-mode-ui '/storage/nvme5/new_clones/Ren'Py/renpy-portrait-mode-ui' &
git clone https://github.com/valery-iwanofu/renpy-shader-collection '/storage/nvme5/new_clones/Ren'Py/renpy-shader-collection' &
git clone https://github.com/proudust/ddlc-mas-jp-patch '/storage/nvme5/new_clones/Ren'Py/ddlc-mas-jp-patch' &
git clone https://github.com/SoDaRa/RenpyWaveShader '/storage/nvme5/new_clones/Ren'Py/RenpyWaveShader' &
git clone https://github.com/RenpyRemix/outline-shader '/storage/nvme5/new_clones/Ren'Py/outline-shader' &
git clone https://github.com/bibanon/a-tsundere-christmas-carol '/storage/nvme5/new_clones/Ren'Py/a-tsundere-christmas-carol' &
git clone https://github.com/DRincs-Productions/PG-GUI '/storage/nvme5/new_clones/Ren'Py/PG-GUI' &
git clone https://github.com/sonymanetov/Avocats '/storage/nvme5/new_clones/Ren'Py/Avocats' &
git clone https://github.com/tacoen/reramen '/storage/nvme5/new_clones/Ren'Py/reramen' &
git clone https://github.com/Emperrific/Renpy-Tutorials-CG-Gallery '/storage/nvme5/new_clones/Ren'Py/Renpy-Tutorials-CG-Gallery' &
git clone https://github.com/Ex4i/RenPy-gallery-tutorial '/storage/nvme5/new_clones/Ren'Py/RenPy-gallery-tutorial' &
git clone https://github.com/Friends-of-Monika/mas-autostart '/storage/nvme5/new_clones/Ren'Py/mas-autostart' &
git clone https://github.com/DrakeTheDuelist/MAS-Dreams-and-Nightmares '/storage/nvme5/new_clones/Ren'Py/MAS-Dreams-and-Nightmares' &
git clone https://github.com/faithvoid/RenpyNXPorts '/storage/nvme5/new_clones/Ren'Py/RenpyNXPorts' &
git clone https://github.com/IGRINI/decompile_everlasting_summer_all '/storage/nvme5/new_clones/Ren'Py/decompile_everlasting_summer_all' &
git clone https://github.com/College-Kings/College-Kings '/storage/nvme5/new_clones/Ren'Py/College-Kings' &
git clone https://github.com/pass-by-reference/renpy-space-invaders '/storage/nvme5/new_clones/Ren'Py/renpy-space-invaders' &
git clone https://github.com/LordUnderscore/SummertimeSaga '/storage/nvme5/new_clones/Ren'Py/SummertimeSaga' &
git clone https://github.com/Kiaazad/0GUI '/storage/nvme5/new_clones/Ren'Py/0GUI' &
git clone https://github.com/cheonbyeol/RenPy-GalleryPlus '/storage/nvme5/new_clones/Ren'Py/RenPy-GalleryPlus' &
git clone https://github.com/lightlyss/rievegh '/storage/nvme5/new_clones/Ren'Py/rievegh' &
git clone https://github.com/College-Kings/college-kings-translations '/storage/nvme5/new_clones/Ren'Py/college-kings-translations' &
git clone https://github.com/VimislikArt/dragdropcode '/storage/nvme5/new_clones/Ren'Py/dragdropcode' &
git clone https://github.com/andrefelipebarros/First-Game-for-Ren-Py '/storage/nvme5/new_clones/Ren'Py/First-Game-for-Ren-Py' &
git clone https://github.com/Blobadoodle/ddlc-decompiled '/storage/nvme5/new_clones/Ren'Py/ddlc-decompiled' &
git clone https://github.com/Koya-Sato/DDLC-Modding-Starter-Pack '/storage/nvme5/new_clones/Ren'Py/DDLC-Modding-Starter-Pack' &
git clone https://github.com/IJEMIN/RenPy-Yandere-Girl '/storage/nvme5/new_clones/Ren'Py/RenPy-Yandere-Girl' &
git clone https://github.com/RenpyRemix/extra-animated-value '/storage/nvme5/new_clones/Ren'Py/extra-animated-value' &
git clone https://github.com/KarmicBacklash/FatefulRemake '/storage/nvme5/new_clones/Ren'Py/FatefulRemake' &
git clone https://github.com/lolabray/Renpy-lovense-boilerplate '/storage/nvme5/new_clones/Ren'Py/Renpy-lovense-boilerplate' &
git clone https://github.com/therationalpi/DDLC-self-voicing '/storage/nvme5/new_clones/Ren'Py/DDLC-self-voicing' &
git clone https://github.com/CupCake-Team/Natsulogue '/storage/nvme5/new_clones/Ren'Py/Natsulogue' &
git clone https://github.com/Wilson-Smith/New-Stuff-for-Monika '/storage/nvme5/new_clones/Ren'Py/New-Stuff-for-Monika' &
git clone https://github.com/Sayo-nika/PressKit '/storage/nvme5/new_clones/Ren'Py/PressKit' &
git clone https://github.com/Glowtranslations/DDLC_ESP '/storage/nvme5/new_clones/Ren'Py/DDLC_ESP' &
git clone https://github.com/multimokia/MAS-Submod-consistent-menus '/storage/nvme5/new_clones/Ren'Py/MAS-Submod-consistent-menus' &
git clone https://github.com/qirien/personal-space2 '/storage/nvme5/new_clones/Ren'Py/personal-space2' &
git clone https://github.com/NathanGuilhot/Renpy-simple-messaging-system-for-mobile-game '/storage/nvme5/new_clones/Ren'Py/Renpy-simple-messaging-system-for-mobile-game' &
git clone https://github.com/CharlieFuu69/Codigos_RenPy '/storage/nvme5/new_clones/Ren'Py/Codigos_RenPy' &
git clone https://github.com/tw4449-s-MAS-Submods/Custom-Room-Den '/storage/nvme5/new_clones/Ren'Py/Custom-Room-Den' &
git clone https://github.com/Kiaazad/0GUI-dev-tools '/storage/nvme5/new_clones/Ren'Py/0GUI-dev-tools' &
git clone https://github.com/salty-salty-studios/first-snow '/storage/nvme5/new_clones/Ren'Py/first-snow' &
git clone https://github.com/thenamesgiu/VisualNovelTest '/storage/nvme5/new_clones/Ren'Py/VisualNovelTest' &
git clone https://github.com/RenpyRemix/multi-notify '/storage/nvme5/new_clones/Ren'Py/multi-notify' &
git clone https://github.com/Thediamondcryst/Ren-Py-Free-to-Use-Falling-Leaves '/storage/nvme5/new_clones/Ren'Py/Ren-Py-Free-to-Use-Falling-Leaves' &
git clone https://github.com/geneTechnician/watch-things-with-monika '/storage/nvme5/new_clones/Ren'Py/watch-things-with-monika' &
git clone https://github.com/RuolinZheng08/renpy-static-chessboard '/storage/nvme5/new_clones/Ren'Py/renpy-static-chessboard' &
git clone https://github.com/wowm03/Take-Monika-On-A-Date '/storage/nvme5/new_clones/Ren'Py/Take-Monika-On-A-Date' &
git clone https://github.com/StupidConference/simsim18 '/storage/nvme5/new_clones/Ren'Py/simsim18' &
git clone https://github.com/fanpu/The-Scarlet-Record '/storage/nvme5/new_clones/Ren'Py/The-Scarlet-Record' &
git clone https://github.com/EternalFeather/Angel_Seasons_Renpy_RPG '/storage/nvme5/new_clones/Ren'Py/Angel_Seasons_Renpy_RPG' &
git clone https://github.com/NyashniyVladya/gameWithMatches '/storage/nvme5/new_clones/Ren'Py/gameWithMatches' &
git clone https://github.com/Lezalith/LezInventory '/storage/nvme5/new_clones/Ren'Py/LezInventory' &
git clone https://github.com/zer0fixer/SubmodMAS '/storage/nvme5/new_clones/Ren'Py/SubmodMAS' &
git clone https://github.com/WatercressStudios/Ah-My-Girlfriend-is-a-Demon-Summoned-from-the-Depths-of-Hell '/storage/nvme5/new_clones/Ren'Py/Ah-My-Girlfriend-is-a-Demon-Summoned-from-the-Depths-of-Hell' &
git clone https://github.com/aquapaulo/renpy-typewriter-sounds '/storage/nvme5/new_clones/Ren'Py/renpy-typewriter-sounds' &
git clone https://github.com/geneTechnician/drink-coffee-with-monika '/storage/nvme5/new_clones/Ren'Py/drink-coffee-with-monika' &
git clone https://github.com/McFishFillet/MAS_yandere '/storage/nvme5/new_clones/Ren'Py/MAS_yandere' &
git clone https://github.com/chronoshag/DDLCMPT '/storage/nvme5/new_clones/Ren'Py/DDLCMPT' &
git clone https://github.com/hud0shnik/cold_hands '/storage/nvme5/new_clones/Ren'Py/cold_hands' &
git clone https://github.com/melothemarten/renpy-discord-integration '/storage/nvme5/new_clones/Ren'Py/renpy-discord-integration' &
