#!/bin/bash

git clone https://github.com/rescript-lang/rescript '/storage/nvme5/new_clones/ReScript/rescript' &
git clone https://github.com/ShenaniganDApp/brightid-discord-bot '/storage/nvme5/new_clones/ReScript/brightid-discord-bot' &
git clone https://github.com/purogamer/Fluent-for-Steam '/storage/nvme5/new_clones/ReScript/Fluent-for-Steam' &
git clone https://github.com/draftbit/avatar-generator '/storage/nvme5/new_clones/ReScript/avatar-generator' &
git clone https://github.com/Jack-Myth/Threshold-Miku '/storage/nvme5/new_clones/ReScript/Threshold-Miku' &
git clone https://github.com/rescript-react-native/rescript-react-native '/storage/nvme5/new_clones/ReScript/rescript-react-native' &
git clone https://github.com/redsigma/UPMetroSkin '/storage/nvme5/new_clones/ReScript/UPMetroSkin' &
git clone https://github.com/Xilinx/Vitis-HLS-Introductory-Examples '/storage/nvme5/new_clones/ReScript/Vitis-HLS-Introductory-Examples' &
git clone https://github.com/giraud/bs-css '/storage/nvme5/new_clones/ReScript/bs-css' &
git clone https://github.com/rescript-lang/rescript-react '/storage/nvme5/new_clones/ReScript/rescript-react' &
git clone https://github.com/ThePrimeagen/tyrone-biggums '/storage/nvme5/new_clones/ReScript/tyrone-biggums' &
git clone https://github.com/ungstein/OG-Steam '/storage/nvme5/new_clones/ReScript/OG-Steam' &
git clone https://github.com/rescriptbr/reform '/storage/nvme5/new_clones/ReScript/reform' &
git clone https://github.com/zth/rescript-relay '/storage/nvme5/new_clones/ReScript/rescript-relay' &
git clone https://github.com/rescript-lang/rescript-vscode '/storage/nvme5/new_clones/ReScript/rescript-vscode' &
git clone https://github.com/Wonder-Technology/Wonder.js '/storage/nvme5/new_clones/ReScript/Wonder.js' &
git clone https://github.com/glennsl/rescript-jest '/storage/nvme5/new_clones/ReScript/rescript-jest' &
git clone https://github.com/putaindecode/putaindecode.io '/storage/nvme5/new_clones/ReScript/putaindecode.io' &
git clone https://github.com/somini/Pixelvision2 '/storage/nvme5/new_clones/ReScript/Pixelvision2' &
git clone https://github.com/cca-io/rescript-mui '/storage/nvme5/new_clones/ReScript/rescript-mui' &
git clone https://github.com/teamwalnut/rescript-urql '/storage/nvme5/new_clones/ReScript/rescript-urql' &
git clone https://github.com/RationalJS/future '/storage/nvme5/new_clones/ReScript/future' &
git clone https://github.com/reasonml-community/bs-express '/storage/nvme5/new_clones/ReScript/bs-express' &
git clone https://github.com/DZakh/rescript-schema '/storage/nvme5/new_clones/ReScript/rescript-schema' &
git clone https://github.com/banacorn/agda-mode-vscode '/storage/nvme5/new_clones/ReScript/agda-mode-vscode' &
git clone https://github.com/Meta3D-Technology/Meta3D '/storage/nvme5/new_clones/ReScript/Meta3D' &
git clone https://github.com/bloodyowl/rescript-recoil '/storage/nvme5/new_clones/ReScript/rescript-recoil' &
git clone https://github.com/rescriptbr/ancestor '/storage/nvme5/new_clones/ReScript/ancestor' &
git clone https://github.com/TheSpyder/rescript-webapi '/storage/nvme5/new_clones/ReScript/rescript-webapi' &
git clone https://github.com/johnridesabike/coronate '/storage/nvme5/new_clones/ReScript/coronate' &
git clone https://github.com/ryyppy/rescript-promise '/storage/nvme5/new_clones/ReScript/rescript-promise' &
git clone https://github.com/jihchi/vitejs-template-react-rescript '/storage/nvme5/new_clones/ReScript/vitejs-template-react-rescript' &
git clone https://github.com/jeddeloh/rescript-apollo-client '/storage/nvme5/new_clones/ReScript/rescript-apollo-client' &
git clone https://github.com/darklang/rescript-tea '/storage/nvme5/new_clones/ReScript/rescript-tea' &
git clone https://github.com/JuliaAI/DataScienceTutorials.jl '/storage/nvme5/new_clones/ReScript/DataScienceTutorials.jl' &
git clone https://github.com/shakacode/rescript-dnd '/storage/nvme5/new_clones/ReScript/rescript-dnd' &
git clone https://github.com/shakacode/rescript-logger '/storage/nvme5/new_clones/ReScript/rescript-logger' &
git clone https://github.com/shakacode/rescript-classnames '/storage/nvme5/new_clones/ReScript/rescript-classnames' &
git clone https://github.com/mobily/rescript-date '/storage/nvme5/new_clones/ReScript/rescript-date' &
git clone https://github.com/vmarcosp/timerlab '/storage/nvme5/new_clones/ReScript/timerlab' &
git clone https://github.com/bloodyowl/rescript-react-update '/storage/nvme5/new_clones/ReScript/rescript-react-update' &
git clone https://github.com/dracula/steam '/storage/nvme5/new_clones/ReScript/steam' &
git clone https://github.com/ysu1989/GraphQuestions '/storage/nvme5/new_clones/ReScript/GraphQuestions' &
git clone https://github.com/ibmresilient/resilient-community-apps '/storage/nvme5/new_clones/ReScript/resilient-community-apps' &
git clone https://github.com/TheSpyder/rescript-nodejs '/storage/nvme5/new_clones/ReScript/rescript-nodejs' &
git clone https://github.com/draftbit/rescript-storybook '/storage/nvme5/new_clones/ReScript/rescript-storybook' &
git clone https://github.com/rescriptbr/react-query '/storage/nvme5/new_clones/ReScript/react-query' &
git clone https://github.com/bloodyowl/rescript-test '/storage/nvme5/new_clones/ReScript/rescript-test' &
git clone https://github.com/bloodyowl/rescript-express '/storage/nvme5/new_clones/ReScript/rescript-express' &
git clone https://github.com/hyoretsu/Ultimate-Steam-Dark-Mode-Skin '/storage/nvme5/new_clones/ReScript/Ultimate-Steam-Dark-Mode-Skin' &
git clone https://github.com/nkrkv/jzon '/storage/nvme5/new_clones/ReScript/jzon' &
git clone https://github.com/bodhish/mytemplate.xyz '/storage/nvme5/new_clones/ReScript/mytemplate.xyz' &
git clone https://github.com/ocaml/v3.ocaml.org-rescript '/storage/nvme5/new_clones/ReScript/v3.ocaml.org-rescript' &
git clone https://github.com/rescript-react-native/rescript-react-navigation '/storage/nvme5/new_clones/ReScript/rescript-react-navigation' &
git clone https://github.com/n0kk/ahud '/storage/nvme5/new_clones/ReScript/ahud' &
git clone https://github.com/SleepDaemon/Modern-Steam '/storage/nvme5/new_clones/ReScript/Modern-Steam' &
git clone https://github.com/bloodyowl/rescript-js '/storage/nvme5/new_clones/ReScript/rescript-js' &
git clone https://github.com/bloodyowl/rescript-future '/storage/nvme5/new_clones/ReScript/rescript-future' &
git clone https://github.com/cometkim/rescript-ink '/storage/nvme5/new_clones/ReScript/rescript-ink' &
git clone https://github.com/rescript-ui/rescript-chakra '/storage/nvme5/new_clones/ReScript/rescript-chakra' &
git clone https://github.com/javamonn/sunspot '/storage/nvme5/new_clones/ReScript/sunspot' &
git clone https://github.com/persianturtle/rescript-react-boilerplate '/storage/nvme5/new_clones/ReScript/rescript-react-boilerplate' &
git clone https://github.com/MoOx/react-from-svg '/storage/nvme5/new_clones/ReScript/react-from-svg' &
git clone https://github.com/rescript-lang/create-rescript-app '/storage/nvme5/new_clones/ReScript/create-rescript-app' &
git clone https://github.com/bloodyowl/reshowcase '/storage/nvme5/new_clones/ReScript/reshowcase' &
git clone https://github.com/bloodyowl/rescript-react-starter-kit '/storage/nvme5/new_clones/ReScript/rescript-react-starter-kit' &
git clone https://github.com/reason-seoul/rescript-collection '/storage/nvme5/new_clones/ReScript/rescript-collection' &
git clone https://github.com/Sevin7/7hud '/storage/nvme5/new_clones/ReScript/7hud' &
git clone https://github.com/glennsl/rescript-fetch '/storage/nvme5/new_clones/ReScript/rescript-fetch' &
git clone https://github.com/Fattafatta/rescript-solidjs '/storage/nvme5/new_clones/ReScript/rescript-solidjs' &
git clone https://github.com/MoOx/rescript-next '/storage/nvme5/new_clones/ReScript/rescript-next' &
git clone https://github.com/TheSpyder/rescript-fast-check '/storage/nvme5/new_clones/ReScript/rescript-fast-check' &
git clone https://github.com/green-labs/rescript-bindings '/storage/nvme5/new_clones/ReScript/rescript-bindings' &
git clone https://github.com/cometkim/rescript-vitest '/storage/nvme5/new_clones/ReScript/rescript-vitest' &
git clone https://github.com/shakacode/rescript-debounce '/storage/nvme5/new_clones/ReScript/rescript-debounce' &
git clone https://github.com/MoOx/react-multiversal '/storage/nvme5/new_clones/ReScript/react-multiversal' &
git clone https://github.com/cca-io/rescript-react-intl '/storage/nvme5/new_clones/ReScript/rescript-react-intl' &
git clone https://github.com/jihchi/app-template-rescript-react '/storage/nvme5/new_clones/ReScript/app-template-rescript-react' &
git clone https://github.com/bloodyowl/rescript-pages '/storage/nvme5/new_clones/ReScript/rescript-pages' &
git clone https://github.com/rescriptbr/react-flow '/storage/nvme5/new_clones/ReScript/react-flow' &
git clone https://github.com/protoship/rescript-tutorial '/storage/nvme5/new_clones/ReScript/rescript-tutorial' &
git clone https://github.com/rescriptbr/rescript-conduit '/storage/nvme5/new_clones/ReScript/rescript-conduit' &
git clone https://github.com/alanrsoares/rescript-game-of-life '/storage/nvme5/new_clones/ReScript/rescript-game-of-life' &
git clone https://github.com/ChargingTurnip/Fortress_Obscura '/storage/nvme5/new_clones/ReScript/Fortress_Obscura' &
git clone https://github.com/bobzhang/rescript-deno '/storage/nvme5/new_clones/ReScript/rescript-deno' &
git clone https://github.com/MoOx/moox '/storage/nvme5/new_clones/ReScript/moox' &
git clone https://github.com/MoOx/LifeTime '/storage/nvme5/new_clones/ReScript/LifeTime' &
git clone https://github.com/jongleb/re-schema-form '/storage/nvme5/new_clones/ReScript/re-schema-form' &
git clone https://github.com/JonasKruckenberg/tauri-rescript-template '/storage/nvme5/new_clones/ReScript/tauri-rescript-template' &
git clone https://github.com/green-labs/garter '/storage/nvme5/new_clones/ReScript/garter' &
git clone https://github.com/rescriptbr/reschema '/storage/nvme5/new_clones/ReScript/reschema' &
git clone https://github.com/Zeesastrous/ZeesHUD '/storage/nvme5/new_clones/ReScript/ZeesHUD' &
git clone https://github.com/cometkim/rescript-deno '/storage/nvme5/new_clones/ReScript/rescript-deno' &
git clone https://github.com/Eniere/idhud '/storage/nvme5/new_clones/ReScript/idhud' &
git clone https://github.com/ocurrent/current-bench '/storage/nvme5/new_clones/ReScript/current-bench' &
git clone https://github.com/oxiKKK/goldsrc-version-list '/storage/nvme5/new_clones/ReScript/goldsrc-version-list' &
git clone https://github.com/pixelpapercraft/pixel-papercraft-generator-builder '/storage/nvme5/new_clones/ReScript/pixel-papercraft-generator-builder' &
git clone https://github.com/quickstrom/ltl-visualizer '/storage/nvme5/new_clones/ReScript/ltl-visualizer' &
git clone https://github.com/eldh/bs-react-spring '/storage/nvme5/new_clones/ReScript/bs-react-spring' &
git clone https://github.com/tom-sherman/rescript-remix '/storage/nvme5/new_clones/ReScript/rescript-remix' &
git clone https://github.com/HyunSeob/seob.dev '/storage/nvme5/new_clones/ReScript/seob.dev' &
git clone https://github.com/tom-sherman/rescript-remix-template '/storage/nvme5/new_clones/ReScript/rescript-remix-template' &
git clone https://github.com/DZakh/rescript-json-schema '/storage/nvme5/new_clones/ReScript/rescript-json-schema' &
git clone https://github.com/DZakh/rescript-envsafe '/storage/nvme5/new_clones/ReScript/rescript-envsafe' &
git clone https://github.com/Zeta611/easyword '/storage/nvme5/new_clones/ReScript/easyword' &
git clone https://github.com/persianturtle/rescript-3d-carousel '/storage/nvme5/new_clones/ReScript/rescript-3d-carousel' &
git clone https://github.com/bloodyowl/rescript-request '/storage/nvme5/new_clones/ReScript/rescript-request' &
git clone https://github.com/bloodyowl/rescript-asyncdata '/storage/nvme5/new_clones/ReScript/rescript-asyncdata' &
git clone https://github.com/r17x/rescript-libs '/storage/nvme5/new_clones/ReScript/rescript-libs' &
git clone https://github.com/pd4d10/echojs-reader '/storage/nvme5/new_clones/ReScript/echojs-reader' &
git clone https://github.com/tkovs/pomodoro '/storage/nvme5/new_clones/ReScript/pomodoro' &
git clone https://github.com/PKU-DAIR/KnobsTuningEA '/storage/nvme5/new_clones/ReScript/KnobsTuningEA' &
git clone https://github.com/Fattafatta/rescript-jotai '/storage/nvme5/new_clones/ReScript/rescript-jotai' &
git clone https://github.com/rescriptbr/react-testing-library '/storage/nvme5/new_clones/ReScript/react-testing-library' &
git clone https://github.com/reason-seoul/snowpack-rescript-react '/storage/nvme5/new_clones/ReScript/snowpack-rescript-react' &
git clone https://github.com/alex35mil/alexfedoseev.com '/storage/nvme5/new_clones/ReScript/alexfedoseev.com' &
git clone https://github.com/snatvb/re-fp '/storage/nvme5/new_clones/ReScript/re-fp' &
git clone https://github.com/MiryangJung/rescript-remix-blog-template '/storage/nvme5/new_clones/ReScript/rescript-remix-blog-template' &
git clone https://github.com/nullprop/TempusRecords '/storage/nvme5/new_clones/ReScript/TempusRecords' &
git clone https://github.com/kmarcie/overwatchhud '/storage/nvme5/new_clones/ReScript/overwatchhud' &
git clone https://github.com/blanton144/kcorrect '/storage/nvme5/new_clones/ReScript/kcorrect' &
git clone https://github.com/smorimoto/rescript-videojs-example '/storage/nvme5/new_clones/ReScript/rescript-videojs-example' &
git clone https://github.com/chris-armstrong/funicular '/storage/nvme5/new_clones/ReScript/funicular' &
git clone https://github.com/believer/wod '/storage/nvme5/new_clones/ReScript/wod' &
git clone https://github.com/zth/rescript-relay-router '/storage/nvme5/new_clones/ReScript/rescript-relay-router' &
git clone https://github.com/chris-armstrong/rescript-aws-sdk-v3-wrapper '/storage/nvme5/new_clones/ReScript/rescript-aws-sdk-v3-wrapper' &
git clone https://github.com/scoville/re-optic '/storage/nvme5/new_clones/ReScript/re-optic' &
git clone https://github.com/opendevtools/rescript-intl '/storage/nvme5/new_clones/ReScript/rescript-intl' &
git clone https://github.com/ordohereticus/open_fortress '/storage/nvme5/new_clones/ReScript/open_fortress' &
git clone https://github.com/bloodyowl/rescript-react-compat '/storage/nvme5/new_clones/ReScript/rescript-react-compat' &
git clone https://github.com/Austaras/retask '/storage/nvme5/new_clones/ReScript/retask' &
git clone https://github.com/minuukang/rescript-relay-next-ssr-template '/storage/nvme5/new_clones/ReScript/rescript-relay-next-ssr-template' &
git clone https://github.com/kmarcie/mkhud '/storage/nvme5/new_clones/ReScript/mkhud' &
git clone https://github.com/lucasfloriani/re-uno '/storage/nvme5/new_clones/ReScript/re-uno' &
git clone https://github.com/andy013/votehud_custom_font '/storage/nvme5/new_clones/ReScript/votehud_custom_font' &
git clone https://github.com/hew/reason-styled-system '/storage/nvme5/new_clones/ReScript/reason-styled-system' &
git clone https://github.com/rescriptbr/rescript-toastify '/storage/nvme5/new_clones/ReScript/rescript-toastify' &
git clone https://github.com/rescript-react-native/svg '/storage/nvme5/new_clones/ReScript/svg' &
git clone https://github.com/brnrdog/rescript-polished '/storage/nvme5/new_clones/ReScript/rescript-polished' &
git clone https://github.com/vmarcosp/es77.dev '/storage/nvme5/new_clones/ReScript/es77.dev' &
git clone https://github.com/r17x/rescript-pulo '/storage/nvme5/new_clones/ReScript/rescript-pulo' &
git clone https://github.com/nathsou/yolang-res '/storage/nvme5/new_clones/ReScript/yolang-res' &
git clone https://github.com/rescriptbr/radix-ui '/storage/nvme5/new_clones/ReScript/radix-ui' &
git clone https://github.com/mikaello/rescript-tinycolor '/storage/nvme5/new_clones/ReScript/rescript-tinycolor' &
git clone https://github.com/reason-seoul/rescript-7guis '/storage/nvme5/new_clones/ReScript/rescript-7guis' &
git clone https://github.com/wires/wtf '/storage/nvme5/new_clones/ReScript/wtf' &
git clone https://github.com/LuKuangChen/stacker-2023 '/storage/nvme5/new_clones/ReScript/stacker-2023' &
git clone https://github.com/gaku-sei/re-jotai '/storage/nvme5/new_clones/ReScript/re-jotai' &
git clone https://github.com/jacobp100/technicalc-core '/storage/nvme5/new_clones/ReScript/technicalc-core' &
git clone https://github.com/opendevtools/wcag-color '/storage/nvme5/new_clones/ReScript/wcag-color' &
git clone https://github.com/TheIRGurus/Playbooks '/storage/nvme5/new_clones/ReScript/Playbooks' &
git clone https://github.com/stanislawbartkowski/mytpcds '/storage/nvme5/new_clones/ReScript/mytpcds' &
git clone https://github.com/riemannulus/rescript-tauri-bolierplate '/storage/nvme5/new_clones/ReScript/rescript-tauri-bolierplate' &
git clone https://github.com/sikanhe/rescript-esbuild-starter '/storage/nvme5/new_clones/ReScript/rescript-esbuild-starter' &
git clone https://github.com/rescriptbr/vite-rescript-starter '/storage/nvme5/new_clones/ReScript/vite-rescript-starter' &
git clone https://github.com/rescript-react-native/paper '/storage/nvme5/new_clones/ReScript/paper' &
git clone https://github.com/believer/kindle-highlights '/storage/nvme5/new_clones/ReScript/kindle-highlights' &
git clone https://github.com/jaredramirez/rescript-json '/storage/nvme5/new_clones/ReScript/rescript-json' &
git clone https://github.com/banacorn/rescript-vscode '/storage/nvme5/new_clones/ReScript/rescript-vscode' &
git clone https://github.com/cometkim/rescript-relay-issue-tracker '/storage/nvme5/new_clones/ReScript/rescript-relay-issue-tracker' &
git clone https://github.com/JoranHonig/tarantula '/storage/nvme5/new_clones/ReScript/tarantula' &
git clone https://github.com/mastercomfig/team-comtress-2-assets '/storage/nvme5/new_clones/ReScript/team-comtress-2-assets' &
git clone https://github.com/jakadak/TF2-extended-fonts '/storage/nvme5/new_clones/ReScript/TF2-extended-fonts' &
git clone https://github.com/ChangJoo-Park/rescript-example-for-starter '/storage/nvme5/new_clones/ReScript/rescript-example-for-starter' &
git clone https://github.com/eWert-Online/rescript-hash '/storage/nvme5/new_clones/ReScript/rescript-hash' &
git clone https://github.com/nickretallack/nameless-language '/storage/nvme5/new_clones/ReScript/nameless-language' &
git clone https://github.com/brettcannon/check-for-changed-files '/storage/nvme5/new_clones/ReScript/check-for-changed-files' &
git clone https://github.com/noble-ai/rescript-cypress '/storage/nvme5/new_clones/ReScript/rescript-cypress' &
git clone https://github.com/DZakh/rescript-ava '/storage/nvme5/new_clones/ReScript/rescript-ava' &
git clone https://github.com/yangdanny97/fire-emblem-chess '/storage/nvme5/new_clones/ReScript/fire-emblem-chess' &
git clone https://github.com/mcolour/colourhud '/storage/nvme5/new_clones/ReScript/colourhud' &
git clone https://github.com/draftbit/bs-js-collections '/storage/nvme5/new_clones/ReScript/bs-js-collections' &
git clone https://github.com/fdaciuk/severino '/storage/nvme5/new_clones/ReScript/severino' &
git clone https://github.com/rescript-react-native/async-storage '/storage/nvme5/new_clones/ReScript/async-storage' &
git clone https://github.com/darklang/tablecloth-rescript '/storage/nvme5/new_clones/ReScript/tablecloth-rescript' &
git clone https://github.com/ielab/sysrev-seed-collection '/storage/nvme5/new_clones/ReScript/sysrev-seed-collection' &
git clone https://github.com/VillageGreenPreserver/Half-Life-Hud '/storage/nvme5/new_clones/ReScript/Half-Life-Hud' &
git clone https://github.com/RawToast/ReTurbo '/storage/nvme5/new_clones/ReScript/ReTurbo' &
git clone https://github.com/professorDeveloper/CS-1.6 '/storage/nvme5/new_clones/ReScript/CS-1.6' &
git clone https://github.com/n0xii/ag2 '/storage/nvme5/new_clones/ReScript/ag2' &
git clone https://github.com/DZakh/rescript-stdlib-vendorer '/storage/nvme5/new_clones/ReScript/rescript-stdlib-vendorer' &
git clone https://github.com/MinimaHQ/safe-routing-blog-app-example '/storage/nvme5/new_clones/ReScript/safe-routing-blog-app-example' &
git clone https://github.com/jihchi/res-msw '/storage/nvme5/new_clones/ReScript/res-msw' &
git clone https://github.com/Zarhin/OpenSeesPyExamples '/storage/nvme5/new_clones/ReScript/OpenSeesPyExamples' &
git clone https://github.com/misterslin/SlinFireHUD '/storage/nvme5/new_clones/ReScript/SlinFireHUD' &
git clone https://github.com/arnabsen1729/rescript-react-starter '/storage/nvme5/new_clones/ReScript/rescript-react-starter' &
git clone https://github.com/faheempatel/fastingtime '/storage/nvme5/new_clones/ReScript/fastingtime' &
git clone https://github.com/weblab-notebook/website '/storage/nvme5/new_clones/ReScript/website' &
git clone https://github.com/bloodyowl/website '/storage/nvme5/new_clones/ReScript/website' &
git clone https://github.com/Valla-Chan/portal-elc-content '/storage/nvme5/new_clones/ReScript/portal-elc-content' &
git clone https://github.com/quickkennedy/cutehud '/storage/nvme5/new_clones/ReScript/cutehud' &
git clone https://github.com/davesnx/try-styled-ppx '/storage/nvme5/new_clones/ReScript/try-styled-ppx' &
git clone https://github.com/1uckyneo/rescript-tutorial '/storage/nvme5/new_clones/ReScript/rescript-tutorial' &
git clone https://github.com/Blixibon/css_weapons_in_hl2 '/storage/nvme5/new_clones/ReScript/css_weapons_in_hl2' &
git clone https://github.com/Apress/introducing-rescript '/storage/nvme5/new_clones/ReScript/introducing-rescript' &
git clone https://github.com/luki1412/Invert '/storage/nvme5/new_clones/ReScript/Invert' &
git clone https://github.com/bakkeby/dusk.resources '/storage/nvme5/new_clones/ReScript/dusk.resources' &
git clone https://github.com/noble-ai/rescript-rxjs '/storage/nvme5/new_clones/ReScript/rescript-rxjs' &
git clone https://github.com/OctoD/thestate '/storage/nvme5/new_clones/ReScript/thestate' &
git clone https://github.com/believer/coc-rescript '/storage/nvme5/new_clones/ReScript/coc-rescript' &
git clone https://github.com/potato-tf/HHAssets '/storage/nvme5/new_clones/ReScript/HHAssets' &
git clone https://github.com/CatalaLang/catala-website '/storage/nvme5/new_clones/ReScript/catala-website' &
git clone https://github.com/ArizonAB/relay-meetup '/storage/nvme5/new_clones/ReScript/relay-meetup' &
git clone https://github.com/SeaMonster-Studios/rescript-index '/storage/nvme5/new_clones/ReScript/rescript-index' &
git clone https://github.com/arafatamim/rescript-swr '/storage/nvme5/new_clones/ReScript/rescript-swr' &
git clone https://github.com/leadscales/warsawhud '/storage/nvme5/new_clones/ReScript/warsawhud' &
git clone https://github.com/resinfo/rescript-lua-ast '/storage/nvme5/new_clones/ReScript/rescript-lua-ast' &
git clone https://github.com/rescript-react-native/netinfo '/storage/nvme5/new_clones/ReScript/netinfo' &
git clone https://github.com/rescript-lang/rescript-sublime '/storage/nvme5/new_clones/ReScript/rescript-sublime' &
git clone https://github.com/woeps/solidjs-rescript '/storage/nvme5/new_clones/ReScript/solidjs-rescript' &
git clone https://github.com/MXYLR/Black-Mesa-workshop-mods-CN-Translation-project '/storage/nvme5/new_clones/ReScript/Black-Mesa-workshop-mods-CN-Translation-project' &
git clone https://github.com/rescript-react-native/webview '/storage/nvme5/new_clones/ReScript/webview' &
git clone https://github.com/stoneman2/tf_coop_extended '/storage/nvme5/new_clones/ReScript/tf_coop_extended' &
git clone https://github.com/shakacode/rescript-react-on-rails '/storage/nvme5/new_clones/ReScript/rescript-react-on-rails' &
git clone https://github.com/qabRieL99/HalfLifeSerisiTurkce '/storage/nvme5/new_clones/ReScript/HalfLifeSerisiTurkce' &
git clone https://github.com/emeks-studio/sensum '/storage/nvme5/new_clones/ReScript/sensum' &
git clone https://github.com/cca-io/rescript-logger '/storage/nvme5/new_clones/ReScript/rescript-logger' &
git clone https://github.com/BeingThink/rescript-koa '/storage/nvme5/new_clones/ReScript/rescript-koa' &
git clone https://github.com/AsianAntwan/AntsHUD '/storage/nvme5/new_clones/ReScript/AntsHUD' &
git clone https://github.com/rescriptbr/rescript-react-bootstrap '/storage/nvme5/new_clones/ReScript/rescript-react-bootstrap' &
git clone https://github.com/rescript-react-native/linear-gradient '/storage/nvme5/new_clones/ReScript/linear-gradient' &
git clone https://github.com/dsiu/rescript-snippets '/storage/nvme5/new_clones/ReScript/rescript-snippets' &
git clone https://github.com/saper150/remporium '/storage/nvme5/new_clones/ReScript/remporium' &
git clone https://github.com/bettercart/rescript-headless-ui-react '/storage/nvme5/new_clones/ReScript/rescript-headless-ui-react' &
git clone https://github.com/err0r500/realworld-app-backend-rescript-ts '/storage/nvme5/new_clones/ReScript/realworld-app-backend-rescript-ts' &
git clone https://github.com/dusty-phillips/rescript-react-intro '/storage/nvme5/new_clones/ReScript/rescript-react-intro' &
git clone https://github.com/fa7ad/reasonable-hackernews '/storage/nvme5/new_clones/ReScript/reasonable-hackernews' &
git clone https://github.com/rescript-react-native/device-info '/storage/nvme5/new_clones/ReScript/device-info' &
git clone https://github.com/MedicodiBiscotti/biscottihud '/storage/nvme5/new_clones/ReScript/biscottihud' &
git clone https://github.com/Ahmed-Naceur/dragon5 '/storage/nvme5/new_clones/ReScript/dragon5' &
git clone https://github.com/DCKT/rescript-router '/storage/nvme5/new_clones/ReScript/rescript-router' &
git clone https://github.com/rescript-react-native/image-picker '/storage/nvme5/new_clones/ReScript/image-picker' &
git clone https://github.com/rescript-react-native/safe-area-context '/storage/nvme5/new_clones/ReScript/safe-area-context' &
git clone https://github.com/cjrose/voidHUD '/storage/nvme5/new_clones/ReScript/voidHUD' &
git clone https://github.com/eldh/pick-a-color '/storage/nvme5/new_clones/ReScript/pick-a-color' &
git clone https://github.com/rescript-react-native/slider '/storage/nvme5/new_clones/ReScript/slider' &
git clone https://github.com/BingBongBonky/SpaceHUD '/storage/nvme5/new_clones/ReScript/SpaceHUD' &
git clone https://github.com/IAEA-NDS/gmapy '/storage/nvme5/new_clones/ReScript/gmapy' &
git clone https://github.com/es2077/workshop-rescript '/storage/nvme5/new_clones/ReScript/workshop-rescript' &
git clone https://github.com/believer/re-actual '/storage/nvme5/new_clones/ReScript/re-actual' &
git clone https://github.com/jdeisenberg/domgraphs '/storage/nvme5/new_clones/ReScript/domgraphs' &
git clone https://github.com/omnibombulator/Flarepunch '/storage/nvme5/new_clones/ReScript/Flarepunch' &
git clone https://github.com/rescript-react-native/safe-area-view '/storage/nvme5/new_clones/ReScript/safe-area-view' &
git clone https://github.com/rescript-react-native/datetimepicker '/storage/nvme5/new_clones/ReScript/datetimepicker' &
git clone https://github.com/leadscales/leadhud '/storage/nvme5/new_clones/ReScript/leadhud' &
git clone https://github.com/alstn2468/gatsby-starter-blog-rescript '/storage/nvme5/new_clones/ReScript/gatsby-starter-blog-rescript' &
git clone https://github.com/MatheusBBarni/youtube-to-genius-extension '/storage/nvme5/new_clones/ReScript/youtube-to-genius-extension' &
git clone https://github.com/shakacode/rescript-throttle '/storage/nvme5/new_clones/ReScript/rescript-throttle' &
git clone https://github.com/rpominov/typesafe-sql '/storage/nvme5/new_clones/ReScript/typesafe-sql' &
git clone https://github.com/1uckyneo/rescript-react-app '/storage/nvme5/new_clones/ReScript/rescript-react-app' &
git clone https://github.com/rishank-1996/EECS470_F19 '/storage/nvme5/new_clones/ReScript/EECS470_F19' &
git clone https://github.com/cca-io/quick-translate '/storage/nvme5/new_clones/ReScript/quick-translate' &
git clone https://github.com/fluxxy/fluxhud '/storage/nvme5/new_clones/ReScript/fluxhud' &
git clone https://github.com/scoville/re-hooks '/storage/nvme5/new_clones/ReScript/re-hooks' &
git clone https://github.com/mapbase-source/mapbase-game-src '/storage/nvme5/new_clones/ReScript/mapbase-game-src' &
git clone https://github.com/rescript-react-native/push-notification-ios '/storage/nvme5/new_clones/ReScript/push-notification-ios' &
git clone https://github.com/FoolEcho/vtmb-up '/storage/nvme5/new_clones/ReScript/vtmb-up' &
git clone https://github.com/Xeogin/HL2DM-Community-Patch '/storage/nvme5/new_clones/ReScript/HL2DM-Community-Patch' &
git clone https://github.com/kyleraykbs/Portal2MultiplayerMod '/storage/nvme5/new_clones/ReScript/Portal2MultiplayerMod' &
git clone https://github.com/connorjan/surface '/storage/nvme5/new_clones/ReScript/surface' &
git clone https://github.com/heliaxdev/rescript-react-feather '/storage/nvme5/new_clones/ReScript/rescript-react-feather' &
git clone https://github.com/An-Tu/bs-bem-cl '/storage/nvme5/new_clones/ReScript/bs-bem-cl' &
git clone https://github.com/pedrobslisboa/reskeleton '/storage/nvme5/new_clones/ReScript/reskeleton' &
