#!/bin/bash

git clone https://github.com/renode/renode '/storage/nvme5/new_clones/RobotFramework/renode' &
git clone https://github.com/robotframework/WebDemo '/storage/nvme5/new_clones/RobotFramework/WebDemo' &
git clone https://github.com/adrianyorke/robotframework-cookbook '/storage/nvme5/new_clones/RobotFramework/robotframework-cookbook' &
git clone https://github.com/vmware/vic-product '/storage/nvme5/new_clones/RobotFramework/vic-product' &
git clone https://github.com/MarketSquare/Robotframework-Database-Library '/storage/nvme5/new_clones/RobotFramework/Robotframework-Database-Library' &
git clone https://github.com/boakley/robotframework-lint '/storage/nvme5/new_clones/RobotFramework/robotframework-lint' &
git clone https://github.com/up1/course-robotframework '/storage/nvme5/new_clones/RobotFramework/course-robotframework' &
git clone https://github.com/MarketSquare/robotframework-tidy '/storage/nvme5/new_clones/RobotFramework/robotframework-tidy' &
git clone https://github.com/openbmc/openbmc-test-automation '/storage/nvme5/new_clones/RobotFramework/openbmc-test-automation' &
git clone https://github.com/antmicro/litex-vexriscv-tensorflow-lite-demo '/storage/nvme5/new_clones/RobotFramework/litex-vexriscv-tensorflow-lite-demo' &
git clone https://github.com/Tesena-smart-testing/WatchUI '/storage/nvme5/new_clones/RobotFramework/WatchUI' &
git clone https://github.com/runwhen-contrib/rw-public-codecollection '/storage/nvme5/new_clones/RobotFramework/rw-public-codecollection' &
git clone https://github.com/flokkr/runtime-compose '/storage/nvme5/new_clones/RobotFramework/runtime-compose' &
git clone https://github.com/brain-tec/odoo-robot-framework '/storage/nvme5/new_clones/RobotFramework/odoo-robot-framework' &
git clone https://github.com/FDio/csit '/storage/nvme5/new_clones/RobotFramework/csit' &
git clone https://github.com/alapanme/Robot-Framework '/storage/nvme5/new_clones/RobotFramework/Robot-Framework' &
git clone https://github.com/collective/robotframework-selenium2screenshots '/storage/nvme5/new_clones/RobotFramework/robotframework-selenium2screenshots' &
git clone https://github.com/eficode/Docker-Selenium-Example '/storage/nvme5/new_clones/RobotFramework/Docker-Selenium-Example' &
git clone https://github.com/serhatbolsu/robotframework-appium-sample '/storage/nvme5/new_clones/RobotFramework/robotframework-appium-sample' &
git clone https://github.com/MarketSquare/robotframework-style-guide '/storage/nvme5/new_clones/RobotFramework/robotframework-style-guide' &
git clone https://github.com/randomsync/robotframework-mqttlibrary '/storage/nvme5/new_clones/RobotFramework/robotframework-mqttlibrary' &
git clone https://github.com/robotframework/DosDontsSlides '/storage/nvme5/new_clones/RobotFramework/DosDontsSlides' &
git clone https://github.com/bendersej/pdf-keywords-extractor '/storage/nvme5/new_clones/RobotFramework/pdf-keywords-extractor' &
git clone https://github.com/opendaylight/integration-test '/storage/nvme5/new_clones/RobotFramework/integration-test' &
git clone https://github.com/robots-from-jupyter/robotlab '/storage/nvme5/new_clones/RobotFramework/robotlab' &
git clone https://github.com/balena-io/autohat '/storage/nvme5/new_clones/RobotFramework/autohat' &
git clone https://github.com/eficode/robotframework-selenium '/storage/nvme5/new_clones/RobotFramework/robotframework-selenium' &
git clone https://github.com/LambdaTest/Robot-Selenium-Sample '/storage/nvme5/new_clones/RobotFramework/Robot-Selenium-Sample' &
git clone https://github.com/MoSedky/RobotFW_KT '/storage/nvme5/new_clones/RobotFramework/RobotFW_KT' &
git clone https://github.com/nottyo/robotframework-samples '/storage/nvme5/new_clones/RobotFramework/robotframework-samples' &
git clone https://github.com/ServiceNow/atf-headless-runner '/storage/nvme5/new_clones/RobotFramework/atf-headless-runner' &
git clone https://github.com/s4int/robotframework-CSVLibrary '/storage/nvme5/new_clones/RobotFramework/robotframework-CSVLibrary' &
git clone https://github.com/openprocurement/robot_tests '/storage/nvme5/new_clones/RobotFramework/robot_tests' &
git clone https://github.com/papitodev/nuclone-appium-robot '/storage/nvme5/new_clones/RobotFramework/nuclone-appium-robot' &
git clone https://github.com/robotframework/IntroSlides '/storage/nvme5/new_clones/RobotFramework/IntroSlides' &
git clone https://github.com/kamalgirdher/RobotFrameworkTraining '/storage/nvme5/new_clones/RobotFramework/RobotFrameworkTraining' &
git clone https://github.com/odonnell-anthony/robotframework-api-example-test-suite '/storage/nvme5/new_clones/RobotFramework/robotframework-api-example-test-suite' &
git clone https://github.com/yuryalencar/mobile_test_automation_template '/storage/nvme5/new_clones/RobotFramework/mobile_test_automation_template' &
git clone https://github.com/red-hat-data-services/ods-ci '/storage/nvme5/new_clones/RobotFramework/ods-ci' &
git clone https://github.com/jimpriest/robotframework-preso '/storage/nvme5/new_clones/RobotFramework/robotframework-preso' &
git clone https://github.com/danielwhatmuff/robot-docker '/storage/nvme5/new_clones/RobotFramework/robot-docker' &
git clone https://github.com/MahmoudElSharkawy/RobotFramework-Practice '/storage/nvme5/new_clones/RobotFramework/RobotFramework-Practice' &
git clone https://github.com/TungstenTransformation/KTScripts '/storage/nvme5/new_clones/RobotFramework/KTScripts' &
git clone https://github.com/bendersej/bill-collector '/storage/nvme5/new_clones/RobotFramework/bill-collector' &
git clone https://github.com/lczub/robotframework-magik '/storage/nvme5/new_clones/RobotFramework/robotframework-magik' &
git clone https://github.com/osandadeshan/robot-framework-web-automation-demo '/storage/nvme5/new_clones/RobotFramework/robot-framework-web-automation-demo' &
git clone https://github.com/etsi-cti-admin/robotframework-mockserver '/storage/nvme5/new_clones/RobotFramework/robotframework-mockserver' &
git clone https://github.com/openafs-contrib/openafs-robotest '/storage/nvme5/new_clones/RobotFramework/openafs-robotest' &
git clone https://github.com/Lazygarde/SPOJ-PTIT '/storage/nvme5/new_clones/RobotFramework/SPOJ-PTIT' &
git clone https://github.com/Dasharo/open-source-firmware-validation '/storage/nvme5/new_clones/RobotFramework/open-source-firmware-validation' &
git clone https://github.com/weareqacademy/rfw-01-parodify '/storage/nvme5/new_clones/RobotFramework/rfw-01-parodify' &
git clone https://github.com/qaninja-academy/roboweek5 '/storage/nvme5/new_clones/RobotFramework/roboweek5' &
git clone https://github.com/spryker/robotframework-suite-tests '/storage/nvme5/new_clones/RobotFramework/robotframework-suite-tests' &
git clone https://github.com/edgexfoundry/edgex-taf '/storage/nvme5/new_clones/RobotFramework/edgex-taf' &
git clone https://github.com/Omenia/robotframework_for_apis '/storage/nvme5/new_clones/RobotFramework/robotframework_for_apis' &
git clone https://github.com/MarketSquare/ci-cd-examples '/storage/nvme5/new_clones/RobotFramework/ci-cd-examples' &
git clone https://github.com/yazidisme/robotframework-bdd-example '/storage/nvme5/new_clones/RobotFramework/robotframework-bdd-example' &
git clone https://github.com/Snooz82/robotframework-browser-migration '/storage/nvme5/new_clones/RobotFramework/robotframework-browser-migration' &
git clone https://github.com/zhoujinjian/robotframework_training '/storage/nvme5/new_clones/RobotFramework/robotframework_training' &
git clone https://github.com/pekkaklarck/robot-libraries-why-and-how '/storage/nvme5/new_clones/RobotFramework/robot-libraries-why-and-how' &
git clone https://github.com/marklogic/marklogic-docker '/storage/nvme5/new_clones/RobotFramework/marklogic-docker' &
git clone https://github.com/odonnell-anthony/robotframework-automation-practice '/storage/nvme5/new_clones/RobotFramework/robotframework-automation-practice' &
git clone https://github.com/laurentbristiel/robotframework-faker-example '/storage/nvme5/new_clones/RobotFramework/robotframework-faker-example' &
git clone https://github.com/SFDO-Community/OmbudsmanCloudCare '/storage/nvme5/new_clones/RobotFramework/OmbudsmanCloudCare' &
git clone https://github.com/mathiasconradt/auth0-tenant-creation-rpa '/storage/nvme5/new_clones/RobotFramework/auth0-tenant-creation-rpa' &
git clone https://github.com/szabolcstoth/robotframework-basics '/storage/nvme5/new_clones/RobotFramework/robotframework-basics' &
git clone https://github.com/okgolove/robotframework-jenkins '/storage/nvme5/new_clones/RobotFramework/robotframework-jenkins' &
git clone https://github.com/wywincl/SeleniumTest '/storage/nvme5/new_clones/RobotFramework/SeleniumTest' &
git clone https://github.com/diogorb/DioAceleraGFT-RobotCodeExamples '/storage/nvme5/new_clones/RobotFramework/DioAceleraGFT-RobotCodeExamples' &
git clone https://github.com/samanthashain/Mail-Merge-for-Salesforce-Nonprofit-Cloud '/storage/nvme5/new_clones/RobotFramework/Mail-Merge-for-Salesforce-Nonprofit-Cloud' &
git clone https://github.com/Atihinen/RobotFramework-Selenium2Library '/storage/nvme5/new_clones/RobotFramework/RobotFramework-Selenium2Library' &
git clone https://github.com/CiscoTestAutomation/CLUS18-DevNet-2595 '/storage/nvme5/new_clones/RobotFramework/CLUS18-DevNet-2595' &
git clone https://github.com/opencord/cord-tester '/storage/nvme5/new_clones/RobotFramework/cord-tester' &
git clone https://github.com/wiremock/robotframework-wiremock '/storage/nvme5/new_clones/RobotFramework/robotframework-wiremock' &
git clone https://github.com/LambdaTest/robot-selenium-hyperexecute-sample '/storage/nvme5/new_clones/RobotFramework/robot-selenium-hyperexecute-sample' &
git clone https://github.com/laojala/robot_docker_demo '/storage/nvme5/new_clones/RobotFramework/robot_docker_demo' &
git clone https://github.com/jjwong/RESTinstance_starter_project '/storage/nvme5/new_clones/RobotFramework/RESTinstance_starter_project' &
git clone https://github.com/ducdhm/robotframework-selenium-example '/storage/nvme5/new_clones/RobotFramework/robotframework-selenium-example' &
git clone https://github.com/robocorp/example-rasa-robot '/storage/nvme5/new_clones/RobotFramework/example-rasa-robot' &
git clone https://github.com/antmicro/renode-rtems-leon3 '/storage/nvme5/new_clones/RobotFramework/renode-rtems-leon3' &
git clone https://github.com/Tesena-smart-testing/selfhealing-robot-framework '/storage/nvme5/new_clones/RobotFramework/selfhealing-robot-framework' &
git clone https://github.com/SFDO-Tooling/CumulusCI-CI-Demo '/storage/nvme5/new_clones/RobotFramework/CumulusCI-CI-Demo' &
git clone https://github.com/LambdaTest/LT-appium-python-robot '/storage/nvme5/new_clones/RobotFramework/LT-appium-python-robot' &
git clone https://github.com/shnigi/Docker-Headless-Testing-Demo '/storage/nvme5/new_clones/RobotFramework/Docker-Headless-Testing-Demo' &
git clone https://github.com/RobotFramework-Italia/FromZerotoHero '/storage/nvme5/new_clones/RobotFramework/FromZerotoHero' &
git clone https://github.com/sauce-archives/Python-Robot-Selenium '/storage/nvme5/new_clones/RobotFramework/Python-Robot-Selenium' &
git clone https://github.com/yaroslav-kuts/Netcracker.TA.Lab '/storage/nvme5/new_clones/RobotFramework/Netcracker.TA.Lab' &
git clone https://github.com/sejaninja/robocamp5-web '/storage/nvme5/new_clones/RobotFramework/robocamp5-web' &
git clone https://github.com/SFDO-Tooling/CCI-Food-Bank '/storage/nvme5/new_clones/RobotFramework/CCI-Food-Bank' &
git clone https://github.com/qentinelqi/qweb_workshop '/storage/nvme5/new_clones/RobotFramework/qweb_workshop' &
git clone https://github.com/Hi-Fi/robotframework-java-example '/storage/nvme5/new_clones/RobotFramework/robotframework-java-example' &
git clone https://github.com/robocorp/example-oauth-email '/storage/nvme5/new_clones/RobotFramework/example-oauth-email' &
git clone https://github.com/dnomyar90/RF-Appium-Parallel-Sample '/storage/nvme5/new_clones/RobotFramework/RF-Appium-Parallel-Sample' &
git clone https://github.com/TungstenRPA/RPA-11.1 '/storage/nvme5/new_clones/RobotFramework/RPA-11.1' &
git clone https://github.com/TungstenRPA/RPA-11.3 '/storage/nvme5/new_clones/RobotFramework/RPA-11.3' &
git clone https://github.com/FormulatedAutomation/StupidRobotTricks '/storage/nvme5/new_clones/RobotFramework/StupidRobotTricks' &
git clone https://github.com/Python3-Training/RF-Inspire '/storage/nvme5/new_clones/RobotFramework/RF-Inspire' &
