#!/bin/bash

git clone https://github.com/friendly/SAS-macros '/storage/nvme5/new_clones/SAS/SAS-macros' &
git clone https://github.com/HHS-AHRQ/MEPS '/storage/nvme5/new_clones/SAS/MEPS' &
git clone https://github.com/scottbass/SAS '/storage/nvme5/new_clones/SAS/SAS' &
git clone https://github.com/sassoftware/sas-prog-for-r-users '/storage/nvme5/new_clones/SAS/sas-prog-for-r-users' &
git clone https://github.com/sassoftware/enlighten-apply '/storage/nvme5/new_clones/SAS/enlighten-apply' &
git clone https://github.com/sasjs/core '/storage/nvme5/new_clones/SAS/core' &
git clone https://github.com/yabwon/SAS_PACKAGES '/storage/nvme5/new_clones/SAS/SAS_PACKAGES' &
git clone https://github.com/phuse-org/phuse-scripts '/storage/nvme5/new_clones/SAS/phuse-scripts' &
git clone https://github.com/AlgorexHealth/hcc-python '/storage/nvme5/new_clones/SAS/hcc-python' &
git clone https://github.com/yubin-park/hcuppy '/storage/nvme5/new_clones/SAS/hcuppy' &
git clone https://github.com/Boemska/macrocore '/storage/nvme5/new_clones/SAS/macrocore' &
git clone https://github.com/sassoftware/sas-studio-custom-steps '/storage/nvme5/new_clones/SAS/sas-studio-custom-steps' &
git clone https://github.com/jlroo/SAS-Programming '/storage/nvme5/new_clones/SAS/SAS-Programming' &
git clone https://github.com/sascommunities/sas-global-forum-2019 '/storage/nvme5/new_clones/SAS/sas-global-forum-2019' &
git clone https://github.com/raleighlittles/SAS-Study-Guide '/storage/nvme5/new_clones/SAS/SAS-Study-Guide' &
git clone https://github.com/BivinSadler/MSDS_6371_Stat_Foundations '/storage/nvme5/new_clones/SAS/MSDS_6371_Stat_Foundations' &
git clone https://github.com/r0f1/sashelp '/storage/nvme5/new_clones/SAS/sashelp' &
git clone https://github.com/eleanormurray/CausalSurvivalAnalysisWorkshop '/storage/nvme5/new_clones/SAS/CausalSurvivalAnalysisWorkshop' &
git clone https://github.com/sassoftware/sas-cert-prep-data '/storage/nvme5/new_clones/SAS/sas-cert-prep-data' &
git clone https://github.com/hqgu/Romance-of-SAS-Programming '/storage/nvme5/new_clones/SAS/Romance-of-SAS-Programming' &
git clone https://github.com/CausalInference/GFORMULA-SAS '/storage/nvme5/new_clones/SAS/GFORMULA-SAS' &
git clone https://github.com/PaulSchmidtGit/Heritability '/storage/nvme5/new_clones/SAS/Heritability' &
git clone https://github.com/sascommunities/the-do-loop-blog '/storage/nvme5/new_clones/SAS/the-do-loop-blog' &
git clone https://github.com/sassoftware/sas-viya-dmml-pipelines '/storage/nvme5/new_clones/SAS/sas-viya-dmml-pipelines' &
git clone https://github.com/sassoftware/learning-sas-by-example-2nd '/storage/nvme5/new_clones/SAS/learning-sas-by-example-2nd' &
git clone https://github.com/tomhub/SAS '/storage/nvme5/new_clones/SAS/SAS' &
git clone https://github.com/edwinhu/sas '/storage/nvme5/new_clones/SAS/sas' &
git clone https://github.com/sassoftware/sasoptpy '/storage/nvme5/new_clones/SAS/sasoptpy' &
git clone https://github.com/gerhard1050/Applying-Data-Science-Using-SAS '/storage/nvme5/new_clones/SAS/Applying-Data-Science-Using-SAS' &
git clone https://github.com/sasutils/macros '/storage/nvme5/new_clones/SAS/macros' &
git clone https://github.com/sassoftware/sas-access-samples '/storage/nvme5/new_clones/SAS/sas-access-samples' &
git clone https://github.com/Jiangtang/SAS_ListProcessing '/storage/nvme5/new_clones/SAS/SAS_ListProcessing' &
git clone https://github.com/IU-Data-Management/SAS '/storage/nvme5/new_clones/SAS/SAS' &
git clone https://github.com/macropeople/macrocore '/storage/nvme5/new_clones/SAS/macrocore' &
git clone https://github.com/jcizel/WRDS-SAS-UTILITIES '/storage/nvme5/new_clones/SAS/WRDS-SAS-UTILITIES' &
git clone https://github.com/sassoftware/ci360-download-client-sas '/storage/nvme5/new_clones/SAS/ci360-download-client-sas' &
git clone https://github.com/eleanormurray/CausalSurvivalAnalysis '/storage/nvme5/new_clones/SAS/CausalSurvivalAnalysis' &
git clone https://github.com/frgrisk/SASPerformanceAnalytics '/storage/nvme5/new_clones/SAS/SASPerformanceAnalytics' &
git clone https://github.com/sassoftware/enlighten-deep '/storage/nvme5/new_clones/SAS/enlighten-deep' &
git clone https://github.com/SASJedi/sas-macros '/storage/nvme5/new_clones/SAS/sas-macros' &
git clone https://github.com/chris-swenson/sasmacros '/storage/nvme5/new_clones/SAS/sasmacros' &
git clone https://github.com/leptonyu/coco '/storage/nvme5/new_clones/SAS/coco' &
git clone https://github.com/lwjohnst86/sasToolkit '/storage/nvme5/new_clones/SAS/sasToolkit' &
git clone https://github.com/Feng-CityUHK/EquityCharacteristicsSAS '/storage/nvme5/new_clones/SAS/EquityCharacteristicsSAS' &
git clone https://github.com/statmike/SAS-Mini-Projects '/storage/nvme5/new_clones/SAS/SAS-Mini-Projects' &
git clone https://github.com/czi-finance/wrds_sample_code '/storage/nvme5/new_clones/SAS/wrds_sample_code' &
git clone https://github.com/KatjaGlassConsulting/SMILE-SmartSASMacros '/storage/nvme5/new_clones/SAS/SMILE-SmartSASMacros' &
git clone https://github.com/allanbowe/BizarroBall '/storage/nvme5/new_clones/SAS/BizarroBall' &
git clone https://github.com/RhoInc/sas-codebook '/storage/nvme5/new_clones/SAS/sas-codebook' &
git clone https://github.com/attilabalogh/012-Matching '/storage/nvme5/new_clones/SAS/012-Matching' &
git clone https://github.com/rogerjdeangelis/utl-end-to-end-cdisc-SDTM-ADaM-processing '/storage/nvme5/new_clones/SAS/utl-end-to-end-cdisc-SDTM-ADaM-processing' &
git clone https://github.com/CDCgov/EPHTracking '/storage/nvme5/new_clones/SAS/EPHTracking' &
git clone https://github.com/gloosace/sasGlue '/storage/nvme5/new_clones/SAS/sasGlue' &
git clone https://github.com/sasjs/react-seed-app '/storage/nvme5/new_clones/SAS/react-seed-app' &
git clone https://github.com/jocoder22/SasClinical '/storage/nvme5/new_clones/SAS/SasClinical' &
git clone https://github.com/xxxspy/TimeSeriesAnalysisPractice '/storage/nvme5/new_clones/SAS/TimeSeriesAnalysisPractice' &
git clone https://github.com/eleanormurray/DiD_Tutorial '/storage/nvme5/new_clones/SAS/DiD_Tutorial' &
git clone https://github.com/JoostImpink/fama-french-industry '/storage/nvme5/new_clones/SAS/fama-french-industry' &
git clone https://github.com/sascommunities/sas-microsoft-graph-api '/storage/nvme5/new_clones/SAS/sas-microsoft-graph-api' &
git clone https://github.com/Gearhj/End-to-End-Data-Science '/storage/nvme5/new_clones/SAS/End-to-End-Data-Science' &
git clone https://github.com/RhoInc/sas-sankeybarchart '/storage/nvme5/new_clones/SAS/sas-sankeybarchart' &
git clone https://github.com/Emory-Yuan/BBISR-SAS-Macros '/storage/nvme5/new_clones/SAS/BBISR-SAS-Macros' &
git clone https://github.com/plpxsk/utility-sas-macros '/storage/nvme5/new_clones/SAS/utility-sas-macros' &
git clone https://github.com/sassoftware/ci360-cdm-loader-sas '/storage/nvme5/new_clones/SAS/ci360-cdm-loader-sas' &
git clone https://github.com/zhuangyh/SAS-Demographic-Table '/storage/nvme5/new_clones/SAS/SAS-Demographic-Table' &
git clone https://github.com/PCORnet-DRN-OC/PCORnet-Data-Curation '/storage/nvme5/new_clones/SAS/PCORnet-Data-Curation' &
git clone https://github.com/myankshah/SAS_Credit_Scoring_Model_using_LogisticRegression '/storage/nvme5/new_clones/SAS/SAS_Credit_Scoring_Model_using_LogisticRegression' &
git clone https://github.com/SASPAC/baseplus '/storage/nvme5/new_clones/SAS/baseplus' &
git clone https://github.com/RMPDC-BDM/SAS2REDCap '/storage/nvme5/new_clones/SAS/SAS2REDCap' &
git clone https://github.com/AMPATH/etl '/storage/nvme5/new_clones/SAS/etl' &
git clone https://github.com/NicoDupont/Resources '/storage/nvme5/new_clones/SAS/Resources' &
git clone https://github.com/caesarmario/heart-disease-prediction-with-logistic-regression-SAS-studio '/storage/nvme5/new_clones/SAS/heart-disease-prediction-with-logistic-regression-SAS-studio' &
git clone https://github.com/jmangori/CDISC-SDTM-deidentify-SAS-phuse '/storage/nvme5/new_clones/SAS/CDISC-SDTM-deidentify-SAS-phuse' &
git clone https://github.com/sashub/macro '/storage/nvme5/new_clones/SAS/macro' &
git clone https://github.com/sasjs/viyatoken '/storage/nvme5/new_clones/SAS/viyatoken' &
git clone https://github.com/77QingLiu/SAS-Program-Library '/storage/nvme5/new_clones/SAS/SAS-Program-Library' &
git clone https://github.com/sasjs/sasjs.io '/storage/nvme5/new_clones/SAS/sasjs.io' &
git clone https://github.com/Apress/practical-business-analytics-using-sas '/storage/nvme5/new_clones/SAS/practical-business-analytics-using-sas' &
git clone https://github.com/austingriffith94/distance_to_default '/storage/nvme5/new_clones/SAS/distance_to_default' &
git clone https://github.com/nicklip/Regression_SAS_code '/storage/nvme5/new_clones/SAS/Regression_SAS_code' &
git clone https://github.com/clindocu/sas-r '/storage/nvme5/new_clones/SAS/sas-r' &
git clone https://github.com/srosanba/sas-sdtm-simulator '/storage/nvme5/new_clones/SAS/sas-sdtm-simulator' &
git clone https://github.com/greg-wootton/sas-programs '/storage/nvme5/new_clones/SAS/sas-programs' &
git clone https://github.com/sasjs/minimal-seed-app '/storage/nvme5/new_clones/SAS/minimal-seed-app' &
git clone https://github.com/jburke5/pyhcup '/storage/nvme5/new_clones/SAS/pyhcup' &
git clone https://github.com/OrysyaStus/UCSD_Data_Mining_Certificate '/storage/nvme5/new_clones/SAS/UCSD_Data_Mining_Certificate' &
git clone https://github.com/CAPITAmodel/CAPITA '/storage/nvme5/new_clones/SAS/CAPITA' &
git clone https://github.com/RhoInc/sas-sgplot '/storage/nvme5/new_clones/SAS/sas-sgplot' &
git clone https://github.com/CityOfNewYork/communicable-disease-surveillance-nycdohmh '/storage/nvme5/new_clones/SAS/communicable-disease-surveillance-nycdohmh' &
git clone https://github.com/susanmhutfless/Overuse-Index-Segal-et-al-Johns-Hopkins-University-ICD-10-Coding '/storage/nvme5/new_clones/SAS/Overuse-Index-Segal-et-al-Johns-Hopkins-University-ICD-10-Coding' &
git clone https://github.com/77QingLiu/AutoGenaCRF '/storage/nvme5/new_clones/SAS/AutoGenaCRF' &
git clone https://github.com/huangxianyang/Customer_positioning_analysis '/storage/nvme5/new_clones/SAS/Customer_positioning_analysis' &
git clone https://github.com/cdfq384903/MonotonicOptimalBinning '/storage/nvme5/new_clones/SAS/MonotonicOptimalBinning' &
git clone https://github.com/RhoInc/sas-beeswarm '/storage/nvme5/new_clones/SAS/sas-beeswarm' &
git clone https://github.com/gerhard1050/Data-Quality-for-Data-Science-Using-SAS '/storage/nvme5/new_clones/SAS/Data-Quality-for-Data-Science-Using-SAS' &
git clone https://github.com/wwwscopin/SAS '/storage/nvme5/new_clones/SAS/SAS' &
git clone https://github.com/keguoh/LittleSAS '/storage/nvme5/new_clones/SAS/LittleSAS' &
git clone https://github.com/USCSchaefferCenterDataCore/Chronic-Conditions-Package '/storage/nvme5/new_clones/SAS/Chronic-Conditions-Package' &
git clone https://github.com/eleanormurray/ABMs-for-causal-inference '/storage/nvme5/new_clones/SAS/ABMs-for-causal-inference' &
git clone https://github.com/CMSgov/T-MSIS-Analytic-File-Generation-Code '/storage/nvme5/new_clones/SAS/T-MSIS-Analytic-File-Generation-Code' &
git clone https://github.com/HHS-AHRQ/MEPS-summary-tables-archive '/storage/nvme5/new_clones/SAS/MEPS-summary-tables-archive' &
git clone https://github.com/sassoftware/converting-sas-code-to-leverage-cas '/storage/nvme5/new_clones/SAS/converting-sas-code-to-leverage-cas' &
git clone https://github.com/ReneNyffenegger/about-SAS '/storage/nvme5/new_clones/SAS/about-SAS' &
git clone https://github.com/cwickham/nass '/storage/nvme5/new_clones/SAS/nass' &
git clone https://github.com/ASHISH9438/Little-SAS-Book-Exercises-And-Projects '/storage/nvme5/new_clones/SAS/Little-SAS-Book-Exercises-And-Projects' &
git clone https://github.com/LHSNet/PCORNet-CDM '/storage/nvme5/new_clones/SAS/PCORNet-CDM' &
git clone https://github.com/nirx/devfOLD '/storage/nvme5/new_clones/SAS/devfOLD' &
git clone https://github.com/heike/data-technologies '/storage/nvme5/new_clones/SAS/data-technologies' &
git clone https://github.com/philipmason/Wood-Street-Consultants '/storage/nvme5/new_clones/SAS/Wood-Street-Consultants' &
git clone https://github.com/RhoInc/sas-violinPlot '/storage/nvme5/new_clones/SAS/sas-violinPlot' &
git clone https://github.com/sassoftware/sas-viya-forecasting '/storage/nvme5/new_clones/SAS/sas-viya-forecasting' &
git clone https://github.com/wgetsnaps/ftp.nhtsa.dot.gov--fars '/storage/nvme5/new_clones/SAS/ftp.nhtsa.dot.gov--fars' &
git clone https://github.com/data-sciences/sas-demo '/storage/nvme5/new_clones/SAS/sas-demo' &
git clone https://github.com/BerkeleyBiostats/SuperLearner-SAS '/storage/nvme5/new_clones/SAS/SuperLearner-SAS' &
git clone https://github.com/SASPAC/macroarray '/storage/nvme5/new_clones/SAS/macroarray' &
git clone https://github.com/taskography/pddlgym '/storage/nvme5/new_clones/SAS/pddlgym' &
git clone https://github.com/akashagte/SAS-Targeted-Marketing-Model '/storage/nvme5/new_clones/SAS/SAS-Targeted-Marketing-Model' &
git clone https://github.com/DGTresor/Saphir '/storage/nvme5/new_clones/SAS/Saphir' &
git clone https://github.com/amitmse/in_SAS_ '/storage/nvme5/new_clones/SAS/in_SAS_' &
git clone https://github.com/CUNYSPHCode/IntroSAS '/storage/nvme5/new_clones/SAS/IntroSAS' &
git clone https://github.com/Treasury-Analytics-and-Insights/Insights-Tool '/storage/nvme5/new_clones/SAS/Insights-Tool' &
git clone https://github.com/caiomsouza/kaggle-competitions '/storage/nvme5/new_clones/SAS/kaggle-competitions' &
git clone https://github.com/sasjs/fileuploader '/storage/nvme5/new_clones/SAS/fileuploader' &
git clone https://github.com/auserj/Advanced_Programming_for_SAS '/storage/nvme5/new_clones/SAS/Advanced_Programming_for_SAS' &
git clone https://github.com/ncsumaize/Heritability_SAS '/storage/nvme5/new_clones/SAS/Heritability_SAS' &
git clone https://github.com/powerepilab/AD_Algorithm_Development '/storage/nvme5/new_clones/SAS/AD_Algorithm_Development' &
git clone https://github.com/ainaimi/gMethods_Intro '/storage/nvme5/new_clones/SAS/gMethods_Intro' &
git clone https://github.com/openefsa/sas-stored-functions-and-macros '/storage/nvme5/new_clones/SAS/sas-stored-functions-and-macros' &
git clone https://github.com/alura-cursos/sas-parte1 '/storage/nvme5/new_clones/SAS/sas-parte1' &
git clone https://github.com/sassoftware/gentle-intro-stats-using-sas-studio '/storage/nvme5/new_clones/SAS/gentle-intro-stats-using-sas-studio' &
git clone https://github.com/MHResearchNetwork/MHRN-Central '/storage/nvme5/new_clones/SAS/MHRN-Central' &
git clone https://github.com/achoczaj/CPD--SAS--Macro_Language_1_Essentials '/storage/nvme5/new_clones/SAS/CPD--SAS--Macro_Language_1_Essentials' &
git clone https://github.com/UNC-EPID-722/2016 '/storage/nvme5/new_clones/SAS/2016' &
git clone https://github.com/sasjs/viya-log-parser '/storage/nvme5/new_clones/SAS/viya-log-parser' &
git clone https://github.com/Hongclass/ITMD529 '/storage/nvme5/new_clones/SAS/ITMD529' &
git clone https://github.com/kiranvenna/Youtubeproblems_code '/storage/nvme5/new_clones/SAS/Youtubeproblems_code' &
git clone https://github.com/cjdinger/source_control_with_saseg '/storage/nvme5/new_clones/SAS/source_control_with_saseg' &
git clone https://github.com/nareshv00/Survival-Analysis-for-Predicting-Employee-Turnover '/storage/nvme5/new_clones/SAS/Survival-Analysis-for-Predicting-Employee-Turnover' &
git clone https://github.com/thomas-rasmussen/sas_macros '/storage/nvme5/new_clones/SAS/sas_macros' &
git clone https://github.com/outcomesinsights/seer_to_omop_cdmv4 '/storage/nvme5/new_clones/SAS/seer_to_omop_cdmv4' &
git clone https://github.com/sassoftware/ci360-sas-tools '/storage/nvme5/new_clones/SAS/ci360-sas-tools' &
git clone https://github.com/deepanshu88/Datasets '/storage/nvme5/new_clones/SAS/Datasets' &
git clone https://github.com/sascommunities/graphics-programming '/storage/nvme5/new_clones/SAS/graphics-programming' &
git clone https://github.com/nsrr/shhs-data-dictionary '/storage/nvme5/new_clones/SAS/shhs-data-dictionary' &
git clone https://github.com/eurostat/dff '/storage/nvme5/new_clones/SAS/dff' &
git clone https://github.com/science-of-imagination/conan-procedural-quest-generation '/storage/nvme5/new_clones/SAS/conan-procedural-quest-generation' &
git clone https://github.com/PCORnet-DRN-OC/Medicare-Data-Transformation '/storage/nvme5/new_clones/SAS/Medicare-Data-Transformation' &
git clone https://github.com/harshbg/Shaving-Blades-Analysis '/storage/nvme5/new_clones/SAS/Shaving-Blades-Analysis' &
git clone https://github.com/gerhard1050/Data-Preparation-for-Data-Science-Using-SAS '/storage/nvme5/new_clones/SAS/Data-Preparation-for-Data-Science-Using-SAS' &
git clone https://github.com/sassoftware/restaf-demos '/storage/nvme5/new_clones/SAS/restaf-demos' &
git clone https://github.com/sassoftware/sas-project-change-manager '/storage/nvme5/new_clones/SAS/sas-project-change-manager' &
git clone https://github.com/sascommunities/sas-users-blog '/storage/nvme5/new_clones/SAS/sas-users-blog' &
