#!/bin/bash

git clone https://github.com/readthedocs/sphinx_rtd_theme '/storage/nvme5/new_clones/Sass/sphinx_rtd_theme' &
git clone https://github.com/pradyunsg/furo '/storage/nvme5/new_clones/Sass/furo' &
git clone https://github.com/Weilbyte/PVEDiscordDark '/storage/nvme5/new_clones/Sass/PVEDiscordDark' &
git clone https://github.com/flickowoa/dotfiles '/storage/nvme5/new_clones/Sass/dotfiles' &
git clone https://github.com/dotfiles/dotfiles.github.com '/storage/nvme5/new_clones/Sass/dotfileshub.com' &
git clone https://github.com/NervanaSystems/maxas '/storage/nvme5/new_clones/Sass/maxas' &
git clone https://github.com/jgthms/wysiwyg.css '/storage/nvme5/new_clones/Sass/wysiwyg.css' &
git clone https://github.com/agragregra/start_html '/storage/nvme5/new_clones/Sass/start_html' &
git clone https://github.com/deps-rs/deps.rs '/storage/nvme5/new_clones/Sass/deps.rs' &
git clone https://github.com/SoftwareBrothers/active_skin '/storage/nvme5/new_clones/Sass/active_skin' &
git clone https://github.com/MorganCaron/IsometricSass '/storage/nvme5/new_clones/Sass/IsometricSass' &
git clone https://github.com/George-debug/obsidian-timeline '/storage/nvme5/new_clones/Sass/obsidian-timeline' &
git clone https://github.com/onweru/newsroom '/storage/nvme5/new_clones/Sass/newsroom' &
git clone https://github.com/OliverBrotchie/CSS-Fingerprint '/storage/nvme5/new_clones/Sass/CSS-Fingerprint' &
git clone https://github.com/nandomoreirame/end2end '/storage/nvme5/new_clones/Sass/end2end' &
git clone https://github.com/ircdocs/modern-irc '/storage/nvme5/new_clones/Sass/modern-irc' &
git clone https://github.com/RatanShreshtha/DeepThought '/storage/nvme5/new_clones/Sass/DeepThought' &
git clone https://github.com/Beg-in/frow '/storage/nvme5/new_clones/Sass/frow' &
git clone https://github.com/bookcasey/harsh '/storage/nvme5/new_clones/Sass/harsh' &
git clone https://github.com/johnbeatty/hnpwa-app '/storage/nvme5/new_clones/Sass/hnpwa-app' &
git clone https://github.com/luanti-org/luanti-org.github.io '/storage/nvme5/new_clones/Sass/luanti-orghub.io' &
git clone https://github.com/datocms/gatsby-portfolio '/storage/nvme5/new_clones/Sass/gatsby-portfolio' &
git clone https://github.com/JupiterBroadcasting/jupiterbroadcasting.com '/storage/nvme5/new_clones/Sass/jupiterbroadcasting.com' &
git clone https://github.com/lucperkins/bulma-dashboard '/storage/nvme5/new_clones/Sass/bulma-dashboard' &
git clone https://github.com/oVirt/ovirt-site '/storage/nvme5/new_clones/Sass/ovirt-site' &
git clone https://github.com/CreativeBulma/bulma-tooltip '/storage/nvme5/new_clones/Sass/bulma-tooltip' &
git clone https://github.com/Wikiki/bulma-checkradio '/storage/nvme5/new_clones/Sass/bulma-checkradio' &
git clone https://github.com/snide/wyrm '/storage/nvme5/new_clones/Sass/wyrm' &
git clone https://github.com/grin3671/shiki-theme '/storage/nvme5/new_clones/Sass/shiki-theme' &
git clone https://github.com/sbstjn/68Keys.io '/storage/nvme5/new_clones/Sass/68Keys.io' &
git clone https://github.com/g1eny0ung/logseq-github-theme '/storage/nvme5/new_clones/Sass/logseq-github-theme' &
git clone https://github.com/doximity/vital '/storage/nvme5/new_clones/Sass/vital' &
git clone https://github.com/GameBoy/gameboy.github.io '/storage/nvme5/new_clones/Sass/gameboyhub.io' &
git clone https://github.com/mds/good-button '/storage/nvme5/new_clones/Sass/good-button' &
git clone https://github.com/Wikiki/bulma-pricingtable '/storage/nvme5/new_clones/Sass/bulma-pricingtable' &
git clone https://github.com/aaronpk/Monocle '/storage/nvme5/new_clones/Sass/Monocle' &
git clone https://github.com/mubaidr/bulma-addons '/storage/nvme5/new_clones/Sass/bulma-addons' &
git clone https://github.com/Ableton/ableton.github.io '/storage/nvme5/new_clones/Sass/abletonhub.io' &
git clone https://github.com/gnehs/ChatUI '/storage/nvme5/new_clones/Sass/ChatUI' &
git clone https://github.com/747/vsselector '/storage/nvme5/new_clones/Sass/vsselector' &
git clone https://github.com/koddr/just-scroll '/storage/nvme5/new_clones/Sass/just-scroll' &
git clone https://github.com/andrey-kudinov/page '/storage/nvme5/new_clones/Sass/page' &
git clone https://github.com/roydukkey/sass-fairy '/storage/nvme5/new_clones/Sass/sass-fairy' &
git clone https://github.com/Biings/biings-ds '/storage/nvme5/new_clones/Sass/biings-ds' &
git clone https://github.com/ThatTonybo/Revolt-Discord-Theme '/storage/nvme5/new_clones/Sass/Revolt-Discord-Theme' &
git clone https://github.com/qgis/QGIS-Website '/storage/nvme5/new_clones/Sass/QGIS-Website' &
git clone https://github.com/azemoh/vscode-onedark '/storage/nvme5/new_clones/Sass/vscode-onedark' &
git clone https://github.com/raw-coding-youtube/intermediate-shop-aspnetcore2 '/storage/nvme5/new_clones/Sass/intermediate-shop-aspnetcore2' &
git clone https://github.com/kata-containers/www.katacontainers.io '/storage/nvme5/new_clones/Sass/www.katacontainers.io' &
git clone https://github.com/jkelin/TribesRevengeance '/storage/nvme5/new_clones/Sass/TribesRevengeance' &
git clone https://github.com/Yoonit-Labs/sass-yoonit-style '/storage/nvme5/new_clones/Sass/sass-yoonit-style' &
git clone https://github.com/ngseke/leetcode-night '/storage/nvme5/new_clones/Sass/leetcode-night' &
git clone https://github.com/heroku/boomerang '/storage/nvme5/new_clones/Sass/boomerang' &
git clone https://github.com/eezeepeezee/lemoneezee '/storage/nvme5/new_clones/Sass/lemoneezee' &
git clone https://github.com/rjaros/kvision-io '/storage/nvme5/new_clones/Sass/kvision-io' &
git clone https://github.com/byuweb/byu-theme-components '/storage/nvme5/new_clones/Sass/byu-theme-components' &
git clone https://github.com/oam-dev/oam-dev.github.io '/storage/nvme5/new_clones/Sass/oam-devhub.io' &
git clone https://github.com/JieRen98/SGEMM-SASS-Annotation '/storage/nvme5/new_clones/Sass/SGEMM-SASS-Annotation' &
git clone https://github.com/algomaster99/portfolio '/storage/nvme5/new_clones/Sass/portfolio' &
git clone https://github.com/esaio/inuicon-rails '/storage/nvme5/new_clones/Sass/inuicon-rails' &
git clone https://github.com/priit/rubyee '/storage/nvme5/new_clones/Sass/rubyee' &
git clone https://github.com/luanti-org/blog '/storage/nvme5/new_clones/Sass/blog' &
git clone https://github.com/hrsetyono/wp-vue-boilerplate '/storage/nvme5/new_clones/Sass/wp-vue-boilerplate' &
git clone https://github.com/amandamcg/joplin-new-theme-sandbox '/storage/nvme5/new_clones/Sass/joplin-new-theme-sandbox' &
git clone https://github.com/codeship/shipyard '/storage/nvme5/new_clones/Sass/shipyard' &
git clone https://github.com/mitmproxy/www '/storage/nvme5/new_clones/Sass/www' &
git clone https://github.com/Skaytacium/Gruvify '/storage/nvme5/new_clones/Sass/Gruvify' &
git clone https://github.com/ibab/babushk.in '/storage/nvme5/new_clones/Sass/babushk.in' &
git clone https://github.com/michaelfiber/family-media-lan '/storage/nvme5/new_clones/Sass/family-media-lan' &
git clone https://github.com/Tagirijus/MantisBTDarkTheme '/storage/nvme5/new_clones/Sass/MantisBTDarkTheme' &
git clone https://github.com/pythonbrasil/pybr2019-site '/storage/nvme5/new_clones/Sass/pybr2019-site' &
git clone https://github.com/nadiannis/cova '/storage/nvme5/new_clones/Sass/cova' &
git clone https://github.com/shizuku2005/gulp-pug-sass '/storage/nvme5/new_clones/Sass/gulp-pug-sass' &
git clone https://github.com/dexidp/website '/storage/nvme5/new_clones/Sass/website' &
git clone https://github.com/RimoChan/my_2dkf_css '/storage/nvme5/new_clones/Sass/my_2dkf_css' &
git clone https://github.com/friktor/figma-complex-themes '/storage/nvme5/new_clones/Sass/figma-complex-themes' &
git clone https://github.com/yowainwright/sassimple '/storage/nvme5/new_clones/Sass/sassimple' &
git clone https://github.com/mopidy/website '/storage/nvme5/new_clones/Sass/website' &
git clone https://github.com/StarlingXWeb/starlingx-website '/storage/nvme5/new_clones/Sass/starlingx-website' &
git clone https://github.com/dracula/fb-messenger '/storage/nvme5/new_clones/Sass/fb-messenger' &
git clone https://github.com/edemaine/hardness-book-site '/storage/nvme5/new_clones/Sass/hardness-book-site' &
git clone https://github.com/dotmpe/ok-lcars-sdk '/storage/nvme5/new_clones/Sass/ok-lcars-sdk' &
git clone https://github.com/t18n/react-typescript-boilerplate '/storage/nvme5/new_clones/Sass/react-typescript-boilerplate' &
git clone https://github.com/pxlrbt/cobalt2-jetbrains '/storage/nvme5/new_clones/Sass/cobalt2-jetbrains' &
git clone https://github.com/karakun/karakun.github.io '/storage/nvme5/new_clones/Sass/karakunhub.io' &
git clone https://github.com/ambanum/pariscall.international '/storage/nvme5/new_clones/Sass/pariscall.international' &
git clone https://github.com/neuroimaging-cookbook/neuroimaging-cookbook.github.io '/storage/nvme5/new_clones/Sass/neuroimaging-cookbookhub.io' &
git clone https://github.com/osunyorg/theme '/storage/nvme5/new_clones/Sass/theme' &
git clone https://github.com/BrandApplause/brandapplause.com '/storage/nvme5/new_clones/Sass/brandapplause.com' &
git clone https://github.com/e200/e200.github.io '/storage/nvme5/new_clones/Sass/e200hub.io' &
git clone https://github.com/MurphyAdam/Flask-chatbot '/storage/nvme5/new_clones/Sass/Flask-chatbot' &
git clone https://github.com/deislabs/deislabs.io '/storage/nvme5/new_clones/Sass/deislabs.io' &
git clone https://github.com/osc-delft/osc-delft.github.io '/storage/nvme5/new_clones/Sass/osc-delfthub.io' &
git clone https://github.com/locaweb/locaweb.github.com '/storage/nvme5/new_clones/Sass/locawebhub.com' &
git clone https://github.com/teles/archived-blog '/storage/nvme5/new_clones/Sass/archived-blog' &
git clone https://github.com/rootwork/hugo-module-site '/storage/nvme5/new_clones/Sass/hugo-module-site' &
git clone https://github.com/apache/royale-docs '/storage/nvme5/new_clones/Sass/royale-docs' &
git clone https://github.com/digital-asset/docs.daml.com '/storage/nvme5/new_clones/Sass/docs.daml.com' &
git clone https://github.com/johnhayesio/fendStarterKit '/storage/nvme5/new_clones/Sass/fendStarterKit' &
git clone https://github.com/ruby-amqp/rubybunny.info '/storage/nvme5/new_clones/Sass/rubybunny.info' &
git clone https://github.com/gma/nesta-theme-slate '/storage/nvme5/new_clones/Sass/nesta-theme-slate' &
git clone https://github.com/joeleisner/chassis-css '/storage/nvme5/new_clones/Sass/chassis-css' &
git clone https://github.com/oulu/oulu '/storage/nvme5/new_clones/Sass/oulu' &
git clone https://github.com/krustlet/krustlet.dev '/storage/nvme5/new_clones/Sass/krustlet.dev' &
git clone https://github.com/kubilaycaglayan/portfolio '/storage/nvme5/new_clones/Sass/portfolio' &
git clone https://github.com/sigstore/sigstore.github.io '/storage/nvme5/new_clones/Sass/sigstorehub.io' &
git clone https://github.com/Caixetadev/itachi '/storage/nvme5/new_clones/Sass/itachi' &
git clone https://github.com/karreiro/learn-dmn-in-15-minutes '/storage/nvme5/new_clones/Sass/learn-dmn-in-15-minutes' &
git clone https://github.com/Eridiant/syndicate '/storage/nvme5/new_clones/Sass/syndicate' &
git clone https://github.com/uhnomoli/Palette '/storage/nvme5/new_clones/Sass/Palette' &
git clone https://github.com/FarazzShaikh/blog '/storage/nvme5/new_clones/Sass/blog' &
git clone https://github.com/bananaappletw/bulma-sass '/storage/nvme5/new_clones/Sass/bulma-sass' &
git clone https://github.com/teacodema/template.teacode.ma '/storage/nvme5/new_clones/Sass/template.teacode.ma' &
git clone https://github.com/remino/scrollerful '/storage/nvme5/new_clones/Sass/scrollerful' &
git clone https://github.com/bkeepers/bkeepers.github.io '/storage/nvme5/new_clones/Sass/bkeepershub.io' &
git clone https://github.com/ajitzero/30min-portfolio '/storage/nvme5/new_clones/Sass/30min-portfolio' &
git clone https://github.com/newtheatre/lx '/storage/nvme5/new_clones/Sass/lx' &
git clone https://github.com/artsy/folio.artsy.net '/storage/nvme5/new_clones/Sass/folio.artsy.net' &
git clone https://github.com/scottcharlesworth/bulma-multiselect '/storage/nvme5/new_clones/Sass/bulma-multiselect' &
git clone https://github.com/orlovmax/gulp-workflow '/storage/nvme5/new_clones/Sass/gulp-workflow' &
git clone https://github.com/binsec/binsec.github.io '/storage/nvme5/new_clones/Sass/binsechub.io' &
git clone https://github.com/olivierlacan/olivierlacan.com '/storage/nvme5/new_clones/Sass/olivierlacan.com' &
git clone https://github.com/versosdomundo/livro '/storage/nvme5/new_clones/Sass/livro' &
git clone https://github.com/crybapp/borealis '/storage/nvme5/new_clones/Sass/borealis' &
git clone https://github.com/DHS-SVIP/digital-wallet-ui '/storage/nvme5/new_clones/Sass/digital-wallet-ui' &
git clone https://github.com/QueerCodeOrg/queercodeberlin.github.io '/storage/nvme5/new_clones/Sass/queercodeberlinhub.io' &
git clone https://github.com/OpenSLO/openslo.github.io '/storage/nvme5/new_clones/Sass/openslohub.io' &
git clone https://github.com/okcashpro/okcash.info.website '/storage/nvme5/new_clones/Sass/okcash.info.website' &
git clone https://github.com/yusufisbilir/Dice-Rolling-Game '/storage/nvme5/new_clones/Sass/Dice-Rolling-Game' &
