#!/bin/bash

git clone https://github.com/scilab/scilab '/storage/nvme5/new_clones/Scilab/scilab' &
git clone https://github.com/opencollab/scilab '/storage/nvme5/new_clones/Scilab/scilab' &
git clone https://github.com/cmoylan/Elements-of-Computing-Systems '/storage/nvme5/new_clones/Scilab/Elements-of-Computing-Systems' &
git clone https://github.com/mc36/freeRtr '/storage/nvme5/new_clones/Scilab/freeRtr' &
git clone https://github.com/predict-idlab/GENESIM '/storage/nvme5/new_clones/Scilab/GENESIM' &
git clone https://github.com/daad-adventure-writer/daad '/storage/nvme5/new_clones/Scilab/daad' &
git clone https://github.com/ScilabOrg/scilab '/storage/nvme5/new_clones/Scilab/scilab' &
git clone https://github.com/hrbrmstr/iptools '/storage/nvme5/new_clones/Scilab/iptools' &
git clone https://github.com/parasoft/parabank '/storage/nvme5/new_clones/Scilab/parabank' &
git clone https://github.com/declaresub/abnf '/storage/nvme5/new_clones/Scilab/abnf' &
git clone https://github.com/mitre/oldcpsa '/storage/nvme5/new_clones/Scilab/oldcpsa' &
git clone https://github.com/sydney-machine-learning/GANclassimbalanced '/storage/nvme5/new_clones/Scilab/GANclassimbalanced' &
git clone https://github.com/mikeizbicki/datasets '/storage/nvme5/new_clones/Scilab/datasets' &
git clone https://github.com/openwall/john-tests '/storage/nvme5/new_clones/Scilab/john-tests' &
git clone https://github.com/sigmorphon/2021Task0 '/storage/nvme5/new_clones/Scilab/2021Task0' &
git clone https://github.com/abarthakur/trepan_python '/storage/nvme5/new_clones/Scilab/trepan_python' &
git clone https://github.com/IAIK/flecc_in_c '/storage/nvme5/new_clones/Scilab/flecc_in_c' &
git clone https://github.com/openstack-attic/akanda '/storage/nvme5/new_clones/Scilab/akanda' &
git clone https://github.com/fsandre/mcflight '/storage/nvme5/new_clones/Scilab/mcflight' &
git clone https://github.com/REFRAME/betacal '/storage/nvme5/new_clones/Scilab/betacal' &
git clone https://github.com/mitre/cpsa '/storage/nvme5/new_clones/Scilab/cpsa' &
git clone https://github.com/aditeyabaral/Linear-Algebra-Scilab-Assignment-UE18MA251 '/storage/nvme5/new_clones/Scilab/Linear-Algebra-Scilab-Assignment-UE18MA251' &
git clone https://github.com/arauhala/libreexp '/storage/nvme5/new_clones/Scilab/libreexp' &
git clone https://github.com/darius/logsim '/storage/nvme5/new_clones/Scilab/logsim' &
git clone https://github.com/cccnqu/co106a '/storage/nvme5/new_clones/Scilab/co106a' &
git clone https://github.com/tanchinluh/arduino '/storage/nvme5/new_clones/Scilab/arduino' &
git clone https://github.com/attaoveisi/Hybrid_Fuzzy_Kalman_Filter '/storage/nvme5/new_clones/Scilab/Hybrid_Fuzzy_Kalman_Filter' &
git clone https://github.com/begoon/acm '/storage/nvme5/new_clones/Scilab/acm' &
git clone https://github.com/holgern/sciflt '/storage/nvme5/new_clones/Scilab/sciflt' &
git clone https://github.com/VitorgsRuffo/Building-The-Hack-Computer '/storage/nvme5/new_clones/Scilab/Building-The-Hack-Computer' &
git clone https://github.com/ulfsri/fsri_materials_database '/storage/nvme5/new_clones/Scilab/fsri_materials_database' &
git clone https://github.com/albertz/PyOverheadGame '/storage/nvme5/new_clones/Scilab/PyOverheadGame' &
git clone https://github.com/akmcc/nand-2-tetris '/storage/nvme5/new_clones/Scilab/nand-2-tetris' &
git clone https://github.com/aidanematzadeh/word_learning '/storage/nvme5/new_clones/Scilab/word_learning' &
git clone https://github.com/verdverm/go-pge '/storage/nvme5/new_clones/Scilab/go-pge' &
git clone https://github.com/whostolebenfrog/The-Elements-of-Computing-Systems '/storage/nvme5/new_clones/Scilab/The-Elements-of-Computing-Systems' &
git clone https://github.com/saketkc/scilab_cloud '/storage/nvme5/new_clones/Scilab/scilab_cloud' &
git clone https://github.com/cccnqu/co107a '/storage/nvme5/new_clones/Scilab/co107a' &
git clone https://github.com/idnavid/supervised_ivectors '/storage/nvme5/new_clones/Scilab/supervised_ivectors' &
git clone https://github.com/hugulas/R-Decision-Tree-Examples '/storage/nvme5/new_clones/Scilab/R-Decision-Tree-Examples' &
git clone https://github.com/sengupta/scilab-maxima '/storage/nvme5/new_clones/Scilab/scilab-maxima' &
git clone https://github.com/beniroquai/SIM-Scilab '/storage/nvme5/new_clones/Scilab/SIM-Scilab' &
git clone https://github.com/ccccourse1/co110a '/storage/nvme5/new_clones/Scilab/co110a' &
git clone https://github.com/rdbyk/balisc '/storage/nvme5/new_clones/Scilab/balisc' &
git clone https://github.com/johnsimcall/storage-install '/storage/nvme5/new_clones/Scilab/storage-install' &
git clone https://github.com/ajahuang/papers '/storage/nvme5/new_clones/Scilab/papers' &
git clone https://github.com/jd-rk9/OpenDJ '/storage/nvme5/new_clones/Scilab/OpenDJ' &
git clone https://github.com/Armando1514/From-Nand-To-Tetris-Build-A-Modern-Computer '/storage/nvme5/new_clones/Scilab/From-Nand-To-Tetris-Build-A-Modern-Computer' &
git clone https://github.com/AdaskoTheBeAsT/NetCoreTypewriterRecipes '/storage/nvme5/new_clones/Scilab/NetCoreTypewriterRecipes' &
