#!/bin/bash

git clone https://github.com/phhusson/treble_experimentations '/storage/nvme5/new_clones/Smali/treble_experimentations' &
git clone https://github.com/XploitWizer-Community/XploitSPY '/storage/nvme5/new_clones/Smali/XploitSPY' &
git clone https://github.com/ScRiPt1337/Teardroid-phprat '/storage/nvme5/new_clones/Smali/Teardroid-phprat' &
git clone https://github.com/HelloHuDi/AndroidReverseNotes '/storage/nvme5/new_clones/Smali/AndroidReverseNotes' &
git clone https://github.com/vtosters/lite '/storage/nvme5/new_clones/Smali/lite' &
git clone https://github.com/AlexeySoshin/smali2java '/storage/nvme5/new_clones/Smali/smali2java' &
git clone https://github.com/efxtv/L3MON '/storage/nvme5/new_clones/Smali/L3MON' &
git clone https://github.com/Bin4ry/deejayeye-modder '/storage/nvme5/new_clones/Smali/deejayeye-modder' &
git clone https://github.com/Lyana-nullptr/android-killer '/storage/nvme5/new_clones/Smali/android-killer' &
git clone https://github.com/xxxyanchenxxx/SigKill '/storage/nvme5/new_clones/Smali/SigKill' &
git clone https://github.com/reverseengineeringer/com.tencent.mm '/storage/nvme5/new_clones/Smali/com.tencent.mm' &
git clone https://github.com/QuinnWilton/sublime-smali '/storage/nvme5/new_clones/Smali/sublime-smali' &
git clone https://github.com/fourbrother/java2smali '/storage/nvme5/new_clones/Smali/java2smali' &
git clone https://github.com/h4ck3r0/Lemon-termux '/storage/nvme5/new_clones/Smali/Lemon-termux' &
git clone https://github.com/plum-umd/redexer '/storage/nvme5/new_clones/Smali/redexer' &
git clone https://github.com/pillfill/hiding-passwords-android '/storage/nvme5/new_clones/Smali/hiding-passwords-android' &
git clone https://github.com/CyberCraftsmanx/-D3VL-L3MON '/storage/nvme5/new_clones/Smali/-D3VL-L3MON' &
git clone https://github.com/Pericena/Droidjack '/storage/nvme5/new_clones/Smali/Droidjack' &
git clone https://github.com/hktkqwe123/All-Hacking-Tools '/storage/nvme5/new_clones/Smali/All-Hacking-Tools' &
git clone https://github.com/Linuxndroid/DroidSpy '/storage/nvme5/new_clones/Smali/DroidSpy' &
git clone https://github.com/YunLambert/TravelFrog_Tool '/storage/nvme5/new_clones/Smali/TravelFrog_Tool' &
git clone https://github.com/mstfknn/rat-collection '/storage/nvme5/new_clones/Smali/rat-collection' &
git clone https://github.com/BurgerZ/jBART '/storage/nvme5/new_clones/Smali/jBART' &
git clone https://github.com/langgithub/RXjadx '/storage/nvme5/new_clones/Smali/RXjadx' &
git clone https://github.com/qinlili23333/KiyomiPDF '/storage/nvme5/new_clones/Smali/KiyomiPDF' &
git clone https://github.com/lulululbj/android-reverse '/storage/nvme5/new_clones/Smali/android-reverse' &
git clone https://github.com/Piyush-Banik/H4CKINTO '/storage/nvme5/new_clones/Smali/H4CKINTO' &
git clone https://github.com/xdek42/AutoReinforce '/storage/nvme5/new_clones/Smali/AutoReinforce' &
git clone https://github.com/freedom-wy/reverse_android '/storage/nvme5/new_clones/Smali/reverse_android' &
git clone https://github.com/AyraHikari/MotorolaAppsPorts '/storage/nvme5/new_clones/Smali/MotorolaAppsPorts' &
git clone https://github.com/amirzaidi/gcam '/storage/nvme5/new_clones/Smali/gcam' &
git clone https://github.com/akbarri/ExaGear-SU '/storage/nvme5/new_clones/Smali/ExaGear-SU' &
git clone https://github.com/Mi-Walkie-Talkie-by-Darkhorse/Mi-Walkie-Talkie-Plus '/storage/nvme5/new_clones/Smali/Mi-Walkie-Talkie-Plus' &
git clone https://github.com/ScRiPt1337/ATANK '/storage/nvme5/new_clones/Smali/ATANK' &
git clone https://github.com/Bhaviktutorials/BloodyRat '/storage/nvme5/new_clones/Smali/BloodyRat' &
git clone https://github.com/popeye0013/Exploit '/storage/nvme5/new_clones/Smali/Exploit' &
git clone https://github.com/MatthewBooth/JFLTE-GPE '/storage/nvme5/new_clones/Smali/JFLTE-GPE' &
git clone https://github.com/MiCode/patchrom_android '/storage/nvme5/new_clones/Smali/patchrom_android' &
git clone https://github.com/szpaku80/Libre2-patched-App '/storage/nvme5/new_clones/Smali/Libre2-patched-App' &
git clone https://github.com/rewhy/happer '/storage/nvme5/new_clones/Smali/happer' &
git clone https://github.com/mouyase/PivisionM-Smali '/storage/nvme5/new_clones/Smali/PivisionM-Smali' &
git clone https://github.com/reverseengineeringer/com.estrongs.android.pop '/storage/nvme5/new_clones/Smali/com.estrongs.android.pop' &
git clone https://github.com/fedorovvl/tso_client '/storage/nvme5/new_clones/Smali/tso_client' &
git clone https://github.com/shenxdtw/PokemonGo-Plugin '/storage/nvme5/new_clones/Smali/PokemonGo-Plugin' &
git clone https://github.com/dan7800/VulnerableAndroidAppOracle '/storage/nvme5/new_clones/Smali/VulnerableAndroidAppOracle' &
git clone https://github.com/aress31/sci '/storage/nvme5/new_clones/Smali/sci' &
git clone https://github.com/darvincisec/StethoInjector '/storage/nvme5/new_clones/Smali/StethoInjector' &
git clone https://github.com/pussycat0x/pegasus_spyware '/storage/nvme5/new_clones/Smali/pegasus_spyware' &
git clone https://github.com/AryanVBW/ANDRO '/storage/nvme5/new_clones/Smali/ANDRO' &
git clone https://github.com/hi-dhl/DebugApkSmali '/storage/nvme5/new_clones/Smali/DebugApkSmali' &
git clone https://github.com/Superviral/PokemonGO-Decompiled '/storage/nvme5/new_clones/Smali/PokemonGO-Decompiled' &
git clone https://github.com/ShaDisNX255/NcX_Stock '/storage/nvme5/new_clones/Smali/NcX_Stock' &
git clone https://github.com/SewellDinG/smaliArmory '/storage/nvme5/new_clones/Smali/smaliArmory' &
git clone https://github.com/LJP-TW/CTF '/storage/nvme5/new_clones/Smali/CTF' &
git clone https://github.com/pzx521521/html2apk '/storage/nvme5/new_clones/Smali/html2apk' &
git clone https://github.com/xausky/emby-for-kitkat '/storage/nvme5/new_clones/Smali/emby-for-kitkat' &
git clone https://github.com/adamyi/AndroidWechatSQLiteDecrypt '/storage/nvme5/new_clones/Smali/AndroidWechatSQLiteDecrypt' &
git clone https://github.com/Everpure/wechatforwarder '/storage/nvme5/new_clones/Smali/wechatforwarder' &
git clone https://github.com/FlymeOS/devices-base_cm '/storage/nvme5/new_clones/Smali/devices-base_cm' &
git clone https://github.com/yifengyou/Android-software-security-and-reverse-analysis '/storage/nvme5/new_clones/Smali/Android-software-security-and-reverse-analysis' &
git clone https://github.com/JonnyBanana/DroidMiner_ProVersion_Decompiled_APK '/storage/nvme5/new_clones/Smali/DroidMiner_ProVersion_Decompiled_APK' &
git clone https://github.com/swagkarna/l3mon-Bind-apk-notes '/storage/nvme5/new_clones/Smali/l3mon-Bind-apk-notes' &
git clone https://github.com/TOSPlus/TPS '/storage/nvme5/new_clones/Smali/TPS' &
git clone https://github.com/Reginer/Crack '/storage/nvme5/new_clones/Smali/Crack' &
git clone https://github.com/egaebel/sony-headphones-hack '/storage/nvme5/new_clones/Smali/sony-headphones-hack' &
git clone https://github.com/felHR85/Uncertify '/storage/nvme5/new_clones/Smali/Uncertify' &
git clone https://github.com/LeeHDsniper/APKAnalyserModules '/storage/nvme5/new_clones/Smali/APKAnalyserModules' &
git clone https://github.com/gkpln3/Gboard-Patched '/storage/nvme5/new_clones/Smali/Gboard-Patched' &
git clone https://github.com/ingbrzy/Xiaomi.eu-MIUIv10-XML-Compare '/storage/nvme5/new_clones/Smali/Xiaomi.eu-MIUIv10-XML-Compare' &
git clone https://github.com/bmh1cker/BMHacker-Botnet '/storage/nvme5/new_clones/Smali/BMHacker-Botnet' &
git clone https://github.com/AyraHikari/XiaomiAppsPort '/storage/nvme5/new_clones/Smali/XiaomiAppsPort' &
git clone https://github.com/FlymeOS/devices-base '/storage/nvme5/new_clones/Smali/devices-base' &
git clone https://github.com/Gavinme/igloggerForSmali '/storage/nvme5/new_clones/Smali/igloggerForSmali' &
git clone https://github.com/ingbrzy/Xiaomi.eu-MIUIv11-XML-Compare '/storage/nvme5/new_clones/Smali/Xiaomi.eu-MIUIv11-XML-Compare' &
git clone https://github.com/XEonAX/ANXMiuiApps '/storage/nvme5/new_clones/Smali/ANXMiuiApps' &
git clone https://github.com/TOLLER-Android/main '/storage/nvme5/new_clones/Smali/main' &
git clone https://github.com/simplehych/HookApp '/storage/nvme5/new_clones/Smali/HookApp' &
git clone https://github.com/sidealice/phicomm_r1 '/storage/nvme5/new_clones/Smali/phicomm_r1' &
git clone https://github.com/Aviksaikat/WalkThroughs '/storage/nvme5/new_clones/Smali/WalkThroughs' &
git clone https://github.com/UND-ARC/IPCam '/storage/nvme5/new_clones/Smali/IPCam' &
git clone https://github.com/luker983/google-ctf-2020 '/storage/nvme5/new_clones/Smali/google-ctf-2020' &
git clone https://github.com/sashka3076/AhMyth-Modified-Version '/storage/nvme5/new_clones/Smali/AhMyth-Modified-Version' &
git clone https://github.com/HttS3at/TeleSMS-Android-Silent-SMS-Forwarder '/storage/nvme5/new_clones/Smali/TeleSMS-Android-Silent-SMS-Forwarder' &
git clone https://github.com/RaynerSec/XploitSPY-New '/storage/nvme5/new_clones/Smali/XploitSPY-New' &
git clone https://github.com/eErenYeager/ims_apk '/storage/nvme5/new_clones/Smali/ims_apk' &
git clone https://github.com/wugemu/DingTalk '/storage/nvme5/new_clones/Smali/DingTalk' &
git clone https://github.com/darvincisec/InjectFakeSecurityProvider '/storage/nvme5/new_clones/Smali/InjectFakeSecurityProvider' &
git clone https://github.com/vzakharchenko/remote-ctrl-gsm '/storage/nvme5/new_clones/Smali/remote-ctrl-gsm' &
git clone https://github.com/Acid-miuipolskapl/v8-XML-Compare '/storage/nvme5/new_clones/Smali/v8-XML-Compare' &
git clone https://github.com/phhusson/huawei_camera_aosp '/storage/nvme5/new_clones/Smali/huawei_camera_aosp' &
git clone https://github.com/0xbitx/dedsec-payload-generator '/storage/nvme5/new_clones/Smali/dedsec-payload-generator' &
git clone https://github.com/CesarMRodriguez/lunesdemobile '/storage/nvme5/new_clones/Smali/lunesdemobile' &
git clone https://github.com/bingghost/SmaliLibrary '/storage/nvme5/new_clones/Smali/SmaliLibrary' &
git clone https://github.com/MikaCybertron/Mod-PlayerPrefs '/storage/nvme5/new_clones/Smali/Mod-PlayerPrefs' &
git clone https://github.com/37MobileTeam/PluginResTool '/storage/nvme5/new_clones/Smali/PluginResTool' &
git clone https://github.com/carrys17/Study-Notes '/storage/nvme5/new_clones/Smali/Study-Notes' &
git clone https://github.com/ingbrzy/Xiaomi.eu-MIUIv9-XML-Compare '/storage/nvme5/new_clones/Smali/Xiaomi.eu-MIUIv9-XML-Compare' &
git clone https://github.com/zeze-zeze/CTF '/storage/nvme5/new_clones/Smali/CTF' &
git clone https://github.com/PaulFreund/SteelHRAutomate '/storage/nvme5/new_clones/Smali/SteelHRAutomate' &
git clone https://github.com/dheera/android-googlepinyin-dvorak '/storage/nvme5/new_clones/Smali/android-googlepinyin-dvorak' &
git clone https://github.com/Byzehirx-Apk/X-Spy-Apk-Build '/storage/nvme5/new_clones/Smali/X-Spy-Apk-Build' &
git clone https://github.com/nhattm3006/Android-CTF '/storage/nvme5/new_clones/Smali/Android-CTF' &
git clone https://github.com/wuxianlin/MIUI_patchrom_Find5 '/storage/nvme5/new_clones/Smali/MIUI_patchrom_Find5' &
git clone https://github.com/Lanthanum-system-toolbox-v2/Prevent-patch-server '/storage/nvme5/new_clones/Smali/Prevent-patch-server' &
git clone https://github.com/xbmcrus/XBMC.ru-forum-Add-ons '/storage/nvme5/new_clones/Smali/XBMC.ru-forum-Add-ons' &
git clone https://github.com/nondanee/Jike-Patcher '/storage/nvme5/new_clones/Smali/Jike-Patcher' &
git clone https://github.com/papundutta/GHOSTBOT '/storage/nvme5/new_clones/Smali/GHOSTBOT' &
git clone https://github.com/ShaDisNX255/RayOS-S21FE-Port '/storage/nvme5/new_clones/Smali/RayOS-S21FE-Port' &
git clone https://github.com/RoyaleTitans/Poseidon '/storage/nvme5/new_clones/Smali/Poseidon' &
git clone https://github.com/DroidFreak32/swype '/storage/nvme5/new_clones/Smali/swype' &
git clone https://github.com/Blkhat1996/https-github.com-D3VL-L3MON- '/storage/nvme5/new_clones/Smali/https-github.com-D3VL-L3MON-' &
git clone https://github.com/Kiwironic/FIILEng '/storage/nvme5/new_clones/Smali/FIILEng' &
git clone https://github.com/Formyown/WechatPlus '/storage/nvme5/new_clones/Smali/WechatPlus' &
git clone https://github.com/H4oK3/Arsenal '/storage/nvme5/new_clones/Smali/Arsenal' &
git clone https://github.com/reverseengineeringer/com.instagram.android '/storage/nvme5/new_clones/Smali/com.instagram.android' &
git clone https://github.com/weljoan/qdlink-android '/storage/nvme5/new_clones/Smali/qdlink-android' &
git clone https://github.com/tea9/CVE-2017-13156-Janus '/storage/nvme5/new_clones/Smali/CVE-2017-13156-Janus' &
git clone https://github.com/gharrington/3Minit_Battery_Mod '/storage/nvme5/new_clones/Smali/3Minit_Battery_Mod' &
git clone https://github.com/suphon-t/OOS-Mods '/storage/nvme5/new_clones/Smali/OOS-Mods' &
git clone https://github.com/Saint-Theana/Prevent-R '/storage/nvme5/new_clones/Smali/Prevent-R' &
git clone https://github.com/ThunderJie/CTF-Practice '/storage/nvme5/new_clones/Smali/CTF-Practice' &
git clone https://github.com/lapwat/NfcScreenOffPie '/storage/nvme5/new_clones/Smali/NfcScreenOffPie' &
git clone https://github.com/mcrax/mcrack '/storage/nvme5/new_clones/Smali/mcrack' &
git clone https://github.com/imbaya2466/apksec '/storage/nvme5/new_clones/Smali/apksec' &
git clone https://github.com/wzv5/PreventSmaliPatch '/storage/nvme5/new_clones/Smali/PreventSmaliPatch' &
git clone https://github.com/ReiDoBrega/SMS-Verification-Fix-WhatsApp '/storage/nvme5/new_clones/Smali/SMS-Verification-Fix-WhatsApp' &
git clone https://github.com/MarcAnt01/GCam '/storage/nvme5/new_clones/Smali/GCam' &
git clone https://github.com/MiCode/patchrom_nexus5 '/storage/nvme5/new_clones/Smali/patchrom_nexus5' &
git clone https://github.com/rick51231/unifi-protect-android-direct '/storage/nvme5/new_clones/Smali/unifi-protect-android-direct' &
git clone https://github.com/9thyear2/anyme_alpha_apk_archive '/storage/nvme5/new_clones/Smali/anyme_alpha_apk_archive' &
git clone https://github.com/kin9-0rz/smafile '/storage/nvme5/new_clones/Smali/smafile' &
git clone https://github.com/Xbalien/GuardDroid '/storage/nvme5/new_clones/Smali/GuardDroid' &
git clone https://github.com/afjoseph/RexLogger '/storage/nvme5/new_clones/Smali/RexLogger' &
git clone https://github.com/rc-chuah/XploitSPY-New '/storage/nvme5/new_clones/Smali/XploitSPY-New' &
git clone https://github.com/Jayapraveen/UTS-mobile-app '/storage/nvme5/new_clones/Smali/UTS-mobile-app' &
git clone https://github.com/MI-Global/MIUI.v8.Patches.Smali '/storage/nvme5/new_clones/Smali/MIUI.v8.Patches.Smali' &
git clone https://github.com/xiaokaixuan/prevent-patch '/storage/nvme5/new_clones/Smali/prevent-patch' &
git clone https://github.com/fehead-studio/TA_Apk_Crack '/storage/nvme5/new_clones/Smali/TA_Apk_Crack' &
git clone https://github.com/nichtverstehen/fairtiq-wearos '/storage/nvme5/new_clones/Smali/fairtiq-wearos' &
git clone https://github.com/wjdwndud0114/REinca '/storage/nvme5/new_clones/Smali/REinca' &
git clone https://github.com/R47DEV/Anubis-7.0-Builder '/storage/nvme5/new_clones/Smali/Anubis-7.0-Builder' &
git clone https://github.com/zheying/WeixinFriendFeed '/storage/nvme5/new_clones/Smali/WeixinFriendFeed' &
git clone https://github.com/CounsellorPolonius/mythras '/storage/nvme5/new_clones/Smali/mythras' &
git clone https://github.com/michelerenzullo/Instagram-Effects-Downloader '/storage/nvme5/new_clones/Smali/Instagram-Effects-Downloader' &
git clone https://github.com/xyzAsian/Android-APK-LogInject '/storage/nvme5/new_clones/Smali/Android-APK-LogInject' &
git clone https://github.com/cookiemonster/BXAQ_base.apk '/storage/nvme5/new_clones/Smali/BXAQ_base.apk' &
git clone https://github.com/therosaer/LuckyPatcher '/storage/nvme5/new_clones/Smali/LuckyPatcher' &
git clone https://github.com/wincoke/NFCEmulator '/storage/nvme5/new_clones/Smali/NFCEmulator' &
git clone https://github.com/bineanzhou/shell '/storage/nvme5/new_clones/Smali/shell' &
git clone https://github.com/GrifoDev/SuperMan-ModdedFiles '/storage/nvme5/new_clones/Smali/SuperMan-ModdedFiles' &
git clone https://github.com/sepbehroozi/es-FileExplorer-3 '/storage/nvme5/new_clones/Smali/es-FileExplorer-3' &
git clone https://github.com/linhphi9x94/Miui8_patchrom_Pantech_IM-A910 '/storage/nvme5/new_clones/Smali/Miui8_patchrom_Pantech_IM-A910' &
git clone https://github.com/amog787/oofgang-mods '/storage/nvme5/new_clones/Smali/oofgang-mods' &
git clone https://github.com/HassanSardar/GBWhatsApp_Raw '/storage/nvme5/new_clones/Smali/GBWhatsApp_Raw' &
git clone https://github.com/razaina/smali-code-injector '/storage/nvme5/new_clones/Smali/smali-code-injector' &
git clone https://github.com/leerduo/AndoridLearningNote '/storage/nvme5/new_clones/Smali/AndoridLearningNote' &
git clone https://github.com/uwushito/Droidjack '/storage/nvme5/new_clones/Smali/Droidjack' &
git clone https://github.com/CalebFenton/AndroidFrameworkSmali '/storage/nvme5/new_clones/Smali/AndroidFrameworkSmali' &
git clone https://github.com/nushosilayer8/writeups '/storage/nvme5/new_clones/Smali/writeups' &
git clone https://github.com/sileht/mirrorlink-nexus5-apps '/storage/nvme5/new_clones/Smali/mirrorlink-nexus5-apps' &
git clone https://github.com/smilearchery/PokemonGoCrack '/storage/nvme5/new_clones/Smali/PokemonGoCrack' &
git clone https://github.com/White9shadow/GOD-SPEED '/storage/nvme5/new_clones/Smali/GOD-SPEED' &
git clone https://github.com/ChickenHook/Anubis-pandemidestek '/storage/nvme5/new_clones/Smali/Anubis-pandemidestek' &
git clone https://github.com/spinogrizz/ps4remote-android-gamepads '/storage/nvme5/new_clones/Smali/ps4remote-android-gamepads' &
git clone https://github.com/amirzaidi/DecompiledPixelLauncher '/storage/nvme5/new_clones/Smali/DecompiledPixelLauncher' &
git clone https://github.com/Zeop-CyberSec/pass_sanitaire '/storage/nvme5/new_clones/Smali/pass_sanitaire' &
git clone https://github.com/jumormt/SmaliApiExtract '/storage/nvme5/new_clones/Smali/SmaliApiExtract' &
git clone https://github.com/VictorAlonsoCM/CTFs '/storage/nvme5/new_clones/Smali/CTFs' &
git clone https://github.com/cstark27/PXv4_GoogleCamera_7.2.014 '/storage/nvme5/new_clones/Smali/PXv4_GoogleCamera_7.2.014' &
git clone https://github.com/AndroVirus/XploitSPY '/storage/nvme5/new_clones/Smali/XploitSPY' &
git clone https://github.com/Liberations/Flyme5_devices_base_cm '/storage/nvme5/new_clones/Smali/Flyme5_devices_base_cm' &
git clone https://github.com/DarkcoderSe/raptor '/storage/nvme5/new_clones/Smali/raptor' &
git clone https://github.com/Andycar/MachineX_ROM '/storage/nvme5/new_clones/Smali/MachineX_ROM' &
git clone https://github.com/akshayachar8055/Just-a-tool-for-exploiting-on-android '/storage/nvme5/new_clones/Smali/Just-a-tool-for-exploiting-on-android' &
git clone https://github.com/zhongguanyao/APKINFO '/storage/nvme5/new_clones/Smali/APKINFO' &
git clone https://github.com/MikeyIsBaeYT/Terraria-Mobile-Source-Code '/storage/nvme5/new_clones/Smali/Terraria-Mobile-Source-Code' &
git clone https://github.com/hqt/reverse-engineering '/storage/nvme5/new_clones/Smali/reverse-engineering' &
git clone https://github.com/TheGalaxyProject/tgp-s7-n-mods '/storage/nvme5/new_clones/Smali/tgp-s7-n-mods' &
git clone https://github.com/reverseengineeringer/com.nianticlabs.pokemongo '/storage/nvme5/new_clones/Smali/com.nianticlabs.pokemongo' &
git clone https://github.com/bla5r/RemoteLogger '/storage/nvme5/new_clones/Smali/RemoteLogger' &
git clone https://github.com/ket0x4/Micam '/storage/nvme5/new_clones/Smali/Micam' &
git clone https://github.com/luk1337/MiuiCamera '/storage/nvme5/new_clones/Smali/MiuiCamera' &
git clone https://github.com/LowSkillDeveloper/Root-3WiFiLocator-Unofficial '/storage/nvme5/new_clones/Smali/Root-3WiFiLocator-Unofficial' &
git clone https://github.com/nondanee/Jellow-Patcher '/storage/nvme5/new_clones/Smali/Jellow-Patcher' &
git clone https://github.com/gituu4567/L3MON-1 '/storage/nvme5/new_clones/Smali/L3MON-1' &
git clone https://github.com/testcc2c/old-tencent-bypass '/storage/nvme5/new_clones/Smali/old-tencent-bypass' &
git clone https://github.com/rip32700/Rephlex '/storage/nvme5/new_clones/Smali/Rephlex' &
git clone https://github.com/reverseengineeringer/com.snapchat.android '/storage/nvme5/new_clones/Smali/com.snapchat.android' &
git clone https://github.com/jakev/dtfmods-core '/storage/nvme5/new_clones/Smali/dtfmods-core' &
git clone https://github.com/MiCode/patchrom_angler '/storage/nvme5/new_clones/Smali/patchrom_angler' &
git clone https://github.com/hanicraft/minecraft-pocket-edition-1.0.1-decompiled '/storage/nvme5/new_clones/Smali/minecraft-pocket-edition-1.0.1-decompiled' &
