#!/bin/bash

git clone https://github.com/pharo-project/pharo '/storage/nvme5/new_clones/Smalltalk/pharo' &
git clone https://github.com/feenkcom/gtoolkit '/storage/nvme5/new_clones/Smalltalk/gtoolkit' &
git clone https://github.com/SeasideSt/Seaside '/storage/nvme5/new_clones/Smalltalk/Seaside' &
git clone https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-Dev' &
git clone https://github.com/redline-smalltalk/redline-smalltalk '/storage/nvme5/new_clones/Smalltalk/redline-smalltalk' &
git clone https://github.com/dolphinsmalltalk/Dolphin '/storage/nvme5/new_clones/Smalltalk/Dolphin' &
git clone https://github.com/h31h31/H31DHTMgr '/storage/nvme5/new_clones/Smalltalk/H31DHTMgr' &
git clone https://github.com/multi30k/dataset '/storage/nvme5/new_clones/Smalltalk/dataset' &
git clone https://github.com/sl4m/gnu_smalltalk_koans '/storage/nvme5/new_clones/Smalltalk/gnu_smalltalk_koans' &
git clone https://github.com/PolyMathOrg/PolyMath '/storage/nvme5/new_clones/Smalltalk/PolyMath' &
git clone https://github.com/linzehui/mRASP '/storage/nvme5/new_clones/Smalltalk/mRASP' &
git clone https://github.com/DrSleep/nas-segm-pytorch '/storage/nvme5/new_clones/Smalltalk/nas-segm-pytorch' &
git clone https://github.com/pavel-krivanek/PharoChipDesigner '/storage/nvme5/new_clones/Smalltalk/PharoChipDesigner' &
git clone https://github.com/newspeaklanguage/newspeak '/storage/nvme5/new_clones/Smalltalk/newspeak' &
git clone https://github.com/svenvc/ston '/storage/nvme5/new_clones/Smalltalk/ston' &
git clone https://github.com/moosetechnology/Moose '/storage/nvme5/new_clones/Smalltalk/Moose' &
git clone https://github.com/pharo-vcs/iceberg '/storage/nvme5/new_clones/Smalltalk/iceberg' &
git clone https://github.com/dalehenrich/filetree '/storage/nvme5/new_clones/Smalltalk/filetree' &
git clone https://github.com/Zag-Research/Zag-Smalltalk '/storage/nvme5/new_clones/Smalltalk/Zag-Smalltalk' &
git clone https://github.com/EiichiroIto/NovaStelo '/storage/nvme5/new_clones/Smalltalk/NovaStelo' &
git clone https://github.com/studio/studio '/storage/nvme5/new_clones/Smalltalk/studio' &
git clone https://github.com/pharo-project/pharo-vm '/storage/nvme5/new_clones/Smalltalk/pharo-vm' &
git clone https://github.com/pharo-project/pharo-launcher '/storage/nvme5/new_clones/Smalltalk/pharo-launcher' &
git clone https://github.com/cdglabs/thinglab '/storage/nvme5/new_clones/Smalltalk/thinglab' &
git clone https://github.com/zeroflag/Teapot '/storage/nvme5/new_clones/Smalltalk/Teapot' &
git clone https://github.com/ObjectProfile/Roassal3 '/storage/nvme5/new_clones/Smalltalk/Roassal3' &
git clone https://github.com/svenvc/zinc '/storage/nvme5/new_clones/Smalltalk/zinc' &
git clone https://github.com/hpi-swa/smalltalkCI '/storage/nvme5/new_clones/Smalltalk/smalltalkCI' &
git clone https://github.com/pharo-iot/PharoThings '/storage/nvme5/new_clones/Smalltalk/PharoThings' &
git clone https://github.com/ErikOnBike/CodeParadise '/storage/nvme5/new_clones/Smalltalk/CodeParadise' &
git clone https://github.com/Metacello/metacello '/storage/nvme5/new_clones/Smalltalk/metacello' &
git clone https://github.com/pharo-graphics/Bloc '/storage/nvme5/new_clones/Smalltalk/Bloc' &
git clone https://github.com/codeyu/LeetCode '/storage/nvme5/new_clones/Smalltalk/LeetCode' &
git clone https://github.com/PolyMathOrg/DataFrame '/storage/nvme5/new_clones/Smalltalk/DataFrame' &
git clone https://github.com/svenvc/P3 '/storage/nvme5/new_clones/Smalltalk/P3' &
git clone https://github.com/NetDevPack/Security.PasswordHasher '/storage/nvme5/new_clones/Smalltalk/Security.PasswordHasher' &
git clone https://github.com/woden-engine/woden '/storage/nvme5/new_clones/Smalltalk/woden' &
git clone https://github.com/magritte-metamodel/magritte '/storage/nvme5/new_clones/Smalltalk/magritte' &
git clone https://github.com/aserg-ufmg/JSClassFinder '/storage/nvme5/new_clones/Smalltalk/JSClassFinder' &
git clone https://github.com/mark-watson/nlp_smalltalk '/storage/nvme5/new_clones/Smalltalk/nlp_smalltalk' &
git clone https://github.com/pharo-spec/Spec '/storage/nvme5/new_clones/Smalltalk/Spec' &
git clone https://github.com/hpi-swa/Squot '/storage/nvme5/new_clones/Smalltalk/Squot' &
git clone https://github.com/rmacnak/primordialsoup '/storage/nvme5/new_clones/Smalltalk/primordialsoup' &
git clone https://github.com/hpi-swa/vivide '/storage/nvme5/new_clones/Smalltalk/vivide' &
git clone https://github.com/NicolasPetton/iliad '/storage/nvme5/new_clones/Smalltalk/iliad' &
git clone https://github.com/akevalion/Mario '/storage/nvme5/new_clones/Smalltalk/Mario' &
git clone https://github.com/kyle-github/littlesmalltalk '/storage/nvme5/new_clones/Smalltalk/littlesmalltalk' &
git clone https://github.com/WengerAG/structured-text-utilities '/storage/nvme5/new_clones/Smalltalk/structured-text-utilities' &
git clone https://github.com/guillep/Scale '/storage/nvme5/new_clones/Smalltalk/Scale' &
git clone https://github.com/pillar-markup/pillar '/storage/nvme5/new_clones/Smalltalk/pillar' &
git clone https://github.com/ba-st/Winter '/storage/nvme5/new_clones/Smalltalk/Winter' &
git clone https://github.com/codefrau/Smalltalk78 '/storage/nvme5/new_clones/Smalltalk/Smalltalk78' &
git clone https://github.com/brunobritodev/JPProject.Core '/storage/nvme5/new_clones/Smalltalk/JPProject.Core' &
git clone https://github.com/KendrickOrg/kendrick '/storage/nvme5/new_clones/Smalltalk/kendrick' &
git clone https://github.com/ba-st/Willow '/storage/nvme5/new_clones/Smalltalk/Willow' &
git clone https://github.com/mxmnk/psychic-octo-computing-machine '/storage/nvme5/new_clones/Smalltalk/psychic-octo-computing-machine' &
git clone https://github.com/OpenPonk/openponk '/storage/nvme5/new_clones/Smalltalk/openponk' &
git clone https://github.com/ApptiveGrid/Soil '/storage/nvme5/new_clones/Smalltalk/Soil' &
git clone https://github.com/VincentBlondeau/Cruiser '/storage/nvme5/new_clones/Smalltalk/Cruiser' &
git clone https://github.com/pharo-contributions/taskit '/storage/nvme5/new_clones/Smalltalk/taskit' &
git clone https://github.com/webcpu/SmalltalkVimMode '/storage/nvme5/new_clones/Smalltalk/SmalltalkVimMode' &
git clone https://github.com/hpi-swa/sandblocks '/storage/nvme5/new_clones/Smalltalk/sandblocks' &
git clone https://github.com/pharo-ide/TelePharo '/storage/nvme5/new_clones/Smalltalk/TelePharo' &
git clone https://github.com/moosetechnology/PetitParser '/storage/nvme5/new_clones/Smalltalk/PetitParser' &
git clone https://github.com/svenvc/NeoJSON '/storage/nvme5/new_clones/Smalltalk/NeoJSON' &
git clone https://github.com/kursjan/petitparser2 '/storage/nvme5/new_clones/Smalltalk/petitparser2' &
git clone https://github.com/DuneSt/MaterialDesignLite '/storage/nvme5/new_clones/Smalltalk/MaterialDesignLite' &
git clone https://github.com/hernanwilkinson/LiveTyping '/storage/nvme5/new_clones/Smalltalk/LiveTyping' &
git clone https://github.com/pillar-markup/Microdown '/storage/nvme5/new_clones/Smalltalk/Microdown' &
git clone https://github.com/ronsaldo/lowtalk '/storage/nvme5/new_clones/Smalltalk/lowtalk' &
git clone https://github.com/nikodemus/foolang '/storage/nvme5/new_clones/Smalltalk/foolang' &
git clone https://github.com/ccrraaiigg/context '/storage/nvme5/new_clones/Smalltalk/context' &
git clone https://github.com/pharo-ide/Calypso '/storage/nvme5/new_clones/Smalltalk/Calypso' &
git clone https://github.com/newapplesho/aws-sdk-smalltalk '/storage/nvme5/new_clones/Smalltalk/aws-sdk-smalltalk' &
git clone https://github.com/powerlang/powerlang '/storage/nvme5/new_clones/Smalltalk/powerlang' &
git clone https://github.com/dvmason/Pharo-Functional '/storage/nvme5/new_clones/Smalltalk/Pharo-Functional' &
git clone https://github.com/SquareBracketAssociates/TinyBlogTutorial '/storage/nvme5/new_clones/Smalltalk/TinyBlogTutorial' &
git clone https://github.com/sebastianconcept/Mapless '/storage/nvme5/new_clones/Smalltalk/Mapless' &
git clone https://github.com/lxsang/PTerm '/storage/nvme5/new_clones/Smalltalk/PTerm' &
git clone https://github.com/juliendelplanque/Mirage '/storage/nvme5/new_clones/Smalltalk/Mirage' &
git clone https://github.com/nopsys/CogNOS '/storage/nvme5/new_clones/Smalltalk/CogNOS' &
git clone https://github.com/dorellang/hunter '/storage/nvme5/new_clones/Smalltalk/hunter' &
git clone https://github.com/pharo-contributions/OSSubprocess '/storage/nvme5/new_clones/Smalltalk/OSSubprocess' &
git clone https://github.com/psvensson/golgotterath '/storage/nvme5/new_clones/Smalltalk/golgotterath' &
git clone https://github.com/vmware/script-runtime-service-for-vsphere '/storage/nvme5/new_clones/Smalltalk/script-runtime-service-for-vsphere' &
git clone https://github.com/exercism/pharo-smalltalk '/storage/nvme5/new_clones/Smalltalk/pharo-smalltalk' &
git clone https://github.com/dalehenrich/tode '/storage/nvme5/new_clones/Smalltalk/tode' &
git clone https://github.com/sytone/OneNotePowerShellProvider '/storage/nvme5/new_clones/Smalltalk/OneNotePowerShellProvider' &
git clone https://github.com/pharo-nosql/voyage '/storage/nvme5/new_clones/Smalltalk/voyage' &
git clone https://github.com/SmaCCRefactoring/SmaCC '/storage/nvme5/new_clones/Smalltalk/SmaCC' &
git clone https://github.com/OpenSmock/Pyramid '/storage/nvme5/new_clones/Smalltalk/Pyramid' &
git clone https://github.com/khinsen/leibniz-pharo '/storage/nvme5/new_clones/Smalltalk/leibniz-pharo' &
git clone https://github.com/pharo-contributions/clap-st '/storage/nvme5/new_clones/Smalltalk/clap-st' &
git clone https://github.com/feenkcom/sparta '/storage/nvme5/new_clones/Smalltalk/sparta' &
git clone https://github.com/hpi-swa-teaching/Algernon-Launcher '/storage/nvme5/new_clones/Smalltalk/Algernon-Launcher' &
git clone https://github.com/martinmcclure/mist '/storage/nvme5/new_clones/Smalltalk/mist' &
git clone https://github.com/PolyMathOrg/libtensorflow-pharo-bindings '/storage/nvme5/new_clones/Smalltalk/libtensorflow-pharo-bindings' &
git clone https://github.com/JurajKubelka/DiscordSt '/storage/nvme5/new_clones/Smalltalk/DiscordSt' &
git clone https://github.com/ba-st/Stargate '/storage/nvme5/new_clones/Smalltalk/Stargate' &
git clone https://github.com/Apress/agile-ai-in-pharo '/storage/nvme5/new_clones/Smalltalk/agile-ai-in-pharo' &
git clone https://github.com/GsDevKit/GsDevKit_home '/storage/nvme5/new_clones/Smalltalk/GsDevKit_home' &
git clone https://github.com/rko281/ReStoreForPharo '/storage/nvme5/new_clones/Smalltalk/ReStoreForPharo' &
git clone https://github.com/pharo-vcs/tonel '/storage/nvme5/new_clones/Smalltalk/tonel' &
git clone https://github.com/tkucic/UniTest '/storage/nvme5/new_clones/Smalltalk/UniTest' &
git clone https://github.com/SeasideSt/Parasol '/storage/nvme5/new_clones/Smalltalk/Parasol' &
git clone https://github.com/timfel/gitocello '/storage/nvme5/new_clones/Smalltalk/gitocello' &
git clone https://github.com/svenvc/NeoConsole '/storage/nvme5/new_clones/Smalltalk/NeoConsole' &
git clone https://github.com/TelescopeSt/Telescope '/storage/nvme5/new_clones/Smalltalk/Telescope' &
git clone https://github.com/NikolaySuslov/croquet-squeak '/storage/nvme5/new_clones/Smalltalk/croquet-squeak' &
git clone https://github.com/Wilfred/Brainfrack '/storage/nvme5/new_clones/Smalltalk/Brainfrack' &
git clone https://github.com/Helsinki-NLP/OPUS-translator '/storage/nvme5/new_clones/Smalltalk/OPUS-translator' &
git clone https://github.com/svenvc/NeoCSV '/storage/nvme5/new_clones/Smalltalk/NeoCSV' &
git clone https://github.com/peteruhnak/git-migration '/storage/nvme5/new_clones/Smalltalk/git-migration' &
git clone https://github.com/osoco/PharoPDS '/storage/nvme5/new_clones/Smalltalk/PharoPDS' &
git clone https://github.com/ericvanderwal/TextMeshPro_Playmaker '/storage/nvme5/new_clones/Smalltalk/TextMeshPro_Playmaker' &
git clone https://github.com/FrankRouter/product-classification '/storage/nvme5/new_clones/Smalltalk/product-classification' &
git clone https://github.com/dmatveev/shampoo '/storage/nvme5/new_clones/Smalltalk/shampoo' &
git clone https://github.com/theseion/Fuel '/storage/nvme5/new_clones/Smalltalk/Fuel' &
git clone https://github.com/CampSmalltalk/Cypress '/storage/nvme5/new_clones/Smalltalk/Cypress' &
git clone https://github.com/ericvanderwal/VRTK_Playmaker3x '/storage/nvme5/new_clones/Smalltalk/VRTK_Playmaker3x' &
git clone https://github.com/cormas/cormas '/storage/nvme5/new_clones/Smalltalk/cormas' &
git clone https://github.com/ObjectProfile/Roassal2 '/storage/nvme5/new_clones/Smalltalk/Roassal2' &
git clone https://github.com/OpenSmock/Molecule '/storage/nvme5/new_clones/Smalltalk/Molecule' &
git clone https://github.com/juliendelplanque/Python3Generator '/storage/nvme5/new_clones/Smalltalk/Python3Generator' &
git clone https://github.com/grpistoia/Mathemagics '/storage/nvme5/new_clones/Smalltalk/Mathemagics' &
git clone https://github.com/darth-cheney/safe-bet '/storage/nvme5/new_clones/Smalltalk/safe-bet' &
git clone https://github.com/cmfcmf/MagicMouse '/storage/nvme5/new_clones/Smalltalk/MagicMouse' &
git clone https://github.com/j-brant/SmaCC '/storage/nvme5/new_clones/Smalltalk/SmaCC' &
git clone https://github.com/pharo-rdbms/glorp '/storage/nvme5/new_clones/Smalltalk/glorp' &
git clone https://github.com/jvdsandt/pharo-aws-toolbox '/storage/nvme5/new_clones/Smalltalk/pharo-aws-toolbox' &
git clone https://github.com/hpi-swa/Ohm-S '/storage/nvme5/new_clones/Smalltalk/Ohm-S' &
git clone https://github.com/wmt-conference/wmt21-news-systems '/storage/nvme5/new_clones/Smalltalk/wmt21-news-systems' &
git clone https://github.com/ErikOnBike/TinyBootstrap '/storage/nvme5/new_clones/Smalltalk/TinyBootstrap' &
git clone https://github.com/grype/Ethel '/storage/nvme5/new_clones/Smalltalk/Ethel' &
git clone https://github.com/pharo-contributions/pharo-talents '/storage/nvme5/new_clones/Smalltalk/pharo-talents' &
git clone https://github.com/seandenigris/Dynabook '/storage/nvme5/new_clones/Smalltalk/Dynabook' &
git clone https://github.com/astares/Tealight '/storage/nvme5/new_clones/Smalltalk/Tealight' &
git clone https://github.com/AgileArtificialIntelligence/AgileArtificialIntelligence.github.io '/storage/nvme5/new_clones/Smalltalk/AgileArtificialIntelligencehub.io' &
git clone https://github.com/khinsen/ipfs-pharo '/storage/nvme5/new_clones/Smalltalk/ipfs-pharo' &
git clone https://github.com/LabWare/MQTT-broker '/storage/nvme5/new_clones/Smalltalk/MQTT-broker' &
git clone https://github.com/pharo-rdbms/Pharo-SQLite3 '/storage/nvme5/new_clones/Smalltalk/Pharo-SQLite3' &
git clone https://github.com/zweidenker/OpenAPI '/storage/nvme5/new_clones/Smalltalk/OpenAPI' &
git clone https://github.com/pharo-ai/graph-algorithms '/storage/nvme5/new_clones/Smalltalk/graph-algorithms' &
git clone https://github.com/hpi-swa-teaching/IMAPClient '/storage/nvme5/new_clones/Smalltalk/IMAPClient' &
git clone https://github.com/psvensson/cloudsdk-st '/storage/nvme5/new_clones/Smalltalk/cloudsdk-st' &
git clone https://github.com/astares/Pharo-Chrome '/storage/nvme5/new_clones/Smalltalk/Pharo-Chrome' &
git clone https://github.com/pharo-contributions/mutalk '/storage/nvme5/new_clones/Smalltalk/mutalk' &
git clone https://github.com/msgpack/msgpack-smalltalk '/storage/nvme5/new_clones/Smalltalk/msgpack-smalltalk' &
git clone https://github.com/ba-st/Buoy '/storage/nvme5/new_clones/Smalltalk/Buoy' &
git clone https://github.com/feenkcom/gtoolkit-completer '/storage/nvme5/new_clones/Smalltalk/gtoolkit-completer' &
git clone https://github.com/pharo-spec/NewTools '/storage/nvme5/new_clones/Smalltalk/NewTools' &
git clone https://github.com/Cuis-University/Cuis-University '/storage/nvme5/new_clones/Smalltalk/Cuis-University' &
git clone https://github.com/ObjectProfile/PythonBridge '/storage/nvme5/new_clones/Smalltalk/PythonBridge' &
git clone https://github.com/beefarino/EntityShell '/storage/nvme5/new_clones/Smalltalk/EntityShell' &
git clone https://github.com/activepapers/activepapers-pharo '/storage/nvme5/new_clones/Smalltalk/activepapers-pharo' &
git clone https://github.com/estebanlm/themes '/storage/nvme5/new_clones/Smalltalk/themes' &
git clone https://github.com/lukego/xoos '/storage/nvme5/new_clones/Smalltalk/xoos' &
git clone https://github.com/smalljvm/SmallJ '/storage/nvme5/new_clones/Smalltalk/SmallJ' &
git clone https://github.com/Chen188/MicroBlog '/storage/nvme5/new_clones/Smalltalk/MicroBlog' &
git clone https://github.com/pharo-ide/Seamless '/storage/nvme5/new_clones/Smalltalk/Seamless' &
git clone https://github.com/janniklaval/phratch '/storage/nvme5/new_clones/Smalltalk/phratch' &
git clone https://github.com/Netstyle/Workflow '/storage/nvme5/new_clones/Smalltalk/Workflow' &
git clone https://github.com/smartanvil/Fog '/storage/nvme5/new_clones/Smalltalk/Fog' &
git clone https://github.com/eftomi/Pharo-Webview '/storage/nvme5/new_clones/Smalltalk/Pharo-Webview' &
git clone https://github.com/wmt-conference/wmt22-news-systems '/storage/nvme5/new_clones/Smalltalk/wmt22-news-systems' &
git clone https://github.com/sera0506/Live-2D-with-Unity '/storage/nvme5/new_clones/Smalltalk/Live-2D-with-Unity' &
git clone https://github.com/brackendev/SwiftPlayground-Pharo '/storage/nvme5/new_clones/Smalltalk/SwiftPlayground-Pharo' &
git clone https://github.com/pablomarx/Smalltalk76 '/storage/nvme5/new_clones/Smalltalk/Smalltalk76' &
git clone https://github.com/tkucic/brOscatLib '/storage/nvme5/new_clones/Smalltalk/brOscatLib' &
git clone https://github.com/pegesund/heysql '/storage/nvme5/new_clones/Smalltalk/heysql' &
git clone https://github.com/juliendelplanque/MatplotLibBridge '/storage/nvme5/new_clones/Smalltalk/MatplotLibBridge' &
git clone https://github.com/feenkcom/lepiter '/storage/nvme5/new_clones/Smalltalk/lepiter' &
git clone https://github.com/gcotelli/RenoirSt '/storage/nvme5/new_clones/Smalltalk/RenoirSt' &
git clone https://github.com/SeasideSt/Grease '/storage/nvme5/new_clones/Smalltalk/Grease' &
git clone https://github.com/pharo-graphics/Toplo '/storage/nvme5/new_clones/Smalltalk/Toplo' &
git clone https://github.com/pharo-nosql/mongotalk '/storage/nvme5/new_clones/Smalltalk/mongotalk' &
git clone https://github.com/ericvanderwal/timeline-playmaker '/storage/nvme5/new_clones/Smalltalk/timeline-playmaker' &
git clone https://github.com/dionisiydk/Mocketry '/storage/nvme5/new_clones/Smalltalk/Mocketry' &
git clone https://github.com/maximsamokhval/Automation-Community '/storage/nvme5/new_clones/Smalltalk/Automation-Community' &
git clone https://github.com/jvuletich/Cuis '/storage/nvme5/new_clones/Smalltalk/Cuis' &
git clone https://github.com/pharo-contributions/Artefact '/storage/nvme5/new_clones/Smalltalk/Artefact' &
git clone https://github.com/hernanmd/Territorial '/storage/nvme5/new_clones/Smalltalk/Territorial' &
git clone https://github.com/bpieber/Cuis-Smalltalk-StyledTextEditor '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-StyledTextEditor' &
git clone https://github.com/garciadelcastillo/ViveTrack-Dynamo '/storage/nvme5/new_clones/Smalltalk/ViveTrack-Dynamo' &
git clone https://github.com/hernanmd/BioSmalltalk '/storage/nvme5/new_clones/Smalltalk/BioSmalltalk' &
git clone https://github.com/guillep/PharoCandle '/storage/nvme5/new_clones/Smalltalk/PharoCandle' &
git clone https://github.com/brackendev/ELIZA-Smalltalk '/storage/nvme5/new_clones/Smalltalk/ELIZA-Smalltalk' &
git clone https://github.com/asciamanna/iTunesLibraryParser '/storage/nvme5/new_clones/Smalltalk/iTunesLibraryParser' &
git clone https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-UI '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-UI' &
git clone https://github.com/EiichiroIto/Gratch '/storage/nvme5/new_clones/Smalltalk/Gratch' &
git clone https://github.com/AnySDK/Sample_Unity '/storage/nvme5/new_clones/Smalltalk/Sample_Unity' &
git clone https://github.com/pavel-krivanek/terminal '/storage/nvme5/new_clones/Smalltalk/terminal' &
git clone https://github.com/dickiepotter/Vector '/storage/nvme5/new_clones/Smalltalk/Vector' &
git clone https://github.com/OBJECTSEMANTICS/GraphQL '/storage/nvme5/new_clones/Smalltalk/GraphQL' &
git clone https://github.com/fuhrmanator/PlantUMLPharoGizmo '/storage/nvme5/new_clones/Smalltalk/PlantUMLPharoGizmo' &
git clone https://github.com/hegdenaveen1/ARSpectroscope1 '/storage/nvme5/new_clones/Smalltalk/ARSpectroscope1' &
git clone https://github.com/NoMod-Programming/Whiskers '/storage/nvme5/new_clones/Smalltalk/Whiskers' &
git clone https://github.com/sebastianconcept/flow '/storage/nvme5/new_clones/Smalltalk/flow' &
git clone https://github.com/seandenigris/Simple-Persistence '/storage/nvme5/new_clones/Smalltalk/Simple-Persistence' &
git clone https://github.com/ronsaldo/phanide '/storage/nvme5/new_clones/Smalltalk/phanide' &
git clone https://github.com/shingarov/MachineArithmetic '/storage/nvme5/new_clones/Smalltalk/MachineArithmetic' &
git clone https://github.com/hpi-swa-teaching/Scamper '/storage/nvme5/new_clones/Smalltalk/Scamper' &
git clone https://github.com/pablo1n7/bottlegram '/storage/nvme5/new_clones/Smalltalk/bottlegram' &
git clone https://github.com/pharo-pkg/pakbot '/storage/nvme5/new_clones/Smalltalk/pakbot' &
git clone https://github.com/hpi-swa-teaching/TelegramClient '/storage/nvme5/new_clones/Smalltalk/TelegramClient' &
git clone https://github.com/jgfoster/Jade.bak '/storage/nvme5/new_clones/Smalltalk/Jade.bak' &
git clone https://github.com/spec-framework/spec '/storage/nvme5/new_clones/Smalltalk/spec' &
git clone https://github.com/badetitou/Pharo-LibVLC '/storage/nvme5/new_clones/Smalltalk/Pharo-LibVLC' &
git clone https://github.com/hpi-swa/Gramada '/storage/nvme5/new_clones/Smalltalk/Gramada' &
git clone https://github.com/IJEMIN/Live2D-Wrapper-Sample-Unity-App '/storage/nvme5/new_clones/Smalltalk/Live2D-Wrapper-Sample-Unity-App' &
git clone https://github.com/len/Cuis-Smalltalk-DWM '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-DWM' &
git clone https://github.com/hpi-swa-teaching/Koans '/storage/nvme5/new_clones/Smalltalk/Koans' &
git clone https://github.com/zweidenker/Units '/storage/nvme5/new_clones/Smalltalk/Units' &
git clone https://github.com/Uko/QualityAssistant '/storage/nvme5/new_clones/Smalltalk/QualityAssistant' &
git clone https://github.com/zweidenker/JSONSchema '/storage/nvme5/new_clones/Smalltalk/JSONSchema' &
git clone https://github.com/MoosheTV/PropHuntV '/storage/nvme5/new_clones/Smalltalk/PropHuntV' &
git clone https://github.com/ba-st/Launchpad '/storage/nvme5/new_clones/Smalltalk/Launchpad' &
git clone https://github.com/noha/JSONWebToken '/storage/nvme5/new_clones/Smalltalk/JSONWebToken' &
git clone https://github.com/ThierryGoubier/GitFileTree-MergeDriver '/storage/nvme5/new_clones/Smalltalk/GitFileTree-MergeDriver' &
git clone https://github.com/mumez/SIXX '/storage/nvme5/new_clones/Smalltalk/SIXX' &
git clone https://github.com/David5i6/Uncommon-Themes '/storage/nvme5/new_clones/Smalltalk/Uncommon-Themes' &
git clone https://github.com/UoB-HPC/neutral '/storage/nvme5/new_clones/Smalltalk/neutral' &
git clone https://github.com/mumez/Tarantalk '/storage/nvme5/new_clones/Smalltalk/Tarantalk' &
git clone https://github.com/lucretiomsp/Coypu '/storage/nvme5/new_clones/Smalltalk/Coypu' &
git clone https://github.com/hpi-swa-lab/home-desktop-system '/storage/nvme5/new_clones/Smalltalk/home-desktop-system' &
git clone https://github.com/bouraqadi/PharoMisc '/storage/nvme5/new_clones/Smalltalk/PharoMisc' &
git clone https://github.com/nmingotti/The-Cuis-CookBook '/storage/nvme5/new_clones/Smalltalk/The-Cuis-CookBook' &
git clone https://github.com/jecisc/GitBridge '/storage/nvme5/new_clones/Smalltalk/GitBridge' &
git clone https://github.com/moiji-mobile/hlr '/storage/nvme5/new_clones/Smalltalk/hlr' &
git clone https://github.com/sfl0r3nz05/OT-NWbasedOnGNS3 '/storage/nvme5/new_clones/Smalltalk/OT-NWbasedOnGNS3' &
git clone https://github.com/GemTalk/Rowan '/storage/nvme5/new_clones/Smalltalk/Rowan' &
git clone https://github.com/jecisc/TinyLogger '/storage/nvme5/new_clones/Smalltalk/TinyLogger' &
git clone https://github.com/svenvc/SimpleRedisClient '/storage/nvme5/new_clones/Smalltalk/SimpleRedisClient' &
git clone https://github.com/EiichiroIto/Box2DLiteForPharo '/storage/nvme5/new_clones/Smalltalk/Box2DLiteForPharo' &
git clone https://github.com/hpi-swa-lab/babylonian-programming-smalltalk '/storage/nvme5/new_clones/Smalltalk/babylonian-programming-smalltalk' &
git clone https://github.com/jecisc/pharo-scripts '/storage/nvme5/new_clones/Smalltalk/pharo-scripts' &
git clone https://github.com/astares/Pharo-OS-Windows '/storage/nvme5/new_clones/Smalltalk/Pharo-OS-Windows' &
git clone https://github.com/quentinplessis/Teamtalk '/storage/nvme5/new_clones/Smalltalk/Teamtalk' &
git clone https://github.com/progtb/1c-style-guide-progtb '/storage/nvme5/new_clones/Smalltalk/1c-style-guide-progtb' &
git clone https://github.com/moosetechnology/Famix '/storage/nvme5/new_clones/Smalltalk/Famix' &
git clone https://github.com/tomooda/ViennaTalk '/storage/nvme5/new_clones/Smalltalk/ViennaTalk' &
git clone https://github.com/VincentBlondeau/Tabular '/storage/nvme5/new_clones/Smalltalk/Tabular' &
git clone https://github.com/estebanlm/MUDClient '/storage/nvme5/new_clones/Smalltalk/MUDClient' &
git clone https://github.com/feenkcom/gtoolkit-visualizer '/storage/nvme5/new_clones/Smalltalk/gtoolkit-visualizer' &
git clone https://github.com/pharo-spec/mars-gtk '/storage/nvme5/new_clones/Smalltalk/mars-gtk' &
git clone https://github.com/estebanlm/crono '/storage/nvme5/new_clones/Smalltalk/crono' &
git clone https://github.com/pharo-ai/data-inspector '/storage/nvme5/new_clones/Smalltalk/data-inspector' &
git clone https://github.com/Pharophile/Transducers '/storage/nvme5/new_clones/Smalltalk/Transducers' &
git clone https://github.com/lxsang/SystemProcess '/storage/nvme5/new_clones/Smalltalk/SystemProcess' &
git clone https://github.com/Pharophile/TilingWindowManager '/storage/nvme5/new_clones/Smalltalk/TilingWindowManager' &
git clone https://github.com/tesonep/pharo-vm-embedded-example '/storage/nvme5/new_clones/Smalltalk/pharo-vm-embedded-example' &
git clone https://github.com/hpi-swa-teaching/GameMecha '/storage/nvme5/new_clones/Smalltalk/GameMecha' &
git clone https://github.com/maenu/BlockStyler '/storage/nvme5/new_clones/Smalltalk/BlockStyler' &
git clone https://github.com/vast-community-hub/tensorflow-vast '/storage/nvme5/new_clones/Smalltalk/tensorflow-vast' &
git clone https://github.com/khinsen/guix-gtoolkit '/storage/nvme5/new_clones/Smalltalk/guix-gtoolkit' &
git clone https://github.com/peteruhnak/live-instance-viewer '/storage/nvme5/new_clones/Smalltalk/live-instance-viewer' &
git clone https://github.com/Moose2Model/Moose2Model '/storage/nvme5/new_clones/Smalltalk/Moose2Model' &
git clone https://github.com/smarr/SMark '/storage/nvme5/new_clones/Smalltalk/SMark' &
git clone https://github.com/yannij/TMM '/storage/nvme5/new_clones/Smalltalk/TMM' &
git clone https://github.com/jvdsandt/protobuf-smalltalk '/storage/nvme5/new_clones/Smalltalk/protobuf-smalltalk' &
git clone https://github.com/noha/mustache '/storage/nvme5/new_clones/Smalltalk/mustache' &
git clone https://github.com/pharo-spec/Spec-Gtk '/storage/nvme5/new_clones/Smalltalk/Spec-Gtk' &
git clone https://github.com/feenkcom/gt4gemstone-old '/storage/nvme5/new_clones/Smalltalk/gt4gemstone-old' &
git clone https://github.com/tatut/LiveWeb '/storage/nvme5/new_clones/Smalltalk/LiveWeb' &
git clone https://github.com/hpi-swa-lab/sb-tree-sitter '/storage/nvme5/new_clones/Smalltalk/sb-tree-sitter' &
git clone https://github.com/juliendelplanque/PharoCodeGenerator '/storage/nvme5/new_clones/Smalltalk/PharoCodeGenerator' &
git clone https://github.com/seandenigris/Computer-World '/storage/nvme5/new_clones/Smalltalk/Computer-World' &
git clone https://github.com/pharo-project/pharo-beacon '/storage/nvme5/new_clones/Smalltalk/pharo-beacon' &
git clone https://github.com/ba-st/HighchartsSt '/storage/nvme5/new_clones/Smalltalk/HighchartsSt' &
git clone https://github.com/mumez/PunQLite '/storage/nvme5/new_clones/Smalltalk/PunQLite' &
git clone https://github.com/hpi-swa-lab/godot-squeak '/storage/nvme5/new_clones/Smalltalk/godot-squeak' &
git clone https://github.com/tomooda/tekka '/storage/nvme5/new_clones/Smalltalk/tekka' &
git clone https://github.com/pavel-krivanek/VoxelSpace '/storage/nvme5/new_clones/Smalltalk/VoxelSpace' &
git clone https://github.com/svenvc/UTF8String '/storage/nvme5/new_clones/Smalltalk/UTF8String' &
git clone https://github.com/astares/Pharo-Pomodoro '/storage/nvme5/new_clones/Smalltalk/Pharo-Pomodoro' &
git clone https://github.com/ramyothman/DotNetAnalyticsAPI '/storage/nvme5/new_clones/Smalltalk/DotNetAnalyticsAPI' &
git clone https://github.com/svenvc/mqtt '/storage/nvme5/new_clones/Smalltalk/mqtt' &
git clone https://github.com/Eurus-Holmes/MNMT '/storage/nvme5/new_clones/Smalltalk/MNMT' &
git clone https://github.com/ajlopez/AjTalkJs '/storage/nvme5/new_clones/Smalltalk/AjTalkJs' &
git clone https://github.com/adolfopa/microkanren-pharo '/storage/nvme5/new_clones/Smalltalk/microkanren-pharo' &
git clone https://github.com/khinsen/GT-Zotero '/storage/nvme5/new_clones/Smalltalk/GT-Zotero' &
git clone https://github.com/pablo1n7/Smallbook '/storage/nvme5/new_clones/Smalltalk/Smallbook' &
git clone https://github.com/sebastianconcept/PharoDawnTheme '/storage/nvme5/new_clones/Smalltalk/PharoDawnTheme' &
git clone https://github.com/Ducasse/SOUL '/storage/nvme5/new_clones/Smalltalk/SOUL' &
git clone https://github.com/pharo-contributions/Pharo-Spreadsheet '/storage/nvme5/new_clones/Smalltalk/Pharo-Spreadsheet' &
git clone https://github.com/feenkcom/gtoolkit-examples '/storage/nvme5/new_clones/Smalltalk/gtoolkit-examples' &
git clone https://github.com/lifia-unlp/Kobold '/storage/nvme5/new_clones/Smalltalk/Kobold' &
git clone https://github.com/ReMobidyc/ReMobidyc '/storage/nvme5/new_clones/Smalltalk/ReMobidyc' &
git clone https://github.com/rcornwell/smalltalk '/storage/nvme5/new_clones/Smalltalk/smalltalk' &
git clone https://github.com/mcandre/quicksmash '/storage/nvme5/new_clones/Smalltalk/quicksmash' &
git clone https://github.com/koukdw/Aquarium_tools '/storage/nvme5/new_clones/Smalltalk/Aquarium_tools' &
git clone https://github.com/guillep/GitHub '/storage/nvme5/new_clones/Smalltalk/GitHub' &
git clone https://github.com/LinqLover/TelegramSmalltalkBot '/storage/nvme5/new_clones/Smalltalk/TelegramSmalltalkBot' &
git clone https://github.com/tcj2001/Clean_Architecture_Program_Generator_for_CSharp_and_NET6 '/storage/nvme5/new_clones/Smalltalk/Clean_Architecture_Program_Generator_for_CSharp_and_NET6' &
git clone https://github.com/octotrike/trike '/storage/nvme5/new_clones/Smalltalk/trike' &
git clone https://github.com/UBA-FCEN-IngSoft1/Parciales '/storage/nvme5/new_clones/Smalltalk/Parciales' &
git clone https://github.com/Laeri/shapegrammar_pharo '/storage/nvme5/new_clones/Smalltalk/shapegrammar_pharo' &
git clone https://github.com/guillermoamaral/Pharo-Webside '/storage/nvme5/new_clones/Smalltalk/Pharo-Webside' &
git clone https://github.com/Helsinki-NLP/OPUS-MT-testsets '/storage/nvme5/new_clones/Smalltalk/OPUS-MT-testsets' &
git clone https://github.com/pharo-contributions/Scheduler '/storage/nvme5/new_clones/Smalltalk/Scheduler' &
git clone https://github.com/ronsaldo/pharo-git-thermite '/storage/nvme5/new_clones/Smalltalk/pharo-git-thermite' &
git clone https://github.com/hernanwilkinson/Cuis-Smalltalk-Refactoring '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-Refactoring' &
git clone https://github.com/brackendev/TwitterSDK-Pharo '/storage/nvme5/new_clones/Smalltalk/TwitterSDK-Pharo' &
git clone https://github.com/pablomarx/AltoST80 '/storage/nvme5/new_clones/Smalltalk/AltoST80' &
git clone https://github.com/tomooda/Jun '/storage/nvme5/new_clones/Smalltalk/Jun' &
git clone https://github.com/skaplar/NewWave '/storage/nvme5/new_clones/Smalltalk/NewWave' &
git clone https://github.com/juliendelplanque/JRPC '/storage/nvme5/new_clones/Smalltalk/JRPC' &
git clone https://github.com/pablo1n7/ImageForm '/storage/nvme5/new_clones/Smalltalk/ImageForm' &
git clone https://github.com/monofonik/scribble '/storage/nvme5/new_clones/Smalltalk/scribble' &
git clone https://github.com/pharo-contributions/XML-XMLParser '/storage/nvme5/new_clones/Smalltalk/XML-XMLParser' &
git clone https://github.com/svenvc/ztimestamp '/storage/nvme5/new_clones/Smalltalk/ztimestamp' &
git clone https://github.com/GemTalk/Sparkle '/storage/nvme5/new_clones/Smalltalk/Sparkle' &
git clone https://github.com/maenu/LiteratureResearcher '/storage/nvme5/new_clones/Smalltalk/LiteratureResearcher' &
git clone https://github.com/GeeLaw/Dock-PS '/storage/nvme5/new_clones/Smalltalk/Dock-PS' &
git clone https://github.com/sovelten/smallworlds '/storage/nvme5/new_clones/Smalltalk/smallworlds' &
git clone https://github.com/newapplesho/elasticsearch-smalltalk '/storage/nvme5/new_clones/Smalltalk/elasticsearch-smalltalk' &
git clone https://github.com/Pier-CMS/Pier3 '/storage/nvme5/new_clones/Smalltalk/Pier3' &
git clone https://github.com/hpi-swa/MessageSendRecorder '/storage/nvme5/new_clones/Smalltalk/MessageSendRecorder' &
git clone https://github.com/feenkcom/pharo-futures '/storage/nvme5/new_clones/Smalltalk/pharo-futures' &
git clone https://github.com/mumez/VerStix '/storage/nvme5/new_clones/Smalltalk/VerStix' &
git clone https://github.com/hpi-swa/animations '/storage/nvme5/new_clones/Smalltalk/animations' &
git clone https://github.com/souravdatta/turtles '/storage/nvme5/new_clones/Smalltalk/turtles' &
git clone https://github.com/InesSosa95/PHANtom '/storage/nvme5/new_clones/Smalltalk/PHANtom' &
git clone https://github.com/hpi-swa-teaching/Morphic-Testing-Framework '/storage/nvme5/new_clones/Smalltalk/Morphic-Testing-Framework' &
git clone https://github.com/pharo-contributions/Cryptography '/storage/nvme5/new_clones/Smalltalk/Cryptography' &
git clone https://github.com/pharo-contributions/SingularizePluralize '/storage/nvme5/new_clones/Smalltalk/SingularizePluralize' &
git clone https://github.com/brackendev/GistBrowser-Pharo '/storage/nvme5/new_clones/Smalltalk/GistBrowser-Pharo' &
git clone https://github.com/peteruhnak/pharo-sentry '/storage/nvme5/new_clones/Smalltalk/pharo-sentry' &
git clone https://github.com/astares/Seaside-Bootstrap '/storage/nvme5/new_clones/Smalltalk/Seaside-Bootstrap' &
git clone https://github.com/mumez/Stick '/storage/nvme5/new_clones/Smalltalk/Stick' &
git clone https://github.com/LinqLover/SimulationStudio '/storage/nvme5/new_clones/Smalltalk/SimulationStudio' &
git clone https://github.com/feenkcom/gt4smacc '/storage/nvme5/new_clones/Smalltalk/gt4smacc' &
git clone https://github.com/zweidenker/SnapDump '/storage/nvme5/new_clones/Smalltalk/SnapDump' &
git clone https://github.com/psvensson/firebase-st '/storage/nvme5/new_clones/Smalltalk/firebase-st' &
git clone https://github.com/emdonahue/SmallKanren '/storage/nvme5/new_clones/Smalltalk/SmallKanren' &
git clone https://github.com/mircealungu/Polite '/storage/nvme5/new_clones/Smalltalk/Polite' &
git clone https://github.com/hpi-swa-teaching/AutoTDD '/storage/nvme5/new_clones/Smalltalk/AutoTDD' &
git clone https://github.com/instantiations/tonel-vast '/storage/nvme5/new_clones/Smalltalk/tonel-vast' &
git clone https://github.com/carpentry-org/gt4carp '/storage/nvme5/new_clones/Smalltalk/gt4carp' &
git clone https://github.com/astares/Seaside-Bootstrap5 '/storage/nvme5/new_clones/Smalltalk/Seaside-Bootstrap5' &
git clone https://github.com/babelsberg/babelsberg-s '/storage/nvme5/new_clones/Smalltalk/babelsberg-s' &
git clone https://github.com/ChrisHammond/dnnsimplearticle '/storage/nvme5/new_clones/Smalltalk/dnnsimplearticle' &
git clone https://github.com/pharo-rdbms/Pharo-ODBC '/storage/nvme5/new_clones/Smalltalk/Pharo-ODBC' &
git clone https://github.com/jordanmontt/illimani-memory-profiler '/storage/nvme5/new_clones/Smalltalk/illimani-memory-profiler' &
git clone https://github.com/astares/Pharo-Compendium '/storage/nvme5/new_clones/Smalltalk/Pharo-Compendium' &
git clone https://github.com/fniephaus/BroDCPU '/storage/nvme5/new_clones/Smalltalk/BroDCPU' &
git clone https://github.com/eftomi/PharoADO '/storage/nvme5/new_clones/Smalltalk/PharoADO' &
git clone https://github.com/HaZardModding/hzm-mohaa-coop-mod '/storage/nvme5/new_clones/Smalltalk/hzm-mohaa-coop-mod' &
git clone https://github.com/LeonMatthes/Autocompletion '/storage/nvme5/new_clones/Smalltalk/Autocompletion' &
git clone https://github.com/dalehenrich/metacello_old '/storage/nvme5/new_clones/Smalltalk/metacello_old' &
git clone https://github.com/sebastianconcept/Aggregate '/storage/nvme5/new_clones/Smalltalk/Aggregate' &
git clone https://github.com/Wilfred/mal_pharo '/storage/nvme5/new_clones/Smalltalk/mal_pharo' &
git clone https://github.com/ba-st/Superluminal '/storage/nvme5/new_clones/Smalltalk/Superluminal' &
git clone https://github.com/feenkcom/gtoolkit-demos '/storage/nvme5/new_clones/Smalltalk/gtoolkit-demos' &
git clone https://github.com/hpi-swa-teaching/SpreadSheetTool '/storage/nvme5/new_clones/Smalltalk/SpreadSheetTool' &
git clone https://github.com/hernanmd/badges '/storage/nvme5/new_clones/Smalltalk/badges' &
git clone https://github.com/ghosthamlet/strand '/storage/nvme5/new_clones/Smalltalk/strand' &
git clone https://github.com/len/RayTracer '/storage/nvme5/new_clones/Smalltalk/RayTracer' &
git clone https://github.com/estebanlm/pharo-mastodon '/storage/nvme5/new_clones/Smalltalk/pharo-mastodon' &
git clone https://github.com/juliendelplanque/Iterators '/storage/nvme5/new_clones/Smalltalk/Iterators' &
git clone https://github.com/LazaroProject/Lazaro '/storage/nvme5/new_clones/Smalltalk/Lazaro' &
git clone https://github.com/hernanmd/package-formulas '/storage/nvme5/new_clones/Smalltalk/package-formulas' &
git clone https://github.com/osoco/pharo-eda '/storage/nvme5/new_clones/Smalltalk/pharo-eda' &
git clone https://github.com/brunobuzzi/U-Fabrik '/storage/nvme5/new_clones/Smalltalk/U-Fabrik' &
git clone https://github.com/NicolasPetton/sandstonedb '/storage/nvme5/new_clones/Smalltalk/sandstonedb' &
git clone https://github.com/dupriezt/HaltManager '/storage/nvme5/new_clones/Smalltalk/HaltManager' &
git clone https://github.com/kilon/Atlas '/storage/nvme5/new_clones/Smalltalk/Atlas' &
git clone https://github.com/pharo-vcs/github-api '/storage/nvme5/new_clones/Smalltalk/github-api' &
git clone https://github.com/EiichiroIto/microwitch '/storage/nvme5/new_clones/Smalltalk/microwitch' &
git clone https://github.com/feenkcom/gt4edx '/storage/nvme5/new_clones/Smalltalk/gt4edx' &
git clone https://github.com/OpenSmock/Penfeld '/storage/nvme5/new_clones/Smalltalk/Penfeld' &
git clone https://github.com/Peter-H-Meadows/GtMetamath '/storage/nvme5/new_clones/Smalltalk/GtMetamath' &
git clone https://github.com/npapoylias/Geranium '/storage/nvme5/new_clones/Smalltalk/Geranium' &
git clone https://github.com/pharo-graphics/Tutorials '/storage/nvme5/new_clones/Smalltalk/Tutorials' &
git clone https://github.com/ba-st/Hyperspace '/storage/nvme5/new_clones/Smalltalk/Hyperspace' &
git clone https://github.com/ObjectProfile/DMirror '/storage/nvme5/new_clones/Smalltalk/DMirror' &
git clone https://github.com/pharo-ai/datasets '/storage/nvme5/new_clones/Smalltalk/datasets' &
git clone https://github.com/ldh/DesktopAssistant '/storage/nvme5/new_clones/Smalltalk/DesktopAssistant' &
git clone https://github.com/smarr/LibGit '/storage/nvme5/new_clones/Smalltalk/LibGit' &
git clone https://github.com/noha/pharo-minimal '/storage/nvme5/new_clones/Smalltalk/pharo-minimal' &
git clone https://github.com/Zenchess/pharoRaylib '/storage/nvme5/new_clones/Smalltalk/pharoRaylib' &
git clone https://github.com/hpi-swa-teaching/StatisticsWorkbench '/storage/nvme5/new_clones/Smalltalk/StatisticsWorkbench' &
git clone https://github.com/hesam/JOHN-COLA-Planner-Library '/storage/nvme5/new_clones/Smalltalk/JOHN-COLA-Planner-Library' &
git clone https://github.com/aucerna/bee-dmr '/storage/nvme5/new_clones/Smalltalk/bee-dmr' &
git clone https://github.com/svenvc/zodiac '/storage/nvme5/new_clones/Smalltalk/zodiac' &
git clone https://github.com/maxwills/SeekerDebugger '/storage/nvme5/new_clones/Smalltalk/SeekerDebugger' &
git clone https://github.com/feenkcom/JSLink '/storage/nvme5/new_clones/Smalltalk/JSLink' &
git clone https://github.com/astares/Pharo-Regex-Tools '/storage/nvme5/new_clones/Smalltalk/Pharo-Regex-Tools' &
git clone https://github.com/souravdatta/TurtleStudio '/storage/nvme5/new_clones/Smalltalk/TurtleStudio' &
git clone https://github.com/JurajKubelka/OrgMode '/storage/nvme5/new_clones/Smalltalk/OrgMode' &
git clone https://github.com/darth-cheney/pharo-irc '/storage/nvme5/new_clones/Smalltalk/pharo-irc' &
git clone https://github.com/pharo-contributions/file-dialog-transfered-to-newtools '/storage/nvme5/new_clones/Smalltalk/file-dialog-transfered-to-newtools' &
git clone https://github.com/dotmpe/udanax-mpe '/storage/nvme5/new_clones/Smalltalk/udanax-mpe' &
git clone https://github.com/Uko/MatchTool '/storage/nvme5/new_clones/Smalltalk/MatchTool' &
git clone https://github.com/pharo-contributions/DeepTraverser '/storage/nvme5/new_clones/Smalltalk/DeepTraverser' &
git clone https://github.com/juliendelplanque/SQLite3 '/storage/nvme5/new_clones/Smalltalk/SQLite3' &
git clone https://github.com/ObjectProfile/Roassal3Exporters '/storage/nvme5/new_clones/Smalltalk/Roassal3Exporters' &
git clone https://github.com/juliangrigera/PharoTweaks '/storage/nvme5/new_clones/Smalltalk/PharoTweaks' &
git clone https://github.com/tesonep/pharo-com '/storage/nvme5/new_clones/Smalltalk/pharo-com' &
git clone https://github.com/hpi-swa-teaching/AnimationsEditor '/storage/nvme5/new_clones/Smalltalk/AnimationsEditor' &
git clone https://github.com/Traadh/bittrex '/storage/nvme5/new_clones/Smalltalk/bittrex' &
git clone https://github.com/botwhytho/GtDatabaseVisualizer '/storage/nvme5/new_clones/Smalltalk/GtDatabaseVisualizer' &
git clone https://github.com/feenkcom/gtoolkit-documenter '/storage/nvme5/new_clones/Smalltalk/gtoolkit-documenter' &
git clone https://github.com/maenu/gtoolkit-contribution-typer '/storage/nvme5/new_clones/Smalltalk/gtoolkit-contribution-typer' &
git clone https://github.com/feenkcom/gtoolkit-presenter '/storage/nvme5/new_clones/Smalltalk/gtoolkit-presenter' &
git clone https://github.com/badetitou/Casino '/storage/nvme5/new_clones/Smalltalk/Casino' &
git clone https://github.com/peteruhnak/IconFactory '/storage/nvme5/new_clones/Smalltalk/IconFactory' &
git clone https://github.com/timfel/JSON-st '/storage/nvme5/new_clones/Smalltalk/JSON-st' &
git clone https://github.com/mumez/RediStick '/storage/nvme5/new_clones/Smalltalk/RediStick' &
git clone https://github.com/pharo-rdbms/garage '/storage/nvme5/new_clones/Smalltalk/garage' &
git clone https://github.com/DraagrenKirneh/TOML '/storage/nvme5/new_clones/Smalltalk/TOML' &
git clone https://github.com/hpi-swa/Rack '/storage/nvme5/new_clones/Smalltalk/Rack' &
git clone https://github.com/newapplesho/google-api-smalltalk-client '/storage/nvme5/new_clones/Smalltalk/google-api-smalltalk-client' &
git clone https://github.com/ygraham/direct-assessment '/storage/nvme5/new_clones/Smalltalk/direct-assessment' &
git clone https://github.com/ba-st/Willow-Playground '/storage/nvme5/new_clones/Smalltalk/Willow-Playground' &
git clone https://github.com/miki/HTML-Feature '/storage/nvme5/new_clones/Smalltalk/HTML-Feature' &
git clone https://github.com/hpi-swa-lab/squeak-graphics-opengl '/storage/nvme5/new_clones/Smalltalk/squeak-graphics-opengl' &
git clone https://github.com/akgrant43/GeoSphere '/storage/nvme5/new_clones/Smalltalk/GeoSphere' &
git clone https://github.com/rvillemeur/QRCode '/storage/nvme5/new_clones/Smalltalk/QRCode' &
git clone https://github.com/moosetechnology/MooseIDE '/storage/nvme5/new_clones/Smalltalk/MooseIDE' &
git clone https://github.com/seandenigris/Living-Code '/storage/nvme5/new_clones/Smalltalk/Living-Code' &
git clone https://github.com/pharo-nosql/OmniBase '/storage/nvme5/new_clones/Smalltalk/OmniBase' &
git clone https://github.com/smartanvil/Keccak '/storage/nvme5/new_clones/Smalltalk/Keccak' &
git clone https://github.com/clementbera/Scorch '/storage/nvme5/new_clones/Smalltalk/Scorch' &
git clone https://github.com/JanBliznicenko/eleven '/storage/nvme5/new_clones/Smalltalk/eleven' &
git clone https://github.com/feenkcom/gtoolkit-glutin '/storage/nvme5/new_clones/Smalltalk/gtoolkit-glutin' &
git clone https://github.com/alacap/hashids-pharo '/storage/nvme5/new_clones/Smalltalk/hashids-pharo' &
git clone https://github.com/mumez/nagare-logger '/storage/nvme5/new_clones/Smalltalk/nagare-logger' &
git clone https://github.com/eMaringolo/pharo-bip39mnemonic '/storage/nvme5/new_clones/Smalltalk/pharo-bip39mnemonic' &
git clone https://github.com/moosetechnology/MooseAlgos '/storage/nvme5/new_clones/Smalltalk/MooseAlgos' &
git clone https://github.com/TelescopeSt/TelescopeCytoscape '/storage/nvme5/new_clones/Smalltalk/TelescopeCytoscape' &
git clone https://github.com/pharo-ai/ai '/storage/nvme5/new_clones/Smalltalk/ai' &
git clone https://github.com/PolyMathOrg/Domains '/storage/nvme5/new_clones/Smalltalk/Domains' &
git clone https://github.com/tom95/Pheno '/storage/nvme5/new_clones/Smalltalk/Pheno' &
git clone https://github.com/feenkcom/gt4gemstone '/storage/nvme5/new_clones/Smalltalk/gt4gemstone' &
git clone https://github.com/timfel/SCouchDB '/storage/nvme5/new_clones/Smalltalk/SCouchDB' &
git clone https://github.com/RichardAlexanderGreen/GivenWhenThen '/storage/nvme5/new_clones/Smalltalk/GivenWhenThen' &
git clone https://github.com/Rydier/SSDP '/storage/nvme5/new_clones/Smalltalk/SSDP' &
git clone https://github.com/frankshearar/Parsing-Derivatives '/storage/nvme5/new_clones/Smalltalk/Parsing-Derivatives' &
git clone https://github.com/KenDickey/Cuis-Smalltalk-BabySteps '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-BabySteps' &
git clone https://github.com/npapagna/cuis-code-coverage '/storage/nvme5/new_clones/Smalltalk/cuis-code-coverage' &
git clone https://github.com/feenkcom/gtoolkit-remote '/storage/nvme5/new_clones/Smalltalk/gtoolkit-remote' &
git clone https://github.com/hpi-swa-teaching/Algernon-Launcher-old '/storage/nvme5/new_clones/Smalltalk/Algernon-Launcher-old' &
git clone https://github.com/tinchodias/pharo-rita-history '/storage/nvme5/new_clones/Smalltalk/pharo-rita-history' &
git clone https://github.com/hpi-swa-teaching/poppy-print '/storage/nvme5/new_clones/Smalltalk/poppy-print' &
git clone https://github.com/tinchodias/BaselineBuilder '/storage/nvme5/new_clones/Smalltalk/BaselineBuilder' &
git clone https://github.com/dalehenrich/FSGit '/storage/nvme5/new_clones/Smalltalk/FSGit' &
git clone https://github.com/pavel-krivanek/CCodeGenerator '/storage/nvme5/new_clones/Smalltalk/CCodeGenerator' &
git clone https://github.com/ApptiveGrid/MoniBase '/storage/nvme5/new_clones/Smalltalk/MoniBase' &
git clone https://github.com/hernanmd/GraphViz '/storage/nvme5/new_clones/Smalltalk/GraphViz' &
git clone https://github.com/pavel-krivanek/Marvin '/storage/nvme5/new_clones/Smalltalk/Marvin' &
git clone https://github.com/DuneSt/Heimdall '/storage/nvme5/new_clones/Smalltalk/Heimdall' &
git clone https://github.com/SeasideSt/Seaside-old '/storage/nvme5/new_clones/Smalltalk/Seaside-old' &
git clone https://github.com/grpistoia/Atomic '/storage/nvme5/new_clones/Smalltalk/Atomic' &
git clone https://github.com/Pharophile/XmppTalk '/storage/nvme5/new_clones/Smalltalk/XmppTalk' &
git clone https://github.com/ba-st/Evelyn '/storage/nvme5/new_clones/Smalltalk/Evelyn' &
git clone https://github.com/Appeon/.NET-DataStore-Example '/storage/nvme5/new_clones/Smalltalk/.NET-DataStore-Example' &
git clone https://github.com/ironirc/Pharo-Oracle-Call-Interface '/storage/nvme5/new_clones/Smalltalk/Pharo-Oracle-Call-Interface' &
git clone https://github.com/yannij/Seaside-Quasar '/storage/nvme5/new_clones/Smalltalk/Seaside-Quasar' &
git clone https://github.com/Ducasse/OSC '/storage/nvme5/new_clones/Smalltalk/OSC' &
git clone https://github.com/lauritzthamsen/TraitClasses '/storage/nvme5/new_clones/Smalltalk/TraitClasses' &
git clone https://github.com/estebanlm/objcbridge '/storage/nvme5/new_clones/Smalltalk/objcbridge' &
git clone https://github.com/kilon/CPP '/storage/nvme5/new_clones/Smalltalk/CPP' &
git clone https://github.com/NDark/KobayashiMaruCommanderOS '/storage/nvme5/new_clones/Smalltalk/KobayashiMaruCommanderOS' &
git clone https://github.com/kilon/Ephestos '/storage/nvme5/new_clones/Smalltalk/Ephestos' &
git clone https://github.com/astares/Pharo-UDBC '/storage/nvme5/new_clones/Smalltalk/Pharo-UDBC' &
git clone https://github.com/hernanwilkinson/Cuis-Smalltalk-DenotativeObject '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-DenotativeObject' &
git clone https://github.com/hpi-swa/metacello-git '/storage/nvme5/new_clones/Smalltalk/metacello-git' &
git clone https://github.com/sadeq220/docs '/storage/nvme5/new_clones/Smalltalk/docs' &
git clone https://github.com/astares/Pharo-Harbour '/storage/nvme5/new_clones/Smalltalk/Pharo-Harbour' &
git clone https://github.com/khinsen/GT-SQLiteBrowser '/storage/nvme5/new_clones/Smalltalk/GT-SQLiteBrowser' &
git clone https://github.com/ba-st/Willow-Bootstrap '/storage/nvme5/new_clones/Smalltalk/Willow-Bootstrap' &
git clone https://github.com/massimo-nocentini/microkanrenst '/storage/nvme5/new_clones/Smalltalk/microkanrenst' &
git clone https://github.com/Ducasse/Cozy '/storage/nvme5/new_clones/Smalltalk/Cozy' &
git clone https://github.com/NoMod-Programming/Whiskers-2.8 '/storage/nvme5/new_clones/Smalltalk/Whiskers-2.8' &
git clone https://github.com/hpi-swa-teaching/WindowAcrobatics '/storage/nvme5/new_clones/Smalltalk/WindowAcrobatics' &
git clone https://github.com/pharo-GIS/Shapes '/storage/nvme5/new_clones/Smalltalk/Shapes' &
git clone https://github.com/pharo-project/pharo-llvmDisassembler '/storage/nvme5/new_clones/Smalltalk/pharo-llvmDisassembler' &
git clone https://github.com/feenkcom/gtoolkit-debugger '/storage/nvme5/new_clones/Smalltalk/gtoolkit-debugger' &
git clone https://github.com/jgfoster/WebGS '/storage/nvme5/new_clones/Smalltalk/WebGS' &
git clone https://github.com/PierceNg/libffidemo '/storage/nvme5/new_clones/Smalltalk/libffidemo' &
git clone https://github.com/the-tech-academy-1/developers '/storage/nvme5/new_clones/Smalltalk/developers' &
git clone https://github.com/hernanmd/COVID-2019 '/storage/nvme5/new_clones/Smalltalk/COVID-2019' &
git clone https://github.com/feenkcom/gtoolkit-inspector '/storage/nvme5/new_clones/Smalltalk/gtoolkit-inspector' &
git clone https://github.com/hpi-swa-teaching/SqueakIssueIntegration '/storage/nvme5/new_clones/Smalltalk/SqueakIssueIntegration' &
git clone https://github.com/ObjectProfile/Spy2 '/storage/nvme5/new_clones/Smalltalk/Spy2' &
git clone https://github.com/juliendelplanque/DrTests '/storage/nvme5/new_clones/Smalltalk/DrTests' &
git clone https://github.com/pharo-ai/Polyglot '/storage/nvme5/new_clones/Smalltalk/Polyglot' &
git clone https://github.com/khinsen/GT-OpenAlex '/storage/nvme5/new_clones/Smalltalk/GT-OpenAlex' &
git clone https://github.com/hellerve/gt4processing '/storage/nvme5/new_clones/Smalltalk/gt4processing' &
git clone https://github.com/ba-st/Kepler '/storage/nvme5/new_clones/Smalltalk/Kepler' &
git clone https://github.com/robvanlopik/Pots '/storage/nvme5/new_clones/Smalltalk/Pots' &
git clone https://github.com/feenkcom/PharoLink '/storage/nvme5/new_clones/Smalltalk/PharoLink' &
git clone https://github.com/brunobuzzi/BpmFlow '/storage/nvme5/new_clones/Smalltalk/BpmFlow' &
git clone https://github.com/olekscode/MLNeuralNetwork '/storage/nvme5/new_clones/Smalltalk/MLNeuralNetwork' &
git clone https://github.com/EiichiroIto/MicroWiz '/storage/nvme5/new_clones/Smalltalk/MicroWiz' &
git clone https://github.com/bonzini/gst-visualgst '/storage/nvme5/new_clones/Smalltalk/gst-visualgst' &
git clone https://github.com/jigyasa-grover/sQuick_new '/storage/nvme5/new_clones/Smalltalk/sQuick_new' &
git clone https://github.com/newapplesho/sendgrid-smalltalk '/storage/nvme5/new_clones/Smalltalk/sendgrid-smalltalk' &
git clone https://github.com/desromech/form-scene-graph '/storage/nvme5/new_clones/Smalltalk/form-scene-graph' &
git clone https://github.com/Cuis-Smalltalk/Morphic '/storage/nvme5/new_clones/Smalltalk/Morphic' &
git clone https://github.com/NicolasPetton/Grease '/storage/nvme5/new_clones/Smalltalk/Grease' &
git clone https://github.com/DuneSt/ChartJs '/storage/nvme5/new_clones/Smalltalk/ChartJs' &
git clone https://github.com/KenDickey/BeeYourself '/storage/nvme5/new_clones/Smalltalk/BeeYourself' &
git clone https://github.com/Ndochp/1c_fight_and_work '/storage/nvme5/new_clones/Smalltalk/1c_fight_and_work' &
git clone https://github.com/theseion/libgit2-pharo-bindings '/storage/nvme5/new_clones/Smalltalk/libgit2-pharo-bindings' &
git clone https://github.com/hpi-swa-teaching/OpenSqueakMap '/storage/nvme5/new_clones/Smalltalk/OpenSqueakMap' &
git clone https://github.com/estebanlm/TalkFFI '/storage/nvme5/new_clones/Smalltalk/TalkFFI' &
git clone https://github.com/pharo-iot/Firmata '/storage/nvme5/new_clones/Smalltalk/Firmata' &
git clone https://github.com/pharo-project/threadedFFI-Plugin '/storage/nvme5/new_clones/Smalltalk/threadedFFI-Plugin' &
git clone https://github.com/juliendelplanque/PostgreSQLParser '/storage/nvme5/new_clones/Smalltalk/PostgreSQLParser' &
git clone https://github.com/khinsen/PythonBridgeGToolkit '/storage/nvme5/new_clones/Smalltalk/PythonBridgeGToolkit' &
git clone https://github.com/eMaringolo/seaside-plotlyjs '/storage/nvme5/new_clones/Smalltalk/seaside-plotlyjs' &
git clone https://github.com/npapoylias/lands '/storage/nvme5/new_clones/Smalltalk/lands' &
git clone https://github.com/pharo-contributions/OSWinSubprocess '/storage/nvme5/new_clones/Smalltalk/OSWinSubprocess' &
git clone https://github.com/SergeStinckwich/PlayerST '/storage/nvme5/new_clones/Smalltalk/PlayerST' &
git clone https://github.com/brackendev/RSSTools-Pharo '/storage/nvme5/new_clones/Smalltalk/RSSTools-Pharo' &
git clone https://github.com/hpi-swa-teaching/Interactive-Profiling '/storage/nvme5/new_clones/Smalltalk/Interactive-Profiling' &
git clone https://github.com/pa2rdk/DRA818-2M-Transceiver '/storage/nvme5/new_clones/Smalltalk/DRA818-2M-Transceiver' &
git clone https://github.com/RMODINRIA/RoelTyper '/storage/nvme5/new_clones/Smalltalk/RoelTyper' &
git clone https://github.com/hpi-swa-lab/squeak-tracedebugger '/storage/nvme5/new_clones/Smalltalk/squeak-tracedebugger' &
git clone https://github.com/astares/Pharo-I18N '/storage/nvme5/new_clones/Smalltalk/Pharo-I18N' &
git clone https://github.com/botwhytho/LeShellSnippet '/storage/nvme5/new_clones/Smalltalk/LeShellSnippet' &
git clone https://github.com/hpi-swa-teaching/ToolBuilder '/storage/nvme5/new_clones/Smalltalk/ToolBuilder' &
git clone https://github.com/estebanlm/OmniBase '/storage/nvme5/new_clones/Smalltalk/OmniBase' &
git clone https://github.com/zecke/pharo-protobuf '/storage/nvme5/new_clones/Smalltalk/pharo-protobuf' &
git clone https://github.com/Assertores/ProjectAres '/storage/nvme5/new_clones/Smalltalk/ProjectAres' &
git clone https://github.com/aranega/pybridge '/storage/nvme5/new_clones/Smalltalk/pybridge' &
git clone https://github.com/pharo-contributions/EventRecorder '/storage/nvme5/new_clones/Smalltalk/EventRecorder' &
git clone https://github.com/astares/Pharo-Teachable '/storage/nvme5/new_clones/Smalltalk/Pharo-Teachable' &
git clone https://github.com/mumez/SCypherGraph '/storage/nvme5/new_clones/Smalltalk/SCypherGraph' &
git clone https://github.com/vitamink/Rei.Random '/storage/nvme5/new_clones/Smalltalk/Rei.Random' &
git clone https://github.com/codeZeilen/SMailDir '/storage/nvme5/new_clones/Smalltalk/SMailDir' &
git clone https://github.com/massung/squeak-dataframes '/storage/nvme5/new_clones/Smalltalk/squeak-dataframes' &
git clone https://github.com/nicolas-cellier-aka-nice/smallapack '/storage/nvme5/new_clones/Smalltalk/smallapack' &
git clone https://github.com/lifia-unlp/Tycho '/storage/nvme5/new_clones/Smalltalk/Tycho' &
git clone https://github.com/jingtaozf/literate-smalltalk '/storage/nvme5/new_clones/Smalltalk/literate-smalltalk' &
git clone https://github.com/cmfcmf/ReactS '/storage/nvme5/new_clones/Smalltalk/ReactS' &
git clone https://github.com/pharo-ai/data-partitioners '/storage/nvme5/new_clones/Smalltalk/data-partitioners' &
git clone https://github.com/JurajKubelka/PharoSprint '/storage/nvme5/new_clones/Smalltalk/PharoSprint' &
git clone https://github.com/badetitou/SmartTest '/storage/nvme5/new_clones/Smalltalk/SmartTest' &
git clone https://github.com/Ducasse/Chrysal '/storage/nvme5/new_clones/Smalltalk/Chrysal' &
git clone https://github.com/AgileArtificialIntelligence/PharoSourceCode '/storage/nvme5/new_clones/Smalltalk/PharoSourceCode' &
git clone https://github.com/medicka/graPharo '/storage/nvme5/new_clones/Smalltalk/graPharo' &
git clone https://github.com/kasperosterbye/PillarRichTextRender '/storage/nvme5/new_clones/Smalltalk/PillarRichTextRender' &
git clone https://github.com/NaveedAhmadHematmal/AdvancedSoftwareEngineering '/storage/nvme5/new_clones/Smalltalk/AdvancedSoftwareEngineering' &
git clone https://github.com/canol/iyziForum '/storage/nvme5/new_clones/Smalltalk/iyziForum' &
git clone https://github.com/pharo-contributions/ImageWorker '/storage/nvme5/new_clones/Smalltalk/ImageWorker' &
git clone https://github.com/dolphinsmalltalk/Contributions '/storage/nvme5/new_clones/Smalltalk/Contributions' &
git clone https://github.com/pharo-contributions/MethodProxies '/storage/nvme5/new_clones/Smalltalk/MethodProxies' &
git clone https://github.com/dtlewis290/Cuis-Smalltalk-CommandShell '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-CommandShell' &
git clone https://github.com/matthias-springer/space-cleanup '/storage/nvme5/new_clones/Smalltalk/space-cleanup' &
git clone https://github.com/dionisiydk/StateSpecs '/storage/nvme5/new_clones/Smalltalk/StateSpecs' &
git clone https://github.com/ObjectProfile/KerasBridge '/storage/nvme5/new_clones/Smalltalk/KerasBridge' &
git clone https://github.com/feenkcom/gt4opencv '/storage/nvme5/new_clones/Smalltalk/gt4opencv' &
git clone https://github.com/kasperosterbye/pharo-elucidator '/storage/nvme5/new_clones/Smalltalk/pharo-elucidator' &
git clone https://github.com/tomooda/PharoIM '/storage/nvme5/new_clones/Smalltalk/PharoIM' &
git clone https://github.com/namv22/GFL-Live2D-Viewer '/storage/nvme5/new_clones/Smalltalk/GFL-Live2D-Viewer' &
git clone https://github.com/pharo-contributions/Soup '/storage/nvme5/new_clones/Smalltalk/Soup' &
git clone https://github.com/noha/Foliage '/storage/nvme5/new_clones/Smalltalk/Foliage' &
git clone https://github.com/hpi-swa-teaching/SwaLint '/storage/nvme5/new_clones/Smalltalk/SwaLint' &
git clone https://github.com/pavel-krivanek/RefsHunter '/storage/nvme5/new_clones/Smalltalk/RefsHunter' &
git clone https://github.com/astares/Pharo-MessageFlowBrowser '/storage/nvme5/new_clones/Smalltalk/Pharo-MessageFlowBrowser' &
git clone https://github.com/ContentSide/LingX '/storage/nvme5/new_clones/Smalltalk/LingX' &
git clone https://github.com/pharo-contributions/OrderPreservingDictionary '/storage/nvme5/new_clones/Smalltalk/OrderPreservingDictionary' &
git clone https://github.com/capsulecorplab/patternbuffer '/storage/nvme5/new_clones/Smalltalk/patternbuffer' &
git clone https://github.com/peteruhnak/pharo-scripts '/storage/nvme5/new_clones/Smalltalk/pharo-scripts' &
git clone https://github.com/pdebruic/stripe-smalltalk '/storage/nvme5/new_clones/Smalltalk/stripe-smalltalk' &
git clone https://github.com/pavel-krivanek/NCurses '/storage/nvme5/new_clones/Smalltalk/NCurses' &
git clone https://github.com/hernanmd/merlin '/storage/nvme5/new_clones/Smalltalk/merlin' &
git clone https://github.com/joao-pedro-braz/Firmata-LiquidCrystalI2C '/storage/nvme5/new_clones/Smalltalk/Firmata-LiquidCrystalI2C' &
git clone https://github.com/myroslavarm/Experimental-Completion '/storage/nvme5/new_clones/Smalltalk/Experimental-Completion' &
git clone https://github.com/Epaminondaslage/OpenPLC '/storage/nvme5/new_clones/Smalltalk/OpenPLC' &
git clone https://github.com/juliendelplanque/turing-machine '/storage/nvme5/new_clones/Smalltalk/turing-machine' &
git clone https://github.com/smartanvil/SmartShackle '/storage/nvme5/new_clones/Smalltalk/SmartShackle' &
git clone https://github.com/chicoary/small-forth '/storage/nvme5/new_clones/Smalltalk/small-forth' &
git clone https://github.com/ba-st/Sagan '/storage/nvme5/new_clones/Smalltalk/Sagan' &
git clone https://github.com/ericvanderwal/postprocess_playmaker '/storage/nvme5/new_clones/Smalltalk/postprocess_playmaker' &
git clone https://github.com/peteruhnak/xml-magritte-generator '/storage/nvme5/new_clones/Smalltalk/xml-magritte-generator' &
git clone https://github.com/feenkcom/gtoolkit-robocoder '/storage/nvme5/new_clones/Smalltalk/gtoolkit-robocoder' &
git clone https://github.com/mumez/FileMan '/storage/nvme5/new_clones/Smalltalk/FileMan' &
git clone https://github.com/cormas/ProjectFramework '/storage/nvme5/new_clones/Smalltalk/ProjectFramework' &
git clone https://github.com/GsSqueak/GsSqueak '/storage/nvme5/new_clones/Smalltalk/GsSqueak' &
git clone https://github.com/svenvc/Reddit '/storage/nvme5/new_clones/Smalltalk/Reddit' &
git clone https://github.com/hpi-swa-teaching/Liquid '/storage/nvme5/new_clones/Smalltalk/Liquid' &
git clone https://github.com/kilon/CPPBridge-old '/storage/nvme5/new_clones/Smalltalk/CPPBridge-old' &
git clone https://github.com/hpi-swa-lab/GlyphHub '/storage/nvme5/new_clones/Smalltalk/GlyphHub' &
git clone https://github.com/hpi-swa/MethodWrappers '/storage/nvme5/new_clones/Smalltalk/MethodWrappers' &
git clone https://github.com/feenkcom/gtoolkit-coder '/storage/nvme5/new_clones/Smalltalk/gtoolkit-coder' &
git clone https://github.com/feenkcom/gt4pharo '/storage/nvme5/new_clones/Smalltalk/gt4pharo' &
git clone https://github.com/lm/sublime-smalltalk-syntax '/storage/nvme5/new_clones/Smalltalk/sublime-smalltalk-syntax' &
git clone https://github.com/hpi-swa-teaching/UiDesigner '/storage/nvme5/new_clones/Smalltalk/UiDesigner' &
git clone https://github.com/pharo-contributions/Gettext '/storage/nvme5/new_clones/Smalltalk/Gettext' &
git clone https://github.com/codereport/Pharo-NDArray '/storage/nvme5/new_clones/Smalltalk/Pharo-NDArray' &
git clone https://github.com/pharo-contributions/XML-XMLParserHTML '/storage/nvme5/new_clones/Smalltalk/XML-XMLParserHTML' &
git clone https://github.com/alanrodas/PharoBot '/storage/nvme5/new_clones/Smalltalk/PharoBot' &
git clone https://github.com/pbella/Cuis-Ports '/storage/nvme5/new_clones/Smalltalk/Cuis-Ports' &
git clone https://github.com/jigyasa-grover/CORMAS-Pharo '/storage/nvme5/new_clones/Smalltalk/CORMAS-Pharo' &
git clone https://github.com/mkobetic/Xtreams '/storage/nvme5/new_clones/Smalltalk/Xtreams' &
git clone https://github.com/tomooda/HoneyGinger '/storage/nvme5/new_clones/Smalltalk/HoneyGinger' &
git clone https://github.com/mumez/squeak-ja '/storage/nvme5/new_clones/Smalltalk/squeak-ja' &
git clone https://github.com/estebanlm/pharo-posix-signal '/storage/nvme5/new_clones/Smalltalk/pharo-posix-signal' &
git clone https://github.com/hernanwilkinson/Pharo-Aconcagua '/storage/nvme5/new_clones/Smalltalk/Pharo-Aconcagua' &
git clone https://github.com/juliendelplanque/TypedSlot '/storage/nvme5/new_clones/Smalltalk/TypedSlot' &
git clone https://github.com/svenvc/pharo-lz4-tools '/storage/nvme5/new_clones/Smalltalk/pharo-lz4-tools' &
git clone https://github.com/majella67/TagGrid '/storage/nvme5/new_clones/Smalltalk/TagGrid' &
git clone https://github.com/thiagoslino/Cuis-Smalltalk-Chip8 '/storage/nvme5/new_clones/Smalltalk/Cuis-Smalltalk-Chip8' &
git clone https://github.com/hpi-swa/widgets '/storage/nvme5/new_clones/Smalltalk/widgets' &
git clone https://github.com/jgfoster/Jade '/storage/nvme5/new_clones/Smalltalk/Jade' &
git clone https://github.com/vast-community-hub/carrillon '/storage/nvme5/new_clones/Smalltalk/carrillon' &
