#!/bin/bash

git clone https://github.com/adafruit/Adafruit_CAD_Parts '/storage/nvme5/new_clones/SMT/Adafruit_CAD_Parts' &
git clone https://github.com/cvc5/cvc5 '/storage/nvme5/new_clones/SMT/cvc5' &
git clone https://github.com/Boolector/boolector '/storage/nvme5/new_clones/SMT/boolector' &
git clone https://github.com/bitwuzla/bitwuzla '/storage/nvme5/new_clones/SMT/bitwuzla' &
git clone https://github.com/ARMmbed/mbed-HDK '/storage/nvme5/new_clones/SMT/mbed-HDK' &
git clone https://github.com/ONEARMY/precious-plastic-kit '/storage/nvme5/new_clones/SMT/precious-plastic-kit' &
git clone https://github.com/ARMmbed/mbed-HDK-Eagle-Projects '/storage/nvme5/new_clones/SMT/mbed-HDK-Eagle-Projects' &
git clone https://github.com/dreal/dreal4 '/storage/nvme5/new_clones/SMT/dreal4' &
git clone https://github.com/eclsnowman/Eustathios-Spider-V2 '/storage/nvme5/new_clones/SMT/Eustathios-Spider-V2' &
git clone https://github.com/PL-ML/code2inv '/storage/nvme5/new_clones/SMT/code2inv' &
git clone https://github.com/Practical-Formal-Methods/storm '/storage/nvme5/new_clones/SMT/storm' &
git clone https://github.com/eth-sri/fastsmt '/storage/nvme5/new_clones/SMT/fastsmt' &
git clone https://github.com/hopv/rust-horn '/storage/nvme5/new_clones/SMT/rust-horn' &
git clone https://github.com/bzhan/holpy '/storage/nvme5/new_clones/SMT/holpy' &
git clone https://github.com/regb/cafesat '/storage/nvme5/new_clones/SMT/cafesat' &
git clone https://github.com/marmat/nikon-gp1-diy '/storage/nvme5/new_clones/SMT/nikon-gp1-diy' &
git clone https://github.com/regb/scala-smtlib '/storage/nvme5/new_clones/SMT/scala-smtlib' &
git clone https://github.com/matt-noonan/gdp-paper '/storage/nvme5/new_clones/SMT/gdp-paper' &
git clone https://github.com/Z3Prover/doc '/storage/nvme5/new_clones/SMT/doc' &
git clone https://github.com/c-cube/mc2 '/storage/nvme5/new_clones/SMT/mc2' &
git clone https://github.com/jamesbornholt/z3-ios '/storage/nvme5/new_clones/SMT/z3-ios' &
git clone https://github.com/SyGuS-Org/benchmarks '/storage/nvme5/new_clones/SMT/benchmarks' &
git clone https://github.com/awslabs/rust-smt-ir '/storage/nvme5/new_clones/SMT/rust-smt-ir' &
git clone https://github.com/Paradoxika/Skeptik '/storage/nvme5/new_clones/SMT/Skeptik' &
git clone https://github.com/RAKWireless/Awesome-WisBlock '/storage/nvme5/new_clones/SMT/Awesome-WisBlock' &
git clone https://github.com/PrintM3D/Promega '/storage/nvme5/new_clones/SMT/Promega' &
git clone https://github.com/TermCOMP/TPDB '/storage/nvme5/new_clones/SMT/TPDB' &
git clone https://github.com/paddygoat/WEEDINATOR '/storage/nvme5/new_clones/SMT/WEEDINATOR' &
git clone https://github.com/Z3Prover/z3test '/storage/nvme5/new_clones/SMT/z3test' &
git clone https://github.com/tip-org/benchmarks '/storage/nvme5/new_clones/SMT/benchmarks' &
git clone https://github.com/lucansky/BrainDeadMPPT '/storage/nvme5/new_clones/SMT/BrainDeadMPPT' &
git clone https://github.com/Sebastian-Schuetz/OPEN-SOURCE-LARGE-FORMAT-CNC-MACHINE-3D-PRINTER '/storage/nvme5/new_clones/SMT/OPEN-SOURCE-LARGE-FORMAT-CNC-MACHINE-3D-PRINTER' &
git clone https://github.com/c-cube/sidekick '/storage/nvme5/new_clones/SMT/sidekick' &
git clone https://github.com/julianthome/smtlibv2-grammar '/storage/nvme5/new_clones/SMT/smtlibv2-grammar' &
git clone https://github.com/zhoulaifu/xsat '/storage/nvme5/new_clones/SMT/xsat' &
git clone https://github.com/nathanielks/nice-nano-holder '/storage/nvme5/new_clones/SMT/nice-nano-holder' &
git clone https://github.com/ezyang/SMT-LIB-benchmarks-pytorch-shapes '/storage/nvme5/new_clones/SMT/SMT-LIB-benchmarks-pytorch-shapes' &
git clone https://github.com/open-ephys/flexDrive '/storage/nvme5/new_clones/SMT/flexDrive' &
git clone https://github.com/CVC4/CVC4-archived '/storage/nvme5/new_clones/SMT/CVC4-archived' &
git clone https://github.com/kframework/matching-logic-prover '/storage/nvme5/new_clones/SMT/matching-logic-prover' &
git clone https://github.com/GaloisInc/reopt-vcg '/storage/nvme5/new_clones/SMT/reopt-vcg' &
git clone https://github.com/britig/Hierarchical-Program-Triggered-RL '/storage/nvme5/new_clones/SMT/Hierarchical-Program-Triggered-RL' &
git clone https://github.com/IljaRukin/scara_plotter '/storage/nvme5/new_clones/SMT/scara_plotter' &
git clone https://github.com/giuspek/FormalMethods-2022 '/storage/nvme5/new_clones/SMT/FormalMethods-2022' &
git clone https://github.com/Columpio/RInGen '/storage/nvme5/new_clones/SMT/RInGen' &
git clone https://github.com/secure-foundations/mariposa '/storage/nvme5/new_clones/SMT/mariposa' &
git clone https://github.com/classicwuhao/qmaxuse '/storage/nvme5/new_clones/SMT/qmaxuse' &
git clone https://github.com/imandra-ai/batsmt '/storage/nvme5/new_clones/SMT/batsmt' &
git clone https://github.com/yoni206/lazybv2int '/storage/nvme5/new_clones/SMT/lazybv2int' &
git clone https://github.com/ahorn/benchmarks '/storage/nvme5/new_clones/SMT/benchmarks' &
git clone https://github.com/awslabs/rust-smt-ir-examples '/storage/nvme5/new_clones/SMT/rust-smt-ir-examples' &
git clone https://github.com/gernst/korn '/storage/nvme5/new_clones/SMT/korn' &
git clone https://github.com/csbl/platereader '/storage/nvme5/new_clones/SMT/platereader' &
git clone https://github.com/divyeshunadkat/VAJRA '/storage/nvme5/new_clones/SMT/VAJRA' &
git clone https://github.com/pimdegroot/Icebreaker-Case '/storage/nvme5/new_clones/SMT/Icebreaker-Case' &
git clone https://github.com/cdstanford/dz3-artifact '/storage/nvme5/new_clones/SMT/dz3-artifact' &
git clone https://github.com/MichalHe/amaya '/storage/nvme5/new_clones/SMT/amaya' &
git clone https://github.com/kuhar/smt-jit '/storage/nvme5/new_clones/SMT/smt-jit' &
git clone https://github.com/physical-computation/Warp-hardware '/storage/nvme5/new_clones/SMT/Warp-hardware' &
git clone https://github.com/mechtaev/maxsmt-playground '/storage/nvme5/new_clones/SMT/maxsmt-playground' &
git clone https://github.com/Wren6991/OpenILA '/storage/nvme5/new_clones/SMT/OpenILA' &
git clone https://github.com/GaloisInc/what4-solvers '/storage/nvme5/new_clones/SMT/what4-solvers' &
git clone https://github.com/sl-comp/SL-COMP19 '/storage/nvme5/new_clones/SMT/SL-COMP19' &
git clone https://github.com/chessai/diet '/storage/nvme5/new_clones/SMT/diet' &
git clone https://github.com/apalache-mc/apalache-tests '/storage/nvme5/new_clones/SMT/apalache-tests' &
git clone https://github.com/leonardoalt/chc_benchmarks_solidity '/storage/nvme5/new_clones/SMT/chc_benchmarks_solidity' &
git clone https://github.com/makaimann/Stanford-FAST '/storage/nvme5/new_clones/SMT/Stanford-FAST' &
git clone https://github.com/PatrickTrentin88/omt_python_examples '/storage/nvme5/new_clones/SMT/omt_python_examples' &
git clone https://github.com/UFESL/ISV '/storage/nvme5/new_clones/SMT/ISV' &
git clone https://github.com/tudo-aqua/jconstraints '/storage/nvme5/new_clones/SMT/jconstraints' &
git clone https://github.com/runtime-verification/benchmark-challenge-2018 '/storage/nvme5/new_clones/SMT/benchmark-challenge-2018' &
git clone https://github.com/cdstanford/regex-smt-benchmarks '/storage/nvme5/new_clones/SMT/regex-smt-benchmarks' &
