#!/bin/bash

git clone https://github.com/acemod/ACE3 '/storage/nvme5/new_clones/SQF/ACE3' &
git clone https://github.com/KillahPotatoes/KP-Liberation '/storage/nvme5/new_clones/SQF/KP-Liberation' &
git clone https://github.com/AsYetUntitled/Framework '/storage/nvme5/new_clones/SQF/Framework' &
git clone https://github.com/ALiVEOS/ALiVE.OS '/storage/nvme5/new_clones/SQF/ALiVE.OS' &
git clone https://github.com/nk3nny/LambsDanger '/storage/nvme5/new_clones/SQF/LambsDanger' &
git clone https://github.com/auQuiksilver/Apex-Framework '/storage/nvme5/new_clones/SQF/Apex-Framework' &
git clone https://github.com/Xeno69/Domination '/storage/nvme5/new_clones/SQF/Domination' &
git clone https://github.com/Defent/DMS_Exile '/storage/nvme5/new_clones/SQF/DMS_Exile' &
git clone https://github.com/A3Antistasi/A3-Antistasi '/storage/nvme5/new_clones/SQF/A3-Antistasi' &
git clone https://github.com/ArmaAchilles/Achilles '/storage/nvme5/new_clones/SQF/Achilles' &
git clone https://github.com/genesis92x/VcomAI-3.0 '/storage/nvme5/new_clones/SQF/VcomAI-3.0' &
git clone https://github.com/CaptainPStar/co10_Escape '/storage/nvme5/new_clones/SQF/co10_Escape' &
git clone https://github.com/ferstaberinde/F3 '/storage/nvme5/new_clones/SQF/F3' &
git clone https://github.com/RPFramework/RPFramework '/storage/nvme5/new_clones/SQF/RPFramework' &
git clone https://github.com/diwako/diwako_dui '/storage/nvme5/new_clones/SQF/diwako_dui' &
git clone https://github.com/GreuhZbug/greuh_liberation.Altis '/storage/nvme5/new_clones/SQF/greuh_liberation.Altis' &
git clone https://github.com/DUWS-R-Team/DUWS-R '/storage/nvme5/new_clones/SQF/DUWS-R' &
git clone https://github.com/zerty/Benny-Edition-CTI-0.97-Zerty-Modification '/storage/nvme5/new_clones/SQF/Benny-Edition-CTI-0.97-Zerty-Modification' &
git clone https://github.com/TMF3/TMF '/storage/nvme5/new_clones/SQF/TMF' &
git clone https://github.com/Lyeed/Framework_Tanoa_Life '/storage/nvme5/new_clones/SQF/Framework_Tanoa_Life' &
git clone https://github.com/Bjanski/ExAd '/storage/nvme5/new_clones/SQF/ExAd' &
git clone https://github.com/A3Antistasi/antistasi-1.x '/storage/nvme5/new_clones/SQF/antistasi-1.x' &
git clone https://github.com/alexcroox/R3 '/storage/nvme5/new_clones/SQF/R3' &
git clone https://github.com/secondcoming/a3_exile_occupation '/storage/nvme5/new_clones/SQF/a3_exile_occupation' &
git clone https://github.com/denisio/Dayz-Epoch-Linux-Server '/storage/nvme5/new_clones/SQF/Dayz-Epoch-Linux-Server' &
git clone https://github.com/ole1986/a3-admintoolkit '/storage/nvme5/new_clones/SQF/a3-admintoolkit' &
git clone https://github.com/dklollol/Olsen-Framework-Arma-3 '/storage/nvme5/new_clones/SQF/Olsen-Framework-Arma-3' &
git clone https://github.com/sethduda/AdvancedTowing '/storage/nvme5/new_clones/SQF/AdvancedTowing' &
git clone https://github.com/soulkobk/ArmA3_Scripts '/storage/nvme5/new_clones/SQF/ArmA3_Scripts' &
git clone https://github.com/Savage-Game-Design/Mike-Force '/storage/nvme5/new_clones/SQF/Mike-Force' &
git clone https://github.com/f3cuk/WICKED-AI '/storage/nvme5/new_clones/SQF/WICKED-AI' &
git clone https://github.com/Omnomios/DynamicBulwarks '/storage/nvme5/new_clones/SQF/DynamicBulwarks' &
git clone https://github.com/y0014984/Advanced-Equipment '/storage/nvme5/new_clones/SQF/Advanced-Equipment' &
git clone https://github.com/LordGolias/antistasi '/storage/nvme5/new_clones/SQF/antistasi' &
git clone https://github.com/hpy/Enigma_Exile_Revive '/storage/nvme5/new_clones/SQF/Enigma_Exile_Revive' &
git clone https://github.com/SnarkIndustries/DZAI '/storage/nvme5/new_clones/SQF/DZAI' &
git clone https://github.com/sethduda/AdvancedSlingLoading '/storage/nvme5/new_clones/SQF/AdvancedSlingLoading' &
git clone https://github.com/Wolfenswan/ws_fnc '/storage/nvme5/new_clones/SQF/ws_fnc' &
git clone https://github.com/Ppgtjmad/SimpleShops '/storage/nvme5/new_clones/SQF/SimpleShops' &
git clone https://github.com/sethduda/AdvancedTrainSimulator '/storage/nvme5/new_clones/SQF/AdvancedTrainSimulator' &
git clone https://github.com/gruppe-adler/grad-persistence '/storage/nvme5/new_clones/SQF/grad-persistence' &
git clone https://github.com/SceptreOfficial/Simplex-Support-Services '/storage/nvme5/new_clones/SQF/Simplex-Support-Services' &
git clone https://github.com/sethduda/AdvancedRappelling '/storage/nvme5/new_clones/SQF/AdvancedRappelling' &
git clone https://github.com/TMschar/A3RPGFramework '/storage/nvme5/new_clones/SQF/A3RPGFramework' &
git clone https://github.com/vos/dayz '/storage/nvme5/new_clones/SQF/dayz' &
git clone https://github.com/DevZupa/ZCP-A3-Exile '/storage/nvme5/new_clones/SQF/ZCP-A3-Exile' &
git clone https://github.com/sethduda/AdvancedUrbanRappelling '/storage/nvme5/new_clones/SQF/AdvancedUrbanRappelling' &
git clone https://github.com/TaktiCool/CLib '/storage/nvme5/new_clones/SQF/CLib' &
git clone https://github.com/fabrizioT/bCombat '/storage/nvme5/new_clones/SQF/bCombat' &
git clone https://github.com/Bradenm1/Evannex '/storage/nvme5/new_clones/SQF/Evannex' &
git clone https://github.com/realitymod/pra3 '/storage/nvme5/new_clones/SQF/pra3' &
git clone https://github.com/treendy/TRGM2.Malden '/storage/nvme5/new_clones/SQF/TRGM2.Malden' &
git clone https://github.com/aussie-battler/GEORGE-FLOROS-GR-Arma3-Scripts '/storage/nvme5/new_clones/SQF/GEORGE-FLOROS-GR-Arma3-Scripts' &
git clone https://github.com/diwako/diwako_cbrn '/storage/nvme5/new_clones/SQF/diwako_cbrn' &
git clone https://github.com/Crowdedlight/Crows-Electronic-Warfare '/storage/nvme5/new_clones/SQF/Crows-Electronic-Warfare' &
git clone https://github.com/mrnotsoevil/Black-Lagoon-Altis-Life '/storage/nvme5/new_clones/SQF/Black-Lagoon-Altis-Life' &
git clone https://github.com/completely-burned/glowing-octo-shame-arma2 '/storage/nvme5/new_clones/SQF/glowing-octo-shame-arma2' &
git clone https://github.com/gruppe-adler/grad_civs '/storage/nvme5/new_clones/SQF/grad_civs' &
git clone https://github.com/Gamer-Dad/warlordsredux.altis '/storage/nvme5/new_clones/SQF/warlordsredux.altis' &
git clone https://github.com/antoinebidault/DynamicCivilWar '/storage/nvme5/new_clones/SQF/DynamicCivilWar' &
git clone https://github.com/horbin/FuMS-HC-Exile '/storage/nvme5/new_clones/SQF/FuMS-HC-Exile' &
git clone https://github.com/patrix87/ExileZ-2 '/storage/nvme5/new_clones/SQF/ExileZ-2' &
git clone https://github.com/TaktiCool/Streamator '/storage/nvme5/new_clones/SQF/Streamator' &
git clone https://github.com/TaktiCool/ArmaAtWar '/storage/nvme5/new_clones/SQF/ArmaAtWar' &
git clone https://github.com/HallyG/HALs_Store '/storage/nvme5/new_clones/SQF/HALs_Store' &
git clone https://github.com/IT07/a3_vemf_reloaded '/storage/nvme5/new_clones/SQF/a3_vemf_reloaded' &
git clone https://github.com/Jeroen-Notenbomer/Limited-Arsenal '/storage/nvme5/new_clones/SQF/Limited-Arsenal' &
git clone https://github.com/Vampurica/DZMS-DayZMissionSystem '/storage/nvme5/new_clones/SQF/DZMS-DayZMissionSystem' &
git clone https://github.com/RyanTT/DynamicMarket '/storage/nvme5/new_clones/SQF/DynamicMarket' &
git clone https://github.com/ArmaForces/Mods '/storage/nvme5/new_clones/SQF/Mods' &
git clone https://github.com/diwako/stalker_anomalies '/storage/nvme5/new_clones/SQF/stalker_anomalies' &
git clone https://github.com/farooqaaa/far_revive '/storage/nvme5/new_clones/SQF/far_revive' &
git clone https://github.com/jshear95/ArmaTerminal '/storage/nvme5/new_clones/SQF/ArmaTerminal' &
git clone https://github.com/shaygman/mcc_sandbox.Altis '/storage/nvme5/new_clones/SQF/mcc_sandbox.Altis' &
git clone https://github.com/gianni001/ExileReborn '/storage/nvme5/new_clones/SQF/ExileReborn' &
git clone https://github.com/pennyworth12345/ConfigDumpFileIO '/storage/nvme5/new_clones/SQF/ConfigDumpFileIO' &
git clone https://github.com/Asaayu/integrated-voice-control-system '/storage/nvme5/new_clones/SQF/integrated-voice-control-system' &
git clone https://github.com/Pergor/ADV_Medical '/storage/nvme5/new_clones/SQF/ADV_Medical' &
git clone https://github.com/DreadPirateAU/JEBUS '/storage/nvme5/new_clones/SQF/JEBUS' &
git clone https://github.com/diwako/ACRE2-Custom-Signal-Calculation '/storage/nvme5/new_clones/SQF/ACRE2-Custom-Signal-Calculation' &
git clone https://github.com/mgkid3310/AWESome '/storage/nvme5/new_clones/SQF/AWESome' &
git clone https://github.com/secondcoming/ExileTravellingTrader '/storage/nvme5/new_clones/SQF/ExileTravellingTrader' &
git clone https://github.com/maca134/exile-server-package '/storage/nvme5/new_clones/SQF/exile-server-package' &
git clone https://github.com/SkaceKamen/random-infantry-skirmish '/storage/nvme5/new_clones/SQF/random-infantry-skirmish' &
git clone https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3 '/storage/nvme5/new_clones/SQF/Olsen-Framework-Arma-3' &
git clone https://github.com/kami-/plank '/storage/nvme5/new_clones/SQF/plank' &
git clone https://github.com/MrEliasen/Supremacy-Framework '/storage/nvme5/new_clones/SQF/Supremacy-Framework' &
git clone https://github.com/Kolmain/Evolution-A3 '/storage/nvme5/new_clones/SQF/Evolution-A3' &
git clone https://github.com/itc-addons/ITC_Land_Systems '/storage/nvme5/new_clones/SQF/ITC_Land_Systems' &
git clone https://github.com/sethduda/AIC '/storage/nvme5/new_clones/SQF/AIC' &
git clone https://github.com/Fickdichhard/A3XAI-UPLOAD '/storage/nvme5/new_clones/SQF/A3XAI-UPLOAD' &
git clone https://github.com/x-cessive/Exile '/storage/nvme5/new_clones/SQF/Exile' &
git clone https://github.com/v-Arma/a3g-loadout '/storage/nvme5/new_clones/SQF/a3g-loadout' &
git clone https://github.com/DerZade/BackpackOnChest '/storage/nvme5/new_clones/SQF/BackpackOnChest' &
git clone https://github.com/ConnorAU/A3ExtendedFunctionViewer '/storage/nvme5/new_clones/SQF/A3ExtendedFunctionViewer' &
git clone https://github.com/gruppe-adler/grad-fortifications '/storage/nvme5/new_clones/SQF/grad-fortifications' &
git clone https://github.com/Vampurica/VEMF '/storage/nvme5/new_clones/SQF/VEMF' &
git clone https://github.com/maca134/m3e_3den '/storage/nvme5/new_clones/SQF/m3e_3den' &
git clone https://github.com/ebayShopper/ESSV3 '/storage/nvme5/new_clones/SQF/ESSV3' &
git clone https://github.com/ravmustang/eXpochVectorBuild4Exile '/storage/nvme5/new_clones/SQF/eXpochVectorBuild4Exile' &
git clone https://github.com/JakubNei/a3-misc '/storage/nvme5/new_clones/SQF/a3-misc' &
git clone https://github.com/oiad/virtualGarage '/storage/nvme5/new_clones/SQF/virtualGarage' &
git clone https://github.com/DavisBrown723/SpyderAddons '/storage/nvme5/new_clones/SQF/SpyderAddons' &
git clone https://github.com/DextroNC/Framework '/storage/nvme5/new_clones/SQF/Framework' &
git clone https://github.com/ConnorAU/A3AnimatePAA '/storage/nvme5/new_clones/SQF/A3AnimatePAA' &
git clone https://github.com/rscaptainjack/ZOMBIES_CODE '/storage/nvme5/new_clones/SQF/ZOMBIES_CODE' &
git clone https://github.com/Arma-TCL-TypeX/TCL-TypeX-docs '/storage/nvme5/new_clones/SQF/TCL-TypeX-docs' &
git clone https://github.com/ostinelli/SCAR_UCM '/storage/nvme5/new_clones/SQF/SCAR_UCM' &
git clone https://github.com/ToxaBes2/ADR-Spec-Ops '/storage/nvme5/new_clones/SQF/ADR-Spec-Ops' &
git clone https://github.com/alezm00/ARMA-3-3D-Progress-Bar '/storage/nvme5/new_clones/SQF/ARMA-3-3D-Progress-Bar' &
git clone https://github.com/SavageCDN/DAC_A3 '/storage/nvme5/new_clones/SQF/DAC_A3' &
git clone https://github.com/AriesLR/Exile-AI-Missions '/storage/nvme5/new_clones/SQF/Exile-AI-Missions' &
git clone https://github.com/TEHGAM/ADR '/storage/nvme5/new_clones/SQF/ADR' &
git clone https://github.com/RimBlock/Epoch '/storage/nvme5/new_clones/SQF/Epoch' &
git clone https://github.com/gruppe-adler/grad-listBuymenu '/storage/nvme5/new_clones/SQF/grad-listBuymenu' &
git clone https://github.com/broma-arma/BromA-A3-Framework-Mark3 '/storage/nvme5/new_clones/SQF/BromA-A3-Framework-Mark3' &
git clone https://github.com/KillahPotatoes/KP-A3-Scripts '/storage/nvme5/new_clones/SQF/KP-A3-Scripts' &
git clone https://github.com/rebelvg/klpq_musicRadio '/storage/nvme5/new_clones/SQF/klpq_musicRadio' &
git clone https://github.com/withoutx/a3s_epoch_0103 '/storage/nvme5/new_clones/SQF/a3s_epoch_0103' &
git clone https://github.com/Phantomsmedia/Wavelength '/storage/nvme5/new_clones/SQF/Wavelength' &
git clone https://github.com/LISTINGS09/ZEI '/storage/nvme5/new_clones/SQF/ZEI' &
git clone https://github.com/JustOscarMike/iBuild '/storage/nvme5/new_clones/SQF/iBuild' &
git clone https://github.com/Rafael09ED/Arma '/storage/nvme5/new_clones/SQF/Arma' &
git clone https://github.com/Project-Hatchet/Interaction-Framework '/storage/nvme5/new_clones/SQF/Interaction-Framework' &
git clone https://github.com/CoopR-Mod/CoopR-Mod '/storage/nvme5/new_clones/SQF/CoopR-Mod' &
git clone https://github.com/X39/XMS2 '/storage/nvme5/new_clones/SQF/XMS2' &
git clone https://github.com/CRE4MPIE/StatusBar '/storage/nvme5/new_clones/SQF/StatusBar' &
git clone https://github.com/lazyink/BattleRoyaleGames '/storage/nvme5/new_clones/SQF/BattleRoyaleGames' &
git clone https://github.com/T-800a/T8_Units '/storage/nvme5/new_clones/SQF/T8_Units' &
git clone https://github.com/SceptreOfficial/Simplex-Dialog-Framework '/storage/nvme5/new_clones/SQF/Simplex-Dialog-Framework' &
git clone https://github.com/ispan55/ExileMod-KillMessages '/storage/nvme5/new_clones/SQF/ExileMod-KillMessages' &
git clone https://github.com/JakubNei/a3-loadout '/storage/nvme5/new_clones/SQF/a3-loadout' &
git clone https://github.com/Armitxes/TakistanLife '/storage/nvme5/new_clones/SQF/TakistanLife' &
git clone https://github.com/rambo/arma3_missions '/storage/nvme5/new_clones/SQF/arma3_missions' &
git clone https://github.com/KillahPotatoes/arma.warfare '/storage/nvme5/new_clones/SQF/arma.warfare' &
git clone https://github.com/arma3/SQF-Gems '/storage/nvme5/new_clones/SQF/SQF-Gems' &
git clone https://github.com/expung3d/Enhanced-Zeus-Modules '/storage/nvme5/new_clones/SQF/Enhanced-Zeus-Modules' &
git clone https://github.com/Tally-1/soldier-FSM '/storage/nvme5/new_clones/SQF/soldier-FSM' &
git clone https://github.com/BennyBoy-/BECTI '/storage/nvme5/new_clones/SQF/BECTI' &
git clone https://github.com/Mezo/Claim-Vehicles '/storage/nvme5/new_clones/SQF/Claim-Vehicles' &
git clone https://github.com/Pergor/ADV_MissionTemplate '/storage/nvme5/new_clones/SQF/ADV_MissionTemplate' &
git clone https://github.com/ivaylosp/message_boards '/storage/nvme5/new_clones/SQF/message_boards' &
git clone https://github.com/LAMBS-Nopryl/LMF.VR '/storage/nvme5/new_clones/SQF/LMF.VR' &
git clone https://github.com/IT07/ArmA3_exile_restartWarnings '/storage/nvme5/new_clones/SQF/ArmA3_exile_restartWarnings' &
git clone https://github.com/DarthRogue/Exile-Heli-Crashes '/storage/nvme5/new_clones/SQF/Exile-Heli-Crashes' &
git clone https://github.com/alganthe/Co-ops '/storage/nvme5/new_clones/SQF/Co-ops' &
git clone https://github.com/ConnorAU/A3GunGame '/storage/nvme5/new_clones/SQF/A3GunGame' &
git clone https://github.com/auQuiksilver/Soldier-Tracker '/storage/nvme5/new_clones/SQF/Soldier-Tracker' &
git clone https://github.com/ARandy-BADPMC/Bad-Company-Operation-Chainbreaker '/storage/nvme5/new_clones/SQF/Bad-Company-Operation-Chainbreaker' &
git clone https://github.com/raymix/SnapPro '/storage/nvme5/new_clones/SQF/SnapPro' &
git clone https://github.com/Mezo/MostWanted '/storage/nvme5/new_clones/SQF/MostWanted' &
git clone https://github.com/jweisner/Exile-ClaimCrates '/storage/nvme5/new_clones/SQF/Exile-ClaimCrates' &
git clone https://github.com/diwako/armor_plates_system '/storage/nvme5/new_clones/SQF/armor_plates_system' &
git clone https://github.com/TMNFr33d0m/A3M-PMC-Simulator '/storage/nvme5/new_clones/SQF/A3M-PMC-Simulator' &
git clone https://github.com/Giallustio/HeartsAndMinds '/storage/nvme5/new_clones/SQF/HeartsAndMinds' &
git clone https://github.com/phire0/A3FL '/storage/nvme5/new_clones/SQF/A3FL' &
git clone https://github.com/vitalymind/XM8_repairMate '/storage/nvme5/new_clones/SQF/XM8_repairMate' &
git clone https://github.com/diwako/playabledog '/storage/nvme5/new_clones/SQF/playabledog' &
git clone https://github.com/vitalymind/XM8_apps_improved '/storage/nvme5/new_clones/SQF/XM8_apps_improved' &
git clone https://github.com/Ghostrider-DbD-/GMS_RC '/storage/nvme5/new_clones/SQF/GMS_RC' &
git clone https://github.com/MGTDB/Exile_Abandon_Territory '/storage/nvme5/new_clones/SQF/Exile_Abandon_Territory' &
git clone https://github.com/Sparker95/Layout-Manager '/storage/nvme5/new_clones/SQF/Layout-Manager' &
git clone https://github.com/ahoys/Actionbuilder '/storage/nvme5/new_clones/SQF/Actionbuilder' &
git clone https://github.com/LAxemann/L_ambiDrive '/storage/nvme5/new_clones/SQF/L_ambiDrive' &
git clone https://github.com/R3voA3/Simple-Conversation-Script '/storage/nvme5/new_clones/SQF/Simple-Conversation-Script' &
git clone https://github.com/CombinedArmsGaming/F3_CA '/storage/nvme5/new_clones/SQF/F3_CA' &
git clone https://github.com/Jigsor/BMR_Insurgency.Altis '/storage/nvme5/new_clones/SQF/BMR_Insurgency.Altis' &
git clone https://github.com/G3rrus/LMF_Revised '/storage/nvme5/new_clones/SQF/LMF_Revised' &
git clone https://github.com/y0014984/pps '/storage/nvme5/new_clones/SQF/pps' &
git clone https://github.com/Savage-Game-Design/Paradigm '/storage/nvme5/new_clones/SQF/Paradigm' &
git clone https://github.com/Patapignouf/RandomPatrolGenerator '/storage/nvme5/new_clones/SQF/RandomPatrolGenerator' &
git clone https://github.com/501stLegionA3/501st-Missions '/storage/nvme5/new_clones/SQF/501st-Missions' &
git clone https://github.com/PC-Gamercom/pcg_tanoa '/storage/nvme5/new_clones/SQF/pcg_tanoa' &
git clone https://github.com/WilliamJBrown/Re-Worked-WAI-0.17 '/storage/nvme5/new_clones/SQF/Re-Worked-WAI-0.17' &
git clone https://github.com/snkman/Public '/storage/nvme5/new_clones/SQF/Public' &
git clone https://github.com/DomT602/Altis_Scriptorium '/storage/nvme5/new_clones/SQF/Altis_Scriptorium' &
git clone https://github.com/10Dozen/dzn_tSFramework '/storage/nvme5/new_clones/SQF/dzn_tSFramework' &
git clone https://github.com/preister/Celts_Altis_Life '/storage/nvme5/new_clones/SQF/Celts_Altis_Life' &
git clone https://github.com/Tenga/Arma-3-Fluid-Door-Opening '/storage/nvme5/new_clones/SQF/Arma-3-Fluid-Door-Opening' &
git clone https://github.com/code34/war-in-takistan '/storage/nvme5/new_clones/SQF/war-in-takistan' &
git clone https://github.com/FatLurch/ARMACOM '/storage/nvme5/new_clones/SQF/ARMACOM' &
git clone https://github.com/56curious/VKN_Official_Mod '/storage/nvme5/new_clones/SQF/VKN_Official_Mod' &
git clone https://github.com/xDodo/exile_rearm '/storage/nvme5/new_clones/SQF/exile_rearm' &
git clone https://github.com/secondcoming/Arma3-Epoch-Lootspawner '/storage/nvme5/new_clones/SQF/Arma3-Epoch-Lootspawner' &
git clone https://github.com/Crito-VanaheimServers/Working-Drag-Dead-Body-Script-For-Exile '/storage/nvme5/new_clones/SQF/Working-Drag-Dead-Body-Script-For-Exile' &
git clone https://github.com/zulu-alpha/zamf '/storage/nvme5/new_clones/SQF/zamf' &
git clone https://github.com/fencr0c/fen_a3 '/storage/nvme5/new_clones/SQF/fen_a3' &
git clone https://github.com/TheTimidShade/TTS-Cloak '/storage/nvme5/new_clones/SQF/TTS-Cloak' &
git clone https://github.com/10Dozen/dzn_dynai '/storage/nvme5/new_clones/SQF/dzn_dynai' &
git clone https://github.com/horbin/FuMS-HC-Server '/storage/nvme5/new_clones/SQF/FuMS-HC-Server' &
git clone https://github.com/EpochSC/SingleCurrencyBanking '/storage/nvme5/new_clones/SQF/SingleCurrencyBanking' &
git clone https://github.com/Jenartor/exile-vehicle_spawn_with_inventory '/storage/nvme5/new_clones/SQF/exile-vehicle_spawn_with_inventory' &
git clone https://github.com/slb2k11/Exile_R3F '/storage/nvme5/new_clones/SQF/Exile_R3F' &
git clone https://github.com/maca134/m3editor '/storage/nvme5/new_clones/SQF/m3editor' &
git clone https://github.com/Jigsor/BMR-Insurgency '/storage/nvme5/new_clones/SQF/BMR-Insurgency' &
git clone https://github.com/ole1986/a3-exile-scratchie '/storage/nvme5/new_clones/SQF/a3-exile-scratchie' &
git clone https://github.com/nabeky/a3_exile_lootbox '/storage/nvme5/new_clones/SQF/a3_exile_lootbox' &
git clone https://github.com/Ignatz-HeMan/Ignatz_Tools '/storage/nvme5/new_clones/SQF/Ignatz_Tools' &
git clone https://github.com/gruppe-adler/grad-moneyMenu '/storage/nvme5/new_clones/SQF/grad-moneyMenu' &
git clone https://github.com/code34/real_weather_mission.Altis '/storage/nvme5/new_clones/SQF/real_weather_mission.Altis' &
git clone https://github.com/Porkeld/A3xai-2.3 '/storage/nvme5/new_clones/SQF/A3xai-2.3' &
git clone https://github.com/LISTINGS09/A3_Mission_Generator '/storage/nvme5/new_clones/SQF/A3_Mission_Generator' &
git clone https://github.com/DarthRogue/Status_Bar '/storage/nvme5/new_clones/SQF/Status_Bar' &
git clone https://github.com/Theseus-Aegis/Olympus '/storage/nvme5/new_clones/SQF/Olympus' &
git clone https://github.com/gruppe-adler/TvT_BreakingContact.Stratis '/storage/nvme5/new_clones/SQF/TvT_BreakingContact.Stratis' &
git clone https://github.com/RimantasGalvonas/Arma-3-AI-vs-AI-Battle-Scenario-Template '/storage/nvme5/new_clones/SQF/Arma-3-AI-vs-AI-Battle-Scenario-Template' &
