#!/bin/bash

git clone https://github.com/cahyadsn/wilayah '/storage/nvme5/new_clones/SQL/wilayah' &
git clone https://github.com/Thomas-George-T/HackerRank-SQL-Challenges-Solutions '/storage/nvme5/new_clones/SQL/HackerRank-SQL-Challenges-Solutions' &
git clone https://github.com/basedosdados/sdk '/storage/nvme5/new_clones/SQL/sdk' &
git clone https://github.com/brunocampos01/banco-de-dados '/storage/nvme5/new_clones/SQL/banco-de-dados' &
git clone https://github.com/Velir/dbt-ga4 '/storage/nvme5/new_clones/SQL/dbt-ga4' &
git clone https://github.com/tony-landis/agilebill '/storage/nvme5/new_clones/SQL/agilebill' &
git clone https://github.com/dhaval1406/SQL '/storage/nvme5/new_clones/SQL/SQL' &
git clone https://github.com/Snowflake-Labs/dbt_constraints '/storage/nvme5/new_clones/SQL/dbt_constraints' &
git clone https://github.com/cahyadsn/daerah '/storage/nvme5/new_clones/SQL/daerah' &
git clone https://github.com/leehach/census-postgres '/storage/nvme5/new_clones/SQL/census-postgres' &
git clone https://github.com/SparkhoundSQL/sql-server-toolbox '/storage/nvme5/new_clones/SQL/sql-server-toolbox' &
git clone https://github.com/ssahibsingh/Social-Media-Database-Project '/storage/nvme5/new_clones/SQL/Social-Media-Database-Project' &
git clone https://github.com/ndleah/8-Week-SQL-Challenge '/storage/nvme5/new_clones/SQL/8-Week-SQL-Challenge' &
git clone https://github.com/mgramin/malewicz '/storage/nvme5/new_clones/SQL/malewicz' &
git clone https://github.com/sunnotes/Ali-Data-Mining '/storage/nvme5/new_clones/SQL/Ali-Data-Mining' &
git clone https://github.com/TrinityCore/TDB_4.3.4_NLU '/storage/nvme5/new_clones/SQL/TDB_4.3.4_NLU' &
git clone https://github.com/mattDevigili/dms-smm695 '/storage/nvme5/new_clones/SQL/dms-smm695' &
git clone https://github.com/cahyadsn/db_rajaongkir '/storage/nvme5/new_clones/SQL/db_rajaongkir' &
git clone https://github.com/fab-geocommuns/RNB '/storage/nvme5/new_clones/SQL/RNB' &
git clone https://github.com/biljana-zobenica/SQL-complete-tutorial '/storage/nvme5/new_clones/SQL/SQL-complete-tutorial' &
git clone https://github.com/shivamgarg444/Cyclistic-Case-Study '/storage/nvme5/new_clones/SQL/Cyclistic-Case-Study' &
git clone https://github.com/ybg345/sql-hands-on '/storage/nvme5/new_clones/SQL/sql-hands-on' &
git clone https://github.com/Alexsandro-01/mysql '/storage/nvme5/new_clones/SQL/mysql' &
git clone https://github.com/FL-Marine/8-Week-SQL-Challenge '/storage/nvme5/new_clones/SQL/8-Week-SQL-Challenge' &
git clone https://github.com/ndleah/people-data-analysis '/storage/nvme5/new_clones/SQL/people-data-analysis' &
git clone https://github.com/ritakalach/sqlzoo-solutions '/storage/nvme5/new_clones/SQL/sqlzoo-solutions' &
git clone https://github.com/jhajagos/DocGraph '/storage/nvme5/new_clones/SQL/DocGraph' &
git clone https://github.com/pietdaniel/poetification '/storage/nvme5/new_clones/SQL/poetification' &
git clone https://github.com/longwall/voynich_manchu_oradb '/storage/nvme5/new_clones/SQL/voynich_manchu_oradb' &
git clone https://github.com/andrewmunro/Vanilla '/storage/nvme5/new_clones/SQL/Vanilla' &
git clone https://github.com/ndleah/health-analysis '/storage/nvme5/new_clones/SQL/health-analysis' &
git clone https://github.com/kolorobot/quartz-jee-demo '/storage/nvme5/new_clones/SQL/quartz-jee-demo' &
git clone https://github.com/thatjpcsguy/shorts '/storage/nvme5/new_clones/SQL/shorts' &
git clone https://github.com/sfc-gh-dflippo/snowflake-dbt-demo '/storage/nvme5/new_clones/SQL/snowflake-dbt-demo' &
git clone https://github.com/folio-org/folio-analytics '/storage/nvme5/new_clones/SQL/folio-analytics' &
git clone https://github.com/Flowminder/COVID-19 '/storage/nvme5/new_clones/SQL/COVID-19' &
git clone https://github.com/valencprado/mysql-colinha '/storage/nvme5/new_clones/SQL/mysql-colinha' &
git clone https://github.com/nextail/pulpocon-data-pipelines '/storage/nvme5/new_clones/SQL/pulpocon-data-pipelines' &
git clone https://github.com/bharathguntreddi3/Oracle_DB_SSMS_Development '/storage/nvme5/new_clones/SQL/Oracle_DB_SSMS_Development' &
git clone https://github.com/01walid/Algerian-Wilayas '/storage/nvme5/new_clones/SQL/Algerian-Wilayas' &
git clone https://github.com/DFE-Digital/gias-query-tool '/storage/nvme5/new_clones/SQL/gias-query-tool' &
git clone https://github.com/piotrsobecki/jSQLtuner '/storage/nvme5/new_clones/SQL/jSQLtuner' &
git clone https://github.com/fhoffa/AdventOfCodeSQL '/storage/nvme5/new_clones/SQL/AdventOfCodeSQL' &
git clone https://github.com/ndleah/northwind '/storage/nvme5/new_clones/SQL/northwind' &
git clone https://github.com/dwijendra626/DataAnalysis_and_Visualization_Projects '/storage/nvme5/new_clones/SQL/DataAnalysis_and_Visualization_Projects' &
git clone https://github.com/ShawnStrasser/ATSPM_Aggregation '/storage/nvme5/new_clones/SQL/ATSPM_Aggregation' &
git clone https://github.com/grahamwetzler/advent-of-code-dbt-2022 '/storage/nvme5/new_clones/SQL/advent-of-code-dbt-2022' &
git clone https://github.com/vipul-shinde/people-analytics-cs '/storage/nvme5/new_clones/SQL/people-analytics-cs' &
git clone https://github.com/Emon-ProCoder7/sql-Command-Repository '/storage/nvme5/new_clones/SQL/sql-Command-Repository' &
git clone https://github.com/cistoner/Lstore '/storage/nvme5/new_clones/SQL/Lstore' &
git clone https://github.com/vipul-shinde/marketing-analytics-cs '/storage/nvme5/new_clones/SQL/marketing-analytics-cs' &
git clone https://github.com/simandebvu/SQL-Zoo '/storage/nvme5/new_clones/SQL/SQL-Zoo' &
git clone https://github.com/Prakashdeveloper03/Leetcode-SQL '/storage/nvme5/new_clones/SQL/Leetcode-SQL' &
git clone https://github.com/SANKALP1011/LibraryDatabase '/storage/nvme5/new_clones/SQL/LibraryDatabase' &
git clone https://github.com/ShenHongFei/dolphindb-vs-influxdb '/storage/nvme5/new_clones/SQL/dolphindb-vs-influxdb' &
git clone https://github.com/hacker9/Donor9 '/storage/nvme5/new_clones/SQL/Donor9' &
git clone https://github.com/sondosaabed/TNB-MySQL '/storage/nvme5/new_clones/SQL/TNB-MySQL' &
git clone https://github.com/Oyebamiji-Micheal/100-Days-of-SQL-Beginner-to-Advance '/storage/nvme5/new_clones/SQL/100-Days-of-SQL-Beginner-to-Advance' &
git clone https://github.com/artie93/When-Was-the-Golden-Age-of-Video-Games- '/storage/nvme5/new_clones/SQL/When-Was-the-Golden-Age-of-Video-Games-' &
git clone https://github.com/shukkkur/International-Debt-Statistics '/storage/nvme5/new_clones/SQL/International-Debt-Statistics' &
git clone https://github.com/manaswikamila05/RSVP-Movies '/storage/nvme5/new_clones/SQL/RSVP-Movies' &
git clone https://github.com/ndleah/dvd-rental-marketing-analytics '/storage/nvme5/new_clones/SQL/dvd-rental-marketing-analytics' &
git clone https://github.com/echlebek/nutes '/storage/nvme5/new_clones/SQL/nutes' &
git clone https://github.com/basedosdados/archived-queries-basedosdados '/storage/nvme5/new_clones/SQL/archived-queries-basedosdados' &
git clone https://github.com/AlysterF/8week-SQL-challenge '/storage/nvme5/new_clones/SQL/8week-SQL-challenge' &
git clone https://github.com/Prakashdeveloper03/HackerSQL '/storage/nvme5/new_clones/SQL/HackerSQL' &
git clone https://github.com/zikwall/clickhouse-docs '/storage/nvme5/new_clones/SQL/clickhouse-docs' &
git clone https://github.com/ndleah/bitcoin-prices-analysis '/storage/nvme5/new_clones/SQL/bitcoin-prices-analysis' &
git clone https://github.com/FL-Marine/SQL_best_practices '/storage/nvme5/new_clones/SQL/SQL_best_practices' &
git clone https://github.com/SelimHorri/oracle-sql-handy-queries '/storage/nvme5/new_clones/SQL/oracle-sql-handy-queries' &
git clone https://github.com/MHeydari/BCrypt-algorithm-in-Oracle-plsql '/storage/nvme5/new_clones/SQL/BCrypt-algorithm-in-Oracle-plsql' &
git clone https://github.com/sr320/ipython_nb '/storage/nvme5/new_clones/SQL/ipython_nb' &
git clone https://github.com/FL-Marine/Health-Analytics-Mini-Case-Study '/storage/nvme5/new_clones/SQL/Health-Analytics-Mini-Case-Study' &
git clone https://github.com/j-b-ferguson/relational-database-design-and-test '/storage/nvme5/new_clones/SQL/relational-database-design-and-test' &
git clone https://github.com/qanhnn12/SQL-Leetcode-Challenge-Solutions '/storage/nvme5/new_clones/SQL/SQL-Leetcode-Challenge-Solutions' &
git clone https://github.com/wetory/sql-server-maintenance '/storage/nvme5/new_clones/SQL/sql-server-maintenance' &
git clone https://github.com/wetory/sql-server-replication-monitoring '/storage/nvme5/new_clones/SQL/sql-server-replication-monitoring' &
