#!/bin/bash

git clone https://github.com/CafeFPS/r5_flowstate '/storage/nvme5/new_clones/Squirrel/r5_flowstate' &
git clone https://github.com/gszabi99/War-Thunder-Datamine '/storage/nvme5/new_clones/Squirrel/War-Thunder-Datamine' &
git clone https://github.com/Mauler125/scripts_r5 '/storage/nvme5/new_clones/Squirrel/scripts_r5' &
git clone https://github.com/R2Northstar/NorthstarMods '/storage/nvme5/new_clones/Squirrel/NorthstarMods' &
git clone https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod '/storage/nvme5/new_clones/Squirrel/Portal-2-Multiplayer-Mod' &
git clone https://github.com/BEEmod/BEE2-items '/storage/nvme5/new_clones/Squirrel/BEE2-items' &
git clone https://github.com/electricimp/reference '/storage/nvme5/new_clones/Squirrel/reference' &
git clone https://github.com/samisalreadytaken/vs_library '/storage/nvme5/new_clones/Squirrel/vs_library' &
git clone https://github.com/Tsuey/L4D2-Community-Update '/storage/nvme5/new_clones/Squirrel/L4D2-Community-Update' &
git clone https://github.com/Syampuuh/Titanfall2 '/storage/nvme5/new_clones/Squirrel/Titanfall2' &
git clone https://github.com/gflze/CSGO-ZE-Configs '/storage/nvme5/new_clones/Squirrel/CSGO-ZE-Configs' &
git clone https://github.com/misyltoad/riscv-vscript '/storage/nvme5/new_clones/Squirrel/riscv-vscript' &
git clone https://github.com/smilz0/Left4Bots '/storage/nvme5/new_clones/Squirrel/Left4Bots' &
git clone https://github.com/L4D2Scripters/vslib '/storage/nvme5/new_clones/Squirrel/vslib' &
git clone https://github.com/sparkfun/Wimp_Weather_Station '/storage/nvme5/new_clones/Squirrel/Wimp_Weather_Station' &
git clone https://github.com/birjj/csgo-vscripts '/storage/nvme5/new_clones/Squirrel/csgo-vscripts' &
git clone https://github.com/p2sr/Portal2SpeedrunMod '/storage/nvme5/new_clones/Squirrel/Portal2SpeedrunMod' &
git clone https://github.com/Derpduck/L4D2-Comp-Stripper-Rework '/storage/nvme5/new_clones/Squirrel/L4D2-Comp-Stripper-Rework' &
git clone https://github.com/Lin515/L4D2_LinGe_VScripts '/storage/nvme5/new_clones/Squirrel/L4D2_LinGe_VScripts' &
git clone https://github.com/hephaestus9/Power_Monitor '/storage/nvme5/new_clones/Squirrel/Power_Monitor' &
git clone https://github.com/Syampuuh/TitanfallApexLegends '/storage/nvme5/new_clones/Squirrel/TitanfallApexLegends' &
git clone https://github.com/Blick1337/apex-legends-scripts '/storage/nvme5/new_clones/Squirrel/apex-legends-scripts' &
git clone https://github.com/s-ol/csgo-vscripts '/storage/nvme5/new_clones/Squirrel/csgo-vscripts' &
git clone https://github.com/newrelic/futurestack14_badge '/storage/nvme5/new_clones/Squirrel/futurestack14_badge' &
git clone https://github.com/taskinoz/Enhanced-Menu-Mod '/storage/nvme5/new_clones/Squirrel/Enhanced-Menu-Mod' &
git clone https://github.com/deinferno/CSGO-Vscript-collection '/storage/nvme5/new_clones/Squirrel/CSGO-Vscript-collection' &
git clone https://github.com/MSUTeam/MSU '/storage/nvme5/new_clones/Squirrel/MSU' &
git clone https://github.com/saracoth/newdark-mods '/storage/nvme5/new_clones/Squirrel/newdark-mods' &
git clone https://github.com/ghostcap-gaming/Zombie-Escape-Configs-CS-GO '/storage/nvme5/new_clones/Squirrel/Zombie-Escape-Configs-CS-GO' &
git clone https://github.com/Battle-Modders/mod-reforged '/storage/nvme5/new_clones/Squirrel/mod-reforged' &
git clone https://github.com/luizluca/nut-snmpagent '/storage/nvme5/new_clones/Squirrel/nut-snmpagent' &
git clone https://github.com/mikangogo/JRTrainPack '/storage/nvme5/new_clones/Squirrel/JRTrainPack' &
git clone https://github.com/ersatzavian/ei-fw-tom '/storage/nvme5/new_clones/Squirrel/ei-fw-tom' &
git clone https://github.com/zpaolo11x/Arcadeflow '/storage/nvme5/new_clones/Squirrel/Arcadeflow' &
git clone https://github.com/fbef0102/L4D2-Unlimited-Map '/storage/nvme5/new_clones/Squirrel/L4D2-Unlimited-Map' &
git clone https://github.com/electricimp/LIS3DH '/storage/nvme5/new_clones/Squirrel/LIS3DH' &
git clone https://github.com/notkoen/Zombie-Escape-Configs '/storage/nvme5/new_clones/Squirrel/Zombie-Escape-Configs' &
git clone https://github.com/inlife/squirrel-require '/storage/nvme5/new_clones/Squirrel/squirrel-require' &
git clone https://github.com/F1F7Y/Better.Serverbrowser '/storage/nvme5/new_clones/Squirrel/Better.Serverbrowser' &
git clone https://github.com/esquiloio/lib '/storage/nvme5/new_clones/Squirrel/lib' &
git clone https://github.com/BroFox86/ss2-modpack '/storage/nvme5/new_clones/Squirrel/ss2-modpack' &
git clone https://github.com/NgGH707/NgGH-Magic-Origins-Mod '/storage/nvme5/new_clones/Squirrel/NgGH-Magic-Origins-Mod' &
git clone https://github.com/electricimp/Salesforce '/storage/nvme5/new_clones/Squirrel/Salesforce' &
git clone https://github.com/sparkfun/Tomatoless_Boots '/storage/nvme5/new_clones/Squirrel/Tomatoless_Boots' &
git clone https://github.com/ersatzavian/flowbright '/storage/nvme5/new_clones/Squirrel/flowbright' &
git clone https://github.com/jacob404/Official-Vscripts-Decompiled '/storage/nvme5/new_clones/Squirrel/Official-Vscripts-Decompiled' &
git clone https://github.com/newk5/decui '/storage/nvme5/new_clones/Squirrel/decui' &
git clone https://github.com/electricimp/Rocky '/storage/nvme5/new_clones/Squirrel/Rocky' &
git clone https://github.com/electricimp/BQ25895 '/storage/nvme5/new_clones/Squirrel/BQ25895' &
git clone https://github.com/mickelson/attract-extra '/storage/nvme5/new_clones/Squirrel/attract-extra' &
git clone https://github.com/potato-tf/ArchiveAssets '/storage/nvme5/new_clones/Squirrel/ArchiveAssets' &
git clone https://github.com/hasseily/GridCartographer-Mapping '/storage/nvme5/new_clones/Squirrel/GridCartographer-Mapping' &
git clone https://github.com/R2Spyglass/IMC.Spyglass '/storage/nvme5/new_clones/Squirrel/IMC.Spyglass' &
git clone https://github.com/electricimp/JSONParser '/storage/nvme5/new_clones/Squirrel/JSONParser' &
git clone https://github.com/electricimp/WolframDataDrop '/storage/nvme5/new_clones/Squirrel/WolframDataDrop' &
git clone https://github.com/sw1ft747/Library-of-Utils '/storage/nvme5/new_clones/Squirrel/Library-of-Utils' &
git clone https://github.com/smilz0/Left4Lib '/storage/nvme5/new_clones/Squirrel/Left4Lib' &
git clone https://github.com/electricimp/STN1110 '/storage/nvme5/new_clones/Squirrel/STN1110' &
git clone https://github.com/electricimp/UBloxM8N '/storage/nvme5/new_clones/Squirrel/UBloxM8N' &
git clone https://github.com/F1F7Y/ServerUtilities '/storage/nvme5/new_clones/Squirrel/ServerUtilities' &
git clone https://github.com/EladNLG/Roguelike '/storage/nvme5/new_clones/Squirrel/Roguelike' &
git clone https://github.com/spumer/vscripts '/storage/nvme5/new_clones/Squirrel/vscripts' &
git clone https://github.com/SakuraAyi/CSGO_VScripts '/storage/nvme5/new_clones/Squirrel/CSGO_VScripts' &
git clone https://github.com/etsmit/sp_levels '/storage/nvme5/new_clones/Squirrel/sp_levels' &
git clone https://github.com/inlife/squirrel-orm '/storage/nvme5/new_clones/Squirrel/squirrel-orm' &
git clone https://github.com/Dinorush/LTSRebalance '/storage/nvme5/new_clones/Squirrel/LTSRebalance' &
git clone https://github.com/electricimp/MCP2515 '/storage/nvme5/new_clones/Squirrel/MCP2515' &
git clone https://github.com/ianfitzpatrick/popuparcade '/storage/nvme5/new_clones/Squirrel/popuparcade' &
git clone https://github.com/taskinoz/Streamer-Mode '/storage/nvme5/new_clones/Squirrel/Streamer-Mode' &
git clone https://github.com/electricimp/PN532 '/storage/nvme5/new_clones/Squirrel/PN532' &
git clone https://github.com/newrelic/futurestack_badge '/storage/nvme5/new_clones/Squirrel/futurestack_badge' &
git clone https://github.com/electricimp/WS2812 '/storage/nvme5/new_clones/Squirrel/WS2812' &
git clone https://github.com/rwaldron/tyrion '/storage/nvme5/new_clones/Squirrel/tyrion' &
git clone https://github.com/stanleyseow/electricimp-nRF24L01 '/storage/nvme5/new_clones/Squirrel/electricimp-nRF24L01' &
git clone https://github.com/MinchinWeb/openttd-wmdot '/storage/nvme5/new_clones/Squirrel/openttd-wmdot' &
git clone https://github.com/biast12/Gun-Spawner '/storage/nvme5/new_clones/Squirrel/Gun-Spawner' &
git clone https://github.com/p2r3/ppmod '/storage/nvme5/new_clones/Squirrel/ppmod' &
git clone https://github.com/CuewarsTaner/r5_and_flowstate_cn '/storage/nvme5/new_clones/Squirrel/r5_and_flowstate_cn' &
git clone https://github.com/simutrans/pak128 '/storage/nvme5/new_clones/Squirrel/pak128' &
git clone https://github.com/Titanfall-Mods/Icepick-Core-Mods '/storage/nvme5/new_clones/Squirrel/Icepick-Core-Mods' &
git clone https://github.com/vfig/thiefy-stuff '/storage/nvme5/new_clones/Squirrel/thiefy-stuff' &
git clone https://github.com/Syampuuh/Titanfall2-orig '/storage/nvme5/new_clones/Squirrel/Titanfall2-orig' &
git clone https://github.com/jcsato/of_flesh_and_faith_plus '/storage/nvme5/new_clones/Squirrel/of_flesh_and_faith_plus' &
git clone https://github.com/electricimp/QL720NW '/storage/nvme5/new_clones/Squirrel/QL720NW' &
git clone https://github.com/sw1ft747/l4d2-vscript-projects '/storage/nvme5/new_clones/Squirrel/l4d2-vscript-projects' &
git clone https://github.com/oomek/ambience-hd '/storage/nvme5/new_clones/Squirrel/ambience-hd' &
git clone https://github.com/barnabwhy/Barnab.AutoBalance '/storage/nvme5/new_clones/Squirrel/Barnab.AutoBalance' &
git clone https://github.com/nothans/thingspeak-electric-imp '/storage/nvme5/new_clones/Squirrel/thingspeak-electric-imp' &
git clone https://github.com/taskinoz/Dev-Mode '/storage/nvme5/new_clones/Squirrel/Dev-Mode' &
git clone https://github.com/joel-wehr/electric_imp_security_system '/storage/nvme5/new_clones/Squirrel/electric_imp_security_system' &
git clone https://github.com/TheEnderek0/QoL-Reloaded '/storage/nvme5/new_clones/Squirrel/QoL-Reloaded' &
git clone https://github.com/Squinkz/vscript_timer '/storage/nvme5/new_clones/Squirrel/vscript_timer' &
git clone https://github.com/cat-haines/ISS-Overhead '/storage/nvme5/new_clones/Squirrel/ISS-Overhead' &
git clone https://github.com/mafia2online/M2Online-Resources '/storage/nvme5/new_clones/Squirrel/M2Online-Resources' &
git clone https://github.com/electricimp/LSM9DS0 '/storage/nvme5/new_clones/Squirrel/LSM9DS0' &
git clone https://github.com/Suor/battle-brothers-mods '/storage/nvme5/new_clones/Squirrel/battle-brothers-mods' &
git clone https://github.com/Daraan/Dark-Squirrel-Scripts '/storage/nvme5/new_clones/Squirrel/Dark-Squirrel-Scripts' &
git clone https://github.com/Rectus/l4d2-vscripts '/storage/nvme5/new_clones/Squirrel/l4d2-vscripts' &
git clone https://github.com/MinchinWeb/openttd-metalibrary '/storage/nvme5/new_clones/Squirrel/openttd-metalibrary' &
git clone https://github.com/7ychu5/vscript_csgo '/storage/nvme5/new_clones/Squirrel/vscript_csgo' &
git clone https://github.com/electricimp/JSONEncoder '/storage/nvme5/new_clones/Squirrel/JSONEncoder' &
git clone https://github.com/electricimp/MAX17055 '/storage/nvme5/new_clones/Squirrel/MAX17055' &
git clone https://github.com/nagadomi/l4d2_versus_single '/storage/nvme5/new_clones/Squirrel/l4d2_versus_single' &
git clone https://github.com/EladNLG/HUDRevamp '/storage/nvme5/new_clones/Squirrel/HUDRevamp' &
git clone https://github.com/electricimp/Wiznet_5500 '/storage/nvme5/new_clones/Squirrel/Wiznet_5500' &
git clone https://github.com/uifnm/GeneralAtsPlugin '/storage/nvme5/new_clones/Squirrel/GeneralAtsPlugin' &
git clone https://github.com/TaroEld/mod_stronghold '/storage/nvme5/new_clones/Squirrel/mod_stronghold' &
