#!/bin/bash

git clone https://github.com/GoogleContainerTools/distroless '/storage/nvme5/new_clones/Starlark/distroless' &
git clone https://github.com/googleapis/googleapis '/storage/nvme5/new_clones/Starlark/googleapis' &
git clone https://github.com/google/cel-spec '/storage/nvme5/new_clones/Starlark/cel-spec' &
git clone https://github.com/bazelbuild/starlark '/storage/nvme5/new_clones/Starlark/starlark' &
git clone https://github.com/bazelbuild/rules_docker '/storage/nvme5/new_clones/Starlark/rules_docker' &
git clone https://github.com/lucperkins/colossus '/storage/nvme5/new_clones/Starlark/colossus' &
git clone https://github.com/bazelbuild/examples '/storage/nvme5/new_clones/Starlark/examples' &
git clone https://github.com/bazel-contrib/rules_nodejs '/storage/nvme5/new_clones/Starlark/rules_nodejs' &
git clone https://github.com/bazelbuild/rules_rust '/storage/nvme5/new_clones/Starlark/rules_rust' &
git clone https://github.com/bazel-contrib/rules_foreign_cc '/storage/nvme5/new_clones/Starlark/rules_foreign_cc' &
git clone https://github.com/envoyproxy/data-plane-api '/storage/nvme5/new_clones/Starlark/data-plane-api' &
git clone https://github.com/bazelbuild/rules_python '/storage/nvme5/new_clones/Starlark/rules_python' &
git clone https://github.com/bazelbuild/rules_apple '/storage/nvme5/new_clones/Starlark/rules_apple' &
git clone https://github.com/grailbio/bazel-compilation-database '/storage/nvme5/new_clones/Starlark/bazel-compilation-database' &
git clone https://github.com/owncloud-docker/server '/storage/nvme5/new_clones/Starlark/server' &
git clone https://github.com/GoogleContainerTools/base-images-docker '/storage/nvme5/new_clones/Starlark/base-images-docker' &
git clone https://github.com/tidbyt/community '/storage/nvme5/new_clones/Starlark/community' &
git clone https://github.com/bazelbuild/bazel-skylib '/storage/nvme5/new_clones/Starlark/bazel-skylib' &
git clone https://github.com/bazelbuild/rules_scala '/storage/nvme5/new_clones/Starlark/rules_scala' &
git clone https://github.com/bazel-contrib/rules_jvm_external '/storage/nvme5/new_clones/Starlark/rules_jvm_external' &
git clone https://github.com/bazel-contrib/rules_oci '/storage/nvme5/new_clones/Starlark/rules_oci' &
git clone https://github.com/aspect-build/rules_js '/storage/nvme5/new_clones/Starlark/rules_js' &
git clone https://github.com/bazelbuild/rules_swift '/storage/nvme5/new_clones/Starlark/rules_swift' &
git clone https://github.com/tweag/rules_nixpkgs '/storage/nvme5/new_clones/Starlark/rules_nixpkgs' &
git clone https://github.com/bazel-contrib/toolchains_llvm '/storage/nvme5/new_clones/Starlark/toolchains_llvm' &
git clone https://github.com/ethpandaops/ethereum-package '/storage/nvme5/new_clones/Starlark/ethereum-package' &
git clone https://github.com/bazelbuild/rules_k8s '/storage/nvme5/new_clones/Starlark/rules_k8s' &
git clone https://github.com/bazel-ios/rules_ios '/storage/nvme5/new_clones/Starlark/rules_ios' &
git clone https://github.com/bazelbuild/bazel-central-registry '/storage/nvme5/new_clones/Starlark/bazel-central-registry' &
git clone https://github.com/tweag/rules_haskell '/storage/nvme5/new_clones/Starlark/rules_haskell' &
git clone https://github.com/grpc/grpc-proto '/storage/nvme5/new_clones/Starlark/grpc-proto' &
git clone https://github.com/rules-proto-grpc/rules_proto_grpc '/storage/nvme5/new_clones/Starlark/rules_proto_grpc' &
git clone https://github.com/googleapis/api-common-protos '/storage/nvme5/new_clones/Starlark/api-common-protos' &
git clone https://github.com/cncf/udpa '/storage/nvme5/new_clones/Starlark/udpa' &
git clone https://github.com/bazelbuild/rules_pkg '/storage/nvme5/new_clones/Starlark/rules_pkg' &
git clone https://github.com/stakater/application '/storage/nvme5/new_clones/Starlark/application' &
git clone https://github.com/tilt-dev/tilt-extensions '/storage/nvme5/new_clones/Starlark/tilt-extensions' &
git clone https://github.com/cncf/xds '/storage/nvme5/new_clones/Starlark/xds' &
git clone https://github.com/line/rules_apple_line '/storage/nvme5/new_clones/Starlark/rules_apple_line' &
git clone https://github.com/bazelbuild/rules_cc '/storage/nvme5/new_clones/Starlark/rules_cc' &
git clone https://github.com/bazel-contrib/rules_dotnet '/storage/nvme5/new_clones/Starlark/rules_dotnet' &
git clone https://github.com/adobe/rules_gitops '/storage/nvme5/new_clones/Starlark/rules_gitops' &
git clone https://github.com/bazelbuild/rules_proto '/storage/nvme5/new_clones/Starlark/rules_proto' &
git clone https://github.com/tweag/clodl '/storage/nvme5/new_clones/Starlark/clodl' &
git clone https://github.com/google/llvm-bazel '/storage/nvme5/new_clones/Starlark/llvm-bazel' &
git clone https://github.com/cloudflare/sciuro '/storage/nvme5/new_clones/Starlark/sciuro' &
git clone https://github.com/openconfig/gnoi '/storage/nvme5/new_clones/Starlark/gnoi' &
git clone https://github.com/typedb/bazel-distribution '/storage/nvme5/new_clones/Starlark/bazel-distribution' &
git clone https://github.com/bazel-contrib/bazel-lib '/storage/nvme5/new_clones/Starlark/bazel-lib' &
git clone https://github.com/apple/apple_rules_lint '/storage/nvme5/new_clones/Starlark/apple_rules_lint' &
git clone https://github.com/hdl/bazel_rules_hdl '/storage/nvme5/new_clones/Starlark/bazel_rules_hdl' &
git clone https://github.com/bazel-contrib/bazel-mypy-integration '/storage/nvme5/new_clones/Starlark/bazel-mypy-integration' &
git clone https://github.com/kriscfoster/multi-language-bazel-monorepo '/storage/nvme5/new_clones/Starlark/multi-language-bazel-monorepo' &
git clone https://github.com/aspect-build/bazel-examples '/storage/nvme5/new_clones/Starlark/bazel-examples' &
git clone https://github.com/atlassian/bazel-tools '/storage/nvme5/new_clones/Starlark/bazel-tools' &
git clone https://github.com/hexdae/toolchains_arm_gnu '/storage/nvme5/new_clones/Starlark/toolchains_arm_gnu' &
git clone https://github.com/f0rmiga/gcc-toolchain '/storage/nvme5/new_clones/Starlark/gcc-toolchain' &
git clone https://github.com/bazelbuild/platforms '/storage/nvme5/new_clones/Starlark/platforms' &
git clone https://github.com/erenon/bazel_clang_tidy '/storage/nvme5/new_clones/Starlark/bazel_clang_tidy' &
git clone https://github.com/aspect-build/rules_ts '/storage/nvme5/new_clones/Starlark/rules_ts' &
git clone https://github.com/apache/skywalking-data-collect-protocol '/storage/nvme5/new_clones/Starlark/skywalking-data-collect-protocol' &
git clone https://github.com/bazelembedded/bazel-embedded '/storage/nvme5/new_clones/Starlark/bazel-embedded' &
git clone https://github.com/pybind/pybind11_bazel '/storage/nvme5/new_clones/Starlark/pybind11_bazel' &
git clone https://github.com/amaizfinance/redis-operator '/storage/nvme5/new_clones/Starlark/redis-operator' &
git clone https://github.com/thundergolfer/bazel-linting-system '/storage/nvme5/new_clones/Starlark/bazel-linting-system' &
git clone https://github.com/bazelruby/rules_ruby '/storage/nvme5/new_clones/Starlark/rules_ruby' &
git clone https://github.com/aspect-build/rules_py '/storage/nvme5/new_clones/Starlark/rules_py' &
git clone https://github.com/kubernetes/repo-infra '/storage/nvme5/new_clones/Starlark/repo-infra' &
git clone https://github.com/bazel-contrib/rules_cuda '/storage/nvme5/new_clones/Starlark/rules_cuda' &
git clone https://github.com/cgrindel/rules_swift_package_manager '/storage/nvme5/new_clones/Starlark/rules_swift_package_manager' &
git clone https://github.com/mvukov/rules_ros2 '/storage/nvme5/new_clones/Starlark/rules_ros2' &
git clone https://github.com/bazel-contrib/rules_fuzzing '/storage/nvme5/new_clones/Starlark/rules_fuzzing' &
git clone https://github.com/google/bazel-common '/storage/nvme5/new_clones/Starlark/bazel-common' &
git clone https://github.com/keith/rules_multirun '/storage/nvme5/new_clones/Starlark/rules_multirun' &
git clone https://github.com/eomii/rules_ll '/storage/nvme5/new_clones/Starlark/rules_ll' &
git clone https://github.com/thelgevold/react-bazel-example '/storage/nvme5/new_clones/Starlark/react-bazel-example' &
git clone https://github.com/jankremlacek/go-bazel '/storage/nvme5/new_clones/Starlark/go-bazel' &
git clone https://github.com/bazelbuild/apple_support '/storage/nvme5/new_clones/Starlark/apple_support' &
git clone https://github.com/prysmaticlabs/ethereumapis '/storage/nvme5/new_clones/Starlark/ethereumapis' &
git clone https://github.com/bazel-contrib/rules-template '/storage/nvme5/new_clones/Starlark/rules-template' &
git clone https://github.com/bazelbuild/rules_license '/storage/nvme5/new_clones/Starlark/rules_license' &
git clone https://github.com/ProdriveTechnologies/bazel-latex '/storage/nvme5/new_clones/Starlark/bazel-latex' &
git clone https://github.com/bazelbuild/rules_java '/storage/nvme5/new_clones/Starlark/rules_java' &
git clone https://github.com/nicolov/ros-bazel '/storage/nvme5/new_clones/Starlark/ros-bazel' &
git clone https://github.com/soniaai/rules_poetry '/storage/nvme5/new_clones/Starlark/rules_poetry' &
git clone https://github.com/etsy/rules_grafana '/storage/nvme5/new_clones/Starlark/rules_grafana' &
git clone https://github.com/bazel-contrib/rules_jsonnet '/storage/nvme5/new_clones/Starlark/rules_jsonnet' &
git clone https://github.com/whois/ianawhois '/storage/nvme5/new_clones/Starlark/ianawhois' &
git clone https://github.com/jayconrod/rules_go_simple '/storage/nvme5/new_clones/Starlark/rules_go_simple' &
git clone https://github.com/higherkindness/rules_scala '/storage/nvme5/new_clones/Starlark/rules_scala' &
git clone https://github.com/OpenAPITools/openapi-generator-bazel '/storage/nvme5/new_clones/Starlark/openapi-generator-bazel' &
git clone https://github.com/jvolkman/rules_pycross '/storage/nvme5/new_clones/Starlark/rules_pycross' &
git clone https://github.com/salesforce/bazel-mystery '/storage/nvme5/new_clones/Starlark/bazel-mystery' &
git clone https://github.com/keith/bazel-rust-mobile-demo '/storage/nvme5/new_clones/Starlark/bazel-rust-mobile-demo' &
git clone https://github.com/keith/rules_apple_linker '/storage/nvme5/new_clones/Starlark/rules_apple_linker' &
git clone https://github.com/thoughtpolice/buck2-nix '/storage/nvme5/new_clones/Starlark/buck2-nix' &
git clone https://github.com/masmovil/masorange_rules_helm '/storage/nvme5/new_clones/Starlark/masorange_rules_helm' &
git clone https://github.com/GoogleContainerTools/rules_distroless '/storage/nvme5/new_clones/Starlark/rules_distroless' &
git clone https://github.com/jmhodges/bazel_gomock '/storage/nvme5/new_clones/Starlark/bazel_gomock' &
git clone https://github.com/enginoid/monorepo-base '/storage/nvme5/new_clones/Starlark/monorepo-base' &
git clone https://github.com/zegl/rules_codeowners '/storage/nvme5/new_clones/Starlark/rules_codeowners' &
git clone https://github.com/ash2k/bazel-tools '/storage/nvme5/new_clones/Starlark/bazel-tools' &
git clone https://github.com/cgrindel/rules_spm '/storage/nvme5/new_clones/Starlark/rules_spm' &
git clone https://github.com/tweag/nix_bazel_codelab '/storage/nvme5/new_clones/Starlark/nix_bazel_codelab' &
git clone https://github.com/aspect-build/bazel-super-formatter '/storage/nvme5/new_clones/Starlark/bazel-super-formatter' &
git clone https://github.com/facebook/buck2-prelude '/storage/nvme5/new_clones/Starlark/buck2-prelude' &
git clone https://github.com/chenrui333/rules_openapi '/storage/nvme5/new_clones/Starlark/rules_openapi' &
git clone https://github.com/bazel-contrib/rules_bazel_integration_test '/storage/nvme5/new_clones/Starlark/rules_bazel_integration_test' &
git clone https://github.com/bazelbuild/rules_sass '/storage/nvme5/new_clones/Starlark/rules_sass' &
git clone https://github.com/bufbuild/rules_buf '/storage/nvme5/new_clones/Starlark/rules_buf' &
git clone https://github.com/paulcavallaro/systems-programming '/storage/nvme5/new_clones/Starlark/systems-programming' &
git clone https://github.com/s0l0ist/bazel-emscripten '/storage/nvme5/new_clones/Starlark/bazel-emscripten' &
git clone https://github.com/cbracken/rules_dart '/storage/nvme5/new_clones/Starlark/rules_dart' &
git clone https://github.com/google-coral/test_data '/storage/nvme5/new_clones/Starlark/test_data' &
git clone https://github.com/nikunjy/golink '/storage/nvme5/new_clones/Starlark/golink' &
git clone https://github.com/bazelbuild/bazel-federation '/storage/nvme5/new_clones/Starlark/bazel-federation' &
git clone https://github.com/sgammon/rules_graalvm '/storage/nvme5/new_clones/Starlark/rules_graalvm' &
git clone https://github.com/limdor/bazel-examples '/storage/nvme5/new_clones/Starlark/bazel-examples' &
git clone https://github.com/ApexAI/rules_ros '/storage/nvme5/new_clones/Starlark/rules_ros' &
git clone https://github.com/justbuchanan/bazel_rules_qt '/storage/nvme5/new_clones/Starlark/bazel_rules_qt' &
git clone https://github.com/aspect-build/rules_swc '/storage/nvme5/new_clones/Starlark/rules_swc' &
git clone https://github.com/stackb/rules_hugo '/storage/nvme5/new_clones/Starlark/rules_hugo' &
git clone https://github.com/tweag/rules_sh '/storage/nvme5/new_clones/Starlark/rules_sh' &
git clone https://github.com/kku1993/bazel-hermetic-python '/storage/nvme5/new_clones/Starlark/bazel-hermetic-python' &
git clone https://github.com/storypku/bazel_iwyu '/storage/nvme5/new_clones/Starlark/bazel_iwyu' &
git clone https://github.com/GoogleCloudPlatform/container-definitions '/storage/nvme5/new_clones/Starlark/container-definitions' &
git clone https://github.com/andyscott/rules_graal '/storage/nvme5/new_clones/Starlark/rules_graal' &
git clone https://github.com/google/cabal2bazel '/storage/nvme5/new_clones/Starlark/cabal2bazel' &
git clone https://github.com/bbreslauer/qt-bazel-example '/storage/nvme5/new_clones/Starlark/qt-bazel-example' &
git clone https://github.com/wildarch/blackjack '/storage/nvme5/new_clones/Starlark/blackjack' &
git clone https://github.com/Planck1858/golang101 '/storage/nvme5/new_clones/Starlark/golang101' &
git clone https://github.com/rnburn/rules_cc_module '/storage/nvme5/new_clones/Starlark/rules_cc_module' &
git clone https://github.com/OasisDigital/bazelcon-2019 '/storage/nvme5/new_clones/Starlark/bazelcon-2019' &
git clone https://github.com/pcj/bazel_aspects '/storage/nvme5/new_clones/Starlark/bazel_aspects' &
git clone https://github.com/grailbio/rules_r '/storage/nvme5/new_clones/Starlark/rules_r' &
git clone https://github.com/keith/buildifier-prebuilt '/storage/nvme5/new_clones/Starlark/buildifier-prebuilt' &
git clone https://github.com/google/bazel_rules_install '/storage/nvme5/new_clones/Starlark/bazel_rules_install' &
git clone https://github.com/benley/bazel_rules_pex '/storage/nvme5/new_clones/Starlark/bazel_rules_pex' &
git clone https://github.com/jl777/coins '/storage/nvme5/new_clones/Starlark/coins' &
git clone https://github.com/cgrushko/proto_library '/storage/nvme5/new_clones/Starlark/proto_library' &
git clone https://github.com/jin/rules_ocaml '/storage/nvme5/new_clones/Starlark/rules_ocaml' &
git clone https://github.com/rabbitmq/rules_erlang '/storage/nvme5/new_clones/Starlark/rules_erlang' &
git clone https://github.com/tnarg/rules_cue '/storage/nvme5/new_clones/Starlark/rules_cue' &
git clone https://github.com/bazelbuild/rules_android_ndk '/storage/nvme5/new_clones/Starlark/rules_android_ndk' &
git clone https://github.com/lunaris/minirepo '/storage/nvme5/new_clones/Starlark/minirepo' &
git clone https://github.com/bazelembedded/rules_cc_toolchain '/storage/nvme5/new_clones/Starlark/rules_cc_toolchain' &
git clone https://github.com/hedronvision/bazel-make-cc-https-easy '/storage/nvme5/new_clones/Starlark/bazel-make-cc-https-easy' &
git clone https://github.com/simuons/rules_clojure '/storage/nvme5/new_clones/Starlark/rules_clojure' &
git clone https://github.com/guymers/containers_by_bazel '/storage/nvme5/new_clones/Starlark/containers_by_bazel' &
git clone https://github.com/Dig-Doug/rules_typescript_proto '/storage/nvme5/new_clones/Starlark/rules_typescript_proto' &
git clone https://github.com/aspect-build/rules_webpack '/storage/nvme5/new_clones/Starlark/rules_webpack' &
git clone https://github.com/obazl/rules_ocaml '/storage/nvme5/new_clones/Starlark/rules_ocaml' &
git clone https://github.com/ajbouh/bazel-zig-cc '/storage/nvme5/new_clones/Starlark/bazel-zig-cc' &
git clone https://github.com/sluongng/nogo-analyzer '/storage/nvme5/new_clones/Starlark/nogo-analyzer' &
git clone https://github.com/bazelbuild/rules_appengine '/storage/nvme5/new_clones/Starlark/rules_appengine' &
git clone https://github.com/Vertexwahn/rules_qt6 '/storage/nvme5/new_clones/Starlark/rules_qt6' &
git clone https://github.com/stackb/bazel-stack-vscode-cc '/storage/nvme5/new_clones/Starlark/bazel-stack-vscode-cc' &
git clone https://github.com/evie404/golang-boilerplate '/storage/nvme5/new_clones/Starlark/golang-boilerplate' &
git clone https://github.com/RobotLocomotion/models '/storage/nvme5/new_clones/Starlark/models' &
git clone https://github.com/simplebuild/please.make '/storage/nvme5/new_clones/Starlark/please.make' &
git clone https://github.com/thought-machine/please-examples '/storage/nvme5/new_clones/Starlark/please-examples' &
git clone https://github.com/vmware-archive/rules_oss_audit '/storage/nvme5/new_clones/Starlark/rules_oss_audit' &
git clone https://github.com/bazel-contrib/rules_ruby '/storage/nvme5/new_clones/Starlark/rules_ruby' &
git clone https://github.com/aspect-build/rules_esbuild '/storage/nvme5/new_clones/Starlark/rules_esbuild' &
git clone https://github.com/fmeum/rules_jni '/storage/nvme5/new_clones/Starlark/rules_jni' &
git clone https://github.com/lalten/rules_appimage '/storage/nvme5/new_clones/Starlark/rules_appimage' &
git clone https://github.com/anthanh/bazel-next-typescript-monorepo '/storage/nvme5/new_clones/Starlark/bazel-next-typescript-monorepo' &
git clone https://github.com/Digital-Production-Aachen/OpenVectorFormat '/storage/nvme5/new_clones/Starlark/OpenVectorFormat' &
git clone https://github.com/GoogleCloudPlatform/layer-definitions '/storage/nvme5/new_clones/Starlark/layer-definitions' &
git clone https://github.com/gregestren/snippets '/storage/nvme5/new_clones/Starlark/snippets' &
git clone https://github.com/jvolkman/bazel-nix-example '/storage/nvme5/new_clones/Starlark/bazel-nix-example' &
git clone https://github.com/bazel-contrib/rules_perl '/storage/nvme5/new_clones/Starlark/rules_perl' &
git clone https://github.com/mum4k/platformio_rules '/storage/nvme5/new_clones/Starlark/platformio_rules' &
git clone https://github.com/wayou/bazel-ts-example '/storage/nvme5/new_clones/Starlark/bazel-ts-example' &
git clone https://github.com/coinbase/rules_ruby '/storage/nvme5/new_clones/Starlark/rules_ruby' &
git clone https://github.com/kczulko/rules_elm '/storage/nvme5/new_clones/Starlark/rules_elm' &
git clone https://github.com/abrisco/rules_helm '/storage/nvme5/new_clones/Starlark/rules_helm' &
git clone https://github.com/spietras/rules_conda '/storage/nvme5/new_clones/Starlark/rules_conda' &
git clone https://github.com/digital-plumbers-union/rules_pyenv '/storage/nvme5/new_clones/Starlark/rules_pyenv' &
git clone https://github.com/bazelbuild/tools_android '/storage/nvme5/new_clones/Starlark/tools_android' &
git clone https://github.com/mvukov/rules_ros '/storage/nvme5/new_clones/Starlark/rules_ros' &
git clone https://github.com/quittle/rules_web '/storage/nvme5/new_clones/Starlark/rules_web' &
git clone https://github.com/aspect-build/rules_jest '/storage/nvme5/new_clones/Starlark/rules_jest' &
git clone https://github.com/kkiningh/rules_verilator '/storage/nvme5/new_clones/Starlark/rules_verilator' &
git clone https://github.com/bazel-contrib/rules_debian_packages '/storage/nvme5/new_clones/Starlark/rules_debian_packages' &
git clone https://github.com/bazelbuild/rules_d '/storage/nvme5/new_clones/Starlark/rules_d' &
git clone https://github.com/discolix/discolix '/storage/nvme5/new_clones/Starlark/discolix' &
git clone https://github.com/bazelbuild/rules_testing '/storage/nvme5/new_clones/Starlark/rules_testing' &
git clone https://github.com/jdreaver/rules_terraform '/storage/nvme5/new_clones/Starlark/rules_terraform' &
git clone https://github.com/tmate-io/tmate-kube '/storage/nvme5/new_clones/Starlark/tmate-kube' &
git clone https://github.com/ratanparai/cpp-template '/storage/nvme5/new_clones/Starlark/cpp-template' &
git clone https://github.com/facebookarchive/buckit '/storage/nvme5/new_clones/Starlark/buckit' &
git clone https://github.com/ltekieli/bazel_cross_compile '/storage/nvme5/new_clones/Starlark/bazel_cross_compile' &
git clone https://github.com/GoogleCloudPlatform/marketplace-tools '/storage/nvme5/new_clones/Starlark/marketplace-tools' &
git clone https://github.com/salrashid123/go-grpc-bazel-docker '/storage/nvme5/new_clones/Starlark/go-grpc-bazel-docker' &
git clone https://github.com/jessecureton/python_bazel_template '/storage/nvme5/new_clones/Starlark/python_bazel_template' &
git clone https://github.com/zaucy/vscode-bazel-cpp-example '/storage/nvme5/new_clones/Starlark/vscode-bazel-cpp-example' &
git clone https://github.com/cosyneco/MediaPipe.NET.Runtime '/storage/nvme5/new_clones/Starlark/MediaPipe.NET.Runtime' &
git clone https://github.com/aignas/rules_shellcheck '/storage/nvme5/new_clones/Starlark/rules_shellcheck' &
git clone https://github.com/linzhp/codegen_example '/storage/nvme5/new_clones/Starlark/codegen_example' &
git clone https://github.com/hchauvin/bazel-coverage-report '/storage/nvme5/new_clones/Starlark/bazel-coverage-report' &
git clone https://github.com/AndrewGuenther/rules_python_poetry '/storage/nvme5/new_clones/Starlark/rules_python_poetry' &
git clone https://github.com/flakrimjusufi/grpc-with-rest '/storage/nvme5/new_clones/Starlark/grpc-with-rest' &
git clone https://github.com/openconfig/gnsi '/storage/nvme5/new_clones/Starlark/gnsi' &
git clone https://github.com/buildbarn/bb-event-service '/storage/nvme5/new_clones/Starlark/bb-event-service' &
git clone https://github.com/vincent-picaud/Bazel_with_GTest '/storage/nvme5/new_clones/Starlark/Bazel_with_GTest' &
git clone https://github.com/tensorflow/toolchains '/storage/nvme5/new_clones/Starlark/toolchains' &
git clone https://github.com/attilaolah/wasm '/storage/nvme5/new_clones/Starlark/wasm' &
git clone https://github.com/google-coral/crosstool '/storage/nvme5/new_clones/Starlark/crosstool' &
git clone https://github.com/thelgevold/svelte-bazel-example '/storage/nvme5/new_clones/Starlark/svelte-bazel-example' &
git clone https://github.com/keith/swift-syntax-bazel '/storage/nvme5/new_clones/Starlark/swift-syntax-bazel' &
git clone https://github.com/thelgevold/rules_svelte '/storage/nvme5/new_clones/Starlark/rules_svelte' &
git clone https://github.com/benchsci/rules_kustomize '/storage/nvme5/new_clones/Starlark/rules_kustomize' &
git clone https://github.com/apache/rocketmq-apis '/storage/nvme5/new_clones/Starlark/rocketmq-apis' &
git clone https://github.com/bazelbuild/rules_gwt '/storage/nvme5/new_clones/Starlark/rules_gwt' &
git clone https://github.com/ebendutoit/zetasql-analyzer-server '/storage/nvme5/new_clones/Starlark/zetasql-analyzer-server' &
git clone https://github.com/uhthomas/tesla_exporter '/storage/nvme5/new_clones/Starlark/tesla_exporter' &
git clone https://github.com/bazeltools/bazel_jar_jar '/storage/nvme5/new_clones/Starlark/bazel_jar_jar' &
git clone https://github.com/fmeum/rules_runfiles '/storage/nvme5/new_clones/Starlark/rules_runfiles' &
git clone https://github.com/Bencodes/bazel_jetpack_compose_example '/storage/nvme5/new_clones/Starlark/bazel_jetpack_compose_example' &
git clone https://github.com/cgrindel/bazel-starlib '/storage/nvme5/new_clones/Starlark/bazel-starlib' &
git clone https://github.com/seh/rules_cue '/storage/nvme5/new_clones/Starlark/rules_cue' &
git clone https://github.com/TokTok/toktok-stack '/storage/nvme5/new_clones/Starlark/toktok-stack' &
git clone https://github.com/jmillikin/rules_bison '/storage/nvme5/new_clones/Starlark/rules_bison' &
git clone https://github.com/yicm/BazelMixedLanguage '/storage/nvme5/new_clones/Starlark/BazelMixedLanguage' &
git clone https://github.com/nikunjy/go '/storage/nvme5/new_clones/Starlark/go' &
git clone https://github.com/airyhq/bazel-tools '/storage/nvme5/new_clones/Starlark/bazel-tools' &
git clone https://github.com/jmillikin/rules_m4 '/storage/nvme5/new_clones/Starlark/rules_m4' &
git clone https://github.com/caseyduquettesc/rules_python_pytest '/storage/nvme5/new_clones/Starlark/rules_python_pytest' &
git clone https://github.com/simonhorlick/bazel_esp32 '/storage/nvme5/new_clones/Starlark/bazel_esp32' &
git clone https://github.com/TheGrizzlyDev/snazel '/storage/nvme5/new_clones/Starlark/snazel' &
git clone https://github.com/scalio/bazel-dotnetcore-starter '/storage/nvme5/new_clones/Starlark/bazel-dotnetcore-starter' &
git clone https://github.com/kgreenek/rules_pcl '/storage/nvme5/new_clones/Starlark/rules_pcl' &
git clone https://github.com/jmillikin/rules_flex '/storage/nvme5/new_clones/Starlark/rules_flex' &
git clone https://github.com/typedb/typedb-protocol '/storage/nvme5/new_clones/Starlark/typedb-protocol' &
git clone https://github.com/jadarve/rules_vulkan '/storage/nvme5/new_clones/Starlark/rules_vulkan' &
git clone https://github.com/dmadisetti/rules_euler '/storage/nvme5/new_clones/Starlark/rules_euler' &
git clone https://github.com/itsbalamurali/rust-fhir '/storage/nvme5/new_clones/Starlark/rust-fhir' &
git clone https://github.com/secretflow/interconnection '/storage/nvme5/new_clones/Starlark/interconnection' &
git clone https://github.com/jpsim/swiftlint-bazel-example '/storage/nvme5/new_clones/Starlark/swiftlint-bazel-example' &
git clone https://github.com/jkulhanek/bazel-libtorch-cpp '/storage/nvme5/new_clones/Starlark/bazel-libtorch-cpp' &
git clone https://github.com/robolectric/robolectric-bazel '/storage/nvme5/new_clones/Starlark/robolectric-bazel' &
git clone https://github.com/EngFlow/example '/storage/nvme5/new_clones/Starlark/example' &
git clone https://github.com/ekhabarov/bazel-k8s-envoy '/storage/nvme5/new_clones/Starlark/bazel-k8s-envoy' &
git clone https://github.com/aspect-build/rules_deno '/storage/nvme5/new_clones/Starlark/rules_deno' &
git clone https://github.com/buildbuddy-io/buildbuddy-toolchain '/storage/nvme5/new_clones/Starlark/buildbuddy-toolchain' &
git clone https://github.com/voidstarHQ/voidstar '/storage/nvme5/new_clones/Starlark/voidstar' &
git clone https://github.com/jmileson/rules_terraform '/storage/nvme5/new_clones/Starlark/rules_terraform' &
git clone https://github.com/hiroyuki-komatsu/japanese-usage-dictionary '/storage/nvme5/new_clones/Starlark/japanese-usage-dictionary' &
git clone https://github.com/chenrui333/rules_avro '/storage/nvme5/new_clones/Starlark/rules_avro' &
git clone https://github.com/curtismuntz/bazel_compilers '/storage/nvme5/new_clones/Starlark/bazel_compilers' &
git clone https://github.com/Enopios/Enopios '/storage/nvme5/new_clones/Starlark/Enopios' &
git clone https://github.com/dvulpe/bazel-terraform-rules '/storage/nvme5/new_clones/Starlark/bazel-terraform-rules' &
git clone https://github.com/moshix/osvs2src '/storage/nvme5/new_clones/Starlark/osvs2src' &
git clone https://github.com/extremecoders-re/uncompyle6-builds '/storage/nvme5/new_clones/Starlark/uncompyle6-builds' &
git clone https://github.com/SUMGlobal/bazel-micronaut-example '/storage/nvme5/new_clones/Starlark/bazel-micronaut-example' &
git clone https://github.com/FaBrand/bazel-learning '/storage/nvme5/new_clones/Starlark/bazel-learning' &
git clone https://github.com/c16a/hydradb '/storage/nvme5/new_clones/Starlark/hydradb' &
git clone https://github.com/flolu/docker-puppeteer-webgl '/storage/nvme5/new_clones/Starlark/docker-puppeteer-webgl' &
git clone https://github.com/hlopko/bazel-jni-example '/storage/nvme5/new_clones/Starlark/bazel-jni-example' &
git clone https://github.com/purkhusid/biff '/storage/nvme5/new_clones/Starlark/biff' &
git clone https://github.com/metarsit/golang-repository-template '/storage/nvme5/new_clones/Starlark/golang-repository-template' &
git clone https://github.com/michael-quinlan/jupyter-bazel '/storage/nvme5/new_clones/Starlark/jupyter-bazel' &
git clone https://github.com/jeongukjae/faiss-server '/storage/nvme5/new_clones/Starlark/faiss-server' &
git clone https://github.com/filmil/bazel-ebook '/storage/nvme5/new_clones/Starlark/bazel-ebook' &
git clone https://github.com/GerritCodeReview/bazlets '/storage/nvme5/new_clones/Starlark/bazlets' &
git clone https://github.com/samolisov/bazel-llvm-bridge '/storage/nvme5/new_clones/Starlark/bazel-llvm-bridge' &
git clone https://github.com/tilt-dev/bazel_example '/storage/nvme5/new_clones/Starlark/bazel_example' &
git clone https://github.com/nickdecooman/bazel-rust-docker-example '/storage/nvme5/new_clones/Starlark/bazel-rust-docker-example' &
git clone https://github.com/tinder-maxwellelliott/ios-bazel-test-with-coverage '/storage/nvme5/new_clones/Starlark/ios-bazel-test-with-coverage' &
git clone https://github.com/GoogleCloudPlatform/payment-gateway '/storage/nvme5/new_clones/Starlark/payment-gateway' &
git clone https://github.com/pmoncadaisla/bazel-testcontainers '/storage/nvme5/new_clones/Starlark/bazel-testcontainers' &
git clone https://github.com/mwalbeck/docker-python-poetry '/storage/nvme5/new_clones/Starlark/docker-python-poetry' &
git clone https://github.com/typedb/typedb-dependencies '/storage/nvme5/new_clones/Starlark/typedb-dependencies' &
git clone https://github.com/flolu/nextjs-bazel '/storage/nvme5/new_clones/Starlark/nextjs-bazel' &
git clone https://github.com/georgeliaw/rules_wheel '/storage/nvme5/new_clones/Starlark/rules_wheel' &
git clone https://github.com/agoessling/bazel_bootlin '/storage/nvme5/new_clones/Starlark/bazel_bootlin' &
git clone https://github.com/tilt-dev/tilt-example-bazel '/storage/nvme5/new_clones/Starlark/tilt-example-bazel' &
git clone https://github.com/dmcavinue/tidbyt-proxy '/storage/nvme5/new_clones/Starlark/tidbyt-proxy' &
git clone https://github.com/egen/disruptor '/storage/nvme5/new_clones/Starlark/disruptor' &
git clone https://github.com/samborba/mediapipe-api '/storage/nvme5/new_clones/Starlark/mediapipe-api' &
git clone https://github.com/fenollp/bazel_upgradable '/storage/nvme5/new_clones/Starlark/bazel_upgradable' &
git clone https://github.com/bshepherdson/grpc-web-bazel-ts-example '/storage/nvme5/new_clones/Starlark/grpc-web-bazel-ts-example' &
git clone https://github.com/owncloud-docker/ubuntu '/storage/nvme5/new_clones/Starlark/ubuntu' &
git clone https://github.com/bazelbuild/rules_groovy '/storage/nvme5/new_clones/Starlark/rules_groovy' &
git clone https://github.com/ob/rules_kubebuilder '/storage/nvme5/new_clones/Starlark/rules_kubebuilder' &
git clone https://github.com/nvidia-riva/common '/storage/nvme5/new_clones/Starlark/common' &
git clone https://github.com/lokshunhung/bazel-ts-monorepo '/storage/nvme5/new_clones/Starlark/bazel-ts-monorepo' &
git clone https://github.com/cdleary/bazel_pybind_sample '/storage/nvme5/new_clones/Starlark/bazel_pybind_sample' &
git clone https://github.com/joneshf/purs-tools '/storage/nvme5/new_clones/Starlark/purs-tools' &
git clone https://github.com/googleapis/googleapis-discovery '/storage/nvme5/new_clones/Starlark/googleapis-discovery' &
git clone https://github.com/andyscott/misc_rules '/storage/nvme5/new_clones/Starlark/misc_rules' &
git clone https://github.com/psigen/bazel-python-cpp-example '/storage/nvme5/new_clones/Starlark/bazel-python-cpp-example' &
git clone https://github.com/psigen/bazel-python-cpp-example '/storage/nvme5/new_clones/Starlark/bazel-python-cpp-example' &
git clone https://github.com/ubiquitoustech/rules_vite '/storage/nvme5/new_clones/Starlark/rules_vite' &
git clone https://github.com/pedrobarco/typescript-bazel-template '/storage/nvme5/new_clones/Starlark/typescript-bazel-template' &
git clone https://github.com/Gogistics/prj-envoy-v1 '/storage/nvme5/new_clones/Starlark/prj-envoy-v1' &
git clone https://github.com/felixmulder/rules_purescript '/storage/nvme5/new_clones/Starlark/rules_purescript' &
git clone https://github.com/bmustiata/bazel-samples '/storage/nvme5/new_clones/Starlark/bazel-samples' &
git clone https://github.com/johanbrandhorst/bazel-mono '/storage/nvme5/new_clones/Starlark/bazel-mono' &
git clone https://github.com/weisi/bazel_for_gcloud_python '/storage/nvme5/new_clones/Starlark/bazel_for_gcloud_python' &
git clone https://github.com/thelgevold/svelte-dotnet-samples '/storage/nvme5/new_clones/Starlark/svelte-dotnet-samples' &
git clone https://github.com/kgreenek/rules_capnproto '/storage/nvme5/new_clones/Starlark/rules_capnproto' &
git clone https://github.com/Mousius/rules_python_poetry '/storage/nvme5/new_clones/Starlark/rules_python_poetry' &
git clone https://github.com/bazeltools/bazelfe '/storage/nvme5/new_clones/Starlark/bazelfe' &
git clone https://github.com/DiligentCorp/tilt-rancher-example '/storage/nvme5/new_clones/Starlark/tilt-rancher-example' &
git clone https://github.com/whilp/world '/storage/nvme5/new_clones/Starlark/world' &
git clone https://github.com/happy-co/rules_node '/storage/nvme5/new_clones/Starlark/rules_node' &
git clone https://github.com/Wind-River/meta-apollo '/storage/nvme5/new_clones/Starlark/meta-apollo' &
git clone https://github.com/filmil/bazel-bats '/storage/nvme5/new_clones/Starlark/bazel-bats' &
git clone https://github.com/JetBrains/rules_idea '/storage/nvme5/new_clones/Starlark/rules_idea' &
git clone https://github.com/meteorcloudy/windows-crosstool '/storage/nvme5/new_clones/Starlark/windows-crosstool' &
git clone https://github.com/iceboy233/boost '/storage/nvme5/new_clones/Starlark/boost' &
git clone https://github.com/zachgrayio/binaural-beats '/storage/nvme5/new_clones/Starlark/binaural-beats' &
git clone https://github.com/jmillikin/rules_ragel '/storage/nvme5/new_clones/Starlark/rules_ragel' &
git clone https://github.com/zaucy/rules_vulkan '/storage/nvme5/new_clones/Starlark/rules_vulkan' &
git clone https://github.com/lianmakesthings/secrets-management-talk '/storage/nvme5/new_clones/Starlark/secrets-management-talk' &
git clone https://github.com/agoessling/rules_sphinx '/storage/nvme5/new_clones/Starlark/rules_sphinx' &
git clone https://github.com/dsuess/mediapipe-pytorch '/storage/nvme5/new_clones/Starlark/mediapipe-pytorch' &
git clone https://github.com/bazelbuild/rules_postcss '/storage/nvme5/new_clones/Starlark/rules_postcss' &
git clone https://github.com/typedb/bazel-intellij-rust-example '/storage/nvme5/new_clones/Starlark/bazel-intellij-rust-example' &
git clone https://github.com/HappyCerberus/bazel-golang-minimal-example '/storage/nvme5/new_clones/Starlark/bazel-golang-minimal-example' &
git clone https://github.com/0xf005ba11/bazel_ewdk_cc '/storage/nvme5/new_clones/Starlark/bazel_ewdk_cc' &
git clone https://github.com/jwmcglynn/bazel-cpp20 '/storage/nvme5/new_clones/Starlark/bazel-cpp20' &
git clone https://github.com/aspect-build/rules_cypress '/storage/nvme5/new_clones/Starlark/rules_cypress' &
git clone https://github.com/brentleyjones/rules_xcodeproj-demo '/storage/nvme5/new_clones/Starlark/rules_xcodeproj-demo' &
git clone https://github.com/aherrmann/bazel-transitions-demo '/storage/nvme5/new_clones/Starlark/bazel-transitions-demo' &
git clone https://github.com/snxq/multi-language-bazel-test '/storage/nvme5/new_clones/Starlark/multi-language-bazel-test' &
git clone https://github.com/sunfrank1987/build_tensorflow_lite '/storage/nvme5/new_clones/Starlark/build_tensorflow_lite' &
git clone https://github.com/bisontrails/rules_kustomize '/storage/nvme5/new_clones/Starlark/rules_kustomize' &
git clone https://github.com/cgrindel/rules_updatesrc '/storage/nvme5/new_clones/Starlark/rules_updatesrc' &
git clone https://github.com/hult/tidbyt-apps '/storage/nvme5/new_clones/Starlark/tidbyt-apps' &
git clone https://github.com/salesforce/bazel-java-builder-template '/storage/nvme5/new_clones/Starlark/bazel-java-builder-template' &
git clone https://github.com/bazelRio/bazelRio '/storage/nvme5/new_clones/Starlark/bazelRio' &
git clone https://github.com/plezentek/rules_sqlc '/storage/nvme5/new_clones/Starlark/rules_sqlc' &
git clone https://github.com/davidB/sandbox_bazel '/storage/nvme5/new_clones/Starlark/sandbox_bazel' &
git clone https://github.com/clstb/phi '/storage/nvme5/new_clones/Starlark/phi' &
git clone https://github.com/3rdparty/bazel-rules-openssl '/storage/nvme5/new_clones/Starlark/bazel-rules-openssl' &
git clone https://github.com/cyberdelia/starlark '/storage/nvme5/new_clones/Starlark/starlark' &
git clone https://github.com/acqio/rules_databricks '/storage/nvme5/new_clones/Starlark/rules_databricks' &
git clone https://github.com/1e100/cloud_archive '/storage/nvme5/new_clones/Starlark/cloud_archive' &
git clone https://github.com/blaizard/bzd-channel '/storage/nvme5/new_clones/Starlark/bzd-channel' &
git clone https://github.com/grpckit/omniproto '/storage/nvme5/new_clones/Starlark/omniproto' &
git clone https://github.com/0x2Adr1/bazel-hobby-OS-template '/storage/nvme5/new_clones/Starlark/bazel-hobby-OS-template' &
git clone https://github.com/jackhumphries/bazel-ebpf '/storage/nvme5/new_clones/Starlark/bazel-ebpf' &
git clone https://github.com/cgrindel/rules_swiftformat '/storage/nvme5/new_clones/Starlark/rules_swiftformat' &
git clone https://github.com/uKetki/PlayFeatureDelivery '/storage/nvme5/new_clones/Starlark/PlayFeatureDelivery' &
git clone https://github.com/cloneable/rules_ent '/storage/nvme5/new_clones/Starlark/rules_ent' &
git clone https://github.com/kurtosis-tech/near-package '/storage/nvme5/new_clones/Starlark/near-package' &
git clone https://github.com/googlemaps/js-types '/storage/nvme5/new_clones/Starlark/js-types' &
git clone https://github.com/uber-research/brezel '/storage/nvme5/new_clones/Starlark/brezel' &
git clone https://github.com/TheButlah/rules_pyo3 '/storage/nvme5/new_clones/Starlark/rules_pyo3' &
git clone https://github.com/Brightspace/rules_csharp '/storage/nvme5/new_clones/Starlark/rules_csharp' &
git clone https://github.com/Bencodes/rules_android_lint '/storage/nvme5/new_clones/Starlark/rules_android_lint' &
git clone https://github.com/jcju/opencv_bazel_win '/storage/nvme5/new_clones/Starlark/opencv_bazel_win' &
git clone https://github.com/narendasan/rules_cuda '/storage/nvme5/new_clones/Starlark/rules_cuda' &
git clone https://github.com/mikberg/bazel-vite '/storage/nvme5/new_clones/Starlark/bazel-vite' &
git clone https://github.com/fmeum/rules_meta '/storage/nvme5/new_clones/Starlark/rules_meta' &
git clone https://github.com/googleapis/rules_gapic '/storage/nvme5/new_clones/Starlark/rules_gapic' &
git clone https://github.com/alban-read/forth '/storage/nvme5/new_clones/Starlark/forth' &
git clone https://github.com/bmuschko/getting-started-bazel '/storage/nvme5/new_clones/Starlark/getting-started-bazel' &
git clone https://github.com/humphrej/rules_dhall '/storage/nvme5/new_clones/Starlark/rules_dhall' &
git clone https://github.com/BalderOdinson/rules_cuda '/storage/nvme5/new_clones/Starlark/rules_cuda' &
git clone https://github.com/bazelembedded/rules_emulation '/storage/nvme5/new_clones/Starlark/rules_emulation' &
git clone https://github.com/mackorone/tidbyt-bouncing-dvd-logo '/storage/nvme5/new_clones/Starlark/tidbyt-bouncing-dvd-logo' &
git clone https://github.com/salrashid123/cosign_bazel_cloud_build '/storage/nvme5/new_clones/Starlark/cosign_bazel_cloud_build' &
git clone https://github.com/tanishiking/bazel-tutorial-scala '/storage/nvme5/new_clones/Starlark/bazel-tutorial-scala' &
git clone https://github.com/duarten/rust-bazel-cross '/storage/nvme5/new_clones/Starlark/rust-bazel-cross' &
git clone https://github.com/tilt-dev/tilt-example-builders '/storage/nvme5/new_clones/Starlark/tilt-example-builders' &
git clone https://github.com/zntrio/hexagonal-bazel '/storage/nvme5/new_clones/Starlark/hexagonal-bazel' &
git clone https://github.com/martinxsliu/rules_python_poetry '/storage/nvme5/new_clones/Starlark/rules_python_poetry' &
git clone https://github.com/aarnphm/bazix '/storage/nvme5/new_clones/Starlark/bazix' &
git clone https://github.com/christianscott/experimental_rules_jest_worker '/storage/nvme5/new_clones/Starlark/experimental_rules_jest_worker' &
git clone https://github.com/mackorone/tidbyt-nyan-cat '/storage/nvme5/new_clones/Starlark/tidbyt-nyan-cat' &
git clone https://github.com/owncloud-docker/openshift '/storage/nvme5/new_clones/Starlark/openshift' &
git clone https://github.com/cloudhan/rules_cuda_examples '/storage/nvme5/new_clones/Starlark/rules_cuda_examples' &
git clone https://github.com/jacksmith15/bazel-python-demo '/storage/nvme5/new_clones/Starlark/bazel-python-demo' &
git clone https://github.com/erenon/rules_pch '/storage/nvme5/new_clones/Starlark/rules_pch' &
git clone https://github.com/cgrindel/rules_bzlformat '/storage/nvme5/new_clones/Starlark/rules_bzlformat' &
git clone https://github.com/dfr/rules_pico '/storage/nvme5/new_clones/Starlark/rules_pico' &
git clone https://github.com/snyk-labs/rules_snyk '/storage/nvme5/new_clones/Starlark/rules_snyk' &
git clone https://github.com/loonghao/portable_rez '/storage/nvme5/new_clones/Starlark/portable_rez' &
git clone https://github.com/aspect-build/rules_terser '/storage/nvme5/new_clones/Starlark/rules_terser' &
git clone https://github.com/world-federation-of-advertisers/cross-media-measurement-api '/storage/nvme5/new_clones/Starlark/cross-media-measurement-api' &
git clone https://github.com/hexdae/bazel-nordic-sdk '/storage/nvme5/new_clones/Starlark/bazel-nordic-sdk' &
git clone https://github.com/lukasoyen/experiments_rules_conan '/storage/nvme5/new_clones/Starlark/experiments_rules_conan' &
git clone https://github.com/btwiuse/k0s '/storage/nvme5/new_clones/Starlark/k0s' &
git clone https://github.com/segiddins/bazel_nondeterministic_actions '/storage/nvme5/new_clones/Starlark/bazel_nondeterministic_actions' &
git clone https://github.com/salvalcantara/bazel-flink-scala '/storage/nvme5/new_clones/Starlark/bazel-flink-scala' &
git clone https://github.com/zaucy/rules_blender '/storage/nvme5/new_clones/Starlark/rules_blender' &
git clone https://github.com/ahyangyi/astraeus-workspace '/storage/nvme5/new_clones/Starlark/astraeus-workspace' &
git clone https://github.com/aherrmann/bazel-toolchain-version-select '/storage/nvme5/new_clones/Starlark/bazel-toolchain-version-select' &
git clone https://github.com/realtimetodie/bazel-rust-grpc-aperture '/storage/nvme5/new_clones/Starlark/bazel-rust-grpc-aperture' &
git clone https://github.com/vardaro/rules_py_simple '/storage/nvme5/new_clones/Starlark/rules_py_simple' &
git clone https://github.com/Bencodes/bazel_rules_dokka '/storage/nvme5/new_clones/Starlark/bazel_rules_dokka' &
git clone https://github.com/takov751/Pyoxidizer_example '/storage/nvme5/new_clones/Starlark/Pyoxidizer_example' &
git clone https://github.com/bentoml/plugins '/storage/nvme5/new_clones/Starlark/plugins' &
git clone https://github.com/discord/rlottiebinding-ios '/storage/nvme5/new_clones/Starlark/rlottiebinding-ios' &
git clone https://github.com/storypku/llvm-x-toolchain '/storage/nvme5/new_clones/Starlark/llvm-x-toolchain' &
git clone https://github.com/flyteorg/bazelrules_flyte '/storage/nvme5/new_clones/Starlark/bazelrules_flyte' &
git clone https://github.com/danilocutrim/dev-with-tilt '/storage/nvme5/new_clones/Starlark/dev-with-tilt' &
git clone https://github.com/damianbaar/local-aws '/storage/nvme5/new_clones/Starlark/local-aws' &
git clone https://github.com/sagikazarmark/mypleasings '/storage/nvme5/new_clones/Starlark/mypleasings' &
git clone https://github.com/jfrog/jfrog-distroless '/storage/nvme5/new_clones/Starlark/jfrog-distroless' &
git clone https://github.com/TheGrizzlyDev/rules_deno '/storage/nvme5/new_clones/Starlark/rules_deno' &
git clone https://github.com/grailbio/py_singlefile_binary '/storage/nvme5/new_clones/Starlark/py_singlefile_binary' &
git clone https://github.com/moshix/MVS38j.SYS1.MACLIB '/storage/nvme5/new_clones/Starlark/MVS38j.SYS1.MACLIB' &
git clone https://github.com/radixbio/urep-scala '/storage/nvme5/new_clones/Starlark/urep-scala' &
git clone https://github.com/bodnar-dan/bazel-poc '/storage/nvme5/new_clones/Starlark/bazel-poc' &
git clone https://github.com/acqio/rules_microsoft_azure '/storage/nvme5/new_clones/Starlark/rules_microsoft_azure' &
git clone https://github.com/aspect-build/rules_sol '/storage/nvme5/new_clones/Starlark/rules_sol' &
git clone https://github.com/plezentek/rules_wire '/storage/nvme5/new_clones/Starlark/rules_wire' &
git clone https://github.com/b25/larnaca '/storage/nvme5/new_clones/Starlark/larnaca' &
git clone https://github.com/square/sqldelight_bazel_rules '/storage/nvme5/new_clones/Starlark/sqldelight_bazel_rules' &
git clone https://github.com/nchavez324/rules_metal '/storage/nvme5/new_clones/Starlark/rules_metal' &
git clone https://github.com/stackb/bazel-gazelle-debug '/storage/nvme5/new_clones/Starlark/bazel-gazelle-debug' &
git clone https://github.com/jwillker/demo-opentelemetry-go '/storage/nvme5/new_clones/Starlark/demo-opentelemetry-go' &
git clone https://github.com/owncloud-docker/helm-charts '/storage/nvme5/new_clones/Starlark/helm-charts' &
git clone https://github.com/kellyjonbrazil/jc-packaging '/storage/nvme5/new_clones/Starlark/jc-packaging' &
