#!/bin/bash

git clone https://github.com/theme-next/hexo-theme-next '/storage/nvme5/new_clones/Stylus/hexo-theme-next' &
git clone https://github.com/probberechts/hexo-theme-cactus '/storage/nvme5/new_clones/Stylus/hexo-theme-cactus' &
git clone https://github.com/stylus/nib '/storage/nvme5/new_clones/Stylus/nib' &
git clone https://github.com/lynnandtonic/a-single-div '/storage/nvme5/new_clones/Stylus/a-single-div' &
git clone https://github.com/Molunerfinn/hexo-theme-melody '/storage/nvme5/new_clones/Stylus/hexo-theme-melody' &
git clone https://github.com/YunYouJun/hexo-theme-yun '/storage/nvme5/new_clones/Stylus/hexo-theme-yun' &
git clone https://github.com/ConardLi/ConardLi.github.io '/storage/nvme5/new_clones/Stylus/ConardLihub.io' &
git clone https://github.com/amehime/hexo-theme-shoka '/storage/nvme5/new_clones/Stylus/hexo-theme-shoka' &
git clone https://github.com/Siricee/hexo-theme-Chic '/storage/nvme5/new_clones/Stylus/hexo-theme-Chic' &
git clone https://github.com/frontendbr/eventos '/storage/nvme5/new_clones/Stylus/eventos' &
git clone https://github.com/CntChen/cntchen.github.io '/storage/nvme5/new_clones/Stylus/cntchenhub.io' &
git clone https://github.com/BaiduHiDeviOS/iOS-Tech-Weekly '/storage/nvme5/new_clones/Stylus/iOS-Tech-Weekly' &
git clone https://github.com/hexojs/site '/storage/nvme5/new_clones/Stylus/site' &
git clone https://github.com/A/largescaleJS_ru '/storage/nvme5/new_clones/Stylus/largescaleJS_ru' &
git clone https://github.com/liuyib/hexo-theme-stun '/storage/nvme5/new_clones/Stylus/hexo-theme-stun' &
git clone https://github.com/zhwangart/hexo-theme-ocean '/storage/nvme5/new_clones/Stylus/hexo-theme-ocean' &
git clone https://github.com/vednoc/dark-whatsapp '/storage/nvme5/new_clones/Stylus/dark-whatsapp' &
git clone https://github.com/victorvoid/space-jekyll-template '/storage/nvme5/new_clones/Stylus/space-jekyll-template' &
git clone https://github.com/raphaelfabeni/ui-interactions '/storage/nvme5/new_clones/Stylus/ui-interactions' &
git clone https://github.com/f-dong/hexo-theme-minimalism '/storage/nvme5/new_clones/Stylus/hexo-theme-minimalism' &
git clone https://github.com/hexojs/hexo-theme-landscape '/storage/nvme5/new_clones/Stylus/hexo-theme-landscape' &
git clone https://github.com/hexojs/hexo-theme-light '/storage/nvme5/new_clones/Stylus/hexo-theme-light' &
git clone https://github.com/zgq354/typecho-theme-next '/storage/nvme5/new_clones/Stylus/typecho-theme-next' &
git clone https://github.com/lynnandtonic/airport-codes '/storage/nvme5/new_clones/Stylus/airport-codes' &
git clone https://github.com/nodejs/nodejs-ko '/storage/nvme5/new_clones/Stylus/nodejs-ko' &
git clone https://github.com/iTimeTraveler/hexo-theme-hipaper '/storage/nvme5/new_clones/Stylus/hexo-theme-hipaper' &
git clone https://github.com/frontendbr/frontendbr.github.io '/storage/nvme5/new_clones/Stylus/frontendbrhub.io' &
git clone https://github.com/geist-org/style '/storage/nvme5/new_clones/Stylus/style' &
git clone https://github.com/blleng/hexo-theme-lx '/storage/nvme5/new_clones/Stylus/hexo-theme-lx' &
git clone https://github.com/FuShaoLei/hexo-theme-white '/storage/nvme5/new_clones/Stylus/hexo-theme-white' &
git clone https://github.com/ShanaMaid/hexo-theme-shana '/storage/nvme5/new_clones/Stylus/hexo-theme-shana' &
git clone https://github.com/stiekel/hexo-theme-random '/storage/nvme5/new_clones/Stylus/hexo-theme-random' &
git clone https://github.com/andyet/yeti.css '/storage/nvme5/new_clones/Stylus/yeti.css' &
git clone https://github.com/fan-lv/Fan '/storage/nvme5/new_clones/Stylus/Fan' &
git clone https://github.com/auth0/styleguide '/storage/nvme5/new_clones/Stylus/styleguide' &
git clone https://github.com/ting-talk/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/lynnandtonic/nestflix.fun '/storage/nvme5/new_clones/Stylus/nestflix.fun' &
git clone https://github.com/loadingio/loading.css '/storage/nvme5/new_clones/Stylus/loading.css' &
git clone https://github.com/mickeyouyou/yinwang '/storage/nvme5/new_clones/Stylus/yinwang' &
git clone https://github.com/gary-Shen/hexo-theme-bear '/storage/nvme5/new_clones/Stylus/hexo-theme-bear' &
git clone https://github.com/zoeingwingkei/frame '/storage/nvme5/new_clones/Stylus/frame' &
git clone https://github.com/cyrilf/vuepress-theme-book '/storage/nvme5/new_clones/Stylus/vuepress-theme-book' &
git clone https://github.com/tzvetkov75/solar-theme-hexo '/storage/nvme5/new_clones/Stylus/solar-theme-hexo' &
git clone https://github.com/xaoxuu/hexo-theme-resume '/storage/nvme5/new_clones/Stylus/hexo-theme-resume' &
git clone https://github.com/SwiftGGTeam/GGHexo '/storage/nvme5/new_clones/Stylus/GGHexo' &
git clone https://github.com/chunqiuyiyu/hexo-theme-polk '/storage/nvme5/new_clones/Stylus/hexo-theme-polk' &
git clone https://github.com/Lete114/Hexo-Theme-MengD '/storage/nvme5/new_clones/Stylus/Hexo-Theme-MengD' &
git clone https://github.com/hexojs/hexo-theme-phase '/storage/nvme5/new_clones/Stylus/hexo-theme-phase' &
git clone https://github.com/viko16/vuepress-theme-simple '/storage/nvme5/new_clones/Stylus/vuepress-theme-simple' &
git clone https://github.com/jorge8168711/Checkbox.css '/storage/nvme5/new_clones/Stylus/Checkbox.css' &
git clone https://github.com/Cerallin/hexo-theme-yuzu '/storage/nvme5/new_clones/Stylus/hexo-theme-yuzu' &
git clone https://github.com/Ionogy/kernel.css '/storage/nvme5/new_clones/Stylus/kernel.css' &
git clone https://github.com/Danktuary/vuepress-theme-yuu '/storage/nvme5/new_clones/Stylus/vuepress-theme-yuu' &
git clone https://github.com/wencaizhang/oh-my-js '/storage/nvme5/new_clones/Stylus/oh-my-js' &
git clone https://github.com/prinsss/hexo-theme-murasaki '/storage/nvme5/new_clones/Stylus/hexo-theme-murasaki' &
git clone https://github.com/FriendlyUser/vuepress-theme-cool '/storage/nvme5/new_clones/Stylus/vuepress-theme-cool' &
git clone https://github.com/ismail9k/neomorphism '/storage/nvme5/new_clones/Stylus/neomorphism' &
git clone https://github.com/markdone/cssume '/storage/nvme5/new_clones/Stylus/cssume' &
git clone https://github.com/Chorer/hexo-theme-PureBlue '/storage/nvme5/new_clones/Stylus/hexo-theme-PureBlue' &
git clone https://github.com/lynnandtonic/hollywood-age-gap '/storage/nvme5/new_clones/Stylus/hollywood-age-gap' &
git clone https://github.com/tolking/vuepress-theme-default-prefers-color-scheme '/storage/nvme5/new_clones/Stylus/vuepress-theme-default-prefers-color-scheme' &
git clone https://github.com/leirock/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/suenyiyang/hexo-theme-linear '/storage/nvme5/new_clones/Stylus/hexo-theme-linear' &
git clone https://github.com/passport/www.passportjs.org '/storage/nvme5/new_clones/Stylus/www.passportjs.org' &
git clone https://github.com/shinux/hexo-theme-adoubi '/storage/nvme5/new_clones/Stylus/hexo-theme-adoubi' &
git clone https://github.com/rcore-os/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/jaywcjlove/stylus-px2rem '/storage/nvme5/new_clones/Stylus/stylus-px2rem' &
git clone https://github.com/elkowar/a-box-of-gruv '/storage/nvme5/new_clones/Stylus/a-box-of-gruv' &
git clone https://github.com/whyaz/whyaz '/storage/nvme5/new_clones/Stylus/whyaz' &
git clone https://github.com/mosaic101/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/vednoc/dark-instagram '/storage/nvme5/new_clones/Stylus/dark-instagram' &
git clone https://github.com/platframe/platframe '/storage/nvme5/new_clones/Stylus/platframe' &
git clone https://github.com/huff-language/huff-docs '/storage/nvme5/new_clones/Stylus/huff-docs' &
git clone https://github.com/nodejs/nodejs-uk '/storage/nvme5/new_clones/Stylus/nodejs-uk' &
git clone https://github.com/kwokronny/stylus-shortcut '/storage/nvme5/new_clones/Stylus/stylus-shortcut' &
git clone https://github.com/vednoc/dark-github '/storage/nvme5/new_clones/Stylus/dark-github' &
git clone https://github.com/CristhGunners/Coolors '/storage/nvme5/new_clones/Stylus/Coolors' &
git clone https://github.com/BoiseCodeWorks/student-workbook '/storage/nvme5/new_clones/Stylus/student-workbook' &
git clone https://github.com/Leviathan1995/hexo-theme-polk-x '/storage/nvme5/new_clones/Stylus/hexo-theme-polk-x' &
git clone https://github.com/thiagobraga/google-calendar-userstyles '/storage/nvme5/new_clones/Stylus/google-calendar-userstyles' &
git clone https://github.com/includeios/document '/storage/nvme5/new_clones/Stylus/document' &
git clone https://github.com/JeremyFan/hexo-theme-still '/storage/nvme5/new_clones/Stylus/hexo-theme-still' &
git clone https://github.com/yusixian/cos_blogs '/storage/nvme5/new_clones/Stylus/cos_blogs' &
git clone https://github.com/Xedecimal/userstyles '/storage/nvme5/new_clones/Stylus/userstyles' &
git clone https://github.com/qiantao94/hexo-theme-oasis '/storage/nvme5/new_clones/Stylus/hexo-theme-oasis' &
git clone https://github.com/future-architect/tech-blog '/storage/nvme5/new_clones/Stylus/tech-blog' &
git clone https://github.com/CityOfBoston/patterns '/storage/nvme5/new_clones/Stylus/patterns' &
git clone https://github.com/hangvane/academia-hexo-netlify-cms-vercel '/storage/nvme5/new_clones/Stylus/academia-hexo-netlify-cms-vercel' &
git clone https://github.com/teambition/TB-Icons '/storage/nvme5/new_clones/Stylus/TB-Icons' &
git clone https://github.com/autoload/hexo-theme-auto '/storage/nvme5/new_clones/Stylus/hexo-theme-auto' &
git clone https://github.com/QIUZAIYOU/Stylish '/storage/nvme5/new_clones/Stylus/Stylish' &
git clone https://github.com/Ikaleio/argon-luogu '/storage/nvme5/new_clones/Stylus/argon-luogu' &
git clone https://github.com/loveminimal/hexo-theme-zero '/storage/nvme5/new_clones/Stylus/hexo-theme-zero' &
git clone https://github.com/Jacksgong/Blog '/storage/nvme5/new_clones/Stylus/Blog' &
git clone https://github.com/z-xl-t/hexo-theme-aurora '/storage/nvme5/new_clones/Stylus/hexo-theme-aurora' &
git clone https://github.com/NightTeam/nightteam.github.io '/storage/nvme5/new_clones/Stylus/nightteamhub.io' &
git clone https://github.com/welksonramos/flags-brazil '/storage/nvme5/new_clones/Stylus/flags-brazil' &
git clone https://github.com/future-architect/future-architect.github.io '/storage/nvme5/new_clones/Stylus/future-architecthub.io' &
git clone https://github.com/userstyles-world/tweaks '/storage/nvme5/new_clones/Stylus/tweaks' &
git clone https://github.com/wdullaer/raml2html-slate-theme '/storage/nvme5/new_clones/Stylus/raml2html-slate-theme' &
git clone https://github.com/zjx137/hexo-theme-Tsu '/storage/nvme5/new_clones/Stylus/hexo-theme-Tsu' &
git clone https://github.com/lixuetaoleo/hexo-theme-leo '/storage/nvme5/new_clones/Stylus/hexo-theme-leo' &
git clone https://github.com/ricewind012/userstyles '/storage/nvme5/new_clones/Stylus/userstyles' &
git clone https://github.com/Akilarlxh/Butterfly_Candy '/storage/nvme5/new_clones/Stylus/Butterfly_Candy' &
git clone https://github.com/chenxz21/hexo-theme-bcxm '/storage/nvme5/new_clones/Stylus/hexo-theme-bcxm' &
git clone https://github.com/guixueting/guixueting.github.io '/storage/nvme5/new_clones/Stylus/guixuetinghub.io' &
git clone https://github.com/vednoc/custom-fonts '/storage/nvme5/new_clones/Stylus/custom-fonts' &
git clone https://github.com/kunpengcompute/kunpengcompute.github.io '/storage/nvme5/new_clones/Stylus/kunpengcomputehub.io' &
git clone https://github.com/GCL-Seminar/Awesome-Graphics-Papers '/storage/nvme5/new_clones/Stylus/Awesome-Graphics-Papers' &
git clone https://github.com/aeilot/hexo-theme-paperwhite '/storage/nvme5/new_clones/Stylus/hexo-theme-paperwhite' &
git clone https://github.com/FuShaoLei/hexo-theme-hiya '/storage/nvme5/new_clones/Stylus/hexo-theme-hiya' &
git clone https://github.com/kp-z/hexo-theme-unicorn '/storage/nvme5/new_clones/Stylus/hexo-theme-unicorn' &
git clone https://github.com/Akilarlxh/Tag_Plugins '/storage/nvme5/new_clones/Stylus/Tag_Plugins' &
git clone https://github.com/gpolek/blog.gpolek.com '/storage/nvme5/new_clones/Stylus/blog.gpolek.com' &
git clone https://github.com/jingtaiboke/jingtaiboke.github.io '/storage/nvme5/new_clones/Stylus/jingtaibokehub.io' &
git clone https://github.com/lewky/hexo-theme-beep '/storage/nvme5/new_clones/Stylus/hexo-theme-beep' &
git clone https://github.com/ivan-94/bobi.ink '/storage/nvme5/new_clones/Stylus/bobi.ink' &
git clone https://github.com/xiaoluoboding/vuepress-tailwind-theme-starter '/storage/nvme5/new_clones/Stylus/vuepress-tailwind-theme-starter' &
git clone https://github.com/muzi502/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/cylong1016/HexoBlog '/storage/nvme5/new_clones/Stylus/HexoBlog' &
git clone https://github.com/thinkerchan/hexo-theme-greyshade '/storage/nvme5/new_clones/Stylus/hexo-theme-greyshade' &
git clone https://github.com/btcpayserver/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/geist-org/themes '/storage/nvme5/new_clones/Stylus/themes' &
git clone https://github.com/clocklimited/responsive-grid '/storage/nvme5/new_clones/Stylus/responsive-grid' &
git clone https://github.com/tristan-mcdonald/tenet '/storage/nvme5/new_clones/Stylus/tenet' &
git clone https://github.com/eai04191/mastodon-deck-like-style '/storage/nvme5/new_clones/Stylus/mastodon-deck-like-style' &
git clone https://github.com/0xcert/docs '/storage/nvme5/new_clones/Stylus/docs' &
git clone https://github.com/fegemo/cefet-cg '/storage/nvme5/new_clones/Stylus/cefet-cg' &
git clone https://github.com/divawth/bell-ui '/storage/nvme5/new_clones/Stylus/bell-ui' &
git clone https://github.com/trendmicro-frontend/react-buttons '/storage/nvme5/new_clones/Stylus/react-buttons' &
git clone https://github.com/Yin-Hongwei/hexo-theme-Yin '/storage/nvme5/new_clones/Stylus/hexo-theme-Yin' &
git clone https://github.com/npulidom/vue-parcel '/storage/nvme5/new_clones/Stylus/vue-parcel' &
git clone https://github.com/antharuu/bubblegum '/storage/nvme5/new_clones/Stylus/bubblegum' &
git clone https://github.com/journey-ad/nocilol.me '/storage/nvme5/new_clones/Stylus/nocilol.me' &
git clone https://github.com/talgautb/vexillum '/storage/nvme5/new_clones/Stylus/vexillum' &
git clone https://github.com/ZevenFang/fangzf.me '/storage/nvme5/new_clones/Stylus/fangzf.me' &
git clone https://github.com/arBmind/2022-function-en '/storage/nvme5/new_clones/Stylus/2022-function-en' &
git clone https://github.com/Soitora/SweClockers-Dark '/storage/nvme5/new_clones/Stylus/SweClockers-Dark' &
git clone https://github.com/CaiChenghan/iLiKE '/storage/nvme5/new_clones/Stylus/iLiKE' &
git clone https://github.com/intave/documentation '/storage/nvme5/new_clones/Stylus/documentation' &
git clone https://github.com/realwds/realwds-blog '/storage/nvme5/new_clones/Stylus/realwds-blog' &
git clone https://github.com/zyhahaha/zyhahaha.github.io '/storage/nvme5/new_clones/Stylus/zyhahahahub.io' &
git clone https://github.com/hexojs/hexo-webui '/storage/nvme5/new_clones/Stylus/hexo-webui' &
git clone https://github.com/hanpfei/hanpfei-documents '/storage/nvme5/new_clones/Stylus/hanpfei-documents' &
git clone https://github.com/Small-Ku/focus-matters '/storage/nvme5/new_clones/Stylus/focus-matters' &
git clone https://github.com/geekrainy/hexo-theme-purely '/storage/nvme5/new_clones/Stylus/hexo-theme-purely' &
git clone https://github.com/StylusThemes/YouTube-Tweaks '/storage/nvme5/new_clones/Stylus/YouTube-Tweaks' &
git clone https://github.com/melitele/byways '/storage/nvme5/new_clones/Stylus/byways' &
git clone https://github.com/noionion/noionion.github.io '/storage/nvme5/new_clones/Stylus/noionionhub.io' &
git clone https://github.com/DyingDown/hexo-theme-last '/storage/nvme5/new_clones/Stylus/hexo-theme-last' &
git clone https://github.com/next-geek/next-geek '/storage/nvme5/new_clones/Stylus/next-geek' &
git clone https://github.com/thiagobraga/gmail-userstyles '/storage/nvme5/new_clones/Stylus/gmail-userstyles' &
git clone https://github.com/dukeluo/hexo-theme-candelas '/storage/nvme5/new_clones/Stylus/hexo-theme-candelas' &
git clone https://github.com/dnomak/flexiblegs-stylus '/storage/nvme5/new_clones/Stylus/flexiblegs-stylus' &
git clone https://github.com/jorge8168711/introducing-people-cards '/storage/nvme5/new_clones/Stylus/introducing-people-cards' &
git clone https://github.com/Honye/Honye.github.io '/storage/nvme5/new_clones/Stylus/Honyehub.io' &
git clone https://github.com/HeXA-UNIST/hexa-blog '/storage/nvme5/new_clones/Stylus/hexa-blog' &
git clone https://github.com/stephenLYZ/hexo-theme-windows-95 '/storage/nvme5/new_clones/Stylus/hexo-theme-windows-95' &
git clone https://github.com/BraveY/BraveY.github.io '/storage/nvme5/new_clones/Stylus/BraveYhub.io' &
git clone https://github.com/dmoosocool/hexo-theme-diaspora '/storage/nvme5/new_clones/Stylus/hexo-theme-diaspora' &
git clone https://github.com/JiangYongKang/JiangYongKang.github.io '/storage/nvme5/new_clones/Stylus/JiangYongKanghub.io' &
git clone https://github.com/cnyist/hexo-modify-theme-butterfly '/storage/nvme5/new_clones/Stylus/hexo-modify-theme-butterfly' &
git clone https://github.com/BKWLD/stylus-library '/storage/nvme5/new_clones/Stylus/stylus-library' &
git clone https://github.com/libevm/website '/storage/nvme5/new_clones/Stylus/website' &
git clone https://github.com/rashfael/buntpapier '/storage/nvme5/new_clones/Stylus/buntpapier' &
git clone https://github.com/ricewind012/4chan-win95 '/storage/nvme5/new_clones/Stylus/4chan-win95' &
git clone https://github.com/Djaler/vuetify-stylus-fixed-table-header '/storage/nvme5/new_clones/Stylus/vuetify-stylus-fixed-table-header' &
git clone https://github.com/vednoc/userstyles '/storage/nvme5/new_clones/Stylus/userstyles' &
git clone https://github.com/CristhGunners/MinimalHackerNews '/storage/nvme5/new_clones/Stylus/MinimalHackerNews' &
git clone https://github.com/alcidesqueiroz/tooltippy '/storage/nvme5/new_clones/Stylus/tooltippy' &
git clone https://github.com/ericon-io/comments '/storage/nvme5/new_clones/Stylus/comments' &
git clone https://github.com/guguliu/Hexo-butterfly-demo '/storage/nvme5/new_clones/Stylus/Hexo-butterfly-demo' &
git clone https://github.com/lwxisastudent/48calls '/storage/nvme5/new_clones/Stylus/48calls' &
git clone https://github.com/jorge8168711/Css-Acordeon '/storage/nvme5/new_clones/Stylus/Css-Acordeon' &
git clone https://github.com/G-Cinder/Memoranda '/storage/nvme5/new_clones/Stylus/Memoranda' &
git clone https://github.com/20minutes/colette '/storage/nvme5/new_clones/Stylus/colette' &
git clone https://github.com/vednoc/dark-switcher '/storage/nvme5/new_clones/Stylus/dark-switcher' &
git clone https://github.com/yahiarefaiea/2018.yahiarefaiea.com '/storage/nvme5/new_clones/Stylus/2018.yahiarefaiea.com' &
git clone https://github.com/atomantic/bespoke-theme-atomantic '/storage/nvme5/new_clones/Stylus/bespoke-theme-atomantic' &
git clone https://github.com/nufrankz/whatsapp-css '/storage/nvme5/new_clones/Stylus/whatsapp-css' &
git clone https://github.com/style-it-themes/dd-wrt-inspired-themes '/storage/nvme5/new_clones/Stylus/dd-wrt-inspired-themes' &
git clone https://github.com/can-dy-jack/hexo-theme-delicate '/storage/nvme5/new_clones/Stylus/hexo-theme-delicate' &
git clone https://github.com/louis70109/louis70109.github.io '/storage/nvme5/new_clones/Stylus/louis70109hub.io' &
git clone https://github.com/tigeroses/blog '/storage/nvme5/new_clones/Stylus/blog' &
git clone https://github.com/mikem33/pandora-boilerplate '/storage/nvme5/new_clones/Stylus/pandora-boilerplate' &
