#!/bin/bash

git clone https://github.com/lowRISC/opentitan '/storage/nvme5/new_clones/SystemVerilog/opentitan' &
git clone https://github.com/lowRISC/ibex '/storage/nvme5/new_clones/SystemVerilog/ibex' &
git clone https://github.com/pulp-platform/axi '/storage/nvme5/new_clones/SystemVerilog/axi' &
git clone https://github.com/itsfrank/MinecraftHDL '/storage/nvme5/new_clones/SystemVerilog/MinecraftHDL' &
git clone https://github.com/hdl-util/hdmi '/storage/nvme5/new_clones/SystemVerilog/hdmi' &
git clone https://github.com/rsd-devel/rsd '/storage/nvme5/new_clones/SystemVerilog/rsd' &
git clone https://github.com/openhwgroup/cv32e40p '/storage/nvme5/new_clones/SystemVerilog/cv32e40p' &
git clone https://github.com/hughperkins/VeriGPU '/storage/nvme5/new_clones/SystemVerilog/VeriGPU' &
git clone https://github.com/syntacore/scr1 '/storage/nvme5/new_clones/SystemVerilog/scr1' &
git clone https://github.com/westerndigitalcorporation/swerv_eh1 '/storage/nvme5/new_clones/SystemVerilog/swerv_eh1' &
git clone https://github.com/chipsalliance/Cores-VeeR-EH1 '/storage/nvme5/new_clones/SystemVerilog/Cores-VeeR-EH1' &
git clone https://github.com/hwayne/lets-prove-leftpad '/storage/nvme5/new_clones/SystemVerilog/lets-prove-leftpad' &
git clone https://github.com/black-parrot/black-parrot '/storage/nvme5/new_clones/SystemVerilog/black-parrot' &
git clone https://github.com/projf/projf-explore '/storage/nvme5/new_clones/SystemVerilog/projf-explore' &
git clone https://github.com/lowRISC/lowrisc-chip '/storage/nvme5/new_clones/SystemVerilog/lowrisc-chip' &
git clone https://github.com/trivialmips/nontrivial-mips '/storage/nvme5/new_clones/SystemVerilog/nontrivial-mips' &
git clone https://github.com/pulp-platform/common_cells '/storage/nvme5/new_clones/SystemVerilog/common_cells' &
git clone https://github.com/bespoke-silicon-group/basejump_stl '/storage/nvme5/new_clones/SystemVerilog/basejump_stl' &
git clone https://github.com/raysalemi/uvmprimer '/storage/nvme5/new_clones/SystemVerilog/uvmprimer' &
git clone https://github.com/pulp-platform/pulp '/storage/nvme5/new_clones/SystemVerilog/pulp' &
git clone https://github.com/openhwgroup/cvfpu '/storage/nvme5/new_clones/SystemVerilog/cvfpu' &
git clone https://github.com/VerificationExcellence/SystemVerilogReference '/storage/nvme5/new_clones/SystemVerilog/SystemVerilogReference' &
git clone https://github.com/pulp-platform/pulpissimo '/storage/nvme5/new_clones/SystemVerilog/pulpissimo' &
git clone https://github.com/facebookresearch/deepfloat '/storage/nvme5/new_clones/SystemVerilog/deepfloat' &
git clone https://github.com/taichi-ishitani/tvip-axi '/storage/nvme5/new_clones/SystemVerilog/tvip-axi' &
git clone https://github.com/raulbehl/100DaysOfRTL '/storage/nvme5/new_clones/SystemVerilog/100DaysOfRTL' &
git clone https://github.com/openhwgroup/cvw '/storage/nvme5/new_clones/SystemVerilog/cvw' &
git clone https://github.com/chipsalliance/sv-tests '/storage/nvme5/new_clones/SystemVerilog/sv-tests' &
git clone https://github.com/RoaLogic/RV12 '/storage/nvme5/new_clones/SystemVerilog/RV12' &
git clone https://github.com/RHSResearchLLC/NiteFury-and-LiteFury '/storage/nvme5/new_clones/SystemVerilog/NiteFury-and-LiteFury' &
git clone https://github.com/tymonx/logic '/storage/nvme5/new_clones/SystemVerilog/logic' &
git clone https://github.com/chipsalliance/Cores-VeeR-EL2 '/storage/nvme5/new_clones/SystemVerilog/Cores-VeeR-EL2' &
git clone https://github.com/VerificationExcellence/UVMReference '/storage/nvme5/new_clones/SystemVerilog/UVMReference' &
git clone https://github.com/bespoke-silicon-group/bsg_manycore '/storage/nvme5/new_clones/SystemVerilog/bsg_manycore' &
git clone https://github.com/pulp-platform/riscv-dbg '/storage/nvme5/new_clones/SystemVerilog/riscv-dbg' &
git clone https://github.com/fpgasystems/Coyote '/storage/nvme5/new_clones/SystemVerilog/Coyote' &
git clone https://github.com/openhwgroup/cv32e40x '/storage/nvme5/new_clones/SystemVerilog/cv32e40x' &
git clone https://github.com/chipsalliance/Cores-VeeR-EH2 '/storage/nvme5/new_clones/SystemVerilog/Cores-VeeR-EH2' &
git clone https://github.com/pulp-platform/snitch '/storage/nvme5/new_clones/SystemVerilog/snitch' &
git clone https://github.com/risclite/SuperScalar-RISCV-CPU '/storage/nvme5/new_clones/SystemVerilog/SuperScalar-RISCV-CPU' &
git clone https://github.com/svunit/svunit '/storage/nvme5/new_clones/SystemVerilog/svunit' &
git clone https://github.com/apfaudio/eurorack-pmod '/storage/nvme5/new_clones/SystemVerilog/eurorack-pmod' &
git clone https://github.com/mathis-s/SoomRV '/storage/nvme5/new_clones/SystemVerilog/SoomRV' &
git clone https://github.com/cluelogic/uvm-tutorial-for-candy-lovers '/storage/nvme5/new_clones/SystemVerilog/uvm-tutorial-for-candy-lovers' &
git clone https://github.com/subbdue/systemverilog.io '/storage/nvme5/new_clones/SystemVerilog/systemverilog.io' &
git clone https://github.com/tilk/riscv-simple-sv '/storage/nvme5/new_clones/SystemVerilog/riscv-simple-sv' &
git clone https://github.com/openhwgroup/core-v-mcu '/storage/nvme5/new_clones/SystemVerilog/core-v-mcu' &
git clone https://github.com/srg320/Saturn_MiSTer '/storage/nvme5/new_clones/SystemVerilog/Saturn_MiSTer' &
git clone https://github.com/taichi-ishitani/tnoc '/storage/nvme5/new_clones/SystemVerilog/tnoc' &
git clone https://github.com/courageheart/AMBA_APB_SRAM '/storage/nvme5/new_clones/SystemVerilog/AMBA_APB_SRAM' &
git clone https://github.com/aignacio/ravenoc '/storage/nvme5/new_clones/SystemVerilog/ravenoc' &
git clone https://github.com/intel/fpga-npu '/storage/nvme5/new_clones/SystemVerilog/fpga-npu' &
git clone https://github.com/GodelMachine/AHB2 '/storage/nvme5/new_clones/SystemVerilog/AHB2' &
git clone https://github.com/azonenberg/starshipraider '/storage/nvme5/new_clones/SystemVerilog/starshipraider' &
git clone https://github.com/openhwgroup/cv32e40s '/storage/nvme5/new_clones/SystemVerilog/cv32e40s' &
git clone https://github.com/karthisugumar/CSE240D-Hierarchical_Mesh_NoC-Eyeriss_v2 '/storage/nvme5/new_clones/SystemVerilog/CSE240D-Hierarchical_Mesh_NoC-Eyeriss_v2' &
git clone https://github.com/dpretet/axi-crossbar '/storage/nvme5/new_clones/SystemVerilog/axi-crossbar' &
git clone https://github.com/loykylewong/FPGA-Application-Development-and-Simulation '/storage/nvme5/new_clones/SystemVerilog/FPGA-Application-Development-and-Simulation' &
git clone https://github.com/mayurkubavat/UVM-Examples '/storage/nvme5/new_clones/SystemVerilog/UVM-Examples' &
git clone https://github.com/agalimberti/NoCRouter '/storage/nvme5/new_clones/SystemVerilog/NoCRouter' &
git clone https://github.com/kumarrishav14/AXI '/storage/nvme5/new_clones/SystemVerilog/AXI' &
git clone https://github.com/pulp-platform/iDMA '/storage/nvme5/new_clones/SystemVerilog/iDMA' &
git clone https://github.com/agg23/analogue-pocket-utils '/storage/nvme5/new_clones/SystemVerilog/analogue-pocket-utils' &
git clone https://github.com/ic-lab-duth/RISC-V-Vector '/storage/nvme5/new_clones/SystemVerilog/RISC-V-Vector' &
git clone https://github.com/lizhirui/AXI-SDCard-High-Speed-Controller '/storage/nvme5/new_clones/SystemVerilog/AXI-SDCard-High-Speed-Controller' &
git clone https://github.com/pulp-platform/register_interface '/storage/nvme5/new_clones/SystemVerilog/register_interface' &
git clone https://github.com/Xilinx/open-nic-shell '/storage/nvme5/new_clones/SystemVerilog/open-nic-shell' &
git clone https://github.com/trivialmips/TrivialMIPS '/storage/nvme5/new_clones/SystemVerilog/TrivialMIPS' &
git clone https://github.com/OPAE/intel-fpga-bbb '/storage/nvme5/new_clones/SystemVerilog/intel-fpga-bbb' &
git clone https://github.com/RC4ML/Shuhai '/storage/nvme5/new_clones/SystemVerilog/Shuhai' &
git clone https://github.com/StefanSredojevic/Deep-Neural-Network-Hardware-Accelerator '/storage/nvme5/new_clones/SystemVerilog/Deep-Neural-Network-Hardware-Accelerator' &
git clone https://github.com/spcl/pspin '/storage/nvme5/new_clones/SystemVerilog/pspin' &
git clone https://github.com/eliaskousk/parallella-riscv '/storage/nvme5/new_clones/SystemVerilog/parallella-riscv' &
git clone https://github.com/waviousllc/wav-lpddr-hw '/storage/nvme5/new_clones/SystemVerilog/wav-lpddr-hw' &
git clone https://github.com/pulp-platform/hero '/storage/nvme5/new_clones/SystemVerilog/hero' &
git clone https://github.com/krikzz/edn8-pro-pub '/storage/nvme5/new_clones/SystemVerilog/edn8-pro-pub' &
git clone https://github.com/daglem/reDIP-SID '/storage/nvme5/new_clones/SystemVerilog/reDIP-SID' &
git clone https://github.com/gundy/tiny-synth '/storage/nvme5/new_clones/SystemVerilog/tiny-synth' &
git clone https://github.com/Xilinx/kria-vitis-platforms '/storage/nvme5/new_clones/SystemVerilog/kria-vitis-platforms' &
git clone https://github.com/Verdvana/AXI4_Interconnect '/storage/nvme5/new_clones/SystemVerilog/AXI4_Interconnect' &
git clone https://github.com/nelsoncsc/ISP_UVM '/storage/nvme5/new_clones/SystemVerilog/ISP_UVM' &
git clone https://github.com/intel/fpga-partial-reconfig '/storage/nvme5/new_clones/SystemVerilog/fpga-partial-reconfig' &
git clone https://github.com/chipsalliance/uvm-verilator '/storage/nvme5/new_clones/SystemVerilog/uvm-verilator' &
git clone https://github.com/lowRISC/muntjac '/storage/nvme5/new_clones/SystemVerilog/muntjac' &
git clone https://github.com/RoaLogic/ahb3lite_interconnect '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_interconnect' &
git clone https://github.com/VerificationExcellence/SystemVerilogAssertions '/storage/nvme5/new_clones/SystemVerilog/SystemVerilogAssertions' &
git clone https://github.com/mbits-mirafra/SystemVerilogCourse '/storage/nvme5/new_clones/SystemVerilog/SystemVerilogCourse' &
git clone https://github.com/Siddhi-95/AHB-to-APB-Bridge-Verification '/storage/nvme5/new_clones/SystemVerilog/AHB-to-APB-Bridge-Verification' &
git clone https://github.com/seabeam/yuu_ahb '/storage/nvme5/new_clones/SystemVerilog/yuu_ahb' &
git clone https://github.com/YosysHQ/nerv '/storage/nvme5/new_clones/SystemVerilog/nerv' &
git clone https://github.com/Lampro-Mellon/LM-RISCV-DV '/storage/nvme5/new_clones/SystemVerilog/LM-RISCV-DV' &
git clone https://github.com/dovstamler/uvm_agents '/storage/nvme5/new_clones/SystemVerilog/uvm_agents' &
git clone https://github.com/amiq-consulting/svaunit '/storage/nvme5/new_clones/SystemVerilog/svaunit' &
git clone https://github.com/sach/System-Verilog-Packet-Library '/storage/nvme5/new_clones/SystemVerilog/System-Verilog-Packet-Library' &
git clone https://github.com/f4pga/prjuray '/storage/nvme5/new_clones/SystemVerilog/prjuray' &
git clone https://github.com/ananthbhat94/DDR4MemoryController '/storage/nvme5/new_clones/SystemVerilog/DDR4MemoryController' &
git clone https://github.com/BrianHGinc/BrianHG-DDR3-Controller '/storage/nvme5/new_clones/SystemVerilog/BrianHG-DDR3-Controller' &
git clone https://github.com/KastnerRG/cgra4ml '/storage/nvme5/new_clones/SystemVerilog/cgra4ml' &
git clone https://github.com/chipfail/chipfail-glitcher '/storage/nvme5/new_clones/SystemVerilog/chipfail-glitcher' &
git clone https://github.com/amiq-consulting/amiq_apb '/storage/nvme5/new_clones/SystemVerilog/amiq_apb' &
git clone https://github.com/crossroadsfpga/enso '/storage/nvme5/new_clones/SystemVerilog/enso' &
git clone https://github.com/SonalPinto/kronos '/storage/nvme5/new_clones/SystemVerilog/kronos' &
git clone https://github.com/Pusty/writeups '/storage/nvme5/new_clones/SystemVerilog/writeups' &
git clone https://github.com/grayresearch/CX '/storage/nvme5/new_clones/SystemVerilog/CX' &
git clone https://github.com/pulp-platform/pulp_cluster '/storage/nvme5/new_clones/SystemVerilog/pulp_cluster' &
git clone https://github.com/hdl-util/mipi-csi-2 '/storage/nvme5/new_clones/SystemVerilog/mipi-csi-2' &
git clone https://github.com/openhwgroup/cva5 '/storage/nvme5/new_clones/SystemVerilog/cva5' &
git clone https://github.com/tishi43/h265_decoder '/storage/nvme5/new_clones/SystemVerilog/h265_decoder' &
git clone https://github.com/azonenberg/antikernel-ipcores '/storage/nvme5/new_clones/SystemVerilog/antikernel-ipcores' &
git clone https://github.com/fpgasystems/davos '/storage/nvme5/new_clones/SystemVerilog/davos' &
git clone https://github.com/openhwgroup/core-v-xif '/storage/nvme5/new_clones/SystemVerilog/core-v-xif' &
git clone https://github.com/pulp-platform/axi_riscv_atomics '/storage/nvme5/new_clones/SystemVerilog/axi_riscv_atomics' &
git clone https://github.com/davemuscle/sigma_delta_converters '/storage/nvme5/new_clones/SystemVerilog/sigma_delta_converters' &
git clone https://github.com/mikeroyal/Verilog-SystemVerilog-Guide '/storage/nvme5/new_clones/SystemVerilog/Verilog-SystemVerilog-Guide' &
git clone https://github.com/hypernyan/eth_vlg '/storage/nvme5/new_clones/SystemVerilog/eth_vlg' &
git clone https://github.com/jerralph/riscv-vip '/storage/nvme5/new_clones/SystemVerilog/riscv-vip' &
git clone https://github.com/dadongshangu/async_FIFO '/storage/nvme5/new_clones/SystemVerilog/async_FIFO' &
git clone https://github.com/MiSTer-devel/S32X_MiSTer '/storage/nvme5/new_clones/SystemVerilog/S32X_MiSTer' &
git clone https://github.com/siliconcompiler/zerosoc '/storage/nvme5/new_clones/SystemVerilog/zerosoc' &
git clone https://github.com/muneebullashariff/axi4_vip '/storage/nvme5/new_clones/SystemVerilog/axi4_vip' &
git clone https://github.com/hanysalah/Design-Pattern-in-SV '/storage/nvme5/new_clones/SystemVerilog/Design-Pattern-in-SV' &
git clone https://github.com/sifferman/labs-with-cva6 '/storage/nvme5/new_clones/SystemVerilog/labs-with-cva6' &
git clone https://github.com/ucam-comparch/clarvi '/storage/nvme5/new_clones/SystemVerilog/clarvi' &
git clone https://github.com/bsdevlin/fpga_snark_prover '/storage/nvme5/new_clones/SystemVerilog/fpga_snark_prover' &
git clone https://github.com/doswellf/combinator-uvm '/storage/nvme5/new_clones/SystemVerilog/combinator-uvm' &
git clone https://github.com/Featherweight-IP/fwrisc '/storage/nvme5/new_clones/SystemVerilog/fwrisc' &
git clone https://github.com/dpretet/cdc '/storage/nvme5/new_clones/SystemVerilog/cdc' &
git clone https://github.com/oprecomp/DDR4_controller '/storage/nvme5/new_clones/SystemVerilog/DDR4_controller' &
git clone https://github.com/pulp-platform/bigpulp '/storage/nvme5/new_clones/SystemVerilog/bigpulp' &
git clone https://github.com/CestSansImportance/SNN-FPGA '/storage/nvme5/new_clones/SystemVerilog/SNN-FPGA' &
git clone https://github.com/swetland/zynq-sandbox '/storage/nvme5/new_clones/SystemVerilog/zynq-sandbox' &
git clone https://github.com/aignacio/axi_dma '/storage/nvme5/new_clones/SystemVerilog/axi_dma' &
git clone https://github.com/hyperreality/ctf-writeups '/storage/nvme5/new_clones/SystemVerilog/ctf-writeups' &
git clone https://github.com/emwzq/example_uvm '/storage/nvme5/new_clones/SystemVerilog/example_uvm' &
git clone https://github.com/johan92/fpga-hash-table '/storage/nvme5/new_clones/SystemVerilog/fpga-hash-table' &
git clone https://github.com/swetland/gateware '/storage/nvme5/new_clones/SystemVerilog/gateware' &
git clone https://github.com/supranational/vdf-fpga '/storage/nvme5/new_clones/SystemVerilog/vdf-fpga' &
git clone https://github.com/ttchisholm/10g-low-latency-ethernet '/storage/nvme5/new_clones/SystemVerilog/10g-low-latency-ethernet' &
git clone https://github.com/akzare/Async_FIFO_Verification '/storage/nvme5/new_clones/SystemVerilog/Async_FIFO_Verification' &
git clone https://github.com/Travissss/ahb2apb-bridge '/storage/nvme5/new_clones/SystemVerilog/ahb2apb-bridge' &
git clone https://github.com/tymonx/virtio '/storage/nvme5/new_clones/SystemVerilog/virtio' &
git clone https://github.com/pbing/FM_Radio '/storage/nvme5/new_clones/SystemVerilog/FM_Radio' &
git clone https://github.com/Superscalar-HIT-Core/Superscalar-HIT-Core-NSCSCC2020 '/storage/nvme5/new_clones/SystemVerilog/Superscalar-HIT-Core-NSCSCC2020' &
git clone https://github.com/accellera/uvm '/storage/nvme5/new_clones/SystemVerilog/uvm' &
git clone https://github.com/makestuff/altera-pcie '/storage/nvme5/new_clones/SystemVerilog/altera-pcie' &
git clone https://github.com/luuvish/amba3-vip '/storage/nvme5/new_clones/SystemVerilog/amba3-vip' &
git clone https://github.com/pulp-platform/common_verification '/storage/nvme5/new_clones/SystemVerilog/common_verification' &
git clone https://github.com/esnet/esnet-smartnic-hw '/storage/nvme5/new_clones/SystemVerilog/esnet-smartnic-hw' &
git clone https://github.com/hjking/uvm_gen '/storage/nvme5/new_clones/SystemVerilog/uvm_gen' &
git clone https://github.com/ben-marshall/croyde-riscv '/storage/nvme5/new_clones/SystemVerilog/croyde-riscv' &
git clone https://github.com/sgherbst/svreal '/storage/nvme5/new_clones/SystemVerilog/svreal' &
git clone https://github.com/kvablack/fpga-flight-controller '/storage/nvme5/new_clones/SystemVerilog/fpga-flight-controller' &
git clone https://github.com/shehanmunasinghe/tinyGPU '/storage/nvme5/new_clones/SystemVerilog/tinyGPU' &
git clone https://github.com/zhouchuanrui/JSONinSV '/storage/nvme5/new_clones/SystemVerilog/JSONinSV' &
git clone https://github.com/diwu1990/UnarySim '/storage/nvme5/new_clones/SystemVerilog/UnarySim' &
git clone https://github.com/pulp-platform/tech_cells_generic '/storage/nvme5/new_clones/SystemVerilog/tech_cells_generic' &
git clone https://github.com/Shehab-Naga/ddr5_phy '/storage/nvme5/new_clones/SystemVerilog/ddr5_phy' &
git clone https://github.com/tinyvision-ai-inc/Hands-on-FPGA-class '/storage/nvme5/new_clones/SystemVerilog/Hands-on-FPGA-class' &
git clone https://github.com/k0nze/zedboard_axi4_master_burst_example '/storage/nvme5/new_clones/SystemVerilog/zedboard_axi4_master_burst_example' &
git clone https://github.com/NSCSCC-2020-Fudan/FDU1.1-NSCSCC '/storage/nvme5/new_clones/SystemVerilog/FDU1.1-NSCSCC' &
git clone https://github.com/muneebullashariff/i2c_vip '/storage/nvme5/new_clones/SystemVerilog/i2c_vip' &
git clone https://github.com/j-marjanovic/pp-sp-reference-design '/storage/nvme5/new_clones/SystemVerilog/pp-sp-reference-design' &
git clone https://github.com/RoaLogic/ahb3lite_apb_bridge '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_apb_bridge' &
git clone https://github.com/pulp-platform/redmule '/storage/nvme5/new_clones/SystemVerilog/redmule' &
git clone https://github.com/whatmough/CHIPKIT '/storage/nvme5/new_clones/SystemVerilog/CHIPKIT' &
git clone https://github.com/ARM-software/DeepFreeze '/storage/nvme5/new_clones/SystemVerilog/DeepFreeze' &
git clone https://github.com/ARC-Lab-UF/intel-training-modules '/storage/nvme5/new_clones/SystemVerilog/intel-training-modules' &
git clone https://github.com/pulp-platform/fpu '/storage/nvme5/new_clones/SystemVerilog/fpu' &
git clone https://github.com/KOTHAVANI/100-Days-of-RTL-code '/storage/nvme5/new_clones/SystemVerilog/100-Days-of-RTL-code' &
git clone https://github.com/ThalesGroup/cva6-softcore-contest '/storage/nvme5/new_clones/SystemVerilog/cva6-softcore-contest' &
git clone https://github.com/howard789/uvm_example '/storage/nvme5/new_clones/SystemVerilog/uvm_example' &
git clone https://github.com/OpenXiangShan/XS-Verilog-Library '/storage/nvme5/new_clones/SystemVerilog/XS-Verilog-Library' &
git clone https://github.com/darthsider/UART '/storage/nvme5/new_clones/SystemVerilog/UART' &
git clone https://github.com/adamchristiansen/fpga-ethernet-udp '/storage/nvme5/new_clones/SystemVerilog/fpga-ethernet-udp' &
git clone https://github.com/Poofjunior/fpga_fast_serial_sort '/storage/nvme5/new_clones/SystemVerilog/fpga_fast_serial_sort' &
git clone https://github.com/microsoft/DUA '/storage/nvme5/new_clones/SystemVerilog/DUA' &
git clone https://github.com/Anjali-287/SPI-Interface '/storage/nvme5/new_clones/SystemVerilog/SPI-Interface' &
git clone https://github.com/vishal1303/PIEO-Scheduler '/storage/nvme5/new_clones/SystemVerilog/PIEO-Scheduler' &
git clone https://github.com/nelsoncsc/easyUVM '/storage/nvme5/new_clones/SystemVerilog/easyUVM' &
git clone https://github.com/vinodsake/NAND-Flash-Memory-Controller-verification '/storage/nvme5/new_clones/SystemVerilog/NAND-Flash-Memory-Controller-verification' &
git clone https://github.com/mbits-mirafra/UVMCourse '/storage/nvme5/new_clones/SystemVerilog/UVMCourse' &
git clone https://github.com/abdelrhman-oun/DDR5_PHY_WriteOperation '/storage/nvme5/new_clones/SystemVerilog/DDR5_PHY_WriteOperation' &
git clone https://github.com/justcatthefish/justctf-2019 '/storage/nvme5/new_clones/SystemVerilog/justctf-2019' &
git clone https://github.com/ironsteel/nes_ecp5 '/storage/nvme5/new_clones/SystemVerilog/nes_ecp5' &
git clone https://github.com/pulp-platform/axi_mem_if '/storage/nvme5/new_clones/SystemVerilog/axi_mem_if' &
git clone https://github.com/YosysHQ-GmbH/SVA-AXI4-FVIP '/storage/nvme5/new_clones/SystemVerilog/SVA-AXI4-FVIP' &
git clone https://github.com/pezy-computing/pzbcm '/storage/nvme5/new_clones/SystemVerilog/pzbcm' &
git clone https://github.com/JoseIuri/UVM-APB_RAL '/storage/nvme5/new_clones/SystemVerilog/UVM-APB_RAL' &
git clone https://github.com/kaushalmodi/custom_uvm_report_server '/storage/nvme5/new_clones/SystemVerilog/custom_uvm_report_server' &
git clone https://github.com/martinKindall/risc-v-single-cycle '/storage/nvme5/new_clones/SystemVerilog/risc-v-single-cycle' &
git clone https://github.com/qleenju/PDPU '/storage/nvme5/new_clones/SystemVerilog/PDPU' &
git clone https://github.com/esynr3z/proto245 '/storage/nvme5/new_clones/SystemVerilog/proto245' &
git clone https://github.com/Lampro-Mellon/apb-uart-uvm-env '/storage/nvme5/new_clones/SystemVerilog/apb-uart-uvm-env' &
git clone https://github.com/MatrixAINetwork/Sampling-Model '/storage/nvme5/new_clones/SystemVerilog/Sampling-Model' &
git clone https://github.com/RoaLogic/plic '/storage/nvme5/new_clones/SystemVerilog/plic' &
git clone https://github.com/Maxpicca-Li/CDIM '/storage/nvme5/new_clones/SystemVerilog/CDIM' &
git clone https://github.com/NotCamelCase/Pathsy '/storage/nvme5/new_clones/SystemVerilog/Pathsy' &
git clone https://github.com/cjdrake/AES '/storage/nvme5/new_clones/SystemVerilog/AES' &
git clone https://github.com/bhunt2/DDR4Sim '/storage/nvme5/new_clones/SystemVerilog/DDR4Sim' &
git clone https://github.com/AI-Vector-Accelerator/ava-core '/storage/nvme5/new_clones/SystemVerilog/ava-core' &
git clone https://github.com/dumpo/my_verilog_projects '/storage/nvme5/new_clones/SystemVerilog/my_verilog_projects' &
git clone https://github.com/WukLab/FPGA-OS '/storage/nvme5/new_clones/SystemVerilog/FPGA-OS' &
git clone https://github.com/nelsoncsc/sv_image '/storage/nvme5/new_clones/SystemVerilog/sv_image' &
git clone https://github.com/raiker/tarsier '/storage/nvme5/new_clones/SystemVerilog/tarsier' &
git clone https://github.com/esynr3z/usb20dev '/storage/nvme5/new_clones/SystemVerilog/usb20dev' &
git clone https://github.com/chiggs/UVM '/storage/nvme5/new_clones/SystemVerilog/UVM' &
git clone https://github.com/EEESlab/combinational-bnn '/storage/nvme5/new_clones/SystemVerilog/combinational-bnn' &
git clone https://github.com/esynr3z/axi_vip_demo '/storage/nvme5/new_clones/SystemVerilog/axi_vip_demo' &
git clone https://github.com/ObKo/USBCore '/storage/nvme5/new_clones/SystemVerilog/USBCore' &
git clone https://github.com/designsolver/ahb3_uvm_tb '/storage/nvme5/new_clones/SystemVerilog/ahb3_uvm_tb' &
git clone https://github.com/ericlewis/openfpga-spacerace '/storage/nvme5/new_clones/SystemVerilog/openfpga-spacerace' &
git clone https://github.com/gvekony/sv-1800-2012 '/storage/nvme5/new_clones/SystemVerilog/sv-1800-2012' &
git clone https://github.com/uvmdebug/uvm_debug '/storage/nvme5/new_clones/SystemVerilog/uvm_debug' &
git clone https://github.com/yvnr4you/AMBA_AXI3 '/storage/nvme5/new_clones/SystemVerilog/AMBA_AXI3' &
git clone https://github.com/snbk001/100DaysofRTL '/storage/nvme5/new_clones/SystemVerilog/100DaysofRTL' &
git clone https://github.com/aseddin/ece_4305 '/storage/nvme5/new_clones/SystemVerilog/ece_4305' &
git clone https://github.com/amichai-bd/riscv-multi-core-lotr '/storage/nvme5/new_clones/SystemVerilog/riscv-multi-core-lotr' &
git clone https://github.com/ekiwi/rtl-fuzz-lab '/storage/nvme5/new_clones/SystemVerilog/rtl-fuzz-lab' &
git clone https://github.com/Dmitriy0111/nanoFOX '/storage/nvme5/new_clones/SystemVerilog/nanoFOX' &
git clone https://github.com/Open-Source-Hardware-Initiative/AES '/storage/nvme5/new_clones/SystemVerilog/AES' &
git clone https://github.com/seabeam/yuu_apb '/storage/nvme5/new_clones/SystemVerilog/yuu_apb' &
git clone https://github.com/yuravg/uvm_tb_cross_bar '/storage/nvme5/new_clones/SystemVerilog/uvm_tb_cross_bar' &
git clone https://github.com/nahidrn/axi_vip_master '/storage/nvme5/new_clones/SystemVerilog/axi_vip_master' &
git clone https://github.com/anycore/anycore-riscv-src '/storage/nvme5/new_clones/SystemVerilog/anycore-riscv-src' &
git clone https://github.com/avashist003/UVM_Verification '/storage/nvme5/new_clones/SystemVerilog/UVM_Verification' &
git clone https://github.com/ecilasun/NekoIchi '/storage/nvme5/new_clones/SystemVerilog/NekoIchi' &
git clone https://github.com/ic-lab-duth/DRIM-S '/storage/nvme5/new_clones/SystemVerilog/DRIM-S' &
git clone https://github.com/kaushalmodi/nim-systemverilog-dpic '/storage/nvme5/new_clones/SystemVerilog/nim-systemverilog-dpic' &
git clone https://github.com/RoaLogic/Hamming-ECC '/storage/nvme5/new_clones/SystemVerilog/Hamming-ECC' &
git clone https://github.com/balmerdx/sdio_linux_fpga '/storage/nvme5/new_clones/SystemVerilog/sdio_linux_fpga' &
git clone https://github.com/designsolver/ahb2apb_bridge_vip '/storage/nvme5/new_clones/SystemVerilog/ahb2apb_bridge_vip' &
git clone https://github.com/carsonrobles/fpga-guitar-pedal '/storage/nvme5/new_clones/SystemVerilog/fpga-guitar-pedal' &
git clone https://github.com/alaasal/GPCore '/storage/nvme5/new_clones/SystemVerilog/GPCore' &
git clone https://github.com/RSPwFPGAs/virtio-fpga-bridge '/storage/nvme5/new_clones/SystemVerilog/virtio-fpga-bridge' &
git clone https://github.com/martinriis/RISC-V-Vector-Processor '/storage/nvme5/new_clones/SystemVerilog/RISC-V-Vector-Processor' &
git clone https://github.com/hildebrandmw/de10lite-hdl '/storage/nvme5/new_clones/SystemVerilog/de10lite-hdl' &
git clone https://github.com/taichi-ishitani/tvip-apb '/storage/nvme5/new_clones/SystemVerilog/tvip-apb' &
git clone https://github.com/wenxuan-hu/SSRL_work '/storage/nvme5/new_clones/SystemVerilog/SSRL_work' &
git clone https://github.com/pulp-platform/jtag_dpi '/storage/nvme5/new_clones/SystemVerilog/jtag_dpi' &
git clone https://github.com/Xilinx/RFNoC-HLS-ATSC-RX '/storage/nvme5/new_clones/SystemVerilog/RFNoC-HLS-ATSC-RX' &
git clone https://github.com/mxg/svx '/storage/nvme5/new_clones/SystemVerilog/svx' &
git clone https://github.com/PacoReinaCampo/MPSoC-DV '/storage/nvme5/new_clones/SystemVerilog/MPSoC-DV' &
git clone https://github.com/flyskywalker/ahb_sramc '/storage/nvme5/new_clones/SystemVerilog/ahb_sramc' &
git clone https://github.com/muzafferkal/axi-bfm '/storage/nvme5/new_clones/SystemVerilog/axi-bfm' &
git clone https://github.com/openhwgroup/cv32e41p '/storage/nvme5/new_clones/SystemVerilog/cv32e41p' &
git clone https://github.com/merledu/azadi-soc '/storage/nvme5/new_clones/SystemVerilog/azadi-soc' &
git clone https://github.com/gokulbalagopal/Verification-of-FIFO-using-SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/Verification-of-FIFO-using-SystemVerilog' &
git clone https://github.com/muneeb-mbytes/axi4_avip '/storage/nvme5/new_clones/SystemVerilog/axi4_avip' &
git clone https://github.com/mbits-mirafra/axi4_avip '/storage/nvme5/new_clones/SystemVerilog/axi4_avip' &
git clone https://github.com/besm6/micro-besm '/storage/nvme5/new_clones/SystemVerilog/micro-besm' &
git clone https://github.com/hdl-util/i2c '/storage/nvme5/new_clones/SystemVerilog/i2c' &
git clone https://github.com/thomask77/verilog-sid-mos6581 '/storage/nvme5/new_clones/SystemVerilog/verilog-sid-mos6581' &
git clone https://github.com/luuvish/system-verilog-patterns '/storage/nvme5/new_clones/SystemVerilog/system-verilog-patterns' &
git clone https://github.com/programer-guan/digital_ic_verification '/storage/nvme5/new_clones/SystemVerilog/digital_ic_verification' &
git clone https://github.com/PacoReinaCampo/MPSoC-NoC '/storage/nvme5/new_clones/SystemVerilog/MPSoC-NoC' &
git clone https://github.com/amiq-consulting/yamm '/storage/nvme5/new_clones/SystemVerilog/yamm' &
git clone https://github.com/zhajio1988/ExtremeDV_UVM '/storage/nvme5/new_clones/SystemVerilog/ExtremeDV_UVM' &
git clone https://github.com/AkeelMedina22/RISC-V-Pipelined-Processor '/storage/nvme5/new_clones/SystemVerilog/RISC-V-Pipelined-Processor' &
git clone https://github.com/black-parrot-hdk/zynq-parrot '/storage/nvme5/new_clones/SystemVerilog/zynq-parrot' &
git clone https://github.com/Poofjunior/HardwareModules '/storage/nvme5/new_clones/SystemVerilog/HardwareModules' &
git clone https://github.com/pulp-platform/uvm-components '/storage/nvme5/new_clones/SystemVerilog/uvm-components' &
git clone https://github.com/zhelnio/mil1553-spi '/storage/nvme5/new_clones/SystemVerilog/mil1553-spi' &
git clone https://github.com/bensampson5/libsv '/storage/nvme5/new_clones/SystemVerilog/libsv' &
git clone https://github.com/krikzz/tot6502 '/storage/nvme5/new_clones/SystemVerilog/tot6502' &
git clone https://github.com/advanced-uvm/second_edition '/storage/nvme5/new_clones/SystemVerilog/second_edition' &
git clone https://github.com/ljgibbslf/basic_cache_core '/storage/nvme5/new_clones/SystemVerilog/basic_cache_core' &
git clone https://github.com/StanfordVLSI/dragonphy2 '/storage/nvme5/new_clones/SystemVerilog/dragonphy2' &
git clone https://github.com/RSPwFPGAs/virtio-fpga '/storage/nvme5/new_clones/SystemVerilog/virtio-fpga' &
git clone https://github.com/Verdvana/AXI_SRAM '/storage/nvme5/new_clones/SystemVerilog/AXI_SRAM' &
git clone https://github.com/pulp-platform/clint '/storage/nvme5/new_clones/SystemVerilog/clint' &
git clone https://github.com/SymbioticEDA/nerv '/storage/nvme5/new_clones/SystemVerilog/nerv' &
git clone https://github.com/riscv-verification/riscvISACOV '/storage/nvme5/new_clones/SystemVerilog/riscvISACOV' &
git clone https://github.com/chipsalliance/aib-protocols '/storage/nvme5/new_clones/SystemVerilog/aib-protocols' &
git clone https://github.com/isuckatdrifting/Gaia '/storage/nvme5/new_clones/SystemVerilog/Gaia' &
git clone https://github.com/vfinotti/cortex-m0-soft-microcontroller '/storage/nvme5/new_clones/SystemVerilog/cortex-m0-soft-microcontroller' &
git clone https://github.com/muneebullashariff/apb_vip '/storage/nvme5/new_clones/SystemVerilog/apb_vip' &
git clone https://github.com/NetTLP/adapter '/storage/nvme5/new_clones/SystemVerilog/adapter' &
git clone https://github.com/avashist003/SystemVerilog_Design_Verification '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog_Design_Verification' &
git clone https://github.com/mcrl/soff-hardware-opae '/storage/nvme5/new_clones/SystemVerilog/soff-hardware-opae' &
git clone https://github.com/letitbe0201/AXI-DMA-master-verification '/storage/nvme5/new_clones/SystemVerilog/AXI-DMA-master-verification' &
git clone https://github.com/pulp-platform/axi_spi_slave '/storage/nvme5/new_clones/SystemVerilog/axi_spi_slave' &
git clone https://github.com/kkenshin1/AXI-Ethernet-UVM '/storage/nvme5/new_clones/SystemVerilog/AXI-Ethernet-UVM' &
git clone https://github.com/pulp-platform/stream-ebpc '/storage/nvme5/new_clones/SystemVerilog/stream-ebpc' &
git clone https://github.com/mingzhang952/uvm_auto '/storage/nvme5/new_clones/SystemVerilog/uvm_auto' &
git clone https://github.com/myriadrf/LimeADPD '/storage/nvme5/new_clones/SystemVerilog/LimeADPD' &
git clone https://github.com/PacoReinaCampo/SoC-DV '/storage/nvme5/new_clones/SystemVerilog/SoC-DV' &
git clone https://github.com/dpretet/friscv '/storage/nvme5/new_clones/SystemVerilog/friscv' &
git clone https://github.com/xerpi/tiny5 '/storage/nvme5/new_clones/SystemVerilog/tiny5' &
git clone https://github.com/recogni/svlib '/storage/nvme5/new_clones/SystemVerilog/svlib' &
git clone https://github.com/stcmtk/fpga-webinar-2020 '/storage/nvme5/new_clones/SystemVerilog/fpga-webinar-2020' &
git clone https://github.com/antoinemadec/uvm_code_gen '/storage/nvme5/new_clones/SystemVerilog/uvm_code_gen' &
git clone https://github.com/muneeb-mbytes/spi_avip '/storage/nvme5/new_clones/SystemVerilog/spi_avip' &
git clone https://github.com/AsFigo/ivl_uvm '/storage/nvme5/new_clones/SystemVerilog/ivl_uvm' &
git clone https://github.com/maltevesper/JetStream-hardware '/storage/nvme5/new_clones/SystemVerilog/JetStream-hardware' &
git clone https://github.com/dovoto/FPGA_Gameboy_Watch '/storage/nvme5/new_clones/SystemVerilog/FPGA_Gameboy_Watch' &
git clone https://github.com/pulp-platform/axi_llc '/storage/nvme5/new_clones/SystemVerilog/axi_llc' &
git clone https://github.com/muneeb-mbytes/apb_avip '/storage/nvme5/new_clones/SystemVerilog/apb_avip' &
git clone https://github.com/Efinix-Inc/evsoc '/storage/nvme5/new_clones/SystemVerilog/evsoc' &
git clone https://github.com/gchinna/uvm-1.2 '/storage/nvme5/new_clones/SystemVerilog/uvm-1.2' &
git clone https://github.com/MushroomZQ/RISC_VERIF_DEMO_0 '/storage/nvme5/new_clones/SystemVerilog/RISC_VERIF_DEMO_0' &
git clone https://github.com/hossein1387/pito_riscv '/storage/nvme5/new_clones/SystemVerilog/pito_riscv' &
git clone https://github.com/intel/pfr-wilson-city '/storage/nvme5/new_clones/SystemVerilog/pfr-wilson-city' &
git clone https://github.com/supranational/hardware '/storage/nvme5/new_clones/SystemVerilog/hardware' &
git clone https://github.com/Dongtata2020/UVM_Verification_for_P2S_Data_Converter '/storage/nvme5/new_clones/SystemVerilog/UVM_Verification_for_P2S_Data_Converter' &
git clone https://github.com/tej-chavan/Design-and-Verification-of-DDR3-Memory-Controller '/storage/nvme5/new_clones/SystemVerilog/Design-and-Verification-of-DDR3-Memory-Controller' &
git clone https://github.com/racerxdl/pcieledblink '/storage/nvme5/new_clones/SystemVerilog/pcieledblink' &
git clone https://github.com/PacoReinaCampo/SoC-RISCV '/storage/nvme5/new_clones/SystemVerilog/SoC-RISCV' &
git clone https://github.com/hdl-util/mipi-ccs '/storage/nvme5/new_clones/SystemVerilog/mipi-ccs' &
git clone https://github.com/srishis/DMA8237A '/storage/nvme5/new_clones/SystemVerilog/DMA8237A' &
git clone https://github.com/georgeyhere/FPGA-Video-Processing '/storage/nvme5/new_clones/SystemVerilog/FPGA-Video-Processing' &
git clone https://github.com/A-T-Kristensen/simple-alu-uvm '/storage/nvme5/new_clones/SystemVerilog/simple-alu-uvm' &
git clone https://github.com/taichi-ishitani/tue '/storage/nvme5/new_clones/SystemVerilog/tue' &
git clone https://github.com/hanysalah/uart2bustestbench '/storage/nvme5/new_clones/SystemVerilog/uart2bustestbench' &
git clone https://github.com/grant4001/MNIST_Classification_FPGA '/storage/nvme5/new_clones/SystemVerilog/MNIST_Classification_FPGA' &
git clone https://github.com/chenshuo/veriloglabs '/storage/nvme5/new_clones/SystemVerilog/veriloglabs' &
git clone https://github.com/toivoh/rastrgrafx '/storage/nvme5/new_clones/SystemVerilog/rastrgrafx' &
git clone https://github.com/bvnirliptha/AMBA-3-AHB--LITE-Protocol-Design-and-Verification '/storage/nvme5/new_clones/SystemVerilog/AMBA-3-AHB--LITE-Protocol-Design-and-Verification' &
git clone https://github.com/RoaLogic/ahb3lite_memory '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_memory' &
git clone https://github.com/tianrenz2/Single-Cycle-Processor '/storage/nvme5/new_clones/SystemVerilog/Single-Cycle-Processor' &
git clone https://github.com/vlotnik/uvm_sin_cos_table '/storage/nvme5/new_clones/SystemVerilog/uvm_sin_cos_table' &
git clone https://github.com/muneeb-mbytes/pulpino__spi_master__ip_verification '/storage/nvme5/new_clones/SystemVerilog/pulpino__spi_master__ip_verification' &
git clone https://github.com/ForwardCom/softcoreA '/storage/nvme5/new_clones/SystemVerilog/softcoreA' &
git clone https://github.com/medalotte/SystemVerilog-UART '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog-UART' &
git clone https://github.com/fpgasystems/dma-driver '/storage/nvme5/new_clones/SystemVerilog/dma-driver' &
git clone https://github.com/raysalemi/fpgasimulation '/storage/nvme5/new_clones/SystemVerilog/fpgasimulation' &
git clone https://github.com/dh73/A_Formal_Tale_Chapter_I_AMBA '/storage/nvme5/new_clones/SystemVerilog/A_Formal_Tale_Chapter_I_AMBA' &
git clone https://github.com/harpreetbhatia/sv_practice '/storage/nvme5/new_clones/SystemVerilog/sv_practice' &
git clone https://github.com/nguyenquanicd/UvmEnvUartApb '/storage/nvme5/new_clones/SystemVerilog/UvmEnvUartApb' &
git clone https://github.com/KafCoppelia/uvm-mcdf '/storage/nvme5/new_clones/SystemVerilog/uvm-mcdf' &
git clone https://github.com/pulp-platform/axi_spi_master '/storage/nvme5/new_clones/SystemVerilog/axi_spi_master' &
git clone https://github.com/go2uvm/go2uvm '/storage/nvme5/new_clones/SystemVerilog/go2uvm' &
git clone https://github.com/jiegec/verilog-format '/storage/nvme5/new_clones/SystemVerilog/verilog-format' &
git clone https://github.com/pgroupATusc/fasthash '/storage/nvme5/new_clones/SystemVerilog/fasthash' &
git clone https://github.com/openformal/sva_basics '/storage/nvme5/new_clones/SystemVerilog/sva_basics' &
git clone https://github.com/ic-lab-duth/DRIM '/storage/nvme5/new_clones/SystemVerilog/DRIM' &
git clone https://github.com/JulianKemmerer/Drexel-ECEC575 '/storage/nvme5/new_clones/SystemVerilog/Drexel-ECEC575' &
git clone https://github.com/fpga-soc/mil-std-1553b-soc '/storage/nvme5/new_clones/SystemVerilog/mil-std-1553b-soc' &
git clone https://github.com/pulp-platform/clic '/storage/nvme5/new_clones/SystemVerilog/clic' &
git clone https://github.com/brianhill11/FPGA-CNN '/storage/nvme5/new_clones/SystemVerilog/FPGA-CNN' &
git clone https://github.com/pulp-platform/axi_node '/storage/nvme5/new_clones/SystemVerilog/axi_node' &
git clone https://github.com/srg320/Saturn '/storage/nvme5/new_clones/SystemVerilog/Saturn' &
git clone https://github.com/seabeam/yuu_vip_gen '/storage/nvme5/new_clones/SystemVerilog/yuu_vip_gen' &
git clone https://github.com/ciniml/tn_serv '/storage/nvme5/new_clones/SystemVerilog/tn_serv' &
git clone https://github.com/pulp-platform/fpu_div_sqrt_mvp '/storage/nvme5/new_clones/SystemVerilog/fpu_div_sqrt_mvp' &
git clone https://github.com/zhouchuanrui/Cryptography-in-Systemverilog '/storage/nvme5/new_clones/SystemVerilog/Cryptography-in-Systemverilog' &
git clone https://github.com/ljhsiun2/EllipticCurves_SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/EllipticCurves_SystemVerilog' &
git clone https://github.com/CompuSAR/sar6502 '/storage/nvme5/new_clones/SystemVerilog/sar6502' &
git clone https://github.com/rgwan/AMBA '/storage/nvme5/new_clones/SystemVerilog/AMBA' &
git clone https://github.com/PacoReinaCampo/PU-RISCV '/storage/nvme5/new_clones/SystemVerilog/PU-RISCV' &
git clone https://github.com/smartfoxdata/uvm_apb '/storage/nvme5/new_clones/SystemVerilog/uvm_apb' &
git clone https://github.com/yuxuanZh/SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog' &
git clone https://github.com/gilgamsh/GenshinCPU '/storage/nvme5/new_clones/SystemVerilog/GenshinCPU' &
git clone https://github.com/pbridd/lzrw1-compression-core '/storage/nvme5/new_clones/SystemVerilog/lzrw1-compression-core' &
git clone https://github.com/amiq-consulting/physical_coding_library '/storage/nvme5/new_clones/SystemVerilog/physical_coding_library' &
git clone https://github.com/pulp-platform/axi2apb '/storage/nvme5/new_clones/SystemVerilog/axi2apb' &
git clone https://github.com/pulp-platform/hwpe-stream '/storage/nvme5/new_clones/SystemVerilog/hwpe-stream' &
git clone https://github.com/pulp-platform/trace_debugger '/storage/nvme5/new_clones/SystemVerilog/trace_debugger' &
git clone https://github.com/WeiChungWu/UVM_UART_Example '/storage/nvme5/new_clones/SystemVerilog/UVM_UART_Example' &
git clone https://github.com/martinKindall/mips_cpu '/storage/nvme5/new_clones/SystemVerilog/mips_cpu' &
git clone https://github.com/nosnhojn/uvm-utest '/storage/nvme5/new_clones/SystemVerilog/uvm-utest' &
git clone https://github.com/QmppmQ/riscv '/storage/nvme5/new_clones/SystemVerilog/riscv' &
git clone https://github.com/pulp-platform/sne '/storage/nvme5/new_clones/SystemVerilog/sne' &
git clone https://github.com/lowRISC/ariane-ethernet '/storage/nvme5/new_clones/SystemVerilog/ariane-ethernet' &
git clone https://github.com/msinger/iceboy '/storage/nvme5/new_clones/SystemVerilog/iceboy' &
git clone https://github.com/openhwgroup/core-v-mcu-uvm '/storage/nvme5/new_clones/SystemVerilog/core-v-mcu-uvm' &
git clone https://github.com/RoaLogic/adv_dbg_if '/storage/nvme5/new_clones/SystemVerilog/adv_dbg_if' &
git clone https://github.com/NamiLiy/Helios_scalable_QEC '/storage/nvme5/new_clones/SystemVerilog/Helios_scalable_QEC' &
git clone https://github.com/forever-gk/AHB-SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/AHB-SystemVerilog' &
git clone https://github.com/Mohamed-Younis/SPI-UVM-Testbench '/storage/nvme5/new_clones/SystemVerilog/SPI-UVM-Testbench' &
git clone https://github.com/NUDT-NF5/NF5 '/storage/nvme5/new_clones/SystemVerilog/NF5' &
git clone https://github.com/mxg/topaz '/storage/nvme5/new_clones/SystemVerilog/topaz' &
git clone https://github.com/PacoReinaCampo/verilog2vhdl '/storage/nvme5/new_clones/SystemVerilog/verilog2vhdl' &
git clone https://github.com/CircuitCoder/mill '/storage/nvme5/new_clones/SystemVerilog/mill' &
git clone https://github.com/hackdac/hackdac_2018_beta '/storage/nvme5/new_clones/SystemVerilog/hackdac_2018_beta' &
git clone https://github.com/muneebullashariff/spi_vip '/storage/nvme5/new_clones/SystemVerilog/spi_vip' &
git clone https://github.com/antmicro/verilator-verification-features-tests '/storage/nvme5/new_clones/SystemVerilog/verilator-verification-features-tests' &
git clone https://github.com/JoseIuri/axi4lite2uart '/storage/nvme5/new_clones/SystemVerilog/axi4lite2uart' &
git clone https://github.com/deekshithkrishnegowda/AHB2APB-bridge-IP-core-verification '/storage/nvme5/new_clones/SystemVerilog/AHB2APB-bridge-IP-core-verification' &
git clone https://github.com/intel/multi_power_sequencer '/storage/nvme5/new_clones/SystemVerilog/multi_power_sequencer' &
git clone https://github.com/dpretet/svlogger '/storage/nvme5/new_clones/SystemVerilog/svlogger' &
git clone https://github.com/dpretet/bster '/storage/nvme5/new_clones/SystemVerilog/bster' &
git clone https://github.com/efeslab/hardware-bugbase '/storage/nvme5/new_clones/SystemVerilog/hardware-bugbase' &
git clone https://github.com/gundy/tinyfpga-bx-demos '/storage/nvme5/new_clones/SystemVerilog/tinyfpga-bx-demos' &
git clone https://github.com/muneebullashariff/uart_vip '/storage/nvme5/new_clones/SystemVerilog/uart_vip' &
git clone https://github.com/eisl-nctu/falco '/storage/nvme5/new_clones/SystemVerilog/falco' &
git clone https://github.com/SymbioticEDA/sva-demos '/storage/nvme5/new_clones/SystemVerilog/sva-demos' &
git clone https://github.com/opensocdebug/osd-hw '/storage/nvme5/new_clones/SystemVerilog/osd-hw' &
git clone https://github.com/OFS/ofs-platform-afu-bbb '/storage/nvme5/new_clones/SystemVerilog/ofs-platform-afu-bbb' &
git clone https://github.com/tom01h/zero-riscy '/storage/nvme5/new_clones/SystemVerilog/zero-riscy' &
git clone https://github.com/RoaLogic/ahb3lite_pkg '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_pkg' &
git clone https://github.com/Anjali-287/Synchronous-FIFO-UVM-TB '/storage/nvme5/new_clones/SystemVerilog/Synchronous-FIFO-UVM-TB' &
git clone https://github.com/PacoReinaCampo/vhdl2verilog '/storage/nvme5/new_clones/SystemVerilog/vhdl2verilog' &
git clone https://github.com/arcade-lab/tia-infrastructure '/storage/nvme5/new_clones/SystemVerilog/tia-infrastructure' &
git clone https://github.com/ved-rivos/iommu-rtl '/storage/nvme5/new_clones/SystemVerilog/iommu-rtl' &
git clone https://github.com/Cognoscan/AxiCores '/storage/nvme5/new_clones/SystemVerilog/AxiCores' &
git clone https://github.com/GabbedT/ApogeoRV '/storage/nvme5/new_clones/SystemVerilog/ApogeoRV' &
git clone https://github.com/kumarrishav14/AMBA_APB '/storage/nvme5/new_clones/SystemVerilog/AMBA_APB' &
git clone https://github.com/smartfoxdata/uvm_axi4lite '/storage/nvme5/new_clones/SystemVerilog/uvm_axi4lite' &
git clone https://github.com/krz-max/Digital-Circuits-and-Systems '/storage/nvme5/new_clones/SystemVerilog/Digital-Circuits-and-Systems' &
git clone https://github.com/BaylorComputerEngineering/ARM-Lab '/storage/nvme5/new_clones/SystemVerilog/ARM-Lab' &
git clone https://github.com/Angela-WangBo/Shenjing-RTL '/storage/nvme5/new_clones/SystemVerilog/Shenjing-RTL' &
git clone https://github.com/amiq-consulting/uvm_reg_to_ipxact '/storage/nvme5/new_clones/SystemVerilog/uvm_reg_to_ipxact' &
git clone https://github.com/svunit/svmock '/storage/nvme5/new_clones/SystemVerilog/svmock' &
git clone https://github.com/muguang123/AXI_Verification '/storage/nvme5/new_clones/SystemVerilog/AXI_Verification' &
git clone https://github.com/JoseIuri/UVM_Python_UVMC '/storage/nvme5/new_clones/SystemVerilog/UVM_Python_UVMC' &
git clone https://github.com/HITSZ-NSCSCC22/mycpu '/storage/nvme5/new_clones/SystemVerilog/mycpu' &
git clone https://github.com/pulp-platform/rbe '/storage/nvme5/new_clones/SystemVerilog/rbe' &
git clone https://github.com/alisemi/fpga-projects '/storage/nvme5/new_clones/SystemVerilog/fpga-projects' &
git clone https://github.com/apriya-ram/AXI_FIFO_BFM '/storage/nvme5/new_clones/SystemVerilog/AXI_FIFO_BFM' &
git clone https://github.com/nikulshr/resnet_fpga '/storage/nvme5/new_clones/SystemVerilog/resnet_fpga' &
git clone https://github.com/joegrand/bsodomizer-hd-c5g '/storage/nvme5/new_clones/SystemVerilog/bsodomizer-hd-c5g' &
git clone https://github.com/zhajio1988/uvm_candy_lover '/storage/nvme5/new_clones/SystemVerilog/uvm_candy_lover' &
git clone https://github.com/smartfoxdata/uvm_axi '/storage/nvme5/new_clones/SystemVerilog/uvm_axi' &
git clone https://github.com/iammituraj/skid_buffer '/storage/nvme5/new_clones/SystemVerilog/skid_buffer' &
git clone https://github.com/shady831213/jarvisuk '/storage/nvme5/new_clones/SystemVerilog/jarvisuk' &
git clone https://github.com/Laxer3a/PS-GPU '/storage/nvme5/new_clones/SystemVerilog/PS-GPU' &
git clone https://github.com/yoonisi/R2FFT '/storage/nvme5/new_clones/SystemVerilog/R2FFT' &
git clone https://github.com/nockieboy/gpu '/storage/nvme5/new_clones/SystemVerilog/gpu' &
git clone https://github.com/iammituraj/FIFOs '/storage/nvme5/new_clones/SystemVerilog/FIFOs' &
git clone https://github.com/asadalam/FINN_MatrixVector_RTL '/storage/nvme5/new_clones/SystemVerilog/FINN_MatrixVector_RTL' &
git clone https://github.com/tinylabs/tinylabs-cores '/storage/nvme5/new_clones/SystemVerilog/tinylabs-cores' &
git clone https://github.com/mahmutefil/AXI2APB-Bridge-Design-and-Verification '/storage/nvme5/new_clones/SystemVerilog/AXI2APB-Bridge-Design-and-Verification' &
git clone https://github.com/kinap/AES-Processor '/storage/nvme5/new_clones/SystemVerilog/AES-Processor' &
git clone https://github.com/mbits-mirafra/i3c_avip '/storage/nvme5/new_clones/SystemVerilog/i3c_avip' &
git clone https://github.com/aignacio/ahb_lite_bus '/storage/nvme5/new_clones/SystemVerilog/ahb_lite_bus' &
git clone https://github.com/charkster/usb_pd_monitor '/storage/nvme5/new_clones/SystemVerilog/usb_pd_monitor' &
git clone https://github.com/mbits-mirafra/apb_avip '/storage/nvme5/new_clones/SystemVerilog/apb_avip' &
git clone https://github.com/muneeb-mbytes/UVMF '/storage/nvme5/new_clones/SystemVerilog/UVMF' &
git clone https://github.com/srg320/SH '/storage/nvme5/new_clones/SystemVerilog/SH' &
git clone https://github.com/jsloan256/dpll '/storage/nvme5/new_clones/SystemVerilog/dpll' &
git clone https://github.com/euphoric-hardware/simcommand '/storage/nvme5/new_clones/SystemVerilog/simcommand' &
git clone https://github.com/azonenberg/sata-sniffer '/storage/nvme5/new_clones/SystemVerilog/sata-sniffer' &
git clone https://github.com/holdenQWER/systemverilog_design_pattern '/storage/nvme5/new_clones/SystemVerilog/systemverilog_design_pattern' &
git clone https://github.com/nikitabuzov/SpikingNeuralNet '/storage/nvme5/new_clones/SystemVerilog/SpikingNeuralNet' &
git clone https://github.com/ZSusskind/BTHOWeN '/storage/nvme5/new_clones/SystemVerilog/BTHOWeN' &
git clone https://github.com/theapi/nand2tetris_fpga '/storage/nvme5/new_clones/SystemVerilog/nand2tetris_fpga' &
git clone https://github.com/Vivek-Dave/UVM_TestBench_For_Single_Port_RAM '/storage/nvme5/new_clones/SystemVerilog/UVM_TestBench_For_Single_Port_RAM' &
git clone https://github.com/chad-q/andes-vector-riscv-dv '/storage/nvme5/new_clones/SystemVerilog/andes-vector-riscv-dv' &
git clone https://github.com/Xilinx/vck190-base-trd '/storage/nvme5/new_clones/SystemVerilog/vck190-base-trd' &
git clone https://github.com/nelsoncsc/FFT '/storage/nvme5/new_clones/SystemVerilog/FFT' &
git clone https://github.com/FPGA-MAFIA/fpga_mafia '/storage/nvme5/new_clones/SystemVerilog/fpga_mafia' &
git clone https://github.com/oshears/SNN-FPGA-Implementation '/storage/nvme5/new_clones/SystemVerilog/SNN-FPGA-Implementation' &
git clone https://github.com/avashist003/FIFO_SystemVerilog_Assertion '/storage/nvme5/new_clones/SystemVerilog/FIFO_SystemVerilog_Assertion' &
git clone https://github.com/muneebullashariff/pulpino_soc_uvm_testbench '/storage/nvme5/new_clones/SystemVerilog/pulpino_soc_uvm_testbench' &
git clone https://github.com/asveske/apb_vip '/storage/nvme5/new_clones/SystemVerilog/apb_vip' &
git clone https://github.com/muneeb-mbytes/i2c_avip '/storage/nvme5/new_clones/SystemVerilog/i2c_avip' &
git clone https://github.com/hotwolf/WbXbc '/storage/nvme5/new_clones/SystemVerilog/WbXbc' &
git clone https://github.com/alice820621/A-UVM-verification-for-DAC-and-ADC-model-with-APB-BFM '/storage/nvme5/new_clones/SystemVerilog/A-UVM-verification-for-DAC-and-ADC-model-with-APB-BFM' &
git clone https://github.com/chenyangbing/UVM-example '/storage/nvme5/new_clones/SystemVerilog/UVM-example' &
git clone https://github.com/RoaLogic/apb4_mux '/storage/nvme5/new_clones/SystemVerilog/apb4_mux' &
git clone https://github.com/wallento/wb2axi '/storage/nvme5/new_clones/SystemVerilog/wb2axi' &
git clone https://github.com/tudortimi/reflection '/storage/nvme5/new_clones/SystemVerilog/reflection' &
git clone https://github.com/ChienKaiMa/HDR-Imaging-with-FPGA '/storage/nvme5/new_clones/SystemVerilog/HDR-Imaging-with-FPGA' &
git clone https://github.com/pulp-platform/ne16 '/storage/nvme5/new_clones/SystemVerilog/ne16' &
git clone https://github.com/zwhexplorer/Spiking-Neural-Network-Accelerator-EE552-project '/storage/nvme5/new_clones/SystemVerilog/Spiking-Neural-Network-Accelerator-EE552-project' &
git clone https://github.com/bwitherspoon/rv32cpu '/storage/nvme5/new_clones/SystemVerilog/rv32cpu' &
git clone https://github.com/zhajio1988/YasaUvk '/storage/nvme5/new_clones/SystemVerilog/YasaUvk' &
git clone https://github.com/kkudrolli/USB-Host '/storage/nvme5/new_clones/SystemVerilog/USB-Host' &
git clone https://github.com/luunguyen97/DPU-TRD-ZCU104 '/storage/nvme5/new_clones/SystemVerilog/DPU-TRD-ZCU104' &
git clone https://github.com/pulp-platform/apb '/storage/nvme5/new_clones/SystemVerilog/apb' &
git clone https://github.com/rajdeep87/verilog-c '/storage/nvme5/new_clones/SystemVerilog/verilog-c' &
git clone https://github.com/radiolok/dekatronpc '/storage/nvme5/new_clones/SystemVerilog/dekatronpc' &
git clone https://github.com/kitune-san/KFPC-XT '/storage/nvme5/new_clones/SystemVerilog/KFPC-XT' &
git clone https://github.com/yoshi-ki/RISC-V-core '/storage/nvme5/new_clones/SystemVerilog/RISC-V-core' &
git clone https://github.com/muhammedkocaoglu/SystemVerilog-Tutorials '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog-Tutorials' &
git clone https://github.com/tudortimi/vpi '/storage/nvme5/new_clones/SystemVerilog/vpi' &
git clone https://github.com/Weierstras-s/RISCV-CPU '/storage/nvme5/new_clones/SystemVerilog/RISCV-CPU' &
git clone https://github.com/Rain92/FPGA-Mandelbrot '/storage/nvme5/new_clones/SystemVerilog/FPGA-Mandelbrot' &
git clone https://github.com/I-Doctor/gnn-acceleration-framework-with-FPGA '/storage/nvme5/new_clones/SystemVerilog/gnn-acceleration-framework-with-FPGA' &
git clone https://github.com/nietzhuang/RISC-V-SoC-Design '/storage/nvme5/new_clones/SystemVerilog/RISC-V-SoC-Design' &
git clone https://github.com/taichi-ishitani/tvip-common '/storage/nvme5/new_clones/SystemVerilog/tvip-common' &
git clone https://github.com/Hong-Ming/FPGA-Oscilloscope '/storage/nvme5/new_clones/SystemVerilog/FPGA-Oscilloscope' &
git clone https://github.com/briandong/regModel '/storage/nvme5/new_clones/SystemVerilog/regModel' &
git clone https://github.com/nmikstas/fpga-filter-implementation '/storage/nvme5/new_clones/SystemVerilog/fpga-filter-implementation' &
git clone https://github.com/PacoReinaCampo/MPSoC-DMA '/storage/nvme5/new_clones/SystemVerilog/MPSoC-DMA' &
git clone https://github.com/flasonil/Serial-Multiplier '/storage/nvme5/new_clones/SystemVerilog/Serial-Multiplier' &
git clone https://github.com/HunterBitos/Implementation-of-AMBA-AXI3-protocol '/storage/nvme5/new_clones/SystemVerilog/Implementation-of-AMBA-AXI3-protocol' &
git clone https://github.com/aiju/fpga-blit '/storage/nvme5/new_clones/SystemVerilog/fpga-blit' &
git clone https://github.com/sifferman/fpga_screensaver '/storage/nvme5/new_clones/SystemVerilog/fpga_screensaver' &
git clone https://github.com/pulp-platform/hci '/storage/nvme5/new_clones/SystemVerilog/hci' &
git clone https://github.com/eanchlia/NN_Network_On_Chip '/storage/nvme5/new_clones/SystemVerilog/NN_Network_On_Chip' &
git clone https://github.com/Nikola2444/RISC-V-vector-processor '/storage/nvme5/new_clones/SystemVerilog/RISC-V-vector-processor' &
git clone https://github.com/JoseIuri/Simple_UVM '/storage/nvme5/new_clones/SystemVerilog/Simple_UVM' &
git clone https://github.com/cmcmicrosystems/pulpissimo-zcu102 '/storage/nvme5/new_clones/SystemVerilog/pulpissimo-zcu102' &
git clone https://github.com/fcayci/sv-digital-design '/storage/nvme5/new_clones/SystemVerilog/sv-digital-design' &
git clone https://github.com/Lombiq/Hastlayer-Hardware-Framework---Catapult '/storage/nvme5/new_clones/SystemVerilog/Hastlayer-Hardware-Framework---Catapult' &
git clone https://github.com/kiwih/pic16f-antastic '/storage/nvme5/new_clones/SystemVerilog/pic16f-antastic' &
git clone https://github.com/stephanosio/BPSKModem '/storage/nvme5/new_clones/SystemVerilog/BPSKModem' &
git clone https://github.com/vinodsake/Last-Level-Cache-Simulator '/storage/nvme5/new_clones/SystemVerilog/Last-Level-Cache-Simulator' &
git clone https://github.com/rggen/rggen-sv-rtl '/storage/nvme5/new_clones/SystemVerilog/rggen-sv-rtl' &
git clone https://github.com/makararasi/UVM_AXI4-Stream '/storage/nvme5/new_clones/SystemVerilog/UVM_AXI4-Stream' &
git clone https://github.com/GuiZhaoCodeSource/Func_Verif_MMU_Code_Source '/storage/nvme5/new_clones/SystemVerilog/Func_Verif_MMU_Code_Source' &
git clone https://github.com/j1s1e1/VerilogPolarCodes '/storage/nvme5/new_clones/SystemVerilog/VerilogPolarCodes' &
git clone https://github.com/gokulbalagopal/Verification-of-APB-Protocol-using-UVM '/storage/nvme5/new_clones/SystemVerilog/Verification-of-APB-Protocol-using-UVM' &
git clone https://github.com/0ctobyte/procyon '/storage/nvme5/new_clones/SystemVerilog/procyon' &
git clone https://github.com/amiq-consulting/cagt '/storage/nvme5/new_clones/SystemVerilog/cagt' &
git clone https://github.com/PacoReinaCampo/MPSoC-NTM '/storage/nvme5/new_clones/SystemVerilog/MPSoC-NTM' &
git clone https://github.com/kumarswamy12/ROUTER-1-3 '/storage/nvme5/new_clones/SystemVerilog/ROUTER-1-3' &
git clone https://github.com/Verdvana/Async_FIFO '/storage/nvme5/new_clones/SystemVerilog/Async_FIFO' &
git clone https://github.com/esnet/esnet-fpga-library '/storage/nvme5/new_clones/SystemVerilog/esnet-fpga-library' &
git clone https://github.com/pulp-platform/adv_dbg_if '/storage/nvme5/new_clones/SystemVerilog/adv_dbg_if' &
git clone https://github.com/pulp-platform/cluster_interconnect '/storage/nvme5/new_clones/SystemVerilog/cluster_interconnect' &
git clone https://github.com/ElectronAsh/sim_3do '/storage/nvme5/new_clones/SystemVerilog/sim_3do' &
git clone https://github.com/enkerewpo/methane '/storage/nvme5/new_clones/SystemVerilog/methane' &
git clone https://github.com/semify-eda/waveform-generator '/storage/nvme5/new_clones/SystemVerilog/waveform-generator' &
git clone https://github.com/Harshil1995/I2C_UVM_APB '/storage/nvme5/new_clones/SystemVerilog/I2C_UVM_APB' &
git clone https://github.com/RoaLogic/apb4_gpio '/storage/nvme5/new_clones/SystemVerilog/apb4_gpio' &
git clone https://github.com/GustavoDinizMonteiro/loac-tirinhas '/storage/nvme5/new_clones/SystemVerilog/loac-tirinhas' &
git clone https://github.com/RoaLogic/ahb3lite_timer '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_timer' &
git clone https://github.com/pulp-platform/apb_timer '/storage/nvme5/new_clones/SystemVerilog/apb_timer' &
git clone https://github.com/Jefferson-Lopes/Correlator '/storage/nvme5/new_clones/SystemVerilog/Correlator' &
git clone https://github.com/Ashwin-Rajesh/RiSC-16 '/storage/nvme5/new_clones/SystemVerilog/RiSC-16' &
git clone https://github.com/rakeshgehalot/Ethernet_switch_verification '/storage/nvme5/new_clones/SystemVerilog/Ethernet_switch_verification' &
git clone https://github.com/cyyself/CDIM-SoC '/storage/nvme5/new_clones/SystemVerilog/CDIM-SoC' &
git clone https://github.com/wshenyi/EECS-470-FinalProject '/storage/nvme5/new_clones/SystemVerilog/EECS-470-FinalProject' &
git clone https://github.com/liuch00/fpga_cnn '/storage/nvme5/new_clones/SystemVerilog/fpga_cnn' &
git clone https://github.com/amane-uehara/cpubook-code '/storage/nvme5/new_clones/SystemVerilog/cpubook-code' &
git clone https://github.com/PacoReinaCampo/MPSoC-RISCV '/storage/nvme5/new_clones/SystemVerilog/MPSoC-RISCV' &
git clone https://github.com/hyf6661669/verilog_library '/storage/nvme5/new_clones/SystemVerilog/verilog_library' &
git clone https://github.com/jeras/rp32 '/storage/nvme5/new_clones/SystemVerilog/rp32' &
git clone https://github.com/Psichico/Universal_Verification_Methodology '/storage/nvme5/new_clones/SystemVerilog/Universal_Verification_Methodology' &
git clone https://github.com/diadatp/nasti-ddrx-mc '/storage/nvme5/new_clones/SystemVerilog/nasti-ddrx-mc' &
git clone https://github.com/pulp-platform/apb_uart_sv '/storage/nvme5/new_clones/SystemVerilog/apb_uart_sv' &
git clone https://github.com/bwitherspoon/wiphy '/storage/nvme5/new_clones/SystemVerilog/wiphy' &
git clone https://github.com/ucsbieee/mapache64 '/storage/nvme5/new_clones/SystemVerilog/mapache64' &
git clone https://github.com/AlessandroCilardo/NaplesPU '/storage/nvme5/new_clones/SystemVerilog/NaplesPU' &
git clone https://github.com/leeds-embedded-systems/ELEC5566M-Resources '/storage/nvme5/new_clones/SystemVerilog/ELEC5566M-Resources' &
git clone https://github.com/rdou/UVM-Verification-Testbench-For-FIFO '/storage/nvme5/new_clones/SystemVerilog/UVM-Verification-Testbench-For-FIFO' &
git clone https://github.com/Srisrijakka1/UART-Design-simulation-using-verilog '/storage/nvme5/new_clones/SystemVerilog/UART-Design-simulation-using-verilog' &
git clone https://github.com/jchengX/MAC_BFM '/storage/nvme5/new_clones/SystemVerilog/MAC_BFM' &
git clone https://github.com/IObundle/iob-interconnect '/storage/nvme5/new_clones/SystemVerilog/iob-interconnect' &
git clone https://github.com/dpretet/meduram '/storage/nvme5/new_clones/SystemVerilog/meduram' &
git clone https://github.com/gjlies/configgpgpu '/storage/nvme5/new_clones/SystemVerilog/configgpgpu' &
git clone https://github.com/pulp-platform/hier-icache '/storage/nvme5/new_clones/SystemVerilog/hier-icache' &
git clone https://github.com/evanmays/cherrycore '/storage/nvme5/new_clones/SystemVerilog/cherrycore' &
git clone https://github.com/ecilasun/e32e '/storage/nvme5/new_clones/SystemVerilog/e32e' &
git clone https://github.com/freecores/i2c_master_slave_core '/storage/nvme5/new_clones/SystemVerilog/i2c_master_slave_core' &
git clone https://github.com/XinlueLiu/UVM '/storage/nvme5/new_clones/SystemVerilog/UVM' &
git clone https://github.com/zstechly/systemverilog '/storage/nvme5/new_clones/SystemVerilog/systemverilog' &
git clone https://github.com/kennych418/FPGA_AudioVisualizer '/storage/nvme5/new_clones/SystemVerilog/FPGA_AudioVisualizer' &
git clone https://github.com/ishfaqahmed29/FIFO_UVM_Verification '/storage/nvme5/new_clones/SystemVerilog/FIFO_UVM_Verification' &
git clone https://github.com/mediaic/VLSI_Lab2 '/storage/nvme5/new_clones/SystemVerilog/VLSI_Lab2' &
git clone https://github.com/jnestor/SV_Examples '/storage/nvme5/new_clones/SystemVerilog/SV_Examples' &
git clone https://github.com/tishi43/sgbm '/storage/nvme5/new_clones/SystemVerilog/sgbm' &
git clone https://github.com/RoaLogic/memory '/storage/nvme5/new_clones/SystemVerilog/memory' &
git clone https://github.com/va7deo/TerraCresta '/storage/nvme5/new_clones/SystemVerilog/TerraCresta' &
git clone https://github.com/Freecellera/freecellera-uvm '/storage/nvme5/new_clones/SystemVerilog/freecellera-uvm' &
git clone https://github.com/smartfoxdata/uvm_starter '/storage/nvme5/new_clones/SystemVerilog/uvm_starter' &
git clone https://github.com/aaronshappell/tage-predictor '/storage/nvme5/new_clones/SystemVerilog/tage-predictor' &
git clone https://github.com/semify-eda/go.debug '/storage/nvme5/new_clones/SystemVerilog/go.debug' &
git clone https://github.com/vfinotti/ahb3lite_dma '/storage/nvme5/new_clones/SystemVerilog/ahb3lite_dma' &
git clone https://github.com/AbhishekTaur/System-Verilog-Practice '/storage/nvme5/new_clones/SystemVerilog/System-Verilog-Practice' &
git clone https://github.com/seabeam/yuu_clock '/storage/nvme5/new_clones/SystemVerilog/yuu_clock' &
git clone https://github.com/amichai-bd/rvc_asap '/storage/nvme5/new_clones/SystemVerilog/rvc_asap' &
git clone https://github.com/rubinsteina13/SV_I2S_RX_CORE '/storage/nvme5/new_clones/SystemVerilog/SV_I2S_RX_CORE' &
git clone https://github.com/hellgate202/axi4_lib '/storage/nvme5/new_clones/SystemVerilog/axi4_lib' &
git clone https://github.com/pulp-platform/apb_spi_master '/storage/nvme5/new_clones/SystemVerilog/apb_spi_master' &
git clone https://github.com/jmcneal/config_policy_pattern '/storage/nvme5/new_clones/SystemVerilog/config_policy_pattern' &
git clone https://github.com/jkopanski/802.15.4 '/storage/nvme5/new_clones/SystemVerilog/802.15.4' &
git clone https://github.com/pulp-platform/redundancy_cells '/storage/nvme5/new_clones/SystemVerilog/redundancy_cells' &
git clone https://github.com/MinecraftMachina/FabricHDL '/storage/nvme5/new_clones/SystemVerilog/FabricHDL' &
git clone https://github.com/techav-homebrew/SE-VGA '/storage/nvme5/new_clones/SystemVerilog/SE-VGA' &
git clone https://github.com/semahawk/wishbone '/storage/nvme5/new_clones/SystemVerilog/wishbone' &
git clone https://github.com/chipsalliance/verible-formatter-action '/storage/nvme5/new_clones/SystemVerilog/verible-formatter-action' &
git clone https://github.com/Matt8898/leg '/storage/nvme5/new_clones/SystemVerilog/leg' &
git clone https://github.com/UMJI-VE450-21SU/Ria '/storage/nvme5/new_clones/SystemVerilog/Ria' &
git clone https://github.com/kang-0909/mips-cpu '/storage/nvme5/new_clones/SystemVerilog/mips-cpu' &
git clone https://github.com/hdl-util/image-processing '/storage/nvme5/new_clones/SystemVerilog/image-processing' &
git clone https://github.com/kumarrishav14/SRAM_UVM '/storage/nvme5/new_clones/SystemVerilog/SRAM_UVM' &
git clone https://github.com/zhiyb/SVNES '/storage/nvme5/new_clones/SystemVerilog/SVNES' &
git clone https://github.com/pulp-platform/gpio '/storage/nvme5/new_clones/SystemVerilog/gpio' &
git clone https://github.com/supranational/vdf-fpga-round1-results '/storage/nvme5/new_clones/SystemVerilog/vdf-fpga-round1-results' &
git clone https://github.com/AleksandarKostovic/Matrix-MAC-Unit '/storage/nvme5/new_clones/SystemVerilog/Matrix-MAC-Unit' &
git clone https://github.com/GeorgeSangillo/ARM-Single-Cycle-Processor '/storage/nvme5/new_clones/SystemVerilog/ARM-Single-Cycle-Processor' &
git clone https://github.com/j1s1e1/VerilogTurboCodeMaxProduct '/storage/nvme5/new_clones/SystemVerilog/VerilogTurboCodeMaxProduct' &
git clone https://github.com/rdou/UVM-Verification-Testbench-For-SimpleBus '/storage/nvme5/new_clones/SystemVerilog/UVM-Verification-Testbench-For-SimpleBus' &
git clone https://github.com/srishis/DMA8237A_VERIF '/storage/nvme5/new_clones/SystemVerilog/DMA8237A_VERIF' &
git clone https://github.com/adibis/uvmBasics '/storage/nvme5/new_clones/SystemVerilog/uvmBasics' &
git clone https://github.com/CPEN-391-TEAM-7/RNN_Accelerator '/storage/nvme5/new_clones/SystemVerilog/RNN_Accelerator' &
git clone https://github.com/SarahElzayat/RISC-pipelined-processor '/storage/nvme5/new_clones/SystemVerilog/RISC-pipelined-processor' &
git clone https://github.com/mbits-mirafra/pulpino__spi_master__subsystem_verification '/storage/nvme5/new_clones/SystemVerilog/pulpino__spi_master__subsystem_verification' &
git clone https://github.com/taneroksuz/cpu-medium '/storage/nvme5/new_clones/SystemVerilog/cpu-medium' &
git clone https://github.com/PulseRain/FP51_fast_core '/storage/nvme5/new_clones/SystemVerilog/FP51_fast_core' &
git clone https://github.com/nelsoncsc/basic_uvmc_oct '/storage/nvme5/new_clones/SystemVerilog/basic_uvmc_oct' &
git clone https://github.com/andreili/FlexRV32 '/storage/nvme5/new_clones/SystemVerilog/FlexRV32' &
git clone https://github.com/mbits-mirafra/spi_avip '/storage/nvme5/new_clones/SystemVerilog/spi_avip' &
git clone https://github.com/jmoles/keccak-verilog '/storage/nvme5/new_clones/SystemVerilog/keccak-verilog' &
git clone https://github.com/Rain92/vga_interface '/storage/nvme5/new_clones/SystemVerilog/vga_interface' &
git clone https://github.com/chandanpalai/SystemVerilog-Assertions '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog-Assertions' &
git clone https://github.com/Ludini1/minimal-risc-v-cpu '/storage/nvme5/new_clones/SystemVerilog/minimal-risc-v-cpu' &
git clone https://github.com/waviousllc/wav-d2d-hw '/storage/nvme5/new_clones/SystemVerilog/wav-d2d-hw' &
git clone https://github.com/mtabini/G76-Mini '/storage/nvme5/new_clones/SystemVerilog/G76-Mini' &
git clone https://github.com/USCPOSH/NUSADC '/storage/nvme5/new_clones/SystemVerilog/NUSADC' &
git clone https://github.com/go2uvm/sva_traces '/storage/nvme5/new_clones/SystemVerilog/sva_traces' &
git clone https://github.com/Infineon/adsbenchmark '/storage/nvme5/new_clones/SystemVerilog/adsbenchmark' &
git clone https://github.com/pulp-platform/hwpe-mac-engine '/storage/nvme5/new_clones/SystemVerilog/hwpe-mac-engine' &
git clone https://github.com/pulp-platform/fpu_ss '/storage/nvme5/new_clones/SystemVerilog/fpu_ss' &
git clone https://github.com/ijor/stBlitter '/storage/nvme5/new_clones/SystemVerilog/stBlitter' &
git clone https://github.com/Nimausfi/UVM_RAL_DMA '/storage/nvme5/new_clones/SystemVerilog/UVM_RAL_DMA' &
git clone https://github.com/drom/stack '/storage/nvme5/new_clones/SystemVerilog/stack' &
git clone https://github.com/joshtyler/manila-ice '/storage/nvme5/new_clones/SystemVerilog/manila-ice' &
git clone https://github.com/mehaltalukder/UART_UVM_Project '/storage/nvme5/new_clones/SystemVerilog/UART_UVM_Project' &
git clone https://github.com/RoaLogic/universal_jtag_tap '/storage/nvme5/new_clones/SystemVerilog/universal_jtag_tap' &
git clone https://github.com/monkey2000/rv5stage '/storage/nvme5/new_clones/SystemVerilog/rv5stage' &
git clone https://github.com/smartfoxdata/axi4lite_gpio '/storage/nvme5/new_clones/SystemVerilog/axi4lite_gpio' &
git clone https://github.com/kumarrishav14/arm_watchdog '/storage/nvme5/new_clones/SystemVerilog/arm_watchdog' &
git clone https://github.com/mballance/amba_sys_ip '/storage/nvme5/new_clones/SystemVerilog/amba_sys_ip' &
git clone https://github.com/omphardcloud/hardcloud '/storage/nvme5/new_clones/SystemVerilog/hardcloud' &
git clone https://github.com/taichi-ishitani/tbcm '/storage/nvme5/new_clones/SystemVerilog/tbcm' &
git clone https://github.com/freecores/aes_decrypt_fpga '/storage/nvme5/new_clones/SystemVerilog/aes_decrypt_fpga' &
git clone https://github.com/SymbiFlow/axi-vip '/storage/nvme5/new_clones/SystemVerilog/axi-vip' &
git clone https://github.com/nimish15shah/DPU_DAG_Processing_Unit '/storage/nvme5/new_clones/SystemVerilog/DPU_DAG_Processing_Unit' &
git clone https://github.com/sigasi/sigasi_demos '/storage/nvme5/new_clones/SystemVerilog/sigasi_demos' &
git clone https://github.com/hashi0203/riscv-processor '/storage/nvme5/new_clones/SystemVerilog/riscv-processor' &
git clone https://github.com/milestone12/JSON.sv '/storage/nvme5/new_clones/SystemVerilog/JSON.sv' &
git clone https://github.com/adervay1/CIMulator '/storage/nvme5/new_clones/SystemVerilog/CIMulator' &
git clone https://github.com/reed-foster/pynq-audio '/storage/nvme5/new_clones/SystemVerilog/pynq-audio' &
git clone https://github.com/HDLForBeginners/HDLBits '/storage/nvme5/new_clones/SystemVerilog/HDLBits' &
git clone https://github.com/kbbuch/LC3-Verification '/storage/nvme5/new_clones/SystemVerilog/LC3-Verification' &
git clone https://github.com/iDoka/GNSS-verilog-signal-simulator '/storage/nvme5/new_clones/SystemVerilog/GNSS-verilog-signal-simulator' &
git clone https://github.com/adibis/alu_tb '/storage/nvme5/new_clones/SystemVerilog/alu_tb' &
git clone https://github.com/stong/risc-uproc '/storage/nvme5/new_clones/SystemVerilog/risc-uproc' &
git clone https://github.com/pietroglyph/pipelined-rv32i '/storage/nvme5/new_clones/SystemVerilog/pipelined-rv32i' &
git clone https://github.com/lowRISC/rv_plic '/storage/nvme5/new_clones/SystemVerilog/rv_plic' &
git clone https://github.com/dalance/svlint-action '/storage/nvme5/new_clones/SystemVerilog/svlint-action' &
git clone https://github.com/Menci/pipeline '/storage/nvme5/new_clones/SystemVerilog/pipeline' &
git clone https://github.com/zhouzaixin/Documents_for_ic '/storage/nvme5/new_clones/SystemVerilog/Documents_for_ic' &
git clone https://github.com/Mehdi0xC/MLP-FeedForward-RTL-Acceleration '/storage/nvme5/new_clones/SystemVerilog/MLP-FeedForward-RTL-Acceleration' &
git clone https://github.com/MineQihang/MIPS_CPU '/storage/nvme5/new_clones/SystemVerilog/MIPS_CPU' &
git clone https://github.com/JoseIuri/UVM_Python '/storage/nvme5/new_clones/SystemVerilog/UVM_Python' &
git clone https://github.com/pConst/vivado_design_space_explorer_template '/storage/nvme5/new_clones/SystemVerilog/vivado_design_space_explorer_template' &
git clone https://github.com/GregAC/ibex_super_system '/storage/nvme5/new_clones/SystemVerilog/ibex_super_system' &
git clone https://github.com/NazerkeT/MultilevelTLB '/storage/nvme5/new_clones/SystemVerilog/MultilevelTLB' &
git clone https://github.com/Shivanagender123/AHB_APB-Bridge '/storage/nvme5/new_clones/SystemVerilog/AHB_APB-Bridge' &
git clone https://github.com/TaoHeyi/ECE385-Tank-World-on-FPGA '/storage/nvme5/new_clones/SystemVerilog/ECE385-Tank-World-on-FPGA' &
git clone https://github.com/shivanishah269/vsdfpga '/storage/nvme5/new_clones/SystemVerilog/vsdfpga' &
git clone https://github.com/suisuisi/SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog' &
git clone https://github.com/KafCoppelia/uvm-mcdf_v2 '/storage/nvme5/new_clones/SystemVerilog/uvm-mcdf_v2' &
git clone https://github.com/pulp-platform/apb_i2c '/storage/nvme5/new_clones/SystemVerilog/apb_i2c' &
git clone https://github.com/chan-henry/apb_uvm '/storage/nvme5/new_clones/SystemVerilog/apb_uvm' &
git clone https://github.com/Hazem-ali/SystemVerilog-Codes '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog-Codes' &
git clone https://github.com/guanzetong/OoO_processor '/storage/nvme5/new_clones/SystemVerilog/OoO_processor' &
git clone https://github.com/antmicro/ahb-tl-bridge '/storage/nvme5/new_clones/SystemVerilog/ahb-tl-bridge' &
git clone https://github.com/nockieboy/YM2149_PSG_system '/storage/nvme5/new_clones/SystemVerilog/YM2149_PSG_system' &
git clone https://github.com/ZivFung/zedboard_cnn '/storage/nvme5/new_clones/SystemVerilog/zedboard_cnn' &
git clone https://github.com/pulp-platform/udma_core '/storage/nvme5/new_clones/SystemVerilog/udma_core' &
git clone https://github.com/pulp-platform/apb_gpio '/storage/nvme5/new_clones/SystemVerilog/apb_gpio' &
git clone https://github.com/merledu/azadi '/storage/nvme5/new_clones/SystemVerilog/azadi' &
git clone https://github.com/andmiele/uCodedRiscV '/storage/nvme5/new_clones/SystemVerilog/uCodedRiscV' &
git clone https://github.com/GkyHub/fpga_cnn_train '/storage/nvme5/new_clones/SystemVerilog/fpga_cnn_train' &
git clone https://github.com/cheimu/4Issue-7Stage-OutOfOrder-Superscalar-RISCV-CPU-ArianeBased '/storage/nvme5/new_clones/SystemVerilog/4Issue-7Stage-OutOfOrder-Superscalar-RISCV-CPU-ArianeBased' &
git clone https://github.com/Csuk0914/dnn-rtl '/storage/nvme5/new_clones/SystemVerilog/dnn-rtl' &
git clone https://github.com/PacoReinaCampo/UVM '/storage/nvme5/new_clones/SystemVerilog/UVM' &
git clone https://github.com/jiegec/fpnew-wrapper '/storage/nvme5/new_clones/SystemVerilog/fpnew-wrapper' &
git clone https://github.com/nguyenquanicd/FirstX2P '/storage/nvme5/new_clones/SystemVerilog/FirstX2P' &
git clone https://github.com/yeehui1988/QCM '/storage/nvme5/new_clones/SystemVerilog/QCM' &
git clone https://github.com/colinpate/fpga-vr-remap '/storage/nvme5/new_clones/SystemVerilog/fpga-vr-remap' &
git clone https://github.com/robfinch/Float '/storage/nvme5/new_clones/SystemVerilog/Float' &
git clone https://github.com/kitune-san/KF8259 '/storage/nvme5/new_clones/SystemVerilog/KF8259' &
git clone https://github.com/ghosh17/DualCoreProcessor '/storage/nvme5/new_clones/SystemVerilog/DualCoreProcessor' &
git clone https://github.com/nbdd0121/muntjac-soc '/storage/nvme5/new_clones/SystemVerilog/muntjac-soc' &
git clone https://github.com/PXVI/ip_amba_ahb_ms_rtl_v '/storage/nvme5/new_clones/SystemVerilog/ip_amba_ahb_ms_rtl_v' &
git clone https://github.com/seabeam/yuu_common '/storage/nvme5/new_clones/SystemVerilog/yuu_common' &
git clone https://github.com/kdurant/uvm_study '/storage/nvme5/new_clones/SystemVerilog/uvm_study' &
git clone https://github.com/m1a1x1/Bloom_pattern_search '/storage/nvme5/new_clones/SystemVerilog/Bloom_pattern_search' &
git clone https://github.com/pulp-platform/axi-io-pmp '/storage/nvme5/new_clones/SystemVerilog/axi-io-pmp' &
git clone https://github.com/BrianHGinc/SystemVerilog-HDMI-encoder-serializer-PLL-generator '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog-HDMI-encoder-serializer-PLL-generator' &
git clone https://github.com/pulp-platform/core2axi '/storage/nvme5/new_clones/SystemVerilog/core2axi' &
git clone https://github.com/Yucao42/AES_GCM '/storage/nvme5/new_clones/SystemVerilog/AES_GCM' &
git clone https://github.com/VimfulDang/APB-SPI-Controller-Verification '/storage/nvme5/new_clones/SystemVerilog/APB-SPI-Controller-Verification' &
git clone https://github.com/hdl-util/sound '/storage/nvme5/new_clones/SystemVerilog/sound' &
git clone https://github.com/rafafigueredoviana/RISCV_MCU_CYCLONEV '/storage/nvme5/new_clones/SystemVerilog/RISCV_MCU_CYCLONEV' &
git clone https://github.com/Maxpicca-Li/LaunchMIPS '/storage/nvme5/new_clones/SystemVerilog/LaunchMIPS' &
git clone https://github.com/EisernSchild/YM2149 '/storage/nvme5/new_clones/SystemVerilog/YM2149' &
git clone https://github.com/Mr-southerly/router_verification '/storage/nvme5/new_clones/SystemVerilog/router_verification' &
git clone https://github.com/bchangip/NibblerCPU '/storage/nvme5/new_clones/SystemVerilog/NibblerCPU' &
git clone https://github.com/flashbangout/apb_watchdog- '/storage/nvme5/new_clones/SystemVerilog/apb_watchdog-' &
git clone https://github.com/risc-v-cpu/ez-risc-v-cpu '/storage/nvme5/new_clones/SystemVerilog/ez-risc-v-cpu' &
git clone https://github.com/gvsrmk/Design-and-Verification-of-DDR3-SDRAM-memory-controller '/storage/nvme5/new_clones/SystemVerilog/Design-and-Verification-of-DDR3-SDRAM-memory-controller' &
git clone https://github.com/KULeuven-MICAS/PSMA-benchmark '/storage/nvme5/new_clones/SystemVerilog/PSMA-benchmark' &
git clone https://github.com/carljohnsen/vitis_rtl '/storage/nvme5/new_clones/SystemVerilog/vitis_rtl' &
git clone https://github.com/jeras/rp8 '/storage/nvme5/new_clones/SystemVerilog/rp8' &
git clone https://github.com/Space-Odie/GA '/storage/nvme5/new_clones/SystemVerilog/GA' &
git clone https://github.com/kariannekk/Portable-Stimulus '/storage/nvme5/new_clones/SystemVerilog/Portable-Stimulus' &
git clone https://github.com/amiq-consulting/amiq_reg_agt '/storage/nvme5/new_clones/SystemVerilog/amiq_reg_agt' &
git clone https://github.com/flasonil/APB_PWM '/storage/nvme5/new_clones/SystemVerilog/APB_PWM' &
git clone https://github.com/tamannarupani/SimpleAdder-UVM '/storage/nvme5/new_clones/SystemVerilog/SimpleAdder-UVM' &
git clone https://github.com/hdl-util/clock-domain-crossing '/storage/nvme5/new_clones/SystemVerilog/clock-domain-crossing' &
git clone https://github.com/swabianinstruments/TimeTagger-FPGALink-Reference '/storage/nvme5/new_clones/SystemVerilog/TimeTagger-FPGALink-Reference' &
git clone https://github.com/sriramvb/DDR4-Memory-Controller '/storage/nvme5/new_clones/SystemVerilog/DDR4-Memory-Controller' &
git clone https://github.com/PulseRain/PulseRain_RISCV_MCU '/storage/nvme5/new_clones/SystemVerilog/PulseRain_RISCV_MCU' &
git clone https://github.com/LTDS-Capo/ProcessORC '/storage/nvme5/new_clones/SystemVerilog/ProcessORC' &
git clone https://github.com/smirnovich/ofd '/storage/nvme5/new_clones/SystemVerilog/ofd' &
git clone https://github.com/pzressinno/asyn_fifo_uvm_verify '/storage/nvme5/new_clones/SystemVerilog/asyn_fifo_uvm_verify' &
git clone https://github.com/ChrisShakkour/RV32I-MAF-project '/storage/nvme5/new_clones/SystemVerilog/RV32I-MAF-project' &
git clone https://github.com/SalomeDevkule7/Neural-Network-Layer-Generator '/storage/nvme5/new_clones/SystemVerilog/Neural-Network-Layer-Generator' &
git clone https://github.com/apsarras/shared-buffer-hw '/storage/nvme5/new_clones/SystemVerilog/shared-buffer-hw' &
git clone https://github.com/deekshithkrishnegowda/Router1x3-Design-Verification '/storage/nvme5/new_clones/SystemVerilog/Router1x3-Design-Verification' &
git clone https://github.com/anthonyabeo/digital_circuits '/storage/nvme5/new_clones/SystemVerilog/digital_circuits' &
git clone https://github.com/ridvancelikcs/Songs '/storage/nvme5/new_clones/SystemVerilog/Songs' &
git clone https://github.com/Vivek-Dave/FIFO_UVM_Testbench_Reactive_Stimulus '/storage/nvme5/new_clones/SystemVerilog/FIFO_UVM_Testbench_Reactive_Stimulus' &
git clone https://github.com/PacoReinaCampo/SoC-FinTech '/storage/nvme5/new_clones/SystemVerilog/SoC-FinTech' &
git clone https://github.com/takah29/arm-cpu '/storage/nvme5/new_clones/SystemVerilog/arm-cpu' &
git clone https://github.com/advanced-uvm/hawkins '/storage/nvme5/new_clones/SystemVerilog/hawkins' &
git clone https://github.com/PedroHSCavalcante/uvm-phase-jumping '/storage/nvme5/new_clones/SystemVerilog/uvm-phase-jumping' &
git clone https://github.com/scp10086/FPGA_UNDERWAY_SALES_MACHINE '/storage/nvme5/new_clones/SystemVerilog/FPGA_UNDERWAY_SALES_MACHINE' &
git clone https://github.com/ecilasun/nekoyon '/storage/nvme5/new_clones/SystemVerilog/nekoyon' &
git clone https://github.com/elegz/nnFPGA '/storage/nvme5/new_clones/SystemVerilog/nnFPGA' &
git clone https://github.com/zli87/SystemVerilog_Coursework '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog_Coursework' &
git clone https://github.com/grant4001/CORDIC-UART-Artix-7 '/storage/nvme5/new_clones/SystemVerilog/CORDIC-UART-Artix-7' &
git clone https://github.com/skudlur/cayde '/storage/nvme5/new_clones/SystemVerilog/cayde' &
git clone https://github.com/atmughrabi/AccelGraph '/storage/nvme5/new_clones/SystemVerilog/AccelGraph' &
git clone https://github.com/hdlguy/iir_filter '/storage/nvme5/new_clones/SystemVerilog/iir_filter' &
git clone https://github.com/kitune-san/KFPS2KB '/storage/nvme5/new_clones/SystemVerilog/KFPS2KB' &
git clone https://github.com/Panda-Cores/PandaZero '/storage/nvme5/new_clones/SystemVerilog/PandaZero' &
git clone https://github.com/openhwgroup/advanced-riscv-verification-methodologies '/storage/nvme5/new_clones/SystemVerilog/advanced-riscv-verification-methodologies' &
git clone https://github.com/amiq-consulting/amiq_fifo '/storage/nvme5/new_clones/SystemVerilog/amiq_fifo' &
git clone https://github.com/alexzhang007/wishbone_uvc '/storage/nvme5/new_clones/SystemVerilog/wishbone_uvc' &
git clone https://github.com/chenyangbing/Memory '/storage/nvme5/new_clones/SystemVerilog/Memory' &
git clone https://github.com/nelsoncsc/sv_math '/storage/nvme5/new_clones/SystemVerilog/sv_math' &
git clone https://github.com/PhigentRobotics/Phigent_Heimdallr '/storage/nvme5/new_clones/SystemVerilog/Phigent_Heimdallr' &
git clone https://github.com/takatz28/FIFO-BIST '/storage/nvme5/new_clones/SystemVerilog/FIFO-BIST' &
git clone https://github.com/robfinch/rfPhoenix '/storage/nvme5/new_clones/SystemVerilog/rfPhoenix' &
git clone https://github.com/aunics/AHB5 '/storage/nvme5/new_clones/SystemVerilog/AHB5' &
git clone https://github.com/sthornington/gemmm2s '/storage/nvme5/new_clones/SystemVerilog/gemmm2s' &
git clone https://github.com/lmco/tlrb_aib_phy '/storage/nvme5/new_clones/SystemVerilog/tlrb_aib_phy' &
git clone https://github.com/teekamkhandelwal/memory_verification_using_system_verilog '/storage/nvme5/new_clones/SystemVerilog/memory_verification_using_system_verilog' &
git clone https://github.com/seabeam/yuu_amba '/storage/nvme5/new_clones/SystemVerilog/yuu_amba' &
git clone https://github.com/guanrenyang/Tiny-TPU '/storage/nvme5/new_clones/SystemVerilog/Tiny-TPU' &
git clone https://github.com/victoresque/DCLab '/storage/nvme5/new_clones/SystemVerilog/DCLab' &
git clone https://github.com/mayurkubavat/UPF '/storage/nvme5/new_clones/SystemVerilog/UPF' &
git clone https://github.com/dywsjtu/2-Way-Superscalar-P6-Processor '/storage/nvme5/new_clones/SystemVerilog/2-Way-Superscalar-P6-Processor' &
git clone https://github.com/lmco/axi4_aib_bridge '/storage/nvme5/new_clones/SystemVerilog/axi4_aib_bridge' &
git clone https://github.com/IAIK/coco-ibex '/storage/nvme5/new_clones/SystemVerilog/coco-ibex' &
git clone https://github.com/kitsuneh/SVGameBoy '/storage/nvme5/new_clones/SystemVerilog/SVGameBoy' &
git clone https://github.com/saleh1204/riffa_arria10_stratix5 '/storage/nvme5/new_clones/SystemVerilog/riffa_arria10_stratix5' &
git clone https://github.com/kenzhang82/HDLBits '/storage/nvme5/new_clones/SystemVerilog/HDLBits' &
git clone https://github.com/tudortimi/verification-gentleman-blog-code '/storage/nvme5/new_clones/SystemVerilog/verification-gentleman-blog-code' &
git clone https://github.com/GuzTech/verilog_ips '/storage/nvme5/new_clones/SystemVerilog/verilog_ips' &
git clone https://github.com/sergev/zpu-avalanche '/storage/nvme5/new_clones/SystemVerilog/zpu-avalanche' &
git clone https://github.com/Elias-Rosales/MIPSVerification_UVM '/storage/nvme5/new_clones/SystemVerilog/MIPSVerification_UVM' &
git clone https://github.com/blargony/uvm_agent_gen '/storage/nvme5/new_clones/SystemVerilog/uvm_agent_gen' &
git clone https://github.com/openx86/w8086 '/storage/nvme5/new_clones/SystemVerilog/w8086' &
git clone https://github.com/ppujari24/SonyCellSPU '/storage/nvme5/new_clones/SystemVerilog/SonyCellSPU' &
git clone https://github.com/Minz9/SNN-on-FPGA '/storage/nvme5/new_clones/SystemVerilog/SNN-on-FPGA' &
git clone https://github.com/lizhirui/MyRISC-VCore-rtl '/storage/nvme5/new_clones/SystemVerilog/MyRISC-VCore-rtl' &
git clone https://github.com/pulp-platform/axi2per '/storage/nvme5/new_clones/SystemVerilog/axi2per' &
git clone https://github.com/shrutiprakashgupta/RISCV_Formal_Verification '/storage/nvme5/new_clones/SystemVerilog/RISCV_Formal_Verification' &
git clone https://github.com/mgoldio/tiny8v1 '/storage/nvme5/new_clones/SystemVerilog/tiny8v1' &
git clone https://github.com/Verdvana/Enc8b10b '/storage/nvme5/new_clones/SystemVerilog/Enc8b10b' &
git clone https://github.com/neofangnv/core-v-isg '/storage/nvme5/new_clones/SystemVerilog/core-v-isg' &
git clone https://github.com/fpgasystems/Coyote-CIRCT '/storage/nvme5/new_clones/SystemVerilog/Coyote-CIRCT' &
git clone https://github.com/efeslab/optimus-intel-fpga-bbb '/storage/nvme5/new_clones/SystemVerilog/optimus-intel-fpga-bbb' &
git clone https://github.com/kippy620/uvm '/storage/nvme5/new_clones/SystemVerilog/uvm' &
git clone https://github.com/angelus9/AI-Robotics '/storage/nvme5/new_clones/SystemVerilog/AI-Robotics' &
git clone https://github.com/yodalee/icesugar-playground '/storage/nvme5/new_clones/SystemVerilog/icesugar-playground' &
git clone https://github.com/cggewehr/RISCV-crypto '/storage/nvme5/new_clones/SystemVerilog/RISCV-crypto' &
git clone https://github.com/nbdd0121/OpenIP '/storage/nvme5/new_clones/SystemVerilog/OpenIP' &
git clone https://github.com/phwl/elec3608-lab '/storage/nvme5/new_clones/SystemVerilog/elec3608-lab' &
git clone https://github.com/miguelangelo78/LEGv8-ISA '/storage/nvme5/new_clones/SystemVerilog/LEGv8-ISA' &
git clone https://github.com/chiselverify/otherverify '/storage/nvme5/new_clones/SystemVerilog/otherverify' &
git clone https://github.com/antmicro/tl-ahb-bridge '/storage/nvme5/new_clones/SystemVerilog/tl-ahb-bridge' &
git clone https://github.com/BrianHGinc/BHG_I2C_init_RS232_debugger '/storage/nvme5/new_clones/SystemVerilog/BHG_I2C_init_RS232_debugger' &
git clone https://github.com/pulp-platform/axi_slice '/storage/nvme5/new_clones/SystemVerilog/axi_slice' &
git clone https://github.com/allanko/lasernet '/storage/nvme5/new_clones/SystemVerilog/lasernet' &
git clone https://github.com/cpuex2019-7th/core '/storage/nvme5/new_clones/SystemVerilog/core' &
git clone https://github.com/nfproc/PYNQ-BitPack '/storage/nvme5/new_clones/SystemVerilog/PYNQ-BitPack' &
git clone https://github.com/rggen/rggen-sv-ral '/storage/nvme5/new_clones/SystemVerilog/rggen-sv-ral' &
git clone https://github.com/pradyuman/aes-encryption-engine '/storage/nvme5/new_clones/SystemVerilog/aes-encryption-engine' &
git clone https://github.com/OFS/ofs-fim-common '/storage/nvme5/new_clones/SystemVerilog/ofs-fim-common' &
git clone https://github.com/kitune-san/KFMMC '/storage/nvme5/new_clones/SystemVerilog/KFMMC' &
git clone https://github.com/ObviouslyGreen/JZ-Wentworth-Cache-Now '/storage/nvme5/new_clones/SystemVerilog/JZ-Wentworth-Cache-Now' &
git clone https://github.com/adnanashraf17501/UVM_AMBA3_APB_FUNCTIONAL-COVERAGE '/storage/nvme5/new_clones/SystemVerilog/UVM_AMBA3_APB_FUNCTIONAL-COVERAGE' &
git clone https://github.com/ministrike3/ECE-385-Final-Project '/storage/nvme5/new_clones/SystemVerilog/ECE-385-Final-Project' &
git clone https://github.com/tsmk94/Taiga '/storage/nvme5/new_clones/SystemVerilog/Taiga' &
git clone https://github.com/jay16udani/ECE745_LC3_Verification '/storage/nvme5/new_clones/SystemVerilog/ECE745_LC3_Verification' &
git clone https://github.com/putongputong-lin/ahb2sram '/storage/nvme5/new_clones/SystemVerilog/ahb2sram' &
git clone https://github.com/ericgineer/ADCinterface '/storage/nvme5/new_clones/SystemVerilog/ADCinterface' &
git clone https://github.com/VeriBlock/vBlake-RTL '/storage/nvme5/new_clones/SystemVerilog/vBlake-RTL' &
git clone https://github.com/QianfengClarkShen/easy_fifo '/storage/nvme5/new_clones/SystemVerilog/easy_fifo' &
git clone https://github.com/shashwat2707/APB-Verification '/storage/nvme5/new_clones/SystemVerilog/APB-Verification' &
git clone https://github.com/AI-Vector-Accelerator/x-ava-core '/storage/nvme5/new_clones/SystemVerilog/x-ava-core' &
git clone https://github.com/gchinna/ahb_pkg '/storage/nvme5/new_clones/SystemVerilog/ahb_pkg' &
git clone https://github.com/pulp-platform/apb_node '/storage/nvme5/new_clones/SystemVerilog/apb_node' &
git clone https://github.com/Emi-Pushpam/AHB-with-FIFO '/storage/nvme5/new_clones/SystemVerilog/AHB-with-FIFO' &
git clone https://github.com/zhelnio/uvm_ahb_lite '/storage/nvme5/new_clones/SystemVerilog/uvm_ahb_lite' &
git clone https://github.com/JamesG321/FPGA-GPU '/storage/nvme5/new_clones/SystemVerilog/FPGA-GPU' &
git clone https://github.com/U-Ar/Kotsu2Risc '/storage/nvme5/new_clones/SystemVerilog/Kotsu2Risc' &
git clone https://github.com/smartfoxdata/aes128 '/storage/nvme5/new_clones/SystemVerilog/aes128' &
git clone https://github.com/bharathp04/ahb2apb_bridge_verification '/storage/nvme5/new_clones/SystemVerilog/ahb2apb_bridge_verification' &
git clone https://github.com/ZivFung/xc7a50t_microblaze_FDAF '/storage/nvme5/new_clones/SystemVerilog/xc7a50t_microblaze_FDAF' &
git clone https://github.com/Dragon-Git/icdk '/storage/nvme5/new_clones/SystemVerilog/icdk' &
git clone https://github.com/lowRISC/gsoc-sim-mem '/storage/nvme5/new_clones/SystemVerilog/gsoc-sim-mem' &
git clone https://github.com/hdlguy/arty_mac_test '/storage/nvme5/new_clones/SystemVerilog/arty_mac_test' &
git clone https://github.com/Luke7412/IpLibrary '/storage/nvme5/new_clones/SystemVerilog/IpLibrary' &
git clone https://github.com/Harrypotterrrr/mips-CPU54 '/storage/nvme5/new_clones/SystemVerilog/mips-CPU54' &
git clone https://github.com/PaulZC/XLR8_VGA_HDMI_XB '/storage/nvme5/new_clones/SystemVerilog/XLR8_VGA_HDMI_XB' &
git clone https://github.com/hypernyan/hdl_generics '/storage/nvme5/new_clones/SystemVerilog/hdl_generics' &
git clone https://github.com/EliasManj/Verilog-PS2-LCD-Interface '/storage/nvme5/new_clones/SystemVerilog/Verilog-PS2-LCD-Interface' &
git clone https://github.com/Darksecond/TimeWave '/storage/nvme5/new_clones/SystemVerilog/TimeWave' &
git clone https://github.com/pulp-training/sw '/storage/nvme5/new_clones/SystemVerilog/sw' &
git clone https://github.com/artemglukhov/FLOG_BFLOAT16 '/storage/nvme5/new_clones/SystemVerilog/FLOG_BFLOAT16' &
git clone https://github.com/sanketkkeni/Dual-issue-Pipelined-Multimedia-Processor-Architecture- '/storage/nvme5/new_clones/SystemVerilog/Dual-issue-Pipelined-Multimedia-Processor-Architecture-' &
git clone https://github.com/vishpbharadwaj/Lenet_arch '/storage/nvme5/new_clones/SystemVerilog/Lenet_arch' &
git clone https://github.com/kashifminhas/IBEX-Design-Verification-Environment '/storage/nvme5/new_clones/SystemVerilog/IBEX-Design-Verification-Environment' &
git clone https://github.com/AmeerAbdelhadi/Linear-Feedback-Shift-Register-LFSR-Counter '/storage/nvme5/new_clones/SystemVerilog/Linear-Feedback-Shift-Register-LFSR-Counter' &
git clone https://github.com/kumarrishav14/ALU_UVM '/storage/nvme5/new_clones/SystemVerilog/ALU_UVM' &
git clone https://github.com/ajaybin/APB-UART-bridge '/storage/nvme5/new_clones/SystemVerilog/APB-UART-bridge' &
git clone https://github.com/darthsider/SystemVerilog '/storage/nvme5/new_clones/SystemVerilog/SystemVerilog' &
git clone https://github.com/arunov/musk '/storage/nvme5/new_clones/SystemVerilog/musk' &
git clone https://github.com/charkster/cmod_a7_spi_sram '/storage/nvme5/new_clones/SystemVerilog/cmod_a7_spi_sram' &
git clone https://github.com/msinger/dmg-sim '/storage/nvme5/new_clones/SystemVerilog/dmg-sim' &
git clone https://github.com/basilwong/FPGA-ARC4-cracker '/storage/nvme5/new_clones/SystemVerilog/FPGA-ARC4-cracker' &
git clone https://github.com/Reconfigurable-Computing/flex_BRAM_FPGA '/storage/nvme5/new_clones/SystemVerilog/flex_BRAM_FPGA' &
git clone https://github.com/theSergeyGusev/simple10GbaseR '/storage/nvme5/new_clones/SystemVerilog/simple10GbaseR' &
git clone https://github.com/vincent-camus/benchmarking-precision-scalable-mac-units '/storage/nvme5/new_clones/SystemVerilog/benchmarking-precision-scalable-mac-units' &
git clone https://github.com/pulp-platform/icache_private '/storage/nvme5/new_clones/SystemVerilog/icache_private' &
git clone https://github.com/david-fong/Sudoku-SV '/storage/nvme5/new_clones/SystemVerilog/Sudoku-SV' &
git clone https://github.com/ComicAddict/Polyphonic_FPGA_Synthesizer '/storage/nvme5/new_clones/SystemVerilog/Polyphonic_FPGA_Synthesizer' &
git clone https://github.com/j1s1e1/VerilogFarrowFilter '/storage/nvme5/new_clones/SystemVerilog/VerilogFarrowFilter' &
git clone https://github.com/mist-devel/nes '/storage/nvme5/new_clones/SystemVerilog/nes' &
git clone https://github.com/Yummot/adapters '/storage/nvme5/new_clones/SystemVerilog/adapters' &
git clone https://github.com/Travissss/100BT1_DV '/storage/nvme5/new_clones/SystemVerilog/100BT1_DV' &
git clone https://github.com/souryadey/mlp-ondevice-training '/storage/nvme5/new_clones/SystemVerilog/mlp-ondevice-training' &
git clone https://github.com/theSergeyGusev/svReadWrite_pcap '/storage/nvme5/new_clones/SystemVerilog/svReadWrite_pcap' &
git clone https://github.com/rajkumarraval/i2c_wb_sv_uvm '/storage/nvme5/new_clones/SystemVerilog/i2c_wb_sv_uvm' &
git clone https://github.com/Ammar-10xe/RISCV-32I-Single-Cycle-Processor '/storage/nvme5/new_clones/SystemVerilog/RISCV-32I-Single-Cycle-Processor' &
git clone https://github.com/iammituraj/debouncer '/storage/nvme5/new_clones/SystemVerilog/debouncer' &
git clone https://github.com/SpiNNakerManchester/spif '/storage/nvme5/new_clones/SystemVerilog/spif' &
git clone https://github.com/YosysHQ/scy '/storage/nvme5/new_clones/SystemVerilog/scy' &
git clone https://github.com/pulp-platform/hwpe-ctrl '/storage/nvme5/new_clones/SystemVerilog/hwpe-ctrl' &
git clone https://github.com/VerticalResearchGroup/ComputeLibrary '/storage/nvme5/new_clones/SystemVerilog/ComputeLibrary' &
git clone https://github.com/comestime/RTL4Interview '/storage/nvme5/new_clones/SystemVerilog/RTL4Interview' &
git clone https://github.com/nbdd0121/sdhci '/storage/nvme5/new_clones/SystemVerilog/sdhci' &
git clone https://github.com/mballance/sv_bfms '/storage/nvme5/new_clones/SystemVerilog/sv_bfms' &
git clone https://github.com/AkshayXPatil/Design-verification '/storage/nvme5/new_clones/SystemVerilog/Design-verification' &
