#!/bin/bash

git clone https://github.com/tlaplus/Examples '/storage/nvme5/new_clones/TLA/Examples' &
git clone https://github.com/spacejam/tla-rust '/storage/nvme5/new_clones/TLA/tla-rust' &
git clone https://github.com/tlaplus/DrTLAPlus '/storage/nvme5/new_clones/TLA/DrTLAPlus' &
git clone https://github.com/lemmy/BlockingQueue '/storage/nvme5/new_clones/TLA/BlockingQueue' &
git clone https://github.com/ongardie/raft.tla '/storage/nvme5/new_clones/TLA/raft.tla' &
git clone https://github.com/pingcap/tla-plus '/storage/nvme5/new_clones/TLA/tla-plus' &
git clone https://github.com/Apress/practical-tla-plus '/storage/nvme5/new_clones/TLA/practical-tla-plus' &
git clone https://github.com/tlaplus/CommunityModules '/storage/nvme5/new_clones/TLA/CommunityModules' &
git clone https://github.com/Azure/azure-cosmos-tla '/storage/nvme5/new_clones/TLA/azure-cosmos-tla' &
git clone https://github.com/hwayne/learntla-v2 '/storage/nvme5/new_clones/TLA/learntla-v2' &
git clone https://github.com/DistCompiler/pgo '/storage/nvme5/new_clones/TLA/pgo' &
git clone https://github.com/Vanlightly/bookkeeper-tlaplus '/storage/nvme5/new_clones/TLA/bookkeeper-tlaplus' &
git clone https://github.com/will62794/spectacle '/storage/nvme5/new_clones/TLA/spectacle' &
git clone https://github.com/hachikuji/kafka-specification '/storage/nvme5/new_clones/TLA/kafka-specification' &
git clone https://github.com/muratdem/PlusCal-examples '/storage/nvme5/new_clones/TLA/PlusCal-examples' &
git clone https://github.com/Vanlightly/kafka-tlaplus '/storage/nvme5/new_clones/TLA/kafka-tlaplus' &
git clone https://github.com/Vanlightly/raft-tlaplus '/storage/nvme5/new_clones/TLA/raft-tlaplus' &
git clone https://github.com/HappyCS-Gu/Parallel-Raft-tla '/storage/nvme5/new_clones/TLA/Parallel-Raft-tla' &
git clone https://github.com/tlaplus-workshops/ewd998 '/storage/nvme5/new_clones/TLA/ewd998' &
git clone https://github.com/lorin/tla-linearizability '/storage/nvme5/new_clones/TLA/tla-linearizability' &
git clone https://github.com/visualzhou/mongo-repl-tla '/storage/nvme5/new_clones/TLA/mongo-repl-tla' &
git clone https://github.com/will62794/tlaplus_animation '/storage/nvme5/new_clones/TLA/tlaplus_animation' &
git clone https://github.com/ElliotSwart/pragmaticformalmodeling '/storage/nvme5/new_clones/TLA/pragmaticformalmodeling' &
git clone https://github.com/lostbearlabs/tiny-tlaplus-examples '/storage/nvme5/new_clones/TLA/tiny-tlaplus-examples' &
git clone https://github.com/JYwellin/CRDT-TLA '/storage/nvme5/new_clones/TLA/CRDT-TLA' &
git clone https://github.com/lemmy/ewd998 '/storage/nvme5/new_clones/TLA/ewd998' &
git clone https://github.com/fpaxos/fpaxos-tlaplus '/storage/nvme5/new_clones/TLA/fpaxos-tlaplus' &
git clone https://github.com/mitchellh/tlaplus-radix-tree '/storage/nvme5/new_clones/TLA/tlaplus-radix-tree' &
git clone https://github.com/Vanlightly/vsr-tlaplus '/storage/nvme5/new_clones/TLA/vsr-tlaplus' &
git clone https://github.com/istoilkovska/synchronous-tla-benchmarks '/storage/nvme5/new_clones/TLA/synchronous-tla-benchmarks' &
git clone https://github.com/mryndzionek/tlaplus_specs '/storage/nvme5/new_clones/TLA/tlaplus_specs' &
git clone https://github.com/dgpv/SASwap_TLAplus_spec '/storage/nvme5/new_clones/TLA/SASwap_TLAplus_spec' &
git clone https://github.com/belaban/pluscal '/storage/nvme5/new_clones/TLA/pluscal' &
git clone https://github.com/skarupke/two_bit_mutex '/storage/nvme5/new_clones/TLA/two_bit_mutex' &
git clone https://github.com/cwi-swat/tla-ci '/storage/nvme5/new_clones/TLA/tla-ci' &
git clone https://github.com/cobusve/TLAPLUS_DeadlockEmpire '/storage/nvme5/new_clones/TLA/TLAPLUS_DeadlockEmpire' &
git clone https://github.com/Isaac-DeFrain/TLAplusFun '/storage/nvme5/new_clones/TLA/TLAplusFun' &
git clone https://github.com/parlarjb/tla_workshop '/storage/nvme5/new_clones/TLA/tla_workshop' &
git clone https://github.com/matklad/paxosnotes '/storage/nvme5/new_clones/TLA/paxosnotes' &
git clone https://github.com/afonsonf/ceph-consensus-spec '/storage/nvme5/new_clones/TLA/ceph-consensus-spec' &
git clone https://github.com/Starydark/PaxosStore-tla '/storage/nvme5/new_clones/TLA/PaxosStore-tla' &
git clone https://github.com/crytic/whipstaff '/storage/nvme5/new_clones/TLA/whipstaff' &
git clone https://github.com/hwayne/tla-snippets '/storage/nvme5/new_clones/TLA/tla-snippets' &
git clone https://github.com/tezedge/tezedge-specification '/storage/nvme5/new_clones/TLA/tezedge-specification' &
git clone https://github.com/will62794/mongo-repl-tla-models '/storage/nvme5/new_clones/TLA/mongo-repl-tla-models' &
git clone https://github.com/nano-o/PaxosMadeSimple '/storage/nvme5/new_clones/TLA/PaxosMadeSimple' &
git clone https://github.com/dranov/raft-tla '/storage/nvme5/new_clones/TLA/raft-tla' &
git clone https://github.com/ease-lab/Zeus '/storage/nvme5/new_clones/TLA/Zeus' &
git clone https://github.com/fpaxos/ffpaxos-tlaplus '/storage/nvme5/new_clones/TLA/ffpaxos-tlaplus' &
git clone https://github.com/kuujo/just-in-time-paxos '/storage/nvme5/new_clones/TLA/just-in-time-paxos' &
git clone https://github.com/will62794/snapshot-isolation-spec '/storage/nvme5/new_clones/TLA/snapshot-isolation-spec' &
git clone https://github.com/stresch/pingpong '/storage/nvme5/new_clones/TLA/pingpong' &
git clone https://github.com/statechannels/tla-specs '/storage/nvme5/new_clones/TLA/tla-specs' &
git clone https://github.com/decanus/rutschblock '/storage/nvme5/new_clones/TLA/rutschblock' &
git clone https://github.com/VadimPlh/Arrival '/storage/nvme5/new_clones/TLA/Arrival' &
git clone https://github.com/siddontang/tlaplus-example '/storage/nvme5/new_clones/TLA/tlaplus-example' &
git clone https://github.com/lorin/epidemic-register '/storage/nvme5/new_clones/TLA/epidemic-register' &
git clone https://github.com/talex5/spec-vchan '/storage/nvme5/new_clones/TLA/spec-vchan' &
git clone https://github.com/informalsystems/audits '/storage/nvme5/new_clones/TLA/audits' &
git clone https://github.com/TeamTilapia/vscode-tilapia '/storage/nvme5/new_clones/TLA/vscode-tilapia' &
git clone https://github.com/muratdem/HLC '/storage/nvme5/new_clones/TLA/HLC' &
git clone https://github.com/gotchoices/MyCHIPs '/storage/nvme5/new_clones/TLA/MyCHIPs' &
git clone https://github.com/kit-dsn/payment-channel-tla '/storage/nvme5/new_clones/TLA/payment-channel-tla' &
git clone https://github.com/will62794/endive '/storage/nvme5/new_clones/TLA/endive' &
git clone https://github.com/Rebalanser/wiki '/storage/nvme5/new_clones/TLA/wiki' &
git clone https://github.com/will62794/logless-reconfig '/storage/nvme5/new_clones/TLA/logless-reconfig' &
git clone https://github.com/aman-goel/ivybench '/storage/nvme5/new_clones/TLA/ivybench' &
git clone https://github.com/tbg/caspaxos-tla '/storage/nvme5/new_clones/TLA/caspaxos-tla' &
git clone https://github.com/nano-o/MultiPaxos '/storage/nvme5/new_clones/TLA/MultiPaxos' &
git clone https://github.com/cs6213/tlaplus-examples '/storage/nvme5/new_clones/TLA/tlaplus-examples' &
git clone https://github.com/irfansharif/raft.tla '/storage/nvme5/new_clones/TLA/raft.tla' &
git clone https://github.com/skarupke/glibc_cv_tla_plus '/storage/nvme5/new_clones/TLA/glibc_cv_tla_plus' &
git clone https://github.com/informalsystems/atomkraft-cosmos '/storage/nvme5/new_clones/TLA/atomkraft-cosmos' &
git clone https://github.com/Cjen1/consensus-tlaplus '/storage/nvme5/new_clones/TLA/consensus-tlaplus' &
git clone https://github.com/BinyuHuang-nju/zab-tla '/storage/nvme5/new_clones/TLA/zab-tla' &
git clone https://github.com/sanjosh/tlaplus '/storage/nvme5/new_clones/TLA/tlaplus' &
git clone https://github.com/oscarcosta/crdt-tla '/storage/nvme5/new_clones/TLA/crdt-tla' &
git clone https://github.com/heidihoward/leaderelection-tlaplus '/storage/nvme5/new_clones/TLA/leaderelection-tlaplus' &
git clone https://github.com/atomix/atomix-tlaplus '/storage/nvme5/new_clones/TLA/atomix-tlaplus' &
git clone https://github.com/dmilstein/channels '/storage/nvme5/new_clones/TLA/channels' &
git clone https://github.com/DistAlgo/proofs '/storage/nvme5/new_clones/TLA/proofs' &
git clone https://github.com/byisystems/byihive '/storage/nvme5/new_clones/TLA/byihive' &
git clone https://github.com/lorin/tla-prophecy '/storage/nvme5/new_clones/TLA/tla-prophecy' &
git clone https://github.com/mbellotti/tla-cascading-failure '/storage/nvme5/new_clones/TLA/tla-cascading-failure' &
git clone https://github.com/hop-protocol/tla-spec '/storage/nvme5/new_clones/TLA/tla-spec' &
git clone https://github.com/zobront/tla-specs '/storage/nvme5/new_clones/TLA/tla-specs' &
git clone https://github.com/Starydark/Tencent-Paxos-TLA '/storage/nvme5/new_clones/TLA/Tencent-Paxos-TLA' &
git clone https://github.com/ahelwer/runway-tla-eval '/storage/nvme5/new_clones/TLA/runway-tla-eval' &
git clone https://github.com/vacp2p/formalities '/storage/nvme5/new_clones/TLA/formalities' &
git clone https://github.com/pkj415/PBFT-TLA '/storage/nvme5/new_clones/TLA/PBFT-TLA' &
git clone https://github.com/suhr/advent-of-tla '/storage/nvme5/new_clones/TLA/advent-of-tla' &
git clone https://github.com/ease-lab/1Update '/storage/nvme5/new_clones/TLA/1Update' &
git clone https://github.com/johnynek/rules_tla '/storage/nvme5/new_clones/TLA/rules_tla' &
git clone https://github.com/arnaudbos/aoc2020-tla-plus '/storage/nvme5/new_clones/TLA/aoc2020-tla-plus' &
git clone https://github.com/rust-p2p/specs '/storage/nvme5/new_clones/TLA/specs' &
git clone https://github.com/hengxin/tla-causal-consistency '/storage/nvme5/new_clones/TLA/tla-causal-consistency' &
git clone https://github.com/longinus41/pod_spec '/storage/nvme5/new_clones/TLA/pod_spec' &
