#!/bin/bash

git clone https://github.com/pelias/pelias '/storage/nvme5/new_clones/Twig/pelias' &
git clone https://github.com/symfony/web-profiler-bundle '/storage/nvme5/new_clones/Twig/web-profiler-bundle' &
git clone https://github.com/userfrosting/UserFrosting '/storage/nvme5/new_clones/Twig/UserFrosting' &
git clone https://github.com/timber/starter-theme '/storage/nvme5/new_clones/Twig/starter-theme' &
git clone https://github.com/PUGX/badge-poser '/storage/nvme5/new_clones/Twig/badge-poser' &
git clone https://github.com/Rareloop/lumberjack '/storage/nvme5/new_clones/Twig/lumberjack' &
git clone https://github.com/boltdesignsystem/bolt '/storage/nvme5/new_clones/Twig/bolt' &
git clone https://github.com/nystudio107/craft '/storage/nvme5/new_clones/Twig/craft' &
git clone https://github.com/appwrite/sdk-generator '/storage/nvme5/new_clones/Twig/sdk-generator' &
git clone https://github.com/mattwaler/tea-stack '/storage/nvme5/new_clones/Twig/tea-stack' &
git clone https://github.com/tfxor/terrahub '/storage/nvme5/new_clones/Twig/terrahub' &
git clone https://github.com/craftcms/craft '/storage/nvme5/new_clones/Twig/craft' &
git clone https://github.com/PrestaShop/example-modules '/storage/nvme5/new_clones/Twig/example-modules' &
git clone https://github.com/brendt/stitcher.io '/storage/nvme5/new_clones/Twig/stitcher.io' &
git clone https://github.com/silverstripe/silverstripe-installer '/storage/nvme5/new_clones/Twig/silverstripe-installer' &
git clone https://github.com/php-fig/www.php-fig.org '/storage/nvme5/new_clones/Twig/www.php-fig.org' &
git clone https://github.com/lewisjenkins/craft-dynamic-fields '/storage/nvme5/new_clones/Twig/craft-dynamic-fields' &
git clone https://github.com/sandoche/Detoxify-app '/storage/nvme5/new_clones/Twig/Detoxify-app' &
git clone https://github.com/davidpv/symfony2cheatsheet '/storage/nvme5/new_clones/Twig/symfony2cheatsheet' &
git clone https://github.com/yemiwebby/symfony-hackathon-starter '/storage/nvme5/new_clones/Twig/symfony-hackathon-starter' &
git clone https://github.com/kevinpapst/TablerBundle '/storage/nvme5/new_clones/Twig/TablerBundle' &
git clone https://github.com/ivandoric/d8theming '/storage/nvme5/new_clones/Twig/d8theming' &
git clone https://github.com/SyliusCrafts/BootstrapTheme '/storage/nvme5/new_clones/Twig/BootstrapTheme' &
git clone https://github.com/cearls/timberland '/storage/nvme5/new_clones/Twig/timberland' &
git clone https://github.com/nystudio107/devmode '/storage/nvme5/new_clones/Twig/devmode' &
git clone https://github.com/knpuniversity/symfony4 '/storage/nvme5/new_clones/Twig/symfony4' &
git clone https://github.com/w3c/w3c-website-templates-bundle '/storage/nvme5/new_clones/Twig/w3c-website-templates-bundle' &
git clone https://github.com/onedarnleyroad/craftcms '/storage/nvme5/new_clones/Twig/craftcms' &
git clone https://github.com/monsieurbiz/SyliusRichEditorPlugin '/storage/nvme5/new_clones/Twig/SyliusRichEditorPlugin' &
git clone https://github.com/giggsey/libphonenumber-example '/storage/nvme5/new_clones/Twig/libphonenumber-example' &
git clone https://github.com/webfactory/exceptions-bundle '/storage/nvme5/new_clones/Twig/exceptions-bundle' &
git clone https://github.com/shopware/storefront '/storage/nvme5/new_clones/Twig/storefront' &
git clone https://github.com/TYPO3/TYPO3.Icons '/storage/nvme5/new_clones/Twig/TYPO3.Icons' &
git clone https://github.com/SymfonyCasts/symfony5 '/storage/nvme5/new_clones/Twig/symfony5' &
git clone https://github.com/UltimateModuleCreator/umc '/storage/nvme5/new_clones/Twig/umc' &
git clone https://github.com/flagbit/shopware6-tailwind-theme '/storage/nvme5/new_clones/Twig/shopware6-tailwind-theme' &
git clone https://github.com/paragonie/paseto-io '/storage/nvme5/new_clones/Twig/paseto-io' &
git clone https://github.com/coopTilleuls/CoopTilleulsCKEditorSonataMediaBundle '/storage/nvme5/new_clones/Twig/CoopTilleulsCKEditorSonataMediaBundle' &
git clone https://github.com/loganmarchione/docker-php-startpage '/storage/nvme5/new_clones/Twig/docker-php-startpage' &
git clone https://github.com/davidhellmann/craftcms-baukasten '/storage/nvme5/new_clones/Twig/craftcms-baukasten' &
git clone https://github.com/craftcms/spoke-and-chain '/storage/nvme5/new_clones/Twig/spoke-and-chain' &
git clone https://github.com/alexsoin/pepelac '/storage/nvme5/new_clones/Twig/pepelac' &
git clone https://github.com/afsy/website '/storage/nvme5/new_clones/Twig/website' &
git clone https://github.com/anthonyaxenov/iptv '/storage/nvme5/new_clones/Twig/iptv' &
git clone https://github.com/robbinjohansson/haywire-grav '/storage/nvme5/new_clones/Twig/haywire-grav' &
git clone https://github.com/PacktPublishing/Drupal-10-Development-Cookbook '/storage/nvme5/new_clones/Twig/Drupal-10-Development-Cookbook' &
git clone https://github.com/gantry/docs '/storage/nvme5/new_clones/Twig/docs' &
git clone https://github.com/digitalmanufaktur/shopware6-manu-theme '/storage/nvme5/new_clones/Twig/shopware6-manu-theme' &
git clone https://github.com/web-auth/symfony-webauthn-demo '/storage/nvme5/new_clones/Twig/symfony-webauthn-demo' &
git clone https://github.com/glauberportella/cnab-layouts '/storage/nvme5/new_clones/Twig/cnab-layouts' &
git clone https://github.com/uicrooks/shopify-mail-notifications '/storage/nvme5/new_clones/Twig/shopify-mail-notifications' &
git clone https://github.com/getgrav/grav-plugin-devtools '/storage/nvme5/new_clones/Twig/grav-plugin-devtools' &
git clone https://github.com/FriendsOfShopware/FroshProductCompare '/storage/nvme5/new_clones/Twig/FroshProductCompare' &
git clone https://github.com/ThronesDB/thronesdb '/storage/nvme5/new_clones/Twig/thronesdb' &
git clone https://github.com/uvdesk/support-center-bundle '/storage/nvme5/new_clones/Twig/support-center-bundle' &
git clone https://github.com/runelaenen/shopware6-advanced-banners '/storage/nvme5/new_clones/Twig/shopware6-advanced-banners' &
git clone https://github.com/CreateSean/craft-starter '/storage/nvme5/new_clones/Twig/craft-starter' &
git clone https://github.com/SallaApp/theme-raed '/storage/nvme5/new_clones/Twig/theme-raed' &
git clone https://github.com/wp-cli/package-index '/storage/nvme5/new_clones/Twig/package-index' &
git clone https://github.com/dsmink/twig-bulma-form-theme-bundle '/storage/nvme5/new_clones/Twig/twig-bulma-form-theme-bundle' &
git clone https://github.com/netgen/media-site '/storage/nvme5/new_clones/Twig/media-site' &
git clone https://github.com/phpbenchmarks/benchmark-kit '/storage/nvme5/new_clones/Twig/benchmark-kit' &
git clone https://github.com/statikbe/craft '/storage/nvme5/new_clones/Twig/craft' &
git clone https://github.com/ParitoshBh/grav-coder '/storage/nvme5/new_clones/Twig/grav-coder' &
git clone https://github.com/lemmon/kirby-portfolio-theme '/storage/nvme5/new_clones/Twig/kirby-portfolio-theme' &
git clone https://github.com/chr-hertel/console-example '/storage/nvme5/new_clones/Twig/console-example' &
git clone https://github.com/tomaszbujnowicz/hybrid-utility-itcss '/storage/nvme5/new_clones/Twig/hybrid-utility-itcss' &
git clone https://github.com/iamromeo/worldanvil-templates '/storage/nvme5/new_clones/Twig/worldanvil-templates' &
git clone https://github.com/jadu/pulsar '/storage/nvme5/new_clones/Twig/pulsar' &
git clone https://github.com/FoxyCart/2.0-templates '/storage/nvme5/new_clones/Twig/2.0-templates' &
git clone https://github.com/Perlkonig/grav-theme-knowledge-base '/storage/nvme5/new_clones/Twig/grav-theme-knowledge-base' &
git clone https://github.com/paulmassen/grav-theme-chalk '/storage/nvme5/new_clones/Twig/grav-theme-chalk' &
git clone https://github.com/emulsify-ds/emulsify-wordpress-theme '/storage/nvme5/new_clones/Twig/emulsify-wordpress-theme' &
git clone https://github.com/bolt/themes '/storage/nvme5/new_clones/Twig/themes' &
git clone https://github.com/Pagerfanta/twig '/storage/nvme5/new_clones/Twig/twig' &
git clone https://github.com/epfl-si/elements '/storage/nvme5/new_clones/Twig/elements' &
git clone https://github.com/imarc/padstone '/storage/nvme5/new_clones/Twig/padstone' &
git clone https://github.com/nelson6e65/phpdoc-vuepress '/storage/nvme5/new_clones/Twig/phpdoc-vuepress' &
git clone https://github.com/hibbitts-design/grav-theme-quark-open-publishing '/storage/nvme5/new_clones/Twig/grav-theme-quark-open-publishing' &
git clone https://github.com/getgrav/grav-plugin-snipcart '/storage/nvme5/new_clones/Twig/grav-plugin-snipcart' &
git clone https://github.com/Drupal-FR/site-drupalfr '/storage/nvme5/new_clones/Twig/site-drupalfr' &
git clone https://github.com/leduc92/sbuorderadvancedfilter '/storage/nvme5/new_clones/Twig/sbuorderadvancedfilter' &
git clone https://github.com/kimai/invoice-templates '/storage/nvme5/new_clones/Twig/invoice-templates' &
git clone https://github.com/Arkounay/ux-media '/storage/nvme5/new_clones/Twig/ux-media' &
git clone https://github.com/ishetnogferre/craft-template '/storage/nvme5/new_clones/Twig/craft-template' &
git clone https://github.com/pixdoet/yt-2005-watch '/storage/nvme5/new_clones/Twig/yt-2005-watch' &
git clone https://github.com/ihabunek/hub3-api '/storage/nvme5/new_clones/Twig/hub3-api' &
git clone https://github.com/jgonyea/grav-plugin-podcast '/storage/nvme5/new_clones/Twig/grav-plugin-podcast' &
git clone https://github.com/OXID-eSales/apex-theme '/storage/nvme5/new_clones/Twig/apex-theme' &
git clone https://github.com/darylknight/boilerplate '/storage/nvme5/new_clones/Twig/boilerplate' &
git clone https://github.com/getgrav/grav-theme-bootstrap '/storage/nvme5/new_clones/Twig/grav-theme-bootstrap' &
git clone https://github.com/hackzilla/password-generator-app '/storage/nvme5/new_clones/Twig/password-generator-app' &
git clone https://github.com/elgentos/shopware-seo-canonical-url '/storage/nvme5/new_clones/Twig/shopware-seo-canonical-url' &
git clone https://github.com/Shape-and-Shift/shopware-cms-grid-blocks '/storage/nvme5/new_clones/Twig/shopware-cms-grid-blocks' &
git clone https://github.com/stefanpoensgen/SptecLazyload '/storage/nvme5/new_clones/Twig/SptecLazyload' &
git clone https://github.com/diomed/casper '/storage/nvme5/new_clones/Twig/casper' &
git clone https://github.com/philippebeck/animadio.org '/storage/nvme5/new_clones/Twig/animadio.org' &
git clone https://github.com/OXID-eSales/twig-admin-theme '/storage/nvme5/new_clones/Twig/twig-admin-theme' &
git clone https://github.com/jasonccox/grav-theme-webfolio '/storage/nvme5/new_clones/Twig/grav-theme-webfolio' &
git clone https://github.com/trilbymedia/grav-theme-bootstrap4 '/storage/nvme5/new_clones/Twig/grav-theme-bootstrap4' &
git clone https://github.com/Jonathanlight/sentraider_fr '/storage/nvme5/new_clones/Twig/sentraider_fr' &
git clone https://github.com/Sublime-Instincts/BetterTwig '/storage/nvme5/new_clones/Twig/BetterTwig' &
git clone https://github.com/symfonycorp/platformsh-symfony-template '/storage/nvme5/new_clones/Twig/platformsh-symfony-template' &
git clone https://github.com/CityofOakland/oaklandca.gov '/storage/nvme5/new_clones/Twig/oaklandca.gov' &
git clone https://github.com/moskoweb/New-Blank-Mautic-Theme '/storage/nvme5/new_clones/Twig/New-Blank-Mautic-Theme' &
git clone https://github.com/whatwedo/EsrBundle '/storage/nvme5/new_clones/Twig/EsrBundle' &
git clone https://github.com/tpmatthes/Twig.novaextension '/storage/nvme5/new_clones/Twig/Twig.novaextension' &
git clone https://github.com/MitocGroup/www '/storage/nvme5/new_clones/Twig/www' &
git clone https://github.com/eckinox/bolt-navigation-ui '/storage/nvme5/new_clones/Twig/bolt-navigation-ui' &
git clone https://github.com/thegreenter/report '/storage/nvme5/new_clones/Twig/report' &
git clone https://github.com/sinyayadynya/tailvite '/storage/nvme5/new_clones/Twig/tailvite' &
git clone https://github.com/ayozehd/grav-theme-bootstrap-blog '/storage/nvme5/new_clones/Twig/grav-theme-bootstrap-blog' &
git clone https://github.com/novosga/attendance-bundle '/storage/nvme5/new_clones/Twig/attendance-bundle' &
git clone https://github.com/juliangut/docker-phpdev '/storage/nvme5/new_clones/Twig/docker-phpdev' &
git clone https://github.com/MelvinAchterhuis/MelvDiscountSummary '/storage/nvme5/new_clones/Twig/MelvDiscountSummary' &
git clone https://github.com/FuenRob/Modules-Prestashop-1.7 '/storage/nvme5/new_clones/Twig/Modules-Prestashop-1.7' &
git clone https://github.com/kevinpapst/TablerBundle-Demo '/storage/nvme5/new_clones/Twig/TablerBundle-Demo' &
git clone https://github.com/thegreenter/xml '/storage/nvme5/new_clones/Twig/xml' &
git clone https://github.com/arnapou/gw2tools '/storage/nvme5/new_clones/Twig/gw2tools' &
git clone https://github.com/hotdoy/grav-theme-wheat '/storage/nvme5/new_clones/Twig/grav-theme-wheat' &
git clone https://github.com/PrestaShop/mjml-theme-converter '/storage/nvme5/new_clones/Twig/mjml-theme-converter' &
git clone https://github.com/elgentos/shopware-dutch-email-templates '/storage/nvme5/new_clones/Twig/shopware-dutch-email-templates' &
git clone https://github.com/timpritlove/podlove-templates '/storage/nvme5/new_clones/Twig/podlove-templates' &
git clone https://github.com/roadiz/BaseTheme '/storage/nvme5/new_clones/Twig/BaseTheme' &
git clone https://github.com/islandora-interest-groups/Islandora-Documentation-Interest-Group '/storage/nvme5/new_clones/Twig/Islandora-Documentation-Interest-Group' &
git clone https://github.com/SymfonyCasts/symfony6 '/storage/nvme5/new_clones/Twig/symfony6' &
git clone https://github.com/rayen-creator/SahtiAPPWeb '/storage/nvme5/new_clones/Twig/SahtiAPPWeb' &
git clone https://github.com/craftcms/tutorial-project '/storage/nvme5/new_clones/Twig/tutorial-project' &
git clone https://github.com/tpartner/LimeSurvey-Searchable-Dropdown-3x-5x '/storage/nvme5/new_clones/Twig/LimeSurvey-Searchable-Dropdown-3x-5x' &
git clone https://github.com/imarc/boilerplate '/storage/nvme5/new_clones/Twig/boilerplate' &
git clone https://github.com/localgovdrupal/localgov_base '/storage/nvme5/new_clones/Twig/localgov_base' &
git clone https://github.com/BZFlag-Dev/bzflag.org '/storage/nvme5/new_clones/Twig/bzflag.org' &
git clone https://github.com/PacktPublishing/Drupal-8-Development-Beginners-Guide-Second-Edition '/storage/nvme5/new_clones/Twig/Drupal-8-Development-Beginners-Guide-Second-Edition' &
git clone https://github.com/isubit/iastate_theme '/storage/nvme5/new_clones/Twig/iastate_theme' &
git clone https://github.com/drupalwxt/wxt_bootstrap '/storage/nvme5/new_clones/Twig/wxt_bootstrap' &
git clone https://github.com/iastate/iastate22-wordpress '/storage/nvme5/new_clones/Twig/iastate22-wordpress' &
git clone https://github.com/novosga/monitor-bundle '/storage/nvme5/new_clones/Twig/monitor-bundle' &
git clone https://github.com/italia/design-comuni-drupal-theme '/storage/nvme5/new_clones/Twig/design-comuni-drupal-theme' &
git clone https://github.com/SrGMC/pikion '/storage/nvme5/new_clones/Twig/pikion' &
git clone https://github.com/Elao/elao_ '/storage/nvme5/new_clones/Twig/elao_' &
git clone https://github.com/DarrylDias/Sidewalk '/storage/nvme5/new_clones/Twig/Sidewalk' &
git clone https://github.com/qw3rtty/grav-plugin-simple-cookie '/storage/nvme5/new_clones/Twig/grav-plugin-simple-cookie' &
git clone https://github.com/workos/php-example-applications '/storage/nvme5/new_clones/Twig/php-example-applications' &
git clone https://github.com/italia/design-drupal-theme '/storage/nvme5/new_clones/Twig/design-drupal-theme' &
git clone https://github.com/tfxor/www '/storage/nvme5/new_clones/Twig/www' &
git clone https://github.com/vanderbilt-redcap/external-module-templater '/storage/nvme5/new_clones/Twig/external-module-templater' &
git clone https://github.com/straightlight/opencart_contributions '/storage/nvme5/new_clones/Twig/opencart_contributions' &
git clone https://github.com/kerns/craft-on-ddev '/storage/nvme5/new_clones/Twig/craft-on-ddev' &
git clone https://github.com/romeritoCL/paypal-playground '/storage/nvme5/new_clones/Twig/paypal-playground' &
git clone https://github.com/beryllium/sculpin-tailwind-landing-skeleton '/storage/nvme5/new_clones/Twig/sculpin-tailwind-landing-skeleton' &
git clone https://github.com/giorgiopogliani/craftcms-starter-template '/storage/nvme5/new_clones/Twig/craftcms-starter-template' &
git clone https://github.com/ilrWebServices/union '/storage/nvme5/new_clones/Twig/union' &
git clone https://github.com/massimo-cassandro/symfony-bootstrap-form-theme '/storage/nvme5/new_clones/Twig/symfony-bootstrap-form-theme' &
git clone https://github.com/ruOpenCart/opencart3-webpack-theme '/storage/nvme5/new_clones/Twig/opencart3-webpack-theme' &
git clone https://github.com/cld-agency/craftwind-boilerplate '/storage/nvme5/new_clones/Twig/craftwind-boilerplate' &
git clone https://github.com/zidsa/custom-theme-sample '/storage/nvme5/new_clones/Twig/custom-theme-sample' &
git clone https://github.com/19h47/ride404 '/storage/nvme5/new_clones/Twig/ride404' &
git clone https://github.com/GaryClarke/promotions-engine-client '/storage/nvme5/new_clones/Twig/promotions-engine-client' &
git clone https://github.com/JunaidQadirB/awe-theme '/storage/nvme5/new_clones/Twig/awe-theme' &
git clone https://github.com/scrhllbrg/twigger '/storage/nvme5/new_clones/Twig/twigger' &
git clone https://github.com/PROGRAP/sw6-google-customer-reviews '/storage/nvme5/new_clones/Twig/sw6-google-customer-reviews' &
git clone https://github.com/FriendsOfShopware/FroshLazySizes '/storage/nvme5/new_clones/Twig/FroshLazySizes' &
git clone https://github.com/novosga/triage-bundle '/storage/nvme5/new_clones/Twig/triage-bundle' &
git clone https://github.com/fr3nch13/phpdoc-markdown '/storage/nvme5/new_clones/Twig/phpdoc-markdown' &
git clone https://github.com/tpartner/LimeSurvey-Card-Sorting-5x-6x '/storage/nvme5/new_clones/Twig/LimeSurvey-Card-Sorting-5x-6x' &
git clone https://github.com/getherbie/start-website '/storage/nvme5/new_clones/Twig/start-website' &
git clone https://github.com/brefphp/runtimes.bref.sh '/storage/nvme5/new_clones/Twig/runtimes.bref.sh' &
git clone https://github.com/willard/craftcms-rollupjs '/storage/nvme5/new_clones/Twig/craftcms-rollupjs' &
git clone https://github.com/drdogbot7/salvia-theme '/storage/nvme5/new_clones/Twig/salvia-theme' &
git clone https://github.com/Sylius/SyliusAdminBundle '/storage/nvme5/new_clones/Twig/SyliusAdminBundle' &
git clone https://github.com/web-illinois/illinois_framework_theme '/storage/nvme5/new_clones/Twig/illinois_framework_theme' &
git clone https://github.com/stakovicz/ux-collection '/storage/nvme5/new_clones/Twig/ux-collection' &
git clone https://github.com/guanguans/poetry '/storage/nvme5/new_clones/Twig/poetry' &
git clone https://github.com/vittominacori/funnychatgenerator '/storage/nvme5/new_clones/Twig/funnychatgenerator' &
git clone https://github.com/Amdouni-Dev/Project-with-scrum-method-Symfony-V4-Java-DESKTOP-CodeNameOne- '/storage/nvme5/new_clones/Twig/Project-with-scrum-method-Symfony-V4-Java-DESKTOP-CodeNameOne-' &
git clone https://github.com/zooboole/simple-static-website-with-Slim-3 '/storage/nvme5/new_clones/Twig/simple-static-website-with-Slim-3' &
git clone https://github.com/edgarjaviertec/php-admin-dashboard '/storage/nvme5/new_clones/Twig/php-admin-dashboard' &
git clone https://github.com/N-Parsons/grav-plugin-file-browser '/storage/nvme5/new_clones/Twig/grav-plugin-file-browser' &
git clone https://github.com/tpartner/LimeSurvey-Range-Slider-5x-6x '/storage/nvme5/new_clones/Twig/LimeSurvey-Range-Slider-5x-6x' &
git clone https://github.com/webstylecenter/Homepage '/storage/nvme5/new_clones/Twig/Homepage' &
git clone https://github.com/phpDocumentor/phpdoc.org '/storage/nvme5/new_clones/Twig/phpdoc.org' &
git clone https://github.com/PrestaShop/example_module_mailtheme '/storage/nvme5/new_clones/Twig/example_module_mailtheme' &
git clone https://github.com/poschi3/podlove-publisher-templates '/storage/nvme5/new_clones/Twig/podlove-publisher-templates' &
git clone https://github.com/mikesnoeren/craft '/storage/nvme5/new_clones/Twig/craft' &
git clone https://github.com/AsociacionDrupalES/AED '/storage/nvme5/new_clones/Twig/AED' &
git clone https://github.com/mozfr/nightly '/storage/nvme5/new_clones/Twig/nightly' &
git clone https://github.com/Vallic/bulma '/storage/nvme5/new_clones/Twig/bulma' &
git clone https://github.com/thomjjames/tws-tailwind-theme '/storage/nvme5/new_clones/Twig/tws-tailwind-theme' &
git clone https://github.com/ubc-web-services/galactus '/storage/nvme5/new_clones/Twig/galactus' &
