#!/bin/bash

git clone https://github.com/long-war-2/lwotc '/storage/nvme5/new_clones/UnrealScript/lwotc' &
git clone https://github.com/Defaultplayer001/Deus-Ex-Universe-Community-Update- '/storage/nvme5/new_clones/UnrealScript/Deus-Ex-Universe-Community-Update-' &
git clone https://github.com/alexstrout/foxWSFix-UT2k4 '/storage/nvme5/new_clones/UnrealScript/foxWSFix-UT2k4' &
git clone https://github.com/DarklightGames/DarkestHour '/storage/nvme5/new_clones/UnrealScript/DarkestHour' &
git clone https://github.com/X2CommunityCore/X2WOTCCommunityHighlander '/storage/nvme5/new_clones/UnrealScript/X2WOTCCommunityHighlander' &
git clone https://github.com/npruehs/hostile-worlds '/storage/nvme5/new_clones/UnrealScript/hostile-worlds' &
git clone https://github.com/BlueRaja/XCom2Mods '/storage/nvme5/new_clones/UnrealScript/XCom2Mods' &
git clone https://github.com/fullcone-nat-nftables/openwrt-firewall4-with-fullcone '/storage/nvme5/new_clones/UnrealScript/openwrt-firewall4-with-fullcone' &
git clone https://github.com/Slipyx/UT99 '/storage/nvme5/new_clones/UnrealScript/UT99' &
git clone https://github.com/alexstrout/foxWSFix-UT99 '/storage/nvme5/new_clones/UnrealScript/foxWSFix-UT99' &
git clone https://github.com/TotemArts/Renegade-X '/storage/nvme5/new_clones/UnrealScript/Renegade-X' &
git clone https://github.com/pdinklag/TitanRPG '/storage/nvme5/new_clones/UnrealScript/TitanRPG' &
git clone https://github.com/notblackout/kf2-controlled-difficulty '/storage/nvme5/new_clones/UnrealScript/kf2-controlled-difficulty' &
git clone https://github.com/EliotVU/Forms '/storage/nvme5/new_clones/UnrealScript/Forms' &
git clone https://github.com/ththi/Microbial-Interkingdom-Suppl '/storage/nvme5/new_clones/UnrealScript/Microbial-Interkingdom-Suppl' &
git clone https://github.com/WOTCStrategyOverhaul/CovertInfiltration '/storage/nvme5/new_clones/UnrealScript/CovertInfiltration' &
git clone https://github.com/metallicafan212/HP2UScriptDecompile '/storage/nvme5/new_clones/UnrealScript/HP2UScriptDecompile' &
git clone https://github.com/shrimpza/monsterhunt '/storage/nvme5/new_clones/UnrealScript/monsterhunt' &
git clone https://github.com/tinkertims/RL-Dummy-Classes-v2 '/storage/nvme5/new_clones/UnrealScript/RL-Dummy-Classes-v2' &
git clone https://github.com/uCalc/powerbasic-to-cpp '/storage/nvme5/new_clones/UnrealScript/powerbasic-to-cpp' &
git clone https://github.com/Ch0wW/xiii_unrealscript '/storage/nvme5/new_clones/UnrealScript/xiii_unrealscript' &
git clone https://github.com/chrishayesmu/XCOM-LW-CommunityEdition '/storage/nvme5/new_clones/UnrealScript/XCOM-LW-CommunityEdition' &
git clone https://github.com/OldUnreal/oldskool '/storage/nvme5/new_clones/UnrealScript/oldskool' &
git clone https://github.com/robertkhamilton/udkosc '/storage/nvme5/new_clones/UnrealScript/udkosc' &
git clone https://github.com/Deaod/UT2004 '/storage/nvme5/new_clones/UnrealScript/UT2004' &
git clone https://github.com/InsultingPros/KillingFloor '/storage/nvme5/new_clones/UnrealScript/KillingFloor' &
git clone https://github.com/hnlab/can-ai-do '/storage/nvme5/new_clones/UnrealScript/can-ai-do' &
git clone https://github.com/SeriousBuggie/XVehicles '/storage/nvme5/new_clones/UnrealScript/XVehicles' &
git clone https://github.com/andrewgu/ModConfigMenu '/storage/nvme5/new_clones/UnrealScript/ModConfigMenu' &
git clone https://github.com/Kizoky/p2unrealscript '/storage/nvme5/new_clones/UnrealScript/p2unrealscript' &
git clone https://github.com/CacoFFF/SiegeIV-UT99 '/storage/nvme5/new_clones/UnrealScript/SiegeIV-UT99' &
git clone https://github.com/EliotVU/UnrealScript-Unflect '/storage/nvme5/new_clones/UnrealScript/UnrealScript-Unflect' &
git clone https://github.com/PacktPublishing/UDK-Game-Development '/storage/nvme5/new_clones/UnrealScript/UDK-Game-Development' &
git clone https://github.com/l0m-dev/Undying-Renewal '/storage/nvme5/new_clones/UnrealScript/Undying-Renewal' &
git clone https://github.com/Ballistic-Weapons-Community/BallisticWeapons '/storage/nvme5/new_clones/UnrealScript/BallisticWeapons' &
git clone https://github.com/ShyKiss/Picker '/storage/nvme5/new_clones/UnrealScript/Picker' &
git clone https://github.com/Iramok/KF2mods '/storage/nvme5/new_clones/UnrealScript/KF2mods' &
git clone https://github.com/TalonBraveInfo/uw-resources '/storage/nvme5/new_clones/UnrealScript/uw-resources' &
git clone https://github.com/SystenceGames/TheMaestros-uScriptSource '/storage/nvme5/new_clones/UnrealScript/TheMaestros-uScriptSource' &
git clone https://github.com/stijn-volckaert/udemo '/storage/nvme5/new_clones/UnrealScript/udemo' &
git clone https://github.com/Speedy37/Alone '/storage/nvme5/new_clones/UnrealScript/Alone' &
git clone https://github.com/Favid/LongWar2AbilitiesForWotC '/storage/nvme5/new_clones/UnrealScript/LongWar2AbilitiesForWotC' &
git clone https://github.com/1337GameDev/Ut99Mods '/storage/nvme5/new_clones/UnrealScript/Ut99Mods' &
git clone https://github.com/X2CommunityCore/X2CommunityHighlander '/storage/nvme5/new_clones/UnrealScript/X2CommunityHighlander' &
git clone https://github.com/mbovijn/BTPog '/storage/nvme5/new_clones/UnrealScript/BTPog' &
git clone https://github.com/CacoFFF/LCWeapons-UT99 '/storage/nvme5/new_clones/UnrealScript/LCWeapons-UT99' &
git clone https://github.com/EliteTrials/UT2004-MutBestTimes '/storage/nvme5/new_clones/UnrealScript/UT2004-MutBestTimes' &
git clone https://github.com/ArHShRn/HealingExtend '/storage/nvme5/new_clones/UnrealScript/HealingExtend' &
git clone https://github.com/Ch0wW/pariah-uscript-source '/storage/nvme5/new_clones/UnrealScript/pariah-uscript-source' &
git clone https://github.com/wfut/wfut '/storage/nvme5/new_clones/UnrealScript/wfut' &
