#!/bin/bash

git clone https://github.com/vlang/v '/storage/nvme5/new_clones/V/v' &
git clone https://github.com/vlang/ui '/storage/nvme5/new_clones/V/ui' &
git clone https://github.com/cotowali/cotowali '/storage/nvme5/new_clones/V/cotowali' &
git clone https://github.com/vlang/vsl '/storage/nvme5/new_clones/V/vsl' &
git clone https://github.com/nedpals/vex '/storage/nvme5/new_clones/V/vex' &
git clone https://github.com/vlang/vab '/storage/nvme5/new_clones/V/vab' &
git clone https://github.com/elliotchance/vsql '/storage/nvme5/new_clones/V/vsql' &
git clone https://github.com/vlang/vls '/storage/nvme5/new_clones/V/vls' &
git clone https://github.com/vlang/coreutils '/storage/nvme5/new_clones/V/coreutils' &
git clone https://github.com/lydiandy/vlang_note '/storage/nvme5/new_clones/V/vlang_note' &
git clone https://github.com/v-community/v_by_example '/storage/nvme5/new_clones/V/v_by_example' &
git clone https://github.com/vlang/vtl '/storage/nvme5/new_clones/V/vtl' &
git clone https://github.com/valvalio/valval '/storage/nvme5/new_clones/V/valval' &
git clone https://github.com/dariotarantini/vgram '/storage/nvme5/new_clones/V/vgram' &
git clone https://github.com/pisaiah/Vide '/storage/nvme5/new_clones/V/Vide' &
git clone https://github.com/Terisback/discord.v '/storage/nvme5/new_clones/V/discord.v' &
git clone https://github.com/webui-dev/v-webui '/storage/nvme5/new_clones/V/v-webui' &
git clone https://github.com/vpkg-project/vpkg '/storage/nvme5/new_clones/V/vpkg' &
git clone https://github.com/S-YOU/pico.v '/storage/nvme5/new_clones/V/pico.v' &
git clone https://github.com/pisaiah/ui '/storage/nvme5/new_clones/V/ui' &
git clone https://github.com/malisipi/mui '/storage/nvme5/new_clones/V/mui' &
git clone https://github.com/lemoncmd/vcc '/storage/nvme5/new_clones/V/vcc' &
git clone https://github.com/thecodrr/boxx '/storage/nvme5/new_clones/V/boxx' &
git clone https://github.com/v420v/vas '/storage/nvme5/new_clones/V/vas' &
git clone https://github.com/vlang/pdf '/storage/nvme5/new_clones/V/pdf' &
git clone https://github.com/vlang/sdl '/storage/nvme5/new_clones/V/sdl' &
git clone https://github.com/malisipi/Vebview.JS '/storage/nvme5/new_clones/V/Vebview.JS' &
git clone https://github.com/joe-conigliaro/tinyv '/storage/nvme5/new_clones/V/tinyv' &
git clone https://github.com/patrickpissurno/vredis '/storage/nvme5/new_clones/V/vredis' &
git clone https://github.com/vlang/py2v '/storage/nvme5/new_clones/V/py2v' &
git clone https://github.com/pisaiah/vpaint '/storage/nvme5/new_clones/V/vpaint' &
git clone https://github.com/v-community/learn_v_in_y_minutes '/storage/nvme5/new_clones/V/learn_v_in_y_minutes' &
git clone https://github.com/organization/boundstone '/storage/nvme5/new_clones/V/boundstone' &
git clone https://github.com/vgtk/vgtk3 '/storage/nvme5/new_clones/V/vgtk3' &
git clone https://github.com/thecodrr/crayon '/storage/nvme5/new_clones/V/crayon' &
git clone https://github.com/NTBBloodbath/nvenv '/storage/nvme5/new_clones/V/nvenv' &
git clone https://github.com/emily33901/vproto '/storage/nvme5/new_clones/V/vproto' &
git clone https://github.com/justjosie/event-info-and-assets '/storage/nvme5/new_clones/V/event-info-and-assets' &
git clone https://github.com/vlang/markdown '/storage/nvme5/new_clones/V/markdown' &
git clone https://github.com/PacktPublishing/Getting-Started-with-V-Programming '/storage/nvme5/new_clones/V/Getting-Started-with-V-Programming' &
git clone https://github.com/eioo/vrobot '/storage/nvme5/new_clones/V/vrobot' &
git clone https://github.com/nsauzede/vnk '/storage/nvme5/new_clones/V/vnk' &
git clone https://github.com/ali-raheem/vraytracer '/storage/nvme5/new_clones/V/vraytracer' &
git clone https://github.com/larpon/vee '/storage/nvme5/new_clones/V/vee' &
git clone https://github.com/MajorHard/vraylib '/storage/nvme5/new_clones/V/vraylib' &
git clone https://github.com/thecodrr/vspeech '/storage/nvme5/new_clones/V/vspeech' &
git clone https://github.com/vlang/mongo '/storage/nvme5/new_clones/V/mongo' &
git clone https://github.com/lydiandy/vsql '/storage/nvme5/new_clones/V/vsql' &
git clone https://github.com/nsauzede/vsdl2 '/storage/nvme5/new_clones/V/vsdl2' &
git clone https://github.com/schicho/vwc '/storage/nvme5/new_clones/V/vwc' &
git clone https://github.com/JinChen-tw/pynqz2_dpu140 '/storage/nvme5/new_clones/V/pynqz2_dpu140' &
git clone https://github.com/serkonda7/termtable '/storage/nvme5/new_clones/V/termtable' &
git clone https://github.com/vlang/adventofcode '/storage/nvme5/new_clones/V/adventofcode' &
git clone https://github.com/Ekopalypse/NppLspClient '/storage/nvme5/new_clones/V/NppLspClient' &
git clone https://github.com/spaceface777/viano '/storage/nvme5/new_clones/V/viano' &
git clone https://github.com/hex2f/vib '/storage/nvme5/new_clones/V/vib' &
git clone https://github.com/hungrybluedev/whisker '/storage/nvme5/new_clones/V/whisker' &
git clone https://github.com/thecodrr/vave '/storage/nvme5/new_clones/V/vave' &
git clone https://github.com/ali-furkan/minesweeper-v '/storage/nvme5/new_clones/V/minesweeper-v' &
git clone https://github.com/nedpals/vargs '/storage/nvme5/new_clones/V/vargs' &
git clone https://github.com/zztkm/vdotenv '/storage/nvme5/new_clones/V/vdotenv' &
git clone https://github.com/vlang/v-llvm '/storage/nvme5/new_clones/V/v-llvm' &
git clone https://github.com/Delta456/monkey_v '/storage/nvme5/new_clones/V/monkey_v' &
git clone https://github.com/veltiosoft/vss '/storage/nvme5/new_clones/V/vss' &
git clone https://github.com/KeyWeeUsr/the-book-of-v '/storage/nvme5/new_clones/V/the-book-of-v' &
git clone https://github.com/alexfrancow/offensive-vlang '/storage/nvme5/new_clones/V/offensive-vlang' &
git clone https://github.com/xiangze/CNN_FPGA '/storage/nvme5/new_clones/V/CNN_FPGA' &
git clone https://github.com/l1mey112/jitcalc '/storage/nvme5/new_clones/V/jitcalc' &
git clone https://github.com/Delta456/range '/storage/nvme5/new_clones/V/range' &
git clone https://github.com/nedpals/v-jsonrpc '/storage/nvme5/new_clones/V/v-jsonrpc' &
git clone https://github.com/prime31/via '/storage/nvme5/new_clones/V/via' &
git clone https://github.com/yue-best-practices/vpm '/storage/nvme5/new_clones/V/vpm' &
git clone https://github.com/vlang/libsodium '/storage/nvme5/new_clones/V/libsodium' &
git clone https://github.com/Waqar144/progressbar '/storage/nvme5/new_clones/V/progressbar' &
git clone https://github.com/scurty-labs/vblog '/storage/nvme5/new_clones/V/vblog' &
git clone https://github.com/RustemB/rosetta-code-v '/storage/nvme5/new_clones/V/rosetta-code-v' &
git clone https://github.com/elliotchance/reflect '/storage/nvme5/new_clones/V/reflect' &
git clone https://github.com/lydiandy/vast '/storage/nvme5/new_clones/V/vast' &
git clone https://github.com/carlosqsilva/vqrcode '/storage/nvme5/new_clones/V/vqrcode' &
git clone https://github.com/russo-2025/papyrus-compiler '/storage/nvme5/new_clones/V/papyrus-compiler' &
git clone https://github.com/nedpals/v-mime '/storage/nvme5/new_clones/V/v-mime' &
git clone https://github.com/jdonnerstag/vlang-yaml '/storage/nvme5/new_clones/V/vlang-yaml' &
git clone https://github.com/jacobsalmela/vsh '/storage/nvme5/new_clones/V/vsh' &
git clone https://github.com/BafS/hn-top '/storage/nvme5/new_clones/V/hn-top' &
git clone https://github.com/larpon/jni '/storage/nvme5/new_clones/V/jni' &
git clone https://github.com/lazalong/V-Hello '/storage/nvme5/new_clones/V/V-Hello' &
git clone https://github.com/spytheman/v2048 '/storage/nvme5/new_clones/V/v2048' &
git clone https://github.com/etienne-napoleone/chalk '/storage/nvme5/new_clones/V/chalk' &
git clone https://github.com/abhra0897/gowin-easy-linux '/storage/nvme5/new_clones/V/gowin-easy-linux' &
git clone https://github.com/endeveit/v-validate '/storage/nvme5/new_clones/V/v-validate' &
git clone https://github.com/EasyHax/Vack '/storage/nvme5/new_clones/V/Vack' &
git clone https://github.com/emily33901/vapor '/storage/nvme5/new_clones/V/vapor' &
git clone https://github.com/gura-conf/vgura '/storage/nvme5/new_clones/V/vgura' &
git clone https://github.com/vlang/msgpack '/storage/nvme5/new_clones/V/msgpack' &
git clone https://github.com/vlang/viscord '/storage/nvme5/new_clones/V/viscord' &
git clone https://github.com/rhygg/spinners '/storage/nvme5/new_clones/V/spinners' &
git clone https://github.com/nsauzede/sdl2test '/storage/nvme5/new_clones/V/sdl2test' &
git clone https://github.com/hungrybluedev/klonol '/storage/nvme5/new_clones/V/klonol' &
git clone https://github.com/cookieforpres/spaceship '/storage/nvme5/new_clones/V/spaceship' &
git clone https://github.com/vlang/vlibc '/storage/nvme5/new_clones/V/vlibc' &
git clone https://github.com/Ekopalypse/EnhanceAnyLexer '/storage/nvme5/new_clones/V/EnhanceAnyLexer' &
git clone https://github.com/medvednikov/v2 '/storage/nvme5/new_clones/V/v2' &
git clone https://github.com/diljith369/OffensiveVLang '/storage/nvme5/new_clones/V/OffensiveVLang' &
git clone https://github.com/0x1CA3/GoAhead-IPCAM-XSS-and-RCE '/storage/nvme5/new_clones/V/GoAhead-IPCAM-XSS-and-RCE' &
git clone https://github.com/jordan-bonecutter/vmq '/storage/nvme5/new_clones/V/vmq' &
git clone https://github.com/end-me/voxel '/storage/nvme5/new_clones/V/voxel' &
git clone https://github.com/sh4rkov1tch/VTik '/storage/nvme5/new_clones/V/VTik' &
git clone https://github.com/ChAoSUnItY/vaker '/storage/nvme5/new_clones/V/vaker' &
git clone https://github.com/jeenyuhs/vesseract '/storage/nvme5/new_clones/V/vesseract' &
git clone https://github.com/louisliuwei/pynq-dpu '/storage/nvme5/new_clones/V/pynq-dpu' &
git clone https://github.com/mohamedLT/V_ecs '/storage/nvme5/new_clones/V/V_ecs' &
git clone https://github.com/lmangani/vLogQL '/storage/nvme5/new_clones/V/vLogQL' &
git clone https://github.com/Delta456/random '/storage/nvme5/new_clones/V/random' &
git clone https://github.com/Jmgr/vsfml '/storage/nvme5/new_clones/V/vsfml' &
git clone https://github.com/svelterust/vom '/storage/nvme5/new_clones/V/vom' &
git clone https://github.com/0xLeif/lol '/storage/nvme5/new_clones/V/lol' &
git clone https://github.com/EasyHax/NerVe '/storage/nvme5/new_clones/V/NerVe' &
git clone https://github.com/mnentwig/forthytwo '/storage/nvme5/new_clones/V/forthytwo' &
git clone https://github.com/pisaiah/verminal '/storage/nvme5/new_clones/V/verminal' &
git clone https://github.com/ergoadams/vii '/storage/nvme5/new_clones/V/vii' &
git clone https://github.com/KaleidoDeer/vlua '/storage/nvme5/new_clones/V/vlua' &
git clone https://github.com/CleverCloud/CleverCloud-exheres '/storage/nvme5/new_clones/V/CleverCloud-exheres' &
git clone https://github.com/Henrixounez/vpng '/storage/nvme5/new_clones/V/vpng' &
git clone https://github.com/aheissenberger/vlang-aws-lambda '/storage/nvme5/new_clones/V/vlang-aws-lambda' &
git clone https://github.com/onyxcode/vish '/storage/nvme5/new_clones/V/vish' &
git clone https://github.com/nedpals/jisoni '/storage/nvme5/new_clones/V/jisoni' &
git clone https://github.com/erdetn/vi2c '/storage/nvme5/new_clones/V/vi2c' &
git clone https://github.com/serkonda7/v-coding-challenges '/storage/nvme5/new_clones/V/v-coding-challenges' &
git clone https://github.com/larpon/earcut '/storage/nvme5/new_clones/V/earcut' &
git clone https://github.com/helto4real/micro_v '/storage/nvme5/new_clones/V/micro_v' &
git clone https://github.com/zenith391/vwxml '/storage/nvme5/new_clones/V/vwxml' &
git clone https://github.com/Blank-c/Blankrypt '/storage/nvme5/new_clones/V/Blankrypt' &
git clone https://github.com/snow-blade/vlite '/storage/nvme5/new_clones/V/vlite' &
git clone https://github.com/thecodrr/vws '/storage/nvme5/new_clones/V/vws' &
git clone https://github.com/v-community/v_rosetta '/storage/nvme5/new_clones/V/v_rosetta' &
git clone https://github.com/ifndev/v-fancy-logs '/storage/nvme5/new_clones/V/v-fancy-logs' &
git clone https://github.com/ArtemkaKun/v-project-basement '/storage/nvme5/new_clones/V/v-project-basement' &
git clone https://github.com/radare/v-r2 '/storage/nvme5/new_clones/V/v-r2' &
git clone https://github.com/exercism/vlang '/storage/nvme5/new_clones/V/vlang' &
git clone https://github.com/mcastorina/viter '/storage/nvme5/new_clones/V/viter' &
git clone https://github.com/islonely/vasteroids '/storage/nvme5/new_clones/V/vasteroids' &
git clone https://github.com/larpon/tipsy '/storage/nvme5/new_clones/V/tipsy' &
git clone https://github.com/emily33901/vlang-net '/storage/nvme5/new_clones/V/vlang-net' &
git clone https://github.com/inxomnyaa/v-pong '/storage/nvme5/new_clones/V/v-pong' &
git clone https://github.com/LouisSchmieder/Flappy-Bird '/storage/nvme5/new_clones/V/Flappy-Bird' &
git clone https://github.com/SheatNoisette/vavr '/storage/nvme5/new_clones/V/vavr' &
git clone https://github.com/Le0Developer/vqoi '/storage/nvme5/new_clones/V/vqoi' &
git clone https://github.com/nzbr/vlogsolv '/storage/nvme5/new_clones/V/vlogsolv' &
git clone https://github.com/erdetn/vserialx '/storage/nvme5/new_clones/V/vserialx' &
git clone https://github.com/mvlootman/aoc2019 '/storage/nvme5/new_clones/V/aoc2019' &
git clone https://github.com/asvvvad1/vlipboard '/storage/nvme5/new_clones/V/vlipboard' &
git clone https://github.com/blacktrub/vmemcached '/storage/nvme5/new_clones/V/vmemcached' &
git clone https://github.com/lydiandy/cjson '/storage/nvme5/new_clones/V/cjson' &
git clone https://github.com/openSUSE-zh/wps-office-appimage '/storage/nvme5/new_clones/V/wps-office-appimage' &
git clone https://github.com/Terisback/treplo '/storage/nvme5/new_clones/V/treplo' &
git clone https://github.com/manen/glfw_v '/storage/nvme5/new_clones/V/glfw_v' &
git clone https://github.com/v-script/vmir '/storage/nvme5/new_clones/V/vmir' &
git clone https://github.com/erdetn/vserialport '/storage/nvme5/new_clones/V/vserialport' &
git clone https://github.com/hungrybluedev/geo '/storage/nvme5/new_clones/V/geo' &
git clone https://github.com/atomkirk/v-playground '/storage/nvme5/new_clones/V/v-playground' &
git clone https://github.com/Trivaxy/vain '/storage/nvme5/new_clones/V/vain' &
git clone https://github.com/vpkgs/slog '/storage/nvme5/new_clones/V/slog' &
git clone https://github.com/mohamedLT/Vroutine '/storage/nvme5/new_clones/V/Vroutine' &
git clone https://github.com/elitru/v-jwt '/storage/nvme5/new_clones/V/v-jwt' &
git clone https://github.com/RGBCube/color.v '/storage/nvme5/new_clones/V/color.v' &
git clone https://github.com/vlang/glfw '/storage/nvme5/new_clones/V/glfw' &
git clone https://github.com/larpon/sgldraw '/storage/nvme5/new_clones/V/sgldraw' &
git clone https://github.com/Henrixounez/v-git '/storage/nvme5/new_clones/V/v-git' &
git clone https://github.com/rcqls/vsvg '/storage/nvme5/new_clones/V/vsvg' &
git clone https://github.com/Lexxrt/vShell '/storage/nvme5/new_clones/V/vShell' &
git clone https://github.com/evowizz/vadb '/storage/nvme5/new_clones/V/vadb' &
git clone https://github.com/manen/gl_v '/storage/nvme5/new_clones/V/gl_v' &
git clone https://github.com/nsauzede/mytstc '/storage/nvme5/new_clones/V/mytstc' &
git clone https://github.com/boonsboos/tvitch '/storage/nvme5/new_clones/V/tvitch' &
git clone https://github.com/apoprotsky/portctl '/storage/nvme5/new_clones/V/portctl' &
git clone https://github.com/nocturlab/vi-v '/storage/nvme5/new_clones/V/vi-v' &
git clone https://github.com/larpon/particle '/storage/nvme5/new_clones/V/particle' &
git clone https://github.com/ArtemkaKun/VlangBenchmarksVisualization '/storage/nvme5/new_clones/V/VlangBenchmarksVisualization' &
git clone https://github.com/alexesprit/colors '/storage/nvme5/new_clones/V/colors' &
git clone https://github.com/watzon/safety '/storage/nvme5/new_clones/V/safety' &
git clone https://github.com/vlang/discord-bot '/storage/nvme5/new_clones/V/discord-bot' &
git clone https://github.com/phoreverpheebs/m3u8v '/storage/nvme5/new_clones/V/m3u8v' &
git clone https://github.com/mvenditto/v-python '/storage/nvme5/new_clones/V/v-python' &
git clone https://github.com/radare/v-toxml '/storage/nvme5/new_clones/V/v-toxml' &
git clone https://github.com/Jictyvoo/v_html '/storage/nvme5/new_clones/V/v_html' &
git clone https://github.com/smartiniOnGitHub/vweb-example '/storage/nvme5/new_clones/V/vweb-example' &
git clone https://github.com/depperm/fast_noise_lite '/storage/nvme5/new_clones/V/fast_noise_lite' &
git clone https://github.com/ken0x0a/v_derive '/storage/nvme5/new_clones/V/v_derive' &
git clone https://github.com/ninive/v-arkadroid '/storage/nvme5/new_clones/V/v-arkadroid' &
git clone https://github.com/carlosqsilva/vfetch '/storage/nvme5/new_clones/V/vfetch' &
git clone https://github.com/nedpals/lsp.v '/storage/nvme5/new_clones/V/lsp.v' &
git clone https://github.com/hungrybluedev/v-htmx-todolist '/storage/nvme5/new_clones/V/v-htmx-todolist' &
git clone https://github.com/trufae/v-asm '/storage/nvme5/new_clones/V/v-asm' &
git clone https://github.com/martinkiefer/Scotch '/storage/nvme5/new_clones/V/Scotch' &
git clone https://github.com/serkonda7/symlinker-v '/storage/nvme5/new_clones/V/symlinker-v' &
git clone https://github.com/shovon/raytracing-vlang '/storage/nvme5/new_clones/V/raytracing-vlang' &
git clone https://github.com/helto4real/websocket '/storage/nvme5/new_clones/V/websocket' &
git clone https://github.com/xelalin/Ultra96v2-DPU '/storage/nvme5/new_clones/V/Ultra96v2-DPU' &
git clone https://github.com/Henrixounez/v-midi '/storage/nvme5/new_clones/V/v-midi' &
git clone https://github.com/invipal/nanoid '/storage/nvme5/new_clones/V/nanoid' &
git clone https://github.com/ntrupin/navmv '/storage/nvme5/new_clones/V/navmv' &
git clone https://github.com/freeflowuniverse/crystallib '/storage/nvme5/new_clones/V/crystallib' &
git clone https://github.com/WolvesFortress/vxbl-oauth '/storage/nvme5/new_clones/V/vxbl-oauth' &
git clone https://github.com/yeboahnanaosei/members-of-parliament '/storage/nvme5/new_clones/V/members-of-parliament' &
git clone https://github.com/xy3/v-password-validator '/storage/nvme5/new_clones/V/v-password-validator' &
git clone https://github.com/CesiumLabs/vcord '/storage/nvme5/new_clones/V/vcord' &
git clone https://github.com/trufae/v-frida '/storage/nvme5/new_clones/V/v-frida' &
git clone https://github.com/malisipi/gezgin-satici '/storage/nvme5/new_clones/V/gezgin-satici' &
git clone https://github.com/vgtk/vgobject '/storage/nvme5/new_clones/V/vgobject' &
git clone https://github.com/vidner/termvin '/storage/nvme5/new_clones/V/termvin' &
git clone https://github.com/penguindark/vviewer '/storage/nvme5/new_clones/V/vviewer' &
git clone https://github.com/trufae/v-filelock '/storage/nvme5/new_clones/V/v-filelock' &
git clone https://github.com/nord501/pe.v '/storage/nvme5/new_clones/V/pe.v' &
git clone https://github.com/organization/VRakLib '/storage/nvme5/new_clones/V/VRakLib' &
git clone https://github.com/Ouri028/vagi '/storage/nvme5/new_clones/V/vagi' &
git clone https://github.com/larpon/chew '/storage/nvme5/new_clones/V/chew' &
git clone https://github.com/MohammadMD1383/verve '/storage/nvme5/new_clones/V/verve' &
git clone https://github.com/Wertzui123/HashMap '/storage/nvme5/new_clones/V/HashMap' &
git clone https://github.com/Alfex4936/V-algorithms '/storage/nvme5/new_clones/V/V-algorithms' &
git clone https://github.com/nsauzede/sokoterm '/storage/nvme5/new_clones/V/sokoterm' &
git clone https://github.com/vmulti/vidi '/storage/nvme5/new_clones/V/vidi' &
git clone https://github.com/l1mey112/tl-v '/storage/nvme5/new_clones/V/tl-v' &
git clone https://github.com/RGBCube/chatgpt.v '/storage/nvme5/new_clones/V/chatgpt.v' &
git clone https://github.com/SheatNoisette/bloomfilter '/storage/nvme5/new_clones/V/bloomfilter' &
git clone https://github.com/AlfieRan/MonoChain '/storage/nvme5/new_clones/V/MonoChain' &
git clone https://github.com/boonsboos/tetrvm '/storage/nvme5/new_clones/V/tetrvm' &
git clone https://github.com/khalyomede/i18n '/storage/nvme5/new_clones/V/i18n' &
git clone https://github.com/ulises-jeremias/rxv '/storage/nvme5/new_clones/V/rxv' &
git clone https://github.com/mehtaarn000/vcurrency '/storage/nvme5/new_clones/V/vcurrency' &
git clone https://github.com/ka-weihe/btree-v '/storage/nvme5/new_clones/V/btree-v' &
git clone https://github.com/medvednikov/vbrew '/storage/nvme5/new_clones/V/vbrew' &
git clone https://github.com/q60/zhenyan '/storage/nvme5/new_clones/V/zhenyan' &
git clone https://github.com/StephaneBunel/v-xbrightness '/storage/nvme5/new_clones/V/v-xbrightness' &
git clone https://github.com/xiusin/very '/storage/nvme5/new_clones/V/very' &
git clone https://github.com/popzxc/vtest '/storage/nvme5/new_clones/V/vtest' &
git clone https://github.com/alexesprit/semver '/storage/nvme5/new_clones/V/semver' &
git clone https://github.com/spytheman/vnew '/storage/nvme5/new_clones/V/vnew' &
git clone https://github.com/nedimf/vmob '/storage/nvme5/new_clones/V/vmob' &
git clone https://github.com/onerbs/vit '/storage/nvme5/new_clones/V/vit' &
git clone https://github.com/fanlia/iconv '/storage/nvme5/new_clones/V/iconv' &
git clone https://github.com/spytheman/veditline '/storage/nvme5/new_clones/V/veditline' &
git clone https://github.com/pisaiah/gui-builder '/storage/nvme5/new_clones/V/gui-builder' &
git clone https://github.com/ninive/v-ecs '/storage/nvme5/new_clones/V/v-ecs' &
git clone https://github.com/SheatNoisette/smalloc-v '/storage/nvme5/new_clones/V/smalloc-v' &
git clone https://github.com/jdonnerstag/vlang-rosie '/storage/nvme5/new_clones/V/vlang-rosie' &
git clone https://github.com/ChristoPy/silk '/storage/nvme5/new_clones/V/silk' &
git clone https://github.com/hanabi1224/vlang-big-integer '/storage/nvme5/new_clones/V/vlang-big-integer' &
git clone https://github.com/crthpl/os-idea '/storage/nvme5/new_clones/V/os-idea' &
git clone https://github.com/trufae/v-objc '/storage/nvme5/new_clones/V/v-objc' &
git clone https://github.com/Leiyks/openapi '/storage/nvme5/new_clones/V/openapi' &
git clone https://github.com/ArtemkaKun/text-processing '/storage/nvme5/new_clones/V/text-processing' &
git clone https://github.com/Skrillec-Security/Skrillec-Botnet '/storage/nvme5/new_clones/V/Skrillec-Botnet' &
git clone https://github.com/Chank1e/mongov '/storage/nvme5/new_clones/V/mongov' &
git clone https://github.com/alii/alissembly '/storage/nvme5/new_clones/V/alissembly' &
git clone https://github.com/ninive/v_quadtree '/storage/nvme5/new_clones/V/v_quadtree' &
git clone https://github.com/lemoncmd/VikanOS '/storage/nvme5/new_clones/V/VikanOS' &
git clone https://github.com/chipnetics/pval '/storage/nvme5/new_clones/V/pval' &
git clone https://github.com/rcqls/uicomponent '/storage/nvme5/new_clones/V/uicomponent' &
git clone https://github.com/radare/v-r2pipe '/storage/nvme5/new_clones/V/v-r2pipe' &
git clone https://github.com/nevrome/vconrand '/storage/nvme5/new_clones/V/vconrand' &
git clone https://github.com/watzon/vnntp '/storage/nvme5/new_clones/V/vnntp' &
git clone https://github.com/srackham/pcre2 '/storage/nvme5/new_clones/V/pcre2' &
git clone https://github.com/vmulti/audio '/storage/nvme5/new_clones/V/audio' &
git clone https://github.com/Iaiao/jsonmap '/storage/nvme5/new_clones/V/jsonmap' &
git clone https://github.com/Wertzui123/ehttp '/storage/nvme5/new_clones/V/ehttp' &
git clone https://github.com/mohamedLT/vraylib '/storage/nvme5/new_clones/V/vraylib' &
git clone https://github.com/ZeroX-DG/vudoku '/storage/nvme5/new_clones/V/vudoku' &
git clone https://github.com/rymaju/v-lisp '/storage/nvme5/new_clones/V/v-lisp' &
git clone https://github.com/jasperalani/expression-evaluator '/storage/nvme5/new_clones/V/expression-evaluator' &
git clone https://github.com/Henrixounez/v-lisp '/storage/nvme5/new_clones/V/v-lisp' &
