#!/bin/bash

git clone https://github.com/linuxmint/timeshift '/storage/nvme5/new_clones/Vala/timeshift' &
git clone https://github.com/fossasia/lxlauncher-vala '/storage/nvme5/new_clones/Vala/lxlauncher-vala' &
git clone https://github.com/p-e-w/plotinus '/storage/nvme5/new_clones/Vala/plotinus' &
git clone https://github.com/Sweets/tiramisu '/storage/nvme5/new_clones/Vala/tiramisu' &
git clone https://github.com/frida/frida-core '/storage/nvme5/new_clones/Vala/frida-core' &
git clone https://github.com/johanmattssonm/birdfont '/storage/nvme5/new_clones/Vala/birdfont' &
git clone https://github.com/GNOME/geary '/storage/nvme5/new_clones/Vala/geary' &
git clone https://github.com/eyelash/xi-gtk '/storage/nvme5/new_clones/Vala/xi-gtk' &
git clone https://github.com/tiliado/nuvolaplayer '/storage/nvme5/new_clones/Vala/nuvolaplayer' &
git clone https://github.com/ensemblesaw/ensembles-app '/storage/nvme5/new_clones/Vala/ensembles-app' &
git clone https://github.com/Schneegans/Gnome-Pie '/storage/nvme5/new_clones/Vala/Gnome-Pie' &
git clone https://github.com/voldyman/MarkMyWords '/storage/nvme5/new_clones/Vala/MarkMyWords' &
git clone https://github.com/GNOME/shotwell '/storage/nvme5/new_clones/Vala/shotwell' &
git clone https://github.com/radare/tiv '/storage/nvme5/new_clones/Vala/tiv' &
git clone https://github.com/GNOME/gnome-boxes '/storage/nvme5/new_clones/Vala/gnome-boxes' &
git clone https://github.com/vikoadi/indicator-kdeconnect '/storage/nvme5/new_clones/Vala/indicator-kdeconnect' &
git clone https://github.com/artemanufrij/playmymusic '/storage/nvme5/new_clones/Vala/playmymusic' &
git clone https://github.com/muriloventuroso/pdftricks '/storage/nvme5/new_clones/Vala/pdftricks' &
git clone https://github.com/poinck/lampe '/storage/nvme5/new_clones/Vala/lampe' &
git clone https://github.com/regolith-linux/ilia '/storage/nvme5/new_clones/Vala/ilia' &
git clone https://github.com/PlugaruT/wingpanel-indicator-sys-monitor '/storage/nvme5/new_clones/Vala/wingpanel-indicator-sys-monitor' &
git clone https://github.com/lxde/lxsession '/storage/nvme5/new_clones/Vala/lxsession' &
git clone https://github.com/GijsGoudzwaard/Image-Optimizer '/storage/nvme5/new_clones/Vala/Image-Optimizer' &
git clone https://github.com/artemanufrij/webpin '/storage/nvme5/new_clones/Vala/webpin' &
git clone https://github.com/elework/Spreadsheet '/storage/nvme5/new_clones/Vala/Spreadsheet' &
git clone https://github.com/lcallarec/live-chart '/storage/nvme5/new_clones/Vala/live-chart' &
git clone https://github.com/gerito1/vala-gtk-examples '/storage/nvme5/new_clones/Vala/vala-gtk-examples' &
git clone https://github.com/TiZ-HugLife/xfce4-dockbarx-plugin '/storage/nvme5/new_clones/Vala/xfce4-dockbarx-plugin' &
git clone https://github.com/muriloventuroso/givemelyrics '/storage/nvme5/new_clones/Vala/givemelyrics' &
git clone https://github.com/dcharles525/Caroline '/storage/nvme5/new_clones/Vala/Caroline' &
git clone https://github.com/SkyzohKey/Konv '/storage/nvme5/new_clones/Vala/Konv' &
git clone https://github.com/zesterer/vulcan '/storage/nvme5/new_clones/Vala/vulcan' &
git clone https://github.com/artemanufrij/imageburner '/storage/nvme5/new_clones/Vala/imageburner' &
git clone https://github.com/apmasell/vapis '/storage/nvme5/new_clones/Vala/vapis' &
git clone https://github.com/nemequ/vala-extra-vapis '/storage/nvme5/new_clones/Vala/vala-extra-vapis' &
git clone https://github.com/atheriel/snapshot-explorer '/storage/nvme5/new_clones/Vala/snapshot-explorer' &
git clone https://github.com/erik/valatra '/storage/nvme5/new_clones/Vala/valatra' &
git clone https://github.com/artemanufrij/regextester '/storage/nvme5/new_clones/Vala/regextester' &
git clone https://github.com/Philip-Scott/wallpaperize '/storage/nvme5/new_clones/Vala/wallpaperize' &
git clone https://github.com/vamega/The-Vala-Guide '/storage/nvme5/new_clones/Vala/The-Vala-Guide' &
git clone https://github.com/elementary/wingpanel-indicator-sound '/storage/nvme5/new_clones/Vala/wingpanel-indicator-sound' &
git clone https://github.com/dontsueme/shtpl '/storage/nvme5/new_clones/Vala/shtpl' &
git clone https://github.com/AmbitionFramework/ambition '/storage/nvme5/new_clones/Vala/ambition' &
git clone https://github.com/artemanufrij/screencast '/storage/nvme5/new_clones/Vala/screencast' &
git clone https://github.com/phastmike/vala-circular-progress-bar '/storage/nvme5/new_clones/Vala/vala-circular-progress-bar' &
git clone https://github.com/nick92/tranqil '/storage/nvme5/new_clones/Vala/tranqil' &
git clone https://github.com/flobrosch/valadoc-org '/storage/nvme5/new_clones/Vala/valadoc-org' &
git clone https://github.com/elementary/app-template '/storage/nvme5/new_clones/Vala/app-template' &
git clone https://github.com/ev3dev/brickman '/storage/nvme5/new_clones/Vala/brickman' &
git clone https://github.com/kjlaw89/draw '/storage/nvme5/new_clones/Vala/draw' &
git clone https://github.com/koyuspace/fossil '/storage/nvme5/new_clones/Vala/fossil' &
git clone https://github.com/BuddiesOfBudgie/budgie-desktop-view '/storage/nvme5/new_clones/Vala/budgie-desktop-view' &
git clone https://github.com/nemequ/vala-girs '/storage/nvme5/new_clones/Vala/vala-girs' &
git clone https://github.com/artemanufrij/playmyvideos '/storage/nvme5/new_clones/Vala/playmyvideos' &
git clone https://github.com/Nine-H/apollo11 '/storage/nvme5/new_clones/Vala/apollo11' &
git clone https://github.com/RidgeRun/gstd '/storage/nvme5/new_clones/Vala/gstd' &
git clone https://github.com/sdl2-vapi/sdl2-vapi '/storage/nvme5/new_clones/Vala/sdl2-vapi' &
git clone https://github.com/radare/radare2-capstone '/storage/nvme5/new_clones/Vala/radare2-capstone' &
git clone https://github.com/lucabrunox/gtkhah '/storage/nvme5/new_clones/Vala/gtkhah' &
git clone https://github.com/Maia-Everett/valagl '/storage/nvme5/new_clones/Vala/valagl' &
git clone https://github.com/benwaffle/pulse-flow '/storage/nvme5/new_clones/Vala/pulse-flow' &
git clone https://github.com/technosophos/ValaXdebugTools '/storage/nvme5/new_clones/Vala/ValaXdebugTools' &
git clone https://github.com/antono/synapse '/storage/nvme5/new_clones/Vala/synapse' &
git clone https://github.com/elementary/wingpanel-indicator-session '/storage/nvme5/new_clones/Vala/wingpanel-indicator-session' &
git clone https://github.com/artemanufrij/graphui '/storage/nvme5/new_clones/Vala/graphui' &
git clone https://github.com/Miqueas/TapeDeck '/storage/nvme5/new_clones/Vala/TapeDeck' &
git clone https://github.com/p12tic/awn-extras '/storage/nvme5/new_clones/Vala/awn-extras' &
git clone https://github.com/tkowalewski/harvest-gtk '/storage/nvme5/new_clones/Vala/harvest-gtk' &
git clone https://github.com/milohr/babe-music-player '/storage/nvme5/new_clones/Vala/babe-music-player' &
git clone https://github.com/Apress/introducing-vala-programming '/storage/nvme5/new_clones/Vala/introducing-vala-programming' &
git clone https://github.com/apmasell/tabbedmux '/storage/nvme5/new_clones/Vala/tabbedmux' &
git clone https://github.com/abenga/valagtk3tutorial '/storage/nvme5/new_clones/Vala/valagtk3tutorial' &
git clone https://github.com/mickeyl/introduction-to-vala '/storage/nvme5/new_clones/Vala/introduction-to-vala' &
git clone https://github.com/ev3dev/ev3devKit '/storage/nvme5/new_clones/Vala/ev3devKit' &
git clone https://github.com/PerfectCarl/vala-stacktrace '/storage/nvme5/new_clones/Vala/vala-stacktrace' &
git clone https://github.com/databasefx/ldbfx '/storage/nvme5/new_clones/Vala/ldbfx' &
git clone https://github.com/roymckenzie/gnome-builder-vala-granite-boilerplate '/storage/nvme5/new_clones/Vala/gnome-builder-vala-granite-boilerplate' &
git clone https://github.com/moson-mo/cryptor '/storage/nvme5/new_clones/Vala/cryptor' &
git clone https://github.com/avalanche-games/avalanche '/storage/nvme5/new_clones/Vala/avalanche' &
git clone https://github.com/GNOME/vala-extra-vapis '/storage/nvme5/new_clones/Vala/vala-extra-vapis' &
git clone https://github.com/RapidFingers/Translator '/storage/nvme5/new_clones/Vala/Translator' &
git clone https://github.com/phastmike/tags '/storage/nvme5/new_clones/Vala/tags' &
git clone https://github.com/naipotato/gtk-mvvm-sample '/storage/nvme5/new_clones/Vala/gtk-mvvm-sample' &
git clone https://github.com/rschroll/webkitdom '/storage/nvme5/new_clones/Vala/webkitdom' &
git clone https://github.com/lxmcf/raylib-vapi '/storage/nvme5/new_clones/Vala/raylib-vapi' &
git clone https://github.com/smx-smx/openSage '/storage/nvme5/new_clones/Vala/openSage' &
git clone https://github.com/serge1peshcoff/photostream '/storage/nvme5/new_clones/Vala/photostream' &
git clone https://github.com/ferhatgec/prism '/storage/nvme5/new_clones/Vala/prism' &
git clone https://github.com/artemanufrij/metronome '/storage/nvme5/new_clones/Vala/metronome' &
git clone https://github.com/phastmike/vala-design-patterns-for-humans '/storage/nvme5/new_clones/Vala/vala-design-patterns-for-humans' &
git clone https://github.com/nmelnick/Log4Vala '/storage/nvme5/new_clones/Vala/Log4Vala' &
git clone https://github.com/ThiefMD/theme-generator '/storage/nvme5/new_clones/Vala/theme-generator' &
git clone https://github.com/lcallarec/dockery '/storage/nvme5/new_clones/Vala/dockery' &
git clone https://github.com/vanat/vanat '/storage/nvme5/new_clones/Vala/vanat' &
git clone https://github.com/luqmana/ValaMediaPlayer '/storage/nvme5/new_clones/Vala/ValaMediaPlayer' &
git clone https://github.com/emrevit/vala-http '/storage/nvme5/new_clones/Vala/vala-http' &
git clone https://github.com/albert-tomanek/tflite-demo '/storage/nvme5/new_clones/Vala/tflite-demo' &
git clone https://github.com/artemanufrij/hashit '/storage/nvme5/new_clones/Vala/hashit' &
git clone https://github.com/artemanufrij/showmypictures '/storage/nvme5/new_clones/Vala/showmypictures' &
git clone https://github.com/tiliado/valacef '/storage/nvme5/new_clones/Vala/valacef' &
git clone https://github.com/robinhellen/diva '/storage/nvme5/new_clones/Vala/diva' &
git clone https://github.com/elementary/wingpanel-indicator-privacy '/storage/nvme5/new_clones/Vala/wingpanel-indicator-privacy' &
git clone https://github.com/aarnt/alpm_octopi_utils '/storage/nvme5/new_clones/Vala/alpm_octopi_utils' &
git clone https://github.com/codecov/example-vala '/storage/nvme5/new_clones/Vala/example-vala' &
git clone https://github.com/refi64/isolatekit '/storage/nvme5/new_clones/Vala/isolatekit' &
git clone https://github.com/abiosoft/launchar '/storage/nvme5/new_clones/Vala/launchar' &
git clone https://github.com/I-hate-farms/ivy '/storage/nvme5/new_clones/Vala/ivy' &
git clone https://github.com/ThiefMD/libwritegood-vala '/storage/nvme5/new_clones/Vala/libwritegood-vala' &
git clone https://github.com/voldyman/plugin-app '/storage/nvme5/new_clones/Vala/plugin-app' &
git clone https://github.com/rainwoodman/vast '/storage/nvme5/new_clones/Vala/vast' &
git clone https://github.com/lcallarec/united '/storage/nvme5/new_clones/Vala/united' &
git clone https://github.com/jakobwesthoff/pdf2svg '/storage/nvme5/new_clones/Vala/pdf2svg' &
git clone https://github.com/artemanufrij/trimdown '/storage/nvme5/new_clones/Vala/trimdown' &
git clone https://github.com/tkashkin/Boiler '/storage/nvme5/new_clones/Vala/Boiler' &
git clone https://github.com/bbuhler/HostsManager '/storage/nvme5/new_clones/Vala/HostsManager' &
git clone https://github.com/sapoturge/froggum '/storage/nvme5/new_clones/Vala/froggum' &
git clone https://github.com/davidmhewitt/vala-cycle-detector '/storage/nvme5/new_clones/Vala/vala-cycle-detector' &
git clone https://github.com/bitwalk123/vala-samples '/storage/nvme5/new_clones/Vala/vala-samples' &
git clone https://github.com/rainwoodman/libyaml-glib '/storage/nvme5/new_clones/Vala/libyaml-glib' &
git clone https://github.com/spaetz/vala-notmuch '/storage/nvme5/new_clones/Vala/vala-notmuch' &
git clone https://github.com/DaveDavenport/squishybox '/storage/nvme5/new_clones/Vala/squishybox' &
git clone https://github.com/moson-mo/matray '/storage/nvme5/new_clones/Vala/matray' &
git clone https://github.com/basjam/ValaCompiler '/storage/nvme5/new_clones/Vala/ValaCompiler' &
git clone https://github.com/donadigo/gala-plank-preview-plugin '/storage/nvme5/new_clones/Vala/gala-plank-preview-plugin' &
git clone https://github.com/war1025/gmailnotify '/storage/nvme5/new_clones/Vala/gmailnotify' &
git clone https://github.com/artemanufrij/translit '/storage/nvme5/new_clones/Vala/translit' &
git clone https://github.com/himanshugoel2797/ValaOnWindows-Binaries '/storage/nvme5/new_clones/Vala/ValaOnWindows-Binaries' &
git clone https://github.com/benwaffle/vala-starter '/storage/nvme5/new_clones/Vala/vala-starter' &
git clone https://github.com/VerbalExpressions/ValaVerbalExpressions '/storage/nvme5/new_clones/Vala/ValaVerbalExpressions' &
git clone https://github.com/SpikedPaladin/TelegramGLib '/storage/nvme5/new_clones/Vala/TelegramGLib' &
git clone https://github.com/rastersoft/terminus '/storage/nvme5/new_clones/Vala/terminus' &
git clone https://github.com/jbuchbinder/sugarsync-linux '/storage/nvme5/new_clones/Vala/sugarsync-linux' &
git clone https://github.com/fourdollars/alphabbs '/storage/nvme5/new_clones/Vala/alphabbs' &
git clone https://github.com/naaando/wingpanel-indicator-pomodoro '/storage/nvme5/new_clones/Vala/wingpanel-indicator-pomodoro' &
git clone https://github.com/TiZ-HugLife/xfce4-namebar-plugin '/storage/nvme5/new_clones/Vala/xfce4-namebar-plugin' &
git clone https://github.com/poppa/PlayStation '/storage/nvme5/new_clones/Vala/PlayStation' &
git clone https://github.com/Abraca/Abraca '/storage/nvme5/new_clones/Vala/Abraca' &
git clone https://github.com/ferhatgec/codefad '/storage/nvme5/new_clones/Vala/codefad' &
git clone https://github.com/davidmhewitt/vala-language-server '/storage/nvme5/new_clones/Vala/vala-language-server' &
git clone https://github.com/nmelnick/gredis '/storage/nvme5/new_clones/Vala/gredis' &
git clone https://github.com/Wolf2789/ROCCAT-SuoraFX-Effects-Animator '/storage/nvme5/new_clones/Vala/ROCCAT-SuoraFX-Effects-Animator' &
git clone https://github.com/oleavr/process-inspector '/storage/nvme5/new_clones/Vala/process-inspector' &
git clone https://github.com/PerfectCarl/elementary-uncrustify '/storage/nvme5/new_clones/Vala/elementary-uncrustify' &
git clone https://github.com/kucaahbe/ncurses.vala '/storage/nvme5/new_clones/Vala/ncurses.vala' &
git clone https://github.com/AmbitionFramework/almanna '/storage/nvme5/new_clones/Vala/almanna' &
git clone https://github.com/voldyman/GistIt '/storage/nvme5/new_clones/Vala/GistIt' &
git clone https://github.com/artemanufrij/findfileconflicts '/storage/nvme5/new_clones/Vala/findfileconflicts' &
git clone https://github.com/fabiand/gst-plugins-cl '/storage/nvme5/new_clones/Vala/gst-plugins-cl' &
git clone https://github.com/aeldemery/gtk4_dnd '/storage/nvme5/new_clones/Vala/gtk4_dnd' &
git clone https://github.com/bynect/mongo-vapi '/storage/nvme5/new_clones/Vala/mongo-vapi' &
git clone https://github.com/sinticbolivia/DesktopFramework '/storage/nvme5/new_clones/Vala/DesktopFramework' &
git clone https://github.com/radareorg/ragui '/storage/nvme5/new_clones/Vala/ragui' &
git clone https://github.com/nova-reta-vortaro/nrv-gtk '/storage/nvme5/new_clones/Vala/nrv-gtk' &
git clone https://github.com/johanmattssonm/xmlbird '/storage/nvme5/new_clones/Vala/xmlbird' &
git clone https://github.com/arteymix/sentry-glib '/storage/nvme5/new_clones/Vala/sentry-glib' &
git clone https://github.com/unyieldinggrace/EasyJSON '/storage/nvme5/new_clones/Vala/EasyJSON' &
git clone https://github.com/nemequ/bump '/storage/nvme5/new_clones/Vala/bump' &
git clone https://github.com/unixpickle/plop '/storage/nvme5/new_clones/Vala/plop' &
git clone https://github.com/cxw42/pfft '/storage/nvme5/new_clones/Vala/pfft' &
git clone https://github.com/nao1215/libvalacore '/storage/nvme5/new_clones/Vala/libvalacore' &
git clone https://github.com/mikesmullin/Vala-Genie-OpenGL '/storage/nvme5/new_clones/Vala/Vala-Genie-OpenGL' &
git clone https://github.com/aeldemery/gtk4_shadertoy '/storage/nvme5/new_clones/Vala/gtk4_shadertoy' &
git clone https://github.com/eminfedar/simple-todo '/storage/nvme5/new_clones/Vala/simple-todo' &
git clone https://github.com/krishenriksen/ThemeTwister '/storage/nvme5/new_clones/Vala/ThemeTwister' &
git clone https://github.com/guillaumev/piwigoshotwell '/storage/nvme5/new_clones/Vala/piwigoshotwell' &
git clone https://github.com/valum-framework/vsgi '/storage/nvme5/new_clones/Vala/vsgi' &
git clone https://github.com/arrufat/tensorflow-vala '/storage/nvme5/new_clones/Vala/tensorflow-vala' &
git clone https://github.com/aissat/Jaa '/storage/nvme5/new_clones/Vala/Jaa' &
git clone https://github.com/tiliado/diorite '/storage/nvme5/new_clones/Vala/diorite' &
git clone https://github.com/ferhatgec/monifor '/storage/nvme5/new_clones/Vala/monifor' &
git clone https://github.com/alainm23/RetroByte '/storage/nvme5/new_clones/Vala/RetroByte' &
git clone https://github.com/SYNACKtra/OneRootkit '/storage/nvme5/new_clones/Vala/OneRootkit' &
