#!/bin/bash

git clone https://github.com/mdsecactivebreach/SharpShooter '/storage/nvme5/new_clones/VBA/SharpShooter' &
git clone https://github.com/ivankokan/Excel2LaTeX '/storage/nvme5/new_clones/VBA/Excel2LaTeX' &
git clone https://github.com/S3cur3Th1sSh1t/OffensiveVBA '/storage/nvme5/new_clones/VBA/OffensiveVBA' &
git clone https://github.com/Jonathan-LeRoux/IguanaTex '/storage/nvme5/new_clones/VBA/IguanaTex' &
git clone https://github.com/itm4n/VBA-RunPE '/storage/nvme5/new_clones/VBA/VBA-RunPE' &
git clone https://github.com/bluetata/concise-excel-vba '/storage/nvme5/new_clones/VBA/concise-excel-vba' &
git clone https://github.com/hilkoc/vbaDeveloper '/storage/nvme5/new_clones/VBA/vbaDeveloper' &
git clone https://github.com/AllenMattson/VBA '/storage/nvme5/new_clones/VBA/VBA' &
git clone https://github.com/fabiogjardim/bigdata_docker '/storage/nvme5/new_clones/VBA/bigdata_docker' &
git clone https://github.com/tristancalderbank/excel-messenger '/storage/nvme5/new_clones/VBA/excel-messenger' &
git clone https://github.com/VBA-tools/VBA-Dictionary '/storage/nvme5/new_clones/VBA/VBA-Dictionary' &
git clone https://github.com/RelaxTools/RelaxTools-Addin '/storage/nvme5/new_clones/VBA/RelaxTools-Addin' &
git clone https://github.com/maxonthegit/PPspliT '/storage/nvme5/new_clones/VBA/PPspliT' &
git clone https://github.com/sancarn/stdVBA '/storage/nvme5/new_clones/VBA/stdVBA' &
git clone https://github.com/iappyx/Instrumenta '/storage/nvme5/new_clones/VBA/Instrumenta' &
git clone https://github.com/vbaidiot/ariawase '/storage/nvme5/new_clones/VBA/ariawase' &
git clone https://github.com/DylanTallchiefGit/xlStudio '/storage/nvme5/new_clones/VBA/xlStudio' &
git clone https://github.com/kjnh10/ExcelLikeVim '/storage/nvme5/new_clones/VBA/ExcelLikeVim' &
git clone https://github.com/joyfullservice/msaccess-vcs-addin '/storage/nvme5/new_clones/VBA/msaccess-vcs-addin' &
git clone https://github.com/xarial/codestack '/storage/nvme5/new_clones/VBA/codestack' &
git clone https://github.com/VBA-tools/vba-test '/storage/nvme5/new_clones/VBA/vba-test' &
git clone https://github.com/xiaolai/slidology-from-xiaolai '/storage/nvme5/new_clones/VBA/slidology-from-xiaolai' &
git clone https://github.com/jph00/latex-ppt '/storage/nvme5/new_clones/VBA/latex-ppt' &
git clone https://github.com/CNCKitchen/ExtrusionSystemBenchmark '/storage/nvme5/new_clones/VBA/ExtrusionSystemBenchmark' &
git clone https://github.com/krijnsent/crypto_vba '/storage/nvme5/new_clones/VBA/crypto_vba' &
git clone https://github.com/Adepts-Of-0xCC/VBA-macro-experiments '/storage/nvme5/new_clones/VBA/VBA-macro-experiments' &
git clone https://github.com/jpimbert/VBAToolKit '/storage/nvme5/new_clones/VBA/VBAToolKit' &
git clone https://github.com/Vitosh/VBA_personal '/storage/nvme5/new_clones/VBA/VBA_personal' &
git clone https://github.com/med0x2e/vba2clr '/storage/nvme5/new_clones/VBA/vba2clr' &
git clone https://github.com/DaviesGit/office_handwriting '/storage/nvme5/new_clones/VBA/office_handwriting' &
git clone https://github.com/BC-SECURITY/Offensive-VBA-and-XLS-Entanglement '/storage/nvme5/new_clones/VBA/Offensive-VBA-and-XLS-Entanglement' &
git clone https://github.com/spences10/VBA-IDE-Code-Export '/storage/nvme5/new_clones/VBA/VBA-IDE-Code-Export' &
git clone https://github.com/smbx/smbx-legacy-source '/storage/nvme5/new_clones/VBA/smbx-legacy-source' &
git clone https://github.com/ImtsSrl/KUKAVARPROXY '/storage/nvme5/new_clones/VBA/KUKAVARPROXY' &
git clone https://github.com/JohnWoodman/VBA-Macro-Reverse-Shell '/storage/nvme5/new_clones/VBA/VBA-Macro-Reverse-Shell' &
git clone https://github.com/pyscripter/XLRisk '/storage/nvme5/new_clones/VBA/XLRisk' &
git clone https://github.com/Senipah/VBA-Better-Array '/storage/nvme5/new_clones/VBA/VBA-Better-Array' &
git clone https://github.com/JohnWoodman/VBA-Macro-Projects '/storage/nvme5/new_clones/VBA/VBA-Macro-Projects' &
git clone https://github.com/vbatools/MacroToolsVBA '/storage/nvme5/new_clones/VBA/MacroToolsVBA' &
git clone https://github.com/rmdavy/HeapsOfFun '/storage/nvme5/new_clones/VBA/HeapsOfFun' &
git clone https://github.com/S3cur3Th1sSh1t/Excel-Phish '/storage/nvme5/new_clones/VBA/Excel-Phish' &
git clone https://github.com/x-vba/xlib '/storage/nvme5/new_clones/VBA/xlib' &
git clone https://github.com/stu-bell/ExcelDarkMode '/storage/nvme5/new_clones/VBA/ExcelDarkMode' &
git clone https://github.com/yas78/QRCodeLibVBA '/storage/nvme5/new_clones/VBA/QRCodeLibVBA' &
git clone https://github.com/GCuser99/SeleniumVBA '/storage/nvme5/new_clones/VBA/SeleniumVBA' &
git clone https://github.com/cristianbuse/VBA-FileTools '/storage/nvme5/new_clones/VBA/VBA-FileTools' &
git clone https://github.com/brucemcpherson/VbaGit '/storage/nvme5/new_clones/VBA/VbaGit' &
git clone https://github.com/rubberduck-vba/Battleship '/storage/nvme5/new_clones/VBA/Battleship' &
git clone https://github.com/RisalNasar/Excel-Macro-VBA-Library '/storage/nvme5/new_clones/VBA/Excel-Macro-VBA-Library' &
git clone https://github.com/tbr/bjontegaard_etro '/storage/nvme5/new_clones/VBA/bjontegaard_etro' &
git clone https://github.com/Snowflake-Labs/Excelerator '/storage/nvme5/new_clones/VBA/Excelerator' &
git clone https://github.com/andreafortuna/VBAIPFunctions '/storage/nvme5/new_clones/VBA/VBAIPFunctions' &
git clone https://github.com/cristianbuse/VBA-UserForm-MouseScroll '/storage/nvme5/new_clones/VBA/VBA-UserForm-MouseScroll' &
git clone https://github.com/IvanBond/Power-Refresh '/storage/nvme5/new_clones/VBA/Power-Refresh' &
git clone https://github.com/todar/VBA-Arrays '/storage/nvme5/new_clones/VBA/VBA-Arrays' &
git clone https://github.com/sha5010/vim.xlam '/storage/nvme5/new_clones/VBA/vim.xlam' &
git clone https://github.com/Beakerboy/VBA-SQL-Library '/storage/nvme5/new_clones/VBA/VBA-SQL-Library' &
git clone https://github.com/JWock82/xlFrame '/storage/nvme5/new_clones/VBA/xlFrame' &
git clone https://github.com/nathanhere/Excel-VBA-Data-Functions '/storage/nvme5/new_clones/VBA/Excel-VBA-Data-Functions' &
git clone https://github.com/DISREL/Ring0VBA '/storage/nvme5/new_clones/VBA/Ring0VBA' &
git clone https://github.com/scottzhang/AKStreamDocker '/storage/nvme5/new_clones/VBA/AKStreamDocker' &
git clone https://github.com/yhpong/Scientific-Toolkit '/storage/nvme5/new_clones/VBA/Scientific-Toolkit' &
git clone https://github.com/xraymemory/bookstory-en '/storage/nvme5/new_clones/VBA/bookstory-en' &
git clone https://github.com/PerditionC/VBAChromeDevProtocol '/storage/nvme5/new_clones/VBA/VBAChromeDevProtocol' &
git clone https://github.com/nilsding/wordle97 '/storage/nvme5/new_clones/VBA/wordle97' &
git clone https://github.com/PGS62/JuliaExcel.jl '/storage/nvme5/new_clones/VBA/JuliaExcel.jl' &
git clone https://github.com/uezo/TinySeleniumVBA '/storage/nvme5/new_clones/VBA/TinySeleniumVBA' &
git clone https://github.com/rubberduck-vba/MVVM '/storage/nvme5/new_clones/VBA/MVVM' &
git clone https://github.com/leveryd/vulndocker '/storage/nvme5/new_clones/VBA/vulndocker' &
git clone https://github.com/ViperSRT3g/VBA-General '/storage/nvme5/new_clones/VBA/VBA-General' &
git clone https://github.com/hongwenjun/corelvba '/storage/nvme5/new_clones/VBA/corelvba' &
git clone https://github.com/rubberduck-vba/examples '/storage/nvme5/new_clones/VBA/examples' &
git clone https://github.com/xarial/cad-plus '/storage/nvme5/new_clones/VBA/cad-plus' &
git clone https://github.com/vba-blocks/vba-blocks '/storage/nvme5/new_clones/VBA/vba-blocks' &
git clone https://github.com/lee-soft/ViDock '/storage/nvme5/new_clones/VBA/ViDock' &
git clone https://github.com/tdjastrzebski/Vincenty-Excel '/storage/nvme5/new_clones/VBA/Vincenty-Excel' &
git clone https://github.com/brucemcpherson/GoingGas '/storage/nvme5/new_clones/VBA/GoingGas' &
git clone https://github.com/sanand0/geocode-excel '/storage/nvme5/new_clones/VBA/geocode-excel' &
git clone https://github.com/Ruimusume/PMSV '/storage/nvme5/new_clones/VBA/PMSV' &
git clone https://github.com/irBags/Project-P3OL-compatible-software '/storage/nvme5/new_clones/VBA/Project-P3OL-compatible-software' &
git clone https://github.com/spences10/pacellman '/storage/nvme5/new_clones/VBA/pacellman' &
git clone https://github.com/Serialcomms/Serial-Ports-in-VBA-new-for-2022 '/storage/nvme5/new_clones/VBA/Serial-Ports-in-VBA-new-for-2022' &
git clone https://github.com/cristianbuse/VBA-MemoryTools '/storage/nvme5/new_clones/VBA/VBA-MemoryTools' &
git clone https://github.com/cavo789/vba_excel_sql '/storage/nvme5/new_clones/VBA/vba_excel_sql' &
git clone https://github.com/austinleedavis/VBA-utilities '/storage/nvme5/new_clones/VBA/VBA-utilities' &
git clone https://github.com/pdftables/vba-pdftables-api '/storage/nvme5/new_clones/VBA/vba-pdftables-api' &
git clone https://github.com/LJI-Bioinformatics/Excel-Reverse-Complement '/storage/nvme5/new_clones/VBA/Excel-Reverse-Complement' &
git clone https://github.com/Wittline/apache-spark-docker '/storage/nvme5/new_clones/VBA/apache-spark-docker' &
git clone https://github.com/thetrik/VbTrickThreading '/storage/nvme5/new_clones/VBA/VbTrickThreading' &
git clone https://github.com/shapiromatron/funcVBA '/storage/nvme5/new_clones/VBA/funcVBA' &
git clone https://github.com/mabentwickeltsich/MendeleyMacros '/storage/nvme5/new_clones/VBA/MendeleyMacros' &
git clone https://github.com/2MinhetNguyles/Chaturbate-Recorder-GUI '/storage/nvme5/new_clones/VBA/Chaturbate-Recorder-GUI' &
git clone https://github.com/TypeInBooks/books '/storage/nvme5/new_clones/VBA/books' &
git clone https://github.com/ReneNyffenegger/WinAPI-4-VBA '/storage/nvme5/new_clones/VBA/WinAPI-4-VBA' &
git clone https://github.com/tdowd/excel-geocoder '/storage/nvme5/new_clones/VBA/excel-geocoder' &
git clone https://github.com/rmdavy/AMSI_Ordinal_Bypass '/storage/nvme5/new_clones/VBA/AMSI_Ordinal_Bypass' &
git clone https://github.com/bskinn/excel-csvexporter '/storage/nvme5/new_clones/VBA/excel-csvexporter' &
git clone https://github.com/kellyethridge/SimplyVBUnit '/storage/nvme5/new_clones/VBA/SimplyVBUnit' &
git clone https://github.com/strathausen/qtrek.bas '/storage/nvme5/new_clones/VBA/qtrek.bas' &
git clone https://github.com/serkonda7/vscode-vba '/storage/nvme5/new_clones/VBA/vscode-vba' &
git clone https://github.com/team-moeller/better-access-charts '/storage/nvme5/new_clones/VBA/better-access-charts' &
git clone https://github.com/glinares/VBA-Stendhal '/storage/nvme5/new_clones/VBA/VBA-Stendhal' &
git clone https://github.com/lee-soft/ViGlance '/storage/nvme5/new_clones/VBA/ViGlance' &
git clone https://github.com/sjgray/cbm-transfer '/storage/nvme5/new_clones/VBA/cbm-transfer' &
git clone https://github.com/sylhare/Excel_VBA '/storage/nvme5/new_clones/VBA/Excel_VBA' &
git clone https://github.com/x-vba/xplus '/storage/nvme5/new_clones/VBA/xplus' &
git clone https://github.com/todar/VBA-Boilerplate '/storage/nvme5/new_clones/VBA/VBA-Boilerplate' &
git clone https://github.com/esap/exbook '/storage/nvme5/new_clones/VBA/exbook' &
git clone https://github.com/jpbro/VbFcgi '/storage/nvme5/new_clones/VBA/VbFcgi' &
git clone https://github.com/BitWrecker/Archived-VPN-Comparison-Spreadsheet '/storage/nvme5/new_clones/VBA/Archived-VPN-Comparison-Spreadsheet' &
git clone https://github.com/tannerhelland/VB6-Compression '/storage/nvme5/new_clones/VBA/VB6-Compression' &
git clone https://github.com/sdkn104/VBA-CSV '/storage/nvme5/new_clones/VBA/VBA-CSV' &
git clone https://github.com/k4j8/outlook-move-to-thread '/storage/nvme5/new_clones/VBA/outlook-move-to-thread' &
git clone https://github.com/tannerhelland/vb6-code '/storage/nvme5/new_clones/VBA/vb6-code' &
git clone https://github.com/cristianbuse/VBA-ArrayTools '/storage/nvme5/new_clones/VBA/VBA-ArrayTools' &
git clone https://github.com/Rabadash8820/VbaModuleManager '/storage/nvme5/new_clones/VBA/VbaModuleManager' &
git clone https://github.com/rickding/HelloDocker '/storage/nvme5/new_clones/VBA/HelloDocker' &
git clone https://github.com/antoniopapa/nest-ambassador '/storage/nvme5/new_clones/VBA/nest-ambassador' &
git clone https://github.com/GPFSimon/Speed-Bionic-Reading '/storage/nvme5/new_clones/VBA/Speed-Bionic-Reading' &
git clone https://github.com/6234456/Excel-VBA-Dicts '/storage/nvme5/new_clones/VBA/Excel-VBA-Dicts' &
git clone https://github.com/thetrik/VbTrickTimer '/storage/nvme5/new_clones/VBA/VbTrickTimer' &
git clone https://github.com/Rotifer/VBA '/storage/nvme5/new_clones/VBA/VBA' &
git clone https://github.com/ricardocamisa/clsTextBox '/storage/nvme5/new_clones/VBA/clsTextBox' &
git clone https://github.com/ven2day/Bigdata-docker-sandbox '/storage/nvme5/new_clones/VBA/Bigdata-docker-sandbox' &
git clone https://github.com/todar/VBA-Userform-EventListener '/storage/nvme5/new_clones/VBA/VBA-Userform-EventListener' &
git clone https://github.com/charl-potgieter/SpreadsheetBI '/storage/nvme5/new_clones/VBA/SpreadsheetBI' &
git clone https://github.com/SonyaNadesan/ReusablePerformanceOptimisedVBAFunctions '/storage/nvme5/new_clones/VBA/ReusablePerformanceOptimisedVBAFunctions' &
git clone https://github.com/ColmBhandal/VbaSync '/storage/nvme5/new_clones/VBA/VbaSync' &
git clone https://github.com/PGS62/VBA-CSV '/storage/nvme5/new_clones/VBA/VBA-CSV' &
git clone https://github.com/opensoldat/polyworks '/storage/nvme5/new_clones/VBA/polyworks' &
git clone https://github.com/moqianbei/qianbeibiaoge '/storage/nvme5/new_clones/VBA/qianbeibiaoge' &
git clone https://github.com/jet2jet/vb2clr '/storage/nvme5/new_clones/VBA/vb2clr' &
git clone https://github.com/yamato1413/WebDriverManager-for-VBA '/storage/nvme5/new_clones/VBA/WebDriverManager-for-VBA' &
git clone https://github.com/454a1/CATIA_VBA '/storage/nvme5/new_clones/VBA/CATIA_VBA' &
git clone https://github.com/SweetIceLolly/DragControlsIDE-v2 '/storage/nvme5/new_clones/VBA/DragControlsIDE-v2' &
git clone https://github.com/VBoilerplate/Boiler '/storage/nvme5/new_clones/VBA/Boiler' &
git clone https://github.com/DanGolding/Linear-and-bilinear-interpolation-in-Excel '/storage/nvme5/new_clones/VBA/Linear-and-bilinear-interpolation-in-Excel' &
git clone https://github.com/brucemcpherson/vbaJavaScript '/storage/nvme5/new_clones/VBA/vbaJavaScript' &
git clone https://github.com/Aozhuoer/YUYU '/storage/nvme5/new_clones/VBA/YUYU' &
git clone https://github.com/jonadv/VBA-Benchmark '/storage/nvme5/new_clones/VBA/VBA-Benchmark' &
git clone https://github.com/EagleAglow/vba-websocket '/storage/nvme5/new_clones/VBA/vba-websocket' &
git clone https://github.com/JohnWoodman/VBA-Macro-Dump-Process '/storage/nvme5/new_clones/VBA/VBA-Macro-Dump-Process' &
git clone https://github.com/shishouyuan/HandyRefVBA '/storage/nvme5/new_clones/VBA/HandyRefVBA' &
git clone https://github.com/getkks/Power-Query '/storage/nvme5/new_clones/VBA/Power-Query' &
git clone https://github.com/zzs01/IronJoe '/storage/nvme5/new_clones/VBA/IronJoe' &
git clone https://github.com/TotallyInformation/outlook-filer '/storage/nvme5/new_clones/VBA/outlook-filer' &
git clone https://github.com/kmierzeje/plantuml-powerpoint-addin '/storage/nvme5/new_clones/VBA/plantuml-powerpoint-addin' &
git clone https://github.com/RelaxTools/Hidennotare '/storage/nvme5/new_clones/VBA/Hidennotare' &
git clone https://github.com/rmdavy/AmsiPEBWalkVBA '/storage/nvme5/new_clones/VBA/AmsiPEBWalkVBA' &
git clone https://github.com/aicells/aicells '/storage/nvme5/new_clones/VBA/aicells' &
git clone https://github.com/Ba11istix/VB-VBA-Colour-Change '/storage/nvme5/new_clones/VBA/VB-VBA-Colour-Change' &
git clone https://github.com/ricardocamisa/AdminVBA '/storage/nvme5/new_clones/VBA/AdminVBA' &
git clone https://github.com/kujirahand/chozetu-excel-vba '/storage/nvme5/new_clones/VBA/chozetu-excel-vba' &
git clone https://github.com/MarkJohnstoneGitHub/VBA-IDictionary '/storage/nvme5/new_clones/VBA/VBA-IDictionary' &
git clone https://github.com/er-ri/selenium-wrapper-vba '/storage/nvme5/new_clones/VBA/selenium-wrapper-vba' &
git clone https://github.com/KedalionDaimon/LispForTandy '/storage/nvme5/new_clones/VBA/LispForTandy' &
git clone https://github.com/py7hagoras/OfficeMacro64 '/storage/nvme5/new_clones/VBA/OfficeMacro64' &
git clone https://github.com/open-rpa/examples-files '/storage/nvme5/new_clones/VBA/examples-files' &
git clone https://github.com/felipebacelo/ApplicationVBA '/storage/nvme5/new_clones/VBA/ApplicationVBA' &
git clone https://github.com/SSlinky/VBA-ExtendedDictionary '/storage/nvme5/new_clones/VBA/VBA-ExtendedDictionary' &
git clone https://github.com/C64-Mark/C64-Listings '/storage/nvme5/new_clones/VBA/C64-Listings' &
git clone https://github.com/thetrik/Vb64BitDllUsage '/storage/nvme5/new_clones/VBA/Vb64BitDllUsage' &
git clone https://github.com/David-Brewin/PowerpointToPDF '/storage/nvme5/new_clones/VBA/PowerpointToPDF' &
git clone https://github.com/todar/VBA-Strings '/storage/nvme5/new_clones/VBA/VBA-Strings' &
git clone https://github.com/rmdavy/VBAFunctionPointers '/storage/nvme5/new_clones/VBA/VBAFunctionPointers' &
git clone https://github.com/Afzalwas/Excel-VBA-Scripts '/storage/nvme5/new_clones/VBA/Excel-VBA-Scripts' &
git clone https://github.com/martinctc/Excel-VBA '/storage/nvme5/new_clones/VBA/Excel-VBA' &
git clone https://github.com/InvisibleRain/Tetris-in-Excel '/storage/nvme5/new_clones/VBA/Tetris-in-Excel' &
git clone https://github.com/formix/RetroZ '/storage/nvme5/new_clones/VBA/RetroZ' &
git clone https://github.com/ba5tz/vbaTutorial '/storage/nvme5/new_clones/VBA/vbaTutorial' &
git clone https://github.com/SanjayPrabhakaran/JyotishCalc '/storage/nvme5/new_clones/VBA/JyotishCalc' &
git clone https://github.com/duyanning/womacs '/storage/nvme5/new_clones/VBA/womacs' &
git clone https://github.com/VinceCrusty/Quest-Homes-Environment-Converter '/storage/nvme5/new_clones/VBA/Quest-Homes-Environment-Converter' &
git clone https://github.com/GustavBrock/VBA.ModernBox '/storage/nvme5/new_clones/VBA/VBA.ModernBox' &
git clone https://github.com/videogamepreservation/oregontrail '/storage/nvme5/new_clones/VBA/oregontrail' &
git clone https://github.com/tannerhelland/pd2D '/storage/nvme5/new_clones/VBA/pd2D' &
git clone https://github.com/vbatools/UserForms-VBA-Context-Menu '/storage/nvme5/new_clones/VBA/UserForms-VBA-Context-Menu' &
git clone https://github.com/lucaspdude/laravel_docker '/storage/nvme5/new_clones/VBA/laravel_docker' &
git clone https://github.com/paladin-t/b8.plugins '/storage/nvme5/new_clones/VBA/b8.plugins' &
git clone https://github.com/GustavBrock/VBA.Cryptography '/storage/nvme5/new_clones/VBA/VBA.Cryptography' &
git clone https://github.com/francescofoti/Reading_Text_Files '/storage/nvme5/new_clones/VBA/Reading_Text_Files' &
git clone https://github.com/boar24/InsertCrossReferencesComfortably '/storage/nvme5/new_clones/VBA/InsertCrossReferencesComfortably' &
git clone https://github.com/KatrinaJames/vba-gb '/storage/nvme5/new_clones/VBA/vba-gb' &
git clone https://github.com/KotorinChunChun/VbaDevelopSupportOLD '/storage/nvme5/new_clones/VBA/VbaDevelopSupportOLD' &
git clone https://github.com/jbossdemocentral/rhpam7-order-management-demo-repo '/storage/nvme5/new_clones/VBA/rhpam7-order-management-demo-repo' &
git clone https://github.com/gpolic/kmeans-excel '/storage/nvme5/new_clones/VBA/kmeans-excel' &
git clone https://github.com/mandiant/vbScript_deobfuscator '/storage/nvme5/new_clones/VBA/vbScript_deobfuscator' &
git clone https://github.com/wavoigt/FNIRSI-1013D-WAV-Viewer-in-Excel-VBA '/storage/nvme5/new_clones/VBA/FNIRSI-1013D-WAV-Viewer-in-Excel-VBA' &
git clone https://github.com/thetrik/DX9VB '/storage/nvme5/new_clones/VBA/DX9VB' &
git clone https://github.com/ulu-ventures/VCDA '/storage/nvme5/new_clones/VBA/VCDA' &
git clone https://github.com/BdR76/barcode128.bas '/storage/nvme5/new_clones/VBA/barcode128.bas' &
git clone https://github.com/ReneNyffenegger/about-VBA '/storage/nvme5/new_clones/VBA/about-VBA' &
git clone https://github.com/rmdavy/AmsiPEBWalkVBAx64 '/storage/nvme5/new_clones/VBA/AmsiPEBWalkVBAx64' &
git clone https://github.com/DaanV2/Vba-Standard-Files '/storage/nvme5/new_clones/VBA/Vba-Standard-Files' &
git clone https://github.com/erujs/vba-webdata '/storage/nvme5/new_clones/VBA/vba-webdata' &
git clone https://github.com/takanaweb5/EasyLout '/storage/nvme5/new_clones/VBA/EasyLout' &
git clone https://github.com/cristianbuse/Excel-VBA-ProgressBar '/storage/nvme5/new_clones/VBA/Excel-VBA-ProgressBar' &
git clone https://github.com/cristianbuse/VBA-FastExcelUDFs '/storage/nvme5/new_clones/VBA/VBA-FastExcelUDFs' &
git clone https://github.com/oahrens/Zotero-Tools '/storage/nvme5/new_clones/VBA/Zotero-Tools' &
git clone https://github.com/cristianbuse/Excel-VBA-Tools '/storage/nvme5/new_clones/VBA/Excel-VBA-Tools' &
git clone https://github.com/wangguo/Macro_word '/storage/nvme5/new_clones/VBA/Macro_word' &
git clone https://github.com/syntax53/Nightmare-Redux '/storage/nvme5/new_clones/VBA/Nightmare-Redux' &
git clone https://github.com/x-vba/xtemplate '/storage/nvme5/new_clones/VBA/xtemplate' &
git clone https://github.com/rickmanalexander/ADODBDataAccessAPI '/storage/nvme5/new_clones/VBA/ADODBDataAccessAPI' &
git clone https://github.com/cristianbuse/VBA-WeakReference '/storage/nvme5/new_clones/VBA/VBA-WeakReference' &
git clone https://github.com/VBGAMER45/GMD-Recovery '/storage/nvme5/new_clones/VBA/GMD-Recovery' &
git clone https://github.com/PeterRoach/VBA '/storage/nvme5/new_clones/VBA/VBA' &
git clone https://github.com/wanderleihuttel/vba '/storage/nvme5/new_clones/VBA/vba' &
git clone https://github.com/ralfyang/docker-compose_for_go_revel '/storage/nvme5/new_clones/VBA/docker-compose_for_go_revel' &
git clone https://github.com/rcfdtools/R.HydroTools '/storage/nvme5/new_clones/VBA/R.HydroTools' &
git clone https://github.com/GustavBrock/VBA.Round '/storage/nvme5/new_clones/VBA/VBA.Round' &
git clone https://github.com/TommasoBelluzzo/StrataXL '/storage/nvme5/new_clones/VBA/StrataXL' &
git clone https://github.com/GustavBrock/VBA.Compress '/storage/nvme5/new_clones/VBA/VBA.Compress' &
git clone https://github.com/otomad/OutputVideo-Addon-for-PPTX '/storage/nvme5/new_clones/VBA/OutputVideo-Addon-for-PPTX' &
git clone https://github.com/edugca/xlFOCUS '/storage/nvme5/new_clones/VBA/xlFOCUS' &
git clone https://github.com/Sarania/Project-Cherry '/storage/nvme5/new_clones/VBA/Project-Cherry' &
git clone https://github.com/klui-freiberg/PowerEver '/storage/nvme5/new_clones/VBA/PowerEver' &
git clone https://github.com/mbirth/gwbasic '/storage/nvme5/new_clones/VBA/gwbasic' &
git clone https://github.com/TimPaterson/CNC-Tool-Library-Manager '/storage/nvme5/new_clones/VBA/CNC-Tool-Library-Manager' &
git clone https://github.com/cristianbuse/VBA-StringBuffer '/storage/nvme5/new_clones/VBA/VBA-StringBuffer' &
git clone https://github.com/thetrik/ctlBinData '/storage/nvme5/new_clones/VBA/ctlBinData' &
git clone https://github.com/FellippeHeitor/INI-Manager '/storage/nvme5/new_clones/VBA/INI-Manager' &
git clone https://github.com/StinkCat/VlookupTool '/storage/nvme5/new_clones/VBA/VlookupTool' &
git clone https://github.com/shinespeciall/WarioLand4MultiEditor '/storage/nvme5/new_clones/VBA/WarioLand4MultiEditor' &
git clone https://github.com/denissa4/vlookup-custom-formula-for-web-API-JSON '/storage/nvme5/new_clones/VBA/vlookup-custom-formula-for-web-API-JSON' &
git clone https://github.com/MOLFDIR/MOLFDIR '/storage/nvme5/new_clones/VBA/MOLFDIR' &
git clone https://github.com/neginhemati/EXCELing '/storage/nvme5/new_clones/VBA/EXCELing' &
git clone https://github.com/thetrik/CTrickSubclass '/storage/nvme5/new_clones/VBA/CTrickSubclass' &
git clone https://github.com/HALTEC/VBA-commons-lib '/storage/nvme5/new_clones/VBA/VBA-commons-lib' &
git clone https://github.com/wqweto/VBTixyLand '/storage/nvme5/new_clones/VBA/VBTixyLand' &
git clone https://github.com/thetrik/CTrickWait '/storage/nvme5/new_clones/VBA/CTrickWait' &
git clone https://github.com/kawashimaken/docker-lamp-lesson '/storage/nvme5/new_clones/VBA/docker-lamp-lesson' &
git clone https://github.com/bikibird/AppleIIGames '/storage/nvme5/new_clones/VBA/AppleIIGames' &
git clone https://github.com/GustavBrock/VBA.Date '/storage/nvme5/new_clones/VBA/VBA.Date' &
git clone https://github.com/Nitrokey/openpgp-card '/storage/nvme5/new_clones/VBA/openpgp-card' &
git clone https://github.com/AntoniotheFuture/VBA-SaveImgToPPT '/storage/nvme5/new_clones/VBA/VBA-SaveImgToPPT' &
git clone https://github.com/AshishKingdom/QB64_OpenGL_Demos '/storage/nvme5/new_clones/VBA/QB64_OpenGL_Demos' &
git clone https://github.com/Jack-Badger/SWMacros '/storage/nvme5/new_clones/VBA/SWMacros' &
git clone https://github.com/avimallu/PowerPointSnap '/storage/nvme5/new_clones/VBA/PowerPointSnap' &
git clone https://github.com/thetrik/CEmbeddedFiles '/storage/nvme5/new_clones/VBA/CEmbeddedFiles' &
git clone https://github.com/aouwt/qb-wm '/storage/nvme5/new_clones/VBA/qb-wm' &
git clone https://github.com/sancarn/VbaJsBridge '/storage/nvme5/new_clones/VBA/VbaJsBridge' &
git clone https://github.com/juliolmuller/vba-outlook '/storage/nvme5/new_clones/VBA/vba-outlook' &
git clone https://github.com/wqweto/Biff12Writer '/storage/nvme5/new_clones/VBA/Biff12Writer' &
git clone https://github.com/dnissim/VBA_Progress-Bar '/storage/nvme5/new_clones/VBA/VBA_Progress-Bar' &
git clone https://github.com/brucemcpherson/cDataSet '/storage/nvme5/new_clones/VBA/cDataSet' &
git clone https://github.com/sancarn/uiVBA '/storage/nvme5/new_clones/VBA/uiVBA' &
git clone https://github.com/happybono/GEOSage '/storage/nvme5/new_clones/VBA/GEOSage' &
git clone https://github.com/PNNL-Comp-Mass-Spec/Molecular-Weight-Calculator-VB6 '/storage/nvme5/new_clones/VBA/Molecular-Weight-Calculator-VB6' &
git clone https://github.com/cavo789/vba_access '/storage/nvme5/new_clones/VBA/vba_access' &
git clone https://github.com/NaoOtosaka/PCR-Timeline-Rec '/storage/nvme5/new_clones/VBA/PCR-Timeline-Rec' &
git clone https://github.com/JosueElihu/Vb6IconCreator '/storage/nvme5/new_clones/VBA/Vb6IconCreator' &
git clone https://github.com/M-Scott-Lassiter/Fred-the-Developer '/storage/nvme5/new_clones/VBA/Fred-the-Developer' &
git clone https://github.com/cxw42/VimWord '/storage/nvme5/new_clones/VBA/VimWord' &
git clone https://github.com/rfl808/Notify '/storage/nvme5/new_clones/VBA/Notify' &
git clone https://github.com/xformerfhs/VBAUtilities '/storage/nvme5/new_clones/VBA/VBAUtilities' &
git clone https://github.com/tmgerard/Matrix-Structural-Analysis-Excel '/storage/nvme5/new_clones/VBA/Matrix-Structural-Analysis-Excel' &
git clone https://github.com/archerbird/Pacman '/storage/nvme5/new_clones/VBA/Pacman' &
git clone https://github.com/williamjiamin/VBA '/storage/nvme5/new_clones/VBA/VBA' &
git clone https://github.com/thetrik/MemoryUsage '/storage/nvme5/new_clones/VBA/MemoryUsage' &
git clone https://github.com/0xbad53c/VBA-Talk-Dirty-To-Me '/storage/nvme5/new_clones/VBA/VBA-Talk-Dirty-To-Me' &
git clone https://github.com/ricardocamisa/excelparatodos '/storage/nvme5/new_clones/VBA/excelparatodos' &
git clone https://github.com/codetuner/VBA-Library '/storage/nvme5/new_clones/VBA/VBA-Library' &
git clone https://github.com/midelic/Ersky9x-Tx-bas-scripts '/storage/nvme5/new_clones/VBA/Ersky9x-Tx-bas-scripts' &
git clone https://github.com/lreis2415/SimDTA '/storage/nvme5/new_clones/VBA/SimDTA' &
git clone https://github.com/lreis2415/SimDTA '/storage/nvme5/new_clones/VBA/SimDTA' &
git clone https://github.com/sherwin-dc/ansi-logo-generator '/storage/nvme5/new_clones/VBA/ansi-logo-generator' &
git clone https://github.com/Greedquest/VBA-Timing-Methods '/storage/nvme5/new_clones/VBA/VBA-Timing-Methods' &
git clone https://github.com/buger404/Emerald '/storage/nvme5/new_clones/VBA/Emerald' &
git clone https://github.com/Aeraphe/xdebug '/storage/nvme5/new_clones/VBA/xdebug' &
git clone https://github.com/mayaohan/egg-example '/storage/nvme5/new_clones/VBA/egg-example' &
git clone https://github.com/SinlinLi/VB-neural-network '/storage/nvme5/new_clones/VBA/VB-neural-network' &
git clone https://github.com/TypeInBooks/magazines '/storage/nvme5/new_clones/VBA/magazines' &
git clone https://github.com/juliaaano/rhpam-quickstart '/storage/nvme5/new_clones/VBA/rhpam-quickstart' &
git clone https://github.com/VBForumsCommunity/vbimg2pdf '/storage/nvme5/new_clones/VBA/vbimg2pdf' &
git clone https://github.com/BPOutlaws/QB64-Platformer-Test '/storage/nvme5/new_clones/VBA/QB64-Platformer-Test' &
git clone https://github.com/uricod/ExcelMacros '/storage/nvme5/new_clones/VBA/ExcelMacros' &
git clone https://github.com/tiffanyScorpio/UI-material '/storage/nvme5/new_clones/VBA/UI-material' &
git clone https://github.com/UoLeevi/excel '/storage/nvme5/new_clones/VBA/excel' &
git clone https://github.com/FellippeHeitor/tui '/storage/nvme5/new_clones/VBA/tui' &
git clone https://github.com/GustavBrock/VBA.CurrencyExchange '/storage/nvme5/new_clones/VBA/VBA.CurrencyExchange' &
git clone https://github.com/longvh211/Edge-IE-Mode-Automation-with-IES-for-VBA '/storage/nvme5/new_clones/VBA/Edge-IE-Mode-Automation-with-IES-for-VBA' &
git clone https://github.com/24000/ChromeControler-No-Selenium-WebDriver-VBAJSON '/storage/nvme5/new_clones/VBA/ChromeControler-No-Selenium-WebDriver-VBAJSON' &
git clone https://github.com/mherzog01/SAP-Data-Automation-Toolkit '/storage/nvme5/new_clones/VBA/SAP-Data-Automation-Toolkit' &
git clone https://github.com/ReneNyffenegger/VBA-calls-DLL '/storage/nvme5/new_clones/VBA/VBA-calls-DLL' &
git clone https://github.com/maxamin/Crypters-sources '/storage/nvme5/new_clones/VBA/Crypters-sources' &
git clone https://github.com/AntoniotheFuture/VBACode '/storage/nvme5/new_clones/VBA/VBACode' &
git clone https://github.com/lucschulz/VBA_ORM '/storage/nvme5/new_clones/VBA/VBA_ORM' &
git clone https://github.com/iyandi/js-shellcode '/storage/nvme5/new_clones/VBA/js-shellcode' &
git clone https://github.com/carlislefox/Mirage-Source-v3.0.3 '/storage/nvme5/new_clones/VBA/Mirage-Source-v3.0.3' &
git clone https://github.com/paigerodeghero/TigerDataCoding '/storage/nvme5/new_clones/VBA/TigerDataCoding' &
git clone https://github.com/RodrigoACM/VBARepository '/storage/nvme5/new_clones/VBA/VBARepository' &
git clone https://github.com/ZakariaMahmoud/Docker-BigData-Tools '/storage/nvme5/new_clones/VBA/Docker-BigData-Tools' &
git clone https://github.com/paladin-t/pomodoro '/storage/nvme5/new_clones/VBA/pomodoro' &
git clone https://github.com/jimbrig/OutlookSaver '/storage/nvme5/new_clones/VBA/OutlookSaver' &
git clone https://github.com/anabastos/PatriotaAdventures-basic8 '/storage/nvme5/new_clones/VBA/PatriotaAdventures-basic8' &
git clone https://github.com/aminya/AcuteMSWord '/storage/nvme5/new_clones/VBA/AcuteMSWord' &
git clone https://github.com/Beakerboy/VBA-Unit-Tester '/storage/nvme5/new_clones/VBA/VBA-Unit-Tester' &
git clone https://github.com/kyledeer-32/vba_fuzzymatching '/storage/nvme5/new_clones/VBA/vba_fuzzymatching' &
git clone https://github.com/EagleAglow/vba-websocket-class '/storage/nvme5/new_clones/VBA/vba-websocket-class' &
git clone https://github.com/mobadarah/Ammoria '/storage/nvme5/new_clones/VBA/Ammoria' &
git clone https://github.com/standard-software/st_vba '/storage/nvme5/new_clones/VBA/st_vba' &
git clone https://github.com/msuba-dev/SAP-GUI-VBA-Excel-scripting '/storage/nvme5/new_clones/VBA/SAP-GUI-VBA-Excel-scripting' &
git clone https://github.com/JoshyFrancis/VB6-Print-Class '/storage/nvme5/new_clones/VBA/VB6-Print-Class' &
git clone https://github.com/mojontwins/QBAGLE '/storage/nvme5/new_clones/VBA/QBAGLE' &
git clone https://github.com/todar/VBA-Version-Control '/storage/nvme5/new_clones/VBA/VBA-Version-Control' &
git clone https://github.com/buananetpbun/Avaco-Uninstaller-VB6.0 '/storage/nvme5/new_clones/VBA/Avaco-Uninstaller-VB6.0' &
git clone https://github.com/rnfc/vba '/storage/nvme5/new_clones/VBA/vba' &
git clone https://github.com/Nume1977/Nova3D-File-Manager '/storage/nvme5/new_clones/VBA/Nova3D-File-Manager' &
git clone https://github.com/mygreen/ExcelERD '/storage/nvme5/new_clones/VBA/ExcelERD' &
git clone https://github.com/Greedquest/vbInvoke '/storage/nvme5/new_clones/VBA/vbInvoke' &
git clone https://github.com/TheGeekExplorer/GTIN-Validation '/storage/nvme5/new_clones/VBA/GTIN-Validation' &
git clone https://github.com/VBGAMER45/Domain-Manager-Pro '/storage/nvme5/new_clones/VBA/Domain-Manager-Pro' &
git clone https://github.com/navferty/SampleExcelXlamAddin '/storage/nvme5/new_clones/VBA/SampleExcelXlamAddin' &
git clone https://github.com/tebl/D32-Joystick-Adapter '/storage/nvme5/new_clones/VBA/D32-Joystick-Adapter' &
git clone https://github.com/GustavBrock/VBA.RowNumbers '/storage/nvme5/new_clones/VBA/VBA.RowNumbers' &
git clone https://github.com/Gagniuc/Algorithms-in-Visual-Basic-for-Applications '/storage/nvme5/new_clones/VBA/Algorithms-in-Visual-Basic-for-Applications' &
git clone https://github.com/logicahealth/OpenAHLTA '/storage/nvme5/new_clones/VBA/OpenAHLTA' &
git clone https://github.com/Greedquest/VBA-Toolbox '/storage/nvme5/new_clones/VBA/VBA-Toolbox' &
git clone https://github.com/marc01989/VBA-Tips-and-Tricks '/storage/nvme5/new_clones/VBA/VBA-Tips-and-Tricks' &
git clone https://github.com/weigtman/note '/storage/nvme5/new_clones/VBA/note' &
git clone https://github.com/pchemguy/ContactEditor '/storage/nvme5/new_clones/VBA/ContactEditor' &
git clone https://github.com/Bearx2004/vb6jsonx '/storage/nvme5/new_clones/VBA/vb6jsonx' &
git clone https://github.com/queler/WinSPAuthenticator '/storage/nvme5/new_clones/VBA/WinSPAuthenticator' &
git clone https://github.com/warbe-maker/VBA-Error '/storage/nvme5/new_clones/VBA/VBA-Error' &
git clone https://github.com/Beakerboy/VBA-Math-Objects '/storage/nvme5/new_clones/VBA/VBA-Math-Objects' &
git clone https://github.com/Subhankar2000/DOS_BOX '/storage/nvme5/new_clones/VBA/DOS_BOX' &
git clone https://github.com/DirectY1996/SuperMarioWorldMaker '/storage/nvme5/new_clones/VBA/SuperMarioWorldMaker' &
git clone https://github.com/imxcstar/vb6-miniblink-SDK '/storage/nvme5/new_clones/VBA/vb6-miniblink-SDK' &
git clone https://github.com/KotorinChunChun/ExcelFormulaEditor '/storage/nvme5/new_clones/VBA/ExcelFormulaEditor' &
git clone https://github.com/Excel-lent/Miltithreading-in-VBA-using-VBScript '/storage/nvme5/new_clones/VBA/Miltithreading-in-VBA-using-VBScript' &
git clone https://github.com/Gagniuc/Visual-Basic-modules-Markov-Chains '/storage/nvme5/new_clones/VBA/Visual-Basic-modules-Markov-Chains' &
git clone https://github.com/dagiz007/ExcelAddin4Atlassian '/storage/nvme5/new_clones/VBA/ExcelAddin4Atlassian' &
git clone https://github.com/macros4outlook/quotefixmacro '/storage/nvme5/new_clones/VBA/quotefixmacro' &
git clone https://github.com/richgel999/QBMOD '/storage/nvme5/new_clones/VBA/QBMOD' &
git clone https://github.com/ndmitchell/office '/storage/nvme5/new_clones/VBA/office' &
git clone https://github.com/nasservb/IR3 '/storage/nvme5/new_clones/VBA/IR3' &
git clone https://github.com/Beakerboy/VBA-Drupal-Library '/storage/nvme5/new_clones/VBA/VBA-Drupal-Library' &
git clone https://github.com/ksyx/slides2PdfWithBreaks '/storage/nvme5/new_clones/VBA/slides2PdfWithBreaks' &
git clone https://github.com/b-gonzalez/Fluent-VBA '/storage/nvme5/new_clones/VBA/Fluent-VBA' &
git clone https://github.com/Zoomicon/tranXform '/storage/nvme5/new_clones/VBA/tranXform' &
git clone https://github.com/GustavBrock/VBA.TimeEntry '/storage/nvme5/new_clones/VBA/VBA.TimeEntry' &
git clone https://github.com/BriargateExcel/VBATableManagement '/storage/nvme5/new_clones/VBA/VBATableManagement' &
git clone https://github.com/warbe-maker/VBA-Component-Management '/storage/nvme5/new_clones/VBA/VBA-Component-Management' &
git clone https://github.com/ReneNyffenegger/VBAModules '/storage/nvme5/new_clones/VBA/VBAModules' &
git clone https://github.com/charl-potgieter/SpreadsheetCreator '/storage/nvme5/new_clones/VBA/SpreadsheetCreator' &
git clone https://github.com/FellippeHeitor/amongst '/storage/nvme5/new_clones/VBA/amongst' &
git clone https://github.com/thetrik/CSharedMemory '/storage/nvme5/new_clones/VBA/CSharedMemory' &
git clone https://github.com/dindoliboon/archive '/storage/nvme5/new_clones/VBA/archive' &
git clone https://github.com/brianferguson/excel-addins '/storage/nvme5/new_clones/VBA/excel-addins' &
git clone https://github.com/Excel-VBA-Diary/GetThisWorkbookLocalPath '/storage/nvme5/new_clones/VBA/GetThisWorkbookLocalPath' &
git clone https://github.com/iam-abbas/URL-Shortener '/storage/nvme5/new_clones/VBA/URL-Shortener' &
git clone https://github.com/StringEpsilon/fbNetwork '/storage/nvme5/new_clones/VBA/fbNetwork' &
git clone https://github.com/zq99/mvc-design-pattern-in-excel-vba '/storage/nvme5/new_clones/VBA/mvc-design-pattern-in-excel-vba' &
git clone https://github.com/FirstMoonMan/OutlookToExcelTimeSheet '/storage/nvme5/new_clones/VBA/OutlookToExcelTimeSheet' &
git clone https://github.com/maxamin/Binders-sources '/storage/nvme5/new_clones/VBA/Binders-sources' &
git clone https://github.com/AccessGlobal/VBA-Code '/storage/nvme5/new_clones/VBA/VBA-Code' &
git clone https://github.com/buananetpbun/VB6.0-Siemens-GSM-CellPhone-With-Full-AT-Command '/storage/nvme5/new_clones/VBA/VB6.0-Siemens-GSM-CellPhone-With-Full-AT-Command' &
git clone https://github.com/takanaweb5/IconEditor '/storage/nvme5/new_clones/VBA/IconEditor' &
git clone https://github.com/Obsidian-pb/GraFiS-Tactic '/storage/nvme5/new_clones/VBA/GraFiS-Tactic' &
git clone https://github.com/JPMakesStuff/KeepRunning '/storage/nvme5/new_clones/VBA/KeepRunning' &
git clone https://github.com/BdR76/Manage-translations '/storage/nvme5/new_clones/VBA/Manage-translations' &
git clone https://github.com/abarabone/vbaEnumeration '/storage/nvme5/new_clones/VBA/vbaEnumeration' &
git clone https://github.com/jyoberle/c64asm '/storage/nvme5/new_clones/VBA/c64asm' &
git clone https://github.com/theAwesomeFufuman/VBA-Excel-Table-To-JSON '/storage/nvme5/new_clones/VBA/VBA-Excel-Table-To-JSON' &
git clone https://github.com/Pritesh-Mhatre/autotrader-web '/storage/nvme5/new_clones/VBA/autotrader-web' &
git clone https://github.com/marmeleiro/kintoneDataReaderforVBA '/storage/nvme5/new_clones/VBA/kintoneDataReaderforVBA' &
git clone https://github.com/buger404/DogTools-v2 '/storage/nvme5/new_clones/VBA/DogTools-v2' &
git clone https://github.com/GustavBrock/VBA.Timezone-Windows '/storage/nvme5/new_clones/VBA/VBA.Timezone-Windows' &
git clone https://github.com/wqweto/VbUdpBroadcast '/storage/nvme5/new_clones/VBA/VbUdpBroadcast' &
git clone https://github.com/alainbryden/Custom-Office-Add-Ons '/storage/nvme5/new_clones/VBA/Custom-Office-Add-Ons' &
git clone https://github.com/dnissim/VBA_General '/storage/nvme5/new_clones/VBA/VBA_General' &
git clone https://github.com/Gagniuc/Mix-two-signals-in-VB '/storage/nvme5/new_clones/VBA/Mix-two-signals-in-VB' &
git clone https://github.com/yzEric/Femap-toolbox '/storage/nvme5/new_clones/VBA/Femap-toolbox' &
git clone https://github.com/EagleAglow/vba-websocket-async '/storage/nvme5/new_clones/VBA/vba-websocket-async' &
git clone https://github.com/Max-Schmeling/code_snippets '/storage/nvme5/new_clones/VBA/code_snippets' &
git clone https://github.com/yhpong/Supervised-Learning '/storage/nvme5/new_clones/VBA/Supervised-Learning' &
git clone https://github.com/santosrai/VBA-For-Everyone '/storage/nvme5/new_clones/VBA/VBA-For-Everyone' &
git clone https://github.com/mckryton/senfgurke '/storage/nvme5/new_clones/VBA/senfgurke' &
git clone https://github.com/wakfi/msword-vba '/storage/nvme5/new_clones/VBA/msword-vba' &
git clone https://github.com/sysdzw/WebView2DemoForVb6 '/storage/nvme5/new_clones/VBA/WebView2DemoForVb6' &
git clone https://github.com/mkopack73/cmm2_tests '/storage/nvme5/new_clones/VBA/cmm2_tests' &
git clone https://github.com/zq99/audit-trail-in-vba-for-excel-workbook '/storage/nvme5/new_clones/VBA/audit-trail-in-vba-for-excel-workbook' &
git clone https://github.com/unbibium/baba-is-c64 '/storage/nvme5/new_clones/VBA/baba-is-c64' &
git clone https://github.com/tokarskiy/VBA-List '/storage/nvme5/new_clones/VBA/VBA-List' &
git clone https://github.com/caglartoklu/instantarchive '/storage/nvme5/new_clones/VBA/instantarchive' &
git clone https://github.com/WolfpackWilson/VBA-Scripting-Library '/storage/nvme5/new_clones/VBA/VBA-Scripting-Library' &
git clone https://github.com/LelandGrunt/AVQ '/storage/nvme5/new_clones/VBA/AVQ' &
git clone https://github.com/delacruzfranklyn93/stock_analysis_VBA '/storage/nvme5/new_clones/VBA/stock_analysis_VBA' &
git clone https://github.com/MyTDT-Mysoft/DarkTheme-Npp-Plugin '/storage/nvme5/new_clones/VBA/DarkTheme-Npp-Plugin' &
git clone https://github.com/gueleh/flowframework2 '/storage/nvme5/new_clones/VBA/flowframework2' &
git clone https://github.com/furyutei/ConvertCsvToTable '/storage/nvme5/new_clones/VBA/ConvertCsvToTable' &
git clone https://github.com/jonathanng/art_vandelay '/storage/nvme5/new_clones/VBA/art_vandelay' &
git clone https://github.com/zeeshanmulla/Mobile-plan '/storage/nvme5/new_clones/VBA/Mobile-plan' &
git clone https://github.com/spert/excel-vba-chart-formatter '/storage/nvme5/new_clones/VBA/excel-vba-chart-formatter' &
git clone https://github.com/Totoesc/-VBA-for-Word '/storage/nvme5/new_clones/VBA/-VBA-for-Word' &
git clone https://github.com/GustavBrock/VBA.Random '/storage/nvme5/new_clones/VBA/VBA.Random' &
git clone https://github.com/jiangzhe11/anti-jiyu '/storage/nvme5/new_clones/VBA/anti-jiyu' &
git clone https://github.com/buananetpbun/Keyboard-Diagnostic-VB6.0 '/storage/nvme5/new_clones/VBA/Keyboard-Diagnostic-VB6.0' &
git clone https://github.com/QB64Team/YoutubeTutorials '/storage/nvme5/new_clones/VBA/YoutubeTutorials' &
git clone https://github.com/Cybermonkey342/cmm2-examples '/storage/nvme5/new_clones/VBA/cmm2-examples' &
git clone https://github.com/VisualStudioEX3/TLSA_Engine_VB6 '/storage/nvme5/new_clones/VBA/TLSA_Engine_VB6' &
git clone https://github.com/devinbinnie/matter95 '/storage/nvme5/new_clones/VBA/matter95' &
git clone https://github.com/tdalon/outlook-vba '/storage/nvme5/new_clones/VBA/outlook-vba' &
git clone https://github.com/mnru/VBA-Functional-Array '/storage/nvme5/new_clones/VBA/VBA-Functional-Array' &
git clone https://github.com/GustavBrock/VBA.Callback '/storage/nvme5/new_clones/VBA/VBA.Callback' &
git clone https://github.com/alexofrhodes/VBA-Library '/storage/nvme5/new_clones/VBA/VBA-Library' &
git clone https://github.com/vbamagician/Desgin-Patterns-in-VBA '/storage/nvme5/new_clones/VBA/Desgin-Patterns-in-VBA' &
git clone https://github.com/nishanc/powerpoint-slide-timeline '/storage/nvme5/new_clones/VBA/powerpoint-slide-timeline' &
git clone https://github.com/gpe-mw-training/advanced-process-development-labs '/storage/nvme5/new_clones/VBA/advanced-process-development-labs' &
git clone https://github.com/felipebacelo/ProgressBars '/storage/nvme5/new_clones/VBA/ProgressBars' &
git clone https://github.com/zq99/data-access-layer-vba-sql-server '/storage/nvme5/new_clones/VBA/data-access-layer-vba-sql-server' &
git clone https://github.com/mumaritc/zatca.TLV.QRCode.MSAccess.VBA '/storage/nvme5/new_clones/VBA/zatca.TLV.QRCode.MSAccess.VBA' &
git clone https://github.com/eclectic-matt/Visual-Basic-for-Applications '/storage/nvme5/new_clones/VBA/Visual-Basic-for-Applications' &
git clone https://github.com/TheMayoras/VBA-Helpers '/storage/nvme5/new_clones/VBA/VBA-Helpers' &
git clone https://github.com/sancarn/VBProjectHack '/storage/nvme5/new_clones/VBA/VBProjectHack' &
git clone https://github.com/jbossdemocentral/rhpam7-mortgage-demo-repo '/storage/nvme5/new_clones/VBA/rhpam7-mortgage-demo-repo' &
git clone https://github.com/redhat-italy/rht-summit2020-pam '/storage/nvme5/new_clones/VBA/rht-summit2020-pam' &
git clone https://github.com/samirsaci/sap-automation-po '/storage/nvme5/new_clones/VBA/sap-automation-po' &
git clone https://github.com/Gagniuc/WebCam-software-sampling '/storage/nvme5/new_clones/VBA/WebCam-software-sampling' &
git clone https://github.com/cristianbuse/Excel-VBA-SafeTimers '/storage/nvme5/new_clones/VBA/Excel-VBA-SafeTimers' &
git clone https://github.com/ReneNyffenegger/winsqlite3.dll-4-VBA '/storage/nvme5/new_clones/VBA/winsqlite3.dll-4-VBA' &
git clone https://github.com/InventorCode/InventorVBA '/storage/nvme5/new_clones/VBA/InventorVBA' &
git clone https://github.com/Psyproxine/Last-Chaos-Clientless-Bot '/storage/nvme5/new_clones/VBA/Last-Chaos-Clientless-Bot' &
git clone https://github.com/RETROQB45/QDigger '/storage/nvme5/new_clones/VBA/QDigger' &
git clone https://github.com/neilsf/Flying-Saucers '/storage/nvme5/new_clones/VBA/Flying-Saucers' &
git clone https://github.com/rmdavy/enumprocmodules '/storage/nvme5/new_clones/VBA/enumprocmodules' &
git clone https://github.com/Kr00l/CTimer '/storage/nvme5/new_clones/VBA/CTimer' &
git clone https://github.com/maxamin/Keylogger-sources '/storage/nvme5/new_clones/VBA/Keylogger-sources' &
git clone https://github.com/aouwt/stupidc '/storage/nvme5/new_clones/VBA/stupidc' &
git clone https://github.com/vbatools/UserForms-VBA-Splitter '/storage/nvme5/new_clones/VBA/UserForms-VBA-Splitter' &
git clone https://github.com/team-moeller/better-access-pivottable '/storage/nvme5/new_clones/VBA/better-access-pivottable' &
git clone https://github.com/cavo789/vba_outlook_save_pdf '/storage/nvme5/new_clones/VBA/vba_outlook_save_pdf' &
git clone https://github.com/VBA-tools2/FixLinks2UDF.vba '/storage/nvme5/new_clones/VBA/FixLinks2UDF.vba' &
