#!/bin/bash

git clone https://github.com/abbodi1406/vcredist '/storage/nvme5/new_clones/VBScript/vcredist' &
git clone https://github.com/pyenv-win/pyenv-win '/storage/nvme5/new_clones/VBScript/pyenv-win' &
git clone https://github.com/rootclay/WMIHACKER '/storage/nvme5/new_clones/VBScript/WMIHACKER' &
git clone https://github.com/Da2dalus/The-MALWARE-Repo '/storage/nvme5/new_clones/VBScript/The-MALWARE-Repo' &
git clone https://github.com/abbodi1406/BatUtil '/storage/nvme5/new_clones/VBScript/BatUtil' &
git clone https://github.com/sailay1996/awesome_windows_logical_bugs '/storage/nvme5/new_clones/VBScript/awesome_windows_logical_bugs' &
git clone https://github.com/z1un/Z1-AggressorScripts '/storage/nvme5/new_clones/VBScript/Z1-AggressorScripts' &
git clone https://github.com/farag2/Install-Office '/storage/nvme5/new_clones/VBScript/Install-Office' &
git clone https://github.com/bugfan/i996 '/storage/nvme5/new_clones/VBScript/i996' &
git clone https://github.com/onx/ILOVEYOU '/storage/nvme5/new_clones/VBScript/ILOVEYOU' &
git clone https://github.com/king-angmar/weathertop '/storage/nvme5/new_clones/VBScript/weathertop' &
git clone https://github.com/N-able/ScriptsAndAutomationPolicies '/storage/nvme5/new_clones/VBScript/ScriptsAndAutomationPolicies' &
git clone https://github.com/lixk/easy-window '/storage/nvme5/new_clones/VBScript/easy-window' &
git clone https://github.com/stanleyguevara/win10-bluetooth-headphones '/storage/nvme5/new_clones/VBScript/win10-bluetooth-headphones' &
git clone https://github.com/NYAN-x-CAT/Bypass-Windows-Defender-VBS '/storage/nvme5/new_clones/VBScript/Bypass-Windows-Defender-VBS' &
git clone https://github.com/djhohnstein/ScatterBrain '/storage/nvme5/new_clones/VBScript/ScatterBrain' &
git clone https://github.com/nak1114/rbenv-win '/storage/nvme5/new_clones/VBScript/rbenv-win' &
git clone https://github.com/pippo1980/ja-netfilter-all '/storage/nvme5/new_clones/VBScript/ja-netfilter-all' &
git clone https://github.com/LazyTitan33/CTF-Writeups '/storage/nvme5/new_clones/VBScript/CTF-Writeups' &
git clone https://github.com/aikoncwd/win10script '/storage/nvme5/new_clones/VBScript/win10script' &
git clone https://github.com/ElectricRCAircraftGuy/Windows_Proxy_Toggler '/storage/nvme5/new_clones/VBScript/Windows_Proxy_Toggler' &
git clone https://github.com/erwan2212/tinypxeserver '/storage/nvme5/new_clones/VBScript/tinypxeserver' &
git clone https://github.com/bewhale/BurpLoaderKeygen-Modified '/storage/nvme5/new_clones/VBScript/BurpLoaderKeygen-Modified' &
git clone https://github.com/vbousquet/flexdmd '/storage/nvme5/new_clones/VBScript/flexdmd' &
git clone https://github.com/susam/aes.vbs '/storage/nvme5/new_clones/VBScript/aes.vbs' &
git clone https://github.com/seeumail/OfficeRTool '/storage/nvme5/new_clones/VBScript/OfficeRTool' &
git clone https://github.com/gobravedave/Enterprise-Architect '/storage/nvme5/new_clones/VBScript/Enterprise-Architect' &
git clone https://github.com/NJUPTFreeExams/NJUPT-TE-Free-Exams '/storage/nvme5/new_clones/VBScript/NJUPT-TE-Free-Exams' &
git clone https://github.com/n8felton/Firefox-ADMX '/storage/nvme5/new_clones/VBScript/Firefox-ADMX' &
git clone https://github.com/xiaokaixuan/gost-heroku '/storage/nvme5/new_clones/VBScript/gost-heroku' &
git clone https://github.com/oracle-samples/xml-sample-demo '/storage/nvme5/new_clones/VBScript/xml-sample-demo' &
git clone https://github.com/dhamstack/AREDNstack '/storage/nvme5/new_clones/VBScript/AREDNstack' &
git clone https://github.com/laoqiuqiu/DOpus-Script '/storage/nvme5/new_clones/VBScript/DOpus-Script' &
git clone https://github.com/gajos112/Digital-Forensics '/storage/nvme5/new_clones/VBScript/Digital-Forensics' &
git clone https://github.com/sverrewl/vpxtable_scripts '/storage/nvme5/new_clones/VBScript/vpxtable_scripts' &
git clone https://github.com/janhebnes/chocolatey-packages '/storage/nvme5/new_clones/VBScript/chocolatey-packages' &
git clone https://github.com/N-able/InstallAgent '/storage/nvme5/new_clones/VBScript/InstallAgent' &
git clone https://github.com/KhaledMostafaME/RPA-Visual-Basic-Scripts-VBS '/storage/nvme5/new_clones/VBScript/RPA-Visual-Basic-Scripts-VBS' &
git clone https://github.com/Digressive/MDT-Files '/storage/nvme5/new_clones/VBScript/MDT-Files' &
git clone https://github.com/Legion-Expansion/Legion-Expansion '/storage/nvme5/new_clones/VBScript/Legion-Expansion' &
git clone https://github.com/keydet89/LNK '/storage/nvme5/new_clones/VBScript/LNK' &
git clone https://github.com/CertainLach/SongAPI '/storage/nvme5/new_clones/VBScript/SongAPI' &
git clone https://github.com/unknown-user-account/Windows-11-Taskbar-Blackener '/storage/nvme5/new_clones/VBScript/Windows-11-Taskbar-Blackener' &
git clone https://github.com/GeertBellekens/Enterprise-Architect-VBScript-Library '/storage/nvme5/new_clones/VBScript/Enterprise-Architect-VBScript-Library' &
git clone https://github.com/gbuktenica/PsRun '/storage/nvme5/new_clones/VBScript/PsRun' &
git clone https://github.com/google/password-sync-support-tool '/storage/nvme5/new_clones/VBScript/password-sync-support-tool' &
git clone https://github.com/rickstaa/todoist-global-shortcuts-WIN10 '/storage/nvme5/new_clones/VBScript/todoist-global-shortcuts-WIN10' &
git clone https://github.com/koswald/VBScript '/storage/nvme5/new_clones/VBScript/VBScript' &
git clone https://github.com/cavo789/vba_excel_export_code '/storage/nvme5/new_clones/VBScript/vba_excel_export_code' &
git clone https://github.com/xcanwin/XBurpCrack '/storage/nvme5/new_clones/VBScript/XBurpCrack' &
git clone https://github.com/191801737/securecrt_network '/storage/nvme5/new_clones/VBScript/securecrt_network' &
git clone https://github.com/YangSirrr/YangsirRedTeamTools '/storage/nvme5/new_clones/VBScript/YangsirRedTeamTools' &
git clone https://github.com/paveleremin/cisco-anyconnect-vpn-save-password '/storage/nvme5/new_clones/VBScript/cisco-anyconnect-vpn-save-password' &
git clone https://github.com/palahsu/VCoils '/storage/nvme5/new_clones/VBScript/VCoils' &
git clone https://github.com/valeriofarias/vbsunit '/storage/nvme5/new_clones/VBScript/vbsunit' &
git clone https://github.com/joaopauloaramuni/vbscript '/storage/nvme5/new_clones/VBScript/vbscript' &
git clone https://github.com/Scatty81/zabbix-windows '/storage/nvme5/new_clones/VBScript/zabbix-windows' &
git clone https://github.com/rescenic/autossh '/storage/nvme5/new_clones/VBScript/autossh' &
git clone https://github.com/AdiMarianMutu/MSHTA-VBS-download-and-execute '/storage/nvme5/new_clones/VBScript/MSHTA-VBS-download-and-execute' &
git clone https://github.com/tmizu23/demtool '/storage/nvme5/new_clones/VBScript/demtool' &
git clone https://github.com/fconhkd/admin-scripts '/storage/nvme5/new_clones/VBScript/admin-scripts' &
git clone https://github.com/SQL-FineBuild/v3.5 '/storage/nvme5/new_clones/VBScript/v3.5' &
git clone https://github.com/hemanth-07-11/Fake-virus-Prank '/storage/nvme5/new_clones/VBScript/Fake-virus-Prank' &
git clone https://github.com/zelon88/HR-AV '/storage/nvme5/new_clones/VBScript/HR-AV' &
git clone https://github.com/lilyhcn1/ExcelCodeGenerate '/storage/nvme5/new_clones/VBScript/ExcelCodeGenerate' &
git clone https://github.com/m9nd/ILOVEYOU '/storage/nvme5/new_clones/VBScript/ILOVEYOU' &
git clone https://github.com/TheDarkMythos/windows-malware '/storage/nvme5/new_clones/VBScript/windows-malware' &
git clone https://github.com/Aeryle/library-gui '/storage/nvme5/new_clones/VBScript/library-gui' &
git clone https://github.com/blackjack4494/MS-WinX-ProductKey-Calculator '/storage/nvme5/new_clones/VBScript/MS-WinX-ProductKey-Calculator' &
git clone https://github.com/gnh1201/wsh-js-gtk '/storage/nvme5/new_clones/VBScript/wsh-js-gtk' &
git clone https://github.com/roberttidey/FNISR1013DScope '/storage/nvme5/new_clones/VBScript/FNISR1013DScope' &
git clone https://github.com/ISO-TC211/HMMG '/storage/nvme5/new_clones/VBScript/HMMG' &
git clone https://github.com/cavo789/vbs_classes '/storage/nvme5/new_clones/VBScript/vbs_classes' &
git clone https://github.com/alefranzoni/vba-course '/storage/nvme5/new_clones/VBScript/vba-course' &
git clone https://github.com/jasonadsit/powershell-scripts '/storage/nvme5/new_clones/VBScript/powershell-scripts' &
git clone https://github.com/JRCSTU/wltp '/storage/nvme5/new_clones/VBScript/wltp' &
git clone https://github.com/kurtismash/Windows10Pro_DesktopKiosk '/storage/nvme5/new_clones/VBScript/Windows10Pro_DesktopKiosk' &
git clone https://github.com/tankaishuai/win32exts_for_VBScript '/storage/nvme5/new_clones/VBScript/win32exts_for_VBScript' &
git clone https://github.com/PacktPublishing/Robotic-Process-Automation-with-Automation-Anywhere '/storage/nvme5/new_clones/VBScript/Robotic-Process-Automation-with-Automation-Anywhere' &
git clone https://github.com/smjburton/v_JSON '/storage/nvme5/new_clones/VBScript/v_JSON' &
git clone https://github.com/glytzhkof/all '/storage/nvme5/new_clones/VBScript/all' &
git clone https://github.com/fsctcommunity/Policies '/storage/nvme5/new_clones/VBScript/Policies' &
git clone https://github.com/cavo789/vbs_utilities '/storage/nvme5/new_clones/VBScript/vbs_utilities' &
git clone https://github.com/unblog/outlooksignature '/storage/nvme5/new_clones/VBScript/outlooksignature' &
git clone https://github.com/termux-lab/ddos-whatsapp '/storage/nvme5/new_clones/VBScript/ddos-whatsapp' &
git clone https://github.com/DefectiveStudios/UniMerge-Docs '/storage/nvme5/new_clones/VBScript/UniMerge-Docs' &
git clone https://github.com/CBIIT/bridg-model '/storage/nvme5/new_clones/VBScript/bridg-model' &
git clone https://github.com/Pericena/WhatScriptApp '/storage/nvme5/new_clones/VBScript/WhatScriptApp' &
git clone https://github.com/Krokodil-Fish/test '/storage/nvme5/new_clones/VBScript/test' &
git clone https://github.com/Oaklight/Aria2.conf '/storage/nvme5/new_clones/VBScript/Aria2.conf' &
git clone https://github.com/amymor/AIO-per-game-tweaks '/storage/nvme5/new_clones/VBScript/AIO-per-game-tweaks' &
git clone https://github.com/andyzib/Scripts '/storage/nvme5/new_clones/VBScript/Scripts' &
git clone https://github.com/AlexanderPro/VBScripts '/storage/nvme5/new_clones/VBScript/VBScripts' &
git clone https://github.com/rbicelli/example-admx-template '/storage/nvme5/new_clones/VBScript/example-admx-template' &
git clone https://github.com/antonig/VBScript '/storage/nvme5/new_clones/VBScript/VBScript' &
git clone https://github.com/anthonyalfimov/Lightpad-Block-Sandbox '/storage/nvme5/new_clones/VBScript/Lightpad-Block-Sandbox' &
git clone https://github.com/exploitblizzard/AutoExecute '/storage/nvme5/new_clones/VBScript/AutoExecute' &
git clone https://github.com/ctic-sje-ifsc/ansible '/storage/nvme5/new_clones/VBScript/ansible' &
git clone https://github.com/CW-Khristos/scripts '/storage/nvme5/new_clones/VBScript/scripts' &
git clone https://github.com/dodonki1223/CreateScript '/storage/nvme5/new_clones/VBScript/CreateScript' &
git clone https://github.com/buzzer-re/Write-ups '/storage/nvme5/new_clones/VBScript/Write-ups' &
git clone https://github.com/GamehunterKaan/VBSBadUSB '/storage/nvme5/new_clones/VBScript/VBSBadUSB' &
git clone https://github.com/tatumroaquin/vbe-encoding '/storage/nvme5/new_clones/VBScript/vbe-encoding' &
git clone https://github.com/m4mallu/windows-product-key-finder '/storage/nvme5/new_clones/VBScript/windows-product-key-finder' &
git clone https://github.com/allenk/RyzenMaster-zhTW-Translator '/storage/nvme5/new_clones/VBScript/RyzenMaster-zhTW-Translator' &
git clone https://github.com/gioxx/o365 '/storage/nvme5/new_clones/VBScript/o365' &
git clone https://github.com/OldLiu001/TerminalController.vbs '/storage/nvme5/new_clones/VBScript/TerminalController.vbs' &
git clone https://github.com/ynlamy/mdt_custom_show_make_model '/storage/nvme5/new_clones/VBScript/mdt_custom_show_make_model' &
git clone https://github.com/cavo789/vbs_access_export '/storage/nvme5/new_clones/VBScript/vbs_access_export' &
git clone https://github.com/Pericena/ApkDcx '/storage/nvme5/new_clones/VBScript/ApkDcx' &
git clone https://github.com/andrey-malets/win-boot '/storage/nvme5/new_clones/VBScript/win-boot' &
git clone https://github.com/master7720/my-version-of-the-ILOVEYOU-virus '/storage/nvme5/new_clones/VBScript/my-version-of-the-ILOVEYOU-virus' &
git clone https://github.com/microsoft/AddOutlookJapanHoliday '/storage/nvme5/new_clones/VBScript/AddOutlookJapanHoliday' &
git clone https://github.com/TuomoKu/SPX_Videotool '/storage/nvme5/new_clones/VBScript/SPX_Videotool' &
git clone https://github.com/comol/Usefull-1C-Scripts '/storage/nvme5/new_clones/VBScript/Usefull-1C-Scripts' &
git clone https://github.com/ReneNyffenegger/VBS-MS-Office-App-Creator '/storage/nvme5/new_clones/VBScript/VBS-MS-Office-App-Creator' &
git clone https://github.com/Hennepin-County/MAXIS-scripts '/storage/nvme5/new_clones/VBScript/MAXIS-scripts' &
git clone https://github.com/VHS32/Bug32 '/storage/nvme5/new_clones/VBScript/Bug32' &
git clone https://github.com/rafaelfoster/server-scripts '/storage/nvme5/new_clones/VBScript/server-scripts' &
git clone https://github.com/Panlyg/Leakedware '/storage/nvme5/new_clones/VBScript/Leakedware' &
git clone https://github.com/ReneNyffenegger/runVBAFilesInOffice '/storage/nvme5/new_clones/VBScript/runVBAFilesInOffice' &
git clone https://github.com/YuuyaGitHub/MalwareDataBase '/storage/nvme5/new_clones/VBScript/MalwareDataBase' &
git clone https://github.com/sharkyiwc/PDF24_OCR '/storage/nvme5/new_clones/VBScript/PDF24_OCR' &
git clone https://github.com/Euronymou5/WhatsApp-nuker '/storage/nvme5/new_clones/VBScript/WhatsApp-nuker' &
git clone https://github.com/Los-had/Programas-Simples-com-VBS '/storage/nvme5/new_clones/VBScript/Programas-Simples-com-VBS' &
git clone https://github.com/jabezwinston/vb_scripts '/storage/nvme5/new_clones/VBScript/vb_scripts' &
git clone https://github.com/Neos21/unlock-excel-book-password '/storage/nvme5/new_clones/VBScript/unlock-excel-book-password' &
git clone https://github.com/Gabrielcarvfer/WSLSetup '/storage/nvme5/new_clones/VBScript/WSLSetup' &
git clone https://github.com/cavo789/marknotes_convert '/storage/nvme5/new_clones/VBScript/marknotes_convert' &
git clone https://github.com/ArTicZera/Simple-Email-Worm-in-VBScript '/storage/nvme5/new_clones/VBScript/Simple-Email-Worm-in-VBScript' &
git clone https://github.com/GHbasicuser/RB2RS-Database-Updater '/storage/nvme5/new_clones/VBScript/RB2RS-Database-Updater' &
git clone https://github.com/shuhongfan/OfficeTool '/storage/nvme5/new_clones/VBScript/OfficeTool' &
git clone https://github.com/osamazafar980/Remote-Access-Tool-Kit-RAT- '/storage/nvme5/new_clones/VBScript/Remote-Access-Tool-Kit-RAT-' &
git clone https://github.com/jakOuis/RAT-Crypting-Spreading-Tools '/storage/nvme5/new_clones/VBScript/RAT-Crypting-Spreading-Tools' &
git clone https://github.com/PramodKumarYadav/Rusty '/storage/nvme5/new_clones/VBScript/Rusty' &
