#!/bin/bash

git clone https://github.com/mileszs/ack.vim '/storage/nvme5/new_clones/Vim script/ack.vim' &
git clone https://github.com/godlygeek/tabular '/storage/nvme5/new_clones/Vim script/tabular' &
git clone https://github.com/msanders/snipmate.vim '/storage/nvme5/new_clones/Vim script/snipmate.vim' &
git clone https://github.com/garybernhardt/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/kchmck/vim-coffee-script '/storage/nvme5/new_clones/Vim script/vim-coffee-script' &
git clone https://github.com/learnbyexample/scripting_course '/storage/nvme5/new_clones/Vim script/scripting_course' &
git clone https://github.com/lambdalisue/vim-fern '/storage/nvme5/new_clones/Vim script/vim-fern' &
git clone https://github.com/MaxMEllon/vim-jsx-pretty '/storage/nvme5/new_clones/Vim script/vim-jsx-pretty' &
git clone https://github.com/prabirshrestha/asyncomplete.vim '/storage/nvme5/new_clones/Vim script/asyncomplete.vim' &
git clone https://github.com/lymslive/vimllearn '/storage/nvme5/new_clones/Vim script/vimllearn' &
git clone https://github.com/Shougo/vimfiler.vim '/storage/nvme5/new_clones/Vim script/vimfiler.vim' &
git clone https://github.com/michaeljsmith/vim-indent-object '/storage/nvme5/new_clones/Vim script/vim-indent-object' &
git clone https://github.com/jamessan/vim-gnupg '/storage/nvme5/new_clones/Vim script/vim-gnupg' &
git clone https://github.com/tpope/vim-scriptease '/storage/nvme5/new_clones/Vim script/vim-scriptease' &
git clone https://github.com/bkad/CamelCaseMotion '/storage/nvme5/new_clones/Vim script/CamelCaseMotion' &
git clone https://github.com/rhysd/8cc.vim '/storage/nvme5/new_clones/Vim script/8cc.vim' &
git clone https://github.com/dag/vim-fish '/storage/nvme5/new_clones/Vim script/vim-fish' &
git clone https://github.com/xolox/vim-misc '/storage/nvme5/new_clones/Vim script/vim-misc' &
git clone https://github.com/hdima/python-syntax '/storage/nvme5/new_clones/Vim script/python-syntax' &
git clone https://github.com/durdn/cfg '/storage/nvme5/new_clones/Vim script/cfg' &
git clone https://github.com/qpkorr/vim-bufkill '/storage/nvme5/new_clones/Vim script/vim-bufkill' &
git clone https://github.com/thinca/vim-themis '/storage/nvme5/new_clones/Vim script/vim-themis' &
git clone https://github.com/mattjmorrison/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/vivien/vim-linux-coding-style '/storage/nvme5/new_clones/Vim script/vim-linux-coding-style' &
git clone https://github.com/kana/vim-vspec '/storage/nvme5/new_clones/Vim script/vim-vspec' &
git clone https://github.com/jamis/fuzzyfinder_textmate '/storage/nvme5/new_clones/Vim script/fuzzyfinder_textmate' &
git clone https://github.com/ZSaberLv0/ZFVimIM '/storage/nvme5/new_clones/Vim script/ZFVimIM' &
git clone https://github.com/Netherdrake/Dotfiles '/storage/nvme5/new_clones/Vim script/Dotfiles' &
git clone https://github.com/vim-skk/eskk.vim '/storage/nvme5/new_clones/Vim script/eskk.vim' &
git clone https://github.com/ciaranm/detectindent '/storage/nvme5/new_clones/Vim script/detectindent' &
git clone https://github.com/blueyed/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/vim-jp/vim-vimlparser '/storage/nvme5/new_clones/Vim script/vim-vimlparser' &
git clone https://github.com/Shougo/context_filetype.vim '/storage/nvme5/new_clones/Vim script/context_filetype.vim' &
git clone https://github.com/BurntSushi/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/sophacles/vim-processing '/storage/nvme5/new_clones/Vim script/vim-processing' &
git clone https://github.com/vim-jp/go-vimlparser '/storage/nvme5/new_clones/Vim script/go-vimlparser' &
git clone https://github.com/ahw/vim-hooks '/storage/nvme5/new_clones/Vim script/vim-hooks' &
git clone https://github.com/2072/PHP-Indenting-for-VIm '/storage/nvme5/new_clones/Vim script/PHP-Indenting-for-VIm' &
git clone https://github.com/Integralist/ProVim '/storage/nvme5/new_clones/Vim script/ProVim' &
git clone https://github.com/dbakker/vim-projectroot '/storage/nvme5/new_clones/Vim script/vim-projectroot' &
git clone https://github.com/Shougo/neco-vim '/storage/nvme5/new_clones/Vim script/neco-vim' &
git clone https://github.com/anzhihe/Efficient-office '/storage/nvme5/new_clones/Vim script/Efficient-office' &
git clone https://github.com/mattn/vim-brain '/storage/nvme5/new_clones/Vim script/vim-brain' &
git clone https://github.com/sunaku/vim-unbundle '/storage/nvme5/new_clones/Vim script/vim-unbundle' &
git clone https://github.com/WolfgangMehner/bash-support '/storage/nvme5/new_clones/Vim script/bash-support' &
git clone https://github.com/vim-scripts/bash-support.vim '/storage/nvme5/new_clones/Vim script/bash-support.vim' &
git clone https://github.com/mfukar/robotframework-vim '/storage/nvme5/new_clones/Vim script/robotframework-vim' &
git clone https://github.com/itspriddle/vim-shellcheck '/storage/nvme5/new_clones/Vim script/vim-shellcheck' &
git clone https://github.com/vim-scripts/indentpython.vim '/storage/nvme5/new_clones/Vim script/indentpython.vim' &
git clone https://github.com/davidbeckingsale/writegood.vim '/storage/nvme5/new_clones/Vim script/writegood.vim' &
git clone https://github.com/qpkorr/vim-renamer '/storage/nvme5/new_clones/Vim script/vim-renamer' &
git clone https://github.com/MilesCranmer/gso '/storage/nvme5/new_clones/Vim script/gso' &
git clone https://github.com/xolox/vim-reload '/storage/nvme5/new_clones/Vim script/vim-reload' &
git clone https://github.com/vim-scripts/L9 '/storage/nvme5/new_clones/Vim script/L9' &
git clone https://github.com/jiangmiao/simple-javascript-indenter '/storage/nvme5/new_clones/Vim script/simple-javascript-indenter' &
git clone https://github.com/haya14busa/underscore.vim '/storage/nvme5/new_clones/Vim script/underscore.vim' &
git clone https://github.com/vim-scripts/JavaScript-Indent '/storage/nvme5/new_clones/Vim script/JavaScript-Indent' &
git clone https://github.com/taq/vim-git-branch-info '/storage/nvme5/new_clones/Vim script/vim-git-branch-info' &
git clone https://github.com/ghewgill/vim-scmdiff '/storage/nvme5/new_clones/Vim script/vim-scmdiff' &
git clone https://github.com/cocopon/pgmnt.vim '/storage/nvme5/new_clones/Vim script/pgmnt.vim' &
git clone https://github.com/jayflo/vim-skip '/storage/nvme5/new_clones/Vim script/vim-skip' &
git clone https://github.com/shibumi/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/vsbuffalo/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/jeffbuttars/Vimdown '/storage/nvme5/new_clones/Vim script/Vimdown' &
git clone https://github.com/captbaritone/better-indent-support-for-php-with-html '/storage/nvme5/new_clones/Vim script/better-indent-support-for-php-with-html' &
git clone https://github.com/ingydotnet/yaml-vim '/storage/nvme5/new_clones/Vim script/yaml-vim' &
git clone https://github.com/haya14busa/vim-debugger '/storage/nvme5/new_clones/Vim script/vim-debugger' &
git clone https://github.com/vim-jp/syntax-vim-ex '/storage/nvme5/new_clones/Vim script/syntax-vim-ex' &
git clone https://github.com/rbtnn/vim-rabbit-ui '/storage/nvme5/new_clones/Vim script/vim-rabbit-ui' &
git clone https://github.com/adamlowe/vim-slurper '/storage/nvme5/new_clones/Vim script/vim-slurper' &
git clone https://github.com/rbtnn/vim-game_engine '/storage/nvme5/new_clones/Vim script/vim-game_engine' &
git clone https://github.com/vim-scripts/perl-support.vim '/storage/nvme5/new_clones/Vim script/perl-support.vim' &
git clone https://github.com/kh3phr3n/python-syntax '/storage/nvme5/new_clones/Vim script/python-syntax' &
git clone https://github.com/iandoe/vim-osx-colorpicker '/storage/nvme5/new_clones/Vim script/vim-osx-colorpicker' &
git clone https://github.com/bradymholt/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/GatoImorrivel/GAR '/storage/nvme5/new_clones/Vim script/GAR' &
git clone https://github.com/mtwb47/dwmricer '/storage/nvme5/new_clones/Vim script/dwmricer' &
git clone https://github.com/khaveesh/vim-fish-syntax '/storage/nvme5/new_clones/Vim script/vim-fish-syntax' &
git clone https://github.com/machakann/vim-Verdin '/storage/nvme5/new_clones/Vim script/vim-Verdin' &
git clone https://github.com/Bakudankun/qline.vim '/storage/nvme5/new_clones/Vim script/qline.vim' &
git clone https://github.com/joeytwiddle/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/lambdalisue/vim-backslash '/storage/nvme5/new_clones/Vim script/vim-backslash' &
git clone https://github.com/idbrii/daveconfig '/storage/nvme5/new_clones/Vim script/daveconfig' &
git clone https://github.com/hiyali/nvim '/storage/nvme5/new_clones/Vim script/nvim' &
git clone https://github.com/haya14busa/vital-power-assert '/storage/nvme5/new_clones/Vim script/vital-power-assert' &
git clone https://github.com/sophacles/vim-bundle-mako '/storage/nvme5/new_clones/Vim script/vim-bundle-mako' &
git clone https://github.com/ELLIOTTCABLE/System '/storage/nvme5/new_clones/Vim script/System' &
git clone https://github.com/pgilad/vim-skeletons '/storage/nvme5/new_clones/Vim script/vim-skeletons' &
git clone https://github.com/glts/vim-magnum '/storage/nvme5/new_clones/Vim script/vim-magnum' &
git clone https://github.com/h1mesuke/vim-unittest '/storage/nvme5/new_clones/Vim script/vim-unittest' &
git clone https://github.com/docteurklein/php-getter-setter.vim '/storage/nvme5/new_clones/Vim script/php-getter-setter.vim' &
git clone https://github.com/vobornik/vim-mql4 '/storage/nvme5/new_clones/Vim script/vim-mql4' &
git clone https://github.com/motemen/hatena-vim '/storage/nvme5/new_clones/Vim script/hatena-vim' &
git clone https://github.com/c9s/vim-makefile '/storage/nvme5/new_clones/Vim script/vim-makefile' &
git clone https://github.com/pit-ray/vim-autograd '/storage/nvme5/new_clones/Vim script/vim-autograd' &
git clone https://github.com/id774/scripts '/storage/nvme5/new_clones/Vim script/scripts' &
git clone https://github.com/WolfgangMehner/perl-support '/storage/nvme5/new_clones/Vim script/perl-support' &
git clone https://github.com/sagotsky/.dotfiles '/storage/nvme5/new_clones/Vim script/.dotfiles' &
git clone https://github.com/tweekmonster/exception.vim '/storage/nvme5/new_clones/Vim script/exception.vim' &
git clone https://github.com/rbtnn/vim-vimconsole '/storage/nvme5/new_clones/Vim script/vim-vimconsole' &
git clone https://github.com/MarcWeber/vim-addon-nix '/storage/nvme5/new_clones/Vim script/vim-addon-nix' &
git clone https://github.com/vim-scripts/VimIRC.vim '/storage/nvme5/new_clones/Vim script/VimIRC.vim' &
git clone https://github.com/felixhummel/setcolors.vim '/storage/nvme5/new_clones/Vim script/setcolors.vim' &
git clone https://github.com/koron/imcsc-vim '/storage/nvme5/new_clones/Vim script/imcsc-vim' &
git clone https://github.com/dmalikov/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/WolfgangMehner/lua-support '/storage/nvme5/new_clones/Vim script/lua-support' &
git clone https://github.com/vim-scripts/python.vim--Vasiliev '/storage/nvme5/new_clones/Vim script/python.vim--Vasiliev' &
git clone https://github.com/dimasg/vim-mark '/storage/nvme5/new_clones/Vim script/vim-mark' &
git clone https://github.com/kopri-nb/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/exercism/vimscript '/storage/nvme5/new_clones/Vim script/vimscript' &
git clone https://github.com/gumayunov/homedir '/storage/nvme5/new_clones/Vim script/homedir' &
git clone https://github.com/hungpham3112/vide '/storage/nvme5/new_clones/Vim script/vide' &
git clone https://github.com/modood/vimrc '/storage/nvme5/new_clones/Vim script/vimrc' &
git clone https://github.com/koron/chalice '/storage/nvme5/new_clones/Vim script/chalice' &
git clone https://github.com/mityu/vim-applescript '/storage/nvme5/new_clones/Vim script/vim-applescript' &
git clone https://github.com/dahu/LearnVimL '/storage/nvme5/new_clones/Vim script/LearnVimL' &
git clone https://github.com/Rican7/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/JoseBlanca/vim-for-python '/storage/nvme5/new_clones/Vim script/vim-for-python' &
git clone https://github.com/vim-scripts/Mark '/storage/nvme5/new_clones/Vim script/Mark' &
git clone https://github.com/dterei/VimBookmarking '/storage/nvme5/new_clones/Vim script/VimBookmarking' &
git clone https://github.com/ironcamel/vim-script-runner '/storage/nvme5/new_clones/Vim script/vim-script-runner' &
git clone https://github.com/kartik1998/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/chenkaie/DotFiles '/storage/nvme5/new_clones/Vim script/DotFiles' &
git clone https://github.com/jlarimer/android-stuff '/storage/nvme5/new_clones/Vim script/android-stuff' &
git clone https://github.com/AndrewRadev/vim-eco '/storage/nvme5/new_clones/Vim script/vim-eco' &
git clone https://github.com/vim-scripts/AfterColors.vim '/storage/nvme5/new_clones/Vim script/AfterColors.vim' &
git clone https://github.com/metalelf0/VimColorSchemeTest-Ruby '/storage/nvme5/new_clones/Vim script/VimColorSchemeTest-Ruby' &
git clone https://github.com/MicahElliott/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/Termplexed/vfix '/storage/nvme5/new_clones/Vim script/vfix' &
git clone https://github.com/guns/haus '/storage/nvme5/new_clones/Vim script/haus' &
git clone https://github.com/vim-scripts/autoload_cscope.vim '/storage/nvme5/new_clones/Vim script/autoload_cscope.vim' &
git clone https://github.com/jvoorhis/coq.vim '/storage/nvme5/new_clones/Vim script/coq.vim' &
git clone https://github.com/lambdalisue/vim-amake '/storage/nvme5/new_clones/Vim script/vim-amake' &
git clone https://github.com/GatoImorrivel/YAR '/storage/nvme5/new_clones/Vim script/YAR' &
git clone https://github.com/hdima/vim-scripts '/storage/nvme5/new_clones/Vim script/vim-scripts' &
git clone https://github.com/yinflying/matlab.vim '/storage/nvme5/new_clones/Vim script/matlab.vim' &
git clone https://github.com/salamander2/RaspberryPI_installs '/storage/nvme5/new_clones/Vim script/RaspberryPI_installs' &
git clone https://github.com/KitN/nand2-vim-syn '/storage/nvme5/new_clones/Vim script/nand2-vim-syn' &
git clone https://github.com/EsrafilElahi/vim-linux '/storage/nvme5/new_clones/Vim script/vim-linux' &
git clone https://github.com/everett1992/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/MaxMEllon/vim-shiny '/storage/nvme5/new_clones/Vim script/vim-shiny' &
git clone https://github.com/jiangyinzuo/vimrc '/storage/nvme5/new_clones/Vim script/vimrc' &
git clone https://github.com/mockee/vitamine '/storage/nvme5/new_clones/Vim script/vitamine' &
git clone https://github.com/Shougo/vesting '/storage/nvme5/new_clones/Vim script/vesting' &
git clone https://github.com/svaksha/yaksha '/storage/nvme5/new_clones/Vim script/yaksha' &
git clone https://github.com/michalliu/jsoncodecs.vim '/storage/nvme5/new_clones/Vim script/jsoncodecs.vim' &
git clone https://github.com/cohama/the-ocamlspot.vim '/storage/nvme5/new_clones/Vim script/the-ocamlspot.vim' &
git clone https://github.com/jsks/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/1995eaton/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/prodhe/acme-setup '/storage/nvme5/new_clones/Vim script/acme-setup' &
git clone https://github.com/adambiggs/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/projektile/dotfiles-scripts '/storage/nvme5/new_clones/Vim script/dotfiles-scripts' &
git clone https://github.com/uyu423/vimrc-vundle-script '/storage/nvme5/new_clones/Vim script/vimrc-vundle-script' &
git clone https://github.com/vim-scripts/vim-coffee-script '/storage/nvme5/new_clones/Vim script/vim-coffee-script' &
git clone https://github.com/yalesov/vim-ember-script '/storage/nvme5/new_clones/Vim script/vim-ember-script' &
git clone https://github.com/GirlBossRush/personal_preferences '/storage/nvme5/new_clones/Vim script/personal_preferences' &
git clone https://github.com/fcamel/configs '/storage/nvme5/new_clones/Vim script/configs' &
git clone https://github.com/vim-scripts/underscore.vim '/storage/nvme5/new_clones/Vim script/underscore.vim' &
git clone https://github.com/Clavelito/indent-awk.vim '/storage/nvme5/new_clones/Vim script/indent-awk.vim' &
git clone https://github.com/Smattr/mattutils '/storage/nvme5/new_clones/Vim script/mattutils' &
git clone https://github.com/philipforget/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/tsiemens/vim-aftercolors '/storage/nvme5/new_clones/Vim script/vim-aftercolors' &
git clone https://github.com/erossignon/BowlingKata-NodeJs-VIM '/storage/nvme5/new_clones/Vim script/BowlingKata-NodeJs-VIM' &
git clone https://github.com/jeffreytse/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/vim-scripts/JavaScript-syntax '/storage/nvme5/new_clones/Vim script/JavaScript-syntax' &
git clone https://github.com/unixbhaskar/AdminScripts '/storage/nvme5/new_clones/Vim script/AdminScripts' &
git clone https://github.com/rccggl/macOS_settings '/storage/nvme5/new_clones/Vim script/macOS_settings' &
git clone https://github.com/vim-scripts/indenthtml.vim '/storage/nvme5/new_clones/Vim script/indenthtml.vim' &
git clone https://github.com/grepsedawk/.dotfiles '/storage/nvme5/new_clones/Vim script/.dotfiles' &
git clone https://github.com/rbtnn/vim-vimscript_indentexpr '/storage/nvme5/new_clones/Vim script/vim-vimscript_indentexpr' &
git clone https://github.com/mkaz/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/rygwdn/rope-omni '/storage/nvme5/new_clones/Vim script/rope-omni' &
git clone https://github.com/jaantollander/dotfiles-arch '/storage/nvme5/new_clones/Vim script/dotfiles-arch' &
git clone https://github.com/vim-scripts/ack.vim '/storage/nvme5/new_clones/Vim script/ack.vim' &
git clone https://github.com/shabiel/vim-mumps-tools '/storage/nvme5/new_clones/Vim script/vim-mumps-tools' &
git clone https://github.com/jubnzv/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/h1mesuke/vim-benchmark '/storage/nvme5/new_clones/Vim script/vim-benchmark' &
git clone https://github.com/farajyeet/vim '/storage/nvme5/new_clones/Vim script/vim' &
git clone https://github.com/marslo/marslo.vim '/storage/nvme5/new_clones/Vim script/marslo.vim' &
git clone https://github.com/rbtnn/vim-vimscript_lasterror '/storage/nvme5/new_clones/Vim script/vim-vimscript_lasterror' &
git clone https://github.com/jbbarth/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/masukomi/masuconfigs '/storage/nvme5/new_clones/Vim script/masuconfigs' &
git clone https://github.com/sqwishy/vim-sqf-syntax '/storage/nvme5/new_clones/Vim script/vim-sqf-syntax' &
git clone https://github.com/ZSaberLv0/ZFVimJob '/storage/nvme5/new_clones/Vim script/ZFVimJob' &
git clone https://github.com/da-x/vim-syntax-legend '/storage/nvme5/new_clones/Vim script/vim-syntax-legend' &
git clone https://github.com/WolfgangMehner/awk-support '/storage/nvme5/new_clones/Vim script/awk-support' &
git clone https://github.com/dag10/drew-vimrc '/storage/nvme5/new_clones/Vim script/drew-vimrc' &
git clone https://github.com/vim-scripts/ccase.vim '/storage/nvme5/new_clones/Vim script/ccase.vim' &
git clone https://github.com/kannokanno/vmock '/storage/nvme5/new_clones/Vim script/vmock' &
git clone https://github.com/normful/portable-dotfiles '/storage/nvme5/new_clones/Vim script/portable-dotfiles' &
git clone https://github.com/paper777/env_script '/storage/nvme5/new_clones/Vim script/env_script' &
git clone https://github.com/mhartzel/vim_python3_ide_installer '/storage/nvme5/new_clones/Vim script/vim_python3_ide_installer' &
git clone https://github.com/weakish/rcshell.vim '/storage/nvme5/new_clones/Vim script/rcshell.vim' &
git clone https://github.com/jrk/vim-ocaml '/storage/nvme5/new_clones/Vim script/vim-ocaml' &
git clone https://github.com/christophgysin/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/zeek/vim-zeek '/storage/nvme5/new_clones/Vim script/vim-zeek' &
git clone https://github.com/vim-scripts/PHP-correct-Indenting '/storage/nvme5/new_clones/Vim script/PHP-correct-Indenting' &
git clone https://github.com/thinca/vim-vparsec '/storage/nvme5/new_clones/Vim script/vim-vparsec' &
git clone https://github.com/rajatvig/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/thinca/vim-jautil '/storage/nvme5/new_clones/Vim script/vim-jautil' &
git clone https://github.com/pastjean/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/abesto/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/godvmxi/tools '/storage/nvme5/new_clones/Vim script/tools' &
git clone https://github.com/hrp/EnhancedCommentify '/storage/nvme5/new_clones/Vim script/EnhancedCommentify' &
git clone https://github.com/termoshtt/toggl.vim '/storage/nvme5/new_clones/Vim script/toggl.vim' &
git clone https://github.com/soarpenguin/bash-scripts '/storage/nvme5/new_clones/Vim script/bash-scripts' &
git clone https://github.com/mbriggs/mark.vim '/storage/nvme5/new_clones/Vim script/mark.vim' &
git clone https://github.com/mjbrownie/pythoncomplete.vim '/storage/nvme5/new_clones/Vim script/pythoncomplete.vim' &
git clone https://github.com/sharpsaw/vim-dots '/storage/nvme5/new_clones/Vim script/vim-dots' &
git clone https://github.com/vim-scripts/Vimya '/storage/nvme5/new_clones/Vim script/Vimya' &
git clone https://github.com/renderedtext/vim-elixir-alternative-files '/storage/nvme5/new_clones/Vim script/vim-elixir-alternative-files' &
git clone https://github.com/andymeneely/scripts-settings '/storage/nvme5/new_clones/Vim script/scripts-settings' &
git clone https://github.com/kevinw/vim '/storage/nvme5/new_clones/Vim script/vim' &
git clone https://github.com/flatcap/vim-piper '/storage/nvme5/new_clones/Vim script/vim-piper' &
git clone https://github.com/vim-jp/vim-sweep_trail '/storage/nvme5/new_clones/Vim script/vim-sweep_trail' &
git clone https://github.com/h1mesuke/vim-oop '/storage/nvme5/new_clones/Vim script/vim-oop' &
git clone https://github.com/MarcWeber/vim-addon-ocaml '/storage/nvme5/new_clones/Vim script/vim-addon-ocaml' &
git clone https://github.com/allenhwkim/nextfile.vim '/storage/nvme5/new_clones/Vim script/nextfile.vim' &
git clone https://github.com/darkk/home '/storage/nvme5/new_clones/Vim script/home' &
git clone https://github.com/jaburns/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/igemnace/vim-playground '/storage/nvme5/new_clones/Vim script/vim-playground' &
git clone https://github.com/vim-scripts/PreciseJump '/storage/nvme5/new_clones/Vim script/PreciseJump' &
git clone https://github.com/ZSaberLv0/ZFVimToc '/storage/nvme5/new_clones/Vim script/ZFVimToc' &
git clone https://github.com/tupton/vim-support '/storage/nvme5/new_clones/Vim script/vim-support' &
git clone https://github.com/datchley/mysystem '/storage/nvme5/new_clones/Vim script/mysystem' &
git clone https://github.com/glenngillen/nitrous.io-pairing-setup '/storage/nvme5/new_clones/Vim script/nitrous.io-pairing-setup' &
git clone https://github.com/01walid/my-arch-stuff '/storage/nvme5/new_clones/Vim script/my-arch-stuff' &
git clone https://github.com/AnapalOne/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/jesseschalken/list-text-object '/storage/nvme5/new_clones/Vim script/list-text-object' &
git clone https://github.com/jneen/eco.vim '/storage/nvme5/new_clones/Vim script/eco.vim' &
git clone https://github.com/vim-scripts/jcommenter.vim '/storage/nvme5/new_clones/Vim script/jcommenter.vim' &
git clone https://github.com/vim-scripts/jpythonfold.vim '/storage/nvme5/new_clones/Vim script/jpythonfold.vim' &
git clone https://github.com/vim-scripts/groovyindent-unix '/storage/nvme5/new_clones/Vim script/groovyindent-unix' &
git clone https://github.com/vim-scripts/JavaScript-Libraries-Syntax '/storage/nvme5/new_clones/Vim script/JavaScript-Libraries-Syntax' &
git clone https://github.com/lotabout/ywvim '/storage/nvme5/new_clones/Vim script/ywvim' &
git clone https://github.com/vim-scripts/sort-python-imports '/storage/nvme5/new_clones/Vim script/sort-python-imports' &
git clone https://github.com/Yggdroot/vim-mark '/storage/nvme5/new_clones/Vim script/vim-mark' &
git clone https://github.com/zhuochun/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/msbmsb/porter-stem.vim '/storage/nvme5/new_clones/Vim script/porter-stem.vim' &
git clone https://github.com/daviddias/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/RodrigoCMoraes/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/wting/dotvim '/storage/nvme5/new_clones/Vim script/dotvim' &
git clone https://github.com/kyoro/myconf '/storage/nvme5/new_clones/Vim script/myconf' &
git clone https://github.com/vim-scripts/lh-vim-lib '/storage/nvme5/new_clones/Vim script/lh-vim-lib' &
git clone https://github.com/dang/scripts '/storage/nvme5/new_clones/Vim script/scripts' &
git clone https://github.com/Kaikj/bash-scripts '/storage/nvme5/new_clones/Vim script/bash-scripts' &
git clone https://github.com/MSadeghzadehG/just-run-it '/storage/nvme5/new_clones/Vim script/just-run-it' &
git clone https://github.com/thinca/vim-guicolorscheme '/storage/nvme5/new_clones/Vim script/vim-guicolorscheme' &
git clone https://github.com/mattn/vim9script-logistic-regression-iris '/storage/nvme5/new_clones/Vim script/vim9script-logistic-regression-iris' &
git clone https://github.com/vim-scripts/Decho '/storage/nvme5/new_clones/Vim script/Decho' &
git clone https://github.com/quisquous/vim-kolmafia '/storage/nvme5/new_clones/Vim script/vim-kolmafia' &
git clone https://github.com/suderman/source.vim '/storage/nvme5/new_clones/Vim script/source.vim' &
git clone https://github.com/ShotaKitazawa/dotfiles '/storage/nvme5/new_clones/Vim script/dotfiles' &
git clone https://github.com/thinca/vim-scall '/storage/nvme5/new_clones/Vim script/vim-scall' &
git clone https://github.com/Buckmeister/nvim-nightly '/storage/nvme5/new_clones/Vim script/nvim-nightly' &
git clone https://github.com/tomtom/spec_vim '/storage/nvme5/new_clones/Vim script/spec_vim' &
git clone https://github.com/cdlm/infrastructure '/storage/nvme5/new_clones/Vim script/infrastructure' &
git clone https://github.com/aiya000/dhall-to-vim '/storage/nvme5/new_clones/Vim script/dhall-to-vim' &
git clone https://github.com/obcat/voyager.vim '/storage/nvme5/new_clones/Vim script/voyager.vim' &
git clone https://github.com/haya14busa/vim-snoopy '/storage/nvme5/new_clones/Vim script/vim-snoopy' &
git clone https://github.com/vim-scripts/vimpp '/storage/nvme5/new_clones/Vim script/vimpp' &
git clone https://github.com/fsabado/cadence-skill '/storage/nvme5/new_clones/Vim script/cadence-skill' &
git clone https://github.com/gilsondev/lizard '/storage/nvme5/new_clones/Vim script/lizard' &
git clone https://github.com/rbtnn/vim-tips '/storage/nvme5/new_clones/Vim script/vim-tips' &
git clone https://github.com/jasonroelofs/dev '/storage/nvme5/new_clones/Vim script/dev' &
