#!/bin/bash

git clone https://github.com/broadinstitute/warp '/storage/nvme5/new_clones/WDL/warp' &
git clone https://github.com/gatk-workflows/gatk4-data-processing '/storage/nvme5/new_clones/WDL/gatk4-data-processing' &
git clone https://github.com/gatk-workflows/gatk4-germline-snps-indels '/storage/nvme5/new_clones/WDL/gatk4-germline-snps-indels' &
git clone https://github.com/openwdl/learn-wdl '/storage/nvme5/new_clones/WDL/learn-wdl' &
git clone https://github.com/biowdl/tasks '/storage/nvme5/new_clones/WDL/tasks' &
git clone https://github.com/gatk-workflows/gatk4-somatic-snvs-indels '/storage/nvme5/new_clones/WDL/gatk4-somatic-snvs-indels' &
git clone https://github.com/gatk-workflows/gatk4-rnaseq-germline-snps-indels '/storage/nvme5/new_clones/WDL/gatk4-rnaseq-germline-snps-indels' &
git clone https://github.com/broadinstitute/viral-pipelines '/storage/nvme5/new_clones/WDL/viral-pipelines' &
git clone https://github.com/lilab-bcb/cumulus '/storage/nvme5/new_clones/WDL/cumulus' &
git clone https://github.com/ENCODE-DCC/hic-pipeline '/storage/nvme5/new_clones/WDL/hic-pipeline' &
git clone https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline '/storage/nvme5/new_clones/WDL/five-dollar-genome-analysis-pipeline' &
git clone https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels '/storage/nvme5/new_clones/WDL/broad-prod-wgs-germline-snps-indels' &
git clone https://github.com/PacificBiosciences/HiFi-human-WGS-WDL '/storage/nvme5/new_clones/WDL/HiFi-human-WGS-WDL' &
git clone https://github.com/gatk-workflows/gatk4-exome-analysis-pipeline '/storage/nvme5/new_clones/WDL/gatk4-exome-analysis-pipeline' &
git clone https://github.com/gatk-workflows/gatk3-4-rnaseq-germline-snps-indels '/storage/nvme5/new_clones/WDL/gatk3-4-rnaseq-germline-snps-indels' &
git clone https://github.com/grst/snakemake_nextflow_wdl '/storage/nvme5/new_clones/WDL/snakemake_nextflow_wdl' &
git clone https://github.com/hall-lab/sv-pipeline '/storage/nvme5/new_clones/WDL/sv-pipeline' &
git clone https://github.com/HumanCellAtlas/skylab '/storage/nvme5/new_clones/WDL/skylab' &
git clone https://github.com/ENCODE-DCC/long-read-rna-pipeline '/storage/nvme5/new_clones/WDL/long-read-rna-pipeline' &
git clone https://github.com/gatk-workflows/gatk4-somatic-cnvs '/storage/nvme5/new_clones/WDL/gatk4-somatic-cnvs' &
git clone https://github.com/gatk-workflows/seq-format-conversion '/storage/nvme5/new_clones/WDL/seq-format-conversion' &
git clone https://github.com/stjudecloud/workflows '/storage/nvme5/new_clones/WDL/workflows' &
git clone https://github.com/nanoporegenomics/napu_wf '/storage/nvme5/new_clones/WDL/napu_wf' &
git clone https://github.com/biowdl/RNA-seq '/storage/nvme5/new_clones/WDL/RNA-seq' &
git clone https://github.com/clara-parabricks-workflows/parabricks-wdl '/storage/nvme5/new_clones/WDL/parabricks-wdl' &
git clone https://github.com/FINNGEN/finemapping-pipeline '/storage/nvme5/new_clones/WDL/finemapping-pipeline' &
git clone https://github.com/gatk-workflows/gatk4-genome-processing-pipeline '/storage/nvme5/new_clones/WDL/gatk4-genome-processing-pipeline' &
git clone https://github.com/broadinstitute/GATK-for-Microbes '/storage/nvme5/new_clones/WDL/GATK-for-Microbes' &
git clone https://github.com/biowdl/germline-DNA '/storage/nvme5/new_clones/WDL/germline-DNA' &
git clone https://github.com/broadinstitute/palantir-workflows '/storage/nvme5/new_clones/WDL/palantir-workflows' &
git clone https://github.com/gatk-workflows/gatk4-mitochondria-pipeline '/storage/nvme5/new_clones/WDL/gatk4-mitochondria-pipeline' &
git clone https://github.com/vgteam/vg_wdl '/storage/nvme5/new_clones/WDL/vg_wdl' &
git clone https://github.com/broadinstitute/epi-SHARE-seq-pipeline '/storage/nvme5/new_clones/WDL/epi-SHARE-seq-pipeline' &
git clone https://github.com/ENCODE-DCC/mirna-seq-pipeline '/storage/nvme5/new_clones/WDL/mirna-seq-pipeline' &
git clone https://github.com/FINNGEN/saige-pipelines '/storage/nvme5/new_clones/WDL/saige-pipelines' &
git clone https://github.com/malariagen/pipelines '/storage/nvme5/new_clones/WDL/pipelines' &
git clone https://github.com/dnanexus-rnd/liftover_plink_beds '/storage/nvme5/new_clones/WDL/liftover_plink_beds' &
git clone https://github.com/FredHutch/reproducible-workflows '/storage/nvme5/new_clones/WDL/reproducible-workflows' &
git clone https://github.com/PacificBiosciences/pb-human-wgs-workflow-wdl '/storage/nvme5/new_clones/WDL/pb-human-wgs-workflow-wdl' &
git clone https://github.com/Intel-HLS/BIGstack '/storage/nvme5/new_clones/WDL/BIGstack' &
git clone https://github.com/DataBiosphere/topmed-workflows '/storage/nvme5/new_clones/WDL/topmed-workflows' &
git clone https://github.com/gatk-workflows/gatk4-pathseq '/storage/nvme5/new_clones/WDL/gatk4-pathseq' &
git clone https://github.com/dnanexus-rnd/DeepVariant-GLnexus-WDL '/storage/nvme5/new_clones/WDL/DeepVariant-GLnexus-WDL' &
git clone https://github.com/Cristianetaniguti/Reads2Map '/storage/nvme5/new_clones/WDL/Reads2Map' &
git clone https://github.com/freeseek/mochawdl '/storage/nvme5/new_clones/WDL/mochawdl' &
git clone https://github.com/Sentieon/Sentieon-WDL '/storage/nvme5/new_clones/WDL/Sentieon-WDL' &
git clone https://github.com/truwl/capanno '/storage/nvme5/new_clones/WDL/capanno' &
git clone https://github.com/kbolton-lab/ArCH '/storage/nvme5/new_clones/WDL/ArCH' &
git clone https://github.com/biowdl/somatic-variantcalling '/storage/nvme5/new_clones/WDL/somatic-variantcalling' &
git clone https://github.com/FINNGEN/regenie-pipelines '/storage/nvme5/new_clones/WDL/regenie-pipelines' &
git clone https://github.com/gatk-workflows/gatk4-cnn-variant-filter '/storage/nvme5/new_clones/WDL/gatk4-cnn-variant-filter' &
git clone https://github.com/biowdl/structural-variantcalling '/storage/nvme5/new_clones/WDL/structural-variantcalling' &
git clone https://github.com/babelomics/MIGNON '/storage/nvme5/new_clones/WDL/MIGNON' &
git clone https://github.com/my-rna-health/rna-seq '/storage/nvme5/new_clones/WDL/rna-seq' &
git clone https://github.com/biowdl/WGSinCancerDiagnostics '/storage/nvme5/new_clones/WDL/WGSinCancerDiagnostics' &
git clone https://github.com/broadinstitute/fungal-wdl '/storage/nvme5/new_clones/WDL/fungal-wdl' &
git clone https://github.com/microbiomedata/WorkflowPlanning '/storage/nvme5/new_clones/WDL/WorkflowPlanning' &
git clone https://github.com/gusevlab/panel-imp '/storage/nvme5/new_clones/WDL/panel-imp' &
git clone https://github.com/broadinstitute/cellprofiler-on-Terra '/storage/nvme5/new_clones/WDL/cellprofiler-on-Terra' &
git clone https://github.com/aligenomics/gtx-fpga '/storage/nvme5/new_clones/WDL/gtx-fpga' &
git clone https://github.com/amp-pd/amp-pd-workflows '/storage/nvme5/new_clones/WDL/amp-pd-workflows' &
git clone https://github.com/DataBiosphere/analysis_pipeline_WDL '/storage/nvme5/new_clones/WDL/analysis_pipeline_WDL' &
git clone https://github.com/mendelics/bioinfo-praticas '/storage/nvme5/new_clones/WDL/bioinfo-praticas' &
git clone https://github.com/stjude/seaseq '/storage/nvme5/new_clones/WDL/seaseq' &
git clone https://github.com/wustl-oncology/analysis-wdls '/storage/nvme5/new_clones/WDL/analysis-wdls' &
git clone https://github.com/ENCODE-DCC/dnase-seq-pipeline '/storage/nvme5/new_clones/WDL/dnase-seq-pipeline' &
git clone https://github.com/gatk-workflows/gatk4-basic-joint-genotyping '/storage/nvme5/new_clones/WDL/gatk4-basic-joint-genotyping' &
git clone https://github.com/oskarvid/wdl_germline_pipeline '/storage/nvme5/new_clones/WDL/wdl_germline_pipeline' &
