#!/bin/bash

git clone https://github.com/kisonecat/web2js '/storage/nvme5/new_clones/xBase/web2js' &
git clone https://github.com/fdbozzo/foxbin2prg '/storage/nvme5/new_clones/xBase/foxbin2prg' &
git clone https://github.com/xjtuecho/AgmPill '/storage/nvme5/new_clones/xBase/AgmPill' &
git clone https://github.com/Irwin1985/JSONFox '/storage/nvme5/new_clones/xBase/JSONFox' &
git clone https://github.com/VFPX/nfJson '/storage/nvme5/new_clones/xBase/nfJson' &
git clone https://github.com/NaldoDj-zz/BlackTDN '/storage/nvme5/new_clones/xBase/BlackTDN' &
git clone https://github.com/saulogm/advpl-excel '/storage/nvme5/new_clones/xBase/advpl-excel' &
git clone https://github.com/matteobaccan/MultiRipper '/storage/nvme5/new_clones/xBase/MultiRipper' &
git clone https://github.com/nginformatica/advpl-testsuite '/storage/nvme5/new_clones/xBase/advpl-testsuite' &
git clone https://github.com/totvs/tlpp-sample-rest '/storage/nvme5/new_clones/xBase/tlpp-sample-rest' &
git clone https://github.com/VFPX/Thor '/storage/nvme5/new_clones/xBase/Thor' &
git clone https://github.com/tgmti/TGM_Advpl_Tools '/storage/nvme5/new_clones/xBase/TGM_Advpl_Tools' &
git clone https://github.com/VFPX/FoxBarcode '/storage/nvme5/new_clones/xBase/FoxBarcode' &
git clone https://github.com/julianeventeu/Dominando-MVC-AdvPL '/storage/nvme5/new_clones/xBase/Dominando-MVC-AdvPL' &
git clone https://github.com/llrafaell/SemPreju-Exemplos '/storage/nvme5/new_clones/xBase/SemPreju-Exemplos' &
git clone https://github.com/shawroad/NLP_tensorflow_project '/storage/nvme5/new_clones/xBase/NLP_tensorflow_project' &
git clone https://github.com/v89080/Crypto '/storage/nvme5/new_clones/xBase/Crypto' &
git clone https://github.com/VFPX/FoxCharts '/storage/nvme5/new_clones/xBase/FoxCharts' &
git clone https://github.com/arquimedescrivelari/foxpages '/storage/nvme5/new_clones/xBase/foxpages' &
git clone https://github.com/sait/vfpjson '/storage/nvme5/new_clones/xBase/vfpjson' &
git clone https://github.com/imsys/Protheus-Include '/storage/nvme5/new_clones/xBase/Protheus-Include' &
git clone https://github.com/endreodev/ADVPL-TlPP-PROTHEUS '/storage/nvme5/new_clones/xBase/ADVPL-TlPP-PROTHEUS' &
git clone https://github.com/StevenBlack/intl '/storage/nvme5/new_clones/xBase/intl' &
git clone https://github.com/VFPX/FoxBarcodeQR '/storage/nvme5/new_clones/xBase/FoxBarcodeQR' &
git clone https://github.com/siga0984/Blog '/storage/nvme5/new_clones/xBase/Blog' &
git clone https://github.com/andrewsegas/UTCTOOL '/storage/nvme5/new_clones/xBase/UTCTOOL' &
git clone https://github.com/AlencarGabriel/advpl-MsgTimer '/storage/nvme5/new_clones/xBase/advpl-MsgTimer' &
git clone https://github.com/nginformatica/advpl-rest-examples '/storage/nvme5/new_clones/xBase/advpl-rest-examples' &
git clone https://github.com/danielAlbuquerque/ADVPL-API-APP-ESTOQUE '/storage/nvme5/new_clones/xBase/ADVPL-API-APP-ESTOQUE' &
git clone https://github.com/DougHennig/ProjectExplorer '/storage/nvme5/new_clones/xBase/ProjectExplorer' &
git clone https://github.com/VFPX/FoxUnit '/storage/nvme5/new_clones/xBase/FoxUnit' &
git clone https://github.com/RickStrahl/wwMongoDb '/storage/nvme5/new_clones/xBase/wwMongoDb' &
git clone https://github.com/DougHennig/Ribbon '/storage/nvme5/new_clones/xBase/Ribbon' &
git clone https://github.com/calloatti/modrobot '/storage/nvme5/new_clones/xBase/modrobot' &
git clone https://github.com/GillesK/Protheus-Advpl-OO-Framework '/storage/nvme5/new_clones/xBase/Protheus-Advpl-OO-Framework' &
git clone https://github.com/Irwin1985/VFPRestClient '/storage/nvme5/new_clones/xBase/VFPRestClient' &
git clone https://github.com/danielflira/advplayl '/storage/nvme5/new_clones/xBase/advplayl' &
git clone https://github.com/ssllllll/Hello-World.plus '/storage/nvme5/new_clones/xBase/Hello-World.plus' &
git clone https://github.com/MacroDave/MARTIN '/storage/nvme5/new_clones/xBase/MARTIN' &
git clone https://github.com/danielAlbuquerque/tlpp-rest-api-boilerplate '/storage/nvme5/new_clones/xBase/tlpp-rest-api-boilerplate' &
git clone https://github.com/mattslay/GoFish '/storage/nvme5/new_clones/xBase/GoFish' &
git clone https://github.com/hansmarc/Otis '/storage/nvme5/new_clones/xBase/Otis' &
git clone https://github.com/JoseQuintas/sefazclass '/storage/nvme5/new_clones/xBase/sefazclass' &
git clone https://github.com/mwisslead/VFP-Embedded-Python '/storage/nvme5/new_clones/xBase/VFP-Embedded-Python' &
git clone https://github.com/EricLendvai/DataWharf '/storage/nvme5/new_clones/xBase/DataWharf' &
git clone https://github.com/claudefox/ActiveVFP '/storage/nvme5/new_clones/xBase/ActiveVFP' &
git clone https://github.com/nginformatica/advpl-logger '/storage/nvme5/new_clones/xBase/advpl-logger' &
git clone https://github.com/daniel-cabral/Fluig '/storage/nvme5/new_clones/xBase/Fluig' &
git clone https://github.com/VFPX/GDIPlusX '/storage/nvme5/new_clones/xBase/GDIPlusX' &
git clone https://github.com/siga0984/NETiZAP '/storage/nvme5/new_clones/xBase/NETiZAP' &
git clone https://github.com/VFPX/FoxTabs '/storage/nvme5/new_clones/xBase/FoxTabs' &
git clone https://github.com/julianeventeu/advpl-first-steps '/storage/nvme5/new_clones/xBase/advpl-first-steps' &
git clone https://github.com/StevenBlack/VFP '/storage/nvme5/new_clones/xBase/VFP' &
git clone https://github.com/lucasbrustolin/ProtheusTelegram '/storage/nvme5/new_clones/xBase/ProtheusTelegram' &
git clone https://github.com/StevenBlack/envLib '/storage/nvme5/new_clones/xBase/envLib' &
git clone https://github.com/DougHennig/SFMail '/storage/nvme5/new_clones/xBase/SFMail' &
git clone https://github.com/lucasbrustolin/Protheus-Janela-Processamento '/storage/nvme5/new_clones/xBase/Protheus-Janela-Processamento' &
git clone https://github.com/marcosgambeta/qt5xhb-v1 '/storage/nvme5/new_clones/xBase/qt5xhb-v1' &
git clone https://github.com/fandongmeng/DTMT_InDec '/storage/nvme5/new_clones/xBase/DTMT_InDec' &
git clone https://github.com/calloatti/TBZ '/storage/nvme5/new_clones/xBase/TBZ' &
git clone https://github.com/VFPX/nfXML '/storage/nvme5/new_clones/xBase/nfXML' &
git clone https://github.com/eselje/FoxTypes '/storage/nvme5/new_clones/xBase/FoxTypes' &
git clone https://github.com/nginformatica/json-advpl '/storage/nvme5/new_clones/xBase/json-advpl' &
git clone https://github.com/VFPX/FoxcodePlus '/storage/nvme5/new_clones/xBase/FoxcodePlus' &
git clone https://github.com/FrancisFaure/vfp_tmlanguage_generator '/storage/nvme5/new_clones/xBase/vfp_tmlanguage_generator' &
git clone https://github.com/mikepotjer/vfp-git-utils '/storage/nvme5/new_clones/xBase/vfp-git-utils' &
git clone https://github.com/ricardomansano/Exemplos '/storage/nvme5/new_clones/xBase/Exemplos' &
git clone https://github.com/VFPX/ThemedControls '/storage/nvme5/new_clones/xBase/ThemedControls' &
git clone https://github.com/kodhework/kodnet '/storage/nvme5/new_clones/xBase/kodnet' &
git clone https://github.com/InfomindsAg/XSharpExamples '/storage/nvme5/new_clones/xBase/XSharpExamples' &
git clone https://github.com/DougHennig/ErrorHandler '/storage/nvme5/new_clones/xBase/ErrorHandler' &
git clone https://github.com/izacsc/lodash-advpl '/storage/nvme5/new_clones/xBase/lodash-advpl' &
git clone https://github.com/RDMMakerspace/cnc-mill-with-ABB-robotic-arm '/storage/nvme5/new_clones/xBase/cnc-mill-with-ABB-robotic-arm' &
git clone https://github.com/ircsasw/CFD-CFDI-con-VFP '/storage/nvme5/new_clones/xBase/CFD-CFDI-con-VFP' &
git clone https://github.com/ljyit/foxjson '/storage/nvme5/new_clones/xBase/foxjson' &
git clone https://github.com/VFPX/Log4VFP '/storage/nvme5/new_clones/xBase/Log4VFP' &
git clone https://github.com/ThorstenDoherr/searchengine '/storage/nvme5/new_clones/xBase/searchengine' &
git clone https://github.com/ricardomansano/layouts_advpl '/storage/nvme5/new_clones/xBase/layouts_advpl' &
git clone https://github.com/andersontoledo/ProtheusRestSamples '/storage/nvme5/new_clones/xBase/ProtheusRestSamples' &
git clone https://github.com/atlopes/csv '/storage/nvme5/new_clones/xBase/csv' &
git clone https://github.com/ricardomansano/webengine_samples '/storage/nvme5/new_clones/xBase/webengine_samples' &
git clone https://github.com/totvs/frame-sp-universo '/storage/nvme5/new_clones/xBase/frame-sp-universo' &
git clone https://github.com/EricLendvai/Harbour_ORM '/storage/nvme5/new_clones/xBase/Harbour_ORM' &
git clone https://github.com/jerfweb/API-REST-PROTHEUS '/storage/nvme5/new_clones/xBase/API-REST-PROTHEUS' &
git clone https://github.com/FiveTechSoft/wsserver '/storage/nvme5/new_clones/xBase/wsserver' &
git clone https://github.com/VictorBassoon/REST-ADVPL '/storage/nvme5/new_clones/xBase/REST-ADVPL' &
git clone https://github.com/atlopes/DPIAwareManager '/storage/nvme5/new_clones/xBase/DPIAwareManager' &
git clone https://github.com/camilo-cf/Robotarm-ABB140-AutoDrawing '/storage/nvme5/new_clones/xBase/Robotarm-ABB140-AutoDrawing' &
git clone https://github.com/EricLendvai/Harbour_Samples '/storage/nvme5/new_clones/xBase/Harbour_Samples' &
git clone https://github.com/raulvfp/ajaxRest '/storage/nvme5/new_clones/xBase/ajaxRest' &
git clone https://github.com/VFPX/ExcelXML '/storage/nvme5/new_clones/xBase/ExcelXML' &
git clone https://github.com/calloatti/WINHTTP '/storage/nvme5/new_clones/xBase/WINHTTP' &
git clone https://github.com/proudindiv/FRBUSinR '/storage/nvme5/new_clones/xBase/FRBUSinR' &
git clone https://github.com/NaldoDj-zz/tBigNumber '/storage/nvme5/new_clones/xBase/tBigNumber' &
git clone https://github.com/cwollenhaupt/foxCryptoNG '/storage/nvme5/new_clones/xBase/foxCryptoNG' &
git clone https://github.com/nginformatica/advpl-debugger '/storage/nvme5/new_clones/xBase/advpl-debugger' &
git clone https://github.com/X-Sharp/XSharpTools '/storage/nvme5/new_clones/xBase/XSharpTools' &
git clone https://github.com/VFPX/UpsizingWizard '/storage/nvme5/new_clones/xBase/UpsizingWizard' &
git clone https://github.com/davidgiven/cowbel '/storage/nvme5/new_clones/xBase/cowbel' &
git clone https://github.com/VFPX/Gauge '/storage/nvme5/new_clones/xBase/Gauge' &
git clone https://github.com/CordyJ/Open-TuringPlus '/storage/nvme5/new_clones/xBase/Open-TuringPlus' &
git clone https://github.com/VFPX/AutomatedBuild '/storage/nvme5/new_clones/xBase/AutomatedBuild' &
git clone https://github.com/VFPX/CodeAnalyst '/storage/nvme5/new_clones/xBase/CodeAnalyst' &
git clone https://github.com/Irwin1985/TrucosVFP '/storage/nvme5/new_clones/xBase/TrucosVFP' &
git clone https://github.com/siga0984/zLIB '/storage/nvme5/new_clones/xBase/zLIB' &
git clone https://github.com/VFPX/IntelliSenseX '/storage/nvme5/new_clones/xBase/IntelliSenseX' &
git clone https://github.com/JoseCamilo/poo-advpl '/storage/nvme5/new_clones/xBase/poo-advpl' &
git clone https://github.com/maximinocastro/finnet '/storage/nvme5/new_clones/xBase/finnet' &
git clone https://github.com/VFPX/ThorRepository '/storage/nvme5/new_clones/xBase/ThorRepository' &
git clone https://github.com/calloatti/LIBCURL '/storage/nvme5/new_clones/xBase/LIBCURL' &
git clone https://github.com/MikeDX/div-pitfall '/storage/nvme5/new_clones/xBase/div-pitfall' &
git clone https://github.com/VFPX/OOPMenu '/storage/nvme5/new_clones/xBase/OOPMenu' &
git clone https://github.com/FiveTechSoft/hbide '/storage/nvme5/new_clones/xBase/hbide' &
git clone https://github.com/alkresin/HDroidGUI '/storage/nvme5/new_clones/xBase/HDroidGUI' &
git clone https://github.com/vitorebatista/advpl.translate '/storage/nvme5/new_clones/xBase/advpl.translate' &
git clone https://github.com/rsalzer/leafletswisstopo '/storage/nvme5/new_clones/xBase/leafletswisstopo' &
git clone https://github.com/VFPX/TwilioX '/storage/nvme5/new_clones/xBase/TwilioX' &
git clone https://github.com/nginformatica/nghashmap '/storage/nvme5/new_clones/xBase/nghashmap' &
git clone https://github.com/MRonaldo/MR-Tools '/storage/nvme5/new_clones/xBase/MR-Tools' &
git clone https://github.com/Irwin1985/FoxNone '/storage/nvme5/new_clones/xBase/FoxNone' &
git clone https://github.com/ircsasw/VFPconGit '/storage/nvme5/new_clones/xBase/VFPconGit' &
git clone https://github.com/totvs/twebengine-sample '/storage/nvme5/new_clones/xBase/twebengine-sample' &
git clone https://github.com/raulvfp/getURL '/storage/nvme5/new_clones/xBase/getURL' &
git clone https://github.com/lucasbrustolin/Protheus '/storage/nvme5/new_clones/xBase/Protheus' &
git clone https://github.com/atlopes/zintbarcode '/storage/nvme5/new_clones/xBase/zintbarcode' &
git clone https://github.com/Irwin1985/FoxFaker '/storage/nvme5/new_clones/xBase/FoxFaker' &
git clone https://github.com/haskellcamargo/fwquerybuilder '/storage/nvme5/new_clones/xBase/fwquerybuilder' &
git clone https://github.com/VFPX/VFPRegExTool '/storage/nvme5/new_clones/xBase/VFPRegExTool' &
git clone https://github.com/QuimFerrer/sepa '/storage/nvme5/new_clones/xBase/sepa' &
git clone https://github.com/osantana-archive/siscan '/storage/nvme5/new_clones/xBase/siscan' &
git clone https://github.com/gavanderhoorn/epson_experimental '/storage/nvme5/new_clones/xBase/epson_experimental' &
git clone https://github.com/carles9000/tweb '/storage/nvme5/new_clones/xBase/tweb' &
git clone https://github.com/lucasbrustolin/Browser-Tab-Temporaria-filtro '/storage/nvme5/new_clones/xBase/Browser-Tab-Temporaria-filtro' &
git clone https://github.com/alidioribeiro/ADVPL-CODES '/storage/nvme5/new_clones/xBase/ADVPL-CODES' &
git clone https://github.com/cnpj-ws/protheus '/storage/nvme5/new_clones/xBase/protheus' &
git clone https://github.com/RickBorup/FoxDates '/storage/nvme5/new_clones/xBase/FoxDates' &
git clone https://github.com/Petewg/MgM '/storage/nvme5/new_clones/xBase/MgM' &
git clone https://github.com/FiveTechSoft/fivetouch '/storage/nvme5/new_clones/xBase/fivetouch' &
git clone https://github.com/antoniomeza/foxydb '/storage/nvme5/new_clones/xBase/foxydb' &
git clone https://github.com/VFPX/PEMEditor '/storage/nvme5/new_clones/xBase/PEMEditor' &
git clone https://github.com/soulsys/totvs-advpl-lib '/storage/nvme5/new_clones/xBase/totvs-advpl-lib' &
git clone https://github.com/berithpy/digitoverificador '/storage/nvme5/new_clones/xBase/digitoverificador' &
git clone https://github.com/ThreeME-org/ThreeME_V3-open '/storage/nvme5/new_clones/xBase/ThreeME_V3-open' &
git clone https://github.com/VFPX/FastXTab '/storage/nvme5/new_clones/xBase/FastXTab' &
git clone https://github.com/lscheffler/bin2text '/storage/nvme5/new_clones/xBase/bin2text' &
git clone https://github.com/tiritas/FoxWeb-FullTextSearch '/storage/nvme5/new_clones/xBase/FoxWeb-FullTextSearch' &
git clone https://github.com/manuelcalerosolis/Gestool '/storage/nvme5/new_clones/xBase/Gestool' &
git clone https://github.com/VictorCasajuanaMas/hbunit '/storage/nvme5/new_clones/xBase/hbunit' &
git clone https://github.com/AnyMarket/Protheus '/storage/nvme5/new_clones/xBase/Protheus' &
git clone https://github.com/cwollenhaupt/foxmock '/storage/nvme5/new_clones/xBase/foxmock' &
git clone https://github.com/MikeDX/balloon-fight '/storage/nvme5/new_clones/xBase/balloon-fight' &
git clone https://github.com/AugustoPontin/advpl_react_controle_acessos_backend '/storage/nvme5/new_clones/xBase/advpl_react_controle_acessos_backend' &
git clone https://github.com/vitorebatista/advpl.rodados '/storage/nvme5/new_clones/xBase/advpl.rodados' &
git clone https://github.com/alkresin/hbedit '/storage/nvme5/new_clones/xBase/hbedit' &
git clone https://github.com/JanderSousa/vscode-themes-for-vfp '/storage/nvme5/new_clones/xBase/vscode-themes-for-vfp' &
git clone https://github.com/VFPX/AlternateSCCText '/storage/nvme5/new_clones/xBase/AlternateSCCText' &
