#!/bin/bash

git clone https://github.com/GuntherRademacher/rr '/storage/nvme5/new_clones/XQuery/rr' &
git clone https://github.com/PerseusDL/canonical-greekLit '/storage/nvme5/new_clones/XQuery/canonical-greekLit' &
git clone https://github.com/marklogic-community/roxy '/storage/nvme5/new_clones/XQuery/roxy' &
git clone https://github.com/microsoft/Dynamics365FO-AppChecker '/storage/nvme5/new_clones/XQuery/Dynamics365FO-AppChecker' &
git clone https://github.com/ntra00/marc2bibframe '/storage/nvme5/new_clones/XQuery/marc2bibframe' &
git clone https://github.com/robwhitby/xray '/storage/nvme5/new_clones/XQuery/xray' &
git clone https://github.com/yangchenyun/dbclass-exercises '/storage/nvme5/new_clones/XQuery/dbclass-exercises' &
git clone https://github.com/CliffordAnderson/XQuery4Humanists '/storage/nvme5/new_clones/XQuery/XQuery4Humanists' &
git clone https://github.com/PerseusDL/canonical-latinLit '/storage/nvme5/new_clones/XQuery/canonical-latinLit' &
git clone https://github.com/cfoster/xqrs '/storage/nvme5/new_clones/XQuery/xqrs' &
git clone https://github.com/erlangen-crm/ecrm '/storage/nvme5/new_clones/XQuery/ecrm' &
git clone https://github.com/marklogic-community/commons '/storage/nvme5/new_clones/XQuery/commons' &
git clone https://github.com/xquery/xquerydoc '/storage/nvme5/new_clones/XQuery/xquerydoc' &
git clone https://github.com/marklogic-community/Corona '/storage/nvme5/new_clones/XQuery/Corona' &
git clone https://github.com/xquery/rxq '/storage/nvme5/new_clones/XQuery/rxq' &
git clone https://github.com/LeoWoerteler/xq-modules '/storage/nvme5/new_clones/XQuery/xq-modules' &
git clone https://github.com/mblakele/taskbot '/storage/nvme5/new_clones/XQuery/taskbot' &
git clone https://github.com/altomator/Image_Retrieval '/storage/nvme5/new_clones/XQuery/Image_Retrieval' &
git clone https://github.com/james-jw/xq-promise '/storage/nvme5/new_clones/XQuery/xq-promise' &
git clone https://github.com/Clear-Bible/macula-greek '/storage/nvme5/new_clones/XQuery/macula-greek' &
git clone https://github.com/ryanjdew/XQuery-XML-Memory-Operations '/storage/nvme5/new_clones/XQuery/XQuery-XML-Memory-Operations' &
git clone https://github.com/hrennau/foxpath '/storage/nvme5/new_clones/XQuery/foxpath' &
git clone https://github.com/marklogic-community/semantic '/storage/nvme5/new_clones/XQuery/semantic' &
git clone https://github.com/wolfgangmm/tei-simple-pm '/storage/nvme5/new_clones/XQuery/tei-simple-pm' &
git clone https://github.com/odaata/HisTEI '/storage/nvme5/new_clones/XQuery/HisTEI' &
git clone https://github.com/haggis78/Nexus '/storage/nvme5/new_clones/XQuery/Nexus' &
git clone https://github.com/openhie/openinfoman '/storage/nvme5/new_clones/XQuery/openinfoman' &
git clone https://github.com/dscape/mustache.xq '/storage/nvme5/new_clones/XQuery/mustache.xq' &
git clone https://github.com/sumeetsk/dbclass '/storage/nvme5/new_clones/XQuery/dbclass' &
git clone https://github.com/joewiz/xqjson '/storage/nvme5/new_clones/XQuery/xqjson' &
git clone https://github.com/evanlenz/Carrot '/storage/nvme5/new_clones/XQuery/Carrot' &
git clone https://github.com/marklogic-community/marklogicworkflow '/storage/nvme5/new_clones/XQuery/marklogicworkflow' &
git clone https://github.com/garyvidal/xquerrail '/storage/nvme5/new_clones/XQuery/xquerrail' &
git clone https://github.com/jpcs/functional.xq '/storage/nvme5/new_clones/XQuery/functional.xq' &
git clone https://github.com/srophe/srophe '/storage/nvme5/new_clones/XQuery/srophe' &
git clone https://github.com/jpcs/data.xq '/storage/nvme5/new_clones/XQuery/data.xq' &
git clone https://github.com/xquery/xquery_functional_catalog '/storage/nvme5/new_clones/XQuery/xquery_functional_catalog' &
git clone https://github.com/msDesc/consolidated-tei-schema '/storage/nvme5/new_clones/XQuery/consolidated-tei-schema' &
git clone https://github.com/HistoryAtState/hsg-project '/storage/nvme5/new_clones/XQuery/hsg-project' &
git clone https://github.com/marklogic-community/data-explorer '/storage/nvme5/new_clones/XQuery/data-explorer' &
git clone https://github.com/eXist-db/demo-apps '/storage/nvme5/new_clones/XQuery/demo-apps' &
git clone https://github.com/holmesw/isbn '/storage/nvme5/new_clones/XQuery/isbn' &
git clone https://github.com/eliudmeza/OOXML-Library-XQuery-BaseXdb '/storage/nvme5/new_clones/XQuery/OOXML-Library-XQuery-BaseXdb' &
git clone https://github.com/joewiz/punch '/storage/nvme5/new_clones/XQuery/punch' &
git clone https://github.com/ssire/oppidum '/storage/nvme5/new_clones/XQuery/oppidum' &
git clone https://github.com/jpcs/xqueryparser.xq '/storage/nvme5/new_clones/XQuery/xqueryparser.xq' &
git clone https://github.com/inspire-eu-validation/ets-repository '/storage/nvme5/new_clones/XQuery/ets-repository' &
git clone https://github.com/line-o/xbow '/storage/nvme5/new_clones/XQuery/xbow' &
git clone https://github.com/marklogic-community/marklogic-unit-test '/storage/nvme5/new_clones/XQuery/marklogic-unit-test' &
git clone https://github.com/eXist-db/documentation '/storage/nvme5/new_clones/XQuery/documentation' &
git clone https://github.com/eXist-db/exist-markdown '/storage/nvme5/new_clones/XQuery/exist-markdown' &
git clone https://github.com/synopsx/synopsx '/storage/nvme5/new_clones/XQuery/synopsx' &
git clone https://github.com/garyvidal/marklogic-ant-tasks '/storage/nvme5/new_clones/XQuery/marklogic-ant-tasks' &
git clone https://github.com/hrennau/TopicTools '/storage/nvme5/new_clones/XQuery/TopicTools' &
git clone https://github.com/xproc/1.0-specification '/storage/nvme5/new_clones/XQuery/1.0-specification' &
git clone https://github.com/Edirom/SMuFL-Browser '/storage/nvme5/new_clones/XQuery/SMuFL-Browser' &
git clone https://github.com/ryangrimm/mljson '/storage/nvme5/new_clones/XQuery/mljson' &
git clone https://github.com/jpcs/transform.xq '/storage/nvme5/new_clones/XQuery/transform.xq' &
git clone https://github.com/srophe/syriac-corpus '/storage/nvme5/new_clones/XQuery/syriac-corpus' &
git clone https://github.com/marklogic-community/demo-cat '/storage/nvme5/new_clones/XQuery/demo-cat' &
git clone https://github.com/marklogic-community/smart-mastering-core '/storage/nvme5/new_clones/XQuery/smart-mastering-core' &
git clone https://github.com/coding4humanists/xquery4humanists '/storage/nvme5/new_clones/XQuery/xquery4humanists' &
git clone https://github.com/jpcs/rbtree.xq '/storage/nvme5/new_clones/XQuery/rbtree.xq' &
git clone https://github.com/BetaMasaheft/Manuscripts '/storage/nvme5/new_clones/XQuery/Manuscripts' &
git clone https://github.com/dracor-org/dracor-api '/storage/nvme5/new_clones/XQuery/dracor-api' &
git clone https://github.com/marklogic-community/ml-rest-lib '/storage/nvme5/new_clones/XQuery/ml-rest-lib' &
git clone https://github.com/eXist-book/using-exist-101 '/storage/nvme5/new_clones/XQuery/using-exist-101' &
git clone https://github.com/hrennau/shax '/storage/nvme5/new_clones/XQuery/shax' &
git clone https://github.com/james-jw/xqpm '/storage/nvme5/new_clones/XQuery/xqpm' &
git clone https://github.com/marklogic-community/atompub-server '/storage/nvme5/new_clones/XQuery/atompub-server' &
git clone https://github.com/HistoryAtState/hsg-shell '/storage/nvme5/new_clones/XQuery/hsg-shell' &
git clone https://github.com/eeditiones/tuttle '/storage/nvme5/new_clones/XQuery/tuttle' &
git clone https://github.com/lcnetdev/marcauth-to-madsrdf '/storage/nvme5/new_clones/XQuery/marcauth-to-madsrdf' &
git clone https://github.com/pulcams/catalogers-workbench '/storage/nvme5/new_clones/XQuery/catalogers-workbench' &
git clone https://github.com/HistoryAtState/travels '/storage/nvme5/new_clones/XQuery/travels' &
git clone https://github.com/joemfb/group-by '/storage/nvme5/new_clones/XQuery/group-by' &
git clone https://github.com/expkg-zone58/ex-xparse '/storage/nvme5/new_clones/XQuery/ex-xparse' &
git clone https://github.com/PersDigUMD/PDL '/storage/nvme5/new_clones/XQuery/PDL' &
git clone https://github.com/ryanjdew/ml-slush-discovery-app '/storage/nvme5/new_clones/XQuery/ml-slush-discovery-app' &
git clone https://github.com/grtjn/marklogic-typescript-definitions '/storage/nvme5/new_clones/XQuery/marklogic-typescript-definitions' &
git clone https://github.com/lcahlander/xsd2json '/storage/nvme5/new_clones/XQuery/xsd2json' &
git clone https://github.com/dariok/wdbplus '/storage/nvme5/new_clones/XQuery/wdbplus' &
git clone https://github.com/marklogic-community/hands-on-data-modeling '/storage/nvme5/new_clones/XQuery/hands-on-data-modeling' &
git clone https://github.com/hcts-hra/tamboti '/storage/nvme5/new_clones/XQuery/tamboti' &
git clone https://github.com/gibaholms/articles '/storage/nvme5/new_clones/XQuery/articles' &
git clone https://github.com/AndrewSales/XQS '/storage/nvme5/new_clones/XQuery/XQS' &
git clone https://github.com/fgeorges/xproject '/storage/nvme5/new_clones/XQuery/xproject' &
git clone https://github.com/umd-mith/mishnah '/storage/nvme5/new_clones/XQuery/mishnah' &
git clone https://github.com/ndw/ML-Schematron '/storage/nvme5/new_clones/XQuery/ML-Schematron' &
git clone https://github.com/eXist-db/public-repo '/storage/nvme5/new_clones/XQuery/public-repo' &
git clone https://github.com/eXistSolutions/exist-jwt '/storage/nvme5/new_clones/XQuery/exist-jwt' &
git clone https://github.com/hrennau/greenfox '/storage/nvme5/new_clones/XQuery/greenfox' &
git clone https://github.com/CliffordAnderson/ninety-nine '/storage/nvme5/new_clones/XQuery/ninety-nine' &
git clone https://github.com/readchina/ReadAct '/storage/nvme5/new_clones/XQuery/ReadAct' &
git clone https://github.com/mblakele/task-rebalancer '/storage/nvme5/new_clones/XQuery/task-rebalancer' &
git clone https://github.com/nevenjovanovic/croatiae-auctores-latini-textus '/storage/nvme5/new_clones/XQuery/croatiae-auctores-latini-textus' &
git clone https://github.com/mblakele/xqut '/storage/nvme5/new_clones/XQuery/xqut' &
git clone https://github.com/telic/exist-annotation-store '/storage/nvme5/new_clones/XQuery/exist-annotation-store' &
git clone https://github.com/sashamitrovich/MarkLogic-k-dashboard '/storage/nvme5/new_clones/XQuery/MarkLogic-k-dashboard' &
git clone https://github.com/chartes/dico-topo '/storage/nvme5/new_clones/XQuery/dico-topo' &
git clone https://github.com/ahn-ens-lyon/synopsx '/storage/nvme5/new_clones/XQuery/synopsx' &
git clone https://github.com/marklogic/entity-services '/storage/nvme5/new_clones/XQuery/entity-services' &
git clone https://github.com/apb2006/graphxq '/storage/nvme5/new_clones/XQuery/graphxq' &
git clone https://github.com/marklogic-community/DocumentDiscovery '/storage/nvme5/new_clones/XQuery/DocumentDiscovery' &
git clone https://github.com/sastafford/Tarantula '/storage/nvme5/new_clones/XQuery/Tarantula' &
git clone https://github.com/biblicalhumanities/treedown '/storage/nvme5/new_clones/XQuery/treedown' &
git clone https://github.com/xquery/xproc.xq '/storage/nvme5/new_clones/XQuery/xproc.xq' &
git clone https://github.com/ekimbernow/basex-orchestration '/storage/nvme5/new_clones/XQuery/basex-orchestration' &
git clone https://github.com/line-o/dicey '/storage/nvme5/new_clones/XQuery/dicey' &
git clone https://github.com/ryanjdew/marklogic-entity-extraction '/storage/nvme5/new_clones/XQuery/marklogic-entity-extraction' &
git clone https://github.com/peterstadler/Query-TEI-data-by-class '/storage/nvme5/new_clones/XQuery/Query-TEI-data-by-class' &
git clone https://github.com/jpcs/queryplan-viewer '/storage/nvme5/new_clones/XQuery/queryplan-viewer' &
git clone https://github.com/nativelogix/xquerrail2.framework '/storage/nvme5/new_clones/XQuery/xquerrail2.framework' &
git clone https://github.com/apb2006/restlib '/storage/nvme5/new_clones/XQuery/restlib' &
git clone https://github.com/mustard57/MarkLogic-IO-Test '/storage/nvme5/new_clones/XQuery/MarkLogic-IO-Test' &
git clone https://github.com/dita-community/dita-for-small-teams '/storage/nvme5/new_clones/XQuery/dita-for-small-teams' &
git clone https://github.com/gossebouma/lassy2ud '/storage/nvme5/new_clones/XQuery/lassy2ud' &
git clone https://github.com/jpcs/parser.xq '/storage/nvme5/new_clones/XQuery/parser.xq' &
git clone https://github.com/eeditiones/vangogh '/storage/nvme5/new_clones/XQuery/vangogh' &
git clone https://github.com/wshager/xsltea '/storage/nvme5/new_clones/XQuery/xsltea' &
git clone https://github.com/rhdunn/document-viewer '/storage/nvme5/new_clones/XQuery/document-viewer' &
git clone https://github.com/Islandora-Labs/islandora-xquery-examples '/storage/nvme5/new_clones/XQuery/islandora-xquery-examples' &
git clone https://github.com/eXist-db/semver.xq '/storage/nvme5/new_clones/XQuery/semver.xq' &
git clone https://github.com/eeditiones/tei-publisher-data-template '/storage/nvme5/new_clones/XQuery/tei-publisher-data-template' &
git clone https://github.com/Quodatum/xqdoca '/storage/nvme5/new_clones/XQuery/xqdoca' &
git clone https://github.com/VandyVRC/tcadrt '/storage/nvme5/new_clones/XQuery/tcadrt' &
git clone https://github.com/LiteratureInContext/LiC-data '/storage/nvme5/new_clones/XQuery/LiC-data' &
git clone https://github.com/rwalpole/xquery-sparql '/storage/nvme5/new_clones/XQuery/xquery-sparql' &
git clone https://github.com/AdamSteffanick/od-api-xquery '/storage/nvme5/new_clones/XQuery/od-api-xquery' &
git clone https://github.com/philipfennell/grip '/storage/nvme5/new_clones/XQuery/grip' &
git clone https://github.com/jbrazda/com.informatica.cloud.das '/storage/nvme5/new_clones/XQuery/com.informatica.cloud.das' &
git clone https://github.com/marklogic-community/infostudio-plugins '/storage/nvme5/new_clones/XQuery/infostudio-plugins' &
git clone https://github.com/HistoryAtState/pocom '/storage/nvme5/new_clones/XQuery/pocom' &
