#!/bin/bash

git clone https://github.com/tobykurien/Xtendroid '/storage/nvme5/new_clones/Xtend/Xtendroid' &
git clone https://github.com/tobykurien/WebApps '/storage/nvme5/new_clones/Xtend/WebApps' &
git clone https://github.com/ThomDietrich/openhab-config '/storage/nvme5/new_clones/Xtend/openhab-config' &
git clone https://github.com/jhipster/jhipster-ide '/storage/nvme5/new_clones/Xtend/jhipster-ide' &
git clone https://github.com/borkdominik/bigER '/storage/nvme5/new_clones/Xtend/bigER' &
git clone https://github.com/COVESA/capicxx-someip-tools '/storage/nvme5/new_clones/Xtend/capicxx-someip-tools' &
git clone https://github.com/prof7bit/wallet-key-tool '/storage/nvme5/new_clones/Xtend/wallet-key-tool' &
git clone https://github.com/tobykurien/WebMediaShare '/storage/nvme5/new_clones/Xtend/WebMediaShare' &
git clone https://github.com/svenefftinge/xtendfx '/storage/nvme5/new_clones/Xtend/xtendfx' &
git clone https://github.com/TypeFox/yang-lsp '/storage/nvme5/new_clones/Xtend/yang-lsp' &
git clone https://github.com/oehme/xtend-contrib '/storage/nvme5/new_clones/Xtend/xtend-contrib' &
git clone https://github.com/ftsrg/gamma '/storage/nvme5/new_clones/Xtend/gamma' &
git clone https://github.com/svenefftinge/xtext-lsp-workshop '/storage/nvme5/new_clones/Xtend/xtext-lsp-workshop' &
git clone https://github.com/japkit/japkit '/storage/nvme5/new_clones/Xtend/japkit' &
git clone https://github.com/UBC-Stat-ML/blangSDK '/storage/nvme5/new_clones/Xtend/blangSDK' &
git clone https://github.com/Guite/MostGenerator '/storage/nvme5/new_clones/Xtend/MostGenerator' &
git clone https://github.com/dragos/typesafe-config-eclipse '/storage/nvme5/new_clones/Xtend/typesafe-config-eclipse' &
git clone https://github.com/oddgen/oddgen '/storage/nvme5/new_clones/Xtend/oddgen' &
git clone https://github.com/blueneogeo/xtend-tools '/storage/nvme5/new_clones/Xtend/xtend-tools' &
git clone https://github.com/graph-quilt/graphql-xtext '/storage/nvme5/new_clones/Xtend/graphql-xtext' &
git clone https://github.com/tobykurien/Sparkler '/storage/nvme5/new_clones/Xtend/Sparkler' &
git clone https://github.com/sirolf2009/samurai '/storage/nvme5/new_clones/Xtend/samurai' &
git clone https://github.com/GENIVI/franca_plus '/storage/nvme5/new_clones/Xtend/franca_plus' &
git clone https://github.com/Smart-Contract-Modelling-uOttawa/Symboleo-IDE '/storage/nvme5/new_clones/Xtend/Symboleo-IDE' &
git clone https://github.com/modal-dsl/modal '/storage/nvme5/new_clones/Xtend/modal' &
git clone https://github.com/REGnosys/rosetta-code-generators '/storage/nvme5/new_clones/Xtend/rosetta-code-generators' &
git clone https://github.com/rzymek/java2xtend '/storage/nvme5/new_clones/Xtend/java2xtend' &
git clone https://github.com/Minres/CoreDSL '/storage/nvme5/new_clones/Xtend/CoreDSL' &
git clone https://github.com/szschaler/GridGames '/storage/nvme5/new_clones/Xtend/GridGames' &
git clone https://github.com/blueneogeo/xtend-async '/storage/nvme5/new_clones/Xtend/xtend-async' &
git clone https://github.com/Namek/TheConsole '/storage/nvme5/new_clones/Xtend/TheConsole' &
git clone https://github.com/OpenNTF/CommandLineEmailClient '/storage/nvme5/new_clones/Xtend/CommandLineEmailClient' &
git clone https://github.com/wwu-pi/md2-framework '/storage/nvme5/new_clones/Xtend/md2-framework' &
git clone https://github.com/fuinorg/org.fuin.dsl.ddd '/storage/nvme5/new_clones/Xtend/org.fuin.dsl.ddd' &
git clone https://github.com/spagnuolocarmine/FLY-language '/storage/nvme5/new_clones/Xtend/FLY-language' &
git clone https://github.com/danieldietrich/xtext-protected-regions '/storage/nvme5/new_clones/Xtend/xtext-protected-regions' &
git clone https://github.com/PacktPublishing/Implementing-Domain-Specific-Languages-with-Xtext-and-Xtend '/storage/nvme5/new_clones/Xtend/Implementing-Domain-Specific-Languages-with-Xtext-and-Xtend' &
git clone https://github.com/plugback/jpa '/storage/nvme5/new_clones/Xtend/jpa' &
git clone https://github.com/TypeFox/xtext2langium '/storage/nvme5/new_clones/Xtend/xtext2langium' &
git clone https://github.com/basilfx/xtext-standalone-maven-build '/storage/nvme5/new_clones/Xtend/xtext-standalone-maven-build' &
git clone https://github.com/scottopell/vim-xtext '/storage/nvme5/new_clones/Xtend/vim-xtext' &
git clone https://github.com/hypery2k/galen_ide '/storage/nvme5/new_clones/Xtend/galen_ide' &
git clone https://github.com/sargunv/cursed-languages '/storage/nvme5/new_clones/Xtend/cursed-languages' &
git clone https://github.com/UBC-Stat-ML/nowellpack '/storage/nvme5/new_clones/Xtend/nowellpack' &
git clone https://github.com/Hellmy/plantuml-eclipse-xtext '/storage/nvme5/new_clones/Xtend/plantuml-eclipse-xtext' &
git clone https://github.com/theia-ide/yang-eclipse '/storage/nvme5/new_clones/Xtend/yang-eclipse' &
git clone https://github.com/gzsombor/logging-annotation '/storage/nvme5/new_clones/Xtend/logging-annotation' &
git clone https://github.com/davidB/jme3_ext_deferred '/storage/nvme5/new_clones/Xtend/jme3_ext_deferred' &
git clone https://github.com/markus1978/emf-compress '/storage/nvme5/new_clones/Xtend/emf-compress' &
git clone https://github.com/markus1978/xraw '/storage/nvme5/new_clones/Xtend/xraw' &
git clone https://github.com/2over12/sleigh-lsp-extension '/storage/nvme5/new_clones/Xtend/sleigh-lsp-extension' &
git clone https://github.com/czarly/scilla-language-server '/storage/nvme5/new_clones/Xtend/scilla-language-server' &
