#!/bin/bash

git clone https://github.com/whitequark/parser '/storage/nvme5/new_clones/Yacc/parser' &
git clone https://github.com/bisqwit/compiler_series '/storage/nvme5/new_clones/Yacc/compiler_series' &
git clone https://github.com/ruby/racc '/storage/nvme5/new_clones/Yacc/racc' &
git clone https://github.com/mventurelli/relichunterszero '/storage/nvme5/new_clones/Yacc/relichunterszero' &
git clone https://github.com/ID-10086/freenode '/storage/nvme5/new_clones/Yacc/freenode' &
git clone https://github.com/jackc/sqlfmt '/storage/nvme5/new_clones/Yacc/sqlfmt' &
git clone https://github.com/inpla/inpla '/storage/nvme5/new_clones/Yacc/inpla' &
git clone https://github.com/staruml/staruml-cpp '/storage/nvme5/new_clones/Yacc/staruml-cpp' &
git clone https://github.com/MattDMo/Neon-color-scheme '/storage/nvme5/new_clones/Yacc/Neon-color-scheme' &
git clone https://github.com/Dragon-Developer/Mega-Man-X-Engine '/storage/nvme5/new_clones/Yacc/Mega-Man-X-Engine' &
git clone https://github.com/jengelsma/yacc-tutorial '/storage/nvme5/new_clones/Yacc/yacc-tutorial' &
git clone https://github.com/fred-wang/TeXZilla '/storage/nvme5/new_clones/Yacc/TeXZilla' &
git clone https://github.com/AnjaneyaTripathi/c-compiler '/storage/nvme5/new_clones/Yacc/c-compiler' &
git clone https://github.com/SilverScar/C-Language-Parser '/storage/nvme5/new_clones/Yacc/C-Language-Parser' &
git clone https://github.com/gregkh/gregkh-linux '/storage/nvme5/new_clones/Yacc/gregkh-linux' &
git clone https://github.com/staruml/staruml-csharp '/storage/nvme5/new_clones/Yacc/staruml-csharp' &
git clone https://github.com/DavidStrachan/GM-Perfect-Platforming-Paragon '/storage/nvme5/new_clones/Yacc/GM-Perfect-Platforming-Paragon' &
git clone https://github.com/jgarzik/sqlfun '/storage/nvme5/new_clones/Yacc/sqlfun' &
git clone https://github.com/mbbill/flexbison '/storage/nvme5/new_clones/Yacc/flexbison' &
git clone https://github.com/Hirnbix/captain-holetooth '/storage/nvme5/new_clones/Yacc/captain-holetooth' &
git clone https://github.com/Gizmo199/fauxton3D '/storage/nvme5/new_clones/Yacc/fauxton3D' &
git clone https://github.com/gopikchr/gopikchr '/storage/nvme5/new_clones/Yacc/gopikchr' &
git clone https://github.com/Gizmo199/non_repeating_hextiling '/storage/nvme5/new_clones/Yacc/non_repeating_hextiling' &
git clone https://github.com/andyjansson/postcss-conditionals '/storage/nvme5/new_clones/Yacc/postcss-conditionals' &
git clone https://github.com/phplang/xhp '/storage/nvme5/new_clones/Yacc/xhp' &
git clone https://github.com/bleibig/rust-grammar '/storage/nvme5/new_clones/Yacc/rust-grammar' &
git clone https://github.com/LDinos/Dijeweled '/storage/nvme5/new_clones/Yacc/Dijeweled' &
git clone https://github.com/hoterran/sqlparser '/storage/nvme5/new_clones/Yacc/sqlparser' &
git clone https://github.com/Chrisejorge/Causal-Inference '/storage/nvme5/new_clones/Yacc/Causal-Inference' &
git clone https://github.com/konieshadow/lex-yacc-examples '/storage/nvme5/new_clones/Yacc/lex-yacc-examples' &
git clone https://github.com/Lojemiru/Loj-Hadron-Collider '/storage/nvme5/new_clones/Yacc/Loj-Hadron-Collider' &
git clone https://github.com/babaganosch/NotificationSystem '/storage/nvme5/new_clones/Yacc/NotificationSystem' &
git clone https://github.com/kaushiksk/mini-c-compiler '/storage/nvme5/new_clones/Yacc/mini-c-compiler' &
git clone https://github.com/johnwdubois/rezonator '/storage/nvme5/new_clones/Yacc/rezonator' &
git clone https://github.com/tree-sitter/tree-sitter-agda '/storage/nvme5/new_clones/Yacc/tree-sitter-agda' &
git clone https://github.com/shivananda199/Mini-C-Compiler '/storage/nvme5/new_clones/Yacc/Mini-C-Compiler' &
git clone https://github.com/kranthikiran01/subc-compiler '/storage/nvme5/new_clones/Yacc/subc-compiler' &
git clone https://github.com/studiawan/data-compression '/storage/nvme5/new_clones/Yacc/data-compression' &
git clone https://github.com/0xPolygonHermez/zkasmcom '/storage/nvme5/new_clones/Yacc/zkasmcom' &
git clone https://github.com/ArcaneNibble/yavhdl '/storage/nvme5/new_clones/Yacc/yavhdl' &
git clone https://github.com/gm-core/patchwire-gm '/storage/nvme5/new_clones/Yacc/patchwire-gm' &
git clone https://github.com/Gizmo199/horri-fi '/storage/nvme5/new_clones/Yacc/horri-fi' &
git clone https://github.com/Project-Wak/Project-wak '/storage/nvme5/new_clones/Yacc/Project-wak' &
git clone https://github.com/gurpreetsinghmatharoo/gms2.3-turn-based-rpg '/storage/nvme5/new_clones/Yacc/gms2.3-turn-based-rpg' &
git clone https://github.com/doug-moen/openscad2 '/storage/nvme5/new_clones/Yacc/openscad2' &
git clone https://github.com/Emperor2000/gms-sample-library '/storage/nvme5/new_clones/Yacc/gms-sample-library' &
git clone https://github.com/Yaazarai/2DGI '/storage/nvme5/new_clones/Yacc/2DGI' &
git clone https://github.com/pliu6/vhd2vl '/storage/nvme5/new_clones/Yacc/vhd2vl' &
git clone https://github.com/AthrunArthur/cxxparser '/storage/nvme5/new_clones/Yacc/cxxparser' &
git clone https://github.com/PoshoDev/DexTool '/storage/nvme5/new_clones/Yacc/DexTool' &
git clone https://github.com/SandyaSivakumar/Mini-Compiler '/storage/nvme5/new_clones/Yacc/Mini-Compiler' &
git clone https://github.com/bytbox/pas2js '/storage/nvme5/new_clones/Yacc/pas2js' &
git clone https://github.com/gm-core/delta '/storage/nvme5/new_clones/Yacc/delta' &
git clone https://github.com/kraifpatrik/SSGI '/storage/nvme5/new_clones/Yacc/SSGI' &
git clone https://github.com/andycraig/r-anonymous-functions '/storage/nvme5/new_clones/Yacc/r-anonymous-functions' &
git clone https://github.com/nabilatsoulcade/GMS2-3D-Library '/storage/nvme5/new_clones/Yacc/GMS2-3D-Library' &
git clone https://github.com/laspencer91/GMS2-Game-Template '/storage/nvme5/new_clones/Yacc/GMS2-Game-Template' &
git clone https://github.com/YosysHQ/yosys-plugins '/storage/nvme5/new_clones/Yacc/yosys-plugins' &
git clone https://github.com/DatZach/Destructors '/storage/nvme5/new_clones/Yacc/Destructors' &
git clone https://github.com/ckshitij/LEX-AND-YACC '/storage/nvme5/new_clones/Yacc/LEX-AND-YACC' &
git clone https://github.com/BentleyBlanks/t2CSSPareser '/storage/nvme5/new_clones/Yacc/t2CSSPareser' &
git clone https://github.com/gm-core/event-horizon '/storage/nvme5/new_clones/Yacc/event-horizon' &
git clone https://github.com/sjjian/oracle-sql-parser '/storage/nvme5/new_clones/Yacc/oracle-sql-parser' &
git clone https://github.com/aswanthpp/Compiler-Design '/storage/nvme5/new_clones/Yacc/Compiler-Design' &
git clone https://github.com/mstop4/useful-gml-scripts '/storage/nvme5/new_clones/Yacc/useful-gml-scripts' &
git clone https://github.com/tomlee130/staruml-starumlSwift '/storage/nvme5/new_clones/Yacc/staruml-starumlSwift' &
git clone https://github.com/Igameart/DopeFishEngine '/storage/nvme5/new_clones/Yacc/DopeFishEngine' &
git clone https://github.com/mishal23/mini-c-compiler '/storage/nvme5/new_clones/Yacc/mini-c-compiler' &
git clone https://github.com/blueburncz/GMD3D11 '/storage/nvme5/new_clones/Yacc/GMD3D11' &
git clone https://github.com/Applemunch/LibreTower '/storage/nvme5/new_clones/Yacc/LibreTower' &
git clone https://github.com/Matth33w/super-mario-xp-remastered '/storage/nvme5/new_clones/Yacc/super-mario-xp-remastered' &
git clone https://github.com/dev-dwarf/Stack3D '/storage/nvme5/new_clones/Yacc/Stack3D' &
git clone https://github.com/mrdaneeyul/good-vibes '/storage/nvme5/new_clones/Yacc/good-vibes' &
git clone https://github.com/gp48k/zmac '/storage/nvme5/new_clones/Yacc/zmac' &
git clone https://github.com/CreativeHandOficial/gm-i18n '/storage/nvme5/new_clones/Yacc/gm-i18n' &
git clone https://github.com/nikita-volkov/postgresql-syntax '/storage/nvme5/new_clones/Yacc/postgresql-syntax' &
git clone https://github.com/bennyfrancis/Celestefall '/storage/nvme5/new_clones/Yacc/Celestefall' &
git clone https://github.com/razorrazo/Pacman-Game---GameMaker-Studio-2 '/storage/nvme5/new_clones/Yacc/Pacman-Game---GameMaker-Studio-2' &
git clone https://github.com/ngdream/H5assembler '/storage/nvme5/new_clones/Yacc/H5assembler' &
git clone https://github.com/nommiin/ultralight-gm '/storage/nvme5/new_clones/Yacc/ultralight-gm' &
git clone https://github.com/sarsanaee/Simple-C-Compiler '/storage/nvme5/new_clones/Yacc/Simple-C-Compiler' &
git clone https://github.com/momentlib/core '/storage/nvme5/new_clones/Yacc/core' &
git clone https://github.com/Hyperion-21/pokecards_plus '/storage/nvme5/new_clones/Yacc/pokecards_plus' &
git clone https://github.com/YoYoYoDude/I_Wanna_GMS2_YoYo_Edition '/storage/nvme5/new_clones/Yacc/I_Wanna_GMS2_YoYo_Edition' &
git clone https://github.com/Sidorakh/http.gml '/storage/nvme5/new_clones/Yacc/http.gml' &
git clone https://github.com/Lojemiru/Chameleon '/storage/nvme5/new_clones/Yacc/Chameleon' &
git clone https://github.com/chendante/Principles-of-Compilers-Assignments '/storage/nvme5/new_clones/Yacc/Principles-of-Compilers-Assignments' &
git clone https://github.com/ethanhe42/c0-compiler '/storage/nvme5/new_clones/Yacc/c0-compiler' &
git clone https://github.com/0xPolygonHermez/zkevm-storage-rom '/storage/nvme5/new_clones/Yacc/zkevm-storage-rom' &
git clone https://github.com/Cons-Cat/Superstar-Game-Suite '/storage/nvme5/new_clones/Yacc/Superstar-Game-Suite' &
git clone https://github.com/gm-core/GMTest '/storage/nvme5/new_clones/Yacc/GMTest' &
git clone https://github.com/IvanoBilenchi/flex-bison-example '/storage/nvme5/new_clones/Yacc/flex-bison-example' &
git clone https://github.com/bergey/preql '/storage/nvme5/new_clones/Yacc/preql' &
git clone https://github.com/nabilatsoulcade/GMS2-UI-Library '/storage/nvme5/new_clones/Yacc/GMS2-UI-Library' &
git clone https://github.com/cznic/parser '/storage/nvme5/new_clones/Yacc/parser' &
git clone https://github.com/SubjectNoi/X0-PL0-Compiler-Public '/storage/nvme5/new_clones/Yacc/X0-PL0-Compiler-Public' &
git clone https://github.com/friendlycosmonaut/Dialogue-System '/storage/nvme5/new_clones/Yacc/Dialogue-System' &
git clone https://github.com/massivecatapult/gamemaker-3d-io '/storage/nvme5/new_clones/Yacc/gamemaker-3d-io' &
git clone https://github.com/mahi97/Persian-Compiler '/storage/nvme5/new_clones/Yacc/Persian-Compiler' &
git clone https://github.com/svn2github/edif2kicad '/storage/nvme5/new_clones/Yacc/edif2kicad' &
git clone https://github.com/Jadezzz/microC-compiler '/storage/nvme5/new_clones/Yacc/microC-compiler' &
git clone https://github.com/Nikko-the-cat/GML-Classes '/storage/nvme5/new_clones/Yacc/GML-Classes' &
git clone https://github.com/OmegaX1000/DanmakuProject '/storage/nvme5/new_clones/Yacc/DanmakuProject' &
git clone https://github.com/sehugg/zmac '/storage/nvme5/new_clones/Yacc/zmac' &
git clone https://github.com/jarble/javascript-to-rust '/storage/nvme5/new_clones/Yacc/javascript-to-rust' &
git clone https://github.com/haroldl/clip '/storage/nvme5/new_clones/Yacc/clip' &
git clone https://github.com/vedic-partap/Compilers-lab '/storage/nvme5/new_clones/Yacc/Compilers-lab' &
git clone https://github.com/aisamanra/bison-flex-sample '/storage/nvme5/new_clones/Yacc/bison-flex-sample' &
git clone https://github.com/sibasmarak/CSE-5th-Semester-IIT-KGP '/storage/nvme5/new_clones/Yacc/CSE-5th-Semester-IIT-KGP' &
git clone https://github.com/dev-dwarf/lianthus '/storage/nvme5/new_clones/Yacc/lianthus' &
git clone https://github.com/Heyooooooooooo/SimpleSQL '/storage/nvme5/new_clones/Yacc/SimpleSQL' &
git clone https://github.com/AdelRizq/A3E '/storage/nvme5/new_clones/Yacc/A3E' &
git clone https://github.com/Chaoswizard98/Engine_of_Chaos '/storage/nvme5/new_clones/Yacc/Engine_of_Chaos' &
git clone https://github.com/wan2land/okreadme '/storage/nvme5/new_clones/Yacc/okreadme' &
git clone https://github.com/samspadegamedev/YouTube-Perlin-Noise-Public '/storage/nvme5/new_clones/Yacc/YouTube-Perlin-Noise-Public' &
git clone https://github.com/Igameart/Lustre '/storage/nvme5/new_clones/Yacc/Lustre' &
git clone https://github.com/MisterFishing/gpl '/storage/nvme5/new_clones/Yacc/gpl' &
git clone https://github.com/hurdad/pmysql '/storage/nvme5/new_clones/Yacc/pmysql' &
git clone https://github.com/GithubSPerez/Funkin-Fanworks '/storage/nvme5/new_clones/Yacc/Funkin-Fanworks' &
git clone https://github.com/maifeeulasad/CSE712-HW-1 '/storage/nvme5/new_clones/Yacc/CSE712-HW-1' &
git clone https://github.com/zyguan/idea-goyacc '/storage/nvme5/new_clones/Yacc/idea-goyacc' &
git clone https://github.com/farhaven/wireless '/storage/nvme5/new_clones/Yacc/wireless' &
git clone https://github.com/richsalz/tlsparser '/storage/nvme5/new_clones/Yacc/tlsparser' &
git clone https://github.com/filipebraida/compilador-disciplina '/storage/nvme5/new_clones/Yacc/compilador-disciplina' &
git clone https://github.com/andylamp/ptucc_compiler '/storage/nvme5/new_clones/Yacc/ptucc_compiler' &
git clone https://github.com/azartech/Flex-Bison-Calculator '/storage/nvme5/new_clones/Yacc/Flex-Bison-Calculator' &
git clone https://github.com/yiwangchunyu/X0Compiler '/storage/nvme5/new_clones/Yacc/X0Compiler' &
git clone https://github.com/samspadegamedev/YouTube-Pubsub '/storage/nvme5/new_clones/Yacc/YouTube-Pubsub' &
git clone https://github.com/FarhanSadaf/chicken-language '/storage/nvme5/new_clones/Yacc/chicken-language' &
git clone https://github.com/XboxDev/a56 '/storage/nvme5/new_clones/Yacc/a56' &
git clone https://github.com/mytchallb/gamemaker-web3 '/storage/nvme5/new_clones/Yacc/gamemaker-web3' &
git clone https://github.com/bramblex/modern-lang '/storage/nvme5/new_clones/Yacc/modern-lang' &
git clone https://github.com/Verdini/celeste-classic-web '/storage/nvme5/new_clones/Yacc/celeste-classic-web' &
git clone https://github.com/samspadegamedev/YouTube-Vectors-and-Steering-Behaviors '/storage/nvme5/new_clones/Yacc/YouTube-Vectors-and-Steering-Behaviors' &
git clone https://github.com/bigsql/pgtsql '/storage/nvme5/new_clones/Yacc/pgtsql' &
git clone https://github.com/dasunpubudumal/lex-yacc '/storage/nvme5/new_clones/Yacc/lex-yacc' &
git clone https://github.com/AkshayGogeri/If-Else-Compiler-in-C '/storage/nvme5/new_clones/Yacc/If-Else-Compiler-in-C' &
git clone https://github.com/Synthasmagoria/Synth-Engine-GMS2.3 '/storage/nvme5/new_clones/Yacc/Synth-Engine-GMS2.3' &
git clone https://github.com/iwVerve/Parafox '/storage/nvme5/new_clones/Yacc/Parafox' &
git clone https://github.com/kalwar/LexerCompiler '/storage/nvme5/new_clones/Yacc/LexerCompiler' &
git clone https://github.com/Arena-of-Wakgood/Arena-of-woowakgood '/storage/nvme5/new_clones/Yacc/Arena-of-woowakgood' &
git clone https://github.com/geekysuavo/ll1 '/storage/nvme5/new_clones/Yacc/ll1' &
git clone https://github.com/JeffersonJales/pooling_objects '/storage/nvme5/new_clones/Yacc/pooling_objects' &
git clone https://github.com/tabularelf/GMVerlet-Integration '/storage/nvme5/new_clones/Yacc/GMVerlet-Integration' &
git clone https://github.com/mxple/TPGsim '/storage/nvme5/new_clones/Yacc/TPGsim' &
git clone https://github.com/jojoee/docker-via '/storage/nvme5/new_clones/Yacc/docker-via' &
git clone https://github.com/ZhenbangYou/SysY-Front-End '/storage/nvme5/new_clones/Yacc/SysY-Front-End' &
git clone https://github.com/JACOBIN-SCTCS/SUBSET_COMPILER '/storage/nvme5/new_clones/Yacc/SUBSET_COMPILER' &
git clone https://github.com/Kezarus-tech/Monastery-Framework_GM2 '/storage/nvme5/new_clones/Yacc/Monastery-Framework_GM2' &
git clone https://github.com/XorDev/ThreeMiceInaTrenchcoat '/storage/nvme5/new_clones/Yacc/ThreeMiceInaTrenchcoat' &
git clone https://github.com/MJ10/Yet-Another-Programming-Language '/storage/nvme5/new_clones/Yacc/Yet-Another-Programming-Language' &
git clone https://github.com/arman324/My-Compiler '/storage/nvme5/new_clones/Yacc/My-Compiler' &
git clone https://github.com/Gizmo199/vector-library '/storage/nvme5/new_clones/Yacc/vector-library' &
git clone https://github.com/tabularelf/Lens '/storage/nvme5/new_clones/Yacc/Lens' &
git clone https://github.com/tabularelf/Room-Editor-Friendly-WarpSystem '/storage/nvme5/new_clones/Yacc/Room-Editor-Friendly-WarpSystem' &
git clone https://github.com/lindenb/newicktools '/storage/nvme5/new_clones/Yacc/newicktools' &
git clone https://github.com/git-together-jam/git-together-0 '/storage/nvme5/new_clones/Yacc/git-together-0' &
git clone https://github.com/proXDhiya/calculator_flex-Bison '/storage/nvme5/new_clones/Yacc/calculator_flex-Bison' &
git clone https://github.com/ConConner/ConConsMapMapper '/storage/nvme5/new_clones/Yacc/ConConsMapMapper' &
git clone https://github.com/NsCrosu/DEMO-inksansGMS2 '/storage/nvme5/new_clones/Yacc/DEMO-inksansGMS2' &
git clone https://github.com/Elzawawy/java-bytecode-generator '/storage/nvme5/new_clones/Yacc/java-bytecode-generator' &
git clone https://github.com/SheepYhangCN/Underplus-Engine '/storage/nvme5/new_clones/Yacc/Underplus-Engine' &
git clone https://github.com/davidgiven/plmc '/storage/nvme5/new_clones/Yacc/plmc' &
git clone https://github.com/z1skgr/FLEX-BISON '/storage/nvme5/new_clones/Yacc/FLEX-BISON' &
git clone https://github.com/Avikalp7/Tiny-C-Compiler '/storage/nvme5/new_clones/Yacc/Tiny-C-Compiler' &
git clone https://github.com/cznic/y '/storage/nvme5/new_clones/Yacc/y' &
git clone https://github.com/christyharagan/dremio-node-api '/storage/nvme5/new_clones/Yacc/dremio-node-api' &
git clone https://github.com/deiuch/c-to-json '/storage/nvme5/new_clones/Yacc/c-to-json' &
git clone https://github.com/AlubJ/Lock-And-Key '/storage/nvme5/new_clones/Yacc/Lock-And-Key' &
git clone https://github.com/sjackman/gfalint '/storage/nvme5/new_clones/Yacc/gfalint' &
git clone https://github.com/elem-azar-unis/Compilers-Principles-01 '/storage/nvme5/new_clones/Yacc/Compilers-Principles-01' &
git clone https://github.com/ranizouaoui/Compiler '/storage/nvme5/new_clones/Yacc/Compiler' &
git clone https://github.com/nkkav/gvizparse '/storage/nvme5/new_clones/Yacc/gvizparse' &
git clone https://github.com/hacks-at-mac/calculator '/storage/nvme5/new_clones/Yacc/calculator' &
git clone https://github.com/JujuAdams/Pinocchio '/storage/nvme5/new_clones/Yacc/Pinocchio' &
git clone https://github.com/prateekvij/FrontEnd-C-Compiler '/storage/nvme5/new_clones/Yacc/FrontEnd-C-Compiler' &
git clone https://github.com/tim70036/c99-codegen-andes '/storage/nvme5/new_clones/Yacc/c99-codegen-andes' &
git clone https://github.com/Yuki-book/legend-emu80 '/storage/nvme5/new_clones/Yacc/legend-emu80' &
git clone https://github.com/Harsini15/Automatic-c-code-generator '/storage/nvme5/new_clones/Yacc/Automatic-c-code-generator' &
git clone https://github.com/hackernogg/CS_ELTE_BC '/storage/nvme5/new_clones/Yacc/CS_ELTE_BC' &
git clone https://github.com/IammyselfYBX/Lex-Yacc '/storage/nvme5/new_clones/Yacc/Lex-Yacc' &
git clone https://github.com/Tabrizian/CompilerCompiler '/storage/nvme5/new_clones/Yacc/CompilerCompiler' &
git clone https://github.com/zsoltmester/simple-abap-compiler '/storage/nvme5/new_clones/Yacc/simple-abap-compiler' &
git clone https://github.com/Abdallah-Sobehy/compiler '/storage/nvme5/new_clones/Yacc/compiler' &
git clone https://github.com/neeraj3029/MathLib '/storage/nvme5/new_clones/Yacc/MathLib' &
git clone https://github.com/rockcarry/ffpl0 '/storage/nvme5/new_clones/Yacc/ffpl0' &
git clone https://github.com/tabularelf/LWO '/storage/nvme5/new_clones/Yacc/LWO' &
git clone https://github.com/schnorr/calc '/storage/nvme5/new_clones/Yacc/calc' &
git clone https://github.com/ShaunJS/gms2-transitions '/storage/nvme5/new_clones/Yacc/gms2-transitions' &
git clone https://github.com/compiler-craft/compiler-craft '/storage/nvme5/new_clones/Yacc/compiler-craft' &
git clone https://github.com/yektaKamane/Yet-Another-Python-Compiler '/storage/nvme5/new_clones/Yacc/Yet-Another-Python-Compiler' &
git clone https://github.com/SilsRepositories/UT-CodeSnippets '/storage/nvme5/new_clones/Yacc/UT-CodeSnippets' &
git clone https://github.com/badwrongg/gm_basic_platformer '/storage/nvme5/new_clones/Yacc/gm_basic_platformer' &
git clone https://github.com/yoadwo/Compi '/storage/nvme5/new_clones/Yacc/Compi' &
git clone https://github.com/wst24365888/MiniLisp-Yacc-Interpreter '/storage/nvme5/new_clones/Yacc/MiniLisp-Yacc-Interpreter' &
git clone https://github.com/apurv1205/Compilers '/storage/nvme5/new_clones/Yacc/Compilers' &
git clone https://github.com/sarveshpathak139/LEX-AND-YACC-SIMPLE-CALCULATOR '/storage/nvme5/new_clones/Yacc/LEX-AND-YACC-SIMPLE-CALCULATOR' &
git clone https://github.com/ashbin1008/LEX-AND-YACC '/storage/nvme5/new_clones/Yacc/LEX-AND-YACC' &
git clone https://github.com/Gizmo199/msdf_previewer '/storage/nvme5/new_clones/Yacc/msdf_previewer' &
git clone https://github.com/Garfounkel/A-Leaf-In-Space '/storage/nvme5/new_clones/Yacc/A-Leaf-In-Space' &
git clone https://github.com/ValdrST/proyecto-final-compiladores '/storage/nvme5/new_clones/Yacc/proyecto-final-compiladores' &
git clone https://github.com/JorgeAmbrocio/example-jison-taller-2021 '/storage/nvme5/new_clones/Yacc/example-jison-taller-2021' &
git clone https://github.com/RajputGarima/LatexToHtml '/storage/nvme5/new_clones/Yacc/LatexToHtml' &
git clone https://github.com/tim70036/c99-parser '/storage/nvme5/new_clones/Yacc/c99-parser' &
git clone https://github.com/Sidorakh/gm-sds '/storage/nvme5/new_clones/Yacc/gm-sds' &
git clone https://github.com/hyruleredrawn/zeldaNES '/storage/nvme5/new_clones/Yacc/zeldaNES' &
git clone https://github.com/mwberry/yacc-examples '/storage/nvme5/new_clones/Yacc/yacc-examples' &
git clone https://github.com/zarif98sjs/CSE-310-Compiler '/storage/nvme5/new_clones/Yacc/CSE-310-Compiler' &
git clone https://github.com/ZhenbangYou/SysY-to-Tigger '/storage/nvme5/new_clones/Yacc/SysY-to-Tigger' &
git clone https://github.com/BlaXun/Random-Dungeon-Generator-GMS-2.3 '/storage/nvme5/new_clones/Yacc/Random-Dungeon-Generator-GMS-2.3' &
git clone https://github.com/greenpixels/game-maker-ui-library '/storage/nvme5/new_clones/Yacc/game-maker-ui-library' &
git clone https://github.com/unlam-alumnos/lenguajesycompiladores '/storage/nvme5/new_clones/Yacc/lenguajesycompiladores' &
git clone https://github.com/melchisedech333/lex-yacc-experiments '/storage/nvme5/new_clones/Yacc/lex-yacc-experiments' &
git clone https://github.com/jatin69/python-parser '/storage/nvme5/new_clones/Yacc/python-parser' &
git clone https://github.com/KGrykiel/ATPlatformerProject '/storage/nvme5/new_clones/Yacc/ATPlatformerProject' &
git clone https://github.com/xpii/Golden-Warden-Jam-Edition '/storage/nvme5/new_clones/Yacc/Golden-Warden-Jam-Edition' &
git clone https://github.com/vishal7695/arithmetic-expression-validator-and-evaluator-compiler-design '/storage/nvme5/new_clones/Yacc/arithmetic-expression-validator-and-evaluator-compiler-design' &
git clone https://github.com/FusionSid/Moyai-Lang '/storage/nvme5/new_clones/Yacc/Moyai-Lang' &
git clone https://github.com/shreyavshetty/AutoGenerationOfCcode '/storage/nvme5/new_clones/Yacc/AutoGenerationOfCcode' &
git clone https://github.com/MatusKysel/pseudo-code '/storage/nvme5/new_clones/Yacc/pseudo-code' &
git clone https://github.com/GamemakerCasts/particles '/storage/nvme5/new_clones/Yacc/particles' &
git clone https://github.com/1213637677/sqlparser '/storage/nvme5/new_clones/Yacc/sqlparser' &
git clone https://github.com/bg21/space_shooter_gamemaker2 '/storage/nvme5/new_clones/Yacc/space_shooter_gamemaker2' &
git clone https://github.com/sabinachang/mini-lisp-project '/storage/nvme5/new_clones/Yacc/mini-lisp-project' &
