#!/bin/bash

git clone https://github.com/ansistrano/deploy '/storage/nvme5/new_clones/YAML/deploy' &
git clone https://github.com/k3s-io/k3s-ansible '/storage/nvme5/new_clones/YAML/k3s-ansible' &
git clone https://github.com/usnistgov/macos_security '/storage/nvme5/new_clones/YAML/macos_security' &
git clone https://github.com/kubeflow/manifests '/storage/nvme5/new_clones/YAML/manifests' &
git clone https://github.com/trinib/AdGuard-WireGuard-Unbound-DNScrypt '/storage/nvme5/new_clones/YAML/AdGuard-WireGuard-Unbound-DNScrypt' &
git clone https://github.com/ansible-lockdown/RHEL7-CIS '/storage/nvme5/new_clones/YAML/RHEL7-CIS' &
git clone https://github.com/web-platform-dx/web-features '/storage/nvme5/new_clones/YAML/web-features' &
git clone https://github.com/k8ssandra/k8ssandra '/storage/nvme5/new_clones/YAML/k8ssandra' &
git clone https://github.com/mustache/spec '/storage/nvme5/new_clones/YAML/spec' &
git clone https://github.com/COVESA/vehicle_signal_specification '/storage/nvme5/new_clones/YAML/vehicle_signal_specification' &
git clone https://github.com/ansible-lockdown/RHEL8-CIS '/storage/nvme5/new_clones/YAML/RHEL8-CIS' &
git clone https://github.com/ansible-lockdown/RHEL7-STIG '/storage/nvme5/new_clones/YAML/RHEL7-STIG' &
git clone https://github.com/sublime-security/sublime-rules '/storage/nvme5/new_clones/YAML/sublime-rules' &
git clone https://github.com/ansistrano/rollback '/storage/nvme5/new_clones/YAML/rollback' &
git clone https://github.com/dell/omnia '/storage/nvme5/new_clones/YAML/omnia' &
git clone https://github.com/ansible-lockdown/UBUNTU22-CIS '/storage/nvme5/new_clones/YAML/UBUNTU22-CIS' &
git clone https://github.com/EvisHome/Home-Assistant '/storage/nvme5/new_clones/YAML/Home-Assistant' &
git clone https://github.com/RedHat-EMEA-SSA-Team/hetzner-ocp4 '/storage/nvme5/new_clones/YAML/hetzner-ocp4' &
git clone https://github.com/ansible-lockdown/UBUNTU20-CIS '/storage/nvme5/new_clones/YAML/UBUNTU20-CIS' &
git clone https://github.com/awslabs/kubeflow-manifests '/storage/nvme5/new_clones/YAML/kubeflow-manifests' &
git clone https://github.com/sleighzy/k3s-traefik-v2-kubernetes-crd '/storage/nvme5/new_clones/YAML/k3s-traefik-v2-kubernetes-crd' &
git clone https://github.com/hackclub/dns '/storage/nvme5/new_clones/YAML/dns' &
git clone https://github.com/RealOrangeOne/infrastructure '/storage/nvme5/new_clones/YAML/infrastructure' &
git clone https://github.com/ipr-cnrs/nftables '/storage/nvme5/new_clones/YAML/nftables' &
git clone https://github.com/ansible-lockdown/RHEL9-CIS '/storage/nvme5/new_clones/YAML/RHEL9-CIS' &
git clone https://github.com/kencx/homelab '/storage/nvme5/new_clones/YAML/homelab' &
git clone https://github.com/ansible-lockdown/Windows-2019-CIS '/storage/nvme5/new_clones/YAML/Windows-2019-CIS' &
git clone https://github.com/shaderecker/ansible-pihole '/storage/nvme5/new_clones/YAML/ansible-pihole' &
git clone https://github.com/aquaproj/aqua-registry '/storage/nvme5/new_clones/YAML/aqua-registry' &
git clone https://github.com/gabe565/charts '/storage/nvme5/new_clones/YAML/charts' &
git clone https://github.com/hummingbird-me/api-docs '/storage/nvme5/new_clones/YAML/api-docs' &
git clone https://github.com/ansible-lockdown/RHEL8-STIG '/storage/nvme5/new_clones/YAML/RHEL8-STIG' &
git clone https://github.com/IBM/z_ansible_collections_samples '/storage/nvme5/new_clones/YAML/z_ansible_collections_samples' &
git clone https://github.com/dask/helm-chart '/storage/nvme5/new_clones/YAML/helm-chart' &
git clone https://github.com/ansible-lockdown/Windows-2022-CIS '/storage/nvme5/new_clones/YAML/Windows-2022-CIS' &
git clone https://github.com/sleighzy/ansible-zookeeper '/storage/nvme5/new_clones/YAML/ansible-zookeeper' &
git clone https://github.com/KSP-CKAN/NetKAN '/storage/nvme5/new_clones/YAML/NetKAN' &
git clone https://github.com/sleighzy/k3s-traefik-forward-auth-openid-connect '/storage/nvme5/new_clones/YAML/k3s-traefik-forward-auth-openid-connect' &
git clone https://github.com/adapter-hub/Hub '/storage/nvme5/new_clones/YAML/Hub' &
git clone https://github.com/chrisvanmeer/at-hashi-demo '/storage/nvme5/new_clones/YAML/at-hashi-demo' &
git clone https://github.com/pascaliske/infrastructure '/storage/nvme5/new_clones/YAML/infrastructure' &
git clone https://github.com/redhat-cop/aap_configuration_template '/storage/nvme5/new_clones/YAML/aap_configuration_template' &
git clone https://github.com/sap-linuxlab/community.sap_install '/storage/nvme5/new_clones/YAML/community.sap_install' &
git clone https://github.com/sleighzy/k3s-minio-deployment '/storage/nvme5/new_clones/YAML/k3s-minio-deployment' &
git clone https://github.com/litmuschaos/litmus-helm '/storage/nvme5/new_clones/YAML/litmus-helm' &
git clone https://github.com/soffes/home-old '/storage/nvme5/new_clones/YAML/home-old' &
git clone https://github.com/harrytruman/elk-ansible '/storage/nvme5/new_clones/YAML/elk-ansible' &
git clone https://github.com/ansible-lockdown/UBUNTU22-CIS-Audit '/storage/nvme5/new_clones/YAML/UBUNTU22-CIS-Audit' &
git clone https://github.com/camunda-community-hub/camunda-7-community-helm '/storage/nvme5/new_clones/YAML/camunda-7-community-helm' &
git clone https://github.com/fred-drake/infrastructure '/storage/nvme5/new_clones/YAML/infrastructure' &
git clone https://github.com/ansible-lockdown/Windows-2019-STIG '/storage/nvme5/new_clones/YAML/Windows-2019-STIG' &
git clone https://github.com/pl4nty/homelab '/storage/nvme5/new_clones/YAML/homelab' &
git clone https://github.com/ansible-lockdown/RHEL8-CIS-Audit '/storage/nvme5/new_clones/YAML/RHEL8-CIS-Audit' &
git clone https://github.com/TheChrisK/PMM '/storage/nvme5/new_clones/YAML/PMM' &
git clone https://github.com/starcraft66/infrastructure '/storage/nvme5/new_clones/YAML/infrastructure' &
git clone https://github.com/ansible-lockdown/UBUNTU18-CIS '/storage/nvme5/new_clones/YAML/UBUNTU18-CIS' &
git clone https://github.com/ansible-lockdown/AMAZON2-CIS '/storage/nvme5/new_clones/YAML/AMAZON2-CIS' &
git clone https://github.com/ansible-lockdown/RHEL9-CIS-Audit '/storage/nvme5/new_clones/YAML/RHEL9-CIS-Audit' &
git clone https://github.com/gabe565/esphome-configs '/storage/nvme5/new_clones/YAML/esphome-configs' &
git clone https://github.com/RealOrangeOne/dotfiles '/storage/nvme5/new_clones/YAML/dotfiles' &
git clone https://github.com/ansible-lockdown/Windows-2016-CIS '/storage/nvme5/new_clones/YAML/Windows-2016-CIS' &
git clone https://github.com/idealista/cookiecutter-ansible-role '/storage/nvme5/new_clones/YAML/cookiecutter-ansible-role' &
git clone https://github.com/idealista/mysql_role '/storage/nvme5/new_clones/YAML/mysql_role' &
git clone https://github.com/sleighzy/k3s-keycloak-deployment '/storage/nvme5/new_clones/YAML/k3s-keycloak-deployment' &
git clone https://github.com/victor-gp/cmd-help-sublime-syntax '/storage/nvme5/new_clones/YAML/cmd-help-sublime-syntax' &
git clone https://github.com/ansible-lockdown/RHEL7-CIS-Audit '/storage/nvme5/new_clones/YAML/RHEL7-CIS-Audit' &
git clone https://github.com/TOSIT-IO/tdp-collection '/storage/nvme5/new_clones/YAML/tdp-collection' &
git clone https://github.com/mmalyska/home-ops '/storage/nvme5/new_clones/YAML/home-ops' &
git clone https://github.com/IBM/Ansible-OpenShift-Provisioning '/storage/nvme5/new_clones/YAML/Ansible-OpenShift-Provisioning' &
git clone https://github.com/r3dspace/home-lab '/storage/nvme5/new_clones/YAML/home-lab' &
git clone https://github.com/ArthurVardevanyan/HomeLab '/storage/nvme5/new_clones/YAML/HomeLab' &
git clone https://github.com/idealista/kafka_role '/storage/nvme5/new_clones/YAML/kafka_role' &
git clone https://github.com/thorian93/ansible-role-upgrade '/storage/nvme5/new_clones/YAML/ansible-role-upgrade' &
git clone https://github.com/ansible-lockdown/RHEL7-STIG-Audit '/storage/nvme5/new_clones/YAML/RHEL7-STIG-Audit' &
git clone https://github.com/ionfury/homelab '/storage/nvme5/new_clones/YAML/homelab' &
git clone https://github.com/AshAvalanche/ansible-avalanche-collection '/storage/nvme5/new_clones/YAML/ansible-avalanche-collection' &
git clone https://github.com/ansible-lockdown/UBUNTU20-CIS-Audit '/storage/nvme5/new_clones/YAML/UBUNTU20-CIS-Audit' &
git clone https://github.com/stejoo/ansible-teamspeak '/storage/nvme5/new_clones/YAML/ansible-teamspeak' &
git clone https://github.com/scottharwell/cloud-ee '/storage/nvme5/new_clones/YAML/cloud-ee' &
git clone https://github.com/tjungbauer/helm-charts '/storage/nvme5/new_clones/YAML/helm-charts' &
git clone https://github.com/SelimHorri/kubernetes-deployment-service-yml-exp '/storage/nvme5/new_clones/YAML/kubernetes-deployment-service-yml-exp' &
git clone https://github.com/idealista/nexus-role '/storage/nvme5/new_clones/YAML/nexus-role' &
git clone https://github.com/idealista/java_role '/storage/nvme5/new_clones/YAML/java_role' &
git clone https://github.com/ansible-lockdown/RHEL8-STIG-Audit '/storage/nvme5/new_clones/YAML/RHEL8-STIG-Audit' &
git clone https://github.com/ansible-lockdown/Windows-10-STIG '/storage/nvme5/new_clones/YAML/Windows-10-STIG' &
git clone https://github.com/idealista/consul_role '/storage/nvme5/new_clones/YAML/consul_role' &
git clone https://github.com/robbederks/open-hardware-definitions '/storage/nvme5/new_clones/YAML/open-hardware-definitions' &
git clone https://github.com/idealista/jira_role '/storage/nvme5/new_clones/YAML/jira_role' &
git clone https://github.com/SelimHorri/ecommerce-monolithic-backend-app '/storage/nvme5/new_clones/YAML/ecommerce-monolithic-backend-app' &
git clone https://github.com/data-tangles/ansible '/storage/nvme5/new_clones/YAML/ansible' &
git clone https://github.com/BitPatty/dev-containers '/storage/nvme5/new_clones/YAML/dev-containers' &
git clone https://github.com/aamkye/ubuntu_on_WD_PRx100 '/storage/nvme5/new_clones/YAML/ubuntu_on_WD_PRx100' &
git clone https://github.com/ansible-lockdown/POSTGRES-12-CIS '/storage/nvme5/new_clones/YAML/POSTGRES-12-CIS' &
git clone https://github.com/jiaozhentian/kubeflow-manifest-mirror '/storage/nvme5/new_clones/YAML/kubeflow-manifest-mirror' &
git clone https://github.com/idealista/goreplay-role '/storage/nvme5/new_clones/YAML/goreplay-role' &
git clone https://github.com/opencrypto-io/data '/storage/nvme5/new_clones/YAML/data' &
git clone https://github.com/ansiblebook/ansible_role_ssh '/storage/nvme5/new_clones/YAML/ansible_role_ssh' &
git clone https://github.com/mcfio/home-cluster '/storage/nvme5/new_clones/YAML/home-cluster' &
git clone https://github.com/ansible-lockdown/Windows-2022-STIG '/storage/nvme5/new_clones/YAML/Windows-2022-STIG' &
git clone https://github.com/CoFH/cofh.github.io '/storage/nvme5/new_clones/YAML/cofhhub.io' &
git clone https://github.com/ansible-lockdown/Windows-2016-STIG '/storage/nvme5/new_clones/YAML/Windows-2016-STIG' &
git clone https://github.com/idealista/redis_role '/storage/nvme5/new_clones/YAML/redis_role' &
git clone https://github.com/ansible-lockdown/KUBERNETES-STIG '/storage/nvme5/new_clones/YAML/KUBERNETES-STIG' &
git clone https://github.com/ansible-content-lab/aws.infrastructure_config_demos '/storage/nvme5/new_clones/YAML/aws.infrastructure_config_demos' &
git clone https://github.com/Jasstkn/helmwave-demo '/storage/nvme5/new_clones/YAML/helmwave-demo' &
git clone https://github.com/ansible-lockdown/AMAZON2-CIS-Audit '/storage/nvme5/new_clones/YAML/AMAZON2-CIS-Audit' &
git clone https://github.com/thorian93/main '/storage/nvme5/new_clones/YAML/main' &
git clone https://github.com/rayshoo/vansinetes '/storage/nvme5/new_clones/YAML/vansinetes' &
git clone https://github.com/ansible-lockdown/Windows-2019-CIS-Audit '/storage/nvme5/new_clones/YAML/Windows-2019-CIS-Audit' &
git clone https://github.com/PaloAltoNetworks/LogFileHighlighting '/storage/nvme5/new_clones/YAML/LogFileHighlighting' &
git clone https://github.com/shaderecker/ansible-system-updates '/storage/nvme5/new_clones/YAML/ansible-system-updates' &
git clone https://github.com/cguertin14/infra '/storage/nvme5/new_clones/YAML/infra' &
git clone https://github.com/ansible-lockdown/Windows-2016-CIS-Audit '/storage/nvme5/new_clones/YAML/Windows-2016-CIS-Audit' &
git clone https://github.com/berbiche/infrastructure '/storage/nvme5/new_clones/YAML/infrastructure' &
git clone https://github.com/idealista/nginx_role '/storage/nvme5/new_clones/YAML/nginx_role' &
git clone https://github.com/blalop/ansible-role-pihole '/storage/nvme5/new_clones/YAML/ansible-role-pihole' &
git clone https://github.com/tjungbauer/openshift-cluster-bootstrap '/storage/nvme5/new_clones/YAML/openshift-cluster-bootstrap' &
git clone https://github.com/ansible-content-lab/azure.infrastructure_config_demos '/storage/nvme5/new_clones/YAML/azure.infrastructure_config_demos' &
git clone https://github.com/DevopsFactoryTTT/Elastic-Project '/storage/nvme5/new_clones/YAML/Elastic-Project' &
git clone https://github.com/invakid404/home-cluster '/storage/nvme5/new_clones/YAML/home-cluster' &
git clone https://github.com/khuedoan/ansible-collection-workstation '/storage/nvme5/new_clones/YAML/ansible-collection-workstation' &
git clone https://github.com/ibm-s390-cloud/ocp-kvm-ipi-automation '/storage/nvme5/new_clones/YAML/ocp-kvm-ipi-automation' &
git clone https://github.com/badnetmask/pi-services '/storage/nvme5/new_clones/YAML/pi-services' &
git clone https://github.com/ansible-lockdown/CISCO-IOS-L2S-STIG '/storage/nvme5/new_clones/YAML/CISCO-IOS-L2S-STIG' &
git clone https://github.com/noobient/noobuntu '/storage/nvme5/new_clones/YAML/noobuntu' &
git clone https://github.com/tiberiushunter/hassio-config '/storage/nvme5/new_clones/YAML/hassio-config' &
git clone https://github.com/jharris126/preppin-data-dbt '/storage/nvme5/new_clones/YAML/preppin-data-dbt' &
git clone https://github.com/TOSIT-IO/tdp-observability '/storage/nvme5/new_clones/YAML/tdp-observability' &
git clone https://github.com/racqspace/ansible-role-unattended-upgrades '/storage/nvme5/new_clones/YAML/ansible-role-unattended-upgrades' &
git clone https://github.com/ansible-lockdown/UBUNTU18-STIG '/storage/nvme5/new_clones/YAML/UBUNTU18-STIG' &
