#!/bin/bash

git clone https://github.com/pa1nki113r/Project_Brutality '/storage/nvme5/new_clones/ZenScript/Project_Brutality' &
git clone https://github.com/EnigmaticaModpacks/Enigmatica2Expert '/storage/nvme5/new_clones/ZenScript/Enigmatica2Expert' &
git clone https://github.com/TCreopargh/GreedyCraft '/storage/nvme5/new_clones/ZenScript/GreedyCraft' &
git clone https://github.com/DarkPacks/SkyFactory-4 '/storage/nvme5/new_clones/ZenScript/SkyFactory-4' &
git clone https://github.com/CFPAOrg/Modpack-GuideBook-i18n '/storage/nvme5/new_clones/ZenScript/Modpack-GuideBook-i18n' &
git clone https://github.com/Rebirth-of-the-Night/Rebirth-of-the-Night '/storage/nvme5/new_clones/ZenScript/Rebirth-of-the-Night' &
git clone https://github.com/EmeraldCoasttt/BrutalDoomPlatinum '/storage/nvme5/new_clones/ZenScript/BrutalDoomPlatinum' &
git clone https://github.com/dr3ams/Roguelike-Adventures-and-Dungeons-2 '/storage/nvme5/new_clones/ZenScript/Roguelike-Adventures-and-Dungeons-2' &
git clone https://github.com/Minecraft-Eternal/MC-Eternal-1.12 '/storage/nvme5/new_clones/ZenScript/MC-Eternal-1.12' &
git clone https://github.com/TerraFirmaRescue/TerraFirma-Rescue-Modpack '/storage/nvme5/new_clones/ZenScript/TerraFirma-Rescue-Modpack' &
git clone https://github.com/BevoTechPack/BevoTechPack '/storage/nvme5/new_clones/ZenScript/BevoTechPack' &
git clone https://github.com/jekyllgrim/Alice-Toys-of-Madness '/storage/nvme5/new_clones/ZenScript/Alice-Toys-of-Madness' &
git clone https://github.com/3saster/fullscrn_huds '/storage/nvme5/new_clones/ZenScript/fullscrn_huds' &
git clone https://github.com/jekyllgrim/Painslayer '/storage/nvme5/new_clones/ZenScript/Painslayer' &
git clone https://github.com/AFADoomer/Wolf3D-TC-3.0 '/storage/nvme5/new_clones/ZenScript/Wolf3D-TC-3.0' &
git clone https://github.com/VazkiiMods/crucial2 '/storage/nvme5/new_clones/ZenScript/crucial2' &
git clone https://github.com/EnigmaticaModpacks/Enigmatica2 '/storage/nvme5/new_clones/ZenScript/Enigmatica2' &
git clone https://github.com/MyM-ModpackTeam/GalacticScience '/storage/nvme5/new_clones/ZenScript/GalacticScience' &
git clone https://github.com/Sunekaer/stoneBlock '/storage/nvme5/new_clones/ZenScript/stoneBlock' &
git clone https://github.com/sainagh/meatballcraft '/storage/nvme5/new_clones/ZenScript/meatballcraft' &
git clone https://github.com/DarkPacks/SkyFactory-5 '/storage/nvme5/new_clones/ZenScript/SkyFactory-5' &
git clone https://github.com/ToxicFrog/doom-mods '/storage/nvme5/new_clones/ZenScript/doom-mods' &
git clone https://github.com/Project-Interactions/Interactions '/storage/nvme5/new_clones/ZenScript/Interactions' &
git clone https://github.com/EdwinYoungSteve/GreedyCraft2-Reborn '/storage/nvme5/new_clones/ZenScript/GreedyCraft2-Reborn' &
git clone https://github.com/wormzjl/Project-PFAA '/storage/nvme5/new_clones/ZenScript/Project-PFAA' &
git clone https://github.com/belathus/Wanderlust-Renewed '/storage/nvme5/new_clones/ZenScript/Wanderlust-Renewed' &
git clone https://github.com/Yarden-zamir/ProjectGear '/storage/nvme5/new_clones/ZenScript/ProjectGear' &
git clone https://github.com/KryptonCaptain/Misc-Files '/storage/nvme5/new_clones/ZenScript/Misc-Files' &
git clone https://github.com/EnigmaticaModpacks/Enigmatica4 '/storage/nvme5/new_clones/ZenScript/Enigmatica4' &
git clone https://github.com/TIMWTeam/This-Is-My-World-IV-Trial-of-God '/storage/nvme5/new_clones/ZenScript/This-Is-My-World-IV-Trial-of-God' &
git clone https://github.com/VazkiiMods/Bliss '/storage/nvme5/new_clones/ZenScript/Bliss' &
git clone https://github.com/Krutoy242/Craft.zs '/storage/nvme5/new_clones/ZenScript/Craft.zs' &
git clone https://github.com/ArtpokeBr/Minecraft-Ultimato '/storage/nvme5/new_clones/ZenScript/Minecraft-Ultimato' &
git clone https://github.com/Filostorm/Multiblock-Madness '/storage/nvme5/new_clones/ZenScript/Multiblock-Madness' &
git clone https://github.com/SmashingMods/antimatter-chemistry '/storage/nvme5/new_clones/ZenScript/antimatter-chemistry' &
git clone https://github.com/CraftTweaker/CraftTweaker-Examples '/storage/nvme5/new_clones/ZenScript/CraftTweaker-Examples' &
git clone https://github.com/friendlyhj/GrassUtils '/storage/nvme5/new_clones/ZenScript/GrassUtils' &
git clone https://github.com/zeta-group/ZetaBot '/storage/nvme5/new_clones/ZenScript/ZetaBot' &
git clone https://github.com/WesCook/Homestead '/storage/nvme5/new_clones/ZenScript/Homestead' &
git clone https://github.com/pyure/infitech-prototype '/storage/nvme5/new_clones/ZenScript/infitech-prototype' &
git clone https://github.com/friendlyhj/FlyingRoad3 '/storage/nvme5/new_clones/ZenScript/FlyingRoad3' &
git clone https://github.com/thephoenixlodge/Heavens-of-Sorcery '/storage/nvme5/new_clones/ZenScript/Heavens-of-Sorcery' &
git clone https://github.com/ArtpokeBr/Pluma-a-Journey-to-the-Future '/storage/nvme5/new_clones/ZenScript/Pluma-a-Journey-to-the-Future' &
git clone https://github.com/CalaMariGold/TREPIDATION '/storage/nvme5/new_clones/ZenScript/TREPIDATION' &
git clone https://github.com/Erisia/builder '/storage/nvme5/new_clones/ZenScript/builder' &
git clone https://github.com/Pulz-TCP/TheClassicPack '/storage/nvme5/new_clones/ZenScript/TheClassicPack' &
git clone https://github.com/xt9/cryogenic-simulation '/storage/nvme5/new_clones/ZenScript/cryogenic-simulation' &
git clone https://github.com/MARYT-Studio/Blessed-Or-Cursed-Minecraft-Modpack '/storage/nvme5/new_clones/ZenScript/Blessed-Or-Cursed-Minecraft-Modpack' &
git clone https://github.com/EnigmaticaModpacks/Enigmatica2ExpertSkyblock '/storage/nvme5/new_clones/ZenScript/Enigmatica2ExpertSkyblock' &
git clone https://github.com/RicardoLuis0/ZJSON '/storage/nvme5/new_clones/ZenScript/ZJSON' &
git clone https://github.com/programgames/Gregblock-revamped '/storage/nvme5/new_clones/ZenScript/Gregblock-revamped' &
git clone https://github.com/Krutoy242/D.zs '/storage/nvme5/new_clones/ZenScript/D.zs' &
git clone https://github.com/GeminiCrafterMan/pandoras-wrath '/storage/nvme5/new_clones/ZenScript/pandoras-wrath' &
git clone https://github.com/VazkiiModsArchive/Crucial '/storage/nvme5/new_clones/ZenScript/Crucial' &
git clone https://github.com/AnodeCathode/TechNodeFirmaCraft '/storage/nvme5/new_clones/ZenScript/TechNodeFirmaCraft' &
git clone https://github.com/DrasticDemise/Simply-Magic '/storage/nvme5/new_clones/ZenScript/Simply-Magic' &
git clone https://github.com/wormzjl/Fabrica-Atlantica '/storage/nvme5/new_clones/ZenScript/Fabrica-Atlantica' &
git clone https://github.com/DNSTechpack/DNS12-MC1.12.2 '/storage/nvme5/new_clones/ZenScript/DNS12-MC1.12.2' &
git clone https://github.com/vDubs93/HD-SystemShock '/storage/nvme5/new_clones/ZenScript/HD-SystemShock' &
git clone https://github.com/fictioncraft-team/FC-Atomic-Space '/storage/nvme5/new_clones/ZenScript/FC-Atomic-Space' &
git clone https://github.com/hibanka/crafttweaker-scripts '/storage/nvme5/new_clones/ZenScript/crafttweaker-scripts' &
git clone https://github.com/Project-AT/ThirdRebirth '/storage/nvme5/new_clones/ZenScript/ThirdRebirth' &
git clone https://github.com/AllTheMods/ATM3-Expert '/storage/nvme5/new_clones/ZenScript/ATM3-Expert' &
git clone https://github.com/MelaDoZer/Union-Doom '/storage/nvme5/new_clones/ZenScript/Union-Doom' &
git clone https://github.com/DenisMasterHerobrine/RotN-Translation '/storage/nvme5/new_clones/ZenScript/RotN-Translation' &
git clone https://github.com/BiggestXuan/BxP '/storage/nvme5/new_clones/ZenScript/BxP' &
git clone https://github.com/AvalonServers/DescentPacks '/storage/nvme5/new_clones/ZenScript/DescentPacks' &
git clone https://github.com/Boondorl/Weather '/storage/nvme5/new_clones/ZenScript/Weather' &
git clone https://github.com/OverDriver05/Vanilla-Glory-Kill '/storage/nvme5/new_clones/ZenScript/Vanilla-Glory-Kill' &
git clone https://github.com/PIPILAN/Parasites-Blood-Dawn '/storage/nvme5/new_clones/ZenScript/Parasites-Blood-Dawn' &
git clone https://github.com/kreezxil/World-of-Dragons '/storage/nvme5/new_clones/ZenScript/World-of-Dragons' &
git clone https://github.com/ProjectICR/IsolatedCrystalRemaker '/storage/nvme5/new_clones/ZenScript/IsolatedCrystalRemaker' &
git clone https://github.com/vrnavi/Realistic-Unreality '/storage/nvme5/new_clones/ZenScript/Realistic-Unreality' &
git clone https://github.com/SamLam140330/DangerousWorld '/storage/nvme5/new_clones/ZenScript/DangerousWorld' &
git clone https://github.com/MCTeamPotato/Tankoptimization '/storage/nvme5/new_clones/ZenScript/Tankoptimization' &
git clone https://github.com/Caishangqi/GonerAge '/storage/nvme5/new_clones/ZenScript/GonerAge' &
git clone https://github.com/Ironnoob73/FARmodpack '/storage/nvme5/new_clones/ZenScript/FARmodpack' &
git clone https://github.com/Dark2932/CrTFunnyThings '/storage/nvme5/new_clones/ZenScript/CrTFunnyThings' &
git clone https://github.com/JadedPacks/Agrarian-Skies-2 '/storage/nvme5/new_clones/ZenScript/Agrarian-Skies-2' &
git clone https://github.com/Firefly-Studio/Annals-Mechanizac '/storage/nvme5/new_clones/ZenScript/Annals-Mechanizac' &
git clone https://github.com/Hiiragi283/Good-Old-Halcyon-Days '/storage/nvme5/new_clones/ZenScript/Good-Old-Halcyon-Days' &
