#!/bin/bash

git clone https://github.com/historicalsource/zork1 '/storage/nvme5/new_clones/ZIL/zork1' &
git clone https://github.com/historicalsource/hitchhikersguide '/storage/nvme5/new_clones/ZIL/hitchhikersguide' &
git clone https://github.com/historicalsource/zork '/storage/nvme5/new_clones/ZIL/zork' &
git clone https://github.com/historicalsource/zork1-gold '/storage/nvme5/new_clones/ZIL/zork1-gold' &
git clone https://github.com/historicalsource/zork3 '/storage/nvme5/new_clones/ZIL/zork3' &
git clone https://github.com/historicalsource/deadline '/storage/nvme5/new_clones/ZIL/deadline' &
git clone https://github.com/historicalsource/bureaucracy '/storage/nvme5/new_clones/ZIL/bureaucracy' &
git clone https://github.com/historicalsource/trinity '/storage/nvme5/new_clones/ZIL/trinity' &
git clone https://github.com/historicalsource/suspended '/storage/nvme5/new_clones/ZIL/suspended' &
git clone https://github.com/historicalsource/infidel '/storage/nvme5/new_clones/ZIL/infidel' &
git clone https://github.com/historicalsource/lurkinghorror '/storage/nvme5/new_clones/ZIL/lurkinghorror' &
git clone https://github.com/historicalsource/leathergoddesses-gold '/storage/nvme5/new_clones/ZIL/leathergoddesses-gold' &
git clone https://github.com/historicalsource/starcross '/storage/nvme5/new_clones/ZIL/starcross' &
git clone https://github.com/historicalsource/wishbringer '/storage/nvme5/new_clones/ZIL/wishbringer' &
git clone https://github.com/historicalsource/spellbreaker '/storage/nvme5/new_clones/ZIL/spellbreaker' &
git clone https://github.com/historicalsource/arthur '/storage/nvme5/new_clones/ZIL/arthur' &
git clone https://github.com/historicalsource/borderzone '/storage/nvme5/new_clones/ZIL/borderzone' &
git clone https://github.com/historicalsource/hollywoodhijinx '/storage/nvme5/new_clones/ZIL/hollywoodhijinx' &
git clone https://github.com/historicalsource/ballyhoo '/storage/nvme5/new_clones/ZIL/ballyhoo' &
git clone https://github.com/historicalsource/nordandbert '/storage/nvme5/new_clones/ZIL/nordandbert' &
git clone https://github.com/historicalsource/suspect '/storage/nvme5/new_clones/ZIL/suspect' &
git clone https://github.com/historicalsource/wishbringer-gold '/storage/nvme5/new_clones/ZIL/wishbringer-gold' &
git clone https://github.com/historicalsource/infocom-sampler '/storage/nvme5/new_clones/ZIL/infocom-sampler' &
git clone https://github.com/historicalsource/minizork-1982 '/storage/nvme5/new_clones/ZIL/minizork-1982' &
git clone https://github.com/historicalsource/minizork-1987 '/storage/nvme5/new_clones/ZIL/minizork-1987' &
git clone https://github.com/historicalsource/zork-german '/storage/nvme5/new_clones/ZIL/zork-german' &
git clone https://github.com/jeffnyman/zmachine '/storage/nvme5/new_clones/ZIL/zmachine' &
git clone https://github.com/the-infocom-files/trinity '/storage/nvme5/new_clones/ZIL/trinity' &
git clone https://github.com/the-infocom-files/hitchhiker '/storage/nvme5/new_clones/ZIL/hitchhiker' &
git clone https://github.com/heasm66/mdlzork '/storage/nvme5/new_clones/ZIL/mdlzork' &
git clone https://github.com/PDP-10/muddle '/storage/nvme5/new_clones/ZIL/muddle' &
git clone https://github.com/jeffnyman/zifmia '/storage/nvme5/new_clones/ZIL/zifmia' &
git clone https://github.com/the-infocom-files/zork1 '/storage/nvme5/new_clones/ZIL/zork1' &
git clone https://github.com/the-infocom-files/planetfall '/storage/nvme5/new_clones/ZIL/planetfall' &
git clone https://github.com/the-infocom-files/bureaucracy '/storage/nvme5/new_clones/ZIL/bureaucracy' &
git clone https://github.com/the-infocom-files/suspended '/storage/nvme5/new_clones/ZIL/suspended' &
git clone https://github.com/the-infocom-files/zork2 '/storage/nvme5/new_clones/ZIL/zork2' &
git clone https://github.com/the-infocom-files/hitchhiker-invclues '/storage/nvme5/new_clones/ZIL/hitchhiker-invclues' &
git clone https://github.com/the-infocom-files/enchanter '/storage/nvme5/new_clones/ZIL/enchanter' &
git clone https://github.com/eriktorbjorn/minizork2-renovated '/storage/nvme5/new_clones/ZIL/minizork2-renovated' &
git clone https://github.com/heasm66/modified_zork1 '/storage/nvme5/new_clones/ZIL/modified_zork1' &
git clone https://github.com/jeffnyman/zil-retro '/storage/nvme5/new_clones/ZIL/zil-retro' &
git clone https://github.com/the-infocom-files/plunderedhearts '/storage/nvme5/new_clones/ZIL/plunderedhearts' &
git clone https://github.com/the-infocom-files/lurkinghorror '/storage/nvme5/new_clones/ZIL/lurkinghorror' &
git clone https://github.com/ZoBoRf/ZIL-Tool-Chain '/storage/nvme5/new_clones/ZIL/ZIL-Tool-Chain' &
git clone https://github.com/the-infocom-files/amfv '/storage/nvme5/new_clones/ZIL/amfv' &
git clone https://github.com/the-infocom-files/wishbringer '/storage/nvme5/new_clones/ZIL/wishbringer' &
git clone https://github.com/the-infocom-files/sherlock '/storage/nvme5/new_clones/ZIL/sherlock' &
